### PR TITLE
memtx: allow to abort checkpoint if it wasn't started

### LINKED ISSUE #10265: memtx_engine_abort_checkpoint(engine*): Assertion `memtx->checkpoint != NULL' failed.
**Bug description**

```
4,402745221776],["=",7,false]]]
2024-07-17T13:18:44.7250603Z 2024-07-17 13:17:48.181 [83503] main/125/WRK #12/test.fuzz.lua.test_engine I> PUT_OP [[645265475650.62,203510957126,"1ef9bd15-a5ea-468f-908d-44ab17d3df59",186894885380,"frlhcdncnr",879453543773,true,"564409750564","2024-07-17T13:17:48Z",[1,2,3,4,5,6,7,8],{"4":4,"1":1,"5":5,"2":2,"3":3}]]
2024-07-17T13:18:44.7252855Z 2024-07-17 13:17:48.181 [83503] main/125/WRK #12/test.fuzz.lua.test_engine I> ERROR: opname "PUT_OP", err "Failed to allocate 16384 bytes in mempool for new slab", args [[645265475650.62,203510957126,"1ef9bd15-a5ea-468f-908d-44ab17d3df59",186894885380,"frlhcdncnr",879453543773,true,"564409750564","2024-07-17T13:17:48Z",[1,2,3,4,5,6,7,8],{"4":4,"1":1,"5":5,"2":2,"3":3}]]
2024-07-17T13:18:44.7253457Z 2024-07-17 13:17:48.181 [83503] main/125/WRK #12/test.fuzz.lua.test_engine I> BSIZE_OP []
2024-07-17T13:18:44.7253986Z 2024-07-17 13:17:48.181 [83503] main/125/WRK #12/test.fuzz.lua.test_engine I> TX_ROLLBACK []
2024-07-17T13:18:44.7255117Z 2024-07-17 13:17:48.181 [83503] main/125/WRK #12/test.fuzz.lua.test_engine I> DELETE_OP [[491618185974,"5d9ce990-fb81-4965-9999-e0b64a01ce39",890250949399.79,"ryzyvukdfl",606228667069]]
2024-07-17T13:18:44.7255889Z 2024-07-17 13:17:48.181 [83503] main/106/checkpoint_daemon I> scheduled next checkpoint for Wed Jul 17 13:18:32 2024
2024-07-17T13:18:44.7256220Z 2024-07-17 13:17:48.182 [83503] coio V> loading vylog 25483
2024-07-17T13:18:44.7256548Z 2024-07-17 13:17:48.182 [83503] coio V> done loading vylog
2024-07-17T13:18:44.7256967Z 2024-07-17 13:17:48.182 [83503] coio I> removed ./00000000000000022498.snap
2024-07-17T13:18:44.7258221Z 2024-07-17 13:17:48.182 [83503] main/314/ERRINJ/test.fuzz.lua.test_engine I> Enabled fault injections: ["ERRINJ_VY_RUN_WRITE_STMT_TIMEOUT","ERRINJ_INDEX_ALLOC","ERRINJ_VY_DELAY_PK_LOOKUP","ERRINJ_XLOG_READ"]
2024-07-17T13:18:44.7259109Z 2024-07-17 13:17:48.182 [83503] main/314/ERRINJ/test.fuzz.lua.test_engine I> TOGGLE RANDOM ERROR INJECTION: ERRINJ_INDEX_ITERATOR_NEW -> true
2024-07-17T13:18:44.7259589Z 2024-07-17 13:17:48.182 [83503] main I> WAL threshold exceeded, triggering checkpoint
2024-07-17T13:18:44.7260005Z 2024-07-17 13:17:48.182 [83503] coio I> removed ./00000000000000022498.xlog
2024-07-17T13:18:44.7260913Z tarantool: ./src/box/memtx_engine.cc:1258: void memtx_engine_abort_checkpoint(engine*): Assertion `memtx->checkpoint != NULL' failed.
2024-07-17T13:18:44.7261054Z Aborted (core dumped)
```

CI run: https://github.com/tarantool/tarantool/actions/runs/9974731324/job/27563103333?pr=10264
CI log:  
[log.zip](https://github.com/user-attachments/files/16269476/log.zip)

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

tarantool version 62c49367a2eab6d8008da2d7201ffa03e002c31e
https://github.com/ligurio/tarantool/tree/ligurio/engine-fuzzing

**Steps to reproduce**

Download `test/fuzz/lua/test_engine.lua` and execute: `tarantool test/fuzz/lua/test_engine.lua --workers 200 --engine memtx --test_duration $((2*60)) --verbose --seed 1721222224`

**Actual behavior**

assert is triggered

**Expected behavior**

no assert

### PR DESCRIPTION
**Pull request by drewdzzz**
When checkpoint fails, we abort it in all engines even if it wasn't started succesfully. If it fails right from the start so that checkpoint in memtx wasn't started, assertion in `memtx_engine_abort_checkpoint` fails - memtx doesn't expect that checkpoint will be aborted if it failed to start. Let's do the same thing as vinyl does - no-op if there is no checkpoint in progress.

Closes #10265

### CODE REVIEW

File: test/box-luatest/gh_10265_memtx_checkpoint_fail_assertion_test.lua [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+end)
+
+g.test_memtx_checkpoint_fail_assertion = function(cg)
+    cg.server:exec(function()
+        local s = box.schema.space.create('test')
+        s:create_index('pk')
+        s:replace{0, 0}
+        -- Set error injection to iterator creation to fail
+        -- memtx checkpoint right from the start.
+        box.error.injection.set('ERRINJ_INDEX_ITERATOR_NEW', true)
```
Comment (locker) [inline test/box-luatest/gh_10265_memtx_checkpoint_fail_assertion_test.lua:23]: I doubt it's possible to reproduce this issue without an error injection so it doesn't make much sense to include the fix into the release notes - I'd drop the changelog.

**Review by locker — APPROVED** [review]

File: changelogs/unreleased/gh-10265-checkpoint-oom-crash.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+## bugfix/box
+
+* Fixed a crash when Tarantool went out of memory at the start of
+  checkpoint (gh-10265).
```
Comment (andreyaksenov) [inline changelogs/unreleased/gh-10265-checkpoint-oom-crash.md:4]:
```suggestion
  a checkpoint (gh-10265).
```

**Review by andreyaksenov — APPROVED** [review]

File: test/box-luatest/gh_10265_memtx_checkpoint_fail_assertion_test.lua (hunk 1 above)
Comment (locker) [reply test/box-luatest/gh_10265_memtx_checkpoint_fail_assertion_test.lua:23]: Yes, I think it's okay to merge this one.

**Comment by locker** [comment]
Cherry-picked to 3.1 and 2.11.
