### PR TITLE
qsync: fix box_wait_quorum hang

### LINKED ISSUE #11574: Promote can get stuck in transition to election leader
**Steps to reproduce**

1. Setup two replicas, replica 1 being the synchronous queue owner with a synchronous quorum 3. Enable manual elections on replica 2.
```lua
-- replica 1
console = require('console')

box.cfg{
    listen = 3301,
    replication = {3301, 3302},
    replication_timeout = 0.1,
    replication_synchro_timeout = 600,
    replication_synchro_quorum = 3,
}

box.once('bootstrap', function()
    box.schema.user.grant('guest', 'super')

    box.schema.create_space('s', {is_sync = true}):create_index('p')

    box.ctl.promote()
end)

console.start()

os.exit()

-- replica 2
console = require('console')

box.cfg{
    listen = 3302,
    read_only = true,
    replication = {3301, 3302},
    replication_synchro_quorum = 3,
    replication_timeout = 0.1,
    election_mode = 'manual',
}

console.start()

os.exit()
```

2. Add a request to the synchronous replication queue owned by replica 1. After that, enable manual elections on replica 1 and promote it to leader.
```lua
-- replica 1

box.atomic({wait = 'submit'}, function() box.space.s:replace{0} end)
box.cfg{election_mode = 'manual'}

```

**Actual behavior**

The raft worker on replica 1 will wait forever for quorum 3:
https://github.com/tarantool/tarantool/blob/5921a93d0b4b4ccf490e3561c144cbc9fc4e0c2e/src/box/box.cc#L2688-L2705

* It is impossible to demote replica 1, since it is stuck in the promote.
* Changing the quorum on replica 1 does not have any effect.
* Cancelling the `raft_worker` on replica 1 does not have any effect.

As a result, the promote on replica 1 is stuck.

**Expected behavior**

The promote on replica 1 is not stuck.

### PR DESCRIPTION
**Pull request by mrForza**
Before this patch when there are uncommitted transactions in the limbo
and the `replication_synchro_quorum > replicaset.registered_count`, a
node performing the `box.ctl.promote` may become the leader but remain
in RO state. The cause of the problem is that the `box_wait_quorum`
hangs because the current node can't gather a sufficient number of acks.

This bug negatively influence on quorum-based replication because we
can't exit from this hanged state of the `box_wait_quorum`. These
actions can't help us to get back to normal state:
1) Performing `box.ctl.promote`, because we are already in the leader
   state.
2) Performing `box.ctl.demote`, because terms of the limbo and the raft
   state machine are different. The term of the limbo can't be changed
   until all transactions are committed.
3) Lowering the `replication_symchro_quorum`, because the
   `box_wait_quorum` is in the infinite yield until it get new acks and
   as a result, this function doesn't keep track some changes in
   `box.cfg`.
4) Connecting a new replica to replicaset, because our current node is
   in the RO state. It can't write into `box.space._cluster`.

To fix this issue, we decided to keep track changes of
`replication_synchro_quorum` param during transition to RW state. If
this param changes during the hang of `box_wait_quorum`, we raise the
client error `ER_QUORUM_WAIT` and consider the current execution of this
function obsolete. After that the execution of the `box_wait_quorum`
starts over with new quorum. This solution allows the user to fix an
incorrectly configured `replication_synchro_quorum` param and get rid of
hang while transition to RW state.

Also we modify the `gh_9263_assertion_in_box_promote_qsync` test by
changing expected result from fiber's join. It was done because the test
didn't expect an error if user reconfigures `replication_synchro_quorum`
while `box_wait_quorum` collecting acks.

Closes #11574

NO_DOC=bugfix

### CODE REVIEW

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+end
+
+g.test_box_wait_quorum_while_changing_replication_synchro_quorum = function(g)
+    capture_synchro_queue_and_push_sync_transaction(g.server1)
+    g.server1:exec(function()
+        box.cfg{replication_synchro_quorum = 3}
+        _G.raft_worker_f:join()
+    end)
+    wait_until_synchro_queue_is_empty(g.server1)
+    t.assert(g.server1:grep_log("ER_QUORUM_WAIT"))
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: Flaky

```
[004] Test failed! Output from reject file /tmp/t/rejects/replication-luatest/gh_11574_hang_in_box_wait_quorum.reject:
[004] Tarantool version is 3.5.0-entrypoint-127-g1d6eb2397c
[004] TAP version 13
[004] 1..3
[004] # Started on Fri Jul 25 11:54:52 2025
[004] # Starting group: replication-luatest.gh_11574_hang_in_box_wait_quorum
[004] not ok 1	replication-luatest.gh_11574_hang_in_box_wait_quorum.test_box_wait_quorum_while_changing_replication_synchro_quorum
[004] #   ...cation-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:98: expected: a value evaluating to true, actual: nil
[004] #   stack traceback:
[004] #   	...cation-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:98: in function 'replication-luatest.gh_11574_hang_in_box_wait_quorum.test_box_wait_quorum_while_changing_replication_synchro_quorum'
[004] #   artifacts:
[004] #   	server1 -> /tmp/t/004_replication-luatest/artifacts/rs-V7Rv54THy3U4/server1-9s2U4z_FVbBE
[004] ok     2	replication-luatest.gh_11574_hang_in_box_wait_quorum.test_box_wait_quorum_by_cluster_size_replication_synchro_quorum
[004] ok     3	replication-luatest.gh_11574_hang_in_box_wait_quorum.test_box_wait_quorum_with_lower_replication_synchro_quorum
[004] # Ran 3 tests in 4.079 seconds, 2 succeeded, 1 failed
[004] 
```

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
+
+* Bug fixed: master node used to hang when it couldn't get
+  enough acks to commit synchronous transaction (gh-11531).
```
Comment (Serpentian) [inline changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: We should describe more thoroughly in the commit msg, what happened, why did this happen, how we're fixing that, and why we decide to go that path. Actually, I already don't remember, why noticing the quorum change is enough for us. 

After becoming the master Raft node couldn't enter RW state, since it hanged in the `box_wait_quorum`. And there're were no way to exit from that state. That's the root of the problem

I also find changelog confusing, master didn't hang itself, it wasn't able to transition to RW

File: src/box/box.cc [hunk 3]
```diff
@@ -2832,10 +2835,19 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+		while (!fiber_is_cancelled() && t.ack_count < t.quorum) {
+			if (fiber_cond_wait_deadline(&synchro_quorum_cond,
+						     deadline) == -1) {
 				break;
-		} while (!fiber_is_cancelled() && t.ack_count < t.quorum);
+			}
+
+			if (quorum != replication_synchro_quorum) {
+				diag_set(ClientError, ER_QUORUM_WAIT, quorum,
+					 "replication_synchro_quorum was changed while waiting");
```
Comment (Serpentian) [inline src/box/box.cc]: Let's make the msg consistent with:

https://github.com/tarantool/tarantool/blob/a0748bea849bd9e069b1be817b9323fd87240838/src/box/box.cc#L3221-L3222

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+    g.server_1_uri = server.build_listen_uri("server1", g.replicaset.id)
+    g.server_2_uri = server.build_listen_uri("server2", g.replicaset.id)
+    g.server_3_uri = server.build_listen_uri("server3", g.replicaset.id)
+
+    g.server1 = g.replicaset:build_and_add_server({
+        alias = "server1",
+        box_cfg = {
+            listen = g.server_1_uri,
+            replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
+            replication_synchro_quorum = 4,
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:25]: Did you consider lowering `replication_timeout`?

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+        _G.raft_worker_f:join()
+    end)
+    wait_until_synchro_queue_is_empty(g.server1)
+    t.assert(g.server1:grep_log("ER_QUORUM_WAIT"))
+end
+
+g.test_box_wait_quorum_by_cluster_size_replication_synchro_quorum = function(g)
+    capture_synchro_queue_and_push_sync_transaction(g.server1)
+    g.server1:exec(function() _G.raft_worker_f:join() end)
+    wait_until_synchro_queue_is_empty(g.server1)
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:115]: You don't reset the `replication_synchro_quorum` in the end of the tests. I suppose, that's the reason, why this test works. If you'll properly reset quorum (which you should do) and will use new compat, the test won't work:

```
diff --git a/test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua b/test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua
index 0caa345a4e..cf335a57d5 100644
--- a/test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua
+++ b/test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua
@@ -96,9 +96,11 @@ g.test_box_wait_quorum_while_changing_replication_synchro_quorum = function(g)
     end)
     wait_until_synchro_queue_is_empty(g.server1)
     t.assert(g.server1:grep_log("ER_QUORUM_WAIT"))
+    g.server1:update_box_cfg({ replication_synchro_quorum = 4 })
 end
 
 g.test_box_wait_quorum_by_cluster_size_replication_synchro_quorum = function(g)
+    g.server1:exec(function() require('compat').replication_synchro_timeout = 'new' end)
     capture_synchro_queue_and_push_sync_transaction(g.server1)
     g.server1:exec(function() _G.raft_worker_f:join() end)
     wait_until_synchro_queue_is_empty(g.server1)
```

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 1 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: fixed. The flaky happens because the **g.server1** doesn't have enough time to enter into "leader" state. As a result, `box_raft_update_synchro_quorum` ends with nothing and doesn't invoke `box_wait_quorum` before reconfiguration.

I ran this test 512 times in parallel with 22 threads. Everything is OK.

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md (hunk 2 above)
Comment (mrForza) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: fixed

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 4 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:25]: Yes, I tried. It didn't help me.

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 5 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:115]: In this case you typo in `replication_synchro_quorum` parameter in the end of first test. As a result in the second test we try to detect that there is no hang in `box_wait_quorum` when we can't gather enough acks and don't reconfigure our node while hang. The value of `replication_synchro_quorum` in the second test should be 3, not 4. 

I apply your diff. Everything works!

File: src/box/box.cc (hunk 3 above)
Comment (mrForza) [reply src/box/box.cc]: It can be confusing in the case when the user lower the `replication_synchro_quorum` parameter (e.g. from 10 to 3) and get error: "quorum was **increased** while waiting". May be another description is more suitable in this case?

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 1 above)
Comment (Serpentian) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: Fixed for me too

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md [hunk 6]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
+
+* Bug fixed: the leader node can't enter into RW state due
+  to hang in box_wait_quorum (gh-11531).
```
Comment (Serpentian) [inline changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: Incorrect issue number in changelog

File: src/box/box.cc (hunk 3 above)
Comment (Serpentian) [reply src/box/box.cc]: Nah, I meant `quorum was changed`, but now I understood, that this may be not obvious, which quorum was changed (maybe it's `replication_connect_quorum`), so it's there, where the message is incorrect. Here we can leave the msg here as it's now

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 4 above)
Comment (Serpentian) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:25]: Nah, I meant, that we need to do that) It'll make your test twice as fast. But, of course, the test should remain stable:

```diff
diff --git a/test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua b/test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua
index 06e0a6998a..fab13b0bcf 100644
--- a/test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua
+++ b/test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua
@@ -16,6 +16,7 @@ g.before_all(function(g)
             listen = g.server_1_uri,
             replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
             replication_synchro_quorum = 4,
+            replication_timeout = 0.1,
         },
     })
 
@@ -26,6 +27,7 @@ g.before_all(function(g)
             replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
             read_only = true,
             election_mode = "manual",
+            replication_timeout = 0.1,
         },
     })
 
@@ -36,6 +38,7 @@ g.before_all(function(g)
             replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
             read_only = true,
             election_mode = "manual",
+            replication_timeout = 0.1,
         },
     })
 
@@ -92,6 +95,7 @@ end
 g.test_box_wait_quorum_while_changing_replication_synchro_quorum = function(g)
     capture_synchro_queue_and_push_sync_transaction(g.server1)
     g.server1:exec(function()
+        _G.raft_worker_f:join()
         -- It is necessary to wait until the g.server1 enters the leader state,
         -- because otherwise the reconfiguration may appear earlier than
         -- the invocation of the box_wait_quorum with higher quorum - 4.
@@ -101,7 +105,6 @@ g.test_box_wait_quorum_while_changing_replication_synchro_quorum = function(g)
             t.assert_equals(box.info.election.state, "leader")
         end)
         box.cfg{replication_synchro_quorum = 3}
-        _G.raft_worker_f:join()
     end)
     wait_until_synchro_queue_is_empty(g.server1)
     t.assert(g.server1:grep_log("ER_QUORUM_WAIT"))
```

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 5 above)
Comment (Serpentian) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:115]: Nope, I didn't make a typo. Every test should return the cluster to the same state it was before the test. You're starting the first test with quorum 4, then the second one has 3, the third one - 2. This is not a way to go.

We must explicitly set the quorum to the desired value at the beginning of the test, if we need to.

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md (hunk 6 above)
Comment (mrForza) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: fixed

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 4 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:25]: fixed. The test still stable

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 5 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:115]: fixed. I reset `replication_synchro_quorum` to 4 in the end of every test and they still work fine!

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md [hunk 7]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
+
+* Bug fixed: the leader node can't enter into RW state due
```
Comment (Serpentian) [inline changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: Nit: we use past tense, when describing fixed bugs

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 4 above)
Comment (Serpentian) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:25]: For me it's not, unfortunately:

```
[010] Test failed! Output from reject file /tmp/t/rejects/replication-luatest/gh_11574_hang_in_box_wait_quorum.reject:
[010] Tarantool version is 3.5.0-entrypoint-127-gc33c7dd1d1
[010] TAP version 13
[010] 1..3
[010] # Started on Tue Jul 29 18:00:25 2025
[010] # Starting group: replication-luatest.gh_11574_hang_in_box_wait_quorum
[010] not ok 1	replication-luatest.gh_11574_hang_in_box_wait_quorum.test_box_wait_quorum_while_changing_replication_synchro_quorum
[010] #   ...cation-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:110: expected: a value evaluating to true, actual: nil
[010] #   stack traceback:
[010] #   	...cation-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:110: in function 'replication-luatest.gh_11574_hang_in_box_wait_quorum.test_box_wait_quorum_while_changing_replication_synchro_quorum'
[010] #   artifacts:
[010] #   	server1 -> /tmp/t/010_replication-luatest/artifacts/rs-dwBBXGxZYhYZ/server1-V7j1A6qYfzsZ
[010] ok     2	replication-luatest.gh_11574_hang_in_box_wait_quorum.test_box_wait_quorum_by_cluster_size_replication_synchro_quorum
[010] ok     3	replication-luatest.gh_11574_hang_in_box_wait_quorum.test_box_wait_quorum_with_lower_replication_synchro_quorum
[010] # Ran 3 tests in 2.179 seconds, 2 succeeded, 1 failed
[010] 
```

0.5 seconds is stable for me

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md (hunk 7 above)
Comment (mrForza) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: fixed

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 4 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:25]: fixed

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md [hunk 8]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
+
+* Bug fixed: the leader node couldn't enter into RW state
+  due to hang in box_wait_quorum (gh-11574).
```
Comment (Serpentian) [inline changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: You're saying users the info, they cannot parse. This is the message, which is gonna be on the release page, and user knows nothing about internal C `box_wait_quorum`. The other thing is the fact, that we didn't fix the hang itself, now we allow users to continue the promotion by lowering the quorum, the promotion itself will still hang, if quorum is too big.

File: src/box/box.cc [hunk 9]
```diff
@@ -2832,10 +2835,19 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
 		trigger_create(&t.base, box_quorum_on_ack_f, NULL, NULL);
 		trigger_add(&replicaset.on_ack, &t.base);
 		double deadline = ev_monotonic_now(loop()) + timeout;
-		do {
-			if (fiber_yield_deadline(deadline))
+		while (!fiber_is_cancelled() && t.ack_count < t.quorum) {
```
Comment (Serpentian) [inline src/box/box.cc]: I propose to add a warning in `box_wait_quorum`, when it's started with quorum more than the number of `registered_count`. Otherwise, if it happens on production it's non-obvious, why the node is still in RO, if it's a leader already

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua [hunk 10]
```diff
@@ -0,0 +1,128 @@
...
+g.after_all(function(g)
+    g.replicaset:drop()
+end)
+
+local function capture_synchro_queue_and_push_sync_transaction(server)
+    server:exec(function()
+        local fiber = require("fiber")
+        require('compat').replication_synchro_timeout = 'new'
+        if box.space.s == nil then
+            box.schema.create_space("s", {is_sync = true}):create_index("p")
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: Let's move it to `before_all`, the space is used in all tests. The same applies to the compat

**Review by Serpentian — COMMENTED** [review]
These are the final nits I have

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md (hunk 8 above)
Comment (mrForza) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: fixed

File: src/box/box.cc (hunk 9 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 10 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: fixed

File: src/box/box.cc (hunk 9 above)
Comment (Serpentian) [reply src/box/box.cc]: There's no need to warn user on evert wakeup) It's enough to say it once, when the function is started, IMHO

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md (hunk 8 above)
Comment (Serpentian) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: Sorry, but I still cannot parse, what was fixed, from the changelog) Let's say smth like:

Fixed a bug, when instance hanged during transition to RW state after promotion with a quorum greater than the number of registered instances in the replicaset. Now the transition can be continued by reducing the `replication_synchro_quorum` value.

Or smth like that)

**Review by Serpentian — APPROVED** [review]
I don't have any major comments regarding the patch itself, only nits are left. I still think, it's better to place the `box_wait_quorum` alongside with the cond to the `replication.cc` and `struct replicaset`, but I don't insist.

Great work! Let's fix the remainings)

File: src/box/box.cc [hunk 11]
```diff
@@ -2832,10 +2835,22 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+			if (replicaset.registered_count < replication_synchro_quorum)
+				say_warn("replication_synchro_quorum is higher than number of "
+					 "registered replicas. The node will be in RO state "
+					 "because it can't collect acks for synchronous queue");
+			if (fiber_cond_wait_deadline(&synchro_quorum_cond,
```
Comment (Gerold103) [inline src/box/box.cc]: I suggest to reuse `txn_limbo::wait_cond` instead of introducing new global variables.

File: src/box/box.cc [hunk 12]
```diff
@@ -2832,10 +2835,22 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
 		trigger_create(&t.base, box_quorum_on_ack_f, NULL, NULL);
 		trigger_add(&replicaset.on_ack, &t.base);
 		double deadline = ev_monotonic_now(loop()) + timeout;
-		do {
-			if (fiber_yield_deadline(deadline))
+		while (!fiber_is_cancelled() && t.ack_count < t.quorum) {
+			if (replicaset.registered_count < replication_synchro_quorum)
+				say_warn("replication_synchro_quorum is higher than number of "
+					 "registered replicas. The node will be in RO state "
+					 "because it can't collect acks for synchronous queue");
```
Comment (Gerold103) [inline src/box/box.cc]: 1. Nikita is right, we can't log that on each wakeup. Please, do that just once per call of `box_wait_quorum()`.
2. Saying here anything about "staying in RO state" while being probably correct, would be logically confusing, because `box_wait_quorum()` doesn't control RO state. It might be used by functions controlling that, but it is as related to actually setting the RO state as function `say_warn()` itself. It doesn't even mention synchronous replication in any way. So lets probably just drop the second sentence. What would help is to make the message contain the specific numbers - values of `replicaset.registered_count` and `replication_synchro_quorum`. Or move this entire log into `box_wait_limbo_acked()`.

File: src/box/box.cc [hunk 13]
```diff
@@ -2832,10 +2835,22 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+			if (fiber_cond_wait_deadline(&synchro_quorum_cond,
+						     deadline) == -1) {
 				break;
-		} while (!fiber_is_cancelled() && t.ack_count < t.quorum);
+			}
+			if (quorum != replication_synchro_quorum) {
```
Comment (Gerold103) [inline src/box/box.cc]: Here is the hardest point of the patch. The function `box_wait_limbo_acked()` was not related to synchronous replication. If you look what it does, you would notice that it doesn't even mention synchro at all. Its only job was to wait for N replicas to reach the needed LSN. A very simple task on top of which we could already build something related to synchro.

Even its parameter `quorum` was passed explicitly instead of using the global `replication_synchro_quorum` in it.

And the latter is what happens now. It renders all the things mentioned above void. I would rather suggest we find a way to keep this function simple and not connected to synchro. Not even mentioning it anywhere.

However I don't see how to do that right away, if we don't want to leave it as is. Then another option is to do the following:
- Extract the first half of `box_wait_quorum()` into a function `box_ack_count(lead_id, target_lsn)`. It would just count how many nodes have the needed LSN of the given node.
- Inline the rest of the code into `box_wait_limbo_acked()`. It would call `box_ack_count()` and then sit in the loop until the quorum is reached on top of that ack count.
- It would explicitly use `replication_synchro_quorum`, not an opaque `quorum` param.
- `box_quorum_trigger` and `box_quorum_on_ack_f` would need to be renamed accordingly, to mention synchro explicitly.
- `box_quorum_trigger::quorum` can be deleted and you would use `replication_synchro_quorum` directly.
- The error `replication_synchro_quorum was changed while waiting` can be deleted, because the fact of the quorum change is not really an error. It was a hack to restart the waiting. Now you won't need to restart it. Can simply check if the new quorum is already reached. And if not, then continue waiting.

**Review by Gerold103 — COMMENTED** [review]
Thanks for the patch! Untrivial bug tbh. Lets see what options we have for fixes.

File: src/box/box.cc (hunk 11 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: src/box/box.cc (hunk 12 above)
Comment (mrForza) [reply src/box/box.cc]: 1. done
2. done (I did not change this log, just move it into `box_wait_limbo_acked`)

File: src/box/box.cc (hunk 13 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md (hunk 8 above)
Comment (mrForza) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: fixed

File: src/box/box.cc [hunk 14]
```diff
@@ -2782,24 +2780,15 @@ box_check_waiting_for_own_rows(void)
...
- * Wait until at least @a quorum of nodes confirm @a target_lsn from the node
- * with id @a lead_id.
+/*
+ * A helper which count how many nodes have the needed LSN of the given node
  */
 static int
-box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
-		double timeout)
+box_ack_count(uint32_t leader_id, int64_t target_lsn,
+	      struct synchro_quorum_trigger *t)
```
Comment (Gerold103) [inline src/box/box.cc]: Here we have a similar problem as in the previous version of the patch. You mention "synchro" in the code which has nothing to do with synchro. Doesn't depend on that.

The function's `box_ack_count()` only job is to count acks from replicas. Imagine like it should be usable even without any synchro replication at all. But now it requires some sort of "synchro trigger". This defeats the purpose of isolation of this function.

I think in this case you can workaround this by passing just the vclock pointer into this function. It doesn't need the whole trigger.

File: src/box/box.cc [hunk 15]
```diff
@@ -2782,24 +2780,15 @@ box_check_waiting_for_own_rows(void)
...
-    ++errinj(ERRINJ_WAIT_QUORUM_COUNT, ERRINJ_INT)->iparam;
-#endif
-
-	struct box_quorum_trigger t;
-	memset(&t, 0, sizeof(t));
-	vclock_create(&t.vclock);
-
 	/* Take this node into account immediately. */
-	int ack_count = vclock_get(box_vclock, lead_id) >= target_lsn;
+	int ack_count = vclock_get(box_vclock, leader_id) >= target_lsn;
```
Comment (Gerold103) [inline src/box/box.cc]: Perhaps better leave the old variable name. Then you wouldn't have this diff and one more below.

File: src/box/txn_limbo.c [hunk 16]
```diff
@@ -1456,8 +1456,17 @@ txn_limbo_process(struct txn_limbo *limbo, const struct synchro_request *req)
...
+		return;
+	if (txn_limbo_is_frozen(limbo)) {
+		/*
+		 * If limbo is frozen we need to broadcast wait_cond
+		 * in order to not hang in box_wait_limbo_acked during
+		 * collecting acks.
+		 */
+		fiber_cond_broadcast(&limbo->wait_cond);
 		return;
+	}
```
Comment (Gerold103) [inline src/box/txn_limbo.c]: AFAIU, `txn_limbo_confirm()` below is a nop if nothing needs to be done. So you could just remove `|| txn_limbo_is_frozen(limbo)` above and leave everything else as is, no? The wakeup on the same cond is done in the end of this func anyway.

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md [hunk 17]
```diff
@@ -0,0 +1,7 @@
+## bugfix/core
```
Comment (Gerold103) [inline changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md:1]: The commit says:
```
To fix this issue, we decided to keep track changes of
`replication_synchro_quorum` param during transition to RW state. If
this param changes during the hang of `box_wait_quorum`, we consider
the current execution of this function obsolete. After that the
execution of the `box_wait_quorum` starts over with new quorum.
```
But this isn't so anymore, is it? The wait-quorum won't fail now. It would just continue waiting if the new quorum is still > ack count.

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md [hunk 18]
```diff
@@ -0,0 +1,7 @@
...
+
+* Fixed a bug, when instance hanged during transition to RW
```
Comment (Gerold103) [inline changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: Here I have a question to the doc team. @maryiaLichko in this case, I guess. Isn't this supposed to be `hung` instead of `hanged`? From what I am reading, `hanged` is used exclusively for describing the act of hanging a person on a rope at the neck until death.

Comment (maryiaLichko) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]:
```suggestion
* Fixed a bug when the instance hung during transition to RW
```

File: src/box/box.cc (hunk 14 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: src/box/box.cc (hunk 15 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: src/box/txn_limbo.c (hunk 16 above)
Comment (mrForza) [reply src/box/txn_limbo.c]: fixed

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md (hunk 17 above)
Comment (mrForza) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md:1]: fixed

File: changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md (hunk 18 above)
Comment (mrForza) [reply changelogs/unreleased/gh-11574-hang-in-box-wait-quorum.md]: fixed

File: src/box/box.cc [hunk 19]
```diff
@@ -3200,30 +3159,68 @@ box_wait_limbo_acked(double timeout)
...
 			return -1;
 		}
 	}
 	assert(last_entry->lsn > 0);
 	int64_t wait_lsn = last_entry->lsn;
 
-	if (box_wait_quorum(txn_limbo.owner_id, wait_lsn, quorum, timeout) != 0)
-		return -1;
+#ifndef NDEBUG
+    ++errinj(ERRINJ_WAIT_QUORUM_COUNT, ERRINJ_INT)->iparam;
```
Comment (Gerold103) [inline src/box/box.cc]: The alignment here isn't right. You have used 4 spaces apparently, instead of one tab. I am wondering why didn't checkpatch notice that (@locker).

**Review by Gerold103 — APPROVED** [review]
💪⬅️🚨

File: src/box/box.cc (hunk 19 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: src/box/txn_limbo.c (hunk 16 above)
Comment (sergepetrenko) [reply src/box/txn_limbo.c]: @Gerold103, so now a node will be able to write a CONFIRM after its quorum is decreased even if its limbo is frozen?
I don't think that's right.

File: src/box/box.cc [hunk 20]
```diff
@@ -171,7 +171,6 @@ static bool is_storage_initialized = false;
 static bool is_storage_shutdown = false;
 static bool is_ro = true;
 static fiber_cond ro_cond;
-
```
Comment (sergepetrenko) [inline src/box/box.cc:181]: nit: extraneous change

File: src/box/box.cc [hunk 21]
```diff
@@ -2782,22 +2780,13 @@ box_check_waiting_for_own_rows(void)
 	}
 }
 
-/**
- * Wait until at least @a quorum of nodes confirm @a target_lsn from the node
- * with id @a lead_id.
+/*
```
Comment (sergepetrenko) [inline src/box/box.cc]: nit: A function comment should start with `/**`.

File: src/box/box.cc [hunk 22]
```diff
@@ -2782,22 +2780,13 @@ box_check_waiting_for_own_rows(void)
...
+ * A helper which count how many nodes have the needed LSN of the given node
```
Comment (sergepetrenko) [inline src/box/box.cc]: Please add comments with a dot.

File: src/box/box.cc [hunk 23]
```diff
@@ -2782,22 +2780,13 @@ box_check_waiting_for_own_rows(void)
...
  */
 static int
-box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
-		double timeout)
+box_ack_count(uint32_t lead_id, int64_t target_lsn,
+	      struct vclock *vclock)
```
Comment (sergepetrenko) [inline src/box/box.cc]: `vclock` could fit on the previous line.

File: src/box/box.cc [hunk 24]
```diff
@@ -2808,7 +2797,8 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
 		assert(replica->id != REPLICA_ID_NIL);
 		assert(!tt_uuid_is_equal(&INSTANCE_UUID, &replica->uuid));
 
-		int64_t lsn = vclock_get(relay_vclock(replica->relay), lead_id);
+		int64_t lsn = vclock_get(relay_vclock(replica->relay),
+					 lead_id);
```
Comment (sergepetrenko) [inline src/box/box.cc]: `lead_id` could fit on the previous line.

**Review by sergepetrenko — COMMENTED** [review]
Thanks for the patch, Roman!

I have a couple of comments - one regarding the `txn_limbo_on_parameters_change` and some nits.

File: src/box/box.cc (hunk 20 above)
Comment (mrForza) [reply src/box/box.cc:181]: fixed

File: src/box/box.cc (hunk 21 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: src/box/box.cc (hunk 23 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: src/box/box.cc (hunk 22 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: src/box/box.cc (hunk 24 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: src/box/txn_limbo.c (hunk 16 above)
Comment (Gerold103) [reply src/box/txn_limbo.c]: Hm. I thought that `txn_limbo_confirm()` filters this case out on its own. But apparently it doesn't. I suggest:
- First of all write a test which would fail right now. Otherwise we can't confirm a bug.
- Make `txn_limbo_confirm()` nop when the limbo is frozen.

Would that work?

Comment (Serpentian) [reply src/box/txn_limbo.c]: Seems good to me, it's safe to write promote even in the frozen state, since the node will anyway remain in the RO, but not because the current node is not an owner, but due to the frozen limbo itself. Moreover, we've already become a leader and should write our PROMOTE

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua [hunk 25]
```diff
@@ -0,0 +1,128 @@
...
+    capture_synchro_queue_and_push_sync_transaction(g.server1)
+    g.server1:exec(function() _G.raft_worker_f:join() end)
+    wait_until_synchro_queue_is_empty(g.server1)
+end
+
+g.test_box_wait_quorum_with_lower_replication_synchro_quorum = function(g)
+    g.server1:update_box_cfg({replication_synchro_quorum = 2})
+    capture_synchro_queue_and_push_sync_transaction(g.server1)
+    g.server1:exec(function() _G.raft_worker_f:join() end)
+    wait_until_synchro_queue_is_empty(g.server1)
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:122]: Let's also check, that the node is in RW at the end of the tests

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua [hunk 26]
```diff
@@ -0,0 +1,128 @@
...
+g.before_all(function(g)
+    g.replicaset = replicaset:new({})
+    g.server_1_uri = server.build_listen_uri("server1", g.replicaset.id)
+    g.server_2_uri = server.build_listen_uri("server2", g.replicaset.id)
+    g.server_3_uri = server.build_listen_uri("server3", g.replicaset.id)
+
+    g.server1 = g.replicaset:build_and_add_server({
+        alias = "server1",
+        box_cfg = {
+            listen = g.server_1_uri,
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: Nit: listen is set automatically by luatest, can be skipped (see `server_instance.lua`, if you wanna see the implementation)

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua [hunk 27]
```diff
@@ -0,0 +1,128 @@
...
+            replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
+            replication_synchro_quorum = 4,
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:25]: Nit: let's set the quorum explicitly in the first test, as you do for other tests, it's easy to skip, that the test works under quorum 4

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua [hunk 28]
```diff
@@ -0,0 +1,128 @@
...
+    })
+
+    g.server3 = g.replicaset:build_and_add_server({
+        alias = "server3",
+        box_cfg = {
+            listen = g.server_3_uri,
+            replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
+            read_only = true,
+            election_mode = "manual",
+            replication_timeout = 0.5,
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: Nit: the box_cfg is the same for `server2` and `server3`, let's not duplicate the code and just use a variable `replica_box_cfg` or smth like that. The motivation is not making an observer to compare the tables manually

File: src/box/box.cc [hunk 29]
```diff
@@ -3200,30 +3158,68 @@ box_wait_limbo_acked(double timeout)
...
+		while (!fiber_is_cancelled() &&
+		       t.ack_count < replication_synchro_quorum) {
+			if (fiber_cond_wait_deadline(&txn_limbo.wait_cond,
+						     deadline) == -1) {
+				break;
+			}
+		}
+		trigger_clear(&t.base);
+		ack_count = t.ack_count;
+	       /*
```
Comment (Serpentian) [inline src/box/box.cc]: Nit: the indent of the comment is not right, should be:

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 1d4301af4f..85cbae380c 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -3195,12 +3195,13 @@ box_wait_limbo_acked(double timeout)
 		}
 		trigger_clear(&t.base);
 		ack_count = t.ack_count;
-	       /*
-		* No point to proceed after cancellation even if got the quorum.
-		* The quorum is waited by limbo clear function. Emptying the
-		* limbo involves a pair of blocking WAL writes, making the fiber
-		* sleep even longer, which isn't appropriate when it's canceled.
-		*/
+		/*
+		 * No point to proceed after cancellation even if got the
+		 * quorum. The quorum is waited by limbo clear function.
+		 * Emptying the limbo involves a pair of blocking WAL writes,
+		 * making the fiber sleep even longer, which isn't appropriate
+		 * when it's canceled.
+		 */
 		if (fiber_is_cancelled()) {
 			diag_set(FiberIsCancelled);
 			return -1;
```

File: src/box/box.cc [hunk 30]
```diff
@@ -3200,30 +3158,68 @@ box_wait_limbo_acked(double timeout)
...
+		t.waiter = fiber();
+		trigger_create(&t.base, synchro_quorum_on_ack_f, NULL, NULL);
+		trigger_add(&replicaset.on_ack, &t.base);
+		double deadline = ev_monotonic_now(loop()) + timeout;
+		while (!fiber_is_cancelled() &&
+		       t.ack_count < replication_synchro_quorum) {
+			if (fiber_cond_wait_deadline(&txn_limbo.wait_cond,
+						     deadline) == -1) {
+				break;
+			}
```
Comment (Serpentian) [inline src/box/box.cc]: Nit: the brackets are not needed

File: src/box/txn_limbo.c (hunk 16 above)
Comment (mrForza) [reply src/box/txn_limbo.c]: I wrote the next test:

<details>
<summary>Limbo test</summary>

```lua
local t = require("luatest")
local server = require("luatest.server")
local replicaset = require("luatest.replica_set")

local g = t.group()

g.before_all(function(g)
    g.replicaset = replicaset:new({})
    g.server_1_uri = server.build_listen_uri("server1", g.replicaset.id)
    g.server_2_uri = server.build_listen_uri("server2", g.replicaset.id)
    g.server_3_uri = server.build_listen_uri("server3", g.replicaset.id)

    g.server1 = g.replicaset:build_and_add_server({
        alias = "server1",
        box_cfg = {
            listen = g.server_1_uri,
            replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
            replication_synchro_quorum = 4,
            replication_timeout = 0.5,
        },
    })

    g.server2 = g.replicaset:build_and_add_server({
        alias = "server2",
        box_cfg = {
            listen = g.server_2_uri,
            replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
            read_only = true,
            election_mode = "manual",
            replication_timeout = 0.5,
        },
    })

    g.server3 = g.replicaset:build_and_add_server({
        alias = "server3",
        box_cfg = {
            listen = g.server_3_uri,
            replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri},
            read_only = true,
            election_mode = "manual",
            replication_timeout = 0.5,
        },
    })

    g.replicaset:start()
    g.replicaset:wait_for_fullmesh()
    g.server1:exec(function()
        require('compat').replication_synchro_timeout = 'new'
        box.schema.create_space("s", {is_sync = true}):create_index("p")
    end)
end)

g.after_each(function(g)
    g.server1:update_box_cfg({replication_synchro_quorum = 4})
end)

g.after_all(function(g)
    g.replicaset:drop()
end)

local function capture_synchro_queue_and_push_sync_transaction(server)
    server:exec(function()
        local fiber = require("fiber")
        -- We should set election_mode to "off" in order to capture the
        -- synchronous queue and store a sync transaction into it. It is
        -- important that the transaction should not be committed before
        -- a successful box.ctl.promote.
        box.cfg{election_mode = "off"}
        box.ctl.promote()
        t.assert_equals(box.info.election.state, "follower")
        t.assert_equals(box.info.synchro.queue.owner, box.info.id)
        t.assert_equals(box.info.synchro.queue.len, 0)
        box.atomic({wait = "submit"}, function() box.space.s:replace{0} end)
        t.assert_equals(box.info.synchro.queue.len, 1)
        -- So that we have the opportunity to perform some actions during
        -- hang in box_wait_quorum, we wrap the last box.ctl.promote into
        -- fiber and join it after some actions. In our case this action
        -- is reconfiguring of replication_synchro_quorum.
        box.cfg{election_mode = "manual"}
        rawset(_G, "raft_worker_f", fiber.new(function()
            box.ctl.promote()
            require("log").info("!\tlorem")
            t.assert_equals(box.info.election.state, "leader")
        end))
        _G.raft_worker_f:set_joinable(true)
    end)
end

local function wait_until_synchro_queue_is_empty(server)
    -- In some rare cases the limbo may not be cleared in time after
    -- successful completion of box_wait_quorum. We should wrap it
    -- into retrying block.
    server:exec(function()
        t.helpers.retrying({}, function()
            t.assert_equals(box.info.synchro.queue.len, 0)
        end)
    end)
end

g.test_transaction_confirmation_during_frozen_limbo = function(g)
    local full_replication = {g.server_1_uri, g.server_2_uri, g.server_3_uri}
    g.server1:update_box_cfg({
        replication_synchro_quorum = 2,
        replication = {g.server_1_uri},
    })
    g.server2:update_box_cfg({replication = {g.server_2_uri, g.server_3_uri}})
    g.server3:update_box_cfg({replication = {g.server_2_uri, g.server_3_uri}})

    capture_synchro_queue_and_push_sync_transaction(g.server1)
    g.server1:update_box_cfg({replication_synchro_quorum = 1})
    g.server3:exec(function()
        t.helpers.retrying({}, function()
            local is_success, res, err = pcall(box.ctl.promote)
            t.assert(is_success)
            t.assert_not(err)
            t.assert_equals(box.info.election.state, "leader")
        end)
    end)
    g.server1:exec(function() _G.raft_worker_f:join() end)
    wait_until_synchro_queue_is_empty(g.server1)

    for _, server in pairs({g.server1, g.server2, g.server3}) do
        server:update_box_cfg({replication = full_replication})
    end
    g.server1:exec(function(server_3_id)
        t.assert_equals(box.space.s:select(), {{0}})
        local rs = box.info.replication[server_3_id]
        t.assert(rs.upstream)
        t.assert_equals(rs.upstream.status, "stopped")
        t.assert_str_contains(rs.upstream.message, "Split-Brain discovered")
    end, {g.server3:get_instance_id()})
    g.server3:exec(function()
        t.assert_equals(box.space.s:select(), {})
    end)
end
```
</details>

<br>

This test checks the next case:

1) `server1` breaks the replication with `server2` and `server3`
2) `server1` captures synchro queue and push one sync transaction into it
3) `server1` hangs as it can't collect needed amount of acks. `replication_synchro_quorum = 2`, but the replication is broken.
4) During the hang we decrease `replication_synchro_quorum` to 1. (Limbo is in a frozen state).

<br>

In the current patch we get the next situation:

1) As we decrease a `replication_synchro_quorum`, our sync transaction can get enough acks - 1/1 and `server1` wins the elecion process as it gets the quorum of votes - 1/1.
2) Then server1 writes `RAFT` and `RAFT_PROMOTE` entries (analogue of `CONFIRM`) in .xlog file.
3) In the end of the test, we restore the replication among all nodes. As a result we get Split-Brain detection error and our server1 breaks all connections with `server2` and `server3`.

<br>

In the master branch we get the situation in which server1 will continue to be in the hanged state, as no one can interrupt the hanged while loop in `box_wait_quorum`. `txn_limbo_on_parameters_change` is a nop in this case because we exit from it due to `txn_limbo_is_frozen` check.

File: src/box/box.cc (hunk 30 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 25 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:122]: fixed

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 27 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:25]: fixed

File: src/box/box.cc (hunk 29 above)
Comment (mrForza) [reply src/box/box.cc]: fixed

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 26 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: Yes, but I need predefined uris in order to set `box_cfg.replication`.

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 28 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua]: fixed

File: src/box/txn_limbo.c (hunk 16 above)
Comment (sergepetrenko) [reply src/box/txn_limbo.c]: @mrForza, TBH what happens in this test looks suspicious. 

> In the current patch we get the next situation:
> 
> 1. As we decrease a `replication_synchro_quorum`, our sync transaction can get enough acks - 1/1 and `server1` wins the elecion process as it gets the quorum of votes - 1/1.
> 2. Then server1 writes `RAFT` and `RAFT_PROMOTE` entries (analogue of `CONFIRM`) in .xlog file.
> 3. In the end of the test, we restore the replication among all nodes. As a result we get Split-Brain detection error and our server1 breaks all connections with `server2` and `server3`.

Here's a small test which shows the problem:

```lua
-- Instance 1.
-- Step 1.
box.cfg{
    listen = 3301,
    replication = {3301, 3302},
    election_mode = 'candidate',
    replication_synchro_quorum = 2,
}

box.once("bootstrap", function()
    box.schema.space.create('test', {is_sync=true})
    box.space.test:create_index('pk')
    box.schema.user.grant('guest', 'super')
end)

-- Step 4.
box.cfg{replication_synchro_quorum = 1}

-- Step 5.
box.info.synchro -- Observe that limbo is empty, all its entries are confirmed
box.space.test:fselect{} -- The entry is committed.
box.info.election

-- Instance 2.
-- Step 2.
box.cfg{
    listen = 3302,
    replication = {3301,3302},
    election_mode = 'voter',
    replication_synchro_quorum = 2,
}

-- Console.
-- Step 3.
-- Take instance 2 pid instead of <pid>.
kill -stop <pid> && echo 'box.space.test:replace{1}' | tt connect 127.0.0.1:3301
```

The problem here is that instance1 reacts to quorum change and confirms an entry, even though it has already fenced before, and shouldn't do that before new elections start and a leader emerges.

Also somehow the instance starts new elections, although it shouldn't do that without user command in `manual` election mode.

Here it can be seen that a node first commits an entry (erroneously), and only then starts an election (also erroneously, if we're speaking of election_mode manual):
```
tarantool> -- Step 4.
---
...

tarantool> box.cfg{replication_synchro_quorum = 1}
---
...

tarantool> 
---
...

tarantool> -- Step 5.
---
...

tarantool> box.info.synchro -- Observe that limbo is empty, all its entries are confirmed
---
- queue:
    owner: 1
    size: 0
    confirm_lag: 156.860603
    busy: false
    age: 0
    len: 0
    term: 2
  quorum: 1
...

tarantool> box.space.test:fselect{} -- The entry is committed.
---
- |-
  +-----+
  |col1 |
  +-----+
  |  1  |
  +-----+
...

tarantool> box.info.election
---
- leader_idle: 156.975416
  state: follower
  vote: 1
  term: 2
  leader: 0
...

2025-09-29 18:36:49.507 [48294] main raft.c:959 I> RAFT: begin new election round
2025-09-29 18:36:49.507 [48294] main raft.c:891 I> RAFT: bump term to 3, follow
2025-09-29 18:36:49.508 [48294] main raft.c:929 I> RAFT: vote for 1, follow
2025-09-29 18:36:49.508 [48294] main/119/raft_worker raft.c:785 I> RAFT: persisted state {term: 3, vote: 1}
2025-09-29 18:36:49.508 [48294] main/119/raft_worker raft.c:844 I> RAFT: enter leader state with quorum 1
2025-09-29 18:36:49.508 [48294] main/119/raft_worker box.cc:445 I> box switched to rw

```

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 25 above)
Comment (Serpentian) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:122]: Maybe I'm missing smth, but I cannot find that in the patch

File: src/box/box.cc [hunk 31]
```diff
@@ -2723,11 +2723,9 @@ box_set_instance_name(void)
 }
```
Comment (Serpentian) [inline src/box/box.cc:2723]: Nit: commit msg - not `symchro`, `synchro`

File: test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua [hunk 32]
```diff
@@ -0,0 +1,71 @@
...
+    })
+
+    g.replicaset:start()
+    g.replicaset:wait_for_fullmesh()
+    g.server1:wait_for_election_leader()
+    g.server1:exec(function()
+        require('compat').replication_synchro_timeout = 'new'
+        box.schema.create_space("s", {is_sync = true}):create_index("p")
+    end)
+    g.server1:wait_for_vclock_of(g.server2)
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua]: Not needed, `server1` has greater vclock than `server2`

File: test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua [hunk 33]
```diff
@@ -0,0 +1,71 @@
...
+
+g.after_all(function(g)
+    g.replicaset:drop()
+end)
+
+g.test_no_promote_confirmation_during_frozen_limbo = function(g)
+    g.server2:exec(function()
+        box.error.injection.set("ERRINJ_WAL_IO", true)
+    end)
+    g.server1:exec(function()
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua:49]: Nit: you call `server1:exec` 3 times in a row, this should be one single `server:exec`

File: test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua [hunk 34]
```diff
@@ -0,0 +1,71 @@
...
+    g.server2:wait_for_vclock_of(g.server1)
+end)
+
+g.after_all(function(g)
+    g.replicaset:drop()
+end)
+
+g.test_no_promote_confirmation_during_frozen_limbo = function(g)
+    g.server2:exec(function()
+        box.error.injection.set("ERRINJ_WAL_IO", true)
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua:47]: Please, don't forget to remove it in the end of a test

File: test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua [hunk 35]
```diff
@@ -0,0 +1,71 @@
...
+    g.server1:exec(function()
+        t.helpers.retrying({}, function()
+            t.assert(box.info.ro)
+            t.assert_equals(box.info.ro_reason, "election")
+        end)
+    end)
+    g.server1:exec(function()
+        box.cfg{replication_synchro_quorum = 1}
+        t.assert_equals(box.space.s:select(), {{0}})
+        t.assert_equals(box.info.synchro.queue.len, 1)
```
Comment (Serpentian) [inline test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua:61]: The problem with this test is that it successfully passes before the patch, which should not be the case.

However, it indeed reproduces the issue, well done! The following passes:

```diff
diff --git a/src/box/txn_limbo.c b/src/box/txn_limbo.c
index fd9a5be8ba..52d0fea245 100644
--- a/src/box/txn_limbo.c
+++ b/src/box/txn_limbo.c
@@ -1051,8 +1051,6 @@ static void
 txn_limbo_confirm(struct txn_limbo *limbo)
 {
 	assert(txn_limbo_is_owned_by_current_instance(limbo));
-	if (txn_limbo_is_frozen(limbo))
-		return;
 	if (limbo->is_in_rollback)
 		return;
 	if (limbo->entry_to_confirm == NULL ||
diff --git a/test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua b/test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua
index 6fd2a4088f..ce78e3a02e 100644
--- a/test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua
+++ b/test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua
@@ -61,8 +61,9 @@ g.test_no_promote_confirmation_during_frozen_limbo = function(g)
     end)
     g.server1:exec(function()
         box.cfg{replication_synchro_quorum = 1}
-        t.assert_equals(box.space.s:select(), {{0}})
-        t.assert_equals(box.info.synchro.queue.len, 1)
+        t.helpers.retrying({}, function()
+            t.assert_equals(box.info.synchro.queue.len, 0)
+        end)
     end)
     g.server2:exec(function()
         t.assert_equals(box.space.s:select(), {})
```

I propose to change the test, so that it fails before the patch and succeedes after. Check out the following:

```diff
diff --git a/test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua b/test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua
index 6fd2a4088f..3c086a5f11 100644
--- a/test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua
+++ b/test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua
@@ -31,10 +31,10 @@ g.before_all(function(g)
     g.replicaset:wait_for_fullmesh()
     g.server1:wait_for_election_leader()
     g.server1:exec(function()
+        box.ctl.promote()
         require('compat').replication_synchro_timeout = 'new'
         box.schema.create_space("s", {is_sync = true}):create_index("p")
     end)
-    g.server1:wait_for_vclock_of(g.server2)
     g.server2:wait_for_vclock_of(g.server1)
 end)
 
@@ -47,25 +47,19 @@ g.test_no_promote_confirmation_during_frozen_limbo = function(g)
         box.error.injection.set("ERRINJ_WAL_IO", true)
     end)
     g.server1:exec(function()
-        box.ctl.promote()
-        t.assert_equals(box.info.election.state, "leader")
-        t.assert_equals(box.info.election.term, 2)
-        box.atomic({wait = "submit"}, function() box.space.s:replace{0} end)
-    end)
-    -- Wait until node switches into fencing mode
-    g.server1:exec(function()
+        local f = require('fiber').create(function() box.space.s:replace{0} end)
+        f:set_joinable(true)
+        -- Wait until node switches into fencing mode
         t.helpers.retrying({}, function()
             t.assert(box.info.ro)
             t.assert_equals(box.info.ro_reason, "election")
         end)
-    end)
-    g.server1:exec(function()
         box.cfg{replication_synchro_quorum = 1}
-        t.assert_equals(box.space.s:select(), {{0}})
+        t.assert_not(f:join(1))
         t.assert_equals(box.info.synchro.queue.len, 1)
     end)
     g.server2:exec(function()
-        t.assert_equals(box.space.s:select(), {})
         t.assert_equals(box.info.synchro.queue.len, 0)
+        box.error.injection.set("ERRINJ_WAL_IO", false)
     end)
 end
```

File: test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua (hunk 25 above)
Comment (Serpentian) [reply test/replication-luatest/gh_11574_hang_in_box_wait_quorum_test.lua:122]: Bump

File: src/box/box.cc (hunk 31 above)
Comment (mrForza) [reply src/box/box.cc:2723]: fixed

File: test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua (hunk 32 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua]: fixed

File: test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua (hunk 33 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua:49]: fixed

File: test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua (hunk 34 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua:47]: fixed

File: test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua (hunk 35 above)
Comment (mrForza) [reply test/replication-luatest/gh_11574_no_promote_confirmation_during_frozen_limbo_test.lua:61]: fixed

File: src/box/txn_limbo.c (hunk 16 above)
Comment (Serpentian) [reply src/box/txn_limbo.c]: The last commit confirms the bug and fixes it

Comment (sergepetrenko) [reply src/box/txn_limbo.c]: Thanks!
