### PR TITLE
config/schema: support field deletion using :set()

### LINKED ISSUE #10190: config/schema: :set() can't set a field nested to a box.NULL record/map
For example, there is a config with some objects that are defined as `record`s or `map`s:

```yaml
objects:
  obj2: null
  obj3: {}
  obj4:
    x: 1
```

It is transformed by `yaml.decode()` to Lua as follows:

```lua
{
    objects = {
        -- obj1 = nil,
        obj2 = box.NULL,
        obj3 = {},
        obj4 = {x = 1},
    },
}
```

It is natural to consider missed and `null` values as missed objects and other ones, including an empty table, as present objects. This way, `obj1` and `obj2` are missed, `obj3` and `obj4` are present.

Let's set some nested value in the given config:

```lua
local data = {objects = <...>}
myconfig_schema:set(data, 'objects.obj1.x', 1) -- OK
myconfig_schema:set(data, 'objects.obj2.x', 1) -- error
-- error: [myconfig_schema] objects.obj2.x: Unexpected data type for a record: "cdata"
```

However, it would be natural if assignments in `obj1` and `obj2` work in the same way.

<details>
<summary>More examples</summary>

```lua
local schema = require('internal.config.utils.schema')

-- Verify that box.NULL record is replaced by a table if a nested
-- field is set.
local s = schema.new('myschema', schema.record({
    foo = schema.record({
        bar = schema.scalar({type = 'string'}),
    }),
}))

local data = {foo = box.NULL}
s:set(data, 'foo.bar', 'mydata')
-- actual: error: [myschema] foo.bar: Unexpected data type for a record: "cdata"
-- expected: data = {foo = {bar = 'mydata'}}
```

```lua
local schema = require('internal.config.utils.schema')

-- Verify that box.NULL map is replaced by a table if a nested
-- field is set.
local s = schema.new('myschema', schema.map({
    key = schema.scalar({type = 'string'}),
    value = schema.map({
        key = schema.scalar({type = 'string'}),
        value = schema.scalar({type = 'string'}),
    }),
}))

local data = {foo = box.NULL}
s:set(data, 'foo.bar', 'mydata')
-- actual: [myschema] foo.bar: Unexpected data type for a map: "cdata"
-- expected: data = {foo = {bar = 'mydata'}}
```
</details>

This issue is neither feature, nor a bug in regards to the public API, because the module is internal until #10117 will be resolved. Moreover, there are no internal usages that can trigger the problem (all the usages are in `src/box/lua/config/source/env.lua`). I'm going to apply a fix to `3.2.0` and later, where the module will be public.

### LINKED ISSUE #10193: config/schema: :set() can't set a field of a record/a map to box.NULL
For example, there is a config with some objects that are defined as `record`s or `maps` (as in #10190):

```yaml
objects:
  obj2: null
  obj3: {}
  obj4:
    x: 1
```

It is impossible to set `obj3` or `obj4` to `null` (`box.NULL` in Lua).

```lua
local data = {objects = <...>}
myconfig_schema:set(data, 'objects.obj4', box.NULL)
-- error: [myconfig_schema] objects.obj4: Unexpected data type for a record: "cdata"
```

Also, we can't set a particular field of an object to `null`:

```lua
local data = {objects = <...>}
myconfig_schema:set(data, 'objects.obj4.x', box.NULL)
-- error: [myconfig_schema] objects.obj4.x: Unexpected data for scalar "string": Expected "string", got "cdata"
```

<details>
<summary>More examples</summary>

```lua
-- Verify that record's field can be set to box.NULL.

local schema = require('internal.config.utils.schema')

local s = schema.new('myschema', schema.record({
    foo = schema.record({
        bar = schema.scalar({type = 'string'}),
    }),
}))

local data = {}
s:set(data, 'foo', box.NULL)
-- actual: error: [myschema] foo: Unexpected data type for a record: "cdata"
-- expected: data = {foo = box.NULL}

local data = {}
s:set(data, 'foo.bar', box.NULL)
-- actual: error: [myschema] foo.bar: Unexpected data for scalar "string": Expected "string", got "cdata"
-- expected: data = {foo = {bar = box.NULL}}
```

```lua
-- Verify that map's field can be set to box.NULL.

local schema = require('internal.config.utils.schema')

local s = schema.new('myschema', schema.map({
    key = schema.scalar({type = 'string'}),
    value = schema.map({
        key = schema.scalar({type = 'string'}),
        value = schema.scalar({type = 'string'}),
    }),
}))

local data = {}
s:set(data, 'foo', box.NULL)
-- actual: error: [myschema] foo: Unexpected data type for a map: "cdata"
-- expected: data = {foo = box.NULL}

local data = {}
s:set(data, 'foo.bar', box.NULL)
-- actual: error: [myschema] foo.bar: Unexpected data for scalar "string": Expected "string", got "cdata"
-- expected: data = {foo = {bar = box.NULL}}
```
</details>

Similarly to #10190 I'm going to solve it in `3.2.0` and newer, because previous releases have no this functionality in the public API (and `<schema object>:set(<...>, box.NULL)` is not used internally).

### LINKED ISSUE #10194: config/schema: :set() can't delete a field
The `<schema object>:set()` method doesn't allow to delete a field.

For example, I would use assigning to `nil` in a flat table:

```lua
local config = {
    foo = 1,
    bar = 2,
}
config.foo = nil
-- config = {bar = 2}
```

It is expected that a similar functionality exists in the hierarchical configuration processing module:

```lua
local schema = require('internal.config.utils.schema')

local config_schema = schema.new('myconfig', schema.record({
    nested = schema.record({
        foo = schema.scalar({type = 'integer'}),
        bar = schema.scalar({type = 'integer'}),
    }),
}))

local config = {
    nested = {
        foo = 1,
        bar = 2,
    },
}
config_schema:set(config, 'nested.foo', nil)
-- actual: error: [myconfig] nested.foo: Unexpected data for scalar "integer": Expected "number", got "nil"
-- expected: config = {nested = {bar = 2}}
```

It is planned for `3.2.0` and newer, where the module is exposed into the public API (see #10117).

### PR DESCRIPTION
**Pull request by Totktonada**
This commit implements the `<schema object>:set()` algorithm in a more accurate way and it solves several drawbacks of the previous implementation.

* It was impossible to set a field that is nested to a record or a map that has the box.NULL value (#10190).
* It was impossible to set a field to the box.NULL value (#10193).
* It was impossible to delete a field, now `nil` RHS value means the deletion (#10194).

See `<schema object>:set()` section in https://github.com/tarantool/doc/issues/4279 for the documentation.

Fixes #10190
Fixes #10193
Fixes #10194

### CODE REVIEW

**Review by lenkis — APPROVED** [review]

File: src/box/lua/config/utils/schema.lua [hunk 1]
```diff
@@ -775,26 +783,52 @@ local function set_impl(schema, data, rhs, ctx)
...
+            -- a table.
+            if data ~= nil then -- table
+                data[requested_field] = nil
+            end
+        else
+            -- Assign the field. Replaces nil and box.NULL with
+            -- a newly created table, modifies a table.
+            if data == nil then -- nil or box.NULL
+                data = {}
+            end
```
Comment (mkokryashkin) [inline src/box/lua/config/utils/schema.lua:828]: Idiomatic way to do this is the following:
```lua
data = data or {}
```

File: src/box/lua/config/utils/schema.lua [hunk 2]
```diff
@@ -775,26 +783,52 @@ local function set_impl(schema, data, rhs, ctx)
...
-        data[requested_field] = set_impl(field_def, field_value, rhs, ctx)
+        local new_field_value = set_impl(field_def, field_value, rhs, ctx)
+
+        if type(new_field_value) == 'nil' then
+            -- Delete the field. Keeps nil and box.NULL, modifies
+            -- a table.
+            if data ~= nil then -- table
+                data[requested_field] = nil
+            end
+        else
```
Comment (mkokryashkin) [inline src/box/lua/config/utils/schema.lua:823]: It would be nice to drop a comment, mentioning that `nil` branch is here to avoid creation of an empty table.
Otherwise, it is unclear at a first glance why the entire chunk was not simplified down to something like:
```lua
data = data or {}
data[requested_field] = new_field_value
```

File: src/box/lua/config/utils/schema.lua (hunk 1 above)
Comment (Totktonada) [reply src/box/lua/config/utils/schema.lua:828]: It doesn't work in case of `box.NULL`. It is why I'm leaving the `-- nil or box.NULL` comments in such cases.

Comment (mkokryashkin) [reply src/box/lua/config/utils/schema.lua:863]: Forgot about that issues, thanks for the clarification

**Review by mkokryashkin — APPROVED** [review]
