### PR TITLE
recovery: fix recovering from 1.6 xlogs/snaps

### LINKED ISSUE #6794: Tarantool fails to recover from 1.6 xlogs/snaps
We've encountered the following behaviour when updating Tarantool 1.6 to 1.10:

An updated node (running Tarantool 1.10) cannot recover from 1.6 data directory:

```
2022-01-14 14:31:15.889 [25195] main/101 I> recover from `./00000000000552892554.xlog'
2022-01-14 14:31:16.121 [25195] main/101 I> done `./00000000000552892554.xlog'
2022-01-14 14:54:10.067 [25195] main/101 F> Can't proceed. Replicaset vclock ({1: 126408462, 2: 29577963, 3: 397148821, 4: 0, 5: 0, 6: 0, 7: 0}) doesn't match recovered data ({1: 126506038, 2: 29577963, 3: 397148821, 4: 0, 5: 0, 6: 0, 7: 0})
```

There are only two files in the data directory:
`00000000000553135246.snap` and `00000000000552892554.xlog`.

All tarantool versions >= 1.10 (probably earlier) are affected.

The problem is that Tarantool 1.6 doesn't rotate xlogs upon snapshot creation: that's why we have an `xlog`, which covers a range of insertions **before** `00000000000553135246.snap` and **after** it.

Tarantool 1.10 recovers the data from such files correctly, taking everything there is **after** the `snap` from `xlog`, but it only takes `replicaset.vclock` from the `snap`, and never updates it during `xlog` recovery (it believes `xlog` is older than the `snap`, judging by the file names. But this is not the case for 1.6-generated files).

### PR DESCRIPTION
**Pull request by sergepetrenko**
Tarantool 1.6 didn't rotate xlogs on snap creation.
This means, that Tarantool 1.6 data dir may contain files like
0...0.xlog and 0...01.snap, where 0...0.xlog covers changes both before
and after the snap creation.

New Tarantool versions fail to recover from such files: they recover the
data correctly, but fail to update the vclock accordingly.

Let's allow recovering from such files and update the vclock
accordingly, but only when force_recovery is set.

Patch 634f59c7 ("recovery: panic in case of recovery and replicaset
vclock mismatch") added the panic, which helped to discover the issue.
Before that patch Tarantool would silently recover with an outdated
vclock.

Also, while we're at it, refactor the check leading to a panic: it never
happens after hot_standby, so move it into "else" branch of hot_standby.

The patch lacks a test, because the test would require specially crafted
snap/xlog pair. For example, 0...1.snap and 0...0.xlog, where 0...0.xlog
spans to vclock greater than the one present in 0...1.snap.
One could create such xlog by concatenating two subsequent xlogs, or by
copying an existing xlog of another instance and replacing the
instance_uuid in the header.

Closes #6794

### CODE REVIEW

File: src/box/box.cc [hunk 1]
```diff
@@ -3530,17 +3530,45 @@ local_recovery(const struct tt_uuid *instance_uuid,
...
+		 *
+		 * The second case could be distinguished from the first one,
+		 * but this would require unnecessarily re-reading an xlog
+		 * preceding the latest snap, just to make sure the WAL doesn't
+		 * span over the snap creation signature.
+		 *
+		 * Allow both cases, if the user has set force_recovery.
+		 */
+		const char *mismatch_str =
+			tt_sprintf("Replicaset_vclock %s doesn't match "
```
Comment (locker) [inline src/box/box.cc:3557]: Nit: unnecessary underscore (_) between 'replicaset' and 'vclock'.

File: src/box/box.cc [hunk 2]
```diff
@@ -3530,17 +3530,45 @@ local_recovery(const struct tt_uuid *instance_uuid,
...
+				   "recovered data %s",
+				   vclock_to_string(&replicaset.vclock),
+				   vclock_to_string(&recovery->vclock));
+		if (is_force_recovery) {
+			say_warn("%s: ignoring, because 'force_recovery' "
+				 "configuration option is set.", mismatch_str);
+			vclock_copy(&replicaset.vclock, &recovery->vclock);
```
Comment (locker) [inline src/box/box.cc:3564]: Let's please add a test. I think it's okay to craft an xlog/snap pair and commit them to the repository as binary files.

Comment (locker) [inline src/box/box.cc:3564]: Changelog is missing. Please add.

**Review by locker — CHANGES_REQUESTED** [review]

**Comment by sergepetrenko** [comment]
@locker, thanks for the review!

I've force-pushed an updated version.

<details><summary>Here's the diff:</summary>

```diff
diff --git a/changelogs/unreleased/gh-6794-recover-1.6-xlogs.md b/changelogs/unreleased/gh-6794-recover-1.6-xlogs.md
new file mode 100644
index 000000000..760ced595
--- /dev/null
+++ b/changelogs/unreleased/gh-6794-recover-1.6-xlogs.md
@@ -0,0 +1,6 @@
+## bugfix/recovery
+
+* When `force_recovery` cfg option is set, Tarantool is able to boot from
+  `snap`/`xlog` combinations where `xlog` covers changes committed both before
+  and after `snap` creation. For example, `0...0.xlog`, covering everything up
+  to vclock `{1: 15}` and `0...09.snap`, corresponding to `vclock `{1: 9}` (gh-6794).
diff --git a/src/box/box.cc b/src/box/box.cc
index dfa0d5aee..6a33203df 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -3554,7 +3554,7 @@ local_recovery(const struct tt_uuid *instance_uuid,
 		 * Allow both cases, if the user has set force_recovery.
 		 */
 		const char *mismatch_str =
-			tt_sprintf("Replicaset_vclock %s doesn't match "
+			tt_sprintf("Replicaset vclock %s doesn't match "
 				   "recovered data %s",
 				   vclock_to_string(&replicaset.vclock),
 				   vclock_to_string(&recovery->vclock));
diff --git a/test/box-luatest/gh_6794_data/00000000000000000000.xlog b/test/box-luatest/gh_6794_data/00000000000000000000.xlog
new file mode 100644
index 000000000..2ceca712c
Binary files /dev/null and b/test/box-luatest/gh_6794_data/00000000000000000000.xlog differ
diff --git a/test/box-luatest/gh_6794_data/00000000000000000001.snap b/test/box-luatest/gh_6794_data/00000000000000000001.snap
new file mode 100644
index 000000000..68571d186
Binary files /dev/null and b/test/box-luatest/gh_6794_data/00000000000000000001.snap differ
diff --git a/test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua b/test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua
new file mode 100644
index 000000000..9bddfb44a
--- /dev/null
+++ b/test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua
@@ -0,0 +1,46 @@
+local server = require('test.luatest_helpers.server')
+local t = require('luatest')
+local g = t.group()
+local fio = require('fio')
+
+g.before_each(function()
+    g.server = server:new({alias = 'master'})
+    -- Initialize server's workdir with specially crafted snap/xlog pair.
+    os.execute(string.format('ln -s %s/* %s/',
+                             fio.abspath('./test/box-luatest/gh_6794_data'),
+                             g.server.workdir))
+end)
+
+g.after_test("test_panic_without_force_recovery", function()
+    g.server:cleanup()
+end)
+
+g.after_test("test_ignore_with_force_recovery", function()
+    g.server:drop()
+end)
+
+local mismatch_msg = "Replicaset vclock {.*} doesn't match recovered data {.*}"
+
+g.test_panic_without_force_recovery = function()
+    g.server:start({wait_for_readiness = false})
+    t.helpers.retrying({}, function()
+        local msg = "Can't proceed. " .. mismatch_msg
+        local filename = fio.pathjoin(g.server.workdir, g.server.alias..'.log')
+        assert(g.server:grep_log(msg, nil, {filename = filename}))
+    end)
+end
+
+g.test_ingore_with_force_recovery = function()
+    g.server.box_cfg = {force_recovery = true}
+    g.server:start()
+    t.helpers.retrying({}, function()
+        local msg = mismatch_msg .. ": ignoring, because 'force_recovery' "..
+                    "configuration option is set."
+        assert(g.server:grep_log(msg))
+    end)
+    assert(g.server:exec(function()
+               return box.info.signature >= 2 and
+                      box.info.status == 'running' and
+                      box.info.ro == false end),
+           "Failed to recover data")
+end
```

</details>

File: test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+end)
+
+local mismatch_msg = "Replicaset vclock {.*} doesn't match recovered data {.*}"
+
+g.test_panic_without_force_recovery = function()
+    g.server:start({wait_for_readiness = false})
+    t.helpers.retrying({}, function()
+        local msg = "Can't proceed. " .. mismatch_msg
+        local filename = fio.pathjoin(g.server.workdir, g.server.alias..'.log')
+        assert(g.server:grep_log(msg, nil, {filename = filename}))
```
Comment (locker) [inline test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua:29]: You should use `t.assert`. Please fix here and everywhere else.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/box.cc (hunk 2 above)
Comment (sergepetrenko) [reply src/box/box.cc:3564]: Okay, sure

File: changelogs/unreleased/gh-6794-recover-1.6-xlogs.md [hunk 4]
```diff
@@ -0,0 +1,6 @@
+## bugfix/recovery
+
+* When `force_recovery` cfg option is set, Tarantool is able to boot from
+  `snap`/`xlog` combinations where `xlog` covers changes committed both before
+  and after `snap` creation. For example, `0...0.xlog`, covering everything up
+  to vclock `{1: 15}` and `0...09.snap`, corresponding to `vclock `{1: 9}` (gh-6794).
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply changelogs/unreleased/gh-6794-recover-1.6-xlogs.md:6]: I prefer a more detailed description, if you don't mind

File: test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+                             g.server.workdir))
+end)
+
+g.after_test("test_panic_without_force_recovery", function()
+    g.server:cleanup()
+end)
+
+g.after_test("test_ignore_with_force_recovery", function()
+    g.server:drop()
+end)
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua:20]: Because `drop` (which's `stop` + `cleanup`) fails on a crashed server. Hangs, IIRC.

File: test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua (hunk 3 above)
Comment (sergepetrenko) [reply test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua]: Indeed, my bad. Thanks!

Here's the diff. Please, let me know whether you prefer small diffs per comment or a single incremental diff in reply to all comments.
```diff
@@ -26,7 +24,7 @@ g.test_panic_without_force_recovery = function()
     t.helpers.retrying({}, function()
         local msg = "Can't proceed. " .. mismatch_msg
         local filename = fio.pathjoin(g.server.workdir, g.server.alias..'.log')
-        assert(g.server:grep_log(msg, nil, {filename = filename}))
+        t.assert(g.server:grep_log(msg, nil, {filename = filename}))
     end)
 end
 
@@ -36,11 +34,11 @@ g.test_ingore_with_force_recovery = function()
     t.helpers.retrying({}, function()
         local msg = mismatch_msg .. ": ignoring, because 'force_recovery' "..
                     "configuration option is set."
-        assert(g.server:grep_log(msg))
+        t.assert(g.server:grep_log(msg))
     end)
-    assert(g.server:exec(function()
-               return box.info.signature >= 2 and
-                      box.info.status == 'running' and
-                      box.info.ro == false end),
-           "Failed to recover data")
+    t.assert(g.server:exec(function()
+                return box.info.signature >= 2 and
+                       box.info.status == 'running' and
+                       box.info.ro == false end),
+             "Failed to recover data")
 end
```

**Review by locker — APPROVED** [review]

File: changelogs/unreleased/gh-6794-recover-1.6-xlogs.md (hunk 4 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply changelogs/unreleased/gh-6794-recover-1.6-xlogs.md:6]: I would highlight that the user story is 'able to bootstrap the new tarantool from tarantool 1.6 snapshot and xlogs', while we have no '1.6' here at all.

The primary goal of release notes is to offer understanding what is changed to a user without internal team jargon and gory details. I don't mind details (but consider moving them into a separate paragraph), however the key value of the change for a user should be cleanly stated, I think.

[the remark this answers is not in the document]
Comment (Totktonada) [reply changelogs/unreleased/gh-6794-recover-1.6-xlogs.md:6]: (I'll reopen the discussion to keep my concern tracked, but feel free to close it without changes.)

**Review by Gerold103 — APPROVED** [review]
Thanks for the patch!

File: changelogs/unreleased/gh-6794-recover-1.6-xlogs.md (hunk 4 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply changelogs/unreleased/gh-6794-recover-1.6-xlogs.md:6]: @Totktonada, I see your point, thanks! Sorry I missed your comment. I'll keep that in mind next time.
