### PR TITLE
txm: switch to normal mode earlier durion recovery with MVCC

### LINKED ISSUE #5610: Dirty reads after restart with synchronous replication and transaction manager
Tarantool version: 2.6+

Follow these steps to reproduce: 
1. Start a single instance and configure it as follows:
```lua
box.cfg{
    replication_synchro_quorum=2,
    replication_synchro_timeout=100,
    memtx_use_mvcc_engine=true
}
```
2. Create a synchronous space
```lua
box.schema.space.create('test', {is_sync=true})
box.space.test:create_index('pk')
```
3. Insert something to the space. Since `replication_synchro_quorum` is `2`, the insertion will stall for 100 seconds.
```lua
require('fiber').new(function() box.space.test:insert{1} end)
```
4. Everything's fine for now: `box.space.test:select{}` returns nothing.
5. Kill the instance before the insertion from step 3 times out.
6. Restart the instance, configure it the same way that we did in step 1
7. The synchronous transaction isn't committed. You may check that by doing something like
```lua
box.space.schema:replace{'smth'}.
```
The replace will stall, since the limbo isn't empty..
8. Still, `box.space.test:select{}` will return `[1]` ?!

### PR DESCRIPTION
**Pull request by alyapunov**
Usually during final recovery, when .xlog files are loaded and
applied, a special memtx_space_replace_primary_key function is
used for faster recovery. The function only updates primary key
while all other indexes are scheduled to build at the end of
recovery.

This approach doesn't work with MVCC engine and synchro spaces:
When transactions appear in xlog and they may or may not be
committed, we should process the in normal mode throught all
indexes in order to leave transaction history in each index.

Fixes #5610 #5973

### CODE REVIEW

File: test/box/gh-5610-dirty-restart.lua [hunk 1]
```diff
@@ -0,0 +1,12 @@
+#!/usr/bin/env tarantool
+
+box.cfg{
+    listen                 = os.getenv("LISTEN"),
+    memtx_memory           = 107374182,
+    pid_file               = "tarantool.pid",
```
Comment (Korablev77) [inline test/box/gh-5610-dirty-restart.lua:6]: Anyway didn't get the necessity of memtx_memory and pid_file settings. Otherwise LGTM

**Review by Korablev77 — APPROVED** [review]
>we should process the in normal mode

I guess you should swap words 'the' and 'in'

File: test/box/gh-5610-dirty-restart.test.lua [hunk 2]
```diff
@@ -0,0 +1,20 @@
+env = require('test_run')
+test_run = env.new()
+test_run:cmd("create server gh_5610_dirty_restart with script='box/gh-5610-dirty-restart.lua'")
+test_run:cmd("start server gh_5610_dirty_restart")
+test_run:cmd("switch gh_5610_dirty_restart")
+
+fiber = require('fiber')
+s = box.schema.space.create('test', {is_sync = true})
+i = s:create_index('pk')
+fiber.new(function() box.space.test:insert{1} end)
```
Comment (EvgenyMekhanik) [inline test/box/gh-5610-dirty-restart.test.lua:10]: Here it's better to write like this
_ = fiber.new(function() box.space.test:insert{1} end)
I see in test result
fiber.new(function() box.space.test:insert{1} end)
 ---
 - status: suspended
   name: lua
   id: 124
I am not shure that id is always equal to 124, so it's may be flaky test

Comment (EvgenyMekhanik) [reply test/box/gh-5610-dirty-restart.test.lua:10]: I try to start it 100 times on my local machine and it's fails!
] +++ var/rejects/box/gh-5610-dirty-restart.reject	Wed Apr 14 14:29:24 2021
[001] @@ -31,7 +31,7 @@
[001]   | ---
[001]   | - status: suspended
[001]   |   name: lua
[001] - |   id: 124
[001] + |   id: 126
[001]   | ...

Comment (alyapunov) [reply test/box/gh-5610-dirty-restart.test.lua]: Thanks! applied your fix.

**Review by EvgenyMekhanik — APPROVED** [review]
