### PR TITLE
applier: fix isolation level of applied transactions

### LINKED ISSUE #8121: mvcc shouldn't work on a replication stream
Reproduced on latest master (2.11.0-entrypoint-850-g182034dc9)

**Bug description**
Run 2 Tarantool instances in console:
```lua
-- Instance 1.
-- Step 1.
box.cfg{
    listen = 3301,
    memtx_use_mvcc_engine = true,
    txn_isolation = 'read-confirmed',
}

box.once('bootstrap', function()
    box.schema.user.grant('guest', 'replication')
    box.schema.space.create('test')
    box.space.test:create_index('pk')
    box.space.test:insert{1}
end)

-- Step 3.
box.space.test:delete{1}
box.space.test:delete{1}

-- Instance 2.
-- Step 2.
box.cfg{replication = 3301, memtx_use_mvcc_engine = true, txn_isolation = 'read-confirmed'}
box.cfg{replication = ""}

-- Step 4.
box.cfg{replication = 3301}
```

After these steps the replica will disconnect from master with an `ER_TRANSACTION_CONFLICT` error.
It's box.info.replication will read:
```
tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: 95005d25-21b3-42cb-8eb8-9aed62f35771
    lsn: 8
    upstream:
      peer: '3301'
      lag: 0.00046181678771973
      status: stopped
      idle: 4.4793854899999
      message: Transaction has been aborted by conflict
  2:
    id: 2
    uuid: e00fad89-c417-4d39-af1c-e6b7197ea38b
    lsn: 0
...

```

The reason for this is that from master's point of view the deletes were run sequentially, but for replica they were concurrent: that's because replica applies transactions in parallel: commits them asynchronously not waiting for a wal write to complete.

It seems mvcc shouldn't work on a replication stream. At least when this stream comes from a single master. Because having transactions in master's WAL means there were no conflicts when master committed them.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Closes #8121

### CODE REVIEW

File: src/box/applier.cc [hunk 1]
```diff
@@ -1378,6 +1378,7 @@ apply_plain_tx(uint32_t replica_id, struct stailq *rows,
 	struct applier_tx_row *item;
 	if (txn == NULL)
 		 return -1;
+	txn->isolation = TXN_ISOLATION_READ_COMMITTED;
```
Comment (sergepetrenko) [inline src/box/applier.cc:1381]: I'd probably use `box_txn_set_isolation` here. Then we'll be safe in case setting txn isolation becomes more complex than just setting a variable someday.

Or even better, to avoid the extra checks `box_txn_set_isolation` performs, you can extract the part which sets the isolation in a separate routine and use it here.
And also use it in `box_txn_set_isolation` after the checks.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+    cg.replica = cg.cluster:build_server(
+            {
+                alias = 'replica',
+                box_cfg = {
+                    replication = server.build_listen_uri('master'),
+                    memtx_use_mvcc_engine = true,
+                    txn_isolation = 'read-confirmed',
+                }
+            })
+    cg.cluster:add_server(cg.master)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:19]: BTW, you can use `build_and_add_server` instead of `build_server`, `add_server`.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+    cg.cluster:add_server(cg.replica)
+    cg.cluster:start()
+    cg.master:exec(function()
+        local s = box.schema.space.create('s')
+        s:create_index('pk')
+        s:insert{0}
+    end)
+    t.helpers.retrying({}, function()
+        cg.replica:assert_follows_upstream(cg.master:get_instance_id())
+    end)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:29]: Better use `cg.replica:wait_for_vclock_of(cg.master)` here.
the fact that replica follows upstream doesn't prove anything here. It might follow master, but it might not have the same vclock yet.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+end)
+
+-- Checks that replication stream does not get transaction conflict errors.
+g.test_replication_stream_transaction_conflict_errors = function(cg)
+    cg.replica:exec(function()
+        box.cfg{replication = ""}
+    end)
+    cg.master:exec(function()
+        box.space.s:delete{0}
+        box.space.s:delete{0}
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:43]: I see that the test fails on the current master, which's good.

But wasn't the case with 2 deletes fixed in #8122 ?
For example, when I try to run the original reproducer with 2 deletes, it doesn't cause a conflict.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua [hunk 5]
```diff
@@ -0,0 +1,57 @@
+local t = require('luatest')
+local cluster = require('luatest.replica_set')
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:2]: Nit: since the module was renamed to `replica_set`, let's call it replica_set in new tests.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the patch!

Please find my comments below.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua (hunk 4 above)
Comment (CuriousGeorgiy) [reply test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:43]: > For example, when I try to run the original reproducer with 2 deletes, it doesn't cause a conflict.

But at the same time you say:
> I see that the test fails on the current master, which's good.

> But wasn't the case with 2 deletes fixed in https://github.com/tarantool/tarantool/issues/8122 ?

No, AFAIC, it wasn't — I run the original reproducer with 2 deletes and it causes conflict on master.
Screen Shot 2023-01-20 at 11 30 04

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua (hunk 5 above)
Comment (CuriousGeorgiy) [reply test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:2]: Fixed.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua (hunk 3 above)
Comment (CuriousGeorgiy) [reply test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:29]: Changed to `cg.master:wait_for_downstream_to(cg.replica)`.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua (hunk 2 above)
Comment (CuriousGeorgiy) [reply test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:19]: Thanks for the suggestion, applied!

File: src/box/applier.cc (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/applier.cc:1381]: Not sure about this. `box_txn_set_isolation` is really general: even if we factor out the part that sets the passed transaction's isolation level, it still performs additional checks, e.g., whether the isolation level is default, and whether the transaction needs to be linearized.

@alyapunov RFC

Comment (alyapunov) [reply src/box/applier.cc:1381]: I agree with @CuriousGeorgiy, box_txn_set_isolation is a part of API but we do some internal thing here and there's no reason to do additional check.

Perhaps one day we'll need a wrapper like `txn_set_isolation` but it seems to be an overkill today.

Comment (CuriousGeorgiy) [reply src/box/applier.cc:1381]: Besides, we didn't do this this in vinyl: https://github.com/tarantool/tarantool/blob/a24714c55305280838576fa6dec9a9781763e893/src/box/vy_tx.c#L344.

Comment (CuriousGeorgiy) [reply src/box/applier.cc:1381]: @locker what do you think about this?

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+                alias = 'replica',
+                box_cfg = {
+                    replication = server.build_listen_uri('master'),
+                    memtx_use_mvcc_engine = true,
+                    txn_isolation = 'read-confirmed',
+                }
+            })
+    cg.replica_set:start()
+    cg.master:exec(function()
+        local s = box.schema.space.create('s')
```
Comment (locker) [inline test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:21]: Let's make this space multi-engine.

File: src/box/applier.cc (hunk 1 above)
Comment (locker) [reply src/box/applier.cc:1381]: Vinyl inherits the isolation level from `struct txn`:

https://github.com/tarantool/tarantool/blob/02e2b2920e2c99c349bcfc246976a0f3e0c2a199/src/box/vinyl.c#L2433

Still, it'd be nice to have a test that makes sure this patches fixes the issue for both engines.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua (hunk 6 above)
Comment (CuriousGeorgiy) [reply test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua]: Made the test multi-engine.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua [hunk 7]
```diff
@@ -0,0 +1,61 @@
+local t = require('luatest')
+local replica_set = require('luatest.replica_set')
+local server = require('luatest.server')
+
+local g = t.group(nil, t.helpers.matrix({eng = {'memtx', 'vinyl'}}))
```
Comment (locker) [inline test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:5]: Nit: please don't use confusing abbreviations like 'eng' - 'engine' is short enough.

Comment (CuriousGeorgiy) [reply test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua]: Ok, fixed.

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+    cg.master = cg.replica_set:build_and_add_server({alias = 'master'})
+    cg.replica = cg.replica_set:build_and_add_server(
+            {
+                alias = 'replica',
+                box_cfg = {
+                    replication = server.build_listen_uri('master'),
+                    memtx_use_mvcc_engine = true,
+                    txn_isolation = 'read-confirmed',
+                }
+            })
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:18]: Don't forget to lower `replication_timeout`. We usually set 0.1, and it speeds the tests up quite a bit. For example for this test the time went down from ~ 3.4 seconds to ~ 1.6 on my machine.
```diff
diff --git a/test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua b/test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua
index 1157a287c..7debcda00 100644
--- a/test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua
+++ b/test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua
@@ -6,12 +6,19 @@ local g = t.group(nil, t.helpers.matrix({eng = {'memtx', 'vinyl'}}))
 
 g.before_all(function(cg)
     cg.replica_set = replica_set:new()
-    cg.master = cg.replica_set:build_and_add_server({alias = 'master'})
+    cg.master = cg.replica_set:build_and_add_server(
+            {
+                alias = 'master',
+                box_cfg = {
+                    replication_timeout = 0.1,
+                },
+            })
     cg.replica = cg.replica_set:build_and_add_server(
             {
                 alias = 'replica',
                 box_cfg = {
                     replication = server.build_listen_uri('master'),
+                    replication_timeout = 0.1,
                     memtx_use_mvcc_engine = true,
                     txn_isolation = 'read-confirmed',
                 }
```

**Review by sergepetrenko — CHANGES_REQUESTED** [review]

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua (hunk 8 above)
Comment (CuriousGeorgiy) [reply test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua]: Ok, fixed. Why isn't this the default value then?

**Review by sergepetrenko — APPROVED** [review]
LGTM!

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+
+-- Checks that replication stream does not get transaction conflict errors.
+g.test_replication_stream_transaction_conflict_errors = function(cg)
+    cg.replica:exec(function()
+        local t = require('luatest')
+
+        t.assert_equals(box.space.s:select{}, {{0}})
+    end)
+    cg.master:exec(function()
+        box.space.s:delete{0}
```
Comment (kyukhin) [inline test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:53]: Could you please add a comment describing why there're two deletes?

**Review by kyukhin — CHANGES_REQUESTED** [review]

File: test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua (hunk 9 above)
Comment (CuriousGeorgiy) [reply test/replication-luatest/gh_8121_memtx_mvcc_replication_stream_test.lua:53]: Actually, this is just a reproducer from the ticket, but I also added a comment as you asked for.

**Comment by kyukhin** [comment]
CI for alpine seems to be broken due to other reasons. So, let's ignore them.

**Review by kyukhin — APPROVED** [review]
