### PR TITLE
Multithread friendly signals

### LINKED ISSUE #7408: clock_lowres_tick: Assertion `clock_lowres_thread_is_owner()' failed.
In Debug build in TDG CI I see:
```
2022-07-14T02:12:54.5475017Z WARNING  localhost:45166:server.py:42 tarantool: /__w/sdk/sdk/tarantool-master/tarantool/src/lib/core/clock_lowres.c:59: clock_lowres_tick: Assertion `clock_lowres_thread_is_owner()' failed.
```

2.11.0-entrypoint-5-g4aa52ce0b-r499

It shoots in tests that uses https://github.com/tarantool/kafka module.

### PR DESCRIPTION
**Pull request by drewdzzz**
Currently, tarantool is not designed to allow user to spawn his
own threads with unblocked signals in new modules, applications 
using tarantool and so on. This patch adapts tarantool to this possibility.

This is supposed to solve the problem, described in #7408.

Closes #7408

### CODE REVIEW

File: test/unit/tt_sigaction.c [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+	while (clock_monotonic() - start < TEST_LEN)
+		sched_yield();
+	return NULL;
+}
+
+static void
+handler_f(int signum)
+{
+	(void)signum;
+	fail_if(!pthread_equal(pthread_self(), main_thread));
```
Comment (locker) [inline test/unit/tt_sigaction.c:31]: Better count the number of times the signal handler was executed from a wrong thread and then check that it's zero in the end of the test.

File: test/unit/tt_sigaction.c [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+main(void)
+{
+	plan(1);
+
+	struct sigaction sa;
+	memset(&sa, 0, sizeof(sa));
+	sa.sa_handler = handler_f;
+	if (tt_sigaction(SIGALRM, &sa, NULL) != 0) {
+		note("Cannot set signal handler");
+		exit(-1);
```
[the remark this answers is not in the document]
Comment (drewdzzz) [reply test/unit/tt_sigaction.c]: Changed to `fail_if`

File: test/unit/tt_sigaction.c [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+
+/** Test duration in seconds. */
+#define TEST_LEN 1.5
+/** Signal sending period in usec. Must be lower than second. */
+#define SIGNAL_PERIOD 1e3
+
+pthread_t main_thread;
+
+void *
+thread_f(void *arg)
```
[the remark this answers is not in the document]
Comment (drewdzzz) [reply test/unit/tt_sigaction.c:24]: done

File: test/unit/tt_sigaction.c (hunk 1 above)
Comment (drewdzzz) [reply test/unit/tt_sigaction.c]: Done

File: test/unit/tt_sigaction.c [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+	pthread_attr_t attr;
+	if (pthread_attr_init(&attr) != 0) {
+		note("Cannot init pthread_attr");
+		exit(-1);
+	}
+	if (pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE) != 0) {
+		note("Cannot set joinable attr");
+		exit(-1);
+	}
+	if (pthread_create(&child_thread, &attr, &thread_f, NULL) != 0) {
```
[the remark this answers is not in the document]
Comment (drewdzzz) [reply test/unit/tt_sigaction.c]: Done

File: test/unit/tt_sigaction.c [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+#define SIGNAL_PERIOD 1e3
+
+pthread_t main_thread;
+
+void *
+thread_f(void *arg)
+{
+	double start = clock_monotonic();
+	while (clock_monotonic() - start < TEST_LEN)
+		sched_yield();
```
[the remark this answers is not in the document]
Comment (drewdzzz) [reply test/unit/tt_sigaction.c]: We cannot sleep because sleep implementation can use SIGALRM, which is used by test. Changed to busy cycle.

[the remark this answers is not in the document]
Comment (locker) [reply test/unit/tt_sigaction.c]: What wrong can happen in this case? We use `sleep` here and there so avoiding it in the test looks suspicious. You could use `thread_sleep` - it calls `nanosleep` under the hood. There's nothing said about `alarm` in `nanosleep` man page.

[the remark this answers is not in the document]
Comment (locker) [reply test/unit/tt_sigaction.c]: Busy loop is no better than `sched_yield`.

File: src/lib/core/crash.c [hunk 6]
```diff
@@ -508,20 +508,28 @@ crash_report_stderr(struct crash_info *cinfo)
...
-		crash_report_stderr(cinfo);
-		if (send_crashinfo &&
-		    crash_report_feedback_daemon(cinfo) != 0) {
-			pr_crit("unable to send a crash report");
+	/**
+	 * Some users of tarantool spawn threads and do not
+	 * block signals on them, so let's check that callback
+	 * is being executed on the main thread. If it is not -
+	 * we will only try to dump a core.
+	 */
```
Comment (locker) [inline src/lib/core/crash.c:516]: SIGSEGV and SIGFPE are thread directed signals - AFAIK they are always received by the thread that triggered the fault, even if they are blocked. AFAICS this patch basically breaks stack trace reporting for faults in threads other than tx (iproto, wal, etc). I think that `crash_collect` should be safe to call from any thread.

File: test/unit/tt_sigaction.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (drewdzzz) [reply test/unit/tt_sigaction.c]: Changed to `usleep`.

File: src/lib/core/crash.c (hunk 6 above)
Comment (drewdzzz) [reply src/lib/core/crash.c:517]: > I think that crash_collect should be safe to call from any thread.
From any thread with initialized `cord` (at least, it uses `fiber()` macro for backtraces), so I changed condition `cord_is_main()` to `(cord() != NULL)`.

File: test/unit/tt_sigaction.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (locker) [reply test/unit/tt_sigaction.c]: Still, why not use `thread_sleep` instead of

```C
	double start = clock_monotonic();
	while (clock_monotonic() - start < TEST_LEN)
		usleep(USLEEP_INTERVAL);
```

?

`thread_sleep` restarts `nanosleep` if it receives a signal so the loop wouldn't be necessary.

File: src/lib/core/crash.c (hunk 6 above)
Comment (locker) [reply src/lib/core/crash.c:517]: AFAICS `backtace_collect()` doesn't use `fiber` if it equals self. I think that we should have `backtrace_collect_fiber(bt, fiber)` and `backtrace_collect(bt)`. The latter shouldn't depend on `fiber()` or `cord()`.

Anyway, the comment to the commit is stale.

File: test/unit/tt_sigaction.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (drewdzzz) [reply test/unit/tt_sigaction.c]: > thread_sleep restarts nanosleep
I didn't know about it. Changed to `thread_sleep`.

File: src/lib/core/crash.c (hunk 6 above)
Comment (drewdzzz) [reply src/lib/core/crash.c:517]: https://github.com/tarantool/tarantool/blob/f21f8e903a53b7c9ed11b689d4f8a10f50639003/src/lib/core/crash.c#L215-L220
`crash_collect()` uses `fiber()` as an argument for `backtace_collect()`. If `cord` is not initialized, `fiber()` macro will dereference a NULL pointer.

Comment (drewdzzz) [reply src/lib/core/crash.c:517]: > Anyway, the comment to the commit is stale.

What an inattention! Fixed it.

Comment (locker) [reply src/lib/core/crash.c:517]: `backtrace_collect()` implementation doesn't use the fiber if it equals `fiber()`.

File: test/unit/tt_sigaction.c [hunk 7]
```diff
@@ -0,0 +1,87 @@
...
+#define USLEEP_INTERVAL 1e5
+
+static pthread_t main_thread;
+
+static atomic_ullong false_handle_cnt;
+
+static void *
+thread_f(void *arg)
+{
+	double start = clock_monotonic();
```
Comment (locker) [inline test/unit/tt_sigaction.c:27]: `start` is never used.

File: src/lib/core/crash.c (hunk 6 above)
Comment (drewdzzz) [reply src/lib/core/crash.c:517]: Dereferencing `NULL` is UB. Even if it is not used later.

Comment (locker) [reply src/lib/core/crash.c:517]: Please read again what I wrote [here](https://github.com/tarantool/tarantool/pull/7431#discussion_r927569882) and think.

File: test/unit/tt_sigaction.c (hunk 7 above)
Comment (drewdzzz) [reply test/unit/tt_sigaction.c]: Removed it.

File: src/lib/core/crash.c (hunk 6 above)
Comment (drewdzzz) [reply src/lib/core/crash.c]: Sorry, I somehow missed that part. What if we just allow to pass `NULL` as fiber argument, and guarantee that module `fiber` won't be used in `backtrace_collect` if `NULL` is passed? (That's what I've done now).

Comment (locker) [reply src/lib/core/crash.c]: Sounds good to me.

File: src/lib/core/backtrace.c [hunk 8]
```diff
@@ -98,6 +98,8 @@ collect_current_stack(struct backtrace *bt, void *stack)
 /*
  * Restore target fiber context (if needed) and call `collect_current_stack`
  * over it.
+ * It is guaranteed that if NULL passed as fiber argument, fiber
+ * module will not be used.
```
Comment (locker) [inline src/lib/core/backtrace.c:102]: Nit: please also update the comment to the function declaration in the header.

**Review by locker — CHANGES_REQUESTED** [review]
To link an issue to a PR you should add `Closes #XXXX` or `Fixes #XXXX` to the PR description (I updated it for you). See one last nit pick.

File: src/lib/core/backtrace.c (hunk 8 above)
Comment (drewdzzz) [reply src/lib/core/backtrace.c:102]: Done

**Review by locker — APPROVED** [review]

**Review by locker — CHANGES_REQUESTED** [review]
The patch fails to build on some platforms. Please fix.

```
/build/usr/src/debug/tarantool-2.11.0~entrypoint.281.dev/test/unit/tt_sigaction.c:8:23: fatal error: stdatomic.h: No such file or directory
 #include "stdatomic.h"
```

https://github.com/tarantool/tarantool/runs/7519210930?check_suite_focus=true

```
In file included from /build/tarantool-2.11.0~entrypoint.281.dev/test/unit/tt_sigaction.c:8:0:
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:40:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic _Bool atomic_bool;
 ^~~~~~~
```

https://github.com/tarantool/tarantool/runs/7519211829?check_suite_focus=true

**Comment by drewdzzz** [comment]
Changed `stdatomic` to `pmatomic`.

**Review by locker — APPROVED** [review]
