### PR TITLE
config/schema: deep set/delete for `any` type

### LINKED ISSUE #10204: config/schema: :set() can't assign/delete a field inside 'any' type
For example, we have a logger module/role/app and a configuration for it. The configuration should contain a field without a strict structure: for example, an initial diagnostics context to add into log entries.

```lua
local yaml = require('yaml')
local schema = require('experimental.config.utils.schema')

local logger_config_schema = schema.new('logger_config', schema.record({
    level = schema.enum({
        'fatal',
        'syserror',
        'error',
        'crit',
        'warn',
        'info',
        'verbose',
        'debug',
    }, {
        default = 'info',
    }), 
    -- Initial context (MDC).
    context = schema.map({
        key = schema.scalar({type = 'string'}),
        value = schema.scalar({type = 'any'}),  -- !!
    }), 
}))

local logger_config = logger_config_schema:apply_default({})

-- It is OK.
logger_config_schema:set(logger_config, 'context.hostname', box.info.hostname)

-- It raises an error.
logger_config_schema:set(logger_config, 'context.process.pid', box.info.pid)
-- error: [logger_config] context.process: Attempt to index a scalar value of type any by field "pid"

print(yaml.encode(logger_config))
```

It seems convenient to support assigning/deleting a field inside an `any` type.

### PR DESCRIPTION
**Pull request by mandesero**
This patch adds support for assigning and deleting nested fields inside schema scalar nodes of the `any` type using deep paths.

Previously, attempts to set a nested field past an `any` scalar resulted in a type error. Now such nodes are treated as schemaless containers, and intermediate tables are created automatically when needed.

Closes #10204

### CODE REVIEW

File: src/box/lua/config/utils/schema.lua [hunk 1]
```diff
@@ -830,6 +830,45 @@ local function get_schemaless(data, ctx)
...
+    if new_field_value == nil then
+        if data ~= nil then
+            data[requested_field] = nil
+        end
+    else
+        if data == nil then
+            data = {}
+        end
+        data[requested_field] = new_field_value
+    end
```
Comment (grafin) [inline src/box/lua/config/utils/schema.lua]: nit: this logic doesn't seem obvious (took me a minute to understand), maybe something like the following code will be better?

```lua
if new_field_value == nil and data == nil then
    return data
end

if data == nil then
    data = {}
end

data[requested_field] = new_field_value

return data
```

Comment (mandesero) [reply src/box/lua/config/utils/schema.lua]: Thanks!

I replaced it with (and made it a bit shorter)
```lua
    if new_field_value == nil and data == nil then
        return data
    end

    data = data or {}
    data[requested_field] = new_field_value

    return data
```

File: src/box/lua/config/utils/schema.lua [hunk 2]
```diff
@@ -973,7 +1008,9 @@ local function set_impl(schema, data, rhs, ctx)
     local requested_field = ctx.journey[1]
     assert(requested_field ~= nil)
 
-    if is_scalar(schema) then
+    if is_scalar(schema) and schema.type == 'any' then
```
Comment (georgiy-belyanin) [inline src/box/lua/config/utils/schema.lua]: Minor: this can be simplified.

```suggestion
    if schema.type == 'any' then
```

Probably, you might consider introducing `is_any()` or something separately.

File: src/box/lua/config/utils/schema.lua [hunk 3]
```diff
@@ -830,6 +830,41 @@ local function get_schemaless(data, ctx)
...
+    if data ~= nil and type(data) ~= 'table' then
+        walkthrough_error(ctx, 'Attempt to index a non-table value ' ..
+            '(%s) by field %q', type(data), requested_field)
+    end
+
+    walkthrough_enter(ctx, requested_field)
+
+    local field_value
+    if data ~= nil then
+        field_value = data[requested_field]
```
Comment (georgiy-belyanin) [inline src/box/lua/config/utils/schema.lua:852]: Why don't we need `walkthrough_assert_table()` here?

File: test/config-luatest/schema_test.lua [hunk 4]
```diff
@@ -1545,6 +1545,24 @@ g.test_set_record_field_any = function()
...
+    s:set(data, 'foo.bar.baz', nil)
+    t.assert_equals(data, {foo = {bar = {giz = 'keep'}}})
+
+    -- Indexing a non-table value inside 'any' is still forbidden.
+    local exp_err_msg = '[myschema] foo.bar: Attempt to index a non-table ' ..
+        'value (string) by field "baz"'
+    local data = {foo = {bar = 'mydata'}}
+    t.assert_error_msg_equals(exp_err_msg, function()
+        s:set(data, 'foo.bar.baz', 'mydata')
+    end)
```
Comment (georgiy-belyanin) [inline test/config-luatest/schema_test.lua:1576]: Could you also test using `box.NULL` as value to set?

File: src/box/lua/config/utils/schema.lua (hunk 3 above)
Comment (mandesero) [reply src/box/lua/config/utils/schema.lua:852]: There is no schema node to pass to `walkthrough_assert_table(ctx, schema, data)`, so we perform a direct type check here. This logic is also similar to `get_schemaless`.
https://github.com/mandesero/tarantool/blob/c32b82582ec18fdbe5c0120ab0f9f02ab1952a92/src/box/lua/config/utils/schema.lua#L819-L823

File: test/config-luatest/schema_test.lua (hunk 4 above)
Comment (mandesero) [reply test/config-luatest/schema_test.lua:1576]: Added.

File: src/box/lua/config/utils/schema.lua (hunk 2 above)
Comment (mandesero) [reply src/box/lua/config/utils/schema.lua]: Done.

File: test/config-luatest/schema_test.lua (hunk 4 above)
Comment (georgiy-belyanin) [reply test/config-luatest/schema_test.lua:1576]: Thank you!
