### PR TITLE
net.box: fix hang in graceful shutdown protocol

### LINKED ISSUE #7225: Timeout waiting for graceful shutdown if net.box connection was partially garbage collected
Reproduced with Tarantool 2.11.0-entrypoint-93-g37d5ac5ac9bd.
Tarantool 2.10.0 is affected as well.
The bug was found while working on https://github.com/tarantool/tarantool/issues/6820.

How graceful shutdown works:
1. Server sends `box.shutdown` event to all clients that subscribed to it.
2. Upon receiving the event, the clients should close connections.
3. Once all connections are closed or a timeout occurs (see `box.ctl.set_on_shutdown_timeout`), the server exits.

If Lua garbage collector collected `callback`, `remote`, but hasn't collected `weak_callback` and `transport` yet, the net.box connection will not react to the `box.shutdown` event, because it's processed by `callback`:

https://github.com/tarantool/tarantool/blob/37d5ac5ac9bdd4db55300b5b31060077edb9f121/src/box/lua/net_box.lua#L380-L398

As a result the socket won't be closed, and the server will exit only on timeout.

To reproduce the issue, apply the following patch

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 8819327274d2..d4198d016255 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -94,7 +94,7 @@ static char status[64] = "unknown";
 /** box.stat rmean */
 struct rmean *rmean_box;
 
-double on_shutdown_trigger_timeout = 3.0;
+double on_shutdown_trigger_timeout = 9000.0;
 
 double txn_timeout_default;
 ```

and run `box-tap/session.test.lua` - it'll hang waiting for the server to stop.

If you collect garbage before trying to stop the server, the test'll pass:

```diff
diff --git a/test/box-tap/session.test.lua b/test/box-tap/session.test.lua
index 49ef1006e24a..c98d0329e78e 100755
--- a/test/box-tap/session.test.lua
+++ b/test/box-tap/session.test.lua
@@ -210,6 +210,7 @@ conn:close()
 box.schema.user.revoke('guest', 'execute', 'function', 'f1')
 box.schema.user.revoke('guest', 'execute', 'function', 'f2')
 
+collectgarbage('collect')
 inspector:cmd('stop server session with cleanup=1')
 session = nil
 os.exit(test:check() == true and 0 or -1)
```

### PR DESCRIPTION
**Pull request by locker**
The graceful shutdown protocol works as follows:
1. The server sends a shutdown request (the box.shutdown event) to all its clients that subscribed to it.
2. Upon receiving a shutdown request, a client is supposed to close its connection.
3. The server waits for all clients subscribed to box.shutdown event to exit.
4. The server exits.

In net.box, the box.shutdown event is processed by `remote._callback`. The problem is it may occur that `remote._callback` is garbage collected while the `remote` object isn't. If this happens, the shutdown request will never get processed, and the server won't exit until the `remote` object is garbage collected, which may take forever.

Let's fix this issue by breaking the worker loop if we see that the callback was garbage collected.

Closes #7225

### CODE REVIEW

File: src/box/lua/net_box.lua [hunk 1]
```diff
@@ -389,6 +389,13 @@ local function new_sm(uri, opts)
     local function weak_callback(...)
         local callback = weak_refs.callback
         if callback then return callback(...) end
+        -- The callback is responsible for handling graceful shutdown.
+        -- If it's garbage collected, the connection won't be closed on
+        -- receiving 'box.shutdown' event and so the server won't exit
+        -- until the connection object is garbage collected, which may
+        -- take forever. To avoid that, let's break the worker loop if
+        -- we see that the callback is unavailable.
+        error('garbage collected')
```
Comment (Gerold103) [inline src/box/lua/net_box.lua:398]: That does not really look like an error. The owner was garbage collected like it is supposed to, correct? If you throw an error here, then you will get it in the logs which might be confusing and even look like a bug (some strange message `"garbage collected"` coming from an internal file `net_box.lua`). The logging will happen in `netbox_transport_on_state_change_pcall()`.

I would suggest to find a way to break the loop without raising an error.

File: test/box-luatest/graceful_shutdown_test.lua [hunk 2]
```diff
@@ -506,3 +506,18 @@ g.test_graceful_shutdown_not_supported_by_client = function()
...
+-- Checks that if the net.box callback, which processes box.shutdown event, is
+-- garbage callected while the remote isn't, such partially garbage collected
+-- connection won't block shutdown (gh-7225).
+g.test_net_box_callback_garbage_collected = function()
+    g.server:exec(function()
+        box.ctl.set_on_shutdown_timeout(9000)
+    end)
+    local conn = net.connect(g.server.net_box_uri)
+    t.assert_is_not(conn._callback, nil)
+    conn._callback = nil
```
Comment (Gerold103) [inline test/box-luatest/graceful_shutdown_test.lua:519]: I couldn't understand how is that possible. `conn` is not a weak table. Hence its `_callback` member shouldn't be collected while `conn` has refs. Can you give more details please?

**Review by Gerold103 — COMMENTED** [review]
Thanks for the patch!

File: test/box-luatest/graceful_shutdown_test.lua (hunk 2 above)
Comment (locker) [reply test/box-luatest/graceful_shutdown_test.lua:522]: The Lua garbage collector runs in step when there's memory pressure, and there's no guarantee it'll perform all steps at once. If the `conn` reference is lost, the garbage collector may collect `conn._callback` and stop before collecting `conn._gc_hook`. It doesn't mean it'll never collect it, but it may take indefinitely long if there's no pressure on Lua memory. As a result, the gc method, which closes the underlying socket won't be called and the server will hang. I added a comment to the test.

File: src/box/lua/net_box.lua (hunk 1 above)
Comment (locker) [reply src/box/lua/net_box.lua]: Right. I didn't think about error logging. Replaced with `transport:stop()`. Thanks for catching this.

File: src/box/lua/net_box.lua [hunk 3]
```diff
@@ -386,12 +386,20 @@ local function new_sm(uri, opts)
...
     local function weak_callback(...)
         local callback = weak_refs.callback
         if callback then return callback(...) end
+        -- The callback is responsible for handling graceful shutdown.
+        -- If it's garbage collected, the connection won't be closed on
+        -- receiving 'box.shutdown' event and so the server won't exit
+        -- until the connection object is garbage collected, which may
+        -- take forever. To avoid that, let's break the worker loop if
+        -- we see that the callback is unavailable.
+        transport:stop()
```
Comment (Gerold103) [inline src/box/lua/net_box.lua:399]: Are you sure you can ref the transport variable inside of `weak_callback`? I made this test:
```Lua
box.cfg{listen = 3313}
box.schema.user.grant('guest', 'super')
net = require('net.box')
c = net.connect(box.cfg.listen)
c:eval('return 100')
c:close()
c = nil
collectgarbage()
collectgarbage()
collectgarbage()
```
and applied this patch:
```Diff
diff --git a/src/box/lua/net_box.c b/src/box/lua/net_box.c
index d79f90fd9..99330aa5f 100644
--- a/src/box/lua/net_box.c
+++ b/src/box/lua/net_box.c
@@ -1727,6 +1727,7 @@ luaT_check_netbox_transport(struct lua_State *L, int idx)
 static int
 luaT_netbox_transport_gc(struct lua_State *L)
 {
+	printf("luaT_netbox_transport_gc\n");
 	struct netbox_transport *transport = luaT_check_netbox_transport(L, 1);
 	netbox_transport_destroy(transport);
 	return 0;
```
Before your commit I saw the message printed, but now I don't. Can it be a leak? Would it help if the weak callback would return true when has callback and false when it doesn't, and the transport in the latter case would stop self?

File: test/box-luatest/graceful_shutdown_test.lua (hunk 2 above)
Comment (Gerold103) [reply test/box-luatest/graceful_shutdown_test.lua:522]: Thanks for the explanation!

**Review by Gerold103 — COMMENTED** [review]
Thanks for the fixes!

File: test/box-luatest/graceful_shutdown_test.lua [hunk 4]
```diff
@@ -506,3 +506,21 @@ g.test_graceful_shutdown_not_supported_by_client = function()
     t.assert_equals(tostring(err), 'Peer closed')
     conn:close()
 end
+
+-- Checks that if the net.box callback, which processes box.shutdown event, is
+-- garbage callected while the remote isn't, such partially garbage collected
```
Comment (psergee) [inline test/box-luatest/graceful_shutdown_test.lua:511]:
```suggestion
-- garbage collected while the remote isn't, such partially garbage collected
```

File: src/box/lua/net_box.lua (hunk 3 above)
Comment (locker) [reply src/box/lua/net_box.lua]: You're totally right - the patch would result in a leak. Thanks for catching this. That's unfortunate that we didn't have a test case for this.

I don't like adding a return value to the callback, because that would complicate the code quite a bit (the callback is invoked from multiple places in `net_box.c`). Instead I turned `transport` into a weak reference. I also added a test case that ensures that both `transport` and `callback` are garbage collected.

File: test/box-luatest/graceful_shutdown_test.lua (hunk 4 above)
Comment (locker) [reply test/box-luatest/graceful_shutdown_test.lua]: A typo indeed. Fixed, thanks.

File: test/box-luatest/net_box_test.lua [hunk 5]
```diff
@@ -314,3 +315,24 @@ g.test_box_error = function()
...
+        callback = c._callback,
+        transport = c._transport,
+    }, {__mode = 'v'})
+    t.assert(weak_refs.conn)
+    t.assert(weak_refs.callback)
+    t.assert(weak_refs.transport)
+    c = nil -- luacheck: no unused
+    fiber.sleep(0)
+    collectgarbage('collect')
+    fiber.sleep(0)
```
Comment (Gerold103) [inline test/box-luatest/net_box_test.lua:333]: Nit: `fiber.sleep(0) == fiber.yield()` in Lua.

**Review by Gerold103 — APPROVED** [review]
Thanks for quickly fixing the comments, looks good now!

I only hope that `weak_refs.transport` won't also be collected together with `weak_refs.callback` so you won't be able to break the loop. Shouldn't be possible since the callback is called by the transport. Hence the latter can't possibly be collected yet.

File: test/box-luatest/net_box_test.lua (hunk 5 above)
Comment (locker) [reply test/box-luatest/net_box_test.lua]: Fixed.

**Comment by locker** [comment]
Cherry-picked to 2.10.
