### PR TITLE
replication: fix wrong assumption in `box.ctl.make_bootstrap_leader`

### LINKED ISSUE #11704: replication: box.ctl.make_bootstrap_leader() fails with assertion
Tarantool version: 3.5.0-entrypoint-132-g8c7cfb1cd0

## Reproduce files

`i.lua` (same as in #11703 except one line):

```lua
#!/usr/bin/env tarantool

local fio = require('fio')
local fiber = require('fiber')

local port = tonumber(arg[1])
assert(port ~= nil, port)
fio.mkdir(port)
if port == 3301 then
    fiber.new(function()
        -- fiber.sleep(2) -- uncomment to easier reproduce gh-11703
        box.ctl.make_bootstrap_leader({graceful = true})
        while box.info.status ~= 'running' do
            fiber.sleep(0.001)
        end
        box.ctl.promote()
        box.cfg({read_only = false})
        box.ctl.wait_rw()
        box.schema.user.grant('guest', 'super')
    end)
end
box.cfg({
    read_only = true,
    work_dir = tostring(port),
    listen = port,
    replication = {3301, 3302, 3303},
    election_mode = 'manual',
    bootstrap_strategy = 'supervised',
})
```

`Procfile` (same as in #11703):

```procfile
i-3301: ./src/tarantool i.lua 3301
i-3302: ./src/tarantool i.lua 3302
i-3303: ./src/tarantool i.lua 3303
```

## Reproduce steps

```sh
$ rm -r 3301 3302 3303
$ honcho start
<..wait for gh-11703 crash or send SIGINT manually..>
$ honcho start
```

## Result

```
tarantool: ./src/box/box.cc:2435: int box_make_bootstrap_leader(bool): Assertion `bootstrap_strategy != BOOTSTRAP_STRATEGY_INVALID' failed.
```

The relevant code (the assertion is on the 2435 line):

https://github.com/tarantool/tarantool/blob/8c7cfb1cd0b3f5ce1d5b181403f68f7aaf657d9a/src/box/box.cc#L2429-L2448

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
This patch fixes a wrong assumption about bootstrap during recovery in `box.ctl.make_bootstrap_leader`.

Closes #11704

### CODE REVIEW

File: src/box/box.cc [hunk 1]
```diff
@@ -2429,10 +2429,8 @@ box_make_bootstrap_leader_nongraceful(void)
 int
 box_make_bootstrap_leader(bool graceful)
 {
-	/* Bootstrap strategy is read by the time instance uuid is known. */
```
Comment (sergepetrenko) [inline src/box/box.cc:2439]: Please leave a comment about `bootstrap_strategy_invalid` meaning. That it means we haven't read the config yet.

File: test/replication-luatest/bootstrap_strategy_test.lua [hunk 2]
```diff
@@ -1437,3 +1437,52 @@ g_graceful_supervised.test_after_box_cfg_read_only = function(cg)
...
+
+-- Check that `box.ctl.make_bootstrap_leader` is handled correctly during
+-- recovery.
+g_make_bootstrap_leader_during_recovery.test_error = function(cg)
+    cg.box_cfg.bootstrap_strategy = 'supervised'
+    cg.server2:restart({box_cfg = cg.box_cfg}, {wait_until_ready = false})
+    local run_before_cfg = [[
+        rawset(_G, "make_bootstrap_leader_ok", false)
+        require('fiber').new(function()
+            local ok = pcall(box.ctl.make_bootstrap_leader)
```
Comment (sergepetrenko) [inline test/replication-luatest/bootstrap_strategy_test.lua:1479]: AFAIU this code will get executed on the first ever yield of `box.cfg()`. This must happen in `cord_costart` inside `wal_init`. I don't see any other places. Let's please mention `wal_init` in the commit message and also drop a line or two here, explaining why this test works as expected.

**Review by sergepetrenko — COMMENTED** [review]
Thanks for the patch!

File: src/box/box.cc (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/box.cc:2439]: Done.

File: test/replication-luatest/bootstrap_strategy_test.lua (hunk 2 above)
Comment (CuriousGeorgiy) [reply test/replication-luatest/bootstrap_strategy_test.lua:1479]: Done. It actually yields because of `iproto_do_cfg`.

Comment (sergepetrenko) [reply test/replication-luatest/bootstrap_strategy_test.lua:1479]: Thanks!
