### PR TITLE
replication: say warning if before_replace trigger changed replica_id

### LINKED ISSUE #7846: `_cluster:before_replace()` crash if replica ID is altered
```Lua
--
-- Instance 1
--
-- Step 1
--
box.cfg{
    listen = 3313,
}
box.schema.user.grant('guest', 'super')
box.space._cluster:before_replace(function(old, new)
    return new:update({{'+', 1, 10}})
end)

--
-- Instance 2
--
-- Step 2
--
box.cfg{
    listen = 3314,
    replication = 3313,
}
```
Result:
```
tarantool> Assertion failed: (replica_by_uuid(uuid)->id == id), function box_register_replica, file /Users/gerold/Work/Repositories/tarantool/src/box/box.cc, line 3124.
Process 37607 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x00000001001666ec tarantool`box_register_replica(id=2, uuid=0x000000010b8ffac0) at box.cc:3124:2
   3121		if (boxk(IPROTO_INSERT, BOX_CLUSTER_ID, "[%u%s]",
   3122			 (unsigned) id, tt_uuid_str(uuid)) != 0)
   3123			diag_raise();
-> 3124		assert(replica_by_uuid(uuid)->id == id);
   3125	}
   3126	
   3127	/**
Target 0: (tarantool) stopped.
```
Shouldn't crash. Just get the resulting replica ID from the replica object and that is it. Otherwise it might make sense to ban certain triggers on system spaces, like `before_replace()`, which allow to change data.

### PR DESCRIPTION
**Pull request by drewdzzz**
Currently, there is an assertion that checks if replica_id haven't been changed after it's registration. Let's replace this assertion with warning message about id being altered - new id will be used for affected replica.

Closes #7846

### CODE REVIEW

**Review by Gerold103 — CHANGES_REQUESTED** [review]
It still crashes if I do this:
```Lua
--
-- Instance 1
--
-- Step 1
--
box.cfg{
    listen = 3313,
}
box.schema.user.grant('guest', 'super')
box.space._cluster:before_replace(function(old, new)
    return nil
end)

--
-- Instance 2
--
-- Step 2
--
box.cfg{
    listen = 3314,
    replication = 3313,
}
```

Also the ticket mentions a more general problem with the triggers. They can break other system spaces too. For example, this is what happens in `_space`:
```Lua
box.cfg{}
box.space._space:before_replace(function(old, new)
    return nil
end)
box.schema.create_space('test')
```
```
tarantool> box.schema.create_space('test')
---
- null
- created
...
```
AFAIU this function is not supposed to return `null` ever. And what is `"created"`?

**Comment by drewdzzz** [comment]
I think that we should merge this patch and create a new issue describing a global problem.
You suggested to ban `before_replace` trigger on system spaces, but it is a bad option - AFAIK advanced users of tarantool uses this "feature". So teamP should decide how to deal with this problem.

**Comment by unera** [comment]
I think that we should merge the PR and check the other system space triggers' problems separately.

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Please, look at my previous comment again. `_cluster` still crashes on `before_replace` trigger even after your patch. Ok, you can move the other spaces into another ticket, but I suggest to fix this particular space properly here.

**Comment by drewdzzz** [comment]
OK, I will fix all the problems with space `_cluster` that you describe, but I will not investigate them in the scope of the current problem. Please let me know if you find more problems.

**Comment by Gerold103** [comment]
There is just one more bug with `_cluster`. It is already investigated - I gave you the second reproducer. The reproducer is different from the old one literally in a single Lua line. And the crash is in the same line in box.cc as the crash in the ticket. Do I really have to make a new ticket for each tiny bug in a single line of C++ code?

File: test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua [hunk 1]
```diff
@@ -0,0 +1,57 @@
+local server = require('test.luatest_helpers.server')
+local t = require('luatest')
+local urilib = require('uri')
+local fiber = require('fiber')
+
+local g = t.group('before_replace alter')
+
+g.test_replica_id_inc = function()
```
Comment (Gerold103) [inline test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua:8]: This and `test_replica_id_nullify` are almost identical. You could make them one function which would take the trigger's full body or a flag whether it should delete or replace the ID. And then call that one function 2 times. Would be ~x2 times shorter.

File: test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+    local server2 = server:new{
+        alias = 'server2',
+        box_cfg = {replication = uri.unix}
+    }
+    -- We cannot wait until ready because server2 will not be started at all,
+    -- so let's just sleep here.
+    server2:start({wait_for_readiness=false})
+    fiber.sleep(1)
+
+    local msg = server1:grep_log('Replica ID is changed by a trigger', 1024)
```
Comment (Gerold103) [inline test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua:53]: Relying on 1 second being enough doesn't look good - 1) sometimes it won't be enough for sure, 2) most of the time it is too long. I would rather replace it with `t.helpers.retrying()` where you would wait on the log entry appearance. Also I am afraid that `server2:cleanup()` if done before the server is terminated might leave the server running. Wouldn't `:drop()` work?

**Review by Gerold103 — APPROVED** [review]
Thanks for the fixes! Looks fine except some stuff in the tests. You can proceed to a second review anyway.

File: test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua (hunk 2 above)
Comment (drewdzzz) [reply test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua:53]: `drop()` does not work because `stop()` method, which is called before `cleanup()`, throws an error, because the server was not started. So `cleanup()` is the best option I've found.

File: test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua (hunk 1 above)
Comment (drewdzzz) [reply test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua]: Done

File: test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua (hunk 2 above)
Comment (drewdzzz) [reply test/box-luatest/gh_7846_crash_on_replica_id_alter_test.lua]: Replaced sleep with retry

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.10.
