### PR TITLE
applier: add timeout to greeting read

### LINKED ISSUE #7204: No error reason reported if relay doesn't send greeting
The bug was reproduced with 2.11.0-entrypoint-83-g2e067472fb13.
All supported Tarantool versions are affected.
Related issue: https://github.com/tarantool/tarantool-ee/issues/137

Tarantool usually prints an error reason if it fails to connect to the master. For example, try running the following script when nobody listens on 3301:

```Lua
box.cfg{
    replication = 3301,
    replication_timeout = 1,
    replication_connect_timeout = 5,
}
```

In a jiffy you'll see an error:

```
2022-05-27 14:08:16.634 [1285226] main/103/test.lua I> connecting to 1 replicas
2022-05-27 14:08:16.634 [1285226] main/110/applier/ I> can't connect to master
2022-05-27 14:08:16.634 [1285226] main/110/applier/ coio.c:83 E> SocketError: connect, called on fd 19, aka 127.0.0.1:60918: Connection refused
2022-05-27 14:08:16.634 [1285226] main/110/applier/ I> will retry every 1.00 second
2022-05-27 14:08:21.634 [1285226] main/103/test.lua C> failed to connect to 1 out of 1 replicas
2022-05-27 14:08:21.635 [1285226] main/103/test.lua replication.cc:833 E> ER_CFG: Incorrect value for option 'replication': failed to connect to one or more replicas
2022-05-27 14:08:21.635 [1285226] main/103/test.lua F> can't initialize storage: Incorrect value for option 'replication': failed to connect to one or more replicas
```

However, if somebody listens on the replication port, but never sends a greeting, no error reason is reported. The instance just says that the replication configuration is incorrect without specifying what went wrong.

```Lua
local s = require('socket').tcp_server('localhost', 3301, {
    handler = function() require('fiber').sleep(9000) end
})
box.cfg{
    replication = 3301,
    replication_timeout = 1,
    replication_connect_timeout = 5,
}
```

```
2022-05-27 14:07:33.023 [1285212] main/103/test.lua I> connecting to 1 replicas
2022-05-27 14:07:38.024 [1285212] main/103/test.lua C> failed to connect to 1 out of 1 replicas
2022-05-27 14:07:38.024 [1285212] main/103/test.lua replication.cc:833 E> ER_CFG: Incorrect value for option 'replication': failed to connect to one or more replicas
2022-05-27 14:07:38.024 [1285212] main/103/test.lua F> can't initialize storage: Incorrect value for option 'replication': failed to connect to one or more replicas
```

This is confusing. What's worse this results in a hang trying to disable encryption on a replicated connection, as described in https://github.com/tarantool/tarantool-ee/issues/137#issuecomment-1138657595:
1. First, SSL is enabled both on the master and the replica.
2. Then SSL is disabled on the replica by resetting `box.cfg.replication`. Since the server still uses SSL, the replica hangs trying to read the greeting (SSL expects a client to send first).
3. Now the master disables SSL, but this doesn't close or reconfigure open connections so the replica continues to wait for the greeting on an encrypted connection, which it never gets.

To avoid this issue and report a proper error, a replica should abort read if the master doesn't send a greeting.

### PR DESCRIPTION
**Pull request by locker**
A Tarantool server is supposed to send a greeting message right after accepting a new client so the first thing an applier does after connecting to the master is reads the greeting. It does this without timeouts. The problem is that if by mistake we connect to a wrong instance, which doesn't send anything to clients, the applier will hang forever (until the remote closes the socket), without logging any errors.

This may happen even with a valid Tarantool instance - if SSL encryption is enabled on the master, but not on the client, because the SSL protocol assumes that the client initiates a connection by writing to the socket first (before the server).

Let's add a timeout to the operation reading the greeting. The timeout is set to replication_disconnect_timeout(), after which a connection is broken if the master doesn't send heartbeats for that long. Note, we don't add a timeout to other read/write operations issued to initiate a replication connection, because if we received a greeting and it's valid, then the master is likely to be fine.

Closes #7204
Needed for https://github.com/tarantool/tarantool-ee/issues/137

### CODE REVIEW

File: test/replication-luatest/gh_7204_greeting_timeout_test.lua [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+g.before_all(function(g)
+    g.master_uri = server.build_instance_uri('master')
+    g.master = server:new({
+        alias = 'master',
+        box_cfg = {
+            replication_timeout = 0.1,
+        },
+    })
+    g.master:start()
```
Comment (Gerold103) [inline test/replication-luatest/gh_7204_greeting_timeout_test.lua:16]: You probably don't need 2 instances. You can start one and right away try to set its replication to the URI where the fake server listens, then wait for the errors.

**Review by Gerold103 — APPROVED** [review]
Thanks for the quick fix!

File: test/replication-luatest/gh_7204_greeting_timeout_test.lua (hunk 1 above)
Comment (locker) [reply test/replication-luatest/gh_7204_greeting_timeout_test.lua]: You're right. I removed the master instance. Now the test looks much simpler:

<details><summary>Test</summary>

```Lua
local fiber = require('fiber')
local server = require('test.luatest_helpers.server')
local socket = require('socket')
local t = require('luatest')

local g = t.group()

g.before_all(function(g)
    g.server = server:new({
        alias = 'master',
        box_cfg = {
            replication_timeout = 0.1,
            replication_connect_timeout = 0.5,
        },
    })
    g.server:start()
end)

g.after_all(function(g)
    g.server:drop()
end)

g.test_greeting_timeout = function(g)
    local uri = server.build_instance_uri('server')
    local s = socket.tcp_server('unix/', uri, {
        handler = function() fiber.sleep(9000) end
    })
    t.assert(s)
    g.server:exec(function(uri)
        box.cfg{replication = uri}
    end, {uri})
    t.helpers.retrying({}, function()
        t.assert(g.server:grep_log('timed out'))
        t.assert(g.server:grep_log('will retry'))
    end)
    s:close()
end
```

</details>

**Comment by locker** [comment]
Cherry-picked to 2.10.
