### PR TITLE
mvcc: track nothing-found range read

### LINKED ISSUE #7025: MVCC fails to track empty range select
Usually MVCC collects read set of transaction, including range selects, preventing phantom reads. But in the case below it does not happen:
```lua
        local s = box.schema.space.create('test')
        s:create_index('primary', {parts = {{1, 'uint'}, {2, 'uint'}}})

        local txn_proxy = require("test.box.lua.txn_proxy")
        local tx = txn_proxy.new()
        s:replace{1, 0}
        s:replace{3, 0}

        tx:begin()
        tx('box.space.test:select{2}') -- {} ok
        s:replace{2, 0}
        tx('box.space.test:select{2}') -- got {2, 0} but must be {} or...
        tx:commit() -- ..or that must throw an error, but it completes with success.
```

### PR DESCRIPTION
**Pull request by alyapunov**
MVCC must track a read set of transaction, including cases when
the select returns an empty result. In this case MVCC has two
options: to store a point key if the select has a full key or
to store a gap otherwise.

By a mistake the second variant was not implemented. Fix it now.

Closes #7025

### CODE REVIEW

File: test/box-luatest/gh_7025_mvcc_dirty_range_test.lua [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+
+g.after_each(function()
+    g.server:exec(function()
+        if box.space.test then
+            box.space.test:drop()
+        end
+    end)
+end)
+
+g.test_empty_range_select_left = function()
```
Comment (drewdzzz) [inline test/box-luatest/gh_7025_mvcc_dirty_range_test.lua:33]: Please, use different names for different tests: now only one of the three tests will run.

File: src/box/memtx_tree.cc [hunk 2]
```diff
@@ -686,9 +686,20 @@ tree_iterator_start_raw(struct iterator *iterator, struct tuple **ret)
...
+		 */
+		if (key_is_full) {
 			memtx_tx_track_point(txn, space, idx, it->key_data.key);
+			return 0;
+		}
+		/* it->tree_iterator is positioned on successor of a key! */
+		struct memtx_tree_data<USE_HINT> *res =
+			memtx_tree_iterator_get_elem(tree, &it->tree_iterator);
+		struct tuple *successor = res == NULL ? NULL : res->tuple;
+		memtx_tx_track_gap(in_txn(), space, idx, successor, type,
```
Comment (drewdzzz) [inline src/box/memtx_tree.cc:701]: Nit: you can use variable `txn` instead of `in_txn()` for code uniformity.

File: test/box-luatest/gh_7025_mvcc_dirty_range_test.lua [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+        local replace_req = 'box.space.test:replace{' .. strkey .. ', 1}'
+        t.assert_equals(tx(select_req), {{}})
+        s:replace{key, 0}
+        t.assert_equals(tx(select_req), {{}})
+        t.assert_equals(tx(replace_req), {{key, 1}})
+        t.assert_equals(tx(select_req), {{{key, 1}}})
+        t.assert_equals(tx:commit(),
+            {{error = "Transaction has been aborted by conflict"}})
+
+        t.assert_equals(s:select{}, {{1, 0}, {2, 0}, {3, 0}})
```
Comment (drewdzzz) [inline test/box-luatest/gh_7025_mvcc_dirty_range_test.lua:56]: Nit: the same code is encountered three times. Maybe it's better to write one test with loop?

**Review by drewdzzz — CHANGES_REQUESTED** [review]

File: test/box-luatest/gh_7025_mvcc_dirty_range_test.lua [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+g.before_each(function()
+    g.server:exec(function()
+        local s = box.schema.space.create('test')
+        s:create_index('primary', {parts = {{1, 'uint'}, {2, 'uint'}}})
+    end)
+end)
+
+g.after_each(function()
+    g.server:exec(function()
+        if box.space.test then
```
Comment (CuriousGeorgiy) [inline test/box-luatest/gh_7025_mvcc_dirty_range_test.lua:27]: Nit: doesn't `box.space.test` always exist?

File: src/box/memtx_tree.cc [hunk 5]
```diff
@@ -686,9 +686,20 @@ tree_iterator_start_raw(struct iterator *iterator, struct tuple **ret)
...
+		if (key_is_full) {
 			memtx_tx_track_point(txn, space, idx, it->key_data.key);
+			return 0;
+		}
+		/* it->tree_iterator is positioned on successor of a key! */
+		struct memtx_tree_data<USE_HINT> *res =
+			memtx_tree_iterator_get_elem(tree, &it->tree_iterator);
+		struct tuple *successor = res == NULL ? NULL : res->tuple;
+		memtx_tx_track_gap(txn, space, idx, successor, type,
+				   it->key_data.key, it->key_data.part_count);
```
Comment (CuriousGeorgiy) [inline src/box/memtx_tree.cc:702]: I don't like this logic duplication:
https://github.com/tarantool/tarantool/blob/a9e30fb365c1643484054aa07038c015383e7faa/src/box/memtx_tree.cc#L706-L715

File: test/box-luatest/gh_7025_mvcc_dirty_range_test.lua [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+        local s = box.space.test
+        local key = 1
+        s:replace{2, 0}
+        s:replace{3, 0}
+
+        local txn_proxy = require("test.box.lua.txn_proxy")
+        local tx = txn_proxy.new()
+
+        tx:begin()
+        local strkey = tostring(key)
```
Comment (CuriousGeorgiy) [inline test/box-luatest/gh_7025_mvcc_dirty_range_test.lua:45]: Nit: AFAIK, this conversion is done automatically by the Lua runtime.
