### PR TITLE
box: rollback txns in WAL queue before in-flight tnxs

### LINKED ISSUE #11179: WAL does not respect rollback order when its queue is full
**Description**

When rollback happens, all the transactions must be rolled back in reverse order of their preparation. And WAL handles it - it sends to TX its queue in reversed order on rollback. However, a problem happens when WAL queue is full and there are some transactions waiting for a space to join the queue - these transactions must be rolled back before ones from WAL queue (and strictly in reversed order), but they are not.

That's a very serious problem that has caused several fuzzing crashes.
The issue definitely causes https://github.com/tarantool/tarantool/issues/10802 and https://github.com/tarantool/tarantool/issues/10082 (the second one can also be triggered by other problems, though).
Potential cause of https://github.com/tarantool/tarantool-ee/issues/999 and https://github.com/tarantool/tarantool/issues/10283.

**Reproducer**

```lua
local fiber = require('fiber')
local os = require('os')
-- Cleanup
os.execute('rm 000*')

-- Start Tarantool with limited WAL queue.
box.cfg{wal_queue_max_size = 1024}

s = box.schema.space.create('test')
s:create_index('pk')

-- Set WAL delay and do a bunch of transactions replacing the same key.
-- Note that some transactions won't enqueue WAL because of the size limitation.
box.error.injection.set('ERRINJ_WAL_DELAY', true)
for i = 1, 1500 do
    fiber.create(function()
        s:replace{1, i}
        -- s:truncate()
    end)
end

-- Inject an error and wait for crash.
box.error.injection.set('ERRINJ_WAL_DELAY', false)
box.error.injection.set('ERRINJ_WAL_WRITE', true)

fiber.sleep(1)
```

Output:
```
index.cc:232 E> ER_TUPLE_FOUND: Duplicate key exists in unique index "pk" in space "test" with old tuple - [1, 1500] and new tuple - [1, 16]
Assertion failed: (0), function memtx_engine_rollback_statement, file memtx_engine.cc, line 696.
```

If you comment out `s:replace{1}` and uncomment `s:truncate()`, you will face another crash:
```
Assertion failed: (old_space_by_id == old_space), function space_cache_replace, file space_cache.c, line 149.
```

### PR DESCRIPTION
**Pull request by nshy**
In case of WAL error we should rollback txns in WAL queue before any in-flight txns (already submitted to WAL thread).

Work around is to disable WAL queue by `box.cfg{wal_queue_max_size = 0}` so that no request can be queued.

Closes #11179

### CODE REVIEW

File: src/box/journal.c [hunk 1]
```diff
@@ -162,6 +162,20 @@ journal_queue_flush(void)
 	fiber_sleep(0);
 }
 
+void
+journal_queue_rollback(void)
+{
+	struct stailq rollback;
+	stailq_cut_tail(&journal_queue.requests, NULL, &rollback);
```
Comment (locker) [inline src/box/journal.c:169]: Better use `stailq_concat()`.

**Review by locker — APPROVED** [review]

File: src/box/journal.c (hunk 1 above)
Comment (nshy) [reply src/box/journal.c:169]: Fixed.

```diff
diff --git a/src/box/journal.c b/src/box/journal.c
index 9815c7db4c..ae6ccfc3fa 100644
--- a/src/box/journal.c
+++ b/src/box/journal.c
@@ -166,7 +166,8 @@ void
 journal_queue_rollback(void)
 {
        struct stailq rollback;
-       stailq_cut_tail(&journal_queue.requests, NULL, &rollback);
+       stailq_create(&rollback);
+       stailq_concat(&rollback, &journal_queue.requests);
        stailq_reverse(&rollback);
        struct journal_entry *req;
        stailq_foreach_entry(req, &rollback, fifo) {
```

File: changelogs/unreleased/gh-11179-wal-queue-rollback.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+## bugfix/box
+
+* Fixed a bug when txns in WAL queue are not rollbacked on WAL error (gh-11179).
```
Comment (xuniq) [inline changelogs/unreleased/gh-11179-wal-queue-rollback.md:3]:
```suggestion
* Fixed a bug when transactions in the WAL queue were not rolled back on WAL error (gh-11179).
```

**Review by xuniq — APPROVED** [review]

File: src/box/journal.h [hunk 3]
```diff
@@ -271,6 +275,7 @@ journal_write_submit(struct journal_entry *entry)
 	journal_queue_on_append(entry);
 	if (current_journal->write_async(current_journal, entry) != 0) {
 		journal_queue_on_complete(entry);
+		journal_queue_rollback();
```
Comment (sergepetrenko) [inline src/box/journal.h:278]: You could factor out common parts of `journal_queue_rollback()` and `journal_queue_wait`, where you roll back entries due to a fiber cancel, into a separate helper.

Up to you.

File: test/box-luatest/gh_11179_wal_queue_rollback_test.lua [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+--
+-- Here we test a different situation. Part of in-flight requests can be
+-- successfully written and part of requests are not. Imagine also in-flight
+-- requests are split into 2 batches. The first has both successful and not
+-- successful and the second has only unsuccessful requests. So when first
+-- batch is returned to TX thread we wakeup fibers in WAL queue. As part of
+-- a batch is failed new fibers from queue will fail with cascade rollback
+-- error. Unfortunately in this case we do not rollback requests in queue in
+-- correct order. Why do we need two batches here? With only one batch we
+-- rollback whole queue before requests from queue will pass to WAL.
```
Comment (sergepetrenko) [inline test/box-luatest/gh_11179_wal_queue_rollback_test.lua:85]: Sorry, I don't understand how this could happen. Could you explain it once again?

**Review by sergepetrenko — COMMENTED** [review]
Thanks! It was a nasty bug.

File: test/box-luatest/gh_11179_wal_queue_rollback_test.lua (hunk 4 above)
Comment (sergepetrenko) [reply test/box-luatest/gh_11179_wal_queue_rollback_test.lua:85]: Thanks! It's more clear now. Let's use this variant.

A few typos:
don not do procceed -> don't proceed
 Waked up fiber -> woken up.
 will be rollbacked -> will be rolled back.

Comment (nshy) [reply test/box-luatest/gh_11179_wal_queue_rollback_test.lua:85]: Fixed

```diff
 -- successfully written and part of requests are not. Imagine also in-flight
 -- requests are split into 2 batches. The first has both successful and not
 -- successful and the second has only unsuccessful requests. So when first
--- batch is returned to TX thread we don not do procceed with rollback yet
+-- batch is returned to TX thread we don't proceed with rollback yet
 -- waiting for the second batch. But we complete the successful part of
--- the batch and thus wakeup journal queue. Waked up fiber will try
+-- the batch and thus wakeup journal queue. Woken up fiber will try
 -- to submit new request to WAL but fail as cascade rollback is in
--- progress. The failed request from journal will be rollbacked and
+-- progress. The failed request from journal will be rolled back and
 -- this is not correct. First we should rollback newer requests form the
 -- journal queue.
 --
```

File: changelogs/unreleased/gh-11179-wal-queue-rollback.md (hunk 2 above)
Comment (nshy) [reply changelogs/unreleased/gh-11179-wal-queue-rollback.md:3]: Fixed.

File: src/box/journal.h (hunk 3 above)
Comment (sergepetrenko) [reply src/box/journal.h:278]: Ok, as you wish.

**Review by sergepetrenko — APPROVED** [review]
Thanks for the fix!
LGTM.
