### PR TITLE
config: fix on_event roles callback config argument

### LINKED ISSUE #10934: config: on_event callback recieves wrong argument for the config
**Bug description**

The `on_event(config, key, value)` callback of a role should receive it's roles config as its first argument. Currently it receives the whole config object instead, which is not the intended behavior.

* OS: Linux
* OS Version: NixOS 24.11 (Vicuna)
* Architecture: amd64

`tarantool -v` output:
```
Tarantool 3.4.0-entrypoint-13-g7731d13d0a
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/boris/dev/github/tarantool/tarantool/build/install -DENABLE_BACKTRACE=TRUE
Compiler: Clang-18.1.8
C_FLAGS:--sysroot=/ -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fprofile-arcs -ftest-coverage -fsanitize=address -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/boris/dev/github/tarantool/tarantool=. -std=c11 -Wall -Wextra  -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize=object-size,pointer-overflow,null,nonnull-attribute,function -fno-sanitize-recover=undefined -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fprofile-arcs -ftest-coverage -fsanitize=address -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/boris/dev/github/tarantool/tarantool=. -std=c++11 -Wall -Wextra  -fno-omit-frame-pointer -fsanitize=undefined -fno-sanitize=object-size,pointer-overflow,null,nonnull-attribute,function -fno-sanitize-recover=undefined -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Werror -g -ggdb -O0
```

**Steps to reproduce**

Using the following role `one.lua`:
```lua
_G.foo = nil

return {
    validate = function() end,
    apply = function() end,
    stop = function() end,
    on_event = function(config, _, _)
        _G.foo = config
    end,
}
```

With the config `config.yaml`:
```yaml
---
credentials:
  users:
    guest:
      roles:
      - super
groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: []
roles_cfg:
  one: 12345
iproto:
  listen:
  - uri: unix/:./{{ instance_name }}.iproto
roles:
- one
...
```

How to run:
`tarantool --name instance-001 --config config.yaml -i`

**Actual behavior**
```
tarantool> print(_G.foo)
table: 0x41bd6308
```

**Expected behavior**
`_G.foo` should contain the config for the role 'one'

```
tarantool> print(_G.foo)
12345
```

Jira: TNTP-941

### PR DESCRIPTION
**Pull request by grafin**
The config object was passed to the `on_event` callback instead of the corresponding roles config before. Lets fix it, implementing the intended behavior.

NO_DOC=bugfix

Closes #10934

### CODE REVIEW

File: src/box/lua/config/applier/roles.lua [hunk 1]
```diff
@@ -260,14 +260,14 @@ local function post_apply(config)
 
     roles_state.last_loaded = loaded
     roles_state.last_roles_ordered = roles_ordered
-    roles_state.last_config = table.deepcopy(config)
+    roles_state.last_config = table.deepcopy(roles_cfg)
```
Comment (Totktonada) [inline src/box/lua/config/applier/roles.lua:263]: Nit: I would adjust the description at top of the module as well.

Maybe it alsoworth to rename it to `last_roles_cfg` to make it more obvious what is stored here.

Comment (grafin) [reply src/box/lua/config/applier/roles.lua]: I was thinking about the renaming too, but at first decided to keep the changes minimal. Now that you mentioned it - renamed)

File: src/box/lua/config/applier/roles.lua [hunk 2]
```diff
@@ -44,7 +45,7 @@ local call_on_event_callbacks = locked(function(config, key, value)
             log.verbose(('roles.on_event: calling callback for role ' ..
                          '"%s"'):format(role_name))
             local ok, err = pcall(role.on_event,
-                                  config, key, value)
+                                  config[role_name], key, value)
```
Comment (Totktonada) [inline src/box/lua/config/applier/roles.lua:48]: Should we rename the argument here from `config` to `roles_cfg` as well (to use one term for one object)?

**Review by Totktonada — APPROVED** [review]
The fix seems quite straightforward. LGTM.

**Comment by Totktonada** [comment]
@georgiy-belyanin I would appreciate a second glance from you, since in #10865 we both with Borislav overlooked this problem :)

**Review by georgiy-belyanin — APPROVED** [review]
After testing it a bit seems like the scenario described in the Red Chat works as intended. Thank you!

File: src/box/lua/config/applier/roles.lua (hunk 2 above)
Comment (grafin) [reply src/box/lua/config/applier/roles.lua]: done!

**Review by xuniq — APPROVED** [review]
