### PR TITLE
sql: fix assertion during INDEXED BY

### LINKED ISSUE #5976: Assertion with INDEXED BY clause
I have Ubuntu 20.04.
I have Tarantool 2.7.1-186-g365e67c51  pulled from source today.

I execute these requests:
box.execute([[CREATE TABLE j (s1 INT PRIMARY KEY, s2 STRING);]])
box.space.J:create_index('I3',{parts={2, 'string'}})
box.space.J:create_index('I5', {unique = true, parts = {{field = 2, type = 'string'}}})
box.execute([[UPDATE j SET s2 = 'a';]])
box.execute([[INSERT INTO j VALUES (7, 'k');]])
box.execute([[UPDATE j INDEXED BY i5 SET s2 = 'a' WHERE s2 = 'z';]])

Result:
tarantool> box.execute([[UPDATE j INDEXED BY i5 SET s2 = 'a' WHERE s2 = 'z';]])
tarantool: /home/pgulutzan/tarantool-2.7/src/box/sql/vdbe.c:242: allocateCursor: Assertion `iCur>=0 && iCur<p->nCursor' failed.
Aborted (core dumped)

### PR DESCRIPTION
**Pull request by ImeevMA**
This patch fixed the assertion when using INDEXED BY with an index that is at least the third in space.

Closes #5976

NO_DOC=bugfix

### CODE REVIEW

File: src/box/sql/where.c [hunk 1]
```diff
@@ -4606,10 +4606,10 @@ sqlWhereBegin(Parse * pParse,	/* The parser context */
 					assert(wctrlFlags &
 					       WHERE_ONEPASS_DESIRED);
 					while (pJ->def->iid != idx_def->iid) {
-						iIndexCur++;
 						iid++;
 						pJ = pTabItem->space->index[iid];
 					}
+					iIndexCur++;
```
Comment (Gerold103) [inline src/box/sql/where.c:4612]: Why third? Why no crash with a second index? I can't understand it from the code. Tbh, I understand this code at all :) - like, what is `iIndexCur`? What is `iAuxArg`? But I suppose it should be fine if the tests pass.

**Review by Gerold103 — APPROVED** [review]
Thanks for the patch!

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.10.
