### PR TITLE
fiber: fix leak on dead joinable fiber search

### LINKED ISSUE #10187: lsan: memory leak on `fiber.find` of dead joinable fiber
Found in `3.2.0-entrypoint-112-g319357d59` (reported by LSAN on `replication-luatest/gh_6842_qsync_applier_order_test.lua` run)

Repro (will not be reproduced with current set of suppressions though).

```lua
local fiber = require('fiber')
local f = fiber.new(function() end)
f:set_joinable(true)
f:wakeup()
fiber.yield()
x = fiber.find(f:id())
x:join()
os.exit()
```

Produces:
```
*[shiny@mynote tarantool]$ ./build-asan-debug/src/tarantool test.lua

=================================================================
==244453==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x5d783b411e09 in malloc (/home/shiny/dev/tarantool/build-asan-debug/src/tarantool+0x1244e09) (BuildId: ed6592a2a30628f9bb82dded4d7ba4248c288fbd)
    #1 0x5d783c6aa073 in lbox_pushfiber /home/shiny/dev/tarantool/src/lua/fiber.c:121:23
    #2 0x5d783c6a1cc1 in lbox_fiber_find /home/shiny/dev/tarantool/src/lua/fiber.c:723:3
    #3 0x5d783ca7a326 in lj_BC_FUNCC /home/shiny/dev/tarantool/build-asan-debug/third_party/luajit/src/lj_vm.S:811

SUMMARY: AddressSanitizer: 56 byte(s) leaked in 1 allocation(s).
```

The issue is on `f` fiber stop `lbox_fiber_on_stop` is executed and `f->storage.lua.fid_ref` is cleared. So `fiber.find` creates new fiber user data in `lbox_pushfiber`. The latter creates new on stop trigger which will never be triggered and simply dropped when fiber is recyled.

There are related issues:
- fiber user data is leaked
- fiber storage is leaked (if accessed between `yield` and `join` in the example)
- `x ~= f` unexpectedly

### PR DESCRIPTION
**Pull request by nshy**
When fiber is accessed from Lua we create a userdata object and keep the reference for future accesses. The reference is cleared when fiber is stopped. But if fiber is joinable is still can be found with `fiber.find`. In this case we create userdata object again. Unfortunately as fiber is already stopped we fail to clear the reference. The trigger memory that clear the reference is also leaked. As well as fiber storage if it is accessed after fiber is stopped.

Let's add `on_destroy` trigger to fiber and clear the references there.

Note that with current set of LSAN suppressions the trigger memory leak is not reported.

Closes #10187

### CODE REVIEW

File: src/lua/fiber.c [hunk 1]
```diff
@@ -653,6 +658,14 @@ lbox_fiber_storage(struct lua_State *L)
 	struct fiber *f = lbox_checkfiber(L, 1);
 	int storage_ref = f->storage.lua.storage_ref;
 	if (storage_ref == FIBER_LUA_NOREF) {
+		if (f->flags & FIBER_IS_DEAD) {
+			diag_set(IllegalParams, "Fiber is dead");
```
Comment (locker) [inline src/lua/fiber.c:662]: In other places the error message is a bit different: "the fiber is dead". Let's be consistent with that:

https://github.com/tarantool/tarantool/blob/319357d5973d15d08b8eda6a230eada08b710802/src/lua/fiber.c#L592

Also, what about adding a helper function like `lbox_checkfiber` that would raise this error if the fiber exists but is dead?

File: test/app-luatest/fiber_test.lua [hunk 2]
```diff
@@ -57,3 +57,26 @@ g.test_gh_9406_shutdown_with_lingering_fiber_join = function()
     local cmd = string.format('%s -e "%s"', tarantool_bin, script)
     t.assert(os.execute(cmd) == 0)
 end
+
+g.test_gh_10187_no_memory_leak_on_dead_fiber_search = function()
```
Comment (locker) [inline test/app-luatest/fiber_test.lua:61]: I think that this fix does deserve a changelog entry.

File: src/lua/fiber.c (hunk 1 above)
Comment (nshy) [reply src/lua/fiber.c:662]: Discussed f2f and decided to just change message to 'the fiber is dead'. In other cases the fiber does not exist.

Comment (nshy) [reply src/lua/fiber.c:662]:
```diff
diff --git a/src/lua/fiber.c b/src/lua/fiber.c
index 585576b46..c8415649f 100644
--- a/src/lua/fiber.c
+++ b/src/lua/fiber.c
@@ -659,7 +659,7 @@ lbox_fiber_storage(struct lua_State *L)
        int storage_ref = f->storage.lua.storage_ref;
        if (storage_ref == FIBER_LUA_NOREF) {
                if (f->flags & FIBER_IS_DEAD) {
-                       diag_set(IllegalParams, "Fiber is dead");
+                       diag_set(IllegalParams, "the fiber is dead");
                        luaT_error(L);
                }
                struct trigger *on_stop = xmalloc(sizeof(*on_stop));
```

File: test/app-luatest/fiber_test.lua (hunk 2 above)
Comment (nshy) [reply test/app-luatest/fiber_test.lua:61]: Done.

```md
## bugfix/box

* Fixed memory leaks on using dead fiber (gh-10187).
```

File: changelogs/unreleased/gh-10187-fix-memleaks-on-dead-fiber-usage.md [hunk 3]
```diff
@@ -0,0 +1,3 @@
+## bugfix/box
```
Comment (locker) [inline changelogs/unreleased/gh-10187-fix-memleaks-on-dead-fiber-usage.md:1]: Should probably be `bugfix/core`.

**Review by locker — APPROVED** [review]

**Review by lenkis — APPROVED** [review]

File: src/lua/fiber.c [hunk 4]
```diff
@@ -88,21 +88,29 @@ luaL_testcancel(struct lua_State *L)
...
 /**
- * Trigger invoked when the fiber has stopped execution of its
- * current request. Only purpose - delete storage.lua.fid_ref and
- * storage.lua.storage_ref keeping a reference of Lua
- * fiber and fiber.storage objects. Unlike Lua stack,
- * Lua fiber storage may be created not only for fibers born from
- * Lua land. For example, an IProto request may execute a Lua
- * function, which can create the storage. Trigger guarantees,
- * that even for non-Lua fibers the Lua storage is destroyed.
+ * Trigger invoked when the fiber is stopped. Only purpose - delete and
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/lua/fiber.c:91]: Fixed.

File: test/app-luatest/fiber_test.lua [hunk 5]
```diff
@@ -57,3 +57,26 @@ g.test_gh_9406_shutdown_with_lingering_fiber_join = function()
...
+    local f = fiber.new(function() end)
+    f:set_joinable(true)
+    f:wakeup()
+    fiber.yield()
+    local x = fiber.find(f:id())
+    -- Check found fiber object is same as created after fiber become dead.
```
[the remark this answers is not in the document]
Comment (nshy) [reply test/app-luatest/fiber_test.lua:67]: Fixed.

File: changelogs/unreleased/gh-10187-fix-memleaks-on-dead-fiber-usage.md (hunk 3 above)
Comment (nshy) [reply changelogs/unreleased/gh-10187-fix-memleaks-on-dead-fiber-usage.md:1]: Fixed.

**Comment by locker** [comment]
Cherry-picked to 2.11 and 3.1.
