### PR TITLE
core: fix interval MsgPack decoding

### LINKED ISSUE #10360: SIGSEGV on parsing MessagePack buffer: mp_check_uint: Assertion `cur < end' failed.
**Bug description**

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool 3.2.0-entrypoint-205-g8afc163fe3
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-11.4.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/sergeyb/sources/MRG/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

```lua
local msgpack = require("msgpack")
local digest = require("digest")

local buf = digest.base64_decode("1wYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgY=")
msgpack.decode(buf)
```

How to run:

Just type `tarantool test.lua`.

**Actual behavior**

``` 
tarantool: ./src/lib/msgpuck/msgpuck.h:2199: mp_check_uint: Assertion `cur < end' failed.
Aborted (core dumped)
```

Backtrace:

```c++
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140100700048064) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140100700048064) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140100700048064, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f6bbb442476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f6bbb4287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f6bbb42871b in __assert_fail_base (fmt=0x7f6bbb5dd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x55dc8935843c "cur < end", file=0x55dc89358420 "./src/lib/msgpuck/msgpuck.h", line=2199, function=<optimized out>)
    at ./assert/assert.c:92
#6  0x00007f6bbb439e96 in __GI___assert_fail (assertion=0x55dc8935843c "cur < end", file=0x55dc89358420 "./src/lib/msgpuck/msgpuck.h", line=2199, 
    function=0x55dc89358920 <__PRETTY_FUNCTION__.29> "mp_check_uint") at ./assert/assert.c:101
#7  0x000055dc88e98b9a in mp_check_uint (cur=0x412e1932 '\006' <repeats 25 times>, end=0x412e1932 '\006' <repeats 25 times>)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/msgpuck/msgpuck.h:2199
#8  0x000055dc88d78a47 in interval_unpack (data=0x7f6bb8880b08, len=7, itv=0x7f6bb8880b20)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/core/mp_interval.c:122
#9  0x000055dc88d78e3e in mp_validate_interval (data=0x412e1932 '\006' <repeats 25 times>, len=8)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/core/mp_interval.c:217
#10 0x000055dc88a7190b in msgpack_check_ext_data (type=6 '\006', data=0x412e192a '\006' <repeats 33 times>, len=8)
    at /home/sergeyb/sources/MRG/tarantool/src/box/msgpack.c:133
#11 0x000055dc88e9b3bf in mp_check (data=0x7f6bb8880c88, end=0x412e194b "") at /home/sergeyb/sources/MRG/tarantool/src/lib/msgpuck/msgpuck.h:3222
#12 0x000055dc88d10ce4 in lua_msgpack_decode_string (L=0x41f63378, check=true) at /home/sergeyb/sources/MRG/tarantool/src/lua/msgpack.c:617
#13 0x000055dc88d10dd2 in lua_msgpack_decode (L=0x41f63378) at /home/sergeyb/sources/MRG/tarantool/src/lua/msgpack.c:636
#14 0x000055dc88da38a7 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#15 0x000055dc88db141f in lua_pcall (L=0x41f63378, nargs=0, nresults=0, errfunc=0)
    at /home/sergeyb/sources/MRG/tarantool/third_party/luajit/src/lj_api.c:1173
#16 0x000055dc88d14dd1 in luaT_call (L=0x41f63378, nargs=0, nreturns=0) at /home/sergeyb/sources/MRG/tarantool/src/lua/utils.c:689
#17 0x000055dc88d06361 in lua_main (L=0x41f63378, is_debugging=false, argc=1, argv=0x55dc8a8bd558)
    at /home/sergeyb/sources/MRG/tarantool/src/lua/init.c:920
#18 0x000055dc88d06f7b in run_script_f (ap=0x7f6bb8c10858) at /home/sergeyb/sources/MRG/tarantool/src/lua/init.c:1133
#19 0x000055dc88a6a177 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55dc88d0637a <run_script_f>, ap=0x7f6bb8c10858)
    at /home/sergeyb/sources/MRG/tarantool/src/lib/core/fiber.h:1324
#20 0x000055dc88d459c0 in fiber_loop (data=0x0) at /home/sergeyb/sources/MRG/tarantool/src/lib/core/fiber.c:1162
#21 0x000055dc8913a6d8 in coro_init () at /home/sergeyb/sources/MRG/tarantool/third_party/coro/coro.c:108
```

tarantool binary and coredump: 
[gh-10360.zip](https://github.com/user-attachments/files/16474515/gh-10360.zip)

**Expected behavior**

correct error handling

### PR DESCRIPTION
**Pull request by nshy**
Currently we do not check if we have enough data to read when loading field key.

While at it also fix limits checking for `year`, `month`, `week` and `nanoseconds` fields we lost in the commit 01c7ae1128e1 ("msgpack: fix decoding intervals with int64").

Also as we check the upper limit for `ajust` field let's check the lower limit too.

Closes #10360

### CODE REVIEW

File: src/lib/core/mp_interval.c [hunk 1]
```diff
@@ -109,34 +109,29 @@ interval_unpack(const char **data, uint32_t len, struct interval *itv)
...
-		if (type == MP_UINT) {
-			if (mp_check_uint(*data, end) > 0)
-				return NULL;
-		} else if (type == MP_INT) {
-			if (mp_check_int(*data, end) > 0)
-				return NULL;
-		} else {
-			return NULL;
-		}
 		if (mp_read_int64(data, &value) != 0)
```
Comment (locker) [inline src/lib/core/mp_interval.c]: AFAICS `mp_read_int64` doesn't check boundaries so we should still check them.

File: src/lib/core/mp_interval.c [hunk 2]
```diff
@@ -109,34 +109,29 @@ interval_unpack(const char **data, uint32_t len, struct interval *itv)
...
 			return NULL;
 		switch (field) {
 		case FIELD_YEAR:
+			if (value < INT32_MIN || value > INT32_MAX)
```
Comment (locker) [inline src/lib/core/mp_interval.c]: Can we use `mp_read_int32` here instead?

File: src/lib/core/mp_interval.c (hunk 1 above)
Comment (nshy) [reply src/lib/core/mp_interval.c]: Right, thanx! Dropped this hunk.

Comment (nshy) [reply src/lib/core/mp_interval.c]: Added tests:

```diff
+       /* Check reading field value is checked. */
+       ok(mp_validate_interval("\x01\x00\xce", 3) != 0,
+          "reading interval field value is checked");
+       ok(mp_validate_interval("\x01\x00\xd3", 3) != 0,
+          "reading interval field value is checked");
```

File: src/lib/core/mp_interval.c (hunk 2 above)
Comment (nshy) [reply src/lib/core/mp_interval.c]: Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/lib/core/mp_interval.c b/src/lib/core/mp_interval.c
index 58764bc6da..cc3427b28b 100644
--- a/src/lib/core/mp_interval.c
+++ b/src/lib/core/mp_interval.c
@@ -126,42 +126,46 @@ interval_unpack(const char **data, uint32_t len, struct interval *itv)
 		} else {
 			return NULL;
 		}
-		if (mp_read_int64(data, &value) != 0)
-			return NULL;
 		switch (field) {
 		case FIELD_YEAR:
-			if (value < INT32_MIN || value > INT32_MAX)
+			if (mp_read_int32(data, &itv->year) != 0)
 				return NULL;
-			itv->year = value;
 			break;
 		case FIELD_MONTH:
-			if (value < INT32_MIN || value > INT32_MAX)
+			if (mp_read_int32(data, &itv->month) != 0)
 				return NULL;
-			itv->month = value;
 			break;
 		case FIELD_WEEK:
-			if (value < INT32_MIN || value > INT32_MAX)
+			if (mp_read_int32(data, &itv->week) != 0)
 				return NULL;
-			itv->week = value;
 			break;
 		case FIELD_DAY:
+			if (mp_read_int64(data, &value) != 0)
+				return NULL;
 			itv->day = value;
 			break;
 		case FIELD_HOUR:
+			if (mp_read_int64(data, &value) != 0)
+				return NULL;
 			itv->hour = value;
 			break;
 		case FIELD_MINUTE:
+			if (mp_read_int64(data, &value) != 0)
+				return NULL;
 			itv->min = value;
 			break;
 		case FIELD_SECOND:
+			if (mp_read_int64(data, &value) != 0)
+				return NULL;
 			itv->sec = value;
 			break;
 		case FIELD_NANOSECOND:
-			if (value < INT32_MIN || value > INT32_MAX)
+			if (mp_read_int32(data, &itv->nsec) != 0)
 				return NULL;
-			itv->nsec = value;
 			break;
 		case FIELD_ADJUST:
+			if (mp_read_int64(data, &value) != 0)
+				return NULL;
 			if (value < 0 || value > DT_SNAP)
 				return NULL;
 			itv->adjust = (dt_adjust_t)value;
```

</details>

File: src/lib/core/mp_interval.c (hunk 1 above)
Comment (nshy) [reply src/lib/core/mp_interval.c]: Also fixed the added check (`1` changed to `2`):

```c
                if (end - *data < 2)
                        return NULL;
```

File: changelogs/unreleased/gh-10360-fix-interval-decoding.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+## bugfix/core
+
+* Fixed reading after MsgPack end of invalid interval MsgPack on decoding.
+  Fixed checking bounds on decoding of year, month, week, nanosecond and
+  adjust fields of interval MsgPack (gh-10360).
```
Comment (xuniq) [inline changelogs/unreleased/gh-10360-fix-interval-decoding.md]:
```suggestion
* Fixed reading after MsgPack end of invalid interval MsgPack on decoding.
  Fixed checking bounds on decoding of year, month, week, and nanosecond, and
  adjusted the fields of the interval MsgPack (gh-10360).
```

Comment (nshy) [reply changelogs/unreleased/gh-10360-fix-interval-decoding.md]: Thanx! Fixed.

**Comment by locker** [comment]
Cherry-picked to 3.2, 3.3, 3.4.
