### PR TITLE
config: fix startup hang in supervised failover

### LINKED ISSUE #11318: config: startup may stuck on permissions applying in replication.failover = supervised
There is a simple test in the failover coordinator's test suite, which adds a replica with a maximum failover priority.

The relevant part of the test is quoted below.

```lua
g.test_upscale_cluster = function(g)
    local cluster_config1 = cbuilder:new(remote_config)
         :use_replicaset('r-001')
         :add_instance('i-001', {})
         :add_instance('i-002', {})
         :config()

    -- Start a replicaset in the supervised failover mode.
    g.cluster = cluster.new(g, cluster_config1, {}, {dir = g.dir})

    cs_helpers.write_local_config(g, g.dir)
    cs_helpers.write_remote_config(g, cluster_config1)

    g.cluster:start()

    local coordinator = failover.new(g, g.dir)
    coordinator:start()

    -- Try to update the cluster topology by increasing the number
    -- of instances.
    local cluster_config2 = cbuilder:new(remote_config)
         :use_replicaset('r-001')
         :add_instance('i-001', {})
         :add_instance('i-002', {})
         :add_instance('i-003', {})
         :set_global_option('failover.replicasets.r-001.priority', {
             ['i-003'] = 1,
         })
         :config()

    g.cluster:sync(cluster_config2)
    cs_helpers.write_local_config(g, g.dir)
    cs_helpers.write_remote_config(g, cluster_config2)

    g.cluster['i-003']:start()
    <...>
```

The last line stucks.

Run the following command several times from `tarantool-ee` sources to reproduce:

```sh
$ ./tarantool/src/tarantool $(which luatest) -v test/enterprise-luatest/config_storage_update_test.lua -p upscale -c
```

The `i-003` instance stuck in the `startup_in_progress` config's status, on waiting of a response from a background credentials/permissions applying fiber on line 1008:

https://github.com/tarantool/tarantool/blob/e2a6e2cd13b73cd3ace7b055489de47bc8ecd1a2/src/box/lua/config/applier/credentials.lua#L1001-L1017

The idea of this code is that we go to the blocking synchronization only if the instance is RW. In fact, we should go to the `else` branch in this scenario, but we have the following logic in the `box_cfg` applier:

https://github.com/tarantool/tarantool/blob/e2a6e2cd13b73cd3ace7b055489de47bc8ecd1a2/src/box/lua/config/applier/box_cfg.lua#L321-L349

So, there is a change to see RW in the `credentials` applier and then stuck here, because the instance is RO:

https://github.com/tarantool/tarantool/blob/e2a6e2cd13b73cd3ace7b055489de47bc8ecd1a2/src/box/lua/config/applier/credentials.lua#L858-L870

While it is another incarnation of #11286, it seems possible to work around. I would rewrite the `config_set_read_only_if_not_bootstrap_leader` fiber to exit once `box.info.id != 1` and join this fiber in the `box_cfg` applier. This way we should see consistent `box.info.ro` result in the `credentials` applier.

OTOH, the `credentials` applier still may see inconsistent `box.info.ro` values due to other reasons and we possibly should look into it once again.

### PR DESCRIPTION
**Pull request by mandesero**
This patch fixes a bug where an instance could hang during startup because it tried to distinguish a bootstrap leader from a regular replica before learning its replicaset id (box.info.id == 0), which led to inconsistent box.info state.

Closes #11318

NO_DOC=bugfix
NO_CHANGELOG=bugfix

### CODE REVIEW

File: src/box/lua/config/applier/box_cfg.lua [hunk 1]
```diff
@@ -367,16 +391,8 @@ local function set_ro_rw(config, box_cfg)
         -- If box.info.id != 1, then the replicaset was already
         -- bootstrapped and so we should go to RO.
         if am_i_bootstrap_leader then
-            fiber.new(function()
-                local name = 'config_set_read_only_if_not_bootstrap_leader'
-                fiber.self():name(name, {truncate = true})
-                box.ctl.wait_rw()
-                if box.info.id ~= 1 then
```
Comment (grafin) [inline src/box/lua/config/applier/box_cfg.lua:374]: Is it possible for instance to become rw while its id is 0? I think its not. If so, why didn't this approach work?

Comment (mandesero) [reply src/box/lua/config/applier/box_cfg.lua:374]: The supervised failover startup logic may mark an instance as RW before it knows its id. This happens in the startup path when the instance is selected as a potential bootstrap leader. See that computes `am_i_bootstrap_leader` and immediately sets `box_cfg.read_only = not am_i_bootstrap_leader` before the first `box.cfg()` finishes. https://github.com/tarantool/tarantool/blob/c1c34cc3f647c87f416f41c4911afbb096c471a7/src/box/lua/config/applier/box_cfg.lua#L367-L374

After `box.cfg()` returns, we must decide whether the instance really became the bootstrap leader. The only reliable check is `box.info.id == 1`. The bootstrap leader gets id 1, while a regular replica gets another id.

What about `box.ctl.wait_rw()` - it only waits until the instance becomes RW, but it does not guarantee that `box.info.id` has been assigned.
https://github.com/tarantool/tarantool/blob/c1c34cc3f647c87f416f41c4911afbb096c471a7/src/box/lua/ctl.c#L66-L76

---

Because of this timing, the post-`box.cfg()` hook waits until `box.info.id` becomes != 0 and only then verifies `box.info.id == 1`. If the id is not 1, the instance is not a bootstrap leader and must switch back to RO.

I think the comment should be adjusted.
```diff
-        -- However, after leaving box.cfg() or from a background
-        -- fiber after box.ctl.wait_rw() we can check that the
+        -- However, after leaving box.cfg() we can check that the
         -- instance was a bootstrap leader using the
         -- box.info.id == 1 condition.
+        -- Note that box.ctl.wait_rw() doesn't wait for box.info.id
+        -- assignment: box_cfg.read_only is set above before the
+        -- instance learns its id. So a background fiber should
+        -- wait until box.info.id becomes non-zero.
         --
         -- If box.info.id != 1, then the replicaset was already
         -- bootstrapped and so we should go to RO.
         if am_i_bootstrap_leader then
             assert(post_box_cfg_hooks ~= nil)
             post_box_cfg_hooks:add(wait_if_not_bootstrap_leader)
         end
```

**Comment by mandesero** [comment]
EE tested in https://github.com/tarantool/tarantool-ee/pull/1601

File: src/box/lua/config/applier/box_cfg.lua [hunk 2]
```diff
@@ -178,7 +178,31 @@ end
...
+    local deadline = fiber.time() + TIMEOUT
+    while box.info.id == 0 do
+        if fiber.time() > deadline then
+            error(string.format(
+                'failed to learn instance id in the replicaset within %d ' ..
+                'seconds; cannot distinguish bootstrap leader from a ' ..
+                'regular replica.', TIMEOUT))
+        end
+        fiber.sleep(0.01)
+    end
```
[the remark this answers is not in the document]
Comment (mandesero) [reply src/box/lua/config/applier/box_cfg.lua:196]: Replaced with 30 sec

File: src/box/lua/config/applier/box_cfg.lua [hunk 3]
```diff
@@ -178,7 +178,31 @@ end
...
+    -- distinguish a bootstrap leader from a regular replica.
+    local TIMEOUT = 10
+    local deadline = fiber.time() + TIMEOUT
+    while box.info.id == 0 do
+        if fiber.time() > deadline then
+            error(string.format(
+                'failed to learn instance id in the replicaset within %d ' ..
+                'seconds; cannot distinguish bootstrap leader from a ' ..
+                'regular replica.', TIMEOUT))
+        end
```
[the remark this answers is not in the document]
Comment (mandesero) [reply src/box/lua/config/applier/box_cfg.lua:194]: Fixed.

File: test/config-luatest/supervised_bootstrap_test.lua [hunk 4]
```diff
@@ -73,3 +69,36 @@ g.test_basic = function(g)
...
+    cluster:sync(config_2)
+    cluster:start_instance('i-003')
+
+    cluster['i-003']:exec(function()
+        local config = require('config')
+        local t = require('luatest')
+        t.helpers.retrying({timeout = 60}, function()
+            t.assert_equals(config:info().status, 'ready')
+            t.assert_equals(box.info.ro, true)
+            t.assert_not_equals(box.info.id, 1)
```
[the remark this answers is not in the document]
Comment (mandesero) [reply test/config-luatest/supervised_bootstrap_test.lua:101]: I think the current timeout is sufficient to ensure that the config reaches the `ready` state.

File: src/box/lua/config/applier/box_cfg.lua [hunk 5]
```diff
@@ -178,7 +178,33 @@ end
...
+
+    -- Wait until the instance learns its id in the replicaset to
+    -- distinguish a bootstrap leader from a regular replica.
+    --
+    -- Default value for `replication.connect_timeout` is 30 seconds.
+    local TIMEOUT = 30
+    local deadline = fiber.time() + TIMEOUT
+    while box.info.id == 0 do
+        if fiber.time() > deadline then
+            error(string.format(
```
Comment (georgiy-belyanin) [inline src/box/lua/config/applier/box_cfg.lua:190]: It seems to me that this would be executed in the tx thread (since post box cfg hooks are not isolated). Probably, it should be isolated the same way as the `go isolated after box.cfg` hook?

File: src/box/lua/config/applier/box_cfg.lua [hunk 6]
```diff
@@ -359,24 +385,20 @@ local function set_ro_rw(config, box_cfg)
...
-        -- However, after leaving box.cfg() or from a background
-        -- fiber after box.ctl.wait_rw() we can check that the
+        -- However, after leaving box.cfg() we can check that the
         -- instance was a bootstrap leader using the
         -- box.info.id == 1 condition.
         --
+        -- Note that box.ctl.wait_rw() doesn't wait for box.info.id
+        -- assignment: box_cfg.read_only is set above before the
+        -- instance learns its id. So a background fiber should
+        -- wait until box.info.id becomes non-zero.
```
Comment (georgiy-belyanin) [inline src/box/lua/config/applier/box_cfg.lua]: In addition, the current implementation doesn't do it in a background fiber. Instead it uses the main one.

**Review by georgiy-belyanin — COMMENTED** [review]
Thank you for working on this one! Consider my comments.

File: src/box/lua/config/applier/box_cfg.lua (hunk 5 above)
Comment (mandesero) [reply src/box/lua/config/applier/box_cfg.lua:190]: I tried moving `wait_if_not_bootstrap_leader()` into a separate fiber, but it reintroduced flakiness. With a background fiber the check and possible switch back to RO happen later, which creates a race where the instance may stay RW for some time and be observed in that intermediate state. Running it synchronously in the post-`box.cfg()` hook appears to be stable and avoids this race.

So I kept it synchronous and adjusted the comment accordingly. Also ran stress tests: 3 runs x 150 iterations for EE and CE - all passed without issues.

File: src/box/lua/config/applier/box_cfg.lua (hunk 6 above)
Comment (mandesero) [reply src/box/lua/config/applier/box_cfg.lua]: I updated the comment

Comment (georgiy-belyanin) [reply src/box/lua/config/applier/box_cfg.lua]: Nice!

File: src/box/lua/config/applier/box_cfg.lua (hunk 5 above)
Comment (georgiy-belyanin) [reply src/box/lua/config/applier/box_cfg.lua:190]: Hm, I see. I don't know the exact reason. Thanks for testing this.

**Review by georgiy-belyanin — APPROVED** [review]
Thank you! Neat work.

**Review by grafin — APPROVED** [review]

**Comment by georgiy-belyanin** [comment]
@grafin, @mandesero I think a changelog entry is needed.

File: changelogs/unreleased/gh-11318-fix-failover-hang.md [hunk 7]
```diff
@@ -0,0 +1,4 @@
+## bugfix/failover
+
+* Fixed a bug in supervised failover when a replica could hang on startup while
+  joining an already bootstrapped replicaset (gh-11318).
```
Comment (lenkis) [inline changelogs/unreleased/gh-11318-fix-failover-hang.md]:
```suggestion
* Fixed a bug in supervised failover when a replica could hang on startup while
  joining an already bootstrapped replica set (gh-11318).
```

**Review by lenkis — APPROVED** [review]
