### PR TITLE
box: allow to access to the granted role in _vuser space

### LINKED ISSUE #10057: `box.schema.user.info()` - attempt to index a nil value
**Bug description**

* OS: Linux
* OS Version: Ubuntu 22.04.3 LTS
* Architecture: amd64

```
Tarantool 2.11.3-0-gf933f77904
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=TRUE
Compiler: GNU-11.2.0
C_FLAGS:-g -O2 -ffile-prefix-map=/build/tarantool-2.11.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/tarantool-2.11.3=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -ffile-prefix-map=/build/tarantool-2.11.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/build/tarantool-2.11.3=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Run two tarantool instances iteractively.

In console 1:
- `box.cfg{listen = 3301}`
- `box.schema.role.create('manager')`
- `box.schema.user.grant('testuser', 'manager')`

In console 2:
- `net_box = require('net.box')`
- `conn = net_box.connect('testuser:foobar@localhost:3301')`
- `conn:call("box.schema.user.info", {})`

**Actual behavior**

In console 2:
```
error: 'builtin/box/schema.lua:3022: attempt to index a nil value'
```

**Expected behavior**

In console 2:
```
[['execute', 'role', 'public'], ['session,usage', 'universe', ''], ['alter', 'user', 'testuser']]
```

### PR DESCRIPTION
**Pull request by mkostoevr**
Prior to this patch it was not possible for a user to see any role in the `_vuser` space except the one created by him and the `public` one.

Let's also make it possible to see roles that he is granted with, so calls to the `box.schema.user.info()` functions won't fail if a user has a non-'public' role granted.

Closes #10057

NO_DOC=bugfix

### CODE REVIEW

File: src/box/sysview.c [hunk 1]
```diff
@@ -317,8 +318,26 @@ vuser_filter(struct space *source, struct tuple *tuple)
...
 	if (tuple_field_u32(tuple, BOX_USER_FIELD_UID, &owner_id) != 0)
 		return false;
+
 	/* Allow access for self, childs or public user. */
-	return uid == cr->uid || owner_id == cr->uid || uid == PUBLIC;
+	if (uid == cr->uid || owner_id == cr->uid || uid == PUBLIC)
+		return true;
+
+	uint32_t type_str_len;
+	const char *type_str =
```
Comment (drewdzzz) [inline src/box/sysview.c:327]: You could check the type right in the user object:
```c
struct user *role = user_by_id(uid);
if (role->def->type == SC_ROLE) {
    ....
}
```
Or do I miss something?

File: test/box-luatest/gh_10057_user_role_test.lua [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+g.after_all(function(cg)
+    cg.server:drop()
+end)
+
+g.test_origins_in_privs = function(cg)
+    cg.server:exec(function()
+        box.schema.user.create('testuser')
+        box.schema.role.create('manager')
+        box.schema.role.create('director')
+        box.schema.user.grant('testuser', 'manager')
```
Comment (drewdzzz) [inline test/box-luatest/gh_10057_user_role_test.lua:20]: Let's check a transition in another test: role is granted to another role that is granted to a user.

**Review by drewdzzz — CHANGES_REQUESTED** [review]
Thanks for the patch!
I left a couple of suggestions.

File: changelogs/unreleased/gh-10057-box-schema-user-info.md [hunk 3]
```diff
@@ -0,0 +1,4 @@
+## bugfix/box
+
+* Fixed a bug when the `box.schema.user.info()` function could fail if a current
+  user is granted with a non-'public' role (gh-10057).
```
Comment (xuniq) [inline changelogs/unreleased/gh-10057-box-schema-user-info.md:4]:
```suggestion
* Fixed a bug when the `box.schema.user.info()` function could fail if a current
  user was granted with a non-`public` role (gh-10057).
```

**Review by xuniq — APPROVED** [review]

File: src/box/sysview.c (hunk 1 above)
Comment (mkostoevr) [reply src/box/sysview.c]: <details>

<summary>Right.</summary>

```diff
--- a/src/box/sysview.c
+++ b/src/box/sysview.c
@@ -326,17 +326,9 @@ vuser_filter(struct space *source, struct tuple *tuple)
                return true;
 
        /* Allow access to a role granted to the effective user. */
-       uint32_t type_str_len;
-       const char *type_str =
-               tuple_field_str(tuple, BOX_USER_FIELD_TYPE, &type_str_len);
-       if (type_str == NULL)
-               return false;
-       if (type_str_len == strlen("role") &&
-           !strncmp(type_str, "role", type_str_len)) {
-               struct user *role = user_by_id(uid);
-               if (role_is_granted(role, cr->auth_token))
-                       return true;
-       }
+       struct user *role = user_by_id(uid);
+       if (role->def->type == SC_ROLE && role_is_granted(role, cr->auth_token))
+               return true;
 
        return false;
 }
```

</details>

File: test/box-luatest/gh_10057_user_role_test.lua (hunk 2 above)
Comment (mkostoevr) [reply test/box-luatest/gh_10057_user_role_test.lua:31]: <details>

<summary>Made the check transitive.</summary>

```diff
diff --git a/src/box/user.cc b/src/box/user.cc
index 0501283e72..3be61fa178 100644
--- a/src/box/user.cc
+++ b/src/box/user.cc
@@ -912,7 +912,20 @@ role_revoke(struct user *grantee, struct user *role)
 bool
 role_is_granted(struct user *role, uint8_t auth_token)
 {
-       return user_map_is_set(&role->users, auth_token);
+       /* Check if the role is granted directly. */
+       if (user_map_is_set(&role->users, auth_token))
+               return true;
+
+       /* Check if the role is granted transitively. */
+       struct user_map_iterator it;
+       user_map_iterator_init(&it, &role->users);
+       struct user *transitive_role;
+       while ((transitive_role = user_map_iterator_next(&it))) {
+               if (transitive_role->def->type == SC_ROLE &&
+                   role_is_granted(transitive_role, auth_token))
+                       return true;
+       }
+       return false;
 }
 
 int
diff --git a/test/box-luatest/gh_10057_user_role_test.lua b/test/box-luatest/gh_10057_user_role_test.lua
index 316e96a83b..cbf103ab62 100644
--- a/test/box-luatest/gh_10057_user_role_test.lua
+++ b/test/box-luatest/gh_10057_user_role_test.lua
@@ -35,3 +44,24 @@ g.test_user_role = function(cg)
         box.session.su(original_user)
     end)
 end
+
+g.test_transitive_role = function(cg)
+    cg.server:exec(function()
+        box.schema.user.create('testuser')
+        box.schema.role.create('staff')
+        box.schema.role.create('manager')
+        box.schema.role.grant('manager', 'staff')
+        box.schema.user.grant('testuser', 'manager')
+
+        local original_user = box.session.effective_user()
+        box.session.su('testuser')
+
+        -- Check the user has an access to the 'manager' role.
+        t.assert_equals(#box.space._vuser.index.name:select('manager'), 1)
+
+        -- Check the user has a transitive access to the 'staff' role.
+        t.assert_equals(#box.space._vuser.index.name:select('staff'), 1)
+
+        box.session.su(original_user)
+    end)
+end
```

</details>

File: test/box-luatest/gh_10057_user_role_test.lua [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+    cg.server:exec(function()
+        box.schema.user.create('testuser')
+        box.schema.role.create('staff')
+        box.schema.role.create('manager')
+        box.schema.role.grant('manager', 'staff')
+        box.schema.user.grant('testuser', 'manager')
+
+        local original_user = box.session.effective_user()
+        box.session.su('testuser')
+
```
Comment (drewdzzz) [inline test/box-luatest/gh_10057_user_role_test.lua:73]: Let's check `box.schema.user.info()` here as well.

File: src/box/user.cc [hunk 5]
```diff
@@ -906,6 +906,28 @@ role_revoke(struct user *grantee, struct user *role)
...
+	/* Check if the role is granted transitively. */
+	struct user_map_iterator it;
+	user_map_iterator_init(&it, &role->users);
+	struct user *transitive_role;
+	while ((transitive_role = user_map_iterator_next(&it))) {
+		if (transitive_role->def->type == SC_ROLE &&
+		    role_is_granted(transitive_role, auth_token))
+			return true;
+	}
+	return false;
```
Comment (drewdzzz) [inline src/box/user.cc]: I would use BFS instead of DFS here:
1. I believe it's a good practice to beware of recursion.
2. If we decide (and we, probably, will) to increase maximal amount of users, let's say to 65535, such recursion will be able to crash Tarantool due to stack overflow, even if the graph is acyclic. 
3. It would be consistent with implementation of `role_check` function.

Function `role_check` is a good example of BFS implementation for privileges.

**Review by drewdzzz — COMMENTED** [review]
Thank you for the fixes!
I have a couple of comments.

File: src/box/user.cc (hunk 5 above)
Comment (mkostoevr) [reply src/box/user.cc]: <details>

<summary>Right.</summary>

```diff
--- a/src/box/user.cc
+++ b/src/box/user.cc
@@ -917,15 +917,25 @@ role_is_granted(struct user *role, uint8_t auth_token)
                return true;
 
        /* Check if the role is granted transitively. */
-       struct user_map_iterator it;
-       user_map_iterator_init(&it, &role->users);
-       struct user *transitive_role;
-       while ((transitive_role = user_map_iterator_next(&it))) {
-               if (transitive_role->def->type == SC_ROLE &&
-                   role_is_granted(transitive_role, auth_token))
-                       return true;
+       struct user_map transitive_closure = user_map_nil;
+       struct user_map current_layer = user_map_nil;
+       user_map_union(&current_layer, &role->users);
+       while (!user_map_is_empty(&current_layer)) {
+               /*
+                * There's no loops in the role graph (this is guaranteed
+                * by the role_check), so we're are bound to end at some
+                * point in a layer with no incoming edges.
+                */
+               struct user_map next_layer = user_map_nil;
+               struct user_map_iterator it;
+               user_map_iterator_init(&it, &current_layer);
+               struct user *transitive_role;
+               while ((transitive_role = user_map_iterator_next(&it)))
+                       user_map_union(&next_layer, &transitive_role->users);
+               user_map_union(&transitive_closure, &next_layer);
+               current_layer = next_layer;
        }
-       return false;
+       return user_map_is_set(&transitive_closure, auth_token);
 }
 
 int
```

</details>

File: test/box-luatest/gh_10057_user_role_test.lua (hunk 4 above)
Comment (mkostoevr) [reply test/box-luatest/gh_10057_user_role_test.lua:73]: Seems redundant, it's tested above and implicitly tested here by selecting the `manager` role.

Comment (drewdzzz) [reply test/box-luatest/gh_10057_user_role_test.lua:73]: The user will call `box.schema.user.info()`, not `_vuser:select` - why not cover it with a test as well?

**Review by drewdzzz — APPROVED** [review]
Thank you for the patch, LGTM!

File: test/box-luatest/gh_10057_user_role_test.lua (hunk 4 above)
Comment (sergepetrenko) [reply test/box-luatest/gh_10057_user_role_test.lua:73]: I agree with @drewdzzz, the test shouldn't make such assumptions about internals (i.e. that covering `select` implicitly covers `box.schema.user.info()`).
Let's check `box.schema.user.info()` here as well.

Comment (mkostoevr) [reply test/box-luatest/gh_10057_user_role_test.lua:73]: <details>

<summary>diff</summary>

```diff
--- a/test/box-luatest/gh_10057_user_role_test.lua
+++ b/test/box-luatest/gh_10057_user_role_test.lua
@@ -33,7 +33,7 @@ g.test_user_role = function(cg)
         local original_user = box.session.effective_user()
         box.session.su('testuser')

-        -- Check we don't have a Lua error on box.schema.info().
+        -- Check we don't have a Lua error on box.schema.user.info().
         local ok = pcall(box.schema.user.info)
         t.assert(ok)

@@ -73,18 +73,26 @@ g.test_transitive_role = function(cg)

         -- Check the user has an access to the 'manager' role.
         t.assert_equals(#box.space._vuser.index.name:select('manager'), 1)
+        t.assert(pcall(box.schema.role.info, 'manager'))
+        t.assert(pcall(box.schema.user.info, 'testuser'))

         -- Check the user doesn't have access to the 'director' role.
         t.assert_equals(#box.space._vuser.index.name:select('director'), 0)
+        t.assert(not pcall(box.schema.role.info, 'director'))

         -- Check the user has an access to the 'management' role.
         t.assert_equals(#box.space._vuser.index.name:select('management'), 1)
+        t.assert(pcall(box.schema.role.info, 'management'))
+        t.assert(pcall(box.schema.role.info, 'manager'))

         -- Check the user doesn't have access to the 'infra' role.
         t.assert_equals(#box.space._vuser.index.name:select('infra'), 0)
+        t.assert(not pcall(box.schema.role.info, 'infra'))

         -- Check the user has an access to the 'staff' role.
         t.assert_equals(#box.space._vuser.index.name:select('staff'), 1)
+        t.assert(pcall(box.schema.role.info, 'staff'))
+        t.assert(pcall(box.schema.role.info, 'management'))

         box.session.su(original_user)
     end)
```

</details>
