### PR TITLE
lua: fix uninitialized var usage in `luamp_encode_with_translation`

### LINKED ISSUE #9023: Coverity reports an issue in MP_EXT decoding
image

### PR DESCRIPTION
**Pull request by Gumix**
`*type_out` was set to uninitialized value for `field->type == MP_EXT`.
This was introduced by commit 9f9142d64289 ("box: cleanup on tuple encoding failure")

Closes #9023

### CODE REVIEW

**Review by nshy — APPROVED** [review]

File: test/unit/lua_msgpack.c [hunk 1]
```diff
@@ -101,6 +103,22 @@ test_translation_in_encoding(lua_State *L)
...
+				      translation, &type);
+	lua_pop(L, 1);
+	mpstream_flush(&stream);
+	const char *mp_expected = "\xd8\x02\x00\x00\x00\x00\x00\x00\x00"
+				  "\x00\x00\x00\x00\x00\x00\x00\x00\x00";
+	ok(strncmp(ibuf->buf, mp_expected, ibuf_used(ibuf)) == 0,
+	   "UUID is encoded as MP_EXT");
+	ok(type == MP_EXT, "type of UUID is MP_EXT");
+	ibuf_reset(ibuf);
+	mpstream_reset(&stream);
```
Comment (locker) [inline test/unit/lua_msgpack.c:120]: Please move to a new function (for example, `test_encode_ext`) because this case has nothing to do with translation.

**Review by locker — CHANGES_REQUESTED** [review]

**Review by ochaplashkin — APPROVED** [review]

File: test/unit/lua_msgpack.c (hunk 1 above)
Comment (Gumix) [reply test/unit/lua_msgpack.c]: Done.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.11.
