### PR TITLE
box: set TXN_WAIT_SYNC with xrow rather than limbo state during recovery

### LINKED ISSUE #11053: Record in `_gc_consumers` space is lost after PROMOTE followed by an instance restart
**Steps to reproduce**

1. Setup two replicas, replica 1 being master.
```lua
-- replica 1
console = require('console')

box.cfg{
    listen = 3301,
    replication = {3301, 3302},
    replication_timeout = 0.1,
    replication_synchro_timeout = 600,
    replication_synchro_quorum = 4,
}

box.once('bootstrap', function()
    box.schema.user.grant('guest', 'super')

    box.schema.create_space('s', {is_sync = true}):create_index('p')

    box.ctl.promote()
end)

console.start()

os.exit()

-- replica 2
console = require('console')

box.cfg{
    listen = 3302,
    read_only = true,
    replication = {3301, 3302},
    replication_synchro_quorum = 4,
    replication_timeout = 0.1,
}

console.start()

os.exit()
```

2. Simulate network partitioning of replica 2 from replica 1 on replica 2.
```lua
-- replica 2

box.cfg{replication = ''}
```

3. Execute a synchronous transaction on replica 1 (master) while being partitioned from replica 2.
```lua
-- replica 1

box.atomic({wait = 'submit'}, function() box.space.s:replace{0} end)
```

4. Setup a third replica.
```lua
-- replica 3
console = require('console')

box.cfg{
    listen = 3303,
    read_only = true,
    replication = {3301, 3302},
    replication_synchro_quorum = 4,
    replication_timeout = 0.1,
}

console.start()

os.exit()
```

5. Check `_gc_consumers` space on replica 1 and observe new record for replica 3.
```lua
-- replica 1

box.space._gc_consumers:select{}
```

6. Promote replica 2.
```lua
-- replica 2

box.ctl.promote()
```

7. Wait until replica 1 receives the promote request from replica 2.

8. Restart replica 1.

9. Check `_gc_consumers` space on replica 1 and observe loss of record for replica 3.
```lua
box.space._gc_consumers:select{}
```

**Actual behavior**

The record in `_gc_consumers` space for replica 3 is lost after PROMOTE followed by an instance restart.

**Expected behavior**

The record in `_gc_consumers` space for replica 3 is not lost after PROMOTE followed by an instance restart.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
This patchset fixes a bug with `TXN_FORCE_ASYNC` transactions being lost after receiving a promote request from another instance and restarting the current instance.

Closes #11053

### CODE REVIEW

File: src/box/box.cc [hunk 1]
```diff
@@ -831,8 +831,8 @@ wal_stream_apply_dml_row(struct wal_stream *stream, struct xrow_header *row)
 	assert(txn != NULL);
 	if (!row->is_commit)
 		return 0;
-	if (row->wait_ack)
-		box_txn_make_sync();
+	txn_set_xrow_flags(row->flags);
+	txn_recovery_set_limbo_policy();
```
Comment (Gerold103) [inline src/box/box.cc:835]: Lets just inline this function right here. It is used in a single place, and mentions "recovery", but doesn't depend on being called during the recovery anyhow. It also makes a check if called outside of any txns, which is never true here.

File: test/replication-luatest/gh_11053_gc_consumer_record_lost_after_promote_and_restart_test.lua [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+g.before_each(function(cg)
+    cg.replica_set = replica_set:new{}
+    cg.box_cfg = {
+        replication = {
+            server.build_listen_uri('master', cg.replica_set.id),
+            server.build_listen_uri('replica', cg.replica_set.id),
+        },
+        replication_timeout = 0.1,
+        replication_synchro_timeout = 120,
+        replication_synchro_quorum = 4,
```
Comment (Gerold103) [inline test/replication-luatest/gh_11053_gc_consumer_record_lost_after_promote_and_restart_test.lua:16]: I forgot again why do we have here quorum 4, and all still works fine 😭. If it is not needed, then can we drop it? If it is needed exactly 4, then can you write a comment why, please?

**Review by xuniq — APPROVED** [review]

**Review by Gerold103 — APPROVED** [review]
Thank you, @CuriousGeorgiy, for making the fix and addressing my nitpicking 🙏!

**Comment by sergepetrenko** [comment]
> @sergepetrenko
> 
> > Another test, probably with some error injection is needed in older versions.
> 
> I think this would be a bit overkill. Since this would a mere refactoring for older versions ([#11053 (comment)](https://github.com/tarantool/tarantool/issues/11053#issuecomment-2792178100)), what do you think about backporting without a test?

@CuriousGeorgiy, ok, the change looks safe, indeed.
