### PR TITLE
memtx: track read story in when conflicting full scans due to gap write

### LINKED ISSUE #7493: memtx HASH index repeatable read violation
**Steps to reproduce**

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local ffi = require('ffi')
local json = require('json')
local log = require('log')
local txn_proxy = require('txn_proxy')

box.cfg{memtx_use_mvcc_engine = true}

box.schema.space.create('s')
box.space.s:create_index('pk', {type = 'HASH'})


local tx1 = txn_proxy:new()
local tx2 = txn_proxy:new()
local tx3 = txn_proxy:new()

tx1('box.begin()')
tx1('box.space.s:select({}, {fullscan = true})')
tx2('box.begin()')
tx2('box.space.s:insert{0}')
tx3('box.begin()')
tx3('box.space.s:insert{0}')
tx3('box.commit()')
log.info("%s", json.encode(tx1('box.space.s:select({}, {fullscan = true})')))

os.exit()
```

**Actual behavior**

```console
[[[0]]]
```

**Expected behavior**

```console
[[]]
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
When conflicting transactions that made full scans in
`memtx_tx_handle_gap_write`, we need to also track that the conflicted
transaction has read the inserted tuple, just like we do in gap tracking
for ordered indexes — otherwise another transaction can overwrite the
inserted tuple in which case no gap tracking will be handled.

Closes #7493

NO_DOC=bugfix

### CODE REVIEW

**Review by alyapunov — APPROVED** [review]

File: test/box-luatest/gh_7493_memtx_hash_idx_repeatable_read_violation_test.lua [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    cg.server:exec(function()
+        box.space.s:drop()
+    end)
+end)
+
+--[[
+Checks that commit of a tuple replacing a gap-inserted tuple from a concurrent
+transaction is correctly handled.
+]]
+g.test_gap_tracking_full_key_corner_cases = function(cg)
```
Comment (drewdzzz) [inline test/box-luatest/gh_7493_memtx_hash_idx_repeatable_read_violation_test.lua:35]: Test name is stale.

**Review by drewdzzz — CHANGES_REQUESTED** [review]
Everything is OK instead of the test name.

File: test/box-luatest/gh_7493_memtx_hash_idx_repeatable_read_violation_test.lua (hunk 1 above)
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_7493_memtx_hash_idx_repeatable_read_violation_test.lua]: Fixed, sorry, doing a lot of copy-paste for tests lately.

**Review by drewdzzz — APPROVED** [review]

**Review by alyapunov — APPROVED** [review]
