### PR TITLE
Linearizable read

### LINKED ISSUE #6707: Synchro replication: quorum read
As we have a synchronous write for the data, we need the opposite for read.
Currently we have no mechanism to prevent client from reading data from a node that is not up to date with quorum write. The trivial solution to read from master can fail also, since master can be elect, still not up to date from limbo - #6689. 

We need to elaborate interface and the machinery behind to enable the subj.

### PR DESCRIPTION
**Pull request by sergepetrenko**
Linearizability is a property of operations when operation performed on
any node sees all the operations performed earlier on any other node of
the cluster.

More strictly speaking, it's a property, demanding, that if a response
for some write request arrived earlier than some read request was made,
this read request must see the results of that (or any earlier) write
request.

This patch introduces "linearizable" isolation level to box.begin(). When
the option is set, the begin() is stalled until the node receives the
latest data from at least one member of the quorum. This is needed to
make sure that the node sees all the writes committed on a quorum.
The transaction is served only after the node sees the relevant data,
thus implementing linearizable semantics.

Closes #6707

### CODE REVIEW

File: src/box/engine.h [hunk 1]
```diff
@@ -490,6 +501,8 @@ int generic_engine_backup(struct engine *, const struct vclock *,
 void generic_engine_memory_stat(struct engine *, struct engine_memory_stat *);
 void generic_engine_reset_stat(struct engine *);
 int generic_engine_check_space_def(struct space_def *);
+int
+generic_engine_check_space_linearizability(const struct space *space);
```
Comment (Gerold103) [inline src/box/engine.h:505]: Maybe could be easier to drop all the new virtual functions and simply check `space->engine` + `space->def->opts` manually? Doesn't look like you really need any engine-specific parts of a space. Only its common properties.

File: src/box/lua/schema.lua [hunk 2]
```diff
@@ -423,6 +432,11 @@ box.begin = function(options)
         box.rollback()
         box.error()
     end
+    if linearizable and
+       builtin.box_txn_set_is_linearizable(linearizable) ~= 0 then
```
Comment (Gerold103) [inline src/box/lua/schema.lua:436]: A small optimization would be to make `box_txn_set_is_linearizable()` take void args. It does not look like a txn can "revert" its linearizability. Hence it only makes sense to do `box_txn_set_is_linearizable(true)`, and that means the argument isn't needed.

File: src/box/relay.cc [hunk 3]
```diff
@@ -179,6 +183,8 @@ struct relay {
 	double txn_lag;
 	/** Relay sync state. */
 	enum relay_state state;
+	/** Whether relay should speed up the next heartbeat dispatch. */
+	bool speedup_heartbeat;
```
Comment (Gerold103) [inline src/box/relay.cc:187]: "Speedup" is a verb, which makes this name look like an action, a function. I would recommend to start all flags with `is/has/does/need/...` to emphasize this is just a flag. For example, here it could be `do_bump_heartbeat` or `need_new_heartbeat` or likewise.

File: src/box/relay.cc [hunk 4]
```diff
@@ -752,6 +767,21 @@ relay_send_heartbeat(struct relay *relay)
 	}
 }
 
+/**
+ * The heartbeat interval. Is usually equal to @a replication_timeout, but
+ * might be smaller, when it's important to exchange heartbeats with replica as
+ * soon as possible.
+ */
+static double
+relay_heartbeat_interval(struct relay *relay)
```
Comment (Gerold103) [inline src/box/relay.cc:776]: This can be const.

File: src/box/relay.cc [hunk 5]
```diff
@@ -823,6 +856,56 @@ relay_thread_on_stop(void *arg)
...
+			      relay_next_sync_f, relay_next_sync_msg_free,
+			      timeout) < 0)
+		diag_raise();
+	uint64_t sync = msg->sync;
+	free(msg);
+	return sync;
+}
+
+uint64_t
+relay_sync(struct relay *relay)
```
Comment (Gerold103) [inline src/box/relay.cc:904]: Can be const.

File: src/box/replication.cc [hunk 6]
```diff
@@ -116,6 +116,7 @@ replication_init(int num_threads)
 	rlist_create(&replicaset.applier.on_wal_write);
 
 	rlist_create(&replicaset.on_ack);
+	rlist_create(&replicaset.on_relay_thread_start);
```
Comment (Gerold103) [inline src/box/replication.cc:119]: Also need to destroy the trigger list in `replication_free()`.

File: src/box/space.h [hunk 7]
```diff
@@ -38,6 +38,7 @@
 #include "index.h"
 #include "error.h"
 #include "diag.h"
+#include "tt_static.h"
```
Comment (Gerold103) [inline src/box/space.h:41]: Are you sure this is needed? I dropped it and compilation worked.

File: src/box/txn.c [hunk 8]
```diff
@@ -681,36 +682,44 @@ txn_commit_stmt(struct txn *txn, struct request *request)
...
-		if (!rlist_empty(&stmt->space->before_replace)) {
-			/*
-			 * Triggers see old_tuple and that tuple
-			 * must remain the same
-			 */
-			stmt->does_require_old_tuple = true;
+	struct space *space = stmt->space;
+	if (space != NULL) {
+		if (txn->is_linearizable &&
+		    engine_check_space_linearizability(space->engine,
```
Comment (Gerold103) [inline src/box/txn.c:688]: Shouldn't this be in `txn_begin_stmt()` instead of `txn_commit_stmt()`?

File: src/box/txn.h [hunk 9]
```diff
@@ -557,6 +557,8 @@ struct txn {
 	 * Nesting level of space on_replace triggers for current txn.
 	 */
 	int space_on_replace_triggers_depth;
+	/** Whether the transaction is linearizable. */
+	bool is_linearizable;
```
Comment (Gerold103) [inline src/box/txn.h:561]: AFAICS, the flags are supposed to be stored in `txn.flags` and should all be listed in `enum txn_flag`.

File: src/box/wal.c [hunk 10]
```diff
@@ -374,6 +376,7 @@ tx_complete_batch(struct cmsg *msg)
 	/* Update the tx vclock to the latest written by wal. */
 	vclock_copy(&replicaset.vclock, &batch->vclock);
 	tx_schedule_queue(&batch->commit);
+	trigger_run(&wal_on_batch_write, NULL);
```
Comment (Gerold103) [inline src/box/wal.c:379]: Can somehow `wal_set_watcher()` be reused? Like relays do. The problem right now is that we add this slowdown for the common path, for all WAL writes, even for non-linearizable txns.

**Review by Gerold103 — COMMENTED** [review]
Thanks for the patch! Good work!

From the commit message: *"this read request must see the results of that (or any later) write request."* - did you mean *"or any earlier"*? We can't guarantee that a read will see any writes done after the read was started. And of course can't see the writes done after the read ends, because it would mean time travel. Or have I misread that?

Another comment is that from the doc request it is not clear what happens if can't gather a quorum. From the code I can see a timeout error is raised. Would be good to add a couple of words about that.

I didn't review the tests yet. Will continue.

File: src/box/relay.cc [hunk 11]
```diff
@@ -807,59 +790,37 @@ relay_push_raft_msg(struct relay *relay)
...
+		 */
+		if (relay->tx.is_raft_push_pending)
+			relay_push_raft_msg(relay);
+	}
 }
 
-/** Relay thread part of the Raft flag setting, second hop. */
 static void
-relay_set_is_raft_enabled(struct cmsg *base)
+relay_set_is_raft_disabled(struct relay *relay)
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/relay.cc:839]: Yes, indeed. Done:
<details><summary>diff</summary>

```diff
diff --git a/src/box/relay.cc b/src/box/relay.cc
index 42cf316d7..49dad8499 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -791,8 +791,9 @@ relay_push_raft_msg(struct relay *relay)
 }
 
 static void
-relay_set_is_raft_enabled(struct relay *relay)
+relay_thread_on_start(void *arg)
 {
+	struct relay *relay = (struct relay *)arg;
 	if (!relay->replica->anon && relay->version_id >= version_id(2, 6, 0)) {
 		relay->tx.is_raft_enabled = true;
 		/*
@@ -803,24 +804,11 @@ relay_set_is_raft_enabled(struct relay *relay)
 	}
 }
 
-static void
-relay_set_is_raft_disabled(struct relay *relay)
-{
-	relay->tx.is_raft_enabled = false;
-}
-
-static void
-relay_thread_on_start(void *arg)
-{
-	struct relay *relay = (struct relay *)arg;
-	relay_set_is_raft_enabled(relay);
-}
-
 static void
 relay_thread_on_stop(void *arg)
 {
 	struct relay *relay = (struct relay *)arg;
-	relay_set_is_raft_disabled(relay);
+	relay->tx.is_raft_enabled = false;
 }
 
 /**

```

</details>

File: src/box/applier.cc [hunk 12]
```diff
@@ -1496,6 +1518,8 @@ applier_process_batch(struct cmsg *base)
 			stailq_first_entry(&tx->rows, struct applier_tx_row,
 					    next);
 		raft_process_heartbeat(box_raft(), applier->instance_id);
+		if (applier_process_sync(applier, txr->row.sync) != 0)
+			diag_raise();
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/applier.cc:1522]: We should. I process sync twice for simplicity. First row sync for all messages(like raft, heartbeat and so on) and then last row for transactions:
https://github.com/tarantool/tarantool/pull/7611/files#diff-a99e106ecbdb0944db62f223fa59b3140ea961842ef5c2c139f0a603e1989d9fL1266-L1267

File: src/box/box.cc [hunk 13]
```diff
@@ -1805,6 +1805,214 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+	 */
+	vclock_map_t collected_vclock_map;
+	/** The fiber waiting for vclock. */
+	struct fiber *waiter;
+	/** Collected vclock. */
+	struct vclock *vclock;
+	/** The request deadline. */
+	double deadline;
+	/** Whether the request is timed out. */
+	bool timed_out;
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1823]: Ok, renamed.

File: src/box/box.cc [hunk 14]
```diff
@@ -1805,6 +1805,214 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+	trigger_add(&replicaset.on_ack, &on_ack);
+	replicaset_foreach(replica) {
+		if (relay_get_state(replica->relay) != RELAY_FOLLOW ||
+		    replica->anon) {
+			continue;
+		}
+		/* Might be already filled by on_relay_thread_start trigger. */
+		if (data.syncs[replica->id] == 0) {
+			data.syncs[replica->id] =
+				relay_next_sync(replica->relay, deadline);
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1912]: Since all `relay_next_sync()` calls go to the same endpoint (tx), their returns are ordered.
Now, while an old relay can still write a message, it's state is still "FOLLOW", because it's changed to "STOPPED" only when the relay thread is joined.
So either the old relay fails with no response at all or its message will be first in queue. The order will be correct.

Have I answered your question?

File: src/box/relay.cc (hunk 5 above)
Comment (sergepetrenko) [reply src/box/relay.cc:904]: Done.

File: src/box/replication.cc (hunk 6 above)
Comment (sergepetrenko) [reply src/box/replication.cc:119]: Fixed.

File: src/box/space.h (hunk 7 above)
Comment (sergepetrenko) [reply src/box/space.h:41]: Oops, that's a leftover from some intermediate patch version. Removed, sorry.

File: src/box/lua/schema.lua (hunk 2 above)
Comment (sergepetrenko) [reply src/box/lua/schema.lua:436]: Good point, done.

File: src/box/relay.cc (hunk 3 above)
Comment (sergepetrenko) [reply src/box/relay.cc:187]: Let it be `need_new_heartbeat`. Fixed.

File: src/box/wal.c (hunk 10 above)
Comment (sergepetrenko) [reply src/box/wal.c:379]: I was going to write that it can't, but it actually can.
You see, the problem is that watcher is notified first and only then `tx_complete_batch` message is sent. So by the time watcher is notified in tx, fresh vclock is not yet delivered there. So I can't check if target vclock is reached or not in watcher callback. I have to wake up all the waiter fibers, because by the time they are woken up vclock will be already delivered.

TBH this looks rather complex IMO. Also do we really care about a performance impact of `trigger_run` for empty trigger list when no linearizable transactions are used? There's a walk over list of finished transactions anyway.

Some pseudocode of how I see it. I didn't try to compile it, this is just to illustrate. Let me know if you like it or not.
<details><summary>example</summary>

```c

/** A vclock watcher structure. */
struct box_vclock_watcher {
	/** The base wal watcher. */
	struct wal_watcher watcher;
	/** How many fibers are subscribed to vclock updates. */
	int waiter_count;
	/** Fibers waiting for some vclock. */
	struct rlist waiters;
};

/**
 * A single watcher for all vclock waiters initialized and destroyed on demand.
 */
struct box_vclock_watcher box_vclock_watcher;

struct vclock_waiter {
	/** The fiber waiting for vclock. */
	struct fiber *fiber;
	/** A link in all registered waiters list. */
	struct rlist link;
};

/** This is called in tx_prio, just like tx_complete_batch.
 * Since we don't yield, it's fine that this callback is fired before the
 * tx_complete_batch. By the time waiters wake up they already see the new
 * vclock.
 */
static void
box_vclock_watcher_cb(struct wal_watcher *watcher, unsigned events)
{
	(void) events;
	assert(watcher == &box_vclock_watcher.watcher);
	struct vclock_waiter *waiter;
	/**
	 * Wake up everyone. Vclock is not delivered yet, it's delivered by
	 * next cbus message. But it'll be known by the time fibers wake up.
	 */
	rlist_foreach_entry(waiter, box_vclock_watcher.waiters, link) {
		fiber_wakeup(waiter->fiber);
	}
}

void
box_add_vclock_waiter(struct vclock_waiter *waiter)
{
	if (box_vclock_watcher.waiter_count++ == 0) {
		//XXX: some difficulties with watcher initialization left out.
		// It does cbus_pair inside, we don't need that for tx <-> wal.
		// They're already connected.
		wal_set_watcher(&box_vclock_watcher.watcher, "wal",
				box_vclock_watcher_cb, NULL);
	}
	rlist_add_tail_entry(&box_vclock_watcher.waiters, waiter, link);
	return;
}

void
box_remove_vclock_waiter(struct vclock_waiter *waiter)
{
	if (--box_vclock_watcher.waiter_count == 0) {
		wal_clear_watcher(&box_vclock_watcher.watcher, NULL);
	}
	rlist_del_entry(waiter, link);
}

static int
box_wait_vclock(const struct vclock *vclock, double deadline)
{
	struct vclock_waiter waiter = {
		.fiber = fiber(),
		.link = RLIST_LINK_INITIALIZER,
	};
	box_add_vclock_waiter(&waiter);
	bool done = false;
	do {
		if (fiber_yield_deadline(deadline))
			break;
		done = vclock_compare_ignore0(&replicaset.vclock, vclock) <= 0;
	} while (!done);

	box_remove_vclock_waiter(&waiter);

	if (!done) {
		diag_set(ClientError, ER_TIMEOUT);
		return -1;
	}
	return 0;
}

```
</details>

File: src/box/txn.h (hunk 9 above)
Comment (sergepetrenko) [reply src/box/txn.h:561]: I didn't put `IS_LINEARIZABLE` to flags initially, because I thought `flags` hold technical details, like IS_ABORTED, or IS_CONFLICTED or CAN_YIELD rather than txn mode or txn isolation.

But I see that `TXN_WAIT_SYNC` is in flags, so I'll make `linearizable` a flag as well:

<details><summary>diff</summary>

```diff
diff --git a/src/box/txn.c b/src/box/txn.c
index 5a70c7394..5c8024a74 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -553,7 +553,6 @@ txn_begin(void)
        txn->fiber = NULL;
        txn->timeout = TIMEOUT_INFINITY;
        txn->rollback_timer = NULL;
-       txn->is_linearizable = false;
        fiber_set_txn(fiber(), txn);
        trigger_create(&txn->fiber_on_yield, txn_on_yield, NULL, NULL);
        trigger_add(&fiber()->on_yield, &txn->fiber_on_yield);
@@ -608,7 +607,7 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type)
                txn_set_flags(txn, TXN_IS_CONFLICTED);
        }
 
-       if (space != NULL && txn->is_linearizable &&
+       if (space != NULL && txn_has_flag(txn, TXN_IS_LINEARIZABLE) &&
            engine_check_space_linearizability(space->engine, space) != 0) {
                return -1;
        }
@@ -1422,7 +1421,7 @@ box_txn_make_linearizable(void)
        }
        if (box_wait_linearization_point(txn->timeout) != 0)
                return -1;
-       txn->is_linearizable = true;
+       txn_set_flags(txn, TXN_IS_LINEARIZABLE);
        return 0;
 }
 
diff --git a/src/box/txn.h b/src/box/txn.h
index 1d8701ee2..a8a7e4501 100644
--- a/src/box/txn.h
+++ b/src/box/txn.h
@@ -101,6 +101,11 @@ enum txn_flag {
         * rolled back at commit.
         */
        TXN_IS_ABORTED_BY_TIMEOUT = 0x100,
+       /**
+        * Transaction is linearizable, so it can only touch certain types of
+        * spaces (synchronous ones, for example).
+        */
+       TXN_IS_LINEARIZABLE = 0x200,
 };
 
 enum {
@@ -557,8 +562,6 @@ struct txn {
         * Nesting level of space on_replace triggers for current txn.
         */
        int space_on_replace_triggers_depth;
-       /** Whether the transaction is linearizable. */
-       bool is_linearizable;
 };
 
 static inline bool
@@ -798,7 +801,7 @@ txn_begin_ro_stmt(struct space *space, struct txn **txn,
                        diag_set(ClientError, ER_TRANSACTION_CONFLICT);
                        return -1;
                }
-               if ((*txn)->is_linearizable &&
+               if (txn_has_flag(*txn, TXN_IS_LINEARIZABLE) &&
                    engine_check_space_linearizability(space->engine,
                                                       space) != 0) {
                        return -1;

```

</details>

File: src/box/box.cc [hunk 15]
```diff
@@ -1805,6 +1805,214 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+		/* Might be already accounted by on_ack trigger. */
+		if (!bit_test(&data.collected_vclock_map, replica->id) &&
+		    sync > 0 && relay_sync(relay) >= sync) {
+			vclock_max_ignore0(confirmed_vclock,
+					   relay_vclock(relay));
+			bit_set(&data.collected_vclock_map, replica->id);
+		}
+	}
+
+	while (bit_count_u32(data.collected_vclock_map) + 1 < vclock_count &&
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1931]: Yes.
Imagine, you have a cluster of 3 nodes, quorum is 2. Then the user sets quorum to 3. It means that linearizable read doesn't need to visit remote nodes anymore to complete. If existing linearizable read requests stopped waiting for vclocks because of quorum increase, it would make them see old data (because there still might be some requests that were on 2 other nodes but haven't yet reached this node).

And vice versa. When out of 3 nodes quorum was 2, and then became 1, we don't have to wait for all 3 nodes. Because at the start of linearizable read quorum was 2, so all the requests that were committed at the moment linearizable read started are definitely on 2 out of 3 replicas.

File: src/box/box.cc (hunk 14 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1912]: Thanks, my bad. I made it return an error instead of throwing.

Will cover it with a test tomorrow.

<details><summary>diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 248aab990..8a793df7d 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1856,12 +1856,11 @@ relay_get_sync_on_start(struct trigger *trigger, void *event)
 	struct sync_trigger_data *data =
 		(struct sync_trigger_data *)trigger->data;
 	uint32_t id = replica->id;
-	try {
-		if (!bit_test(&data->collected_vclock_map, id)) {
-			data->syncs[id] = relay_next_sync(relay,
-							  data->deadline);
-		}
-	} catch (TimedOut *) {
+	/* Already accounted. */
+	if (bit_test(&data->collected_vclock_map, id))
+		return 0;
+	if (relay_next_sync(relay, &data->syncs[id], data->deadline) != 0) {
+		diag_clear(diag_get());
 		data->is_timed_out = true;
 		fiber_wakeup(data->waiter);
 	}
@@ -1907,9 +1906,14 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
 			continue;
 		}
 		/* Might be already filled by on_relay_thread_start trigger. */
-		if (data.syncs[replica->id] == 0) {
-			data.syncs[replica->id] =
-				relay_next_sync(replica->relay, deadline);
+		if (data.syncs[replica->id] != 0)
+			continue;
+		if (relay_next_sync(replica->relay, &data.syncs[replica->id],
+				    deadline) != 0) {
+			/* Timed out. */
+			trigger_clear(&on_ack);
+			trigger_clear(&on_relay_thread_start);
+			return -1;
 		}
 	}
 	replicaset_foreach(replica) {
diff --git a/src/box/relay.cc b/src/box/relay.cc
index b900100be..493c95eba 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -872,8 +872,8 @@ relay_next_sync_f(struct cbus_call_msg *msg)
 	return 0;
 }
 
-uint64_t
-relay_next_sync(struct relay *relay, double deadline)
+int
+relay_next_sync(struct relay *relay, uint64_t *sync, double deadline)
 {
 	struct relay_next_sync_msg *msg =
 		(struct relay_next_sync_msg *)xmalloc(sizeof(*msg));
@@ -882,10 +882,10 @@ relay_next_sync(struct relay *relay, double deadline)
 	if (cbus_call_timeout(&relay->relay_pipe, &relay->tx_pipe, &msg->base,
 			      relay_next_sync_f, relay_next_sync_msg_free,
 			      timeout) < 0)
-		diag_raise();
-	uint64_t sync = msg->sync;
+		return -1;
+	*sync = msg->sync;
 	free(msg);
-	return sync;
+	return 0;
 }
 
 uint64_t
diff --git a/src/box/relay.h b/src/box/relay.h
index eff2eb3d1..927a4e9c9 100644
--- a/src/box/relay.h
+++ b/src/box/relay.h
@@ -101,8 +101,8 @@ double
 relay_txn_lag(const struct relay *relay);
 
 /** Returns the next sync relay is about to send. */
-uint64_t
-relay_next_sync(struct relay *relay, double deadline);
+int
+relay_next_sync(struct relay *relay, uint64_t *sync, double deadline);
 
 /** Returns the last sync received in response from a replica. */
 uint64_t

```

</details>

File: src/box/engine.h (hunk 1 above)
Comment (sergepetrenko) [reply src/box/engine.h:505]: Good idea, will do tomorrow.

**Comment by sergepetrenko** [comment]
@Gerold103 thanks for the review!
I've addressed most of your comments and will return to the remaining ones tomorrow.
Also reworded the commit message:
> From the commit message: "this read request must see the results of that (or any later) write request." - did you mean "or any earlier"?

Yep, sure, thanks for noticing.

And added a paragraph about timing out to doc request.

**Comment by sergepetrenko** [comment]
Checkpatch still fails complaining about result files for some reason.

**Comment by sergos** [comment]
> Checkpatch still fails complaining about result files for some reason.

There is a new rule in checkpatch that prevents new diff tests appearance. Although, there was an [issue](https://github.com/tarantool/checkpatch/issues/35) and a fix is already in the checkpatch master. Perhaps you just have to restart CI - probably after rebase?

**Comment by sergepetrenko** [comment]
> There is a new rule in checkpatch that prevents new diff tests appearance. Although, there was an https://github.com/tarantool/checkpatch/issues/35 and a fix is already in the checkpatch master. Perhaps you just have to restart CI - probably after rebase?

The issue wasn't fixed completely, it seems. I have checkpatch checked out locally at commit
```
commit 418505c89ce5866fc9697a52e0df832b3b35fafb
Author: Sergey Bronnikov <sergeyb@tarantool.org>
Date:   Mon Sep 5 19:13:44 2022 +0300

    Allow updating .result files
```
And still the issue persists. Old checkpatch complained about 3 of my commits, because they changed `test/unit/*.result`
And new checkpatch complains about deletions in `test/box-py/iproto.result`, it seems:
```
-----------------------------------------------------------------
Commit 98691a9d825b ("core: introduce linearizable transactions")
-----------------------------------------------------------------
ERROR: Please avoid new tests with .result files

total: 1 errors, 1346 lines checked
Commit 98691a9d825b ("core: introduce linearizable transactions") has style problems, please review.

```
`git show 98691a9d825b -- *.result` output :
```diff
diff --git a/test/box-py/iproto.result b/test/box-py/iproto.result
index ea32f8bc8..70e37ae57 100644
--- a/test/box-py/iproto.result
+++ b/test/box-py/iproto.result
@@ -129,18 +129,12 @@ space2 = box.schema.create_space('test2')
 ...
 Schema changed -> error: True
 Got another schema_id: True
-Sync ok
-Sync on error is ok
 space:drop()
 ---
 ...
 space2:drop()
 ---
 ...
-box.space._cluster:delete{2} ~= nil
----
-- true
-...
 space = box.schema.create_space('gh1280', { engine = 'vinyl' })
 ---
 ...

```

File: src/box/engine.h (hunk 1 above)
Comment (sergepetrenko) [reply src/box/engine.h:505]: Done.
<details><summary>diff</summary>

```diff
diff --git a/src/box/blackhole.c b/src/box/blackhole.c
index 95e0c7e2d..a7857bf0d 100644
--- a/src/box/blackhole.c
+++ b/src/box/blackhole.c
@@ -198,8 +198,6 @@ static const struct engine_vtab blackhole_engine_vtab = {
 	/* .memory_stat = */ generic_engine_memory_stat,
 	/* .reset_stat = */ generic_engine_reset_stat,
 	/* .check_space_def = */ generic_engine_check_space_def,
-	/* .check_space_linearizability = */
-	generic_engine_check_space_linearizability,
 };
 
 struct engine *
diff --git a/src/box/engine.c b/src/box/engine.c
index c47613731..226cd0f77 100644
--- a/src/box/engine.c
+++ b/src/box/engine.c
@@ -461,14 +461,4 @@ generic_engine_check_space_def(struct space_def *def)
 	return 0;
 }
 
-int
-generic_engine_check_space_linearizability(const struct space *space)
-{
-	(void)space;
-	diag_set(ClientError, ER_UNSUPPORTED,
-		 tt_sprintf("space \"%s\"", space_name(space)),
-		 "linearizable operations");
-	return -1;
-}
-
 /* }}} */
diff --git a/src/box/engine.h b/src/box/engine.h
index e985174c4..13d25aaec 100644
--- a/src/box/engine.h
+++ b/src/box/engine.h
@@ -247,10 +247,6 @@ struct engine_vtab {
 	 * tables.
 	 */
 	int (*check_space_def)(struct space_def *);
-	/**
-	 * Check whether the space may be accessed by linearizable requests.
-	 */
-	int (*check_space_linearizability)(const struct space *space);
 };
 
 enum {
@@ -386,13 +382,6 @@ engine_read_view_delete(struct engine_read_view *rv)
 	rv->vtab->free(rv);
 }
 
-static inline int
-engine_check_space_linearizability(struct engine *engine,
-				   const struct space *space)
-{
-	return engine->vtab->check_space_linearizability(space);
-}
-
 /**
  * Shutdown all engine factories.
  */
@@ -501,8 +490,6 @@ int generic_engine_backup(struct engine *, const struct vclock *,
 void generic_engine_memory_stat(struct engine *, struct engine_memory_stat *);
 void generic_engine_reset_stat(struct engine *);
 int generic_engine_check_space_def(struct space_def *);
-int
-generic_engine_check_space_linearizability(const struct space *space);
 
 #if defined(__cplusplus)
 } /* extern "C" */
diff --git a/src/box/memtx_engine.cc b/src/box/memtx_engine.cc
index 4bb3887f4..8135ae0c9 100644
--- a/src/box/memtx_engine.cc
+++ b/src/box/memtx_engine.cc
@@ -1150,28 +1150,6 @@ memtx_engine_memory_stat(struct engine *engine, struct engine_memory_stat *stat)
 	stat->index += index_stats.totals.used;
 }
 
-/** Check whether the space may be accessed by linearizable operations. */
-static int
-memtx_engine_check_space_linearizability(const struct space *space)
-{
-	/*
-	 * We can't guarantee linearizable access to async spaces. This would
-	 * require checking whether **any** node in the replicaset has
-	 * committed something, which's impossible as soon as at least one node
-	 * becomes unavailable.
-	 * The only exception are local and temporary spaces, which only store
-	 * updates present on this particular node.
-	 */
-	if (!space->def->opts.is_sync && !space->def->opts.is_temporary &&
-	    space->def->opts.group_id != GROUP_LOCAL) {
-		diag_set(ClientError, ER_UNSUPPORTED,
-			 tt_sprintf("space \"%s\"", space_name(space)),
-			 "linearizable operations");
-		return -1;
-	}
-	return 0;
-}
-
 static const struct engine_vtab memtx_engine_vtab = {
 	/* .shutdown = */ memtx_engine_shutdown,
 	/* .create_space = */ memtx_engine_create_space,
@@ -1200,8 +1178,6 @@ static const struct engine_vtab memtx_engine_vtab = {
 	/* .memory_stat = */ memtx_engine_memory_stat,
 	/* .reset_stat = */ generic_engine_reset_stat,
 	/* .check_space_def = */ generic_engine_check_space_def,
-	/* .check_space_linearizability = */
-	memtx_engine_check_space_linearizability,
 };
 
 /**
diff --git a/src/box/service_engine.c b/src/box/service_engine.c
index a505bd6ee..db2fc70aa 100644
--- a/src/box/service_engine.c
+++ b/src/box/service_engine.c
@@ -115,8 +115,6 @@ static const struct engine_vtab service_engine_vtab = {
 	/* .memory_stat = */ generic_engine_memory_stat,
 	/* .reset_stat = */ generic_engine_reset_stat,
 	/* .check_space_def = */ generic_engine_check_space_def,
-	/* .check_space_linearizability = */
-	generic_engine_check_space_linearizability,
 };
 
 struct engine *
diff --git a/src/box/sysview.c b/src/box/sysview.c
index 03bb808d2..112abe96e 100644
--- a/src/box/sysview.c
+++ b/src/box/sysview.c
@@ -587,8 +587,6 @@ static const struct engine_vtab sysview_engine_vtab = {
 	/* .memory_stat = */ generic_engine_memory_stat,
 	/* .reset_stat = */ generic_engine_reset_stat,
 	/* .check_space_def = */ generic_engine_check_space_def,
-	/* .check_space_linearizability = */
-	generic_engine_check_space_linearizability,
 };
 
 struct sysview_engine *
diff --git a/src/box/txn.c b/src/box/txn.c
index 5c8024a74..0af2e5e3b 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -608,7 +608,7 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type)
 	}
 
 	if (space != NULL && txn_has_flag(txn, TXN_IS_LINEARIZABLE) &&
-	    engine_check_space_linearizability(space->engine, space) != 0) {
+	    txn_check_space_linearizability(txn, space) != 0) {
 		return -1;
 	}
 
diff --git a/src/box/txn.h b/src/box/txn.h
index a8a7e4501..2c52c2b8b 100644
--- a/src/box/txn.h
+++ b/src/box/txn.h
@@ -37,6 +37,7 @@
 #include "fiber.h"
 #include "space.h"
 #include "journal.h"
+#include "tt_static.h"
 
 #if defined(__cplusplus)
 extern "C" {
@@ -565,7 +566,7 @@ struct txn {
 };
 
 static inline bool
-txn_has_flag(struct txn *txn, enum txn_flag flag)
+txn_has_flag(const struct txn *txn, enum txn_flag flag)
 {
 	assert((flag & (flag - 1)) == 0);
 	return (txn->flags & flag) != 0;
@@ -782,6 +783,42 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type);
 int
 txn_begin_in_engine(struct engine *engine, struct txn *txn);
 
+static inline int
+txn_check_space_linearizability(const struct txn *txn,
+				const struct space *space)
+{
+	assert(txn_has_flag(txn, TXN_IS_LINEARIZABLE));
+	(void)txn;
+	/*
+	 * XXX: can't promise the user linearizability with Vinyl until
+	 * https://github.com/tarantool/tarantool/issues/5522 is fixed.
+	 * For now it doesn't matter if txn isolation is set, mvcc is turned on
+	 * or the space is synchronous.
+	 */
+	if (!space_is_memtx(space)) {
+		diag_set(ClientError, ER_UNSUPPORTED,
+			 tt_sprintf("space \"%s\"", space_name(space)),
+			 "linearizable operations");
+		return -1;
+	}
+	/*
+	 * We can't guarantee linearizable access to async spaces. This would
+	 * require checking whether **any** node in the replicaset has
+	 * committed something, which's impossible as soon as at least one node
+	 * becomes unavailable.
+	 * The only exception are local and temporary spaces, which only store
+	 * updates present on this particular node.
+	 */
+	if (!space_is_sync(space) && !space_is_temporary(space) &&
+	    !space_is_local(space)) {
+		diag_set(ClientError, ER_UNSUPPORTED,
+			 tt_sprintf("space \"%s\"", space_name(space)),
+			 "linearizable operations");
+		return -1;
+	}
+	return 0;
+}
+
 /**
  * This is an optimization, which exists to speed up selects
  * in autocommit mode. For such selects, we only need to
@@ -802,8 +839,7 @@ txn_begin_ro_stmt(struct space *space, struct txn **txn,
 			return -1;
 		}
 		if (txn_has_flag(*txn, TXN_IS_LINEARIZABLE) &&
-		    engine_check_space_linearizability(space->engine,
-						       space) != 0) {
+		    txn_check_space_linearizability(*txn, space) != 0) {
 			return -1;
 		}
 		struct engine *engine = space->engine;
diff --git a/src/box/vinyl.c b/src/box/vinyl.c
index 956ae3231..f8a4bb916 100644
--- a/src/box/vinyl.c
+++ b/src/box/vinyl.c
@@ -4537,13 +4537,6 @@ static const struct engine_vtab vinyl_engine_vtab = {
 	/* .reset_stat = */ vinyl_engine_reset_stat,
 	/* .check_space_def = */ vinyl_engine_check_space_def,
 	/* .check_space_linearizability = */
-	/*
-	 * XXX: can't promise the user linearizability with Vinyl until
-	 * https://github.com/tarantool/tarantool/issues/5522 is fixed.
-	 * For now it doesn't matter if txn isolation is set, mvcc is turned on
-	 * or the space is synchronous.
-	 */
-	generic_engine_check_space_linearizability,
 };
 
 static const struct space_vtab vinyl_space_vtab = {
```

</details>

File: src/box/box.cc (hunk 14 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc]: Yes, indeed. Now it's possible that we're querying the relays one-by-one and waste all the time on this, even though querying all the relays at once would be much faster

[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc]: Added a test:
<details><summary>test</summary>

```diff
diff --git a/test/replication-luatest/linearizable_read_test.lua b/test/replication-luatest/linearizable_read_test.lua
index a535b76ed..d963d2b58 100644
--- a/test/replication-luatest/linearizable_read_test.lua
+++ b/test/replication-luatest/linearizable_read_test.lua
@@ -80,6 +80,18 @@ g.test_wait_others = function(g)
     t.assert(ok, 'begin() succeeds after replica connections are established')
 end
 
+g.test_timeout = function(g)
+    g.servers[1]:exec(function()
+        local t = require('luatest')
+        box.error.injection.set('ERRINJ_RELAY_FROM_TX_DELAY', true)
+        local ok, err = pcall(box.begin, {linearizable = true, timeout = 0.01})
+        box.error.injection.set('ERRINJ_RELAY_FRMO_TX_DELAY', false)
+        t.assert(not ok, 'Error when relay is unresponsive')
+        t.assert_equals(err.type, 'TimedOut',
+                        'Timeout when relay is unresponsive')
+    end)
+end
+
 g.before_test('test_no_dirty_reads', function(g)
     -- Make cluster size 5. Having quorum 3 out of 5 will make the instance
     -- poll 5 - 3 + 1 == all 3 of the "real" nodes.
```

</details>

**Comment by sergepetrenko** [comment]
@Gerold103, I've adressed all your comments. Please, take a look.

File: src/box/box.cc [hunk 16]
```diff
@@ -1805,6 +1805,218 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+	};
+	struct trigger on_relay_thread_start;
+	trigger_create(&on_relay_thread_start, relay_get_sync_on_start, &data,
+		       NULL);
+	trigger_add(&replicaset.on_relay_thread_start, &on_relay_thread_start);
+	struct trigger on_ack;
+	trigger_create(&on_ack, check_sync_on_ack, &data, NULL);
+	trigger_add(&replicaset.on_ack, &on_ack);
+	replicaset_foreach(replica) {
+		if (relay_get_state(replica->relay) != RELAY_FOLLOW ||
```
Comment (Gerold103) [inline src/box/box.cc:1904]: We are trying to get latest data. Getting data works via appliers. I suppose we use relays here only because they can do the pings, and appliers can only send ACKs, but not request them? Which means the feature works only if the instance, doing the linearizable txn, is also a replication source on at least quorum of nodes, right? Essentially, it can't be used on some rogue (maybe anon) replica to get latest data if the replica itself is not a part of the quorum. Might be worth reflecting in the documentation. But up to you.

File: src/box/box.cc [hunk 17]
```diff
@@ -1805,6 +1805,218 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+		.is_ready = false,
+		.vclock = vclock,
+		.waiter = fiber(),
+	};
+	trigger_create(&on_wal_write, box_wait_vclock_f, &data, NULL);
+	trigger_add(&wal_on_batch_write, &on_wal_write);
+	do {
+		if (fiber_yield_deadline(deadline))
+			break;
+	} while (!data.is_ready);
```
Comment (Gerold103) [inline src/box/box.cc:1994]: Should we also break if the fiber is cancelled? Same for the while-loop in `box_collect_confirmed_vclock()`.

File: src/box/txn.c [hunk 18]
```diff
@@ -681,36 +686,39 @@ txn_commit_stmt(struct txn *txn, struct request *request)
...
+				 * must remain the same
+				 */
+				stmt->does_require_old_tuple = true;
+				txn->space_on_replace_triggers_depth++;
+				int rc = trigger_run(&space->on_replace,
+						     txn);
+				txn->space_on_replace_triggers_depth--;
+				if (rc != 0)
+					goto fail;
+			}
```
Comment (Gerold103) [inline src/box/txn.c:721]: You don't seem to need this refactoring anymore, right?

File: src/box/vinyl.c [hunk 19]
```diff
@@ -4536,6 +4536,7 @@ static const struct engine_vtab vinyl_engine_vtab = {
 	/* .memory_stat = */ vinyl_engine_memory_stat,
 	/* .reset_stat = */ vinyl_engine_reset_stat,
 	/* .check_space_def = */ vinyl_engine_check_space_def,
+	/* .check_space_linearizability = */
```
Comment (Gerold103) [inline src/box/vinyl.c:4539]: Can drop this line now.

File: test/replication-luatest/linearizable_read_test.lua [hunk 20]
```diff
@@ -0,0 +1,273 @@
...
+    g.proxies[1]:pause()
+    local fid = g.servers[1]:exec(function()
+        local t = require('luatest')
+        local f = require('fiber').new(function()
+            return pcall(box.begin, {linearizable = true})
+        end)
+        f:set_joinable(true)
+        t.assert_equals(f:status(), 'suspended', 'begin() waits for replicas')
+        return f:id()
+    end)
```
Comment (Gerold103) [inline test/replication-luatest/linearizable_read_test.lua:73]: I would suggest to add here a little fiber sleep for, say, 0.01 ms and then check that the fiber is not finished yet. That it is actually waiting. Otherwise this test will pass even if `box.begin()` succeeds immediately.

File: test/replication-luatest/linearizable_read_test.lua [hunk 21]
```diff
@@ -0,0 +1,273 @@
...
+    g.servers[1]:exec(function()
+        box.space._cluster:delete{4}
+        box.space._cluster:delete{5}
+    end)
+    g.servers[2]:wait_vclock_of(g.servers[1])
+    g.servers[3]:wait_vclock_of(g.servers[1])
+end)
+
+g.test_no_dirty_reads = function(g)
+    -- So that server 2 doesn't receive acks and thus doesn't confirm the
```
Comment (Gerold103) [inline test/replication-luatest/linearizable_read_test.lua:129]: It seems there is a missing sentence before `-- So ...`.

File: test/replication-luatest/linearizable_read_test.lua [hunk 22]
```diff
@@ -0,0 +1,273 @@
...
+        box.error.injection.set('ERRINJ_RELAY_FROM_TX_DELAY', false)
+        t.assert(not ok, 'Error when relay is unresponsive')
+        t.assert_equals(err.type, 'TimedOut',
+                        'Timeout when relay is unresponsive')
+    end)
+end
+
+g.before_test('test_no_dirty_reads', function(g)
+    -- Make cluster size 5. Having quorum 3 out of 5 will make the instance
+    -- poll 5 - 3 + 1 == all 3 of the "real" nodes.
```
Comment (Gerold103) [inline test/replication-luatest/linearizable_read_test.lua:97]: You could also keep cluster size 3 and block server1<->server3 connection via the proxy. Then server1 would have to wait for server2.

**Review by Gerold103 — COMMENTED** [review]
Thanks for the fixes, nice work!

File: src/box/wal.c (hunk 10 above)
Comment (Gerold103) [reply src/box/wal.c:379]: > You see, the problem is that watcher is notified first and only then tx_complete_batch message is sent. So by the time watcher is notified in tx, fresh vclock is not yet delivered there. So I can't check if target vclock is reached or not in watcher callback.

Upon receipt of WAL notification you can do `wal_sync()` in `box_wait_vclock()` to ensure the vclock is up to date, and then read it.

As for having a global watcher with all waiters - AFAIU the problem is only that watcher attachment is expensive due to cbus_pair/unpair things, right? Maybe it could be simplified to be able attach without pairing the current thread with WAL thread? Then you could have "small" single-fiber watchers for each such txn.

I am not insisting on it. The current version also works. As for performance - after the current version surely it wouldn't get better. Currently `trigger_run()` even for an empty list will try to run 2 loops. It is also not too good for the branch predictor because these loops are not always empty or always full. It might affect perf under insane load like say 1kk txns per second. Nonetheless, I am fine with that. Up to you if you want to try the WAL watchers way.

File: src/box/box.cc (hunk 15 above)
[the remark this answers is not in the document]
Comment (Gerold103) [reply src/box/box.cc:1935]: Thanks for the explanation, sounds legit.

File: src/box/box.cc (hunk 14 above)
[the remark this answers is not in the document]
Comment (Gerold103) [reply src/box/box.cc]: Probably :) Still I wouldn't count on that, but can keep it like now too.

File: src/box/applier.cc (hunk 12 above)
[the remark this answers is not in the document]
Comment (Gerold103) [reply src/box/applier.cc:1525]: Why the last row wouldn't be enough though?

[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/applier.cc:1525]: It would. I just didn't want to fetch the last row one more time. (It's done already in applier_apply_tx).
But I guess this doesn't matter much, so changed:
<details><summary>diff</summary>

```diff
diff --git a/src/box/applier.cc b/src/box/applier.cc
index 28ad0a430..f0d782e98 100644
--- a/src/box/applier.cc
+++ b/src/box/applier.cc
@@ -1285,8 +1285,6 @@ applier_apply_tx(struct applier *applier, struct stailq *rows)
        struct xrow_header *first_row = &txr->row;
        struct xrow_header *last_row;
        last_row = &stailq_last_entry(rows, struct applier_tx_row, next)->row;
-       if (applier_process_sync(applier, last_row->sync) != 0)
-               return -1;
        struct replica *replica = replica_by_id(first_row->replica_id);
        int rc = 0;
        /*
@@ -1517,14 +1515,14 @@ applier_process_batch(struct cmsg *base)
        struct applier *applier = msg->base.applier;
        struct applier_tx *tx;
        stailq_foreach_entry(tx, &msg->txs, next) {
-               struct applier_tx_row *txr =
-                       stailq_first_entry(&tx->rows, struct applier_tx_row,
-                                           next);
+               struct applier_tx_row *last_txr =
+                       stailq_last_entry(&tx->rows, struct applier_tx_row,
+                                         next);
                raft_process_heartbeat(box_raft(), applier->instance_id);
-               if (applier_process_sync(applier, txr->row.sync) != 0)
+               if (applier_process_sync(applier, last_txr->row.sync) != 0)
                        diag_raise();
-               if (txr->row.lsn == 0) {
-                       if (applier_handle_raft(applier, txr) != 0)
+               if (last_txr->row.lsn == 0) {
+                       if (applier_handle_raft(applier, last_txr) != 0)
                                diag_raise();
                        applier_signal_ack(applier);
                        applier_check_sync(applier);
```

</details>

File: src/box/wal.c (hunk 10 above)
Comment (sergepetrenko) [reply src/box/wal.c:379]: > Upon receipt of WAL notification you can do wal_sync() in box_wait_vclock() to ensure the vclock is up to date, and then read it.

I'll have to do it in `box_wait_vclock`, i.e. in the waiting fiber, not in the watcher callback. Because watcher callback is fired by sched fiber. Besides, I already know the new vclock in the waiting fiber. Because by the time it's woken up the fresh vclock is delivered.

The problem I wanted to point out was that the callback doesn't know if the target vclock is reached or not, and has to wake every waiter on every batch return from wal. Which is also suboptimal. We could as well make all waiters sleep for 0.01 seconds or something in a busy loop.

Now, as for small per-fiber watchers, I don't see how we can avoid doing a cbus_call to WAL to attach the watcher.
If a watcher is attached per each new linearizable request, this will clog the WAL thread queue.
Because wathcer attaches are not batched into a single cbus message like transactions.

Long story short, watcher is a good idea only if it knows which vclock was reached in its callback. Our watcher doesn't know that, so has to wake up all waiters (even with your idea about wal_sync). In this case I think that doing a `sleep(0.01)` loop without any watchers is better. Because it's much simpler, and it results in almost the same sleeps and wake-ups for waiting fibers.

Although we could try to make watchers deliver written vclock to tx thread. Do you see any problems with that?

If the watcher knows the vclock, it will wake only the necessary waiters. We will have a single watcher for all waiters, and there will be no penalty for simple transactions when no linearizable transactions are in flight.

File: src/box/applier.cc [hunk 23]
```diff
@@ -1237,6 +1238,23 @@ applier_synchro_filter_tx(struct stailq *rows)
 	}
 }
 
+/** Remember the sync coming with current row to use it in future ACKs. */
+static inline int
+applier_process_sync(struct applier *applier, uint64_t sync)
+{
+	if (sync == 0)
+		return 0;
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/applier.cc:1246]: Yes, it's not needed right now, with both old and new tarantool masters, but I'd rather leave it here. This way `sync` may become optional in future. For example, master may send a new sync only when it has pending linearizable transactions

File: src/box/applier.cc [hunk 24]
```diff
@@ -1363,6 +1384,7 @@ applier_thread_signal_ack(struct cmsg *base)
 	fiber_cond_signal(&applier->thread.writer_cond);
 	applier->thread.has_acks_to_send = true;
 	applier->thread.txn_last_tm = msg->txn_last_tm;
+	applier->thread.last_sync = msg->sync;
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/applier.cc:1387]: You're correct, but this is fine.

Let's for simplicity call the moment, when a linearizable request is started, a `start`.
Let's call the master a node performing a linearizable transaction. So it issues a request with some `sync` and waits for vclocks in response with the same sync.

Having a `sync` in request and response guarantees, that an ACK coming with that `sync` was surely sent **after** `start`. This is enough. This means that `ack_vclock` coming together with that `sync` in an ACK **was** the greatest vclock replica has ever reported to anyone  at the moment of `start`.

Now, when we have `replication_connect_quorum = Q`, master receives `N - Q + 1` acks with sync.
At least one of `ack_vclock`s contains everything that **was** committed at the moment of `start`. Because at least one of `N - Q + 1` nodes must have ACKed the committed transaction.

To be more precise, we need componentwise max of `ack_vclock`s and name it `max_vclock`.

This all, in turn, means, that even if some other master has committed something **before** `start`, this something is surely reflected in `max_vclock`. And once we wait for this vclock, we have reached the linearization point.

P.S. of course, at the moment of responding to master's request, replica might already be writing something new. But this something is guaranteed to commit later, than `start`. So we don't care about seeing it.

File: src/box/box.cc (hunk 16 above)
Comment (sergepetrenko) [reply src/box/box.cc:1904]: Good point, I'll write a couple of words about that in the doc request:

```
    Note: starting a linearizable transaction requires that the node is the
    replication **source** for at least N - Q + 1 remote replicas. Here `N` is
    the count of registered nodes in the cluster and `Q` is
    `replication_synchro_quorum` value (the same as
    `box.info.synchro.quorum`). This is the implementation limitation. For
    example, you may start linearizable transactions on any node of a
    cluster in full-mesh topology, but you can't perform linearizable
    transactions on anonymous replicas, because noone replicates **from**
    them.

```

File: src/box/box.cc (hunk 17 above)
Comment (sergepetrenko) [reply src/box/box.cc:1994]: Yes, probably. Altough `relay_next_sync` can't be interrupted anyway. Because `cbus_call_timeout` can't.
But you're right. We should at least let the user cancel the fiber while it waits for already known syncs or vclocks.

<details><summary>diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 8a793df7d..6a1485a5d 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1933,13 +1934,18 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
 	}
 
 	while (bit_count_u32(data.collected_vclock_map) + 1 < vclock_count &&
-	       !data.is_timed_out) {
+	       !data.is_timed_out && !fiber_is_cancelled()) {
 		if (fiber_yield_deadline(deadline))
 			break;
 	}
 
 	trigger_clear(&on_ack);
 	trigger_clear(&on_relay_thread_start);
+	if (fiber_is_cancelled()) {
+		diag_set(ClientError, ER_QUORUM_WAIT, vclock_count,
+			 "fiber is cancelled");
+		return -1;
+	}
 	if (bit_count_u32(data.collected_vclock_map) + 1 < vclock_count) {
 		diag_set(ClientError, ER_QUORUM_WAIT, vclock_count,
 			 "timed out waiting for remote node vclocks");
@@ -1991,10 +1997,16 @@ box_wait_vclock(const struct vclock *vclock, double deadline)
 	do {
 		if (fiber_yield_deadline(deadline))
 			break;
-	} while (!data.is_ready);
+	} while (!data.is_ready && !fiber_is_cancelled());
 	trigger_clear(&on_wal_write);
+	if (fiber_is_cancelled()) {
+		diag_set(ClientError, ER_VCLOCK_WAIT, vclock_to_string(vclock),
+			 "fiber is cancelled");
+		return -1;
+	}
 	if (!data.is_ready) {
-		diag_set(ClientError, ER_TIMEOUT);
+		diag_set(ClientError, ER_VCLOCK_WAIT, vclock_to_string(vclock),
+			 "timed out");
 		return -1;
 	}
 	return 0;
diff --git a/src/box/errcode.h b/src/box/errcode.h
index 733d3f137..4f5f7ef73 100644
--- a/src/box/errcode.h
+++ b/src/box/errcode.h
@@ -297,6 +297,7 @@ struct errcode_record {
 	/*242 */_(ER_NO_ELECTION_QUORUM,	"Not enough peers connected to start elections: %d out of minimal required %d")\
 	/*243 */_(ER_SSL,			"%s") \
 	/*244 */_(ER_SPLIT_BRAIN,		"Split-Brain discovered: %s") \
+	/*245 */_(ER_VCLOCK_WAIT,		"Failed to wait for vclock %s: %s")\
 
 /*
  * !IMPORTANT! Please follow instructions at start of the file
```
</details>

File: src/box/txn.c (hunk 18 above)
Comment (sergepetrenko) [reply src/box/txn.c:721]: Yep. Sorry I missed thatn

File: src/box/vinyl.c (hunk 19 above)
Comment (sergepetrenko) [reply src/box/vinyl.c:4539]: Thanks, my bad.

File: src/box/wal.c (hunk 10 above)
Comment (sergepetrenko) [reply src/box/wal.c:379]: > If the watcher knows the vclock, it will wake only the necessary waiters. We will have a single watcher for all waiters, and there will be no penalty for simple transactions when no linearizable transactions are in flight.

I can try to make `tx_complete_batch` be sent earlier than wal_watcher_notify. Then watcher callback will know the actual vclock by the time it's scheduled.

File: test/replication-luatest/linearizable_read_test.lua (hunk 20 above)
Comment (sergepetrenko) [reply test/replication-luatest/linearizable_read_test.lua:73]: Good idea, done:
```diff
diff --git a/test/replication-luatest/linearizable_read_test.lua b/test/replication-luatest/linearizable_read_test.lua
index bc8a3ae58..494d107ba 100644
--- a/test/replication-luatest/linearizable_read_test.lua
+++ b/test/replication-luatest/linearizable_read_test.lua
@@ -64,10 +64,12 @@ g.test_wait_others = function(g)
     g.proxies[1]:pause()
     local fid = g.servers[1]:exec(function()
         local t = require('luatest')
-        local f = require('fiber').new(function()
+        local fiber = require('fiber')
+        local f = fiber.new(function()
             return pcall(box.begin, {linearizable = true})
         end)
         f:set_joinable(true)
+        fiber.sleep(0.01)
         t.assert_equals(f:status(), 'suspended', 'begin() waits for replicas')
         return f:id()
     end)
```

File: test/replication-luatest/linearizable_read_test.lua (hunk 21 above)
Comment (sergepetrenko) [reply test/replication-luatest/linearizable_read_test.lua:129]: I just removed this comment. `replication_synchro_quorum` is made 4 on server2 in `before_test`. So this commen must relate to that. I think it's excess.

File: src/box/wal.c (hunk 10 above)
Comment (sergepetrenko) [reply src/box/wal.c:379]: > I will try to make tx_complete_batch be sent earlier than wal_watcher_notify. Then watcher callback will know the actual vclock by the time it's scheduled.

Here's how it looks like (not pushed here yet, because I'm still trying to rework the watcher to use existing pipes)

<details><summary>diff</summary>

```diff
diff --git a/src/box/wal.c b/src/box/wal.c
index dae8e5f1d..af7a6ae29 100644
--- a/src/box/wal.c
+++ b/src/box/wal.c
@@ -219,7 +219,10 @@ static void
 tx_complete_batch(struct cmsg *msg);
 
 static struct cmsg_hop wal_request_route[] = {
-	{wal_write_to_disk, &wal_writer_singleton.tx_prio_pipe},
+	{wal_write_to_disk, NULL},
+};
+
+static struct cmsg_hop wal_response_route[] ={
 	{tx_complete_batch, NULL},
 };
 
@@ -236,7 +239,8 @@ wal_msg_create(struct wal_msg *batch)
 static struct wal_msg *
 wal_msg(struct cmsg *msg)
 {
-	return msg->route == wal_request_route ? (struct wal_msg *) msg : NULL;
+	return msg->route == wal_request_route ||
+	       msg->route == wal_response_route ? (struct wal_msg *) msg : NULL;
 }
 
 /** Write a request to a log in a single transaction. */
@@ -1174,8 +1178,15 @@ done:
 		assert(err_code == JOURNAL_ENTRY_ERR_UNKNOWN);
 	}
 	fiber_gc();
+	cmsg_init(msg, wal_response_route);
+	ERRINJ_NOT_SET(ERRINJ_RELAY_FASTER_THAN_TX, {
+		cpipe_push(&writer->tx_prio_pipe, msg);
+	});
 	wal_notify_watchers(writer, WAL_EVENT_WRITE);
-	ERROR_INJECT_SLEEP(ERRINJ_RELAY_FASTER_THAN_TX);
+	ERROR_INJECT(ERRINJ_RELAY_FASTER_THAN_TX, {
+		ERROR_INJECT_SLEEP(ERRINJ_RELAY_FASTER_THAN_TX);
+		cpipe_push(&writer->tx_prio_pipe, msg);
+	});
 }
 
 /** WAL writer main loop.  */
diff --git a/src/lib/core/errinj.h b/src/lib/core/errinj.h
index f015c9354..221eae5f4 100644
--- a/src/lib/core/errinj.h
+++ b/src/lib/core/errinj.h
@@ -202,6 +202,7 @@ void errinj_set_with_environment_vars(void);
 #  define ERROR_INJECT_WHILE(ID, CODE)
 #  define errinj(ID, TYPE) ((struct errinj *) NULL)
 #  define ERROR_INJECT_COUNTDOWN(ID, CODE)
+#  define ERRINJ_NOT_SET(ID, CODE) CODE
 #else
 #  /* Returns the error injection by id */
 #  define errinj(ID, TYPE) \
@@ -233,6 +234,12 @@ void errinj_set_with_environment_vars(void);
 			CODE;						\
 		}							\
 	} while (0)
+#  define ERRINJ_NOT_SET(ID, CODE)			\
+	do {						\
+		if (!errinj(ID, ERRINJ_BOOL)->bparam) {	\
+			CODE;				\
+		}					\
+	} while (0)
 #endif
 
 #define ERROR_INJECT_RETURN(ID) ERROR_INJECT(ID, return -1)

```
</details>

Comment (sergepetrenko) [reply src/box/wal.c:379]: As I've written in the chat, `wal_watcher` rework turned out quite badly.
`wal_watcher` owns `cpipe`s to WAL and back to watcher. TX thread already has a pipe to and from WAL, and using separate pipes for the watcher is not an option: watcher notification has to arrive via the same pipe as tx batch return.
Otherwise watcher notification and tx batch return are unordered, which makes the watcher pointless. It might be notified before vclock is updated.

Leaving watcher rework aside, the patch about making the watcher always notified **after** tx batch return is still quite ugly (see in the comment above).

Now about the watcher rework: I have to introduce some `light_watcher`, which doesn't own cpipes. This results in either a lot of code duplication or ugly attempts to reuse code for regular and light watchers.

Long story short, I propose to go back to fiber sleep loop. No on_batch_return triggers, no watchers.
This is almost busy waiting, but it's much simpler, and it has no performance impact on "normal" transactions.

File: test/replication-luatest/linearizable_read_test.lua (hunk 22 above)
Comment (sergepetrenko) [reply test/replication-luatest/linearizable_read_test.lua:99]: Yes, but then I'd have to use 2 separate proxies between server1<>server2 and server1<>server3.

Currently proxies[3] blocks server3 relays and server1 appliers.
And proxies[1] blocks all server1 relays.

So it seems easier for me to make the node poll every other node.

Also, I could set `replication_synchro_quorum` to 1 on server1. It would make it query 3 - 1 + 1 = 3. Everyone.
But I decided to use a less hacky way to set `replication_connect_quorum`. Who knows, maybe one day quorum will always be the majority.

Anyway, I'm fine with setting quorum to 1 on server1, if you want me to

File: src/box/wal.c (hunk 10 above)
Comment (sergepetrenko) [reply src/box/wal.c:379]: After some more discussions in chat decided to leave the current approach with on_batch_write triggers.

**Comment by sergepetrenko** [comment]
I've made some changes to the last commit after a self-review:
<details><summary>diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 46333d95e..ff0d72968 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1819,6 +1819,8 @@ struct sync_trigger_data {
 	struct vclock *vclock;
 	/** The request deadline. */
 	double deadline;
+	/** How many vclocks are needed. */
+	int count;
 	/** Whether the request is timed out. */
 	bool is_timed_out;
 };
@@ -1836,11 +1838,14 @@ check_sync_on_ack(struct trigger *trigger, void *event)
 		(struct sync_trigger_data *)trigger->data;
 	uint32_t id = ack->source;
 	uint64_t sync = data->syncs[id];
+	int accounted_count = bit_count_u32(data->collected_vclock_map) + 1;
 	if (!bit_test(&data->collected_vclock_map, id) && sync > 0 &&
-	    ack->sync >= sync) {
+	    ack->sync >= sync && accounted_count < data->count) {
 		vclock_max_ignore0(data->vclock, ack->vclock);
 		bit_set(&data->collected_vclock_map, id);
-		fiber_wakeup(data->waiter);
+		++accounted_count;
+		if (accounted_count >= data->count)
+			fiber_wakeup(data->waiter);
 	}
 	return 0;
 }
@@ -1891,6 +1896,7 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
 		.waiter = fiber(),
 		.vclock = confirmed_vclock,
 		.deadline = deadline,
+		.count = vclock_count,
 		.is_timed_out = false,
 	};
 	struct trigger on_relay_thread_start;
@@ -1916,21 +1922,6 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
 			return -1;
 		}
 	}
-	replicaset_foreach(replica) {
-		if (relay_get_state(replica->relay) != RELAY_FOLLOW ||
-		    replica->anon)
-			continue;
-		uint64_t sync = data.syncs[replica->id];
-		struct relay *relay = replica->relay;
-
-		/* Might be already accounted by on_ack trigger. */
-		if (!bit_test(&data.collected_vclock_map, replica->id) &&
-		    sync > 0 && relay_sync(relay) >= sync) {
-			vclock_max_ignore0(confirmed_vclock,
-					   relay_vclock(relay));
-			bit_set(&data.collected_vclock_map, replica->id);
-		}
-	}
 
 	while (bit_count_u32(data.collected_vclock_map) + 1 < vclock_count &&
 	       !data.is_timed_out && !fiber_is_cancelled()) {
diff --git a/src/box/engine.c b/src/box/engine.c
index 226cd0f77..90a301f74 100644
--- a/src/box/engine.c
+++ b/src/box/engine.c
@@ -33,8 +33,6 @@
 #include <stdint.h>
 #include <string.h>
 #include <small/rlist.h>
-#include "space.h"
-#include "tt_static.h"
 
 RLIST_HEAD(engines);
 
diff --git a/src/box/iproto_constants.c b/src/box/iproto_constants.c
index ede6512f7..f2c37e279 100644
--- a/src/box/iproto_constants.c
+++ b/src/box/iproto_constants.c
@@ -153,7 +153,7 @@ const unsigned char iproto_key_type[IPROTO_KEY_MAX] =
 	/* 0x57 */	MP_STR, /* IPROTO_EVENT_KEY */
 	/* 0x58 */	MP_NIL, /* IPROTO_EVENT_DATA (can be any) */
 	/* 0x59 */	MP_UINT, /* IPROTO_TXN_ISOLATION */
-	/* 0x60 */	MP_BOOL, /* IPROTO_LINEARIZABLE_READ */
+	/* 0x60 */	MP_BOOL, /* IPROTO_TXN_IS_LINEARIZABLE */
 	/* }}} */
 };
 
diff --git a/src/box/relay.cc b/src/box/relay.cc
index d68c81a5d..9f5851010 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -112,7 +112,7 @@ struct relay {
 	struct iostream *io;
 	/** Request sync */
 	uint64_t sync;
-	/** Biggest sync already received from the replica. */
+	/** Biggest sync already received in response from the replica. */
 	uint64_t recv_sync;
 	/** Recovery instance to read xlog from the disk */
 	struct recovery *r;
@@ -196,7 +196,7 @@ struct relay {
 		 * from TX thread only.
 		 */
 		double txn_lag;
-		/** Known sync received from replica. */
+		/** Known sync received in response from replica. */
 		uint64_t sync;
 		/**
 		 * True if the relay needs Raft updates. It can live fine
@@ -806,7 +806,6 @@ relay_send_heartbeat_on_timeout(struct relay *relay)
 	    now - relay->tx_seen_time >= replication_disconnect_timeout())
 		return;
 	relay_send_heartbeat(relay);
-	relay->need_new_heartbeat = false;
 }
 
 static void
@@ -1097,6 +1096,7 @@ relay_send(struct relay *relay, struct xrow_header *packet)
 	packet->sync = ++relay->sync;
 	relay->last_row_time = ev_monotonic_now(loop());
 	coio_write_xrow(relay->io, packet);
+	relay->need_new_heartbeat = false;
 	fiber_gc();
 
 	struct errinj *inj = errinj(ERRINJ_RELAY_TIMEOUT, ERRINJ_DOUBLE);

```
</details>

File: src/box/wal.c (hunk 10 above)
Comment (Gerold103) [reply src/box/wal.c:379]: Thanks for trying.

File: src/box/applier.cc (hunk 24 above)
[the remark this answers is not in the document]
Comment (Gerold103) [reply src/box/applier.cc:1385]: Thanks for the explanation .Sounds edgy, but ok.

File: src/box/box.cc (hunk 16 above)
Comment (Gerold103) [reply src/box/box.cc:1910]: Hm, TBH this scheme looks quite unnatural. The channel is reversed. Did you think about trying to implement mutual syncs for applier<->relay pair? So as not only relay would send syncs, but also applier could send them at least on demand? Maybe it wouldn't be too complicated?

In future it could also be of use in general too. Applier, by getting vclock of the remote replication source, could estimate and report how big is the gap and reflect it in `box.info.replication`.

File: test/replication-luatest/linearizable_read_test.lua (hunk 22 above)
Comment (Gerold103) [reply test/replication-luatest/linearizable_read_test.lua:99]: Oh, somewhy I had an impression that your proxy schema was `server1 <-> proxyN <-> serverN` with N >= 2. But if server1 has only one front proxy, then lets leave the cluster size 5.

File: src/box/iproto_constants.h [hunk 25]
```diff
@@ -154,6 +154,8 @@ enum iproto_key {
 	IPROTO_EVENT_DATA = 0x58,
 	/** Isolation level, is used only by IPROTO_BEGIN request. */
 	IPROTO_TXN_ISOLATION = 0x59,
+	/** Linearizability flag, used only by IPROTO_BEGIN request. */
+	IPROTO_TXN_IS_LINEARIZABLE = 0x60,
```
Comment (Gerold103) [inline src/box/iproto_constants.h:158]: Forgot to document the protocol change.

File: src/box/relay.cc [hunk 26]
```diff
@@ -813,6 +845,56 @@ relay_thread_on_stop(void *arg)
...
+	m->sync = m->relay->sync + 1;
+	m->relay->need_new_heartbeat = true;
+	return 0;
+}
+
+int
+relay_next_sync(struct relay *relay, uint64_t *sync, double deadline)
+{
+	struct relay_next_sync_msg *msg =
+		(struct relay_next_sync_msg *)xmalloc(sizeof(*msg));
```
Comment (Gerold103) [inline src/box/relay.cc:880]: If you want to mAkE sOmE cOoL oPtImIsAtIoNs to improve batching, then you could make this `relay_next_sync_msg` a part of `struct relay` instead of allocating it on the heap. And it would work like iproto kharon and applier ack - go back and forth on demand. As a bonus, it could then be reused by multiple linerizable txns requesting next sync at the same time. If a txn comes and sees the sync req is not yet sent, then it pushes the message. If txns come and see the req is already sent, then they set a flag in relay that the msg should be re-sent and wait for it being re-sent and re-delivered.

When sync returns to tx thread, the first txn takes it and leaves. The others together re-request the sync. When it returns, they also all take it and leave.

Current approach is fine too, although not so good for batching. My only worry is that if relay thread is busy for too long, then there can be quite a lot of timed out 'next_sync' calls which leave `relay_next_sync_msg` garbage allocated on the heap until they complete.

Can leave it as is if you want.

File: src/box/wal.c [hunk 27]
```diff
@@ -63,6 +63,8 @@ const char *wal_mode_STRS[WAL_MODE_MAX] = {
 
 int wal_dir_lock = -1;
 
+struct rlist wal_on_batch_write = RLIST_HEAD_INITIALIZER(wal_on_batch_write);
```
Comment (Gerold103) [inline src/box/wal.c:66]: You might want to destroy this list in `wal_free()`.

File: src/box/box.cc [hunk 28]
```diff
@@ -1805,6 +1805,220 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+	if (replica->anon)
+		return 0;
+	struct relay *relay = replica->relay;
+	struct sync_trigger_data *data =
+		(struct sync_trigger_data *)trigger->data;
+	uint32_t id = replica->id;
+	/* Already accounted. */
+	if (bit_test(&data->collected_vclock_map, id))
+		return 0;
+	if (relay_next_sync(relay, &data->syncs[id], data->deadline) != 0) {
```
Comment (Gerold103) [inline src/box/box.cc:1867]: I added an `assert(false)` here and the tests passed. Maybe worth adding a test, at least a small simple one?

**Review by Gerold103 — COMMENTED** [review]
Thanks for the fixes, nice! I don't think I see any bugs here, but can a few give other comments.

File: src/box/wal.c (hunk 27 above)
Comment (sergepetrenko) [reply src/box/wal.c:66]: Thanks!
```diff
diff --git a/src/box/wal.c b/src/box/wal.c
index dae8e5f1d..aa9440682 100644
--- a/src/box/wal.c
+++ b/src/box/wal.c
@@ -594,6 +594,8 @@ wal_free(void)
                panic_syserror("WAL writer: thread join failed");
        }
 
+       trigger_destroy(&wal_on_batch_write);
+
        wal_writer_destroy(writer);
 }
 
```

File: src/box/iproto_constants.h (hunk 25 above)
Comment (sergepetrenko) [reply src/box/iproto_constants.h:158]: Yep, fixed:
```
    The binary protocol receives the same change. `IPROTO_BEGIN` command now
    has a new key: `IPROTO_TXN_IS_LINEARIZABLE = 0x60`. This key holds a
    `BOOL` value. When the value is true, transaction becomes linearizable.
    When the key is omitted or the value is false, transaction is not
    linearizable.

```

File: src/box/box.cc (hunk 28 above)
Comment (sergepetrenko) [reply src/box/box.cc:1867]: I added a test: seems `relay_get_sync_on_start` wasn't tested at all.
I only tested the success route though, because making `relay_next_sync` timeout in `relay_get_sync_on_start` before the waiting times out in `box_collect_confirmed_vclock` is tricky.
<details><summary>diff</summary>

```diff
diff --git a/test/replication-luatest/linearizable_read_test.lua b/test/replication-luatest/linearizable_read_test.lua
index d6ef275e4..33c48a4ce 100644
--- a/test/replication-luatest/linearizable_read_test.lua
+++ b/test/replication-luatest/linearizable_read_test.lua
@@ -1,9 +1,10 @@
 local t = require('luatest')
 local cluster = require('test.luatest_helpers.cluster')
 local server = require('test.luatest_helpers.server')
+local proxy = require('test.luatest_helpers.proxy.proxy')
 local g = t.group('linearizable-read')
 
-local proxy = require('test.luatest_helpers.proxy.proxy')
+local fiber = require('fiber')
 
 local function build_replication(num_instances)
     local t = {}
@@ -18,7 +19,7 @@ local num_servers = 3
 g.before_all(function()
     g.cluster = cluster:new({})
     g.servers = {}
-    local box_cfg = {
+    g.box_cfg = {
         replication = build_replication(num_servers),
         replication_timeout = 0.1,
         txn_isolation = 'read-confirmed',
@@ -26,16 +27,16 @@ g.before_all(function()
     }
     g.servers[1] = g.cluster:build_and_add_server({
         alias = 'server_1',
-        box_cfg = box_cfg,
+        box_cfg = g.box_cfg,
     })
     -- Servers 2 and 3 are interconnected without a proxy.
     for i = 2, num_servers do
-        box_cfg.replication[i] = server.build_instance_uri('server_' .. i)
+        g.box_cfg.replication[i] = server.build_instance_uri('server_' .. i)
     end
     for i = 2, num_servers do
         g.servers[i] = g.cluster:build_and_add_server({
             alias = 'server_' .. i,
-            box_cfg = box_cfg,
+            box_cfg = g.box_cfg,
         })
     end
     g.proxies = {}
@@ -148,6 +149,32 @@ g.test_no_dirty_reads = function(g)
     end)
 end
 
+g.test_reconnect_while_waiting = function(g)
+    for i = 2, 3 do
+        g.servers[i]:exec(function()
+            local repl = table.copy(box.cfg.replication)
+            table.remove(repl, 1)
+            box.cfg{replication = repl}
+        end)
+    end
+    local f = fiber.new(g.servers[1].exec, g.servers[1], function()
+        local ok, err = pcall(box.begin, {linearizable = true})
+        if ok then
+            box.commit()
+        end
+        return ok, err
+    end)
+    f:set_joinable(true)
+    for i = 2, 3 do
+        g.servers[i]:exec(function(repl)
+            box.cfg{replication = repl}
+        end, {g.box_cfg.replication})
+    end
+    local success, ok, err = f:join()
+    t.assert(success, 'fiber joined successfully')
+    t.assert(ok, 'reconnect while begin() waits for vclocks is tolerated')
+end
+
 g.test_leader_change = function(g)
     g.servers[1]:exec(function()
         box.ctl.promote()
```
</details>

**Comment by sergepetrenko** [comment]
I've found a bug: my implementation only waited until the transaction, which might be confirmed, reaches the node. But it didn't wait until this transaction is actually confirmed. Which is wrong.
Fixed the bug and reworked the corresponding test a bit (there was a testcase which tested the wrong behaviour):
<details><summary>diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index ff0d72968..2e9f8ff47 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -2012,9 +2012,23 @@ box_wait_linearization_point(double timeout)
 	double deadline = ev_monotonic_now(loop()) + timeout;
 	struct vclock confirmed_vclock;
 	vclock_create(&confirmed_vclock);
-	if (box_collect_confirmed_vclock(&confirmed_vclock, deadline) < 0)
+	/*
+	 * First find out the vclock which might be confirmed on remote
+	 * instances.
+	 */
+	if (box_collect_confirmed_vclock(&confirmed_vclock, deadline) != 0)
 		return -1;
-	if (box_wait_vclock(&confirmed_vclock, deadline) < 0)
+	/* Then wait until all the rows up to this vclock are received. */
+	if (box_wait_vclock(&confirmed_vclock, deadline) != 0)
+		return -1;
+	/*
+	 * Finally, wait until all the synchronous transactions, which should be
+	 * visible to this tx, become visible.
+	 */
+	bool is_rollback;
+	timeout = deadline - ev_monotonic_now(loop());
+	if (!txn_limbo_is_empty(&txn_limbo) &&
+	    txn_limbo_wait_last_txn(&txn_limbo, &is_rollback, timeout) != 0)
 		return -1;
 	return 0;
 }
diff --git a/src/box/txn_limbo.c b/src/box/txn_limbo.c
index f1dc62aa1..acdde6695 100644
--- a/src/box/txn_limbo.c
+++ b/src/box/txn_limbo.c
@@ -694,10 +694,7 @@ txn_rollback_cb(struct trigger *trigger, void *event)
 	return 0;
 }
 
-/**
- * Wait until the last transaction in the limbo is finished and get its result.
- */
-static int
+int
 txn_limbo_wait_last_txn(struct txn_limbo *limbo, bool *is_rollback,
 			double timeout)
 {
diff --git a/src/box/txn_limbo.h b/src/box/txn_limbo.h
index 5fb858295..bf64804da 100644
--- a/src/box/txn_limbo.h
+++ b/src/box/txn_limbo.h
@@ -391,6 +391,13 @@ txn_limbo_process(struct txn_limbo *limbo, const struct synchro_request *req);
 int
 txn_limbo_wait_confirm(struct txn_limbo *limbo);
 
+/**
+ * Wait until the last transaction in the limbo is finished and gets its result.
+ */
+int
+txn_limbo_wait_last_txn(struct txn_limbo *limbo, bool *is_rollback,
+			double timeout);
+
 /** Wait until the limbo is empty. Regardless of how its transactions end. */
 int
 txn_limbo_wait_empty(struct txn_limbo *limbo, double timeout);
diff --git a/test/replication-luatest/linearizable_read_test.lua b/test/replication-luatest/linearizable_read_test.lua
index d87a9c100..02fde2771 100644
--- a/test/replication-luatest/linearizable_read_test.lua
+++ b/test/replication-luatest/linearizable_read_test.lua
@@ -104,11 +104,8 @@ g.before_test('test_no_dirty_reads', function(g)
         box.space._cluster:insert{5, tostring(uuid.new())}
     end)
     g.servers[2]:wait_vclock_of(g.servers[1])
-    g.replication_synchro_quorum = g.servers[2]:exec(function()
+    g.servers[2]:exec(function()
         box.ctl.promote()
-        local q = box.cfg.replication_synchro_quorum
-        box.cfg{replication_synchro_quorum = 4}
-        return q
     end)
     g.servers[1]:wait_vclock_of(g.servers[2])
     g.servers[3]:wait_vclock_of(g.servers[2])
@@ -116,9 +113,8 @@ end)
 
 g.after_test('test_no_dirty_reads', function(g)
     g.servers[2]:exec(function(q)
-        box.cfg{replication_synchro_quorum = q}
         box.ctl.demote()
-    end, {g.replication_synchro_quorum})
+    end)
     g.servers[1]:wait_vclock_of(g.servers[2])
     g.servers[1]:exec(function()
         box.space._cluster:delete{4}
@@ -129,12 +125,27 @@ g.after_test('test_no_dirty_reads', function(g)
 end)
 
 g.test_no_dirty_reads = function(g)
-    g.servers[2]:exec(function()
+    g.replication_synchro_quorum = g.servers[2]:exec(function()
         local t = require('luatest')
         local lsn = box.info.lsn
+        local q = box.cfg.replication_synchro_quorum
+        box.cfg{replication_synchro_quorum = 4}
         require('fiber').new(box.space.sync.insert, box.space.sync, {1})
         t.helpers.retrying({}, function() assert(box.info.lsn > lsn) end)
+        return q
     end)
+    g.servers[1]:exec(function()
+        local t = require('luatest')
+        local ok, err = pcall(box.begin, {linearizable = true, timeout = 0.1})
+        t.assert(not ok, 'Error with unconfirmed transaction')
+        t.assert_equals(err.type, 'TimedOut', 'Timeout waiting for confirm')
+        t.assert_equals(box.info.synchro.queue.len, 1,
+                        'Pending transaction is seen')
+        t.assert_equals(box.space.sync:get{1}, nil, 'No dirty reads')
+    end)
+    g.servers[2]:exec(function(q)
+        box.cfg{replication_synchro_quorum = q}
+    end, {g.replication_synchro_quorum})
     g.servers[1]:exec(function()
         local t = require('luatest')
         box.begin{linearizable = true}
@@ -144,8 +155,8 @@ g.test_no_dirty_reads = function(g)
         -- If the assertion fails before box.commit(), ER_FUNCTION_TX_ACTIVE
         -- shadows the real error. So save the values inside the txn and check
         -- them outside.
-        t.assert_equals(len, 1, 'Pending transaction is seen')
-        t.assert_equals(get, nil, 'No dirty reads')
+        t.assert_equals(len, 0, 'Waited for confirm')
+        t.assert_equals(get, {1}, 'Confirmed data is seen')
     end)
 end

```
</details>

File: src/box/relay.cc (hunk 26 above)
Comment (sergepetrenko) [reply src/box/relay.cc:880]: Yes, it's a good idea, but I'd rather not do that now. As we've discussed in the RFC, linearizable transactions aren't supposed to be fast. I think it's better to concentrate on correctness rather than speed right now.

File: src/box/wal.c (hunk 27 above)
Comment (locker) [inline src/box/wal.c:66]: Nit: You could write:

```C
struct RLIST_HEAD(wal_on_batch_write);
```

Maybe, name it simply `wal_on_write`? (Looks like there's no such thing as non-batch write.)

Also, the declaration needs a comment that triggers are actually invoked in tx, upon confirming a write.

File: test/replication-luatest/suite.ini [hunk 29]
```diff
@@ -2,4 +2,4 @@
 core = luatest
 description = replication luatests
 is_parallel = True
-release_disabled = gh_5295_split_brain_test.lua gh_6036_qsync_order_test.lua gh_6842_qsync_applier_order_test.lua gh_6033_box_promote_demote_test.lua gh_7253_election_long_wal_write_test.lua
+release_disabled = gh_5295_split_brain_test.lua gh_6036_qsync_order_test.lua gh_6842_qsync_applier_order_test.lua gh_6033_box_promote_demote_test.lua gh_7253_election_long_wal_write_test.lua linearizable_read_test.lua
```
Comment (locker) [inline test/replication-luatest/suite.ini:5]: Nit: Maybe better use this in test code instead:

https://github.com/tarantool/tarantool/blob/7f52f445ed4c3b0f12665de5ae712653591d79b1/test/luatest_helpers/misc.lua#L15

File: changelogs/unreleased/linearizable-read.md [hunk 30]
```diff
@@ -0,0 +1,5 @@
+## feature/core
+
+* Introduced linearizable transactions: turned on by `box.begin{linearizable =
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply changelogs/unreleased/linearizable-read.md:3]: > Anyway, since it requires read-confirmed (strictest so far) isolation level to be set (according to the doc request), why not introduce a new isolation level instead - isolation_level = 'linearizable'?

I thought about it as well, but decided that 'linearizable' is not an isolation level, after all.
IMO isolation levels are about how transactions performed on one instance see each other's changes, while linearizability is about seeing changes performed on other instances.

Anyway, I'm not against it, but I think I'll have to ask products about that.

[the remark this answers is not in the document]
Comment (sergepetrenko) [reply changelogs/unreleased/linearizable-read.md:3]: > In the doc bot request the option is named linearizable_read.

Thanks for noticing! Fixed.

File: src/box/box.cc [hunk 31]
```diff
@@ -1805,6 +1805,234 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+	trigger_create(&on_wal_write, box_wait_vclock_f, &data, NULL);
+	trigger_add(&wal_on_batch_write, &on_wal_write);
+	do {
+		if (fiber_yield_deadline(deadline))
+			break;
+	} while (!data.is_ready && !fiber_is_cancelled());
+	trigger_clear(&on_wal_write);
+	if (fiber_is_cancelled()) {
+		diag_set(ClientError, ER_VCLOCK_WAIT, vclock_to_string(vclock),
+			 "fiber is cancelled");
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1994]: Don't we want to be more verbose?

Anyway, I did that to conform to `box_wait_quorum`:
https://github.com/tarantool/tarantool/blob/60702571bec60c85d5e919e02dbf21bfa21de4e9/src/box/box.cc#L1794-L1797
https://github.com/tarantool/tarantool/blob/60702571bec60c85d5e919e02dbf21bfa21de4e9/src/box/box.cc#L1799-L1803

Should I change these places as well?

File: src/box/applier.cc [hunk 32]
```diff
@@ -1237,6 +1238,23 @@ applier_synchro_filter_tx(struct stailq *rows)
...
 }
 
+/** Remember the sync coming with current row to use it in future ACKs. */
+static inline int
+applier_process_sync(struct applier *applier, uint64_t sync)
+{
+	if (sync == 0)
+		return 0;
+	if (applier->last_sync > sync) {
+		diag_set(ClientError, ER_UNSUPPORTED, "replication",
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/applier.cc:1248]: Sure. Fixed.
<details><summary>diff</summary>

```diff
diff --git a/src/box/applier.cc b/src/box/applier.cc
index f0d782e98..0703ea8eb 100644
--- a/src/box/applier.cc
+++ b/src/box/applier.cc
@@ -1245,9 +1245,9 @@ applier_process_sync(struct applier *applier, uint64_t sync)
        if (sync == 0)
                return 0;
        if (applier->last_sync > sync) {
-               diag_set(ClientError, ER_UNSUPPORTED, "replication",
-                        tt_sprintf("doesn't support non-monotonic sync value: "
-                                   "previous: %" PRIu64 ", new: %" PRIu64,
+               diag_set(ClientError, ER_PROTOCOL,
+                        tt_sprintf("Non-monotonic sync value. Old: "
+                                   "%" PRIu64 ", new: %" PRIu64,
                                    applier->last_sync, sync));
                return -1;
        }
```
</details>

File: src/box/wal.c (hunk 27 above)
Comment (sergepetrenko) [reply src/box/wal.c:66]: <details><summary>Done:</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index a980a8e3d..8b8c7594a 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1983,7 +1983,7 @@ box_wait_vclock(const struct vclock *vclock, double deadline)
                .waiter = fiber(),
        };
        trigger_create(&on_wal_write, box_wait_vclock_f, &data, NULL);
-       trigger_add(&wal_on_batch_write, &on_wal_write);
+       trigger_add(&wal_on_write, &on_wal_write);
        do {
                if (fiber_yield_deadline(deadline))
                        break;
diff --git a/src/box/wal.c b/src/box/wal.c
index aa9440682..59d249cd3 100644
--- a/src/box/wal.c
+++ b/src/box/wal.c
@@ -63,7 +63,7 @@ const char *wal_mode_STRS[WAL_MODE_MAX] = {
 
 int wal_dir_lock = -1;
 
-struct rlist wal_on_batch_write = RLIST_HEAD_INITIALIZER(wal_on_batch_write);
+RLIST_HEAD(wal_on_write);
 
 static int
 wal_write_async(struct journal *, struct journal_entry *);
@@ -376,7 +376,7 @@ tx_complete_batch(struct cmsg *msg)
        /* Update the tx vclock to the latest written by wal. */
        vclock_copy(&replicaset.vclock, &batch->vclock);
        tx_schedule_queue(&batch->commit);
-       trigger_run(&wal_on_batch_write, NULL);
+       trigger_run(&wal_on_write, NULL);
        mempool_free(&writer->msg_pool, container_of(msg, struct wal_msg, base));
 }
 
@@ -594,7 +594,7 @@ wal_free(void)
                panic_syserror("WAL writer: thread join failed");
        }
 
-       trigger_destroy(&wal_on_batch_write);
+       trigger_destroy(&wal_on_write);
 
        wal_writer_destroy(writer);
 }
diff --git a/src/box/wal.h b/src/box/wal.h
index 7185d56bc..8940416aa 100644
--- a/src/box/wal.h
+++ b/src/box/wal.h
@@ -77,9 +77,10 @@ extern const char *wal_mode_STRS[];
 extern int wal_dir_lock;
 
 /**
- * Triggers invoked after WAL write confirmation for a batch of transactions.
+ * Triggers ivoked by tx thread's sched fiber upon WAL write confirmation
+ * arrival.
  */
-extern struct rlist wal_on_batch_write;
+extern struct rlist wal_on_write;
 
 #if defined(__cplusplus)
 extern "C" {
```
</details>

File: src/box/box.cc [hunk 33]
```diff
@@ -1805,6 +1805,234 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+		return -1;
+	}
+	return 0;
+}
+
+int
+box_wait_linearization_point(double timeout)
+{
+	if (timeout < 0) {
+		diag_set(ClientError, ER_TIMEOUT);
```
[the remark this answers is not in the document]
Comment (locker) [reply src/box/box.cc:2009]: > The code below (`fiber_yield_deadline()`) will still yield even if deadline is in the past, AFAICS.

But AFAICS nothing bad would happen in this case so I wouldn't bother. You don't bother checking the deadline in `box_collect_confirmed_vclock` BTW.

Unrelated: I think that you should explicitly mention in the documentation that `box.begin()` can yield now. (It's not quite obvious from the doc bot request.)

File: src/box/box.cc (hunk 31 above)
[the remark this answers is not in the document]
Comment (locker) [reply src/box/box.cc:1994]: > Don't we want to be more verbose?

I don't see a reason to be more verbose in case the fiber is cancelled. You can check file/line set in diag to figure out where exactly it was cancelled. I don't think that we should use different kinds of errors for this. BTW you use plain `ER_TIMEOUT` in case of timeout. Using plain `FiberIsCancelled` would only be consistent with that.

> https://github.com/tarantool/tarantool/blob/60702571bec60c85d5e919e02dbf21bfa21de4e9/src/box/box.cc#L1794-L1797

I'd change this place to use `FiberIsCancelled` as well.

File: test/replication-luatest/suite.ini (hunk 29 above)
Comment (sergepetrenko) [reply test/replication-luatest/suite.ini:5]: I didn't know about that, thanks!
```diff
diff --git a/test/replication-luatest/linearizable_read_test.lua b/test/replication-luatest/linearizable_read_test.lua
index d20420b1d..e6373dd0e 100644
--- a/test/replication-luatest/linearizable_read_test.lua
+++ b/test/replication-luatest/linearizable_read_test.lua
@@ -1,4 +1,5 @@
 local t = require('luatest')
+local misc = require('test.luatest_helpers.misc')
 local cluster = require('test.luatest_helpers.cluster')
 local server = require('test.luatest_helpers.server')
 local proxy = require('test.luatest_helpers.proxy.proxy')
@@ -84,6 +85,7 @@ g.test_wait_others = function(g)
 end
 
 g.test_timeout = function(g)
+    misc.skip_if_not_debug()
     g.servers[1]:exec(function()
         local t = require('luatest')
         box.error.injection.set('ERRINJ_RELAY_FROM_TX_DELAY', true)
diff --git a/test/replication-luatest/suite.ini b/test/replication-luatest/suite.ini
index 2c9ca5557..c2805362f 100644
--- a/test/replication-luatest/suite.ini
+++ b/test/replication-luatest/suite.ini
@@ -2,4 +2,4 @@
 core = luatest
 description = replication luatests
 is_parallel = True
-release_disabled = gh_5295_split_brain_test.lua gh_6036_qsync_order_test.lua gh_6842_qsync_applier_order_test.lua gh_6033_box_promote_demote_test.lua gh_7253_election_long_wal_write_test.lua linearizable_read_test.lua
+release_disabled = gh_5295_split_brain_test.lua gh_6036_qsync_order_test.lua gh_6842_qsync_applier_order_test.lua gh_6033_box_promote_demote_test.lua gh_7253_election_long_wal_write_test.lua
```

File: src/box/lua/schema.lua [hunk 34]
```diff
@@ -411,6 +414,12 @@ box.begin = function(options)
         if txn_isolation ~= nil then
             txn_isolation = normalize_txn_isolation_level(txn_isolation)
         end
+        linearizable = options.linearizable
+        if linearizable ~= nil and
+           type(linearizable) ~= 'boolean' then
+            box.error(box.error.ILLEGAL_PARAMS,
+                      "linearizable must be a boolean")
+        end
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/lua/schema.lua:422]: Good idea, haven't thought of that.
Done in a new commit:
<details><summary>diff</summary>

```diff
commit e9ca65ca3a7c71c786ca9a8fd11798037ea52161
Author: Serge Petrenko <sergepetrenko@tarantool.org>
Date:   Wed Sep 14 13:15:24 2022 +0300

    box: refactor box.begin() options validation
    
    Reuse check_param_table() funciton in box begin instead of some custom
    parameter checking code.
    As one of the side effects, unknown options are now declined by
    `box.begin{}`, which becomes more and more important with new options
    introduction.
    
    In-scope-of #6707
    
    NO_DOC=refactoring
    NO_CHANGELOG=refactoring

diff --git a/src/box/lua/schema.lua b/src/box/lua/schema.lua
index 51a44d99e..864dd4a81 100644
--- a/src/box/lua/schema.lua
+++ b/src/box/lua/schema.lua
@@ -397,21 +397,22 @@ end
 
 box.internal.normalize_txn_isolation_level = normalize_txn_isolation_level
 
-box.begin = function(options)
-    local timeout
-    local txn_isolation
-    if options then
-        check_param(options, 'options', 'table')
-        timeout = options.timeout
-        if timeout and (type(timeout) ~= "number" or timeout <= 0) then
+local begin_options = {
+    timeout = function(timeout)
+        if type(timeout) ~= "number" or timeout <= 0 then
             box.error(box.error.ILLEGAL_PARAMS,
                       "timeout must be a number greater than 0")
         end
-        txn_isolation = options.txn_isolation
-        if txn_isolation ~= nil then
-            txn_isolation = normalize_txn_isolation_level(txn_isolation)
-        end
-    end
+        return true
+    end,
+    txn_isolation = normalize_txn_isolation_level,
+}
+
+box.begin = function(options)
+    check_param_table(options, begin_options)
+    local timeout = options and options.timeout
+    local txn_isolation = options and options.txn_isolation and
+                          normalize_txn_isolation_level(options.txn_isolation)
     if builtin.box_txn_begin() == -1 then
         box.error()
     end
diff --git a/test/box-luatest/begin_options_validation_test.lua b/test/box-luatest/begin_options_validation_test.lua
new file mode 100644
index 000000000..b044dd610
--- /dev/null
+++ b/test/box-luatest/begin_options_validation_test.lua
@@ -0,0 +1,23 @@
+local server = require("test.luatest_helpers.server")
+local t = require("luatest")
+
+local g = t.group("begin-options-validation")
+
+g.before_all = function()
+    g.server = server:new{
+        alias = "default",
+    }
+    g.server:start()
+end
+
+g.after_all = function()
+    g.server:drop()
+end
+
+g.test_begin_options_validation = function()
+    g.server:exec(function()
+        require("luatest").assert_error_msg_content_equals(
+            "Illegal parameters, unexpected option 'foo'",
+            box.begin, {foo = "bar"})
+    end)
+end

```
</details>

File: src/box/space.h [hunk 35]
```diff
@@ -309,6 +309,17 @@ space_is_temporary(const struct space *space)
 	return space->def->opts.is_temporary;
 }
 
+/** Return true if space is local. */
+bool
+space_is_local(const struct space *space);
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/space.h:314]: Done.
Also moved `GROUP_LOCAL` definition to `iproto_constants.h`.

File: changelogs/unreleased/linearizable-read.md (hunk 30 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply changelogs/unreleased/linearizable-read.md:3]: > why not introduce a new isolation level instead - isolation_level = 'linearizable'?

Agreed and done:
<details><summary>diff</summary>

```diff
diff --git a/extra/exports b/extra/exports
index 83d08f7a2..607c2fe3d 100644
--- a/extra/exports
+++ b/extra/exports
@@ -138,7 +138,6 @@ box_txn_rollback_to_savepoint
 box_txn_savepoint
 box_txn_set_isolation
 box_txn_set_timeout
-box_txn_make_linearizable
 box_update
 box_upsert
 clock_monotonic
diff --git a/src/box/box.cc b/src/box/box.cc
index 317dce225..c79efd6e9 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1377,6 +1377,12 @@ box_check_txn_isolation(void)
 			 "to 'default'");
 		return txn_isolation_level_MAX;
 	}
+	if (level == TXN_ISOLATION_LINEARIZABLE) {
+		diag_set(ClientError, ER_CFG, "txn_isolation",
+			 "cannot set default transaction isolation "
+			 "to 'linearizable'");
+		return txn_isolation_level_MAX;
+	}
 	return (enum txn_isolation_level)level;
 }
 
diff --git a/src/box/iproto.cc b/src/box/iproto.cc
index ef544bc9f..4dec89211 100644
--- a/src/box/iproto.cc
+++ b/src/box/iproto.cc
@@ -1977,12 +1977,6 @@ tx_process_begin(struct cmsg *m)
 		(void)rc;
 		goto error;
 	}
-	if (msg->begin.is_linearizable && box_txn_make_linearizable() != 0) {
-		int rc = box_txn_rollback();
-		assert(rc == 0);
-		(void)rc;
-		goto error;
-	}
 	out = msg->connection->tx.p_obuf;
 	header = obuf_create_svp(out);
 	iproto_reply_ok(out, msg->header.sync, ::schema_version);
diff --git a/src/box/lua/schema.lua b/src/box/lua/schema.lua
index 33e143c90..f5f045a68 100644
--- a/src/box/lua/schema.lua
+++ b/src/box/lua/schema.lua
@@ -76,8 +76,6 @@ ffi.cdef[[
     box_txn_set_timeout(double timeout);
     int
     box_txn_set_isolation(uint32_t level);
-    int
-    box_txn_make_linearizable(void);
     void
     memtx_tx_story_gc_step();
     /** \endcond public */
@@ -370,6 +368,8 @@ box.txn_isolation_level = {
     ['READ_CONFIRMED'] = 2,
     ['best-effort'] = 3,
     ['BEST_EFFORT'] = 3,
+    ['linearizable'] = 4,
+    ['LINEARIZABLE'] = 4,
 }
 
 -- Create private isolation level map anything-correct -> number.
@@ -388,6 +388,9 @@ box.internal.txn_isolation_level_map = txn_isolation_level_map
 
 -- Convert to numeric the value of txn isolation level, raise if failed.
 local function normalize_txn_isolation_level(txn_isolation)
+    if txn_isolation == nil then
+        return 0
+    end
     txn_isolation = txn_isolation_level_map[txn_isolation]
     if txn_isolation == nil then
         box.error(box.error.ILLEGAL_PARAMS,
@@ -408,19 +411,15 @@ local begin_options = {
         return true
     end,
     txn_isolation = normalize_txn_isolation_level,
-    linearizable = 'boolean',
 }
 
 box.begin = function(options)
     check_param_table(options, begin_options)
     local timeout
     local txn_isolation
-    local linearizable
     if options then
         timeout = options.timeout
-        txn_isolation = options.txn_isolation and
-                        normalize_txn_isolation_level(options.txn_isolation)
-        linearizable = options.linearizable
+        txn_isolation = options.txn_isolation
     end
     if builtin.box_txn_begin() == -1 then
         box.error()
@@ -428,12 +427,9 @@ box.begin = function(options)
     if timeout then
         assert(builtin.box_txn_set_timeout(timeout) == 0)
     end
-    if txn_isolation and
-       builtin.box_txn_set_isolation(txn_isolation) ~= 0 then
-        box.rollback()
-        box.error()
-    end
-    if linearizable and builtin.box_txn_make_linearizable() ~= 0 then
+    txn_isolation = normalize_txn_isolation_level(txn_isolation)
+    assert(txn_isolation ~= nil)
+    if builtin.box_txn_set_isolation(txn_isolation) ~= 0 then
         box.rollback()
         box.error()
     end
diff --git a/src/box/memtx_tx.c b/src/box/memtx_tx.c
index bb0db2a20..432d0e7ad 100644
--- a/src/box/memtx_tx.c
+++ b/src/box/memtx_tx.c
@@ -2415,7 +2415,8 @@ detect_whether_prepared_ok(struct txn *txn)
 		return false;
 	else if (txn->isolation == TXN_ISOLATION_READ_COMMITTED)
 		return true;
-	else if (txn->isolation == TXN_ISOLATION_READ_CONFIRMED)
+	else if (txn->isolation == TXN_ISOLATION_READ_CONFIRMED ||
+		 txn->isolation == TXN_ISOLATION_LINEARIZABLE)
 		return false;
 	assert(txn->isolation == TXN_ISOLATION_BEST_EFFORT);
 	/*
diff --git a/src/box/txn.c b/src/box/txn.c
index cee5d3feb..2eb6046e2 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -54,6 +54,7 @@ const char *txn_isolation_level_strs[txn_isolation_level_MAX] = {
 	"READ_COMMITTED",
 	"READ_CONFIRMED",
 	"BEST_EFFORT",
+	"LINEARIZABLE",
 };
 
 const char *txn_isolation_level_aliases[txn_isolation_level_MAX] = {
@@ -61,6 +62,7 @@ const char *txn_isolation_level_aliases[txn_isolation_level_MAX] = {
 	"read-committed",
 	"read-confirmed",
 	"best-effort",
+	"linearizable"
 };
 
 /* Txn cache. */
@@ -607,7 +609,7 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type)
 		txn_set_flags(txn, TXN_IS_CONFLICTED);
 	}
 
-	if (space != NULL && txn_has_flag(txn, TXN_IS_LINEARIZABLE) &&
+	if (space != NULL && txn_is_linearizable(txn) &&
 	    txn_check_space_linearizability(txn, space) != 0) {
 		return -1;
 	}
@@ -1370,6 +1372,18 @@ box_txn_set_timeout(double timeout)
 	return 0;
 }
 
+/** Wait for a linearization point for a transaction. */
+static int
+txn_make_linearizable(struct txn *txn)
+{
+	if (!memtx_tx_manager_use_mvcc_engine) {
+		diag_set(ClientError, ER_UNSUPPORTED, "Linearizable "
+			 "transaction", "disabled memtx mvcc engine");
+		return -1;
+	}
+	return box_wait_linearization_point(txn->timeout);
+}
+
 int
 box_txn_set_isolation(uint32_t level)
 {
@@ -1390,35 +1404,8 @@ box_txn_set_isolation(uint32_t level)
 	if (level == TXN_ISOLATION_DEFAULT)
 		level = txn_default_isolation;
 	txn->isolation = level;
-	return 0;
-}
-
-int
-box_txn_make_linearizable(void)
-{
-	struct txn *txn = in_txn();
-	if (txn == NULL) {
-		diag_set(ClientError, ER_NO_TRANSACTION);
-		return -1;
-	}
-	if (!stailq_empty(&txn->stmts)) {
-		diag_set(ClientError, ER_ACTIVE_TRANSACTION);
-		return -1;
-	}
-	if (txn->isolation != TXN_ISOLATION_READ_CONFIRMED) {
-		diag_set(ClientError, ER_UNSUPPORTED,
-			 "Linearizable transaction",
-			 "anything but read-confirmed isolation");
-		return -1;
-	}
-	if (!memtx_tx_manager_use_mvcc_engine) {
-		diag_set(ClientError, ER_UNSUPPORTED, "Linearizable "
-			 "transaction", "disabled memtx mvcc engine");
-		return -1;
-	}
-	if (box_wait_linearization_point(txn->timeout) != 0)
-		return -1;
-	txn_set_flags(txn, TXN_IS_LINEARIZABLE);
+	if (level == TXN_ISOLATION_LINEARIZABLE)
+		return txn_make_linearizable(txn);
 	return 0;
 }
 
diff --git a/src/box/txn.h b/src/box/txn.h
index df662e1cb..2a2fd053d 100644
--- a/src/box/txn.h
+++ b/src/box/txn.h
@@ -102,11 +102,6 @@ enum txn_flag {
 	 * rolled back at commit.
 	 */
 	TXN_IS_ABORTED_BY_TIMEOUT = 0x100,
-	/**
-	 * Transaction is linearizable, so it can only touch certain types of
-	 * spaces (synchronous ones, for example).
-	 */
-	TXN_IS_LINEARIZABLE = 0x200,
 };
 
 enum {
@@ -175,6 +170,8 @@ enum txn_isolation_level {
 	TXN_ISOLATION_READ_CONFIRMED,
 	/** Determine isolation level automatically. */
 	TXN_ISOLATION_BEST_EFFORT,
+	/** Allow to read only the changes confirmed on any cluster node. */
+	TXN_ISOLATION_LINEARIZABLE,
 	/** Upper bound of valid values. */
 	txn_isolation_level_MAX,
 };
@@ -783,6 +780,12 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type);
 int
 txn_begin_in_engine(struct engine *engine, struct txn *txn);
 
+static inline bool
+txn_is_linearizable(const struct txn *txn)
+{
+	return txn->isolation == TXN_ISOLATION_LINEARIZABLE;
+}
+
 /**
  * Check if a space supports linearizable access, i.e. it is either synchronous
  * or not replicated at all, and its engine prevents dirty reads.
@@ -791,7 +794,7 @@ static inline int
 txn_check_space_linearizability(const struct txn *txn,
 				const struct space *space)
 {
-	assert(txn_has_flag(txn, TXN_IS_LINEARIZABLE));
+	assert(txn_is_linearizable(txn));
 	(void)txn;
 	/*
 	 * XXX: can't promise the user linearizability with Vinyl until
@@ -842,7 +845,7 @@ txn_begin_ro_stmt(struct space *space, struct txn **txn,
 			diag_set(ClientError, ER_TRANSACTION_CONFLICT);
 			return -1;
 		}
-		if (txn_has_flag(*txn, TXN_IS_LINEARIZABLE) &&
+		if (txn_is_linearizable(*txn) &&
 		    txn_check_space_linearizability(*txn, space) != 0) {
 			return -1;
 		}
@@ -1040,14 +1043,6 @@ box_txn_set_timeout(double timeout);
 API_EXPORT int
 box_txn_set_isolation(uint32_t level);
 
-/**
- * Make the transaction linearizable.
- * @retval  0 on success
- * @retval -1 on failure, diag is set.
- */
-API_EXPORT int
-box_txn_make_linearizable(void);
-
 /** \endcond public */
 
 typedef struct txn_savepoint box_txn_savepoint_t;
diff --git a/test/replication-luatest/linearizable_read_test.lua b/test/replication-luatest/linearizable_test.lua
similarity index 90%
rename from test/replication-luatest/linearizable_read_test.lua
rename to test/replication-luatest/linearizable_test.lua
index e6373dd0e..a342e1a4b 100644
--- a/test/replication-luatest/linearizable_read_test.lua
+++ b/test/replication-luatest/linearizable_test.lua
@@ -23,7 +23,6 @@ g.before_all(function()
     g.box_cfg = {
         replication = build_replication(num_servers),
         replication_timeout = 0.1,
-        txn_isolation = 'read-confirmed',
         memtx_use_mvcc_engine = true,
     }
     g.servers[1] = g.cluster:build_and_add_server({
@@ -68,7 +67,7 @@ g.test_wait_others = function(g)
         local t = require('luatest')
         local fiber = require('fiber')
         local f = fiber.new(function()
-            return pcall(box.begin, {linearizable = true})
+            return pcall(box.begin, {txn_isolation = 'linearizable'})
         end)
         f:set_joinable(true)
         fiber.sleep(0.01)
@@ -89,7 +88,8 @@ g.test_timeout = function(g)
     g.servers[1]:exec(function()
         local t = require('luatest')
         box.error.injection.set('ERRINJ_RELAY_FROM_TX_DELAY', true)
-        local ok, err = pcall(box.begin, {linearizable = true, timeout = 0.01})
+        local ok, err = pcall(box.begin, {txn_isolation = 'linearizable',
+                                          timeout = 0.01})
         box.error.injection.set('ERRINJ_RELAY_FROM_TX_DELAY', false)
         t.assert(not ok, 'Error when relay is unresponsive')
         t.assert_equals(err.type, 'TimedOut',
@@ -138,7 +138,8 @@ g.test_no_dirty_reads = function(g)
     end)
     g.servers[1]:exec(function()
         local t = require('luatest')
-        local ok, err = pcall(box.begin, {linearizable = true, timeout = 0.1})
+        local ok, err = pcall(box.begin, {txn_isolation = 'linearizable',
+                                          timeout = 0.1})
         t.assert(not ok, 'Error with unconfirmed transaction')
         t.assert_equals(err.type, 'TimedOut', 'Timeout waiting for confirm')
         t.assert_equals(box.info.synchro.queue.len, 1,
@@ -150,7 +151,7 @@ g.test_no_dirty_reads = function(g)
     end, {g.replication_synchro_quorum})
     g.servers[1]:exec(function()
         local t = require('luatest')
-        box.begin{linearizable = true}
+        box.begin{txn_isolation = 'linearizable'}
         local len = box.info.synchro.queue.len
         local get = box.space.sync:get{1}
         box.commit()
@@ -171,7 +172,7 @@ g.test_reconnect_while_waiting = function(g)
         end)
     end
     local f = fiber.new(g.servers[1].exec, g.servers[1], function()
-        local ok, err = pcall(box.begin, {linearizable = true})
+        local ok, err = pcall(box.begin, {txn_isolation = 'linearizable'})
         if ok then
             box.commit()
         end
@@ -203,7 +204,7 @@ g.test_leader_change = function(g)
     end)
     local fid = g.servers[1]:exec(function()
         local f = require('fiber').new(function()
-            box.begin{linearizable = true}
+            box.begin{txn_isolation = 'linearizable'}
             local owner = box.info.synchro.queue.owner
             local get = box.space.sync:get{2}
             box.commit()
@@ -261,14 +262,14 @@ local function begin(opts)
 end
 
 local function linearizable_read_from_space(spacename)
-    box.begin{linearizable = true, txn_isolation = 'read-confirmed'}
+    box.begin{txn_isolation = 'linearizable'}
     local ok, err = pcall(box.space[spacename].select, box.space[spacename])
     box.commit()
     return ok, err
 end
 
 local function linearizable_write_to_space(spacename)
-    box.begin{linearizable = true, txn_isolation = 'read-confirmed'}
+    box.begin{txn_isolation = 'linearizable'}
     local ok, err = pcall(box.space[spacename].replace,
                           box.space[spacename], {1})
     box.commit()
@@ -291,13 +292,13 @@ local function test_linearizable_access(node, spacename, is_ok, msg)
 end
 
 g_basic.test_basic = function(g)
-    local ok, err = g.nomvcc:exec(begin, {{linearizable = true}})
-    t.assert(not ok, 'Error without read-confirmed isolatoin')
-    t.assert_equals(err.message, 'Linearizable transaction does not support ' ..
-                                 'anything but read-confirmed isolation',
-                    'Correct error without read-confirmed isolation')
-    ok, err = g.nomvcc:exec(begin, {{linearizable = true,
-                                     txn_isolation = 'read-confirmed'}})
+    local ok, err = pcall(box.cfg, {txn_isolation = 'linearizable'})
+    t.assert(not ok, 'Cannot set default isolation level to linearizable')
+    local msg = "Incorrect value for option 'txn_isolation': cannot set " ..
+                "default transaction isolation to 'linearizable'"
+    t.assert_equals(err.message, msg,
+                    'Correct error when trying to set default isolation')
+    ok, err = g.nomvcc:exec(begin, {{txn_isolation = 'linearizable'}})
     t.assert(not ok, 'Error without mvcc enabled')
     t.assert_equals(err.message, 'Linearizable transaction does not support ' ..
                                  'disabled memtx mvcc engine',

```

</details>

File: src/box/box.cc (hunk 33 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:2009]: > Unrelated: I think that you should explicitly mention in the documentation that box.begin() can yield now. (It's not quite obvious from the doc bot request.)

Done:
```
When called with `{txn_isolation = 'linearizable'}`, `box.begin()`
yields until the instance receives enough data from remote peers to be
sure that the transaction is linearizable.
```

File: src/box/box.cc (hunk 31 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1994]: > I don't see a reason to be more verbose in case the fiber is cancelled. You can check file/line set in diag to figure out where exactly it was cancelled

I left a more detailed error in case of timeout. I think a user needs to know why the request timed out. Maybe the node was waiting for an unrealistic vclock or maybe it was waiting for too many responces.

<details><summary>diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index c79efd6e9..571803816 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1938,8 +1938,7 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
        trigger_clear(&on_ack);
        trigger_clear(&on_relay_thread_start);
        if (fiber_is_cancelled()) {
-               diag_set(ClientError, ER_QUORUM_WAIT, vclock_count,
-                        "fiber is cancelled");
+               diag_set(FiberIsCancelled);
                return -1;
        }
        if (bit_count_u32(data.collected_vclock_map) + 1 < vclock_count) {
@@ -1996,8 +1995,7 @@ box_wait_vclock(const struct vclock *vclock, double deadline)
        } while (!data.is_ready && !fiber_is_cancelled());
        trigger_clear(&on_wal_write);
        if (fiber_is_cancelled()) {
-               diag_set(ClientError, ER_VCLOCK_WAIT, vclock_to_string(vclock),
-                        "fiber is cancelled");
+               diag_set(FiberIsCancelled);
                return -1;
        }
        if (!data.is_ready) {

```

</details>

File: src/box/applier.h [hunk 36]
```diff
@@ -122,6 +122,8 @@ struct applier_ack_msg {
 	double txn_last_tm;
 	/** Replicaset vclock. */
 	struct vclock vclock;
+	/** The sync this message corresponds to. */
+	uint64_t sync;
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/applier.h]: As discussed, I've put the code regarding `vclock_sync` in a separate commit.
The vclock_sync field is encoded in row body, not header, and is sent only in heartbeats, and a heartbeat for the next vclock sync is always sent right away.

File: src/box/relay.h [hunk 37]
```diff
@@ -100,6 +100,14 @@ relay_last_row_time(const struct relay *relay);
 double
 relay_txn_lag(const struct relay *relay);
 
+/** Returns the next sync relay is about to send. */
+int
+relay_next_sync(struct relay *relay, uint64_t *sync, double deadline);
+
+/** Returns the last sync received in response from a replica. */
+uint64_t
+relay_sync(const struct relay *relay);
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/relay.h]: Reworked in a separate commit. Please, take a look.

File: src/box/relay.cc [hunk 38]
```diff
@@ -742,9 +769,16 @@ relay_reader_f(va_list ap)
 static inline void
 relay_send_heartbeat(struct relay *relay)
 {
+	if (relay->is_sending_tx)
+		return;
```
Comment (locker) [inline src/box/relay.cc:773]: Looks like this check as well as the added but never used `relay_next_vclock_sync` function belong to the next patch. This patch is supposed to just add syncs to heartbeats. I think we can do this unconditionally - a sync is tiny in comparison with a vclock, and heartbeats are sent relatively rarely.

File: src/box/xrow.c [hunk 39]
```diff
@@ -1921,21 +1921,39 @@ xrow_encode_join(struct xrow_header *row, const struct tt_uuid *instance_uuid)
...
 {
 	memset(row, 0, sizeof(*row));
-
-	/* Add vclock to response body */
-	size_t size = 8 + mp_sizeof_vclock_ignore0(vclock);
+	row->type = IPROTO_OK;
+	row->replica_id = replica_id;
+	row->tm = tm;
+	/* Reserve mp_sizeof(map + vclock(key) + vclock_sync(key + value)). */
+	size_t size = 12;
```
Comment (locker) [inline src/box/xrow.c:1932]: Let's compute this number instead of using a magic constant (12).

File: src/box/xrow.c [hunk 40]
```diff
@@ -1944,6 +1962,57 @@ xrow_encode_vclock(struct xrow_header *row, const struct vclock *vclock)
...
+		case IPROTO_VCLOCK:
+			if (vclock == NULL)
+				goto skip;
+			if (mp_decode_vclock_ignore0(&d, vclock) != 0) {
+				xrow_on_decode_err(row, ER_INVALID_MSGPACK,
+						   "invalid vclock");
+				return -1;
+			}
+			break;
+		case IPROTO_VCLOCK_SYNC:
```
Comment (locker) [inline src/box/xrow.c:1998]: This function looks like a duplicate of `xrow_decode_subscribe`, but with fewer keys. Maybe, instead of adding a new parser, add `IPROTO_VCLOCK_SYNC` to `xrow_decode_subscribe` and rename the latter to something like `xrow_decode_replication`, then make `xrow_decode_heartbeat` call it?

File: src/box/box.cc [hunk 41]
```diff
@@ -1805,6 +1811,230 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+	trigger_add(&replicaset.on_ack, &on_ack);
+	replicaset_foreach(replica) {
+		if (relay_get_state(replica->relay) != RELAY_FOLLOW ||
+		    replica->anon) {
+			continue;
+		}
+		/* Might be already filled by on_relay_thread_start trigger. */
+		if (data.vclock_syncs[replica->id] != 0)
+			continue;
+		if (relay_next_vclock_sync(replica->relay,
```
Comment (locker) [inline src/box/box.cc:1923]: Better call `relay_trigger_vclock_sync` or even simply `relay_sync_vclock` IMO.

File: src/box/box.cc [hunk 42]
```diff
@@ -1805,6 +1811,230 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+			break;
+	} while (!data.is_ready && !fiber_is_cancelled());
+	trigger_clear(&on_wal_write);
+	if (fiber_is_cancelled()) {
+		diag_set(FiberIsCancelled);
+		return -1;
+	}
+	if (!data.is_ready) {
+		diag_set(ClientError, ER_VCLOCK_WAIT, vclock_to_string(vclock),
+			 "timed out");
```
Comment (locker) [inline src/box/box.cc:2004]: Please use `TimedOut` error for timeouts. Here's why:
1. We never use custom errors for timeouts in other places in the code. Inconsistency is never good.
2. Mixing `TimedOut` with `ClientError{FOO_TIMEOUT}` doesn't give the user any new information, actually. Suppose you failed to sync vclock, because socket lags somewhere inside the replication code internals. Technically it's a socket timeout, but you'll return `ClientError{FOO_TIMEOUT}`, which is confusing. Suppose you failed to wait for vclock, because the code syncing vclocks took too much time. Then you'll get `ER_QUORUM_WAIT` although it could just as well be `ER_VCLOCK_WAIT` error.
3. The user/admin may know nothing about quorum/vclock/etc; there's a CALL that failed because the timeout is too low. It could fail with a timeout in some other place inside the CALL. What the user/admin wants to see is `TimedOut` error. What the developer wants to see is file/line/trace where the `TimedOut` error occurred.

Confirmed by @alyapunov.

Please fix the code below to use generic errors, as well:

https://github.com/tarantool/tarantool/blob/e6abe1c91ae36127bedcd3b9a5d5d4705b802c91/src/box/box.cc#L1794-L1804

File: test/box-luatest/begin_options_validation_test.lua [hunk 43]
```diff
@@ -0,0 +1,23 @@
...
+g.after_all = function()
+    g.server:drop()
+end
+
+g.test_begin_options_validation = function()
+    g.server:exec(function()
+        require("luatest").assert_error_msg_content_equals(
+            "Illegal parameters, unexpected option 'foo'",
+            box.begin, {foo = "bar"})
+    end)
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply test/box-luatest/begin_options_validation_test.lua:22]: Sure:
<details><summary>diff</summary>

```diff
diff --git a/test/box-luatest/begin_options_validation_test.lua b/test/box-luatest/begin_options_validation_test.lua
index b044dd610..cb29c92a2 100644
--- a/test/box-luatest/begin_options_validation_test.lua
+++ b/test/box-luatest/begin_options_validation_test.lua
@@ -16,8 +16,15 @@ end
 
 g.test_begin_options_validation = function()
     g.server:exec(function()
-        require("luatest").assert_error_msg_content_equals(
+        local t = require("luatest")
+        t.assert_error_msg_content_equals(
             "Illegal parameters, unexpected option 'foo'",
             box.begin, {foo = "bar"})
+        t.assert_error_msg_content_equals(
+            "Illegal parameters, timeout must be a number greater than 0",
+            box.begin, {timeout = "0.5"})
+        t.assert_error_msg_content_equals(
+            "Illegal parameters, timeout must be a number greater than 0",
+            box.begin, {timeout = 0})
     end)
 end
```
</details>

File: src/box/iproto_constants.c [hunk 44]
```diff
@@ -153,6 +153,7 @@ const unsigned char iproto_key_type[IPROTO_KEY_MAX] =
 	/* 0x57 */	MP_STR, /* IPROTO_EVENT_KEY */
 	/* 0x58 */	MP_NIL, /* IPROTO_EVENT_DATA (can be any) */
 	/* 0x59 */	MP_UINT, /* IPROTO_TXN_ISOLATION */
+	/* 0x60 */	MP_UINT, /* IPROTO_VCLOCK_SYNC */
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/iproto_constants.c:156]: Oh. My bad, fixed.

File: test/box-luatest/begin_options_validation_test.lua (hunk 43 above)
[the remark this answers is not in the document]
Comment (locker) [reply test/box-luatest/begin_options_validation_test.lua:22]: Let's also add `timeout = "foo"` or `timeout = true` to trigger the type error. (Looks like `"0.5"` is implicitly converted to a number.)

[the remark this answers is not in the document]
Comment (sergepetrenko) [reply test/box-luatest/begin_options_validation_test.lua:22]:
```diff
diff --git a/test/box-luatest/begin_options_validation_test.lua b/test/box-luatest/begin_options_validation_test.lua
index cb29c92a2..4924faedb 100644
--- a/test/box-luatest/begin_options_validation_test.lua
+++ b/test/box-luatest/begin_options_validation_test.lua
@@ -22,7 +22,7 @@ g.test_begin_options_validation = function()
             box.begin, {foo = "bar"})
         t.assert_error_msg_content_equals(
             "Illegal parameters, timeout must be a number greater than 0",
-            box.begin, {timeout = "0.5"})
+            box.begin, {timeout = "not-a-number"})
         t.assert_error_msg_content_equals(
             "Illegal parameters, timeout must be a number greater than 0",
             box.begin, {timeout = 0})
```

(the same error's reported for negative numbers and wrong types there)

[the remark this answers is not in the document]
Comment (locker) [reply test/box-luatest/begin_options_validation_test.lua:22]: I see - I thought that you used the generic `check_param_table` type checker while you actually defined a callback.

File: src/box/box.cc [hunk 45]
```diff
@@ -2867,7 +2867,7 @@ box_process_fetch_snapshot(struct iostream *io,
 
 	/* Send end of snapshot data marker */
 	struct xrow_header row;
-	xrow_encode_vclock_xc(&row, &stop_vclock);
+	xrow_encode_heartbeat_xc(&row, 0, 0, &stop_vclock, 0);
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:3099]: Agreed. The diff's in the reply to the next comment.

File: src/box/applier.cc [hunk 46]
```diff
@@ -207,8 +207,10 @@ applier_thread_writer_f(va_list ap)
 		try {
 			applier->thread.has_acks_to_send = false;
 			struct xrow_header xrow;
-			xrow_encode_vclock(&xrow, &applier->thread.ack_vclock);
-			xrow.tm = applier->thread.txn_last_tm;
+			xrow_encode_heartbeat(&xrow, 0,
+					      applier->thread.txn_last_tm,
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/applier.cc:211]: Good point, thanks.

Done:
<details><summary>diff</summary>

```diff
diff --git a/src/box/applier.cc b/src/box/applier.cc
index cafa6dac4..5e0a821d7 100644
--- a/src/box/applier.cc
+++ b/src/box/applier.cc
@@ -207,10 +207,10 @@ applier_thread_writer_f(va_list ap)
 		try {
 			applier->thread.has_acks_to_send = false;
 			struct xrow_header xrow;
-			xrow_encode_heartbeat(&xrow, 0,
-					      applier->thread.txn_last_tm,
+			xrow_encode_heartbeat(&xrow,
 					      &applier->thread.ack_vclock,
 					      applier->thread.last_vclock_sync);
+			xrow.tm = applier->thread.txn_last_tm;
 			coio_write_xrow(&applier->io, &xrow);
 			ERROR_INJECT(ERRINJ_APPLIER_SLOW_ACK, {
 				fiber_sleep(0.01);
@@ -473,7 +473,7 @@ applier_wait_snapshot(struct applier *applier)
 		 * Used to initialize the replica's initial
 		 * vclock in bootstrap_from_master()
 		 */
-		xrow_decode_heartbeat_xc(&row, &replicaset.vclock, NULL);
+		xrow_decode_vclock_xc(&row, &replicaset.vclock);
 	}
 
 	coio_read_xrow(io, ibuf, &row);
diff --git a/src/box/box.cc b/src/box/box.cc
index b003881a6..586d993e9 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -2867,7 +2867,7 @@ box_process_fetch_snapshot(struct iostream *io,
 
 	/* Send end of snapshot data marker */
 	struct xrow_header row;
-	xrow_encode_heartbeat_xc(&row, 0, 0, &stop_vclock, 0);
+	xrow_encode_vclock_xc(&row, &stop_vclock);
 	row.sync = header->sync;
 	coio_write_xrow(io, &row);
 }
@@ -2946,7 +2946,7 @@ box_process_register(struct iostream *io, const struct xrow_header *header)
 
 	struct xrow_header row;
 	/* Send end of WAL stream marker */
-	xrow_encode_heartbeat_xc(&row, 0, 0, &replicaset.vclock, 0);
+	xrow_encode_vclock_xc(&row, &replicaset.vclock);
 	row.sync = header->sync;
 	coio_write_xrow(io, &row);
 
@@ -3086,7 +3086,7 @@ box_process_join(struct iostream *io, const struct xrow_header *header)
 	vclock_copy(&stop_vclock, &replicaset.vclock);
 	/* Send end of initial stage data marker */
 	struct xrow_header row;
-	xrow_encode_heartbeat_xc(&row, 0, 0, &stop_vclock, 0);
+	xrow_encode_vclock_xc(&row, &stop_vclock);
 	row.sync = header->sync;
 	coio_write_xrow(io, &row);
 
@@ -3098,7 +3098,7 @@ box_process_join(struct iostream *io, const struct xrow_header *header)
 	say_info("final data sent.");
 
 	/* Send end of WAL stream marker */
-	xrow_encode_heartbeat_xc(&row, 0, 0, &replicaset.vclock, 0);
+	xrow_encode_vclock_xc(&row, &replicaset.vclock);
 	row.sync = header->sync;
 	coio_write_xrow(io, &row);
 
diff --git a/src/box/relay.cc b/src/box/relay.cc
index d293b385f..766b03e7d 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -481,7 +481,7 @@ relay_initial_join(struct iostream *io, uint64_t sync, struct vclock *vclock,
 
 	/* Respond to the JOIN request with the current vclock. */
 	struct xrow_header row;
-	xrow_encode_heartbeat_xc(&row, 0, 0, vclock, 0);
+	xrow_encode_vclock_xc(&row, vclock);
 	row.sync = sync;
 	coio_write_xrow(relay->io, &row);
 
@@ -776,8 +776,9 @@ relay_send_heartbeat(struct relay *relay)
 		uint64_t vclock_sync = 0;
 		if (relay->need_new_vclock_sync)
 			vclock_sync = ++relay->sent_vclock_sync;
-		xrow_encode_heartbeat_xc(&row, instance_id, ev_now(loop()),
-					 NULL, vclock_sync);
+		xrow_encode_heartbeat_xc(&row, NULL, vclock_sync);
+		row.tm = ev_now(loop());
+		row.replica_id = instance_id;
 		relay->need_new_vclock_sync = false;
 		relay_send(relay, &row);
 	} catch (Exception *e) {
diff --git a/src/box/xrow.c b/src/box/xrow.c
index f23975589..95d7fe369 100644
--- a/src/box/xrow.c
+++ b/src/box/xrow.c
@@ -1921,13 +1921,11 @@ xrow_encode_join(struct xrow_header *row, const struct tt_uuid *instance_uuid)
 }
 
 int
-xrow_encode_heartbeat(struct xrow_header *row, uint32_t replica_id, double tm,
-		      const struct vclock *vclock, uint64_t vclock_sync)
+xrow_encode_heartbeat(struct xrow_header *row, const struct vclock *vclock,
+		      uint64_t vclock_sync)
 {
 	memset(row, 0, sizeof(*row));
 	row->type = IPROTO_OK;
-	row->replica_id = replica_id;
-	row->tm = tm;
 	/* Reserve mp_sizeof(map + vclock(key) + vclock_sync(key + value)). */
 	size_t size = 12;
 	size_t map_size = 0;
@@ -1958,7 +1956,6 @@ xrow_encode_heartbeat(struct xrow_header *row, uint32_t replica_id, double tm,
 	row->body[0].iov_base = buf;
 	row->body[0].iov_len = (data - buf);
 	row->bodycnt = 1;
-	row->type = IPROTO_OK;
 	return 0;
 }
 
diff --git a/src/box/xrow.h b/src/box/xrow.h
index ddc3d0035..68f8ba1cb 100644
--- a/src/box/xrow.h
+++ b/src/box/xrow.h
@@ -567,8 +567,6 @@ xrow_decode_register(const struct xrow_header *row,
 /**
  * Encode a heartbeat message.
  * @param row[out] Row to encode into.
- * @param replica_id Instance id.
- * @param tm Time stamp.
  * @param vclock vclock.
  * @param vclock_sync vclock synchronisation request id.
  *
@@ -576,8 +574,8 @@ xrow_decode_register(const struct xrow_header *row,
  * @retval -1 Memory error.
  */
 int
-xrow_encode_heartbeat(struct xrow_header *row, uint32_t replica_id, double tm,
-		      const struct vclock *vclock, uint64_t vclock_sync);
+xrow_encode_heartbeat(struct xrow_header *row, const struct vclock *vclock,
+		      uint64_t vclock_sync);
 
 /** Decode a heartbeat message.
  * @param row Row to decode.
@@ -591,6 +589,34 @@ int
 xrow_decode_heartbeat(const struct xrow_header *row, struct vclock *vclock,
 		      uint64_t *vclock_sync);
 
+/**
+ * Encode a vclock.
+ * @param row[out] Row to encode into.
+ * @param vclock.
+ *
+ * @retval 0 Success.
+ * @retval -1 Memory error.
+ */
+static inline int
+xrow_encode_vclock(struct xrow_header *row, const struct vclock *vclock)
+{
+	return xrow_encode_heartbeat(row, vclock, 0);
+}
+
+/**
+ * Decode a vclock.
+ * @param row Row to decode.
+ * @param vclock[out].
+ *
+ * @retval 0 Success.
+ * @retval -1 Format error.
+ */
+static inline int
+xrow_decode_vclock(const struct xrow_header *row, struct vclock *vclock)
+{
+	return xrow_decode_heartbeat(row, vclock, NULL);
+}
+
 /**
  * Encode a response to subscribe request.
  * @param row[out] Row to encode into.
@@ -1101,15 +1127,14 @@ xrow_decode_register_xc(const struct xrow_header *row,
 
 /** @copydoc xrow_encode_heartbeat. */
 static inline void
-xrow_encode_heartbeat_xc(struct xrow_header *row, uint32_t replica_id,
-			 double tm, const struct vclock *vclock,
+xrow_encode_heartbeat_xc(struct xrow_header *row, const struct vclock *vclock,
 			 uint64_t vclock_sync)
 {
-	if (xrow_encode_heartbeat(row, replica_id, tm, vclock,
-				  vclock_sync) != 0)
+	if (xrow_encode_heartbeat(row, vclock, vclock_sync) != 0)
 		diag_raise();
 }
 
+/** @copydoc xrow_decode_heartbeat. */
 static inline void
 xrow_decode_heartbeat_xc(const struct xrow_header *row, struct vclock *vclock,
 			 uint64_t *vclock_sync)
@@ -1118,6 +1143,22 @@ xrow_decode_heartbeat_xc(const struct xrow_header *row, struct vclock *vclock,
 		diag_raise();
 }
 
+/** @copydoc xrow_encode_vclock. */
+static inline void
+xrow_encode_vclock_xc(struct xrow_header *row, const struct vclock *vclock)
+{
+	if (xrow_encode_vclock(row, vclock) != 0)
+		diag_raise();
+}
+
+/** @copydoc xrow_decode_vclock. */
+static inline void
+xrow_decode_vclock_xc(const struct xrow_header *row, struct vclock *vclock)
+{
+	if (xrow_decode_vclock(row, vclock) != 0)
+		diag_raise();
+}
+
 /** @copydoc xrow_encode_subscribe_response. */
 static inline void
 xrow_encode_subscribe_response_xc(struct xrow_header *row,
```
</details>

File: src/box/xrow.c (hunk 40 above)
Comment (sergepetrenko) [reply src/box/xrow.c:1998]: I'm really concerned with `xrow_decode_heartbeat` having to switch-case over all the 'subscribe' keys. Like `IPROTO_INSTANCE_UUID`, `IPROTO_ID_FILTER` and so on.

I think it would be more or less fine for rare requests, like `subscribe` or `join`, but I don't want to trigger the same machinery for heartbeats, which will be sent quite often once linearizable read is introduced.

File: src/box/xrow.c (hunk 39 above)
Comment (sergepetrenko) [reply src/box/xrow.c:1932]: Ok:
```diff
diff --git a/src/box/xrow.c b/src/box/xrow.c
index 95d7fe369..24398af2a 100644
--- a/src/box/xrow.c
+++ b/src/box/xrow.c
@@ -1926,16 +1926,21 @@ xrow_encode_heartbeat(struct xrow_header *row, const struct vclock *vclock,
 {
        memset(row, 0, sizeof(*row));
        row->type = IPROTO_OK;
-       /* Reserve mp_sizeof(map + vclock(key) + vclock_sync(key + value)). */
-       size_t size = 12;
+       size_t size = 0;
        size_t map_size = 0;
        if (vclock != NULL) {
                map_size += 1;
+               size += mp_sizeof_uint(IPROTO_VCLOCK);
                size += mp_sizeof_vclock_ignore0(vclock);
        }
-       map_size += vclock_sync != 0;
+       if (vclock_sync != 0) {
+               map_size += 1;
+               size += mp_sizeof_uint(IPROTO_VCLOCK_SYNC);
+               size += mp_sizeof_uint(vclock_sync);
+       }
        if (map_size == 0)
                return 0;
+       size += mp_sizeof_map(map_size);
        char *buf = (char *) region_alloc(&fiber()->gc, size);
        if (buf == NULL) {
                diag_set(OutOfMemory, size, "region_alloc",
```

File: src/box/xrow.c (hunk 40 above)
Comment (locker) [reply src/box/xrow.c:1998]: Ok.

File: src/box/box.cc (hunk 41 above)
Comment (sergepetrenko) [reply src/box/box.cc:1923]: Yep, `relay_trigger_vclock_sync` makes more sense. Done.
`relay_sync_vclock` would look like the returned sync value is already reached IMO.

File: src/box/relay.cc (hunk 38 above)
Comment (sergepetrenko) [reply src/box/relay.cc:773]: Done.

File: src/box/box.cc (hunk 42 above)
Comment (sergepetrenko) [reply src/box/box.cc:2004]: I'd argue about that:
having a "timed out waiting for 5 remote vclocks" error gives the user some additional info. For example, the user might have a wrong quorum setting, making the read poll for all 5 nodes in the cluster. Even when one of them is dead.

Simply having "timed out" error gives no info.

Anyway, I've changed these places:
```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 56aafafe9..315bed53b 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1944,8 +1944,7 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
                return -1;
        }
        if (bit_count_u32(data.collected_vclock_map) + 1 < vclock_count) {
-               diag_set(ClientError, ER_QUORUM_WAIT, vclock_count,
-                        "timed out waiting for remote node vclocks");
+               diag_set(TimedOut);
                return -1;
        }
        return 0;
@@ -2001,8 +2000,7 @@ box_wait_vclock(const struct vclock *vclock, double deadline)
                return -1;
        }
        if (!data.is_ready) {
-               diag_set(ClientError, ER_VCLOCK_WAIT, vclock_to_string(vclock),
-                        "timed out");
+               diag_set(TimedOut);
                return -1;
        }
        return 0;

```

And done the same for box_wait_quorum in a separate commit.

Comment (locker) [reply src/box/box.cc]: > having a "timed out waiting for 5 remote vclocks" error gives the user some additional info. For example, the user might have a wrong quorum setting, making the read poll for all 5 nodes in the cluster. Even when one of them is dead.

In this case, the transaction should fail before the timeout occurs and raise a proper error.

Comment (sergepetrenko) [reply src/box/box.cc]: I'd say we should try to connect to everyone for a timeout anyway.

Maybe enough connections will be established by that time

Comment (locker) [reply src/box/box.cc]: In this case, you could print a message to the log warning that the configuration might be invalid.

Comment (Gerold103) [reply src/box/box.cc]: I am not in the context since quite a lot has changed in the patch. But if you need any additional info in an error object, you can use `error_append_msg()` and/or `error_set_...()` functions.

File: src/box/xrow.c (hunk 40 above)
Comment (Gerold103) [reply src/box/xrow.c:2000]: FYI: in my future patch I am reworking all these replication request codecs to avoid abusing `xrow_decode_subscribe()` with tons of optional parameters for everything.  Don't necessarily need to dwell on it in this patch.

File: src/box/relay.cc [hunk 47]
```diff
@@ -905,9 +930,10 @@ relay_subscribe_f(va_list ap)
 		/* Collect xlog files received by the replica. */
 		relay_schedule_pending_gc(relay, send_vclock);
 
+		double tx_idle = ev_monotonic_now(loop()) - relay->tx_seen_time;
 		if (vclock_sum(&relay->status_msg.vclock) ==
-		    vclock_sum(send_vclock) &&
-		    ev_monotonic_now(loop()) - relay->tx_seen_time <= timeout)
+		    vclock_sum(send_vclock) && tx_idle <= replication_timeout &&
```
Comment (locker) [inline src/box/relay.cc:996]: Why did you replaced `timeout` with `replication_timeout`? Looks like an unintended change.

File: src/box/applier.cc [hunk 48]
```diff
@@ -207,7 +207,9 @@ applier_thread_writer_f(va_list ap)
 		try {
 			applier->thread.has_acks_to_send = false;
 			struct xrow_header xrow;
-			xrow_encode_vclock(&xrow, &applier->thread.ack_vclock);
+			xrow_encode_heartbeat(&xrow,
```
Comment (locker) [inline src/box/applier.cc:210]: Should be `xrow_encode_heartbeat_xc`?

File: src/box/applier.cc [hunk 49]
```diff
@@ -793,7 +797,10 @@ applier_parse_tx_row(struct applier_tx_row *tx_row)
 			diag_raise();
 		}
 	} else if (type == IPROTO_OK) {
-		/* Nothing to do. */
+		if (xrow_decode_heartbeat(row, NULL,
+					  &tx_row->req.vclock_sync) != 0) {
+			diag_raise();
```
Comment (locker) [inline src/box/applier.cc:802]: Nit: You could use `xrow_decode_heartbeat_xc` here.

File: src/box/lua/schema.lua [hunk 50]
```diff
@@ -414,17 +419,17 @@ box.begin = function(options)
...
         box.error()
     end
     if timeout then
         assert(builtin.box_txn_set_timeout(timeout) == 0)
     end
-    if txn_isolation and
-       builtin.box_txn_set_isolation(txn_isolation) ~= 0 then
+    txn_isolation = normalize_txn_isolation_level(txn_isolation)
+    assert(txn_isolation ~= nil)
+    if builtin.box_txn_set_isolation(txn_isolation) ~= 0 then
```
Comment (locker) [inline src/box/lua/schema.lua:432]: Do you really need to patch `box.begin()`? I think it should do just fine without any modifications.

File: src/box/relay.cc [hunk 51]
```diff
@@ -188,6 +188,14 @@ struct relay {
 	double txn_lag;
 	/** Relay sync state. */
 	enum relay_state state;
+	/** Whether relay should speed up the next heartbeat dispatch. */
+	bool need_new_vclock_sync;
```
Comment (locker) [inline src/box/relay.cc:192]: Nit: `vclock_sync_is_pending` would probably be a better name, but I don't insist - up to you.

File: src/box/relay.cc [hunk 52]
```diff
@@ -832,6 +847,52 @@ relay_thread_on_stop(void *arg)
...
+relay_trigger_vclock_sync(struct relay *relay, uint64_t *vclock_sync,
+			  double deadline)
+{
+	struct relay_trigger_vclock_sync_msg *msg =
+		(struct relay_trigger_vclock_sync_msg *)xmalloc(sizeof(*msg));
+	msg->relay = relay;
+	double timeout = deadline - ev_monotonic_now(loop());
+	if (cbus_call_timeout(&relay->relay_pipe, &relay->tx_pipe, &msg->base,
+			      relay_trigger_vclock_sync_f,
+			      relay_trigger_vclock_sync_msg_free, timeout) < 0)
```
Comment (locker) [inline src/box/relay.cc:889]: I don't think we need a timeout here - triggering a sync is a fast operation that isn't supposed to stall. Having a timeout here only looks confusing IMO.

File: src/box/txn.c [hunk 53]
```diff
@@ -1385,6 +1404,8 @@ box_txn_set_isolation(uint32_t level)
 	if (level == TXN_ISOLATION_DEFAULT)
 		level = txn_default_isolation;
 	txn->isolation = level;
+	if (level == TXN_ISOLATION_LINEARIZABLE)
+		return txn_make_linearizable(txn);
```
Comment (locker) [inline src/box/txn.c:1408]: I don't quite like that `box_txn_set_isolation` may know sleep - it looks like a simple setter. Maybe, we could postpone this until the first statement is executed (`txn_begin_stmt`), like we postpone creation of the transaction in engine (`txn_begin_in_engine`)?

File: src/box/txn.h [hunk 54]
```diff
@@ -777,6 +780,52 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type);
...
+ */
+static inline int
+txn_check_space_linearizability(const struct txn *txn,
+				const struct space *space)
+{
+	assert(txn_is_linearizable(txn));
+	(void)txn;
+	/*
+	 * XXX: can't promise the user linearizability with Vinyl until
+	 * https://github.com/tarantool/tarantool/issues/5522 is fixed.
```
Comment (locker) [inline src/box/txn.h:801]: I'm planning to fix #5522 soon. Let's file another ticket for the reference and add a TODO instead of XXX.

```C
/* TODO(gh-XXXX): Enable linearizable transactions in Vinyl. */
```

File: test/replication-luatest/linearizable_test.lua [hunk 55]
```diff
@@ -0,0 +1,314 @@
...
+    end)
+    g.servers[2]:wait_vclock_of(g.servers[1])
+    g.servers[3]:wait_vclock_of(g.servers[1])
+end)
+
+g.after_all(function()
+    g.cluster:drop()
+end)
+
+g.test_wait_others = function(g)
```
Comment (locker) [inline test/replication-luatest/linearizable_test.lua:64]: Nit: Masking `g` looks confusing. I think it's conventional to use `cg` for the local argument here.

File: src/box/relay.h [hunk 56]
```diff
@@ -100,6 +100,10 @@ relay_last_row_time(const struct relay *relay);
 double
 relay_txn_lag(const struct relay *relay);
 
+/** Returns the last sync received in response from a replica. */
+uint64_t
+relay_known_vclock_sync(const struct relay *relay);
```
Comment (locker) [inline src/box/relay.h:113]: Unused?

File: src/box/txn.h [hunk 57]
```diff
@@ -777,6 +780,52 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type);
...
+
+/**
+ * Check if a space supports linearizable access, i.e. it is either synchronous
+ * or not replicated at all, and its engine prevents dirty reads.
+ */
+static inline int
+txn_check_space_linearizability(const struct txn *txn,
+				const struct space *space)
+{
+	assert(txn_is_linearizable(txn));
```
Comment (locker) [inline src/box/txn.h:797]: Since `txn_is_linearizable()` and `txn_check_space_linearizability()` are always called together, I think we should merge them and call the resulting function simply `txn_check_space()` or something like that. I don't think we need to provide a public `txn_is_linearizable()` helper, as we don't have similar helpers for other isolation levels. Also, it looks this function should be defined as static in `txn.c`.

File: src/box/relay.cc [hunk 58]
```diff
@@ -188,6 +188,14 @@ struct relay {
 	double txn_lag;
 	/** Relay sync state. */
 	enum relay_state state;
+	/** Whether relay should speed up the next heartbeat dispatch. */
+	bool need_new_vclock_sync;
+	/**
+	 * Whether relay is in process of sending a tx to the remote peer. In
+	 * this case cannot interrupt the transaction stream with any heartbeats
```
Comment (locker) [inline src/box/relay.cc:195]: Why?

File: changelogs/unreleased/linearizable-read.md [hunk 59]
```diff
@@ -0,0 +1,4 @@
+## feature/core
+* There is a new transaction isolation level now: "linearizable". Transactions
```
Comment (locker) [inline changelogs/unreleased/linearizable-read.md:2]: Nit: We usually add an empty line after the changelog header. Also, I think it's better to start a changelog entry with a sentence in Past Simple: "Added a new transaction level 'linearizable'. ..."

**Comment by Gerold103** [comment]
I will proceed with the review a bit later. For now I want to comment on the decision to introduce a new `vclock_sync` request key in the replication ping body. I discussed it with @sergos and @sergepetrenko and I still don't see any reason to do it in such a complicated way.

The arguments I heard why we can't reuse `IPROTO_SYNC`:

* *"The syncs might be used by somebody"*. This isn't true, because they were never sent in the acks. This is how the code looks (before this patch) which sends an ACK:
```C
			struct xrow_header xrow;
			xrow_encode_vclock(&xrow, &applier->thread.ack_vclock);
			xrow.tm = applier->thread.txn_last_tm;
			coio_write_xrow(&applier->io, &xrow);
```
There is no sync. Even if you send one in the relay messages, you won't get it back. Thus it just couldn't be used.

* *"Core team is going to do some proxying in the future and syncs might be needed"*. (1) This is controversial with the first reason about syncs being used by somebody. If they are used by people, then you can't re-use them for proxying either. (2) The syncs are actually being used by regular requests, not by the replication. I suppose if you want to reuse `IPROTO_SYNC` for proxying, you could deal with the replication syncs same way you will deal with regular request syncs. (3) ACKs are sent not per each relay row but per batch. There is no one-to-one sync match between relay requests and applier responses. This means in a proxy you can't do syncs translation. Like take client syncs, replace them with other local syncs and then re-match it back for responses.

With that said I would propose to switch back to the original solution about using `IPROT_SYNC`. The new approach seems like huge overengineering right now and doesn't seem to do any good in the future either.

Unless there are other reasons why the complication is worth doing which I missed.

File: src/box/relay.cc (hunk 58 above)
Comment (sergepetrenko) [reply src/box/relay.cc:195]: Because applier reads row stream in transactions. A ping (which's not DML, it's IPROTO_OK, not IPROTO_NOP) will break the transaction.
See here, for example:
https://github.com/tarantool/tarantool/blob/dc147ec9190fc8bbbe56ce8a4a1718fbf8b03484/src/box/applier.cc#L831-L836
It's not that easy to rework that. And I don't see why we should.

**Comment by locker** [comment]
> The arguments I heard why we can't reuse `IPROTO_SYNC`

In the old code version, it took me a while to realize that a relay field called `sync` and encoded as `IPROTO_SYNC` has actually nothing to do with binary protocol syncs, which I'm used to. This was confusing from the code clarity pov. OTOH using a separate field makes the code clear and easy to understand.

> *"Core team is going to do some proxying in the future and syncs might be needed"*. (1) This is controversial with the first reason about syncs being used by somebody. If they are used by people, then you can't re-use them for proxying either. (2) The syncs are actually being used by regular requests, not by the replication. I suppose if you want to reuse `IPROTO_SYNC` for proxying, you could deal with the replication syncs same way you will deal with regular request syncs. (3) ACKs are sent not per each relay row but per batch. There is no one-to-one sync match between relay requests and applier responses. This means in a proxy you can't do syncs translation. Like take client syncs, replace them with other local syncs and then re-match it back for responses.

Currently, the whole replication stream (in and out) uses the same sync number sent in the `IPROTO_SUBSCRIBE` request. We don't use this functionality (set sync to 0), but one can set a non-zero sync number in order to route different replication streams through the same connection. This could be used by multilevel proxies. I think this is what was meant here, but better ask @alyapunov.

> I still don't see any reason to do it in such a complicated way.

Why do you find this solution complicated? Sergey just added a new request body field, that's all. The algorithm and the bulk of the code would be the same if he used syncs.

**Comment by locker** [comment]
> _"The syncs might be used by somebody"_. This isn't true, because they were never sent in the acks. This is how the code looks (before this patch) which sends an ACK:
> 
> ```c
> 			struct xrow_header xrow;
> 			xrow_encode_vclock(&xrow, &applier->thread.ack_vclock);
> 			xrow.tm = applier->thread.txn_last_tm;
> 			coio_write_xrow(&applier->io, &xrow);
> ```
> 
> There is no sync. Even if you send one in the relay messages, you won't get it back. Thus it just couldn't be used.

This is because *our* applier code doesn't use syncs (sets sync send by `IPROTO_SUBSCRIBE` to 0). A third-party applier may actually use non-zero sync numbers, in which case the relay will reply with the same sync number AFAICS.

File: src/box/relay.cc (hunk 47 above)
Comment (sergepetrenko) [reply src/box/relay.cc:996]: Yep, that's a leftover from some refactoring.
Thanks for noticing! Fixed.

File: src/box/applier.cc (hunk 48 above)
Comment (sergepetrenko) [reply src/box/applier.cc:210]: Yes, indeed. Fixed together with the next comment:

<details><summary>diff</summary>

```diff
diff --git a/src/box/applier.cc b/src/box/applier.cc
index 5e0a821d7..11b251293 100644
--- a/src/box/applier.cc
+++ b/src/box/applier.cc
@@ -207,9 +207,10 @@ applier_thread_writer_f(va_list ap)
                try {
                        applier->thread.has_acks_to_send = false;
                        struct xrow_header xrow;
-                       xrow_encode_heartbeat(&xrow,
-                                             &applier->thread.ack_vclock,
-                                             applier->thread.last_vclock_sync);
+                       uint64_t vclock_sync = applier->thread.last_vclock_sync;
+                       struct vclock *ack_vclock = &applier->thread.ack_vclock;
+                       xrow_encode_heartbeat_xc(&xrow, ack_vclock,
+                                                vclock_sync);
                        xrow.tm = applier->thread.txn_last_tm;
                        coio_write_xrow(&applier->io, &xrow);
                        ERROR_INJECT(ERRINJ_APPLIER_SLOW_ACK, {
@@ -797,10 +798,7 @@ applier_parse_tx_row(struct applier_tx_row *tx_row)
                        diag_raise();
                }
        } else if (type == IPROTO_OK) {
-               if (xrow_decode_heartbeat(row, NULL,
-                                         &tx_row->req.vclock_sync) != 0) {
-                       diag_raise();
-               }
+               xrow_decode_heartbeat_xc(row, NULL, &tx_row->req.vclock_sync);
        } else {
                tnt_raise(ClientError, ER_UNKNOWN_REQUEST_TYPE, type);
        }
```

</details>

File: src/box/applier.cc (hunk 49 above)
Comment (sergepetrenko) [reply src/box/applier.cc:802]: Done. See the diff above.

File: src/box/lua/schema.lua (hunk 50 above)
Comment (sergepetrenko) [reply src/box/lua/schema.lua:432]: Yes, I do, because now default isolation can be "linearizable". And this level requires extra actions (wait_linearization_point) once it is set.
Previously `txn->isolation` was set to default value in `txn_begin`, so when `box.begin()` had no isolation, it just left the `txn->isolation` value intact. But this can't be done now when default isolation is 'linearizable'

File: src/box/relay.cc (hunk 51 above)
Comment (sergepetrenko) [reply src/box/relay.cc:192]: I'd rather leave the current name

File: src/box/relay.cc (hunk 52 above)
Comment (sergepetrenko) [reply src/box/relay.cc:889]: There are no guarantees that relay isn't stalled outside of `cbus_proces` loop forever. For example, it might be sending a WAL, and that WAL might be appended at a high rate.

Besides, there's no way to cancel a `cbus_call` without a timeout.

I'd rather stick with the timeout. Besides, it's TIMEOUT_INFINITY, when user doesn't specify anything else.

File: src/box/txn.c (hunk 53 above)
Comment (sergepetrenko) [reply src/box/txn.c:1408]: We'll have another problem then: select will yield. We decided this is not ok while reviewing the RFC.
`txn_set_isolation` is a part of `box.begin()` anyway (or IPROTO_BEGIN), so I don't see why it shouldn't yield.

Maybe factor `txn_make_linearizable` out of `txn_set_isolation` and place it in the end of `box.begin()` and IPROTO_BEGIN pr
ocessing? I think that `txn_set_isolation` and `txn_make_linearizable` should work atomically, but I can live with that.

File: test/replication-luatest/linearizable_test.lua (hunk 55 above)
Comment (sergepetrenko) [reply test/replication-luatest/linearizable_test.lua:64]: Ok.
<details><summary>diff</summary>

```diff
diff --git a/test/replication-luatest/linearizable_test.lua b/test/replication-luatest/linearizable_test.lua
index a342e1a4b..2e628e731 100644
--- a/test/replication-luatest/linearizable_test.lua
+++ b/test/replication-luatest/linearizable_test.lua
@@ -17,53 +17,53 @@ end
 
 local num_servers = 3
 
-g.before_all(function()
-    g.cluster = cluster:new({})
-    g.servers = {}
-    g.box_cfg = {
+g.before_all(function(cg)
+    cg.cluster = cluster:new({})
+    cg.servers = {}
+    cg.box_cfg = {
         replication = build_replication(num_servers),
         replication_timeout = 0.1,
         memtx_use_mvcc_engine = true,
     }
-    g.servers[1] = g.cluster:build_and_add_server({
+    cg.servers[1] = cg.cluster:build_and_add_server({
         alias = 'server_1',
-        box_cfg = g.box_cfg,
+        box_cfg = cg.box_cfg,
     })
     -- Servers 2 and 3 are interconnected without a proxy.
     for i = 2, num_servers do
-        g.box_cfg.replication[i] = server.build_instance_uri('server_' .. i)
+        cg.box_cfg.replication[i] = server.build_instance_uri('server_' .. i)
     end
     for i = 2, num_servers do
-        g.servers[i] = g.cluster:build_and_add_server({
+        cg.servers[i] = cg.cluster:build_and_add_server({
             alias = 'server_' .. i,
-            box_cfg = g.box_cfg,
+            box_cfg = cg.box_cfg,
         })
     end
-    g.proxies = {}
+    cg.proxies = {}
     for i = 1, num_servers do
-        g.proxies[i] = proxy:new({
+        cg.proxies[i] = proxy:new({
             client_socket_path = server.build_instance_uri('server_' .. i .. '_proxy'),
             server_socket_path = server.build_instance_uri('server_' .. i),
         })
-        g.proxies[i]:start({force = true})
+        cg.proxies[i]:start({force = true})
     end
-    g.cluster:start()
-    g.cluster:wait_fullmesh()
-    g.servers[1]:exec(function()
+    cg.cluster:start()
+    cg.cluster:wait_fullmesh()
+    cg.servers[1]:exec(function()
         box.schema.space.create('sync', {is_sync=true})
         box.space.sync:create_index('pk')
     end)
-    g.servers[2]:wait_vclock_of(g.servers[1])
-    g.servers[3]:wait_vclock_of(g.servers[1])
+    cg.servers[2]:wait_vclock_of(cg.servers[1])
+    cg.servers[3]:wait_vclock_of(cg.servers[1])
 end)
 
-g.after_all(function()
-    g.cluster:drop()
+g.after_all(function(cg)
+    cg.cluster:drop()
 end)
 
-g.test_wait_others = function(g)
-    g.proxies[1]:pause()
-    local fid = g.servers[1]:exec(function()
+g.test_wait_others = function(cg)
+    cg.proxies[1]:pause()
+    local fid = cg.servers[1]:exec(function()
         local t = require('luatest')
         local fiber = require('fiber')
         local f = fiber.new(function()
@@ -74,8 +74,8 @@ g.test_wait_others = function(g)
         t.assert_equals(f:status(), 'suspended', 'begin() waits for replicas')
         return f:id()
     end)
-    g.proxies[1]:resume()
-    local ok = g.servers[1]:exec(function(fid)
+    cg.proxies[1]:resume()
+    local ok = cg.servers[1]:exec(function(fid)
         local fiber = require('fiber')
         local _, ok, err =  fiber.join(fiber.find(fid))
         return ok, err
@@ -83,9 +83,9 @@ g.test_wait_others = function(g)
     t.assert(ok, 'begin() succeeds after replica connections are established')
 end
 
-g.test_timeout = function(g)
+g.test_timeout = function(cg)
     misc.skip_if_not_debug()
-    g.servers[1]:exec(function()
+    cg.servers[1]:exec(function()
         local t = require('luatest')
         box.error.injection.set('ERRINJ_RELAY_FROM_TX_DELAY', true)
         local ok, err = pcall(box.begin, {txn_isolation = 'linearizable',
@@ -97,37 +97,37 @@ g.test_timeout = function(g)
     end)
 end
 
-g.before_test('test_no_dirty_reads', function(g)
+g.before_test('test_no_dirty_reads', function(cg)
     -- Make cluster size 5. Having quorum 3 out of 5 will make the instance
     -- poll 5 - 3 + 1 == all 3 of the "real" nodes.
-    g.servers[1]:exec(function()
+    cg.servers[1]:exec(function()
         local uuid = require('uuid')
         box.space._cluster:insert{4, tostring(uuid.new())}
         box.space._cluster:insert{5, tostring(uuid.new())}
     end)
-    g.servers[2]:wait_vclock_of(g.servers[1])
-    g.servers[2]:exec(function()
+    cg.servers[2]:wait_vclock_of(cg.servers[1])
+    cg.servers[2]:exec(function()
         box.ctl.promote()
     end)
-    g.servers[1]:wait_vclock_of(g.servers[2])
-    g.servers[3]:wait_vclock_of(g.servers[2])
+    cg.servers[1]:wait_vclock_of(cg.servers[2])
+    cg.servers[3]:wait_vclock_of(cg.servers[2])
 end)
 
-g.after_test('test_no_dirty_reads', function(g)
-    g.servers[2]:exec(function()
+g.after_test('test_no_dirty_reads', function(cg)
+    cg.servers[2]:exec(function()
         box.ctl.demote()
     end)
-    g.servers[1]:wait_vclock_of(g.servers[2])
-    g.servers[1]:exec(function()
+    cg.servers[1]:wait_vclock_of(cg.servers[2])
+    cg.servers[1]:exec(function()
         box.space._cluster:delete{4}
         box.space._cluster:delete{5}
     end)
-    g.servers[2]:wait_vclock_of(g.servers[1])
-    g.servers[3]:wait_vclock_of(g.servers[1])
+    cg.servers[2]:wait_vclock_of(cg.servers[1])
+    cg.servers[3]:wait_vclock_of(cg.servers[1])
 end)
 
-g.test_no_dirty_reads = function(g)
-    g.replication_synchro_quorum = g.servers[2]:exec(function()
+g.test_no_dirty_reads = function(cg)
+    cg.replication_synchro_quorum = cg.servers[2]:exec(function()
         local t = require('luatest')
         local lsn = box.info.lsn
         local q = box.cfg.replication_synchro_quorum
@@ -136,7 +136,7 @@ g.test_no_dirty_reads = function(g)
         t.helpers.retrying({}, function() assert(box.info.lsn > lsn) end)
         return q
     end)
-    g.servers[1]:exec(function()
+    cg.servers[1]:exec(function()
         local t = require('luatest')
         local ok, err = pcall(box.begin, {txn_isolation = 'linearizable',
                                           timeout = 0.1})
@@ -146,10 +146,10 @@ g.test_no_dirty_reads = function(g)
                         'Pending transaction is seen')
         t.assert_equals(box.space.sync:get{1}, nil, 'No dirty reads')
     end)
-    g.servers[2]:exec(function(q)
+    cg.servers[2]:exec(function(q)
         box.cfg{replication_synchro_quorum = q}
-    end, {g.replication_synchro_quorum})
-    g.servers[1]:exec(function()
+    end, {cg.replication_synchro_quorum})
+    cg.servers[1]:exec(function()
         local t = require('luatest')
         box.begin{txn_isolation = 'linearizable'}
         local len = box.info.synchro.queue.len
@@ -163,15 +163,15 @@ g.test_no_dirty_reads = function(g)
     end)
 end
 
-g.test_reconnect_while_waiting = function(g)
+g.test_reconnect_while_waiting = function(cg)
     for i = 2, 3 do
-        g.servers[i]:exec(function()
+        cg.servers[i]:exec(function()
             local repl = table.copy(box.cfg.replication)
             table.remove(repl, 1)
             box.cfg{replication = repl}
         end)
     end
-    local f = fiber.new(g.servers[1].exec, g.servers[1], function()
+    local f = fiber.new(cg.servers[1].exec, cg.servers[1], function()
         local ok, err = pcall(box.begin, {txn_isolation = 'linearizable'})
         if ok then
             box.commit()
@@ -180,29 +180,29 @@ g.test_reconnect_while_waiting = function(g)
     end)
     f:set_joinable(true)
     for i = 2, 3 do
-        g.servers[i]:exec(function(repl)
+        cg.servers[i]:exec(function(repl)
             box.cfg{replication = repl}
-        end, {g.box_cfg.replication})
+        end, {cg.box_cfg.replication})
     end
     local success, ok, _ = f:join()
     t.assert(success, 'fiber joined successfully')
     t.assert(ok, 'reconnect while begin() waits for vclocks is tolerated')
 end
 
-g.test_leader_change = function(g)
-    g.servers[1]:exec(function()
+g.test_leader_change = function(cg)
+    cg.servers[1]:exec(function()
         box.ctl.promote()
     end)
-    g.servers[2]:wait_vclock_of(g.servers[1])
-    g.servers[3]:wait_vclock_of(g.servers[1])
+    cg.servers[2]:wait_vclock_of(cg.servers[1])
+    cg.servers[3]:wait_vclock_of(cg.servers[1])
     for i = 1, num_servers do
-        g.proxies[i]:pause()
+        cg.proxies[i]:pause()
     end
-    g.servers[2]:exec(function()
+    cg.servers[2]:exec(function()
         box.ctl.promote()
         box.space.sync:insert{2}
     end)
-    local fid = g.servers[1]:exec(function()
+    local fid = cg.servers[1]:exec(function()
         local f = require('fiber').new(function()
             box.begin{txn_isolation = 'linearizable'}
             local owner = box.info.synchro.queue.owner
@@ -216,31 +216,31 @@ g.test_leader_change = function(g)
         return f:id()
     end)
     for i = 1, num_servers do
-        g.proxies[i]:resume()
+        cg.proxies[i]:resume()
     end
-    local owner, get = g.servers[1]:exec(function(fid)
+    local owner, get = cg.servers[1]:exec(function(fid)
         local fiber = require('fiber')
         local _, owner, get = fiber.join(fiber.find(fid))
         return owner, get
     end, {fid})
-    t.assert_equals(owner, g.servers[2]:instance_id(),
+    t.assert_equals(owner, cg.servers[2]:instance_id(),
                     'leader change is noticed in box.begin()')
     t.assert_equals(get, {2}, 'Transaction committed by new leader is seen')
 end
 
 local g_basic = t.group('linearizable-read-basic')
 
-g_basic.before_all(function(g)
-    g.cluster = cluster:new({})
-    g.nomvcc = g.cluster:build_and_add_server({alias = 'nomvcc'})
-    g.mvcc = g.cluster:build_and_add_server({
+g_basic.before_all(function(cg)
+    cg.cluster = cluster:new({})
+    cg.nomvcc = cg.cluster:build_and_add_server({alias = 'nomvcc'})
+    cg.mvcc = cg.cluster:build_and_add_server({
         alias = 'mvcc',
         box_cfg = {
             memtx_use_mvcc_engine = true,
         },
     })
-    g.cluster:start()
-    g.mvcc:exec(function()
+    cg.cluster:start()
+    cg.mvcc:exec(function()
         box.schema.space.create('async'):create_index('pk')
         box.schema.space.create('sync', {is_sync = true}):create_index('pk')
         box.schema.space.create('local', {is_local = true}):create_index('pk')
@@ -253,8 +253,8 @@ g_basic.before_all(function(g)
     end)
 end)
 
-g_basic.after_all(function(g)
-    g.cluster:drop()
+g_basic.after_all(function(cg)
+    cg.cluster:drop()
 end)
 
 local function begin(opts)
@@ -291,24 +291,24 @@ local function test_linearizable_access(node, spacename, is_ok, msg)
     end
 end
 
-g_basic.test_basic = function(g)
+g_basic.test_basic = function(cg)
     local ok, err = pcall(box.cfg, {txn_isolation = 'linearizable'})
     t.assert(not ok, 'Cannot set default isolation level to linearizable')
     local msg = "Incorrect value for option 'txn_isolation': cannot set " ..
                 "default transaction isolation to 'linearizable'"
     t.assert_equals(err.message, msg,
                     'Correct error when trying to set default isolation')
-    ok, err = g.nomvcc:exec(begin, {{txn_isolation = 'linearizable'}})
+    ok, err = cg.nomvcc:exec(begin, {{txn_isolation = 'linearizable'}})
     t.assert(not ok, 'Error without mvcc enabled')
     t.assert_equals(err.message, 'Linearizable transaction does not support ' ..
                                  'disabled memtx mvcc engine',
                     'Correct error without mvcc enabled')
 
     local errmsg = 'space "async" does not support linearizable operations'
-    test_linearizable_access(g.mvcc, 'async', false, errmsg)
+    test_linearizable_access(cg.mvcc, 'async', false, errmsg)
     errmsg = 'space "vinyl" does not support linearizable operations'
-    test_linearizable_access(g.mvcc, 'vinyl', false, errmsg)
-    test_linearizable_access(g.mvcc, 'temporary', true)
-    test_linearizable_access(g.mvcc, 'local', true)
-    test_linearizable_access(g.mvcc, 'sync', true)
+    test_linearizable_access(cg.mvcc, 'vinyl', false, errmsg)
+    test_linearizable_access(cg.mvcc, 'temporary', true)
+    test_linearizable_access(cg.mvcc, 'local', true)
+    test_linearizable_access(cg.mvcc, 'sync', true)
 end
```
</details>

File: src/box/relay.h (hunk 56 above)
Comment (sergepetrenko) [reply src/box/relay.h:113]: Yep, but I thought it would be fine to have it for later.
Removed.

File: src/box/txn.h (hunk 57 above)
Comment (sergepetrenko) [reply src/box/txn.h:797]: Ok, merged.
I don't want to make it local to `txn.c` though, because this way it'll stop being inlined to `txn_begin_ro_stmt`

<details><summary>diff</summary>

```diff
diff --git a/src/box/txn.c b/src/box/txn.c
index 2eb6046e2..289fc3971 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -609,10 +609,8 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type)
                txn_set_flags(txn, TXN_IS_CONFLICTED);
        }
 
-       if (space != NULL && txn_is_linearizable(txn) &&
-           txn_check_space_linearizability(txn, space) != 0) {
+       if (space != NULL && txn_check_space_linearizability(txn, space) != 0)
                return -1;
-       }
 
        if (txn_check_can_continue(txn) != 0)
                return -1;
diff --git a/src/box/txn.h b/src/box/txn.h
index 2a2fd053d..ff84d2acc 100644
--- a/src/box/txn.h
+++ b/src/box/txn.h
@@ -780,12 +780,6 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type);
 int
 txn_begin_in_engine(struct engine *engine, struct txn *txn);
 
-static inline bool
-txn_is_linearizable(const struct txn *txn)
-{
-       return txn->isolation == TXN_ISOLATION_LINEARIZABLE;
-}
-
 /**
  * Check if a space supports linearizable access, i.e. it is either synchronous
  * or not replicated at all, and its engine prevents dirty reads.
@@ -794,8 +788,8 @@ static inline int
 txn_check_space_linearizability(const struct txn *txn,
                                const struct space *space)
 {
-       assert(txn_is_linearizable(txn));
-       (void)txn;
+       if (txn->isolation != TXN_ISOLATION_LINEARIZABLE)
+               return 0;
        /*
         * XXX: can't promise the user linearizability with Vinyl until
         * https://github.com/tarantool/tarantool/issues/5522 is fixed.
@@ -845,10 +839,8 @@ txn_begin_ro_stmt(struct space *space, struct txn **txn,
                        diag_set(ClientError, ER_TRANSACTION_CONFLICT);
                        return -1;
                }
-               if (txn_is_linearizable(*txn) &&
-                   txn_check_space_linearizability(*txn, space) != 0) {
+               if (txn_check_space_linearizability(*txn, space) != 0)
                        return -1;
-               }
                struct engine *engine = space->engine;
                return txn_begin_in_engine(engine, *txn);
        }

```
</details>

File: src/box/txn.h (hunk 54 above)
Comment (sergepetrenko) [reply src/box/txn.h:801]: Here: https://github.com/tarantool/tarantool/issues/7699.
Changed comment is in one of the diffs below.

File: changelogs/unreleased/linearizable-read.md (hunk 59 above)
Comment (locker) [reply changelogs/unreleased/linearizable-read.md:3]: Hmm, I don't see anything about features in this document. It says to use Past Tense to described changed or fixed behavior. Example from the text: "Added per-commit testing, updated YUM repositories". In your case it'd be natural to write: Introduced a new transaction level "linearaziable". Transaction started with `box.begin{txn_isolation = "linearizable"}` always see the latest data confirmed by the quorum.

It's minor though so I don't insist - up to you.

Comment (sergepetrenko) [reply changelogs/unreleased/linearizable-read.md:3]: Here:

> Use the present tense to describe new behavior.
Example
Data changes in read-only mode are now forbidden (gh-5231).

I'd say that new transaction isolation level is new behaviour.

File: src/box/txn.h (hunk 57 above)
Comment (locker) [reply src/box/txn.h]: Nit: I'd call the new function simply `txn_check_space` (check that a space can be used in a transaction) so that we can use it for other stuff, too. Maybe, even do some refactoring like this:

```C
/** Checks that a space can be used in a transaction. */
void txn_check_space(struct txn *txn, struct space *space)
{
    if (txn->isolation == TXN_ISOLATION_LINEARIZABLE)
        txn_check_space_linearizability(space);
    /* We could place other checks here without patching the call sites. */
}
```

File: src/box/relay.cc (hunk 58 above)
Comment (locker) [reply src/box/relay.cc:195]: Okay, let's leave as is. It doesn't seem to be critical.

File: src/box/txn.c (hunk 53 above)
Comment (locker) [reply src/box/txn.c:1406]: Yielding in `select` isn't good.

BTW, I just realized, we can't call `box_txn_set_isolation` via FFI anymore, because it may yield.

File: src/box/lua/schema.lua (hunk 50 above)
Comment (sergepetrenko) [reply src/box/lua/schema.lua:432]: >I think it should do just fine without any modifications.

Agreed

File: src/box/relay.cc (hunk 52 above)
Comment (locker) [reply src/box/relay.cc:889]: OK. Let's leave a timeout - not critical. We can remove it in future, if we make the tx <-> relay bus more reliable.

File: src/box/lua/schema.lua (hunk 50 above)
Comment (sergepetrenko) [reply src/box/lua/schema.lua:432]: I've reverted all the extra changes:
```diff
diff --git a/src/box/lua/schema.lua b/src/box/lua/schema.lua
index f5f045a68..2eead2d3a 100644
--- a/src/box/lua/schema.lua
+++ b/src/box/lua/schema.lua
@@ -388,9 +388,6 @@ box.internal.txn_isolation_level_map = txn_isolation_level_map
 
 -- Convert to numeric the value of txn isolation level, raise if failed.
 local function normalize_txn_isolation_level(txn_isolation)
-    if txn_isolation == nil then
-        return 0
-    end
     txn_isolation = txn_isolation_level_map[txn_isolation]
     if txn_isolation == nil then
         box.error(box.error.ILLEGAL_PARAMS,
@@ -419,7 +416,8 @@ box.begin = function(options)
     local txn_isolation
     if options then
         timeout = options.timeout
-        txn_isolation = options.txn_isolation
+        txn_isolation = options.txn_isolation and
+                        normalize_txn_isolation_level(options.txn_isolation)
     end
     if builtin.box_txn_begin() == -1 then
         box.error()
@@ -427,9 +425,8 @@ box.begin = function(options)
     if timeout then
         assert(builtin.box_txn_set_timeout(timeout) == 0)
     end
-    txn_isolation = normalize_txn_isolation_level(txn_isolation)
-    assert(txn_isolation ~= nil)
-    if builtin.box_txn_set_isolation(txn_isolation) ~= 0 then
+    if txn_isolation and
+       builtin.box_txn_set_isolation(txn_isolation) ~= 0 then
         box.rollback()
         box.error()
     end

```

File: src/box/txn.c (hunk 53 above)
Comment (sergepetrenko) [reply src/box/txn.c:1406]: I've asked @igormunkin, waiting for his response now.

**Comment by Gerold103** [comment]
> This could be used by multilevel proxies. 

Oh, I see now. So the sync actually is not a sync but kind of a stream ID. Btw, that case looks to me exactly like *has actually nothing to do with binary protocol syncs, which I'm used to*.

> A third-party applier may actually use non-zero sync numbers, in which case the relay will reply with the same sync number AFAICS.

Indeed, right. Relay does repeat the same sync over and over as the one which created this relay.

> Why do you find this solution complicated? Sergey just added a new request body field, that's all. 

Because we had to add a body to acks. Previously we could just live with the header and no body.

Anyway, it seems the old syncs might be of use, so I am good with the new approach. Thanks for the explanation.

File: src/box/txn.c (hunk 53 above)
Comment (igormunkin) [reply src/box/txn.c:1406]: It's better not to use FFI for the yielding routines. You can use FFI, if the routine yields unconditionally: JIT engine just blacklists this trace and doesn't compile it later (so there is no need in FFI here except this is a more convenient way to call your routine). You shouldn't use FFI, if yield is made under condition: the trace can be compiled for the call with no yield made, but the compiled trace might be executed with the call yielding underneath, that breaks trace assumptions and hence trace semantics. For the latter case tarantool `panic` call occurs and tarantool instance stops with `exit(EXIT_FAILURE)`.

Comment (sergepetrenko) [reply src/box/txn.c:1406]: @igormunkin, thanks for the clarification!
I've created a Lua/C wrapper for `box_txn_set_isolation`:

<details><summary>diff</summary>

```diff
diff --git a/src/box/lua/misc.cc b/src/box/lua/misc.cc
index db566903b..2c2096a6b 100644
--- a/src/box/lua/misc.cc
+++ b/src/box/lua/misc.cc
@@ -41,6 +41,7 @@
 #include "box/tuple_format.h"
 #include "box/lua/tuple.h"
 #include "box/xrow.h"
+#include "box/txn.h"
 #include "mpstream/mpstream.h"
 
 static uint32_t CTID_STRUCT_TUPLE_FORMAT_PTR;
@@ -220,6 +221,21 @@ lbox_select(lua_State *L)
 
 /* }}} */
 
+/**
+ * Lua/C wrapper over box_txn_set_isolation. Is used in lua sources instead of
+ * a ffi call because box_txn_set_isolation yields occasionally.
+ */
+static int
+lbox_txn_set_isolation(struct lua_State *L)
+{
+	if (lua_gettop(L) != 1 || !lua_isnumber(L, 1))
+		return luaL_error(L, "Usage txn_set_isolation(level)");
+	uint32_t level = lua_tonumber(L, 1);
+	int rc = box_txn_set_isolation(level);
+	lua_pushnumber(L, rc);
+	return 1;
+}
+
 /** {{{ Utils to work with tuple_format. **/
 
 struct tuple_format *
@@ -333,6 +349,7 @@ box_lua_misc_init(struct lua_State *L)
 	static const struct luaL_Reg boxlib_internal[] = {
 		{"select", lbox_select},
 		{"new_tuple_format", lbox_tuple_format_new},
+		{"txn_set_isolation", lbox_txn_set_isolation},
 		{NULL, NULL}
 	};
 
diff --git a/src/box/lua/schema.lua b/src/box/lua/schema.lua
index 2eead2d3a..6b8ecc648 100644
--- a/src/box/lua/schema.lua
+++ b/src/box/lua/schema.lua
@@ -426,7 +426,7 @@ box.begin = function(options)
         assert(builtin.box_txn_set_timeout(timeout) == 0)
     end
     if txn_isolation and
-       builtin.box_txn_set_isolation(txn_isolation) ~= 0 then
+       internal.txn_set_isolation(txn_isolation) ~= 0 then
         box.rollback()
         box.error()
     end
```
</details>

File: src/box/lua/schema.lua [hunk 60]
```diff
@@ -424,7 +426,7 @@ box.begin = function(options)
         assert(builtin.box_txn_set_timeout(timeout) == 0)
     end
     if txn_isolation and
-       builtin.box_txn_set_isolation(txn_isolation) ~= 0 then
+       internal.txn_set_isolation(txn_isolation) ~= 0 then
```
Comment (locker) [inline src/box/lua/schema.lua:429]: Nit: `builtin.box_txn_set_isolation` is now never used so its declaration should be removed from `ffi.cdef`.

Also, I don't quite like that `box.begin` will break a JIT trace in case any isolation level is specified, even the one that never yields. OTOH it shouldn't happen if the default isolation level is used so it should probably be acceptable.

**Review by locker — APPROVED** [review]

File: src/box/lua/schema.lua (hunk 60 above)
Comment (sergepetrenko) [reply src/box/lua/schema.lua:429]: > Nit: builtin.box_txn_set_isolation is now never used so its declaration should be removed from ffi.cdef.

Fixed, thanks!
```diff
diff --git a/src/box/lua/schema.lua b/src/box/lua/schema.lua
index 6b8ecc648..d32d9257f 100644
--- a/src/box/lua/schema.lua
+++ b/src/box/lua/schema.lua
@@ -74,8 +74,6 @@ ffi.cdef[[
     box_txn_begin();
     int
     box_txn_set_timeout(double timeout);
-    int
-    box_txn_set_isolation(uint32_t level);
     void
     memtx_tx_story_gc_step();
     /** \endcond public */
```

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Thanks for the fixes! Good work!

File: src/box/box.cc (hunk 16 above)
Comment (Gerold103) [reply src/box/box.cc:1918]: What is the progress here? Was it decided to leave it upside-down?

File: src/box/alter.cc [hunk 61]
```diff
@@ -2800,7 +2800,7 @@ on_replace_dd_truncate(struct trigger * /* trigger */, void *event)
 	 * spaces truncation.
 	 */
 	if (space_is_temporary(old_space) ||
-	    space_group_id(old_space) == GROUP_LOCAL) {
+	    space_is_local(old_space)) {
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/alter.cc:2803]: Thanks! Also noticed and fixed a couple of other places:
<details><summary>diff</summary>

```diff
diff --git a/src/box/lua/space.cc b/src/box/lua/space.cc
index bfa8e553e..eb662ff55 100644
--- a/src/box/lua/space.cc
+++ b/src/box/lua/space.cc
@@ -353,7 +353,7 @@ lbox_fillspace(struct lua_State *L, struct space *space, int i)
 
        /* space.group_id */
        lua_pushstring(L, "is_local");
-       lua_pushboolean(L, space_group_id(space) == GROUP_LOCAL);
+       lua_pushboolean(L, space_is_local(space));
        lua_settable(L, i);
 
        /* space.is_temp */
@@ -373,7 +373,7 @@ lbox_fillspace(struct lua_State *L, struct space *space, int i)
 
        /* space.is_sync */
        lua_pushstring(L, "is_sync");
-       lua_pushboolean(L, space->def->opts.is_sync);
+       lua_pushboolean(L, space_is_sync(space));
        lua_settable(L, i);
 
        lua_pushstring(L, "enabled");
diff --git a/src/box/txn.c b/src/box/txn.c
index e9598d26d..2377ecb76 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -920,7 +920,7 @@ txn_journal_entry_new(struct txn *txn)
                if (stmt->row->type != IPROTO_NOP) {
                        is_fully_nop = false;
                        is_sync = is_sync || (stmt->space != NULL &&
-                                             stmt->space->def->opts.is_sync);
+                                             space_is_sync(stmt->space));
                }
 
                if (stmt->row->replica_id == 0)
```
</details>

File: src/box/lua/schema.lua [hunk 62]
```diff
@@ -397,20 +397,25 @@ end
...
+            box.error(box.error.ILLEGAL_PARAMS,
+                      "timeout must be a number greater than 0")
+        end
+        return true
+    end,
+    txn_isolation = normalize_txn_isolation_level,
+}
+
 box.begin = function(options)
+    check_param_table(options, begin_options)
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/lua/schema.lua:412]: Done:
<details><summary>diff</summary>

```diff
diff --git a/src/box/lua/schema.lua b/src/box/lua/schema.lua
index 2b0970292..8c2def97e 100644
--- a/src/box/lua/schema.lua
+++ b/src/box/lua/schema.lua
@@ -409,10 +409,10 @@ local begin_options = {
 }
 
 box.begin = function(options)
-    check_param_table(options, begin_options)
     local timeout
     local txn_isolation
     if options then
+        check_param_table(options, begin_options)
         timeout = options.timeout
         txn_isolation = options.txn_isolation and
                         normalize_txn_isolation_level(options.txn_isolation)
```
</details>

File: src/box/xrow.c [hunk 63]
```diff
@@ -1921,26 +1921,97 @@ xrow_encode_join(struct xrow_header *row, const struct tt_uuid *instance_uuid)
...
+		return -1;
+	}
+	uint32_t map_size = mp_decode_map(&d);
+	for (uint32_t i = 0; i < map_size; i++) {
+		if (mp_typeof(*d) != MP_UINT) {
+			mp_next(&d);
+			mp_next(&d);
+			continue;
+		}
+		unsigned key = mp_decode_uint(&d);
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/xrow.c:1989]: Done.

File: src/box/xrow.h [hunk 64]
```diff
@@ -565,28 +565,56 @@ xrow_decode_register(const struct xrow_header *row,
...
- * @retval  0 Success.
+ * @retval 0 Success.
  * @retval -1 Memory error.
  */
 int
-xrow_encode_vclock(struct xrow_header *row, const struct vclock *vclock);
+xrow_encode_heartbeat(struct xrow_header *row, const struct vclock *vclock,
+		      uint64_t vclock_sync);
+
+/** Decode a heartbeat message.
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/xrow.h:580]: Thanks, fixed.

File: src/box/box.cc [hunk 65]
```diff
@@ -1805,6 +1811,228 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+check_vclock_sync_on_ack(struct trigger *trigger, void *event)
+{
+	struct replication_ack *ack = (struct replication_ack *)event;
+	struct sync_trigger_data *data =
+		(struct sync_trigger_data *)trigger->data;
+	uint32_t id = ack->source;
+	uint64_t sync = data->vclock_syncs[id];
+	int accounted_count = bit_count_u32(data->collected_vclock_map) + 1;
+	if (!bit_test(&data->collected_vclock_map, id) && sync > 0 &&
+	    ack->vclock_sync >= sync && accounted_count < data->count) {
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1850]: > Why isn't it `<= data->count` here

Because if it's equal to `data->count`, the waiter was already woken up on the previous iteration.

> and why do you increment accounted_count below even though it is already +1 on the line 1847

It's +1 on line 1847, because I count the local node separately.
+1 below is for the freshly accounted vclock.

Anyway, it seems I better account the local vclock in the map as well. Otherwise the code's rather complicated.
Will paste the diff here once the rework is done.

[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1850]: Here:
<details><summary>diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 01318c9cd..8c843ec5f 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1843,8 +1843,14 @@ check_vclock_sync_on_ack(struct trigger *trigger, void *event)
 	struct sync_trigger_data *data =
 		(struct sync_trigger_data *)trigger->data;
 	uint32_t id = ack->source;
+	/*
+	 * Anonymous replica acks are not counted for synchronous transactions,
+	 * so linearizable read shouldn't count them as well.
+	 */
+	if (id == 0)
+		return 0;
 	uint64_t sync = data->vclock_syncs[id];
-	int accounted_count = bit_count_u32(data->collected_vclock_map) + 1;
+	int accounted_count = bit_count_u32(data->collected_vclock_map);
 	if (!bit_test(&data->collected_vclock_map, id) && sync > 0 &&
 	    ack->vclock_sync >= sync && accounted_count < data->count) {
 		vclock_max_ignore0(data->vclock, ack->vclock);
@@ -1906,6 +1912,7 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
 		.count = vclock_count,
 		.is_timed_out = false,
 	};
+	bit_set(&data.collected_vclock_map, instance_id);
 	struct trigger on_relay_thread_start;
 	trigger_create(&on_relay_thread_start, relay_get_sync_on_start, &data,
 		       NULL);
@@ -1931,7 +1938,7 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
 		}
 	}
 
-	while (bit_count_u32(data.collected_vclock_map) + 1 < vclock_count &&
+	while (bit_count_u32(data.collected_vclock_map) < vclock_count &&
 	       !data.is_timed_out && !fiber_is_cancelled()) {
 		if (fiber_yield_deadline(deadline))
 			break;
@@ -1943,7 +1950,7 @@ box_collect_confirmed_vclock(struct vclock *confirmed_vclock, double deadline)
 		diag_set(FiberIsCancelled);
 		return -1;
 	}
-	if (bit_count_u32(data.collected_vclock_map) + 1 < vclock_count) {
+	if (bit_count_u32(data.collected_vclock_map) < vclock_count) {
 		diag_set(TimedOut);
 		return -1;
 	}

```
</details>

File: src/box/box.cc [hunk 66]
```diff
@@ -1805,6 +1811,228 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+	struct relay *relay = replica->relay;
+	struct sync_trigger_data *data =
+		(struct sync_trigger_data *)trigger->data;
+	uint32_t id = replica->id;
+	/* Already accounted. */
+	if (bit_test(&data->collected_vclock_map, id))
+		return 0;
+	if (relay_trigger_vclock_sync(relay, &data->vclock_syncs[id],
+				      data->deadline) != 0) {
+		diag_clear(diag_get());
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:1876]: Oh, I see.
It would be incremented once if I did `diag_move` to the fiber's diag, right?

File: src/box/box.cc [hunk 67]
```diff
@@ -1805,6 +1811,228 @@ box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
...
+	if (box_wait_vclock(&confirmed_vclock, deadline) != 0)
+		return -1;
+	/*
+	 * Finally, wait until all the synchronous transactions, which should be
+	 * visible to this tx, become visible.
+	 */
+	bool is_rollback;
+	timeout = deadline - ev_monotonic_now(loop());
+	if (!txn_limbo_is_empty(&txn_limbo) &&
+	    txn_limbo_wait_last_txn(&txn_limbo, &is_rollback, timeout) != 0)
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:2032]: It'd be fine to wait until tx with `lsn <= confirmed_vclock` is confirmed, but waiting for some non-last txn in the limbo is costly. You have to find the right txn in the list, going one by one.
OTOH, it's fine to wait a bit more than necessary, so I decided to put `txn_limbo_wait_last_txn` here.

File: src/box/relay.cc [hunk 68]
```diff
@@ -188,6 +188,14 @@ struct relay {
...
+	 * or other requests.
+	 */
+	bool is_sending_tx;
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/relay.cc:198]: Previously `relay_send_heartbeat` was only triggered after a `replication_timeout` has passed after `relay->last_row_time`. So even if it occured while scanning or sending a WAL, it was 99.999% not sent, because `last_row_time` was fresh.
Now when heartbeat is needed, it is sent regardless of `last_row_time`, so it's possible to break a tx being sent by such row. That's why there is this check.

There was a tiny chance of transaction boundary violation with a heartbeat before (if relay stalls after sending one row for too long), now this chance is much higher.

File: src/box/relay.cc [hunk 69]
```diff
@@ -758,13 +768,16 @@ relay_reader_f(va_list ap)
 static inline void
 relay_send_heartbeat(struct relay *relay)
 {
+	if (relay->is_sending_tx)
+		return;
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/relay.cc:772]: > If the heartbeat is skipped here, then a next one is sent only after the timeout.

Not really after the timeout, but after the wal is processed. There is a check for `relay->need_new_vclock_sync` in `relay_send_heartbeat_on_timeout`.

>  In case of a too rapid stream of transactions might wait for quite a long undefined time, right?

This is true. I can change that and make relay check if heartbeat dispatch is needed after each sent row.

```diff
diff --git a/src/box/relay.cc b/src/box/relay.cc
index 8581d520a..99c11681e 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -1240,7 +1240,10 @@ relay_send_row(struct xstream *stream, struct xrow_header *packet)
                                fiber_yield();
                        }
                }
-               relay->is_sending_tx = !packet->is_commit;
                relay_send(relay, packet);
+               relay->is_sending_tx = !packet->is_commit;
+               if (!relay->is_sending_tx) {
+                       relay_send_heartbeat_on_timeout(relay);
+               }
        }
 }
```

I also moved the `is_sending_tx` assignment below, so that it's updated only upon successful row dispatch.

File: src/box/txn.c [hunk 70]
```diff
@@ -607,6 +609,9 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type)
 		txn_set_flags(txn, TXN_IS_CONFLICTED);
 	}
 
+	if (space != NULL && txn_check_space(txn, space) != 0)
+		return -1;
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/txn.c:613]: Done, thanks.
```diff
diff --git a/src/box/txn.c b/src/box/txn.c
index a9068eb68..afa9d2e8a 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -609,9 +609,6 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type)
                txn_set_flags(txn, TXN_IS_CONFLICTED);
        }
 
-       if (space != NULL && txn_check_space(txn, space) != 0)
-               return -1;
-
        if (txn_check_can_continue(txn) != 0)
                return -1;
 
@@ -627,6 +624,9 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type)
        if (space == NULL)
                return 0;
 
+       if (txn_check_space(txn, space) != 0)
+               goto fail;
+
        struct engine *engine = space->engine;
        if (txn_begin_in_engine(engine, txn) != 0)
                goto fail;
```

File: src/box/txn.h [hunk 71]
```diff
@@ -777,6 +780,50 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t type);
 int
 txn_begin_in_engine(struct engine *engine, struct txn *txn);
 
+/**
+ * Check if a space supports linearizable access, i.e. it is either synchronous
+ * or not replicated at all, and its engine prevents dirty reads.
+ */
+static inline int
+txn_check_space_linearizability(const struct txn *txn,
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/txn.h:788]: Yep, makes sense. Done.

File: test/replication-luatest/linearizable_test.lua [hunk 72]
```diff
@@ -0,0 +1,314 @@
...
+    cg.servers[1]:exec(function()
+        box.space._cluster:delete{4}
+        box.space._cluster:delete{5}
+    end)
+    cg.servers[2]:wait_vclock_of(cg.servers[1])
+    cg.servers[3]:wait_vclock_of(cg.servers[1])
+end)
+
+g.test_no_dirty_reads = function(cg)
+    cg.replication_synchro_quorum = cg.servers[2]:exec(function()
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply test/replication-luatest/linearizable_test.lua:130]: Agree. Fixed.

File: src/box/box.cc (hunk 16 above)
Comment (sergepetrenko) [reply src/box/box.cc:1918]: I'd like to leave it upside down for now. We can always return to that later. I filed an [issue](https://github.com/tarantool/tarantool/issues/7723).

The protocol remains compatible: both relay and applier may encode a vclock and a vclock_sync in a heartbeat.
Currently relay only encodes vclock_sync, and applier encodes both fields. When and if we decide to implement the reverse channel, relay may start sending vclock in the heartbeat. Both vclock and vclock_sync are fields in the heartbeat body, so everything stays compatible.

I don't want to do that now because it would require making relay thread poll tx to find out the latest vclock. This is against relay architecture: it doesn't perform requests to tx thread.

File: src/box/box.cc (hunk 66 above)
[the remark this answers is not in the document]
Comment (Gerold103) [reply src/box/box.cc:1882]: Yes.

File: src/box/xrow.c [hunk 73]
```diff
@@ -1921,26 +1921,97 @@ xrow_encode_join(struct xrow_header *row, const struct tt_uuid *instance_uuid)
...
 	assert(data <= buf + size);
 	row->body[0].iov_base = buf;
 	row->body[0].iov_len = (data - buf);
 	row->bodycnt = 1;
-	row->type = IPROTO_OK;
+	return 0;
+}
+
+int
+xrow_decode_heartbeat(const struct xrow_header *row, struct vclock *vclock,
```
[the remark this answers is not in the document]
Comment (Gerold103) [reply src/box/xrow.c:1968]: > But why do you want to separate them anyway?

Currently we rely on heartbeats being the same request in both directions. It is not so even now - relay doesn't send vclocks, sadly. In scope of #7253 I will add term to acks, only in one direction too. As a result we would have 3 optional fields: `vclock_sync`, `vclock`, `term`. Their subset would define what request we want to send - applier->relay ack or relay->applier ack. The result will be a mess just like we have at the moment with `xrow_decode_subscribe()` - it is used for almost everything with various subsets of fields, which is super confusing.

What is worse, we keep growing this confusion - for example, `xrow_decode_heartbeat()` is called by `xrow_decode_vclock()` - these are different requests.

If we update heartbeats with a new field `term`, it will affect all their encode/decode calls (even in relay->applier direction) and even non-related code like `xrow_decode_vclock()`.

This is why I would rather split these acks into separate requests/functions, even if there would be some small code duplication like `vclock_sync` which can be sent by either of them optionally.

> Now the protocol is ready for performing the requests in correct direction

Not really, we will still need to change it again. At least, to send vclocks from relay (on demand, not always, right?). However my ranting is rather about the code, not about the protocol. How `xrow_decode_subscribe()` is used is truly terrifying. I would want us to avoid the same for acks/heartbeats.

> But it might need that later

Yes, exactly. So what I want us to try is to isolate such changes as much as possible. If we change messages relay->applier only, then it shouldn't affect the code, which encodes/decodes applier->relay messages.

Anyway, you don't need to do it all now, as I said. I am doing this big rework of xrow.h in my own patchset already. I couldn't stand to add another optional parameter `term` to `xrow_decode_subscribe()`.

**Review by Gerold103 — APPROVED** [review]
Thanks for the diligent work on this one! Can't wait for #7723 now.

File: src/box/xrow.c (hunk 73 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/xrow.c:1968]: > In scope of https://github.com/tarantool/tarantool/issues/7253 I will add term to acks, only in one direction too. As a result we would have 3 optional fields: vclock_sync, vclock, term. Their subset would define what request we want to send - applier->relay ack or relay->applier ack. The result will be a mess just like we have at the moment with xrow_decode_subscribe() - it is used for almost everything with various subsets of fields, which is super confusing.

I see now, thanks for the explanation!

>> Now the protocol is ready for performing the requests in correct direction
>
> Not really, we will still need to change it again. At least, to send vclocks from relay (on demand, not always, right?)

Yes, I meant that vclock is an optional field, so adding it later won't break the backward compatibility. Old appliers would ignore it, and new ones would use it.

> I couldn't stand to add another optional parameter term to xrow_decode_subscribe().

Yep, it's a mess already.

By the way, I was thinking, maybe we could use some code generation here to reduce the amount of almost identicat functions? I can't imagine how exactly this would be implemented, but I was thinking something like this. It can't be compiled and I'm not sure that C preprocessor has that functionality.
```c
#define DECODE_REPLICATION(func_name, PARAM_LIST)
void
func_name(struct xrow_header *row, PARAM_LIST)
...
    i = mp_decode_map(...);
    for (j = 0; j < i; j++) {
        key = mp_decode_uint(...);
        switch(key) {
#if IPROTO_VCLOCK in PARAM_LIST
        case IPROTO_VCLOCK:
             //decode vclock
             break;
#endif
#if IPROTO_RAFT_TERM in PARAM_LIST
        case IPROTO_RAFT_TERM:
             //decode term
             break;
#endif
       case default:
            //unknown or unneeded key, ignore
        }
   }
```

And do the same for ENCODE_REPLICATION.

And then we would have one mega-macro ENCODE_REPLICATION and DECODE_REPLICATION and a bunch of
functions
ENCODE_REPLICATION(xrow_encode_subscribe, IPROTO_UUID, IPROTO_VCLOCK, ...)

DECODE_REPLICATION(xrow_decode_heartbeat, IPROTO_VCLOCK, IPROTO_VCLOCK_SYNC, ...)

**Comment by CuriousGeorgiy** [comment]
Why was this merged without `full-ci` label?

File: src/box/xrow.c (hunk 73 above)
[the remark this answers is not in the document]
Comment (Gerold103) [reply src/box/xrow.c:1968]: I am doing something like that in my patch. But without compile-time optimizations sadly. That won't be possible with macros in a sane way, but could be possible with C++ templates. We could convert xrow.c to C++ if ever decide we want these opts.

[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/xrow.c:1968]: > I am doing something like that in my patch. But without compile-time optimizations sadly. 

Ok, looking forward to seeing that in your patch!

> We could convert xrow.c to C++ if ever decide we want these opts.

This might be reasonable. But I'm not sure.
