### PR TITLE
memtx: handle OOM on statement rollback

### LINKED ISSUE #11171: Another failure on rollback on OOM
The issue is transaction is not yet aborted when we fail to commit statement and rollback it. As it is not aborted we may fail to allocate memory for index (see `memtx_index_extent_alloc()`). And rollback is failed which is not expected.

```c
#5  0x000076da47a44177 in __assert_fail (assertion=0x64a8782125ee "0",
    file=0x64a878214188 "./tarantool/src/box/memtx_engine.cc", line=697,
    function=0x64a878214630 "void memtx_engine_rollback_statement(engine*, txn*, txn_stmt*)") at assert.c:105
#6  0x000064a877acb10f in memtx_engine_rollback_statement (engine=0x64a89556ad70,
    txn=0x76da4709c038, stmt=0x76da4709c2b0)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/memtx_engine.cc:697
#7  0x000064a877b97e2b in engine_rollback_statement (engine=0x64a89556ad70,
    txn=0x76da4709c038, stmt=0x76da4709c2b0)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/engine.h:421
#8  0x000064a877b9a128 in txn_rollback_one_stmt (txn=0x76da4709c038,
    stmt=0x76da4709c2b0) at /home/shiny/dev/tarantool-ee/tarantool/src/box/txn.c:383
#9  0x000064a877b9a34a in txn_rollback_to_svp (txn=0x76da4709c038, svp=0x0,
    run_triggers=false) at /home/shiny/dev/tarantool-ee/tarantool/src/box/txn.c:432
#10 0x000064a877b9daa2 in txn_rollback_stmt (txn=0x76da4709c038)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/txn.c:1251
#11 0x000064a877b9b919 in txn_commit_stmt (txn=0x76da4709c038,
    request=0x76da09180c20)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/txn.c:731
#12 0x000064a877bafa16 in box_process_rw (request=0x76da09180c20,
    space=0x64a895572ae0, result=0x76da09180d48)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/box.cc:509
#13 0x000064a877bbcfda in box_process1 (request=0x76da09180c20,
    result=0x76da09180d48)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/box.cc:3846
#14 0x000064a877bbdbff in box_replace (space_id=288,
    tuple=0x76da4706b240 "\226\315\002",
    tuple_end=0x76da4706b3a5 'P' <repeats 200 times>..., result=0x76da09180d48)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/box.cc:4042
```

### PR DESCRIPTION
**Pull request by nshy**
Currently during statement rollback we either assume that rollback does not fail or panic on failure. Unfortunately rollback can fail due to OOM because of opened read view and reservations done for rollback.

Let's handle this situation similar to transaction rollback in [1]. Let's set new transaction flag `TXN_STMT_ROLLBACK` before doing statement rollback and check it when we need to allocate memory in memtx arena. If flag is set and memory exhausted then allocate memory outside the arena.

Handle is added to `HASH` and `TREE `indexes. `RTREE` data structure does not handle OOM's yet, we have heuristic reservation in `RTREE `index. `BITSET` partially allocates memory using `realloc`.

To test the situation we can add something like `ERRINJ_INDEX_ALLOC_COUNTDOWN` injection to imitate memory exhausting during statement execution. But tests with such injection are fragile - they depend specific pattern of memory allocation in index data structure. Instead let's build injection around index data structure calls using introduced `INDEX_OOM_ERRINJ`. This way we may have injections that are not possible but it does not hurt. It is not a problem that we check we handle impossible failures too in tests.

[1] commit 32ea713af0a4 ("box: fix crash on rollback on memtx memory OOM and massive index change")

The second commit closes #11171.

### CODE REVIEW

File: src/box/memtx_hash.cc [hunk 1]
```diff
@@ -354,34 +354,29 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
 	/* HASH index doesn't support ordering. */
 	*successor = NULL;
 
-	if (new_tuple) {
+	if (new_tuple != NULL) {
 		uint32_t h = tuple_hash(new_tuple, base->def->key_def);
 		struct tuple *dup_tuple = NULL;
-		uint32_t pos = light_index_replace(hash_table, h, new_tuple,
-						   &dup_tuple);
+		uint32_t pos = INDEX_OOM_ERRINJ(
```
Comment (locker) [inline src/box/memtx_hash.cc:360]: Better make the wrapper set the txn flag on oom. Then it should be renamed so as not to mention errinj.

Also, passing the failure return code just for a couple of light methods doesn't look good. Better wrap those methods to return -1 on oom.

File: src/box/memtx_hash.cc [hunk 2]
```diff
@@ -354,34 +354,29 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
...
-				if (pos == light_index_end) {
-					panic("Failed to allocate memory in "
-					      "recover of int hash_table");
-				}
-			}
+			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+			VERIFY(INDEX_OOM_ERRINJ(light_index_delete, -1,
+						hash_table, pos) == 0);
+			if (dup_tuple)
+				VERIFY(INDEX_OOM_ERRINJ(
```
Comment (locker) [inline src/box/memtx_hash.cc:376]: I see no point in using the wrapper in case the function isn't expected to fail.

File: src/box/memtx_hash.cc [hunk 3]
```diff
@@ -354,34 +354,29 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
...
+					hash_table, h, new_tuple, &dup_tuple);
 		if (pos == light_index_end)
-			pos = light_index_insert(hash_table, h, new_tuple);
-
-		ERROR_INJECT(ERRINJ_HASH_INDEX_REPLACE, {
-			light_index_delete(hash_table, pos);
-			pos = light_index_end;
-		});
-
+			pos = INDEX_OOM_ERRINJ(light_index_insert, -1,
```
Comment (locker) [inline src/box/memtx_hash.cc:364]: This sets `pos` to -1 on errinj but `light_index_insert` still returns `light_index_end` on oom...

File: src/box/txn.h [hunk 4]
```diff
@@ -119,6 +119,8 @@ enum txn_flag {
 	TXN_IS_STARTED_IN_ENGINE = 0x400,
 	/** Transaction supports multiversion concurrency control. */
 	TXN_SUPPORTS_MVCC = 0x800,
+	/** Set during statement rollback. */
```
Comment (locker) [inline src/box/txn.h:122]: Please improve the comment - say how and why it's set.

File: src/box/txn.c [hunk 5]
```diff
@@ -1236,6 +1236,7 @@ txn_rollback_stmt(struct txn *txn)
 	assert(txn->in_sub_stmt > 0);
 	txn->in_sub_stmt--;
 	txn_rollback_to_svp(txn, txn->sub_stmt_begin[txn->in_sub_stmt], false);
+	txn_clear_flags(txn, TXN_STMT_ROLLBACK);
```
Comment (locker) [inline src/box/txn.c:1239]: Please also add assertions ensuring the flag isn't set on begin/commit stmt.

File: src/box/memtx_tree.cc [hunk 6]
```diff
@@ -1480,12 +1483,32 @@ memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
...
+			}
+			goto oom;
+		}
 		*result = old_tuple;
 	} else {
 		*result = NULL;
 	}
 	return 0;
+oom:
+	diag_set(OutOfMemory, MEMTX_EXTENT_SIZE,
```
Comment (locker) [inline src/box/memtx_tree.cc:1509]: Why do you set diag here? It should be set by the function that failed with oom.

File: test/fuzz/lua/test_engine.lua [hunk 7]
```diff
@@ -1479,11 +1479,6 @@ local errinj_set = {
         enable = enable_errinj_boolean,
         disable = disable_errinj_boolean,
     },
-    -- Set to true to fail insertion into memtx hash index.
-    ERRINJ_HASH_INDEX_REPLACE = {
```
Comment (locker) [inline test/fuzz/lua/test_engine.lua:1483]: You should add the new error injections to the fuzzer.

File: changelogs/unreleased/memtx-stmt-rollback-oom.md [hunk 8]
```diff
@@ -0,0 +1,3 @@
+## bugfix/memtx
+
+* Fixed possible crash/panic on hitting memtx memory OOM.
```
Comment (locker) [inline changelogs/unreleased/memtx-stmt-rollback-oom.md:3]: Missing issue reference.

"hitting memtx memory out-of-memory" sounds weird.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/memtx_hash.cc (hunk 1 above)
Comment (nshy) [reply src/box/memtx_hash.cc:360]: Changed as discussed f2f. Introduced wrappers around index data structures. Wrappers add injection and set txn flag on OOM.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/index.cc b/src/box/index.cc
index 148f2398ac..ef3974c4dd 100644
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -295,6 +295,7 @@ index_check_dup(struct index *index, struct tuple *old_tuple,
 			diag_set(ClientError, ER_CANT_UPDATE_PRIMARY_KEY,
 				 index->def->space_name, index->def->space_id,
 				 old_tuple, new_tuple, NULL);
+			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
 			return -1;
 		}
 	} else { /* dup_tuple != NULL */
@@ -310,6 +311,7 @@ index_check_dup(struct index *index, struct tuple *old_tuple,
 				 index->def->name, index->def->space_name,
 				 tuple_str(dup_tuple), tuple_str(new_tuple),
 				 dup_tuple, new_tuple);
+			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
 			return -1;
 		}
 	}
diff --git a/src/box/index.h b/src/box/index.h
index f0cb9ca6c9..e483474dc6 100644
--- a/src/box/index.h
+++ b/src/box/index.h
@@ -1217,19 +1217,30 @@ index_read_view_create_arrow_stream(
 					     stream);
 }
 
+#ifndef NDEBUG
+
 /**
- * Add OOM behaviour to func. After countdown starts to fail returning
- * `oom_value' unless TXN_STMT_ROLLBACK flag is set.
+ * Inject error on OOM.
+ *
+ * After `ERRINJ_INDEX_OOM_COUNTDOWN' countdown injection start to fail
+ * unless txn flag `TXN_STMT_ROLLBACK' is set.
  */
-#define INDEX_OOM_ERRINJ(func, oom_value, ...) ({ \
-	ERROR_INJECT_COUNTDOWN(ERRINJ_INDEX_OOM_COUNTDOWN, { \
-		struct errinj *e = errinj(ERRINJ_INDEX_OOM, ERRINJ_BOOL); \
-		e->bparam = true; \
-	}); \
-	(!errinjs[ERRINJ_INDEX_OOM].bparam || \
-	 txn_has_flag(in_txn(), TXN_STMT_ROLLBACK) ? \
-		func(__VA_ARGS__) : oom_value); \
-})
+#define INDEX_ERROR_INJECT_OOM(CODE) \
+	do { \
+		ERROR_INJECT_COUNTDOWN(ERRINJ_INDEX_OOM_COUNTDOWN, { \
+			struct errinj *e = errinj(ERRINJ_INDEX_OOM, \
+						  ERRINJ_BOOL); \
+			e->bparam = true; \
+		}); \
+		if (errinjs[ERRINJ_INDEX_OOM].bparam && \
+		    !txn_has_flag(in_txn(), TXN_STMT_ROLLBACK)) { \
+			diag_set(OutOfMemory, 777, \
+				 "errinj", "errinj"); \
+			CODE; \
+		} \
+	} while (0)
+
+#endif /** #ifndef NDEBUG */
 
 /*
  * Virtual method stubs.
diff --git a/src/box/memtx_hash.cc b/src/box/memtx_hash.cc
index aa983bb998..5ce046bbe5 100644
--- a/src/box/memtx_hash.cc
+++ b/src/box/memtx_hash.cc
@@ -343,6 +343,91 @@ memtx_hash_index_get_internal(struct index *base, const char *key,
 	return 0;
 }
 
+/**
+ * If key is present then replace it's tuple with `new_tuple'. Otherwise
+ * insert `new_tuple'. In case of replace old tuple is returned in `dup_tuple'.
+ * Insert or replace position is returned in `pos_out'.
+ *
+ * Also adds OOM injection and setting txn flag `TXN_STMT_ROLLBACK'.
+ *
+ * Returns 0 on success and -1 on OOM (diag is set).
+ */
+static int
+light_index_replace_impl(struct light_index_core *hash_table, uint32_t hash,
+			struct tuple *new_tuple, struct tuple **dup_tuple,
+			uint32_t *pos_out)
+{
+	uint32_t pos;
+	INDEX_ERROR_INJECT_OOM(goto fail);
+	pos = light_index_replace(hash_table, hash, new_tuple, dup_tuple);
+	if (pos == light_index_end) {
+		INDEX_ERROR_INJECT_OOM(goto fail);
+		pos = light_index_insert(hash_table, hash, new_tuple);
+		if (pos == light_index_end)
+			goto fail;
+		*dup_tuple = NULL;
+	}
+	*pos_out = pos;
+	return 0;
+fail:
+	txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+	return -1;
+}
+
+/**
+ * Similar to light_index_insert but returns status and not position.
+ *
+ * Also adds OOM injection and setting txn flag `TXN_STMT_ROLLBACK' on OOM
+ * to `light_index_insert'.
+ *
+ * Returns 0 on success and -1 on OOM (diag is set).
+ */
+static int
+light_index_insert_impl(struct light_index_core *hash_table, uint32_t hash,
+			struct tuple *new_tuple)
+{
+	INDEX_ERROR_INJECT_OOM(goto fail);
+	if (light_index_insert(hash_table, hash, new_tuple) == light_index_end)
+		goto fail;
+	return 0;
+fail:
+	txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+	return -1;
+}
+
+/**
+ * Adds OOM injection and setting txn flag `TXN_STMT_ROLLBACK' on OOM
+ * to `light_index_delete'.
+ */
+static uint32_t
+light_index_delete_impl(struct light_index_core *hash_table, uint32_t pos)
+{
+	INDEX_ERROR_INJECT_OOM(goto fail);
+	if (light_index_delete(hash_table, pos) != 0)
+		goto fail;
+	return 0;
+fail:
+	txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+	return -1;
+}
+
+/**
+ * Adds OOM injection and setting txn flag `TXN_STMT_ROLLBACK' on OOM
+ * to `light_index_delete_value'.
+ */
+static uint32_t
+light_index_delete_value_impl(struct light_index_core *hash_table,
+			      uint32_t hash, struct tuple *tuple)
+{
+	INDEX_ERROR_INJECT_OOM(goto fail);
+	if (light_index_delete_value(hash_table, hash, tuple) != 0)
+		goto fail;
+	return 0;
+fail:
+	txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+	return -1;
+}
+
 static int
 memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
 			 struct tuple *new_tuple, enum dup_replace_mode mode,
@@ -356,27 +441,17 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
 
 	if (new_tuple != NULL) {
 		uint32_t h = tuple_hash(new_tuple, base->def->key_def);
-		struct tuple *dup_tuple = NULL;
-		uint32_t pos = INDEX_OOM_ERRINJ(
-					light_index_replace, light_index_end,
-					hash_table, h, new_tuple, &dup_tuple);
-		if (pos == light_index_end)
-			pos = INDEX_OOM_ERRINJ(light_index_insert, -1,
-					       hash_table, h, new_tuple);
-		if (pos == light_index_end) {
-			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
-			goto oom;
-		}
+		struct tuple *dup_tuple;
+		uint32_t pos;
+		if (light_index_replace_impl(hash_table, h,
+					     new_tuple, &dup_tuple, &pos) != 0)
+			return -1;
 		if (index_check_dup(base, old_tuple, new_tuple,
 				    dup_tuple, mode) != 0) {
-			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
-			VERIFY(INDEX_OOM_ERRINJ(light_index_delete, -1,
-						hash_table, pos) == 0);
+			VERIFY(light_index_delete_impl(hash_table, pos) == 0);
 			if (dup_tuple)
-				VERIFY(INDEX_OOM_ERRINJ(
-						light_index_insert, -1,
-						hash_table, h,
-						dup_tuple) != light_index_end);
+				VERIFY(light_index_insert_impl(
+						hash_table, h, dup_tuple) == 0);
 			return -1;
 		}
 
@@ -388,25 +463,19 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
 
 	if (old_tuple != NULL) {
 		uint32_t h = tuple_hash(old_tuple, base->def->key_def);
-		if (INDEX_OOM_ERRINJ(light_index_delete_value, -1, hash_table,
-				     h, old_tuple) != 0) {
-			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+		if (light_index_delete_value_impl(hash_table, h,
+						  old_tuple) != 0) {
 			if (new_tuple != NULL) {
 				uint32_t h = tuple_hash(new_tuple,
 							base->def->key_def);
-				VERIFY(INDEX_OOM_ERRINJ(
-						light_index_delete_value, -1,
+				VERIFY(light_index_delete_value_impl(
 						hash_table, h, new_tuple) == 0);
 			}
-			goto oom;
+			return -1;
 		}
 	}
 	*result = old_tuple;
 	return 0;
-oom:
-	diag_set(OutOfMemory, MEMTX_EXTENT_SIZE,
-		 "hash_table", "key");
-	return -1;
 }
 
 /** Implementation of create_iterator for memtx hash index. */
diff --git a/src/box/memtx_tree.cc b/src/box/memtx_tree.cc
index 4fc427470d..bf5d098e8e 100755
--- a/src/box/memtx_tree.cc
+++ b/src/box/memtx_tree.cc
@@ -1433,6 +1433,64 @@ tree_iterator_position_func(struct iterator *it, const char **pos,
 						pos, size);
 }
 
+/**
+ * Adds OOM injection and setting txn flag `TXN_STMT_ROLLBACK' on OOM
+ * to `memtx_tree_insert'.
+ */
+template <bool USE_HINT>
+static int
+memtx_tree_insert_impl(memtx_tree_t<USE_HINT> *tree,
+		       struct memtx_tree_data<USE_HINT> new_data,
+		       struct memtx_tree_data<USE_HINT> *dup_data,
+		       struct memtx_tree_data<USE_HINT> *suc_data)
+{
+	INDEX_ERROR_INJECT_OOM(goto fail);
+	if (memtx_tree_insert(tree, new_data, dup_data, suc_data) != 0)
+		goto fail;
+	return 0;
+fail:
+	txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+	return -1;
+}
+
+/**
+ * Adds OOM injection and setting txn flag `TXN_STMT_ROLLBACK' on OOM
+ * to `memtx_tree_delete'.
+ */
+template <bool USE_HINT>
+static int
+memtx_tree_delete_impl(memtx_tree_t<USE_HINT> *tree,
+		       struct memtx_tree_data<USE_HINT> elem_data,
+		       struct memtx_tree_data<USE_HINT> *del_data)
+{
+	INDEX_ERROR_INJECT_OOM(goto fail);
+	if (memtx_tree_delete(tree, elem_data, del_data) != 0)
+		goto fail;
+	return 0;
+fail:
+	txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+	return -1;
+}
+
+/**
+ * Adds OOM injection and setting txn flag `TXN_STMT_ROLLBACK' on OOM
+ * to `memtx_tree_delete_value'.
+ */
+template <bool USE_HINT>
+static int
+memtx_tree_delete_value_impl(memtx_tree_t<USE_HINT> *tree,
+			     struct memtx_tree_data<USE_HINT> elem_data,
+			     struct memtx_tree_data<USE_HINT> *del_data)
+{
+	INDEX_ERROR_INJECT_OOM(goto fail);
+	if (memtx_tree_delete_value(tree, elem_data, del_data) != 0)
+		goto fail;
+	return 0;
+fail:
+	txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+	return -1;
+}
+
 template <bool USE_HINT>
 static int
 memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
@@ -1453,22 +1511,19 @@ memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
 		dup_data.tuple = suc_data.tuple = NULL;
 
 		/* Try to optimistically replace the new_tuple. */
-		if (INDEX_OOM_ERRINJ(memtx_tree_insert, -1, &index->tree,
-				     new_data, &dup_data, &suc_data) != 0) {
-			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
-			goto oom;
-		}
+		if (memtx_tree_insert_impl(
+				&index->tree, new_data, &dup_data,
+				&suc_data) != 0)
+			return -1;
 
 		if (index_check_dup(base, old_tuple, new_tuple,
 				    dup_data.tuple, mode) != 0) {
-			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
-			VERIFY(INDEX_OOM_ERRINJ(
-					memtx_tree_delete, -1, &index->tree,
-					new_data, NULL) == 0);
+			VERIFY(memtx_tree_delete_impl<USE_HINT>(
+					&index->tree, new_data, NULL) == 0);
 			if (dup_data.tuple != NULL)
-				VERIFY(INDEX_OOM_ERRINJ(
-					memtx_tree_insert, -1, &index->tree,
-					dup_data, NULL, NULL) == 0);
+				VERIFY(memtx_tree_insert_impl<USE_HINT>(
+						&index->tree, dup_data, NULL,
+						NULL) == 0);
 			return -1;
 		}
 		*successor = suc_data.tuple;
@@ -1483,9 +1538,8 @@ memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
 		old_data.tuple = old_tuple;
 		if (USE_HINT)
 			old_data.set_hint(tuple_hint(old_tuple, cmp_def));
-		if (INDEX_OOM_ERRINJ(memtx_tree_delete, -1, &index->tree,
-				     old_data, NULL) != 0) {
-			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+		if (memtx_tree_delete_impl<USE_HINT>(&index->tree, old_data,
+						     NULL) != 0) {
 			if (new_tuple != NULL &&
 			    !tuple_key_is_excluded(new_tuple, key_def,
 						   MULTIKEY_NONE)) {
@@ -1494,21 +1548,17 @@ memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
 				if (USE_HINT)
 					new_data.set_hint(tuple_hint(new_tuple,
 								     cmp_def));
-				VERIFY(INDEX_OOM_ERRINJ(memtx_tree_delete, -1,
-							&index->tree,
-							new_data, NULL) == 0);
+				VERIFY(memtx_tree_delete_impl<USE_HINT>(
+						&index->tree, new_data,
+						NULL) == 0);
 			}
-			goto oom;
+			return -1;
 		}
 		*result = old_tuple;
 	} else {
 		*result = NULL;
 	}
 	return 0;
-oom:
-	diag_set(OutOfMemory, MEMTX_EXTENT_SIZE,
-		 "memtx_tree_index", "replace");
-	return -1;
 }
 
 /**
@@ -1529,13 +1579,9 @@ memtx_tree_index_replace_multikey_one(struct memtx_tree_index<true> *index,
 	new_data.hint = hint;
 	dup_data.tuple = NULL;
 	*is_multikey_conflict = false;
-	if (INDEX_OOM_ERRINJ(memtx_tree_insert, -1, &index->tree, new_data,
-			     &dup_data, successor_data) != 0) {
-		txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
-		diag_set(OutOfMemory, MEMTX_EXTENT_SIZE, "memtx_tree_index",
-			 "replace");
+	if (memtx_tree_insert_impl(&index->tree, new_data, &dup_data,
+				   successor_data) != 0)
 		return -1;
-	}
 	if (dup_data.tuple == new_tuple) {
 		/*
 		 * When tuple contains the same key multiple
@@ -1545,14 +1591,12 @@ memtx_tree_index_replace_multikey_one(struct memtx_tree_index<true> *index,
 		*is_multikey_conflict = true;
 	} else if (index_check_dup(&index->base, old_tuple, new_tuple,
 				   dup_data.tuple, mode) != 0) {
-		txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
 		/* Rollback replace. */
-		VERIFY(INDEX_OOM_ERRINJ(memtx_tree_delete, -1, &index->tree,
-					new_data, NULL) == 0);
+		VERIFY(memtx_tree_delete_impl<true>(
+				&index->tree, new_data, NULL) == 0);
 		if (dup_data.tuple != NULL)
-			VERIFY(INDEX_OOM_ERRINJ(memtx_tree_insert, -1,
-						&index->tree, dup_data, NULL,
-						NULL) == 0);
+			VERIFY(memtx_tree_insert_impl<true>(
+				&index->tree, dup_data, NULL, NULL) == 0);
 		return -1;
 	}
 	*replaced_data = dup_data;
@@ -1587,9 +1631,8 @@ memtx_tree_index_replace_multikey_rollback(struct memtx_tree_index<true> *index,
 			if (tuple_key_is_excluded(replaced_tuple, key_def, i))
 				continue;
 			data.hint = i;
-			VERIFY(INDEX_OOM_ERRINJ(memtx_tree_insert, -1,
-						&index->tree, data, NULL,
-						NULL) == 0);
+			VERIFY(memtx_tree_insert_impl<true>(
+					&index->tree, data, NULL, NULL) == 0);
 		}
 	}
 	if (new_tuple == NULL)
@@ -1603,7 +1646,7 @@ memtx_tree_index_replace_multikey_rollback(struct memtx_tree_index<true> *index,
 		if (tuple_key_is_excluded(new_tuple, key_def, i))
 			continue;
 		data.hint = i;
-		VERIFY(INDEX_OOM_ERRINJ(memtx_tree_delete_value, -1,
+		VERIFY(memtx_tree_delete_value_impl<true>(
 					&index->tree, data, NULL) == 0);
 	}
 }
@@ -1711,14 +1754,13 @@ memtx_tree_index_replace_multikey(struct index *base, struct tuple *old_tuple,
 			if (tuple_key_is_excluded(old_tuple, key_def, i))
 				continue;
 			data.hint = i;
-			if (INDEX_OOM_ERRINJ(memtx_tree_delete_value, -1,
-					     &index->tree, data, NULL) != 0) {
+			if (memtx_tree_delete_value_impl<true>
+					(&index->tree, data, NULL) != 0) {
 				uint32_t multikey_count = 0;
 				if (new_tuple != 0)
 					multikey_count =
 						tuple_multikey_count(new_tuple,
 								     cmp_def);
-				txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
 				memtx_tree_index_replace_multikey_rollback(
 					index, new_tuple, old_tuple,
 					multikey_count);
@@ -1754,13 +1796,13 @@ memtx_tree_func_index_replace_rollback(struct memtx_tree_index<true> *index,
 {
 	struct func_key_undo *entry;
 	rlist_foreach_entry(entry, new_keys, link) {
-		VERIFY(INDEX_OOM_ERRINJ(memtx_tree_delete_value, -1,
+		VERIFY(memtx_tree_delete_value_impl<true>(
 					&index->tree, entry->key, NULL) == 0);
 		tuple_unref((struct tuple *)entry->key.hint);
 	}
 	rlist_foreach_entry(entry, old_keys, link)
-		VERIFY(INDEX_OOM_ERRINJ(memtx_tree_insert, -1, &index->tree,
-					entry->key, NULL, NULL) == 0);
+		VERIFY(memtx_tree_insert_impl<true>(
+				&index->tree, entry->key, NULL, NULL) == 0);
 }
 
 /**
@@ -1879,10 +1921,8 @@ memtx_tree_func_index_replace(struct index *base, struct tuple *old_tuple,
 		while (key_list_iterator_next(&it, &key) == 0 && key != NULL) {
 			data.hint = (hint_t) key;
 			deleted_data.tuple = NULL;
-			if (INDEX_OOM_ERRINJ(memtx_tree_delete_value, -1,
-					     &index->tree, data,
-					     &deleted_data) != 0) {
-				txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+			if (memtx_tree_delete_value_impl(&index->tree, data,
+							 &deleted_data) != 0) {
 				memtx_tree_func_index_replace_rollback(
 					index, &old_keys, &new_keys);
 				return -1;
```

</details>

File: src/box/memtx_hash.cc (hunk 2 above)
Comment (nshy) [reply src/box/memtx_hash.cc:376]: Discussed f2f. We used newly introduced wrappers here instead. This way we check that txn flag is set on statement rollback in tests.

File: src/box/memtx_hash.cc (hunk 3 above)
Comment (nshy) [reply src/box/memtx_hash.cc:364]: Fixed. This by fortune become `light_index_end`)

File: src/box/txn.h (hunk 4 above)
Comment (nshy) [reply src/box/txn.h:122]: Done.

```diff
-       /** Set during statement rollback. */
+       /**
+        * Set during statement rollback.
+        *
+        * If statetement is rolled back we should not fail due to OOM.
+        * This flag is set when statement rollback is started. If it is set
+        * then memory allocated even if memory limit is reached.
+        */
```

File: src/box/txn.c (hunk 5 above)
Comment (nshy) [reply src/box/txn.c:1239]: Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/txn.c b/src/box/txn.c
index 2777a1265f..5c5378e8b7 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -606,6 +606,7 @@ txn_begin_stmt(struct txn *txn, struct space *space, uint16_t typ>
 {
        assert(txn == in_txn());
        assert(txn != NULL);
+       assert(!txn_has_flag(txn, TXN_STMT_ROLLBACK));
        if (txn->in_sub_stmt > TXN_SUB_STMT_MAX) {
                diag_set(ClientError, ER_SUB_STMT_MAX);
                return -1;
@@ -667,6 +668,7 @@ int
 txn_commit_stmt(struct txn *txn, struct request *request)
 {
        assert(txn->in_sub_stmt > 0);
+       assert(!txn_has_flag(txn, TXN_STMT_ROLLBACK));
        /*
         * Run on_replace triggers. For now, disallow mutation
         * of tuples in the trigger.
```

</details>

File: src/box/memtx_tree.cc (hunk 6 above)
Comment (nshy) [reply src/box/memtx_tree.cc]: Fixed. `box/errinj_index.test.lua` test is updated.

<details>
<summary>diff</summary>

```diff
diff --git a/test/box/errinj_index.result b/test/box/errinj_index.result
index 96e21837fd..c7df22a411 100644
--- a/test/box/errinj_index.result
+++ b/test/box/errinj_index.result
@@ -93,7 +93,7 @@ res
 ...
 for i = 501,2500 do s:insert{i, i} end
 ---
-- error: Failed to allocate 16384 bytes in memtx_tree_index for replace
+- error: Failed to allocate 16384 bytes in mempool for new slab
 ...
 s:delete{1} -- still can delete, it does not require extents if no read view
 ---
@@ -136,7 +136,7 @@ check_iter_and_size(621)
 ...
 for i = 2501,3500 do s:insert{i, i} end
 ---
-- error: Failed to allocate 16384 bytes in memtx_tree_index for replace
+- error: Failed to allocate 16384 bytes in mempool for new slab
 ...
 s:delete{2} -- still can delete, it does not require extents if no read view
 ---
@@ -322,7 +322,7 @@ res
 ...
 for i = 501,2500 do s:insert{i, i} end
 ---
-- error: Failed to allocate 16384 bytes in hash_table for key
+- error: Failed to allocate 16384 bytes in mempool for new slab
 ...
 s:delete{1} -- still can delete, it does not require extents if no read view
 ---
@@ -362,7 +362,7 @@ check_iter_and_size(1023)
 ...
 for i = 2501,3500 do s:insert{i, i} end
 ---
-- error: Failed to allocate 16384 bytes in hash_table for key
+- error: Failed to allocate 16384 bytes in mempool for new slab
 ...
 s:delete{2} -- still can delete, it does not require extents if no read view
 ---
@@ -391,7 +391,7 @@ res
 ...
 for i = 3501,4500 do s:insert{i, i} end
 ---
-- error: Failed to allocate 16384 bytes in hash_table for key
+- error: Failed to allocate 16384 bytes in mempool for new slab
 ...
 s:delete{3} -- still can delete, it does not require extents if no read view
 ---
@@ -468,7 +468,7 @@ errinj.set("ERRINJ_INDEX_OOM", true)
 ...
 s:replace{3594, 3594}
 ---
-- error: Failed to allocate 16384 bytes in hash_table for key
+- error: Failed to allocate 777 bytes in errinj for errinj
 ...
 errinj.set("ERRINJ_INDEX_OOM", false)
 ---
```
</details>

File: test/fuzz/lua/test_engine.lua (hunk 7 above)
Comment (nshy) [reply test/fuzz/lua/test_engine.lua:1483]: Done. 

After that #11171 is reproduced quite easily. I'll fix it in the distinct commit of this PR.

<details>
<summary>diff</summary>

```diff
diff --git a/test/fuzz/lua/test_engine.lua b/test/fuzz/lua/test_engine.lua
index 22da2d2f02..46fbec6f73 100644
--- a/test/fuzz/lua/test_engine.lua
+++ b/test/fuzz/lua/test_engine.lua
@@ -1474,6 +1474,16 @@ local errinj_set = {
         enable = enable_errinj_boolean,
         disable = disable_errinj_boolean,
     },
+    -- Set to number of passes before starting to fail primitive index data
+    -- operations.
+    ERRINJ_INDEX_OOM_COUNTDOWN = {
+        enable = function()
+            return math.random(100)
+        end,
+        disable = function()
+            return -1
+        end,
+    },
     -- Set to true to fail index iterator creation.
     ERRINJ_INDEX_ITERATOR_NEW = {
         enable = enable_errinj_boolean,
```

</details>

File: changelogs/unreleased/memtx-stmt-rollback-oom.md (hunk 8 above)
Comment (nshy) [reply changelogs/unreleased/memtx-stmt-rollback-oom.md:3]: There is no issue for this commit. However there is a ticket for similar issue in memcs - https://github.com/tarantool/tarantool-ee/issues/1107.

Reworded to to `Fixed possible crash/panic on hitting memtx memory limit`.

File: src/box/memtx_engine.cc [hunk 9]
```diff
@@ -2148,7 +2148,9 @@ memtx_index_extent_alloc(struct matras_allocator *matras_allocator)
 		goto fail;
 	return ret;
 fail:
-	if (in_txn() != NULL && in_txn()->status == TXN_ABORTED) {
+	if (in_txn() != NULL &&
+	    (in_txn()->status == TXN_ABORTED ||
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_engine.cc:2152]: The flag is cleared when statement is rolled back. But if need to rollback whole transaction after that we should not fail too. In this case `TXN_ABORTED` is set.

For example `test_rollback_to_svp` is crashed without this check.

```c++
#4  0x0000778f4c4334eb in __assert_fail_base (fmt=<optimized out>,
    assertion=<optimized out>, file=<optimized out>, line=696,
    function=<optimized out>) at assert.c:118
#5  0x00005f464e857c0a in memtx_engine_rollback_statement (engine=0x5f467b3cf740,
    txn=0x778f4bc25038, stmt=0x778f4bc252b0)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/memtx_engine.cc:696
#6  0x00005f464e925744 in engine_rollback_statement (engine=0x5f467b3cf740,
    txn=0x778f4bc25038, stmt=0x778f4bc252b0)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/engine.h:437
#7  0x00005f464e927ad0 in txn_rollback_one_stmt (txn=0x778f4bc25038,
    stmt=0x778f4bc252b0) at /home/shiny/dev/tarantool-ee/tarantool/src/box/txn.c:372
#8  0x00005f464e929578 in txn_complete_fail (txn=0x778f4bc25038)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/txn.c:779
#9  0x00005f464e92b44e in txn_rollback (txn=0x778f4bc25038)
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/txn.c:1253
#10 0x00005f464e92bdaa in box_txn_rollback ()
    at /home/shiny/dev/tarantool-ee/tarantool/src/box/txn.c:1423
#11 0x00005f464ea44ffd in lbox_rollback (L=0x41122328)
```

File: src/box/index.cc [hunk 10]
```diff
@@ -310,6 +311,7 @@ index_check_dup(struct index *index, struct tuple *old_tuple,
 				 index->def->name, index->def->space_name,
 				 tuple_str(dup_tuple), tuple_str(new_tuple),
 				 dup_tuple, new_tuple);
+			txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
 			return -1;
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/index.cc:315]: Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/index.cc b/src/box/index.cc
index ef3974c4dd..6b35031a42 100644
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -295,8 +295,7 @@ index_check_dup(struct index *index, struct tuple *old_tuple,
                        diag_set(ClientError, ER_CANT_UPDATE_PRIMARY_KEY,
                                 index->def->space_name, index->def->space_id,
                                 old_tuple, new_tuple, NULL);
-                       txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
-                       return -1;
+                       goto fail;
                }
        } else { /* dup_tuple != NULL */
                if (dup_tuple != old_tuple &&
@@ -311,11 +310,13 @@ index_check_dup(struct index *index, struct tuple *old_tuple,
                                 index->def->name, index->def->space_name,
                                 tuple_str(dup_tuple), tuple_str(new_tuple),
                                 dup_tuple, new_tuple);
-                       txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
-                       return -1;
+                       goto fail;
                }
        }
        return 0;
+fail:
+       txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
+       return -1;
 }

 char *
```

</details>

File: src/box/memtx_hash.cc [hunk 11]
```diff
@@ -391,10 +461,18 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
...
-	if (old_tuple) {
+	if (old_tuple != NULL) {
 		uint32_t h = tuple_hash(old_tuple, base->def->key_def);
-		int res = light_index_delete_value(hash_table, h, old_tuple);
-		assert(res == 0); (void) res;
+		if (light_index_delete_value_impl(hash_table, h,
+						  old_tuple) != 0) {
+			if (new_tuple != NULL) {
+				uint32_t h = tuple_hash(new_tuple,
+							base->def->key_def);
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_hash.cc:470]: Done.

File: src/box/memtx_hash.cc [hunk 12]
```diff
@@ -343,6 +343,91 @@ memtx_hash_index_get_internal(struct index *base, const char *key,
...
+ * If key is present then replace it's tuple with `new_tuple'. Otherwise
+ * insert `new_tuple'. In case of replace old tuple is returned in `dup_tuple'.
+ * Insert or replace position is returned in `pos_out'.
+ *
+ * Also adds OOM injection and setting txn flag `TXN_STMT_ROLLBACK'.
+ *
+ * Returns 0 on success and -1 on OOM (diag is set).
+ */
+static int
+light_index_replace_impl(struct light_index_core *hash_table, uint32_t hash,
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_hash.cc:356]: Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/memtx_hash.cc b/src/box/memtx_hash.cc
index 1716f768e5..ea8789aadc 100644
--- a/src/box/memtx_hash.cc
+++ b/src/box/memtx_hash.cc
@@ -353,18 +353,19 @@ memtx_hash_index_get_internal(struct index *base, const char *key,
  * Returns 0 on success and -1 on OOM (diag is set).
  */
 static int
-light_index_replace_impl(struct light_index_core *hash_table, uint32_t hash,
-			 struct tuple *new_tuple, struct tuple **dup_tuple,
-			 uint32_t *pos_out)
+memtx_hash_index_replace_impl(struct memtx_hash_index *index, uint32_t hash,
+			      struct tuple *new_tuple, struct tuple **dup_tuple,
+			      uint32_t *pos_out)
 {
 	uint32_t pos;
 	if (index_inject_oom() != 0)
 		goto fail;
-	pos = light_index_replace(hash_table, hash, new_tuple, dup_tuple);
+	pos = light_index_replace(&index->hash_table, hash, new_tuple,
+				  dup_tuple);
 	if (pos == light_index_end) {
 		if (index_inject_oom() != 0)
 			goto fail;
-		pos = light_index_insert(hash_table, hash, new_tuple);
+		pos = light_index_insert(&index->hash_table, hash, new_tuple);
 		if (pos == light_index_end)
 			goto fail;
 		*dup_tuple = NULL;
@@ -385,12 +386,13 @@ light_index_replace_impl(struct light_index_core *hash_table, uint32_t hash,
  * Returns 0 on success and -1 on OOM (diag is set).
  */
 static int
-light_index_insert_impl(struct light_index_core *hash_table, uint32_t hash,
-			struct tuple *new_tuple)
+memtx_hash_index_insert_impl(struct memtx_hash_index *index, uint32_t hash,
+			     struct tuple *new_tuple)
 {
 	if (index_inject_oom() != 0)
 		goto fail;
-	if (light_index_insert(hash_table, hash, new_tuple) == light_index_end)
+	if (light_index_insert(&index->hash_table,
+			       hash, new_tuple) == light_index_end)
 		goto fail;
 	return 0;
 fail:
@@ -403,11 +405,11 @@ light_index_insert_impl(struct light_index_core *hash_table, uint32_t hash,
  * to `light_index_delete'.
  */
 static uint32_t
-light_index_delete_impl(struct light_index_core *hash_table, uint32_t pos)
+memtx_hash_index_delete_impl(struct memtx_hash_index *index, uint32_t pos)
 {
 	if (index_inject_oom() != 0)
 		goto fail;
-	if (light_index_delete(hash_table, pos) != 0)
+	if (light_index_delete(&index->hash_table, pos) != 0)
 		goto fail;
 	return 0;
 fail:
@@ -420,12 +422,13 @@ light_index_delete_impl(struct light_index_core *hash_table, uint32_t pos)
  * to `light_index_delete_value'.
  */
 static uint32_t
-light_index_delete_value_impl(struct light_index_core *hash_table,
-			      uint32_t hash, struct tuple *tuple)
+memtx_hash_index_delete_value_impl(struct memtx_hash_index *index,
+				   struct tuple *tuple)
 {
+	uint32_t h = tuple_hash(tuple, index->base.def->key_def);
 	if (index_inject_oom() != 0)
 		goto fail;
-	if (light_index_delete_value(hash_table, hash, tuple) != 0)
+	if (light_index_delete_value(&index->hash_table, h, tuple) != 0)
 		goto fail;
 	return 0;
 fail:
@@ -439,7 +442,6 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
 			 struct tuple **result, struct tuple **successor)
 {
 	struct memtx_hash_index *index = (struct memtx_hash_index *)base;
-	struct light_index_core *hash_table = &index->hash_table;
 
 	/* HASH index doesn't support ordering. */
 	*successor = NULL;
@@ -448,15 +450,15 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
 		uint32_t h = tuple_hash(new_tuple, base->def->key_def);
 		struct tuple *dup_tuple;
 		uint32_t pos;
-		if (light_index_replace_impl(hash_table, h,
-					     new_tuple, &dup_tuple, &pos) != 0)
+		if (memtx_hash_index_replace_impl(
+				index, h, new_tuple, &dup_tuple, &pos) != 0)
 			return -1;
 		if (index_check_dup(base, old_tuple, new_tuple,
 				    dup_tuple, mode) != 0) {
-			VERIFY(light_index_delete_impl(hash_table, pos) == 0);
+			VERIFY(memtx_hash_index_delete_impl(index, pos) == 0);
 			if (dup_tuple)
-				VERIFY(light_index_insert_impl(
-						hash_table, h, dup_tuple) == 0);
+				VERIFY(memtx_hash_index_insert_impl(
+						index, h, dup_tuple) == 0);
 			return -1;
 		}
 
@@ -467,15 +469,10 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
 	}
 
 	if (old_tuple != NULL) {
-		uint32_t h = tuple_hash(old_tuple, base->def->key_def);
-		if (light_index_delete_value_impl(hash_table, h,
-						  old_tuple) != 0) {
-			if (new_tuple != NULL) {
-				uint32_t h = tuple_hash(new_tuple,
-							base->def->key_def);
-				VERIFY(light_index_delete_value_impl(
-						hash_table, h, new_tuple) == 0);
-			}
+		if (memtx_hash_index_delete_value_impl(index, old_tuple) != 0) {
+			if (new_tuple != NULL)
+				VERIFY(memtx_hash_index_delete_value_impl(
+						index, new_tuple) == 0);
 			return -1;
 		}
 	}
diff --git a/src/box/memtx_tree.cc b/src/box/memtx_tree.cc
index 7aeafac09d..c6713af07f 100755
--- a/src/box/memtx_tree.cc
+++ b/src/box/memtx_tree.cc
@@ -1439,14 +1439,14 @@ tree_iterator_position_func(struct iterator *it, const char **pos,
  */
 template<bool USE_HINT>
 static int
-memtx_tree_insert_impl(memtx_tree_t<USE_HINT> *tree,
-		       struct memtx_tree_data<USE_HINT> new_data,
-		       struct memtx_tree_data<USE_HINT> *dup_data,
-		       struct memtx_tree_data<USE_HINT> *suc_data)
+memtx_tree_index_insert_impl(struct memtx_tree_index<USE_HINT> *index,
+			     struct memtx_tree_data<USE_HINT> new_data,
+			     struct memtx_tree_data<USE_HINT> *dup_data,
+			     struct memtx_tree_data<USE_HINT> *suc_data)
 {
 	if (index_inject_oom() != 0)
 		goto fail;
-	if (memtx_tree_insert(tree, new_data, dup_data, suc_data) != 0)
+	if (memtx_tree_insert(&index->tree, new_data, dup_data, suc_data) != 0)
 		goto fail;
 	return 0;
 fail:
@@ -1460,13 +1460,13 @@ memtx_tree_insert_impl(memtx_tree_t<USE_HINT> *tree,
  */
 template<bool USE_HINT>
 static int
-memtx_tree_delete_impl(memtx_tree_t<USE_HINT> *tree,
-		       struct memtx_tree_data<USE_HINT> elem_data,
-		       struct memtx_tree_data<USE_HINT> *del_data)
+memtx_tree_index_delete_impl(struct memtx_tree_index<USE_HINT> *index,
+			     struct memtx_tree_data<USE_HINT> elem_data,
+			     struct memtx_tree_data<USE_HINT> *del_data)
 {
 	if (index_inject_oom() != 0)
 		goto fail;
-	if (memtx_tree_delete(tree, elem_data, del_data) != 0)
+	if (memtx_tree_delete(&index->tree, elem_data, del_data) != 0)
 		goto fail;
 	return 0;
 fail:
@@ -1480,13 +1480,13 @@ memtx_tree_delete_impl(memtx_tree_t<USE_HINT> *tree,
  */
 template<bool USE_HINT>
 static int
-memtx_tree_delete_value_impl(memtx_tree_t<USE_HINT> *tree,
-			     struct memtx_tree_data<USE_HINT> elem_data,
-			     struct memtx_tree_data<USE_HINT> *del_data)
+memtx_tree_index_delete_value_impl(struct memtx_tree_index<USE_HINT> *index,
+				   struct memtx_tree_data<USE_HINT> elem_data,
+				   struct memtx_tree_data<USE_HINT> *del_data)
 {
 	if (index_inject_oom() != 0)
 		goto fail;
-	if (memtx_tree_delete_value(tree, elem_data, del_data) != 0)
+	if (memtx_tree_delete_value(&index->tree, elem_data, del_data) != 0)
 		goto fail;
 	return 0;
 fail:
@@ -1514,18 +1514,17 @@ memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
 		dup_data.tuple = suc_data.tuple = NULL;
 
 		/* Try to optimistically replace the new_tuple. */
-		if (memtx_tree_insert_impl(
-				&index->tree, new_data, &dup_data,
-				&suc_data) != 0)
+		if (memtx_tree_index_insert_impl(index, new_data, &dup_data,
+						 &suc_data) != 0)
 			return -1;
 
 		if (index_check_dup(base, old_tuple, new_tuple,
 				    dup_data.tuple, mode) != 0) {
-			VERIFY(memtx_tree_delete_impl<USE_HINT>(
-					&index->tree, new_data, NULL) == 0);
+			VERIFY(memtx_tree_index_delete_impl<USE_HINT>(
+						index, new_data, NULL) == 0);
 			if (dup_data.tuple != NULL)
-				VERIFY(memtx_tree_insert_impl<USE_HINT>(
-						&index->tree, dup_data, NULL,
+				VERIFY(memtx_tree_index_insert_impl<USE_HINT>(
+						index, dup_data, NULL,
 						NULL) == 0);
 			return -1;
 		}
@@ -1541,8 +1540,8 @@ memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
 		old_data.tuple = old_tuple;
 		if (USE_HINT)
 			old_data.set_hint(tuple_hint(old_tuple, cmp_def));
-		if (memtx_tree_delete_impl<USE_HINT>(&index->tree, old_data,
-						     NULL) != 0) {
+		if (memtx_tree_index_delete_impl<USE_HINT>(
+					index, old_data, NULL) != 0) {
 			if (new_tuple != NULL &&
 			    !tuple_key_is_excluded(new_tuple, key_def,
 						   MULTIKEY_NONE)) {
@@ -1551,9 +1550,8 @@ memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
 				if (USE_HINT)
 					new_data.set_hint(tuple_hint(new_tuple,
 								     cmp_def));
-				VERIFY(memtx_tree_delete_impl<USE_HINT>(
-						&index->tree, new_data,
-						NULL) == 0);
+				VERIFY(memtx_tree_index_delete_impl<USE_HINT>(
+						index, new_data, NULL) == 0);
 			}
 			return -1;
 		}
@@ -1582,8 +1580,8 @@ memtx_tree_index_replace_multikey_one(struct memtx_tree_index<true> *index,
 	new_data.hint = hint;
 	dup_data.tuple = NULL;
 	*is_multikey_conflict = false;
-	if (memtx_tree_insert_impl(&index->tree, new_data, &dup_data,
-				   successor_data) != 0)
+	if (memtx_tree_index_insert_impl(index, new_data, &dup_data,
+					 successor_data) != 0)
 		return -1;
 	if (dup_data.tuple == new_tuple) {
 		/*
@@ -1595,11 +1593,11 @@ memtx_tree_index_replace_multikey_one(struct memtx_tree_index<true> *index,
 	} else if (index_check_dup(&index->base, old_tuple, new_tuple,
 				   dup_data.tuple, mode) != 0) {
 		/* Rollback replace. */
-		VERIFY(memtx_tree_delete_impl<true>(
-				&index->tree, new_data, NULL) == 0);
+		VERIFY(memtx_tree_index_delete_impl<true>(
+				index, new_data, NULL) == 0);
 		if (dup_data.tuple != NULL)
-			VERIFY(memtx_tree_insert_impl<true>(
-				&index->tree, dup_data, NULL, NULL) == 0);
+			VERIFY(memtx_tree_index_insert_impl<true>(
+					index, dup_data, NULL, NULL) == 0);
 		return -1;
 	}
 	*replaced_data = dup_data;
@@ -1634,8 +1632,8 @@ memtx_tree_index_replace_multikey_rollback(struct memtx_tree_index<true> *index,
 			if (tuple_key_is_excluded(replaced_tuple, key_def, i))
 				continue;
 			data.hint = i;
-			VERIFY(memtx_tree_insert_impl<true>(
-					&index->tree, data, NULL, NULL) == 0);
+			VERIFY(memtx_tree_index_insert_impl<true>(
+					index, data, NULL, NULL) == 0);
 		}
 	}
 	if (new_tuple == NULL)
@@ -1649,8 +1647,8 @@ memtx_tree_index_replace_multikey_rollback(struct memtx_tree_index<true> *index,
 		if (tuple_key_is_excluded(new_tuple, key_def, i))
 			continue;
 		data.hint = i;
-		VERIFY(memtx_tree_delete_value_impl<true>(
-					&index->tree, data, NULL) == 0);
+		VERIFY(memtx_tree_index_delete_value_impl<true>(
+					index, data, NULL) == 0);
 	}
 }
 
@@ -1757,8 +1755,8 @@ memtx_tree_index_replace_multikey(struct index *base, struct tuple *old_tuple,
 			if (tuple_key_is_excluded(old_tuple, key_def, i))
 				continue;
 			data.hint = i;
-			if (memtx_tree_delete_value_impl<true>(
-					&index->tree, data, NULL) != 0) {
+			if (memtx_tree_index_delete_value_impl<true>(
+					index, data, NULL) != 0) {
 				uint32_t multikey_count = 0;
 				if (new_tuple != 0)
 					multikey_count =
@@ -1799,13 +1797,13 @@ memtx_tree_func_index_replace_rollback(struct memtx_tree_index<true> *index,
 {
 	struct func_key_undo *entry;
 	rlist_foreach_entry(entry, new_keys, link) {
-		VERIFY(memtx_tree_delete_value_impl<true>(
-					&index->tree, entry->key, NULL) == 0);
+		VERIFY(memtx_tree_index_delete_value_impl<true>(
+					index, entry->key, NULL) == 0);
 		tuple_unref((struct tuple *)entry->key.hint);
 	}
 	rlist_foreach_entry(entry, old_keys, link)
-		VERIFY(memtx_tree_insert_impl<true>(
-				&index->tree, entry->key, NULL, NULL) == 0);
+		VERIFY(memtx_tree_index_insert_impl<true>(
+				index, entry->key, NULL, NULL) == 0);
 }
 
 /**
@@ -1924,8 +1922,8 @@ memtx_tree_func_index_replace(struct index *base, struct tuple *old_tuple,
 		while (key_list_iterator_next(&it, &key) == 0 && key != NULL) {
 			data.hint = (hint_t) key;
 			deleted_data.tuple = NULL;
-			if (memtx_tree_delete_value_impl(&index->tree, data,
-							 &deleted_data) != 0) {
+			if (memtx_tree_index_delete_value_impl(
+					index, data, &deleted_data) != 0) {
 				memtx_tree_func_index_replace_rollback(
 					index, &old_keys, &new_keys);
 				return -1;
```

</details>

File: src/box/memtx_hash.cc [hunk 13]
```diff
@@ -343,6 +343,91 @@ memtx_hash_index_get_internal(struct index *base, const char *key,
...
+			 struct tuple *new_tuple, struct tuple **dup_tuple,
+			 uint32_t *pos_out)
+{
+	uint32_t pos;
+	INDEX_ERROR_INJECT_OOM(goto fail);
+	pos = light_index_replace(hash_table, hash, new_tuple, dup_tuple);
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_hash.cc:362]: Just wanted to keep it unchanged in case of failure. Fixed.

<details>
<summary>diff</summary>

```diff
 static int
 memtx_hash_index_replace_impl(struct memtx_hash_index *index, uint32_t hash,
                              struct tuple *new_tuple, struct tuple **dup_tuple,
-                             uint32_t *pos_out)
+                             uint32_t *pos)
 {
-       uint32_t pos;
        if (index_inject_oom() != 0)
                goto fail;
-       pos = light_index_replace(&index->hash_table, hash, new_tuple,
-                                 dup_tuple);
-       if (pos == light_index_end) {
+       *pos = light_index_replace(&index->hash_table, hash, new_tuple,
+                                  dup_tuple);
+       if (*pos == light_index_end) {
                if (index_inject_oom() != 0)
                        goto fail;
-               pos = light_index_insert(&index->hash_table, hash, new_tuple);
-               if (pos == light_index_end)
+               *pos = light_index_insert(&index->hash_table, hash, new_tuple);
+               if (*pos == light_index_end)
                        goto fail;
                *dup_tuple = NULL;
        }
-       *pos_out = pos;
        return 0;
 fail:
        txn_set_flags(in_txn(), TXN_STMT_ROLLBACK);
```

</summary>

File: src/box/memtx_engine.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (locker) [reply src/box/memtx_engine.cc:2152]: Maybe, set/clear the flag in `txn_rollback_one_stmt` then?

File: src/box/index.cc [hunk 14]
```diff
@@ -959,6 +962,24 @@ index_read_view_delete(struct index_read_view *rv)
...
+
+int
+index_inject_oom(void)
+{
+	struct errinj *e = errinj(ERRINJ_INDEX_OOM, ERRINJ_BOOL);
+	ERROR_INJECT_COUNTDOWN(ERRINJ_INDEX_OOM_COUNTDOWN, e->bparam = true);
+	if (e->bparam && !txn_has_flag(in_txn(), TXN_STMT_ROLLBACK) &&
+	    in_txn()->status != TXN_ABORTED) {
+		diag_set(OutOfMemory, 777,
+			 "errinj", "errinj");
```
Comment (locker) [inline src/box/index.cc:975]: Could be written in one line. Also, let's use 0 instead of 777 :)

File: src/box/memtx_hash.cc [hunk 15]
```diff
@@ -343,45 +343,120 @@ memtx_hash_index_get_internal(struct index *base, const char *key,
...
-			if (dup_tuple) {
-				uint32_t pos = light_index_insert(hash_table, h, dup_tuple);
-				if (pos == light_index_end) {
-					panic("Failed to allocate memory in "
-					      "recover of int hash_table");
-				}
-			}
+			VERIFY(memtx_hash_index_delete_impl(index, pos) == 0);
+			if (dup_tuple)
+				VERIFY(memtx_hash_index_insert_impl(
```
Comment (locker) [inline src/box/memtx_hash.cc:458]: Let's move hash computation to replace/insert? It's cheap and we'll compute it twice only on error path so it should be fine, I think.

File: src/box/memtx_engine.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_engine.cc:2152]: Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/index.cc b/src/box/index.cc
index 6d409f4bb6..85b1f46525 100644
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -969,9 +969,8 @@ index_inject_oom(void)
 {
 	struct errinj *e = errinj(ERRINJ_INDEX_OOM, ERRINJ_BOOL);
 	ERROR_INJECT_COUNTDOWN(ERRINJ_INDEX_OOM_COUNTDOWN, e->bparam = true);
-	if (e->bparam && !txn_has_flag(in_txn(), TXN_STMT_ROLLBACK) &&
-	    in_txn()->status != TXN_ABORTED) {
-		diag_set(OutOfMemory, 777,
+	if (e->bparam && !txn_has_flag(in_txn(), TXN_STMT_ROLLBACK)) {
+		diag_set(OutOfMemory, 0,
 			 "errinj", "errinj");
 		return -1;
 	}
diff --git a/src/box/memtx_engine.cc b/src/box/memtx_engine.cc
index 6227fa16cb..78e2daf3ca 100644
--- a/src/box/memtx_engine.cc
+++ b/src/box/memtx_engine.cc
@@ -2148,9 +2148,7 @@ memtx_index_extent_alloc(struct matras_allocator *matras_allocator)
 		goto fail;
 	return ret;
 fail:
-	if (in_txn() != NULL &&
-	    (in_txn()->status == TXN_ABORTED ||
-	     txn_has_flag(in_txn(), TXN_STMT_ROLLBACK))) {
+	if (in_txn() != NULL && txn_has_flag(in_txn(), TXN_STMT_ROLLBACK)) {
 		/*
 		 * We cannot sanely reserve blocks for rollback because strictly
 		 * speaking the whole index can change. We cannot tolerate
diff --git a/src/box/txn.c b/src/box/txn.c
index 3b05215c09..bc8212127e 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -368,8 +368,10 @@ txn_rollback_one_stmt(struct txn *txn, struct txn_stmt *stmt)
 		diag_log();
 		panic("statement rollback trigger failed");
 	}
+	txn_set_flags(txn, TXN_STMT_ROLLBACK);
 	if (stmt->engine != NULL && stmt->space != NULL)
 		engine_rollback_statement(stmt->engine, txn, stmt);
+	txn_clear_flags(txn, TXN_STMT_ROLLBACK);
 }
 
 /*
@@ -417,7 +419,6 @@ txn_rollback_to_svp(struct txn *txn, struct stailq_entry *svp,
 							      &rollback) != 0)
 			diag_log();
 	}
-	txn_set_flags(txn, TXN_STMT_ROLLBACK);
 	stailq_foreach_entry(stmt, &rollback, next) {
 		txn_rollback_one_stmt(txn, stmt);
 		if (stmt->row != NULL)
@@ -426,7 +427,6 @@ txn_rollback_to_svp(struct txn *txn, struct stailq_entry *svp,
 		stmt->space = NULL;
 		stmt->row = NULL;
 	}
-	txn_clear_flags(txn, TXN_STMT_ROLLBACK);
 }
 
 /*
diff --git a/test/box/errinj_index.result b/test/box/errinj_index.result
index c7df22a411..dc5012c667 100644
--- a/test/box/errinj_index.result
+++ b/test/box/errinj_index.result
@@ -468,7 +468,7 @@ errinj.set("ERRINJ_INDEX_OOM", true)
 ...
 s:replace{3594, 3594}
 ---
-- error: Failed to allocate 777 bytes in errinj for errinj
+- error: Failed to allocate 0 bytes in errinj for errinj
 ...
 errinj.set("ERRINJ_INDEX_OOM", false)
 ---
```

</details>

File: src/box/index.cc (hunk 14 above)
Comment (nshy) [reply src/box/index.cc:975]: Fixed as part of another conversation.

**Review by locker — APPROVED** [review]

**Review by ligurio — APPROVED** [review]

**Review by xuniq — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 3.4.

@nshy Please cherry-pick to 3.3 and 3.2.
