### PR TITLE
uri: fix IPv6 parsing regression, encapsulate IPv6 addresses in brackets []

### LINKED ISSUE #9556: Uri module doesn't work with IPv6 correctly
`Uri` module doesn't work correctly with IPv6. According to [RFC 2732](https://www.rfc-editor.org/rfc/rfc2732) uri must be wrapped into `[]` before adding :port. 

1. `Uri` module doesn't parse full address at all:

```
tarantool> uri.parse('http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html')
---
- null
- 'Incorrect URI: expected host:service or /unix.socket'
...

tarantool> u = uri.parse('http://FEDC:BA98:7654:3210:FEDC:BA98:7654:3210:80/index.html')
---
- host: FEDC
  scheme: http
  path: BA98:7654:3210:FEDC:BA98:7654:3210:80/index.html
...

tarantool> uri.format(u)
---
- http://FEDCBA98:7654:3210:FEDC:BA98:7654:3210:80/index.html
...
```

2. `Uri` module doesn't add brackets, when ipv6 is used, in `uri.format`:

```
tarantool> uri.parse('[0:0:0:0:0:0:0:1]:3300')
---
- host: 0:0:0:0:0:0:0:1
  service: '3300'
  ipv6: 0:0:0:0:0:0:0:1
...

tarantool> u = uri.parse('[0:0:0:0:0:0:0:1]:3300')
---
...

tarantool> uri.format(u)
---
- 0:0:0:0:0:0:0:1:3300
...
```

### PR DESCRIPTION
**Pull request by mandesero**
Before this patch `uri.parse(<uri-string-with-ipv6-address>)` did not work correctly. In particular, it did not parse an IPv6 address if it contained `A-F`. It is a regression caused by commit https://github.com/tarantool/tarantool/commit/1376aad9b3fd1fa3c42a220dafeadaa63387f7a2 ("Refactor src/uri.rl to support RFC3986 and add Lua bindings").

This patch fixes a bug where characters `A-F` are not supported in IPv6. Also this patch adds encapsulation for IPv6 addresses in brackets when calling uri.format (as per RFC 2732).

Closes #9556

### CODE REVIEW

File: src/lua/uri.lua [hunk 1]
```diff
@@ -226,7 +226,11 @@ local function format(uri, write_password)
     uribuf.scheme = uri.scheme
     uribuf.login = uri.login
     uribuf.password = uri.password
-    uribuf.host = uri.host
+    if uri.ipv6 ~= nil then
+        uribuf.host = string.format("[%s]", uri.host)
+    else
+        uribuf.host = uri.host
+    end
```
Comment (Totktonada) [inline src/lua/uri.lua:233]: Let's split parsing and formatting fixes into own commits.

Comment (Totktonada) [inline src/lua/uri.lua:233]: I would implement in on the C layer, in the `uri_format` function. This way all the usages of `uri_format()` will gain correctly formatted URI. For example, this function is called for appliers to show them in `box.info` (and, maybe, in logs).

We can use the `host_hint == 2` condition for this purpose.

File: src/lib/uri/uri_parser.rl [hunk 2]
```diff
@@ -111,7 +111,9 @@ uri_raw_parse(struct uri_raw *uri, const char *p)
 
 		ip6	= ("[" (
 				((hex1_4?) ((":" (hex1_4?)){1,8})) |
-				("::" [ff][ff][ff][ff] ":" ip4addr))
+				("::" ip4addr) |
+				("::" [ff][ff][ff][ff] ":" ip4addr) |
+				("::" [FF][FF][FF][FF] ":" ip4addr))
```
Comment (Totktonada) [inline src/lib/uri/uri_parser.rl:116]: The IPv6 parsing in an URI should be case-insensitive according to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986.html#section-3.2.2):

> A 128-bit IPv6 address is divided into eight 16-bit pieces. Each piece is represented numerically in **case-insensitive** hexadecimal <...>

It means that `::fFfF:192.168.1.1` should be accepted.

File: test/app-tap/uri.test.lua [hunk 3]
```diff
@@ -41,9 +41,88 @@ local function test_parse(test)
     test:is(u.host, '127.0.0.1', 'host')
     test:is(u.ipv4, '127.0.0.1', 'ipv4')
 
+-- {{
+
+    -- The literal format of an IPv6 address can contain the following
+    -- characters [0-9;a-f;A-F]. It was discovered in that the
+    -- uri does not support the characters A-F, although it should
+    -- according to the RFC 2732.
```
Comment (Totktonada) [inline test/app-tap/uri.test.lua:49]: Nit: I would move examples from RFC 2732 to its own test case.

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+## bugfix/uri
+
+* Fixed a bug that caused characters A-F to be unsupported in IPv6 addresses.
+  Added support for the ::IPv4 format in IPv6 addresses. Changed `uri.format`
+  output for IPv6 to be encapsulated in brackets `[]` (gh-9556).
```
Comment (andreyaksenov) [inline changelogs/unreleased/gh-9556-fix-uri-ipv6.md:5]:
```suggestion
  Added support for the ::IPv4 format in IPv6 addresses. Changed the `uri.format`
  output for IPv6 to be encapsulated in brackets `[]` (gh-9556).
```

**Review by andreyaksenov — APPROVED** [review]

File: test/app-tap/uri.test.lua [hunk 5]
```diff
@@ -177,12 +177,21 @@ local function test_parse_ipv6_format_by_rfc2732(test)
...
     test:is(uri.format(u, true), "user:password@localhost", "password kept")
 
+    -- URI with IPv6
+    u = uri.parse('[2a00:1148:b0ba:2016:12bf:48ff:fe78:fd10]')
+    test:is(uri.format(u), "[2a00:1148:b0ba:2016:12bf:48ff:fe78:fd10]", "URI format")
+
+    -- URI with IPv6 URL
+    u = uri.parse("http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html")
+    test:is(uri.format(u), "http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html",
+            "URI format")
```
Comment (Totktonada) [inline test/app-tap/uri.test.lua:193]: Nit: Can we move it into its own test case too?

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md [hunk 6]
```diff
@@ -0,0 +1,4 @@
+## bugfix/uri
```
Comment (Totktonada) [inline changelogs/unreleased/gh-9556-fix-uri-ipv6.md:1]: Nit: The first commit should be marked as `Part of #9556`.

File: src/lib/uri/uri_parser.rl [hunk 7]
```diff
@@ -101,7 +101,7 @@ uri_raw_parse(struct uri_raw *uri, const char *p)
 			>{ s = p; }
```
Comment (Totktonada) [inline src/lib/uri/uri_parser.rl:101]: The paths in the generated `uri_parser.c` may be important, see 415c05868f95b45a56904d5aa581358aced05efe. I guess they shouldn't be changed on the file regeneration.

File: src/lua/uri.lua [hunk 8]
```diff
@@ -231,6 +231,16 @@ local function format(uri, write_password)
...
     uribuf.fragment = uri.fragment
+    -- IPv6 addresses need to be output encapsulated in brackets [].
+    -- Since gh-9556, we must set the `host_hint` to determine if `uri.host`
+    -- is an IPv6 address (refer to `src/lib/uri/uri.c:uri_format`). The IPv4
+    -- and Unix cases of `uri.host` do not require special formatting, so
+    -- `host_hint` is set to -1 as a catch-all value.
+    if uri.ipv6 ~= nil then
+        uribuf.host_hint = 2
+    else
+        uribuf.host_hint = -1
```
Comment (Totktonada) [inline src/lua/uri.lua:242]: It is zero by default (`uri_raw_parse` calls `memset`), not -1.

Since we anyway fill the `host_hint` value I would set 1 and 3 for `uri.ipv4` and `uri.unix`.

Comment (mandesero) [reply src/lua/uri.lua]: Done

File: src/lib/uri/uri_parser.rl (hunk 7 above)
Comment (mandesero) [reply src/lib/uri/uri_parser.rl:101]: I replaced the paths with the correct ones.

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md (hunk 6 above)
Comment (mandesero) [reply changelogs/unreleased/gh-9556-fix-uri-ipv6.md:1]: Done

File: test/app-tap/uri.test.lua (hunk 5 above)
Comment (mandesero) [reply test/app-tap/uri.test.lua]: created a separate test case

File: test/app-tap/uri.test.lua (hunk 3 above)
Comment (mandesero) [reply test/app-tap/uri.test.lua]: Done

File: src/lib/uri/uri_parser.rl (hunk 2 above)
Comment (mandesero) [reply src/lib/uri/uri_parser.rl]: corrected

File: src/lua/uri.lua (hunk 1 above)
Comment (mandesero) [reply src/lua/uri.lua]: corrected

Comment (mandesero) [reply src/lua/uri.lua]: corrected

**Comment by Totktonada** [comment]
How about marking the `uri_parser.c` file as generated and [ignore](https://github.com/tarantool/checkpatch/pull/75) it in `checkpatch.pl` based on this attribute?

```diff
diff --git a/.gitattributes b/.gitattributes
index e884ab8909..adfb716c66 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -8,3 +8,4 @@
 *.hpp diff=cpp
 *.c++ diff=cpp
 *.h++ diff=cpp
+src/lib/uri/uri_parser.c linguist-generated=true
```

**Comment by Totktonada** [comment]
I've sent PR #10320 with the `.gitattributes` update.

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md (hunk 6 above)
Comment (Totktonada) [inline changelogs/unreleased/gh-9556-fix-uri-ipv6.md:1]: Nit: This way `Uri` becomes a top-level subsection in the `Bugs fixed` section. As for me, it should be in the `Lua` subsection.

IOW, I would make it `## bugfix/lua/uri`.

Comment (Totktonada) [inline changelogs/unreleased/gh-9556-fix-uri-ipv6.md:1]: Nit: The `uri: fix parsing IPv6` feels a bit too general. I would make the title more certain. For example, `uri: fix parsing uppercased IPv6 addresses`.

File: src/lua/uri.lua [hunk 9]
```diff
@@ -231,6 +231,16 @@ local function format(uri, write_password)
     uribuf.path = uri.path
     uribuf.query = uri.query
     uribuf.fragment = uri.fragment
+    -- IPv6 addresses need to be output encapsulated in brackets []. Since
+    -- gh-9556, we must set the `host_hint` to determine the type of `uri.host`
+    -- (refer to `src/lib/uri/uri.c:uri_format`).
```
Comment (Totktonada) [inline src/lua/uri.lua:236]: Nit: I would refer to `uri_format`, but not gh-9556, because iti s already fixed issue for a reader of this code.

For example.

> The `uri_format` function needs the hint to enclose an IPv6
> address into square brackets.

File: .gitattributes [hunk 10]
```diff
@@ -8,3 +8,4 @@
 *.hpp diff=cpp
 *.c++ diff=cpp
 *.h++ diff=cpp
+src/lib/uri/uri_parser.c linguist-generated=true
```
Comment (Totktonada) [inline .gitattributes:11]: I've pushed it in fbea9862b087e161a48dc0ac181a1da06cc0ce9d. Please, rebase this patchset.

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md [hunk 11]
```diff
@@ -1,4 +1,5 @@
 ## bugfix/uri
```
Comment (Totktonada) [inline changelogs/unreleased/gh-9556-fix-uri-ipv6.md:1]: > NO_DOC=no doc feature

What does it mean?

Anyway, I would just mark it as a bugfix: `NO_DOC=bugfix`.

**Review by Totktonada — APPROVED** [review]
Thanks! The patches are OK for me.

Please, consider several remaining stylistic comments and ask the next review from Sergey B.

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md (hunk 6 above)
Comment (mandesero) [reply changelogs/unreleased/gh-9556-fix-uri-ipv6.md]: commit message changed to suggested

Comment (mandesero) [reply changelogs/unreleased/gh-9556-fix-uri-ipv6.md]: replaced

File: src/lua/uri.lua (hunk 9 above)
Comment (mandesero) [reply src/lua/uri.lua]: comment corrected

File: .gitattributes (hunk 10 above)
Comment (mandesero) [reply .gitattributes]: rebased

File: test/app-tap/uri.test.lua [hunk 12]
```diff
@@ -96,6 +96,76 @@ local function test_parse(test)
...
+    test:is(u.host, '::FFFF:129.144.52.38', 'host')
+    test:is(u.scheme, 'http', 'scheme')
+    test:is(u.ipv6, '::FFFF:129.144.52.38', 'ipv6')
+    test:is(u.service, '80', 'service')
+    test:is(u.path, '/index.html', 'path')
+
+    u = uri.parse("http://[2010:836B:4179::836B:4179]")
+    test:is(u.host, '2010:836B:4179::836B:4179', 'host')
+    test:is(u.scheme, 'http', 'scheme')
+    test:is(u.ipv6, '2010:836B:4179::836B:4179', 'ipv6')
```
Comment (ligurio) [inline test/app-tap/uri.test.lua:166]: Please use parameterization for testcases. With luatest [^1] it will be easier. Do it in TAP or in luatest is up to you.

[^1]: https://github.com/tarantool/luatest/?tab=readme-ov-file#parametrization

File: test/app-tap/uri.test.lua [hunk 13]
```diff
@@ -96,6 +96,76 @@ local function test_parse(test)
...
+    -- characters [0-9;a-f;A-F]. It was discovered in that the
+    -- uri does not support the characters A-F, although it should
+    -- according to the RFC 2732.
+    test:plan(36)
+
+    local u
+
+    u = uri.parse("[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]")
+    test:is(u.host, 'FEDC:BA98:7654:3210:FEDC:BA98:7654:3210', 'host')
+    test:is(u.ipv6, 'FEDC:BA98:7654:3210:FEDC:BA98:7654:3210', 'ipv6')
```
Comment (ligurio) [inline test/app-tap/uri.test.lua:110]: Use testcases-specific descriptions in assertions here and below.
For example: `host part in [FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]` instead `host`.
Otherwise in TAP-report all testcases looks same.

File: test/app-tap/uri.test.lua [hunk 14]
```diff
@@ -96,6 +96,76 @@ local function test_parse(test)
...
+
+    u = uri.parse("[1080:0:0:0:8:800:200C:4171]")
+    test:is(u.host, '1080:0:0:0:8:800:200C:4171', 'host')
+    test:is(u.ipv6, '1080:0:0:0:8:800:200C:4171', 'ipv6')
```
Comment (ligurio) [inline test/app-tap/uri.test.lua:114]: Why do you expect that `u` is a table and not `nil`? I would check for `nil` and then that `u` has desired type (`test:istable(u, "<descr>")`). Here and below.

File: test/app-tap/uri.test.lua [hunk 15]
```diff
@@ -96,6 +96,76 @@ local function test_parse(test)
...
+
+    u = uri.parse("[3ffe:2a00:100:7031::1]")
+    test:is(u.host, '3ffe:2a00:100:7031::1', 'host')
+    test:is(u.ipv6, '3ffe:2a00:100:7031::1', 'ipv6')
```
Comment (ligurio) [inline test/app-tap/uri.test.lua:118]: It is not clear why do you choose these examples for testcases.
The patch fixes support of symbols `[0-9;a-f;A-F]` in `uri.parse`, so I would use one example per supported symbol:

Like this:
- `0`: `uri.parse("[0:0:0:0:0:0:0]")`
- `1`: `uri.parse("[1:1:1:1:1:1:1]")`
- ...
- `f`: `uri.parse("[f:f:f:f:f:f:f]")`
- `F`: `uri.parse("[F:F:F:F:F:F:F]")`

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md [hunk 16]
```diff
@@ -0,0 +1,5 @@
+## bugfix/lua/uri
+
```
Comment (ligurio) [inline changelogs/unreleased/gh-9556-fix-uri-ipv6.md:2]: commit message "uri: uri.format encapsulate IPv6 in []":

replace "uri: uri.format encapsulate IPv6 in []" with "uri: uri.format encapsulate IPv6 address in []"

File: test/app-tap/uri.test.lua [hunk 17]
```diff
@@ -160,6 +230,20 @@ local function test_format(test)
             "unix/:/tmp/unix.sock", "URI format")
 end
 
+local function test_format_ipv6_format_by_rfc2732(test)
+    test:plan(2)
+    local u
+
+    -- URI with IPv6
```
Comment (ligurio) [inline test/app-tap/uri.test.lua:237]: missed dot at the end of comment. here and below

**Review by ligurio — COMMENTED** [review]
Maksim, thanks for the patch!

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md [hunk 18]
```diff
@@ -0,0 +1,5 @@
+## bugfix/lua/uri
```
[the remark this answers is not in the document]
Comment (mandesero) [reply changelogs/unreleased/gh-9556-fix-uri-ipv6.md:1]: Head of first commit is "[uri: fix parsing uppercased IPv6 addresses](https://github.com/tarantool/tarantool/pull/10315/commits/9a856ccb8bcdf8c55da03f361e8cc8216944dee6)", not "uri: fix parsing IPv6".

Commit message corrected

File: test/app-tap/uri.test.lua (hunk 12 above)
Comment (mandesero) [reply test/app-tap/uri.test.lua:166]: I moved the tests to a separate file and did the parameterization

File: test/app-tap/uri.test.lua (hunk 13 above)
Comment (mandesero) [reply test/app-tap/uri.test.lua:110]: Replaced to luatest

File: test/app-tap/uri.test.lua (hunk 14 above)
Comment (mandesero) [reply test/app-tap/uri.test.lua:114]: Corrected

File: test/app-tap/uri.test.lua (hunk 15 above)
Comment (mandesero) [reply test/app-tap/uri.test.lua:118]: These examples are taken from RFC 2732, which is referenced in the issue. Not all IPv6 address variants are supported in tarantool:uri, but we have decided not to expand the supported cases in this patch ([see](https://github.com/tarantool/tarantool/issues/9556#issuecomment-2252481861)).

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md (hunk 16 above)
Comment (mandesero) [reply changelogs/unreleased/gh-9556-fix-uri-ipv6.md:2]: Replaced

File: test/app-tap/uri.test.lua (hunk 17 above)
Comment (mandesero) [reply test/app-tap/uri.test.lua:237]: This comment has been removed

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md (hunk 18 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply changelogs/unreleased/gh-9556-fix-uri-ipv6.md:1]: Thanks!

File: test/app-tap/uri.test.lua (hunk 14 above)
Comment (ligurio) [reply test/app-tap/uri.test.lua]: Thanks!

File: changelogs/unreleased/gh-9556-fix-uri-ipv6.md (hunk 16 above)
Comment (ligurio) [reply changelogs/unreleased/gh-9556-fix-uri-ipv6.md:2]: Thanks!

File: test/app-tap/uri.test.lua (hunk 12 above)
Comment (ligurio) [reply test/app-tap/uri.test.lua]: Thanks!

File: test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua [hunk 19]
```diff
@@ -0,0 +1,67 @@
...
+               "[1080::8:800:200C:417A]",
+               "[::FFFF:129.144.52.38]",
+               "[2010:836b:4179::836b:4179]"}
+
+local g1 = t.group('group_parse_ipv6',
+                   t.helpers.matrix({schema = {nil, 'http'},
+                                    service = {nil, 80},
+                                    path = {nil, 'foo', 'index.html'},
+                                    u = addrs,
+                                }))
```
Comment (ligurio) [inline test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua:18]: could you update formatting for tables?

```diff
diff --git a/test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua b/test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua
index 55d270fd83..a5ad68c442 100644
--- a/test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua
+++ b/test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua
@@ -3,19 +3,21 @@ local uri = require('uri')
 
 -- IPv6 addresses from RFC 2732 corresponding to IPv6 addresses
 -- processed by uri (refer to src/lib/uri/uri_parser.rl:114).
-local addrs = {"[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]",
-               "[1080:0:0:0:8:800:200C:4171]",
-               "[3ffe:2a00:100:7031::1]",
-               "[1080::8:800:200C:417A]",
-               "[::FFFF:129.144.52.38]",
-               "[2010:836b:4179::836b:4179]"}
+local addrs = {
+    "[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]",
+    "[1080:0:0:0:8:800:200C:4171]",
+    "[3ffe:2a00:100:7031::1]",
+    "[1080::8:800:200C:417A]",
+    "[::FFFF:129.144.52.38]",
+    "[2010:836b:4179::836b:4179]",
+}
 
-local g1 = t.group('group_parse_ipv6',
-                   t.helpers.matrix({schema = {nil, 'http'},
-                                    service = {nil, 80},
-                                    path = {nil, 'foo', 'index.html'},
-                                    u = addrs,
-                                }))
+local g1 = t.group('group_parse_ipv6', t.helpers.matrix({
+    schema = {nil, 'http'},
+    service = {nil, 80},
+    path = {nil, 'foo', 'index.html'},
+    u = addrs,
+}))
 
 local function join_url(params)
     local url = ''
```

File: test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua [hunk 20]
```diff
@@ -0,0 +1,67 @@
...
+
+local function join_url(params)
```
Comment (ligurio) [inline test/app-luatest/gh_9556_uri_parse_format_ipv6_test.lua:20]: Usually we don't mix single and double quotes, please fix it in the test.

File: test/app-tap/uri.test.lua (hunk 15 above)
Comment (ligurio) [reply test/app-tap/uri.test.lua]: My motivation is the following:
with simple examples, debugging parser would be easier. With failed testcase `uri.parse("[0:0:0:0:0:0:0]")` it is obvious that something is wrong with symbol `0` in a parser and the same for testcases with other supported symbols.

Ok, I'll not insist with this. Feel free to ignore and resolve the comment.

**Review by ligurio — APPROVED** [review]
Maksim, thanks for the patch!

LGTM after resolving comments.

**Comment by Totktonada** [comment]
Pushed to `master`, future `3.2.0` release.

Backported to `release/3.1`, future `3.1.1` release in PR #10337.

Backported to `release/2.11`, future `2.11.4` release in PR #10338.
