### PR TITLE
box: forbid DDL operations until box.schema.upgrade

### LINKED ISSUE #7149: Forbid DDL before `box.schema.upgrade` is called
We already track which schema version is needed for correct Tarantool operation.
The user sees the following message after upgrading the database:
```
2022-05-18 12:54:07.790 [9379] main/103/interactive load_cfg.lua:857 W> Your schema version is 1.10.2 while Tarantool 2.11.0-entrypoint-49-g9ce8798d1 requires a more recent schema version. Please, consider using box.schema.upgrade().
```

Having said that, Tarantool still allows the user to run ddl on a cluster with non-upgraded schema.
This leads to various unpredictable errrors (because the ddl code assumes the schema is already upgraded).

Example (trying to create a space on 2.11 Tarantool with 1.10 schema):
```
tarantool> box.schema.space.create('test')
---
- error: 'Tuple field 1 (id) type does not match one required by operation: expected
    unsigned, got nil'
...
```
Example (trying to drop a space on 2.8 Tarantool with 1.10 schema):
```
- error: 'builtin/box/schema.lua:515: attempt to index field ''space_id'' (a nil value)'
```

First of all, DDL on an old schema might return an unclear error. Like in the example above.
Secondly, DDL might complete without errors but produce erroneous results.
Lastly, when DDL fails on a non-upgraded schema, it might leave the schema in an incorrect state. DDL is not transactional currently (#600), and if the error is generated on some intermediate DDL step, the schema will be left in a partially changed state. And all further attempts to perform DDL will fail.

Let's forbid DDL altogether unless the user has the most recent schema version.

### PR DESCRIPTION
**Pull request by Gumix**
Currently, in case of recovery from an old snapshot, Tarantool allows
to perform DDL operations on an instance with non-upgraded schema.
This leads to various unpredictable errors (because the DDL code
assumes the schema is already upgraded). This patch forbids DDL
altogether unless the user has the most recent schema version.

Closes #7149

### CODE REVIEW

File: src/box/lua/upgrade.lua [hunk 1]
```diff
@@ -1357,6 +1360,8 @@ local function upgrade(options)
     options = options or {}
     setmetatable(options, {__index = {auto = false}})
 
+    ffi.C.box_dd_operations_allowed = true
```
Comment (sergepetrenko) [inline src/box/lua/upgrade.lua:1363]: You allow ddl operations even before running the upgrade handlers.
If any of the handlers fail, we are left with old schema and without ddl protection.

Let's either restore the original value of `box_dd_operations_allowed` upon failure, or (better IMO) let's take a slightly different approach, as proposed in my comment.

**Review by sergepetrenko — COMMENTED** [review]
Hi! Thanks for the patch!
Looks good generally, but I propose a slightly different approach:
I think it would be fine to allow the user to issue direct requests to system spaces (like `box.space._space:insert` or `box.space._schema:replace` and so on).

You might only forbid the requests which look like `box.schema.space.create`, `box.schema.func.create`, `box.schema.user.grant` and so on.

First of all, the users don't use the direct requests (`_space:insert`) and only use the API (`box.schema.space.create`).

Secondly, (regarding my comment in upgrade.lua) with my approach you won't have to set `box_dd_operations_allowed` to true before running the upgrade handlers. The handlers use direct requests, so they will work fine even without ddl allowed.

Finally, we don't have to guard all system spaces: for example, _cluster and _schema may be writeable just fine even without the schema upgrade.
For example, the user might want to join a new replica (triggering a write to _cluster) before upgrading the schema.
Or the user might have some external code, which writes some system data to _schema (for example, [spacer](https://github.com/igorcoding/tarantool-spacer) does that).

I don't see why writes to `_schema` and `_cluster` should be forbidden.

One more point: the only source of errors when trying out DDL before schema upgrade is our code in `box.schema.space.create` and such. It's this code which assumes, that the schema is already upgraded. So IMO it only makes sense to guard this code, and not all writes to system spaces.

What do you think?

File: src/box/lua/upgrade.lua (hunk 1 above)
Comment (Gumix) [reply src/box/lua/upgrade.lua]: Discussed f2f and decided to forbid the following operations in Lua:
- box.schema.space.create
- box.schema.space.drop
- box.schema.space.alter
- box.schema.index.create
- box.schema.index.drop
- box.schema.index.alter
- box.schema.sequence.create
- box.schema.sequence.drop
- box.schema.sequence.alter
- box.schema.func.create
- box.schema.func.drop
- box.internal.collation.create
- box.internal.collation.drop

File: extra/exports [hunk 2]
```diff
@@ -12,6 +12,7 @@
 base64_bufsize
 base64_decode
 base64_encode
+box_dd_version_id
```
Comment (sergepetrenko) [inline extra/exports:15]: You write in the commit message that
```
There's a special case for upgrade() during bootstrap() - triggers are
disabled during bootstrap, that's why dd_version_id is not being updated.
Handle this by passing _initial_version=1.7.5 to the upgrade function.
```

Does it mean that after `box.internal.bootstrap()` when we're trying to save a new bootstrap.snap, for example with schema version 2.12.0, `box_dd_version_id` will stay 2.11.0?

This doesn't matter much, I'm just trying to understand.

File: src/box/lua/schema.lua [hunk 3]
```diff
@@ -241,6 +241,14 @@ local function revoke_object_privs(object_type, object_id)
     end
 end
 
+-- Check if schema version matches Tarantool version and raise an error if not.
+local function check_schema_version(options)
+    local disable_check = options and options._force
+    if internal.schema_needs_upgrade() and not disable_check then
+        box.error(box.error.DDL_NOT_ALLOWED, "box.schema.upgrade() is required")
```
Comment (sergepetrenko) [inline src/box/lua/schema.lua:248]: Let's make the error more verbose. For example, look at
https://github.com/tarantool/tarantool/blob/6e45042473fb973c7b1ad87fcf04c9081a4c40fa/src/box/lua/load_cfg.lua#L979-L990

File: src/box/lua/schema.lua [hunk 4]
```diff
@@ -956,6 +966,7 @@ box.schema.space.alter = function(space_id, options)
         box.error(box.error.NO_SUCH_SPACE, '#'..tostring(space_id))
     end
     check_param_table(options, alter_space_template)
+    check_schema_version(options)
```
Comment (sergepetrenko) [inline src/box/lua/schema.lua:969]: I think it's better to add `_force` to every options template. Like you've done it for `alter_index_template`.
Otherwise there's no point in passing options to `check_schema_version`, if calling code doesn't allow `options._force`.

File: test/box-luatest/gh_7149_forbid_ddl_until_box_schema_upgrade_test.lua [hunk 5]
```diff
@@ -21,3 +21,67 @@ g.test_schema_access = function()
...
+
+g.test_ddl_ops = function()
+    g.server:exec(function()
+        local t = require('luatest')
+        local error_msg = "DDL operations are not allowed: box.schema.upgrade() is required"
+
+        -- Note that automatic schema upgrade will not be performed
+        box.cfg{read_only = false}
+
+        t.assert_error_msg_content_equals(error_msg,
```
Comment (sergepetrenko) [inline test/box-luatest/gh_7149_forbid_ddl_until_box_schema_upgrade_test.lua:44]: Let's please test `_force` variants here as well.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the fixes!
Please, find my comments below.

File: extra/exports (hunk 2 above)
Comment (Gumix) [reply extra/exports:15]: No, if we add a new entry to `handlers` (e.g. `upgrade_to_2_12_0`) and launch Tarantool at clean directory, then during `box.cfg{}` the new handler `upgrade_to_2_12_0` will be called and `box_dd_version_id` will become 2.12.0.

Comment (sergepetrenko) [reply extra/exports:15]: So `box_dd_version_id` will be 2.12.0 both before and after `box.internal.bootstrap()`?

Comment (Gumix) [reply extra/exports:15]: Yes

Comment (sergepetrenko) [reply extra/exports:15]: Ok, thanks for the explanation!

File: src/box/lua/schema.lua (hunk 3 above)
Comment (Gumix) [reply src/box/lua/schema.lua]: Done

File: src/box/lua/schema.lua (hunk 4 above)
Comment (Gumix) [reply src/box/lua/schema.lua:972]: Done

**Review by sergepetrenko — APPROVED** [review]
Thanks!

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/lua/upgrade.lua [hunk 6]
```diff
@@ -1262,13 +1265,10 @@ local handlers = {
...
-    end
-    local major = version[2]
-    local minor = version[3]
-    local patch = version[4] or 0
+    local version = ffi.C.box_dd_version_id()
+    local major = bit.band(bit.rshift(version, 16), 0xff)
+    local minor = bit.band(bit.rshift(version, 8), 0xff)
+    local patch = bit.band(version, 0xff)
 
     return mkversion(major, minor, patch),
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/box/lua/upgrade.lua:1307]: `mkversion` is required here to make the value comparable (see `schema_needs_upgrade` etc.).

File: src/box/lua/schema.lua [hunk 7]
```diff
@@ -1656,6 +1672,7 @@ end
 box.schema.index.drop = function(space_id, index_id)
     check_param(space_id, 'space_id', 'number')
     check_param(index_id, 'index_id', 'number')
+    check_schema_version()
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/box/lua/schema.lua:1671]: Removed `_force` completely.

File: src/box/lua/upgrade.lua [hunk 8]
```diff
@@ -674,10 +674,12 @@ local function upgrade_priv_to_1_10_2()
...
-    _priv.index.primary:alter{parts={2, 'unsigned', 3, 'string', 4, 'scalar'}}
-    _vpriv.index.primary:alter{parts={2, 'unsigned', 3, 'string', 4, 'scalar'}}
-    _priv.index.object:alter{parts={3, 'string', 4, 'scalar'}}
-    _vpriv.index.object:alter{parts={3, 'string', 4, 'scalar'}}
+    _priv.index.primary:alter{parts={2, 'unsigned', 3, 'string', 4, 'scalar'},
+                              _force=true}
+    _vpriv.index.primary:alter{parts={2, 'unsigned', 3, 'string', 4, 'scalar'},
+                               _force=true}
+    _priv.index.object:alter{parts={3, 'string', 4, 'scalar'}, _force=true}
+    _vpriv.index.object:alter{parts={3, 'string', 4, 'scalar'}, _force=true}
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/box/lua/upgrade.lua]: Done

File: src/box/lua/schema.lua [hunk 9]
```diff
@@ -3291,7 +3316,9 @@ box.internal.collation.create = function(name, coll_type, locale, opts)
     end
     local lua_opts = {if_not_exists = opts.if_not_exists }
     check_param_table(lua_opts, {if_not_exists = 'boolean'})
+    check_schema_version(opts)
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/box/lua/schema.lua]: Removed `box.internal.collation` from the patch.

We discussed the list of functions in person and decided that privilege manipulation functions should not be forbidden, but I can't remember why exactly. @sergepetrenko, can you advise?

[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/lua/schema.lua]: It was @alyapunov's point. Loosely speaking "the user might want to set up replication after upgrading tarantool but before issuing `box.schema.upgrade()` and that might require granting privileges in some rare cases".

Although this could be dont via a plain `box.space._priv:replace` as well.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
@Gumix Looks like you missed a few places:
 - `box.schema.space.rename`
 - `box.schema.space.format`
 - `box.schema.index.rename`
 - `space_mt.create_check_constraint`
 - `ck_constraint_mt.drop`
 - `ck_constraint_mt.enable`
