### PR TITLE
vinyl: fix use of dropped space in deferred DELETE handler

### LINKED ISSUE #6448: Tarantool segfaults after aborting DDL transaction
**Bug description**

* OS: Ubuntu
* OS Version:  20.04
* Architecture: amd64, arm

Tarantool 2.8.2-9-g83e17b23e
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.8.2.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.8.2.9=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

**Steps to reproduce**

1. `git clone https://github.com/tarantool/expirationd`
1. `git checkout ligurio/tarantool-segfault`
1. `./.rocks/bin/luatest -c -v test/unit/custom_index_test.lua`

**Actual behavior**

segfault on running expirationd's tests

**Expected behavior**

passed tests without tarantool's crash

**Output**

```
 2021-09-16 19:50:03.568 [1654014] main/103/luatest C> Tarantool 2.8.2-9-g83e17b23e
2021-09-16 19:50:03.568 [1654014] main/103/luatest C> log level 5
2021-09-16 19:50:03.568 [1654014] main/103/luatest I> wal/engine cleanup is paused
2021-09-16 19:50:03.569 [1654014] main/103/luatest I> mapping 268435456 bytes for memtx tuple arena...
2021-09-16 19:50:03.569 [1654014] main/103/luatest I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2021-09-16 19:50:03.569 [1654014] main/103/luatest I> mapping 16777216 bytes for vinyl tuple arena...
2021-09-16 19:50:03.570 [1654014] main/103/luatest I> instance uuid 7079bec5-2b3e-48fd-9449-def1546ca643
2021-09-16 19:50:03.570 [1654014] main/103/luatest I> tx_binary: stopped
2021-09-16 19:50:03.570 [1654014] main/103/luatest I> initializing an empty data directory
2021-09-16 19:50:03.576 [1654014] main/103/luatest I> assigned id 1 to replica 7079bec5-2b3e-48fd-9449-def1546ca643
2021-09-16 19:50:03.576 [1654014] main/103/luatest I> cluster uuid e1c1a68c-16cc-4dde-a48e-5ff6162ccb6e
2021-09-16 19:50:03.577 [1654014] snapshot/101/main I> saving snapshot `/tmp/xWd4LZ/00000000000000000000.snap.inprogress'
2021-09-16 19:50:03.579 [1654014] snapshot/101/main I> done
2021-09-16 19:50:03.579 [1654014] main/103/luatest I> ready to accept requests
2021-09-16 19:50:03.579 [1654014] main/104/gc I> wal/engine cleanup is resumed
2021-09-16 19:50:03.579 [1654014] main/103/luatest I> set 'log_level' configuration option to 5
2021-09-16 19:50:03.579 [1654014] main/105/checkpoint_daemon I> scheduled next checkpoint for Thu Sep 16 21:21:46 2021
2021-09-16 19:50:03.580 [1654014] main/103/luatest I> set 'vinyl_memory' configuration option to 1024
2021-09-16 19:50:03.580 [1654014] main/103/luatest I> set 'log_format' configuration option to "plain"
2021-09-16 19:50:03.588 [1654014] main/118/guardian of "clean_all" I> expiration: task "clean_all" restarted
2021-09-16 19:50:03.609 [1654014] main/120/guardian of "clean_all" I> expiration: task "clean_all" restarted
2021-09-16 19:50:03.630 [1654014] main/122/guardian of "clean_all" I> expiration: task "clean_all" restarted
2021-09-16 19:50:03.654 [1654014] main/124/guardian of "clean_all" I> expiration: task "clean_all" restarted
2021-09-16 19:50:03.777 [1654014] main/126/guardian of "clean_all" I> expiration: task "clean_all" restarted
2021-09-16 19:50:03.899 [1654014] main/103/luatest I> dumping 245824 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:03.900 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:03.901 [1654014] vinyl.dump.0/102/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000024.run'
2021-09-16 19:50:03.903 [1654014] vinyl.dump.0/102/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000024.index'
2021-09-16 19:50:03.906 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:03.907 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:03.907 [1654014] vinyl.dump.0/103/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000026.run'
2021-09-16 19:50:03.909 [1654014] vinyl.dump.0/103/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000026.index'
2021-09-16 19:50:03.912 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:03.913 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:03.913 [1654014] vinyl.dump.0/104/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000028.run'
2021-09-16 19:50:03.915 [1654014] vinyl.dump.0/104/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000028.index'
2021-09-16 19:50:03.918 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:03.918 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:03.918 [1654014] vinyl.dump.0/105/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000030.run'
2021-09-16 19:50:03.920 [1654014] vinyl.dump.0/105/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000030.index'
2021-09-16 19:50:03.923 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:03.923 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:03.923 [1654014] vinyl.dump.0/106/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000032.run'
2021-09-16 19:50:03.924 [1654014] vinyl.dump.0/106/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000032.index'
2021-09-16 19:50:03.927 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:03.927 [1654014] main/107/vinyl.scheduler I> dumped 245824 bytes in 0.0 s, rate 8.3 MB/s
2021-09-16 19:50:03.927 [1654014] main/103/luatest I> dumping 245824 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:03.928 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:03.928 [1654014] vinyl.dump.0/107/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000034.run'
2021-09-16 19:50:03.929 [1654014] vinyl.dump.0/107/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000034.index'
2021-09-16 19:50:03.932 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:03.932 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:03.934 [1654014] vinyl.dump.0/108/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000036.run'
2021-09-16 19:50:03.934 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.934 [1654014] vinyl.compaction.0/102/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000037.run'
2021-09-16 19:50:03.936 [1654014] vinyl.dump.0/108/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000036.index'
2021-09-16 19:50:03.936 [1654014] vinyl.compaction.0/102/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000037.index'
2021-09-16 19:50:03.939 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:03.939 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:03.939 [1654014] vinyl.dump.0/109/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000039.run'
2021-09-16 19:50:03.939 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.940 [1654014] vinyl.compaction.1/102/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000040.run'
2021-09-16 19:50:03.940 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000024.index
2021-09-16 19:50:03.940 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000024.run
2021-09-16 19:50:03.940 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000034.index
2021-09-16 19:50:03.940 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000034.run
2021-09-16 19:50:03.941 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:03.941 [1654014] vinyl.dump.0/109/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000039.index'
2021-09-16 19:50:03.942 [1654014] vinyl.compaction.1/102/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000040.index'
2021-09-16 19:50:03.944 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:03.944 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:03.945 [1654014] vinyl.dump.0/110/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000043.run'
2021-09-16 19:50:03.945 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.945 [1654014] vinyl.compaction.0/103/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000044.run'
2021-09-16 19:50:03.945 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000026.index
2021-09-16 19:50:03.946 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000026.run
2021-09-16 19:50:03.946 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000036.index
2021-09-16 19:50:03.946 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000036.run
2021-09-16 19:50:03.946 [1654014] vinyl.dump.0/110/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000043.index'
2021-09-16 19:50:03.946 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:03.947 [1654014] vinyl.compaction.0/103/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000044.index'
2021-09-16 19:50:03.949 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:03.950 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:03.950 [1654014] vinyl.dump.0/111/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000047.run'
2021-09-16 19:50:03.950 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.950 [1654014] vinyl.compaction.1/103/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000048.run'
2021-09-16 19:50:03.950 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000028.index
2021-09-16 19:50:03.951 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000028.run
2021-09-16 19:50:03.951 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000039.index
2021-09-16 19:50:03.951 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000039.run
2021-09-16 19:50:03.951 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:03.957 [1654014] vinyl.dump.0/111/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000047.index'
2021-09-16 19:50:03.958 [1654014] vinyl.compaction.1/103/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000048.index'
2021-09-16 19:50:03.961 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:03.961 [1654014] main/107/vinyl.scheduler I> dumped 245824 bytes in 0.0 s, rate 7.0 MB/s
2021-09-16 19:50:03.961 [1654014] main/103/luatest I> dumping 245824 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:03.961 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.962 [1654014] main/128/guardian of "clean_all" I> expiration: task "clean_all" restarted
2021-09-16 19:50:03.962 [1654014] vinyl.compaction.0/104/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000051.run'
2021-09-16 19:50:03.962 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:03.962 [1654014] vinyl.dump.0/112/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000052.run'
2021-09-16 19:50:03.963 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000030.index
2021-09-16 19:50:03.963 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000030.run
2021-09-16 19:50:03.963 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000043.index
2021-09-16 19:50:03.963 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000043.run
2021-09-16 19:50:03.964 [1654014] vinyl.compaction.0/104/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000051.index'
2021-09-16 19:50:03.964 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:03.965 [1654014] vinyl.dump.0/112/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000052.index'
2021-09-16 19:50:03.967 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000032.index
2021-09-16 19:50:03.967 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000032.run
2021-09-16 19:50:03.968 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000047.index
2021-09-16 19:50:03.968 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000047.run
2021-09-16 19:50:03.968 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:03.968 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:03.968 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:03.968 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.969 [1654014] vinyl.dump.0/113/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000056.run'
2021-09-16 19:50:03.969 [1654014] vinyl.compaction.0/105/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000057.run'
2021-09-16 19:50:03.970 [1654014] vinyl.compaction.0/105/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000057.index'
2021-09-16 19:50:03.970 [1654014] vinyl.dump.0/113/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000056.index'
2021-09-16 19:50:03.973 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000037.index
2021-09-16 19:50:03.973 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000037.run
2021-09-16 19:50:03.973 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000052.index
2021-09-16 19:50:03.973 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000052.run
2021-09-16 19:50:03.974 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:03.974 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:03.974 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:03.974 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.974 [1654014] vinyl.dump.0/114/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000060.run'
2021-09-16 19:50:03.974 [1654014] vinyl.compaction.0/106/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000061.run'
2021-09-16 19:50:03.976 [1654014] vinyl.dump.0/114/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000060.index'
2021-09-16 19:50:03.976 [1654014] vinyl.compaction.0/106/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000061.index'
2021-09-16 19:50:03.978 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000040.index
2021-09-16 19:50:03.979 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000040.run
2021-09-16 19:50:03.979 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000056.index
2021-09-16 19:50:03.979 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000056.run
2021-09-16 19:50:03.979 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:03.980 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:03.980 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:03.980 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.980 [1654014] vinyl.dump.0/115/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000064.run'
2021-09-16 19:50:03.980 [1654014] vinyl.compaction.0/107/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000065.run'
2021-09-16 19:50:03.981 [1654014] vinyl.dump.0/115/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000064.index'
2021-09-16 19:50:03.982 [1654014] vinyl.compaction.0/107/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000065.index'
2021-09-16 19:50:03.984 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:03.985 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:03.985 [1654014] vinyl.dump.0/116/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000067.run'
2021-09-16 19:50:03.985 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.985 [1654014] vinyl.compaction.1/104/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000068.run'
2021-09-16 19:50:03.986 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000044.index
2021-09-16 19:50:03.986 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000044.run
2021-09-16 19:50:03.986 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000060.index
2021-09-16 19:50:03.987 [1654014] vinyl.dump.0/116/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000067.index'
2021-09-16 19:50:03.987 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000060.run
2021-09-16 19:50:03.987 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:03.988 [1654014] vinyl.compaction.1/104/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000068.index'
2021-09-16 19:50:03.990 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:03.990 [1654014] main/107/vinyl.scheduler I> dumped 245824 bytes in 0.0 s, rate 8.0 MB/s
2021-09-16 19:50:03.990 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:03.990 [1654014] vinyl.compaction.0/108/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000071.run'
2021-09-16 19:50:03.991 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000048.index
2021-09-16 19:50:03.991 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000048.run
2021-09-16 19:50:03.991 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000064.index
2021-09-16 19:50:03.992 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000064.run
2021-09-16 19:50:03.992 [1654014] vinyl.compaction.0/108/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000071.index'
2021-09-16 19:50:03.992 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:03.994 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000051.index
2021-09-16 19:50:03.995 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000051.run
2021-09-16 19:50:03.995 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000067.index
2021-09-16 19:50:03.995 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000067.run
2021-09-16 19:50:03.995 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:04.070 [1654014] main/129/worker of "clean_all" I> dumping 245824 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.071 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:04.071 [1654014] vinyl.dump.0/117/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000074.run'
2021-09-16 19:50:04.074 [1654014] vinyl.dump.0/117/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000074.index'
2021-09-16 19:50:04.077 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:04.077 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:04.078 [1654014] vinyl.dump.0/118/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000076.run'
2021-09-16 19:50:04.078 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.078 [1654014] vinyl.compaction.0/109/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000077.run'
2021-09-16 19:50:04.079 [1654014] vinyl.dump.0/118/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000076.index'
2021-09-16 19:50:04.080 [1654014] vinyl.compaction.0/109/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000077.index'
2021-09-16 19:50:04.083 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:04.083 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:04.084 [1654014] vinyl.dump.0/119/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000079.run'
2021-09-16 19:50:04.084 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.084 [1654014] vinyl.compaction.1/105/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000080.run'
2021-09-16 19:50:04.084 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000057.index
2021-09-16 19:50:04.084 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000057.run
2021-09-16 19:50:04.085 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000074.index
2021-09-16 19:50:04.085 [1654014] vinyl.dump.0/119/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000079.index'
2021-09-16 19:50:04.085 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000074.run
2021-09-16 19:50:04.085 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:04.086 [1654014] vinyl.compaction.1/105/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000080.index'
2021-09-16 19:50:04.088 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:04.089 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:04.089 [1654014] vinyl.dump.0/120/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000083.run'
2021-09-16 19:50:04.089 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.089 [1654014] vinyl.compaction.0/110/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000084.run'
2021-09-16 19:50:04.090 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000061.index
2021-09-16 19:50:04.090 [1654014] vinyl.dump.0/120/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000083.index'
2021-09-16 19:50:04.090 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000061.run
2021-09-16 19:50:04.091 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000076.index
2021-09-16 19:50:04.091 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000076.run
2021-09-16 19:50:04.091 [1654014] vinyl.compaction.0/110/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000084.index'
2021-09-16 19:50:04.091 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:04.094 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:04.094 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.094 [1654014] vinyl.dump.0/121/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000087.run'
2021-09-16 19:50:04.094 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.094 [1654014] vinyl.compaction.1/106/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000088.run'
2021-09-16 19:50:04.095 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000065.index
2021-09-16 19:50:04.095 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000065.run
2021-09-16 19:50:04.095 [1654014] vinyl.dump.0/121/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000087.index'
2021-09-16 19:50:04.096 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000079.index
2021-09-16 19:50:04.096 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000079.run
2021-09-16 19:50:04.096 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:04.096 [1654014] vinyl.compaction.1/106/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000088.index'
2021-09-16 19:50:04.099 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.099 [1654014] main/107/vinyl.scheduler I> dumped 245824 bytes in 0.0 s, rate 8.2 MB/s
2021-09-16 19:50:04.099 [1654014] main/129/worker of "clean_all" I> dumping 49192 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.099 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.099 [1654014] vinyl.compaction.0/111/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000091.run'
2021-09-16 19:50:04.099 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.100 [1654014] vinyl.dump.0/122/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000092.run'
2021-09-16 19:50:04.100 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000068.index
2021-09-16 19:50:04.100 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000068.run
2021-09-16 19:50:04.101 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000083.index
2021-09-16 19:50:04.101 [1654014] vinyl.compaction.0/111/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000091.index'
2021-09-16 19:50:04.101 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000083.run
2021-09-16 19:50:04.101 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:04.102 [1654014] vinyl.dump.0/122/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000092.index'
2021-09-16 19:50:04.105 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000071.index
2021-09-16 19:50:04.106 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000071.run
2021-09-16 19:50:04.106 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000087.index
2021-09-16 19:50:04.107 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000087.run
2021-09-16 19:50:04.107 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:04.107 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.107 [1654014] main/107/vinyl.scheduler I> dumped 49192 bytes in 0.0 s, rate 5.7 MB/s
2021-09-16 19:50:04.107 [1654014] main/129/worker of "clean_all" I> dumping 49192 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.107 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.108 [1654014] vinyl.compaction.0/112/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000096.run'
2021-09-16 19:50:04.108 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.108 [1654014] vinyl.dump.0/123/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000097.run'
2021-09-16 19:50:04.109 [1654014] vinyl.dump.0/123/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000097.index'
2021-09-16 19:50:04.112 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.112 [1654014] main/107/vinyl.scheduler I> dumped 49192 bytes in 0.0 s, rate 10.2 MB/s
2021-09-16 19:50:04.112 [1654014] main/109/main I> dumping 196672 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.112 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:04.112 [1654014] vinyl.dump.0/124/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000099.run'
2021-09-16 19:50:04.113 [1654014] vinyl.compaction.0/112/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000096.index'
2021-09-16 19:50:04.114 [1654014] vinyl.dump.0/124/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000099.index'
2021-09-16 19:50:04.117 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000091.index
2021-09-16 19:50:04.117 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000091.run
2021-09-16 19:50:04.118 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000092.index
2021-09-16 19:50:04.118 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000092.run
2021-09-16 19:50:04.119 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:04.119 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:04.119 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:04.119 [1654014] vinyl.dump.0/125/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000102.run'
2021-09-16 19:50:04.119 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.120 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.120 [1654014] vinyl.compaction.0/113/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000103.run'
2021-09-16 19:50:04.121 [1654014] vinyl.dump.0/125/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000102.index'
2021-09-16 19:50:04.122 [1654014] vinyl.compaction.0/113/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000103.index'
2021-09-16 19:50:04.124 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:04.124 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:04.125 [1654014] vinyl.dump.0/126/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000106.run'
2021-09-16 19:50:04.125 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.125 [1654014] vinyl.compaction.2/102/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000107.run'
2021-09-16 19:50:04.125 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000077.index
2021-09-16 19:50:04.126 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000077.run
2021-09-16 19:50:04.126 [1654014] vinyl.dump.0/126/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000106.index'
2021-09-16 19:50:04.126 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000099.index
2021-09-16 19:50:04.127 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000099.run
2021-09-16 19:50:04.127 [1654014] vinyl.compaction.2/102/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000107.index'
2021-09-16 19:50:04.127 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:04.129 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:04.129 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:04.130 [1654014] vinyl.dump.0/127/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000110.run'
2021-09-16 19:50:04.130 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.130 [1654014] vinyl.compaction.0/114/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000111.run'
2021-09-16 19:50:04.130 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000080.index
2021-09-16 19:50:04.131 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000080.run
2021-09-16 19:50:04.131 [1654014] vinyl.dump.0/127/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000110.index'
2021-09-16 19:50:04.131 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000102.index
2021-09-16 19:50:04.131 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000102.run
2021-09-16 19:50:04.131 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:04.132 [1654014] vinyl.compaction.0/114/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000111.index'
2021-09-16 19:50:04.134 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:04.134 [1654014] main/107/vinyl.scheduler I> dumped 196672 bytes in 0.0 s, rate 8.3 MB/s
2021-09-16 19:50:04.134 [1654014] main/109/main I> dumping 196672 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.135 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.135 [1654014] vinyl.compaction.2/103/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000114.run'
2021-09-16 19:50:04.135 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000084.index
2021-09-16 19:50:04.135 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000084.run
2021-09-16 19:50:04.136 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000106.index
2021-09-16 19:50:04.136 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000106.run
2021-09-16 19:50:04.136 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:04.136 [1654014] vinyl.compaction.2/103/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000114.index'
2021-09-16 19:50:04.137 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000096.index
2021-09-16 19:50:04.137 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000096.run
2021-09-16 19:50:04.137 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000097.index
2021-09-16 19:50:04.138 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000097.run
2021-09-16 19:50:04.138 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:04.138 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:04.138 [1654014] vinyl.dump.0/128/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000116.run'
2021-09-16 19:50:04.139 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000088.index
2021-09-16 19:50:04.139 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000088.run
2021-09-16 19:50:04.139 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000110.index
2021-09-16 19:50:04.140 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000110.run
2021-09-16 19:50:04.140 [1654014] vinyl.dump.0/128/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000116.index'
2021-09-16 19:50:04.140 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:04.142 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:04.142 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:04.142 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.142 [1654014] vinyl.dump.0/129/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000119.run'
2021-09-16 19:50:04.143 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000103.index
2021-09-16 19:50:04.143 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000103.run
2021-09-16 19:50:04.143 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000116.index
2021-09-16 19:50:04.143 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000116.run
2021-09-16 19:50:04.144 [1654014] vinyl.dump.0/129/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000119.index'
2021-09-16 19:50:04.144 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:04.146 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:04.146 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:04.146 [1654014] vinyl.dump.0/130/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000122.run'
2021-09-16 19:50:04.146 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.147 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000107.index
2021-09-16 19:50:04.147 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000107.run
2021-09-16 19:50:04.147 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000119.index
2021-09-16 19:50:04.148 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000119.run
2021-09-16 19:50:04.148 [1654014] vinyl.dump.0/130/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000122.index'
2021-09-16 19:50:04.148 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:04.150 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:04.150 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:04.150 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.150 [1654014] vinyl.dump.0/131/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000125.run'
2021-09-16 19:50:04.151 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000111.index
2021-09-16 19:50:04.151 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000111.run
2021-09-16 19:50:04.151 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000122.index
2021-09-16 19:50:04.151 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000122.run
2021-09-16 19:50:04.151 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:04.151 [1654014] vinyl.dump.0/131/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000125.index'
2021-09-16 19:50:04.153 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:04.154 [1654014] main/107/vinyl.scheduler I> dumped 196672 bytes in 0.0 s, rate 9.8 MB/s
2021-09-16 19:50:04.154 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.154 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000114.index
2021-09-16 19:50:04.154 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000114.run
2021-09-16 19:50:04.155 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000125.index
2021-09-16 19:50:04.155 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000125.run
2021-09-16 19:50:04.155 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:04.184 [1654014] main/103/luatest I> dumping 245824 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.184 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:04.184 [1654014] vinyl.dump.0/132/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000129.run'
2021-09-16 19:50:04.185 [1654014] vinyl.dump.0/132/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000129.index'
2021-09-16 19:50:04.187 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:04.188 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:04.188 [1654014] vinyl.dump.0/133/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000131.run'
2021-09-16 19:50:04.189 [1654014] vinyl.dump.0/133/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000131.index'
2021-09-16 19:50:04.191 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:04.191 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:04.191 [1654014] vinyl.dump.0/134/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000133.run'
2021-09-16 19:50:04.192 [1654014] vinyl.dump.0/134/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000133.index'
2021-09-16 19:50:04.194 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:04.194 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:04.195 [1654014] vinyl.dump.0/135/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000135.run'
2021-09-16 19:50:04.196 [1654014] vinyl.dump.0/135/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000135.index'
2021-09-16 19:50:04.198 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:04.198 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.198 [1654014] vinyl.dump.0/136/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000137.run'
2021-09-16 19:50:04.199 [1654014] vinyl.dump.0/136/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000137.index'
2021-09-16 19:50:04.201 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.201 [1654014] main/107/vinyl.scheduler I> dumped 245824 bytes in 0.0 s, rate 13.1 MB/s
2021-09-16 19:50:04.201 [1654014] main/103/luatest I> dumping 245824 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.202 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:04.202 [1654014] vinyl.dump.0/137/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000139.run'
2021-09-16 19:50:04.203 [1654014] vinyl.dump.0/137/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000139.index'
2021-09-16 19:50:04.205 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:04.206 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:04.206 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.206 [1654014] vinyl.dump.0/138/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000141.run'
2021-09-16 19:50:04.206 [1654014] vinyl.compaction.2/108/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000142.run'
2021-09-16 19:50:04.207 [1654014] vinyl.dump.0/138/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000141.index'
2021-09-16 19:50:04.208 [1654014] vinyl.compaction.2/108/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000142.index'
2021-09-16 19:50:04.210 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:04.210 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:04.210 [1654014] vinyl.dump.0/139/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000144.run'
2021-09-16 19:50:04.210 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.210 [1654014] vinyl.compaction.1/108/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000145.run'
2021-09-16 19:50:04.210 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000129.index
2021-09-16 19:50:04.211 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000129.run
2021-09-16 19:50:04.211 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000139.index
2021-09-16 19:50:04.211 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000139.run
2021-09-16 19:50:04.211 [1654014] vinyl.dump.0/139/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000144.index'
2021-09-16 19:50:04.211 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:04.212 [1654014] vinyl.compaction.1/108/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000145.index'
2021-09-16 19:50:04.214 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:04.214 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:04.214 [1654014] vinyl.dump.0/140/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000148.run'
2021-09-16 19:50:04.214 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.214 [1654014] vinyl.compaction.2/109/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000149.run'
2021-09-16 19:50:04.215 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000131.index
2021-09-16 19:50:04.215 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000131.run
2021-09-16 19:50:04.215 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000141.index
2021-09-16 19:50:04.215 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000141.run
2021-09-16 19:50:04.215 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:04.215 [1654014] vinyl.dump.0/140/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000148.index'
2021-09-16 19:50:04.216 [1654014] vinyl.compaction.2/109/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000149.index'
2021-09-16 19:50:04.218 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:04.218 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.218 [1654014] vinyl.dump.0/141/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000152.run'
2021-09-16 19:50:04.219 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.219 [1654014] vinyl.compaction.1/109/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000153.run'
2021-09-16 19:50:04.219 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000133.index
2021-09-16 19:50:04.219 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000133.run
2021-09-16 19:50:04.219 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000144.index
2021-09-16 19:50:04.219 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000144.run
2021-09-16 19:50:04.220 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:04.220 [1654014] vinyl.dump.0/141/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000152.index'
2021-09-16 19:50:04.220 [1654014] vinyl.compaction.1/109/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000153.index'
2021-09-16 19:50:04.222 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.222 [1654014] main/107/vinyl.scheduler I> dumped 245824 bytes in 0.0 s, rate 11.1 MB/s
2021-09-16 19:50:04.222 [1654014] main/103/luatest I> dumping 245824 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.223 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.223 [1654014] main/131/guardian of "clean_all" I> expiration: task "clean_all" restarted
2021-09-16 19:50:04.223 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:04.223 [1654014] vinyl.compaction.2/110/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000156.run'
2021-09-16 19:50:04.223 [1654014] vinyl.dump.0/142/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000157.run'
2021-09-16 19:50:04.223 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000135.index
2021-09-16 19:50:04.224 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000135.run
2021-09-16 19:50:04.224 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000148.index
2021-09-16 19:50:04.224 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000148.run
2021-09-16 19:50:04.224 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:04.224 [1654014] vinyl.dump.0/142/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000157.index'
2021-09-16 19:50:04.224 [1654014] vinyl.compaction.2/110/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000156.index'
2021-09-16 19:50:04.227 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:04.227 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:04.227 [1654014] vinyl.dump.0/143/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000160.run'
2021-09-16 19:50:04.227 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.227 [1654014] vinyl.compaction.1/110/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000161.run'
2021-09-16 19:50:04.228 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000137.index
2021-09-16 19:50:04.228 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000137.run
2021-09-16 19:50:04.228 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000152.index
2021-09-16 19:50:04.228 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000152.run
2021-09-16 19:50:04.228 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:04.228 [1654014] vinyl.dump.0/143/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000160.index'
2021-09-16 19:50:04.229 [1654014] vinyl.compaction.1/110/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000161.index'
2021-09-16 19:50:04.231 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:04.231 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:04.231 [1654014] vinyl.dump.0/144/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000164.run'
2021-09-16 19:50:04.231 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.231 [1654014] vinyl.compaction.2/111/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000165.run'
2021-09-16 19:50:04.232 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000142.index
2021-09-16 19:50:04.232 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000142.run
2021-09-16 19:50:04.232 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000157.index
2021-09-16 19:50:04.232 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000157.run
2021-09-16 19:50:04.232 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:04.232 [1654014] vinyl.dump.0/144/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000164.index'
2021-09-16 19:50:04.233 [1654014] vinyl.compaction.2/111/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000165.index'
2021-09-16 19:50:04.235 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:04.235 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:04.235 [1654014] vinyl.dump.0/145/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000168.run'
2021-09-16 19:50:04.235 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.235 [1654014] vinyl.compaction.1/111/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000169.run'
2021-09-16 19:50:04.236 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000145.index
2021-09-16 19:50:04.236 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000145.run
2021-09-16 19:50:04.236 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000160.index
2021-09-16 19:50:04.236 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000160.run
2021-09-16 19:50:04.237 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:04.237 [1654014] vinyl.compaction.1/111/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000169.index'
2021-09-16 19:50:04.237 [1654014] vinyl.dump.0/145/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000168.index'
2021-09-16 19:50:04.239 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:04.239 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.240 [1654014] vinyl.dump.0/146/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000172.run'
2021-09-16 19:50:04.240 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.240 [1654014] vinyl.compaction.2/112/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000173.run'
2021-09-16 19:50:04.240 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000149.index
2021-09-16 19:50:04.240 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000149.run
2021-09-16 19:50:04.241 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000164.index
2021-09-16 19:50:04.241 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000164.run
2021-09-16 19:50:04.241 [1654014] vinyl.compaction.2/112/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000173.index'
2021-09-16 19:50:04.241 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:04.241 [1654014] vinyl.dump.0/146/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000172.index'
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000153.index
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000153.run
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000168.index
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000168.run
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> dumped 245824 bytes in 0.0 s, rate 10.8 MB/s
2021-09-16 19:50:04.244 [1654014] main/132/worker of "clean_all" I> dumping 245824 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.244 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:04.244 [1654014] vinyl.compaction.2/113/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000177.run'
2021-09-16 19:50:04.244 [1654014] vinyl.dump.0/147/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000178.run'
2021-09-16 19:50:04.246 [1654014] vinyl.compaction.2/113/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000177.index'
2021-09-16 19:50:04.246 [1654014] vinyl.dump.0/147/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000178.index'
2021-09-16 19:50:04.248 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000156.index
2021-09-16 19:50:04.248 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000156.run
2021-09-16 19:50:04.248 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000172.index
2021-09-16 19:50:04.248 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000172.run
2021-09-16 19:50:04.248 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:04.249 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:04.249 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:04.249 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.249 [1654014] vinyl.dump.0/148/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000181.run'
2021-09-16 19:50:04.249 [1654014] vinyl.compaction.2/114/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000182.run'
2021-09-16 19:50:04.250 [1654014] vinyl.dump.0/148/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000181.index'
2021-09-16 19:50:04.250 [1654014] vinyl.compaction.2/114/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000182.index'
2021-09-16 19:50:04.252 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:04.253 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:04.253 [1654014] vinyl.dump.0/149/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000184.run'
2021-09-16 19:50:04.253 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.253 [1654014] vinyl.compaction.1/112/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000185.run'
2021-09-16 19:50:04.253 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000161.index
2021-09-16 19:50:04.253 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000161.run
2021-09-16 19:50:04.254 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000178.index
2021-09-16 19:50:04.254 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000178.run
2021-09-16 19:50:04.254 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:04.254 [1654014] vinyl.dump.0/149/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000184.index'
2021-09-16 19:50:04.255 [1654014] vinyl.compaction.1/112/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000185.index'
2021-09-16 19:50:04.257 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:04.257 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:04.257 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.257 [1654014] vinyl.dump.0/150/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000188.run'
2021-09-16 19:50:04.257 [1654014] vinyl.compaction.2/115/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000189.run'
2021-09-16 19:50:04.257 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000165.index
2021-09-16 19:50:04.257 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000165.run
2021-09-16 19:50:04.257 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000181.index
2021-09-16 19:50:04.258 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000181.run
2021-09-16 19:50:04.258 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:04.258 [1654014] vinyl.compaction.2/115/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000189.index'
2021-09-16 19:50:04.258 [1654014] vinyl.dump.0/150/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000188.index'
2021-09-16 19:50:04.260 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000169.index
2021-09-16 19:50:04.260 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000169.run
2021-09-16 19:50:04.260 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000184.index
2021-09-16 19:50:04.260 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000184.run
2021-09-16 19:50:04.260 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:04.260 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:04.260 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.260 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.260 [1654014] vinyl.dump.0/151/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000193.run'
2021-09-16 19:50:04.260 [1654014] vinyl.compaction.2/116/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000194.run'
2021-09-16 19:50:04.261 [1654014] vinyl.dump.0/151/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000193.index'
2021-09-16 19:50:04.262 [1654014] vinyl.compaction.2/116/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000194.index'
2021-09-16 19:50:04.264 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.264 [1654014] main/107/vinyl.scheduler I> dumped 245824 bytes in 0.0 s, rate 12.0 MB/s
2021-09-16 19:50:04.264 [1654014] main/132/worker of "clean_all" I> dumping 49192 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.264 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.264 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.264 [1654014] vinyl.compaction.1/113/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000196.run'
2021-09-16 19:50:04.264 [1654014] vinyl.dump.0/152/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000197.run'
2021-09-16 19:50:04.264 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000173.index
2021-09-16 19:50:04.264 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000173.run
2021-09-16 19:50:04.264 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000188.index
2021-09-16 19:50:04.265 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000188.run
2021-09-16 19:50:04.265 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:04.265 [1654014] vinyl.compaction.1/113/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000196.index'
2021-09-16 19:50:04.265 [1654014] vinyl.dump.0/152/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000197.index'
2021-09-16 19:50:04.267 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000177.index
2021-09-16 19:50:04.267 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000177.run
2021-09-16 19:50:04.267 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000193.index
2021-09-16 19:50:04.267 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000193.run
2021-09-16 19:50:04.267 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:04.267 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.267 [1654014] main/107/vinyl.scheduler I> dumped 49192 bytes in 0.0 s, rate 12.8 MB/s
2021-09-16 19:50:04.267 [1654014] main/132/worker of "clean_all" I> dumping 49192 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.267 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.267 [1654014] vinyl.compaction.1/114/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000201.run'
2021-09-16 19:50:04.268 [1654014] main/107/vinyl.scheduler I> 514/0: dump started
2021-09-16 19:50:04.268 [1654014] vinyl.dump.0/153/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000202.run'
2021-09-16 19:50:04.268 [1654014] vinyl.dump.0/153/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000202.index'
2021-09-16 19:50:04.270 [1654014] main/107/vinyl.scheduler I> 514/0: dump completed
2021-09-16 19:50:04.270 [1654014] main/107/vinyl.scheduler I> dumped 49192 bytes in 0.0 s, rate 17.6 MB/s
2021-09-16 19:50:04.270 [1654014] main/109/main I> dumping 196672 bytes, expected rate 10.0 MB/s, ETA 0.0 s, write rate (avg/max) 0.0/0.0 MB/s
2021-09-16 19:50:04.270 [1654014] main/107/vinyl.scheduler I> 514/4: dump started
2021-09-16 19:50:04.270 [1654014] vinyl.dump.0/154/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000204.run'
2021-09-16 19:50:04.271 [1654014] vinyl.compaction.1/114/task I> writing `/tmp/xWd4LZ/514/0/00000000000000000201.index'
2021-09-16 19:50:04.272 [1654014] vinyl.dump.0/154/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000204.index'
2021-09-16 19:50:04.274 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000196.index
2021-09-16 19:50:04.274 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000196.run
2021-09-16 19:50:04.274 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000197.index
2021-09-16 19:50:04.274 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/0/00000000000000000197.run
2021-09-16 19:50:04.274 [1654014] main/107/vinyl.scheduler I> 514/0: completed compacting range (-inf..inf)
2021-09-16 19:50:04.274 [1654014] main/107/vinyl.scheduler I> 514/4: dump completed
2021-09-16 19:50:04.275 [1654014] main/107/vinyl.scheduler I> 514/3: dump started
2021-09-16 19:50:04.275 [1654014] vinyl.dump.0/155/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000207.run'
2021-09-16 19:50:04.275 [1654014] main/107/vinyl.scheduler I> 514/4: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.275 [1654014] main/107/vinyl.scheduler I> 514/0: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.275 [1654014] vinyl.compaction.1/115/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000208.run'
2021-09-16 19:50:04.276 [1654014] vinyl.dump.0/155/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000207.index'
2021-09-16 19:50:04.276 [1654014] vinyl.compaction.1/115/task I> writing `/tmp/xWd4LZ/514/4/00000000000000000208.index'
2021-09-16 19:50:04.278 [1654014] main/107/vinyl.scheduler I> 514/3: dump completed
2021-09-16 19:50:04.278 [1654014] main/107/vinyl.scheduler I> 514/2: dump started
2021-09-16 19:50:04.278 [1654014] main/107/vinyl.scheduler I> 514/3: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.278 [1654014] vinyl.dump.0/156/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000211.run'
2021-09-16 19:50:04.278 [1654014] vinyl.compaction.0/115/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000212.run'
2021-09-16 19:50:04.279 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000182.index
2021-09-16 19:50:04.279 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000182.run
2021-09-16 19:50:04.279 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000204.index
2021-09-16 19:50:04.279 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/4/00000000000000000204.run
2021-09-16 19:50:04.279 [1654014] main/107/vinyl.scheduler I> 514/4: completed compacting range (-inf..inf)
2021-09-16 19:50:04.280 [1654014] vinyl.dump.0/156/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000211.index'
2021-09-16 19:50:04.280 [1654014] vinyl.compaction.0/115/task I> writing `/tmp/xWd4LZ/514/3/00000000000000000212.index'
2021-09-16 19:50:04.282 [1654014] main/107/vinyl.scheduler I> 514/2: dump completed
2021-09-16 19:50:04.282 [1654014] main/107/vinyl.scheduler I> 514/1: dump started
2021-09-16 19:50:04.282 [1654014] vinyl.dump.0/157/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000215.run'
2021-09-16 19:50:04.282 [1654014] main/107/vinyl.scheduler I> 514/2: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.282 [1654014] vinyl.compaction.1/116/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000216.run'
2021-09-16 19:50:04.283 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000185.index
2021-09-16 19:50:04.283 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000185.run
2021-09-16 19:50:04.283 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000207.index
2021-09-16 19:50:04.283 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/3/00000000000000000207.run
2021-09-16 19:50:04.283 [1654014] main/107/vinyl.scheduler I> 514/3: completed compacting range (-inf..inf)
2021-09-16 19:50:04.283 [1654014] vinyl.dump.0/157/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000215.index'
2021-09-16 19:50:04.283 [1654014] vinyl.compaction.1/116/task I> writing `/tmp/xWd4LZ/514/2/00000000000000000216.index'
2021-09-16 19:50:04.286 [1654014] main/107/vinyl.scheduler I> 514/1: dump completed
2021-09-16 19:50:04.286 [1654014] main/107/vinyl.scheduler I> dumped 196672 bytes in 0.0 s, rate 11.9 MB/s
2021-09-16 19:50:04.286 [1654014] main/107/vinyl.scheduler I> 514/1: started compacting range (-inf..inf), runs 2/2
2021-09-16 19:50:04.286 [1654014] vinyl.compaction.0/116/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000219.run'
2021-09-16 19:50:04.287 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000189.index
2021-09-16 19:50:04.287 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000189.run
2021-09-16 19:50:04.287 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000211.index
2021-09-16 19:50:04.287 [1654014] vinyl.compaction.0/116/task I> writing `/tmp/xWd4LZ/514/1/00000000000000000219.index'
2021-09-16 19:50:04.287 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/2/00000000000000000211.run
2021-09-16 19:50:04.287 [1654014] main/107/vinyl.scheduler I> 514/2: completed compacting range (-inf..inf)
2021-09-16 19:50:04.289 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000194.index
2021-09-16 19:50:04.289 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000194.run
2021-09-16 19:50:04.290 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000215.index
2021-09-16 19:50:04.290 [1654014] main/107/vinyl.scheduler I> removed /tmp/xWd4LZ/514/1/00000000000000000215.run
2021-09-16 19:50:04.290 [1654014] main/107/vinyl.scheduler I> 514/1: completed compacting range (-inf..inf)
2021-09-16 19:50:04.344 [1654014] main/103/luatest memtx_tx.c:298 W> Transaction committing DDL (id=576) has aborted another TX (id=575)
2021-09-16 19:50:04.348 [1654014] main/133/guardian of "clean_all" I> expiration: task "clean_all" restarted
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x7ff9284ff5c0
  siginfo: 0x7ff9284ff6f0
  rax      0x3c               60
  rbx      0xf                15
  rcx      0x3033000000000000 3473119737632784384
  rdx      0xf                15
  rsi      0x0                0
  rdi      0x0                0
  rsp      0x7ff9284ffc60     140708099914848
  rbp      0x7ff9284ffcb0     140708099914928
  r8       0x7ff9284ffd48     140708099915080
  r9       0x7ff8f40281ec     140707222421996
  r10      0x7                7
  r11      0x7                7
  r12      0x2777d00          41385216
  r13      0x0                0
  r14      0x7ff8f40281b0     140707222421936
  r15      0x5                5
  rip      0x53bacd           5487309
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1631811004
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x5f8b56 in crash_signal_cb+a6
#1  0x7ff92bf823c0 in funlockfile+60
#2  0x53bacd in vy_stmt_dup_lsregion+2d
#3  0x55c41c in vy_lsm_set+4c
#4  0x535de5 in vy_deferred_delete_on_replace+3d5
#5  0x615052 in trigger_run+32
#6  0x47ff55 in txn_commit_stmt+1e5
#7  0x58d0a4 in vy_deferred_delete_batch_process_f+1f4
#8  0x604618 in cmsg_deliver+18
#9  0x60514f in fiber_pool_f+8f
#10 0x45b011 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+11
#11 0x5fed00 in fiber_loop+30
#12 0x81e704 in coro_init+44
```

### PR DESCRIPTION
**Pull request by locker**
A space can be dropped while the deferred DELETE handler is waiting for
quota so we need to look up the space again after yield to avoid use
after free.

Closes #6448

### CODE REVIEW

File: src/box/vinyl.c [hunk 1]
```diff
@@ -4396,8 +4396,18 @@ vy_deferred_delete_on_replace(struct trigger *trigger, void *event)
...
 	 */
 	struct vy_env *env = vy_env(space->engine);
-	if (is_first_statement)
+	if (is_first_statement) {
 		vy_quota_wait(&env->quota, VY_QUOTA_CONSUMER_COMPACTION);
+		/*
+		 * The space could have been dropped while we were
+		 * waiting for quota.
+		 */
+		space = space_cache_find(space_id);
```
Comment (alyapunov) [inline src/box/vinyl.c:4405]: What if another space with the same ID is created while we are waiting?

Comment (alyapunov) [reply src/box/vinyl.c:4405]: I think we should finally add `unique_id` member to struct space. Having space_id and unique_id we can always definitely determine that the space is still the same.

Comment (locker) [reply src/box/vinyl.c]: Right, I missed that. Thanks for catching this. Fixed by checking `vy_lsm->is_dropped` after the yield. Also added a test checking this case.

**Review by alyapunov — APPROVED** [review]

**Review by kyukhin — APPROVED** [review]
