### PR TITLE
recovery: fix big tuples blocking recovery

### LINKED ISSUE #12029: Big tuples block replica from subsribing
If xlog of a master has big tuples, replica cannot resubscribe to it. Constant reconnect and timeout: 

```
2025-11-13 18:57:49.895 [547632] main/132/applier/3301 applier.cc:112 I> can't read row
2025-11-13 18:57:49.895 [547632] main/132/applier/3301 coio.c:305 E> timed out {"type":"TimedOut","errno":110,"trace":[{"file":"./src/lib/core/coio.c","line":305}]}
2025-11-13 18:57:49.895 [547632] main/132/applier/3301 applier.cc:132 I> will retry every 1.00 second
2025-11-13 18:57:50.896 [547632] main/132/applier/3301 applier.cc:102 I> can't join/subscribe
2025-11-13 18:57:50.896 [547632] main/132/applier/3301 box.cc:4771 E> Incorrect value for option 'replication': duplicate connection with the same replica UUID {"type":"ClientError","code":59,"name":"CFG","option":"replication","details":"duplicate connection with the same replica UUID","trace":[{"file":"./src/box/box.cc","line":4771}]}
2025-11-13 18:57:50.896 [547632] main/132/applier/3301 applier.cc:132 I> will retry every 1.00 second
2025-11-13 18:58:08.918 [547632] main/132/applier/3301 applier.cc:2462 I> subscribed
2025-11-13 18:58:08.918 [547632] main/132/applier/3301 applier.cc:2463 I> remote vclock {1: 2, 2: 32} local vclock {0: 3, 1: 2, 2: 31}
2025-11-13 18:58:08.918 [547632] main/132/applier/3301 raft.c:507 I> RAFT: message {term: 1, state: follower} from 2
tarantool> 2025-11-13 18:58:12.922 [547632] applier_1/107/writer/3301 coio.c:439 E> fiber is cancelled {"type":"FiberIsCancelled","trace":[{"file":"./src/lib/core/coio.c","line":439}]}
2025-11-13 18:58:12.922 [547632] main/132/applier/3301 applier.cc:112 I> can't read row
2025-11-13 18:58:12.922 [547632] main/132/applier/3301 coio.c:305 E> timed out {"type":"TimedOut","errno":110,"trace":[{"file":"./src/lib/core/coio.c","line":305}]}
2025-11-13 18:58:12.922 [547632] main/132/applier/3301 applier.cc:132 I> will retry every 1.00 second
2025-11-13 18:58:13.923 [547632] main/132/applier/3301 applier.cc:102 I> can't join/subscribe
2025-11-13 18:58:13.923 [547632] main/132/applier/3301 box.cc:4771 E> Incorrect value for option 'replication': duplicate connection with the same replica UUID {"type":"ClientError","code":59,"name":"CFG","option":"replication","details":"duplicate connection with the same replica UUID","trace":[{"file":"./src/box/box.cc","line":4771}]}
2025-11-13 18:58:13.923 [547632] main/132/applier/3301 applier.cc:132 I> will retry every 1.00 second
2025-11-13 18:58:30.942 [547632] main/132/applier/3301 applier.cc:2462 I> subscribed
2025-11-13 18:58:30.942 [547632] main/132/applier/3301 applier.cc:2463 I> remote vclock {1: 2, 2: 32} local vclock {0: 3, 1: 2, 2: 31}
2025-11-13 18:58:30.943 [547632] main/132/applier/3301 raft.c:507 I> RAFT: message {term: 1, state: follower} from 2
tarantool> 2025-11-13 18:58:34.946 [547632] applier_1/109/writer/3301 coio.c:439 E> fiber is cancelled {"type":"FiberIsCancelled","trace":[{"file":"./src/lib/core/coio.c","line":439}]}
2025-11-13 18:58:34.946 [547632] main/132/applier/3301 applier.cc:112 I> can't read row
2025-11-13 18:58:34.946 [547632] main/132/applier/3301 coio.c:305 E> timed out {"type":"TimedOut","errno":110,"trace":[{"file":"./src/lib/core/coio.c","line":305}]}
2025-11-13 18:58:34.946 [547632] main/132/applier/3301 applier.cc:132 I> will retry every 1.00 second
2025-11-13 18:58:35.947 [547632] main/132/applier/3301 applier.cc:102 I> can't join/subscribe
2025-11-13 18:58:35.947 [547632] main/132/applier/3301 box.cc:4771 E> Incorrect value for option 'replication': duplicate connection with the same replica UUID {"type":"ClientError","code":59,"name":"CFG","option":"replication","details":"duplicate connection with the same replica UUID","trace":[{"file":"./src/box/box.cc","line":4771}]}
2025-11-13 18:58:35.947 [547632] main/132/applier/3301 applier.cc:132 I> will retry every 1.00 second
2025-11-13 18:58:52.966 [547632] main/132/applier/3301 applier.cc:2462 I> subscribed
2025-11-13 18:58:52.966 [547632] main/132/applier/3301 applier.cc:2463 I> remote vclock {1: 2, 2: 32} local vclock {0: 3, 1: 2, 2: 31}
2025-11-13 18:58:52.967 [547632] main/132/applier/3301 raft.c:507 I> RAFT: message {term: 1, state: follower} from 2
tarantool> 2025-11-13 18:58:56.970 [547632] applier_1/111/writer/3301 coio.c:439 E> fiber is cancelled {"type":"FiberIsCancelled","trace":[{"file":"./src/lib/core/coio.c","line":439}]}
2025-11-13 18:58:56.970 [547632] main/132/applier/3301 applier.cc:112 I> can't read row
2025-11-13 18:58:56.970 [547632] main/132/applier/3301 coio.c:305 E> timed out {"type":"TimedOut","errno":110,"trace":[{"file":"./src/lib/core/coio.c","line":305}]}
2025-11-13 18:58:56.970 [547632] main/132/applier/3301 applier.cc:132 I> will retry every 1.00 second
2025-11-13 18:58:57.971 [547632] main/132/applier/3301 applier.cc:102 I> can't join/subscribe
2025-11-13 18:58:57.971 [547632] main/132/applier/3301 box.cc:4771 E> Incorrect value for option 'replication': duplicate connection with the same replica UUID {"type":"ClientError","code":59,"name":"CFG","option":"replication","details":"duplicate connection with the same replica UUID","trace":[{"file":"./src/box/box.cc","line":4771}]}
2025-11-13 18:58:57.971 [547632] main/132/applier/3301 applier.cc:132 I> will retry every 1.00 second
```

Reproducer:

```lua
--
-- Instance 1
--

-- Step 1.
box.cfg{
    listen = 3301,
    replication = {3301, 3302},
    memtx_max_tuple_size = 1024 * 1024 * 1024,
    memtx_memory = 10 * 1024 * 1024 * 1024,
    wal_max_size = 10 * 1024 * 1024 * 1024
}
box.schema.user.grant('guest', 'super')

-- Step 3.
data = {}
for i = 1, 10000000 do table.insert(data, i * 1000) end
for i = 1, 64 do data = {data} end

box.schema.space.create('test'):create_index('pk')
for i = 1, 100 do
    box.space.test:insert({i, data, data, data, data, data})
    require('fiber').yield()
end

-- Step 5
box.space.test:replace{500, 1}

--
-- Instance 2
--

-- Step 2
box.cfg{
    listen = 3302,
    replication = {3301, 3302},
    memtx_max_tuple_size = 1024 * 1024 * 1024,
    memtx_memory = 10 * 1024 * 1024 * 1024,
    wal_max_size = 10 * 1024 * 1024 * 1024
}

-- Step 4
box.cfg{replication = {}}
-- Step 6
box.cfg{replication = {3301, 3302}}
```

The problem is probably the following code:

https://github.com/tarantool/tarantool/blob/cc77a6ead00b9a07233f302dabae994fc79dde21/src/box/recovery.cc#L255-L257

Replica connects, needs data from very long xlog file, master reads that xlog, yields every `WAL_ROWS_PER_YIELD` rows, but this seems not enough, when tuples in xlog are big in size. Proposed by @sergepetrenko

Seems related (or even duplicate): https://github.com/tarantool/tarantool/issues/6750

### PR DESCRIPTION
**Pull request by LevKats**
Replace constant `WAL_ROWS_PER_YIELD` with `xlog_row_bytes_per_yield`
tweak to ensure that the relay thread does not skip heartbeats while
parsing large tuples, and does not yield too frequently. Introduce
`ERRINJ_XLOG_READ_ROW_DELAY` to emulate the delay when parsing xlogs
consisting of large rows.

Fixes #12029

NO_DOC=bugfix
NO_CHANGELOG=bugfix

### CODE REVIEW

File: src/lib/core/errinj.h [hunk 1]
```diff
@@ -212,6 +212,7 @@ struct errinj {
 	_(ERRINJ_XLOG_GARBAGE, ERRINJ_BOOL, {.bparam = false}) \
 	_(ERRINJ_XLOG_META, ERRINJ_BOOL, {.bparam = false}) \
 	_(ERRINJ_XLOG_READ, ERRINJ_INT, {.iparam = -1}) \
+	_(ERRINJ_XLOG_READ_ROW_DELAY, ERRINJ_DOUBLE, {.dparam = 0}) \
```
Comment (Serpentian) [inline src/lib/core/errinj.h:215]: This errinj is needed exclusively for the test in the last commit. Why do we want to put it in the separate commit?

File: src/box/xstream.h [hunk 2]
```diff
@@ -53,6 +53,8 @@ struct xstream {
 	xstream_write_f write;
 	xstream_yield_f yield;
 	uint64_t row_count;
+	/* Number of parsed bytes since last yield. */
+	uint64_t row_bytes_since_yield;
```
Comment (Serpentian) [inline src/box/xstream.h:57]: The variable looks crutchy to me: it`s way too specific.

I propose to create local variables in `recover_xlog` and `recovery_scan` instead,  it seems we don't need this value to be preserved between different xlog scans or recovery, or am I missing smth?

Alternatively, we can completely encapsulate the variable into `xstream`, so that it's automatically bumped on successfull write inside `xstream_write` and is cleared only on `xstream_reset`. It'll be called smth like `bytes_written`

File: src/box/recovery.cc [hunk 3]
```diff
@@ -43,6 +43,7 @@
 #include "coio_file.h"
 #include "error.h"
 #include "iproto_constants.h"
+#include "tweaks.h"
```
Comment (Serpentian) [inline src/box/recovery.cc:47]: > Setting both `xlog_row_bytes_per_yield` and previously
introduced `WAL_ROWS_PER_YIELD` may be useful when logs consist of both
large and small rows.

It seems that 2 tweaks is an overkill here. The `WAL_ROWS_PER_YIELD` is definitely not enough, since e.g. if user has almost all rows which recover fast and then 2^15 rows, which recover slow, the time between yields for these slow rows will be huge

The yield per N bytes will work iff the time of recovery depends on the size of the row. It seems, it's the case for ARROW, but I`m not sure here. Maybe @Gumix may help us here? The backtrace of slow recovery process is:

<details><summary>Traces</summary>

```
#0  0x00007b7bcf7186c2 in __GI___libc_malloc (bytes=bytes@entry=256) at malloc.c:3079
#1  0x000056ae31ff25d5 in ArrowMalloc (size=size@entry=256)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/third_party/arrow/nanoarrow/src/nanoarrow/common/utils.c:217
#2  0x000056ae31fed45c in ArrowArrayInitFromType (array=array@entry=0x7b790837bf00, storage_type=NANOARROW_TYPE_INT32)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/third_party/arrow/nanoarrow/src/nanoarrow/common/array.c:156
#3  0x000056ae31fed78d in ArrowArrayInitFromArrayView (array=0x7b790837bf00, array_view=0x7b79082b7f70, error=0x7b79082c81d4)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/third_party/arrow/nanoarrow/src/nanoarrow/common/array.c:214
#4  0x000056ae31fed84b in ArrowArrayInitFromArrayView (array=array@entry=0x7b790fd80170, array_view=array_view@entry=0x7b79082c78f8, error=error@entry=0x7b79082c81d4)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/third_party/arrow/nanoarrow/src/nanoarrow/common/array.c:230
#5  0x000056ae31ff47ef in ArrowIpcDecoderDecodeArrayInternal (field_i=field_i@entry=-1, out=out@entry=0x7b790fd80170,
    validation_level=validation_level@entry=NANOARROW_VALIDATION_LEVEL_FULL, error=error@entry=0x7b79082c81d4, decoder=0x7b79082c80e8)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/third_party/arrow/nanoarrow/src/nanoarrow/ipc/decoder.c:1893
#6  0x000056ae31ff8202 in ArrowIpcDecoderDecodeArrayFromShared (decoder=decoder@entry=0x7b79082c80e8, body=body@entry=0x7b790fd80220, i=-1, out=out@entry=0x7b790fd80250,
    validation_level=validation_level@entry=NANOARROW_VALIDATION_LEVEL_FULL, error=error@entry=0x7b79082c81d4)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/third_party/arrow/nanoarrow/src/nanoarrow/ipc/decoder.c:2040
#7  0x000056ae31ffbda0 in ArrowIpcArrayStreamReaderGetNext (stream=<optimized out>, out=0x7b790fd80850)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/third_party/arrow/nanoarrow/src/nanoarrow/ipc/reader.c:472
#8  0x000056ae31a0621a in ArrowArrayStreamGetNext (error=0x7b790fd803a0, out=0x7b790fd80850, array_stream=0x7b790fd80340)
    at /builds/tarantool/delivery/sdk/build.sdk/tarantool-ee-master/static-build/tarantool-prefix/src/tarantool-build/tarantool/build/nanoarrow/include/nanoarrow/common/inline_types.h:387
#9  arrow_ipc_decode (array=0x7b790fd80850, schema=0x7b790fd80800, data=<optimized out>, data_end=<optimized out>)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/lib/core/arrow_ipc.c:142
#10 0x000056ae31cecfd0 in mp_validate_arrow (len=<optimized out>, data=<optimized out>) at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/lib/core/mp_arrow.c:20
#11 msgpack_check_ext_data (type=<optimized out>, data=<optimized out>, len=<optimized out>) at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/msgpack.c:148
#12 0x000056ae3198a14f in mp_check (data=0x56ae3819a340, end=0x7b790fc5def9 "\313A\332IW`}\230\336\b\002\t\001\202\020\315\001\035!\222\001\315t\222\377\004")
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/lib/msgpuck/msgpuck.h:3363
#13 0x000056ae3192236d in xrow_decode (header=0x7b790fd80ae0, pos=0x56ae3819a340, end=<optimized out>, end_is_exact=<optimized out>)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/xrow.c:272
#14 0x000056ae3190cb01 in xlog_tx_cursor_next_row (xrow=0x7b790fd80ae0, tx_cursor=0x56ae3819a330)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/xlog.c:1871
#15 xlog_cursor_next_row (cursor=cursor@entry=0x56ae38199080, xrow=xrow@entry=0x7b790fd80ae0) at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/xlog.c:1990
#16 0x000056ae31912ac4 in xlog_cursor_next (cursor=0x56ae38199080, xrow=0x7b790fd80ae0, force_recovery=false)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/xlog.c:2010
#17 0x000056ae31be5664 in xlog_cursor_next_xc (force_recovery=<optimized out>, xrow=0x7b790fd80ae0, cursor=0x56ae38199080)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/xlog.h:1041
#18 recover_xlog (r=r@entry=0x56ae38198f60, stream=stream@entry=0x56ae35bac860, stop_vclock=stop_vclock@entry=0x0)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/recovery.cc:253
#19 0x000056ae31be5f0a in recover_remaining_wals (r=0x56ae38198f60, stream=0x56ae35bac860, stop_vclock=0x0, scan_dir=<optimized out>)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/recovery.cc:375
#20 0x000056ae31bd55bc in relay_process_wal_event (watcher=0x56ae35bac9f8, events=<optimized out>)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/relay.cc:730
#21 0x000056ae31a09773 in cmsg_deliver (msg=0x56ae35bacaf0) at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/lib/core/cbus.c:360
#22 0x000056ae31a0993b in cbus_process (endpoint=0x56ae35bacc70) at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/lib/core/cbus.c:611
#23 0x000056ae3187ff30 in cbus_pair.constprop.0 (dest_name=dest_name@entry=0x56ae33032c0f "wal", src_name=src_name@entry=0x56ae35bacc70 "relay_wal_0x56ae35bac6c0",
    dest_pipe=dest_pipe@entry=0x56ae35baca10, src_pipe=src_pipe@entry=0x56ae35baca70, pair_cb=<optimized out>, pair_arg=pair_arg@entry=0x56ae35bac9f8, process_cb=<optimized out>)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/lib/core/cbus.c:514
#24 0x000056ae31bdc468 in wal_set_watcher (watcher_cb=0x56ae31bd5580 <relay_process_wal_event(wal_watcher*, unsigned int)>, process_cb=<optimized out>,
    name=0x56ae35bacc70 "relay_wal_0x56ae35bac6c0", watcher=0x56ae35bac9f8) at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/wal.c:1586
#25 relay_subscribe_f(typedef __va_list_tag __va_list_tag *) (ap=<optimized out>) at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/box/relay.cc:1023
#26 0x000056ae31ceafbd in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>)
    at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/lib/core/fiber.h:1324
#27 0x000056ae31a15ae2 in fiber_loop (data=<optimized out>) at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/src/lib/core/fiber.c:1167
#28 0x000056ae318e5428 in coro_init () at /builds/tarantool/delivery/sdk/tarantool-ee-master/tarantool/third_party/coro/coro.c:108
```

</details>

If it's the case, then won't xlog_row_bytes_per_yield be enough? It seems to me it solves both problems. Or am I missing smth? @LevKats

File: src/box/recovery.cc [hunk 4]
```diff
@@ -77,6 +78,9 @@
 
 /* {{{ Initial recovery */
 
+uint64_t xlog_row_bytes_per_yield = 1 << 16;
```
Comment (Serpentian) [inline src/box/recovery.cc]: Well, previously we yielded every 2^15 rows, now we yield either every 2^15 rows or every 2^16 bytes. The question is the default value of the `xlog_row_bytes_per_yield` here, yielding too often will affect the performance of replication, yielding too rarely breaks the replication/join.

I am afraid, that with this default value we might start yielding too often. I don't know the average size of one row among our user's databases. We can start with measuring, how this patch affects the perf of replication with `1mops` test

File: src/box/recovery.cc [hunk 5]
```diff
@@ -43,6 +43,7 @@
 #include "coio_file.h"
```
Comment (Serpentian) [inline src/box/recovery.cc:43]: Another major question about the patch: are we going to change the default values and try to make it work in all cases? On the one hand, we already have user, which complain, that join doesn't work, so it seems, we should fix that for them. On the other hand, it's reproduced only on one specific virtual machine, the speed of CPU and disk on which is pretty slow, so it seems, tweak should be enough.

I`m on the side of tweak here, no change of defaults

**Review by Serpentian — COMMENTED** [review]
Thank you for working on that! It`s pretty controversial problem, let's discuss it a little bit

File: src/box/xstream.h (hunk 2 above)
Comment (LevKats) [reply src/box/xstream.h:57]: Maybe it is somewhat an edge case, but we [do](https://github.com/tarantool/tarantool/blob/0ccd7fe7708338ca3a7157de0622fcd5e8efb386/src/box/recovery.cc#L375) have an example of examples of consecutive `recover_xlog` calls: if there are several xlogs each consisting of large enough tuples but smaller than `xlog_row_bytes_per_yield`. I think we should keep some state between the calls. So I prefer the encapsulation option, however it probably should be consistent with `row_count` modifications which are located in `recovery.cc` and not in `xstream_write`. @Serpentian, what do you think?

File: src/box/recovery.cc (hunk 3 above)
Comment (LevKats) [reply src/box/recovery.cc:47]: My intention to keep `WAL_ROWS_PER_YIELD` in one form or another is indeed due to the fact that we want to take into account the dependence of the parsing speed on the size of the row. The intuition was that we first parse a header with some constant overhead and then the body (which may have some complicated structure). So two tweaks may be set separately for two types of rows. But I haven't really benchmarked this assumption indeed.

File: src/lib/core/errinj.h (hunk 1 above)
Comment (LevKats) [reply src/lib/core/errinj.h:215]: Fixed.

File: src/box/recovery.cc (hunk 3 above)
Comment (LevKats) [reply src/box/recovery.cc:47]: Decided to keep only `xlog_row_bytes_per_yield` and remove `WAL_ROWS_PER_YIELD` completely.

File: src/box/recovery.cc (hunk 4 above)
Comment (LevKats) [reply src/box/recovery.cc]: Changed to 2^19.

File: src/box/recovery.cc (hunk 5 above)
Comment (LevKats) [reply src/box/recovery.cc:43]: Probably fixed as `WAL_ROWS_PER_YIELD` Is removed.

File: src/box/xstream.h (hunk 2 above)
Comment (Serpentian) [reply src/box/xstream.h:57]: But then why don't we want to reset it inside `xstream_reset` as it's done for `row_count`? And maybe we can consider incapsulating the `row_count` inside xstream too? It seems, it's shaky, to rely on external code to bump it. What do you think?

Comment (LevKats) [reply src/box/xstream.h:57]: > why don't we want to reset it inside xstream_reset as it's done for row_count

It's because we don't always reset on yields. However, we do always yield on resets

> And maybe we can consider incapsulating the row_count inside xstream too?

Looks like we call `xstream_write` only in the `recover_xlog` but not in `recovery_scan`, where this logic should be preserved too. So, maybe it is not xstream that should encapsulate the logic.

**Review by Serpentian — APPROVED** [review]
Thank you for working on that!

**Review by Gerold103 — APPROVED** [review]
🚀

**Comment by sergepetrenko** [comment]
Backports:
3.3 https://github.com/tarantool/tarantool/pull/12457
3.5 https://github.com/tarantool/tarantool/pull/12455
3.6 https://github.com/tarantool/tarantool/pull/12456
