### PR TITLE
applier: fix assertion failure after split brain

### LINKED ISSUE #10073: Assertion `l->owner != fiber()` fails after replication reconfiguration and split brain
**Bug description**

* OS: MacOS m1
* OS Version: m1
* Architecture: arm64

Place `tarantool --version` output here.

```
tarantool --version
Tarantool Enterprise 3.1.0-0-g663f509
Target: Darwin-arm64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/Users/michael.filonenko/work/tarantool-ee-3.1/static-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: Clang-15.0.0.15000309
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common  -fmacro-prefix-map=/Users/michael.filonenko/work/tarantool-ee-3.1=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common  -fmacro-prefix-map=/Users/michael.filonenko/work/tarantool-ee-3.1=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
```

**Steps to reproduce**

Run tarantool cluster

- tt init
- cat instances.enabled/app/config.yaml
```
credentials:
  users:
    guest:
      roles: [super]

replication:
  failover: election

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
                - uri: "127.0.0.1:3301"
          instance002:
            iproto:
              listen:
                - uri: "127.0.0.1:3302"
          instance003:
            iproto:
              listen:
                - uri: "127.0.0.1:3303"
```

tt run

make workload using many fibers

make box.ctl.promote() under load

make a split brain replication fault

try to restart replication

`r = box.cfg.replication box.cfg{replication={}} box.cfg{replication=r}`

```
2024-05-30 15:11:12.253 [13918] main/129/applier/127.0.0.1:3301 I> RAFT: leader is 3, follow
Assertion failed: (l->owner != fiber()), function latch_lock_timeout, file latch.h, line 139.
Watchdog 2024/05/30 15:11:12 (WARN): "signal: abort trap".
Watchdog 2024/05/30 15:11:12 (INFO): the Instance has shutdown.
```

```
#1  0x102cb9270 in backtrace_collect+256
#2  0x102ad1e9c in latch_lock_timeout(latch*, double)+156
#3  0x102ad1df4 in latch_lock(latch*)+32
#4  0x102ad425c in applier_apply_tx(applier*, stailq*)+200
#5  0x102ad3c44 in applier_process_batch(cmsg*)+332
#6  0x102acc60c in applier_subscribe(applier*)+3068
#7  0x102ac8d84 in applier_f(char*)+1764
#8  0x102936100 in fiber_cxx_invoke(int (*)(char*), char*)+32
#9  0x102cb03e8 in fiber_loop+268
#10 0x103469b88 in coro_startup+8

Assertion failed: (l->owner != fiber()), function latch_lock_timeout, file latch.h, line 145.
```

A clear and concise description of what you see.

**Expected behavior**

### PR DESCRIPTION
**Pull request by Serpentian**
After receiving async transaction from an old term applier_apply_tx exits without unlocking the latch. If the same applier tries to subscribe for replication, it fails with assertion, as the latch is already locked.

Let's use scope guard in order to avoid leaving the latch locked.

Closes #10073

NO_DOC=bugfix
NO_CHANGELOG=no crash on release version

### CODE REVIEW

File: src/box/applier.cc [hunk 1]
```diff
@@ -1699,6 +1701,7 @@ applier_apply_tx(struct applier *applier, struct stailq *rows)
 			}
 		}
 	}
+	int rc = 0;
 	applier_synchro_filter_tx(rows);
```
Comment (sergepetrenko) [inline src/box/applier.cc:1705]: AFAIU the problem lies in this `applier_synchro_filter_tx` call.
Let's better make it return an error rather than throw it. This will make `applier_apply_tx` behavior more consistent: it will never throw.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the fix!

**Review by sergepetrenko — APPROVED** [review]
Thanks for finding and fixing this!

**Review by Gerold103 — COMMENTED** [review]
Thanks for the patch! Oh, I like how the test is small and didn't even require a new file 🔥 (tbh, I didn't understand it fully, but I trust if fails without the patch).

**Comment by sergepetrenko** [comment]
Backports:
3.1 https://github.com/tarantool/tarantool/pull/10259
2.11 https://github.com/tarantool/tarantool/pull/10260
