### PR TITLE
log: fix inability to start from the root directory

### LINKED ISSUE #8158: Tarantool does not start from the root directory
**Bug description**

If `tarantool` master is installed on the Ubuntu container, after restart `tarantool` binary is broken.

* OS: Ubuntu
* OS Version: 22.04
* Architecture: amd64

`tarantool 2.11.0~entrypoint-877`

**Steps to reproduce**

1. Clone the master
    ```bash
    git checkout master
    git pull origin master
    ```
2. Build the master with packpack
    ```bash
    OS=ubuntu DIST=jammy make -f .pack.mk package
    ```
3. Install the artifact to some clean docker container
    ```bash
    docker run -it -v `pwd`/build:/build ubuntu:22.04
    ```

    ```bash
    cd /build
    apt update
    apt install `pwd`/tarantool_2.11.0~entrypoint.877.dev-1_amd64.deb  -y
    ```
4. Run tarantool (ok)
    ```bash
    tarantool
    Tarantool 2.11.0-entrypoint-877-g457b293cb
    type 'help' for interactive help
    ```
5. Stop the container (Ctrl+C)
6. Restart the container
    ```bash
    docker ps -a
    docker start 2eb062c5c047 
    ```
7. Run tarantool (not ok)
    ```bash
    docker exec -it 2eb062c5c047 /bin/bash
    ```

    ```bash
    tarantool
    PANIC: unprotected error in call to Lua API (builtin/tarantool.lua:78: attempt to perform arithmetic on local 'ind' (a nil value))
    ```

**Actual behavior**

Get `PANIC: unprotected error in call to Lua API (builtin/tarantool.lua:78: attempt to perform arithmetic on local 'ind' (a nil value))` on `tarantool` start.

**Expected behavior**

`tarantool` starts ok.

### PR DESCRIPTION
**Pull request by Gumix**
The function `remove_root_directory`, which is used for obtaining module names for per-module logging, throws an error when current working directory is `/`. Rewrite it to fix the bug and rename it to `strip_cwd_from_path` to make the name more clear.

Closes #8158

### CODE REVIEW

File: src/lua/init.lua [hunk 1]
```diff
@@ -57,27 +57,28 @@ local function get_require_overload_count(stack)
...
-local function remove_root_directory(path)
-    local pwd = os.getenv("PWD")
-    if pwd == nil then
-        return path
+-- Return longest common subpath of two paths.
+local function get_common_subpath(path1, path2)
+    local result = '/'
+    for _, dir in ipairs(path1:split('/')) do
+        local common = fio.pathjoin(result, dir)
+        if path2:startswith(common) then
```
Comment (locker) [inline src/lua/init.lua:65]: This doesn't look correct. For example, after the following change `per_module_log_unit_test` still passes although it shouldn't:

<details><summary>diff</summary>

```diff
diff --git a/test/app-luatest/per_module_log_unit_test.lua b/test/app-luatest/per_module_log_unit_test.lua
index b87e5992c05d..261cb8a4e4d9 100644
--- a/test/app-luatest/per_module_log_unit_test.lua
+++ b/test/app-luatest/per_module_log_unit_test.lua
@@ -8,7 +8,7 @@ local module_name_from_filename = tarantool._internal.module_name_from_filename
 g.test_strip_cwd_from_path = function()
     local testcases = {
         { cwd = '/', path = '/aaa/bbb/ccc', expected = 'aaa/bbb/ccc' },
-        { cwd = '/home/aaa/bbb', path = '/home/aaa/bbb/ccc/ddd', expected = 'ccc/ddd' },
+        { cwd = '/home/aaa/bbb', path = '/home/aaa/bbbccc/ddd', expected = 'ccc/ddd' },
         { cwd = '/home/some/other/path', path = '/home/aaa/bbb', expected = 'aaa/bbb' },
         { cwd = '/totally/different', path = '/home/aaa/bbb', expected = 'home/aaa/bbb' },
         { cwd = '/doesnt/matter', path = 'aaa/bbb', expected = 'aaa/bbb' },
```

</details>

Anyway, I don't quite get why you split the path by `/`. Why not simply find the longest common sub-string?

**Review by locker — CHANGES_REQUESTED** [review]

File: src/lua/init.lua (hunk 1 above)
Comment (Gumix) [reply src/lua/init.lua]: > This doesn't look correct. For example, after the following change `per_module_log_unit_test` still passes although it shouldn't:
 
Thanks, fixed.

> Anyway, I don't quite get why you split the path by `/`. Why not simply find the longest common sub-string?

With `split` it's easier to handle situations like this:
```lua
{ cwd = '/home/common_qwe', path = '/home/common_asd/aaa', expected = 'common_asd/aaa' }
```

File: src/lua/init.lua [hunk 2]
```diff
@@ -57,27 +57,29 @@ local function get_require_overload_count(stack)
...
-        cur_dir = cur_dir:sub(1, ind - 1)
+-- Strip a common part of cwd and path from the path.
+local function strip_cwd_from_path(cwd, path)
+    if not cwd or cwd:sub(1, 1) ~= '/' or
+       not path or path:sub(1, 1) ~= '/' then
+        return path
     end
-    return path
+    local common = get_common_subpath(cwd, path)
+    return path:gsub('^' .. common .. '/?', '')
```
Comment (locker) [inline src/lua/init.lua:82]: It doesn't look like you may use regular expression like that: if I update the test as follows it starts to fail although it shouldn't.

<details><summary>diff</summary>

```diff
diff --git a/test/app-luatest/per_module_log_unit_test.lua b/test/app-luatest/per_module_log_unit_test.lua
index ee6b1b85b598..81f45bb85d71 100644
--- a/test/app-luatest/per_module_log_unit_test.lua
+++ b/test/app-luatest/per_module_log_unit_test.lua
@@ -13,7 +13,7 @@ g.test_strip_cwd_from_path = function()
         { cwd = '/totally/different', path = '/home/aaa/bbb', expected = 'home/aaa/bbb' },
         { cwd = '/doesnt/matter', path = 'aaa/bbb', expected = 'aaa/bbb' },
         { cwd = '/qwerty', path = '/aaa/qwerty/bbb', expected = 'aaa/qwerty/bbb' },
-        { cwd = '/home/aaa/bbb', path = '/home/aaa/bbbccc/ddd', expected = 'bbbccc/ddd' },
+        { cwd = '/home/a-aa/bbb', path = '/home/a-aa/bbbccc/ddd', expected = 'bbbccc/ddd' },
         { cwd = '/home/common_qwe', path = '/home/common_asd/aaa', expected = 'common_asd/aaa' },
     }
     for _, test in pairs(testcases) do
```

</details>

**Review by locker — CHANGES_REQUESTED** [review]

File: src/lua/init.lua (hunk 2 above)
Comment (Gumix) [reply src/lua/init.lua]: Thanks, fixed.

**Review by locker — APPROVED** [review]
