### PR TITLE
lua/fio: clearer error msg for pread()

### LINKED ISSUE #4963: fio: vague error message when calling pread without arguments
Following snippet should be self explanatory:

```
tarantool> f = fio.open('out.json', {'O_RDONLY'})
---
...

tarantool> f:pread() -- Argument error should be thrown instead
---
- error: 'builtin/buffer.lua:123: attempt to perform arithmetic on ''char *'' and
    ''nil'''
...
```

### PR DESCRIPTION
**Pull request by Lord-KA**
fh:pread() will raise a clear error on wrong arguments.

Closes #4963

NO_DOC=bugfix
NO_CHANGELOG=bugfix

### CODE REVIEW

File: src/lua/fio.lua [hunk 1]
```diff
@@ -99,13 +99,21 @@ end
...
 fio_methods.pread = function(self, buf, size, offset)
-    local tmpbuf
+    local no_buf = false
     if not ffi.istype(const_char_ptr_t, buf) then
         offset = size
         size = buf
+        no_buf = true
+    end
+    if (type(size) ~= 'number' or (type(offset) ~= 'number' and offset ~= nil)) then
+        error('usage: fh:pread([buf,] size, offset = 0)')
```
Comment (Totktonada) [inline src/lua/fio.lua:109]: Nit: Python style named parameter syntax may be confusing in the Lua context (is it positional or a table is assumed around?). I propose the following:

```lua
error('Usage: fh:pread(buf, size[, offset]) or fh:pread(size[, offset])')
```

File: src/lua/fio.lua [hunk 2]
```diff
@@ -99,13 +99,21 @@ end
...
+    end
+    local tmpbuf
+    if (no_buf) then
```
Comment (Totktonada) [inline src/lua/fio.lua:112]: Nit: Parentheses are not necessary here.

File: src/lua/fio.lua [hunk 3]
```diff
@@ -99,13 +99,21 @@ end
...
 -- pread(buf, size, offset) -> len
 fio_methods.pread = function(self, buf, size, offset)
-    local tmpbuf
+    local no_buf = false
     if not ffi.istype(const_char_ptr_t, buf) then
         offset = size
         size = buf
+        no_buf = true
+    end
+    if (type(size) ~= 'number' or (type(offset) ~= 'number' and offset ~= nil)) then
```
Comment (Totktonada) [inline src/lua/fio.lua:108]: Nit: Outermost parentheses are not necessary.

Nit: Personally I find this expression a bit too complex -- and/or, several comparisons, negation of what is expected. What if we would have one more parameter?

What do you think about a step-by-step validation?

```lua
local usage = '<...>'
if type(size) ~= 'number' then
    error(usage)
end
if offset ~= nil and type(offset) ~= 'number' then
    error(usage)
end
```

File: test/app-luatest/gh_4963_fio_pread_err_msg_test.lua [hunk 4]
```diff
@@ -0,0 +1,10 @@
+local fio = require('fio')
+
+local t = require('luatest')
+local g = t.group()
+
+g.test_fio_pread_err_msg = function()
+    local fh = fio.open('/tmp/', {'O_RDWR', 'O_TMPFILE'})
```
Comment (Totktonada) [inline test/app-luatest/gh_4963_fio_pread_err_msg_test.lua:7]: Linux specific? I guess `/dev/null` will do the job on most Linux/Mac OS/*BSD systems.

File: src/lua/fio.lua (hunk 2 above)
Comment (Lord-KA) [reply src/lua/fio.lua:112]: Fixed.

File: src/lua/fio.lua (hunk 1 above)
Comment (Lord-KA) [reply src/lua/fio.lua:109]: Fixed.

File: src/lua/fio.lua (hunk 3 above)
Comment (Lord-KA) [reply src/lua/fio.lua:108]: I don't think that dividing the `if` is worth it. Maybe, if we explicitly compare with every format, it would be better:
``` lua
local usage = '...'
if type(size) == 'number' and type(offset) == 'number' then
    usage = nil
end
if type(size) == 'number' and offset == nil then
    usage = nil
end
if (usage) then
    error(usage)
end
```

But I feel that it is too much in this case.

File: test/app-luatest/gh_4963_fio_pread_err_msg_test.lua (hunk 4 above)
Comment (Lord-KA) [reply test/app-luatest/gh_4963_fio_pread_err_msg_test.lua:7]: Good idea, thanks.

File: src/lua/fio.lua (hunk 3 above)
Comment (Totktonada) [reply src/lua/fio.lua]: Okay.

**Review by Totktonada — APPROVED** [review]

**Comment by igormunkin** [comment]
Also backported to 2.10 in scope of 4ec07cb (2.10.3-65-g4ec07cb80) and to 1.10 in scope of f3b6af7 (1.10.14-27-gf3b6af7fb).
