### PR TITLE
box: add details to DML specific errors

### LINKED ISSUE #7223: Invalid key part count error is not descriptive enough
```yaml
- error: Invalid key part count in an exact match (expected 1, got 0)
```

It is hard to spot what exactly raises the error. There are different ways to make it better:

* Give more details: space name, index name.
* Include a code line number into the message itself.
* Change something about error reporting to not miss details.

Inspired by @Mons. He said that he met it as result of a maintenance script run and was angry.

### PR DESCRIPTION
**Pull request by nshy**
Closes #7223

EE part is https://github.com/tarantool/tarantool-ee/pull/776

For example for this setup:

```lua
local test = box.schema.create_space('test')
test:create_index('primary')
test:create_index('second', {parts = {2, 'unsigned', 1, 'unsigned'}})
```

Before we get (note that compat option `box_error_serialize_verbose` is set
to 'new' to show error details in console. It does not affect whether
details are added or not):

```
tarantool> test.index.second:get{1}
---
- error:
code: 19
base_type: ClientError
type: ClientError
message: Invalid key part count in an exact match (expected 2, got 1)
trace:
- file: ./src/box/index.cc
  line: 149
...
```

And now we get (see 'space', 'space_id', 'index', 'index_id' and 'key' fields):

```
tarantool> test.index.second:get{1}
---
- error:
code: 19
base_type: ClientError
message: Invalid key part count in an exact match (expected 2, got 1)
trace:
- file: ./src/box/index.cc
  line: 149
type: ClientError
index: second
space: test
index_id: 2
space_id: 512
key: [1]
...
```

### CODE REVIEW

**Review by andreyaksenov — APPROVED** [review]

File: src/box/index.cc [hunk 1]
```diff
@@ -165,11 +175,15 @@ index_point_lookup_validate(struct index_def *index_def, const char *key,
 {
 	if (!index_def->opts.is_unique) {
 		diag_set(ClientError, ER_MORE_THAN_ONE_TUPLE);
-		return -1;
+		error_set_key_with_part_count(key, part_count);
```
Comment (locker) [inline src/box/index.cc:178]: I don't think we need to know the key for this kind of error.

File: src/box/key_def.c [hunk 2]
```diff
@@ -1219,3 +1219,31 @@ key_validate_parts(const struct key_def *key_def, const char *key,
 	*key_end = key;
 	return 0;
 }
+
+char *
+mp_key_append_part_count(const char *key, uint32_t part_count, char **end)
```
Comment (locker) [inline src/box/key_def.c:1224]: This function looks like an internal helper. No need to make it public. I'd even inline it in `error_set_key_with_part_count`.

Moreover, I think that this payload field should be set by `key_validate_parts`. If we did that, we could drop `error_set_key_with_part_count` altogether (inline it in `key_validate_parts`).

File: src/box/session_settings.c [hunk 3]
```diff
@@ -342,12 +342,16 @@ session_settings_space_execute_update(struct space *space, struct txn *txn,
...
+		diag_set(ClientError, ER_EXACT_MATCH, 1, key_len);
+		index_set_error_details(pk_def);
+		error_set_key_with_part_count(key, key_len);
 		return -1;
 	}
-	if (key_len > 1 || mp_typeof(*key) != MP_STR) {
+	if (mp_typeof(*key) != MP_STR) {
 		diag_set(ClientError, ER_KEY_PART_TYPE, 0, "string");
+		index_set_error_details(pk_def);
+		error_set_key_with_part_count(key, key_len);
```
Comment (locker) [inline src/box/session_settings.c:354]: Let's use `index_point_lookup_validate` here (in the previous patch).

File: src/box/vinyl.c [hunk 4]
```diff
@@ -1714,11 +1714,17 @@ vy_unique_key_validate(struct vy_lsm *lsm, const char *key,
 	if (original_part_count != part_count) {
 		diag_set(ClientError, ER_EXACT_MATCH,
 			 original_part_count, part_count);
-		return -1;
+		goto error;
 	}
 	const char *key_end;
-	return key_validate_parts(lsm->cmp_def, key, part_count, false,
-				  &key_end);
+	if (key_validate_parts(lsm->cmp_def, key, part_count, false,
```
Comment (locker) [inline src/box/vinyl.c:1720]: I think we can use `exact_key_validate` here.

File: src/box/index.h [hunk 5]
```diff
@@ -458,6 +458,17 @@ int
 exact_key_validate(struct key_def *key_def, const char *key,
 		   uint32_t part_count);
 
+/**
+ * Check that index and key are valid for point lookup. Point lookup
+ * points at single tuple.
```
Comment (locker) [inline src/box/index.h:463]: Do we really need this new function? Can't we just patch `exact_key_validate` to take `index_def` and check that the index is actually unique? This would be consistent with `key_validate`.

I'd also drop `exact_key_validate_nullable` while we are at it (inline in `iterator_position_validate`).

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/index.cc (hunk 1 above)
Comment (nshy) [reply src/box/index.cc:178]: Fixed. Source diff:

```diff
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -175,7 +175,6 @@ index_point_lookup_validate(struct index_def *index_def, const ch>
 {
        if (!index_def->opts.is_unique) {
                diag_set(ClientError, ER_MORE_THAN_ONE_TUPLE);
-               error_set_key_with_part_count(key, part_count);
                goto error;
        }
```

File: src/box/session_settings.c (hunk 3 above)
Comment (nshy) [reply src/box/session_settings.c:354]: Done.

<details>
<summary>diff</summary>

```diff
--- a/src/box/session_settings.c
+++ b/src/box/session_settings.c
@@ -342,16 +342,8 @@ session_settings_space_execute_update(struct space *space, struct txn *txn,

        const char *new_key, *key = request->key;
        uint32_t new_size, new_key_len, key_len = mp_decode_array(&key);
-       if (key_len != 1) {
-               diag_set(ClientError, ER_EXACT_MATCH, 1, key_len);
+       if (index_point_lookup_validate(pk_def, key, key_len) != 0) {
                index_set_error_details(pk_def);
-               error_set_key_with_part_count(key, key_len);
-               return -1;
-       }
-       if (mp_typeof(*key) != MP_STR) {
-               diag_set(ClientError, ER_KEY_PART_TYPE, 0, "string");
-               index_set_error_details(pk_def);
-               error_set_key_with_part_count(key, key_len);
                return -1;
        }
        key = mp_decode_str(&key, &key_len);
```

</details>

File: src/box/vinyl.c (hunk 4 above)
Comment (nshy) [reply src/box/vinyl.c:1720]: Looks like there is case when we need this:

<details>
<summary>test output snip</summary>

```diff
[002] vinyl/write_iterator.test.lua                                   [ fail ]
[002]
[002] Test failed! Result content mismatch:
[002] --- vinyl/write_iterator.result	Tue Jan 23 16:39:24 2024
[002] +++ /tmp/t/rejects/vinyl/write_iterator.reject	Thu Apr 11 17:03:54 2024
[002] @@ -217,9 +217,11 @@
[002]  ...
[002]  index2:delete{'9'}
[002]  ---
[002] +- error: Invalid key part count in an exact match (expected 2, got 1)
[002]  ...
[002]  index2:delete{'99'}
[002]  ---
[002] +- error: Invalid key part count in an exact match (expected 2, got 1)
[002]  ...
[002]  box.snapshot()
```

</details>

File: src/box/index.h (hunk 5 above)
Comment (nshy) [reply src/box/index.h:463]: Done. Diff is bit messy.

File: changelogs/unreleased/gh-7223-add-more-error-details.md [hunk 6]
```diff
@@ -0,0 +1,3 @@
+## bugfix/box
+
+* Added details for DML errors related to key validation (gh-7223).
```
[the remark this answers is not in the document]
Comment (nshy) [reply changelogs/unreleased/gh-7223-add-more-error-details.md:3]: Dropped.

File: src/box/memtx_space.c [hunk 7]
```diff
@@ -550,9 +550,13 @@ memtx_space_execute_upsert(struct space *space, struct txn *txn,
...
 		return -1;
 
-	struct index *index = index_find_unique(space, 0);
+	struct index *index = index_find(space, 0);
 	if (index == NULL)
 		return -1;
+	if (!index->def->opts.is_unique) {
+		diag_set(ClientError, ER_MORE_THAN_ONE_TUPLE);
+		return -1;
+	}
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_space.c:559]: Fixed. 

```diff
--- a/src/box/memtx_space.c
+++ b/src/box/memtx_space.c
@@ -553,10 +553,6 @@ memtx_space_execute_upsert(struct space *space, struct txn *txn,
        struct index *index = index_find(space, 0);
        if (index == NULL)
                return -1;
-       if (!index->def->opts.is_unique) {
-               diag_set(ClientError, ER_MORE_THAN_ONE_TUPLE);
-               return -1;
-       }

        uint32_t part_count = index->def->key_def->part_count;
        size_t region_svp = region_used(&fiber()->gc);
```

File: src/box/key_def.c (hunk 2 above)
Comment (nshy) [reply src/box/key_def.c:1224]: Dropped `mp_key_append_part_count`.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/key_def.c b/src/box/key_def.c
index 29681ab05..e1648d55c 100644
--- a/src/box/key_def.c
+++ b/src/box/key_def.c
@@ -1220,30 +1220,18 @@ key_validate_parts(const struct key_def *key_def, const char *key,
 	return 0;
 }
 
-char *
-mp_key_append_part_count(const char *key, uint32_t part_count, char **end)
+void
+error_set_key_with_part_count(const char *key, uint32_t part_count)
 {
 	const char *key_end = key;
 	for (uint32_t i = 0; i < part_count; i++)
 		mp_next(&key_end);
-	uint32_t prefix_size = mp_sizeof_array(part_count);
-	char *key_buf = (char *)xregion_alloc(&fiber()->gc,
-					      key_end - key + prefix_size);
-	char *key_pos = key_buf;
-	key_pos = (char *)mp_encode_array(key_pos, part_count);
-	memcpy(key_pos, key, key_end - key);
-	*end = key_buf + (key_end - key + prefix_size);
-	return key_buf;
-}
-
-void
-error_set_key_with_part_count(const char *key, uint32_t part_count)
-{
 	size_t region_svp = region_used(&fiber()->gc);
-	char *key_array, *key_array_end;
-	key_array = mp_key_append_part_count(key, part_count,
-					     &key_array_end);
+	size_t key_buf_size = key_end - key + mp_sizeof_array(part_count);
+	char *key_buf = (char *)xregion_alloc(&fiber()->gc, key_buf_size);
+	char * key_pos = (char *)mp_encode_array(key_buf, part_count);
+	memcpy(key_pos, key, key_end - key);
 	struct error *e = diag_last_error(diag_get());
-	error_set_mp(e, "key", key_array, key_array_end - key_array);
+	error_set_mp(e, "key", key_buf, key_buf_size);
 	region_truncate(&fiber()->gc, region_svp);
 }
diff --git a/src/box/key_def.h b/src/box/key_def.h
index 03b38fb3b..c41f2303a 100644
--- a/src/box/key_def.h
+++ b/src/box/key_def.h
@@ -1180,14 +1180,6 @@ key_hint(const char *key, uint32_t part_count, struct key_def *key_def)
 	return key_def->key_hint(key, part_count, key_def);
 }
 
-/**
- * Prepend MsgPack array of part_count size to key. Resulting MsgPack
- * is allocated on fiber region. Return the pointer to the beginning
- * of the result. Pointer to the end is returned in key_end.
- */
-char *
-mp_key_append_part_count(const char *key, uint32_t part_count, char **end);
-
 /**
  * Add key as the last error payload field with name "key". The key
  * is MsgPack array without array prefix. The size of the array

```

</details>

I have to keep `error_set_key_with_part_count` here as it used from vinyl also.

File: src/box/index.cc [hunk 8]
```diff
@@ -146,31 +146,22 @@ key_validate(const struct index_def *index_def, enum iterator_type type,
 }
 
 int
-exact_key_validate(struct key_def *key_def, const char *key,
+exact_key_validate(struct index_def *index_def, const char *key,
```
Comment (locker) [inline src/box/index.cc:154]: Bad commit subject: sounds like this function just drops something unused while in fact it does quite a bit of refactoring. I'd say something like "box: refactor index point lookup validation"

File: src/box/index.cc [hunk 9]
```diff
@@ -686,7 +673,13 @@ iterator_position_validate(const char *pos, uint32_t pos_part_count,
 {
 	int cmp;
 	/* Position must be compatible with the index. */
-	if (exact_key_validate_nullable(cmp_def, pos, pos_part_count) != 0)
+	if (cmp_def->part_count != pos_part_count) {
+		diag_set(ClientError, ER_EXACT_MATCH, cmp_def->part_count,
+			 pos_part_count);
```
Comment (locker) [inline src/box/index.cc:690]: This diag isn't used.

File: changelogs/unreleased/gh-7223-add-more-error-details.md [hunk 10]
```diff
@@ -0,0 +1,3 @@
+## bugfix/box
```
Comment (locker) [inline changelogs/unreleased/gh-7223-add-more-error-details.md:1]: Looks more like a feature, not a bug fix, to me.

File: src/box/session_settings.c [hunk 11]
```diff
@@ -342,14 +342,8 @@ session_settings_space_execute_update(struct space *space, struct txn *txn,
 
 	const char *new_key, *key = request->key;
 	uint32_t new_size, new_key_len, key_len = mp_decode_array(&key);
-	if (key_len == 0) {
-		diag_set(ClientError, ER_EXACT_MATCH, 1, 0);
+	if (exact_key_validate(pk_def, key, key_len) != 0)
```
Comment (locker) [inline src/box/session_settings.c:345]: This should be done in the previous patch.

File: test/box-luatest/error_subsystem_improvements_test.lua [hunk 12]
```diff
@@ -449,3 +449,191 @@ g.test_error_name = function()
...
+                      '(expected 1, got 2)'
+        }, space.update, space, {1, 2}, {'=', 'value', true})
+        t.assert_error_covers({
+            space = '_session_settings',
+            index = 'primary',
+            space_id = space.id,
+            index_id = index.id,
+            key = {1},
+            message = 'Supplied key type of part 0 does not match index ' ..
+                      'part type: expected string'
```
Comment (locker) [inline test/box-luatest/error_subsystem_improvements_test.lua:628]: What about invalid tuple errors on DML? Are there any plans to fix those?

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/vinyl.c (hunk 4 above)
Comment (locker) [reply src/box/vinyl.c:1720]: This is unexpected. I don't understand why this happens. Please investigate.

File: src/box/index.cc (hunk 8 above)
Comment (nshy) [reply src/box/index.cc:154]: Done.

File: src/box/index.cc (hunk 9 above)
Comment (nshy) [reply src/box/index.cc:690]: Fixed.

```diff
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -673,11 +673,8 @@ iterator_position_validate(const char *pos, uint32_t pos_part_co>
 {
        int cmp;
        /* Position must be compatible with the index. */
-       if (cmp_def->part_count != pos_part_count) {
-               diag_set(ClientError, ER_EXACT_MATCH, cmp_def->part_count,
-                        pos_part_count);
+       if (cmp_def->part_count != pos_part_count)
                goto fail;
-       }
        const char *pos_end;
        if (key_validate_parts(cmp_def, pos, pos_part_count, true, &pos_end) != 0)
                goto fail;
```

File: src/box/vinyl.c (hunk 4 above)
Comment (nshy) [reply src/box/vinyl.c:1720]: You are right. I used `cmp_def` to get this error which is incorrect.

File: changelogs/unreleased/gh-7223-add-more-error-details.md (hunk 10 above)
Comment (nshy) [reply changelogs/unreleased/gh-7223-add-more-error-details.md:1]: Decided to keep as bugfix after f2f discussion.

File: src/box/errcode.h [hunk 13]
```diff
@@ -234,7 +234,7 @@ struct errcode_record {
 	_(ER_PRIV_NOT_GRANTED, 91,		"User '%s' does not have %s access on %s '%s'", "user", STRING, "privilege", STRING, "object_type", STRING, "object", STRING) \
 	_(ER_ROLE_NOT_GRANTED, 92,		"User '%s' does not have role '%s'", "user", STRING, "role", STRING) \
 	_(ER_MISSING_SNAPSHOT, 93,		"Can't find snapshot") \
-	_(ER_CANT_UPDATE_PRIMARY_KEY, 94,	"Attempt to modify a tuple field which is part of primary index in space '%s'", "space", STRING) \
+	_(ER_CANT_UPDATE_PRIMARY_KEY, 94,	"Attempt to modify a tuple field which is part of primary index in space '%s'", "space", STRING, "index", STRING, "old_tuple", TUPLE, "new_tuple", TUPLE) \
```
Comment (locker) [inline src/box/errcode.h:237]: It'd be nice to store space and index ids in this error as well - for consistency with other errors.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/index.cc [hunk 14]
```diff
@@ -74,10 +74,45 @@ BuildUnsupportedIndexFeature(const char *file, unsigned line,
 	}
 }
 
+/**
+ * Add key as the last error payload field with name "key". The key
+ * is MsgPack array without array prefix. The size of the array
+ * is given by part_count.
+ */
+static void
+error_set_key_with_part_count(const char *key, uint32_t part_count)
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/index.cc:83]: Fixed.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/index.cc b/src/box/index.cc
index 01c9bdc6b..cdcc7c094 100644
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -80,7 +80,7 @@ BuildUnsupportedIndexFeature(const char *file, unsigned line,
  * is given by part_count.
  */
 static void
-error_set_key_with_part_count(const char *key, uint32_t part_count)
+error_set_key(struct error *error, const char *key, uint32_t part_count)
 {
 	const char *key_end = key;
 	for (uint32_t i = 0; i < part_count; i++)
@@ -90,22 +90,19 @@ error_set_key_with_part_count(const char *key, uint32_t part_count)
 	char *key_buf = (char *)xregion_alloc(&fiber()->gc, key_buf_size);
 	char *key_pos = (char *)mp_encode_array(key_buf, part_count);
 	memcpy(key_pos, key, key_end - key);
-	struct error *e = diag_last_error(diag_get());
-	error_set_mp(e, "key", key_buf, key_buf_size);
+	error_set_mp(error, "key", key_buf, key_buf_size);
 	region_truncate(&fiber()->gc, region_svp);
 }
 
 void
-error_set_index(const struct index_def *index_def)
+error_set_index(struct error *error, const struct index_def *index_def)
 {
-	struct error *e = diag_last_error(diag_get());
-	assert(e != NULL);
-	error_set_str(e, "index", index_def->name);
-	error_set_uint(e, "index_id", index_def->iid);
+	error_set_str(error, "index", index_def->name);
+	error_set_uint(error, "index_id", index_def->iid);
 	struct space *space = space_by_id(index_def->space_id);
 	if (space != NULL)
-		error_set_str(e, "space", space->def->name);
-	error_set_uint(e, "space_id", index_def->space_id);
+		error_set_str(error, "space", space->def->name);
+	error_set_uint(error, "space_id", index_def->space_id);
 }
 
 int
@@ -179,8 +176,8 @@ key_validate(const struct index_def *index_def, enum iterator_type type,
 	}
 	return 0;
 error:
-	error_set_index(index_def);
-	error_set_key_with_part_count(key_begin, part_count);
+	error_set_index(diag_last_error(diag_get()), index_def);
+	error_set_key(diag_last_error(diag_get()), key_begin, part_count);
 	return -1;
 }
 
@@ -192,7 +189,7 @@ exact_key_validate(struct index_def *index_def, const char *key,
 	struct key_def *key_def = index_def->key_def;
 	if (!index_def->opts.is_unique) {
 		diag_set(ClientError, ER_MORE_THAN_ONE_TUPLE);
-		error_set_index(index_def);
+		error_set_index(diag_last_error(diag_get()), index_def);
 		return -1;
 	}
 	if (key_def->part_count != part_count) {
@@ -205,8 +202,8 @@ exact_key_validate(struct index_def *index_def, const char *key,
 		goto error;
 	return 0;
 error:
-	error_set_key_with_part_count(key, part_count);
-	error_set_index(index_def);
+	error_set_key(diag_last_error(diag_get()), key, part_count);
+	error_set_index(diag_last_error(diag_get()), index_def);
 	return -1;
 }
 
diff --git a/src/box/index.h b/src/box/index.h
index 0132c4d3c..266e56ca9 100644
--- a/src/box/index.h
+++ b/src/box/index.h
@@ -773,9 +773,9 @@ replace_check_dup(struct space *space, struct index *index,
 		  struct tuple *old_tuple, struct tuple *new_tuple,
 		  struct tuple *dup_tuple, enum dup_replace_mode mode);
 
-/** Add payload fields with index details to the last error. */
+/** Add payload fields with index details to the error. */
 void
-error_set_index(const struct index_def *index_def);
+error_set_index(struct error *error, const struct index_def *index_def);
 
 /**
  * Initialize an index instance.
diff --git a/src/box/memtx_space.c b/src/box/memtx_space.c
index 3186f5aba..47e973fdf 100644
--- a/src/box/memtx_space.c
+++ b/src/box/memtx_space.c
@@ -437,7 +437,7 @@ memtx_space_execute_replace(struct space *space, struct txn *txn,
 		space->format->vtab.tuple_new(space->format, request->tuple,
 					      request->tuple_end);
 	if (new_tuple == NULL) {
-		error_set_space(space->def);
+		error_set_space(diag_last_error(diag_get()), space->def);
 		return -1;
 	}
 	tuple_ref(new_tuple);
@@ -521,7 +521,7 @@ memtx_space_execute_update(struct space *space, struct txn *txn,
 				    old_data, old_data + bsize, format,
 				    &new_size, request->index_base, NULL);
 	if (new_data == NULL) {
-		error_set_index(pk->def);
+		error_set_index(diag_last_error(diag_get()), pk->def);
 		return -1;
 	}
 
@@ -530,7 +530,7 @@ memtx_space_execute_update(struct space *space, struct txn *txn,
 					      new_data + new_size);
 	region_truncate(&fiber()->gc, region_svp);
 	if (new_tuple == NULL) {
-		error_set_index(pk->def);
+		error_set_index(diag_last_error(diag_get()), pk->def);
 		return -1;
 	}
 	tuple_ref(new_tuple);
@@ -554,7 +554,7 @@ memtx_space_execute_upsert(struct space *space, struct txn *txn,
 	 * malformed tuple even if upsert turns into an update.
 	 */
 	if (tuple_validate_raw(space->format, request->tuple)) {
-		error_set_space(space->def);
+		error_set_space(diag_last_error(diag_get()), space->def);
 		return -1;
 	}
 
@@ -602,7 +602,8 @@ memtx_space_execute_upsert(struct space *space, struct txn *txn,
 		 */
 		if (xrow_update_check_ops(request->ops, request->ops_end,
 					  format, request->index_base) != 0) {
-			error_set_space(space->def);
+			error_set_space(diag_last_error(diag_get()),
+					space->def);
 			return -1;
 		}
 		new_tuple =
@@ -632,7 +633,8 @@ memtx_space_execute_upsert(struct space *space, struct txn *txn,
 					    request->index_base, false,
 					    &column_mask);
 		if (new_data == NULL) {
-			error_set_space(space->def);
+			error_set_space(diag_last_error(diag_get()),
+					space->def);
 			return -1;
 		}
 
@@ -641,7 +643,8 @@ memtx_space_execute_upsert(struct space *space, struct txn *txn,
 						      new_data + new_size);
 		region_truncate(&fiber()->gc, region_svp);
 		if (new_tuple == NULL) {
-			error_set_space(space->def);
+			error_set_space(diag_last_error(diag_get()),
+					space->def);
 			return -1;
 		}
 		tuple_ref(new_tuple);
diff --git a/src/box/session_settings.c b/src/box/session_settings.c
index e8334ee77..d94a9470c 100644
--- a/src/box/session_settings.c
+++ b/src/box/session_settings.c
@@ -357,7 +357,7 @@ session_settings_space_execute_update(struct space *space, struct txn *txn,
 				       &new_size, request->index_base,
 				       &column_mask);
 	if (new_data == NULL) {
-		error_set_index(pk_def);
+		error_set_index(diag_last_error(diag_get()), pk_def);
 		goto finish;
 	}
 	*result = box_tuple_new(format, new_data, new_data + new_size);
diff --git a/src/box/space.c b/src/box/space.c
index c2e7b8cde..c6131643b 100644
--- a/src/box/space.c
+++ b/src/box/space.c
@@ -1143,7 +1143,8 @@ after_old_tuple_lookup:;
 					       space->format, &new_size,
 					       request->index_base, NULL);
 		if (new_data == NULL) {
-			error_set_index(index->def);
+			error_set_index(diag_last_error(diag_get()),
+					index->def);
 			return -1;
 		}
 		new_data_end = new_data + new_size;
@@ -1168,7 +1169,8 @@ after_old_tuple_lookup:;
 						  request->ops_end,
 						  space->format,
 						  request->index_base) != 0) {
-				error_set_space(space->def);
+				error_set_space(diag_last_error(diag_get()),
+						space->def);
 				return -1;
 			}
 			break;
@@ -1181,7 +1183,8 @@ after_old_tuple_lookup:;
 					       request->index_base, false,
 					       NULL);
 		if (new_data == NULL) {
-			error_set_space(space->def);
+			error_set_space(diag_last_error(diag_get()),
+					space->def);
 			return -1;
 		}
 		new_data_end = new_data + new_size;
diff --git a/src/box/space.h b/src/box/space.h
index e38221179..00e2c0658 100644
--- a/src/box/space.h
+++ b/src/box/space.h
@@ -746,14 +746,12 @@ space_dump_def(const struct space *space, struct rlist *key_list);
 void
 space_fill_index_map(struct space *space);
 
-/** Add info about space to error. */
+/** Add info about space to the error. */
 static inline void
-error_set_space(struct space_def *def)
+error_set_space(struct error *error, struct space_def *def)
 {
-	struct error *e = diag_last_error(diag_get());
-	assert(e != NULL);
-	error_set_str(e, "space", def->name);
-	error_set_uint(e, "space_id", def->id);
+	error_set_str(error, "space", def->name);
+	error_set_uint(error, "space_id", def->id);
 }
 
 /*
diff --git a/src/box/vinyl.c b/src/box/vinyl.c
index 589d802bb..6cc09d217 100644
--- a/src/box/vinyl.c
+++ b/src/box/vinyl.c
@@ -1901,7 +1901,7 @@ vy_update(struct vy_env *env, struct vy_tx *tx, struct txn_stmt *stmt,
 					pk->mem_format, &new_size,
 					request->index_base, &column_mask);
 	if (new_tuple == NULL) {
-		error_set_index(pk->base.def);
+		error_set_index(diag_last_error(diag_get()), pk->base.def);
 		return -1;
 	}
 	new_tuple_end = new_tuple + new_size;
@@ -1911,7 +1911,7 @@ vy_update(struct vy_env *env, struct vy_tx *tx, struct txn_stmt *stmt,
 	 */
 	if (tuple_validate_raw(pk->mem_format, new_tuple)) {
 		region_truncate(&fiber()->gc, region_svp);
-		error_set_index(pk->base.def);
+		error_set_index(diag_last_error(diag_get()), pk->base.def);
 		return -1;
 	}
 	stmt->new_tuple = vy_stmt_new_replace(pk->mem_format, new_tuple,
@@ -2100,7 +2100,7 @@ vy_upsert(struct vy_env *env, struct vy_tx *tx, struct txn_stmt *stmt,
 	/* Check update operations. */
 	if (xrow_update_check_ops(request->ops, request->ops_end,
 				  pk->mem_format, request->index_base) != 0) {
-		error_set_space(space->def);
+		error_set_space(diag_last_error(diag_get()), space->def);
 		return -1;
 	}
 	if (request->index_base != 0) {
@@ -2215,7 +2215,7 @@ vy_insert(struct vy_env *env, struct vy_tx *tx, struct txn_stmt *stmt,
 	if (vy_is_committed(env, pk))
 		return 0;
 	if (tuple_validate_raw(pk->mem_format, request->tuple)) {
-		error_set_space(space->def);
+		error_set_space(diag_last_error(diag_get()), space->def);
 		return -1;
 	}
 	/* First insert into the primary index. */
@@ -2266,7 +2266,7 @@ vy_replace(struct vy_env *env, struct vy_tx *tx, struct txn_stmt *stmt,
 
 	/* Validate and create a statement for the new tuple. */
 	if (tuple_validate_raw(pk->mem_format, request->tuple)) {
-		error_set_space(space->def);
+		error_set_space(diag_last_error(diag_get()), space->def);
 		return -1;
 	}
 	stmt->new_tuple = vy_stmt_new_replace(pk->mem_format, request->tuple,

```

</details>

File: src/box/index.cc [hunk 15]
```diff
@@ -74,10 +74,45 @@ BuildUnsupportedIndexFeature(const char *file, unsigned line,
...
+void
+error_set_index(const struct index_def *index_def)
+{
+	struct error *e = diag_last_error(diag_get());
+	assert(e != NULL);
+	error_set_str(e, "index", index_def->name);
+	error_set_uint(e, "index_id", index_def->iid);
+	struct space *space = space_by_id(index_def->space_id);
+	if (space != NULL)
+		error_set_str(e, "space", space->def->name);
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/index.cc:107]: Fixed.

```diff
diff --git a/src/box/index.cc b/src/box/index.cc
index cdcc7c094..d11e58de1 100644
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -100,8 +100,7 @@ error_set_index(struct error *error, const struct index_def *inde>
        error_set_str(error, "index", index_def->name);
        error_set_uint(error, "index_id", index_def->iid);
        struct space *space = space_by_id(index_def->space_id);
-       if (space != NULL)
-               error_set_str(error, "space", space->def->name);
+       error_set_str(error, "space", space->def->name);
        error_set_uint(error, "space_id", index_def->space_id);
 }
```

File: src/box/index.cc [hunk 16]
```diff
@@ -210,6 +210,48 @@ exact_key_validate(struct index_def *index_def, const char *key,
...
+	(void)new_tuple;
+	if (dup_tuple == NULL) {
+		if (mode == DUP_REPLACE) {
+			assert(old_tuple != NULL);
+			/*
+			 * dup_replace_mode is DUP_REPLACE, and
+			 * a tuple with the same key is not found.
+			 */
+			if (space == NULL)
+				space = space_by_id(index->def->space_id);
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/index.cc:227]: Fixed.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/index.cc b/src/box/index.cc
index 68baec8bf..d2f2cb5e6 100644
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -207,11 +207,10 @@ exact_key_validate(struct index_def *index_def, const char *key,
 }
 
 int
-replace_check_dup(struct space *space, struct index *index,
-		  struct tuple *old_tuple, struct tuple *new_tuple,
-		  struct tuple *dup_tuple, enum dup_replace_mode mode)
+index_check_dup(struct index *index, struct tuple *old_tuple,
+		struct tuple *new_tuple, struct tuple *dup_tuple,
+		enum dup_replace_mode mode)
 {
-	(void)new_tuple;
 	if (dup_tuple == NULL) {
 		if (mode == DUP_REPLACE) {
 			assert(old_tuple != NULL);
@@ -219,8 +218,7 @@ replace_check_dup(struct space *space, struct index *index,
 			 * dup_replace_mode is DUP_REPLACE, and
 			 * a tuple with the same key is not found.
 			 */
-			if (space == NULL)
-				space = space_by_id(index->def->space_id);
+			struct space *space = space_by_id(index->def->space_id);
 			assert(space != NULL);
 			diag_set(ClientError, ER_CANT_UPDATE_PRIMARY_KEY,
 				 space->def->name);
@@ -235,8 +233,7 @@ replace_check_dup(struct space *space, struct index *index,
 			 * possibly delete more than one tuple
 			 * at once.
 			 */
-			if (space == NULL)
-				space = space_by_id(index->def->space_id);
+			struct space *space = space_by_id(index->def->space_id);
 			assert(space != NULL);
 			diag_set(ClientError, ER_TUPLE_FOUND,
 				 index->def->name, space->def->name,
diff --git a/src/box/index.h b/src/box/index.h
index 266e56ca9..e281ec52c 100644
--- a/src/box/index.h
+++ b/src/box/index.h
@@ -769,9 +769,9 @@ struct index_read_view_iterator {
  * Return 0 on success, -1 on error (diag is set).
  */
 int
-replace_check_dup(struct space *space, struct index *index,
-		  struct tuple *old_tuple, struct tuple *new_tuple,
-		  struct tuple *dup_tuple, enum dup_replace_mode mode);
+index_check_dup(struct index *index, struct tuple *old_tuple,
+		struct tuple *new_tuple, struct tuple *dup_tuple,
+		enum dup_replace_mode mode);
 
 /** Add payload fields with index details to the error. */
 void
diff --git a/src/box/memtx_hash.cc b/src/box/memtx_hash.cc
index 6c0103e95..1ba131523 100644
--- a/src/box/memtx_hash.cc
+++ b/src/box/memtx_hash.cc
@@ -386,8 +386,8 @@ memtx_hash_index_replace(struct index *base, struct tuple *old_tuple,
 				 "hash_table", "key");
 			return -1;
 		}
-		if (replace_check_dup(NULL, base, old_tuple, new_tuple,
-				      dup_tuple, mode) != 0) {
+		if (index_check_dup(base, old_tuple, new_tuple,
+				    dup_tuple, mode) != 0) {
 			light_index_delete(hash_table, pos);
 			if (dup_tuple) {
 				uint32_t pos = light_index_insert(hash_table, h, dup_tuple);
diff --git a/src/box/memtx_tree.cc b/src/box/memtx_tree.cc
index 9b17104b3..1e6716d75 100644
--- a/src/box/memtx_tree.cc
+++ b/src/box/memtx_tree.cc
@@ -1148,8 +1148,8 @@ memtx_tree_index_replace(struct index *base, struct tuple *old_tuple,
 			return -1;
 		}
 
-		if (replace_check_dup(NULL, base, old_tuple, new_tuple,
-				      dup_data.tuple, mode) != 0) {
+		if (index_check_dup(base, old_tuple, new_tuple,
+				    dup_data.tuple, mode) != 0) {
 			memtx_tree_delete(&index->tree, new_data);
 			if (dup_data.tuple != NULL)
 				memtx_tree_insert(&index->tree, dup_data, NULL, NULL);
@@ -1204,8 +1204,8 @@ memtx_tree_index_replace_multikey_one(struct memtx_tree_index<true> *index,
 		 * out of the index.
 		 */
 		*is_multikey_conflict = true;
-	} else if (replace_check_dup(NULL, &index->base, old_tuple, new_tuple,
-				     dup_data.tuple, mode) != 0) {
+	} else if (index_check_dup(&index->base, old_tuple, new_tuple,
+				   dup_data.tuple, mode) != 0) {
 		/* Rollback replace. */
 		memtx_tree_delete(&index->tree, new_data);
 		if (dup_data.tuple != NULL)
diff --git a/src/box/memtx_tx.c b/src/box/memtx_tx.c
index 598915efe..ac6eda5d5 100644
--- a/src/box/memtx_tx.c
+++ b/src/box/memtx_tx.c
@@ -1791,8 +1791,8 @@ check_dup(struct txn_stmt *stmt, struct tuple *new_tuple,
 						  is_own_change);
 	}
 
-	if (replace_check_dup(space, space->index[0], *old_tuple, new_tuple,
-			      visible_replaced, mode) != 0) {
+	if (index_check_dup(space->index[0], *old_tuple, new_tuple,
+			    visible_replaced, mode) != 0) {
 		memtx_tx_track_read(txn, space, visible_replaced);
 		return -1;
 	}
@@ -1822,8 +1822,8 @@ check_dup(struct txn_stmt *stmt, struct tuple *new_tuple,
 							  &unused);
 		}
 
-		if (replace_check_dup(space, space->index[i], visible_replaced,
-				      new_tuple, visible, DUP_INSERT) != 0) {
+		if (index_check_dup(space->index[i], visible_replaced,
+				    new_tuple, visible, DUP_INSERT) != 0) {
 			memtx_tx_track_read(txn, space, visible);
 			return -1;
 		}
```

</details>

File: src/box/errcode.h (hunk 13 above)
Comment (nshy) [reply src/box/errcode.h:237]: Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/errcode.h b/src/box/errcode.h
index 70e9f282d..aec1bc82c 100644
--- a/src/box/errcode.h
+++ b/src/box/errcode.h
@@ -234,7 +234,7 @@ struct errcode_record {
 	_(ER_PRIV_NOT_GRANTED, 91,		"User '%s' does not have %s access on %s '%s'", "user", STRING, "privilege", STRING, "object_type", STRING, "object", STRING) \
 	_(ER_ROLE_NOT_GRANTED, 92,		"User '%s' does not have role '%s'", "user", STRING, "role", STRING) \
 	_(ER_MISSING_SNAPSHOT, 93,		"Can't find snapshot") \
-	_(ER_CANT_UPDATE_PRIMARY_KEY, 94,	"Attempt to modify a tuple field which is part of primary index in space '%s'", "space", STRING, "index", STRING, "old_tuple", TUPLE, "new_tuple", TUPLE) \
+	_(ER_CANT_UPDATE_PRIMARY_KEY, 94,	"Attempt to modify a tuple field which is part of primary index in space '%s'", "space", STRING, "space_id", UINT, "index", STRING, "index_id", UINT, "old_tuple", TUPLE, "new_tuple", TUPLE) \
 	_(ER_UPDATE_INTEGER_OVERFLOW, 95,	"Integer overflow when performing '%c' operation on field %s", "operation", CHAR, "field", STRING) \
 	_(ER_GUEST_USER_PASSWORD, 96,		"Setting password for guest user has no effect") \
 	_(ER_TRANSACTION_CONFLICT, 97,		"Transaction has been aborted by conflict") \
diff --git a/src/box/index.cc b/src/box/index.cc
index 96a8e0d8b..438f5f5ef 100644
--- a/src/box/index.cc
+++ b/src/box/index.cc
@@ -221,7 +221,8 @@ index_check_dup(struct index *index, struct tuple *old_tuple,
 			struct space *space = space_by_id(index->def->space_id);
 			assert(space != NULL);
 			diag_set(ClientError, ER_CANT_UPDATE_PRIMARY_KEY,
-				 space->def->name, index->def->name,
+				 space->def->name, space->def->id,
+				 index->def->name, index->def->iid,
 				 old_tuple, new_tuple);
 			return -1;
 		}
diff --git a/src/box/memtx_space.c b/src/box/memtx_space.c
index 47e973fdf..613b8f27e 100644
--- a/src/box/memtx_space.c
+++ b/src/box/memtx_space.c
@@ -656,7 +656,8 @@ memtx_space_execute_upsert(struct space *space, struct txn *txn,
 				  HINT_NONE, pk->def->key_def) != 0) {
 			/* Primary key is changed: log error and do nothing. */
 			diag_set(ClientError, ER_CANT_UPDATE_PRIMARY_KEY,
-				 space_name(space), pk->def->name,
+				 space_name(space), space_id(space),
+				 pk->def->name, pk->def->iid,
 				 old_tuple, new_tuple);
 			diag_log();
 			tuple_unref(new_tuple);
diff --git a/src/box/session_settings.c b/src/box/session_settings.c
index d94a9470c..420145ff7 100644
--- a/src/box/session_settings.c
+++ b/src/box/session_settings.c
@@ -373,8 +373,8 @@ session_settings_space_execute_update(struct space *space, struct txn *txn,
 			struct tuple *old_tuple =
 				tuple_new(format, old_data, old_data_end);
 			diag_set(ClientError, ER_CANT_UPDATE_PRIMARY_KEY,
-				 space_name(space), pk_def->name,
-				 old_tuple, *result);
+				 space_name(space), space_id(space),
+				 pk_def->name, pk_def->iid, old_tuple, *result);
 			tuple_delete(old_tuple);
 			goto finish;
 		}
diff --git a/src/box/space.c b/src/box/space.c
index c6131643b..a1c793565 100644
--- a/src/box/space.c
+++ b/src/box/space.c
@@ -1284,8 +1284,8 @@ after_old_tuple_lookup:;
 	    tuple_compare(old_tuple, HINT_NONE, new_tuple, HINT_NONE,
 			  pk->def->key_def) != 0) {
 		diag_set(ClientError, ER_CANT_UPDATE_PRIMARY_KEY,
-			 space->def->name, index->def->name,
-			 old_tuple, new_tuple);
+			 space->def->name, space->def->id, index->def->name,
+			 index->def->iid, old_tuple, new_tuple);
 		rc = -1;
 		goto out;
 	}
diff --git a/src/box/vinyl.c b/src/box/vinyl.c
index 6cc09d217..c875a2773 100644
--- a/src/box/vinyl.c
+++ b/src/box/vinyl.c
@@ -1798,8 +1798,8 @@ vy_check_update(struct space *space, const struct vy_lsm *pk,
 	    vy_stmt_compare(old_tuple, HINT_NONE, new_tuple,
 			    HINT_NONE, pk->key_def) != 0) {
 		diag_set(ClientError, ER_CANT_UPDATE_PRIMARY_KEY,
-			 space_name(space), pk->base.def->name,
-			 old_tuple, new_tuple);
+			 space_name(space), space_id(space), pk->base.def->name,
+			 pk->base.def->iid, old_tuple, new_tuple);
 		return -1;
 	}
 	return 0;
diff --git a/test/box-luatest/error_subsystem_improvements_test.lua b/test/box-luatest/error_subsystem_improvements_test.lua
index 823a6943d..bbb559fd5 100644
--- a/test/box-luatest/error_subsystem_improvements_test.lua
+++ b/test/box-luatest/error_subsystem_improvements_test.lua
@@ -817,7 +817,9 @@ g.test_dml_update_primary_key = function(cg)
         test:replace({1, 2})
         t.assert_error_covers({
             space = 'test',
+            space_id = test.id,
             index = 'primary',
+            index_id = 0,
             old_tuple = {1, 2},
             new_tuple = {3, 2},
             message = "Attempt to modify a tuple field which is part of " ..
@@ -830,7 +832,9 @@ g.test_dml_update_primary_key = function(cg)
         test:before_replace(update_pk)
         t.assert_error_covers({
             space = 'test',
+            space_id = test.id,
             index = 'primary',
+            index_id = 0,
             old_tuple = {1, 2},
             new_tuple = {2, 3},
             message = "Attempt to modify a tuple field which is part of " ..
@@ -843,7 +847,9 @@ g.test_dml_update_primary_key = function(cg)
         test:replace({1, 2})
         t.assert_error_covers({
             space = 'test',
+            space_id = test.id,
             index = 'primary',
+            index_id = 0,
             old_tuple = {1, 2},
             new_tuple = {3, 2},
             message = "Attempt to modify a tuple field which is part of " ..
@@ -855,7 +861,9 @@ g.test_dml_update_primary_key = function(cg)
         space:update('sql_full_metadata', {{'=', 2, false}})
         t.assert_error_covers({
             space = '_session_settings',
+            space_id = space.id,
             index = 'primary',
+            index_id = 0,
             old_tuple = {'sql_full_metadata', false},
             new_tuple = {'foo', false},
             message = "Attempt to modify a tuple field which is part of " ..
@@ -867,7 +875,9 @@ g.test_dml_update_primary_key = function(cg)
         test:replace({1, 2})
         t.assert_error_covers({
             space = 'test',
+            space_id = test.id,
             index = 'primary',
+            index_id = 0,
             old_tuple = {1, 2},
             new_tuple = {3, 2},
             message = "Attempt to modify a tuple field which is part of " ..

```

</details>

File: src/box/xrow_update.c [hunk 17]
```diff
@@ -363,8 +370,11 @@ xrow_upsert_execute(const char *expr,const char *expr_end,
 	size_t region_svp = region_used(&fiber()->gc);
 
 	if (xrow_update_read_ops(&update, expr, expr_end, format->dict,
-				 field_count) != 0)
+				 field_count) != 0) {
+		struct error *e = diag_last_error(diag_get());
+		error_set_mp(e, "ops", expr, expr_end - expr);
```
Comment (locker) [inline src/box/xrow_update.c:375]: Why are UDPATE and UPSERT handled differently? Why not set the erroneous operations in `xrow_update_read_ops` and `xrow_update_do_ops`?

Comment (nshy) [reply src/box/xrow_update.c:375]: Fixed.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/xrow_update.c b/src/box/xrow_update.c
index c08a98045..92d2c85b1 100644
--- a/src/box/xrow_update.c
+++ b/src/box/xrow_update.c
@@ -106,20 +106,16 @@ xrow_update_read_ops(struct xrow_update *update, const char *expr,
 		     const char *expr_end, struct tuple_dictionary *dict,
 		     int32_t field_count_hint)
 {
-	if (mp_typeof(*expr) != MP_ARRAY) {
-		diag_set(ClientError, ER_ILLEGAL_PARAMS,
-			 "update operations must be an "
-			 "array {{op,..}, {op,..}}");
-		return -1;
-	}
+	const char *expr_begin = expr;
 	uint64_t column_mask = 0;
+	assert(mp_typeof(*expr) == MP_ARRAY);
 	/* number of operations */
 	update->op_count = mp_decode_array(&expr);
 
 	if (update->op_count > BOX_UPDATE_OP_CNT_MAX) {
 		diag_set(ClientError, ER_ILLEGAL_PARAMS,
 			 "too many operations for update");
-		return -1;
+		goto error;
 	}
 
 	if (update->op_count > 0) {
@@ -135,7 +131,7 @@ xrow_update_read_ops(struct xrow_update *update, const char *expr,
 	for (int i = 1; op < ops_end; op++, i++) {
 		if (xrow_update_op_decode(op, i, update->index_base, dict,
 					  &expr) != 0)
-			return -1;
+			goto error;
 		/*
 		 * Continue collecting the changed columns
 		 * only if there are unset bits in the mask.
@@ -223,14 +219,13 @@ xrow_update_read_ops(struct xrow_update *update, const char *expr,
 		}
 	}
 
-	/* Check the remainder length, the request must be fully read. */
-	if (expr != expr_end) {
-		diag_set(ClientError, ER_ILLEGAL_PARAMS,
-			 "can't unpack update operations");
-		return -1;
-	}
+	assert(expr == expr_end);
 	update->column_mask = column_mask;
 	return 0;
+error:
+	struct error *e = diag_last_error(diag_get());
+	error_set_mp(e, "ops", expr_begin, expr_end - expr_begin);
+	return -1;
 }
 
 /**
@@ -319,10 +314,6 @@ xrow_update_check_ops(const char *expr, const char *expr_end,
 	int ret = xrow_update_read_ops(&update, expr, expr_end,
 				       format->dict, 0);
 	region_truncate(&fiber()->gc, region_svp);
-	if (ret != 0) {
-		struct error *e = diag_last_error(diag_get());
-		error_set_mp(e, "ops", expr, expr_end - expr);
-	}
 	return ret;
 }
 
@@ -342,17 +333,18 @@ xrow_update_execute(const char *expr,const char *expr_end,
 				 field_count) != 0)
 		goto error;
 	if (xrow_update_do_ops(&update, header, old_data, old_data_end,
-			       field_count) != 0)
+			       field_count) != 0) {
+		struct error *e = diag_last_error(diag_get());
+		error_set_mp(e, "ops", expr, expr_end - expr);
+		error_set_mp(e, "tuple", header, old_data_end - header);
 		goto error;
+	}
 	if (column_mask)
 		*column_mask = update.column_mask;
 
 	return xrow_update_finish(&update, format, p_tuple_len);
 
-error:;
-	struct error *e = diag_last_error(diag_get());
-	error_set_mp(e, "ops", expr, expr_end - expr);
-	error_set_mp(e, "tuple", header, old_data_end - header);
+error:
 	region_truncate(&fiber()->gc, region_svp);
 	return NULL;
 }
@@ -370,11 +362,8 @@ xrow_upsert_execute(const char *expr,const char *expr_end,
 	size_t region_svp = region_used(&fiber()->gc);
 
 	if (xrow_update_read_ops(&update, expr, expr_end, format->dict,
-				 field_count) != 0) {
-		struct error *e = diag_last_error(diag_get());
-		error_set_mp(e, "ops", expr, expr_end - expr);
+				 field_count) != 0)
 		goto error;
-	}
 	if (xrow_upsert_do_ops(&update, header, old_data, old_data_end,
 			       field_count, suppress_error) != 0)
 		goto error;
diff --git a/test/box-luatest/error_subsystem_improvements_test.lua b/test/box-luatest/error_subsystem_improvements_test.lua
index 7964931ad..c1336e5d1 100644
--- a/test/box-luatest/error_subsystem_improvements_test.lua
+++ b/test/box-luatest/error_subsystem_improvements_test.lua
@@ -903,16 +903,35 @@ g.test_dml_update_error = function(cg)
         local test = box.schema.create_space('test')
         test:create_index('primary')
         test:replace({1, 2})
+        local ops = {}
+        for i = 1,5000 do ops[i] = {'+', 2, 1} end
+        t.assert_error_covers({
+            space = 'test',
+            space_id = test.id,
+            index = 'primary',
+            index_id = 0,
+            ops = ops,
+            message = 'Illegal parameters, too many operations for update'
+        }, test.update, test, {1}, ops)
         t.assert_error_covers({
             space = 'test',
             space_id = test.id,
             index = 'primary',
             index_id = 0,
-            tuple = {1, 2},
             ops = {{'+', 2, 'foo'}},
             message = "Argument type in operation '+' on field 2 does not " ..
                       "match field type: expected a number",
         }, test.update, test, {1}, {{'+', 2, 'foo'}})
+        t.assert_error_covers({
+            space = 'test',
+            space_id = test.id,
+            index = 'primary',
+            index_id = 0,
+            ops = {{':', 2, 2, 1, 'foo'}},
+            tuple = {1, 2},
+            message = "Argument type in operation ':' on field 2 does not " ..
+                      "match field type: expected a string"
+        }, test.update, test, {1}, {{':', 2, 2, 1, 'foo'}})
 
         local dummy = function(_, new) return new end
         test:before_replace(dummy)
@@ -921,7 +940,6 @@ g.test_dml_update_error = function(cg)
             space_id = test.id,
             index = 'primary',
             index_id = 0,
-            tuple = {1, 2},
             ops = {{'+', 2, 'foo'}},
             message = "Argument type in operation '+' on field 2 does not " ..
                       "match field type: expected a number"
@@ -936,7 +954,6 @@ g.test_dml_update_error = function(cg)
             space_id = space.id,
             index = 'primary',
             index_id = 0,
-            tuple = {'sql_full_metadata', false},
             ops = {{'+', 2, 'foo'}},
             message = "Argument type in operation '+' on field 2 does not " ..
                       "match field type: expected a number"
@@ -950,7 +967,6 @@ g.test_dml_update_error = function(cg)
             space_id = test.id,
             index = 'primary',
             index_id = 0,
-            tuple = {1, 2},
             ops = {{'+', 2, 'foo'}},
             message = "Argument type in operation '+' on field 2 does not " ..
                       "match field type: expected a number",

```

**Review by locker — APPROVED** [review]
