### PR TITLE
Lookup openssl certs at tarantool startup

### LINKED ISSUE #5615: Static build: Bundled curl in Tarantool http client does not accept a valid SSL certificate
Tarantool version:
Tarantool Enterprise 2.3.1-143-g8124538 (corresponds to 2.3.2-0-gcb25c5473)
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type

OS version:
CentOS Linux release 8.2.2004 (Core)

Bug description:
When connecting to a valid HTTPS endpoint, HTTP client Tarantool returns a certificate validation error, when a system curl connects to it without issues.

Steps to reproduce:

The endpoint: https://gw-nalp.x5.ru/agreements-dmz-stage/api/v2/agreements

image

System curl runs without errors (full list of command arguments is omitted):

```
curl --location --request POST 'https://gw-nalp.x5.ru/agreements-dmz-stage/api/v2/agreements' --data '{ ... } --verbose'

About to connect() to gw-nalp.x5.ru port 443 (#0)
*   Trying 193.232.108.67...
* Connected to gw-nalp.x5.ru (193.232.108.67) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*  subject: CN=*.x5.ru,O=OOO Korporativnyy centr IKS 5,L=Moscow,C=RU
*  start date: Aug 12 00:00:00 2020 GMT
*  expire date: Aug 17 12:00:00 2022 GMT
*  common name: *.x5.ru
*  issuer: CN=GeoTrust RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US
> POST /agreements-dmz-stage/api/v2/agreements HTTP/1.1
> User-Agent: curl/7.29.0
> Host: gw-nalp.x5.ru
> Accept: */*
> Content-Type: application/json
> Content-Length: 473
> 
* upload completely sent off: 473 out of 473 bytes
< HTTP/1.1 201 Created
< Date: Thu, 10 Dec 2020 10:14:57 GMT
< Content-Type: application/json
< Allow: POST, OPTIONS
< X-Frame-Options: DENY
< Vary: Cookie
< X-Content-Type-Options: nosniff
< Transfer-Encoding: chunked
<
```

HTTP client in Tarantool returns an error:

```yaml
tarantool> http_client = require('http.client').new({max_connections = 5})
tarantool> http_client:get('https://gw-nalp.x5.ru/agreements-dmz-stage/api/v2/agreements', {verbose = true})
*   Trying 193.232.108.67:443...
* TCP_NODELAY set
* Connected to gw-nalp.x5.ru (193.232.108.67) port 443 (#0)
* ALPN, offering http/1.1
* SSL certificate problem: self signed certificate in certificate chain
* Closing connection 0
---
- status: 495
  reason: SSL peer certificate or SSH remote key was not OK
...
```

Optional (but very desirable):
* coredump
* backtrace
* netstat

### PR DESCRIPTION
**Pull request by HustonMmmavr**
The static build isn't as portable as it should be. In fact, the OPENSSLDIR is configured at build time, but in runtime, it may (and do) differ:

```
$ strace tarantool -e 'require("http.client").get("https://...")'
...
openat(AT_FDCWD, "/__w/sdk/sdk/build/tarantool/static-build/"
                 "openssl-prefix/ssl/cert.pem", O_RDONLY) =
                 -1 ENOENT (No such file or directory)
...
stat("/__w/sdk/sdk/build/tarantool/static-build/"
     "openssl-prefix/ssl/certs/...", ...) =
     -1 ENOENT (No such file or directory)
...
```

As a result, statically build tarantool can't open some https links with an error:

```
tarantool> http_client = require('http.client').new({max_connections = 5})
tarantool> http_client:get('https://..../', {verbose = true})
*   Trying X.Y.Z.W:443...
* TCP_NODELAY set
* Connected to .... (X.Y.Z.W) port 443 (#0)
* ALPN, offering http/1.1
* SSL certificate problem: self signed certificate in certificate chain
* Closing connection 0
---
- status: 495
  reason: SSL peer certificate or SSH remote key was not OK
...
```

Also this error may occur at dynamically build tarantool in case of linkage tarantool binary with incorrectly configured openssl.

In this patch, we adopt the approach from the golang ecosystem [1-3]. At startup, tarantool scans several popular locations and uses it for `SSL_CERT_DIR` and/or `SSL_CERT_FILE` setting. See also [4,5] - it's fun.

[1] https://serverfault.com/a/722646
[2] https://golang.org/src/crypto/x509/root_unix.go
[3] https://golang.org/src/crypto/x509/root_linux.go
[4] https://github.com/edenhill/librdkafka/blob/cb69d2a8486344252e0fcaa1f959c4ab2d8afff3/src/rdkafka_ssl.c#L845
[5] https://www.happyassassin.net/posts/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

Close #5615

Co-authored-by: Yaroslav Dynnikov <yaroslav.dynnikov@gmail.com>

@Changelog

Misc: Lookup openssl certs at tarantool startup and set them if there is no user defined certs (gh-5615)

### CODE REVIEW

**Review by ligurio — CHANGES_REQUESTED** [review]
Thanks for the patches!

Please squash commits to a single one. No sense to keep code style changes for files added in a previous commit in a separate commit.

In commit message you describe a problem with finding openssl config, but commit fixes search paths for certificates. Why? `openssl.cnf` may contains not only certificate's search paths but other settings too, like used crypto algorithms, see [1]. 

Typo: `SSL_SERT_FILE` -> `SSL_CERT_FILE`

It's worth to mention these changes in changelog.

1. https://www.openssl.org/docs/manmaster/man5/config.html

File: src/ssl_cert_paths_discover.c [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+ * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+ * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
+ * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
+ * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+ * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
+ * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
+ * SUCH DAMAGE.
+ */
+
+#include <stdio.h>
```
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c:32]: sprintf was used from stdio,h [there](https://github.com/tarantool/tarantool/blob/56c35b1d54298227a4bb0306c2008e923e923d27/src/ssl_cert_paths_discover.c#L123)

File: src/ssl_cert_paths_discover.c [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+	/* Debian/Ubuntu/Gentoo etc. (OpenSuse) */
+	"/etc/ssl/certs",
+	/* FreeBSD */
+	"/usr/local/share/certs",
+	/* NetBSD */
+	"/etc/openssl/certs",
+	/* macOS */
+	"/private/etc/ssl/certs",
+	"/usr/local/etc/openssl@1.1/certs",
+	"/usr/local/etc/openssl@1.0/certs",
```
Comment (ligurio) [inline src/ssl_cert_paths_discover.c:76]: I see some downsides of hardcoding these paths:
1. Imagine you have your own ca certificate that you cannot place to a system file. How you would use it with Tarantool?
2. For each release we will need to review these paths and update for new operating systems releases and remove old ones.

Have you reviewed approaches in other opensource projects?
I found source code and documentation in curl and Fossil SCM that solves similar problems:
Fossil SCM [1] (they use environment variables) and curl that allows to specify a path to file with CA certificates. Also curl allows to ignore certificate chain check and make connection insecure.

1. https://github.com/curl/curl/tree/master/lib/vtls
2. https://curl.se/docs/sslcerts.html
3. https://www.fossil-scm.org/home/file?name=src/http_ssl.c&ci=trunk

File: src/ssl_cert_paths_discover.c [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+	"/usr/local/etc/openssl/certs",
+	NULL
+};
+
+const char *DEFAULT_CERT_FILE_PATHS[] = {
+	/* Fedora/RHEL 6 */
+	"/etc/pki/tls/certs/ca-bundle.crt",
+	/* CentOS/RHEL 7 */
```
Comment (ligurio) [inline src/ssl_cert_paths_discover.c:84]: What's about CentOS/RHEL 8?

**Review by ligurio — CHANGES_REQUESTED** [review]
Thanks for the patches!

I don't know why, but some comment from a previous review were ignored.
So I'll repeat them here:
- In commit message you describe a problem with finding openssl config, but commit fixes search paths for certificates. Why? openssl.cnf may contains not only certificate's search paths but other settings too, like used crypto algorithms, see [1].
- It's worth to mention these changes in changelog.

File: src/main.cc [hunk 4]
```diff
@@ -710,6 +711,7 @@ main(int argc, char **argv)
 	memtx_tx_manager_init();
 	crypto_init();
 	systemd_init();
+	ssl_cert_paths_discover(0); // don't overwrite user defined env vars
```
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/main.cc]: Fixed

File: src/ssl_cert_paths_discover.c [hunk 5]
```diff
@@ -0,0 +1,144 @@
...
+		"/etc/openssl/certs",
+		/* macOS */
+		"/private/etc/ssl/certs",
+		"/usr/local/etc/openssl@1.1/certs",
+		"/usr/local/etc/openssl@1.0/certs",
+		"/usr/local/etc/openssl/certs",
+		NULL
+	};
+	return default_cert_dir_paths;
+}
```
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Unwrapped

File: src/ssl_cert_paths_discover.c [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+		/* FreeBSD */
+		"/usr/local/share/certs/ca-root-nss.crt",
+		/* macOS */
+		"/private/etc/ssl/cert.pem",
+		"/usr/local/etc/openssl@1.1/cert.pem",
+		"/usr/local/etc/openssl@1.0/cert.pem",
+		NULL
+	};
+	return default_cert_file_paths;
+}
```
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Unwrapped

File: src/ssl_cert_paths_discover.c [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+void
+ssl_cert_paths_discover(int overwrite)
+{
+	char *cert_dirs = tt_static_buf();
+	char *cert_dirs_end = cert_dirs;
+
+	const char *path = NULL;
+	const char **default_dir_paths = get_default_cert_dir_paths();
+	for (int i = 0; (path = default_dir_paths[i]); i++) {
+		struct stat sb;
```
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Fixed

File: src/ssl_cert_paths_discover.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c:76]: These paths goes from openssl package installed via brew on macOS, currently brew doesn't contain openssl 3.0,
so there is no need to add this paths right now.

File: src/ssl_cert_paths_discover.c [hunk 8]
```diff
@@ -0,0 +1,131 @@
...
+	/* Debian/Ubuntu/Gentoo etc. */
+	"/etc/ssl/certs/ca-certificates.crt",
+	/* OpenSUSE */
+	"/etc/ssl/ca-bundle.pem",
+	/* FreeBSD */
+	"/usr/local/share/certs/ca-root-nss.crt",
+	/* macOS */
+	"/private/etc/ssl/cert.pem",
+	"/usr/local/etc/openssl@1.1/cert.pem",
+	"/usr/local/etc/openssl@1.0/cert.pem",
```
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c:95]: These paths goes from openssl package installed via brew on macOS, currently brew doesn't contain openssl 3.0,
so there is no need to add this paths right now.

File: src/ssl_cert_paths_discover.h [hunk 9]
```diff
@@ -0,0 +1,69 @@
...
+ *   - SSL_CERT_DIR - it's a colon-separated list of directories
+ *     (like the Unix PATH variable) where stores certiifcates.
+ *   - SSL_CERT_FILE - it's a path to certificate file
+ * @param overwrite - flag for setenv if overwrite is zero, then the
+ * value of name (variable) not changed (from man setenv)
+ * @see https://serverfault.com/a/722646
+ * @see https://golang.org/src/crypto/x509/root_unix.go
+ * @see https://golang.org/src/crypto/x509/root_linux.go
+ * @see https://github.com/edenhill/librdkafka/blob/cb69d2a8486344252e0fcaa1f959c4ab2d8afff3/src/rdkafka_ssl.c#L845
+ * @see https://www.happyassassin.net/posts/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/
```
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.h]: I've removed first and last links. But other links comes from opensource projects (golang - [second](https://golang.org/src/crypto/x509/root_unix.go) and [third](https://golang.org/src/crypto/x509/root_linux.go) links and [librdkafka](https://github.com/edenhill/librdkafka) - [fourth](https://github.com/edenhill/librdkafka/blob/cb69d2a8486344252e0fcaa1f959c4ab2d8afff3/src/rdkafka_ssl.c#L845) link) solves problem with default ssl certificates, by using lookup paths.

Also this way still allows user to turn off ssl verification for ex. by setting SSL env vars to empty (and call http.request with verify_peer = false).

File: src/ssl_cert_paths_discover.c (hunk 2 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c:76]: About hardcoing paths (this approach used in golang and kafka - see previous answer):
1. User can set SSL env variables matching his situation. They won't be overwritten since function `ssl_cert_paths_discover` is called with `overwrite` = 0 param. 

2. This may be so, but as I researched these paths don't change frequently.

I've reviewd other approaches (see previous answer about golang and librdkafka), also nodejs use hardcoded cert.pem as
string at source code. Here are a links:
- definition of cert: https://github.com/nodejs/node/blob/44a66adbaa9d82cf70b6569701359b9a871acd31/src/node_root_certs.h
- cert using: https://github.com/nodejs/node/blob/f5287a4b7b0b14f69b264d8017b76c100f5bc2c1/src/crypto/crypto_context.cc#L42


Also approach used in this patch still allows user to turn off ssl verification for ex. by setting SSL env vars to empty (and call http.request with verify_peer = false).

File: src/ssl_cert_paths_discover.c (hunk 3 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: The same path as for Centos7. I've fixed comment

**Comment by HustonMmmavr** [comment]
I've added @Changelog to patch description.

Also commit message was fixed - described a problem of finding openssl certificates (not openssl.cfg)
Here is a diff of commit message:

```diff
<     Lookup openssl config at tarantool startup
---
>     Lookup openssl certs at tarantool startup
15c15
<                      "openssl-prefix/ssl/openssl.cnf", O_RDONLY) =
---
>                      "openssl-prefix/ssl/cert.pem", O_RDONLY) =
16a17,21
>     ...
>     stat("/__w/sdk/sdk/build/tarantool/static-build/"
>          "openssl-prefix/ssl/certs/...", ...) =
>          -1 ENOENT (No such file or directory)
>     ...
42c47
<     `SSL_CERT_DIR` and/or `SSL_SERT_FILE` setting. See also [4,5] - it's
---
>     `SSL_CERT_DIR` and/or `SSL_CERT_FILE` setting. See also [4,5] - it's
```

File: src/ssl_cert_paths_discover.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply src/ssl_cert_paths_discover.h]: These links a useful, but I don't see any reasons why it should be a part of autogenerated Tarantool documentation.
Moreover web links may broke.

File: src/ssl_cert_paths_discover.c [hunk 10]
```diff
@@ -0,0 +1,131 @@
...
+	const char *cert_file = NULL;
+	for (int i = 0; (path = DEFAULT_CERT_FILE_PATHS[i]); i++) {
+		if (stat(path, &sb) == 0) {
+			cert_file = path;
+			break;
+		}
+	}
+
+	if (cert_dirs_end > cert_dirs) {
+		*(cert_dirs_end -1) = '\0';
```
Comment (ligurio) [inline src/ssl_cert_paths_discover.c:125]: missed whitespace after `-`?

**Review by ligurio — CHANGES_REQUESTED** [review]
Thanks for patches!

See my two comments. Also we need to create a ticket for documentation where describe how custom paths for OpenSSL certificates can be set..

File: src/ssl_cert_paths_discover.c (hunk 10 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Fixed

File: src/main.cc [hunk 11]
```diff
@@ -710,6 +711,7 @@ main(int argc, char **argv)
 	memtx_tx_manager_init();
 	crypto_init();
 	systemd_init();
+	ssl_cert_paths_discover(0); /* Don't overwrite user defined env vars */
```
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/main.cc]: Fixed

File: src/ssl_cert_paths_discover.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.h]: These links removed

**Comment by HustonMmmavr** [comment]
Thanks for the review!

I've opened ticket for documentation #5802

File: src/ssl_cert_paths_discover.c [hunk 12]
```diff
@@ -0,0 +1,131 @@
...
+	if (!dir)
+		return 1;
+
+	struct dirent *ent;
+	int is_empty = 1;
+	while ((ent = readdir(dir))) {
+		if (strcmp(ent->d_name, ".") && strcmp(ent->d_name, "..")) {
+			if (ent->d_type == DT_REG ||
+			    ent->d_type == DT_LNK ||
+			    ent->d_type == DT_DIR) {
```
Comment (ligurio) [inline src/ssl_cert_paths_discover.c:53]: not aligned with upper `ent->d_type`

**Review by ligurio — CHANGES_REQUESTED** [review]

File: src/ssl_cert_paths_discover.c [hunk 13]
```diff
@@ -0,0 +1,131 @@
...
+{
+	DIR *dir = opendir(dir_path);
+	if (!dir)
+		return 1;
+
+	struct dirent *ent;
+	int is_empty = 1;
+	while ((ent = readdir(dir))) {
+		if (strcmp(ent->d_name, ".") && strcmp(ent->d_name, "..")) {
+			if (ent->d_type == DT_REG ||
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:51]: What is the point of this check? You are ignoring some valid file types. You are also ignoring DT_UNKNOWN which is explicitly forbidden by POSIX.

File: src/ssl_cert_paths_discover.c [hunk 14]
```diff
@@ -0,0 +1,131 @@
...
+				break;
+			}
+		}
+	}
+
+	closedir(dir);
+	return is_empty;
+}
+
+const char *DEFAULT_CERT_DIR_PATHS[] = {
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:64]: Why CAPS?

File: src/ssl_cert_paths_discover.c [hunk 15]
```diff
@@ -0,0 +1,131 @@
...
+	"/etc/openssl/certs",
+	/* macOS */
+	"/private/etc/ssl/certs",
+	"/usr/local/etc/openssl@1.1/certs",
+	"/usr/local/etc/openssl@1.0/certs",
+	"/usr/local/etc/openssl/certs",
+	NULL
+};
+
+const char *DEFAULT_CERT_FILE_PATHS[] = {
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:81]: Why CAPS?

File: src/ssl_cert_paths_discover.c [hunk 16]
```diff
@@ -0,0 +1,131 @@
...
+	char *cert_dirs_end = cert_dirs;
+
+	struct stat sb;
+	const char *path = NULL;
+	for (int i = 0; (path = DEFAULT_CERT_DIR_PATHS[i]); i++) {
+		if ((stat(path, &sb) != 0) || !S_ISDIR(sb.st_mode))
+			continue;
+
+		if (!is_dir_empty(path))
+			cert_dirs_end += sprintf(cert_dirs_end, "%s:", path);
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:112]: Buffer overrun

File: src/ssl_cert_paths_discover.c [hunk 17]
```diff
@@ -0,0 +1,131 @@
...
+
+void
+ssl_cert_paths_discover(int overwrite)
+{
+	char *cert_dirs = tt_static_buf();
+	char *cert_dirs_end = cert_dirs;
+
+	struct stat sb;
+	const char *path = NULL;
+	for (int i = 0; (path = DEFAULT_CERT_DIR_PATHS[i]); i++) {
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:107]: Why you need i? Why you are not checking for NULL (terminator)?

File: src/ssl_cert_paths_discover.c [hunk 18]
```diff
@@ -0,0 +1,131 @@
...
+		if ((stat(path, &sb) != 0) || !S_ISDIR(sb.st_mode))
+			continue;
+
+		if (!is_dir_empty(path))
+			cert_dirs_end += sprintf(cert_dirs_end, "%s:", path);
+	}
+
+	path = NULL;
+	const char *cert_file = NULL;
+	for (int i = 0; (path = DEFAULT_CERT_FILE_PATHS[i]); i++) {
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:117]: Why do you need i? Why you are not checking for NULL (terminator)?

File: src/ssl_cert_paths_discover.h [hunk 19]
```diff
@@ -0,0 +1,64 @@
...
+
+#if defined(__cplusplus)
+extern "C" {
+#endif /* defined(__cplusplus) */
+
+/**
+ * Default paths of directory where stores OpenSSL certificates
+ * for different systems
+ */
+extern const char *DEFAULT_CERT_DIR_PATHS[];
```
Comment (void234) [inline src/ssl_cert_paths_discover.h:42]: Why do you need this in .h?

File: src/ssl_cert_paths_discover.h [hunk 20]
```diff
@@ -0,0 +1,64 @@
...
+
+/**
+ * Default paths of OpenSSL certificates file for different systems
+ */
+extern const char *DEFAULT_CERT_FILE_PATHS[];
```
Comment (void234) [inline src/ssl_cert_paths_discover.h:47]: Why do you need this in .h?

File: src/main.cc [hunk 21]
```diff
@@ -710,6 +711,9 @@ main(int argc, char **argv)
 	memtx_tx_manager_init();
 	crypto_init();
 	systemd_init();
+
+	const int enable_overwrite_user_cert_paths = 0;
```
Comment (void234) [inline src/main.cc:715]: "override_cert_paths_env_vars" seems to be more accurate.
You should also consider separate parameters for overriding SSL_CERT_DIR and SSL_CERT_FILE. Or removing such half-baked functionality completely.

File: src/ssl_cert_paths_discover.h [hunk 22]
```diff
@@ -0,0 +1,64 @@
...
+
+/**
+ * Set SSL certificates paths (from system default paths) through
+ * OpenSSL env variables:
+ *   - SSL_CERT_DIR - it's a colon-separated list of directories
+ *     (like the Unix PATH variable) where stores certiifcates.
```
Comment (void234) [inline src/ssl_cert_paths_discover.h:53]: typo

File: src/ssl_cert_paths_discover.c [hunk 23]
```diff
@@ -0,0 +1,131 @@
...
+		if (stat(path, &sb) == 0) {
+			cert_file = path;
+			break;
+		}
+	}
+
+	if (cert_dirs_end > cert_dirs) {
+		*(cert_dirs_end - 1) = '\0';
+		setenv(X509_get_default_cert_dir_env(), cert_dirs, overwrite);
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:126]: Tarantool should be buildable w/o OpenSSL

File: src/ssl_cert_paths_discover.c [hunk 24]
```diff
@@ -0,0 +1,131 @@
...
+	}
+
+	if (cert_file)
+		setenv(X509_get_default_cert_file_env(), cert_file, overwrite);
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:130]: Tarantool should be buildable w/o OpenSSL

**Comment by void234** [comment]
Thanks for patches! Please resolve security and compatibility issues I have commented on.

File: src/ssl_cert_paths_discover.c (hunk 13 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: This check, really, is unnecessary. Deleted

File: src/ssl_cert_paths_discover.c (hunk 12 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: This check was deleted

File: src/ssl_cert_paths_discover.c (hunk 14 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Fixed (used lowercase)

File: src/ssl_cert_paths_discover.c (hunk 15 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Fixed (used lowercase)

File: src/ssl_cert_paths_discover.c (hunk 16 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Fixed (used dynamic buffer instead of static)

File: src/ssl_cert_paths_discover.c (hunk 17 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Fixed (iterate by pointer)

File: src/ssl_cert_paths_discover.c (hunk 18 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Fixed (iterate by pointer)

File: src/ssl_cert_paths_discover.h (hunk 19 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.h]: This was made for testing purposes (to get this symbol through ffi call)

File: src/ssl_cert_paths_discover.h (hunk 20 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.h]: This was made for testing purposes (to get this symbol through ffi call)

File: src/ssl_cert_paths_discover.h (hunk 22 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.h]: Typo fixed

File: src/main.cc (hunk 21 above)
Comment (HustonMmmavr) [reply src/main.cc]: Variable was renamed.
This flag is used for test purposes to enable overwriting existing SSL env variables, I think there is no need to create separate arguments

File: src/ssl_cert_paths_discover.c (hunk 23 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: This function comes from libcryto (part of OpenSSL, it's true), but our src/lib/crypto already depends on libcrypto.
So I beleive that this approach is more reliable than hardcoding names of SSL env vars at tarantool source code 
(in case of changing these vars' names they'll be imported from libcrypto).

File: src/ssl_cert_paths_discover.c (hunk 24 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c:145]: This function comes from libcryto (part of OpenSSL, it's true), but our src/lib/crypto already depends on libcrypto.
So I beleive that this approach is more reliable than hardcoding names of SSL env vars at tarantool source code 
(in case of changing these vars' names they'll be imported from libcrypto).

File: src/ssl_cert_paths_discover.h (hunk 19 above)
Comment (void234) [reply src/ssl_cert_paths_discover.h]: Are you sure ffi uses .h?

File: src/ssl_cert_paths_discover.h (hunk 20 above)
Comment (void234) [reply src/ssl_cert_paths_discover.h]: Are you sure ffi uses .h?

File: src/ssl_cert_paths_discover.c (hunk 23 above)
Comment (void234) [reply src/ssl_cert_paths_discover.c]: It looks like Tarantool already can't be built w/o OpenSSL.

File: src/main.cc [hunk 25]
```diff
@@ -710,6 +711,13 @@ main(int argc, char **argv)
 	memtx_tx_manager_init();
 	crypto_init();
 	systemd_init();
+
+	const int override_cert_paths_env_vars = 0;
+	int res = ssl_cert_paths_discover(override_cert_paths_env_vars);
+	if (res != 0)
+		panic_syserror("No enough memory for setup "
```
Comment (void234) [inline src/main.cc:718]: Are you sure panic in this case is a good idea? I believe warning will be enough.

File: src/ssl_cert_paths_discover.c [hunk 26]
```diff
@@ -0,0 +1,152 @@
...
+};
+
+int
+ssl_cert_paths_discover(int overwrite)
+{
+	int rc = -1;
+	struct stat sb;
+	size_t dir_buf_end = 0;
+	size_t initial_size = 32;
+	size_t buf_size = initial_size * sizeof(char);
```
Comment (void234) [inline src/ssl_cert_paths_discover.c:102]: sizeof() returns size in chars (not in bytes). There is no point in "* sizeof(char)".

**Comment by void234** [comment]
Thanks for patches! Please resolve remaining issues.

File: src/ssl_cert_paths_discover.c (hunk 23 above)
Comment (Totktonada) [reply src/ssl_cert_paths_discover.c]: OpenSSL is used for crypto functions (`require('crypto')`), so we depend on it anyway.

File: src/ssl_cert_paths_discover.c (hunk 26 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.c]: Fixed.
I've used sizeof(char) for clarity, but you are right it can be omitted

File: src/main.cc (hunk 25 above)
Comment (HustonMmmavr) [reply src/main.cc]: Fixed (used `say_warn` instead of `panic_syserror`)

File: src/ssl_cert_paths_discover.h (hunk 19 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.h]: I've supposed that declaring these symbols in .h file with `extern` keyword will prevent LTO from hiding them, but I was wrong.
Now .h file cleared from these symbols and test was refactored.

File: src/ssl_cert_paths_discover.h (hunk 20 above)
Comment (HustonMmmavr) [reply src/ssl_cert_paths_discover.h]: I've supposed that declaring these symbols in .h file with `extern` keyword will prevent LTO from hiding them, but I was wrong.
Now .h file cleared from these symbols and test was refactored.

**Comment by HustonMmmavr** [comment]
Thanks for the review!
All issues resolved

**Review by void234 — APPROVED** [review]

**Review by ligurio — APPROVED** [review]
LGTM
