### PR TITLE
lua: fix sigint behavior in multiline input mode

### LINKED ISSUE #7109: Ctrl+C does not break multiline input
It seems, we missed this case during implementing #2717.

```lua
$ tarantool
Tarantool 2.11.0-entrypoint-24-g3a0bb34df
type 'help' for interactive help
tarantool> box.cfg({
         > ^C
         > ^C
         > ^C
         > ^C
$ tarantool
Tarantool 2.11.0-entrypoint-24-g3a0bb34df
type 'help' for interactive help
tarantool> foo = function()
         > ^C
         > ^C
         > ^C
         > ^C
```

I guess that all versions since implementing #2717 (2.10.0-beta2-168-ga8b3b267c and later) are affected.

### PR DESCRIPTION
**Pull request by vr009**
This patch fixes the ctrl+c behavior in multiline mode.
The old behavior was ignoring sigint in this mode.
The new behavior is quitting this mode and printing the new
default prompt.
Added a new test for covering the mentioned case.

Follows up #2717
Closes #7109

### CODE REVIEW

File: extra/exports [hunk 1]
```diff
@@ -390,6 +390,7 @@ say_parse_logger_type
 say_set_log_format
```
Comment (Totktonada) [inline extra/exports:390]: > NO_CHANGELOG=BUGFIX

It is bugfix, so what? It is the user visible change, which makes the behaviour different from one that was released in 2.10.0.

> NO_TEST=BUGFIX

But you have added a test. It seems, you don't need `NO_TEST`.

Comment (vr009) [reply extra/exports:390]: Fixed.

Comment (Totktonada) [reply extra/exports:390]: Thanks! (Please, update or, better, strip it from the pull request description.)

File: src/box/lua/console.lua [hunk 2]
```diff
@@ -620,6 +623,9 @@ local function local_read(self)
             buf = buf:sub(0, #buf - #delim)
             break
         end
+        if ffi.C.sigint_is_called() == true then
+            return ''
+        end
```
Comment (Totktonada) [inline src/box/lua/console.lua:628]: We can return `discard_buffer` (boolean) value from the `internal.readline()` function using multireturn. It'll simplify the code.

File: test/app-tap/gh-2717-no-quit-sigint.test.lua [hunk 3]
```diff
@@ -18,7 +18,7 @@ local prompt = 'tarantool> '
 local TARANTOOL_PATH = arg[-1]
 local test = tap.test('gh-2717-no-quit-sigint')
 
-test:plan(6)
+test:plan(8)
```
Comment (Totktonada) [inline test/app-tap/gh-2717-no-quit-sigint.test.lua:21]: When I run the test many times in parallel, it constantly fails.

The command:

```shell
$ ./test/test-run.py $(yes gh-2717 | head -n 1000)
```

The error:

```
[009] Last 15 lines of Tarantool Log file [Instance "app_server"][/tmp/t/009_app-tap/gh-2717-no-quit-sigint.test.lua.tarantool.log]:
[009] LuajitError: ...-meta/r/t-3/test/app-tap/gh-2717-no-quit-sigint.test.lua:194: time_quota is violated
[009] fatal error, exiting the event loop
```

I observed it on `master` too, so it is not related to your patch. Just highligthed it for you (I will resolve this discussion).

File: src/box/lua/console.lua (hunk 2 above)
Comment (vr009) [reply src/box/lua/console.lua]: You are right, thank you! Fixed.

File: src/box/lua/console.c [hunk 4]
```diff
@@ -326,11 +326,11 @@ lbox_console_readline(struct lua_State *L)
 				rl_on_new_line();
 				rl_replace_line("", 0);
 				lua_pushstring(L, "");
+				lua_pushboolean(L, sigint_called);
```
Comment (Totktonada) [inline src/box/lua/console.c:329]: Shouldn't we also adjust `console_push_line()`?

File: src/box/lua/console.c [hunk 5]
```diff
@@ -326,11 +326,11 @@ lbox_console_readline(struct lua_State *L)
...
 
 				readline_L = NULL;
-				sigint_called = false;
```
Comment (Totktonada) [inline src/box/lua/console.c:331]: Deletion of this line now looks redundant, since in this version of the patch we don't lean on the flag value outside of the function anymore.

File: src/box/lua/console.lua [hunk 6]
```diff
@@ -620,6 +620,9 @@ local function local_read(self)
             buf = buf:sub(0, #buf - #delim)
             break
         end
+        if discard_buffer == true then
+            return ''
+        end
```
Comment (Totktonada) [inline src/box/lua/console.lua:625]: Shouldn't we check it before attempt to parse a command? It seems more logical to me, however since we always get `line == ''` at Ctrl+C I can't find any difference in the actual behaviour.

File: src/box/lua/console.c (hunk 5 above)
Comment (vr009) [reply src/box/lua/console.c:331]: This flag get set to false every time, when we enter the readline function, this line is actually not needed here.

Comment (Totktonada) [reply src/box/lua/console.c:331]: I'm a bit afraid about such assumption regarding the global flag. If we'll consume it from some other place, it may show unexpected values.

Comment (vr009) [reply src/box/lua/console.c:331]: Fixed.

File: src/box/lua/console.lua (hunk 6 above)
Comment (vr009) [reply src/box/lua/console.lua]: Fixed.

File: src/box/lua/console.c (hunk 4 above)
Comment (vr009) [reply src/box/lua/console.c:329]: Which way?

[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/lua/console.c:333]: Okay.

File: src/box/lua/console.c (hunk 5 above)
Comment (Totktonada) [reply src/box/lua/console.c:331]: Thanks!

File: src/box/lua/console.c (hunk 4 above)
Comment (vr009) [reply src/box/lua/console.c:333]: You are right, fixed.

Comment (Totktonada) [reply src/box/lua/console.c:333]: Looks resolved now.

File: src/box/lua/console.c [hunk 7]
```diff
@@ -218,6 +218,9 @@ console_completion_handler(const char *text, int start, int end)
  *
  * The callback creates a copy of the line on the Lua stack; this copy
  * becomes the lbox_console_readline()'s ultimate result.
+ *
+ * The second return value is boolean, which means 'do not
+ * discard the line'.
```
Comment (Totktonada) [inline src/box/lua/console.c:223]: It seems, its meaning the opposite.

File: src/box/lua/console.lua [hunk 8]
```diff
@@ -617,13 +617,16 @@ local function local_read(self)
...
         local delim = self.delimiter
-        local line = internal.readline({
+        local line, discard_buffer = internal.readline({
             prompt = prompt.. "> ",
             completion = self.ac and self.completion or nil
         })
         if not line then
             return nil
         end
+        if discard_buffer == true then
```
Comment (Totktonada) [inline src/box/lua/console.lua:627]: Nit: A boolean in an if-condition is usually not checked against equality with true/false.

File: test/app-tap/gh-2717-no-quit-sigint.test.lua [hunk 9]
```diff
@@ -58,6 +58,70 @@ test:like(output, prompt .. '^C\n---\n...\n\n' .. prompt,
...
+    output = output .. ph:read({timeout = 1.0})
+end
+assert(clock.monotonic() - start_time < time_quota, 'time_quota is violated')
+
+ph:write('box.cfg{\n')
+
+start_time = clock.monotonic()
+time_quota = 10.0
+expected_output = expected_output .. 'box.cfg{' .. '\n' ..
+        string.rep(' ', #prompt_name) .. '> '
```
Comment (Totktonada) [inline test/app-tap/gh-2717-no-quit-sigint.test.lua:91]: Nit: `function foo()` would have less side effects comparing to `box.cfg{`, but allows to test the same. Or, say, `foo(`.
