### PR TITLE
vinyl: fix abort of writers on DDL

### LINKED ISSUE #10707: AddressSanitizer: heap-use-after-free on address 0x5140002f77ec at pc 0x62b92f82fb5b bp 0x73673f27d7c0 sp 0x73673f27d7b8
**Bug description**

heap-use-after-free

* OS: Linux
* OS Version: Ubuntu 24.04
* Architecture: amd64

Tarantool 3.3.0-entrypoint-161-gbf09135880
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: Clang-18.1.3
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fsanitize=address -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fsanitize=address -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

`./build/src/tarantool ./test/fuzz/lua/test_engine.lua --workers 800 --test_duration $((60*60*10)) --engine vinyl --verbose --seed 5582`

**Actual behavior**

```c++
==574672==ERROR: AddressSanitizer: heap-use-after-free on address 0x5140002f77ec at pc 0x62b92f82fb5b bp 0x73673f27d7c0 sp 0x73673f27d7b8
READ of size 1 at 0x5140002f77ec thread T0                                                                                                         
    #0 0x62b92f82fb5a in space_is_sync /home/ubuntu/tarantool/src/box/space.h:424:22
    #1 0x62b92f834f6e in txn_journal_entry_new /home/ubuntu/tarantool/src/box/txn.c:1008:12      
    #2 0x62b92f82c655 in txn_commit_impl /home/ubuntu/tarantool/src/box/txn.c:1179:8
    #3 0x62b92f82e691 in box_txn_commit_ex /home/ubuntu/tarantool/src/box/txn.c:1405:9                                                    
    #4 0x62b92fb133b0 in lbox_commit /home/ubuntu/tarantool/src/box/lua/init.c:518:6
    #5 0x62b92fd31586 in lj_BC_FUNCC /home/ubuntu/tarantool/build/third_party/luajit/src/lj_vm.S:811
    #6 0x62b92fd5c11a in lua_pcall /home/ubuntu/tarantool/third_party/luajit/src/lj_api.c:1173:12
    #7 0x62b92fbcb202 in luaT_call /home/ubuntu/tarantool/src/lua/utils.c:695:6
    #8 0x62b92fbb5cce in lua_fiber_run_f /home/ubuntu/tarantool/src/lua/fiber.c:435:11
    #9 0x62b92f504049 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) /home/ubuntu/tarantool/src/lib/core/fiber.h:1324:10
    #10 0x62b92fc2f3f9 in fiber_loop /home/ubuntu/tarantool/src/lib/core/fiber.c:1162:18
    #11 0x62b93067f559 in coro_init /home/ubuntu/tarantool/third_party/coro/coro.c:108:3

0x5140002f77ec is located 428 bytes inside of 436-byte region [0x5140002f7640,0x5140002f77f4)
freed by thread T0 here:
    #0 0x62b92f4bf3ba in free (/home/ubuntu/tarantool/build/src/tarantool+0x2cd3ba) (BuildId: ad3fa14f33098c75c1c9c78c695a98f1be89dd8e)
    #1 0x62b9306104da in small_asan_free /home/ubuntu/tarantool/src/lib/small/small/util.c:137:2
    #2 0x62b93060c40e in mempool_free /home/ubuntu/tarantool/src/lib/small/small/mempool_asan.c:83:2
    #3 0x62b92f93710b in tx_complete_batch /home/ubuntu/tarantool/src/box/wal.c:378:2
    #4 0x62b92fc4a3bd in cmsg_deliver /home/ubuntu/tarantool/src/lib/core/cbus.c:350:2
    #5 0x62b92fc4c2ba in cbus_process /home/ubuntu/tarantool/src/lib/core/cbus.c:601:3
    #6 0x62b92f884473 in tx_prio_cb(ev_loop*, ev_watcher*, int) /home/ubuntu/tarantool/src/box/box.cc:5642:2
    #7 0x62b93064fae5 in ev_invoke_pending /home/ubuntu/tarantool/third_party/libev/ev.c:3797:11
    #8 0x62b93065104d in ev_run /home/ubuntu/tarantool/third_party/libev/ev.c:4221:7
    #9 0x62b92fbaafdb in tarantool_lua_run_script /home/ubuntu/tarantool/src/lua/init.c:1218:2
    #10 0x62b92f50319a in main /home/ubuntu/tarantool/src/main.cc:1060:7
    #11 0x73678022a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #12 0x73678022a28a in __libc_start_main csu/../csu/libc-start.c:360:3 
    #13 0x62b92f424804 in _start (/home/ubuntu/tarantool/build/src/tarantool+0x232804) (BuildId: ad3fa14f33098c75c1c9c78c695a98f1be89dd8e)

previously allocated by thread T0 here:
    #0 0x62b92f4bf653 in malloc (/home/ubuntu/tarantool/build/src/tarantool+0x2cd653) (BuildId: ad3fa14f33098c75c1c9c78c695a98f1be89dd8e)
    #1 0x62b93061001c in small_asan_alloc /home/ubuntu/tarantool/src/lib/small/small/util.c:94:24
    #2 0x62b93060c305 in mempool_alloc /home/ubuntu/tarantool/src/lib/small/small/mempool_asan.c:67:4
    #3 0x62b92f933a8d in wal_write_async /home/ubuntu/tarantool/src/box/wal.c:1353:29
    #4 0x62b92f835c5c in journal_write_submit /home/ubuntu/tarantool/src/box/journal.h:277:9
    #5 0x62b92f82cea9 in txn_commit_impl /home/ubuntu/tarantool/src/box/txn.c:1221:6
    #6 0x62b92f82d756 in txn_commit /home/ubuntu/tarantool/src/box/txn.c:1291:9
    #7 0x62b92f852bc3 in box_process_rw /home/ubuntu/tarantool/src/box/box.cc:516:23
    #8 0x62b92f866855 in box_process1 /home/ubuntu/tarantool/src/box/box.cc:3785:9
    #9 0x62b92f869182 in box_delete /home/ubuntu/tarantool/src/box/box.cc:3996:9
    #10 0x62b92fb3d290 in lbox_index_delete /home/ubuntu/tarantool/src/box/lua/index.c:168:11
    #11 0x62b92fd31586 in lj_BC_FUNCC /home/ubuntu/tarantool/build/third_party/luajit/src/lj_vm.S:811

SUMMARY: AddressSanitizer: heap-use-after-free /home/ubuntu/tarantool/src/box/space.h:424:22 in space_is_sync
Shadow bytes around the buggy address:
  0x5140002f7500: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x5140002f7580: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x5140002f7600: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x5140002f7680: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x5140002f7700: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x5140002f7780: fd fd fd fd fd fd fd fd fd fd fd fd fd[fd]fd fa
  0x5140002f7800: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x5140002f7880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x5140002f7900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x5140002f7980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x5140002f7a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):

Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==574672==ABORTING
```

log and tarantool binary: https://drive.google.com/file/d/1ZRlGXpOoliSt6J_2th3N2tGnJAWAdjJ2/view?usp=drive_link

**Expected behavior**

no heap-use-after-free

### PR DESCRIPTION
**Pull request by locker**
When a DDL statement is committed, all transactions writing to the space must be aborted so that they don't access the stale `txn_stmt::space` pointer on commit. In Vinyl we abort all writers from the special `space_invalidate` engine callback, where we iterate over all writing transactions and abort those of them that have a write set entry pointing to the primary key of the invalidated space, see commit d3e1236956515 ("vinyl: abort affected transactions when space is removed from cache"). We also abort transactions that haven't yet created a write set entry because they need to read the disk first, for example, to perform a tuple update, see commit 4f62ec2102f4 ("vinyl: make tx_manager_abort_writers_for_ddl more thorough").

However, as spotted by @drewdzzz, this code doesn't always work as expected. The problem is, unless dropped, the primary index is moved to the new space container so using the primary index stored in the old space container to abort transactions is wrong: there can't possibly be any transactions associated with it. We don't get a crash because we have an extra check in `vy_lsm_set` that aborts the transaction if the space format was updated (it is updated on every space change), see commit e3c5fde4b57cd ("vinyl: fix DDL with active transactions").

Another problem with `space_invalidate` is that it doesn't abort transactions that turned out to be no-op, such as an update of a non-existing key because such transactions don't add any entries to the write set. Still, they must be aborted because they have a `txn_stmt` pointing to the old space. Letting them proceed to commit would result in a use-after-free bug, see #10707.

Let's fix `space_invalidate` by making it iterate over all statements of writing transactions instead of checking their Vinyl write sets. To achieve that, we store a pointer to `struct txn` in `struct vy_tx`. This lets us drop `vy_tx::last_stmt_space` and `vy_tx::isolation` because they can be accessed via `txn`. We also replace the format check in `vy_lsm_set` mentioned above with an assertion because such transactions should be aborted by `space_invalidate` now.

Closes #10707

### CODE REVIEW

File: src/box/vy_lsm.c [hunk 1]
```diff
@@ -905,13 +905,8 @@ vy_lsm_set(struct vy_lsm *lsm, struct vy_mem *mem,
...
 	assert(*region_stmt == NULL || !vy_stmt_is_refable(*region_stmt));
-
-	/* Abort transaction if format was changed by DDL */
-	if (!vy_stmt_is_key(entry.stmt) &&
-	    format_id != tuple_format_id(mem->format)) {
-		diag_set(ClientError, ER_TRANSACTION_CONFLICT);
-		return -1;
-	}
+	assert(vy_stmt_is_key(entry.stmt) ||
+	       format_id == tuple_format_id(mem->format));
```
Comment (drewdzzz) [inline src/box/vy_lsm.c:909]: Why not `assert(format_id == tuple_format_id(mem->format));` if we abort all writers on DDL?

TBO, I don't understand why we needed this `vy_stmt_is_key(entry.stmt)` check at all.

File: src/box/vy_tx.c [hunk 2]
```diff
@@ -1157,10 +1151,13 @@ vy_tx_manager_abort_writers_for_ddl(struct vy_tx_manager *xm,
 			*need_wal_sync = true;
 		if (tx->state != VINYL_TX_READY)
 			continue;
-		if (tx->last_stmt_space == space ||
-		    write_set_search_key(&tx->write_set, lsm,
-					 lsm->env->empty_key) != NULL)
-			vy_tx_abort(tx);
+		struct txn_stmt *stmt;
```
Comment (drewdzzz) [inline src/box/vy_tx.c:1154]: Offtop: `wal_sync()` seems insufficient here - prepared transactions can be aborted even after reaching WAL due to replication failure.

File: src/box/vy_lsm.c (hunk 1 above)
Comment (drewdzzz) [reply src/box/vy_lsm.c:909]: I got it - keys have a different format so we need to check format of non-key statements only.

**Review by drewdzzz — APPROVED** [review]
LGTM, it's nice that we don't need to handle writes that haven't written something yet anymore!

File: src/box/vy_lsm.c (hunk 1 above)
Comment (locker) [reply src/box/vy_lsm.c:909]: In Vinyl a statement may be in the form of a key or a tuple. The key format is used for DELETE statements if there are no secondary indexes or secondary index DELETEs are deferred. The key format is shared across all LSM trees, see `vy_lsm->env->key_format`.

File: src/box/vy_tx.c (hunk 2 above)
Comment (locker) [reply src/box/vy_tx.c:1154]: Talked f2f. Turns out there's a bug here if sync replication is enabled: `wal_sync()` doesn't wait for quorum confirmation so it doesn't guarantee that all pending statements are committed or rolled back. Looks like we need to wait for limbo resolution here as well. This is another issue that will be addressed separately though.

**Review by xuniq — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 3.2 and 3.3.
