### PR TITLE
serializer: remove duplicate of lua serializer

### LINKED ISSUE #10177: Attempting to access freed Gcudata memory
**Bug description**

ASAN detected an access to already freed GCudata memory.

* OS: Linux
* OS Version: Debian 11
* Architecture: amd64

**`tarantool --version` output:**
Tarantool 3.2.0-entrypoint-84-g9d3859b24
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: Clang-14.0.0
```
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fsanitize=fuzzer-no-link -fsanitize=address -fsanitize-blacklist=/home/mandesero/tarantool/asan/asan.supp  -fmacro-prefix-map=/home/mandesero/tarantool=. -std=c11 -Wall -Wextra -fsanitize=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -fno-sanitize-recover=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -fsanitize=fuzzer-no-link -fsanitize=address -fsanitize-blacklist=/home/mandesero/tarantool/asan/asan.supp  -fmacro-prefix-map=/home/mandesero/tarantool=. -std=c++11 -Wall -Wextra -fsanitize=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -fno-sanitize-recover=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Werror -g -ggdb -O0
```
**Steps to reproduce**

```
cd tarantool/third_party/luajit
git checkout mandesero/dlmalloc-instr
```

```
cmake -S . -B . -DENABLE_WERROR=ON -DENABLE_ASAN=ON -DENABLE_UB_SANITIZER=ON -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=OFF -DENABLE_FUZZER=ON -DTEST_BUILD=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFIBER_STACK_SIZE=640Kb -DLUAJIT_ENABLE_GC64=ON -DCMAKE_BUILD_TYPE=Debug && make -j
cd test
gdb --args ../src/tarantool -i
(tarantool) \set output lua
```

**Actual behavior**

```
ERROR: AddressSanitizer: use-after-poison on address 0x7ffff27b4ddc

READ of size 4 at 0x7ffff27b4ddc thread T0
[Detaching after fork from child process 171534]
    #0 0x555557b3a6de in lua_field_inspect_table /home/mandesero/tarantool/src/lua/serializer.c:369:11
    #1 0x555557b39c02 in luaL_tofield /home/mandesero/tarantool/src/lua/serializer.c:588:10
    #2 0x5555579ba063 in luaL_checkfield /home/mandesero/tarantool/src/lua/serializer.h:329:6
    #3 0x5555579b8c76 in dump_root /home/mandesero/tarantool/src/box/lua/serialize_lua.c:948:2
    #4 0x5555579b7779 in lua_encode /home/mandesero/tarantool/src/box/lua/serialize_lua.c:999:6
    #5 0x5555579a1fac in lbox_console_format_lua /home/mandesero/tarantool/src/box/lua/console.c:126:12
    #6 0x555557ea4608 in lj_BC_FUNCC /home/mandesero/tarantool/third_party/luajit/src/lj_vm.S:852
    #7 0x555557ecf1ca in lua_pcall /home/mandesero/tarantool/third_party/luajit/src/lj_api.c:1173:12
    #8 0x555557b2926e in luaT_call /home/mandesero/tarantool/src/lua/utils.c:689:6
    #9 0x555557ae9389 in lua_main /home/mandesero/tarantool/src/lua/init.c:916:11
    #10 0x555557ae0c54 in run_script_f /home/mandesero/tarantool/src/lua/init.c:1158:7
    #11 0x5555568d39b3 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) /home/mandesero/tarantool/src/lib/core/fiber.h:1308:10
    #12 0x555557c0e92b in fiber_loop /home/mandesero/tarantool/src/lib/core/fiber.c:1153:18
    #13 0x555558c33858 in coro_init /home/mandesero/tarantool/third_party/coro/coro.c:108:3

Address 0x7ffff27b4ddc is a wild pointer inside of access range of size 0x000000000004.
SUMMARY: AddressSanitizer: use-after-poison /home/mandesero/tarantool/src/lua/serializer.c:369:11 in lua_field_inspect_table
```

***Notes***
tarantool/src/lua/serializer.c:369:11: `if (cfg->encode_load_metatables) {`

`cfg=0x7ffff27b4dc0` is part of GCudata allocated in `lj_udata_new (L=0x7ffff4b663b8, sz=136, env=0x7ffff4b67ea8) at /home/mandesero/tarantool/third_party/luajit/src/lj_udata.c:26`, where `ud=0x7ffff27b4d90,`.

Then `ud` is freed

BT:
```
#0  lj_alloc_free (msp=0x7ffff4b66030, ptr=0x7ffff27b4d90) at /home/mandesero/tarantool/third_party/luajit/src/lj_alloc.c:1592
#1  0x000055555801ea2a in lj_alloc_f (msp=0x7ffff4b66030, ptr=0x7ffff27b4d90, osize=184, nsize=0) at /home/mandesero/tarantool/third_party/luajit/src/lj_alloc.c:1742
#2  0x0000555557f54045 in lj_mem_free (g=0x7ffff4b66418, p=0x7ffff27b4d90, osize=184) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.h:119
#3  lj_udata_free (g=0x7ffff4b66418, ud=0x7ffff27b4d90) at /home/mandesero/tarantool/third_party/luajit/src/lj_udata.c:35
#4  0x0000555557efc863 in gc_sweep (g=0x7ffff4b66418, p=0x7ffff27b56a0, lim=12) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.c:415
#5  0x0000555557efda8f in gc_onestep (L=0x7ffff4b663b8) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.c:693
#6  0x0000555557efcbd9 in lj_gc_step (L=0x7ffff4b663b8) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.c:745
#7  0x0000555557efec96 in lj_gc_step_jit (g=0x7ffff4b66418, steps=0) at /home/mandesero/tarantool/third_party/luajit/src/lj_gc.c:778
``` 

**Expected behavior**

```
(tarantool) \set language lua
 - true # no asan error
```

### PR DESCRIPTION
**Pull request by mandesero**
This patch fixes a bug found by the ASAN instrumentation of LuaJIT
allocator [1]. The problem is using a Lua serializer object that has
been cleaned up by GC.

Tarantool build:
 - Tarantool 3.2.0-entrypoint-84-g9d3859b24
 - Target: Linux-x86_64-Debug
 - Compiler: Clang-14.0.0
 - LuaJIT branch: mandesero/dlmalloc-instr
 - CMAKE_FLAGS:
 	```
	-DENABLE_WERROR=ON -DENABLE_ASAN=ON -DENABLE_UB_SANITIZER=ON
	-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=OFF -DENABLE_FUZZER=ON
	-DTEST_BUILD=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
	-DFIBER_STACK_SIZE=640Kb -DLUAJIT_ENABLE_GC64=ON
	-DCMAKE_BUILD_TYPE=Debug
	```
 - ASAN_OPTIONS:
 	```
	detect_invalid_pointer_pairs=1:detect_leaks=1:\
	dump_instruction_bytes=1:heap_profile=0:\
	print_suppressions=0:symbolize=1:unmap_shadow_on_exit=1:\
	redzone=32
	```
 - LSAN_OPTIONS:
 	```
	suppressions=tarantool/asan/lsan.supp
	```

The crash occurs when executing `(tarantool) \set output lua`.

Failing tests:
 - ./test/app-luatest/gh_7031_configure_eos_in_lua_console_test.lua
 - ./test/app-tap/console.test.lua
 - ./test/box/push.test.lua
 - ./app-tap/console_lua.test.lua
 - ./app-luatest/varbinary_test.lua

The `serializer_lua` static member is removed from
`src/box/lua/serialize_lua.c` along with `serializer_lua_init`,
because it is not used by any function other than `serializer_lua_init`,
which is not needed now too.

[1]: Issue https://github.com/tarantool/tarantool/issues/10231

Closes https://github.com/tarantool/tarantool/issues/10177 (this issue is a duplicate of https://github.com/tarantool/tarantool/issues/7404)

NO_TEST=rely on existing tests
NO_CHANGELOG=codehealth
NO_DOC= codehealth

### CODE REVIEW

**Comment by Buristan** [comment]
Looks related to the #7404.

File: src/box/lua/serialize_lua.c [hunk 1]
```diff
@@ -1038,32 +1038,10 @@ lua_parse_opts(lua_State *L, lua_dumper_opts_t *opts)
...
-	serializer_lua->encode_load_metatables	= 1;
-	serializer_lua->encode_use_tostring	= 1;
-	serializer_lua->encode_invalid_as_nil	= 1;
-
-	/*
-	 * Keep a reference to this module so it
-	 * won't be unloaded.
-	 */
-	lua_setfield(L, -2, "formatter_lua");
+	serializer_lua = serializer;
```
Comment (mkokryashkin) [inline src/box/lua/serialize_lua.c:1046]: Yaml serializer above is different from the lua serializer, because it is a static member specific for the console module. Lua serializer is set as a static member in the console module and the same serializer is set as a static member in the lua serializer module. Moreover, lua serializer module is now not responsible for linking the serializer object anywhere, so it static member may hold a pointer to a dead object if someone outside forgets to create a reference.

That static member also seems redundant, because it is not used by any function other than setter, so let's remove it along with the setter.

**Review by mkokryashkin — CHANGES_REQUESTED** [review]
Please specify more details in the commit message: explanation of the issue, failing test name, build parameters. Also it is important to specify that test fails under ASAN. 

Add tag "Related to #7404"

**Review by mkokryashkin — CHANGES_REQUESTED** [review]
> All crashes are the result of attempts to access `serializer_lua`
fields in `src/box/lua/console.c`, which was overwritten when
`src/box/lua/serialize_lua.c:lua_serializer_init` was called due
to repeated call of `lua_setfield(L, -2, “formatter_lua”)`.
Typo: s/to repeated/to the repeated/

>So let's remove the static lua serializer member from
`src/box/lua/serialize_lua.c` along with `serializer_lua_init`,
because it is not used by any function other than `serializer_lua_init`.

It is better to paraphrase like the following:
```
The `serializer_lua` static member is removed from
`src/box/lua/serialize_lua.c` along with `serializer_lua_init`,
because it is not used by any function other than `serializer_lua_init`,
which is not needed now too.
```

Otherwise, patch LGTM

**Review by mkokryashkin — APPROVED** [review]

**Review by ligurio — COMMENTED** [review]
Maksim, thanks for the patch!

1. Actually I don't get why we should describe tarantool version, lsan and asan options in commit message. I believe this information should be added to the ticket #10231 and removed from commit message/
2. reason in `NO_CHANGELOG` and `NO_DOC` can be replaced to `codehealth`. It is not a bugfix, actually.
3. Ilya Verbin said about similar problem (#7404). It is not clear: whether it is a duplicate or not.

**Comment by mandesero** [comment]
> Maksim, thanks for the patch!
> 
> 1. Actually I don't get why we should describe tarantool version, lsan and asan options in commit message. I believe this information should be added to the ticket [ASAN & LuaJIT allocator #10231](https://github.com/tarantool/tarantool/issues/10231) and removed from commit message/
> 2. reason in `NO_CHANGELOG` and `NO_DOC` can be replaced to `codehealth`. It is not a bugfix, actually.
> 3. Ilya Verbin said about similar problem ([Unallocated `serializer_lua` used by `lbox_console_format_lua` #7404](https://github.com/tarantool/tarantool/issues/7404)). It is not clear: whether it is a duplicate or not.

Sergey, thanks for your comment! I took the following points into consideration.

1. I removed the description of the tarantool build from the commit message, a link to the issue where the build is described was added to ASAN & LuaJIT allocator #10231.
2. NO_DOC and NO_CHANGELOG were changed to the suggested ones.
3. The current issue is indeed a duplicate ([Unallocated `serializer_lua` used by `lbox_console_format_lua` #7404](https://github.com/tarantool/tarantool/issues/7404)), only found using ASAN. I indicated information about the duplicate in the commit message.

**Review by ligurio — APPROVED** [review]
LGTM,  thanks

**Review by Totktonada — APPROVED** [review]

**Comment by Totktonada** [comment]
Pushed to `master`, a future `3.2.0` release.

Backported to `release/3.1`, a future `3.1.2` release, in PR #10394.

Backported to `release/2.11`, a future `2.11.4` release, in PR #10395.
