### PR TITLE
httpc: added a decoders to a http response

### LINKED ISSUE #8363: http client: unable to decode "application/json; charset=utf-8" body
Tarantool version: 2.11.0-rc1.

```lua
tarantool> httpc = require('http.client').new()
tarantool> response = httpc:get('https://jsonplaceholder.typicode.com/todos/1')
tarantool> response:decode()
---
- error: 'builtin/http.client.lua:301: attempt to index field ''decoders'' (a nil
    value)'
...
```

https://github.com/tarantool/tarantool/blob/a989cd41bfc9e01a06227d1da65fdc0d76e66511/src/lua/httpc.lua#L301

### PR DESCRIPTION
**Pull request by ligurio**
Patch fixes a bug when body in response couldn't be decoded:

```
tarantool> httpc = require('http.client').new()
tarantool> response = httpc:get('https://jsonplaceholder.typicode.com/todos/1')
tarantool> response:decode()

---
- error: 'builtin/http.client.lua:301: attempt to index field ''decoders'' (a nil
    value)'
...
```

Reported-by: Alexander Turenko <alexander.turenko@tarantool.org>

Fixes #8363

NO_DOC=bugfix

### CODE REVIEW

File: src/lua/httpc.lua [hunk 1]
```diff
@@ -585,6 +585,7 @@ curl_mt = {
 
             if not opts.chunked then
                 resp.url = url_with_params
+                resp.decoders = decoders
```
Comment (Totktonada) [inline src/lua/httpc.lua:588]: Maybe it would be better to start the field from an underscore (so it'll be excluded from the autocompletion) and add `__serialize` that skips fields that start from the underscore. Or capture `decoders` in a locally created function and pass it to `decode_body` in a separate argument.

Comment (Totktonada) [reply src/lua/httpc.lua]: Now the field is named `_decoders` and it is excluded from the serialization.

**Comment by igormunkin** [comment]
The patchset is also backported to 2.11 (2.11.0-rc1-8-g5dcf3114f) in scope of the following patches:
* 5dcf311 (httpc: add a test with decoding using a custom body decoder)
* cf39611 (httpc: add a decoders to a http response)
