### PR TITLE
sql: fix memory leak when calling user functions

### LINKED ISSUE #6789: Memory leak in SQL
**Bug description**

~50 Mb leaks when executing an SQL query

* OS: Linux
* OS Version: Centos 8
* Architecture: amd64

```
Tarantool 2.8.2-24-g917823eac
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/lib64/ccache/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Download and unpack file: https://t.bk.ru/1RFdQSj/sqlleak.tar.gz

Run tarantool under valgrind in the created directory:

```
valgrind \
        --leak-check=full \
        --show-leak-kinds=all \
        --track-origins=yes \
        --keep-stacktraces=alloc-and-free \
        --verbose \
        --log-file=valgrind.log \
        tarantool
```

Load the DB:
```
box.cfg({ memtx_memory = 3500000000 })
```

Execute the query:
```
box.execute([[select (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'mrf_name') as "#1", count(case when "eventName"."name" = 'CRM - Регистрация обращения' and "process"."eventCount" = 1 and not (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'result') in ('Связано с ГП', 'Массовая проблема') and (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'result') not like 'Блок%' then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#2", "processUid" as "#3", count(case when "eventName"."name" = 'CRM - Регистрация обращения' and "process"."eventCount" = 1 and (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'result') not like 'Блок%' then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#4", count(distinct case when "eventName"."name" = 'CRM - Создание групповой проблемы' or "eventName"."name" = 'CRM - Регистрация обращения' and "process"."eventCount" = 1 and (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'result') in ('Связано с ГП', 'Массовая проблема') then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#5", count(distinct case when (select "processAttr"."valueStr" from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'd_gpl_fname') = 'Да' then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#6", count(distinct case when "cfn.pm_match_attr"(1642363404433, 1, "process"."uid", '"1ЛТП"  > "1ЛТП"* > "3ЛТП"+ > .*', 'supp_level', true) then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#7", count(distinct "event"."processUid") as "#8", count(distinct case when "cfn.pm_match_attr"(1642363404433, 2, "process"."uid", '"1ЛТП"  > "1ЛТП"* > ("2ЛТП" | "КДГ")+ > ("1ЛТП" | "2ЛТП" | "КДГ")* > "3ЛТП"+ > .*', 'supp_level', true) then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#9", count(distinct case when "cfn.pm_match_attr"(1642363404433, 3, "process"."uid", '"1ЛТП"  > "1ЛТП"* > ("2ЛТП" | "КДГ")+ > ("1ЛТП" | "2ЛТП" | "КДГ")* > ("1ЛТП" | "2ЛТП" | "КДГ")', 'supp_level', true) then "cfn.pm_uid_to_str"("event"."processUid") else null end) as "#10" from "process" as "process", "event" as "event" inner join "eventName" on "event"."modelUid" = "eventName"."modelUid" and "event"."nameId" = "eventName"."id" where exists(select 1 from "processAttr" where "processAttr"."processUid" = "process"."uid" and "processAttr"."name" = 'mrf_name' and "processAttr"."valueStr" in ('МРФ Волга', 'МРФ Дальний восток', 'МРФ Северо-Запад', 'МРФ Сибирь', 'МРФ Урал', 'МРФ Центр', 'МРФ Юг') limit 1) and "process"."modelUid" = "cfn.pm_str_to_uid"('03c66e84-e6b1-4eaa-904b-fe7200409440') and "process"."uid" = "event"."processUid" group by "#1", "#3";]])
```

**Actual behavior**

Memory shown in ps grows, valgrind reports memory leaks:

```
==700980== 30,888,880 bytes in 483,716 blocks are definitely lost in loss record 571 of 571
==700980==    at 0x4C360A5: malloc (vg_replace_malloc.c:380)
==700980==    by 0x4C1F71: sql_sized_malloc (malloc.c:53)
==700980==    by 0x4C208E: sqlMalloc (malloc.c:123)
==700980==    by 0x4C208E: dbMallocRawFinish (malloc.c:278)
==700980==    by 0x4C3E49: sqlVdbeMemGrow (mem.c:2188)
==700980==    by 0x4CA277: mem_from_mp (mem.c:2696)
==700980==    by 0x4E4201: vdbe_field_ref_fetch (vdbe.c:408)
==700980==    by 0x4E750D: sqlVdbeExec (vdbe.c:2077)
==700980==    by 0x4EA6BA: sqlStep (vdbeapi.c:304)
==700980==    by 0x4EA6BA: sql_step (vdbeapi.c:332)
==700980==    by 0x5A6CF6: sql_execute (execute.c:558)
==700980==    by 0x5A6CF6: sql_prepare_and_execute (execute.c:627)
==700980==    by 0x51299B: lbox_execute (execute.c:456)
==700980==    by 0x65545A: lj_BC_FUNCC (buildvm_x86.dasc:811)
==700980==    by 0x61B907: lua_pcall (lj_api.c:1158)
==700980== 
==700980== LEAK SUMMARY:
==700980==    definitely lost: 46,269,407 bytes in 804,016 blocks
==700980==    indirectly lost: 2,340 bytes in 14 blocks
==700980==      possibly lost: 19,300,320 bytes in 92,318 blocks
==700980==    still reachable: 4,059,750 bytes in 44,190 blocks
==700980==                       of which reachable via heuristic:
==700980==                         length64           : 64,720 bytes in 11 blocks
==700980==                         newarray           : 4,264 bytes in 1 blocks
==700980==         suppressed: 0 bytes in 0 blocks
```

See full log here: https://t.bk.ru/1eNoBEW/valgrind.log

**Expected behavior**

Memory usage is stable, no leaks are detected.

```
definitely lost: 0 bytes in 0 blocks
```

### PR DESCRIPTION
**Pull request by ImeevMA**
In some cases, when calling a user-defined function, some of the memory
allocated earlier could be lost. This patch fixes this problem.

NO_DOC=No need for doc in this case
NO_TEST=Currently there is no proper way to catch the missing memory

Closes #6789

### CODE REVIEW

File: src/box/sql/vdbe.c [hunk 1]
```diff
@@ -1265,7 +1265,7 @@ case OP_FunctionByName: {
 	uint32_t size;
 	struct Mem *mem = (struct Mem *)port_get_vdbemem(&ret, &size);
 	if (mem != NULL && size > 0)
-		*pOut = mem[0];
+		mem_copy(pOut, &mem[0]);
```
Comment (Gerold103) [inline src/box/sql/vdbe.c:1268]: Where is `mem` destroyed if you copy it instead of moving? The mem object itself is on the region, but its content could be on the heap, couldn't it?

File: changelogs/unreleased/gh-6789-fix-memleak-in-vdbe.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+## bugfix/sql
```
Comment (Gerold103) [inline changelogs/unreleased/gh-6789-fix-memleak-in-vdbe.md:1]: I had an impression that we are supposed to put NO_* tags in the end of the commit message (but before docbot request). So here it would be after `Closes`. But I don't know if there is a standard, so up to you. Besides, `NO_TEST` is not checked from what I see. So you don't need to write it.

File: src/box/sql/vdbe.c (hunk 1 above)
Comment (ImeevMA) [reply src/box/sql/vdbe.c]: True, I should be using mem_move() instead of mem_copy() here. Fixed.

File: changelogs/unreleased/gh-6789-fix-memleak-in-vdbe.md (hunk 2 above)
Comment (ImeevMA) [reply changelogs/unreleased/gh-6789-fix-memleak-in-vdbe.md:1]: I used this as an example: https://github.com/tarantool/tarantool/pull/6856

However, I agree that placing these tags after `Closes` makes it better.

Comment (Gerold103) [reply changelogs/unreleased/gh-6789-fix-memleak-in-vdbe.md:1]: Which tags are parsed right now you can check in `tools/check-commits` script. Maybe there is also a doc somewhere, but I didn't find.

**Review by Gerold103 — APPROVED** [review]

File: changelogs/unreleased/gh-6789-fix-memleak-in-vdbe.md (hunk 2 above)
Comment (Totktonada) [reply changelogs/unreleased/gh-6789-fix-memleak-in-vdbe.md:1]: I added `NO_TEST` in PR #6856 because it looks as a good companion of `NO_CHANGELOG` and `NO_DOC`: it is quite intuitive to find this information together. My motivation was not based on whether it is validated or not.

However @locker said that he want to add such check in a future.
