### PR TITLE
memtx: fix heap-use-after-free of tuple stories caused by space alter

### LINKED ISSUE #8781: ASAN: heap-use-after-free in memtx_tx_delete_gap
```console
Tarantool 3.0.0-entrypoint-256-g088b32f38
type 'help' for interactive help
```
Issue on ASAN run of `box/tx_man.test` with ASAN friendly small allocators. The issue is reproduced with PR https://github.com/tarantool/tarantool/pull/8665 refactoring MVCC too.

These allocators are not yet in upsteam. It is WIP in scope of #7327. Temporarily available in https://github.com/nshy/tarantool/tree/small-asan. One need to enable `box/tx_man.test` back to get the repro.

```
2023-06-16 11:40:18.861 [3552870] main/118/console/unix/: memtx_tx.c:636 W> Transaction committing DDL (id=684) has aborted another TX (id=682)
=================================================================
==3552870==ERROR: AddressSanitizer: heap-use-after-free on address 0x611000125e40 at pc 0x557667f255a7 bp 0x7fca5fef6a20 sp 0x7fca5fef6a18
WRITE of size 8 at 0x611000125e40 thread T0
    #0 0x557667f255a6 in rlist_del /home/shiny/dev/tarantool/src/lib/small/include/small/rlist.h:97:19
    #1 0x557667f255a6 in memtx_tx_delete_gap /home/shiny/dev/tarantool/src/box/memtx_tx.c:2830:2
    #2 0x557667f21f3f in memtx_tx_clear_txn_read_lists /home/shiny/dev/tarantool/src/box/memtx_tx.c:3198:3
    #3 0x557667f2ae43 in memtx_tx_clean_txn /home/shiny/dev/tarantool/src/box/memtx_tx.c:3225:2
    #4 0x5576681bcfd1 in txn_free /home/shiny/dev/tarantool/src/box/txn.c:432:2
    #5 0x5576681b826a in txn_complete_fail /home/shiny/dev/tarantool/src/box/txn.c:715:2
    #6 0x5576681bd367 in txn_rollback /home/shiny/dev/tarantool/src/box/txn.c:1132:2
    #7 0x5576681bf94e in box_txn_rollback /home/shiny/dev/tarantool/src/box/txn.c:1238:2
    #8 0x55766849f286 in lbox_rollback /home/shiny/dev/tarantool/src/box/lua/init.c:339:6
    #9 0x5576686c3752 in lj_BC_FUNCC /home/shiny/dev/tarantool/build-asan-release/third_party/luajit/src/lj_vm.S:811
    #10 0x5576686deec5 in lua_pcall /home/shiny/dev/tarantool/third_party/luajit/src/lj_api.c:1163:12
    #11 0x557668551a21 in luaT_call /home/shiny/dev/tarantool/src/lua/utils.c:618:6
    #12 0x55766853eca2 in lua_fiber_run_f /home/shiny/dev/tarantool/src/lua/fiber.c:416:11
    #13 0x557667e3ede8 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) /home/shiny/dev/tarantool/src/lib/core/fiber.h:1234:10
    #14 0x5576685b543f in fiber_loop /home/shiny/dev/tarantool/src/lib/core/fiber.c:1002:18
    #15 0x557668f38c3c in coro_init /home/shiny/dev/tarantool/third_party/coro/coro.c:108:3

0x611000125e40 is located 192 bytes inside of 208-byte region [0x611000125d80,0x611000125e50)
freed by thread T0 here:
    #0 0x557667defd92 in __interceptor_free.part.0 asan_malloc_linux.cpp.o
    #1 0x557667f25c9e in memtx_tx_on_space_delete /home/shiny/dev/tarantool/src/box/memtx_tx.c:2882:3
    #2 0x557668114ac3 in space_delete /home/shiny/dev/tarantool/src/box/space.c:394:2
    #3 0x55766817de68 in alter_space_commit(trigger*, void*) /home/shiny/dev/tarantool/src/box/alter.cc:829:2
    #4 0x55766862687c in trigger_run_list(rlist*, void*) /home/shiny/dev/tarantool/src/lib/core/trigger.cc:119:7
    #5 0x557668626bbd in trigger_run_reverse /home/shiny/dev/tarantool/src/lib/core/trigger.cc:166:9
    #6 0x5576681b9095 in txn_complete_success /home/shiny/dev/tarantool/src/box/txn.c:734:7
    #7 0x5576681c5c3b in txn_on_journal_write /home/shiny/dev/tarantool/src/box/txn.c:791:3
    #8 0x5576682c0cf4 in journal_async_complete /home/shiny/dev/tarantool/src/box/journal.h:257:2
    #9 0x5576682c0cf4 in tx_schedule_queue /home/shiny/dev/tarantool/src/box/wal.c:283:3
    #10 0x5576682bfcb8 in tx_complete_batch /home/shiny/dev/tarantool/src/box/wal.c:379:2
    #11 0x5576685caf20 in cmsg_deliver /home/shiny/dev/tarantool/src/lib/core/cbus.c:375:2
    #12 0x5576685ce2fd in cbus_process /home/shiny/dev/tarantool/src/lib/core/cbus.c:610:3
    #13 0x557668f1089e in ev_invoke_pending /home/shiny/dev/tarantool/third_party/libev/ev.c:3797:11
    #14 0x557668f12dc0 in ev_run /home/shiny/dev/tarantool/third_party/libev/ev.c:4221:7
    #15 0x557667e3d13c in main /home/shiny/dev/tarantool/src/main.cc:850:4
    #16 0x7fca7423984f in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16

previously allocated by thread T0 here:
    #0 0x557667df0dc9 in malloc (/home/shiny/dev/tarantool/build-asan-release/src/tarantool+0x928dc9) (BuildId: e40fe54fec946c1ad56d193b06a0af542eecc072)
    #1 0x557667f366f6 in mempool_alloc /home/shiny/dev/tarantool/src/lib/small/include/small/mempool_malloc.h:96:56
    #2 0x557667f29ac9 in memtx_tx_story_new /home/shiny/dev/tarantool/src/box/memtx_tx.c:855:52
    #3 0x557667f1b89d in memtx_tx_history_add_insert_stmt /home/shiny/dev/tarantool/src/box/memtx_tx.c:1960:34
    #4 0x557667f5ea47 in memtx_space_replace_all_keys /home/shiny/dev/tarantool/src/box/memtx_space.c:287:10
    #5 0x557667f6c740 in memtx_space_replace_tuple /home/shiny/dev/tarantool/src/box/memtx_space.c:358:11
    #6 0x557667f6034b in memtx_space_execute_replace /home/shiny/dev/tarantool/src/box/memtx_space.c:402:6
    #7 0x557668117f98 in space_execute_dml /home/shiny/dev/tarantool/src/box/space.c:807:7
    #8 0x5576681dcc75 in box_process_rw /home/shiny/dev/tarantool/src/box/box.cc:452:6
    #9 0x5576681f886e in box_replace /home/shiny/dev/tarantool/src/box/box.cc:3434:9
    #10 0x5576684c7e2e in lbox_replace /home/shiny/dev/tarantool/src/box/lua/index.c:76:11
    #11 0x5576686c3752 in lj_BC_FUNCC /home/shiny/dev/tarantool/build-asan-release/third_party/luajit/src/lj_vm.S:811

SUMMARY: AddressSanitizer: heap-use-after-free /home/shiny/dev/tarantool/src/lib/small/include/small/rlist.h:97:19 in rlist_del
Shadow bytes around the buggy address:
  0x0c228001cb70: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c228001cb80: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c228001cb90: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c228001cba0: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c228001cbb0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c228001cbc0: fd fd fd fd fd fd fd fd[fd]fd fa fa fa fa fa fa
  0x0c228001cbd0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c228001cbe0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c228001cbf0: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c228001cc00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c228001cc10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3552870==ABORTING
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Closes #8781

### CODE REVIEW

File: src/box/memtx_tx.c [hunk 1]
```diff
@@ -2943,6 +2944,17 @@ memtx_tx_on_space_delete(struct space *space)
...
+		for (uint32_t i = 0; i < story->index_count; i++) {
+			while (!rlist_empty(&story->link[i].read_gaps)) {
+				struct rlist *read_gaps =
+					&story->link[i].read_gaps;
+				struct gap_item_base *item =
+					rlist_first_entry(read_gaps,
+							  struct gap_item_base,
+							  in_read_gaps);
+				memtx_tx_delete_gap(item);
+			}
```
Comment (drewdzzz) [inline src/box/memtx_tx.c:2956]: Nit: it would be more convenient to write `struct rlist *read_gaps = &story->link[i].read_gaps;` before the `while` loop.

File: src/box/memtx_tx.c [hunk 2]
```diff
@@ -955,6 +955,7 @@ memtx_tx_story_delete(struct memtx_story *story)
 	for (uint32_t i = 0; i < story->index_count; i++) {
 		assert(story->link[i].newer_story == NULL);
 		assert(story->link[i].older_story == NULL);
+		assert(rlist_empty(&story->link[i].read_gaps));
```
Comment (drewdzzz) [inline src/box/memtx_tx.c:958]: Nit: would be nice to describe these expectations in the function description.

**Review by drewdzzz — APPROVED** [review]
LGTM, just a couple nitpicks. Also, CI is red, so please make sure that the reason is a flaky test, not your patch.

File: changelogs/unreleased/gh-8781-heap-use-after-free-in-memtx-tx-delete-gap.md [hunk 3]
```diff
@@ -0,0 +1,4 @@
+## bugfix/memtx
+
+* Fixed a heap-use-after-free bug in transaction manager which could occur
+  during a DDL operation happening concurrently with a transaction (gh-8781).
```
Comment (p7nov) [inline changelogs/unreleased/gh-8781-heap-use-after-free-in-memtx-tx-delete-gap.md:4]:
```suggestion
* Fixed a heap-use-after-free bug in the transaction manager, which could occur
  when performing a DDL operation concurrently with a transaction (gh-8781).
```

**Review by p7nov — APPROVED** [review]
Please see my suggestion on the changelog.

File: changelogs/unreleased/gh-8781-heap-use-after-free-in-memtx-tx-delete-gap.md (hunk 3 above)
Comment (CuriousGeorgiy) [reply changelogs/unreleased/gh-8781-heap-use-after-free-in-memtx-tx-delete-gap.md]: Fixed.

File: src/box/memtx_tx.c (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tx.c]: Fixed.

File: src/box/memtx_tx.c (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tx.c:960]: Fixed, moved the comment above to the function level. I guess _fully unlinked_ also describes gaps.

**Review by alyapunov — APPROVED** [review]

**Comment by alyapunov** [comment]
Backported to 2.11 and 2.10.
