### PR TITLE
config: expand vars in `any` nodes

### LINKED ISSUE #10595: config: context variables do not work in roles_cfg.<...> and app.cfg.<...>
Version: all existing tarantool 3.x (tested on 3.2.0).

Config:

```yaml
config:
  context:
    title:
      from: env
      env: TITLE

process:
  title: '{{ context.title }}'

app:
  cfg:
    title: '{{ context.title }}'

roles_cfg:
  foo:
    title: '{{ context.title }}'

groups:
  g:
    replicasets:
      r:
        instances:
          i-001: {}
```

Test:

```lua
$ TITLE=xxx tarantool -i --name i-001 --config config.yaml
tarantool> config = require('config')

tarantool> config:get('process.title')
---
- xxx
...

tarantool> config:get('app.cfg.title')
---
- '{{ context.title }}'
...

tarantool> config:get('roles_cfg.foo.title')
---
- '{{ context.title }}'
...
```

<details>
<summary>And the same for built-in replacements</summary>

```yaml
process:
  title: '{{ instance_name }}'

app:
  cfg:
    title: '{{ instance_name }}'

roles_cfg:
  foo:
    title: '{{ instance_name }}'

groups:
  g:
    replicasets:
      r:
        instances:
          i-001: {}
```

```lua
$ tarantool -i --name i-001 --config config.yaml
tarantool> config = require('config')

tarantool> config:get('process.title')
---
- i-001
...

tarantool> config:get('app.cfg.title')
---
- '{{ instance_name }}'
...

tarantool> config:get('roles_cfg.foo.title')
---
- '{{ instance_name }}'
...
```
</details>

The reason is that `app.cfg.<...>` and `roles_cfg.<...>` have `any` type and this type is not traversed down by the `<schema object>:map()` method.

https://github.com/tarantool/tarantool/blob/f1144c533b6c52c324ffe1cc4fcaeab1f2f6cd9f/src/box/lua/config/instance_config.lua#L444

Also tracked in TNTP-372

### PR DESCRIPTION
**Pull request by mandesero**
Template variables (e.g. `{{ context.title }}`, `{{ instance_name }})` are now expanded inside `app.cfg.*` and `roles_cfg.*` (`any` type fields).

Closes #10595

### CODE REVIEW

File: src/box/lua/config/instance_config.lua [hunk 1]
```diff
@@ -188,15 +188,41 @@ local function instance_uri(self, iconfig, advertise_type, opts)
...
+        return (str:gsub('{{%s*(.-)%s*}}', function(var_name)
+            local v = vars[var_name]
+            if v ~= nil then
+                return tostring(v)
             end
             w.error(('Unknown variable %q'):format(var_name))
         end))
     end
+
+    local function traverse_inplace(val, seen)
```
Comment (Totktonada) [inline src/box/lua/config/instance_config.lua]: I would consider some solution on the `utils/schema.lua` level. Can we adjust `<schema object>:map()` to traverse composite types down similarly as we do that for `<schema object>:get()` (#10206)?

File: src/box/lua/config/instance_config.lua [hunk 2]
```diff
@@ -188,15 +188,41 @@ local function instance_uri(self, iconfig, advertise_type, opts)
...
+        if t == 'string' then
+            return subst(val)
+        elseif t ~= 'table' then
+            return val
+        end
+        seen = seen or {}
+        if seen[val] then
+            return val
+        end
+        seen[val] = true
```
Comment (georgiy-belyanin) [inline src/box/lua/config/instance_config.lua]: Minor: if this code remains the same I'd ask for a small comment why it is important to mark tables as "seen": it is due to recursive tables, YAML anchors or just in case.

File: src/box/lua/config/instance_config.lua (hunk 1 above)
Comment (mandesero) [reply src/box/lua/config/instance_config.lua]: I moved the logic to **utils/schema.lua** and removed it from `instance_config.lua`, now `apply_vars_f` expands `{{...}}` only when the value is a **string** (including `any` type).

File: src/box/lua/config/instance_config.lua (hunk 2 above)
Comment (mandesero) [reply src/box/lua/config/instance_config.lua]: Thanks! That code was removed in the refactor (traversal moved to `utils/schema.lua`), so a `seen` set isn’t needed anymore. Marking this as resolved.

File: src/box/lua/config/utils/schema.lua [hunk 3]
```diff
@@ -1277,6 +1277,33 @@ local function map_impl(schema, data, f, ctx)
...
+            end
+
+            local res = {}
+            for k, v in pairs(data) do
+                walkthrough_enter(ctx, k)
+                res[k] = map_impl(schema, v, f, ctx)
+                walkthrough_leave(ctx)
+            end
+            return res
+        end
```
Comment (Totktonada) [inline src/box/lua/config/utils/schema.lua]: Nit: I would like to extract it from this function like we do in `get_schemaless` and `merge_schemaless`. I would also highlight that:

* these `*_schemaless` methods don't accept a schema node object
* I wouldn't pass the schema node to the transformation function (in `w.schema`), because the passed value doesn't correspond to any schema node directly.

File: src/box/lua/config/utils/schema.lua [hunk 4]
```diff
@@ -1277,6 +1277,33 @@ local function map_impl(schema, data, f, ctx)
...
+                end
+                return res
+            end
+
+            local res = {}
+            for k, v in pairs(data) do
+                walkthrough_enter(ctx, k)
+                res[k] = map_impl(schema, v, f, ctx)
+                walkthrough_leave(ctx)
+            end
```
Comment (Totktonada) [inline src/box/lua/config/utils/schema.lua]: Nit: Is there a reason to split these array/non-array scenarios? We can just always use `pairs`.

Comment (Totktonada) [inline src/box/lua/config/utils/schema.lua]: Nit: We transform keys for `map` schema nodes. I'm not sure that it is a good idea, TBH, but I would do it here too for consistency.

It adds an interesting ability to assign some value *to the given instance* inside a per-instance mapping:

```yaml
app:
  cfg:
    rpc_priority:
      i-001: 1
      i-002: 2
      i-003: 3
      '{{ instance_name }}': 99
```

File: test/config-luatest/expand_any_test.lua
Comment (Totktonada) [inline test/config-luatest/expand_any_test.lua:1]: Sorry for the chores, but I would like to have some schema.lua level test cases in `test/config-luatest/schema_test.lua`.

File: src/box/lua/config/utils/schema.lua [hunk 5]
```diff
@@ -1277,6 +1311,13 @@ local function map_impl(schema, data, f, ctx)
     data = f(data, w, ctx.f_ctx)
 
     if is_scalar(schema) then
+        if schema.type == 'any' then
+            if data == nil or type(data) ~= 'table' then
+                return data
+            end
+
+            return map_schemaless(data, f, ctx)
```
Comment (Totktonada) [inline src/box/lua/config/utils/schema.lua]: This way we perform the user-provided transformation twice for the data of the `any` type.

File: src/box/lua/config/utils/schema.lua [hunk 6]
```diff
@@ -1264,6 +1264,40 @@ end
...
+    }
+    data = f(data, w, ctx.f_ctx)
+
+    if data == nil or type(data) ~= 'table' then
+        return data
+    end
+
+    if visited[data] ~= nil then
+        return visited[data]
+    end
```
Comment (Totktonada) [inline src/box/lua/config/utils/schema.lua]: Should we check it before calling the user-provided transformation function?

File: test/config-luatest/schema_test.lua [hunk 7]
```diff
@@ -2680,6 +2681,132 @@ g.test_map_map_itself = function()
...
+    if data ~= nil and type(data) == 'string' then
+        return (data:gsub('{{ *(.-) *}}', function(var_name)
+            if vars[var_name] ~= nil then
+                return vars[var_name]
+            end
+            w.error(('Unknown variable %q'):format(var_name))
+        end))
+    end
+    return data
+end
```
Comment (Totktonada) [inline test/config-luatest/schema_test.lua]: Nit: It is almost same as `apply_vars` above (in the `Testing helpers for <schema object>:map()` section). Can we reuse it?

Even if not, I would move this helper function to the `Testing helpers for <schema object>:map()` section.

Comment (mandesero) [reply test/config-luatest/schema_test.lua]: The two functions were slightly different in their handling of strings and schema checks, but I ended up unifying them into a single `apply_vars` so now the logic is shared.

File: src/box/lua/config/utils/schema.lua (hunk 6 above)
Comment (mandesero) [reply src/box/lua/config/utils/schema.lua]: Yes, we can. I’ve moved the `visited[data]` check before calling the user-provided function.

File: src/box/lua/config/utils/schema.lua (hunk 5 above)
Comment (mandesero) [reply src/box/lua/config/utils/schema.lua]: Yes, you're right. I've handled the `is_scalar(schema) and schema.type == 'any'` case separately, so the user-provided transformation isn't applied twice.

File: test/config-luatest/expand_any_test.lua
Comment (mandesero) [reply test/config-luatest/expand_any_test.lua:1]: I’ve added the requested schema.lua–level test cases in `test/config-luatest/schema_test.lua`, and also extended the suite with additional checks for YAML anchors.

File: src/box/lua/config/utils/schema.lua (hunk 4 above)
Comment (mandesero) [reply src/box/lua/config/utils/schema.lua]: Done.

Comment (mandesero) [reply src/box/lua/config/utils/schema.lua]: Fixed.

File: src/box/lua/config/utils/schema.lua (hunk 3 above)
Comment (mandesero) [reply src/box/lua/config/utils/schema.lua]: Done.

File: test/config-luatest/schema_test.lua [hunk 8]
```diff
@@ -2296,20 +2297,26 @@ end
 -- It substitutes ${x} patterns in string values with given
 -- variables.
```
Comment (Totktonada) [inline test/config-luatest/schema_test.lua]: Nit: This comment needs an update (or we can use `${<...>}` variables in the new test cases).

File: src/box/lua/config/utils/schema.lua [hunk 9]
```diff
@@ -1264,16 +1264,56 @@ end
...
+
+    return res
+end
+
 local function map_impl(schema, data, f, ctx)
     -- Call the user-provided transformation function.
     --
     -- It is called on a current node before its descandants,
     -- implementing the pre-order traversal.
```
Comment (Totktonada) [inline src/box/lua/config/utils/schema.lua]: Nit: This comment relates to the `f(<...>)` call and now some unrelated code is between the comment and the call itself.

File: src/box/lua/config/utils/schema.lua (hunk 6 above)
Comment (Totktonada) [reply src/box/lua/config/utils/schema.lua]: Hm. We check `visited[data]` before `data = f(data, <...>)`, but assign `visited[data]` after it.

Comment (Totktonada) [reply src/box/lua/config/utils/schema.lua]: Now `data` is named `old` or `new` before/after the `f()` call. And the recursion detection is based on the `new` -> `res` mapping. Looks OK for me, thanks for the update!

**Review by Totktonada — APPROVED** [review]
Thank you!

**Review by maryiaLichko — APPROVED** [review]
