### PR TITLE
txn: forbid waiting for acks on fully local transactions

### LINKED ISSUE #12585: Truncate doesn't work with local spaces and synchronous replication
**Bug description**

The issue exists on both 2.11 and master.

To reproduce:
1. Start one tarantool instance in interactive mode.
2. Issue:
```lua
box.cfg()
box.ctl.promote()
box.schema.space.create('test', {is_local=true})
box.space.test:create_index('pk')
box.space._truncate:alter{is_sync=true}
box.space.test:insert{1,2,3}
box.space.test:truncate()
```

On tarantool 3.x (tested on recent master) the `truncate()` will fail with `error: An attempt to commit a fully local transaction synchronously`.
On tarantool 2.11 the call will succeed, but the resulting xlogs will become unrecoverable:
```
2026-04-20 16:21:47.503 [577387] main/105/interactive I> recover from `./00000000000000000000.xlog'
2026-04-20 16:21:47.503 [577387] main/105/interactive box.cc:834 E> couldn't commit a recovery transaction
2026-04-20 16:21:47.503 [577387] main/105/interactive txn.c:1033 E> ER_UNSUPPORTED: Tarantool does not support Non-blocking commit of a synchronous txn
2026-04-20 16:21:47.503 [577387] main/105/interactive F> can't initialize storage: Tarantool does not support Non-blocking commit of a synchronous txn
```

JIRA issue: https://jira.vk.team/browse/TNTP-7411

### PR DESCRIPTION
**Pull request by Serpentian**
Closes #12585

### CODE REVIEW

**Comment by Serpentian** [comment]
Applied the following patch from the discussion with @Gerold103:

<details><summary>Details</summary>
<p>

```diff
diff --git a/src/box/txn.c b/src/box/txn.c
index ee5a102191..fae1f6e645 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -956,17 +956,8 @@ txn_journal_entry_new(struct txn *txn)
 
 	struct xrow_header **remote_row = req->rows;
 	struct xrow_header **local_row = req->rows + txn->n_applier_rows;
-	bool is_sync = txn_has_flag(txn, TXN_WAIT_ACK);
-
-	/*
-	 * Can't commit a fully local transaction synchronously, if explicitly
-	 * requested with `is_sync` option. It makes no sense in doing that.
-	 */
-	if (is_sync && txn_is_fully_local(txn)) {
-		diag_set(IllegalParams, "An attempt to commit a fully local "
-			 "transaction synchronously");
-		return NULL;
-	}
+	bool is_force_sync = txn_has_flag(txn, TXN_WAIT_ACK);
+	bool is_sync = is_force_sync;
 
 	/*
 	 * A transaction which consists of NOPs solely should pass through the
@@ -1002,16 +993,29 @@ txn_journal_entry_new(struct txn *txn)
 
 		req->approx_len += xrow_approx_len(stmt->row);
 	}
-	/*
-	 * There is a check for all-local rows, because it may happen, that
-	 * fully local transaction becomes synchronous, if some sophisticated
-	 * space is modified (e.g. synchronous `_truncate`, in which whether
-	 * the row is local or remote depends on the truncated space): in such
-	 * case the transaction is added to limbo with `TXN_WAIT_SYNC` flag
-	 * iff limbo is not empty.
-	 */
 	if (!txn_has_flag(txn, TXN_FORCE_ASYNC) && !is_fully_nop) {
-		if (is_sync && !txn_is_fully_local(txn)) {
+		bool is_fully_local = txn_is_fully_local(txn);
+		/*
+		 * Can't commit a fully local transaction synchronously, if
+		 * explicitly requested with `is_sync` option. It makes no
+		 * sense in doing that.
+		 */
+		if (is_force_sync && is_fully_local) {
+			diag_set(IllegalParams,
+				 "An attempt to commit a fully local "
+				 "transaction synchronously");
+			return NULL;
+		}
+		/*
+		 * There is a check for all-local rows, because it may happen,
+		 * that fully local transaction becomes synchronous, if some
+		 * sophisticated space is modified (e.g. synchronous
+		 * `_truncate`, in which whether the row is local or remote
+		 * depends on the truncated space): in such case the
+		 * transaction is added to limbo with `TXN_WAIT_SYNC` flag iff
+		 * limbo is not empty.
+		 */
+		if (is_sync && !is_fully_local) {
 			txn_set_flags(txn, TXN_WAIT_SYNC | TXN_WAIT_ACK);
 		} else if (!txn_limbo_is_empty(&txn_limbo)) {
 			/*
```

</p>
</details>

File: src/box/txn.c [hunk 1]
```diff
@@ -996,22 +993,29 @@ txn_journal_entry_new(struct txn *txn)
...
-			/*
-			 * Can't commit a fully local transaction synchronously.
-			 */
-			if (txn_is_fully_local(txn)) {
-				diag_set(IllegalParams,
-					 "An attempt to commit a fully local "
-					 "transaction synchronously");
-				return NULL;
-			}
+		bool is_fully_local = txn_is_fully_local(txn);
```
Comment (Gerold103) [inline src/box/txn.c]: This is only used when `is_sync` is true (which happens also when `is_force_sync` is true + when a synchronous space is touched). But async txns this line seems unnecessary. Lets then only calculate it when `is_sync` is true. Previously it was also like this, right? Can we keep that?

File: test/replication-luatest/gh_12585_sync_truncate_with_local_space_test.lua [hunk 2]
```diff
@@ -0,0 +1,109 @@
+local t = require('luatest')
+local server = require('luatest.server')
+local replica_set = require('luatest.replica_set')
+
+local g = t.group('sync-truncate-with-local-space')
```
Comment (Gerold103) [inline test/replication-luatest/gh_12585_sync_truncate_with_local_space_test.lua]: Lets give the test file and case the `qsync` prefix, not just `sync`. It is often quite convenient, because allows to run almost all synchro replication tests by 2 keywords: `qsync election`.

File: test/replication-luatest/gh_12585_qsync_truncate_with_local_space_test.lua [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+    g.replica_set = replica_set:new{}
+    local box_cfg = {
+        replication_timeout = 0.1,
+        replication_synchro_quorum = 3,
+        replication_synchro_timeout = 600,
+        election_mode = 'manual',
+        replication = {
+            server.build_listen_uri('master', g.replica_set.id),
+            server.build_listen_uri('replica', g.replica_set.id),
+        },
```
Comment (Gerold103) [inline test/replication-luatest/gh_12585_qsync_truncate_with_local_space_test.lua:18]: You might want to disable the fencing, if the `replication_timeout` is so small. Otherwise on a slow machine the leader might step down anywhere in the test.

**Review by Gerold103 — COMMENTED** [review]
🔥🚀⚡️

File: test/replication-luatest/gh_12585_qsync_truncate_with_local_space_test.lua (hunk 3 above)
Comment (Serpentian) [reply test/replication-luatest/gh_12585_qsync_truncate_with_local_space_test.lua:18]: The test was not flaky, but I added it anyway, just for safety

File: test/replication-luatest/gh_12585_sync_truncate_with_local_space_test.lua (hunk 2 above)
Comment (Serpentian) [reply test/replication-luatest/gh_12585_sync_truncate_with_local_space_test.lua]: Sure, done

File: src/box/txn.c (hunk 1 above)
Comment (Serpentian) [reply src/box/txn.c]: I don't like the way code looks, when we do that. Due to duplicated if case:

```c
if (!txn_limbo_is_empty(&txn_limbo)) {
     txn_set_flags(txn, TXN_WAIT_SYNC);
}
```

And there's no way to get rid of it, if we wanna check for `is_fully_local` only on synchronous code path. We must treat fully local implicitly synchronous transaction as async.

But anyway did that, it may be worth performance-wise, though that compare of 4 numbers in `txn_is_fully_local` on async path would not affect perf that much, IMHO.

P.S. I've left the `is_force_sync` variable on async path, because readability of the code already tends to zero now and with `txn_has_flag(txn, TXN_WAIT_ACK)` check instead it will be even worse.

File: src/box/txn.c [hunk 4]
```diff
@@ -960,7 +956,8 @@ txn_journal_entry_new(struct txn *txn)
```
Comment (sergepetrenko) [inline src/box/txn.c:956]: Missing word in the commit message:
> We recommend making all spaces synchronous (including the system ones)
when **the user** has at least one of them

**Comment by sergepetrenko** [comment]
@Serpentian @Gerold103 what do you think of the following alternative patch?

<details><summary>diff</summary>

```diff
diff --git a/src/box/txn.c b/src/box/txn.c
index 5e77a6ffc0..3032b7f133 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -981,8 +981,18 @@ txn_journal_entry_new(struct txn *txn)
 
                if (stmt->row->type != IPROTO_NOP) {
                        is_fully_nop = false;
+                       /*
+                        * _truncate is the only space which can be synchronous
+                        * and produce local rows at the same time (when
+                        * truncation is done for a local space). Do not treat
+                        * such row as synchronous.
+                        */
+                       assert(stmt->row->group_id != GROUP_LOCAL ||
+                              !space_is_sync(stmt->space) ||
+                              space_id(stmt->space) == BOX_TRUNCATE_ID);
                        is_sync = is_sync || (stmt->space != NULL &&
-                                             space_is_sync(stmt->space));
+                                             space_is_sync(stmt->space) &&
+                                             stmt->row->group_id != GROUP_LOCAL);
                }
 
                if (stmt->row->replica_id == 0)
```

</details>

IMO it turns out easier to understand and there is no extra branching lower, where we support `txn_is_fully_local` as being "valid" synchro txn just for the sake of _truncate.

Side note, not to be done now: why do we even decide on txn being sync/async so late? This could be done right when we apply each txn statement, or during `txn_add_redo`

File: changelogs/unreleased/gh-12585-qsync-truncate-local-space.md [hunk 5]
```diff
@@ -0,0 +1,4 @@
+## bugfix/box
+
+* Fixed a bug where a local space could not be truncated when `_truncate`
+  space is synchronous (gh-12585).
```
Comment (lenkis) [inline changelogs/unreleased/gh-12585-qsync-truncate-local-space.md]:
```suggestion
* Fixed a bug where a local space could not be truncated when the `_truncate`
  space was synchronous (gh-12585).
```

**Review by lenkis — APPROVED** [review]

File: src/box/txn.c (hunk 4 above)
Comment (Serpentian) [reply src/box/txn.c:956]: Fixed

File: changelogs/unreleased/gh-12585-qsync-truncate-local-space.md (hunk 5 above)
Comment (Serpentian) [reply changelogs/unreleased/gh-12585-qsync-truncate-local-space.md]: Fixed

**Comment by Serpentian** [comment]
I really like the version, Sergey proposes. It doesn't add new checks to async path and is easily readable. Applied. @Gerold103, WDYT?

**Comment by Gerold103** [comment]
> Side note, not to be done now: why do we even decide on txn being sync/async so late? This could be done right when we apply each txn statement, or during txn_add_redo

Because a synchro statement can be rolled back. For example using a savepoint rollback. It would require to revisit every previous statement then to recalculate the synchro-flag. But since we iterate the statements right before commit anyway, we piggyback some checks into this final loop.

File: src/box/txn.c (hunk 1 above)
Comment (Gerold103) [reply src/box/txn.c]: I like the Sergey's proposed patch, looks clean! Thanks also for investigating what I proposed abvove.

**Review by Gerold103 — APPROVED** [review]

**Comment by sergepetrenko** [comment]
@Serpentian, please backport to 2.11
