### PR TITLE
limbo: fix a crash in linearization point waiting

### LINKED ISSUE #11807: qsync: txn_limbo_wait_last_txn segfaults
Version: Tarantool Enterprise 3.6.0-entrypoint-0-g8d730c4

Caught on the `enterprise-luatest/config_storage_test.lua` test, on the `test_status` test case.

```
[009] enterprise-luatest/config_storage_test.lua      config-storage-extra.test_status    [ fail ]
[009] Test failed! Output from reject file /tmp/t/rejects/enterprise-luatest/config_storage.reject:
[009] Tarantool version is 3.6.0-entrypoint-0-g8d730c4
[009] TAP version 13
[009] 1..1
[009] # Started on Fri Aug 29 14:28:59 2025
[009] # Starting group: config-storage-extra
[009] not ok 1	config-storage-extra.test_status
[009] #   Peer closed
[009] #   stack traceback:
[009] #   	builtin/box/net_box.lua:935: in function '_request'
[009] #   	builtin/box/net_box.lua:982: in function 'eval'
[009] #   	...arantool/test/enterprise-luatest/config_storage_test.lua:92: in function 'start_replicaset'
[009] #   	...arantool/test/enterprise-luatest/config_storage_test.lua:1430: in function 'config-storage-extra.test_status'
```

Logs from the `cs-001` instance:

```
cs-001 | 2025-08-29 14:29:10.867 [23859] main main.cc:1083 I> entering the event loop
cs-001 | 2025-08-29 14:29:10.867 [23859] main/120/applier/replicator@unix/:./cs-003.iproto raft.c:507 I> RAFT: message {term: 2, vote: 1, leader: 1, state: follower} from 3
cs-001 | 2025-08-29 14:29:10.867 [23859] main/120/applier/replicator@unix/:./cs-003.iproto raft.c:562 I> RAFT: vote request is skipped - can't accept vote for self if not a candidate
cs-001 | 2025-08-29 14:29:10.867 [23859] main/120/applier/replicator@unix/:./cs-003.iproto raft.c:507 I> RAFT: message {term: 2, vote: 1, leader: 1, state: follower} from 3
cs-001 | 2025-08-29 14:29:10.867 [23859] main/120/applier/replicator@unix/:./cs-003.iproto raft.c:562 I> RAFT: vote request is skipped - can't accept vote for self if not a candidate
cs-001 | 2025-08-29 14:29:10.867 [23859] main/119/applier/replicator@unix/:./cs-002.iproto raft.c:507 I> RAFT: message {term: 2, vote: 1, state: follower} from 2
cs-001 | 2025-08-29 14:29:10.867 [23859] main/119/applier/replicator@unix/:./cs-002.iproto raft.c:562 I> RAFT: vote request is skipped - can't accept vote for self if not a candidate
cs-001 | 2025-08-29 14:29:10.867 [23859] main/119/applier/replicator@unix/:./cs-002.iproto raft.c:507 I> RAFT: message {term: 2, vote: 1, state: follower} from 2
cs-001 | 2025-08-29 14:29:10.867 [23859] main/119/applier/replicator@unix/:./cs-002.iproto raft.c:562 I> RAFT: vote request is skipped - can't accept vote for self if not a candidate
cs-001 | 2025-08-29 14:29:10.948 [23859] main/117/main box.cc:5303 I> subscribed replica 2d709328-adbf-4269-93f4-8c0ca4c029d8 at fd 56, aka unix/:(socket), peer of unix/:(socket)
cs-001 | 2025-08-29 14:29:10.948 [23859] main/117/main box.cc:5305 I> remote vclock {1: 31} local vclock {0: 8, 1: 31}
cs-001 | Segmentation fault
cs-001 |   code: SEGV_MAPERR
cs-001 |   addr: 0x10
cs-001 |   context: 0x55fd751fe7c0
cs-001 |   siginfo: 0x55fd751fe8f0
cs-001 |   rax      0x0                0
cs-001 |   rbx      0x4008d540         1074320704
cs-001 |   rcx      0x0                0
cs-001 |   rdx      0x0                0
cs-001 |   rsi      0x20               32
cs-001 |   rdi      0x7f0827236038     139672993095736
cs-001 |   rsp      0x7f0804080a80     139672404101760
cs-001 |   rbp      0x7f0804080b60     139672404101984
cs-001 |   r8       0x55fd71fe081e     94547027560478
cs-001 |   r9       0xee2a             60970
cs-001 |   r10      0x14120f4          21045492
cs-001 |   r11      0x293              659
cs-001 |   r12      0x0                0
cs-001 |   r13      0x0                0
cs-001 |   r14      0x4008e0a0         1074323616
cs-001 |   r15      0x55fd71e151cc     94547025678796
cs-001 |   rip      0x55fd71ce51dd     94547024433629
cs-001 |   eflags   0x10246            66118
cs-001 |   cs       0x33               51
cs-001 |   gs       0x0                0
cs-001 |   fs       0x0                0
cs-001 |   cr2      0x10               16
cs-001 |   err      0x4                4
cs-001 |   oldmask  0x0                0
cs-001 |   trapno   0xe                14
cs-001 | Current time: 1756466950
cs-001 | Please file a bug at https://github.com/tarantool/tarantool/issues
cs-001 | Attempting backtrace... Note: since the server has already crashed,
cs-001 | this may fail as well
cs-001 | #1  0x55fd71fd4d00 in crash_collect+252
cs-001 | #2  0x55fd71fd5734 in crash_signal_cb+96
cs-001 | #3  0x7f0827d996b0 in __sigaction+64
cs-001 | #4  0x55fd71ce51dd in txn_limbo_wait_last_txn+308
cs-001 | #5  0x55fd71cf9c23 in box_wait_linearization_point+427
cs-001 | #6  0x55fd71cde0fa in txn_make_linearizable+243
cs-001 | #7  0x55fd71cde5de in box_txn_set_isolation+643
cs-001 | #8  0x55fd71e1524e in lbox_txn_set_isolation(lua_State*)+130
cs-001 | #9  0x55fd72047417 in lj_BC_FUNCC+70
cs-001 | #10 0x55fd72054e03 in lua_pcall+965
cs-001 | #11 0x55fd71fad5fd in luaT_call+41
cs-001 | #12 0x55fd71fa25d1 in lua_fiber_run_f+185
cs-001 | #13 0x55fd71b90364 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+30
cs-001 | #14 0x55fd71fe146b in fiber_loop+215
cs-001 | #15 0x55fd72373a93 in coro_init+116
```

I'll add more details once I get a stable reproducer.

### PR DESCRIPTION
**Pull request by Gerold103**
The DB state synchronization for a linearizable transaction is trying to wait for the receipt of all potentially confirmed synchro txns from a remote master, and then waits for their confirmation locally. Thus guaranteeing, that if any transaction was committed on the master before this point, then it is now visible on the current replica too.

Waiting for the synchro txns confirmation was done in a way that if the limbo isn't empty, then it 100% must contain a synchro txn in it.

But it is not always so. Sometimes it might contain a volatile async txn, which isn't written to WAL yet. Or it might even contain dummy entries created by the limbo flush operation (for a snapshot, for a new replica join). About these things the linearization sync must not care and should treat them like if the limbo is empty.

Note that there might be more places where txn_limbo_is_empty() seems not exactly 100% safe to use, but for none of them a reproducer could be designed. The other places might actually be safe until proven otherwise.

Closes #11807

NO_DOC=bugfix

### CODE REVIEW

**Comment by Gerold103** [comment]
@Serpentian , ping 🥹.

File: test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+
+        t.assert((f1:join()))
+        t.assert((f2:join()))
+        t.assert((f3:join()))
+        t.assert((f_async:join()))
+
+        t.assert_equals(s:select{}, {{1, _G.test_data}, {2, _G.test_data}})
+        t.assert_equals(a:select{}, {{3, _G.test_data}})
+    end)
+end
```
Comment (Serpentian) [inline test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua:134]: The usage of the `txn_limbo_is_empty` alongside with `txn_limbo_last_synchro_entry` is not safe and we have several more places, were it might lead to crash:

* `txn_checkpoint_build` (join + snapshot?)

https://github.com/tarantool/tarantool/blob/557c40773d50b9bd008a7845c5dedf8ab5b3efa1/src/box/txn_checkpoint.c#L81-L83

* `filter_promote_demote`:

https://github.com/tarantool/tarantool/blob/557c40773d50b9bd008a7845c5dedf8ab5b3efa1/src/box/txn_limbo.c#L1454-L1456

---

The other ones seems safe:

* `box_wait_limbo_acked`, when there's only snap entry in the limbo: should be safe here, since before any `wait_acked` we wait for limbo to be empty

* `write_promote` and `write_demote` expect `NULL` last synchro entry, no problems here

File: test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+            f3 = _G.fiber.create(function()
+                _G.fiber.self():set_joinable(true)
+                box.begin({txn_isolation = 'linearizable'})
+                box.commit()
+            end)
+        end)
+        local f_async = _G.make_txn_fiber(a, 3)
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
+
+        t.assert((f1:join()))
```
Comment (Serpentian) [inline test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua:126]: Nit: double brackets in asserts

File: test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua (hunk 1 above)
Comment (Serpentian) [reply test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua:134]: I didn't manage to reproduce these crashes, so didn't Vlad. For now let's assume, that this is not possible and wait for new coredumps, then we'll at least know, that these crashes can happen

**Review by Serpentian — APPROVED** [review]
I don't have any more comments, thank you!

File: test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua (hunk 2 above)
Comment (Gerold103) [reply test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua:126]: Yeah, I know. The problem is that `fiber:join()` returns 2 values: ok/not-ok and an error object. And `t.assert()` also takes 2 values. Without these nested parentheses the join's second value (error object) falls into `t.assert()`'s second argument, which I don't know how would behave, but I didn't want this to happen.

File: test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua (hunk 1 above)
Comment (Gerold103) [reply test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua:134]: I have created another ticket #11863. I spent hours trying to crash any other places using the same functions, and I couldn't. Perhaps with my proposals in that other ticket (some updates for the error injection tool) would simplify the reproduction, even if it is extremely unrealistic.

File: test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua (hunk 2 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_11807_qsync_linearization_crash_test.lua:126]: Wow, I didn't know that. Cool!
Resolving since the PR is approved.

**Review by xuniq — APPROVED** [review]
