### PR TITLE
net.box: allow calling stored Lua and C module functions with self.call

### LINKED ISSUE #9131: `net.box.self:call` can't find C stored procedure
**Bug description**

The behavior of `net.box.self:call` is inconsistent with `conn:call` in terms of executing C stored procedure. The issue is created from https://github.com/tarantool/vshard/issues/436 and blocks it. Reproduced on `Tarantool 3.0.0-alpha3-1-g2c700aab6`. 

**Steps to reproduce**

1. Create C stored procedure and compile it:
```C
#include "module.h"
int easy(box_function_ctx_t *ctx, const char *args, const char *args_end)
{
  printf("hello world\n");
  return 0;
}
```
```
gcc -shared -o easy.so -fPIC easy.c
```
2. Create function and try execute it
```Lua
> ./tarantool -i       
tarantool> box.cfg{listen = 3301}
tarantool> net_box = require('net.box')
tarantool> c = net_box:connect(3301)
-- Create C stored procedure
tarantool> box.schema.func.create('easy', {language = 'C'})
tarantool> box.schema.user.grant('guest', 'execute', 'function', 'easy')
-- Test the function is callable 
tarantool> c:call('easy')
hello world
---
- []
...
tarantool> net_box.self:call('easy')
---
- error: Procedure 'easy' is not defined
...
```

**Actual behavior**

`net.box.self:call` cannot find C stored procedure. Error `Procedure 'name' is not defined` is thrown.

**Expected behavior**

`net.box.self:call` should be able to find C stored procedure.

### PR DESCRIPTION
**Pull request by locker**
The fix is simple: look up the function in `box.func` by name and, if found, execute its `call` method. The only tricky part is to avoid the lookup before `box.cfg` is called because `box.func` is unavailable at the time. We achieve that by checking `box.ctl.is_recovery_finished`.

Closes #9131

### CODE REVIEW

File: test/box-luatest/gh_9131_net_box_self_call_stored_func_test.lua [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+end)
+
+g.test_box_not_configured = function()
+    local self = require('net.box').self
+    t.assert_equals({self:call('local_func_echo')}, {})
+    t.assert_equals({self:call('local_func_echo', {})}, {})
+    t.assert_equals({self:call('local_func_echo', {1})}, {1})
+    t.assert_equals({self:call('local_func_echo', {1LL})}, {1})
+    t.assert_equals({self:call('local_func_echo', {1, 2, 3})}, {1, 2, 3})
+    t.assert_error_msg_equals('test', self.call, self, 'local_func_error')
```
Comment (nshy) [inline test/box-luatest/gh_9131_net_box_self_call_stored_func_test.lua:51]: Nit: worth to do in a distinct group so no server is created/destroyed without usage.

Comment (locker) [reply test/box-luatest/gh_9131_net_box_self_call_stored_func_test.lua]: Done.

<details><summary>diff</summary>

```diff
diff --git a/test/box-luatest/gh_9131_net_box_self_call_stored_func_test.lua b/test/box-luatest/gh_9131_net_box_self_call_stored_func_test.lua
index cbe10b85658f..3cb872623472 100644
--- a/test/box-luatest/gh_9131_net_box_self_call_stored_func_test.lua
+++ b/test/box-luatest/gh_9131_net_box_self_call_stored_func_test.lua
@@ -1,7 +1,7 @@
 local server = require('luatest.server')
 local t = require('luatest')
 
-local g = t.group()
+local g = t.group('gh_9131')
 
 g.before_all(function(cg)
     cg.server = server:new()
@@ -30,27 +30,13 @@ g.before_all(function(cg)
         rawset(_G, 'unreg_lua_func_error',
                function() return error('test') end)
     end)
-    rawset(_G, 'local_func_echo', function(...) return ... end)
-    rawset(_G, 'local_func_error', function() return error('test') end)
 end)
 
 g.after_all(function(cg)
-    rawset(_G, 'local_func_echo', nil)
-    rawset(_G, 'local_func_error', nil)
     cg.server:drop()
     cg.server = nil
 end)
 
-g.test_box_not_configured = function()
-    local self = require('net.box').self
-    t.assert_equals({self:call('local_func_echo')}, {})
-    t.assert_equals({self:call('local_func_echo', {})}, {})
-    t.assert_equals({self:call('local_func_echo', {1})}, {1})
-    t.assert_equals({self:call('local_func_echo', {1LL})}, {1})
-    t.assert_equals({self:call('local_func_echo', {1, 2, 3})}, {1, 2, 3})
-    t.assert_error_msg_equals('test', self.call, self, 'local_func_error')
-end
-
 g.test_c_func = function(cg)
     cg.server:exec(function()
         local self = require('net.box').self
@@ -115,3 +101,26 @@ g.test_unreg_lua_func = function(cg)
             self.call, self, 'unreg_lua_func_undef')
     end)
 end
+
+local g_local = t.group('gh_9131.local')
+
+g_local.before_all(function()
+    rawset(_G, 'local_func_echo', function(...) return ... end)
+    rawset(_G, 'local_func_error', function() return error('test') end)
+end)
+
+g_local.after_all(function()
+    rawset(_G, 'local_func_echo', nil)
+    rawset(_G, 'local_func_error', nil)
+end)
+
+g_local.test_box_not_configured = function()
+    local self = require('net.box').self
+    t.assert_equals({self:call('local_func_echo')}, {})
+    t.assert_equals({self:call('local_func_echo', {})}, {})
+    t.assert_equals({self:call('local_func_echo', {1})}, {1})
+    t.assert_equals({self:call('local_func_echo', {1LL})}, {1})
+    t.assert_equals({self:call('local_func_echo', {1, 2, 3})}, {1, 2, 3})
+    t.assert_error_msg_equals('test', self.call, self, 'local_func_error')
+end
```

</details>

**Review by nshy — APPROVED** [review]

**Review by p7nov — APPROVED** [review]

**Review by ylobankov — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.11.
