### PR TITLE
test: fix flaky test on temp space truncate

### LINKED ISSUE #6663: test: flaky gh_6123_truncate_temp_space_test.lua
Sometimes I see these failures in CI.
```
[027] replication-luatest/gh_6123_truncate_temp_spac>                 
[027] not ok 2 gh_6123.engine:"vinyl".test_truncate_is_local_transaction #  
[027] Rejected result file: /tmp/tnt/rejects/replication-luatest/gh_6123_truncate_temp_space.reject
[027] [ fail ]
```

### PR DESCRIPTION
**Pull request by sergos**
Replication of data in the test should happened before the data presence
test on the replica. Wait for lsn helper is used.

Closes #6663

### CODE REVIEW

**Comment by ylobankov** [comment]
The fix is LGTM, but please add a couple of words to the commit message.

**Comment by sergos** [comment]
> The fix is LGTM, but please add a couple of words to the commit message.

done

File: test/replication-luatest/gh_6123_truncate_temp_space_test.lua [hunk 1]
```diff
@@ -57,6 +57,10 @@ g.test_truncate_is_local_transaction = function(cg)
 
     -- Checking that replica has received the last transaction,
     -- and that replication isn't broken.
+    local vclock = cg.master:eval("return box.info.vclock")
```
Comment (Gerold103) [inline test/replication-luatest/gh_6123_truncate_temp_space_test.lua:60]: I propose to add a method `:vclock()` to server object. In `test/luatest_helpers/server.lua`. This looks like a useful method for future tests.

**Review by Gerold103 — CHANGES_REQUESTED** [review]

File: test/replication-luatest/gh_6123_truncate_temp_space_test.lua (hunk 1 above)
Comment (sergos) [reply test/replication-luatest/gh_6123_truncate_temp_space_test.lua]: There's one already in `luatest_helpers.lua` so I rebased/forcepushed

**Review by Gerold103 — APPROVED** [review]

**Review by kyukhin — APPROVED** [review]
