### PR TITLE
config: validate permissions in credentials privileges

### LINKED ISSUE #11441: config credentials/users/<username>/privileges/*/permissions should be mandatory field
**Bug description**

Tarantool 3.4.0

**Reproduce**

Set following config

```yaml
credentials:
  users:
    peer:
      password: "<redacted>"
      roles: [ replication ]
      privileges:
          - lua_call:
             - "all"
```

Do reload: `config:reload()`

See error message:

```
builtin/config/applier/credentials.lua:1010: builtin/config/applier/credentials.lua:207: bad argument #1 to 'ipairs' (table expected, got nil) (LuajitError, code 0x20), see src/lua/utils.c line 700
```

**My expectations**

Clear error message in validation parameters, and json-schema of config should fill `permissions` with some values to highlight for me, that this fields should be filled

Jira: TNTP-2728

### PR DESCRIPTION
**Pull request by mandesero**
This patch fixes a bug where config:reload() crashes if a credentials.users.<username>.privileges entry misses the `permissions` field, leading to:

```
credentials.lua:207: bad argument #1 to 'ipairs' (table expected, got nil)
```

This patch adds validation that requires `permissions` in each privileges entry and reports a configuration error instead of crashing.

Closes #11441

NO_DOC=bugfix
NO_CHANGELOG=bugfix

### CODE REVIEW

File: src/box/lua/config/instance_config.lua [hunk 1]
```diff
@@ -1518,6 +1521,9 @@ return schema.new('instance_config', schema.record({
                                 allowed_values = {'all'},
                             }),
                         }),
+                    }, {
+                        validate =
+                            validators['credentials.users.*.privileges.*'],
```
Comment (georgiy-belyanin) [inline src/box/lua/config/instance_config.lua:1526]: Minor: probably also add assert in credentials.

```lua
local function privileges_from_config(config_data)
    local privileges = config_data.privileges or {}
    assert(type(privileges) == 'table')

    local intermediate = {
        ['user'] = {},
        ['role'] = {},
        ['space'] = {},
        ['function'] = {},
        ['sequence'] = {},
        ['universe'] = {},
        ['lua_eval'] = {},
        ['lua_call'] = {},
        ['sql'] = {},
    }

    for _, priv in ipairs(privileges) do
        assert(type(priv.permissions) == 'table')
        for _, perm in ipairs(priv.permissions) do
```

**Review by georgiy-belyanin — APPROVED** [review]
Thank you for fixing it!

File: src/box/lua/config/instance_config.lua (hunk 1 above)
Comment (mandesero) [reply src/box/lua/config/instance_config.lua:1526]: Good idea, added.

**Review by grafin — APPROVED** [review]
Thanks for fixing this! LGTM.
