### PR TITLE
box: fix failing assertion in box_promote_qsync

### LINKED ISSUE #9263: Assertion in box_promote_qsync
**Bug description**
Now it is possible for the following assertion in `box_promote_qsync` function to fail:
https://github.com/tarantool/tarantool/blob/952d15827b9a299e6a13a8f0e3a0f3b0c36118cc/src/box/box.cc#L2890

**Steps to reproduce**
Run the following lua test:
```lua
local t = require('luatest')
local cluster = require('luatest.replica_set')
local proxy = require('luatest.replica_proxy')
local server = require('luatest.server')

local g = t.group('assertion-in-box-promote-qsync')

local wait_timeout = 10

local function wait_pair_sync(server1, server2)
    -- Without retrying it fails sometimes when vclocks are empty and both
    -- instances are in 'connect' state instead of 'follow'.
    t.helpers.retrying({timeout = 10}, function()
        server1:wait_for_vclock_of(server2)
        server2:wait_for_vclock_of(server1)
        server1:assert_follows_upstream(server2:get_instance_id())
        server2:assert_follows_upstream(server1:get_instance_id())
    end)
end

local function server_wait_wal_is_blocked(server)
    server:exec(function()
        t.helpers.retrying({timeout = 10}, function()
            t.assert(box.error.injection.get('ERRINJ_WAL_DELAY'))
        end)
    end)
end

local function server_wait_synchro_queue_len_is_equal(server, expected)
    server:exec(function(expected)
        t.helpers.retrying({timeout = 10}, function(expected)
            t.assert_equals(box.info.synchro.queue.len, expected)
        end, expected)
    end, {expected})
end

local function server_becomes_the_leader_again(server)
    local prev_cfg = server:exec(function()
        local prev_cfg = box.cfg
        box.cfg{
            election_mode='candidate',
            replication_synchro_quorum=1
        }
        return prev_cfg
    end)
    server:wait_until_election_leader_found()
    server:exec(function(prev_cfg)
        t.assert_equals(box.info.election.leader, box.info.id)
        box.cfg{
            election_mode=prev_cfg.election_mode,
            replication_synchro_quorum=prev_cfg.replication_synchro_quorum,
        }
    end, {prev_cfg})
end

local function get_fiber_csw(server, fiber_id)
    return server:exec(function(fiber_id)
        return require('fiber').find(fiber_id):info().csw
    end, {fiber_id})
end

local function server_wait_fiber_csw_ge_than(server, fiber_id, threshold)
    server:exec(function(fiber_id, threshold)
        t.helpers.retrying({timeout = 10}, function(fiber_id, threshold)
            t.assert_ge(require('fiber').find(fiber_id):info().csw, threshold)
        end, fiber_id, threshold)
    end, {fiber_id, threshold})
end

g.before_each(function(cg)
    t.tarantool.skip_if_not_debug()

    cg.cluster = cluster:new({})
    cg.master = cg.cluster:build_and_add_server({
        alias = 'master',
        box_cfg = {
            replication = {
                server.build_listen_uri('master', cg.cluster.id),
                server.build_listen_uri('replica_proxy'),
            },
            election_mode = 'candidate',
            replication_synchro_quorum = 2,
            replication_synchro_timeout = 100000,
            replication_timeout = 0.1,
            election_fencing_mode='off',
        }
    })
    cg.replica = cg.cluster:build_and_add_server({
        alias = 'replica',
        box_cfg = {
            replication = {
                server.build_listen_uri('replica', cg.cluster.id),
                server.build_listen_uri('master_proxy'),
            },
            election_mode = 'off',
            replication_synchro_quorum = 2,
            replication_synchro_timeout = 100000,
            replication_timeout = 0.1
        }
    })
    cg.master_proxy = proxy:new({
        client_socket_path = server.build_listen_uri('master_proxy'),
        server_socket_path = server.build_listen_uri('master', cg.cluster.id),
    })
    t.assert(cg.master_proxy:start({force = true}))
    cg.replica_proxy = proxy:new({
        client_socket_path = server.build_listen_uri('replica_proxy'),
        server_socket_path = server.build_listen_uri('replica', cg.cluster.id),
    })
    t.assert(cg.replica_proxy:start({force = true}))
    cg.cluster:start()
    cg.master:wait_until_election_leader_found()
    cg.replica:wait_until_election_leader_found()

    cg.master:exec(function()
        box.schema.space.create('test', {is_sync = true})
        box.space.test:create_index('pk')
    end)
    wait_pair_sync(cg.replica, cg.master)
end)

g.after_each(function(cg)
    cg.cluster:drop()
end)

g.test_is_in_box_promote = function(cg)
    local f = cg.replica:exec(function()
        box.error.injection.set('ERRINJ_WAL_DELAY_COUNTDOWN', 0)
        local f = require('fiber').create(function() box.ctl.promote() end)
        f:set_joinable(true)
        return f:id()
    end)
    server_wait_wal_is_blocked(cg.replica)

    cg.replica_proxy:pause()

    t.helpers.retrying({timeout = 10}, function()
        cg.master:exec(function()
            local status = box.info.replication[2].upstream.status
            t.assert(status ~= 'follow')
        end)
    end)

    cg.master:exec(function()
        require('fiber').create(function() box.space.test:insert{1} end)
    end)
    server_wait_synchro_queue_len_is_equal(cg.replica, 1)

    local csw = get_fiber_csw(cg.replica, f)
    local ff = require('fiber').create(function()
        cg.replica:exec(function(f)
            box.error.injection.set('ERRINJ_WAL_DELAY', false)
            require('fiber').find(f):join()
        end, {f})
    end)
    ff:set_joinable(true)
    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
    server_becomes_the_leader_again(cg.replica)
    cg.master:exec(function()
        box.cfg{replication_synchro_quorum=1}
    end)
    server_wait_synchro_queue_len_is_equal(cg.replica, 0)
    cg.replica_proxy:resume()
    local ok, err = ff:join()
    t.assert_equals(err, nil)
    t.assert(ok)
end
```

**Actual behavior**

Assert fails.

**Expected behavior**

Assert doesn't fails.

### PR DESCRIPTION
**Pull request by Astronomax**
Fixed a bug when the assertion in `box_promote_qsync` would fail. The assertion is that at the moment when `box_promote_qsync` is executed, no other promote is executed. It turned out that this assertion is basically incorrect. Now after this patch the newly elected leader is trying to repeat `box_promote_qsync` in `box_raft_update_synchro_queue` until it fails due to the fact that some other promotion is currently being executed.

Closes #9263

NO_DOC=bugfix

### CODE REVIEW

File: src/box/raft.c [hunk 1]
```diff
@@ -130,7 +130,9 @@ box_raft_update_synchro_queue(struct raft *raft)
 			errcode = box_error_code(err);
 			diag_log();
 		}
-	} while (rc != 0 && errcode == ER_QUORUM_WAIT && !fiber_is_cancelled());
+		fiber_sleep(0);
```
[the remark this answers is not in the document]
Comment (Astronomax) [reply src/box/raft.c]: Fixed.

File: src/box/errcode.h [hunk 2]
```diff
@@ -329,7 +329,7 @@ struct errcode_record {
 	/*274 */_(ER_UNCONFIGURED,		"Please call box.cfg{} first") \
 	/*275 */_(ER_CREATE_DEFAULT_FUNC,	"Failed to create field default function '%s': %s") \
 	/*276 */_(ER_DEFAULT_FUNC_FAILED,	"Error calling field default function '%s': %s") \
-
+    /*277 */_(ER_IN_ANOTHER_PROMOTE,	"Promote is already running") \
```
[the remark this answers is not in the document]
Comment (Astronomax) [reply src/box/errcode.h]: Fixed.

File: changelogs/unreleased/gh-9263-assertion-in-box-promote-qsync.md [hunk 3]
```diff
@@ -0,0 +1,10 @@
+## bugfix/core
+
+* Fixed a bug when the assertion in `box_promote_qsync` would fail. The assertion
```
[the remark this answers is not in the document]
Comment (Astronomax) [reply changelogs/unreleased/gh-9263-assertion-in-box-promote-qsync.md]: Please check the new description.

File: changelogs/unreleased/gh-9263-assertion-in-box-promote-qsync.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
+## bugfix/core
+
+* Fixed a bug when the assertion in `box_promote_qsync` would fail in Debug build mode.
+  The assertion is that at the moment when `box_promote_qsync` is executed, no other
+  promote is executed. It turned out that this assertion is basically incorrect.
+  In release build mode this incorrect assumption could potentially lead to writing
+  2 PROMOTE entries in the same term (gh-9263).
```
Comment (p7nov) [inline changelogs/unreleased/gh-9263-assertion-in-box-promote-qsync.md:7]:
```suggestion
* Fixed a bug when the assertion in `box_promote_qsync` would fail in the
  debug build mode. The assertion is that at the moment when `box_promote_qsync`
  is called, no other promote is being executed. It turned out that this
  assertion is basically incorrect. In the release build mode, this incorrect
  assumption could potentially lead to writing 2 PROMOTE entries in the same
  term (gh-9263).
```

**Review by p7nov — APPROVED** [review]

File: test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+    cg.master:exec(function()
+        require('fiber').create(function() box.space.test:insert{1} end)
+    end)
+    server_wait_synchro_queue_len_is_equal(cg.replica, 1)
+
+    local wait_quorum_count = get_wait_quorum_count(cg.replica)
+    local ff = require('fiber').create(function()
+        cg.replica:exec(function(f)
+            box.error.injection.set('ERRINJ_WAL_DELAY', false)
+            require('fiber').find(f):join()
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua:135]: Let's also return and check `f` error. It should say something about `ER_INTERFERING_PROMOTE`, it seems.

**Review by sergepetrenko — APPROVED** [review]
Thanks for the fixes!

Looks good to me.

File: test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua (hunk 5 above)
Comment (Astronomax) [reply test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua:135]: No, the first promote in box.ctl.promote() should be written successfully, and the second one will wait all this time. When the first one is completed, the second one will go further and try to write but will see that PROMOTE has already been written in this term.

File: changelogs/unreleased/gh-9263-assertion-in-box-promote-qsync.md (hunk 4 above)
Comment (Astronomax) [reply changelogs/unreleased/gh-9263-assertion-in-box-promote-qsync.md]: Fixed.

File: test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua (hunk 5 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua]: Ok, thanks for the explanation!

File: src/box/raft.c [hunk 6]
```diff
@@ -129,8 +129,11 @@ box_raft_update_synchro_queue(struct raft *raft)
 			struct error *err = diag_last_error(diag_get());
 			errcode = box_error_code(err);
 			diag_log();
+			if (errcode == ER_IN_ANOTHER_PROMOTE)
+				fiber_sleep(0);
```
Comment (Gerold103) [inline src/box/raft.c:133]: This needs either a comment why is the sleep done only for "another promote", or it needs to be done unconditionally. To be frank I see nothing wrong with just making it unconditional.

File: test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua [hunk 7]
```diff
@@ -0,0 +1,153 @@
...
+    cg.master = cg.cluster:build_and_add_server({
+        alias = 'master',
+        box_cfg = box_cfg
+    })
+    box_cfg.replication = {
+        server.build_listen_uri('replica', cg.cluster.id),
+        server.build_listen_uri('master_proxy'),
+    }
+    box_cfg.election_mode = 'off'
+    box_cfg.instance_name='replica'
```
Comment (Gerold103) [inline test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua:78]: Lets be consistent and use `a = b` everywhere, not `a=b`.

Comment (Gerold103) [inline test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua:78]: Why do you need instance names in this test?

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Thanks for the patch!

File: src/box/raft.c (hunk 6 above)
Comment (Astronomax) [reply src/box/raft.c]: Let's do this unconditionally, but only if the loop has to repeat again.
```diff
--- a/src/box/raft.c
+++ b/src/box/raft.c
@@ -123,14 +123,21 @@ box_raft_update_synchro_queue(struct raft *raft)
                return;
        int rc = 0;
        uint32_t errcode = 0;
+       bool try_again = false;
        do {
                rc = box_promote_qsync();
                if (rc != 0) {
                        struct error *err = diag_last_error(diag_get());
                        errcode = box_error_code(err);
                        diag_log();
+                       if (!fiber_is_cancelled() &&
+                           (errcode == ER_QUORUM_WAIT ||
+                           errcode == ER_IN_ANOTHER_PROMOTE)) {
+                               try_again = true;
+                               fiber_sleep(0);
+                       }
                }
-       } while (rc != 0 && errcode == ER_QUORUM_WAIT && !fiber_is_cancelled());
+       } while (try_again);
 }
```

File: test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua (hunk 7 above)
Comment (Astronomax) [reply test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua]:
```diff
--- a/test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua
+++ b/test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua
@@ -63,9 +63,8 @@ g.before_each(function(cg)
         replication_synchro_quorum = 2,
         replication_synchro_timeout = 100000,
         replication_timeout = 0.1,
-        election_fencing_mode='off',
+        election_fencing_mode = 'off',
     }
-    box_cfg.instance_name='master'
     cg.master = cg.cluster:build_and_add_server({
         alias = 'master',
         box_cfg = box_cfg
@@ -75,7 +74,6 @@ g.before_each(function(cg)
         server.build_listen_uri('master_proxy'),
     }
     box_cfg.election_mode = 'off'
-    box_cfg.instance_name='replica'
     cg.replica = cg.cluster:build_and_add_server({
         alias = 'replica',
         box_cfg = box_cfg
@@ -141,8 +139,8 @@ g.test_is_in_box_promote = function(cg)
     server_wait_wait_quorum_count_ge_than(cg.replica, wait_quorum_count + 1)
     cg.replica:exec(function()
         box.cfg{
-            election_mode='candidate',
-            replication_synchro_quorum=1
+            election_mode = 'candidate',
+            replication_synchro_quorum = 1
         }
     end)
     cg.replica:wait_for_election_state('leader')
```

Comment (Astronomax) [reply test/replication-luatest/gh_9263_assertion_in_box_promote_qsync_test.lua]: I don't need instance names.

**Review by Gerold103 — APPROVED** [review]
Thanks for the fixes!

**Comment by sergepetrenko** [comment]
Cherry-pick to 2.11: #9540
