### PR TITLE
box: fix crash on rollback on memtx memory OOM and massive index change

### LINKED ISSUE #10551: Crash on OOM on TX rollback
The script:

```lua
local fiber = require('fiber')

box.cfg{}
for i=1,10 do
    local s = box.schema.create_space('test' .. i)
    s:create_index('pk')
    s:insert({1})
end

local errinj = box.error.injection
errinj.set('ERRINJ_WAL_DELAY', true)
for i=1,10 do
    fiber.create(function()
        local s = box.space['test' .. i]
        s:insert({2})
    end)
end
fiber.create(function()
    box.snapshot()
end)
errinj.set('ERRINJ_INDEX_ALLOC', true)
errinj.set('ERRINJ_WAL_WRITE_DISK', true)
errinj.set('ERRINJ_WAL_DELAY', false)
os.exit()
```

crashes with backtrace:
```c
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007adcaeea5463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007adcaee4c120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007adcaee334c3 in __GI_abort () at abort.c:79
#4  0x00005cfbcb319df2 in crash_signal_cb (signo=11, siginfo=0x5cfbfcc7e330, context=0x5cfbfcc7e200) at /home/shiny/dev/tarantool/src/lib/core/crash.c:204
#5  <signal handler called>
#6  0x00005cfbcb083591 in NS_USE_HINT::bps_tree_memtx_tree_delete_from_leaf (tree=0x5cfbfccf83a8, leaf_path_elem=0x7fffa6254360)
    at /home/shiny/dev/tarantool/src/lib/salad/bps_tree.h:3745
#7  0x00005cfbcb0885b0 in NS_USE_HINT::bps_tree_memtx_tree_process_delete_leaf (tree=0x5cfbfccf83a8, path=0x7fffa62543a0, leaf_path_elem=0x7fffa6254360)
    at /home/shiny/dev/tarantool/src/lib/salad/bps_tree.h:5423
#8  0x00005cfbcb08a7fa in NS_USE_HINT::bps_tree_memtx_tree_delete (t=0x5cfbfccf83a8, elem=..., if_identical=false, deleted_elem=0x0, offset=0x0)
    at /home/shiny/dev/tarantool/src/lib/salad/bps_tree.h:5951
#9  NS_USE_HINT::memtx_tree_delete (t=0x5cfbfccf83a8, elem=...) at /home/shiny/dev/tarantool/src/lib/salad/bps_tree.h:5958
#10 0x00005cfbcb08d4c6 in memtx_tree_index_replace<true> (base=0x5cfbfccf8370, old_tuple=0x7adc9d007f94, new_tuple=0x0, mode=DUP_INSERT, result=0x7fffa6254858,
    successor=0x7fffa6254858) at /home/shiny/dev/tarantool/src/box/memtx_tree.cc:1478
#11 0x00005cfbcb0ae0cb in index_replace (index=0x5cfbfccf8370, old_tuple=0x7adc9d007f94, new_tuple=0x0, mode=DUP_INSERT, result=0x7fffa6254858, successor=0x7fffa6254858)
    at /home/shiny/dev/tarantool/src/box/index.h:917
#12 0x00005cfbcb0b1b59 in memtx_engine_rollback_statement (engine=0x5cfbfccbe690, txn=0x7adcae469038, stmt=0x7adcae4692b0)
    at /home/shiny/dev/tarantool/src/box/memtx_engine.cc:693
#13 0x00005cfbcb17cf05 in engine_rollback_statement (engine=0x5cfbfccbe690, txn=0x7adcae469038, stmt=0x7adcae4692b0) at /home/shiny/dev/tarantool/src/box/engine.h:427
#14 0x00005cfbcb17f110 in txn_rollback_one_stmt (txn=0x7adcae469038, stmt=0x7adcae4692b0) at /home/shiny/dev/tarantool/src/box/txn.c:368
#15 0x00005cfbcb180d7b in txn_complete_fail (txn=0x7adcae469038) at /home/shiny/dev/tarantool/src/box/txn.c:811
#16 0x00005cfbcb181502 in txn_on_journal_write (entry=0x7adcae4693e8) at /home/shiny/dev/tarantool/src/box/txn.c:900
#17 0x00005cfbcb1eb325 in journal_async_complete (entry=0x7adcae4693e8) at /home/shiny/dev/tarantool/src/box/journal.h:253
#18 0x00005cfbcb1ebd70 in tx_schedule_queue (queue=0x5cfbcbb1aed8 <wal_writer_singleton+24>) at /home/shiny/dev/tarantool/src/box/wal.c:280
#19 0x00005cfbcb1ebe27 in tx_complete_rollback () at /home/shiny/dev/tarantool/src/box/wal.c:341
#20 0x00005cfbcb1ebec2 in tx_complete_batch (msg=0x7adcae4501a0) at /home/shiny/dev/tarantool/src/box/wal.c:372
#21 0x00005cfbcb32f4c4 in cmsg_deliver (msg=0x7adcae4501a0) at /home/shiny/dev/tarantool/src/lib/core/cbus.c:350
#22 0x00005cfbcb32fe1c in cbus_process (endpoint=0x5cfbcbb15fc0 <tx_prio_endpoint>) at /home/shiny/dev/tarantool/src/lib/core/cbus.c:601
#23 0x00005cfbcb1a96e3 in tx_prio_cb (loop=0x5cfbcbbe0560 <default_loop_struct>, watcher=0x5cfbcbb16110 <tx_prio_endpoint+336>, events=524288)
    at /home/shiny/dev/tarantool/src/box/box.cc:5595
#24 0x00005cfbcb6f0be5 in ev_invoke_pending (loop=0x5cfbcbbe0560 <default_loop_struct>) at /home/shiny/dev/tarantool/third_party/libev/ev.c:3797
#25 0x00005cfbcb6f1b80 in ev_run (loop=0x5cfbcbbe0560 <default_loop_struct>, flags=0) at /home/shiny/dev/tarantool/third_party/libev/ev.c:4221
#26 0x00005cfbcb2e83f9 in tarantool_lua_run_script (path=0x5cfbfcc745d2 "memtx.lua", instance=0x5cfbcbae0a30 <instance>, opt_mask=0, optc=0, optv=0x0, argc=1,
    argv=0x5cfbfcc745a8) at /home/shiny/dev/tarantool/src/lua/init.c:1218
#27 0x00005cfbcb04bd0d in main (argc=1, argv=0x5cfbfcc745a8) at /home/shiny/dev/tarantool/src/main.cc:1060
```

Originally the issue was found for `memcs` engine (https://github.com/tarantool/tarantool-ee/issues/842) but the `memtx` has the same issue.

### PR DESCRIPTION
**Pull request by nshy**
We cannot tolerate index extent memory allocation failure on rollback. At the same time it is not practical to reserve memory because a whole index can easily be changed on rollback if read view is created before rollback.

So in case of rollback and memtx memory OOM let's allocate outside the memtx arena limited by quota.

Now part of the index can reside outside memtx arena. But regularly the index changes will move this part back to the memtx arena. Until next such situation of course.

Closes #10551

### CODE REVIEW

File: src/box/memtx_engine.cc [hunk 1]
```diff
@@ -66,6 +66,27 @@
...
+mh_ptr_hash(const void *ptr)
+{
+	uintptr_t u = (uintptr_t)ptr;
+	return u ^ (u >> 32);
+}
+
+/**
+ * Set: (void *)
+ */
+#define mh_name _ptr
```
Comment (locker) [inline src/box/memtx_engine.cc:79]: I guess this could be useful somewhere else. Let's put it in `assoc.h` (in a separate commit).

File: src/box/memtx_engine.cc [hunk 2]
```diff
@@ -2123,23 +2146,32 @@ memtx_index_extent_alloc(void *ctx)
...
+		return ret;
+	if (in_txn() != NULL && in_txn()->status == TXN_ABORTED) {
+		/*
+		 * We cannot sanely reserve blocks for rollback because strictly
+		 * speaking the whole index can change. We cannot tolerate
+		 * allocation failure also. So just allocate outside of the
+		 * memtx arena quota.
+		 */
+		ret = xmalloc(MEMTX_EXTENT_SIZE);
+		mh_ptr_put(memtx->malloc_extents, (const void **)&ret,
```
Comment (locker) [inline src/box/memtx_engine.cc:2168]: Can we do without this cast?

File: src/box/memtx_engine.cc (hunk 1 above)
Comment (nshy) [reply src/box/memtx_engine.cc:79]: Done.

File: src/box/memtx_engine.cc [hunk 3]
```diff
@@ -2123,23 +2146,32 @@ memtx_index_extent_alloc(void *ctx)
...
-		diag_set(OutOfMemory, MEMTX_EXTENT_SIZE,
-			 "mempool", "new slab");
-		return NULL;
-	});
-	void *ret;
-	while ((ret = mempool_alloc(&memtx->index_extent_pool)) == NULL) {
+	void *ret = NULL;
+	struct errinj *errinj = errinj(ERRINJ_INDEX_ALLOC, ERRINJ_BOOL);
+	while (!(errinj != NULL && errinj->bparam) &&
+	       (ret = mempool_alloc(&memtx->index_extent_pool)) == NULL) {
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_engine.cc:2152]: This way we can use `malloc` allocation with the injection.

[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_engine.cc:2152]: Changed as discussed f2f to avoid handling injection without macros:

<details>
<summary>diff</summary>

```diff
                return result;
        }
-       ERROR_INJECT(ERRINJ_INDEX_ALLOC, {
-               /* same error as in mempool_alloc */
-               diag_set(OutOfMemory, MEMTX_EXTENT_SIZE,
-                        "mempool", "new slab");
-               return NULL;
-       });
+       ERROR_INJECT(ERRINJ_INDEX_ALLOC, { goto fail; });
        void *ret;
        while ((ret = mempool_alloc(&memtx->index_extent_pool)) == NULL) {
                bool stop;
@@ -2137,9 +2134,23 @@ memtx_index_extent_alloc(void *ctx)
                        break;
        }
        if (ret == NULL)
-               diag_set(OutOfMemory, MEMTX_EXTENT_SIZE,
-                        "mempool", "new slab");
+               goto fail;
        return ret;
+fail:
+       if (in_txn() != NULL && in_txn()->status == TXN_ABORTED) {
+               /*
+                * We cannot sanely reserve blocks for rollback because strictly
+                * speaking the whole index can change. We cannot tolerate
+                * allocation failure also. So just allocate outside of the
+                * memtx arena quota.
+                */
+               ret = xmalloc(MEMTX_EXTENT_SIZE);
+               mh_ptr_put(memtx->malloc_extents, (const void **)&ret,
+                          NULL, NULL);
+               return ret;
+       }
+       diag_set(OutOfMemory, MEMTX_EXTENT_SIZE, "mempool", "new slab");
+       return NULL;
 }

 /**
```

</details>

**Review by locker — APPROVED** [review]

**Review by xuniq — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.11 and 3.2.
