### PR TITLE
bps: prevent missing matras head view changes

### LINKED ISSUE #11979: BPS tree can get invalidated in rare cases in presense of a read view
We've removed touching garbage blocks on pop in 52b3d4b9174b7e27529579dd3094ef2224a554bf, this can lead to a bug similar to tarantool/tarantool-ee#1511. Unlike the BPS vector, here we probably can keep the change, but make sure there's no touches performed between a new block creation via `bps_tree_garbage_pop` and assignment of its last field. The problem seems to only exist in the insertion routine.

<details>
<summary>Here's <code>reproduce.patch</code> for a854a6519462f7f8792dedb97d4cf1ee03be2c4f failing the debug check, apply with <code>git apply --verbose reproduce.patch</code>.</summary>

```patch
From 3c04400696224aebb3e14c3fa3cef39469e0495b Mon Sep 17 00:00:00 2001
From: Magomed Kostoev <m.kostoev@tarantool.org>
Date: Fri, 24 Oct 2025 15:06:10 +0300
Subject: [PATCH] Reproduce

---
 test/unit/bps_tree.cc | 75 +++++++++++++++++++++++++++++++++++++++++--
 1 file changed, 73 insertions(+), 2 deletions(-)

diff --git a/test/unit/bps_tree.cc b/test/unit/bps_tree.cc
index 6a04facd64..d131dd01bd 100644
--- a/test/unit/bps_tree.cc
+++ b/test/unit/bps_tree.cc
@@ -82,6 +82,28 @@ compare(type_t a, type_t b);
 #undef bps_tree_key_t
 #undef bps_tree_arg_t
 
+/* the same tree with extent size x2 of block size */
+#define bx4_TREE_EXTENT_SIZE (SMALL_BLOCK_SIZE * 4)
+#define BPS_TREE_NAME test_bx4
+#define BPS_TREE_BLOCK_SIZE SMALL_BLOCK_SIZE
+#define BPS_TREE_EXTENT_SIZE bx4_TREE_EXTENT_SIZE
+#define BPS_TREE_IS_IDENTICAL(a, b) (a == b)
+#define BPS_TREE_COMPARE(a, b, arg) compare(a, b)
+#define BPS_TREE_COMPARE_KEY(a, b, arg) compare(a, b)
+#define bps_tree_elem_t type_t
+#define bps_tree_key_t type_t
+#define bps_tree_arg_t int
+#include "salad/bps_tree.h"
+#undef BPS_TREE_NAME
+#undef BPS_TREE_BLOCK_SIZE
+#undef BPS_TREE_EXTENT_SIZE
+#undef BPS_TREE_IS_IDENTICAL
+#undef BPS_TREE_COMPARE
+#undef BPS_TREE_COMPARE_KEY
+#undef bps_tree_elem_t
+#undef bps_tree_key_t
+#undef bps_tree_arg_t
+
 struct elem_t {
 	long info;
 	long marker;
@@ -179,11 +201,10 @@ static bool extent_alloc_failure = false;
 static void *
 extent_alloc(struct matras_allocator *allocator)
 {
-	(void)allocator;
 	if (extent_alloc_failure)
 		return NULL;
 	++extents_count;
-	return xmalloc(BPS_TREE_EXTENT_SIZE);
+	return xmalloc(allocator->extent_size);
 }
 
 static void
@@ -992,6 +1013,53 @@ gh_11788_oom_on_first_insertion_test()
 	check_plan();
 }
 
+static void
+gh_xxxxx_head_view_changes_test()
+{
+	plan(1);
+	header();
+
+	/* Create the test-specific allocator. */
+	struct matras_allocator bx4_allocator;
+	matras_allocator_create(&bx4_allocator, bx4_TREE_EXTENT_SIZE,
+				extent_alloc, extent_free);
+
+	test_bx4 tree;
+	test_bx4_view view;
+	struct test_bx4_iterator iterator;
+
+	test_bx4_create(&tree, 0, &bx4_allocator, NULL);
+	const int max_count_in_leaf = BPS_TREE_test_bx4_MAX_COUNT_IN_LEAF;
+	/* Four leafs initially. */
+	const int init_size = max_count_in_leaf * 4;
+	/* Insert into the third leaf for the test. */
+	const int to_insert = max_count_in_leaf * 2 + (max_count_in_leaf / 2);
+	type_t init_data[init_size];
+	/* Fill the tree of 4 leafs, but skip the value to be inserted. */
+	for (int i = 0; i < init_size; i++) {
+		if (i < to_insert)
+			init_data[i] = i;
+		else
+			init_data[i] = i + 1;
+	}
+	if (test_bx4_build(&tree, init_data, init_size))
+		fail("building failed", "true");
+	test_bx4_print(&tree, TYPE_F);
+	test_bx4_view_create(&view, &tree);
+	test_bx4_insert(&tree, to_insert, NULL, NULL);
+	test_bx4_print(&tree, TYPE_F);
+	if (test_bx4_debug_check(&tree) != 0)
+		fail("debug check non-zero", "true");
+	test_bx4_destroy(&tree);
+	ok(true, "head view changes");
+
+	/* Destroy the test-specific allocator. */
+	matras_allocator_destroy(&bx4_allocator);
+
+	footer();
+	check_plan();
+}
+
 int
 main(void)
 {
@@ -1001,6 +1069,9 @@ main(void)
 	matras_allocator_create(&allocator, BPS_TREE_EXTENT_SIZE,
 				extent_alloc, extent_free);
 
+	gh_xxxxx_head_view_changes_test();
+	return 0;
+
 	simple_check();
 	compare_with_sptree_check();
 	compare_with_sptree_check_branches();
-- 
2.43.0

```

</summary>

### PR DESCRIPTION
**Pull request by mkostoevr**
We've removed CoW'ing of garbage blocks for creating new inner/leaf blocks in commit 52b3d4b9174b7e27529579dd3094ef2224a554bf ("salad: reserve block before bps_tree_insert_first_elem") as the blocks are not required to be preserved in views and can be used without CoW.

The problem is that in some circumstances this approach can lead to a tricky problem: if we've created a block, CoW'ed another one and then update values of the created one, the new block could've been CoW'ed by the previous `matras_touch` (as the blocks are located in extents of greater size than the blocks themselves). So following updates in the created block gone into the view while the current matras head had the old view's values remained.

The problem is that if we don't touch the garbage on block creation, we need to make sure there's no any `matras_touch` between the block creation and the last assignment of its field. We could fix the only place where the guarantee is not preserved: the leaf insert routine, but let's keep the tree similar to the BPS vector and simply revert the change and touch popped garbage blocks too.

Since now the garbage pop invokes CoW, we might need to reserve more memory for touches, as some new garbage blocks can be allocated on the `bps_vec_reserve_blocks`, but other ones can be existing in the vector previously, and, for these ones, we must reserve touches. Also, one more touch might be required if a new block allocated on reserve.

Removed the target leaf touch from the `bps_tree_process_insert_leaf` by the way as it's not required cause the leaf is touched on lookup.

Follows-up #11857
Closes #11979

NO_DOC=bugfix
NO_CHANGELOG=was not released

### CODE REVIEW

**Comment by mkostoevr** [comment]
Discussed offline and decided to keep it similar to the BPS vector for now.

File: test/unit/bps_tree.cc [hunk 1]
```diff
@@ -966,21 +1009,16 @@ gh_11788_oom_on_first_insertion_test()
 	test tree;
 	test_view view;
 	type_t replaced;
-	struct test_iterator iterator;
```
Comment (nshy) [inline test/unit/bps_tree.cc:969]: Nit. Let's remove `_test` suffix from test name as in EE version.

Comment (mkostoevr) [reply test/unit/bps_tree.cc:969]: The suffix was outstanding in the vector test: as it has a different naming convention (`check_testname`). Here it seems consistent with other test names (`testname_test`, `testname_check`, `testname`).

**Comment by mkostoevr** [comment]
<details><summary>Fixed a typo.</summary>

```diff
--- a/src/lib/salad/bps_tree.h
+++ b/src/lib/salad/bps_tree.h
@@ -3193,7 +3193,7 @@ bps_tree_garbage_pop(struct bps_tree_common *tree, bps_tree_block_id_t *id)
                 * an existing leaf to link it with the new one, and then
                 * update the new leaf's `next_id` (which updates data of
                 * the read view by the pointer returned here instead of
-                * new CoWed data). This case is easily fixable bit let's
+                * new CoWed data). This case is easily fixable but let's
                 * fix it here the same way as it was fixed in BPS vector,
                 * as keeping this function non-CoW makes its usage error-
                 * prone.
```

</details>

**Comment by mkostoevr** [comment]
Cherry-picked to [3.3](https://github.com/tarantool/tarantool/pull/12008), [3.4](https://github.com/tarantool/tarantool/pull/12009) and [3.5](https://github.com/tarantool/tarantool/pull/12010).
