### PR TITLE
replication: retry join automatically

### LINKED ISSUE #6126: Retry join automatically (for a timeout)
Currently when join fails, the instance is terminated. Even if the error was not critical. For instance, the join-master appeared to be read-only.

It looks like a config error, but actually can happen even without config changes. For instance, if automatic election is used, then a new instance can find the leader, but while it is sending a join request, the leader can resign. The join will fail saying the former leader is read-only.

It should not be hard to retry the join by looking for a new leader. Such not critical errors can be caught in `bootstrap_from_master()`, when box is waiting for applier's state `APPLIER_FETCHED_SNAPSHOT` or `APPLIER_FINAL_JOIN`.

The most complex part would be vinyl, which in `engine_begin_initial_recovery_xc()` can already create some files. It is not clear what to do with them to retry.

Retry itself should re-create the appliers to fetch new ballots, try to find a new join-master, and retry. Retry would need to be done via polling with small sleeps if a leader can not be found. So as this wouldn't be a busy loop.

Another option (more complex but better) would be to subscribe on ballot updates and look for when some of the remote nodes becomes suitable to be a join-master. Hard parts here are:
1. There are no ballot updates now, it needs to be implemented.
2. Need to retry connection establishment to disconnected appliers.

### PR DESCRIPTION
**Pull request by yanshtunder**
If the error is non-critical, the instance retries join
automatically.

@TarantoolBot document
Title: Retry join automatically (for a timeout)

If the error is non-critical, the instance retries join automatically.
For example, if automatic election is used, then a new instance can
find the leader, but while it is sending a join request, the leader
can resign. The join will fail saying the former leader is read-only.
The waiting make sense in this case.

Closes #6126

### CODE REVIEW

File: src/box/applier.cc [hunk 1]
```diff
@@ -454,7 +454,7 @@ applier_wait_snapshot(struct applier *applier)
 			xrow_decode_error_xc(&row); /* re-throw error */
 		} else if (row.type != IPROTO_OK) {
 			tnt_raise(ClientError, ER_UNKNOWN_REQUEST_TYPE,
-				  (uint32_t) row.type);
+				  (uint32_t)row.type);
```
Comment (sergepetrenko) [inline src/box/applier.cc:457]: An extraneous change. Please, remove.

File: src/box/box.cc [hunk 2]
```diff
@@ -3457,7 +3462,18 @@ bootstrap_from_master(struct replica *master)
...
-	applier_resume_to_state(applier, wait_state, TIMEOUT_INFINITY);
+	try {
+		applier_resume_to_state(applier, wait_state,
+					TIMEOUT_INFINITY);
+	} catch (...) {
+		return -1;
+	}
+	try {
+		applier_resume_to_state(applier, APPLIER_CONTINUE_SNAPSHOT,
+					TIMEOUT_INFINITY);
```
Comment (sergepetrenko) [inline src/box/box.cc:3473]: I suggest you refactor this piece a bit.
`wait_state` doesn't matter anymore, because you wait for `APPLIER_CONTINUE_SNAPSHOT` regardless of `wait_state`.

So you may remove the wait for `wait_state` here and only wait for `APPLIER_CONTINUE_SNAPSHOT`

File: src/box/box.cc [hunk 3]
```diff
@@ -3499,6 +3515,28 @@ bootstrap_from_master(struct replica *master)
...
+
+/**
+ * If bootstrap failed from remote master rebootstrap it,
+ * in the case of non-critical error.
+ */
+static void
+rebootstrap_from_master(struct replica *master)
+{
+	do {
+		box_restart_replication();
```
Comment (sergepetrenko) [inline src/box/box.cc:3530]: It's not clear why you reconnect all the appliers between the bootstrap attemts.
This is done to re-fetch remote master ballots so that `replicaset_find_join_master` can operate on fresh data.
Please, add a comment.

File: src/box/box.cc [hunk 4]
```diff
@@ -3545,7 +3583,7 @@ bootstrap(const struct tt_uuid *instance_uuid,
 	assert(master == NULL || master->applier != NULL);
 
 	if (master != NULL && !tt_uuid_is_equal(&master->uuid, &INSTANCE_UUID)) {
-		bootstrap_from_master(master);
+		rebootstrap_from_master(master);
```
Comment (sergepetrenko) [inline src/box/box.cc:3586]: `box_restart_replication()` and `replicaset_find_join_master()` are called above, and they will be called again in `rebootsrap_from_master()`.
This means that the piece of code above should be part of `rebootstrap_from_master()`.
Same about the piece below. With `bootstrap_master()`

File: src/box/box.cc [hunk 5]
```diff
@@ -3499,6 +3515,28 @@ bootstrap_from_master(struct replica *master)
...
+static void
+rebootstrap_from_master(struct replica *master)
+{
+	do {
+		box_restart_replication();
+
+		master = replicaset_find_join_master();
+		assert(master == NULL || master->applier != NULL);
+
+		if (master == NULL || master->applier == NULL ||
```
Comment (sergepetrenko) [inline src/box/box.cc:3535]: It's not an error when master == NULL.
It simply means that this node is the best bootstrap leader available.
So you should call bootstrap_master() in this case.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the patch!
It's mostly what I wanted.
Please, find my comments below.

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+
+local g = t.group('gh_6126')
+
+g.before_each(function(cg)
+    cg.cluster = cluster:new({})
+    local master_uri = server.build_instance_uri('master')
+    local replica_uri = server.build_instance_uri('replica')
+    local replication = {master_uri, replica_uri}
+    local box_cfg = {
+        listen = replica_uri,
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply test/replication-luatest/gh_6126_auto_rejoin_test.lua]: Done

File: src/box/box.cc (hunk 4 above)
Comment (yanshtunder) [reply src/box/box.cc]: Done

File: src/box/box.cc (hunk 3 above)
Comment (yanshtunder) [reply src/box/box.cc]: I wrote comment

File: src/box/applier.cc (hunk 1 above)
Comment (yanshtunder) [reply src/box/applier.cc]: Thanks for the review!
I fixed all.

File: src/box/applier.cc [hunk 7]
```diff
@@ -546,7 +548,6 @@ applier_fetch_snapshot(struct applier *applier)
 	row.type = IPROTO_FETCH_SNAPSHOT;
 	coio_write_xrow(io, &row);
 
-	applier_set_state(applier, APPLIER_FETCH_SNAPSHOT);
```
Comment (sergepetrenko) [inline src/box/applier.cc:549]: There are two quite similar states, APPLIER_INITIAL_JOIN and APPLIER_FETCH_SNAPSHOT.

I remember asking you to delete the latter, because we don't wait for it anywhere.
You need to set the state to APPLIER_INITIAL_JOIN here instead, so that `applier_fetch_snapshot()` is tracked correctly in `replication.cc`.

Let's do this in a separate preparatory commit.

File: src/box/box.cc [hunk 8]
```diff
@@ -3436,12 +3436,17 @@ bootstrap_master(const struct tt_uuid *replicaset_uuid)
  * @param[out] start_vclock  the vector time of the master
  *                           at the moment of replica bootstrap
  */
-static void
+static int
```
Comment (sergepetrenko) [inline src/box/box.cc:3439]: Please, describe the return value in the comment.

The function might throw an exception on an unrecoverable error, it might return -1 in case of a transient error and it might return 0 in case everything is fine.

File: src/box/box.cc [hunk 9]
```diff
@@ -3436,12 +3436,17 @@ bootstrap_master(const struct tt_uuid *replicaset_uuid)
...
 bootstrap_from_master(struct replica *master)
```
Comment (sergepetrenko) [inline src/box/box.cc:3440]: Also, while we are at it: this looks super strange, that the function might throw and might return an error at the same time.

Let's better split it in two: I'm bad with names, but something like
`bootstrap_from_master_begin()`, which never throws, returns 0 when everything is fine and returns -1 when there was an error, which may be retried.
and
`bootstrap_from_master_end()` which returns nothing and throws an exception. Because any of its errors are unrecoverable anyway.

File: src/box/box.cc [hunk 10]
```diff
@@ -3621,7 +3653,17 @@ local_recovery(const struct tt_uuid *instance_uuid,
 		struct replica *master;
 		if (replicaset_needs_rejoin(&master)) {
 			say_crit("replica is too old, initiating rebootstrap");
-			return bootstrap_from_master(master);
+			while (true) {
+				do {
+					box_restart_replication();
```
Comment (sergepetrenko) [inline src/box/box.cc:3658]: I'd rewrite this a bit. Seems to me it's possible that `replicaset_needs_rejoin` returns `false` after one or more iterations of `box_restart_replication()`.

For example, the instance couldn't connect to the one remote node which holds the WALS for it.
Then the instance fails `bootstrap_from_master`, and reconnects to all the nodes.

I'm trying to say you need something similar to:

```c
while(replicaset_needs_rejoin(&master) {
    if (bootstrap_from_master(master) == 0)
         return;
    box_restart_replication()
}
```

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+    local master_uri = server.build_instance_uri('master')
+    local replica_uri = server.build_instance_uri('replica')
+    local replication = {master_uri, replica_uri}
+    local box_cfg = {
+        replication = replication,
+    }
+    cg.replica = cg.cluster:build_and_add_server(
+        {alias = 'replica', box_cfg = box_cfg})
+
+    box_cfg.replication = {master_uri}
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6126_auto_rejoin_test.lua:19]: why not `box_cfg.replication = nil` ?

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua [hunk 12]
```diff
@@ -0,0 +1,55 @@
...
+    cg.master = cg.cluster:build_and_add_server(
+        {alias = 'master', box_cfg = box_cfg})
+
+    cg.master:start()
+end)
+
+g.after_each(function(cg)
+    cg.cluster.servers = nil
+    cg.cluster:drop()
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6126_auto_rejoin_test.lua:28]: Let's set `cluster.servers` to nil after `cg.cluster:drop()`.
`cg.cluster:drop()` iterates over `cluster.servers` to clean them up.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Hi! Thanks for the fixes!
Please, find my comments below.

File: src/box/box.cc [hunk 13]
```diff
@@ -3539,23 +3550,44 @@ bootstrap(const struct tt_uuid *instance_uuid,
...
+	 *
+	 * 1) Try to connect to all nodes in the replicaset during
+	 *    the waiting period in order to update their ballot.
+	 *
+	 * 2) After updated the ballot of all nodes, it are looking
+	 *    for a new master.
+	 *
+	 * 3) Wait until bootstrap_from_master succeeds.
+	 */
+	while (true) {
```
Comment (sergepetrenko) [inline src/box/box.cc:3567]: There's a good comment in the issue description:
> Retry itself should re-create the appliers to fetch new ballots, try to find a new join-master, and retry. Retry would need to be done via polling with small sleeps if a leader can not be found. So as this wouldn't be a busy loop.

Let's do that. I missed that completely.

File: src/box/applier.cc (hunk 7 above)
Comment (yanshtunder) [reply src/box/applier.cc:549]: @sergos, duplicate your comment please. I agree with it.

File: src/box/box.cc (hunk 13 above)
Comment (yanshtunder) [reply src/box/box.cc:3606]: Done. I'm not sure what's right

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua (hunk 11 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_6126_auto_rejoin_test.lua]: Done

File: src/box/box.cc (hunk 10 above)
Comment (yanshtunder) [reply src/box/box.cc]: I understand like this:
If the current instance is too far behind its peers in the replica set, it must be rebooted. `replicaset_needs_rejoin()` returns true and sets the master to the instance that will be used to rejoin.

Since the master has been installed, there is no need to look for a new master after reconnecting to all nodes.

File: src/box/box.cc (hunk 9 above)
Comment (yanshtunder) [reply src/box/box.cc]: Done

File: src/box/box.cc (hunk 8 above)
Comment (yanshtunder) [reply src/box/box.cc:3455]: Comment is below

File: changelogs/unreleased/gh-6126-retry-join-automatically.md [hunk 14]
```diff
@@ -0,0 +1,4 @@
+## feature/core
+
+* If the error is non-critical, the instance retries join
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply changelogs/unreleased/gh-6126-retry-join-automatically.md]: Done

File: changelogs/unreleased/gh-6126-retry-join-automatically.md [hunk 15]
```diff
@@ -0,0 +1,4 @@
...
+  automatically. (gh-6126)
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply changelogs/unreleased/gh-6126-retry-join-automatically.md]: Done

File: src/box/box.cc [hunk 16]
```diff
@@ -3449,15 +3449,20 @@ bootstrap_master(const struct tt_uuid *replicaset_uuid)
...
  *
- * @param[out] start_vclock  the vector time of the master
- *                           at the moment of replica bootstrap
+ * \return -1 in case of a transient error
+ *          0 in case everything is fine
  */
-static void
-bootstrap_from_master(struct replica *master)
+static int
+bootstrap_from_master_begin(struct replica *master)
```
Comment (Gerold103) [inline src/box/box.cc:3456]: You always call `bootstrap_from_master_end` after `bootstrap_from_master_begin`. I suggest to keep them one function then.

File: src/box/box.cc [hunk 17]
```diff
@@ -3473,12 +3478,41 @@ bootstrap_from_master(struct replica *master)
...
+	} catch (...) {
+		return -1;
+	}
+
+	try {
+		applier_resume_to_state(applier, APPLIER_CONTINUE_SNAPSHOT,
+					TIMEOUT_INFINITY);
+	} catch (...) {
+		return -1;
+	}
```
Comment (Gerold103) [inline src/box/box.cc:3493]: As Sergey said in his previous comment, you don't need 2 resumes. You can just keep the last one:
```Diff
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -3475,23 +3475,12 @@ bootstrap_from_master_begin(struct replica *master)
 	 */
 
 	assert(!tt_uuid_is_nil(&INSTANCE_UUID));
-	enum applier_state wait_state = replication_anon ?
-					APPLIER_FETCH_SNAPSHOT :
-					APPLIER_INITIAL_JOIN;
-	try {
-		applier_resume_to_state(applier, wait_state,
-					TIMEOUT_INFINITY);
-	} catch (...) {
-		return -1;
-	}
-
 	try {
 		applier_resume_to_state(applier, APPLIER_CONTINUE_SNAPSHOT,
 					TIMEOUT_INFINITY);
 	} catch (...) {
 		return -1;
 	}
-
 	return 0;
 }
```

File: src/box/box.cc [hunk 18]
```diff
@@ -3473,12 +3478,41 @@ bootstrap_from_master(struct replica *master)
...
+
+	return 0;
+}
+
+/**
+ * Bootstrap from the remote master
+ * \pre master->applier->state == APPLIER_READY
+ *
+ * @param[out] start_vclock  the vector time of the master
```
Comment (Gerold103) [inline src/box/box.cc:3502]: There is no such param in `bootstrap_from_master_end`.

File: src/box/box.cc [hunk 19]
```diff
@@ -3473,12 +3478,41 @@ bootstrap_from_master(struct replica *master)
...
+	} catch (...) {
+		return -1;
+	}
+
+	return 0;
+}
+
+/**
+ * Bootstrap from the remote master
+ * \pre master->applier->state == APPLIER_READY
```
Comment (Gerold103) [inline src/box/box.cc:3500]: Not true really. You rely on it being in `APPLIER_CONTINUE_SNAPSHOT`, don't you?

File: src/box/box.cc [hunk 20]
```diff
@@ -3555,23 +3589,47 @@ bootstrap(const struct tt_uuid *instance_uuid,
...
-		bootstrap_from_master(master);
-		/* Check replica set UUID */
-		if (!tt_uuid_is_nil(replicaset_uuid) &&
-		    !tt_uuid_is_equal(replicaset_uuid, &REPLICASET_UUID)) {
-			tnt_raise(ClientError, ER_REPLICASET_UUID_MISMATCH,
-				  tt_uuid_str(replicaset_uuid),
-				  tt_uuid_str(&REPLICASET_UUID));
+
+	struct replica *master;
+
```
Comment (Gerold103) [inline src/box/box.cc:3594]: Please, reduce number of empty lines in the code. Usually it is fine here and there, but tbh in this patch it seems too much.

File: src/box/box.cc [hunk 21]
```diff
@@ -3555,23 +3589,47 @@ bootstrap(const struct tt_uuid *instance_uuid,
...
+			bootstrap_master(replicaset_uuid);
+			*is_bootstrap_leader = true;
+			break;
 		}
-	} else {
-		bootstrap_master(replicaset_uuid);
-		*is_bootstrap_leader = true;
+
+		fiber_sleep(0.1);
 	}
```
Comment (Gerold103) [inline src/box/box.cc:3633]: Please,
1 - Reduce indentation level;
2 - Add some logging that a first join attempt has failed, and that you are retrying every N secs;
3 - It doesn't look a good idea to keep the retrying infinitely, better make it last not longer than `replication_connect_timeout`;

File: src/box/box.cc [hunk 22]
```diff
@@ -3635,9 +3693,13 @@ local_recovery(const struct tt_uuid *instance_uuid,
...
 		struct replica *master;
-		if (replicaset_needs_rejoin(&master)) {
+		while (replicaset_needs_rejoin(&master)) {
 			say_crit("replica is too old, initiating rebootstrap");
-			return bootstrap_from_master(master);
+			if (bootstrap_from_master_begin(master) == 0) {
+				bootstrap_from_master_end(master);
+				return;
+			}
+			box_restart_replication();
```
Comment (Gerold103) [inline src/box/box.cc:3702]: 1 - Is this retrying tested?
2 - I suggest to add a `fiber_sleep()` here, otherwise you are potentially making a busy loop;
3 - Need a log that you couldn't rejoin first time and will retry every N secs;

File: src/box/box.cc [hunk 23]
```diff
@@ -3635,9 +3693,13 @@ local_recovery(const struct tt_uuid *instance_uuid,
 		box_update_replication();
 
 		struct replica *master;
-		if (replicaset_needs_rejoin(&master)) {
+		while (replicaset_needs_rejoin(&master)) {
 			say_crit("replica is too old, initiating rebootstrap");
```
Comment (Gerold103) [inline src/box/box.cc:3697]: This log doesn't need to be repeated. Would be better to log it out of the loop, above.

File: src/box/applier.cc [hunk 24]
```diff
@@ -499,6 +499,8 @@ applier_wait_snapshot(struct applier *applier)
 		coio_read_xrow(io, ibuf, &row);
 	}
 
+	applier_set_state(applier, APPLIER_CONTINUE_SNAPSHOT);
```
Comment (Gerold103) [inline src/box/applier.cc:502]: The name is really confusing IMO. 'Continue' means it was stopped. But it wasn't. Intuitively, FETCH_SNAPSHOT is the good name, but it is occupied. I would suggest to reshuffle the names a bit:
- `APPLIER_FETCH_SNAPSHOT` -> `APPLIER_WAIT_SNAPSHOT`;
- `APPLIER_CONTINUE_SNAPSHOT` -> `APPLIER_FETCH_SNAPSHOT`.

The first rename should be done in a separate patch. The only worrying part is that there might be some tests using `fetch_snapshot` or whatever it is stringified to. They could be fixed. But I would also recommend to check if the state `fetch_snapshot` is documented anywhere on our web-site. If it is, then we need to think more about whether it can be renamed.

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua [hunk 25]
```diff
@@ -0,0 +1,51 @@
...
+    cg.replica:start({wait_for_readiness = false})
+    local logfile = fio.pathjoin(cg.replica.workdir, 'replica.log')
+    t.helpers.retrying({}, function()
+        t.assert(cg.replica:grep_log('ER_READONLY', nil,
+            {filename = logfile}), 'Can\'t modify data on a read-only'..
+            'instance - box.cfg.read_only is true')
+
+        t.assert(g.master:exec(function()
+            return box.space._cluster:count() == 1
+        end),  'No join while master is read-only')
```
Comment (Gerold103) [inline test/replication-luatest/gh_6126_auto_rejoin_test.lua:39]: If you do that inside of `retrying`, then if it becomes false, you won't notice until the test times out. I would suggest to move this check after `retrying`.

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua [hunk 26]
```diff
@@ -0,0 +1,51 @@
...
+
+    -- Test that replica joins after master became writeable
+    cg.master:exec(function() box.cfg{read_only = false} end)
+    cg.replica:wait_for_readiness()
+    t.helpers.retrying({}, function()
+        t.assert(g.master:exec(function()
+            return box.space._cluster:count() == 2
+        end), 'Join after master became writeable')
+        cg.replica:assert_follows_upstream(1)
+    end)
```
Comment (Gerold103) [inline test/replication-luatest/gh_6126_auto_rejoin_test.lua:50]: Please, add more test cases. For example, what if the master is writeable, but the access is denied?
```Lua
--
-- Instance 1
--
-- Step 1
--
box.cfg{
    listen = 3313,
}
s1 = box.schema.create_space('test1', {engine = 'vinyl'})
_ = s1:create_index('pk')
s1:replace{1}
s2 = box.schema.create_space('test2')
_ = s2:create_index('pk')
s2:replace{2}
box.snapshot()
s1:replace{3}
s2:replace{4}

-- Step 3
--
box.schema.user.grant('guest', 'super')

--
-- Instance 2
--
-- Step 2
--
box.cfg{replication = 3313}
```
It works, but would be good to have it in the tests.
Also, please, add more data to the master instance - a vinyl space, a memtx space, make a snapshot, write more data, that would ensure vinyl has created some files and has in-memory data too.

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Thanks for the patch!

File: src/box/box.cc (hunk 16 above)
Comment (sergepetrenko) [reply src/box/box.cc:3456]: I asked Yan to do that: see [my previous comment](https://github.com/tarantool/tarantool/pull/7183#discussion_r900214694).
The names are quite bad indeed. I don't know. `bootstrap_from_master_retryable` or something similar maybe?

File: src/box/applier.cc (hunk 7 above)
Comment (sergepetrenko) [reply src/box/applier.cc]: > This commit doesn't seem make sense

Exactly. It only makes sense together with this PR. That's why Vlad asked you to send it as part of this PR.
Vlad also has 2 good points [here](https://github.com/tarantool/tarantool/pull/7183#discussion_r906427440) and [there](https://github.com/tarantool/tarantool/pull/7287#pullrequestreview-1014324471).

In summary:

    APPLIER_FETCH_SNAPSHOT -> APPLIER_WAIT_SNAPSHOT;
    APPLIER_CONTINUE_SNAPSHOT -> APPLIER_FETCH_SNAPSHOT;
    APPLIER_INITIAL_JOIN -> APPLIER_WAIT_SNAPSHOT;

And drop APPLIER_INITIAL_JOIN then.

I couldn't find any mentions of these states in doc or in tests, so we should be safe.

File: src/box/applier.cc (hunk 24 above)
Comment (sergepetrenko) [reply src/box/applier.cc:502]: Please, check out my proposal
https://github.com/tarantool/tarantool/pull/7183#discussion_r907215400

File: src/box/box.cc (hunk 13 above)
Comment (sergepetrenko) [reply src/box/box.cc:3606]: I should've pasted a smaller quote, sorry.
I meant you should add small sleeps between loop iterations so that it's not a busy loop.
Vlad already mentioned it in his comment.

File: src/box/box.cc (hunk 10 above)
Comment (sergepetrenko) [reply src/box/box.cc]: My point was that it's possible that the master which holds the needed WALs might be unreachable. That's why on some iteration `replicaset_needs_rejoin` returns true.

Now after some attempts the master might become reachable again. In this case `replicaset_needs_rejoin` will return false, and the instance will continue without rejoining.

No changes in code required. Your current version is correct.

File: src/box/applier.cc (hunk 24 above)
Comment (sergos) [reply src/box/applier.cc:502]: I can't see any verification that the 'continue' is performed using the same snapshot. Between the unfinished fetch and the continuation the snapshot can be done on the relay side. This new snapshot can contain some new data with PK our local applier consider as 'done'.

Comment (sergepetrenko) [reply src/box/applier.cc:502]: I don't understand. No data is applied before `APPLIER_CONTINUE_SNAPSHOT` is set, and no retries are possible after `APPLIER_CONTINUE_SNAPSHOT`. So the applier will either receive a whole snapshot, or receive nothing at all (simply some metadata, which will be overwritten after a retry)

Comment (sergepetrenko) [reply src/box/applier.cc:502]: This patch doesn't help when a snapshot receipt is interrupted in the middle due to some error. It's not easy for the reason you mention (about new data for already processed PK) and also because vinyl creates files which can't be easily overwritten or amended.

So this patch only lets replica retry joining when an error occurs before master starts sending the snapshot

File: src/box/box.cc (hunk 16 above)
Comment (Gerold103) [reply src/box/box.cc:3456]: It doesn't look good that we are trying to determine the result by whether it throws or not. If it throws, it should throw on any error. And if it returned fine, then it wasn't an error. The second option could be done by an out parameter or something. The function simply doesn't look splittable. These 2 pieces are useless without each other. We can't even find names for them.

Comment (sergepetrenko) [reply src/box/box.cc:3456]: Ok, I see your point.
Then @yanshtunder, I suggest to make the function look like
```
static bool
bootstrap_from_master(struct replica *master)
```
And when it failed with a transient error, return `false`.
On success return `true`.
And on an unrecoverable error, throw.

File: src/box/box.cc (hunk 23 above)
Comment (yanshtunder) [reply src/box/box.cc]: Done

File: src/box/box.cc (hunk 22 above)
Comment (yanshtunder) [reply src/box/box.cc:3698]: All done

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua (hunk 25 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_6126_auto_rejoin_test.lua]: Done

File: src/box/applier.cc (hunk 24 above)
Comment (yanshtunder) [reply src/box/applier.cc]: Done

File: src/box/box.cc (hunk 20 above)
Comment (yanshtunder) [reply src/box/box.cc]: I can't reduce number of empty lines in the code. Number of empty lines equal to 8 default in this file. I created the new function `check_replicaset_uuid()`

File: src/box/box.cc (hunk 19 above)
Comment (yanshtunder) [reply src/box/box.cc]: Fixed

File: src/box/box.cc (hunk 17 above)
Comment (yanshtunder) [reply src/box/box.cc:3486]: Done

File: src/box/box.cc (hunk 16 above)
Comment (yanshtunder) [reply src/box/box.cc]: I did as @sergepetrenko  said

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua [hunk 27]
```diff
@@ -0,0 +1,119 @@
...
+    cg.master:start()
+    cg.replica:start()
+    local logfile = fio.pathjoin(cg.replica.workdir, 'replica.log')
+    t.helpers.retrying({}, function()
+        t.assert(cg.replica:grep_log('replica is too old', nil,
+                {filename = logfile}), 'initiating rebootstrap')
+    end)
+end
+
+g.test_access_denied = function(cg)
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply test/replication-luatest/gh_6126_auto_rejoin_test.lua:79]: It seems a proper test case would be something like:
Start two instances, anonymous and normal. Configure their instance_uuid so that anonymous instance has a smaller uuid than a normal one (so that it's chosen a bootstrap leader by some third node). Let them finish bootstrap. Set normal instance to read-only.

Now try to add third instance. It should fail with ER_UNSUPPORTED. because it will chose an anonymous replica as its bootstrap master.
Let it retry, then set normal instance to `box.cfg{read_only=false}`.

Now 3rd instance should find another node to boot off (normal one) and boot successfully.

I tried similar test locally and it ended up in a segfault on a third node:
```
2022-07-06 17:01:42.276 [27202] main/103/interactive I> connecting to 1 replicas
2022-07-06 17:01:42.277 [27202] main/110/applier/ I> remote master dac002d9-adcb-4845-b7f5-a5e8326ec2d4 at [::1]:3301 running Tarantool 2.11.0
2022-07-06 17:01:42.277 [27202] main/103/interactive I> connected to 1 replicas
2022-07-06 17:01:42.277 [27202] main/103/interactive I> bootstrapping replica from dac002d9-adcb-4845-b7f5-a5e8326ec2d4 at [::1]:3301
2022-07-06 17:01:42.278 [27202] main/110/applier/ I> can't read row
2022-07-06 17:01:42.278 [27202] main/110/applier/ box.cc:3050 E> ER_UNSUPPORTED: Anonymous replica does not support registration of non-anonymous nodes.
2022-07-06 17:01:42.278 [27202] main/103/interactive I> join attempt has failed, will retry every 1.00 second
2022-07-06 17:01:43.278 [27202] main/103/interactive I> connecting to 1 replicas
2022-07-06 17:01:43.279 [27202] main/111/applier/ I> remote master dac002d9-adcb-4845-b7f5-a5e8326ec2d4 at [::1]:3301 running Tarantool 2.11.0
2022-07-06 17:01:43.279 [27202] main/103/interactive I> connected to 1 replicas
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x8
  context: 0x11617fb68
  siginfo: 0x11617fb00
Current time: 1657116103
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x10a1ff3ab in crash_collect+187
#2  0x10a1ff25c in crash_signal_cb+60
#3  0x7fff2038cd7d in _sigtramp+29
#4  0x10a0c8a2e in replica_on_applier_state_f(trigger*, void*)+62
#5  0x10a2317ac in trigger_run+140
#6  0x10a0cf16d in trigger_run_xc(rlist*, void*)+29
#7  0x10a0cd413 in applier_set_state(applier*, applier_state)+131
#8  0x10a0d063b in applier_disconnect(applier*, applier_state)+27
#9  0x10a0ce69a in applier_f(__va_list_tag*)+2554
#10 0x109f7a3da in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+26
#11 0x10a209cc7 in fiber_loop+183
#12 0x10a57e6f2 in coro_init+114
Abort trap: 6
```

Now at least something is tested.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the fixes!
The patch looks much better already.

One comment right away: let's rename the first commit.

Please, see other comments below.

File: src/box/box.cc [hunk 28]
```diff
@@ -3449,17 +3449,23 @@ bootstrap_master(const struct tt_uuid *replicaset_uuid)
 /**
  * Bootstrap from the remote master
  * \pre  master->applier->state == APPLIER_CONNECTED
- * \post master->applier->state == APPLIER_READY
+ * \post master->applier->state == APPLIER_FETCH_SNAPSHOT
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply src/box/box.cc:3452]: I did as it was said here https://github.com/tarantool/tarantool/pull/7183#discussion_r906420278

File: src/box/box.cc [hunk 29]
```diff
@@ -3555,23 +3583,44 @@ bootstrap(const struct tt_uuid *instance_uuid,
...
+	 * Rebootstrap
+	 *
+	 * 1) Try to connect to all nodes in the replicaset during
+	 *    the waiting period in order to update their ballot.
+	 *
+	 * 2) After updated the ballot of all nodes, it are looking
+	 *    for a new master.
+	 *
+	 * 3) Wait until bootstrap_from_master succeeds.
+	 */
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply src/box/box.cc:3597]: I'll leave a comment. It sometimes turns out to be more useful.

File: changelogs/unreleased/gh-6126-retry-join-automatically.md [hunk 30]
```diff
@@ -0,0 +1,18 @@
...
+  there is no way to recover, because any of these mistakes
+  are irreparable anyway. For example, vinyl can create some
+  files. It's not clear what to do with them to try bootstrap
+  again (gh-6126).
+
+* In this patch will be introduced a new state for which the
+  name is suitable: `APPLIER_FETCH_SNAPSHOT`. But it's already
+  taken. The names of the state will be reshuffled a bit. Also
+  in this patch we are removing the state `APPLIER_INITIAL_JOIN`
+  and we are using the state `APPLIER_WAIT_SNAPSHOT` instead
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply changelogs/unreleased/gh-6126-retry-join-automatically.md:17]: I take into account in the future. Done

File: changelogs/unreleased/gh-6126-retry-join-automatically.md [hunk 31]
```diff
@@ -0,0 +1,18 @@
...
+
+* There are two types of errors: critical and non-critical.
+  You can recover from non-critical errors. For example, the
+  connection master turned out to be read-only. It looks like
+  a configuration error. If the error is non-critical, the
+  instance retries join automatically. After a critical error
+  there is no way to recover, because any of these mistakes
+  are irreparable anyway. For example, vinyl can create some
+  files. It's not clear what to do with them to try bootstrap
+  again (gh-6126).
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply changelogs/unreleased/gh-6126-retry-join-automatically.md:11]: Done

File: src/box/box.cc [hunk 32]
```diff
@@ -3635,9 +3684,26 @@ local_recovery(const struct tt_uuid *instance_uuid,
...
+				say_crit("replica is too old, initiating "
+					 "rebootstrap");
+			}
+
+			if (bootstrap_from_master(master))
+				return;
+			box_restart_replication();
+
+			if (!say_once) {
+				say_info("join attempt has failed, will "
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply src/box/box.cc:3701]: Done

File: src/box/box.cc [hunk 33]
```diff
@@ -3449,17 +3449,23 @@ bootstrap_master(const struct tt_uuid *replicaset_uuid)
 /**
  * Bootstrap from the remote master
  * \pre  master->applier->state == APPLIER_CONNECTED
- * \post master->applier->state == APPLIER_READY
+ * \post master->applier->state == APPLIER_FETCH_SNAPSHOT
  *
- * @param[out] start_vclock  the vector time of the master
- *                           at the moment of replica bootstrap
+ * \return throw an exception in case an unrecoverable error
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply src/box/box.cc:3454]: Done

File: src/box/applier.cc [hunk 34]
```diff
@@ -105,7 +105,7 @@ applier_log_error(struct applier *applier, struct error *e)
 		break;
 	case APPLIER_SYNC:
 	case APPLIER_FOLLOW:
-	case APPLIER_INITIAL_JOIN:
+	case APPLIER_WAIT_SNAPSHOT:
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply src/box/applier.cc:108]: Done

File: src/box/box.cc [hunk 35]
```diff
@@ -3491,13 +3497,19 @@ bootstrap_from_master(struct replica *master)
 	 */
 
 	assert(!tt_uuid_is_nil(&INSTANCE_UUID));
-	enum applier_state wait_state = APPLIER_WAIT_SNAPSHOT;
-	applier_resume_to_state(applier, wait_state, TIMEOUT_INFINITY);
+	try {
+		applier_resume_to_state(applier, APPLIER_FETCH_SNAPSHOT,
```
Comment (sergepetrenko) [inline src/box/box.cc:3501]: Should be `APPLIER_CONTINUE_SNAPSHOT` as we discussed?

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the fixes!
The test looks good. Only one comment left from my side. Once it's fixed, please, proceed with @Gerold103's review

File: src/box/box.cc (hunk 35 above)
Comment (yanshtunder) [reply src/box/box.cc:3501]: > Should be `APPLIER_CONTINUE_SNAPSHOT` as we discussed?
We wanted to make a change ([comment](https://github.com/tarantool/tarantool/pull/7183#discussion_r907215400)), didn't we?

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua (hunk 26 above)
Comment (Gerold103) [reply test/replication-luatest/gh_6126_auto_rejoin_test.lua]: Nope, I don't see it on the branch.

File: src/box/box.cc (hunk 20 above)
Comment (Gerold103) [reply src/box/box.cc]: I am quite sure the file has many more than just 8 empty lines. But there seems to be misunderstanding. I meant "empty lines", not "indentation level".

Comment (Gerold103) [reply src/box/box.cc]: The new function has a bit unclear name. "Check uuid" for what? For being invalid? For not matching our own `REPLICASET_UUID`? Besides, it is used in a single place anyway. There are ways to reduce indentation in such cases without factoring any code out:
```Diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 53252b768..6d61c8d2c 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -3550,20 +3550,6 @@ bootstrap_from_master(struct replica *master)
 	return true;
 }
 
-/*
- * Check replica set UUID
- */
-static void
-check_replicaset_uuid(const struct tt_uuid *replicaset_uuid)
-{
-	if (!tt_uuid_is_nil(replicaset_uuid) &&
-	    !tt_uuid_is_equal(replicaset_uuid, &REPLICASET_UUID)) {
-		tnt_raise(ClientError, ER_REPLICASET_UUID_MISMATCH,
-			  tt_uuid_str(replicaset_uuid),
-			  tt_uuid_str(&REPLICASET_UUID));
-	}
-}
-
 /**
  * Bootstrap a new instance either as the first master in a
  * replica set or as a replica of an existing master.
@@ -3620,19 +3606,24 @@ bootstrap(const struct tt_uuid *instance_uuid,
 	while (true) {
 		box_restart_replication();
 		master = replicaset_find_join_master();
-
-		if (master != NULL &&
-		    !tt_uuid_is_equal(&master->uuid, &INSTANCE_UUID)) {
-			if (bootstrap_from_master(master)) {
-				check_replicaset_uuid(replicaset_uuid);
-				break;
-			}
-		} else {
+		if (master == NULL ||
+		    tt_uuid_is_equal(&master->uuid, &INSTANCE_UUID)) {
 			bootstrap_master(replicaset_uuid);
 			*is_bootstrap_leader = true;
 			break;
 		}
 
+		bool is_bootstrapped = bootstrap_from_master(master);
+		if (is_bootstrapped && !tt_uuid_is_nil(replicaset_uuid) &&
+		    !tt_uuid_is_equal(replicaset_uuid, &REPLICASET_UUID)) {
+			tnt_raise(ClientError, ER_REPLICASET_UUID_MISMATCH,
+				  tt_uuid_str(replicaset_uuid),
+				  tt_uuid_str(&REPLICASET_UUID));
+		}
+		if (is_bootstrapped) {
+			*is_bootstrap_leader = false;
+			break;
+		}
 		if (!say_once) {
 			say_info("rebootstrap failed, will retry "
 				 "every %.2lf second", timeout);
```

File: src/box/box.cc (hunk 21 above)
Comment (Gerold103) [reply src/box/box.cc]: We are still retrying infinitely despite I suggested to limit the attempts by `replication_connect_timeout`. But ok, I am fine with the current way too while nobody complains.

**Review by Gerold103 — COMMENTED** [review]
In case you missed it somehow, I responded to some old comments. Not all of them are fixed, apparently.

File: src/box/box.cc (hunk 20 above)
Comment (yanshtunder) [reply src/box/box.cc]: Yea, I misunderstood you. Fixed.

File: test/replication-luatest/gh_6126_auto_rejoin_test.lua (hunk 26 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_6126_auto_rejoin_test.lua]: Done

**Review by Gerold103 — APPROVED** [review]
Thanks for the fixes!

File: src/box/box.cc (hunk 35 above)
Comment (sergepetrenko) [reply src/box/box.cc:3500]: Yes, indeed, I got confused. Sorry.

**Review by sergepetrenko — APPROVED** [review]
Let's Get This Merged.

**Comment by yanshtunder** [comment]
Test is red, because checkpatch.pl have the bug. I opened the issue on [that](https://github.com/tarantool/checkpatch/issues/35).

**Comment by sergepetrenko** [comment]
Should be backported to 2.10: #8681 
Will do in scope of #8682
