### PR TITLE
test/fuzz: add dummy mp_check_on_error in xrow fuzzer

### LINKED ISSUE #11178: src/lib/core/diag.h:355: void diag_add_error(struct diag *, struct error *): Assertion `diag->last != NULL' failed.
**Bug description**

An assertion  `diag->last != NULL` in ` src/lib/core/diag.h` is reachable.

* OS: Linux
* Architecture: amd64

**Steps to reproduce**

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.

**Actual behavior**

```c++
command: /mnt/scratch0/clusterfuzz/resources/platform/linux/unshare -c -n /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_tarantool_caa3a1ad02c74673283d2bdba6f7650ecd7baf27/revisions/xrow_header_decode_fuzzer -runs=100 '/mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/04f9d746ad58d918fcadc2e3fd276b98E.-6.ADDR.0.INSTR.[UNKNOWN].fuzz'
	Time ran: 0.03873610496520996
	
	INFO: Running with entropic power schedule (0xFF, 100).
	INFO: Seed: 2174505366
	INFO: Loaded 1 modules   (13462 inline 8-bit counters): 13462 [0x599cd9b9c3e8, 0x599cd9b9f87e),
	INFO: Loaded 1 PC tables (13462 PCs): 13462 [0x599cd9b9f880,0x599cd9bd41e0),
	/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_tarantool_caa3a1ad02c74673283d2bdba6f7650ecd7baf27/revisions/xrow_header_decode_fuzzer: Running 1 inputs 100 time(s) each.
	Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/04f9d746ad58d918fcadc2e3fd276b98E.-6.ADDR.0.INSTR.[UNKNOWN].fuzz
	xrow_header_decode_fuzzer: src/lib/core/diag.h:355: void diag_add_error(struct diag *, struct error *): Assertion `diag->last != NULL' failed.
	==2794== ERROR: libFuzzer: deadly signal
	    #0 0x599cd9976b31 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
	    #1 0x599cd987b8d8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
	    #2 0x599cd985ec73 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:231:3
	    #3 0x7faa7776b41f in libpthread.so.0
	    #4 0x7faa771f500a in __libc_signal_restore_set /build/glibc-LcI20x/glibc-2.31/sysdeps/unix/sysv/linux/internal-signals.h:86:3
	    #5 0x7faa771f500a in raise /build/glibc-LcI20x/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:48:3
	    #6 0x7faa771d4858 in abort /build/glibc-LcI20x/glibc-2.31/stdlib/abort.c:79:7
	    #7 0x7faa771d4728 in __assert_fail_base /build/glibc-LcI20x/glibc-2.31/assert/assert.c:92:3
	    #8 0x7faa771e5fd5 in __assert_fail /build/glibc-LcI20x/glibc-2.31/assert/assert.c:101:3
	    #9 0x599cd99ae653 in diag_add_error [tarantool/src/lib/core/diag.h:355](https://github.com/tarantool/tarantool/blob/3831f9d1a75dd98d11027e8ac47bc0229966bc7d/src/lib/core/diag.h#L355):2
	    #10 0x599cd99ae017 in xrow_decode [tarantool/src/box/xrow.c:278](https://github.com/tarantool/tarantool/blob/3831f9d1a75dd98d11027e8ac47bc0229966bc7d/src/box/xrow.c#L278):3
	    #11 0x599cd99abb43 in LLVMFuzzerTestOneInput [tarantool/test/fuzz/xrow_header_decode_fuzzer.c:31](https://github.com/tarantool/tarantool/blob/3831f9d1a75dd98d11027e8ac47bc0229966bc7d/test/fuzz/xrow_header_decode_fuzzer.c#L31):2
	    #12 0x599cd9860180 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
	    #13 0x599cd984a7a5 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:327:6
	    #14 0x599cd985023f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:862:9
	    #15 0x599cd987c132 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
	    #16 0x7faa771d6082 in __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/libc-start.c:308:16
	    #17 0x599cd984298d in _start
```

**Expected behavior**

Assertion is not reachable.

### PR DESCRIPTION
**Pull request by nshy**
`xrow_decode()` expects that diag is set in case of invalid xrow body MsgPack. Thus add `mp_check_on_error()` stub which will the expectation.

Closes #11178

### CODE REVIEW

File: test/fuzz/xrow_header_decode_fuzzer.c [hunk 1]
```diff
@@ -5,10 +5,18 @@
 void
 cord_on_yield(void) {}
 
+static void
+fuzz_check_on_error(const struct mp_check_error *mperr)
+{
+	/* Dummy error. */
+	diag_set(TimedOut);
```
Comment (locker) [inline test/fuzz/xrow_header_decode_fuzzer.c]: Why `TimedOut`? Why not set `ER_INVALID_MSGPACK`?

Comment (nshy) [reply test/fuzz/xrow_header_decode_fuzzer.c]: Fixed.

```diff
-       diag_set(TimedOut);
+       diag_set(ClientError, ER_INVALID_MSGPACK, "dummy");
```
