### PR TITLE
txn: do not rollback transaction statements on timeout

### LINKED ISSUE #11088: Crash if transaction is aborted by timeout while Vinyl is reading disk
**Bug description**

Tarantool crahses if a transaction is aborted by timeout while Vinyl is reading disk.

Tarantool version:

```
Tarantool 3.4.0-entrypoint-92-ga217b0f5d4cf
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/vlad/src/tarantool/tarantool/build/debug/install -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
```

**Steps to reproduce**

Run the following script with a debug build:

```lua
local fiber = require('fiber')

os.execute('rm -rf [0-9]*')
box.cfg{}

local s = box.schema.space.create('test', {engine = 'vinyl'})
s:create_index('primary')

s:replace({1})
box.snapshot()

-- Suspend disk read for 1 second.
box.error.injection.set('ERRINJ_VY_READ_PAGE_DELAY', true)
fiber.create(function()
    fiber.sleep(2)
    box.error.injection.set('ERRINJ_VY_READ_PAGE_DELAY', false)
end)

-- Transaction is aborted while reading disk.
box.begin{timeout = 0.1}
s:update({1}, {{'!', 2, 20}})
box.commit()
```

**Actual behavior**

Tarantool crashes:

```
2025-02-04 17:02:54.379 [343642] main/104/test.lua error.cc:391 I> ERRINJ_VY_READ_PAGE_DELAY = true
2025-02-04 17:02:56.379 [343642] main/117/lua error.cc:391 I> ERRINJ_VY_READ_PAGE_DELAY = false
2025-02-04 17:02:56.380 [343642] main/104/test.lua vinyl.c:1492 W> 512/0: get([1]) => [1] took too long: 2.002 sec
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x18
  context: 0x644b0f894340
  siginfo: 0x644b0f894470
  rax      0x0                0
  rbx      0x40d2d540         1087558976
  rcx      0x0                0
  rdx      0x16               22
  rsi      0x7d2630880b60     137602976451424
  rdi      0x7d2630c250c0     137602980270272
  rsp      0x7d2630880a60     137602976451168
  rbp      0x7d2630880a90     137602976451216
  r8       0x0                0
  r9       0x0                0
  r10      0x644b0f8df130     110273546285360
  r11      0x293              659
  r12      0x0                0
  r13      0x0                0
  r14      0x40d2e0a0         1087561888
  r15      0x644add2a0e53     110272700878419
  rip      0x644add16ec0c     110272699624460
  eflags   0x10216            66070
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x18               24
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1738677776
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#1  0x644add30f907 in crash_collect+256
#2  0x644add310343 in crash_signal_cb+100
#3  0x7d2633645320 in __sigaction+80
#4  0x644add16ec0c in txn_commit_stmt+95
#5  0x644add1831ea in box_process_rw+427
#6  0x644add190b02 in box_process1+462
#7  0x644add191946 in box_update+276
#8  0x644add2a10d9 in lbox_index_update+646
#9  0x644add37f567 in lj_BC_FUNCC+70
#10 0x644add38d0ab in lua_pcall+969
#11 0x644add2ead03 in luaT_call+45
#12 0x644add2dc1a9 in lua_main+283
#13 0x644add2dcdc3 in run_script_f+3073
#14 0x644add03217c in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34
#15 0x644add31c3fe in fiber_loop+219
#16 0x644add74d4e9 in coro_init+120
Aborted
```

**Expected behavior**

No crash. Instead `TRANSACTION_CONFLICT` error is raised.

### PR DESCRIPTION
**Pull request by locker**
The transaction timeout may be triggered by vinyl taking too long to read disk while executing a statement. If we roll back the transaction in this case, the statement will be deleted, resulting in a crash when we finally try to commit the statement. Actually, in contrast to the case when a transaction is aborted by a fiber yield, there's no need to rollback the transaction on timeout  We don't rollback the transaction on conflict so let's not do it on timeout, either.

Closes #11088

### CODE REVIEW

File: src/box/txn.c [hunk 1]
```diff
@@ -1639,23 +1639,18 @@ txn_on_stop(struct trigger *trigger, void *event)
...
  */
 static void
 txn_on_timeout(ev_loop *loop, ev_timer *watcher, int revents)
 {
 	(void) loop;
 	(void) revents;
 	struct txn *txn = (struct txn *)watcher->data;
-	if (!txn_has_flag(txn, TXN_HAS_TRIGGERS) ||
-	    rlist_empty(&txn->on_rollback)) {
-		txn_rollback_to_svp(txn, NULL, false);
```
Comment (drewdzzz) [inline src/box/txn.c:1657]: Timeout is needed to release resources retained by hung transactions. Without rollback, the feature seems to be much less useful.

(By the way, I'm surprised that we don't delete memtx MVCC trackers here)

Isn't it possible to handle is rollback in `vinyl`?

Comment (drewdzzz) [reply src/box/txn.c:1657]: Or we could try to rollback only `memtx` statements here.

Comment (locker) [reply src/box/txn.c:1657]: > Timeout is needed to release resources retained by hung transactions. Without rollback, the feature seems to be much less useful.

AFAIU timeout is needed in order not to let a yielding transaction run for too long. For example, if the user runs `SELECT *` from Vinyl, it'd better be stopped sooner rather than later. Whether to abort the transaction immediately on timeout or later, when it resumes execution, doesn't really matter in this case. Although even then, we could simply kill the hung fiber manually.

As for transactions that do something and yield forever, I see the following cases:
1. The user connects to the console, types something, then disconnects. This is the case @unera talked about. In this case, the transaction will be aborted by `tx_process_rollback_on_disconnect()`.
2. There's a bug in the application code that creates fibers, start transactions, and hang. Aborting transactions wouldn't really help in this case because the remaining fibers would leak resources anyway.

> (By the way, I'm surprised that we don't delete memtx MVCC trackers here)

Exactly, this immediate rollback doesn't even work as intended. Also, it wouldn't roll back a transaction if it had rollback triggers neither would it clean up the region. To me it looks like the `txn_rollback_to_svp` call was blindly copied from the `txn_on_yield`, where it is actually required for correctness.

> Isn't it possible to handle this rollback in `vinyl`?
>
> Or we could try to rollback only `memtx` statements here.

I don't see much point in complicating the code now for this. Rolling back transactions immediately on conflict/timeout complicates the reasoning about the code because it introduces a new (asynchronous) path to roll back a transaction.

BTW the timeout is set to 1 year by default and the feature is still [undocumented](https://github.com/tarantool/doc/issues/2401) so most likely unused. I suggest to postpone "improving" it until we have an actual complaint about its current behavior. For now, let's fix the crash by simply removing the extra code.

Comment (drewdzzz) [reply src/box/txn.c:1657]: Okay, sounds convincing.

**Review by drewdzzz — APPROVED** [review]

**Review by lenkis — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 3.2 and 3.3.
