### PR TITLE
memtx: use index definition's `key_def` for point hole comparisons

### LINKED ISSUE #10159: Only one of two concurrent transactions conflict if they use different in MsgPack (but equal by key_def) keys
**Bug description**

Since the `number` type had been implemented, the constraint about equality of MsgPack contents of equal tuples has been discontinued, e. g. equal keys may have value of 0 in both `MP_UINT8` and `MP_DOUBLE` format. The same applies to the `double` field type.

The problem is that the MVCC engine [assumes the tuple keys are only equal if they're bitwice identical](https://github.com/tarantool/tarantool/blob/7e9a872f4f63cbc251936bfc7fcdc5113fc1c929/src/box/memtx_tx.c#L331). Simple solution is to compare keys using `key_compare` instead of `memcmp`.

**Steps to reproduce**

```lua
box.cfg{
    memtx_use_mvcc_engine = true
}

s = box.schema.create_space('s')
s:create_index('pk', {type = 'HASH', parts = {1, 'double'}})

fiber = require('fiber')

function unsigned(v)
    return v
end

function double(v)
    return require('ffi').cast('double', v)
end

function conflicting_fiber(cast_lookup_key, prefix, value)
    box.begin()

    -- This creates point hole items in different positions in the hash table
    -- depending on the cast function.
    print(prefix..'Check if {1} exists.')
    local key_exists = #s:select({cast_lookup_key(1)}) ~= 0

    if not key_exists then
        print(prefix..'No, {1} does not exist. Let others go.')
        fiber.sleep(0.25) -- Enough for WAL write of insert {1}.

        print(prefix..'Insert my unique value to abort on conflict.')
        s:insert({value})
    end

    box.commit()
end

print('[0] Create [1].')
f1 = fiber.new(conflicting_fiber, unsigned, '[1] ', 11)
f1:set_joinable(true)

print('[0] Create [2].')
f2 = fiber.new(conflicting_fiber, double, '[2] ', 22)
f2:set_joinable(true)

print('[0] Let [1] and [2] go.')
fiber.yield()

-- This only finds one point hole (one with double or unsigned key), so it only
-- conflicts one of conflicting fibers (must conflict both though).
print('[0] Inserting {1}...')
s:insert({1})

print('[0] Done, now [1] and [2] must be conflicting. The new space contents:')
print(require('yaml').encode(s:select(nil, {limit = 10})))

ok, result = f1:join() -- [0] must abort on commit.
print('[1]', ok, result)

ok, result = f2:join() -- [1] must abort on commit too, but does not.
print('[2]', ok, result)

os.exit()
```

**Actual behavior**

Only one of transactions is conflicted:

```
[0] Create [1].
[0] Create [2].
[0] Let [1] and [2] go.
[1] Check if {1} exists.
[1] No, {1} does not exist. Let others go.
[2] Check if {1} exists.
[2] No, {1} does not exist. Let others go.
[0] Inserting {1}...
[0] Done, now [1] and [2] must be conflicting. The new space contents:
---
- [1]
...

[2] Insert my unique value to abort on conflict.
[1] Insert my unique value to abort on conflict.
[1]	false	Transaction has been aborted by conflict
[2]	true	nil
```

**Expected behavior**

Both transactions are conflicted.

### LINKED ISSUE #11292: Memtx MVCC does not respect collation-based and MsgPack equivalence classes
This code assumes that equivalence classes of keys are defined by the MsgPack encoding:
https://github.com/tarantool/tarantool/blob/23d4771a0d27eb0b9ac30dda994ab20ccec2e3f0/src/box/memtx_tx.c#L362-L372

However, this is not true for collation-based comparisons, and this is also not true for suboptimal MsgPack encodings (#9965).

**Steps to reproduce**
```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local log = require('log')
local txn_proxy = require('test.box.lua.txn_proxy')

box.cfg{memtx_use_mvcc_engine = true}

box.schema.space.create('s'):create_index('p')
box.schema.space.create('c'):create_index('p', {parts = {{1, 'str', collation = 'unicode_ci'}}})

local tx1 = txn_proxy:new()
local tx2 = txn_proxy:new()
local tx3 = txn_proxy:new()

tx1:begin()
tx2:begin()
tx3:begin()

log.info(tx1("box.space.c:get{'ЁлКа'}"))
log.info(tx1("box.space.s:insert{0}"))
log.info(tx2("box.space.c:get{'ЁЛКа'}"))
log.info(tx1("box.space.s:insert{1}"))
log.info(tx3("box.space.c:insert{'ёлка'}"))
log.info(tx3:commit())
log.info(tx1:commit())
log.info(tx2:commit())

os.exit()
```

**Actual behavior**
Only one of `tx1` and `tx2` gets conflicted.

**Expected behavior**
Both `tx1` and `tx2` get conflicted.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
This patchset fixes the incorrect assumption that point hole equivalence classes are defined by
their keys' binary (MsgPack) representation.

Closes #10159
Closes #11292

### CODE REVIEW

File: src/box/memtx_tx.c [hunk 1]
```diff
@@ -1859,11 +1872,7 @@ memtx_tx_handle_point_hole_write(struct space *space, struct memtx_story *story,
 			rlist_entry(item->ring.next,
 				    struct point_hole_item, ring);
 		has_more_items = next_item != item;
-
-		rlist_del(&item->ring);
-		rlist_del(&item->in_point_holes_list);
-		memtx_tx_mempool_free(item->txn, pool, item);
-
```
Comment (mkostoevr) [inline src/box/memtx_tx.c:1858]: Does this mean we had an index leak before this commit (no `index_unref` happened)? Can it be detected by a test?

**Review by mkostoevr — APPROVED** [review]
Nice to see the MVCC subsystem getting cleaner.

**Review by drewdzzz — APPROVED** [review]
Thanks for the patch!
We've fixed this old minor problem finally 😄 
Also, it's nice to see that MVCC code becomes a little more tidy.

**Review by xuniq — APPROVED** [review]

**Comment by sergepetrenko** [comment]
@CuriousGeorgiy, please, prepare the backports to all the relevant branches.
