### PR TITLE
config: add `lua.memory` option

### LINKED ISSUE #8881: New Lua memory limit option after GC64 enabled
Since enabling of GC64 Lua memory can go very high, leading to unexpected OOM across the whole server, instead of just pure OutOfMemory exception inside single instance. So, we need to implement explisit option to cap the memory with ability to change it.

Proposal: new option in section lua:
```yaml
lua:
    memory: 2147483648
```

Default value should be set to 2Gb (2147483648)

Like memtx.memory it could not be lowered, but it whould be good to have an ability to raise it dynamically.

### PR DESCRIPTION
**Pull request by georgiy-belyanin**
Sometimes we need to limit Lua maximum available memory. Add the config property `lua.memory` to specify the maximum byte amount used for lua allocations.

The limit is implemented with a custom allocation function. It's passed into a Lua state during instantiation. The function itself counts memory used by LuaJIT and prevents allocating more than specified in the config file.

If new memory limit is applied at runtime Tarantool waits for instance reload before applying a new option. 

Closes #8881

### CODE REVIEW

**Review by Buristan — CHANGES_REQUESTED** [review]
Hi, Georgiy!
Thanks for the patch!
Please, consider my comments below.

> Sometimes we need to limit lua maximum available memory. Add config

Typo: s/lua/Lua/
Typo: s/config/the config/

> property lua.memory to specify maximum byte amount used for lua

Typo: s/maximum/the maximum/
Typo: s/lua/Lua/

> into a lua state during instantiation. The function itself counts used RAM

Typo: s/lua/Lua/

Not RAM (since we don't count all memory), more likely "memory used by LuaJIT VM".

Width of the commit message line is more than 72 symbols ([see this section](https://github.com/tarantool/tarantool/wiki/Code-review-procedure#commit-message)).

Also, I am against such approach, see my comments below.

> and prevent allocating allocate more space than specified in the config

Typo: s/prevent/prevents/

Typo: s/allocate//

> Closes #10164

Typo: s/#10164/#8881/

File: src/lua/alloc.h [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+#pragma once
+
+#include <stddef.h>
+
+#if defined(__cplusplus)
+extern "C" {
+#endif /* defined(__cplusplus) */
+
+/**
+ * Set maximum available memory for the lua allocator.
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.h:40]: Applied

File: test/box-luatest/gh_7389_memtx_memory_test.lua [hunk 2]
```diff
@@ -1,14 +1,14 @@
...
-local g = t.group('memtx_memory setting test')
-
-g.before_all(function(g)
-    g.server = server:new{
-        alias = 'default',
-        box_cfg = {memtx_memory = 0}
-    }
-    g.server:start()
-end)
+ local t = require('luatest')
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply test/box-luatest/gh_7389_memtx_memory_test.lua]: You're right. Fixed

File: src/main.cc [hunk 3]
```diff
@@ -1018,6 +1024,7 @@ main(int argc, char **argv)
 	/*
 	 * Pass either a configuration file or a script file to
 	 * configure Lua loaders paths.
+
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/main.cc]: Done.

File: src/lua/alloc.h [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+ */
+int
+lua_alloc_set_memory(size_t memory);
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.h]: Changed, moved the functions into `lua/utils.h`

File: src/lua/alloc.cc [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+		      "allocate %zu bytes with a limit of %zu bytes", nsize,
+		      lua_memory);
+		return NULL;
+	}
+
+	if (nsize == 0) {
+		free(ptr);
+		return NULL;
+	} else {
+		void *result = xrealloc(ptr, nsize);
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.cc]: Changed everything to the described approach.

File: test/config-luatest/config_test.lua [hunk 6]
```diff
@@ -236,6 +236,32 @@ g.test_config_general = function()
...
+    local config_file = treegen.write_script(dir, 'config.yaml', config)
+    local opts = {
+        config_file = config_file,
+        alias = 'instance-001',
+        chdir = dir,
+    }
+    g.server = server:new(opts)
+    g.server:start()
+    g.server:exec(function()
+        t.assert_equals(box.cfg.lua_memory, 1000000000)
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply test/config-luatest/config_test.lua]: Done.

File: src/box/lua/cfg.cc [hunk 7]
```diff
@@ -298,6 +299,17 @@ lbox_cfg_set_worker_pool_threads(struct lua_State *L)
 	return 0;
 }
 
+static int
+lbox_cfg_set_lua_memory(struct lua_State *L)
+{
+	try {
+		lua_alloc_set_memory(cfg_geti("lua_memory"));
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/box/lua/cfg.cc]: Done.

File: src/lua/alloc.cc [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+#include "lib/core/diag.h"
+#include "lib/core/exception.h"
+#include "lib/core/say.h"
+
+#include <stdlib.h>
+
+#define LUA_DEFAULT_MEMORY (2ll * 1024 * 1024 * 1024)
+#define LUA_MIN_MEMORY (256ll * 1024 * 1024)
+
+static size_t lua_memory = LUA_DEFAULT_MEMORY;
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.cc]: I think it's a lot clearer. Applied.

File: src/lua/alloc.cc [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+}
+
+void*
+lua_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
+{
+	(void)ud;
+
+	lua_allocated_memory += nsize - osize;
+	if (lua_allocated_memory > lua_memory) {
+		panic("lua allocator reached memory limit when trying to "
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.cc]: Seems like now everything is ok.

File: src/lua/alloc.cc [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+		return NULL;
+	}
+
+	if (nsize == 0) {
+		free(ptr);
+		return NULL;
+	} else {
+		void *result = xrealloc(ptr, nsize);
+		if (result == NULL) {
+			panic("lua allocator ran out of memory when trying to allocate "
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.cc]: Changed the implementation. It's no longer relatable.

File: test/box-luatest/lua_memory.lua [hunk 11]
```diff
@@ -0,0 +1,30 @@
...
+
+        -- Changing available RAM for lua to 256 MB is ok.
+        box.cfg({lua_memory = 256 * 1024 * 1024})
+        t.assert_equals(box.cfg.lua_memory, 256 * 1024 * 1024)
+
+        -- We shouldn't be able to allocate less than 256MB.
+        t.assert_error_msg_equals(err, box.cfg,
+                                  {lua_memory = 200 * 1024 * 1024})
+    end)
+end
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory.lua]: Added corresponding test.

File: src/lua/init.c [hunk 12]
```diff
@@ -724,7 +726,7 @@ void
 tarantool_lua_init(const char *tarantool_bin, const char *script, int argc,
 		   char **argv)
 {
-	lua_State *L = luaL_newstate();
+	lua_State *L = lua_newstate(lua_alloc, NULL);
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/init.c]: Now `tarantool_lua_init()` uses only `luaL_newstate()` and substitutes allocator using `lua_setallocf`

File: src/lua/init.c [hunk 13]
```diff
@@ -49,6 +49,8 @@
 #include "coio.h"
 #include "core/backtrace.h"
 #include "core/tt_static.h"
+#include "cfg.h"
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/init.c]: You're right. It's redundant.

File: test/box-luatest/lua_memory.lua [hunk 14]
```diff
@@ -0,0 +1,30 @@
...
+    g.server:start()
+end)
+
+g.after_all(function(g)
+    g.server:drop()
+end)
+
+g.test_lua_memory = function(g)
+    g.server:exec(function()
+        local err = "cannot limit lua memory to less than 256MB: No such "..
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory.lua]: Now single quotes should be used everywhere in the added tests.

File: test/box-luatest/lua_memory.lua [hunk 15]
```diff
@@ -0,0 +1,30 @@
...
+                    "file or directory"
+
+        -- Changing available RAM for lua to 256 MB is ok.
+        box.cfg({lua_memory = 256 * 1024 * 1024})
+        t.assert_equals(box.cfg.lua_memory, 256 * 1024 * 1024)
+
+        -- We shouldn't be able to allocate less than 256MB.
+        t.assert_error_msg_equals(err, box.cfg,
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory.lua]: Applied this approach.

File: test/box-luatest/lua_memory_test.lua [hunk 16]
```diff
@@ -0,0 +1,42 @@
...
+    g.server:start()
+end)
+
+g.after_all(function(g)
+    g.server:drop()
+end)
+
+g.test_lua_memory_setting = function(g)
+    g.server:exec(function()
+        local MB = 1024 * 1024
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:22]: It is already declared as the upvalue above. This line can be dropped.

File: test/box-luatest/lua_memory_test.lua [hunk 17]
```diff
@@ -0,0 +1,42 @@
...
+        local LUA_MIN_MEMORY = 256 * MB
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:23]: Ditto.

File: test/config-luatest/memory_test.lua [hunk 18]
```diff
@@ -0,0 +1,29 @@
+local yaml = require('yaml')
+local t = require('luatest')
+local treegen = require('test.treegen')
+local helpers = require('test.config-luatest.helpers')
+local justrun = require('test.justrun')
+
+local g = helpers.group()
+
+g.test_relative_config_path = function(g)
+    local dir = treegen.prepare_directory(g, {}, {})
```
Comment (Buristan) [inline test/config-luatest/memory_test.lua:10]: I suppose that running an additional instance for this test is overkill. We might just use `t.assert_error_msg_equals()` like you do for `test_lua_memory_setting()`.

Also, it may be done as a subtest in the <lua_memory_test.lua>, but I don't insist on it.

File: test/box-luatest/lua_memory_test.lua [hunk 19]
```diff
@@ -0,0 +1,42 @@
...
+        t.assert_equals(box.cfg.lua_memory, LUA_MIN_MEMORY + 1)
+
+        local err_decreasing = 'cannot decrease lua allocator available '..
+            'memory at runtime'
+        -- Decreasing shouldn't be allowed.
+        t.assert_error_msg_equals(err_decreasing, box.cfg,
+            {lua_memory = LUA_MIN_MEMORY})
+
+        local err_min = 'cannot limit lua memory with values less than 256MB'
+        -- Setting the limit to values less than should be disabled.
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:38]: Nit: Comment length is more than 66 symbols.

**Review by Buristan — CHANGES_REQUESTED** [review]
Hi, Georgiy!
Thanks for the fixes!
Please don't forget to update the commit message according to the new changes and [the following comment](https://github.com/tarantool/tarantool/pull/10223#pullrequestreview-2182011371).

Also, please consider the bunch of nits and minor comments below.

File: test/box-luatest/lua_memory_test.lua (hunk 16 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:22]: It won't work because `g.server:exec` seems not to be able to capture the outer variable.

File: src/lua/utils.c [hunk 20]
```diff
@@ -59,6 +68,57 @@ uint32_t CTID_UUID;
...
+
+int
+luaT_setalloclimit(size_t memory)
+{
+	if (memory < LUA_MEMORY_LIMIT_MIN) {
+		diag_set(LuajitError, "cannot limit lua memory with values "
+			 "less than 256MB");
+		return -1;
+	}
+	if (memory < alloc.limit) {
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c:113]: It used to be the first approach implemented. But the issue says we shouldn't allow decreasing the memory limit. The same way as the `memtx_memory` config option works.

I'll apply the suggestion. Please, tell me if there is a reason for `memtx_memory` to be implemented in a different way

File: test/box-luatest/lua_memory_test.lua (hunk 17 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:23]: Same as above. Probably I do something wrong but capturing the global variable:
```
test/box-luatest/lua_memory_test.lua:21: bad argument #2 to exec (excess upvalues: LUA_MIN_MEMORY) 
```

File: src/main.cc [hunk 21]
```diff
@@ -444,6 +444,8 @@ load_cfg(void)
 		}
 	}
 
+	box_set_lua_memory();
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/main.cc:447]: `src/lua` subsystem doesn't use `src/box/` at all. It looks like breaking architectural dependency directions.
I'll bring it to `box_lua_init()`. Is it ok?

File: test/box-luatest/lua_memory_test.lua (hunk 19 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:38]: Made it shorter.

File: src/lua/utils.h [hunk 22]
```diff
@@ -81,6 +81,19 @@ extern uint32_t CTID_DATETIME;
 /** Type ID of struct interval. */
 extern uint32_t CTID_INTERVAL;
 
+/**
+ * Creates a new Lua state with a custom allocator function.
+ * Guarantees the state is not null. May panic if something has failed.
+ */
+struct lua_State*
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.h:88]: Fixed.

File: src/box/box.cc [hunk 23]
```diff
@@ -1972,6 +1972,17 @@ box_check_config(void)
 	box_check_memtx_sort_threads();
 }
 
+void
+box_set_lua_memory(void)
+{
+	int lua_memory = cfg_geti("lua_memory");
+	if (!lua_memory)
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/box/box.cc:1979]: The situation is impossible. Removed the check.

File: src/lua/utils.c [hunk 24]
```diff
@@ -59,6 +68,57 @@ uint32_t CTID_UUID;
...
+struct lua_State*
+luaT_newstate(void)
+{
+	struct lua_State *L = luaL_newstate();
+	if (L == NULL) {
+		panic("failed to initialize Lua");
+	}
+
+	void *orig_ud;
+	alloc.orig_alloc = lua_getallocf(L, &orig_ud);
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c:98]: Fixed it by initialising `alloc.allocated` with an allocated memory amount when creating a new state.

File: src/lua/utils.c [hunk 25]
```diff
@@ -59,6 +68,57 @@ uint32_t CTID_UUID;
...
+		diag_set(OutOfMemory, nsize, "luaT_alloc", "lua objects");
+		diag_log();
+		return NULL;
+	}
+
+	void *result = alloc.orig_alloc(ud, ptr, osize, nsize);
+	return result;
+}
+
+struct lua_State*
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c:89]: Fixed.

File: src/lua/utils.c [hunk 26]
```diff
@@ -59,6 +68,57 @@ uint32_t CTID_UUID;
 uint32_t CTID_DATETIME = 0;
 uint32_t CTID_INTERVAL = 0;
 
+/**
+ * Lua custom memory allocation function. It extends the original one with
+ * a memory counter and a limit check.
+ */
+static void*
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c:75]: Fixed.

[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c:75]: Fixed.

File: src/lua/utils.c (hunk 25 above)
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c:89]: Fixed.

File: src/lua/utils.h [hunk 27]
```diff
@@ -81,6 +81,19 @@ extern uint32_t CTID_DATETIME;
 /** Type ID of struct interval. */
 extern uint32_t CTID_INTERVAL;
 
+/**
+ * Creates a new Lua state with a custom allocator function.
+ * Guarantees the state is not null. May panic if something has failed.
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.h:86]: Applied.

File: src/lua/utils.h (hunk 22 above)
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.h:88]: Fixed.

File: test/box-luatest/lua_memory_test.lua (hunk 19 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:38]: Fixed.

File: test/config-luatest/memory_test.lua (hunk 18 above)
Comment (georgiy-belyanin) [reply test/config-luatest/memory_test.lua:10]: When error occurs the Tarantool panics, as I found. `t.assert_error_msg_equals()` aren't able to handle it.

Probably it shouldn't work like this. I couldn't yet find a way to throw an error in allocator (either long jumps nor exceptions nor returning NULL from it works properly).

Comment (Buristan) [reply test/config-luatest/memory_test.lua]: > I couldn't yet find a way to throw an error in allocator

I suppose, in the case of a limit violation, the allocator function should just return `NULL`. In that case, the LuaJIT VM will raise the OOM error, as expected.

File: src/lua/utils.c [hunk 28]
```diff
@@ -59,6 +69,64 @@ uint32_t CTID_UUID;
...
+	struct lua_State *L = luaL_newstate();
+	if (L == NULL) {
+		panic("failed to initialize Lua");
+	}
+
+	/*
+	 * lua_gc(L, LUA_GC_COUNT) returns the allocated memory in KBs
+	 * lua_gc(L, LUA_GC_COUNTB) returns the reminder
+	 */
+	alloc.allocated = lua_gc(L, LUA_GCCOUNT, 0) * 1024ll +
```
Comment (Buristan) [inline src/lua/utils.c:102]: Why do we need `ll` suffix here?

File: test/box-luatest/lua_memory_test.lua [hunk 29]
```diff
@@ -0,0 +1,81 @@
...
+        local err_min = 'cannot limit lua memory with values less than 256MB'
+        -- Setting the limit less than 256MB is prohibited.
+        t.assert_error_msg_equals(err_min, box.cfg,
+            {lua_memory = LUA_MIN_MEMORY - 1})
+
+        box.cfg{lua_memory = LUA_EXTENDED_MEMORY}
+
+        local used = collectgarbage('count') * 1024
+        local free = LUA_EXTENDED_MEMORY - used
+        local a = string.rep('a', free / 3)
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:47]: It is better to use `_` for unused variable in Lua. See [this CI failure](https://github.com/tarantool/tarantool/actions/runs/9994276601/job/27623665785?pr=10223#step:6:999)

File: test/box-luatest/lua_memory_test.lua [hunk 30]
```diff
@@ -0,0 +1,81 @@
...
+
+        --local err_decreasing = 'cannot decrease lua allocator available '..
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:49]: Looks like the remaining part of debugging.

File: src/lua/utils.h [hunk 31]
```diff
@@ -81,6 +81,19 @@ extern uint32_t CTID_DATETIME;
 /** Type ID of struct interval. */
 extern uint32_t CTID_INTERVAL;
 
+/**
+ * Creates a new Lua state with a custom allocator function.
+ * Guarantees the state is not NULL. It panics if lua_State can't be allocated.
```
Comment (Buristan) [inline src/lua/utils.h:86]: Nit: Comment line length is more than 66 symbols.

**Review by Buristan — COMMENTED** [review]
Hi, Georgiy!
Thanks for the fixes!
Please, consider some minor nits below.

File: src/lua/utils.c [hunk 32]
```diff
@@ -59,6 +69,64 @@ uint32_t CTID_UUID;
...
+struct lua_State *
+luaT_newstate(void)
+{
+	struct lua_State *L = luaL_newstate();
+	if (L == NULL) {
+		panic("failed to initialize Lua");
+	}
+
+	/*
+	 * lua_gc(L, LUA_GC_COUNT) returns the allocated memory in KBs
```
Comment (Buristan) [inline src/lua/utils.c:99]: Missed dot at the end of the sentence.

File: src/lua/utils.c [hunk 33]
```diff
@@ -59,6 +69,64 @@ uint32_t CTID_UUID;
...
+	 * lua_gc(L, LUA_GC_COUNTB) returns the reminder
```
Comment (Buristan) [inline src/lua/utils.c:100]: Missed dot at the end of the sentence.

File: src/lua/utils.c (hunk 28 above)
Comment (georgiy-belyanin) [reply src/lua/utils.c:102]: `lua_gc` returns an `int` number. Without `ll` an implicit conversion into a `long long` isn't performed. An overflow is possible.

File: test/box-luatest/lua_memory_test.lua (hunk 29 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:47]: Applied.

File: src/lua/utils.h (hunk 31 above)
Comment (georgiy-belyanin) [reply src/lua/utils.h]: Oh, it's related even to the docs. Fixed.

File: src/lua/utils.c (hunk 32 above)
Comment (georgiy-belyanin) [reply src/lua/utils.c]: Fixed.

File: src/lua/utils.c (hunk 33 above)
Comment (georgiy-belyanin) [reply src/lua/utils.c]: Fixed.

File: test/config-luatest/memory_test.lua (hunk 18 above)
Comment (georgiy-belyanin) [reply test/config-luatest/memory_test.lua]: It's implemented like this right now. I wasn't able to capture the error with `t.assert_error_msg_equals()`

File: changelogs/unreleased/gh-9849-lua-memory-limit-config.md [hunk 34]
```diff
@@ -0,0 +1,3 @@
+## feature/config
+
+* Add `lua.memory` parameter for setting maximum available RAM for lua scripts.
```
Comment (andreyaksenov) [inline changelogs/unreleased/gh-9849-lua-memory-limit-config.md:3]:
```suggestion
* Added the `lua.memory` parameter to set up the maximum available RAM for Lua scripts.
```

**Review by andreyaksenov — APPROVED** [review]

File: changelogs/unreleased/gh-9849-lua-memory-limit-config.md (hunk 34 above)
Comment (georgiy-belyanin) [reply changelogs/unreleased/gh-9849-lua-memory-limit-config.md]: Applied. Thank you.

File: src/main.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/main.cc:447]: Raw thought: a `box.cfg` option was not requested. And the given option has no relation to the database at all. We can expose a Lua function to set the limit from some module in `src/lua`.

`tarantool` module is informational, not a good option. Create some `tarantool.vm` module? Don't know.

Any ideas?

[the remark this answers is not in the document]
Comment (Totktonada) [reply src/main.cc:447]: There is an idea to place the Lua API to the `misc` module.

```yaml
# tarantool> misc
---
- getmetrics: 'function: builtin#203'
  sysprof:
    stop: 'function: builtin#205'
    report: 'function: builtin#206'
    start: 'function: builtin#204'
  memprof:
    start: 'function: builtin#207'
    stop: 'function: builtin#208'
...
```

It looks as a good place. However, the implementation of this module is in the luajit repository (our fork). If we're going to expose a function from it, it seems that the code should reside in the luajit fork too[^1].

I like the idea to have this machinery in the luajit codebase, because luajit's memory limit seems closer to luajit itself rather than tarantool. @Buristan, what do you think?

[^1]: Technically we can add a function into the module table from tarantool, but I don't like that the implementatoin of the module would spread across different files and even repositories in this case.

File: src/lua/utils.c [hunk 35]
```diff
@@ -46,6 +46,16 @@
 #include "trivia/util.h"
 #include "vclock/vclock.h"
 
+#define LUA_MEMORY_LIMIT_MIN (256ll * 1024 * 1024)
+#define LUA_MEMORY_LIMIT_DEFAULT LUA_MEMORY_LIMIT_MIN
```
Comment (Buristan) [inline src/lua/utils.c:50]: It should be 2Gb instead.

File: src/lua/utils.c [hunk 36]
```diff
@@ -59,6 +69,64 @@ uint32_t CTID_UUID;
...
+/**
+ * Lua custom memory allocation function. It extends the original one with
+ * a memory counter and a limit check.
+ */
+static void *
+luaT_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
+{
+	alloc.allocated += nsize - osize;
+	if (alloc.allocated > alloc.limit) {
+		diag_set(OutOfMemory, nsize, "luaT_alloc", "lua objects");
```
Comment (Buristan) [inline src/lua/utils.c:81]: Typo: s/lua/Lua/

File: src/main.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (Buristan) [reply src/main.cc:447]: We discussed this with @Totktonada offline and came to the following conclusion:

Decalring this custom allocator function inside the LuaJIT fork is hardly maintainable (changes in the Tarantool allocator require changes in the LuaJIT fork that look inconsistent) and too specific to be a part of the API, so it should be done as an __internal__ module inside Tarantool.

So we should provide an internal module (say <src/lua/alloc.c>) that provides two Lua C functions -- to set the alloc function and restore the previous one. Also, it provides in the Lua namespace function `internal.alloc.setlimit()` which allows to easily set the limit of the Lua memory.

**Review by Buristan — CHANGES_REQUESTED** [review]

File: test/config-luatest/memory_test.lua (hunk 18 above)
Comment (Buristan) [reply test/config-luatest/memory_test.lua]: This is due to [not restored](https://github.com/tarantool/tarantool/pull/10223#discussion_r1704975669) `allocated` value in the case of the OOM.
After fixing the behaviour we are able to see last error via [`box.error.last()`](https://www.tarantool.io/ru/doc/2.11/reference/reference_lua/box_error/last/).

```sh
src/tarantool -e '
  local function bigalloc()
    -- On your branch before fixing the default value.
    ("x"):rep(1024 * 1024 * 256)
  end
  local r, e = pcall(bigalloc)
  print("err:",  box.error.last())
'
OutOfMemory: Failed to allocate 268435456 bytes in luaT_alloc for lua objects
err:    Failed to allocate 268435456 bytes in luaT_alloc for lua objects

```

File: src/lua/utils.c (hunk 36 above)
Comment (georgiy-belyanin) [reply src/lua/utils.c]: Fixed.

File: src/lua/utils.c [hunk 37]
```diff
@@ -59,6 +69,64 @@ uint32_t CTID_UUID;
...
+	void *orig_ud;
+	alloc.orig_alloc = lua_getallocf(L, &orig_ud);
+	assert(alloc.orig_alloc != NULL);
+	lua_setallocf(L, luaT_alloc, orig_ud);
+
+	return L;
+}
+
+int
+luaT_setalloclimit(size_t memory)
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c]: Applied. It'll be more consistent.

File: src/lua/utils.c [hunk 38]
```diff
@@ -59,6 +69,64 @@ uint32_t CTID_UUID;
...
+	struct lua_State *L = luaL_newstate();
+	if (L == NULL) {
+		panic("failed to initialize Lua");
+	}
+
+	/*
+	 * lua_gc(L, LUA_GC_COUNT) returns the allocated memory in KBs.
+	 * lua_gc(L, LUA_GC_COUNTB) returns the reminder.
+	 */
+	alloc.allocated = lua_gc(L, LUA_GCCOUNT, 0) * 1024ll +
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c]: Done! Thank you.

File: src/lua/utils.c (hunk 35 above)
Comment (georgiy-belyanin) [reply src/lua/utils.c]: Now it's so. Thank you.

File: src/lua/utils.c [hunk 39]
```diff
@@ -59,6 +69,64 @@ uint32_t CTID_UUID;
...
+ * a memory counter and a limit check.
+ */
+static void *
+luaT_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
+{
+	alloc.allocated += nsize - osize;
+	if (alloc.allocated > alloc.limit) {
+		diag_set(OutOfMemory, nsize, "luaT_alloc", "lua objects");
+		diag_log();
+		return NULL;
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c]: Yep. Quite a stupid mistake. Thank you. Fixed

File: test/config-luatest/memory_test.lua (hunk 18 above)
Comment (georgiy-belyanin) [reply test/config-luatest/memory_test.lua]: Oh, you're right. Fixed it. Thanks

File: src/lua/utils.c [hunk 40]
```diff
@@ -46,6 +46,16 @@
 #include "trivia/util.h"
 #include "vclock/vclock.h"
 
+#define LUA_MEMORY_LIMIT_MIN (256ll * 1024 * 1024)
+#define LUA_MEMORY_LIMIT_DEFAULT LUA_MEMORY_LIMIT_MIN
+
+static struct {
+	lua_Alloc orig_alloc;
+
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/utils.c]: Now the variables are moved. Think the comment is no longer relatable.

File: src/main.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/main.cc:447]: Applied the suggested approach.

File: src/lua/alloc.c [hunk 41]
```diff
@@ -0,0 +1,135 @@
...
+void
+tarantool_lua_alloc_init(struct lua_State *L)
+{
+	static const struct luaL_Reg alloc_methods[] = {
+		{"setmemory", lbox_alloc_setmemory},
+		{NULL, NULL}
+	};
+
+	luaT_newmodule(L, "internal.alloc", alloc_methods);
+	lua_setfield(L, -2, "internal.alloc");
```
[the remark this answers is not in the document]
Comment (Buristan) [reply src/lua/alloc.c:133]: Side note: you may debug the Lua C code with a `lj-stack` command which is a part of our [`luajit-gdb.py gdb extension for LuaJIT`](https://github.com/tarantool/luajit/blob/tarantool/master/src/luajit-gdb.py).

File: src/lua/alloc.h [hunk 42]
```diff
@@ -0,0 +1,60 @@
...
+ * SUCH DAMAGE.
+ */
+
+#pragma once
+
+#if defined(__cplusplus)
+extern "C" {
+#endif /* defined(__cplusplus) */
+
+#include <stdint.h>
```
Comment (Buristan) [inline src/lua/alloc.h:38]: This include looks excess.

File: src/lua/alloc.h [hunk 43]
```diff
@@ -0,0 +1,60 @@
...
+#include <lua.h>
+
+/**
+ * Limits the maximum available Lua memory.
+ */
+int
+luaT_setallocmemory(size_t memory);
+
+/**
+ * Initializes custom allocator for the state.
```
Comment (Buristan) [inline src/lua/alloc.h:49]: Minor: "for the state" isn't very clear. "for the LuaJIT VM" is more logical to me.

File: src/main.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (Buristan) [reply src/main.cc:447]: In that case, why do we need to call `box_set_lua_memory()` here (I thought that it should be called in some other place, shouldn't it)?

File: test/app-luatest/alloc_test.lua [hunk 44]
```diff
@@ -0,0 +1,32 @@
...
+    errmsg = 'Invalid memory amount: the value must be >= 0'
+    test(-1024)
+
+    errmsg = 'Cannot limit the Lua memory with values less than 256MB'
+    test(1024)
+    test(1024 * 1024)
+    test(256 * 1024 * 1024 - 1)
+end
+
+g.test_decode = function()
```
Comment (Buristan) [inline test/app-luatest/alloc_test.lua:24]: Why is it named `decode`?

File: test/box-luatest/lua_memory_test.lua [hunk 45]
```diff
@@ -0,0 +1,68 @@
+local server = require('luatest.server')
+local t = require('luatest')
+local g = t.group('lua_memory setting test')
+--local treegen = require('test.treegen')
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:4]: Looks like a part of the previous version.

File: test/box-luatest/lua_memory_test.lua [hunk 46]
```diff
@@ -0,0 +1,68 @@
...
+
+local MB = 1024 * 1024
+local LUA_MIN_MEMORY = 256 * MB
+
+g.before_each(function()
+    g.server = server:new{
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:10]: Please use `()` for function or methods calls. Here and below.

File: test/box-luatest/lua_memory_test.lua [hunk 47]
```diff
@@ -0,0 +1,68 @@
...
+        local LUA_MIN_MEMORY = 256 * MB
+        local LUA_EXTENDED_MEMORY = 600 * MB
+
+        t.assert_equals(box.cfg.lua_memory, LUA_MIN_MEMORY)
+
+        -- Increasing the limit should be ok.
+        box.cfg{lua_memory = LUA_MIN_MEMORY + 1}
+        t.assert_equals(box.cfg.lua_memory, LUA_MIN_MEMORY + 1)
+
+        local err_min = 'Cannot limit the Lua memory with values less than '..
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:34]: It is better to surround operators (`..` in that case) with spaces [1].
Here and below.
[1]: https://www.tarantool.io/en/doc/latest/contributing/lua_style_guide/

File: test/box-luatest/lua_memory_test.lua [hunk 48]
```diff
@@ -0,0 +1,68 @@
...
+                        '256MB'
+        -- Setting the limit less than 256MB is prohibited.
+        t.assert_error_msg_equals(err_min, box.cfg,
+            {lua_memory = LUA_MIN_MEMORY - 1})
+
+        box.cfg{lua_memory = LUA_EXTENDED_MEMORY}
+
+        local used = collectgarbage('count') * 1024
+        local free = LUA_EXTENDED_MEMORY - used
+        local _ = string.rep('a', free / 3)
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:44]: Please add a comment that this string should be successfully allocated.

File: test/box-luatest/lua_memory_test.lua [hunk 49]
```diff
@@ -0,0 +1,68 @@
...
+        local memory = 256 * 1024 * 1024
+
+        local function overflow()
+            local free = memory - (collectgarbage('count')) * 1024
+            local _ = string.rep('a', free / 2)
+        end
+
+        local err_min = 'not enough memory'
+        t.assert_error_msg_equals(err_min, overflow)
+    end)
```
Comment (Buristan) [inline test/box-luatest/lua_memory_test.lua:67]: May be it is worth to check the `box.error.last()` too.

File: src/lua/alloc.c [hunk 50]
```diff
@@ -0,0 +1,135 @@
...
+luaT_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
+{
+	size_t new_allocated = allocated + nsize - osize;
+	if (new_allocated > memory) {
+		diag_set(OutOfMemory, nsize, "luaT_alloc", "Lua objects");
+		return NULL;
+	}
+	allocated = new_allocated;
+
+	return orig_alloc(ud, ptr, osize, nsize);
```
Comment (Buristan) [inline src/lua/alloc.c:65]: I suppose that `orig_alloc` may return `NULL` too. So, we should check the returned pointer and update allocated only if it is not `NULL`.

**Review by Buristan — CHANGES_REQUESTED** [review]
Hi, Georgiy!
Thanks for the fixes!
Please consider my comments below.

> into a Lua state during instantiation. The function itself counts memory

Typo: s/memory/the memory/

File: src/lua/alloc.h (hunk 42 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.h:38]: It was supposed for including `size_t` type. Replaced with `stddef.h`

File: src/lua/alloc.c [hunk 51]
```diff
@@ -0,0 +1,135 @@
...
+tarantool_lua_alloc_init(struct lua_State *L)
+{
+	static const struct luaL_Reg alloc_methods[] = {
+		{"setmemory", lbox_alloc_setmemory},
+		{NULL, NULL}
+	};
+
+	luaT_newmodule(L, "internal.alloc", alloc_methods);
+	lua_setfield(L, -2, "internal.alloc");
+	lua_pop(L, 1);
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.c:134]: Yep, that was the thing I misunderstood when copying the code from the other place. Thanks. Fixed.

File: src/lua/alloc.c (hunk 41 above)
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.c:133]: Fixed. Thank you especially for the `lj-stack` debug solution.

File: src/lua/alloc.c [hunk 52]
```diff
@@ -0,0 +1,135 @@
...
+ * The maximum allowed LuaJIT memory limit.
+ */
+static size_t memory = LUA_MEMORY_DEFAULT;
+/**
+ * Currently allocated memory amount by LuaJIT.
+ */
+static size_t allocated;
+
+/**
+ * Lua custom memory allocation function. It extends the original one with
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.c:52]: Fixed.

File: src/lua/alloc.c [hunk 53]
```diff
@@ -0,0 +1,135 @@
...
+ */
+#include "lua/utils.h"
+
+#include <lauxlib.h> /* luaL_error */
+
+#define LUA_MEMORY_MIN (256ll * 1024 * 1024)
+#define LUA_MEMORY_DEFAULT (2ll * 1024 * 1024 * 1024)
+
+/**
+ * The default allocator function which is wrapped into a new one.
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.c:39]: Merged your and my approaches. Now it says `into a new one with the Lua memory limit checker`

File: src/lua/alloc.c [hunk 54]
```diff
@@ -0,0 +1,135 @@
...
+ * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+ * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
+ * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
+ * SUCH DAMAGE.
+ */
+#include "lua/utils.h"
+
+#include <lauxlib.h> /* luaL_error */
+
+#define LUA_MEMORY_MIN (256ll * 1024 * 1024)
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.c:35]: Applied.

File: src/lua/alloc.h (hunk 43 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.h:49]: Applied.

File: test/app-luatest/alloc_test.lua (hunk 44 above)
Comment (georgiy-belyanin) [reply test/app-luatest/alloc_test.lua:24]: Oh, forget to change the copy/pasted code. Thanks!

File: test/box-luatest/lua_memory_test.lua (hunk 45 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:4]: My bad. Thank you. Fixed!

File: test/box-luatest/lua_memory_test.lua (hunk 46 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:10]: Done.

File: test/box-luatest/lua_memory_test.lua (hunk 48 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:44]: The comment was added.

File: src/lua/alloc.c (hunk 50 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:65]: You're absolutely right, thank you for finding this point.

File: test/box-luatest/lua_memory_test.lua (hunk 49 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:67]: Done!

File: test/box-luatest/lua_memory_test.lua (hunk 47 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:34]: Done.

File: src/lua/alloc.c [hunk 55]
```diff
@@ -0,0 +1,135 @@
...
+	if (amount < 0) {
+		diag_set(IllegalParams, "Invalid memory amount: "
+			 "the value must be >= 0");
+		return luaT_error(L);
+	}
+
+	if (luaT_setallocmemory(amount) < 0)
+		return luaT_error(L);
+
+	lua_pushinteger(L, memory);
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.c:127]: There is a test `app-luatest/alloc_test` that tests the return value of the function.
Actually, I don't understand the first suggestion. You mean we should push the value returned by the `luaT_setallocmemory`? Seems like everything is working ok rn.

[the remark this answers is not in the document]
Comment (Buristan) [reply src/lua/alloc.c:127]: Oh, my bad!
This was counterintuitive for me. I expect that this function should return the __old__ value of the memory limit (like it is done in the `collectgarbage` API for GC settings).

@Totktonada, what do you think about returing of the old value instead?

File: test/box-luatest/lua_memory_test.lua (hunk 49 above)
Comment (Buristan) [reply test/box-luatest/lua_memory_test.lua:71]:
```diff
+        local err1 = 'not enough memory'
+        local err2 = 'Failed to allocate'
+        t.assert_error_msg_equals(err1, overflow)
+        t.assert_str_contains(tostring(box.error.last()), err2)
```

I suppose we can just drop local variables (`err1`, `err2`) here for better readability.

```lua
        t.assert_error_msg_equals('not enough memory', overflow)
        t.assert_str_contains(tostring(box.error.last()), 'Failed to allocate')
```
What do you think?

File: src/lua/alloc.c (hunk 50 above)
Comment (Buristan) [reply src/lua/alloc.c]: I'm not sure, that we should set the `diag` here. That may allow us to separate the error from our allocator and internal ones. @Totktonada, what do you think?

File: src/main.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (Buristan) [reply src/main.cc:447]: What I mean is that it is just an unexpected place for me (I suppose we should end managing with the `pid_file` first). OTOH, it should be done before `box_init_say()`, since it uses Lua memory.
I will ask @Totktonada for the final judgment here.

File: test/box-luatest/lua_memory_test.lua (hunk 48 above)
Comment (Buristan) [reply test/box-luatest/lua_memory_test.lua:46]: Nit: Do you mean `1/3`?

Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:46]: Actually, it allocates ~2/3 of the free memory. Last assignment allocates `free / 3 * 2` memory:
```
tarantool> _ = string.rep('1', 1000 * 1000 * 1000)
freed 6144
allocated 1073733632
allocated 1000000025
```
These log was got by adding printing allocations/frees with size >=4kb.

Some experiments made me think, that there is some kind of a cache for such large calls. The memory is allocated for `string.rep()` call result with the specified parameters and for the variable itself separately. It's easy to see because the later calls `any_other_var = string.rep('1', 1000 * 1000 * 1000)` won't cause any additional large allocations.

File: test/box-luatest/lua_memory_test.lua (hunk 49 above)
Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:69]: Yes, you're right. The strings are short enough. Done!

File: test/box-luatest/lua_memory_test.lua (hunk 48 above)
Comment (Buristan) [reply test/box-luatest/lua_memory_test.lua:46]: I suppose this is due to the growth of the string buffer. Let's drop the mention of the specific memory amount to avoid confusion.

Side note: Later calls don't cause allocations since LuaJIT uses string interning, so there is no additional string created.

Comment (georgiy-belyanin) [reply test/box-luatest/lua_memory_test.lua:45]: Dropped the mention of the strange `2/3` value. Thanks for the side note.

File: src/main.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/main.cc:447]: I remember a result of our past discussions as follows:

* We create an internal Lua module (`internal.alloc`) with the allocator and functions to enable/disable it and get/set the memory limit.
* Tarantool enables the allocator for the main Lua state early at startup (and the default 2 GiB limit is set).
* We create a configuration option and a configuration applier (`src/box/lua/config/applier/lua.lua` or kinda) that allows to configure the limit (it uses the `internal.alloc` API directly).

This way we don't need to add any `box.cfg` option and it looks meaningful -- this option is not related to box (the database). We have fiber slice limit configuration implemented this way.

BTW, I propose to handle decreasing of the limit in the following way. If the limit is decreased, a warning is issued and the limit remains unchanged (until restart). It is how non-dynamic `box.cfg` options are handled.

https://github.com/tarantool/tarantool/blob/d33b14793bea58520139172599621daaaf66b947/src/box/lua/config/applier/box_cfg.lua#L550-L558

The motivation here is that sometimes it is convenient to setup needed options first and restart instances then.

File: src/lua/alloc.c (hunk 55 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/lua/alloc.c:127]: Returning the new value seems a bit confusing to me too.

I would return nothing or an old value.

I also think that we need some function to get the currently set limit.

File: src/main.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/main.cc:447]: Thank you for the suggestion! Now I completely agree with you the option is not related to box at all. I am moving it to a new config applier.

File: src/lua/alloc.c (hunk 55 above)
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/lua/alloc.c:127]: Thanks, now I am returning the old value and provide `internal.alloc.getlimit` call.

File: src/box/lua/config/init.lua [hunk 56]
```diff
@@ -143,6 +143,7 @@ function methods._initialize(self)
         self:_register_source(require('internal.config.source.file').new())
     end
 
+    self:_register_applier(require('internal.config.applier.lua'))
```
Comment (Totktonada) [inline src/box/lua/config/init.lua:146]: It doesn't change things much, but I would add it to `first_phase_appliers` (see below) for consistency with all the other pre-box-cfg appliers.

File: src/box/lua/config/applier/lua.lua [hunk 57]
```diff
@@ -0,0 +1,32 @@
...
+        -- memory with values < 256MB or with an amount less than
+        -- currently allocated.
+        alloc.setmemory(memory)
+        log.verbose(('lua.apply: set memory limit to %d'):format(memory))
+
+        is_lua_memory_applied = true
+    else
+        local warning = 'lua.apply: non-dynamic option lua.memory ' ..
+                        'will not be set until the instance is restarted'
+        config._aboard:set({type = 'warn', message = warning})
```
Comment (Totktonada) [inline src/box/lua/config/applier/lua.lua:25]: Technically this code is called once on reconfiguration and at most twice on startup (and the first call can't issue the alert). However, I wouldn't bother much about a code on the upper level and just be ready to several calls per (re)configuration process. IOW, I would add a key for this alert, so several alerts with this message can't be issued by construction.

File: src/lua/alloc.c (hunk 50 above)
Comment (Totktonada) [reply src/lua/alloc.c]: @georgiy-belyanin Any updates here?

File: src/lua/alloc.c [hunk 58]
```diff
@@ -0,0 +1,171 @@
...
+	if (lua_gettop(L) < 1)
+		luaL_error(L, "Usage: alloc.setmemory(amount)");
+
+	long long amount = lua_tointeger(L, 1);
+
+	if (amount < 0) {
+		diag_set(IllegalParams, "Invalid memory amount: "
+			 "the value must be >= 0");
+		return luaT_error(L);
+	}
```
Comment (Totktonada) [inline src/lua/alloc.c:127]: Seems like we should use either string errors or `IllegalParams` in both cases.

File: src/lua/alloc.c [hunk 59]
```diff
@@ -0,0 +1,171 @@
...
+	lua_setallocf(L, luaT_alloc, orig_ud);
+}
+
+/**
+ * alloc.getmemory() -- get the allocator memory limit.
+ */
+static int
+lbox_alloc_getmemory(struct lua_State *L)
+{
+	lua_pushinteger(L, memory);
```
Comment (Totktonada) [inline src/lua/alloc.c:107]: Should we use `luaL_pushuint64` or something like it? The `memory` variable may go beyond 2^31-1.

File: src/lua/alloc.c [hunk 60]
```diff
@@ -0,0 +1,171 @@
...
+ * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+ * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
+ * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
+ * SUCH DAMAGE.
+ */
+#include "lua/utils.h"
+
+#include <lauxlib.h> /* luaL_error */
+
+#define LUA_MEMORY_DEFAULT (2LL * 1024 * 1024 * 1024)
```
Comment (Totktonada) [inline src/lua/alloc.c:35]: Should be 2ULL (we use `size_t` for these values below, not `ssize_t`).

File: src/lua/alloc.c [hunk 61]
```diff
@@ -0,0 +1,171 @@
...
+ * alloc.setmemory() -- set the allocator memory limit.
+ * Returns old memory limit.
+ */
+static int
+lbox_alloc_setmemory(struct lua_State *L)
+{
+	if (lua_gettop(L) < 1)
+		luaL_error(L, "Usage: alloc.setmemory(amount)");
+
+	long long amount = lua_tointeger(L, 1);
```
Comment (Totktonada) [inline src/lua/alloc.c:121]: Should it be `size_t` too (unsigned)? Does `lua_tointeger` handles values beyond 2^31-1 correctly?

File: src/lua/alloc.c [hunk 62]
```diff
@@ -0,0 +1,171 @@
+/*
+ * Copyright 2010-2024, Tarantool AUTHORS, please see AUTHORS file.
```
Comment (Totktonada) [inline src/lua/alloc.c:2]: Let's use `SPDX-License-Identifier` (grep for examples).

File: src/lua/init.c [hunk 63]
```diff
@@ -49,6 +49,7 @@
 #include "coio.h"
 #include "core/backtrace.h"
 #include "core/tt_static.h"
+#include "lua/alloc.h"
```
Comment (Totktonada) [inline src/lua/init.c:52]: Seems unused here.

Comment (Totktonada) [reply src/lua/init.c:52]: Ah, it is `lua/alloc.h`. Sorry.

File: src/box/box.cc [hunk 64]
```diff
@@ -35,6 +35,7 @@
 #include <sys/utsname.h>
 #include <spawn.h>
 
+#include "lua/alloc.h"
```
Comment (Totktonada) [inline src/box/box.cc:38]: Seems unused here.

File: src/main.cc (hunk 21 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/main.cc]: Seems solved (raised a separate discussiong about the non-dynamism).

**Comment by Totktonada** [comment]
@georgiy-belyanin Glanced briefly. I'm mostly comfortable with the patchset, but I have a few questions I would like to solve before proceed. Mainly the (non)-dynamism.

@Buristan PTAL on the updates if time permits.

File: src/lua/alloc.c (hunk 60 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:35]: You're right. Applied.

File: src/box/box.cc (hunk 64 above)
Comment (georgiy-belyanin) [reply src/box/box.cc:38]: Thank you for noticing. Applied.

File: src/lua/alloc.c (hunk 58 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:127]: You're right. Now using IllegalParams in both of the cases. Thank you.

File: src/lua/alloc.c (hunk 62 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:2]: Done. Thank you for that idea.

File: src/lua/alloc.c (hunk 59 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:107]: Seems like the following methods should be ok, I've stolen the approach from 
```lua
static int
luaT_httpc_io_read(lua_State *L)
{
	struct httpc_io *io = luaT_httpc_checkio(L);
	struct httpc_request *req = io->req;
	uint32_t ctypeid = 0;
	char *buf = *(char **)luaL_checkcdata(L, 2, &ctypeid);
	ssize_t len = luaL_checkinteger(L, 3);
	double timeout = luaL_checknumber(L, 4);

	if (len <= 0) {
		diag_set(IllegalParams, "io: payload length must be >= 0");
		return luaT_error(L);
	}

	if (timeout < 0) {
		diag_set(IllegalParams, "io: timeout must be >= 0");
		return luaT_error(L);
	}

	ssize_t res = httpc_request_io_read(req, buf, len, timeout);
	if (res < 0) {
		return luaT_error(L);
	}

	lua_pushinteger(L, res);
	return 1;
}
```
AFAIU, Lua uses 64-bit integers by default (though it can be compiled in 32-bit mode). I suppose there is no need to take it into account since either Lua is compiled in GC64 mode and the option is works OK or Lua memory limit can't be more than 2^31 - 1.

File: src/lua/alloc.c (hunk 61 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:121]: I've tried to use `size_t` though it works quite strange. So I changed the value type to ssize_t.

You may see quite similar approach is mentioned in [one of the comments above](https://github.com/tarantool/tarantool/pull/10223#discussion_r1853557675).

Full diff of the method:
```diff
@@ -115,10 +90,12 @@ lbox_alloc_getmemory(struct lua_State *L)
 static int
 lbox_alloc_setmemory(struct lua_State *L)
 {
-       if (lua_gettop(L) < 1)
-               luaL_error(L, "Usage: alloc.setmemory(amount)");
+       if (lua_gettop(L) < 1) {
+               diag_set(IllegalParams, "Usage: alloc.setmemory(amount)");
+               return luaT_error(L);
+       }

-       long long amount = lua_tointeger(L, 1);
+       ssize_t amount = luaL_checkinteger(L, 1);
```

File: src/lua/alloc.c (hunk 59 above)
Comment (Totktonada) [reply src/lua/alloc.c:107]: Lua has no integers, just `number` (which is `double` under the hood).

`lua_pushinteger` accepts `lua_Integer`, which is `LUA_INTEGER` defined as `ptrdiff_t`. Hm. Seems like it should work with integers beyond 2^32-1.

OTOH, it likely has rounding problems for values above 2^53. It is ~8PiB. Hm. Maybe we can pass it over.

I would like to hear @Buristan's opinion.

File: src/box/lua/config/init.lua (hunk 56 above)
Comment (georgiy-belyanin) [reply src/box/lua/config/init.lua:146]: Done. Thank you.

File: src/box/lua/config/applier/lua.lua (hunk 57 above)
Comment (georgiy-belyanin) [reply src/box/lua/config/applier/lua.lua]: I've added the key for the alert. Now it's impossible for the alert to be duplicated. Thank you.

File: src/box/lua/config/applier/lua.lua [hunk 65]
```diff
@@ -0,0 +1,32 @@
...
+    end
```
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/box/lua/config/applier/lua.lua]: Oh, I misunderstood you. I though you meant the option shouldn't change during the runtime completely. 

I've changed the code in a such way it allows increasing but prohibits decreasing.

File: src/lua/alloc.c (hunk 50 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c]: I no longer do `diag_set` there. By default lua handles this as `not enough memory`. I suppose it's quite ok since this way the error is quite clear, no extra error handling logic is provided.

File: src/lua/alloc.c (hunk 61 above)
Comment (Totktonada) [reply src/lua/alloc.c]: > I've added the test on setting 8Gb memory limit

But, please, don't actually allocate so much memory in a test. We're testing on various hardware and sometimes these are quite small machines.

File: src/lua/alloc.c (hunk 62 above)
Comment (Totktonada) [reply src/lua/alloc.c]: I would do it in the header file too.

File: src/lua/alloc.c (hunk 61 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c]: It just tests it's possible to specify such limit, not actually allocate this much RAM.

Comment (Totktonada) [reply src/lua/alloc.c]: OK. I don't bother about values beyond 2^63-1.

File: src/lua/alloc.c [hunk 66]
```diff
@@ -0,0 +1,150 @@
...
+static int
+lbox_alloc_allocated(struct lua_State *L)
+{
+	lua_pushinteger(L, allocated);
+	return 1;
+}
+
+/**
+ * alloc.allocated() -- get the amount of free memory.
+ */
```
Comment (Totktonada) [inline src/lua/alloc.c:129]: Typo: alloc.allocated() -> alloc.free().

File: src/lua/alloc.c [hunk 67]
```diff
@@ -0,0 +1,150 @@
...
+}
+
+void
+tarantool_lua_alloc_init(struct lua_State *L)
+{
+	static const struct luaL_Reg alloc_methods[] = {
+		{"setmemory", lbox_alloc_setmemory},
+		{"getmemory", lbox_alloc_getmemory},
+		{"allocated", lbox_alloc_allocated},
+		{"free",      lbox_alloc_free},
```
Comment (Totktonada) [inline src/lua/alloc.c:144]: If we use `ibuf`'s terminology, it is `used` and `unused`. The `free` word feels like a verb ('free memory').

File: src/lua/alloc.c [hunk 68]
```diff
@@ -0,0 +1,150 @@
...
+	lua_pushinteger(L, memory - allocated);
+	return 1;
+}
+
+void
+tarantool_lua_alloc_init(struct lua_State *L)
+{
+	static const struct luaL_Reg alloc_methods[] = {
+		{"setmemory", lbox_alloc_setmemory},
+		{"getmemory", lbox_alloc_getmemory},
```
Comment (Totktonada) [inline src/lua/alloc.c:142]: How about getlimit/setlimit? Seems more intuitive.

Or we can use word 'quota'.

File: src/lua/alloc.h [hunk 69]
```diff
@@ -0,0 +1,60 @@
...
+
+#include <stddef.h>
+
+#include <lua.h>
+
+/**
+ * Limits the maximum available Lua memory.
+ */
+int
+luaT_setallocmemory(size_t memory);
```
Comment (Totktonada) [inline src/lua/alloc.h:46]: It seems, it is not used anywhere outside of `alloc.c`.

File: src/lua/alloc.c [hunk 70]
```diff
@@ -0,0 +1,150 @@
...
+
+	/*
+	 * Result may be NULL, in this case "not enough memory"
+	 * is raised.
+	 */
+	return result;
+}
+
+int
+luaT_setallocmemory(size_t amount)
```
Comment (Totktonada) [inline src/lua/alloc.c:52]: Seems like `luaT` prefix is not needed: the function doesn't access a Lua state.

File: src/lua/alloc.c (hunk 50 above)
Comment (Totktonada) [reply src/lua/alloc.c]: Seems OK for me, thanks for the update!

File: src/box/lua/config/applier/lua.lua [hunk 71]
```diff
@@ -0,0 +1,37 @@
...
+        alloc.setmemory(memory)
+
+        log.verbose(('lua.apply: set memory limit to %d'):format(memory))
+    -- If memory limit is decreased.
+    elseif memory < old_memory then
+        local name = 'lua_memory_decreased'
+        local warning = 'lua.apply: lua.memory decrease will not be applied ' ..
+                        'until the instance is restarted'
+
+        config._aboard:set({type = 'warn', message = warning}, {key = name})
```
Comment (Totktonada) [inline src/box/lua/config/applier/lua.lua:26]: I'm OK, but if the underlying API allows to decrease it to some extent, can we allow to do so from the config? In the similar way: if it is impossible, report an alert and wait for reloading.

I'm OK with the refusal to descrease it in runtime, just curious.

@georgiy-belyanin @Buristan What do you think?

**Review by Totktonada — APPROVED** [review]
I've no objections here. I wrote some remarks/ideas down, but they look optional. OK from me.

File: src/lua/alloc.c (hunk 68 above)
Comment (Buristan) [reply src/lua/alloc.c:142]: `alloc.setlimit()`/`alloc.getlimit()` sounds better for me too.

File: src/lua/alloc.c [hunk 72]
```diff
@@ -0,0 +1,150 @@
...
+/**
+ * Lua custom memory allocation function. It extends the original
+ * one with a memory counter and a limit check.
+ */
+static void *
+luaT_alloc(void *ud, void *ptr, size_t osize, size_t nsize)
+{
+	size_t new_allocated = allocated + nsize - osize;
+	if (new_allocated > memory) {
+		/* Returning NULL results with "not enough memory" error. */
```
Comment (Buristan) [inline src/lua/alloc.c:35]: Nit: Comment line width is more than 66 symbols.
Typo: s/results with/results in the/

File: src/lua/alloc.c [hunk 73]
```diff
@@ -0,0 +1,150 @@
...
+
+/**
+ * The default allocator function which is wrapped into a new one
+ * with the Lua memory limit checker.
+ */
+static lua_Alloc orig_alloc;
+/**
+ * The maximum allowed LuaJIT memory limit.
+ */
+static size_t memory = LUA_MEMORY_DEFAULT;
```
Comment (Buristan) [inline src/lua/alloc.c:20]: Minor: `memory_limit` sounds more clear to me (`memory` associates with a "currently allocated memory").
Feel free to ignore.

File: src/box/lua/config/applier/lua.lua [hunk 74]
```diff
@@ -0,0 +1,37 @@
...
+    end
+    -- Nothing to do if memory limit is unchanged.
+
+
+    is_lua_memory_applied = true
```
[the remark this answers is not in the document]
Comment (Buristan) [reply src/box/lua/config/applier/lua.lua:31]: I think that maybe we should alow to decrease the memory limit, if it is not less than the currently allocated memory amount, since I see no drawbacks of this. Also, this alows to drop the special first-call case.

But I'm OK with your's or Georgiy's approach.

**Review by Buristan — APPROVED** [review]
Hi, Georgiy!
Thanks for the fixes!
I'll proceed with the review per-patch below.

---
**[PATCH 1/2] lua: add custom allocator with memory limit**

LGTM after fixing Alexander's comments, with a few nits regarding the commit message and comments.

> This patch adds support for custom Lua allocator supporting memory

Typo: s/custom/the custom/


> New internal Lua module `internal.alloc` could be used to access the

Typo: s/New/The new/

> checking currently allocated/free amount of memory.

Typo: s/currently/the currently/

**Review by Buristan — APPROVED** [review]
**[PATCH 2/2] config: add `lua.memory` option**

LGTM, with some notes below.

File: src/lua/alloc.c (hunk 72 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:35]: Thank you for noticing the typo.

But for the line width: it's less than 66. Or one tab counts as 8 spaces? If so, I've fixed it.
And, actually, I don't understand why the limit should be 66. I see no such point in [https://www.tarantool.io/en/doc/latest/contributing/c_style_guide/](https://www.tarantool.io/en/doc/latest/contributing/c_style_guide/).

File: src/lua/alloc.c (hunk 67 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:144]: Applied.

File: src/lua/alloc.c (hunk 68 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:142]: Applied. Thank you.

File: src/lua/alloc.c (hunk 66 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:129]: Now the method is called `alloc.unused()`. Applied.

File: src/lua/alloc.c (hunk 62 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c]: Oh, I am sorry. Applied

File: src/lua/alloc.c (hunk 72 above)
Comment (Totktonada) [reply src/lua/alloc.c:35]: 66 characters limit was enforced for comments in the past as optimal width for a prose text readability. But it was not about a significant columns, includes the indent. Don't know why. Later we agreed that 80 symbols is good too.

Personally, I continue to use 66, but it is not enforced anymore.

I guess Sergey refers to the old limit.

File: src/lua/alloc.c (hunk 73 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:20]: Applied. You're right it's clearer.

File: src/lua/alloc.c (hunk 70 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c:52]: I've removed it.  Now it is `set_alloc_limit` .Thank you.

File: src/box/lua/config/applier/lua.lua (hunk 74 above)
[the remark this answers is not in the document]
Comment (georgiy-belyanin) [reply src/box/lua/config/applier/lua.lua:31]: I've worked on this and I suggest to allow the limit to be decreased up to the current amount of the used Lua memory plus some extra unused space (I've chosen arbitrary value of 16MB) to make sure not to instantly throw and error after setting the limit. If there is already too much allocated memory the alert is issued.

[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/lua/config/applier/lua.lua:31]: Allowed limit values in `[used+16MiB; +inf]` look OK for me.

File: src/lua/alloc.c [hunk 75]
```diff
@@ -0,0 +1,153 @@
...
+static int
+lbox_alloc_getlimit(struct lua_State *L)
+{
+	lua_pushinteger(L, memory_limit);
+	return 1;
+}
+
+/**
+ * alloc.set() -- set the allocator memory limit.
+ * Returns old memory limit.
```
Comment (Totktonada) [inline src/lua/alloc.c:93]: Nit: alloc.set() -> alloc.setlimit()

File: src/box/lua/config/applier/lua.lua (hunk 74 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/lua/config/applier/lua.lua]: I would possibly prefer to handle this safely memory amount on the `alloc.c` level, but it may require to report different error codes to the config's applier and complicate things so. Anyway, I'm OK with how it is done now, just thoughts.

File: src/lua/alloc.c (hunk 75 above)
Comment (georgiy-belyanin) [reply src/lua/alloc.c]: Applied. Thank you.

File: src/lua/alloc.c (hunk 72 above)
Comment (Buristan) [reply src/lua/alloc.c]: OK, maybe it is worth updating the Wiki then (I'm personally afraid to alter Vlad's manual :) ).
