### PR TITLE
lua/utils: use `index2adr()` instead of index arithmetic

### LINKED ISSUE #8249: `luaL_checkcdata` et al. do not work with upvalues
**Bug description**

This code performs calculations to obtain the address from the given index, but it doesn't work for pseudo-indexes (e.g. upvalue indexes):
https://github.com/tarantool/tarantool/blob/352fe0c7d774ebaf91b165c99b8c67b9528a2cca/src/lua/utils.c#L171-L176

https://github.com/tarantool/tarantool/blob/352fe0c7d774ebaf91b165c99b8c67b9528a2cca/src/lua/utils.c#L182-L183

**Steps to reproduce**

```c
static int
closure(lua_State *L)
{
	uint32_t ctypeid;
	luaL_checkcdata(L, lua_upvalueindex(1), &ctypeid);
	return 0;
}

static void
test_upvalueindex(lua_State *L)
{
	uint32_t pvoid_ctypeid = luaL_ctypeid(L, "void *");
	*(void **) luaL_pushcdata(L, pvoid_ctypeid) = NULL;
	lua_pushcclosure(L, &closure, 1);
	lua_call(L, 0, 0);
}
```

**Actual behavior**

Lua error `expected cdata as -10002 argument` raised.

**Expected behavior**

No errors.

Needed for #7356

### PR DESCRIPTION
**Pull request by Gumix**
We have a code that performs calculations to obtain the address from the
given index, the address is then passed to `cdataV()` to get cdata value from
the stack. But this doesn't work for pseudo-indexes (e.g. upvalue indexes).
This patch brings `index2adr()` from `luajit/src/lj_api.c`, which accepts all
kinds of indexes, so that the calculations are no longer needed. Also the
helper function `luaL_tocpointer()` is introduced.

Closes #8249

### CODE REVIEW

File: src/lua/utils.c [hunk 1]
```diff
@@ -53,6 +53,37 @@ uint32_t CTID_UUID;
 uint32_t CTID_DATETIME = 0;
 uint32_t CTID_INTERVAL = 0;
 
+/** A copy of index2adr() from luajit/src/lj_api.c */
+static TValue *
+luaL_index2adr(lua_State *L, int idx)
```
Comment (igormunkin) [inline src/lua/utils.c:58]: Generally, we try to avoid using `luaL` prefix in function naming (see #4577 for more info), but this still respects our current guidelines and this function is not exported, so can be freely renamed later. Feel free to ignore.

File: src/lua/utils.c [hunk 2]
```diff
@@ -554,17 +576,13 @@ luaT_tolstring(lua_State *L, int idx, size_t *len)
 	return lua_tolstring(L, -1, len);
 }
 
-/* Based on ffi_meta___call() from luajit/src/lib_ffi.c. */
```
Comment (igormunkin) [inline src/lua/utils.c:557]: Typo: According to our [guidelines](https://www.tarantool.io/en/doc/latest/dev_guide/c_style_guide/#chapter-8-commenting) dots are required in comments. Same for the comment above.

**Review by igormunkin — CHANGES_REQUESTED** [review]
@Gumix, thanks for the patch! Besides the comments below, I also grepped all sources to find all `L->base` occurrences. There is one in `src/lua/utils.h` and two in `src/lua/serializer.c`.

Considering these usages, I'd rather suggest to introduce the helper to obtain cdata payload.

File: src/lua/utils.c (hunk 1 above)
Comment (Gumix) [reply src/lua/utils.c]: Renamed to `index2adr()`.

File: src/lua/utils.c (hunk 2 above)
Comment (Gumix) [reply src/lua/utils.c:598]: Fixed.

**Comment by Gumix** [comment]
> @Gumix, thanks for the patch! Besides the comments below, I also grepped all sources to find all `L->base` occurrences. There is one in `src/lua/utils.h` and two in `src/lua/serializer.c`.
> 
> Considering these usages, I'd rather suggest to introduce the helper to obtain cdata payload.

Added `get_cdata()`.

> P.S. I also think, that changelog is required, since you change the semantics of the public interfaces.

Added changelog and testcase.

File: src/lua/utils.c [hunk 3]
```diff
@@ -54,6 +54,43 @@ uint32_t CTID_UUID;
...
+		} else {
+			idx = LUA_GLOBALSINDEX - idx;
+			return idx <= fn->c.nupvalues ?
+			       &fn->c.upvalue[idx - 1] : niltv(L);
+		}
+	}
+}
+
+GCcdata *
+get_cdata(struct lua_State *L, int idx)
```
Comment (igormunkin) [inline src/lua/utils.c:89]: OK, this is not quite the thing I meant in the previous review. I propose to implement a new function `luaL_tocpointer(lua_State *L, int idx, uint32_t *ctypeid)` with the signature similar to `lua_tolstring` and implementing `luaL_checkcdata` without actual check. I left an example below.

```c
void *
luaL_tocpointer(lua_State *L, int idx, uint32 *ctypeid) {
        TValue *o = index2adr(L, idx);
        if (!tviscdata(o)) {
                if (ctypeid != NULL) *ctypeid = 0;
                return NULL;
        }
        GCcdata *cd = cdataV(o);
        if (ctypeid != NULL) *ctypeid = cd->ctypeid;
        return cdataptr(cd);
}
```

IMHO, such function can be used widely in Tarantool to work with cdata without additional checks.

**Review by igormunkin — CHANGES_REQUESTED** [review]
@Gumix, thanks for the changes! I've left some more comments below.

The main purpose of introducing `luaL_tocpointer` is avoid raw access to `L->base`. For other enhancements (if there is something you want to change) I suggest to open a new PR.

BTW, I'd rather split introducing of `index2adr` helper and `luaL_tocpointer` function into 2 separate commits. This is just recommendation, so feel free to ignore.

File: src/lua/serializer.c [hunk 4]
```diff
@@ -447,9 +465,6 @@ int
 luaL_tofield(struct lua_State *L, struct luaL_serializer *cfg, int index,
 	     struct luaL_field *field)
 {
-	if (index < 0)
-		index = lua_gettop(L) + index + 1;
-
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/lua/serializer.c]: Reverted.

File: src/lua/utils.c (hunk 3 above)
Comment (Gumix) [reply src/lua/utils.c]: Done.

**Review by igormunkin — APPROVED** [review]
@Gumix, thanks for the fixes! LGTM.
