### PR TITLE
config: add env option to `config:get()`

### LINKED ISSUE #9824: config: allow to discard values from `TT_*`` vars in config:get()
We're going to add support for retrieving configuration for other cluster members using `config:get()` (#9680). The syntax is the following.

```lua
-- Acquire the given option values for the given instance.
config:get(<..option..>, {instance = <...>})
```

The only information we know about other instances is the cluster configuration (a file or a remote configuration in etcd/config storage). The configuration from the `TT_*` environment variables relates only to the given instance and has no influence on the other ones.

Taking this into account, `config:get()` with the `instance` option doesn't look into the `TT_*` variables. It also ignores them if the current instance name is passed to the option, it is for consistency.

At the same time, `config:get()` without the `instance` option takes the `TT_*` variables into account.

All this behavior is valid and consistent.

However, a user may be confused by the difference:

```lua
-- Has TT_* values.
config:get(<...>)

-- Has no TT_* values.
config:get(<...>, {instance = box.info.name})
```

An explicit option that controls, whether to take environment variables into account, may resolve this confusion.

```lua
-- Has TT_* values.
config:get(<...>)
config:get(<...>, {use_env = true})
config:get(<...>, {instance = box.info.name, use_env = true})

-- Has no TT_* values.
config:get(<...>, {use_env = false})
config:get(<...>, {instance = box.info.name})
config:get(<...>, {instance = box.info.name, use_env = false})
config:get(<...>, {instance = 'another-instance'})
config:get(<...>, {instance = 'another-instance', use_env = false})

-- Error.
config:get(<...>, {instance = 'another-instance', use_env = true})
- error: config:get: TT_* environment variables taken into account by the "another-instance" instance are unknown on the current instance "myinstance"
```

OTOH, it has no much sense to pass this option together with the `instance` option. We can forbid it.

```lua
-- Has TT_* values.
config:get(<...>)
config:get(<...>, {use_env = true})

-- Has no TT_* values.
config:get(<...>, {use_env = false})
config:get(<...>, {instance = box.info.name})
config:get(<...>, {instance = 'another-instance'})

-- Error.
config:get(<...>, {instance = box.info.name, use_env = false})
config:get(<...>, {instance = box.info.name, use_env = true})
config:get(<...>, {instance = 'another-instance', use_env = true})
- error: config:get: "instance" and "use_env" options can't be used together, because it is unknown which TT_* environment variables were passed to another instance
```

It is also possible to implement some kind of a 'best effort' semantic: look into `TT_*` on `use_env = true` if `instance` is omitted or set to the current one. Ignore `TT_*` on `use_env = false` if the `instance` is NOT the current one.

And, of course, there is an option to don't add the `use_env` option at all. I'm looking into the API variants and TBH don't know whether it adds less confusion than resolves.

Let's discuss?

----

Initially proposed by @locker in https://github.com/tarantool/tarantool/pull/9808#discussion_r1523962804.

### PR DESCRIPTION
**Pull request by mandesero**
This patch adds the env option to `config:get()` to explicitly control whether `TT_*` environment variables are taken into account.

Closes #9824

### CODE REVIEW

File: src/box/lua/config/init.lua [hunk 1]
```diff
@@ -457,12 +457,35 @@ end
...
+    end
+    if opts.instance ~= nil and opts.env == true then
+        error('config:get: "instance" and "env = true" options can\'t be ' ..
+              'used together, because it is unknown which TT_* environment ' ..
+              'variables were passed to another instance', 0)
+    end
+
+    if opts.env == false and opts.instance == nil then
+        opts.instance = self._configdata_applied:names().instance_name
+    end
```
Comment (grafin) [inline src/box/lua/config/init.lua]: Why do we check for `opts.env` here? shouldn't we fallback to `self` in any case?

Comment (mandesero) [reply src/box/lua/config/init.lua]: The `opts.env` option changes the lookup semantics.

When `opts.env == true`, the value is read from env / global scope, where binding to a specific instance does not make sense, so `opts.instance` must remain `nil`. Falling back to `self` in this case would silently turn an environment-level lookup into an instance-level one.

Note that if `opts.env == nil` and `opts.instance == nil`, the request is equivalent to `env = true, instance = nil` 
```lua
-- Has TT_* values.
config:get(<...>)
config:get(<...>, {env = true})
```

Falling back to `self` is only correct when `opts.env == false` and the instance name is not explicitly set, i.e. when an instance-specific value is requested without specifying an instance explicitly.

The same logic could be expressed as:

```lua
-- At this point, we already know that either:
--  - env == true and instance must be nil, or
--  - env == false, and instance may be either explicitly set or unspecified.
if opts.env == false then
    opts.instance = opts.instance or
        self._configdata_applied:names().instance_name
end
```

File: src/box/lua/config/init.lua [hunk 2]
```diff
@@ -457,12 +457,35 @@ end
...
+        error(('Expected boolean, got %s'):format(type(opts.env)), 0)
+    end
+    if opts.instance ~= nil and opts.env == true then
+        error('config:get: "instance" and "env = true" options can\'t be ' ..
+              'used together, because it is unknown which TT_* environment ' ..
+              'variables were passed to another instance', 0)
+    end
+
+    if opts.env == false and opts.instance == nil then
+        opts.instance = self._configdata_applied:names().instance_name
```
Comment (georgiy-belyanin) [inline src/box/lua/config/init.lua]: Nit: This changes the `opts` table, could you, please, take this into account since it can sometimes be quite unexpected (see tarantool/tarantool#10886).

File: src/box/lua/config/init.lua (hunk 1 above)
Comment (georgiy-belyanin) [reply src/box/lua/config/init.lua]: Minor: I would mention that in a comment then. Thank you for an explanation.

File: src/box/lua/config/init.lua (hunk 2 above)
Comment (mandesero) [reply src/box/lua/config/init.lua]: Fixed it. Thanks!

File: src/box/lua/config/init.lua (hunk 1 above)
Comment (mandesero) [reply src/box/lua/config/init.lua]: Added.

File: src/box/lua/config/init.lua (hunk 2 above)
Comment (georgiy-belyanin) [reply src/box/lua/config/init.lua]: Cool! Thank you!

**Review by georgiy-belyanin — APPROVED** [review]
Thank you for working on this! Please, check what is wrong with CI.

**Comment by mandesero** [comment]
> Thank you for working on this! Please, check what is wrong with CI.

Thank you! ~~Unfortunately, I haven't yet figured out what's going wrong and why the test isn't passing. Perhaps it's taking too long and timing out.~~

I ran the test locally and it’s not flaky.
In CI it’s likely being killed due to memory limits (exit code 137 / OOM), so I’ll add the `noflaky` label to skip this workflow.

**Review by lenkis — APPROVED** [review]

**Comment by georgiy-belyanin** [comment]
Hey, @grafin could you take a look at this stale PR?

File: src/box/lua/config/init.lua [hunk 3]
```diff
@@ -457,14 +457,45 @@ end
...
+-- opts.instance is set, an error is raised.
 function methods.get(self, path, opts)
     selfcheck(self, 'get')
     initcheck(self, 'get', 'instance')
 
     opts = opts or {}
 
+    if type(opts) ~= 'table' then
+        error(('Expected table, got %s'):format(type(opts)), 0)
+    end
```
[the remark this answers is not in the document]
Comment (mandesero) [reply src/box/lua/config/init.lua:472]: This feels a bit too nitpicky to me. Passing `false` as `opts` doesn’t seem like a realistic or intended use case for this API.

**Review by Godrik0 — APPROVED** [review]
Thanks for the work! I have no questions.
