### PR TITLE
sql: fix assert when compare a tuple with a key

### LINKED ISSUE #6849: Assertion failure in tarantoolsqlIdxKeyCompare()
Tarantool 2.10.0-beta2-103-gdd1a510e2
Target: Linux-x86_64-Debug

Build:

```
cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF && make -j
```

Test:

```
./test/test-run.py --conf memtx sql-tap/where7.test.lua
```

Result:

```
<...>
[001] ok - where7-2.815.1
[001] ok - where7-2.815.2
[001] ok - 
[001] Last 15 lines of Tarantool Log file [Instance "app_server"][/home/alex/projects/tarantool-meta/r/t-5/test/var/001_sql-tap/where7.test.lua:memtx.tarantool.log]:
[001] tarantool: /home/alex/p/tarantool-meta/r/t-5/src/box/sql.c:781: tarantoolsqlIdxKeyCompare: Assertion `rc == new_rc' failed.
```

Backtrace:

```c
$ gdb ./src/tarantool -c test/var/001_sql-tap/core
<...>
(gdb) bt
#0  0x00007fa6b5d891cc in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007fa6b5d3d982 in raise () from /lib64/libc.so.6
#2  0x00007fa6b5d28449 in abort () from /lib64/libc.so.6
#3  0x00007fa6b5d28375 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007fa6b5d36af2 in __assert_fail () from /lib64/libc.so.6
#5  0x000056127d614ebe in tarantoolsqlIdxKeyCompare (cursor=0x56127e5a84b0, unpacked=0x7fa6b51ff3c0) at /home/alex/p/tarantool-meta/r/t-5/src/box/sql.c:781
#6  0x000056127d69af67 in sqlVdbeExec (p=0x56127e5a8838) at /home/alex/p/tarantool-meta/r/t-5/src/box/sql/vdbe.c:3727
#7  0x000056127d69d8ac in sqlStep (p=0x56127e5a8838) at /home/alex/p/tarantool-meta/r/t-5/src/box/sql/vdbeapi.c:156
#8  0x000056127d69d95c in sql_step (pStmt=0x56127e5a8838) at /home/alex/p/tarantool-meta/r/t-5/src/box/sql/vdbeapi.c:184
#9  0x000056127d61a3d9 in sql_execute (stmt=0x56127e5a8838, port=0x7fa6b51ffce0, region=0x7fa6b5000430) at /home/alex/p/tarantool-meta/r/t-5/src/box/execute.c:558
#10 0x000056127d61a841 in sql_prepare_and_execute (
    sql=0x405a4b50 "     SELECT a FROM t3\n      WHERE (d>=77.0 AND d<78.0 AND d IS NOT NULL)\n         OR a=1\n         OR ((a BETWEEN 93 AND 95) AND a!=94)\n         OR b=278\n         OR (g='xwvutsr' AND f LIKE 'defgh%')\n "..., len=462, bind=0x0, bind_count=0, port=0x7fa6b51ffce0, region=0x7fa6b5000430) at /home/alex/p/tarantool-meta/r/t-5/src/box/execute.c:627
#11 0x000056127d6e13e7 in lbox_execute (L=0x40c91378) at /home/alex/p/tarantool-meta/r/t-5/src/box/lua/execute.c:484
#12 0x000056127d75cb9f in lj_BC_FUNCC () at buildvm_x86.dasc:811
#13 0x000056127d767dab in lua_pcall (L=0x40c91378, nargs=0, nresults=0, errfunc=0) at /home/alex/p/tarantool-meta/r/t-5/third_party/luajit/src/lj_api.c:1187
#14 0x000056127d6f60d3 in luaT_call (L=0x40c91378, nargs=0, nreturns=0) at /home/alex/p/tarantool-meta/r/t-5/src/lua/utils.c:464
#15 0x000056127d6ee233 in lua_main (L=0x40c91378, argc=1, argv=0x56127e559f58) at /home/alex/p/tarantool-meta/r/t-5/src/lua/init.c:797
#16 0x000056127d6ee7a8 in run_script_f (ap=0x7fa6b50004f0) at /home/alex/p/tarantool-meta/r/t-5/src/lua/init.c:886
#17 0x000056127d4e1d5e in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x56127d6ee24c <run_script_f>, ap=0x7fa6b50004f0)
    at /home/alex/p/tarantool-meta/r/t-5/src/lib/core/fiber.h:922
#18 0x000056127d71c16b in fiber_loop (data=0x0) at /home/alex/p/tarantool-meta/r/t-5/src/lib/core/fiber.c:918
#19 0x000056127d9e2045 in coro_init () at /home/alex/p/tarantool-meta/r/t-5/third_party/coro/coro.c:110
```

Lua backtrace:

```c
(gdb) lj-stack
0x41cb44e8:0x41cb4508 [    ] 5 slots: Red zone
0x41cb44e0            [   M]
0x41cb4248:0x41cb44d8 [    ] 83 slots: Free stack slots
0x41cb4240            [  T ]
0x41cb4238            [ B  ] VALUE: string "     SELECT a FROM t3\n      WHERE (d>=77.0 AND d<78.0 AND d IS NOT NULL)\n         OR a=1\n         OR ((a BETWEEN 93 AND 95) AND a!=94)\n         OR b=278\n         OR (g='xwvutsr' AND f LIKE 'defgh%')\n "... @ 0x405a4b40
0x41cb4230            [    ] FRAME: [L] delta=10, C function @ 0x56127d6e12a6
0x41cb4228            [    ] VALUE: string "     SELECT a FROM t3\n      WHERE (d>=77.0 AND d<78.0 AND d IS NOT NULL)\n         OR a=1\n         OR ((a BETWEEN 93 AND 95) AND a!=94)\n         OR b=278\n         OR (g='xwvutsr' AND f LIKE 'defgh%')\n "... @ 0x405a4b40
0x41cb4220            [    ] VALUE: number 1
0x41cb4218            [    ] VALUE: number -nan(0xe7fff00000002)
0x41cb4210            [    ] VALUE: table @ 0x413de2b8 (asize: 3, hmask: 0x0)
0x41cb4208            [    ] VALUE: fast function #4
0x41cb4200            [    ] VALUE: nil
0x41cb41f8            [    ] VALUE: nil
0x41cb41f0            [    ] VALUE: table @ 0x413de2b8 (asize: 3, hmask: 0x0)
0x41cb41e8            [    ] VALUE: string "     SELECT a FROM t3\n      WHERE (d>=77.0 AND d<78.0 AND d IS NOT NULL)\n         OR a=1\n         OR ((a BETWEEN 93 AND 95) AND a!=94)\n         OR b=278\n         OR (g='xwvutsr' AND f LIKE 'defgh%')\n "... @ 0x405a4b40
0x41cb41e0            [    ] FRAME: [L] delta=3, Lua function @ 0x41388af8, 1 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/var/001_sql-tap/sqltester.lua":149
0x41cb41d8            [    ] VALUE: string "     SELECT a FROM t3\n      WHERE (d>=77.0 AND d<78.0 AND d IS NOT NULL)\n         OR a=1\n         OR ((a BETWEEN 93 AND 95) AND a!=94)\n         OR b=278\n         OR (g='xwvutsr' AND f LIKE 'defgh%')\n "... @ 0x405a4b40
0x41cb41d0            [    ] VALUE: table @ 0x41fc9a48 (asize: 0, hmask: 0x3f)
0x41cb41c8            [    ] FRAME: [L] delta=2, Lua function @ 0x41388528, 2 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/var/001_sql-tap/sqltester.lua":166
0x41cb41c0            [    ] VALUE: string "     SELECT a FROM t3\n      WHERE (d>=77.0 AND d<78.0 AND d IS NOT NULL)\n         OR a=1\n         OR ((a BETWEEN 93 AND 95) AND a!=94)\n         OR b=278\n         OR (g='xwvutsr' AND f LIKE 'defgh%')\n "... @ 0x405a4b40
0x41cb41b8            [    ] FRAME: [PP] delta=1, Lua function @ 0x41f56ab8, 1 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/sql-tap/where7.test.lua":30
0x41cb41b0            [    ] FRAME: [L] delta=5, fast function #20
0x41cb41a8            [    ] VALUE: table @ 0x40145840 (asize: 33, hmask: 0x0)
0x41cb41a0            [    ] VALUE: Lua function @ 0x40145820, 1 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/sql-tap/where7.test.lua":32856
0x41cb4198            [    ] VALUE: string "where7-2.878.2" @ 0x412c79b8
0x41cb4190            [    ] VALUE: table @ 0x41fc9a48 (asize: 0, hmask: 0x3f)
0x41cb4188            [    ] FRAME: [L] delta=4, Lua function @ 0x41389238, 3 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/var/001_sql-tap/sqltester.lua":121
0x41cb4180            [    ] VALUE: Lua function @ 0x41f56ab8, 1 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/sql-tap/where7.test.lua":30
0x41cb4178            [    ] VALUE: Lua function @ 0x41f56a78, 1 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/sql-tap/where7.test.lua":25
0x41cb4170            [    ] VALUE: table @ 0x41fc9a48 (asize: 0, hmask: 0x3f)
0x41cb4168            [    ] FRAME: [V] delta=1, Lua function @ 0x4161b970, 0 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/sql-tap/where7.test.lua":0
0x41cb4160            [    ] FRAME: [CP] delta=1, Lua function @ 0x4161b970, 0 upvalues, "@/home/alex/projects/tarantool-meta/r/t-5/test/sql-tap/where7.test.lua":0
0x41cb4158            [S   ] FRAME: dummy L
```

### PR DESCRIPTION
**Pull request by Totktonada**
The function of the question (`tarantoolsqlIdxKeyCompare()`) compares a
tuple with a key. It extracts necessary fields from the tuple and runs
the compare function, which is basically `memcmp()` of two buffers (for
`varbinary` values -- numeric comparisons are different).

In the Debug build the function also re-verifies the result using a
separate comparison code. And here we compare two `memcmp()` return
values.

We shouldn't do it directly, because `memcmp()` only guarantees sign of
the result. Please, consider the linked issue for details.

NO_DOC=only debug build is affected
NO_CHANGELOG=only debug build is affected
NO_TEST=hard to create a stable reproducer

Fixes #6849

### CODE REVIEW

File: src/box/sql.c [hunk 1]
```diff
@@ -778,7 +778,25 @@ tarantoolsqlIdxKeyCompare(struct BtCursor *cursor,
...
+		/*
+		 * Here we compare two results from memcmp() alike
+		 * calls. A particular implementation depends on
+		 * a type of msgpack values to compare. For some
+		 * of them we actually call memcmp().
+		 *
+		 * memcmp() only guarantees that a result will be
+		 * less than zero, zero or more than zero. It
+		 * DOES NOT guarantee that the result will be
+		 * substraction of first non equal bytes or
```
Comment (kyukhin) [inline src/box/sql.c:790]: 1. substraction -> subtraction
2. first -> the first
3. non equal -> non-equal

Comment (Totktonada) [reply src/box/sql.c]: Thanks! Updated.

**Review by kyukhin — APPROVED** [review]

**Review by ImeevMA — APPROVED** [review]
LGTM.

**Comment by Totktonada** [comment]
Cherry-picked to 2.8 in 2.8.3-46-gb63267bf9.

@kyukhin Please, don't forget about that.
