### PR TITLE
box: cover box_wait limbo_acked

### LINKED ISSUE #7318: Cover box_wait_limbo_acked with tests
**Bug description**

Currently all the tests pass fine with the following patch:

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index bfef966fd..1decb956a 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1879,16 +1879,24 @@ box_wait_limbo_acked(double timeout)
        last_entry = txn_limbo_last_synchro_entry(&txn_limbo);
        /* Wait for the last entries WAL write. */
        if (last_entry->lsn < 0) {
+               assert(false);
                int64_t tid = last_entry->txn->id;

-               if (wal_sync(NULL) != 0)
+               if (wal_sync(NULL) != 0) {
+                       assert(false);
                        return -1;
+               }

-               if (box_check_promote_term_intact(promote_term) != 0)
+               if (box_check_promote_term_intact(promote_term) != 0) {
+                       assert(false);
                        return -1;
-               if (txn_limbo_is_empty(&txn_limbo))
+               }
+               if (txn_limbo_is_empty(&txn_limbo)) {
+                       assert(false);
                        return txn_limbo.confirmed_lsn;
+               }
                if (tid != txn_limbo_last_synchro_entry(&txn_limbo)->txn->id) {
+                       assert(false);
                        diag_set(ClientError, ER_QUORUM_WAIT, quorum,
                                 "new synchronous transactions appeared");
                        return -1;
@@ -1900,18 +1908,24 @@ box_wait_limbo_acked(double timeout)
        if (box_wait_quorum(txn_limbo.owner_id, wait_lsn, quorum, timeout) != 0)
                return -1;

-       if (box_check_promote_term_intact(promote_term) != 0)
+       if (box_check_promote_term_intact(promote_term) != 0) {
+               assert(false);
                return -1;
+       }

-       if (txn_limbo_is_empty(&txn_limbo))
+       if (txn_limbo_is_empty(&txn_limbo)) {
+               assert(false);
                return txn_limbo.confirmed_lsn;
+       }

        if (quorum < replication_synchro_quorum) {
+               assert(false);
                diag_set(ClientError, ER_QUORUM_WAIT, quorum,
                         "quorum was increased while waiting");
                return -1;
        }
        if (wait_lsn < txn_limbo_last_synchro_entry(&txn_limbo)->lsn) {
+               assert(false);
                diag_set(ClientError, ER_QUORUM_WAIT, quorum,
                         "new synchronous transactions appeared");
                return -1;
```

**Actual behavior**

All tests pass.

**Expected behavior**

Some tests fail.

### PR DESCRIPTION
**Pull request by Astronomax**
Prior to this patch, there were many possible code execution options
that were not covered by tests. After this commit, any assert(false)
inside box_wait_limbo_acked cause a crash.

Closes #7318

NO_DOC=test
NO_CHANGELOG=test

### CODE REVIEW

**Review by ochaplashkin — APPROVED** [review]

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 1]
```diff
@@ -0,0 +1,433 @@
...
+end
+
+local function check_wal_is_blocked_f()
+    if not box.error.injection.get('ERRINJ_WAL_DELAY') then
+        error('WAL still is not paused')
+    end
+end
+
+local function server_wait_wal_is_blocked(server)
+    t.helpers.retrying({timeout = wait_timeout}, server.exec, server,
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:31]: Nit: you may retry inside `server.exec`. This way there will be no need to retry many exec calls. Instead, all the retrying will be done inside one exec call.
For example, `check_wal_is_blocked_f` may be turned into `wait_wal_is_blocked_f`.

Same for other `check_..._f` and `wait_...` pairs.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 2]
```diff
@@ -0,0 +1,433 @@
...
+            election_mode = 'off',
+            replication_synchro_quorum = 2,
+            replication_synchro_timeout = 100000,
+        }
+    })
+    cg.master_proxy = proxy:new({
+        client_socket_path = server.build_listen_uri('master_proxy'),
+        server_socket_path = server.build_listen_uri('master', cg.cluster.id),
+    })
+    cg.master_proxy:start({force = true})
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:132]: It's good practice to check that `proxy:start()` succeeded

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 3]
```diff
@@ -0,0 +1,433 @@
...
+        require('fiber').create(function() box.space.test:insert{1} end)
+    end)
+    server_wait_synchro_queue_len_is_equal(cg.replica, 1)
+    local csw = get_fiber_csw(cg.replica, f)
+    cg.replica:exec(function()
+        box.error.injection.set('ERRINJ_WAL_SYNC', true)
+        box.error.injection.set('ERRINJ_WAL_DELAY_COUNTDOWN', 0)
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
+    end)
+    server_wait_fiber_csw_geq_than(cg.replica, f, csw + 1)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:171]: This needs a comment. Why waiting for fiber csw helps us stabilize the test?

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 4]
```diff
@@ -0,0 +1,433 @@
...
+        local f = require('fiber').create(function() box.ctl.promote() end)
+        f:set_joinable(true)
+        return f:id()
+    end)
+    server_wait_wal_is_blocked(cg.replica)
+    cg.master:exec(function()
+        require('fiber').create(function() box.space.test:insert{1} end)
+    end)
+    server_wait_synchro_queue_len_is_equal(cg.replica, 1)
+    server_becomes_the_leader_again(cg.master)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:194]: I don't understand why this bumps 'promote greatest term' on the replica. AFAIU replica is still blocked in writing new Term, and the master is the leader with `election_mode='candidate'` anyway. So this call won't bump the term and result in "promote".

I think it would be easier to make the master bump term by first setting `election_mode='off'` and then writing `box.ctl.demote()` on it.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 5]
```diff
@@ -0,0 +1,433 @@
...
+        f:set_joinable(true)
+        return f:id()
+    end)
+    server_wait_wal_is_blocked(cg.replica)
+    cg.master:exec(function()
+        require('fiber').create(function() box.space.test:insert{1} end)
+    end)
+    server_wait_synchro_queue_len_is_equal(cg.master, 1)
+    server_wait_synchro_queue_len_is_equal(cg.replica, 1)
+    cg.master_proxy:pause()
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:406]: This test really passes almost every time.

My idea was that `proxy:pause()` doesn't work right away. So I did this:
```diff
@@ -404,6 +406,11 @@ g.test_new_synchronous_transactions_appeared_while_wait_quorum = function(cg)
     server_wait_synchro_queue_len_is_equal(cg.master, 1)
     server_wait_synchro_queue_len_is_equal(cg.replica, 1)
     cg.master_proxy:pause()
+    t.helpers.retrying({timeout=5}, function() cg.replica:exec(function()
+        local status = box.info.replication[1].upstream.status
+        require'log'.info(require'json'.encode(box.info.replication))
+        t.assert(status ~= 'follow')
+    end) end)
     cg.master:exec(function()
         require('fiber').create(function() box.space.test:insert{2} end)
     end)
```

Now the test started failing when master waits for synchro queue len to become 2. Master's logs contain:
```
2023-10-11 12:47:07.503 [39726] main/111/applier/unix/:/tmp/t/001_replication-luatest/               replica_proxy.sock I> can't read row
  61 2023-10-11 12:47:07.503 [39726] main/111/applier/unix/:/tmp/t/001_replication-luatest/               replica_proxy.sock coio.c:296 E> TimedOut: timed out
  62 2023-10-11 12:47:07.503 [39726] main/111/applier/unix/:/tmp/t/001_replication-luatest/               replica_proxy.sock I> will retry every 0.10 second
  63 2023-10-11 12:47:07.503 [39726] main/111/applier/unix/:/tmp/t/001_replication-luatest/               replica_proxy.sock raft.c:1221 W> RAFT: resigning from leader state
  64 2023-10-11 12:47:07.564 [39726] relay/unix/:(socket)/101/main coio.c:296 E> TimedOut: timed out
  65 2023-10-11 12:47:07.564 [39726] relay/unix/:(socket)/101/main I> exiting the relay loop
  66 2023-10-11 12:47:07.596 [39726] main/124/lua box.cc:355 E> ER_READONLY: Can't modify data on a       read-only instance - state is election follower with term 2
  67 2023-10-11 12:47:07.596 [39726] main/124/lua box.cc:355 E> ER_READONLY: Can't modify data on a       read-only instance - state is election follower with term 2
```

It seems master steps down due to fencing. For some reason setting `election_fencing_mode = 'off'` on master didn't help, but I didn't dig into it much.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Some more comments from me

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 6]
```diff
@@ -0,0 +1,433 @@
...
+
+    local f = cg.replica:exec(function()
+        box.error.injection.set('ERRINJ_WAL_DELAY_COUNTDOWN', 0)
+        local f = require('fiber').create(function() box.ctl.promote() end)
+        f:set_joinable(true)
+        return f:id()
+    end)
+    server_wait_wal_is_blocked(cg.replica)
+    cg.master:exec(function()
+        require('fiber').create(function() box.space.test:insert{1} end)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:223]: You're writing on master with quorum 1. The write will succeed right away, no need to create a fiber here.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 7]
```diff
@@ -0,0 +1,433 @@
...
+    end)
+    server_wait_synchro_queue_len_is_equal(cg.replica, 1)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:225]: Besides waiting for synchro queue length to become "1" you should also wait for synchro queue to become "busy".
Otherwise you can't guarantee that "CONFIRM" from master reaches the replica before replica enters `wal_sync()`. And this is critical for this test.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 8]
```diff
@@ -0,0 +1,545 @@
...
+        t.assert_equals(err.type, 'ClientError')
+        t.assert_equals(err.message, 'Instance with replica id 1 '
+            .. 'was promoted first')
+    end, {f})
+    server_wait_synchro_queue_len_is_equal(cg.replica, 0)
+end
+
+g.test_txn_limbo_is_empty_while_wal_sync = function(cg)
+    cg.replica:exec(function()
+        box.error.injection.set('ERRINJ_WAL_SYNC_DELAY', true)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:232]: Same as above

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 9]
```diff
@@ -0,0 +1,545 @@
...
+    end)
+
+    cg.master:exec(function()
+        require('fiber').create(function() box.space.test:insert{1} end)
+    end)
+    server_wait_synchro_queue_len_is_equal(cg.replica, 1)
+
+    local repl = cg.replica:exec(function()
+        local repl = table.copy(box.cfg.replication)
+        box.cfg{replication={repl[1]}}
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:396]: Can you achieve the same by pausing `master_proxy`?

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 10]
```diff
@@ -0,0 +1,545 @@
...
+    end)
+    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
+    cg.replica:exec(function()
+        box.cfg{replication_synchro_quorum=2}
+    end)
+    csw = get_fiber_csw(cg.replica, f)
+    cg.replica:exec(function()
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
+    end)
+    --we need to be sure we entered the box_wait_quorum call
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:462]: Nit: please start comments with a capital letter and end them with a dot.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 11]
```diff
@@ -0,0 +1,545 @@
...
+    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
+    cg.replica:exec(function(f)
+        box.cfg{replication_synchro_quorum=1}
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:465]: Is it necessary to reset the quorum here?

**Review by sergepetrenko — COMMENTED** [review]
Thanks for the fixes!

Looks nice. I only have a couple comments left.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua (hunk 11 above)
Comment (Astronomax) [reply test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:465]: It is unnecessary.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua (hunk 9 above)
Comment (Astronomax) [reply test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua]: Yes, I really can.

**Review by sergepetrenko — APPROVED** [review]
Good job! LGTM.

Next time please attach a diff in a comment when changes are minor. It's much easier to re-check the patch this way.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 12]
```diff
@@ -0,0 +1,525 @@
...
+    end)
+    server_wait_synchro_queue_len_is_equal(cg.replica, 1)
+    local csw = get_fiber_csw(cg.replica, f)
+    cg.replica:exec(function()
+        box.error.injection.set('ERRINJ_WAL_SYNC', true)
+        box.error.injection.set('ERRINJ_WAL_DELAY_COUNTDOWN', 0)
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
+    end)
+    -- We need to be sure we entered the wal_sync call.
+    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
```
Comment (Gerold103) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:172]: This is a very hacky way to rely on the number of yields. Here and in all the other places. `server_wait_fiber_csw_ge_than()` shouldn't really exist unless you are testing something exactly about specific number of yields.

In this particular case it seems you could just wait on the wal becoming blocked, no?

Another approach would be to move `ERRINJ_WAL_SYNC_DELAY` before `cbus_call()` in `wal_sync()` and make it an integer. When 0, it is not used. When you set it to 1 in a test, then it is turned into 2 by `wal_sync()` + it starts waiting. Then in your tests you can do `box.error.injection.set('ERRINJ_WAL_SYNC_DELAY', 1)` and then wait until `box.error.injection.get('ERRINJ_WAL_SYNC_DELAY') == 2`.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 13]
```diff
@@ -0,0 +1,525 @@
+local t = require('luatest')
```
Comment (Gerold103) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:1]: I didn't review the tests in too much detail because I assume it is expected to be merged before Friday to the release, no matter what I say. But I was able to leave a couple of comments which I believe could be useful to make the tests easier to comprehend. Right now they are all quite hard to read unless you are heavily in the context right now. Also due to relying on number of yields performed somewhere inside qsync code they look quite fragile.

See my other comment about the yield counts. And to the tests being hard to understand - it would help to explain in each test case in a comment what are you doing exactly and why. Otherwise from just the test case name it is much harder to find out than it should be.

**Review by Gerold103 — COMMENTED** [review]
Thanks for the patch!

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 14]
```diff
@@ -0,0 +1,525 @@
...
+    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
+    cg.replica:exec(function()
+        box.cfg{replication_synchro_quorum=2}
+    end)
+    csw = get_fiber_csw(cg.replica, f)
+    cg.replica:exec(function()
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
+    end)
+    -- We need to be sure we entered the box_wait_quorum call.
+    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
```
Comment (Astronomax) [inline test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:448]: Here I need to wait until the fiber `f` reaches the `box_wait_quorum()`.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua (hunk 12 above)
Comment (Astronomax) [reply test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:172]: Yes you are right, here I can just use server_wait_wal_is_blocked. But in some tests, I use `server_wait_fiber_csw_ge_than()` to wait until it reaches `box_wait_quorum()`. And I don't know of a way to make sure that out fiber `f` currently staying in `box_wait_quorum()` other than adding another one errinj. I've left a comment below where this happens.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua (hunk 13 above)
Comment (Astronomax) [reply test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua:1]: I've added more comments and also removed `server_wait_fiber_csw_ge_than()` where possible.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua (hunk 12 above)
Comment (Gerold103) [reply test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua]: You can add another errinj similarly to how `ERRINJ_WAL_WRITE_COUNT` works. It doesn't have to an error. It can be a counter which you can fetch in the test. For example, number of fibers inside of `box_wait_quorum()` right now. It will be fully legal and won't introduce any unrealistic errors (or any errors at all).

Comment (Astronomax) [reply test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua]: I did it.
```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 8940153df..4aa8f75fc 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -2404,6 +2404,10 @@ static int
 box_wait_quorum(uint32_t lead_id, int64_t target_lsn, int quorum,
                double timeout)
 {
+#ifndef NDEBUG
+    ++errinj(ERRINJ_WAIT_QUORUM_COUNT, ERRINJ_INT)->iparam;
+#endif
+
        struct box_quorum_trigger t;
        memset(&t, 0, sizeof(t));
        vclock_create(&t.vclock);
diff --git a/src/lib/core/errinj.h b/src/lib/core/errinj.h
index 4e1ec4ea2..61d5bf8f4 100644
--- a/src/lib/core/errinj.h
+++ b/src/lib/core/errinj.h
@@ -170,6 +170,7 @@ struct errinj {
        _(ERRINJ_VY_STMT_ALLOC, ERRINJ_INT, {.iparam = -1})\
        _(ERRINJ_VY_TASK_COMPLETE, ERRINJ_BOOL, {.bparam = false}) \
        _(ERRINJ_VY_WRITE_ITERATOR_START_FAIL, ERRINJ_BOOL, {.bparam = false})\
+       _(ERRINJ_WAIT_QUORUM_COUNT, ERRINJ_INT, {.iparam = 0}) \
        _(ERRINJ_WAL_BREAK_LSN, ERRINJ_INT, {.iparam = -1}) \
        _(ERRINJ_WAL_DELAY, ERRINJ_BOOL, {.bparam = false}) \
        _(ERRINJ_WAL_DELAY_COUNTDOWN, ERRINJ_INT, {.iparam = -1}) \
diff --git a/test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua b/test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua
index 431797957..143efe57d 100644
--- a/test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua
+++ b/test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua
@@ -56,21 +56,18 @@ local function server_becomes_the_leader_again(server)
     end, {prev_cfg})
 end
 
-local function get_fiber_csw(server, fiber_id)
-    return server:exec(function(fiber_id)
-        return require('fiber').find(fiber_id):info().csw
-    end, {fiber_id})
+local function get_wait_quorum_count(server)
+    return server:exec(function()
+        return box.error.injection.get('ERRINJ_WAIT_QUORUM_COUNT')
+    end)
 end
 
-local function server_wait_fiber_csw_ge_than(server, fiber_id, threshold)
-    server:exec(function(fiber_id, threshold, wait_timeout)
-        t.helpers.retrying({timeout = wait_timeout},
-            function(fiber_id, threshold)
-                local f = require('fiber').find(fiber_id)
-                t.assert_ge(f:info().csw, threshold)
-            end,
-        fiber_id, threshold)
-    end, {fiber_id, threshold, wait_timeout})
+local function server_wait_wait_quorum_count_ge_than(server, threshold)
+    server:exec(function(threshold, wait_timeout)
+        t.helpers.retrying({timeout = wait_timeout}, function(threshold)
+            t.assert_ge(box.error.injection.get('ERRINJ_WAIT_QUORUM_COUNT'), threshold)
+        end, threshold)
+    end, {threshold, wait_timeout})
 end
 
 local function server_wait_synchro_queue_is_busy(server)
@@ -367,7 +364,7 @@ g.test_update_greatest_term_while_wait_quorum = function(cg)
         box.error.injection.set('ERRINJ_WAL_DELAY', false)
     end)
     server_wait_wal_is_blocked(cg.replica)
-    local csw = get_fiber_csw(cg.replica, f)
+    local wait_quorum_count = get_wait_quorum_count(cg.replica)
     local ff = require('fiber').create(function()
         cg.replica:exec(function(f)
             box.error.injection.set('ERRINJ_WAL_DELAY', false)
@@ -381,7 +378,7 @@ g.test_update_greatest_term_while_wait_quorum = function(cg)
     end)
     ff:set_joinable(true)
     -- We need to be sure we entered the 'box_wait_quorum' call.
-    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
+    server_wait_wait_quorum_count_ge_than(cg.replica, wait_quorum_count + 1)
     server_becomes_the_leader_again(cg.master)
     server_wait_promote_greatest_term_ge_than(cg.replica, 3)
     -- Replica collects quorum.
@@ -434,7 +431,7 @@ g.test_txn_limbo_is_empty_while_wait_quorum = function(cg)
     cg.master:exec(function()
         box.cfg{replication_synchro_quorum=2}
     end)
-    local csw = get_fiber_csw(cg.replica, f)
+    local wait_quorum_count = get_wait_quorum_count(cg.replica)
     local ff = require('fiber').create(function()
         cg.replica:exec(function(f)
             box.error.injection.set('ERRINJ_WAL_DELAY', false)
@@ -444,7 +441,7 @@ g.test_txn_limbo_is_empty_while_wait_quorum = function(cg)
         end, {f})
     end)
     ff:set_joinable(true)
-    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
+    server_wait_wait_quorum_count_ge_than(cg.replica, wait_quorum_count + 1)
     -- Now the master will send 'CONFIRM'.
     cg.master_proxy:resume()
     server_wait_synchro_queue_len_is_equal(cg.replica, 0)
@@ -545,7 +542,7 @@ g.test_new_synchronous_transactions_appeared_while_wait_quorum = function(cg)
         box.error.injection.set('ERRINJ_WAL_DELAY', false)
     end)
     server_wait_wal_is_blocked(cg.replica)
-    local csw = get_fiber_csw(cg.replica, f)
+    local wait_quorum_count = get_wait_quorum_count(cg.replica)
     local ff = require('fiber').create(function()
         cg.replica:exec(function(f)
             box.error.injection.set('ERRINJ_WAL_DELAY', false)
@@ -557,7 +554,7 @@ g.test_new_synchronous_transactions_appeared_while_wait_quorum = function(cg)
         end, {f})
     end)
     ff:set_joinable(true)
-    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
+    server_wait_wait_quorum_count_ge_than(cg.replica, wait_quorum_count + 1)
     -- Now the master will send the second insert transaction.
     cg.master_proxy:resume()
     server_wait_synchro_queue_len_is_equal(cg.replica, 2)
```

**Review by Gerold103 — APPROVED** [review]
Thanks for the fixes!

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua (hunk 12 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua]: Resolving since @Gerold103 approved the PR.

File: test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua [hunk 15]
```diff
@@ -0,0 +1,570 @@
...
+            t.assert(not ok)
+            t.assert_equals(err.type, 'ClientError')
+            local master_id = box.info.replication[1].id
+            t.assert_equals(err.message, 'Instance with replica id '
+                .. master_id .. ' was promoted first')
+        end, {f})
+    end)
+    ff:set_joinable(true)
+    -- We need to be sure we entered the box_wait_quorum call.
+    server_wait_fiber_csw_ge_than(cg.replica, f, csw + 1)
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply test/replication-luatest/gh_7318_box_wait_limbo_acked_test.lua]: Resolving since the PR's approved.

**Review by ylobankov — APPROVED** [review]

**Comment by sergepetrenko** [comment]
Cherry-picked to 2.11: a44ed8cfff8bf6561d356fef65979408ae6910d0
Will cherry-pick to 2.10 in scope of https://github.com/tarantool/tarantool/pull/9327
