### PR TITLE
memtx: fix logic of read tracker rebinding during rollback

### LINKED ISSUE #7828: Phantom read after `get`s from different indexes
**Steps to reproduce**

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local json = require('json')
local log = require('log')
local txn_proxy = require('txn_proxy')

box.cfg{memtx_use_mvcc_engine = true}

box.schema.space.create('s')
box.space.s:create_index('pk')
box.space.s:create_index('sk', {parts = {{2}}})

local tx1 = txn_proxy:new()
local tx2 = txn_proxy:new()
local tx3 = txn_proxy:new()

tx1('box.begin()')
tx2('box.begin()')
tx3('box.begin()')

tx1('box.space.s:replace{0, 1}')

tx2('box.space.s.index[1]:get{1}')
tx2('box.space.s:get{0}')

tx3('box.space.s:insert{1, 1}')

tx1('box.rollback()')

box.space.s:insert{0, 2}

log.info(json.encode(tx2('box.space.s:select({}, {fullscan = true})')))

os.exit()
```

**Actual behavior**

```console
2022-10-20 11:50:57.427 [3180] main/103/repro.lua I> ""
2022-10-20 11:50:57.427 [3180] main/103/repro.lua I> [[]]
2022-10-20 11:50:57.427 [3180] main/103/repro.lua I> [[[0,0]]]
```

**Expected behavior**

```console
2022-10-20 11:50:57.427 [3180] main/103/repro.lua I> ""
2022-10-20 11:50:57.427 [3180] main/103/repro.lua I> [[]]
2022-10-20 11:50:57.427 [3180] main/103/repro.lua I> [[]]
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
During rollback read trackers are rebound to newer or older story, if
present. The problem with the current logic is that read trackers are
basically rebound in the first available index: all information about key
parts read from other indexes gets lost — rebind read trackers in all
indexes.

Closes #7828

NO_DOC=bugfix

### CODE REVIEW

**Comment by CuriousGeorgiy** [comment]
# :bangbang: ATTENTION :bangbang:

@alyapunov @drewdzzz  please note that the first commit comes from #7758: we need to merge it first, otherwise the test in the second commit (which is the scope of this PR) will fail.

File: src/box/memtx_tx.c [hunk 1]
```diff
@@ -1234,8 +1234,6 @@ memtx_tx_story_unlink_both_on_rollback(struct memtx_story *story, uint32_t idx)
 			memtx_tx_track_read_story_slow(tracker->reader,
```
Comment (drewdzzz) [inline src/box/memtx_tx.c:1234]: By the way, the function has a bad comment:
*As opposed to `memtx_tx_story_unlink_both_on_rollback`*

**Review by drewdzzz — APPROVED** [review]
LGTM, nit only

File: src/box/memtx_tx.c (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tx.c:1234]: Fixed the typo, thanks!

**Comment by alyapunov** [comment]
Backported to 2.10.
