### PR TITLE
vinyl: use broadcast instead of signal to notify about dump completion

### LINKED ISSUE #10233: Fiber hangs while executing snapshot concurrently with vinyl index build
**Bug description**

If vinyl index build and snapshot are executed concurrently, one of them may hang.

Originally reported by @ligurio.

Reproduced with Tarantool 3.2.0-entrypoint-112-g319357d5973d.

**Steps to reproduce**

Run the script:

```lua
local log = require('log')
local fiber = require('fiber')

box.cfg{}

local s = box.schema.space.create('test', {engine = 'vinyl'})
s:create_index('pk')
s:insert({1, 1})

local f1 = fiber.new(s.create_index, s, 'sk', {parts = {2, 'unsigned'}})
f1:set_joinable(true)

local f2 = fiber.new(box.snapshot)
f2:set_joinable(true)

fiber.sleep(0.1)

local ok, err
local timeout = 3

ok, err = f1:join(timeout)
if not ok then
    log.error('Failed to join ddl fiber')
    box.error(err)
end

ok, err = f2:join(timeout)
if not ok then
    log.error('Failed to join snapshot fiber')
    box.error(err)
end

os.exit(0)
```

**Actual behavior**

The script fails with the error:

```
2024-07-11 17:47:06.763 [76468] main/104/test.lua/test test.lua:33 E> Failed to join snapshot fiber
2024-07-11 17:47:06.763 [76468] main fiber.c:855 E> TimedOut: timed out
```

**Expected behavior**

No error.

### PR DESCRIPTION
**Pull request by locker**
There may be more than one fiber waiting on `vy_scheduler::dump_cond`:

```
box.snapshot
  vinyl_engine_wait_checkpoint
    vy_scheduler_wait_checkpoint

space.create_index
  vinyl_space_build_index
    vy_scheduler_dump
```

To avoid hang, we should use `fiber_cond_broadcast`.

Closes #10233

### CODE REVIEW

File: test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+        s:insert({1, 1})
+        local f1 = fiber.new(s.create_index, s, 'sk', {parts = {2, 'unsigned'}})
+        f1:set_joinable(true)
+        local f2 = fiber.new(box.snapshot)
+        f2:set_joinable(true)
+        fiber.sleep(0.1)
+        local ok, err
+        local timeout = 5
+        ok, err = f1:join(timeout)
+        t.assert_equals(ok or err, true)
```
Comment (nshy) [inline test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua:37]: Nit. Rather cryptic. May be just `t.assert(ok, err)`.

**Review by nshy — APPROVED** [review]

**Review by p7nov — APPROVED** [review]

File: test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua (hunk 1 above)
Comment (locker) [reply test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua]: AFAIU the message shouldn't depend on the test case result so I wouldn't use it. To make the code more straightforward changed to this:

```diff
diff --git a/test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua b/test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua
index ac0691b26a75..3a9ddec74345 100644
--- a/test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua
+++ b/test/vinyl-luatest/gh_10233_index_build_vs_snapshot_test.lua
@@ -26,16 +26,17 @@ g.test_index_build_vs_snapshot = function(cg)
         local s = box.schema.space.create('test', {engine = 'vinyl'})
         s:create_index('pk')
         s:insert({1, 1})
-        local f1 = fiber.new(s.create_index, s, 'sk', {parts = {2, 'unsigned'}})
+        local f1 = fiber.new(function()
+            s:create_index('sk', {parts = {2, 'unsigned'}})
+        end)
         f1:set_joinable(true)
-        local f2 = fiber.new(box.snapshot)
+        local f2 = fiber.new(function()
+            box.snapshot()
+        end)
         f2:set_joinable(true)
         fiber.sleep(0.1)
-        local ok, err
         local timeout = 5
-        ok, err = f1:join(timeout)
-        t.assert_equals(ok or err, true)
-        ok, err = f2:join(timeout)
-        t.assert_equals(ok or err, true)
+        t.assert_equals({f1:join(timeout)}, {true})
+        t.assert_equals({f2:join(timeout)}, {true})
     end)
 end
```

**Comment by locker** [comment]
Cherry-picked to 2.11 and 3.1.
