### PR TITLE
box: fix box.commit({wait = 'none'}) could yield

### LINKED ISSUE #11224: box.commit(wait = 'none') may yield
**Bug description**

`box.commit(wait = 'none')` may yield while is not expected to. The issue on commit we check that queue size is less then limit but there is a gap when we decrease queue size and when waiting fibers are actually poped off the queue.
 
Found in `3.4.0-entrypoint-158-g904e0a702e`.

**Steps to reproduce**

Reproducer script:
```lua
local fiber = require('fiber')
os.execute('rm -f *.snap *.xlog *.vylog')
box.cfg{log_level = 'warn', wal_queue_max_size = 100}
local s = box.schema.create_space('test')
s:create_index('pk')
fiber.create(function()
    box.begin()
    box.on_commit(function()
        fiber.new(function()
            box.begin()
            s:insert({3})
            print(fiber.self().info().csw)
            box.commit({wait = 'none'})
            print(fiber.self().info().csw)
        end)
    end)
    s:insert({1, string.rep('a', 1000)})
    box.commit()
end)
s:insert({2})
os.exit()
```

**Actual behavior**

The script prints:
```
0
1
```

**Expected behavior**

The `box.commit({wait = 'none'}) ` should fail because the txn can not be send to WAL immeditately.

### PR DESCRIPTION
**Pull request by nshy**
The issue is in order to decide whether submitting request to journal would yield or not we check the journal queue size. But the size can be less then limit while queue is not empty. At this moment submitting new request will yield.

Closes #11224

### CODE REVIEW

File: test/box-luatest/gh-11224_fix_commit_wait_none_journal_queue_test.lua [hunk 1]
```diff
@@ -0,0 +1,60 @@
+local server = require('luatest.server')
```
Comment (sergepetrenko) [inline test/box-luatest/gh-11224_fix_commit_wait_none_journal_queue_test.lua:1]: Nit: we usually name tests starting with `gh_`, not `gh-`.

**Review by sergepetrenko — APPROVED** [review]
Thanks for finding and fixing this!
LGTM.

**Comment by sergepetrenko** [comment]
Let's also ask @Gerold103 to take a look.

**Review by maryiaLichko — APPROVED** [review]

File: src/box/journal.h [hunk 2]
```diff
@@ -188,19 +188,12 @@ void
...
-static inline bool
-journal_queue_is_full(void)
-{
-	return journal_queue.size >= journal_queue.max_size;
-}
-
-/** Yield until there's some space in the journal queue. */
 int
-journal_queue_wait(struct journal_entry *entry);
+journal_queue_wait(struct journal_entry *entry, bool no_wait);
```
Comment (Gerold103) [inline src/box/journal.h:196]: The API of sort `wait(bool no_wait)` looks not really good. Please, lets find a way to check for the potential waiting explicitly in the calling code.

Like add a method like `journal_queue_would_block()` which checks for the size + request queue being non-empty.

Alternatively I could suggest to add a new enum for `journal.h` like `enum journal_submit_mode { JOURNAL_SUBMIT_MODE_WAIT, JOURNAL_SUBMIT_MODE_NO_WAIT; }` instead of a flag and you would then translate txn wait mode into the journal wait mode. This magic true/false in the code is really bothering.

**Review by Gerold103 — COMMENTED** [review]
Thanks for the patch! Huh, it was really an unexpected bug in such a simple place!

File: src/box/journal.h (hunk 2 above)
Comment (nshy) [reply src/box/journal.h:196]: These solutions looks more heavy to me, especially the second. So I'll try the first one.

File: test/box-luatest/gh-11224_fix_commit_wait_none_journal_queue_test.lua (hunk 1 above)
Comment (nshy) [reply test/box-luatest/gh-11224_fix_commit_wait_none_journal_queue_test.lua:1]: Fixed.

**Review by Gerold103 — APPROVED** [review]
Thank you, @nshy! The test is especially clean and nice, I like it ❤️.
