### PR TITLE
lua/merger: fix use-after-free during iteration

### LINKED ISSUE #7657: merger: merge source handle is freed during :pairs() traversal
Tarantool versions: 2.7.3, 2.8.3, 2.8.4, 2.10.0, 2.10.2, 2.11.0-entrypoint-446-ga6b48f143 (current master) -- it seems, all versions are affected.

https://github.com/tarantool/tuple-merger is affected as well.

## How the problem was observed

The problem revelas on the following code that uses https://github.com/tarantool/crud:

```lua
crud.pairs(<...>):length()
```

Everything was ok until data grow beyond some threshold: around 230K tuples in the space. The setup: singleton replicaset (all virtual buckets are on one replicaset).

## Recommended workarounds

I have workarounds for crud module users:

1. Preferable: update to a recent crud module and use `crud.len()`. crud supports it since 0.9.0, but I suggest to use more fresh version: it is 0.13.0 ATM.
2. Use crud's built-in merger (pure Lua implementation, may be slower). Add `package.loaded.merger = nil` into the application initialization code as early as possible (before crud is required and before cartridge is configured). Ensure that there is no tuple-merger module installed.

## How to reproduce

```lua
#!/usr/bin/env tarantool

local merger = require('merger')

local iter = 1

local function fetch_chunk(context, state)
    if iter >= 7000 then
        return
    end

    local data = {}
    for i = 1, 2 do
        table.insert(data, {iter, tostring(iter)})
        iter = iter + 1
    end
    return {}, data
end

local function mr_call()
    local source = merger.new_table_source(fetch_chunk, {}, {})
    return source:pairs():length()
end

print(mr_call())
os.exit()
```

Expected output:

```
7000
```

Actual output:

```c
Segmentation fault
<...>
#1  0x5d25d1 in crash_signal_cb+177
#2  0x7f888aecdb20 in __restore_rt+0
#3  0x5addb3 in lbox_merge_source_gen+147
#4  0x610c73 in lj_BC_FUNCC+70
#5  0x61572c in lua_pcall+124
#6  0x5bc1ff in luaT_call+15
#7  0x5b4a19 in lua_main+89
#8  0x5b4dd7 in run_script_f+919
#9  0x41cfe0 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+16
#10 0x5d9510 in fiber_loop+48
#11 0x83a8b8 in coro_init+72
Aborted (core dumped)
```

## Investigation

The following patch add related debug prints and allows to look what is going on:

```diff
diff --git a/src/box/lua/merger.c b/src/box/lua/merger.c
index 91a77b2ae..50ccf5ba0 100644
--- a/src/box/lua/merger.c
+++ b/src/box/lua/merger.c
@@ -238,6 +238,7 @@ static int
 lbox_merge_source_gc(struct lua_State *L)
 {
 	struct merge_source *source = luaT_check_merge_source(L, 1);
+	fprintf(stderr, "DEBUG: merge source %p gc is called\n", source);
 	assert(source != NULL);
 	merge_source_unref(source);
 	return 0;
diff --git a/third_party/luafun/fun.lua b/third_party/luafun/fun.lua
index 2427bb2..00d8b5a 100644
--- a/fun.lua
+++ b/fun.lua
@@ -605,7 +605,9 @@ local length = function(gen, param, state)
     repeat
         state = gen(param, state)
         len = len + 1
+        io.stderr:write('DEBUG: fun.length: ' .. tostring(len - 1) .. '\n')
     until state == nil
+    io.stderr:write('DEBUG: fun.length (retval): ' .. tostring(len - 1) .. '\n')
     return len - 1
 end
 methods.length = method0(length)
```

With the prints the output looks so:

```c
<...>
DEBUG: fun.length: 5309
DEBUG: fun.length: 5310
DEBUG: fun.length: 5311
DEBUG: merge source 0x5633063baa20 gc is called
DEBUG: fun.length: 5312
Segmentation fault
<...>
```

An implementation of the `<merge source>:pairs()` method is the following:

https://github.com/tarantool/tarantool/blob/a6b48f143b73be36464e840c90f32b7f14e6e3a0/src/box/lua/merger.c#L1051-L1092

I see nothing criminal here: `gen` accepts the merge source as a parameter, so it is impossible to loss the merge source somehow and correctly call `gen`.

Other observations:

* `jit.off()` does not make a difference.
* The following patch breaks the reproducer:

  ```diff
  --- repro.lua	2022-09-06 22:56:02.846587936 +0300
  +++ not-repro.lua	2022-09-06 22:55:59.442587758 +0300
  @@ -19,7 +19,8 @@
   
   local function mr_call()
       local source = merger.new_table_source(fetch_chunk, {}, {})
  -    return source:pairs():length()
  +    local res = source:pairs():length()
  +    return res
   end
   
   print(mr_call())
  ```

  Maybe some effects similar to described in 964989765eda1b629bd937f7fbe9f88b13705099 are matter here.

I would like @igormunkin's or @Buristan's glance on this code to diagnose whether merger makes something improperly or LuaJIT actually fires the GC callback prematurely.

### PR DESCRIPTION
**Pull request by Totktonada**
All merge sources (including the merger itself) share the same `<merge source>:pairs()` implementation, which returns `gen, param, state` triplet. `gen` is `lbox_merge_source_gen()`, `param` is `nil`, `state` in the merge source.

The `lbox_merge_source_gen()` returns `source, tuple`. The returned source is supposed to be the same object as one passed to the function (`gen(param, state)`), so the function assumes the object as alive and don't increment source's refcounter at entering, don't decrease it at exitting.

This logic is perfect, but there was a mistake in the implementation: the function returns a new cdata object (which holds the same pointer to the merge source structure) instead of the same cdata object.

The new cdata object neither increases the source's refcounter at pushing to Lua, nor decreases it at collecting. At result, if we'll loss the original merge source object (and the first `state` that is returned from `:pairs()`), the source structure may be freed. The pointer in the new cdata object will be invalid so.

A sketchy code that illustrates the problem:

```lua
gen, param, state0 = source:pairs()
assert(state0 == source)
source = nil
state1, tuple = gen(param, state0)
state0 = nil
-- assert(state1 == source) -- would fails
collectgarbage()
-- The cdata object that is referenced as `source` and as `state`
-- is collected. The GC handler is called and dropped the merge
-- source structure refcounter to zero. The structure is freed.
-- The call below will crash.
gen(param, state1)
```

In the fixed code `state1 == source`, so the GC handler is not called prematurely: we have the merge source object alive till end of the iterator or till stop of the traveral.

Fixes #7657

### CODE REVIEW

File: test/box-luatest/gh_7657_merger_use_after_free_in_gen_test.lua [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+    --
+    -- The fixed code returns the same cdata object, so `state`
+    -- remains the same. The reference isn't lost.
+    local tuple
+    state, tuple = gen(param, state)
+    t.assert_equals(tuple, {1, '1'})
+
+    -- Loss the second reference to the merge source object. If it
+    -- is the last reference to this cdata object in Lua, the GC
+    -- handler will be called and will desrease the refcounter in
```
Comment (Buristan) [inline test/box-luatest/gh_7657_merger_use_after_free_in_gen_test.lua:45]: Typo: s/desrease/decrease/

File: test/box-luatest/gh_7657_merger_use_after_free_in_gen_test.lua [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+    -- the merge source structure to zero, The structure is freed
```
Comment (Buristan) [inline test/box-luatest/gh_7657_merger_use_after_free_in_gen_test.lua:46]: Typo: s/,/./

File: test/box-luatest/gh_7657_merger_use_after_free_in_gen_test.lua [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+    -- in the case.
```
Comment (Buristan) [inline test/box-luatest/gh_7657_merger_use_after_free_in_gen_test.lua:47]: Minor: s/the/this/
Fill free to ignore.

**Review by Buristan — APPROVED** [review]
Hi, Alexander!
Thanks for the patch!

LGTM, except a few insignificant nits below.

> source is supposed to be the same object as one passed to the function

Typo: s/as one passed/as the one passed/

> The new cdata object neither increases the source's refcounter at

Typo: s/object neither/object, neither/

> prematurely: we have the merge source object alive till end of the

Typo: s/till end/till the end/

**Review by igormunkin — APPROVED** [review]
@Totktonada, thanks for the fix! LGTM.

**Comment by igormunkin** [comment]
Also backported to 2.10 in scope of f9aecfb (2.10.2-16-gf9aecfb81).
