### PR TITLE
net.box: add info about sequence to remote space object

### LINKED ISSUE #7858: Unable to check if index uses sequence through net.box
**Bug description**

net.box connection object does not provide any info about using sequence.

Related to https://github.com/tarantool/crud/issues/328

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool 2.10.0-beta2-283-gb56e012bc

**Steps to reproduce**

`init.lua` script:

```lua
local log = require('log')

box.cfg{listen = 3301}

box.schema.user.grant('guest', 'read,write,execute', 'universe')

local sequence_space = box.schema.space.create('space', {
    format = {
        {name = 'id', type = 'unsigned', is_nullable = false},
    },
})

box.schema.sequence.create('id')

sequence_space:create_index('id', {
    parts = { {field = 'id'} },
    unique = true,
    sequence = 'id',
})

log.info("Index with sequence: %s", box.space['space'].index['id'].sequence_id ~= nil)
```

`remote.lua` script:

```lua
local log = require('log')
local net_box = require('net.box')

local conn = net_box.connect(3301)

log.info("Index with sequence: %s", conn.space['space'].index['id'].sequence_id ~= nil)
```

Run `tarantool init.lua` in one console.
Run `tarantool remote.lua` in another console.

**Actual behavior**

Server (`init.lua`) output:
```
Index with sequence: true
```

Client (`remote.lua`) output:
```
Index with sequence: false
```

**Expected behavior**

Server (`init.lua`) output:
```
Index with sequence: true
```

Client (`remote.lua`) output:
```
Index with sequence: true
```

### PR DESCRIPTION
**Pull request by locker**
A remote space object presented by a net.box connection mimics the API of a local space object presented by box.space. Currently, it misses information about sequences. Let's add it.

To achieve that, we also need to add the `_vspace_sequence` system space view of the `_space_sequence` system space.

Closes #7858

### CODE REVIEW

File: test/box-luatest/gh_7858_net_box_space_sequence_test.lua [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+        t.assert_equals(conn.space.test3.index.pk.sequence_fieldno, 2)
+        t.assert_equals(conn.space.test3.index.pk.sequence_path, '.foo.bar')
+        t.assert_equals(conn.space.test3.index.sk.sequence_id, nil)
+        t.assert_equals(conn.space.test3.index.sk.sequence_fieldno, nil)
+        t.assert_equals(conn.space.test3.index.sk.sequence_path, nil)
+        conn:close()
+    end)
+end
+
+local g_old_schema = t.group('gh_7858_net_box_space_sequence.old_schema')
```
Comment (nshy) [inline test/box-luatest/gh_7858_net_box_space_sequence_test.lua:74]: Nit: I saw a trick with just setting `g` to the new value without introducing new variable.

**Review by nshy — APPROVED** [review]

File: test/box-luatest/gh_7858_net_box_space_sequence_test.lua (hunk 1 above)
Comment (locker) [reply test/box-luatest/gh_7858_net_box_space_sequence_test.lua:74]: I used to do that, but now I think that it's better to give test groups proper names, because it makes it easier for a human to analyze the test code IMO.

**Comment by locker** [comment]
**NOTE** I had to create the [2.10.5-entrypoint](https://github.com/tarantool/tarantool/releases/tag/2.10.5-entrypoint) dummy tag to make the tests pass, because net.box now assumes that `_vspace_sequence` is available starting from 2.10.5 and doesn't try to fetch it if the remote version is less. The tag is invisible to users. It's needed solely to bump the version of 2.10 branch from 2.10.4 to yet unreleased 2.10.5.
