### PR TITLE
vinyl: optimize deletion of compacted run files

### LINKED ISSUE #6568: vinyl: replica's initial join consumes much more disk space
There's a tarantool server in production with a large vinyl space (300GB) in it. The problem happens when we try to join a replica to the cluster. It consumes all available disk space (1TB) and fails to start because of disk error. I saw a lot of message in log about started and successfully finished compaction.

There's also was a lot of rumors that vinyl replica join is very slow (in particular it progressively slows down during join process). It seems for me that it can be connected with the subject.

I don't much about that installation, but I know whom to ask, if something would be important. On that instance `vinyl_memory` was set to 4 gigabytes.
<details>
<summary>Here's the space definition</summary>

```
---
- engine: vinyl
  before_replace: 'function: 0x40615e98'
  field_count: 0
  is_sync: false
  ck_constraint: []
  on_replace: 'function: 0x40615d78'
  temporary: false
  index:
    0: &0
      parts:
      - type: integer
        is_nullable: false
        fieldno: 1
      sequence_id: 1
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      space_id: 515
      unique: true
      type: TREE
      sequence_fieldno: 1
      name: PK
      id: 0
    1: &1
      unique: true
      parts:
      - type: string
        is_nullable: true
        fieldno: 2
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      id: 1
      space_id: 515
      type: TREE
      name: IX_guid
    2: &2
      unique: true
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: string
        is_nullable: true
        fieldno: 4
      id: 2
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      space_id: 515
      type: TREE
      name: IX_ch_uid
    3: &3
      unique: false
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: integer
        is_nullable: false
        fieldno: 8
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      id: 3
      space_id: 515
      type: TREE
      name: IX_ch_status
    4: &4
      unique: false
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: string
        is_nullable: false
        fieldno: 5
      - type: integer
        is_nullable: false
        fieldno: 8
      id: 4
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      space_id: 515
      type: TREE
      name: IX_chp_status
    5: &5
      unique: false
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: string
        is_nullable: false
        fieldno: 5
      - type: number
        is_nullable: false
        fieldno: 6
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      id: 5
      space_id: 515
      type: TREE
      name: IX_chp_counter
    6: &6
      unique: false
      parts:
      - type: string
        is_nullable: false
        fieldno: 3
      - type: string
        is_nullable: false
        fieldno: 5
      id: 6
      options:
        page_size: 8192
        run_count_per_level: 2
        run_size_ratio: 3.5
        bloom_fpr: 0.05
        range_size: 1073741824
      space_id: 515
      type: TREE
      name: IX_chp
    IX_channelId_uid: *2
    PK: *0
    IX_channelId_phone_status: *4
    IX_channelId_phone: *6
    IX_channelId_status: *3
    IX_guid: *1
    IX_channelId_phone_counter: *5
  is_local: false
  enabled: true
  name: table_name
  id: 515
```
</details>

We should try to reproduce and investigate the problem.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
On completion of compaction tasks we remove compacted run files created
after the last checkpoint immediately to save disk space. In order to perform this
optimization we compare the unused runs' dump LSN with the last
checkpoint's one.

But during replica's initial JOIN stage we set the LSN of all rows
received from remote master to 0 (see
box/box.cc/boostrap_journal_write). Considering that the LSN of an
initial checkpoint is also 0, our optimization stops working, and we
receive a huge disk space usage spike (as the unused run files will
only get removed when garbage collection occurs).

We should check the vinyl space engine's status and perform
our optimization unconditionally if we are in replica's initial JOIN
stage.

Closes #6568

### CODE REVIEW

File: test/vinyl-luatest/gh_6568_test.lua [hunk 1]
```diff
@@ -0,0 +1,82 @@
+local cluster = require('test.luatest_helpers.cluster')
```
Comment (locker) [inline test/vinyl-luatest/gh_6568_test.lua:1]: 1. We usually name tests so that it's clear what it does, e.g. `gh_5568_read_only_reason_test.lua`. Please rename.
2. The test takes too long to complete (~30 seconds). Please try to reduce the test run time down to 3-5 seconds max.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/vy_scheduler.c [hunk 2]
```diff
@@ -426,14 +427,15 @@ void
 vy_scheduler_create(struct vy_scheduler *scheduler, int write_threads,
 		    vy_scheduler_dump_complete_f dump_complete_cb,
 		    struct vy_run_env *run_env, struct rlist *read_views,
-		    struct vy_quota *quota)
+		    struct vy_quota *quota, struct vy_env *env)
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/box/vy_scheduler.c]: Fixed: added a boolean flag to `vy_run_env` to determine we are in an initial JOIN.

File: test/vinyl-luatest/suite.ini [hunk 3]
```diff
@@ -0,0 +1,3 @@
+[default]
+core = luatest
+description = vinyl space engine luatests
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply test/vinyl-luatest/suite.ini:3]: Fixed: enabled parallel test run for this suite.

File: test/vinyl-luatest/gh_6568_test.lua (hunk 1 above)
Comment (CuriousGeorgiy) [reply test/vinyl-luatest/gh_6568_test.lua]: 1. Thought it would be be better for the sake of brevity to keep the details out of the way (IMO, people still go look up the corresponding issue). Fixed: provided a brief description in the test name.

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+
+    local master_run_files_sz = run_files_sz(master_vinyl_dir)
+    local replica_run_files_sz = run_files_sz(replica_vinyl_dir)
+    local sz_diff = replica_run_files_sz - master_run_files_sz
+    local msg = 'the total size of run files directories of master and' ..
+                'replica must not differ by more than %.1f%%'
+    local perm_rel_sz_diff = 0.5
+    msg = msg:format(perm_rel_sz_diff * 100)
+    t.assert_le(sz_diff / master_run_files_sz, perm_rel_sz_diff, msg)
+end
```
Comment (locker) [inline test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:82]: The test is flaky:

```
$ yes vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua | head -n100 | xargs ./test-run.py
...
Statistics:
* pass: 28
* fail: 1
Failed tasks:
- [vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua,
  null]
```

Please fix. Maybe, instead of checking that the number of files on the replica is roughly the same as the number of files on the master, you could just check that all garbage files have been removed? E.g. by comparing `index:stat().run_count` with the number of run files on disk. Then you wouldn't need to limit memory on the master, which would also speed up the test.

Also, 10 seconds is still too long. If you can't reduce the test run time down to a couple of seconds, you should mark it as long (`long_run` in `suite.ini`), but better speed it up even more, of course.

**Review by locker — CHANGES_REQUESTED** [review]

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua (hunk 4 above)
Comment (CuriousGeorgiy) [reply test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:91]: Fixed: changed the test log. Now we create a space with large tuples, pass vinyl_memory approximately the size enough to hold one tuple, and fill the space with a number of tuples enough for the disk usage overhead without our patch to prove by comparing the total *.run files size with box.stat.vinyl().disk.data.

The test works 3 seconds on my local machine.

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+
+local s_id = 0
+g.before_all(function()
+    local helpers = require('test.luatest_helpers')
+
+    g.cluster = cluster:new({})
+
+    local master_uri = helpers.instance_uri('master')
+    local master_box_cfg = {
+        checkpoint_count = 1,
```
Comment (locker) [inline test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:15]: No need to set `checkpoint_count` AFAIU.

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+        local s = box.schema.space.create('test', {engine = 'vinyl'})
+        s:format({{name = '1', type = 'number'},
+                  {name = '2', type = 'number'},
+                  {name = '3', type = 'number'},
+                  {name = '4', type = 'number'},
+                  {name = '5', type = 'number'},
+                  {name = '6', type = 'number'},
+                  {name = '7', type = 'number'},
+                  {name = '8', type = 'number'}
+                 })
```
Comment (locker) [inline test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:43]: No need to set format - it'll work just fine without it.

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+        s:create_index('primary')
+
+        for i = 1, 64 do s:insert{i, 1e15, 1e15, 1e15, 1e15, 1e15, 1e15, 1e15} end
```
Comment (locker) [inline test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:46]: You could use a string for padding:

```lua
for i = 1, 64 do s:insert{i, string.rep('x', 100)} end
```

**Review by locker — APPROVED** [review]
LGTM. Please see a few minor comments re the test.

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua (hunk 5 above)
Comment (CuriousGeorgiy) [reply test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:15]: @locker following our test logic, during the replica's initial 'JOIN' stage, we want the snapshot fetched from master to be the one containing the inserted rows: otherwise, the replica will receive the boostrap snapshot, and only receive the 'insert' during the final 'JOIN' stage.

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua (hunk 6 above)
Comment (CuriousGeorgiy) [reply test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:43]: Fixed: did not know about this feature.

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua (hunk 7 above)
Comment (CuriousGeorgiy) [reply test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:46]: Fixed: that's a really elegant approach, did not think about that – thank you for sharing.

File: test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua (hunk 5 above)
Comment (locker) [reply test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua:15]: Starting from commit 6332aca655ae7f95d391bdc0109e79915f6e6ad0, Tarantool sends data from a read view during initial join, not from the last snapshot, so whether you have a snapshot on the master or not doesn't matter, see

https://github.com/tarantool/tarantool/blob/e8765ba5cbd73ebb178459b008a9068ba25f98e2/src/box/vinyl.c#L3734-L3764

https://github.com/tarantool/tarantool/blob/e8765ba5cbd73ebb178459b008a9068ba25f98e2/src/box/vinyl.c#L3013-L3037

That is, in your case there will only be the initial join phase (no final join), no matter whether you create a snapshot or not; you just need to create a replica after you populated the test space.

Comment (CuriousGeorgiy) [reply test/vinyl-luatest/gh_6568_replica_initial_join_deletion_of_compacted_run_files_test.lua]: Fixed: thank you for pointing that out to me, did not know about the read view.
