### PR TITLE
console: make __autocomplete retrival for cdata exception-safe

### LINKED ISSUE #9828: Tarantool crashes when pressing `Tab`
Reproducer: start Tarantool interactively and type `box.`:
```
mergen@mega:~/work/ee/tarantool/src$ ./tarantool -i
Tarantool 3.1.0-entrypoint-160-g40bd0eb1a
type 'help' for interactive help
tarantool> box.
```

Then press `Tab`. The result is:
```
mergen@mega:~/work/ee/tarantool/src$ ./tarantool -i
Tarantool 3.1.0-entrypoint-160-g40bd0eb1a
type 'help' for interactive help
ER_UNCONFIGURED: Please call box.cfg{} first
fatal error, exiting the event loop
tarantool> box.mergen@mega:~/work/ee/tarantool/src$ 
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Fixes a regression introduced in cf644abd, which added exception-unsafe code for retrieval of `__autocomplete` metamethod of cdata objects.

I wasn't able to test the orginal reported bug, since the luatest server starts with `box` configured.

Closes #9828

### CODE REVIEW

File: src/box/lua/console.c [hunk 1]
```diff
@@ -1116,8 +1120,14 @@ lua_rl_getcompletion(lua_State *L)
...
 		 * metatable.
 		 */
+		lua_rawgeti(L, LUA_REGISTRYINDEX, gettable_ref);
+		lua_pushvalue(L, -3);
 		lua_pushstring(L, "__autocomplete");
-		lua_gettable(L, -3);
+		if (lua_pcall(L, 2, 1, 0) != 0) {
+			/* pcall returns an error to the stack */
+			lua_pushnil(L);
+			lua_replace(L, -2);
```
Comment (nshy) [inline src/box/lua/console.c:1129]: Nit: looks like easier to pop error and then push nil.

File: src/box/lua/console.c [hunk 2]
```diff
@@ -1116,8 +1120,14 @@ lua_rl_getcompletion(lua_State *L)
...
+		}
```
Comment (nshy) [inline src/box/lua/console.c:1130]: I guess we'd better `return 0` as in case of `__autocomple` function error for consitency. We don't need to fallback to pass the test.

**Review by nshy — CHANGES_REQUESTED** [review]

File: src/box/lua/console.c (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/lua/console.c:1130]: Okay, let's do it this way.

File: src/box/lua/console.c (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/lua/console.c:1129]: I thought that this variant of stack manipulation is slightly more efficient.

**Review by nshy — APPROVED** [review]

File: src/box/lua/console.c [hunk 3]
```diff
@@ -983,6 +984,9 @@ tarantool_lua_console_init(struct lua_State *L)
 	console_hide_prompt_ref = luaL_ref(L, LUA_REGISTRYINDEX);
 	lua_pushcfunction(L, lbox_console_show_prompt);
 	console_show_prompt_ref = luaL_ref(L, LUA_REGISTRYINDEX);
+
+	VERIFY(luaT_dostring(L, "return function(t, k) return t[k] end") == 0);
```
Comment (Gumix) [inline src/box/lua/console.c:988]: I'd drop a comment here to explain what does it verify and why.

File: test/app-luatest/gh_6305_autocomplete_metamethod_test.lua [hunk 4]
```diff
@@ -58,6 +58,12 @@ g.test__autocomplete = function()
                                                    'table11.second',
                                                    'table11.auto',
                                                    })
+    -- __index function can throw an error - should be Ok
+   setmetatable(tab, {__index = function() error('test error') end})
```
Comment (Gumix) [inline test/app-luatest/gh_6305_autocomplete_metamethod_test.lua:62]: Nit: Bad alignment.

**Review by Gumix — APPROVED** [review]

File: src/box/lua/console.c (hunk 3 above)
Comment (CuriousGeorgiy) [reply src/box/lua/console.c:992]: It's just a sanity check that the compilation is successful, not really meaningful. Anyways, dropped a comment here.
