### PR TITLE
memtx: fix tree iterator `next` result clarification

### LINKED ISSUE #7432: `select` with reverse iterator in memtx TREE index returns deleted tuple
**Steps to reproduce**

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local ffi = require('ffi')
local json = require('json')
local log = require('log')
local txn_proxy = require('txn_proxy')

box.cfg{memtx_use_mvcc_engine = true}

local s = box.schema.space.create('s')
s:create_index('pk')

s:insert{0}
s:insert{1}

box.internal.memtx_tx_gc(100)

s:delete{0}

local tx = txn_proxy:new()
tx:begin()
log.info("%s", json.encode(tx("box.space.s:select({1}, {iterator = 'LE', fullscan = true})")))

os.exit()
```

**Actual behavior**

```console
[[[1],[0]]]
```

**Expected behavior**

```console
[[[1]]]
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
The problem is described in #7073. It was fixed only for
`tree_iterator_start_raw` next method, but other methods used for reverse
iterators are also subject to this bug: move tuple clarification from the
wrapper of iterator `next` methods to individual iterator methods.

Closes #7432

### CODE REVIEW

File: src/box/memtx_tree.cc [hunk 1]
```diff
@@ -542,27 +570,12 @@ template <bool USE_HINT>							\
 static int									\
 name(struct iterator *iterator, struct tuple **ret)				\
 {										\
-	memtx_tree_t<USE_HINT> *tree =						\
-		&((struct memtx_tree_index<USE_HINT> *)iterator->index)->tree;	\
 	struct tree_iterator<USE_HINT> *it =   					\
 		get_tree_iterator<USE_HINT>(iterator);				\
```
Comment (drewdzzz) [inline src/box/memtx_tree.cc:574]: LGTM, but when [commit](https://github.com/tarantool/tarantool/pull/7410/commits/c9b393aff0718d2be875c687c1cec9eb27660d0a) will be in master, this variable will be unused, so don't forget to remove it later. (Or you can move that commit to this PR or even merge PRs)

**Review by drewdzzz — APPROVED** [review]
LGTM, but when [commit](https://github.com/tarantool/tarantool/pull/7410/commits/c9b393aff0718d2be875c687c1cec9eb27660d0a) will be in master, this variable will be unused, so don't forget to remove it later. (Or you can move that commit to this PR or even merge PRs)

**Comment by CuriousGeorgiy** [comment]
@drewdzzz what variable?

**Comment by drewdzzz** [comment]
@CuriousGeorgiy 
https://github.com/tarantool/tarantool/blob/969b76ac9901840156c6b9fad45d70ab5de6f221/src/box/memtx_tree.cc#L547-L548
It is used only for `tree_iterator_set_current_tuple(it, *ret);` after this patch, but [commit](https://github.com/tarantool/tarantool/pull/7410/commits/c9b393aff0718d2be875c687c1cec9eb27660d0a) removes it.

**Comment by CuriousGeorgiy** [comment]
@drewdzzz don't worry, build will fail anyways:

```console
/Users/georgiy.lebedev/Work/tarantool/src/box/memtx_tree.cc:609:1: error: unused variable 'it' [-Werror,-Wunused-variable]
WRAP_ITERATOR_METHOD(tree_iterator_next_equal_raw);
^
/Users/georgiy.lebedev/Work/tarantool/src/box/memtx_tree.cc:596:34: note: expanded from macro 'WRAP_ITERATOR_METHOD'
        struct tree_iterator<USE_HINT> *it =                                    \

```

**Review by alyapunov — APPROVED** [review]
