### PR TITLE
Fix a crash on concurrent `fiber:join()`

### LINKED ISSUE #7489: Secondary join to fiber leads to crash
**Bug description**

Segmentation fault
```
#1  0x562cb7a2b702 in crash_signal_cb+194
#2  0x7f123d573420 in __restore_rt+0
#3  0x562cb7a2b19e in error_ref+14
#4  0x562cb7a16e88 in luaT_pusherror+24
#5  0x562cb7a0f57b in lbox_fiber_join+251
#6  0x562cb7a69813 in lj_BC_FUNCC+68
#7  0x562cb7a6e917 in lua_pcall+199
#8  0x562cb7a14c6f in luaT_call+15
#9  0x562cb7a0d649 in lua_main+89
#10 0x562cb7a0dac1 in run_script_f+1105
#11 0x562cb786c0d1 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+17
#12 0x562cb7a32880 in fiber_loop+48
#13 0x562cb7ccce38 in coro_init+72
```

**Steps to reproduce**

`docker run --rm -it  tarantool/tarantool:2.10.0-ubuntu-amd64`

`tarantool>`

```
fiber=require('fiber')

f1 = fiber.new(function()
  fiber.sleep(1)
end)
f1:set_joinable(true)

f2 = fiber.new(function()
  fiber.sleep(0.5)
  f1:join()
end)
f2:set_joinable(true)

f1:cancel()
f1:join()
```

### PR DESCRIPTION
**Pull request by Gumix**
**fiber: introduce fiber_wait_on_deadline()**
It is separated from fiber_join_timeout(), and will be used
in lbox_fiber_join() too.

**fiber: do not crash on concurrent fiber:join()**
If two or more fibers are yielding in fiber_join_timeout(), one of them
will eventually join and recycle the fiber, while the rest will crash
on accessing the recycled fiber's struct. Fix this by doing fiber_find()
again after each waiting attempt in lbox_fiber_join().

**fiber: do not crash on concurrent C fiber_join()**
Like a previous commit, but fix C module API instead of Lua.

Closes https://github.com/tarantool/tarantool/issues/7489
Closes https://github.com/tarantool/tarantool/issues/7531

### CODE REVIEW

File: src/lib/core/fiber.h [hunk 1]
```diff
@@ -338,6 +338,23 @@ fiber_join(struct fiber *f);
...
+ * The fiber must not be detached (@sa fiber_set_joinable()).
+ * @pre FIBER_IS_JOINABLE flag is set.
+ *
+ * \param f fiber to be woken up
+ * \param timeout time during which we wait for the fiber completion
+ * \param retval pointer to the variable for the fiber's return value
+ * \return 0 on success, -1 on error
+ */
+int
+fiber_join_timeout_internal(struct fiber *f, double timeout, int *retval);
```
Comment (Gerold103) [inline src/lib/core/fiber.h:353]: You placed this function into the public API section (starts with `/** \cond public */`). If so, then it should not have `_internal` suffix, should have `API_EXPORT` attribute, be exported as a symbol, needs a docbot request, and shouldn't mention `FIBER_IS_JOINABLE` flag (fiber flags are not exposed to the public API anywhere). Otherwise I would recommend to move it out of the public API.

In either case the function needs unit tests in this commit.

File: src/lua/fiber.c [hunk 2]
```diff
@@ -747,13 +747,14 @@ lbox_fiber_join(struct lua_State *L)
 			luaL_error(L, "fiber:join(timeout): bad arguments");
 		}
 	}
-	int rc = fiber_join_timeout(fiber, timeout);
+	int f_ret, rc = fiber_join_timeout_internal(fiber, timeout, &f_ret);
 
-	if (child_L != NULL) {
+	bool do_coro_unref = (rc == 0) && (child_L != NULL);
```
Comment (Gerold103) [inline src/lua/fiber.c:752]: So this is the reason why we need to distinguish the join fail vs func fail? Maybe try this?
```Diff
diff --git a/src/lua/fiber.c b/src/lua/fiber.c
index 9a4302a6d..bebf15bca 100644
--- a/src/lua/fiber.c
+++ b/src/lua/fiber.c
@@ -733,10 +733,9 @@ static int
 lbox_fiber_join(struct lua_State *L)
 {
 	struct fiber *fiber = lbox_checkfiber(L, 1);
-	struct lua_State *child_L = fiber->storage.lua.stack;
 	struct error *e = NULL;
 	int num_ret = 0;
-	int coro_ref = 0;
+	int coro_ref = LUA_NOREF;
 
 	if (!(fiber->flags & FIBER_IS_JOINABLE))
 		luaL_error(L, "the fiber is not joinable");
@@ -747,14 +746,15 @@ lbox_fiber_join(struct lua_State *L)
 			luaL_error(L, "fiber:join(timeout): bad arguments");
 		}
 	}
-	int f_ret, rc = fiber_join_timeout_internal(fiber, timeout, &f_ret);
-
-	bool do_coro_unref = (rc == 0) && (child_L != NULL);
-	if (do_coro_unref) {
+	int rc = fiber_join_timeout(fiber, timeout);
+	struct lua_State *child_L = fiber->storage.lua.stack;
+	if (child_L != NULL) {
+		fiber->storage.lua.stack = NULL;
 		coro_ref = lua_tointeger(child_L, -1);
 		lua_pop(child_L, 1);
 	}
-	if (rc != 0 || f_ret != 0) {
+
+	if (rc != 0) {
 		/*
 		 * After fiber_join the error of fiber being joined was moved to
 		 * current fiber diag so we have to get it from there.
@@ -772,8 +772,7 @@ lbox_fiber_join(struct lua_State *L)
 			lua_xmove(child_L, L, num_ret);
 		}
 	}
-	if (do_coro_unref)
-		luaL_unref(L, LUA_REGISTRYINDEX, coro_ref);
+	luaL_unref(L, LUA_REGISTRYINDEX, coro_ref);
 	return num_ret + 1;
 }
```
I didn't test, but it could allow not to touch `fiber_join()`.

**Review by Gerold103 — COMMENTED** [review]
Thanks for the patch!

File: src/lua/fiber.c (hunk 2 above)
Comment (Gumix) [reply src/lua/fiber.c:752]: > So this is the reason why we need to distinguish the join fail vs func fail?

Yes.

> Maybe try this?

It won't work because of `memset(&fiber->storage, 0, sizeof(fiber->storage));` in `fiber_join()`.

Comment (Gerold103) [reply src/lua/fiber.c:752]: This looked suspicious anyway, so I did a deeper investigation: https://github.com/tarantool/tarantool/issues/7531. I can tell that while this commit doesn't make things worse, it doesn't fix the problem either. See *"Issue 3"* in the ticket - I used only the public Lua API and a couple of joins to crash the process. Like in the ticket you are trying to fix, but slightly modified.

With that said I would rather recommend to find a more robust way to fix fiber join. In Lua it should never crash and in C we probably should panic if somebody tries to join same fiber in 2 and more places. Short workarounds like in this PR keep appearing periodically, but they can't fix the global problem and only promote potential use-after-free usage.

In the given PR you can try to fix at least the *"Issue 3"* if you 1) keep `fiber_join_timeout()` like it was before, 2) introduce `fiber_wait_on()` which would take `struct fiber *f` and add the current fiber to `f->wake`, 3) in `lbox_fiber_join()` you make a loop like this (pseudocode):
```
while (true) {
    f = fiber_find(id);
    if (f == NULL || !f->is_joinable)
        raise error;
    if (f->is_dead)
        break;
    if (!fiber_wait_on(f, timeout))
        raise error;
}
fiber_join(f); // This will happen immediately - the fiber is already dead.
delete f.lua.stack;
// ...
```
Function `fiber_wait_on()` should not access its parameter `f` after calling `fiber_yield()` inside. Because it can be already freed. This is why I re-call `fiber_find()` after each waiting attempt in the loop. It would also automatically guarantee that the Lua stack is deleted only by one "joiner".

Comment (Gerold103) [reply src/lua/fiber.c:752]: It helped for Issue 3, but now I posted Issue 4 and here this PR doesn't help again. Take a look at the updated ticket. Half-measures won't solve this.

File: src/lib/core/fiber.h (hunk 1 above)
Comment (Gumix) [reply src/lib/core/fiber.h]: Removed this function.

File: src/lua/fiber.c (hunk 2 above)
Comment (Gumix) [reply src/lua/fiber.c]: Looks like all 4 issues from https://github.com/tarantool/tarantool/issues/7531 are fixed by the loop which you have suggested.

File: src/lib/core/fiber.c [hunk 3]
```diff
@@ -653,6 +653,15 @@ fiber_join_timeout(struct fiber *fiber, double timeout)
...
 
+	if ((fiber->flags & FIBER_IS_JOINABLE) == 0) {
+		/*
+		 * Joined by concurrent fiber_join_timeout.
+		 * This should never happen when called from lbox_fiber_join.
+		 */
+		diag_set(IllegalParams, "the fiber is already joined");
+		return -1;
+	}
+
```
Comment (Gerold103) [inline src/lib/core/fiber.c:664]: The problem is the same here as it was in Lua - you can't access `fiber` if it was joined by somebody else already. It will crash or hang, depending on whether the fiber was already reused or just deleted. This slight alteration of the test makes it crash:
```Diff
-	struct fiber *joinee = fiber_new_xc("joinee", noop_f);
+	struct fiber_attr *attr = fiber_attr_new();
+	fail_if(fiber_attr_setstacksize(attr, 1024 * 1024) != 0);
+	struct fiber *joinee = fiber_new_ex("joinee", attr, noop_f);
+	fail_if(joinee == NULL);
+	fiber_attr_delete(attr);
```
It is far from trivial to fix for the public C API. Just doing `fiber_find()` after each yield doesn't look like a good solution in terms of perf. I tried to explain in the ticket our other options. If we don't want to wrap private struct fiber into a safe public version, then maybe we could reference-count the internal fibers. Or just leave the issue as is, I suppose. I won't insist.

This particular commit could be omitted, the problem remains anyway. If the fiber was reused and also became joinable, then you will join a totally foreign fiber. If the fiber was deleted - you will crash.

**Review by Gerold103 — COMMENTED** [review]
Thanks for the fixes! Became much safer now!

File: src/lib/core/fiber.c [hunk 4]
```diff
@@ -627,30 +627,30 @@ fiber_join(struct fiber *fiber)
...
 }
 
+bool
+fiber_wait_on_deadline(struct fiber *fiber, double deadline)
+{
+	/*
+	 * In case fiber is cancelled during yield it will be removed from wake
+	 * queue by a wakeup following the cancel, so we have to put it back in.
+	 */
+	rlist_add_tail_entry(&fiber->wake, fiber(), state);
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/lib/core/fiber.c]: Done

File: src/lib/core/fiber.c [hunk 5]
```diff
@@ -627,30 +627,30 @@ fiber_join(struct fiber *fiber)
...
+	return fiber_yield_deadline(deadline);
+}
+
 int
 fiber_join_timeout(struct fiber *fiber, double timeout)
 {
 	if ((fiber->flags & FIBER_IS_JOINABLE) == 0)
 		panic("the fiber is not joinable");
 
+	double deadline = fiber_clock() + timeout;
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/lib/core/fiber.c]: Done

File: src/lua/fiber.c [hunk 6]
```diff
@@ -732,6 +745,7 @@ lbox_fiber_wakeup(struct lua_State *L)
 static int
 lbox_fiber_join(struct lua_State *L)
 {
+	uint64_t fid = lbox_fiber_id_from_stack(L, 1);
 	struct fiber *fiber = lbox_checkfiber(L, 1);
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/lua/fiber.c]: I have no idea why I did that, fixed.

File: src/lua/fiber.c [hunk 7]
```diff
@@ -747,7 +761,30 @@ lbox_fiber_join(struct lua_State *L)
...
+			e = diag_last_error(&fiber()->diag);
+			lua_pushboolean(L, false);
+			luaT_pusherror(L, e);
+			diag_clear(&fiber()->diag);
+			return 2;
+		}
+		fiber = fiber_find(fid);
+		if (fiber == NULL)
+			luaL_error(L, "the fiber is already joined "
+				      "by concurrent fiber:join()");
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/lua/fiber.c]: Done

File: src/lua/fiber.c [hunk 8]
```diff
@@ -747,7 +761,30 @@ lbox_fiber_join(struct lua_State *L)
...
+		/*
+		 * At this point the fiber's struct may be already reused by
+		 * another fiber.
+		 */
+		if (exceeded) {
+			diag_set(TimedOut);
+			e = diag_last_error(&fiber()->diag);
+			lua_pushboolean(L, false);
+			luaT_pusherror(L, e);
+			diag_clear(&fiber()->diag);
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/lua/fiber.c]: Done

File: test/app-luatest/gh_7489_concurrent_fiber_join_test.lua [hunk 9]
```diff
@@ -0,0 +1,82 @@
+local fiber = require('fiber')
+local t = require('luatest')
+local g1 = t.group('gh-7489-concurrent-fiber-join-1',
+                   {{ do_cancel = false },
+                    { do_cancel = true }})
+local g2 = t.group('gh-7489-concurrent-fiber-join-2')
+
+local error_message = 'the fiber is already joined by concurrent fiber:join()'
+
+g1.test_concurrent_fiber_join = function(cg)
```
[the remark this answers is not in the document]
Comment (Gumix) [reply test/app-luatest/gh_7489_concurrent_fiber_join_test.lua:10]: Done, and simplified the test a bit.

File: src/lib/core/fiber.c (hunk 3 above)
Comment (Gumix) [reply src/lib/core/fiber.c]: I removed this patch and created #7562 about C API.

**Review by Gerold103 — APPROVED** [review]
Thanks for the fixes!

File: test/app-luatest/gh_7489_concurrent_fiber_join_test.lua (hunk 9 above)
[the remark this answers is not in the document]
Comment (Gerold103) [reply test/app-luatest/gh_7489_concurrent_fiber_join_test.lua:10]: Now you just narrate the code, I rather meant we need to explain "what" is tested rather than "how" line-by-line. Nevermind anyway.

File: src/lua/fiber.c [hunk 10]
```diff
@@ -747,7 +748,30 @@ lbox_fiber_join(struct lua_State *L)
...
+			diag_set(TimedOut);
+			e = diag_last_error(&fiber()->diag);
+			lua_pushboolean(L, false);
+			luaT_pusherror(L, e);
+			return 2;
+		}
+		fiber = fiber_find(fid);
+		if (fiber == NULL) {
+			luaL_error(L, "the fiber is already joined "
+				      "by concurrent fiber:join()");
```
Comment (locker) [inline src/lua/fiber.c:769]: Why not do it in `fiber_join_timeout` instead, thus making this function safe against concurrent join?

Also, why do you raise an error in case the fiber has already been joined? Why not return `false, error`, like we do on timeout? According to the [documentation](https://www.tarantool.io/en/doc/latest/reference/reference_lua/fiber/#lua-function.fiber_object.join), this function never raises.

 (I didn't follow the discussion so I'm sorry if this was already discussed.)

Comment (Gumix) [reply src/lua/fiber.c:769]: @Gerold103 said that it will degrade performance: https://github.com/tarantool/tarantool/pull/7513#discussion_r942985411

Comment (locker) [reply src/lua/fiber.c:769]: Are there any numbers to prove his point? `fiber_find` should be pretty cheap and it'd be called only after yield+wakeup so I doubt it'd introduce any noticeable performance degradation.

Comment (locker) [reply src/lua/fiber.c:769]: > * Fixing it this way in C API won't do much good anyway. If the user calls `fiber_join()` from 2 places on the same fiber in C, it can easily happen that he calls second join after the first one has already completed. It is clearly a race. And then he will get use-after-free anyway. The hack with `fiber_find()` works only in Lua API where we carry only fiber IDs, not `struct fiber *` pointers. In C it would work only if multiple `fiber_join()` manage to start before any of them is completed.

Agree. The fix isn't suitable for C API, because we use `struct fiber *` for referencing fibers there.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
integration/vshard test fails, but it fails on the master and in the vshard repository so it's unrelated.

**Comment by locker** [comment]
Cherry-picked to 2.10.
