### PR TITLE
netbox: close transport after stopping worker loop and wait for the stop

### LINKED ISSUE #9621: msgpuck reach unreachable() statement on net.box's schema fetch
I'm running `config-luatest/vshard_test.lua` many times in parallel on a fresh tarantool version (3.1.0-entrypoint-28-g876273220d).

```sh
$ ulimit -c unlimited
$ KEEP_DATA=1 ./test/test-run.py $(yes config-luatest/vshard_test.lua | head -n 100)
```

Sometimes it is failed in the following way.

```c
[002] instance-005 | 2024-01-25 17:23:09.926 [6787] main/125/unix/:./instance-001.iproto (net.box)/vshard.replicaset I> connected to unix/:./instance-001.iproto
[002] instance-005 | 2024-01-25 17:23:09.940 [6787] main/129/unix/:./instance-001.iproto (net.box)/vshard.replicaset I> connected to unix/:./instance-001.iproto
[002] instance-005 | tarantool: ./src/lib/msgpuck/msgpuck.h:2270: mp_decode_uint: Assertion `0' failed.
```

The code with the `unreachable()` [statement](https://github.com/tarantool/msgpuck/blob/e3af562e2bcb415716958aba267d6d1ab24a9d09/msgpuck.h#L2270) that fails is the following.

```c
MP_IMPL uint64_t
mp_decode_uint(const char **data)
{
        uint8_t c = mp_load_u8(data);
        switch (c) {
        case 0xcc:
                return mp_load_u8(data);
        case 0xcd:
                return mp_load_u16(data);
        case 0xce:
                return mp_load_u32(data);
        case 0xcf:
                return mp_load_u64(data);
        default:
                if (mp_unlikely(c > 0x7f))
                        mp_unreachable();
                return c;
        }    
}
````

The backtrace from gdb is the following.

```c
#0  0x00007f510c3dfacc in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f510c392252 in raise () from /lib64/libc.so.6
#2  0x00007f510c37b4f2 in abort () from /lib64/libc.so.6
#3  0x00007f510c37b415 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007f510c38ae82 in __assert_fail () from /lib64/libc.so.6
#5  0x00005621e624ba20 in mp_decode_uint (data=0x7f50d1a80bf8) at /home/alex/p/tarantool-meta/tarantool/src/lib/msgpuck/msgpuck.h:2270
#6  0x00005621e609ed84 in netbox_transport_send_and_recv (transport=0x40f6e070, hdr=0x7f50d1a80cc0) at /home/alex/p/tarantool-meta/tarantool/src/box/lua/net_box.c:1268
#7  0x00005621e60a3d58 in netbox_transport_fetch_schema (transport=0x40f6e070, L=0x40f6e6e8, schema_version=82) at /home/alex/p/tarantool-meta/tarantool/src/box/lua/net_box.c:2952
#8  0x00005621e60a42a1 in netbox_connection_handler_f (L=0x40f6e6e8) at /home/alex/p/tarantool-meta/tarantool/src/box/lua/net_box.c:3064
#9  0x00005621e6158a97 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#10 0x00005621e6166a7e in lua_cpcall (L=0x40f6e6e8, func=0x5621e60a423b <netbox_connection_handler_f>, ud=0x40f6e070) at /home/alex/p/tarantool-meta/tarantool/third_party/luajit/src/lj_api.c:1207
#11 0x00005621e60ce7e6 in luaT_cpcall (L=0x40f6e6e8, func=0x5621e60a423b <netbox_connection_handler_f>, ud=0x40f6e070) at /home/alex/p/tarantool-meta/tarantool/src/lua/utils.c:711
#12 0x00005621e60a459a in netbox_worker_f (ap=0x7f510b814298) at /home/alex/p/tarantool-meta/tarantool/src/box/lua/net_box.c:3093
#13 0x00005621e5e45016 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x5621e60a42c3 <netbox_worker_f>, ap=0x7f510b814298) at /home/alex/p/tarantool-meta/tarantool/src/lib/core/fiber.h:1297
#14 0x00005621e60fc44d in fiber_loop (data=0x0) at /home/alex/p/tarantool-meta/tarantool/src/lib/core/fiber.c:1160
#15 0x00005621e63f89ca in coro_init () at /home/alex/p/tarantool-meta/tarantool/third_party/coro/coro.c:108
```

More info:

```c
(gdb) frame 5
#5  0x00005621e624ba20 in mp_decode_uint (data=0x7f50d1a80bf8) at /home/alex/p/tarantool-meta/tarantool/src/lib/msgpuck/msgpuck.h:2270
2270				mp_unreachable();
(gdb) p/x c
$10 = 0x96

(gdb) frame 6
(gdb) p/x bufpos[0]
$12 = 0x96
(gdb) tt-mp bufpos
[201U, "unicode_sl_s3", 1U, "ICU", "sl", {"strength": "tertiary"}]
```

### LINKED ISSUE #9826: `net.box` crashes if connection is closed from `on_schema_reload` trigger
**Steps to reproduce**

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

fiber = require('fiber')
nb = require('net.box')
socket = require('socket')

box.cfg{listen = 3301}

conn = nb.connect(3301, {wait_connected = false})
conn:on_schema_reload(function(conn)
    pcall(function() conn:close() end)
end)

assert(conn:wait_state('closed', 1))

os.exit()

```

**Actual behavior**

```console
Assertion failed: (transport->state == NETBOX_AUTH || transport->state == NETBOX_FETCH_SCHEMA), function netbox_transport_process_requests, file net_box.c, line 3036.
```

**Expected behavior**

Script successfully executes.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
This patch fixes a bugs in `net.box` related to the connection being closed unexpectedly to the connection's worker fiber.

Closes #9621
Closes #9826

### CODE REVIEW

File: src/box/lua/net_box.c [hunk 1]
```diff
@@ -1151,6 +1151,28 @@ netbox_transport_connect(struct netbox_transport *transport)
 	return -1;
 }
 
+/*
```
Comment (Serpentian) [inline src/box/lua/net_box.c:1154]: `netbox_transport_connect` is also executed inside worker fiber: `coio_connect_timeout` yields in `coio_connect_addr`, after that it tries to read with `coio_readn_timeout` (which also yields, BTW). It looks like we should use `netbox_worker_check_after_yield` in `netbox_transport_connect` too

File: src/box/lua/net_box.c [hunk 2]
```diff
@@ -1151,6 +1151,28 @@ netbox_transport_connect(struct netbox_transport *transport)
...
+ * During a worker fiber's yield, the connection could get closed. Testing that
```
Comment (Serpentian) [inline src/box/lua/net_box.c:1155]: Nit: the commit msg should probably say `Part of #...`. It's strange, that 2 commits close the same issue. It should also be before `NO_TEST ...` statements

File: src/box/lua/net_box.c [hunk 3]
```diff
@@ -1275,6 +1275,17 @@ static int
...
+	 * instance, when decoding the response). Unfortunately, we do not have
+	 * a convenient way to get notified about this event, so the best we can
+	 * do is check the connection state before doing any work.
+	 */
+	if (transport->state == NETBOX_CLOSED) {
+		box_error_raise(ER_NO_CONNECTION, "Connection closed");
+		return -1;
+	}
 	ibuf_consume(&transport->recv_buf, transport->last_msg_size);
 	while (true) {
```
Comment (Serpentian) [inline src/box/lua/net_box.c:1290]: Isn't checking `transport->state` at the beginning of the loop step be safer?

**Review by Serpentian — COMMENTED** [review]
Thank you for the patch! Some minor comments from me

**Review by xuniq — APPROVED** [review]

File: src/box/lua/net_box.c [hunk 4]
```diff
@@ -1234,10 +1256,8 @@ netbox_transport_communicate(struct netbox_transport *transport, size_t limit)
 			box_error_raise(ER_NO_CONNECTION, "Error injection");
 			return -1;
 		});
-		if (fiber_is_cancelled()) {
-			diag_set(FiberIsCancelled);
+		if (netbox_worker_check_after_yield(transport) != 0)
```
Comment (locker) [inline src/box/lua/net_box.c:1259]: > The worker fiber can yield in a number of places: after `coio_wait` and during Lua calls.
> 
> During the worker's yield, the connection can get closed. When the connection is closed, its receive buffer is reset. If there was some pending response that was partially retrieved (e.g., a large select), then after resetting the buffer we will read some inconsistent data. We must not allow this to happen, so let's check for this case after returning from places where the worker can yield.

`luaT_netbox_transport_stop` cancels the worker fiber right after calling `netbox_transport_set_error`, which resets the buffer, so the worker fiber should exit immediately after `coio_wait`, without trying to read the buffer any further. Please describe what happens exactly. Maybe, it'll help preparing a test.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/lua/net_box.c (hunk 4 above)
Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: > `luaT_netbox_transport_stop` cancels the worker fiber right after calling `netbox_transport_set_error`, which resets the buffer, so the worker fiber should exit immediately after `coio_wait`.

This is not always true. In between `netbox_transport_set_error` and `fiber_cancel`, `netbox_transport_on_change` is called:
https://github.com/tarantool/tarantool/blob/3daf2399dd5b2b1987e258918376ff9be87e9b01/src/box/lua/net_box.c#L3188-L3194

`netbox_transport_on_change`, in turn, can call a user-provided `on_disconnect` trigger, which can yield.

So there is a chance that the network fiber returns from `coio_wait` and does not get cancelled, while the connection is already closed.

> Please describe what happens exactly.

Unlike the bug from the second patch, I was not able to materialize an inconsistent state that would crash the network fiber. However, it is fairly easy to observe that the scenario I describe above is possible (I can bring a snippet with `print`s, if you like).

File: src/box/lua/net_box.c (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1155]: Fixed.

File: src/box/lua/net_box.c (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1154]: Fixed.

File: src/box/lua/net_box.c (hunk 3 above)
Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1290]: This is superfluous. The point of this check is to catch the case when we didn't yield, but simply entered the Lua VM and got garbage collected. We don't interact with Lua anywhere inside `netbox_send_and_recv`, and we have separate checks for the case we yield there.

File: src/box/lua/net_box.c (hunk 4 above)
Comment (locker) [reply src/box/lua/net_box.c:1259]: > `netbox_transport_on_change`, in turn, can call a user-provided `on_disconnect` trigger, which can yield.
> 
> So there is a chance that the worker fiber returns from `coio_wait` and does not get cancelled, while the connection is already closed.

Then I think that the issue should be possible to reproduce and test properly as follows:
1. Create a fake Tarantool server that sends only a part of a fixheader (half `MP_UINT`) in reply to some special request, then stops until further notice. Maybe, it can even be done with a real Tarantool server using `box.iproto.override`.
2. Establish a net.box connection to this server and send this special request.
3. Install `on_disconnect` trigger that sleeps.
4. Close the connection, then notify the Tarantool server to send the rest of the packet, then resume the `on_disconnect` trigger.

> > worker fiber should exit immediately after `coio_wait`, without trying to read the buffer any further.
> 
> AFAIC, the worker fiber does not always get blocked at `coio_wait`. If there is data ready in the socket, it can start reading it, let's say reading out `request1` and part of `request2`. Later, it can yield from a Lua call, return from it, not being aware that the connection got closed and that the receive buffer got reset, and continue reading from the socket (assuming another part of `request2` data arrives by this moment), again not being blocked by `coio_wait`. Finally, it will start reading the receive buffer, which contains the middle of `request2` (not the beginning, since it was already read out and the buffer got reset), and crash.

Can you fix this issue by cancelling and joining the worker fiber before resetting the buffer?

Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: > Then I think that the issue should be possible to reproduce and test properly as follows.

Thanks for the suggestion! I will try it out and return to you.

> Can you fix this issue by cancelling and joining the worker fiber before resetting the buffer?

AFAIC, this will not work if we close the connection from inside the worker fiber (either do to a trigger, or garbage collection).

Comment (locker) [reply src/box/lua/net_box.c:1259]: > > Can you fix this issue by cancelling and joining the worker fiber before resetting the buffer?
> 
> AFAIC, this will not work if we close the connection from inside the worker fiber (either due to a trigger, or due to garbage collection).

If we do that, we should raise a Lua exception that would force the worker fiber to exit by itself.

Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: > If we do that, we should raise a Lua exception that would force the worker fiber to exit by itself.

But then again, that would mean we would interfere with the `on_disconnect` trigger (AFAIC, we would not even run it with the solution you suggest).

Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: Here is a reproducer for crash after returning from `coio_wait`:

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

fiber = require('fiber')
nb = require('net.box')
socket = require('socket')

local cond = fiber.cond()
local handler = function(fd)
    -- Greeting.
    fd:write(box.iproto.encode_greeting())
    -- Identification.
    fd:write(box.iproto.encode_packet({request_type =
                                       bit.bor(box.iproto.type.TYPE_ERROR,
                                               box.error.UNKNOWN_REQUEST_TYPE)}))
    -- ce 00 00 00 03 81 00 00
    local packet = box.iproto.encode_packet({request_type = box.iproto.type.OK})
    -- ce 00 00 00 03
    local partial_packet = packet:sub(1, 5)
    -- 81 00 00 ce 00 00 00 03 81 00 00
    local leftover_packet = packet:sub(6) .. packet
    fd:write(partial_packet)
    cond:wait()
    fd:write(leftover_packet)
end

srv = socket.tcp_server('localhost', 3301, handler)

c = nb.new(srv:name().port, {fetch_schema = false})

c:on_disconnect(function()
    fiber.sleep(600)
end)

fiber.create(function()
    c:close()
end)

cond:signal()

fiber.sleep(600)

os.exit()
```

Here is a reproducer for crash after returning from `on_connect` trigger:
```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

fiber = require('fiber')
nb = require('net.box')
socket = require('socket')

local cond1 = fiber.cond()
local cond2 = fiber.cond()
local cond3 = fiber.cond()

local handler = function(fd)
    -- Greeting.
    fd:write(box.iproto.encode_greeting())
    -- Identification.
    fd:read(1)
    -- Identification.
    fd:write(box.iproto.encode_packet({request_type =
                                       bit.bor(box.iproto.type.TYPE_ERROR,
                                               box.error.UNKNOWN_REQUEST_TYPE)}))
    -- ce 00 00 00 03 81 00 00
    local packet = box.iproto.encode_packet({request_type = box.iproto.type.OK})
    -- ce 00 00 00 03
    local partial_packet = packet:sub(1, 5)
    -- 81 00 00 ce 00 00 00 03 81 00 00
    local leftover_packet = packet:sub(6) .. packet
    fd:write(partial_packet)
    cond1:wait()
    fd:write(leftover_packet)
end

srv = socket.tcp_server('localhost', 3301, handler)

c = nb.new(srv:name().port, {wait_connected = false, fetch_schema = false})
c:on_connect(function()
    cond2:signal()
    cond3:wait()
end)

c:on_disconnect(function()
    fiber.sleep(600)
end)

cond2:wait()

fiber.create(function()
    c:close()
end)

cond1:signal()
cond3:signal()

fiber.sleep(600)

os.exit()
```

**Review by ochaplashkin — APPROVED** [review]

File: test/app-luatest/gh_9621_netbox_worker_crash_test.lua
Comment (locker) [inline test/app-luatest/gh_9621_netbox_worker_crash_test.lua:1]: This test is bad:

1. It doesn't fail on my laptop **without this patch** unless I run 10 copies of it in parallel.
   <details>
   
   ```
   vlad@esperanza:~/src/tarantool/tarantool/test$ ./test-run.py --builddir ../build/debug gh_9621
   Started ./test-run.py --builddir ../build/debug gh_9621
   Running in parallel with 16 workers
   
   Timeout options:
   -------------------
   SERVER_START_TIMEOUT:     90
   REPLICATION_SYNC_TIMEOUT: 100
   TEST_TIMEOUT:             110
   NO_OUTPUT_TIMEOUT:        120
   
   Collecting tests in 'app'            (Found 0   tests): application server tests.
   Collecting tests in 'app-luatest'    (Found 1   tests): application server tests on luatest.
   Collecting tests in 'app-tap'        (Found 0   tests): application server tests (TAP).
   Collecting tests in 'box'            (Found 0   tests): Database tests.
   Collecting tests in 'box-luatest'    (Found 0   tests): Database tests.
   Collecting tests in 'box-py'         (Found 0   tests): legacy python tests.
   Collecting tests in 'box-tap'        (Found 0   tests): Database tests with #! using TAP.
   Collecting tests in 'config-luatest' (Found 0   tests): declarative configuration tests.
   Collecting tests in 'engine'         (Found 0   tests): tarantool multiengine tests.
   Collecting tests in 'engine-luatest' (Found 0   tests): Database tests.
   Collecting tests in 'engine-tap'     (Found 0   tests): tarantool multiengine tap tests.
   Collecting tests in 'engine_long'    (Found 0   tests): tarantool engine stress tests.
   Collecting tests in 'metrics-luatest' (Found 0   tests): metrics module tests on luatest.
   Collecting tests in 'replication'    (Found 0   tests): tarantool/box, replication.
   Collecting tests in 'replication-luatest' (Found 0   tests): replication luatests.
   Collecting tests in 'replication-py' (Found 0   tests): tarantool/box, replication.
   Collecting tests in 'small'          (Found 0   tests): libsmall unit tests.
   Collecting tests in 'sql'            (Found 0   tests): sql tests.
   Collecting tests in 'sql-luatest'    (Found 0   tests): SQL tests on luatest.
   Collecting tests in 'sql-tap'        (Found 0   tests): Database tests with #! using TAP.
   Collecting tests in 'swim'           (Found 0   tests): SWIM tests.
   Collecting tests in 'unit'           (Found 0   tests): unit tests.
   Collecting tests in 'vinyl'          (Found 0   tests): vinyl integration tests.
   Collecting tests in 'vinyl-luatest'  (Found 0   tests): vinyl space engine luatests.
   Collecting tests in 'wal_off'        (Found 0   tests): tarantool/box, wal_mode = none.
   Collecting tests in 'xlog'           (Found 0   tests): tarantool write ahead log tests.
   Collecting tests in 'xlog-py'        (Found 0   tests): legacy python tests.
   
   Tarantool server information:
    | Found executable at /home/vlad/src/tarantool/tarantool/build/debug/src/tarantool
    | Found tarantoolctl at /home/vlad/src/tarantool/tarantool/test-run/tarantoolctl
   
    | Tarantool 3.1.0-entrypoint-171-g958b75d68cdd
    | Target: Linux-x86_64-Debug
    | Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/vlad/src/tarantool/tarantool/build/debug/install -DENABLE_BACKTRACE=TRUE
    | Compiler: GNU-11.4.0
    | C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
    | CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
   
   Detected build mode: Debug
   
   ======================================================================================
   WORKR TEST                                            PARAMS          RESULT
   ---------------------------------------------------------------------------------
   [001] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   ---------------------------------------------------------------------------------
   Top 10 tests by occupied memory (RSS, Mb):
   *   24.3 app-luatest/gh_9621_netbox_worker_crash_test.lua
   
   (Tests quicker than 0.1 seconds may be missed.)
   
   ---------------------------------------------------------------------------------
   Top 10 longest tests (seconds):
   *   0.17 app-luatest/gh_9621_netbox_worker_crash_test.lua
   ---------------------------------------------------------------------------------
   Statistics:
   * pass: 1
   vlad@esperanza:~/src/tarantool/tarantool/test$ yes gh_9621 | head -n 10 | xargs ./test-run.py --builddir ../build/debug
   Started ./test-run.py --builddir ../build/debug gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621
   Running in parallel with 16 workers
   
   Timeout options:
   -------------------
   SERVER_START_TIMEOUT:     90
   REPLICATION_SYNC_TIMEOUT: 100
   TEST_TIMEOUT:             110
   NO_OUTPUT_TIMEOUT:        120
   
   Collecting tests in 'app'            (Found 0   tests): application server tests.
   Collecting tests in 'app-luatest'    (Found 10  tests): application server tests on luatest.
   Collecting tests in 'app-tap'        (Found 0   tests): application server tests (TAP).
   Collecting tests in 'box'            (Found 0   tests): Database tests.
   Collecting tests in 'box-luatest'    (Found 0   tests): Database tests.
   Collecting tests in 'box-py'         (Found 0   tests): legacy python tests.
   Collecting tests in 'box-tap'        (Found 0   tests): Database tests with #! using TAP.
   Collecting tests in 'config-luatest' (Found 0   tests): declarative configuration tests.
   Collecting tests in 'engine'         (Found 0   tests): tarantool multiengine tests.
   Collecting tests in 'engine-luatest' (Found 0   tests): Database tests.
   Collecting tests in 'engine-tap'     (Found 0   tests): tarantool multiengine tap tests.
   Collecting tests in 'engine_long'    (Found 0   tests): tarantool engine stress tests.
   Collecting tests in 'metrics-luatest' (Found 0   tests): metrics module tests on luatest.
   Collecting tests in 'replication'    (Found 0   tests): tarantool/box, replication.
   Collecting tests in 'replication-luatest' (Found 0   tests): replication luatests.
   Collecting tests in 'replication-py' (Found 0   tests): tarantool/box, replication.
   Collecting tests in 'small'          (Found 0   tests): libsmall unit tests.
   Collecting tests in 'sql'            (Found 0   tests): sql tests.
   Collecting tests in 'sql-luatest'    (Found 0   tests): SQL tests on luatest.
   Collecting tests in 'sql-tap'        (Found 0   tests): Database tests with #! using TAP.
   Collecting tests in 'swim'           (Found 0   tests): SWIM tests.
   Collecting tests in 'unit'           (Found 0   tests): unit tests.
   Collecting tests in 'vinyl'          (Found 0   tests): vinyl integration tests.
   Collecting tests in 'vinyl-luatest'  (Found 0   tests): vinyl space engine luatests.
   Collecting tests in 'wal_off'        (Found 0   tests): tarantool/box, wal_mode = none.
   Collecting tests in 'xlog'           (Found 0   tests): tarantool write ahead log tests.
   Collecting tests in 'xlog-py'        (Found 0   tests): legacy python tests.
   
   Tarantool server information:
    | Found executable at /home/vlad/src/tarantool/tarantool/build/debug/src/tarantool
    | Found tarantoolctl at /home/vlad/src/tarantool/tarantool/test-run/tarantoolctl
   
    | Tarantool 3.1.0-entrypoint-171-g958b75d68cdd
    | Target: Linux-x86_64-Debug
    | Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/vlad/src/tarantool/tarantool/build/debug/install -DENABLE_BACKTRACE=TRUE
    | Compiler: GNU-11.4.0
    | C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
    | CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
   
   Detected build mode: Debug
   
   ======================================================================================
   WORKR TEST                                            PARAMS          RESULT
   ---------------------------------------------------------------------------------
   [005] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ fail ]
   [005] Test failed! Output from reject file /tmp/t/rejects/app-luatest/gh_9621_netbox_worker_crash.reject:
   [005] Tarantool version is 3.1.0-entrypoint-171-g958b75d68cdd
   [005] TAP version 13
   [005] 1..2
   [005] # Started on Fri Mar 22 16:54:05 2024
   [005] # Starting group: app-luatest.gh_9621_netbox_worker_crash
   [005] not ok 1  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_coio_wait
   [005] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:34: attempt to index local 'srv' (a nil value)
   [005] #   stack traceback:
   [005] #         ...
   [005] #         [C]: in function 'xpcall'
   [005] not ok 2  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_on_connect_trigger
   [005] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:57: attempt to index local 'srv' (a nil value)
   [005] #   stack traceback:
   [005] #         ...
   [005] #         [C]: in function 'xpcall'
   [005] # Ran 2 tests in 0.002 seconds, 0 succeeded, 2 errored
   [005]
   [005] [test-run server "luatest_server"] The log file /tmp/t/005_app-luatest/gh_9621_netbox_worker_crash_test.log has zero size
   [Main process] Got failed test; gently terminate all workers...
   [005] Worker "005_app-luatest" got failed test; stopping the server...
   [003] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [002] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ fail ]
   [002] Test failed! Output from reject file /tmp/t/rejects/app-luatest/gh_9621_netbox_worker_crash.reject:
   [002] Tarantool version is 3.1.0-entrypoint-171-g958b75d68cdd
   [002] TAP version 13
   [002] 1..2
   [002] # Started on Fri Mar 22 16:54:05 2024
   [002] # Starting group: app-luatest.gh_9621_netbox_worker_crash
   [002] ok     1  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_coio_wait
   [002] not ok 2  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_on_connect_trigger
   [002] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:57: attempt to index local 'srv' (a nil value)
   [002] #   stack traceback:
   [002] #         ...
   [002] #         [C]: in function 'xpcall'
   [002] # Ran 2 tests in 0.009 seconds, 1 succeeded, 1 errored
   [002]
   [002] [test-run server "luatest_server"] Last 15 lines of the log file /tmp/t/002_app-luatest/gh_9621_netbox_worker_crash_test.log:
   [002] started
   [002] stopped
   [Main process] Got failed test; gently terminate all workers...
   [002] Worker "002_app-luatest" got failed test; stopping the server...
   [004] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ fail ]
   [004] Test failed! Output from reject file /tmp/t/rejects/app-luatest/gh_9621_netbox_worker_crash.reject:
   [004] Tarantool version is 3.1.0-entrypoint-171-g958b75d68cdd
   [004] TAP version 13
   [004] 1..2
   [004] # Started on Fri Mar 22 16:54:05 2024
   [004] # Starting group: app-luatest.gh_9621_netbox_worker_crash
   [004] not ok 1  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_coio_wait
   [004] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:34: attempt to index local 'srv' (a nil value)
   [004] #   stack traceback:
   [004] #         ...
   [004] #         [C]: in function 'xpcall'
   [004] not ok 2  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_on_connect_trigger
   [004] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:57: attempt to index local 'srv' (a nil value)
   [004] #   stack traceback:
   [004] #         ...
   [004] #         [C]: in function 'xpcall'
   [004] # Ran 2 tests in 0.007 seconds, 0 succeeded, 2 errored
   [004]
   [004] [test-run server "luatest_server"] The log file /tmp/t/004_app-luatest/gh_9621_netbox_worker_crash_test.log has zero size
   [Main process] Got failed test; gently terminate all workers...
   [004] Worker "004_app-luatest" got failed test; stopping the server...
   [001] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [001] Worker "001_app-luatest" got signal to terminate; stopping the server...
   [006] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ fail ]
   [006] Test failed! Output from reject file /tmp/t/rejects/app-luatest/gh_9621_netbox_worker_crash.reject:
   [006] Tarantool version is 3.1.0-entrypoint-171-g958b75d68cdd
   [006] TAP version 13
   [006] 1..2
   [006] # Started on Fri Mar 22 16:54:05 2024
   [006] # Starting group: app-luatest.gh_9621_netbox_worker_crash
   [006] not ok 1  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_coio_wait
   [006] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:34: attempt to index local 'srv' (a nil value)
   [006] #   stack traceback:
   [006] #         ...
   [006] #         [C]: in function 'xpcall'
   [006] not ok 2  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_on_connect_trigger
   [006] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:57: attempt to index local 'srv' (a nil value)
   [006] #   stack traceback:
   [006] #         ...
   [006] #         [C]: in function 'xpcall'
   [006] # Ran 2 tests in 0.002 seconds, 0 succeeded, 2 errored
   [006]
   [006] [test-run server "luatest_server"] The log file /tmp/t/006_app-luatest/gh_9621_netbox_worker_crash_test.log has zero size
   [Main process] Got failed test; gently terminate all workers...
   [006] Worker "006_app-luatest" got failed test; stopping the server...
   [010] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [010] Worker "010_app-luatest" got signal to terminate; stopping the server...
   [008] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [008] Worker "008_app-luatest" got signal to terminate; stopping the server...
   [009] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [009] Worker "009_app-luatest" got signal to terminate; stopping the server...
   [007] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [007] Worker "007_app-luatest" got signal to terminate; stopping the server...
   ---------------------------------------------------------------------------------
   Occupied memory in failed tests (RSS, Mb):
   *  291.8 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *  291.8 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *  291.8 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *  291.8 app-luatest/gh_9621_netbox_worker_crash_test.lua
   
   Top 10 tests by occupied memory (RSS, Mb):
   *  291.8 app-luatest/gh_9621_netbox_worker_crash_test.lua
   
   (Tests quicker than 0.1 seconds may be missed.)
   
   ---------------------------------------------------------------------------------
   Duration of failed tests (seconds):
   *   0.39 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *   0.39 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *   0.39 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *   0.39 app-luatest/gh_9621_netbox_worker_crash_test.lua
   
   Top 10 longest tests (seconds):
   *   0.39 app-luatest/gh_9621_netbox_worker_crash_test.lua
   ---------------------------------------------------------------------------------
   Statistics:
   * fail: 4
   * pass: 6
   Failed tasks:
   - [app-luatest/gh_9621_netbox_worker_crash_test.lua, null]
   # logfile:        /tmp/t/log/005_app-luatest.log
   # reproduce file: /tmp/t/reproduce/005_app-luatest.list.yaml
   - [app-luatest/gh_9621_netbox_worker_crash_test.lua, null]
   # logfile:        /tmp/t/log/002_app-luatest.log
   # reproduce file: /tmp/t/reproduce/002_app-luatest.list.yaml
   - [app-luatest/gh_9621_netbox_worker_crash_test.lua, null]
   # logfile:        /tmp/t/log/004_app-luatest.log
   # reproduce file: /tmp/t/reproduce/004_app-luatest.list.yaml
   - [app-luatest/gh_9621_netbox_worker_crash_test.lua, null]
   # logfile:        /tmp/t/log/006_app-luatest.log
   # reproduce file: /tmp/t/reproduce/006_app-luatest.list.yaml
   ```
   
   </details>

2. At the same time it's flaky. It fails **with this patch** applied when run in parallel.
   <details>
   
   ```
   vlad@esperanza:~/src/tarantool/tarantool/test$ yes gh_9621 | head -n 10 | xargs ./test-run.py --builddir ../build/debug
   Started ./test-run.py --builddir ../build/debug gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621 gh_9621
   Running in parallel with 16 workers
   
   Timeout options:
   -------------------
   SERVER_START_TIMEOUT:     90
   REPLICATION_SYNC_TIMEOUT: 100
   TEST_TIMEOUT:             110
   NO_OUTPUT_TIMEOUT:        120
   
   Collecting tests in 'app'            (Found 0   tests): application server tests.
   Collecting tests in 'app-luatest'    (Found 10  tests): application server tests on luatest.
   Collecting tests in 'app-tap'        (Found 0   tests): application server tests (TAP).
   Collecting tests in 'box'            (Found 0   tests): Database tests.
   Collecting tests in 'box-luatest'    (Found 0   tests): Database tests.
   Collecting tests in 'box-py'         (Found 0   tests): legacy python tests.
   Collecting tests in 'box-tap'        (Found 0   tests): Database tests with #! using TAP.
   Collecting tests in 'config-luatest' (Found 0   tests): declarative configuration tests.
   Collecting tests in 'engine'         (Found 0   tests): tarantool multiengine tests.
   Collecting tests in 'engine-luatest' (Found 0   tests): Database tests.
   Collecting tests in 'engine-tap'     (Found 0   tests): tarantool multiengine tap tests.
   Collecting tests in 'engine_long'    (Found 0   tests): tarantool engine stress tests.
   Collecting tests in 'metrics-luatest' (Found 0   tests): metrics module tests on luatest.
   Collecting tests in 'replication'    (Found 0   tests): tarantool/box, replication.
   Collecting tests in 'replication-luatest' (Found 0   tests): replication luatests.
   Collecting tests in 'replication-py' (Found 0   tests): tarantool/box, replication.
   Collecting tests in 'small'          (Found 0   tests): libsmall unit tests.
   Collecting tests in 'sql'            (Found 0   tests): sql tests.
   Collecting tests in 'sql-luatest'    (Found 0   tests): SQL tests on luatest.
   Collecting tests in 'sql-tap'        (Found 0   tests): Database tests with #! using TAP.
   Collecting tests in 'swim'           (Found 0   tests): SWIM tests.
   Collecting tests in 'unit'           (Found 0   tests): unit tests.
   Collecting tests in 'vinyl'          (Found 0   tests): vinyl integration tests.
   Collecting tests in 'vinyl-luatest'  (Found 0   tests): vinyl space engine luatests.
   Collecting tests in 'wal_off'        (Found 0   tests): tarantool/box, wal_mode = none.
   Collecting tests in 'xlog'           (Found 0   tests): tarantool write ahead log tests.
   Collecting tests in 'xlog-py'        (Found 0   tests): legacy python tests.
   
   Tarantool server information:
    | Found executable at /home/vlad/src/tarantool/tarantool/build/debug/src/tarantool
    | Found tarantoolctl at /home/vlad/src/tarantool/tarantool/test-run/tarantoolctl
   
    | Tarantool 3.1.0-entrypoint-171-g958b75d68cdd
    | Target: Linux-x86_64-Debug
    | Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/vlad/src/tarantool/tarantool/build/debug/install -DENABLE_BACKTRACE=TRUE
    | Compiler: GNU-11.4.0
    | C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
    | CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
   
   Detected build mode: Debug
   
   ======================================================================================
   WORKR TEST                                            PARAMS          RESULT
   ---------------------------------------------------------------------------------
   [002] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ fail ]
   [002] Test failed! Output from reject file /tmp/t/rejects/app-luatest/gh_9621_netbox_worker_crash.reject:
   [002] Tarantool version is 3.1.0-entrypoint-171-g958b75d68cdd
   [002] TAP version 13
   [002] 1..2
   [002] # Started on Fri Mar 22 16:52:39 2024
   [002] # Starting group: app-luatest.gh_9621_netbox_worker_crash
   [002] ok     1  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_coio_wait
   [002] not ok 2  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_on_connect_trigger
   [002] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:57: attempt to index local 'srv' (a nil value)
   [002] #   stack traceback:
   [002] #         ...
   [002] #         [C]: in function 'xpcall'
   [002] # Ran 2 tests in 0.005 seconds, 1 succeeded, 1 errored
   [002]
   [002] [test-run server "luatest_server"] Last 15 lines of the log file /tmp/t/002_app-luatest/gh_9621_netbox_worker_crash_test.log:
   [002] started
   [002] stopped
   [Main process] Got failed test; gently terminate all workers...
   [002] Worker "002_app-luatest" got failed test; stopping the server...
   [004] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ fail ]
   [004] Test failed! Output from reject file /tmp/t/rejects/app-luatest/gh_9621_netbox_worker_crash.reject:
   [004] Tarantool version is 3.1.0-entrypoint-171-g958b75d68cdd
   [004] TAP version 13
   [004] 1..2
   [004] # Started on Fri Mar 22 16:52:39 2024
   [004] # Starting group: app-luatest.gh_9621_netbox_worker_crash
   [004] not ok 1  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_coio_wait
   [004] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:34: attempt to index local 'srv' (a nil value)
   [004] #   stack traceback:
   [004] #         ...
   [004] #         [C]: in function 'xpcall'
   [004] ok     2  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_on_connect_trigger
   [004] # Ran 2 tests in 0.005 seconds, 1 succeeded, 1 errored
   [004]
   [004] [test-run server "luatest_server"] Last 15 lines of the log file /tmp/t/004_app-luatest/gh_9621_netbox_worker_crash_test.log:
   [004] started
   [004] stopped
   [Main process] Got failed test; gently terminate all workers...
   [004] Worker "004_app-luatest" got failed test; stopping the server...
   [006] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ fail ]
   [006] Test failed! Output from reject file /tmp/t/rejects/app-luatest/gh_9621_netbox_worker_crash.reject:
   [006] Tarantool version is 3.1.0-entrypoint-171-g958b75d68cdd
   [006] TAP version 13
   [006] 1..2
   [006] # Started on Fri Mar 22 16:52:39 2024
   [006] # Starting group: app-luatest.gh_9621_netbox_worker_crash
   [006] not ok 1  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_coio_wait
   [006] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:34: attempt to index local 'srv' (a nil value)
   [006] #   stack traceback:
   [006] #         ...
   [006] #         [C]: in function 'xpcall'
   [006] not ok 2  app-luatest.gh_9621_netbox_worker_crash.test_worker_yield_from_on_connect_trigger
   [006] #   ...ol/test/app-luatest/gh_9621_netbox_worker_crash_test.lua:57: attempt to index local 'srv' (a nil value)
   [006] #   stack traceback:
   [006] #         ...
   [006] #         [C]: in function 'xpcall'
   [006] # Ran 2 tests in 0.002 seconds, 0 succeeded, 2 errored
   [006]
   [006] [test-run server "luatest_server"] The log file /tmp/t/006_app-luatest/gh_9621_netbox_worker_crash_test.log has zero size
   [Main process] Got failed test; gently terminate all workers...
   [006] Worker "006_app-luatest" got failed test; stopping the server...
   [005] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [005] Worker "005_app-luatest" got signal to terminate; stopping the server...
   [009] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [009] Worker "009_app-luatest" got signal to terminate; stopping the server...
   [007] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [007] Worker "007_app-luatest" got signal to terminate; stopping the server...
   [003] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [003] Worker "003_app-luatest" got signal to terminate; stopping the server...
   [010] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [010] Worker "010_app-luatest" got signal to terminate; stopping the server...
   [001] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [001] Worker "001_app-luatest" got signal to terminate; stopping the server...
   [008] app-luatest/gh_9621_netbox_worker_crash_test.l>                 [ pass ]
   [008] Worker "008_app-luatest" got signal to terminate; stopping the server...
   ---------------------------------------------------------------------------------
   Occupied memory in failed tests (RSS, Mb):
   *  280.6 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *  280.6 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *  280.6 app-luatest/gh_9621_netbox_worker_crash_test.lua
   
   Top 10 tests by occupied memory (RSS, Mb):
   *  280.6 app-luatest/gh_9621_netbox_worker_crash_test.lua
   
   (Tests quicker than 0.1 seconds may be missed.)
   
   ---------------------------------------------------------------------------------
   Duration of failed tests (seconds):
   *   0.38 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *   0.38 app-luatest/gh_9621_netbox_worker_crash_test.lua
   *   0.38 app-luatest/gh_9621_netbox_worker_crash_test.lua
   
   Top 10 longest tests (seconds):
   *   0.38 app-luatest/gh_9621_netbox_worker_crash_test.lua
   ---------------------------------------------------------------------------------
   Statistics:
   * fail: 3
   * pass: 7
   Failed tasks:
   - [app-luatest/gh_9621_netbox_worker_crash_test.lua, null]
   # logfile:        /tmp/t/log/002_app-luatest.log
   # reproduce file: /tmp/t/reproduce/002_app-luatest.list.yaml
   - [app-luatest/gh_9621_netbox_worker_crash_test.lua, null]
   # logfile:        /tmp/t/log/004_app-luatest.log
   # reproduce file: /tmp/t/reproduce/004_app-luatest.list.yaml
   - [app-luatest/gh_9621_netbox_worker_crash_test.lua, null]
   # logfile:        /tmp/t/log/006_app-luatest.log
   # reproduce file: /tmp/t/reproduce/006_app-luatest.list.yaml
   ```
   
   </details>

File: src/box/lua/net_box.c (hunk 4 above)
Comment (locker) [reply src/box/lua/net_box.c:1259]: Then let's try to call triggers from the fiber. I mean something like the patch below.

<details><summary>patch</summary>

```diff
diff --git a/src/box/lua/net_box.c b/src/box/lua/net_box.c
index 1f1c5f7b65a6..c476c9c8df6f 100644
--- a/src/box/lua/net_box.c
+++ b/src/box/lua/net_box.c
@@ -3082,7 +3082,7 @@ netbox_worker_f(va_list ap)
 	assert(transport->self_ref != LUA_NOREF);
 	const double reconnect_after = !uri_is_nil(&transport->opts.uri) ?
 				       transport->opts.reconnect_after : 0;
-	while (!fiber_is_cancelled()) {
+	while (true) {
 		if (netbox_transport_connect(transport) == 0) {
 			int rc = luaT_cpcall(L, netbox_connection_handler_f,
 					     transport);
@@ -3091,8 +3091,13 @@ netbox_worker_f(va_list ap)
 			(void)rc;
 			iostream_close(&transport->io);
 		}
-		if (transport->state == NETBOX_CLOSED)
+		if (fiber_is_cancelled()) {
+			box_error_raise(ER_NO_CONNECTION, "Connection closed");
+			netbox_transport_set_error(transport);
+			transport->state = NETBOX_CLOSED;
+			netbox_transport_on_state_change_pcall(transport, L);
 			break;
+		}
 		netbox_transport_set_error(transport);
 		transport->state = (reconnect_after > 0 ?
 				    NETBOX_ERROR_RECONNECT : NETBOX_ERROR);
@@ -3179,17 +3184,6 @@ luaT_netbox_transport_stop(struct lua_State *L)
 			fiber_cond_wait(&transport->on_send_buf_empty);
 		transport->is_closing = false;
 	}
-	/*
-	 * While we were waiting for the send buffer to be empty,
-	 * the state could change.
-	 */
-	if (transport->state != NETBOX_CLOSED &&
-	    transport->state != NETBOX_ERROR) {
-		box_error_raise(ER_NO_CONNECTION, "Connection closed");
-		netbox_transport_set_error(transport);
-		transport->state = NETBOX_CLOSED;
-		netbox_transport_on_state_change(transport, L);
-	}
 	/* Cancel the worker fiber. */
 	if (transport->worker != NULL) {
 		fiber_cancel(transport->worker);
```

</details>

It should fix the crashes. If running `on_disconnect` triggers from a cancelled fiber isn't okay, we could use some other way to signal the worker fiber to stop.

File: test/app-luatest/gh_9621_netbox_worker_crash_test.lua
Comment (CuriousGeorgiy) [reply test/app-luatest/gh_9621_netbox_worker_crash_test.lua:1]: 1. Adjusted the test by merging the `id_response` packet with the `partial_packet` into 1 socket write — verified it fails on Linux.

2. Changed the tcp server ports to `0`, running `100` tests concurrently now works on my laptop.

File: src/box/lua/net_box.c (hunk 4 above)
Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: This solution is bad:
1. **With this solution**, the following snippet hangs:
```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local net = require('net.box')

box.cfg{listen = 3301}
box.schema.user.grant('guest', 'execute', 'universe')

local c = net.connect(3301, {wait_connected = false})
c:close()
c:ping()

os.exit()
```
2. **With this solution**, the following snippet crashes:
``lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local fiber = require('fiber')
local net = require('net.box')

box.cfg{listen = 3301}
box.schema.user.grant('guest', 'execute', 'universe')

local c = net.connect(3301, {wait_connected = true})
c:on_disconnect(function()
    fiber.yield()
end)

c:close()

os.exit()
```

Comment (locker) [reply src/box/lua/net_box.c:1259]: I think problem 2 could be solved by waiting for the worker fiber to exit after cancelling it in `luaT_netbox_transport_stop`.

Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: AFAIC, that would cause a deadlock in case `transport_stop` gets called from the worker fiber (e.g., in some trigger).

Comment (locker) [reply src/box/lua/net_box.c:1259]: `luaT_netbox_transport_stop` raises the `FiberIsCancelled` error if called from the worker fiber. It shouldn't wait in this case, apparently.

Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: Problem 2 still remains in this case, since the user can still observe the connection state as active from other fibers (let's say, we have a yield after a close in the trigger).

Comment (locker) [reply src/box/lua/net_box.c:1259]: I don't think this is a problem: `close` will raise an error in this case so there's no guarantee that the connection is closed immediately.

Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: `close` will not raise after #9838 is merged, because raising errors from `luaT_netbox_transport_stop` is UB, see #9678.

But we could patch the Lua part of `close` to check the connection status and throw an error:
https://github.com/tarantool/tarantool/blob/58f5ffe43bffa0901d8d577bbb4d523c4e7e682a/src/box/lua/net_box.lua#L838-L841

Comment (locker) [reply src/box/lua/net_box.c:1259]: `close` should raise an exception only if it's called from the worker fiber - in order to cancel itself. This code can't be called from gc AFAICS because the worker fiber keeps a reference to the connection, i.e. we just need to update the condition in `close` a little:

```lua
diff --git a/src/box/lua/net_box.c b/src/box/lua/net_box.c
index 8b0f693e2806..38ae601201c4 100644
--- a/src/box/lua/net_box.c
+++ b/src/box/lua/net_box.c
@@ -3206,7 +3206,8 @@ luaT_netbox_transport_stop(struct lua_State *L)
 	if (transport->worker != NULL) {
 		fiber_cancel(transport->worker);
 		/* Check if we cancelled ourselves. */
-		luaL_testcancel(L);
+		if (transport->worker == fiber())
+			luaL_testcancel(L);
 	}
 	return 0;
 }
```

Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c:1259]: This code can't be called from gc AFAICS because the worker fiber keeps a reference to the connection, i.e. we just need to update the condition in `close` a little.

No, this code can definitely be called from garbage collection — that's what happens in #9621. To be honest, I do not understand how the referencing works here, this snippet is especially obscure:
https://github.com/tarantool/tarantool/blob/58f5ffe43bffa0901d8d577bbb4d523c4e7e682a/src/box/lua/net_box.lua#L419-L439

And this snippet seems to not even work properly, since #9782 exists.

As you already pointed out, the exception thrown from `stop` will be caught by `pcall` in the `gc` hook. Since the connection is garbage collected, nobody can observe its state, so I think it's totally fine that we have it in this intermediate `closing` state for some time.

Comment (locker) [reply src/box/lua/net_box.c:1259]: > I suggest we go for the patch you suggested, which moves the trigger call after the end of the worker loop, and joins the worker fiber, if it isn't the current fiber. Otherwise we throw an exception to indicate that close did not work properly. The user can either let it fly and stop the worker loop, or catch it at his own peril.

Sounds good to me.

Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c]: Updated the PR as per our discussion. Note that it didn't help fix #9785.

File: src/box/lua/net_box.c [hunk 5]
```diff
@@ -3080,6 +3080,25 @@ netbox_connection_handler_f(struct lua_State *L)
 	}
 	return 0;
 }
+
+/**
+ * A wrapper around `fiber_is_cancelled` that closes the transport.
+ */
+static bool
+netbox_worker_is_cancelled(struct netbox_transport *transport,
```
Comment (locker) [inline src/box/lua/net_box.c:3088]: 1. It's unexpected that a function named `netbox_worker_is_cancelled` can actually change the object state.
2. Clearing `is_closing` here looks redundant.
3. Joining the worker fiber is unsafe because `close` may be called concurrently from different fibers. Calling `fiber_join` on the same fiber more than once is prohibited.
4. Passing the extra flag `in_finalizer` to `luaT_netbox_transport_stop` looks ugly. Instead we can reuse the flag `wait`.

<details><summary>Suggested patch</summary>

```diff
diff --git a/src/box/lua/net_box.c b/src/box/lua/net_box.c
index 8b0f693e2806..a7cf226c0888 100644
--- a/src/box/lua/net_box.c
+++ b/src/box/lua/net_box.c
@@ -252,6 +252,8 @@ struct netbox_transport {
 	struct error *last_error;
 	/** Fiber doing I/O and dispatching responses. */
 	struct fiber *worker;
+	/** Signalled when the worker is stopped. */
+	struct fiber_cond on_worker_stop;
 	/**
 	 * Lua reference to the Lua state used by the worker fiber or
 	 * LUA_NOREF if the worker fiber isn't running.
@@ -544,6 +546,7 @@ netbox_transport_create(struct netbox_transport *transport)
 	transport->is_closing = false;
 	transport->last_error = NULL;
 	transport->worker = NULL;
+	fiber_cond_create(&transport->on_worker_stop);
 	transport->coro_ref = LUA_NOREF;
 	transport->self_ref = LUA_NOREF;
 	iostream_ctx_clear(&transport->io_ctx);
@@ -566,6 +569,7 @@ netbox_transport_destroy(struct netbox_transport *transport)
 	assert(transport->worker == NULL);
 	assert(transport->coro_ref == LUA_NOREF);
 	assert(transport->self_ref == LUA_NOREF);
+	fiber_cond_destroy(&transport->on_worker_stop);
 	iostream_ctx_destroy(&transport->io_ctx);
 	assert(!iostream_is_initialized(&transport->io));
 	assert(ibuf_used(&transport->send_buf) == 0);
@@ -3103,7 +3107,7 @@ netbox_worker_f(va_list ap)
 			(void)rc;
 			iostream_close(&transport->io);
 		}
-		if (transport->state == NETBOX_CLOSED)
+		if (fiber_is_cancelled())
 			break;
 		netbox_transport_set_error(transport);
 		transport->state = (reconnect_after > 0 ?
@@ -3115,7 +3119,14 @@ netbox_worker_f(va_list ap)
 			break;
 		}
 	}
+	if (transport->state != NETBOX_ERROR) {
+		box_error_raise(ER_NO_CONNECTION, "Connection closed");
+		netbox_transport_set_error(transport);
+		transport->state = NETBOX_CLOSED;
+		netbox_transport_on_state_change_pcall(transport, L);
+	}
 	transport->worker = NULL;
+	fiber_cond_broadcast(&transport->on_worker_stop);
 	luaL_unref(tarantool_L, LUA_REGISTRYINDEX, transport->coro_ref);
 	transport->coro_ref = LUA_NOREF;
 	/* Careful: luaL_unref may delete this transport object. */
@@ -3171,17 +3182,17 @@ luaT_netbox_transport_start(struct lua_State *L)
  * Stops a worker fiber.
  *
  * Takes an optional boolean argument 'wait': if set the function will wait
- * for all pending requests to be sent.
+ * for all pending requests to be sent and for the connection to be closed.
  */
 static int
 luaT_netbox_transport_stop(struct lua_State *L)
 {
 	struct netbox_transport *transport = luaT_check_netbox_transport(L, 1);
+	transport->is_closing = true;
 	bool wait = lua_toboolean(L, 2);
-	if (wait && fiber() != transport->worker &&
-	    transport->state != NETBOX_CLOSED &&
-	    transport->state != NETBOX_ERROR) {
-		transport->is_closing = true;
+	if (fiber() == transport->worker)
+		wait = false;
+	if (wait) {
 		/*
 		 * Here we are waiting until send buf became empty:
 		 * it is necessary to ensure that all requests are
@@ -3189,18 +3200,6 @@ luaT_netbox_transport_stop(struct lua_State *L)
 		 */
 		while (ibuf_used(&transport->send_buf) > 0)
 			fiber_cond_wait(&transport->on_send_buf_empty);
-		transport->is_closing = false;
-	}
-	/*
-	 * While we were waiting for the send buffer to be empty,
-	 * the state could change.
-	 */
-	if (transport->state != NETBOX_CLOSED &&
-	    transport->state != NETBOX_ERROR) {
-		box_error_raise(ER_NO_CONNECTION, "Connection closed");
-		netbox_transport_set_error(transport);
-		transport->state = NETBOX_CLOSED;
-		netbox_transport_on_state_change(transport, L);
 	}
 	/* Cancel the worker fiber. */
 	if (transport->worker != NULL) {
@@ -3208,6 +3207,11 @@ luaT_netbox_transport_stop(struct lua_State *L)
 		/* Check if we cancelled ourselves. */
 		luaL_testcancel(L);
 	}
+	if (wait) {
+		/* Wait for the worker fiber to stop. */
+		while (transport->worker != NULL)
+			fiber_cond_wait(&transport->on_worker_stop);
+	}
 	return 0;
 }
 
```

</details>

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/lua/net_box.c (hunk 5 above)
Comment (CuriousGeorgiy) [reply src/box/lua/net_box.c]: > 3. Joining the worker fiber is unsafe because `close` may be called concurrently from different fibers. Calling `fiber_join` on the same fiber more than once is prohibited.

Thanks for the catch, I didn't know about this — added a test case to `box-luatest/net_box_test.lua` for this.

Applied your patch, I don't see any objections.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 3.1 and 2.11.
