### PR TITLE
Fix start of Tarantool with passed TT_BACKGROUND=true

### LINKED ISSUE #6128: Background start of Tarantool fails with LuajitError: cannot read stdin
**Bug description**

* OS: MacOS
* Tarantool 2.8.1-39-g77c0af501

## Reproducer
```bash
TT_PID_FILE=tarantool.pid TT_LOG=tarantool.log TT_BACKGROUND=true TT_LISTEN=3000 ~/tarantool/2.8.1/bin/tarantool -e 'box.cfg{}'

cat tarantool.log
```

```
2021-06-06 10:31:39.173 [96924] main/103/interactive C> Tarantool 2.8.1-39-g77c0af501
2021-06-06 10:31:39.174 [96924] main/103/interactive C> log level 5
2021-06-06 10:31:39.174 [96924] main/103/interactive I> wal/engine cleanup is paused
2021-06-06 10:31:39.175 [96924] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2021-06-06 10:31:39.175 [96924] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2021-06-06 10:31:39.175 [96924] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2021-06-06 10:31:39.183 [96924] main/103/interactive I> instance uuid dc94ea40-792d-4a98-aa00-8a18981ca183
2021-06-06 10:31:39.185 [96924] main/103/interactive I> : bound to [::]:3000
2021-06-06 10:31:39.185 [96924] main/103/interactive I> initializing an empty data directory
2021-06-06 10:31:39.215 [96924] main/103/interactive I> assigned id 1 to replica dc94ea40-792d-4a98-aa00-8a18981ca183
2021-06-06 10:31:39.215 [96924] main/103/interactive I> cluster uuid f34a5b7e-1e50-4b9e-9d93-03b4097f04eb
2021-06-06 10:31:39.217 [96924] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2021-06-06 10:31:39.218 [96924] snapshot/101/main I> done
2021-06-06 10:31:39.219 [96924] main/103/interactive I> ready to accept requests
2021-06-06 10:31:39.219 [96924] main/104/gc I> wal/engine cleanup is resumed
2021-06-06 10:31:39.219 [96924] main/103/interactive I> set 'log_level' configuration option to 5
2021-06-06 10:31:39.219 [96924] main/105/checkpoint_daemon I> scheduled next checkpoint for Sun Jun  6 11:36:08 2021
2021-06-06 10:31:39.219 [96924] main/103/interactive I> set 'listen' configuration option to "3000"
2021-06-06 10:31:39.219 [96924] main/103/interactive I> set 'log_format' configuration option to "plain"
2021-06-06 10:31:39.220 [96924] main init.c:694 E> LuajitError: cannot read stdin: Resource temporarily unavailable
2021-06-06 10:31:39.220 [96924] main F> fatal error, exiting the event loop
2021-06-06 10:31:39.220 [96924] main F> fatal error, exiting the event loop
```

### PR DESCRIPTION
**Pull request by ligurio**
### Commits:

**lua: fix crash on running in background mode**
    
Tarantool with background mode enabled via environment variable could lead a crash:
    
```
$ TT_PID_FILE=tarantool.pid TT_LOG=tarantool.log TT_BACKGROUND=true TT_LISTEN=3301 tarantool -e 'box.cfg{}'
$ tail -3 tarantool.log
2021-11-02 16:05:43.672 [2341202] main init.c:696 E> LuajitError: cannot read stdin: Resource temporarily unavailable
2021-11-02 16:05:43.672 [2341202] main F> fatal error, exiting the event loop
2021-11-02 16:05:43.672 [2341202] main F> fatal error, exiting the event loop
```
    
Patch fixes a crash.

**src: disable raise in cfg**
    
   
Needed for #6128

**lua: use https protocol in a crash report message**

-------

Other testcases were tested too:                                                 

```                                                                                   
$ TT_PID_FILE=tarantool.pid TT_LOG=tarantool.log TT_BACKGROUND=true TT_LISTEN=3301 ./build/src/tarantool < box.cfg.lua
$ echo "box.cfg{}" | TT_PID_FILE=tarantool.pid TT_LOG=tarantool.log TT_BACKGROUND=true TT_LISTEN=3301 ./build/src/tarantool -
$ ./build/src/tarantool -l fiber -e 'fiber.sleep(1) box.cfg{background=true, log="tarantool.log", pid_file="tarantool.pid"}'
                                                                                   
(T="$(realpath ./build/src/tarantool)";                                          
 I=$(realpath third_party/luajit/test/luajit-test-init.lua);                     
 cd third_party/luajit/test/lua-Harness-tests;                                   
 export LUA_PATH="$(realpath .)/?.lua;;";                                        
 "${T}" -e "dofile[[${I}]]" -l profile_tarantool 241-standalone.t)               
```                                                                              
                                                                                  
Git history shows that case with `TT_BACKGROUND=true` never worked.                                                                                 
Related commits:
 
- commit 1b330121ec7d ("box: set box.cfg options via environment variables")        
- commit 9db64aedbfe2 ("lua: add '-' command line option") 

Fixes #6128

------

Regarding chosen way of toggling panics in cfg.

I have considered a number of methods to call `cfg_*` functions without panics.

1. pass an additional parameter to `cfg_*` functions  - it will change function's interface. But it is desirable.
2. [varargs](https://en.cppreference.com/w/c/variadic) is not suitable, because we need to pass two additional parameters to each `cfg_*` functions: params and their length. It will change interface, when it i snot desirable.
```c
static void                                                                                                                                
cfg_get(const char *param, ...)
    int panic = 1;
    va_list args;
    va_start(args, param);
    panic = va_arg(args, int);
    printf("cfg_get background %d\n", panic);
    va_end(args);
    ...
```
3. I chose a way with new functions that enable/disable panics via global variable.

### CODE REVIEW

File: src/lua/init.c [hunk 1]
```diff
@@ -930,13 +930,20 @@ run_script_f(va_list ap)
 		is_a_tty = inj->iparam;
 	});
 
+	const char *env_background = getenv("TT_BACKGROUND");
+	bool is_background = false;
+	if (env_background) {
+		is_background = (strcmp(env_background, "true") == 0 ? true : false);
+	}
```
Comment (Totktonada) [inline src/lua/init.c:937]: I'm sorry if I'm too early, but the pull request is not marked as a draft and I guess I can raise a early discussion here. Don't take it as a nit, please.

If we'll do `tarantool -e "box.cfg{background = true, listen = 3301, log = 'tarantool.log', pid_file = 'tarantool.pid'}"`, we'll get the same error in the log file without any `TT_*` environment variable.

We should access the option via `cfg_getb()` from `src/cfg.h` if the solution is to skip stdin reading when we're going to background in the `-e <...>` script.

However I would think here a bit more. What if `-l fiber -e 'fiber.sleep(1) box.cfg{<...>}'` is passed?

Comment (Totktonada) [reply src/lua/init.c]: Both variants looks working now.

**Review by ImeevMA — CHANGES_REQUESTED** [review]
I propose to change the approach. Since the problem only occurs if `-e` is used, I think the result should be something like this:
```Diff
diff --git a/src/lua/init.c b/src/lua/init.c
index d6cd81a7c..70541fc58 100644
--- a/src/lua/init.c
+++ b/src/lua/init.c
@@ -1002,7 +1002,7 @@ run_script_f(va_list ap)
                        goto luajit_error;
                if (lua_main(L, argc, argv) != 0)
                        goto error;
-       } else if ((!interactive && !is_a_tty) ||
+       } else if ((!interactive && !is_a_tty && !is_option_e_ran) ||
                        (path && strcmp(path, "-") == 0)) {
                /* Execute stdin */
                if (luaL_loadfile(L, NULL) != 0)
```

**Review by ImeevMA — CHANGES_REQUESTED** [review]
Hi! I suggest a bit more complicated diff:
```Diff
diff --git a/src/lua/init.c b/src/lua/init.c
index d6cd81a7c..4cdaadd14 100644
--- a/src/lua/init.c
+++ b/src/lua/init.c
@@ -949,6 +949,7 @@ run_script_f(va_list ap)
        struct diag *diag = va_arg(ap, struct diag *);
        bool aux_loop_is_run = false;
        bool is_option_e_ran = false;
+       bool is_daemonized = false;
 
        /*
         * Load libraries and execute chunks passed by -l and -e
@@ -976,8 +977,10 @@ run_script_f(va_list ap)
                        if (luaL_loadbuffer(L, optv[i + 1], strlen(optv[i + 1]),
                                            "=(command line)") != 0)
                                goto luajit_error;
+                       pid_t pid = getpid();
                        if (luaT_call(L, 0, 0) != 0)
                                goto error;
+                       is_daemonized = pid != getpid();
                        lua_settop(L, 0);
                        is_option_e_ran = true;
                        break;
@@ -1002,7 +1005,7 @@ run_script_f(va_list ap)
                        goto luajit_error;
                if (lua_main(L, argc, argv) != 0)
                        goto error;
-       } else if ((!interactive && !is_a_tty) ||
+       } else if ((!interactive && !is_a_tty && !is_daemonized) ||
                        (path && strcmp(path, "-") == 0)) {
                /* Execute stdin */
                if (luaL_loadfile(L, NULL) != 0)
```

The diff checks that `fork()` was executed during the execution of the `daemonize()` function.

I'm still not sure if this diff fixes all cases. For example, it might be possible that `-` can be done with `-e "box.cfg{}"` or `fork()` can be called in some other cases.

Also, please write a new Luatest test according our rules for tests.

File: src/lua/init.c [hunk 2]
```diff
@@ -28,6 +28,7 @@
  * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
  * SUCH DAMAGE.
  */
+#include "stdbool.h"
```
Comment (ImeevMA) [inline src/lua/init.c:31]: Do you need this library? I believe `bool` variables existed here before this patch.

File: src/lua/init.c [hunk 3]
```diff
@@ -94,6 +95,14 @@ luaopen_zip(lua_State *L);
 
 #define MAX_MODNAME 64
 
+static bool background = false;
```
Comment (ImeevMA) [inline src/lua/init.c:98]: I think it's better to rename it to `is_background` or something like that since the variable is boolean.

File: src/lua/init.c [hunk 4]
```diff
@@ -1000,14 +1009,39 @@ run_script_f(va_list ap)
...
+	 *   - explicitly enabled with box.cfg{ background=true }.
+	 *     Example: tarantool -e 'box.cfg{background=true}'.
+	 *   - explicitly enabled with TT_BACKGROUND via environment.
+	 *   - Example: TT_BACKGROUND=1 tarantool.
+	 * - is_a_tty mode:
+	 *   - whether stdin refers to a terminal.
+	 *     Example: tarantool < script.lua
+	 *     Example: tarantool - < script.lua
+	 *     Example: cat script.lua | tarantool
+	 */
```
Comment (ImeevMA) [inline src/lua/init.c:1029]: I think it's better to move this comment to the description of the function.

File: src/lua/init.h [hunk 5]
```diff
@@ -43,6 +43,14 @@ extern bool start_loop;
 
 extern struct lua_State *tarantool_L;
 
+/**
+ * Sets an internal variable to true when Tarantool goes background.
+ *
+ * @return  None
```
Comment (ImeevMA) [inline src/lua/init.h:49]: I think
```
/** Sets an internal variable to true when Tarantool goes background. */
```
should be enough since Doxigen is not required for function description. Especially for such simple functions.

File: test/box-tap/gh-5602-environment-vars-cfg.test.lua [hunk 6]
```diff
@@ -29,30 +29,42 @@ local repl1_sock = fio.pathjoin(fio.cwd(), 'repl1.sock')
...
+
+    -- testcase 5
     'TT_STRIP_CORE=a',
+
+    -- testcase 6
+    ('%s %s %s %s'):format(
+        string.format('TT_LISTEN=%s', listen_sock),
+        'TT_LOG=tarantool.log',
+        'TT_PID_FILE=tarantool.pid',
+        'TT_BACKGROUND=true'),
```
Comment (ImeevMA) [inline test/box-tap/gh-5602-environment-vars-cfg.test.lua:61]: Are these tests working? I mean I ran these tests on the master and they passed with no problem. If we remove these changes from the patch, the test will pass without problems. Should there be any effect?

**Review by ImeevMA — CHANGES_REQUESTED** [review]
Hi! Thank you for the patch! I have a few comments, but the only serious one is a comment about the test. I do not see how test shows that the problem is fixed.

**Review by ImeevMA — COMMENTED** [review]
Hi! Thank you for the fixes. I don't understand why separate the test from the fix, but there is a more important question: if the error is no longer reproduced on the master, why do we need a fix? If the error still exists, there is a way to catch it, right?

**Comment by ImeevMA** [comment]
I know @Gumix made the change elsewhere, but I think the patch may have also fixed the unwanted flag issue on the `stdin` file descriptor, which in turn fixed #6128. This is just a guess.

As for the test - I see no problem adding it without a fix. However, I tried running the test on a commit before https://github.com/tarantool/tarantool/commit/ec1af12943a1c4c0052c584068d3fbd81fa050bc and it passed without issue. Did I do something wrong?

**Comment by ImeevMA** [comment]
This is what I did:
```
git reset --hard ec1af12~1
git cherry-pick 52de05ec9
git submodule update --init --recursive 
cmake . && make -j
cd test
./test-run.py app-luatest/gh_6128_background_mode_test.lua
```

Result:
```
======================================================================================
WORKR TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------------
[001] app-luatest/gh_6128_background_mode_test.lua                    [ pass ]
---------------------------------------------------------------------------------
Top 10 tests by occupied memory (RSS, Mb):
*   25.4 app-luatest/gh_6128_background_mode_test.lua                 

(Tests quicker than 0.1 seconds may be missed.)

---------------------------------------------------------------------------------
Top 10 longest tests (seconds):
*   0.26 app-luatest/gh_6128_background_mode_test.lua                 
---------------------------------------------------------------------------------
Statistics:
* pass: 1
```

Output of `git status`:
```
mergen@megatron:~/work/dev$ git status 
On branch temp
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	00000000000000000000.snap
	tarantool.log

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by ImeevMA** [comment]
I found an error in `tarantool.log`, but I don't think it's obvious. Can we make the test fail?

**Comment by Gumix** [comment]
> However, I tried running the test on a commit before [ec1af12](https://github.com/tarantool/tarantool/commit/ec1af12943a1c4c0052c584068d3fbd81fa050bc) and it passed without issue. Did I do something wrong?

Maybe `gh_6128_background_mode_test` should fail only on glibc 2.28 and older, since it uses `popen`, which behaviour depends on the glibc version, as described in [ec1af12](https://github.com/tarantool/tarantool/commit/ec1af12943a1c4c0052c584068d3fbd81fa050bc)?

File: changelogs/unreleased/gh-6128-fix-crash-with-background-env-option.md [hunk 7]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
+
+* Fixed a crash that could happen when Tarantool is started in background mode.
+  For example using environment variable `TT_BACKGROUND=true` (gh-6128).
```
Comment (andreyaksenov) [inline changelogs/unreleased/gh-6128-fix-crash-with-background-env-option.md:4]: Minor suggestions regarding changelogs:
```
* Fixed a crash that could happen when Tarantool is started in the background mode.
  For example, using the environment variable (`TT_BACKGROUND=true`) (gh-6128).
```

**Review by andreyaksenov — APPROVED** [review]

File: changelogs/unreleased/gh-6128-fix-crash-with-background-env-option.md (hunk 7 above)
Comment (ligurio) [reply changelogs/unreleased/gh-6128-fix-crash-with-background-env-option.md]: Andrey, updated, thanks!

**Review by xuniq — APPROVED** [review]

**Review by ImeevMA — APPROVED** [review]
Thank you for the fix!

File: changelogs/unreleased/gh-6128-fix-crash-with-background-env-option.md (hunk 7 above)
Comment (igormunkin) [reply changelogs/unreleased/gh-6128-fix-crash-with-background-env-option.md]: Applied new suggestions @andreyaksenov shared with me in MyTeam.

> * Fixed a crash that could happen when Tarantool is started in the
> [background mode](https://www.tarantool.io/en/doc/latest/reference/configuration/#confval-background) (gh-6128).

**Comment by igormunkin** [comment]
Also backported to 2.11 and 2.10 in scope of 861f6bf35 and 9351a0951 respectively.
