### PR TITLE
memtx: track `index:random` reads and clarify result

### LINKED ISSUE #7670: memtx TREE and HASH index `random` transaction management inconsistency
**Steps to reproduce**

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local ffi = require('ffi')
local json = require('json')
local log = require('log')
local txn_proxy = require('txn_proxy')

box.cfg{memtx_use_mvcc_engine = true}

local s = box.schema.space.create('s')
s:create_index('pk')

box.internal.memtx_tx_gc(100)

box.space.s:insert{0, 0}

local tx = txn_proxy:new()
tx:begin()

tx('box.space.s.index[0]:random()')
s:replace{0, 1}

tx('box.space.s:replace{0, 2}')

log.info('%s', json.encode(tx:commit()))

os.exit()
```

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local ffi = require('ffi')
local json = require('json')
local log = require('log')
local txn_proxy = require('txn_proxy')

box.cfg{memtx_use_mvcc_engine = true}

local s = box.schema.space.create('s')
s:create_index('pk', {type = 'HASH'})

box.internal.memtx_tx_gc(100)

box.space.s:insert{0, 0}

local tx = txn_proxy:new()
tx:begin()

tx('box.space.s.index[0]:random()')
s:replace{0, 1}

tx('box.space.s:replace{0, 2}')

log.info('%s', json.encode(tx:commit()))

os.exit()
```

**Actual behavior**

```console
""
```

**Expected behavior**

```console
[{"error":"Transaction has been aborted by conflict"}]
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
TREE (HASH) index implements `random` method: if `random` returns nothing, i.e. the space is empty, add gap tracking of whole range (full scan tracking), since this result is equivalent to `index:select{}`, otherwise clarify result.

Closes #7670

### CODE REVIEW

File: src/box/memtx_hash.cc [hunk 1]
```diff
@@ -286,9 +286,20 @@ memtx_hash_index_random(struct index *base, uint32_t rnd, struct tuple **result)
...
+		/*
+		 * `light_index_end` is returned only in case the space is
+		 * empty.
+		 */
+		memtx_tx_track_full_scan(txn, space, base);
 		return 0;
+	}
 	*result = light_index_get(hash_table, k);
+	assert(*result != NULL);
+	assert(!base->def->key_def->is_multikey);
```
Comment (drewdzzz) [inline src/box/memtx_hash.cc:301]: Does hash supports multikey?

File: src/box/memtx_hash.cc [hunk 2]
```diff
@@ -286,9 +286,20 @@ memtx_hash_index_random(struct index *base, uint32_t rnd, struct tuple **result)
...
+	*result = memtx_tx_tuple_clarify(txn, space, *result, base, 0);
```
Comment (drewdzzz) [inline src/box/memtx_hash.cc:302]: What if we have found invisible tuple (clarified to NULL)?

File: src/box/memtx_tree.cc [hunk 3]
```diff
@@ -886,7 +886,17 @@ memtx_tree_index_random(struct index *base, uint32_t rnd, struct tuple **result)
...
+	struct space *space = space_by_id(base->def->space_id);
+	if (res == NULL) {
+		*result = NULL;
+		memtx_tx_track_gap(txn, space, base, NULL, ITER_GE, NULL, 0);
+		return 0;
+	}
+	bool is_multikey = base->def->key_def->is_multikey;
+	uint32_t mk_index = is_multikey ? (uint32_t)res->hint : 0;
+	*result =
+		memtx_tx_tuple_clarify(txn, space, res->tuple, base, mk_index);
```
Comment (drewdzzz) [inline src/box/memtx_tree.cc:899]: Invisible tuple?

File: src/box/memtx_tree.cc [hunk 4]
```diff
@@ -886,7 +886,17 @@ memtx_tree_index_random(struct index *base, uint32_t rnd, struct tuple **result)
...
-	*result = res != NULL ? res->tuple : NULL;
+	struct txn *txn = in_txn();
+	struct space *space = space_by_id(base->def->space_id);
+	if (res == NULL) {
+		*result = NULL;
+		memtx_tx_track_gap(txn, space, base, NULL, ITER_GE, NULL, 0);
+		return 0;
+	}
+	bool is_multikey = base->def->key_def->is_multikey;
+	uint32_t mk_index = is_multikey ? (uint32_t)res->hint : 0;
```
Comment (drewdzzz) [inline src/box/memtx_tree.cc:897]: We have special constant `MULTIKEY_NONE`.

File: src/box/memtx_hash.cc (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_hash.cc:301]: Please read this snippet:
https://github.com/tarantool/tarantool/blob/8ee0e434610189f3e4bbca0264de60aa79f0696e/src/box/memtx_space.c#L732-L737

Comment (drewdzzz) [reply src/box/memtx_hash.cc:301]: Yep, it doesn't. Do we need this assert then?

File: src/box/memtx_tree.cc (hunk 4 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:897]: I don't understand how it is applicable here, please study this snippet:
https://github.com/tarantool/tarantool/blob/8ee0e434610189f3e4bbca0264de60aa79f0696e/src/box/memtx_tx.c#L2397-L2400

According to it, `memtx_tx_tuple_clarify` expects `0` — `MULTIKEY_NONE` is equal to `-1`.

Comment (drewdzzz) [reply src/box/memtx_tree.cc]: It's OK.

File: src/box/memtx_hash.cc (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_hash.cc]: Removed assertion (it's intent was actually to document the fact that **HASH** index cannot be multikey).

File: src/box/memtx_hash.cc (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_hash.cc]: Discussed with @alyapunov: let's first check if the space is empty from the transaction's perspective, and if it's not repeatedly call `random` and clarify result, until we get a non-empty one.

We do not care about performance here, since all operations in context of
transaction management currently have O(number of dirty tuples)
complexity.

File: src/box/memtx_tree.cc (hunk 3 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc]: Discussed with @alyapunov: let's first check if the space is empty from the transaction's perspective, and if it's not repeatedly call `random` and clarify result, until we get a non-empty one.

We do not care about performance here, since all operations in context of
transaction management currently have O(number of dirty tuples)
complexity.

File: src/box/memtx_hash.cc [hunk 5]
```diff
@@ -285,12 +285,25 @@ memtx_hash_index_random(struct index *base, uint32_t rnd, struct tuple **result)
...
+	struct space *space = space_by_id(base->def->space_id);
+	if (memtx_hash_index_size(base) == 0) {
+		*result = NULL;
+		memtx_tx_track_full_scan(txn, space, base);
 		return 0;
-	*result = light_index_get(hash_table, k);
+	}
+
+	do {
+		uint32_t k = light_index_random(hash_table, rnd);
```
Comment (alyapunov) [inline src/box/memtx_hash.cc:297]: You must increment `rnd` each time, otherwise you'll get the same `k` each time.

File: src/box/memtx_tree.cc [hunk 6]
```diff
@@ -889,8 +889,23 @@ memtx_tree_index_random(struct index *base, uint32_t rnd, struct tuple **result)
...
+	struct space *space = space_by_id(base->def->space_id);
+	bool is_multikey = base->def->key_def->is_multikey;
+	if (memtx_tree_index_size<USE_HINT>(base) == 0) {
+		*result = NULL;
+		memtx_tx_track_gap(txn, space, base, NULL, ITER_GE, NULL, 0);
+		return 0;
+	}
+
+	do {
+		struct memtx_tree_data<USE_HINT> *res =
```
Comment (alyapunov) [inline src/box/memtx_tree.cc:902]: You must increment rnd each time, otherwise you'll get the same `res` each time.

**Review by alyapunov — CHANGES_REQUESTED** [review]

File: src/box/memtx_hash.cc [hunk 7]
```diff
@@ -285,12 +285,25 @@ memtx_hash_index_random(struct index *base, uint32_t rnd, struct tuple **result)
...
+		/*
+		 * `light_index_end` is returned only in case the space is
+		 * empty.
+		 */
+		assert(k != light_index_end);
+		*result = light_index_get(hash_table, k);
+		assert(*result != NULL);
+		*result = memtx_tx_tuple_clarify(txn, space, *result, base, 0);
+	} while (*result == NULL);
```
Comment (drewdzzz) [inline src/box/memtx_hash.cc:306]: What if we are in read_view and space is empty for us? Invisible loop?

File: src/box/memtx_tree.cc [hunk 8]
```diff
@@ -889,8 +889,23 @@ memtx_tree_index_random(struct index *base, uint32_t rnd, struct tuple **result)
...
+			memtx_tree_random(&index->tree, rnd);
+		assert(res != NULL);
+		uint32_t mk_index = is_multikey ? (uint32_t)res->hint : 0;
+		*result = memtx_tx_tuple_clarify(txn, space, res->tuple,
+						 base, mk_index);
+	} while (*result == NULL);
```
Comment (drewdzzz) [inline src/box/memtx_tree.cc:908]: The same.

File: src/box/memtx_hash.cc (hunk 7 above)
Comment (drewdzzz) [reply src/box/memtx_hash.cc:306]: Sorry, didn't noticed your comment and that is checked that space is empty from transaction perspective.

File: test/box-luatest/gh_7670_memtx_tx_manager_idx_rand_inconsistency_test.lua [hunk 9]
```diff
@@ -0,0 +1,125 @@
...
+    cg.server:exec(function()
+        local t = require('luatest')
+        local txn_proxy = require('test.box.lua.txn_proxy')
+
+        local tx = txn_proxy:new()
+        tx:begin()
+
+        box.space.s:insert{0}
+        for i = 1, 100000 do
+            tx(('box.space.s:insert{%d'):format(i))
```
Comment (drewdzzz) [inline test/box-luatest/gh_7670_memtx_tx_manager_idx_rand_inconsistency_test.lua:121]: Missing closing `}`, replaces just silently fail.

**Review by drewdzzz — CHANGES_REQUESTED** [review]

File: src/box/memtx_hash.cc (hunk 5 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_hash.cc]: Yeah, missed that, my test was broken and it didn't catch this out, sorry.

File: src/box/memtx_tree.cc (hunk 6 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:902]: Yeah, missed that, my test was broken and it didn't catch this out, sorry.

File: test/box-luatest/gh_7670_memtx_tx_manager_idx_rand_inconsistency_test.lua (hunk 9 above)
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_7670_memtx_tx_manager_idx_rand_inconsistency_test.lua]: Thanks for spotting this out. I guess we need to think of replacing `txn_proxy` with a solution that throws errors, like streams.

**Review by drewdzzz — APPROVED** [review]
