### PR TITLE
box/lua: allow to set error cause via `prev` argument

### LINKED ISSUE #9103: Allow to set error cause via prev argument
[Link to the design document](https://www.notion.so/tarantool/Error-subsystem-improvements-90faa0a4714b4143abaf8bed2c10b2fc?pvs=4#c72c870f24734020aae1fbf34e2b8569)

Currently, it’s only possible to set an error cause with the [`set_prev`](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_error/error_object/#lua-function.error_object.set_prev) method. This isn’t very convenient, because one has to construct a new error without raising it, then set its cause, and only then raise it. To simplify this, we’ll add a new argument to the error constructor called `prev`.

For example, the code below

```lua
local ok, err = pcall(my_func)
if not ok then
    box.error{type = "MyAppError", message = "my_func failed", prev = err}
end
```

will be equivalent to

```lua
local ok, err = pcall(my_func)
if not ok then
    local err2 = box.error.new{type = "MyAppError", message = "my_func failed"}
    err2:set_prev(err)
    err2:raise()
end
```

This change should be safe and doesn’t require a new [`compat`](https://www.tarantool.io/en/doc/latest/reference/reference_lua/compat/) option.

### PR DESCRIPTION
**Pull request by Gumix**
Currently, it's only possible to set an error cause with the set_prev method. This isn't very convenient, because one has to construct a new error without raising it, then set its cause, and only then raise it. To simplify this, a new argument `prev` is added to the error constructor.

Closes #9103

[Link to the design document](https://www.notion.so/tarantool/Error-subsystem-improvements-90faa0a4714b4143abaf8bed2c10b2fc?pvs=4#c72c870f24734020aae1fbf34e2b8569)

### CODE REVIEW

File: src/box/lua/error.cc [hunk 1]
```diff
@@ -192,11 +192,20 @@ luaT_error_create(lua_State *L, int top_base)
...
+		if (!lua_isnil(L, -1)) {
+			struct error *prev = luaL_iserror(L, -1);
+			if (prev == NULL) {
+				luaL_error(L, "Invalid argument 'prev' (error "
+					   "expected, got %s)",
+					   lua_typename(L, lua_type(L, -1)));
+			}
+			/* Cycle is not possible for newly created error. */
+			VERIFY(error_set_prev(error, prev) == 0);
+		}
```
Comment (CuriousGeorgiy) [inline src/box/lua/error.cc:206]: I would prefer to group the keyword arguments here: https://github.com/tarantool/tarantool/blob/38fc791cbf50615d6c9a3fb2de23b924449f287c/src/box/lua/error.cc#L171-L177

File: test/box-luatest/error_subsystem_improvements_test.lua [hunk 2]
```diff
@@ -1,6 +1,22 @@
 local t = require('luatest')
 local g = t.group()
 
+-- Test the `prev' argument to the table constructor of `box.error.new'
+-- (gh-9103).
+g.test_error_new_prev_arg = function()
+    local e1 = box.error.new({"errare"})
+    local e2 = box.error.new({"humanum", prev = e1})
+    local _, e3 = pcall(box.error, {"est", prev = e2})
```
Comment (CuriousGeorgiy) [inline test/box-luatest/error_subsystem_improvements_test.lua:9]: Why `pcall`?

**Review by CuriousGeorgiy — CHANGES_REQUESTED** [review]

File: test/box-luatest/error_subsystem_improvements_test.lua [hunk 3]
```diff
@@ -1,6 +1,22 @@
 local t = require('luatest')
 local g = t.group()
 
+-- Test the `prev' argument to the table constructor of `box.error.new'
+-- (gh-9103).
+g.test_error_new_prev_arg = function()
+    local e1 = box.error.new({"errare"})
```
Comment (CuriousGeorgiy) [inline test/box-luatest/error_subsystem_improvements_test.lua:7]: Nit: just for your knowledge, you can omit parentheses for table constructors.

File: test/box-luatest/error_subsystem_improvements_test.lua [hunk 4]
```diff
@@ -1,6 +1,22 @@
...
+    local e2 = box.error.new({"humanum", prev = e1})
+    local _, e3 = pcall(box.error, {"est", prev = e2})
+
+    t.assert_equals(e3.prev.prev.message, "errare")
+    t.assert_equals(e3.prev.message, "humanum")
+    t.assert_equals(e3.message, "est")
+
+    t.assert_error_msg_equals(
+        "Invalid argument 'prev' (error expected, got number)",
+        box.error.new, {".", prev = 333})
```
Comment (CuriousGeorgiy) [inline test/box-luatest/error_subsystem_improvements_test.lua:17]: Nit: just for your knowledge, you can omit the `message` argument for table constructors.

File: test/box-luatest/error_subsystem_improvements_test.lua (hunk 3 above)
Comment (Totktonada) [reply test/box-luatest/error_subsystem_improvements_test.lua:7]: Omitting parentheses in such cases is discouraged by our [Lua style guide](https://www.tarantool.io/en/doc/latest/dev_guide/lua_style_guide/#idioms-and-patterns).

Comment (CuriousGeorgiy) [reply test/box-luatest/error_subsystem_improvements_test.lua:7]: Didn't know about that, okay.

File: src/box/lua/error.cc (hunk 1 above)
Comment (Gumix) [reply src/box/lua/error.cc]: Done.

File: test/box-luatest/error_subsystem_improvements_test.lua (hunk 4 above)
Comment (Gumix) [reply test/box-luatest/error_subsystem_improvements_test.lua]: Done.

File: test/box-luatest/error_subsystem_improvements_test.lua (hunk 2 above)
Comment (Gumix) [reply test/box-luatest/error_subsystem_improvements_test.lua:9]: To test `box.error()`, not only `box.error.new()`.

**Review by CuriousGeorgiy — APPROVED** [review]

**Review by andreyaksenov — APPROVED** [review]

**Review by nshy — APPROVED** [review]

**Review by ochaplashkin — APPROVED** [review]
