### PR TITLE
box: populate sysview iterator with position method

### LINKED ISSUE #11953: Virtual space select with pagination segfaults
Steps to reproduce:
In a single tarantool instance console, issue:
```lua
box.cfg{}
box.space._vspace:select({}, {fetch_pos=true})
```
```
Result will be:
Segmentation fault
  code: SEGV_ACCERR
  addr: 0x5050505050505050
  context: 0x1380b7c18
  siginfo: 0x1380b7bb0
Current time: 1760716734
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x104d46874 in crash_collect+192
#2  0x104d46738 in crash_signal_cb+84
#3  0x1874e16a4 in _sigtramp+56
#4  0x104a7f3bc in iterator_position+236
#5  0x104bc17c0 in box_select+1256
#6  0x104bc1cec in box_select_ffi+148
#7  0x104dc1e28 in lj_vm_ffi_call+100
#8  0x104e7f46c in lj_ccall_func+1236
#9  0x104e0a9f8 in lj_cf_ffi_meta___call+148
#10 0x104dc0140 in lj_BC_FUNCC+44
#11 0x104dcd9f0 in lua_pcall+868
#12 0x104d21cd0 in luaT_call+44
#13 0x104d144a4 in lua_main+340
#14 0x104d12f0c in run_script_f+2144
#15 0x104a61fe4 in fiber_cxx_invoke(int (*)(char*), char*)+32
#16 0x104d51304 in fiber_loop+264
#17 0x10514fee0 in coro_startup+8
```

### PR DESCRIPTION
**Pull request by drewdzzz**
Currently Tarantool crashes when one tries to use pagination on a `sysview` space because it doesn't have `iterator_position` method and it's even not initialized to a generic version throwing an error. Anyway, `sysview` spaces support only `tree` indexes, so pagination definitely may work there - let's populate this engine with `iterator_position` method which simply call the same method of the underlying iterator.

Closes #11953

NO_DOC=bugfix

### CODE REVIEW

File: src/box/sysview.c [hunk 1]
```diff
@@ -102,6 +102,20 @@ sysview_iterator_next(struct iterator *iterator, struct tuple **ret)
...
+ * Implementation of `position` iterator method for this engine. Simply calls
+ * the same method of the source iterator.
+ */
+static int
+sysview_iterator_position(struct iterator *it, const char **pos, uint32_t *size)
+{
+	assert(it->free == sysview_iterator_free);
+	struct sysview_iterator *sysview_it = sysview_iterator(it);
+	*pos = NULL;
+	*size = 0;
```
Comment (nshy) [inline src/box/sysview.c]: Won't source iterator will initialize these arguments properly?

File: test/engine-luatest/gh_11953_pagination_sysview_test.lua [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+            t.assert_equals(tuples2, tuples_offset)
+            i = i + 1
+        until #tuples1 == 0
+
+        -- Test pagination on range iterators
+        local key_iter = {
+            ['GE'] = 3,
+            ['GT'] = 2,
+            ['LE'] = 9,
+            ['LT'] = 10,
```
Comment (nshy) [inline test/engine-luatest/gh_11953_pagination_sysview_test.lua]: Keys a bit strange given they are in range 257-388 now.

File: src/box/sysview.c (hunk 1 above)
Comment (drewdzzz) [reply src/box/sysview.c]: Removed unneeded initialization.

File: test/engine-luatest/gh_11953_pagination_sysview_test.lua (hunk 2 above)
Comment (drewdzzz) [reply test/engine-luatest/gh_11953_pagination_sysview_test.lua]: Thanks! Updated the key.

**Review by lenkis — APPROVED** [review]
