### PR TITLE
Log empty or nil `select` calls

### LINKED ISSUE #6539: Write in log when see `space:select(nil)`
We all hate `space:select(nil)` from large space. We see either crash with OOM, either Tarantool is slow in the uptake with 100% of CPU usage by tx thread. Debugging of killer-request is often too painful and exhausting. The simplest solution which doesn't break back compatibility is to write in the log with `crit` level, when this request is occurring. To simplify debugging we can write Lua stack trace with the log level `warn` or less. When a user sees a core dump with OOM backtrace or 100% CPU usage by Tarantool he will check the logs first to be sure, that there is no `space:select(nil)`.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
# lua: introduce `log.crit`

Introduce module-local S_CRIT alias and add crit function to log module
API.

Needed for #6539

# box: log dangerous `select` and calls

Empty or nil `select` calls on user spaces tend to be
dangerous: we see Tarantool crashing with OOM, or Tarantool becoming
unacceptably slow and its transaction thread utilizing 100% CPU usage.
Also, debugging of such killer-requests is often too painful and
exhausting.

To mitigate this, a critical log entry containing the current stack
traceback is created upon such function calls — a user can explicitly
request a full scan though by passing `fullscan = true` to `select`'s
`options` table argument in which a case a log entry will not be created.

Closes #6539

### CODE REVIEW

File: src/box/lua/schema.lua [hunk 1]
```diff
@@ -2340,8 +2340,21 @@ end
 
 box.internal.check_select_opts = check_select_opts -- for net.box
 
+local check_select_args_rl = log.internal.ratelimit:new()
```
Comment (drewdzzz) [inline src/box/lua/schema.lua:2343]: For me, it would be better if the name of the variable described what it is for: something like `dangerous_select_logger`, for example.

File: src/box/lua/schema.lua [hunk 2]
```diff
@@ -2340,8 +2340,21 @@ end
...
+local function check_select_args(index, key, opts)
+    local rl = check_select_args_rl
```
Comment (drewdzzz) [inline src/box/lua/schema.lua:2345]: `logger` would be better, I think.

File: src/lua/log.lua [hunk 3]
```diff
@@ -395,6 +396,63 @@ local function log_pid()
...
+
+function Ratelimit:new(object)
+    object = object or {}
+    setmetatable(object, self)
+    self.__index = self
+    return object
+end
+
+function Ratelimit:check()
+    local clock = require('clock')
```
Comment (drewdzzz) [inline src/lua/log.lua:415]: Nit: it's better to require it once.

File: src/lua/log.lua [hunk 4]
```diff
@@ -395,6 +396,63 @@ local function log_pid()
     return tonumber(ffi.C.log_pid)
 end
 
+local Ratelimit = {
+    interval = 60,
+    burst = 10,
+    emitted = 0,
+    suppressed = 0,
+    start = 0,
+}
```
Comment (drewdzzz) [inline src/lua/log.lua:405]: We can use lua RateLimit later for other purposes. It's better to pass interval and burst through `new` method.

**Review by alyapunov — APPROVED** [review]

File: src/lua/log.lua (hunk 4 above)
Comment (CuriousGeorgiy) [reply src/lua/log.lua:405]: Actually, these are the default values: you can pass a table to the new method overriding them, e.g.:

```lua
local rl = Ratelimit:new{burst = 15}
assert(rl.burst == 15)
```

File: src/box/lua/schema.lua (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/lua/schema.lua:2343]: I want this object to be _tied_ to the `check_select_args` function and provide its state (just like a static function variable would in _C_) — hence the naming.

File: src/box/lua/schema.lua (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/lua/schema.lua:2345]: It were a simple logger, I would simply use the `log` module API: in terms of OOP, `Ratelimit` would actually be a subclass of `Logger` (if we had one) — I want to emphasize its semantics (of rate limiting log messages).

File: src/lua/log.lua (hunk 3 above)
Comment (CuriousGeorgiy) [reply src/lua/log.lua:415]: Fixed: moved the require to the beginning of the module file.

File: changelogs/unreleased/gh-6539-log-user-space-empty-or-nil-select.md [hunk 5]
```diff
@@ -0,0 +1,11 @@
...
+
+* Changed behaviour of empty or nil `select` calls on user spaces: a critical
+  log entry containing the current stack traceback is created upon such
+  function calls — a user can explicitly request a full scan though by passing
+  `fullscan=true` to `select`'s `options` table argument in which a case a
+  log entry will not be created. (gh-6539).
+
+## feature/lua
+* Added a new function to `log` module: `log.crit()` writes a message with
+  CRITICAL log level.
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply changelogs/unreleased/gh-6539-log-user-space-empty-or-nil-select.md]: Fixed: actually the the second changelog entry is redundant (forgot to remove it) — just removed it.

File: src/box/lua/schema.lua [hunk 6]
```diff
@@ -2340,8 +2340,21 @@ end
...
+
+    if index.space_id >= 512 and
+       (type(key) == 'nil' or (type(key) == 'table' and next(key) == nil)) and
+       (opts == nil or not opts.fullscan) then
+        rl:log_crit('empty or nil `select` call on user space with id=%d\n %s',
+                    index.space_id, debug.traceback())
```
Comment (Totktonada) [inline src/box/lua/schema.lua:2351]: `debug.traceback()` is not a cheap call. I would not call it for messages that will be suppressed later. I don't see a problem to support a callable object as an argument and pass a function here.

File: src/box/lua/schema.lua [hunk 7]
```diff
@@ -2340,8 +2340,21 @@ end
...
+    end
+end
```
Comment (Totktonada) [inline src/box/lua/schema.lua:2353]: Are we really want to issue a warning for a limited select?

```lua
tarantool> box.space.s:select(nil, {limit = 1})
2022-05-04 21:03:24.168 [10575] main/103/interactive C> empty or nil `select` call on user space with id=514
 stack traceback:
	builtin/box/schema.lua:2378: in function 'check_select_args'
	builtin/box/schema.lua:2387: in function <builtin/box/schema.lua:2382>
	[C]: in function 'pcall'
	builtin/box/console.lua:404: in function 'eval'
	builtin/box/console.lua:710: in function 'repl'
	builtin/box/console.lua:759: in function <builtin/box/console.lua:747>
---
- - [1]
...
```

I asked the product team about this and will return here back tomorrow.

Comment (CuriousGeorgiy) [reply src/box/lua/schema.lua:2353]: > @alyapunov After internal discussion, we decided:
> 
> * Warn the user about potentially dangerous code
> * With logging level - CRIT
> * For all cases:
>   
>   * `:select()`
>   * `:select(nil)`
>   * `:select{}`
>   * `crud:select()`
>   * `crud:select(nil)`
>   * `crud:select{}`
> * With ratelimit (it's worth raising it higher than 0.5 sec for this particular case)
> * Add the option fullscan=true to suppress the message in the log
> * Remove examples of the form select () from the documentation everywhere
> * 2.10 and 1.10.x
> * **UPD** With backtrace

File: src/box/lua/schema.lua [hunk 8]
```diff
@@ -2365,6 +2378,7 @@ end
 
 base_index_mt.select_luac = function(index, key, opts)
     check_index_arg(index, 'select')
+    check_select_args(index, key, opts)
```
Comment (Totktonada) [inline src/box/lua/schema.lua:2381]: We don't care about unlimited select calls over iproto in this implementation, correct? I don't see how it differs from the call from Lua. I asked the product team about this and will return back here tomorrow.

File: src/box/lua/schema.lua (hunk 7 above)
Comment (Totktonada) [reply src/box/lua/schema.lua:2353]: @NeraverinTarantool said that the product team decided to leave it as is. While it is obvious what to do with `limit = 1`, things get less obvious for `limit = 10000`. There is no good universal threshold.

File: src/box/lua/schema.lua (hunk 8 above)
Comment (Totktonada) [reply src/box/lua/schema.lua:2381]: @NeraverinTarantool said that the product team considered it as not so important problem.

File: src/lua/log.lua (hunk 3 above)
Comment (CuriousGeorgiy) [reply src/lua/log.lua:415]: Actually, I can't move it out because of the order in which modules are loaded:
https://github.com/tarantool/tarantool/blob/12cf9980eaa9542bf222d4ae7dd5aad0ccf218cc/src/lua/init.c#L246-L267

`clock` module is loaded after `log` module.
