### PR TITLE
fiber: fix use-after-free on shutdown with lingering fiber join

### LINKED ISSUE #9406: ASAN: heap-use-after-free on tarantool shutdown in case of lingering join
Tarantool version is `3.0.0-beta1-11-g3ee68d8ba`.

Build:
```shell
CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -B build-asan-release \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DENABLE_WERROR=ON \
        -DENABLE_ASAN=ON \
        -DENABLE_UB_SANITIZER=ON \
        -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=OFF \
        -DFIBER_STACK_SIZE=640Kb \
        -DENABLE_FUZZER=ON \
        -DTEST_BUILD=ON
```

Repro script:
```lua
local fiber = require('fiber')

local f = nil
fiber.create(function()
    fiber.sleep(0.1)
    fiber.join(f);
end)
f = fiber.create(function()
    fiber.sleep(1000)
end)
f:set_joinable(true)
fiber.sleep(0.2)
os.exit()
```
Execution result
```
=================================================================
==999241==ERROR: AddressSanitizer: heap-use-after-free on address 0x6150002d1d28 at pc 0x5592e096a20b bp 0x7ffdecf6e3b0 sp 0x7ffdecf6e3a8
WRITE of size 8 at 0x6150002d1d28 thread T0
    #0 0x5592e096a20a in rlist_del /home/shiny/dev/tarantool-tmp/src/lib/small/include/small/rlist.h:101:19
    #1 0x5592e096a20a in fiber_destroy /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1638:2
    #2 0x5592e096590c in fiber_delete /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1656:2
    #3 0x5592e096590c in cord_delete_fibers_in_list /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1666:3
    #4 0x5592e09657d5 in fiber_delete_all /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1674:2
    #5 0x5592e0969708 in cord_destroy /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1912:3
    #6 0x5592e020b82b in tarantool_free() /home/shiny/dev/tarantool-tmp/src/main.cc:603:2
    #7 0x5592e020b82b in main /home/shiny/dev/tarantool-tmp/src/main.cc:1081:2
    #8 0x7f7a9fe45ccf in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #9 0x7f7a9fe45d89 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #10 0x5592e00ce0b4 in _start (/home/shiny/dev/tarantool-tmp/build-asan-release/src/tarantool+0x8050b4) (BuildId: 0d86dbb60ff457681454c6fc83d08c86e6909512)

0x6150002d1d28 is located 296 bytes inside of 476-byte region [0x6150002d1c00,0x6150002d1ddc)
freed by thread T0 here:
    #0 0x5592e01bb8a2 in __interceptor_free.part.0 asan_malloc_linux.cpp.o
    #1 0x5592e126d79a in small_asan_free /home/shiny/dev/tarantool-tmp/src/lib/small/small/util.c:137:2
    #2 0x5592e0965924 in fiber_delete /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1657:2
    #3 0x5592e0965924 in cord_delete_fibers_in_list /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1666:3
    #4 0x5592e09657d5 in fiber_delete_all /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1674:2
    #5 0x5592e0969708 in cord_destroy /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1912:3
    #6 0x5592e020b82b in tarantool_free() /home/shiny/dev/tarantool-tmp/src/main.cc:603:2
    #7 0x5592e020b82b in main /home/shiny/dev/tarantool-tmp/src/main.cc:1081:2
    #8 0x7f7a9fe45ccf in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16

previously allocated by thread T0 here:
    #0 0x5592e01bc8d9 in malloc (/home/shiny/dev/tarantool-tmp/build-asan-release/src/tarantool+0x8f38d9) (BuildId: 0d86dbb60ff457681454c6fc83d08c86e6909512)
    #1 0x5592e126d3a2 in small_asan_alloc /home/shiny/dev/tarantool-tmp/src/lib/small/small/util.c:94:24
    #2 0x5592e1268d6d in mempool_alloc /home/shiny/dev/tarantool-tmp/src/lib/small/small/mempool_asan.c:67:4
    #3 0x5592e096204f in fiber_new_ex /home/shiny/dev/tarantool-tmp/src/lib/core/fiber.c:1554:4
    #4 0x5592e08eee03 in fiber_create /home/shiny/dev/tarantool-tmp/src/lua/fiber.c:451:20
    #5 0x5592e08eb875 in lbox_fiber_create /home/shiny/dev/tarantool-tmp/src/lua/fiber.c:494:20
    #6 0x5592e0a6dac2 in lj_BC_FUNCC /home/shiny/dev/tarantool-tmp/build-asan-release/third_party/luajit/src/lj_vm.S:811

SUMMARY: AddressSanitizer: heap-use-after-free /home/shiny/dev/tarantool-tmp/src/lib/small/include/small/rlist.h:101:19 in rlist_del
Shadow bytes around the buggy address:
  0x6150002d1a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x6150002d1b00: 00 00 00 00 00 00 00 00 00 00 f7 f7 fa fa fa fa
  0x6150002d1b80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x6150002d1c00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x6150002d1c80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x6150002d1d00: fd fd fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd
  0x6150002d1d80: fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa fa
  0x6150002d1e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x6150002d1e80: f7 f7 f7 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x6150002d1f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x6150002d1f80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==999241==ABORTING
```

### PR DESCRIPTION
**Pull request by nshy**
On Tarantool shutdown we destroy all the fibers in some sequence. We don't require that all the fibers are finished before shutdown. So it may turn out that we first destroy some alive fiber and then destroy another alive fiber which joins the first one. Currently we have use-after-free issue in this case because clearing `link` field of the second fiber changes `wake` field of the first fiber.

Close #9406

### CODE REVIEW

File: test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua
Comment (locker) [inline test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua:1]: Nit: Should be in app-luatest.

File: test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+local g = t.group()
+
+g.test_shutdown_with_lingering_fiber_join = function()
+    local script = [[
+        local fiber = require('fiber')
+
+        local f = nil
+        fiber.create(function()
+            fiber.sleep(0.1)
```
Comment (locker) [inline test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua:11]: It's more reliable to do:

```Lua
while f == nil do
    fiber.sleep(0.1)
end

File: test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+            fiber.join(f)
+        end)
+        f = fiber.create(function()
```
Comment (locker) [inline test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua:14]: You should use `fiber.new` here because `fiber.create` yields.

**Review by locker — CHANGES_REQUESTED** [review]

File: test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+            fiber.sleep(1000)
+        end)
+        f:set_joinable(true)
+        fiber.sleep(0.2)
+        os.exit()
+    ]]
+    local tarantool_bin = arg[-1]
+    local cmd = string.format('%s -e "%s"', tarantool_bin, script)
+    t.assert(os.execute(cmd) == 0)
```
Comment (locker) [inline test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua:23]: Why no changelog? AFAICS this may result in a crash.

File: test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua
Comment (nshy) [reply test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua:1]: Moved to `app-luatest/fiber_test.lua`.

File: test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua (hunk 1 above)
Comment (nshy) [reply test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua:11]: Done.

```diff
diff --git a/test/app-luatest/fiber_test.lua b/test/app-luatest/fiber_test.lua
index bc5237d35..8a681b48e 100644
--- a/test/app-luatest/fiber_test.lua
+++ b/test/app-luatest/fiber_test.lua
@@ -41,10 +41,12 @@ g.test_gh_9406_shutdown_with_lingering_fiber_join = function()

         local f = nil
         fiber.create(function()
-            fiber.sleep(0.1)
+            while f == nil do
+                fiber.sleep(0.1)
+            end
             fiber.join(f)
```

File: test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua (hunk 2 above)
Comment (nshy) [reply test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua:14]: Done.

```diff
diff --git a/test/app-luatest/fiber_test.lua b/test/app-luatest/fiber_test.lua
index bc5237d35..8a681b48e 100644
--- a/test/app-luatest/fiber_test.lua
+++ b/test/app-luatest/fiber_test.lua
@@ -41,10 +41,12 @@ g.test_gh_9406_shutdown_with_lingering_fiber_join = function()
             fiber.join(f)
         end)
-        f = fiber.create(function()
+        f = fiber.new(function()
             fiber.sleep(1000)
         end)
         f:set_joinable(true)
```

File: test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua (hunk 3 above)
Comment (nshy) [reply test/box-luatest/gh_9406_fix_use_after_free_on_shutdown_test.lua:23]: The problem code is executed on finish steps of shutdown when we are only freeing memory. So I guess so we will not overwrite some allocated memory. But let's add changelog anyway.

```md
## bugfix/core

* Fixed potential use-after-free on Tarantool shutdown with lingering
  fiber join (gh-9406).
```

**Review by locker — APPROVED** [review]

**Review by ochaplashkin — APPROVED** [review]

**Review by p7nov — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.11.
