### PR TITLE
relay: fix synchro queue limitation after a local recovery

### LINKED ISSUE #11091: replication: synchro queue is unlimited after local recovery
**Bug description**

The size of the synchronous queue is not limited during recovery by design, because at this moment a lot of transactions can fly into the synchronous queue at high speed. But it was forgotten to enable limitation back after recovering from local snapshots.

**Steps to reproduce**

Run the `replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua` with the following patch:

```diff
--- a/test/replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua
+++ b/test/replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua
@@ -134,7 +134,15 @@ g.test_recovery_with_small_max_size = function(cg)
         box.ctl.promote()
         t.assert_equals(box.space.test:len(), 1000)
         box.cfg{replication_synchro_timeout = 100000}
+        -- wait = 'complete' by default, so after truncate completes,
+        -- the synchronous queue is guaranteed to be empty
+        box.space.test:truncate()
+        t.assert_equals(box.info.synchro.queue.len, 0)
     end)
+    -- synchro queue is empty now, 'test' space truncated,
+    -- so all invariants for test_master_synchro_queue_limited
+    -- are satisfied
+    g.test_master_synchro_queue_limited(cg)
 end
 
 g.test_size_is_updated_correctly_after_commit = function(cg)
```

How to run:

```console
./test-run.py replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua --server-start-timeout=5 --test-timeout=15
```

**Actual behavior**

The test fails.

**Expected behavior**

The test doesn't fail.

### PR DESCRIPTION
**Pull request by Astronomax**
Fixed a bug when the synchronous queue size limit was not enabled after a local reсvery, i.e. its size was not limited by `replication_synchro_queue_max_size`.

Closes #11091

NO_DOC=bugfix

### CODE REVIEW

File: src/box/box.cc [hunk 1]
```diff
@@ -5711,6 +5711,9 @@ local_recovery(const struct vclock *checkpoint_vclock)
 		diag_raise();
```
Comment (Serpentian) [inline src/box/box.cc:5711]: Nit: the commit msg says `relay: ...`, but the patch is not related to relay. It looks like `box: ` to me

File: test/replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua [hunk 2]
```diff
@@ -134,7 +134,15 @@ g.test_recovery_with_small_max_size = function(cg)
...
         box.cfg{replication_synchro_timeout = 100000}
+        -- wait = 'complete' by default, so after truncate completes,
+        -- the synchronous queue is guaranteed to be empty
+        box.space.test:truncate()
+        t.assert_equals(box.info.synchro.queue.len, 0)
     end)
+    -- synchro queue is empty now, 'test' space truncated,
+    -- so all invariants for test_master_synchro_queue_limited
+    -- are satisfied
+    g.test_master_synchro_queue_limited(cg)
```
Comment (Serpentian) [inline test/replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua:145]: Nit: That's surprising, you can call one test from another, but let's not do that. For that we usually create a separate function, which is called from several tests.

**Review by Serpentian — APPROVED** [review]
Thank you for the patch! Great, you found that. I have only nits, so let's fix them and assign Sergey here.

File: src/box/box.cc (hunk 1 above)
Comment (Astronomax) [reply src/box/box.cc:5711]: This is really weird, I don't know why I wrote this :bowtie:

File: test/replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua (hunk 2 above)
Comment (Astronomax) [reply test/replication-luatest/gh_7486_replication_synchro_queue_max_size_test.lua]: Fixed.

**Review by sergepetrenko — APPROVED** [review]
Thanks for the fix!
LGTM.

File: src/box/box.cc (hunk 1 above)
Comment (Serpentian) [reply src/box/box.cc:5711]: Up to you. Both are good here

**Review by Serpentian — APPROVED** [review]
