### PR TITLE
box: fix WAL queue size accounting on errors

### LINKED ISSUE #11081: A sufficient number of cascade rollbacks block the WAL
**Bug description**

On cascade rollback WAL queue size is miscalculated and as a result writing to WAL is completely blocked.

**Steps to reproduce**

Run next script: 

```lua
os.execute('rm -f *.snap *.xlog *.vylog')
box.cfg{log_level = 'warn', wal_queue_max_size = 100}
local s = box.schema.create_space('test')
s:create_index('pk')
box.error.injection.set('ERRINJ_WAL_IO', true)
pcall(s.insert, s, {1, string.rep('a', 1000)})
box.error.injection.set('ERRINJ_WAL_IO', false)
-- Now journal queue size is beyound threshold forever and operations are stuck.
s:insert({1})
os.exit()
```

**Actual behavior**

Hangs.

**Expected behavior**

Do the insertion successfully.

### PR DESCRIPTION
**Pull request by nshy**
If cascade rollback is in progress any new write to WAL will be accounted in queue size forever. Eventually queue size will become larger then threshold forever and writing to WAL will be blocked.

Closes #11081

### CODE REVIEW

File: src/box/journal.h [hunk 1]
```diff
@@ -272,9 +272,16 @@ static inline int
 journal_write_submit(struct journal_entry *entry)
 {
 	journal_queue_wait();
+	/*
+	 * We cannot account entry after write as in case of bootstrap write
+	 * is synchronous and complete entry synchronously.
+	 */
```
Comment (locker) [inline src/box/journal.h:278]: I fail to understand what this comment is trying to say.

File: changelogs/unreleased/gh-11081-fix-wal-queue-size-accounting.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+## bugfix/box
+
+* Fixed issue of hanging write operations forever triggered by heavy write
+  load and WAL writing failures (gh-11081).
```
Comment (lenkis) [inline changelogs/unreleased/gh-11081-fix-wal-queue-size-accounting.md:4]:
```suggestion
* Fixed the issue with hanging write operations forever triggered by heavy write
  load and WAL writing failures on cascade rollback (gh-11081).
```

**Review by lenkis — APPROVED** [review]

File: test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+        local fiber = require('fiber')
+        local s = box.schema.create_space('test')
+        s:create_index('pk')
+        box.cfg{wal_queue_max_size = 100}
+        box.error.injection.set('ERRINJ_WAL_IO', true)
+        t.assert_error_msg_equals(
+            'Failed to write to disk',
+            s.insert, s, {1, string.rep('a', 1000)})
+        box.error.injection.set('ERRINJ_WAL_IO', false)
+        local ch = fiber.channel(1)
```
Comment (locker) [inline test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua:29]: You could use `fiber.join()` instead.

File: test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+-- Deliberately avoid dropping test space. It would hang.
+
+g.test_accounting_on_error = function(g)
+    g.server:exec(function()
+        local fiber = require('fiber')
+        local s = box.schema.create_space('test')
+        s:create_index('pk')
+        box.cfg{wal_queue_max_size = 100}
+        box.error.injection.set('ERRINJ_WAL_IO', true)
+        t.assert_error_msg_equals(
```
Comment (locker) [inline test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua:25]: Let's check the error name with `assert_error_covers` instead.

File: src/box/journal.h (hunk 1 above)
Comment (nshy) [reply src/box/journal.h:278]: Change to 

```c
        /*
         * We cannot account entry after write. If journal is synchronous
         * the journal_queue_on_complete() is called in write_async().
         */
```

File: test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua (hunk 4 above)
Comment (nshy) [reply test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua:25]: Done.

```diff
         box.error.injection.set('ERRINJ_WAL_IO', true)
-        t.assert_error_msg_equals(
-            'Failed to write to disk',
-            s.insert, s, {1, string.rep('a', 1000)})
+        t.assert_error_covers({
+            type = "ClientError",
+            code = 40,
+            message = 'Failed to write to disk',
+        }, s.insert, s, {1, string.rep('a', 1000)})
         box.error.injection.set('ERRINJ_WAL_IO', false)
```

Comment (locker) [reply test/box-luatest/gh_11081_wal_queue_size_accounting_test.lua:25]: Please change to

```lua
code = box.error.WAL_IO,
```

or

```lua
name = 'WAL_IO',
```

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.11, 3.2, 3.3.
