### PR TITLE
coio refactoring

### LINKED ISSUE #4881: refactoring: don't raise exceptions in coio read / write functions
Tarantool version: since [2.4.0-177-g85eea4a8d](https://github.com/tarantool/tarantool/commit/85eea4a8da23328a40fe2cface6bf663e7a88d3c).
OS version: any.

Commit 85eea4a8da23328a40fe2cface6bf663e7a88d3c introduces `*_noex` functions as the temporary solution to safely use read / write functions inside C code (popen backend).

Those functions should be refactored to set an entry to the diagnostics area instead of raising an exception. All invocations should be changed accordingly.

Related discussion:

https://lists.tarantool.org/pipermail/tarantool-patches/2020-April/015621.html
https://lists.tarantool.org/pipermail/tarantool-patches/2020-April/015628.html
https://lists.tarantool.org/pipermail/tarantool-patches/2020-April/015636.html
https://lists.tarantool.org/pipermail/tarantool-patches/2020-April/015652.html

### PR DESCRIPTION
**Pull request by locker**
To convert the net.box state machine to C, I need `coio_connect` to take host and service as strings (not as URI) and be exception-free. While we are at it, let's also convert `coio.cc` to C.

Closes #4881

### CODE REVIEW

File: src/lib/core/coio.cc [hunk 1]
```diff
@@ -332,32 +341,13 @@ coio_readn_ahead_timeout(struct iostream *io, void *buf, size_t sz,
...
 	return nrd;
 }
 
-/*
- * FIXME: Rewrite coio_read_ahead_timeout() w/o C++ exceptions and
- * drop this function.
- */
-ssize_t
-coio_read_ahead_timeout_noxc(struct iostream *io, void *buf, size_t sz,
-			     size_t bufsiz, ev_tstamp timeout)
```
Comment (Totktonada) [inline src/lib/core/coio.cc:340]: It resolves #4881 (together with drop of `coio_write_timeout_noxc()` below).

File: src/lib/core/coio.c [hunk 2]
```diff
@@ -96,23 +94,25 @@ coio_fill_addrinfo(struct addrinfo *ai_local, const char *host,
 {
 	ai_local->ai_next = NULL;
 	if (host_hint == 1) { // IPv4
-		ai_local->ai_addrlen = sizeof(sockaddr_in);
-		ai_local->ai_addr = (sockaddr*)malloc(ai_local->ai_addrlen);
+		ai_local->ai_addrlen = sizeof(struct sockaddr_in);
+		ai_local->ai_addr = xmalloc(ai_local->ai_addrlen);
```
Comment (Totktonada) [inline src/lib/core/coio.c:98]: Nit: malloc -> xmalloc change is not listed in the commit message.

File: src/lib/core/coio.cc [hunk 3]
```diff
@@ -177,34 +185,33 @@ coio_connect_timeout(const char *host, const char *service, int host_hint,
...
 				*addr_len = MIN(ai->ai_addrlen, *addr_len);
 				memcpy(addr, ai->ai_addr, *addr_len);
 			}
 			return fd; /* connected */
-		} catch (SocketError *e) {
-			if (ai->ai_next == NULL)
-				throw;
-			/* ignore exception and try the next address */
 		}
+		if (ai->ai_next == NULL)
```
Comment (EvgenyMekhanik) [inline src/lib/core/coio.cc:193]: Why do you return here? May be it's better to wait loop breaking in the next iteration (ai become equal to zero).

Comment (locker) [reply src/lib/core/coio.cc:193]: Because the original code does, and I don't want to change it in the scope of this commit:

```diff
-               } catch (SocketError *e) {
-                       if (ai->ai_next == NULL)
-                               throw;
-                       /* ignore exception and try the next address */
```

I assume this is done to avoid `ev_now_update` call on the last iteration:

https://github.com/tarantool/tarantool/blob/b8bd3138f294cb08311f28b4908af7afc4041e65/src/lib/core/coio.cc#L197-L208

File: src/lib/core/coio.cc (hunk 1 above)
Comment (locker) [reply src/lib/core/coio.cc:340]: Linked the issue to the pull request. Thanks.

File: src/lib/core/coio.c (hunk 2 above)
Comment (locker) [reply src/lib/core/coio.c:98]: Right. Mentioned it in the commit message.

File: src/lib/core/coio.cc [hunk 4]
```diff
@@ -522,12 +522,13 @@ coio_service_init(struct coio_service *service, const char *name,
 	service->handler_param = handler_param;
 }
 
-void
+int
 coio_service_start(struct evio_service *service, const char *uri)
```
Comment (EvgenyMekhanik) [inline src/lib/core/coio.cc:508]: This function is unused, maybe drop id?

**Review by EvgenyMekhanik — APPROVED** [review]

File: src/lib/core/coio.cc (hunk 4 above)
Comment (locker) [reply src/lib/core/coio.cc:508]: I tried, but @alyapunov opposed: https://github.com/tarantool/tarantool/pull/6583#discussion_r744651864

`coio_service` is unusable, you're right, but let's fix it when we actually need to use it.
