### PR TITLE
replication: don't rollback qsync limbo wait on fiber cancel

### LINKED ISSUE #9480: Fiber cancellation triggers a synchronous transaction rollback
**Bug description**
Fiber cancellation leads to the synchronous transaction rollback.
According to Raft, only the new leader may roll back some of the ongoing transactions, the current leader should never rollback the transactions it has started.

Issue #7486 states the same problem from the different angle: leader shouldn't roll back the transactions by timeout, it shouldn't roll them back due to fiber cancellation. The transaction should stay in limbo.

Otherwise the user might trigger a split-brain by simply cancelling a fiber which hangs waiting for quorum on the old leader.

**Reproducer**
```lua
-- Start 1 server in console.
box.cfg{replication_synchro_quorum = 2, replication_synchro_timeout=1000, memtx_use_mvcc_engine = 'off'}
box.ctl.promote()
box.schema.space.create('test', {is_sync=true}):create_index('pk')
fiber = require("fiber")
f = fiber.new(function() box.space.test:insert{1} end)
f:set_joinable(true)
f:cancel()
```
Now observe
```lua
f:join()
---
- false
- Quorum collection for a synchronous transaction is timed out
...

```
and
```lua
tarantool> box.space.test:fselect{}
---
- |-
  +-----+
  |col1 |
  +-----+
  +-----+
...

```

### PR DESCRIPTION
**Pull request by nshy**
During iproto graceful shutdown which is WIP we cancel all iproto request in progress. This causes election_qsync_stress test failure.

We shutdown master on waiting transaction confirmation from quorum (which is never exist in this test). Currently on shutdown we rollback transaction in this state. So that when previous master is restarted after electing new master we don't expect the rollback on previous master.

Let's keep the transaction in limbo if fiber is cancelled as our direction is to do only quorum rollbacks.

Part of #8423
Closes #9480

### CODE REVIEW

File: src/box/txn_limbo.c [hunk 1]
```diff
@@ -285,8 +285,11 @@ txn_limbo_wait_complete(struct txn_limbo *limbo, struct txn_limbo_entry *entry)
 			goto complete;
 		if (txn_limbo_is_frozen(limbo))
 			goto wait;
-		if (rc != 0)
+		if (rc != 0) {
+			if (fiber_is_cancelled())
```
Comment (sergepetrenko) [inline src/box/txn_limbo.c:289]: The check for `fiber_is_cancelled` should go before the `txn_limbo_is_frozen()` check now. Otherwise a cancelled fiber will continue running until the limbo is unfrozen.

File: src/box/txn.c [hunk 2]
```diff
@@ -1105,8 +1105,15 @@ txn_commit(struct txn *txn)
 			txn_limbo_ack(&txn_limbo, txn_limbo.owner_id,
```
Comment (sergepetrenko) [inline src/box/txn.c:1105]: > NO_TEST=issue is covered with iproto graceful shutdown

I suggest you add a separate test for this issue. It should be quite easy to write one: you only need one server, set quorum to 2 on it, then create a synchronous transaction in a separate fiber and cancel that fiber. If the change is still seen (without mvcc enabled), the test passes.

> NO_CHANGELOG

But this is a user-visible change: now fiber cancellation doesn't lead to synchronous transaction rollback now. AFAIU this is more consistent with async transactions now. They can't be rolled back by a cancellation after a WAL write is started.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the patch! Please see my 2 comments below.

File: src/box/txn_limbo.c (hunk 1 above)
Comment (nshy) [reply src/box/txn_limbo.c:289]: Done. Changed to:

```diff
@@ -283,6 +283,8 @@ txn_limbo_wait_complete(struct txn_limbo *limbo, struct txn_limbo>
                int rc = fiber_cond_wait_timeout(&limbo->wait_cond, timeout);
                if (txn_limbo_entry_is_complete(entry))
                        goto complete;
+               if (rc != 0 && fiber_is_cancelled())
+                       return -1;
                if (txn_limbo_is_frozen(limbo))
                        goto wait;
                if (rc != 0)
```

File: src/box/txn.c (hunk 2 above)
Comment (nshy) [reply src/box/txn.c:1105]: Added a test and a changelog:

```md
## bugfix/replication

* Fixed to not rollback a transaction waiting for quorum from replicas
  on transaction fiber cancel (gh-9480).
```

Comment (sergepetrenko) [reply src/box/txn.c:1105]: Thanks!

**Review by sergepetrenko — APPROVED** [review]
Thanks for the quick fixes!
LGTM.

File: changelogs/unreleased/gh-9480-dont-rollback-on-quorum-wait-cancel.md [hunk 3]
```diff
@@ -0,0 +1,4 @@
+## bugfix/replication
+
+* Fixed to not rollback a transaction waiting for quorum from replicas
+  on transaction fiber cancel (gh-9480).
```
Comment (p7nov) [inline changelogs/unreleased/gh-9480-dont-rollback-on-quorum-wait-cancel.md:4]:
```suggestion
* Now transactions are not rolled back if the transaction fiber is
  cancelled when waiting for quorum from replicas (gh-9480).
```

**Review by p7nov — APPROVED** [review]

**Review by ochaplashkin — APPROVED** [review]

File: changelogs/unreleased/gh-9480-dont-rollback-on-quorum-wait-cancel.md (hunk 3 above)
Comment (nshy) [reply changelogs/unreleased/gh-9480-dont-rollback-on-quorum-wait-cancel.md:4]: Done.

**Comment by sergepetrenko** [comment]
Backported to 2.11: https://github.com/tarantool/tarantool/pull/9482
