### PR TITLE
ffi: export forgotten fiber_join_timeout symbol

### LINKED ISSUE #7125: undefined symbol: fiber_join_timeout
**Bug description**

Symbol `fiber_join_timeout` is undefined in tarantool binary yet being exported in `tarantool/module.h` in the latest release candidate Tarantool. In 2.8.3 the reproducer below works fine. Btw, there is no record on this symbol in the C API Reference chapter of the doc, but I believe it should be exported and documented.

* OS: Linux 5.4
* OS Version: CentOS 8.5
* Architecture: x86_64

```
tarantool --version
Tarantool 2.10.0-rc1-0-g7ed15e62b
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
```

**Steps to reproduce**

*fjt_issue.c*
```
#include <tarantool/lua.h>
#include <tarantool/lauxlib.h>
#include <tarantool/module.h>

static int
fjt_issue_fiber_func(va_list args)
{
        fiber_sleep(1);
        return 0;
}

static int
fjt_issue_use_fjt_from_c(lua_State *L)
{
        struct fiber *fib = fiber_new("fjt_issue_fib", fjt_issue_fiber_func);
        if (!fib)
                return luaL_error(L, "fiber_new: ENOMEM");

        fiber_set_joinable(fib, true);
        fiber_start(fib);

        return fiber_join_timeout(fib, 2);
}

static const struct luaL_Reg
R[] = {
        {"use_fjt_from_c", fjt_issue_use_fjt_from_c},
        {NULL, NULL},
};

LUA_API int
luaopen_fjt_issue(lua_State *L)
{
        luaL_newmetatable(L, "fjt_issue");
        lua_pushvalue(L, -1);
        lua_setfield(L, -2, "__index");
        luaL_register(L, NULL, R);
        return 1;
}
```

*reproducer.lua*
```
local fjt_issue = require('fjt_issue')
fjt_issue.use_fjt_from_c()
```

How to run:

```
gcc -shared -Wall -fPIC -std=c99 -o fjt_issue.so fjt_issue.c
tarantool reproducer.lua
```

**Actual behavior**

Tarantool is unable to load the shared library due to undefined `fiber_join_timeout` symbol.
```
LuajitError: reproducer.lua:1: module 'fjt_issue' not found:
...
        no file '/root/tnt_issues/fiber_join_timeout/fjt_issue/init.lua'/root/tnt_issues/fiber_join_timeout/fjt_issue.so: undefined symbol: fiber_join_timeout
...
```

**Expected behavior**

Successful script execution

### PR DESCRIPTION
**Pull request by alyapunov**
By a mistake it was marked as API_EXPORT but was forgotten to
be added to exports.

Closes #7125

### CODE REVIEW

File: test/app-luatest/gh_7125-export-fiber_join_timeout_test.lua [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+        struct fiber * fiber_self(void);
+        int fiber_join_timeout(struct fiber *f, double timeout);
+    ]])
+    local fiber_ptr = nil
+    local f = fiber.create(function()
+        fiber_ptr = ffi.C.fiber_self()
+        fiber.self():set_joinable(true)
+        fiber.sleep(0.01)
+    end)
+    t.assert_equals(ffi.C.fiber_join_timeout(fiber_ptr, 100500), 0)
```
Comment (olegrok) [inline test/app-luatest/gh_7125-export-fiber_join_timeout_test.lua:20]: fiber_join_timeout yeilds. AFAIK it's a bit unsafe. https://github.com/tarantool/tarantool/commit/2711797be8c2e864db874a3f3a8434bc182d2360

Comment (alyapunov) [reply test/app-luatest/gh_7125-export-fiber_join_timeout_test.lua:20]: Oh, it seems that you are right. I'm sure btw that there's no chance that the bug you mentioned can fire here because tracing usually starts with hot path, but it should be a good practice to avoid ffi + yield.

Comment (alyapunov) [reply test/app-luatest/gh_7125-export-fiber_join_timeout_test.lua:20]: So I remove `fiber.sleep(0.01)` and now `fiber_join_timeout` has guarantee to finish without yield.

**Review by olegrok — APPROVED** [review]

**Review by Korablev77 — APPROVED** [review]
