### PR TITLE
memtx: fix 'use after free' of garbage collected MVCC stories

### LINKED ISSUE #7449: Certain memtx transaction manager state triggers `tuple_has_flag(tuple, TUPLE_IS_DIRTY)` assertion on `replace`
**Steps to reproduce**

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local ffi = require('ffi')
local json = require('json')
local log = require('log')
local txn_proxy = require('txn_proxy')

box.cfg{memtx_use_mvcc_engine = true}

local s = box.schema.space.create('s')
s:create_index('pk')
s:create_index('sk', {unique = false, parts = {{2, 'uint'}}})

box.internal.memtx_tx_gc(100)

s:insert{0, 0}
s:insert{1, 1}

local tx1 = txn_proxy:new()
local tx2 = txn_proxy:new()

tx1:begin()
tx2:begin()

tx1('box.space.s:select{0}')
tx2('box.space.s.index[1]:select({0}, {iterator = "GT"})')
s:delete{0}
tx1:commit()
box.internal.memtx_tx_gc(1)
s:replace{0, 1}

os.exit()
```

**Actual behavior**

```console
Assertion failed: (tuple_has_flag(tuple, TUPLE_IS_DIRTY)), function memtx_tx_story_get, file memtx_tx.c, line 859.
```

**Expected behavior**

Script successfully exits.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
`directly_replaced` stories can potentially get garbage collected in
`memtx_tx_handle_gap_write`, which is unexpected and leads to 'use after
free': in order to fix this, limit garbage collection points only to
external API calls.

Wrap all possible garbage collection points with explicit warnings (see
https://github.com/tarantool/tarantool/commit/c9981a567c74d494064499e555c5a995133d7019).

Closes https://github.com/tarantool/tarantool/issues/7449

### CODE REVIEW

File: test/box-luatest/gh_7449_tuple_is_dirty_assertion_on_replace_test.lua [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+g.after_all(function(cg)
+    cg.server:drop()
+end)
+
+--[[
+Checks that `select` with `LE` iterator does not return deleted tuple do to
+clarification of garbage collected tuple story (triggered by gap tracking).
+]]
+g.test_gap_tracking_full_key_corner_cases = function(cg)
```
Comment (drewdzzz) [inline test/box-luatest/gh_7449_tuple_is_dirty_assertion_on_replace_test.lua:30]: Comment and test name are stale.

**Review by drewdzzz — CHANGES_REQUESTED** [review]
Please, make the lines of the commit messages shorter, and see my comment about the test. Otherwise, it's OK.

File: test/box-luatest/gh_7449_tuple_is_dirty_assertion_on_replace_test.lua (hunk 1 above)
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_7449_tuple_is_dirty_assertion_on_replace_test.lua]: Fixed: sorry, result of copy-pasting.

**Comment by CuriousGeorgiy** [comment]
@drewdzzz fixed commit subject length, opened a corresponding issue (tarantool/checkpatch#29).

**Review by drewdzzz — COMMENTED** [review]
It won't work if we rework GC as we discussed f2f.

File: src/box/memtx_tx.c [hunk 2]
```diff
@@ -2992,7 +3003,7 @@ memtx_tx_snapshot_clarify_slow(struct memtx_tx_snapshot_cleaner *cleaner,
 		assert(entry->from == tuple);
 		tuple = entry->to;
 	}
-
+	memtx_tx_story_gc();
```
Comment (alyapunov) [inline src/box/memtx_tx.c:3006]: Snapshot cleaner **must not** collect garbage at least because it may be run from different thread.

File: src/box/memtx_tx.c [hunk 3]
```diff
@@ -3001,4 +3012,5 @@ memtx_tx_snapshot_cleaner_destroy(struct memtx_tx_snapshot_cleaner *cleaner)
 {
 	if (cleaner->ht != NULL)
 		mh_snapshot_cleaner_delete(cleaner->ht);
+	memtx_tx_story_gc();
```
Comment (alyapunov) [inline src/box/memtx_tx.c:3015]: Since we does not create/delete stories here perhaps we should not collect them too.

**Review by alyapunov — CHANGES_REQUESTED** [review]

File: src/box/memtx_tx.c (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tx.c:3006]: Sorry, I didn't bear that in mind, removed it.

I added it just for the sake of more often garbage collection.

File: src/box/memtx_tx.c (hunk 3 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tx.c:3015]: I added it just for the sake of more often garbage collection.

Okay, removed it here for clarity. Perhaps we could move the snapshot cleaner stuff into a separate file?

**Review by drewdzzz — APPROVED** [review]

File: src/box/memtx_tx.h [hunk 4]
```diff
@@ -536,12 +583,17 @@ memtx_tx_on_index_delete(struct index *index);
...
  * story's destructor are not applicable.
+ *
+ * NB: can trigger story garbage collection.
  */
 void
 memtx_tx_on_space_delete(struct space *space);
 
 /**
  * Create a snapshot cleaner.
+ *
```
Comment (alyapunov) [inline src/box/memtx_tx.h:594]: Since we removed garbage collection in this method we should remove the comment as well.

File: src/box/memtx_tx.h [hunk 5]
```diff
@@ -557,6 +609,9 @@ memtx_tx_snapshot_clarify_slow(struct memtx_tx_snapshot_cleaner *cleaner,
 /**
  * Like a common clarify that function returns proper tuple if original
  * tuple in index is dirty.
+ *
```
Comment (alyapunov) [inline src/box/memtx_tx.h:612]: Since we removed garbage collection in this method we should remove the comment as well.

File: src/box/memtx_tx.h [hunk 6]
```diff
@@ -572,6 +627,8 @@ memtx_tx_snapshot_clarify(struct memtx_tx_snapshot_cleaner *cleaner,
 
 /**
  * Free resources.in shapshot @cleaner.
+ *
```
Comment (alyapunov) [inline src/box/memtx_tx.h:630]: Since we removed garbage collection in this method we should remove the comment as well.

**Review by alyapunov — CHANGES_REQUESTED** [review]

File: src/box/memtx_tx.h (hunk 6 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tx.h]: Sorry, wasn't careful enough, fixed.

File: src/box/memtx_tx.h (hunk 5 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tx.h]: Sorry, wasn't careful enough, fixed.

File: src/box/memtx_tx.h (hunk 4 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tx.h]: Sorry, wasn't careful enough, fixed.

**Review by alyapunov — APPROVED** [review]
