### PR TITLE
datetime: fix interval arithmetic across DST boundaries

### LINKED ISSUE #7698: Datetime with timezone subtraction
**Bug description**

Datetime subtraction ignores timezone info.

* OS: Linux
* OS Version: Ubuntu 20.04
* Architecture: amd64

Tarantool Enterprise 2.10.0-6-gaaed1a3cb-r497

**Steps to reproduce**

```
tarantool> datetime.new{tz='MSK'} - datetime.new{tz='UTC'}
---
- +0 seconds
...

tarantool> datetime.new{tz='MSK'}.timestamp - datetime.new{tz='UTC'}.timestamp
---
- -10800
...

```

**Actual behavior**

Timezone info ignored.

**Expected behavior**

Timezone info is considered while computing timedelta either error is raised for heterogeneous datetimes. Or, if this result is acceptable, document it in some way.

### LINKED ISSUE #7700: Interval ariphmetic with offset change
**Bug description**

If datetime timezone offset has changed during interval addition, result is incorrect.

* OS: Linux
* OS Version: Ubuntu 20.04
* Architecture: amd64

Tarantool Enterprise 2.10.0-6-gaaed1a3cb-r497

**Steps to reproduce**

```
tarantool> datetime.new{year=2008, month=1, day=1, tz='Europe/Moscow'} + datetime.interval.new{month=6}
---
- 2008-07-01T01:00:00 Europe/Moscow
...

```

**Actual behavior**

Extra hour has been added.

**Expected behavior**

`2008-07-01T00:00:00 Europe/Moscow`

### PR DESCRIPTION
**Pull request by tsafin**
Interval arithmetic across DST boundaries
===========================

We did not take into consideration the fact that as result of date/time arithmetic we could get in a different timezone, if DST boundary has been crossed during operation.

```
tarantool> datetime.new{year=2008, month=1, day=1, tz='Europe/Moscow'} + datetime.interval.new{month=6}
---
- 2008-07-01T01:00:00 Europe/Moscow
...
```

Now we resolve tzoffset at the end of operation if tzindex is not 0.

Fixes #7700

Timezone differences in subtraction
=======================

We used to ignore timezone difference (im `tzoffset`) for datetime subtraction operation:

```
tarantool> datetime.new{tz='MSK'} - datetime.new{tz='UTC'}
---
- +0 seconds
...

tarantool> datetime.new{tz='MSK'}.timestamp - datetime.new{tz='UTC'}.timestamp
---
- -10800
...
```

Now we use tzoffset difference in the minute component of
resultant interval:

```
tarantool> datetime.new{tz='MSK'} - datetime.new{tz='UTC'}
---
- -180 minutes
...
```

Closes #7698

### CODE REVIEW

File: src/lib/core/datetime.c [hunk 1]
```diff
@@ -789,6 +791,12 @@ datetime_increment_by(struct datetime *self, int direction,
...
 
+	if (tzindex != 0) {
+		int isdst = 0;
+		long gmtoff = offset * 60;
+		epoch_timezone_lookup(secs, tzindex, &gmtoff, &isdst);
+		offset = gmtoff / 60;
+	}
 	self->epoch = utc_secs(secs, offset);
 	self->nsec = nsec;
 	self->tzoffset = datetime_gmtoff(self) / 60;
```
Comment (sergepetrenko) [inline src/lib/core/datetime.c:802]: You can replace this with `self->tzoffset = offset` now, since you call `epoch_timezone_lookup` for non-null tzindex above

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the patch!

Looks good except one comment.

File: src/lib/core/datetime.c (hunk 1 above)
Comment (tsafin) [reply src/lib/core/datetime.c:802]: Done so, thanks!
```diff
diff --git a/src/lib/core/datetime.c b/src/lib/core/datetime.c
index 3507b7c6a..e22504d2f 100644
--- a/src/lib/core/datetime.c
+++ b/src/lib/core/datetime.c
@@ -799,7 +799,7 @@ datetime_increment_by(struct datetime *self, int direction,
 	}
 	self->epoch = utc_secs(secs, offset);
 	self->nsec = nsec;
-	self->tzoffset = datetime_gmtoff(self) / 60;
+	self->tzoffset = offset;
 	return 0;
 }
```

File: changelogs/unreleased/gh-7700-interval-arithmetic-across-dst.md [hunk 2]
```diff
@@ -0,0 +1,20 @@
+## bugfix/datetime
+
+* fix interval arithmetic for boundaries crossing DST
```
Comment (sergepetrenko) [inline changelogs/unreleased/gh-7700-interval-arithmetic-across-dst.md:3]: Nit: should be "Fixed interval arithmetic for boundaries crossing DST (gh-7700)."

Also please align both changelogs so that the paragraphs below are part of the bullet (indent them by 2 spaces)

Comment (tsafin) [reply changelogs/unreleased/gh-7700-interval-arithmetic-across-dst.md]: Fixed in both commits. Thanks!

**Review by sergepetrenko — COMMENTED** [review]
Thanks for the fixes!

The PR looks good to me, but someone has to prepare test fixes for go-tarantool and tarantool-python before we can proceed.

**Review by sergepetrenko — APPROVED** [review]

File: test/app-tap/datetime.test.lua [hunk 3]
```diff
@@ -1462,6 +1477,21 @@ test:test("Matrix of allowed time and interval additions", function(test)
...
     test:is(tostring(Y5 + Y1), "+6 years", "Y + Y")
 
+    -- timezone sensitive operations
+    test:is(tostring(T2000 + I1), "2000-01-02T00:00:00 Europe/Moscow",
+        "value: 2000 + I")
+    test:is(tostring(T2000 + i1), "2000-01-02T00:00:00 Europe/Moscow",
+        "value: 2000 + i")
+    test:is(tostring(T2000 + M2), "2000-03-01T00:00:00 Europe/Moscow",
+        "value: 2000 + 2M")
+    test:is(tostring(T2000 + M2 + M2 + M2), "2000-07-01T00:00:00 Europe/Moscow",
```
Comment (igormunkin) [inline test/app-tap/datetime.test.lua:1487]: Please, add some tests/comments regarding timezone offset change.

**Review by igormunkin — APPROVED** [review]
@tsafin, thanks for the patches! See no flaws, so LGETM, but I left a single nit, please consider it.

File: test/app-tap/datetime.test.lua (hunk 3 above)
Comment (tsafin) [reply test/app-tap/datetime.test.lua:1487]: Made it a little bit more verbose, with few comments added here and there:
```diff
diff --git a/test/app-tap/datetime.test.lua b/test/app-tap/datetime.test.lua
index 7367e6522..cb06b0a65 100755
--- a/test/app-tap/datetime.test.lua
+++ b/test/app-tap/datetime.test.lua
@@ -1409,7 +1409,7 @@ Matrix of addition operands eligibility and their result type
 | table           |          |          |          |
 ]]
 test:test("Matrix of allowed time and interval additions", function(test)
-    test:plan(73)
+    test:plan(79)
 
     -- check arithmetic with leap dates
     local T1970 = date.new{year = 1970, month = 1, day = 1}
@@ -1477,20 +1477,41 @@ test:test("Matrix of allowed time and interval additions", function(test)
     test:is(tostring(Y1 + T1970), "1971-01-01T00:00:00Z", "value: Y + T")
     test:is(tostring(Y5 + Y1), "+6 years", "Y + Y")
 
-    -- timezone sensitive operations
-    test:is(tostring(T2000 + I1), "2000-01-02T00:00:00 Europe/Moscow",
+    -- Check winter/DST sensitive operations with intervals.
+    -- We use 2000 year here, because then Moscow still were
+    -- switching between winter and summer time.
+    local msk_offset = 180 -- expected winter time offset
+    local msd_offset = 240 -- expected daylight saving time offset
+
+    local res = T2000 + I1
+    test:is(tostring(res), "2000-01-02T00:00:00 Europe/Moscow",
         "value: 2000 + I")
-    test:is(tostring(T2000 + i1), "2000-01-02T00:00:00 Europe/Moscow",
+    test:is(res.tzoffset, msk_offset, "2000-01-02T00:00:00 - winter")
+
+    res = T2000 + i1
+    test:is(tostring(res), "2000-01-02T00:00:00 Europe/Moscow",
         "value: 2000 + i")
-    test:is(tostring(T2000 + M2), "2000-03-01T00:00:00 Europe/Moscow",
+    test:is(res.tzoffset, msk_offset, "2000-01-02T00:00:00 - winter")
+
+    res = T2000 + M2
+    test:is(tostring(res), "2000-03-01T00:00:00 Europe/Moscow",
         "value: 2000 + 2M")
-    test:is(tostring(T2000 + M2 + M2 + M2), "2000-07-01T00:00:00 Europe/Moscow",
+    test:is(res.tzoffset, msk_offset, "2000-03-01T00:00:00 - winter")
+
+    res = T2000 + M2 + M2 + M2
+    test:is(tostring(res), "2000-07-01T00:00:00 Europe/Moscow",
         "value: 2000 + 6M")
-    test:is(tostring(T2000 + m2), "2000-03-01T00:00:00 Europe/Moscow",
+    test:is(res.tzoffset, msd_offset, "2000-07-01T00:00:00 - summer")
+
+    res = T2000 + m2
+    test:is(tostring(res), "2000-03-01T00:00:00 Europe/Moscow",
         "value: 2000 + 2m")
-    test:is(tostring(T2000 + m2 + M2 + m2), "2000-07-01T00:00:00 Europe/Moscow",
-        "value: 2000 + 6m")
+    test:is(res.tzoffset, msk_offset, "2000-03-01T00:00:00 - winter")
 
+    res = T2000 + m2 + M2 + m2
+    test:is(tostring(res), "2000-07-01T00:00:00 Europe/Moscow",
+        "value: 2000 + 6m")
+    test:is(res.tzoffset, msd_offset, "2000-07-01T00:00:00 - summer")
 
     assert_raises_like(test, expected_interval_but,
                        function() return T1970 + 123 end)
```

**Comment by igormunkin** [comment]
Also backported to 2.10 in scope of 9f8b05a (2.10.3-20-g9f8b05ab0) and 8aa1347 (2.10.3-21-g8aa134746).
