### PR TITLE
net.box: support tab complete for stream and future v2

### LINKED ISSUE #6305: Explore and try to implement auto-completion for streams such as it implemented for connections.
Explore and try to implement auto-completion for streams such as it implemented for connections.
Streams use lazy space copy from connections, so auto-completion does not work for them. Explore the possibility of implementation auto-completion for streams.

### PR DESCRIPTION
**Pull request by sergos**
Provide console tab completion support for net.box objects of 'stream' and 'future'.

Closes #6305

### CODE REVIEW

File: src/box/lua/console.c [hunk 1]
```diff
@@ -760,14 +760,31 @@ lua_rl_dmadd(dmlist *ml, const char *p, size_t pn, const char *s, int suf)
...
 		return 0;
 	}
+	/* use __autocomplete metamethod if it's present */
+	lua_pushstring(L, "__autocomplete");
+	lua_rawget(L, -2);
+	if (lua_isfunction(L, -1)) {
+		lua_replace(L, -2);
+		lua_insert(L, -2);
+		if (lua_pcall(L, 1, 1, 0) != 0) {
+			lua_pop(L, 2);
```
Comment (locker) [inline src/box/lua/console.c:781]: This isn't entirely correct: if the function call fails, the metatable won't be on the stack (because you replaced it with the function) and so the code below (fallback on `__index`) won't work.

I think we don't need to handle `__autocomplete` function error, because it's a bug in the user code. The best we can do is to log the error, but even that is optional - I think it's okay to silently swallow it and exit. No fallback on `__index` is necessary in case of error:

File: test/box-luatest/gh_6305_autocomplete_metamethod_test.lua [hunk 2]
```diff
@@ -0,0 +1,54 @@
+local t = require('luatest')
```
Comment (locker) [inline test/box-luatest/gh_6305_autocomplete_metamethod_test.lua:1]: You don't need box for this test so please move this to the `app-luatest` suite.

File: test/box-luatest/gh_6305_autocomplete_metamethod_test.lua [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+local g = t.group()
+local console = require('console')
+
+local function tabcomplete(s)
+        return console.completion_handler(s, 0, #s)
```
Comment (locker) [inline test/box-luatest/gh_6305_autocomplete_metamethod_test.lua:6]: We use four spaces for indentation in Lua source files. Please fix.

File: src/box/lua/net_box.lua [hunk 4]
```diff
@@ -165,7 +165,8 @@ local function stream_wrap_index(stream_id, src)
         _src = src,
     }, {
         __index = src,
-        __serialize = stream_index_serialize
+	__serialize = stream_index_serialize,
+	__autocomplete = stream_index_serialize
```
Comment (locker) [inline src/box/lua/net_box.lua:169]: Bad indentation. Please don't use tabs in Lua files. Fix here and everywhere else in this patch.

File: src/box/lua/net_box.c [hunk 5]
```diff
@@ -1735,6 +1735,13 @@ luaT_netbox_request_gc(struct lua_State *L)
 	return 0;
 }
 
+static int
+luaT_netbox_request_autocomplete(struct lua_State *L)
+{
+	lua_getmetatable(L, -1);
+	return 1;
```
Comment (locker) [inline src/box/lua/net_box.c:1742]: This isn't all we need to do AFAIU.

It's possible to add userdata to a future object:

```lua
local f = f = c:call('foo', {}, {is_async = true})
f.bar = 123
f.bar -- 123
```

We want user keys to be auto-completed as well.

**Review by locker — CHANGES_REQUESTED** [review]
1. Please don't create a new PR after each review iteration.
2. Please link the PR to the issue by adding `Closes #XXXX` to the PR description.
3. See a few comments inline.

File: test/box-luatest/gh_6305_autocomplete_metamethod_test.lua (hunk 2 above)
Comment (sergos) [reply test/box-luatest/gh_6305_autocomplete_metamethod_test.lua:1]: moved

File: src/box/lua/net_box.c (hunk 5 above)
Comment (sergos) [reply src/box/lua/net_box.c:1747]: Ok, I made it through the adding an `__autocomplete` metamethod at the moment of new `netbox_request` got it new index table (in fact, only after user value is added). So that the `netbox_request` type will perform the serialization of the index itself, and the metatable of the latter will have chained `__autocomplete` that will deliver the type's completion.

**Comment by sergos** [comment]
Updated, rebased.

File: test/box-luatest/gh_6305_autocomplete_metamethod_test.lua (hunk 3 above)
Comment (sergos) [reply test/box-luatest/gh_6305_autocomplete_metamethod_test.lua]: fixed

File: src/box/lua/net_box.lua (hunk 4 above)
Comment (locker) [reply src/box/lua/net_box.lua]: Presently, luacheck doesn't check coding style. It'd be nice if it did though. We can also make checkpatch warn about tabs in Lua files.

Comment (locker) [reply src/box/lua/net_box.lua]: I patched checkpatch to warn about tabs in all files except C source files.

File: changelogs/unreleased/gh-6305-net-box-autocomplete.md [hunk 6]
```diff
@@ -0,0 +1,4 @@
+## feature/net.box
```
Comment (locker) [inline changelogs/unreleased/gh-6305-net-box-autocomplete.md:1]: There's no such section as 'net.box':

https://github.com/tarantool/tarantool/blob/b99ac0b4abd2b1beaf7e14123107fd07fb8db4ec/tools/gen-release-notes#L14-L17

Let's use `feature/lua` instead.

File: test/box-luatest/gh_6305_net_box_autocomplete_test.lua [hunk 7]
```diff
@@ -0,0 +1,130 @@
...
+    r = tabcomplete('future1.')
+    t.assert_equals(r, {'future1.',
+                        'future1.user1',
+                        'future1.wait_result(',
+                        'future1.result(',
+                        'future1.discard(',
+                        'future1.pairs(',
+                        'future1.is_ready(',
+                        })
+
```
Comment (locker) [inline test/box-luatest/gh_6305_net_box_autocomplete_test.lua:129]: Nit: redundant blank line. Please remove.

**Review by locker — CHANGES_REQUESTED** [review]
Looks good! Just a couple of nitpicks.

File: changelogs/unreleased/gh-6305-net-box-autocomplete.md (hunk 6 above)
Comment (sergos) [reply changelogs/unreleased/gh-6305-net-box-autocomplete.md]: done. 
let's add some checker in checkpatch?

Comment (sergos) [reply changelogs/unreleased/gh-6305-net-box-autocomplete.md]: Actually, the [release-notes check](https://github.com/tarantool/tarantool/runs/5587899797?check_suite_focus=true) shows the Netbox clause in release notes

#### Netbox

* Added `return_raw` net.box option for returning `msgpack.object` instead of
  decoding the response (gh-4861).

**Comment by sergos** [comment]
Updated, rebased.

File: changelogs/unreleased/gh-6305-net-box-autocomplete.md (hunk 6 above)
Comment (locker) [reply changelogs/unreleased/gh-6305-net-box-autocomplete.md]: Too bad. There's also Net.box section...

```
#### Netbox

* Added `return_raw` net.box option for returning `msgpack.object` instead of
  decoding the response (gh-4861).

...

### Net.box

* Changed the type of the error returned by net.box on timeout
  from ClientError to TimedOut (gh-6144).
```

We need to fix it and add a check to tools/gen-release-notes.

**Review by locker — APPROVED** [review]
