### PR TITLE
config: handle box.cfg's TT_* env vars

### LINKED ISSUE #9485: Listen socket is not created after restart of the instance, if set using environmental variable.
**Bug description**
If setting box.cfg{listen} using "TT_LISTEN" environmental variable, socket is not created after restart of the instance.

* OS: Linux
* OS Version: Ubuntu 20.04.6 LTS
* Architecture: x86_64
```
Tarantool 3.0.0-beta1-0-g18eaeb7
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/tmp/tarantool_install357019311/dynamic-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: GNU-9.4.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool_install357019311=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool_install357019311=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 
```

**Steps to reproduce**

Config file:
```
credentials:
  users:
    guest:
      roles: [super]

log:
  to: file
  file: tnt_{{ instance_name }}.log

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          master: {}
```
Instances file:
```
master:

```

Set environmental variable 'TT_LISTEN':
```
better0fdead@better0fdead:~/tt-system$ pwd
/home/better0fdead/tt-system
better0fdead@better0fdead:~/tt-system$ export TT_LISTEN=/home/better0fdead/tt-system/t.sock
```

Start tarantool instance.

```
better0fdead@better0fdead:~/tt-system$ tarantool --name master --config ./config.yml 
```

In another console check that socket was created.
```
better0fdead@better0fdead:~$ cd tt-system/
better0fdead@better0fdead:~/tt-system$ ls 
config.yml  instances.yml  tnt_master.log  t.sock  var
```

Stop instance and start again.
```
^Cbetter0fdead@better0fdead:~/tt-system$ tarantool --name master --config ./config.yml 
```

In another console check  that socket is not here.
```
better0fdead@better0fdead:~/tt-system$ ls -al
total 28
drwxrwxr-x  3 better0fdead better0fdead 4096 дек 14 14:41 .
drwxr-xr-x 40 better0fdead better0fdead 4096 дек 14 14:38 ..
-rw-rw-r--  1 better0fdead better0fdead  210 дек 12 15:58 config.yml
-rw-rw-r--  1 better0fdead better0fdead    9 ноя 30 01:37 instances.yml
-rw-r-----  1 better0fdead better0fdead 8135 дек 14 14:41 tnt_master.log
drwxrwxr-x  4 better0fdead better0fdead 4096 дек 14 14:39 var
```

Check env:
```
better0fdead@better0fdead:~/tt-system$ printenv | grep 'TT_LISTEN'
TT_LISTEN=/home/better0fdead/tt-system/t.sock
```

Log file:
```
2023-12-14 14:39:39.101 [11734] main/103/interactive I> Tarantool 3.0.0-beta1-0-g18eaeb7 Linux-x86_64-Debug
2023-12-14 14:39:39.101 [11734] main/103/interactive I> log level 5 (INFO)
2023-12-14 14:39:39.101 [11734] main/103/interactive I> wal/engine cleanup is paused
2023-12-14 14:39:39.102 [11734] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2023-12-14 14:39:39.102 [11734] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2023-12-14 14:39:39.102 [11734] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2023-12-14 14:39:39.109 [11734] main/103/interactive I> update replication_synchro_quorum = 1
2023-12-14 14:39:39.109 [11734] main/103/interactive I> instance uuid 4f26aeaf-db23-6762-000a-393c973eddbe
2023-12-14 14:39:39.109 [11734] main/103/interactive I> tx_binary: bound to unix/:(socket)
2023-12-14 14:39:39.109 [11734] main/103/interactive I> initializing an empty data directory
2023-12-14 14:39:39.124 [11734] main/103/interactive I> assigned id 1 to replica 4f26aeaf-db23-6762-000a-393c973eddbe
2023-12-14 14:39:39.125 [11734] main/103/interactive I> update replication_synchro_quorum = 1
2023-12-14 14:39:39.125 [11734] main/103/interactive I> assigned name master to replica 4f26aeaf-db23-6762-000a-393c973eddbe
2023-12-14 14:39:39.125 [11734] main/103/interactive I> replicaset uuid 2ab78dc2-4652-3699-00e4-12df0ae32351
2023-12-14 14:39:39.125 [11734] main/103/interactive I> replicaset name: replicaset-001
2023-12-14 14:39:39.126 [11734] snapshot/101/main I> saving snapshot `var/lib/master/00000000000000000000.snap.inprogress'
2023-12-14 14:39:39.129 [11734] snapshot/101/main I> done
2023-12-14 14:39:39.129 [11734] main/103/interactive I> ready to accept requests
2023-12-14 14:39:39.129 [11734] main/104/gc I> wal/engine cleanup is resumed
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'custom_proc_title' configuration option to "tarantool - master"
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'instance_name' configuration option to "master"
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'log' configuration option to "file:tnt_master.log"
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'log_nonblock' configuration option to false
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'replicaset_name' configuration option to "replicaset-001"
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'instance_uuid' configuration option to "4f26aeaf-db23-6762-000a-393c973eddbe"
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'listen' configuration option to "/home/better0fdead/tt-system/t.sock"
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'replicaset_uuid' configuration option to "2ab78dc2-4652-3699-00e4-12df0ae32351"
2023-12-14 14:39:39.130 [11734] main/103/interactive/box.load_cfg I> set 'metrics' configuration option to {"labels":{"alias":"master"},"include":["all"],"exclude":[]}
2023-12-14 14:39:39.130 [11734] main/105/checkpoint_daemon I> scheduled next checkpoint for Thu Dec 14 16:02:15 2023
2023-12-14 14:39:39.135 [11734] main/114/console/unix/:./var/run/master/tarantool.control/socket I> started
2023-12-14 14:39:39.136 [11734] main I> entering the event loop
2023-12-14 14:41:30.760 [11734] main C> got signal 2 - Interrupt
2023-12-14 14:41:30.760 [11734] main/117/iproto.shutdown I> tx_binary: stopped
2023-12-14 14:41:32.362 [11924] main/103/interactive I> Tarantool 3.0.0-beta1-0-g18eaeb7 Linux-x86_64-Debug
2023-12-14 14:41:32.363 [11924] main/103/interactive I> log level 5 (INFO)
2023-12-14 14:41:32.363 [11924] main/103/interactive I> wal/engine cleanup is paused
2023-12-14 14:41:32.364 [11924] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2023-12-14 14:41:32.364 [11924] main/103/interactive I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2023-12-14 14:41:32.364 [11924] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2023-12-14 14:41:32.364 [11924] main/103/interactive/box.upgrade I> Recovering snapshot with schema version 3.0.0
2023-12-14 14:41:32.369 [11924] main/103/interactive I> update replication_synchro_quorum = 1
2023-12-14 14:41:32.369 [11924] main/103/interactive I> instance uuid 4f26aeaf-db23-6762-000a-393c973eddbe
2023-12-14 14:41:32.369 [11924] main/103/interactive I> instance vclock {1: 1}
2023-12-14 14:41:32.369 [11924] main/103/interactive I> tx_binary: bound to unix/:(socket)
2023-12-14 14:41:32.369 [11924] main/103/interactive I> recovery start
2023-12-14 14:41:32.369 [11924] main/103/interactive I> recovering from `var/lib/master/00000000000000000000.snap'
2023-12-14 14:41:32.377 [11924] main/103/interactive I> replicaset name: replicaset-001
2023-12-14 14:41:32.377 [11924] main/103/interactive I> replicaset uuid 2ab78dc2-4652-3699-00e4-12df0ae32351
2023-12-14 14:41:32.384 [11924] main/103/interactive I> assigned id 1 to replica 4f26aeaf-db23-6762-000a-393c973eddbe
2023-12-14 14:41:32.384 [11924] main/103/interactive I> update replication_synchro_quorum = 1
2023-12-14 14:41:32.384 [11924] main/103/interactive I> assigned name master to replica 4f26aeaf-db23-6762-000a-393c973eddbe
2023-12-14 14:41:32.384 [11924] main/103/interactive I> recover from `var/lib/master/00000000000000000000.xlog'
2023-12-14 14:41:32.384 [11924] main/103/interactive I> done `var/lib/master/00000000000000000000.xlog'
2023-12-14 14:41:32.384 [11924] main/103/interactive I> recover from `var/lib/master/00000000000000000001.xlog'
2023-12-14 14:41:32.384 [11924] main/103/interactive I> done `var/lib/master/00000000000000000001.xlog'
2023-12-14 14:41:32.385 [11924] main/103/interactive I> ready to accept requests
2023-12-14 14:41:32.385 [11924] main/103/interactive I> leaving orphan mode
2023-12-14 14:41:32.385 [11924] main/104/gc I> wal/engine cleanup is resumed
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'custom_proc_title' configuration option to "tarantool - master"
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'instance_name' configuration option to "master"
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'log' configuration option to "file:tnt_master.log"
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'log_nonblock' configuration option to false
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'replicaset_name' configuration option to "replicaset-001"
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'instance_uuid' configuration option to "4f26aeaf-db23-6762-000a-393c973eddbe"
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'listen' configuration option to "/home/better0fdead/tt-system/t.sock"
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'replicaset_uuid' configuration option to "2ab78dc2-4652-3699-00e4-12df0ae32351"
2023-12-14 14:41:32.385 [11924] main/103/interactive/box.load_cfg I> set 'metrics' configuration option to {"labels":{"alias":"master"},"include":["all"],"exclude":[]}
2023-12-14 14:41:32.385 [11924] main/105/checkpoint_daemon I> scheduled next checkpoint for Thu Dec 14 16:27:03 2023
2023-12-14 14:41:32.392 [11924] main/103/interactive I> tx_binary: stopped
2023-12-14 14:41:32.392 [11924] main/103/interactive/box.load_cfg I> set 'listen' configuration option to null
2023-12-14 14:41:32.392 [11924] main/103/interactive I> update replication_synchro_quorum = 1
2023-12-14 14:41:32.393 [11924] main/105/checkpoint_daemon I> scheduled next checkpoint for Thu Dec 14 15:49:17 2023
2023-12-14 14:41:32.395 [11924] main/103/interactive/socket I> tcp_server: remove dead UNIX socket: ./var/run/master/tarantool.control
2023-12-14 14:41:32.396 [11924] main/117/console/unix/:./var/run/master/tarantool.control/socket I> started
2023-12-14 14:41:32.396 [11924] main I> entering the event loop
```

**Actual behavior**

After restart of the instance socket is not created.

**Expected behavior**

After restart of the instance socket is created.

### PR DESCRIPTION
**Pull request by Totktonada**
There may be some confusion, so let's start with a background information.

There are `TT_*` environment variables introduced in commit 1b330121ec7d ("box: set box.cfg options via environment variables"). They're interpreted by the `box.cfg()` call.

There are `TT_*` environment variables introduced in commit 82b0cff9d63b ("config: introduce env source"). They're interpreted by the declarative configuration logic, when tarantool starts with the `--name <...>` CLI option.

box.cfg's env variables have names deduced from box.cfg option names, while config's env variable names are deduced from the config schema.

Some options have the same names here and there, for example `TT_REPLICATION_ANON` (from `box.cfg.replication_anon` and `replication.anon`). However, there are ones that have different names, for example `TT_LISTEN` and `TT_IPROTO_LISTEN`.

Moreover, the declarative configuration has its own restrictions on the configuration data. For example, `TT_IPROTO_LISTEN` is always a list of URIs (like `[{"uri": <...>, "params": {<...>}}]`), not a single URI, not a string, not a number. The declarative configuration has a certain shape and doesn't allow polymorphic values.

Next, handling of box.cfg's variables by the old code in `load_cfg.lua` doesn't work well with the declarative configuration flow.

The main reason is that the new configuration flow calls `box.cfg()` with all the `box.cfg` values set, including default ones. If a user removes an option from its config, it applies its default. On the same time it instructs `box.cfg()` to don't read the corresponding environment variables.

This commit offers a partial solution: it adds support of the most of the box.cfg environment variables. The values are added into the configuration data with the lowest priority: if the same value is set in, for example, a file configuration, the file's value is preferred.

The following box.cfg's environment variables are not handled in this commit.

* `TT_LOG`
* `TT_METRICS`
* `TT_INSTANCE_NAME`
* `TT_REPLICASET_NAME`
* `TT_CLUSTER_NAME`
* `TT_FORCE_RECOVERY`,
* `TT_READ_ONLY`
* `TT_BOOTSTRAP_LEADER`
* `TT_REPLICATION`
* `TT_REPLICATION_CONNECT_QUORUM`

Fixes #9485

### CODE REVIEW

**Review by andreyaksenov — APPROVED** [review]

**Review by ImeevMA — APPROVED** [review]
Thanks for the patch!

File: src/box/lua/config/source/env.lua [hunk 1]
```diff
@@ -75,6 +104,30 @@ end
...
+            if w.schema.box_cfg ~= nil then
+                local value = box.internal.cfg.env[w.schema.box_cfg]
+                if value ~= nil then
+                    -- TT_LISTEN and TT_REPLICATION needs a
+                    -- special handling, because config's schema
+                    -- is more strict regarding a form an URI.
+                    if w.schema.box_cfg == 'listen' then
+                        value = normalize_uri_list(value)
+                    elseif w.schema.box_cfg == 'replication' then
+                        value = normalize_uri_list(value)
```
Comment (Totktonada) [inline src/box/lua/config/source/env.lua:123]: That's incorrect. `replication.peers` is an array of strings. However, we possibly will update it to a list of instance names (in a separate PR).

File: src/box/lua/config/source/env.lua [hunk 2]
```diff
@@ -75,6 +104,30 @@ end
...
 
+    -- Handle old TT_* box.cfg()'s environment variables such as
+    -- IPROTO_LISTEN.
+    --
+    -- TODO: Here we miss all the options without 'box_cfg'
+    -- annotation: at least 'log', 'audit_log' and 'metrics'.
+    if self.name == 'env (default)' then
+        for _, w in instance_config:pairs() do
+            if w.schema.box_cfg ~= nil then
+                local value = box.internal.cfg.env[w.schema.box_cfg]
```
Comment (Totktonada) [inline src/box/lua/config/source/env.lua:115]: It is affected by #9539. Maybe it worth to fix or workaround it.

File: test/config-luatest/box_cfg_env_test.lua [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    end)
+    g.server:wait_until_ready()
+
+    -- Just do some request.
+    local c = net_box.connect(net_box_uri)
+    local info = c:call('box.info')
+    t.assert_equals(info.id, 1)
+end
+
+-- Verify that TT_IPROTO has lower priority than cluster config's
```
Comment (Totktonada) [inline test/config-luatest/box_cfg_env_test.lua:63]: No TT_REPLICATION test.

Let's also add tests for a string option, a numeric option, a test with JSON object and JSON array in an environment variable.

Comment (Totktonada) [reply test/config-luatest/box_cfg_env_test.lua:63]: > No TT_REPLICATION test.

It is irrelevant due to #9541.

File: src/box/lua/config/source/env.lua (hunk 1 above)
Comment (Totktonada) [reply src/box/lua/config/source/env.lua:123]: I'm going to eliminate `TT_REPLICATION` logic at all due to #9541.

**Comment by Totktonada** [comment]
@ImeevMA I've significantly changed the code and the test (see my comments in the pull request above). So, I would appreciate if you'll do a second look. Sorry for the false start.

File: src/box/lua/config/source/env.lua (hunk 1 above)
Comment (Totktonada) [reply src/box/lua/config/source/env.lua]: Updated.

File: src/box/lua/config/source/env.lua (hunk 2 above)
Comment (Totktonada) [reply src/box/lua/config/source/env.lua]: Fixed in PR #9544.

File: test/config-luatest/box_cfg_env_test.lua (hunk 3 above)
Comment (Totktonada) [reply test/config-luatest/box_cfg_env_test.lua:58]: Added more test cases.

**Review by ImeevMA — APPROVED** [review]
Thank you for the changes! Now it looks more complete. LGTM.

**Review by ochaplashkin — APPROVED** [review]
