### PR TITLE
election: fix box.ctl.demote() nop in off-mode

### LINKED ISSUE #6860: box.ctl.demote() and synchro queue owner interaction is inconsistent.
**Bug description**

box.ctl.demote() and synchro queue owner interaction is inconsistent.

Running box.ctl.demote() with election_mode = 'off' sets synchro queue owner to NIL.
Running box.ctl.demote() with election_mode = 'manual' leaves synchro queue owner as is.

**Steps to reproduce**

```lua
box.cfg{election_mode = 'manual'}
box.ctl.promote()
box.ctl.demote()
box.cfg{election_mode = 'off'}
box.schema.create_space('test'):create_index('pk')
box.space.test:replace({1})
box.ctl.demote()
box.space.test:replace({1})
```

This leads to not so obvious behaviour:
On leader node with election_mode = 'manual' run box.ctl.demote(), set box.cfg{replication_mode='off'} now this node (assuming no one else took synchro queue from it) is RW (for synchronous transactions too). Further calls to box.ctl.demote() will not do anything, because term was bumped during previous demote and now this node doesn't consider itself leader.

**Actual behavior**

Node is RW, it can't be demoted.

**Expected behavior**

I don't really know.

### PR DESCRIPTION
**Pull request by Gerold103**
box.ctl.demote() used not to do anything with election_mode='off' if the synchro queue didn't belong to the caller in the same term as the election state.

The reason could be that if the synchro queue term is "outdated", there is no guarantee that some other instance doesn't own it in the latest term right now.

The "problem" is that this could be workarounded easily by just calling promote + demote together.

There isn't much sense in fixing it for the off-mode because the only reasons off-mode exists are 1) for people who don't use synchro at all, 2) who did use it and want to stop. Hence they need demote just to disown the queue.

The patch "legalizes" the mentioned workaround by allowing to perform demote in off-mode even if the synchro queue term is old.

Closes #6860

NO_DOC=bugfix

### CODE REVIEW

File: src/box/box.cc [hunk 1]
```diff
@@ -2958,13 +2958,24 @@ box_demote(void)
...
-	if (!is_leader)
-		return 0;
+	const struct raft *raft = box_raft();
+	if (box_election_mode == ELECTION_MODE_OFF) {
+		assert(raft->state == RAFT_STATE_FOLLOWER);
+		if (raft->leader != REPLICA_ID_NIL) {
+			diag_set(ClientError, ER_NOT_LEADER, raft->leader);
+			return -1;
+		}
+		if (txn_limbo.owner_id == REPLICA_ID_NIL)
```
Comment (sergepetrenko) [inline src/box/box.cc:2968]: In the discussion [here](https://github.com/tarantool/tarantool/issues/6860#issuecomment-1663432137) I meant to skip the term check but not the owner check.

I suppose you removed the owner check because the actual limbo owner might be dead. But do we really want to allow any node to demote the possibly running queue owner?

Maybe leave the crutch with 'promote + demote' for the case when the queue owner is dead?

**Review by sergepetrenko — COMMENTED** [review]
Thanks for the patch!

File: src/box/box.cc (hunk 1 above)
Comment (Gerold103) [reply src/box/box.cc:2968]: The problem is that if you were an owner in an old term, you have no guarantees in the new term. And we don't even track the limbo owner. We only track the election leader. So we can't tell if the queue is owned by anybody else in the newest term.

You said *"Not checking the owner means you may "steal" the synchro queue from the current owner."*, but it still can happen with checking the owner. Because the fact that you were an owner in term N doesn't tell anything about the owner in the term N+1.

Do I miss anything?

Comment (sergepetrenko) [reply src/box/box.cc:2968]: Oh, I think I understood. Yes, indeed, there is no point in checking limbo owner for an old term (when synchro term is N, and election term is N + 1).

My point was that when the limbo term is up to date (equal to election term), it's better to check the limbo owner. Otherwise the running owner may be disrupted by anyone who issues a DEMOTE. And issuing demote on all replicaset nodes simultaneously will make all of them write a DEMOTE to WAL and thus lead to split-brain.

When the limbo term is outdated, it's fine to not check the owner. Even if there is another owner in term N + 1, our demote from term N will lead to split-brain and won't disrupt the owner in term N + 1.

Comment (Gerold103) [reply src/box/box.cc:2968]: > What do you think?

Agreed, done.

**Review by sergepetrenko — APPROVED** [review]
Thanks for the fixes!
LGTM.

**Comment by sergepetrenko** [comment]
@Gerold103, the test hangs occasionally. Please, take a look:
```
[029] replication-luatest/gh_6860_election_off_demot>                 [ fail ]
[029] Test failed! Output from reject file /tmp/t/rejects/replication-luatest/gh_6860_election_off_demote.reject:
[029] Tarantool version is 3.0.0-alpha1-48-g5c271cbd1
[029] TAP version 13
[029] 1..4
[029] # Started on Thu Aug 17 11:07:18 2023
[029] # Starting group: gh-6860
[029] ok     1	gh-6860.test_election_off_demote_self_no_leader
[029] not ok 2	gh-6860.test_election_off_demote_other_no_leader
[029] #   ...gey/Source/sptnt/test-run/lib/luatest/luatest/server.lua:344: Timed out to wait for "synchro queue term" condition for server (alias: server1, workdir: server1-IiT-fhoCY90I, pid: 123472) within 60s
[029] #   stack traceback:
[029] #   	...replication-luatest/gh_6860_election_off_demote_test.lua:126: in function 'gh-6860.test_election_off_demote_other_no_leader'
[029] #   	...
[029] #   	[C]: in function 'xpcall'
[029] ok     3	gh-6860.test_election_off_demote_other_same_term
[029] ok     4	gh-6860.test_election_off_demote_other_leader
[029] # Ran 4 tests in 61.000 seconds, 3 succeeded, 1 errored
[029] 
[029] [test-run server "luatest_server"] The log file /tmp/t/029_replication-luatest/gh_6860_election_off_demote_test.log has zero size

```

**Comment by Gerold103** [comment]
@sergepetrenko I've run the test a few thousand times but couldn't reproduce. Can you please double-check if you maybe have some local changes done?

**Comment by sergepetrenko** [comment]
@Gerold103, hm, yes, I can't reproduce the failure anymore. Sorry for the false alarm.

**Review by grafin — APPROVED** [review]
Thanks for the patch!

**Review by andreyaksenov — APPROVED** [review]

**Review by ylobankov — APPROVED** [review]
Tests LGTM

File: test/replication-luatest/gh_6860_election_off_demote_test.lua [hunk 2]
```diff
@@ -0,0 +1,196 @@
...
+local replicaset = require('luatest.replica_set')
+
+local g = t.group('gh-6860')
+
+local function replicaset_create(g)
+    g.replicaset = replicaset:new({})
+    local box_cfg = {
+        replication_timeout = 0.1,
+        replication_synchro_quorum = 2,
+        replication_synchro_timeout = 1000,
```
Comment (ochaplashkin) [inline test/replication-luatest/gh_6860_election_off_demote_test.lua:12]: too much value, isn't it?

Comment (Gerold103) [reply test/replication-luatest/gh_6860_election_off_demote_test.lua:12]: Why? I intentionally don't want to trigger any timeouts.
