### PR TITLE
popen: add `is_closed()` method

### LINKED ISSUE #11492: No straightforward way to check if popen handle is closed
All popen methods (except `close`) raise an `IllegalParams` error if the popen handle is closed:

```
tarantool> p = require('popen').new({'/bin/true'})
---
...

tarantool> p:close()
---
- true
...

tarantool> p:info()
---
- error: 'popen: attempt to operate on a closed handle'
...

tarantool> box.error.last():unpack()
---
- code: 0
  base_type: IllegalParams
  type: IllegalParams
  message: 'popen: attempt to operate on a closed handle'
  trace:
  - file: builtin/box/console.lua
    line: 429
...
```

This is inconvenient in case a popen handle is created and exported by another module, for example, [`tarantool/sideservice`](https://github.com/tarantool/sideservice), which may close it asynchronously at any moment. Intercepting an `IllegalParams` error doesn't look right.

I see the following ways to make the popen module more user-friendly in this regard:

- Make `info()` work even if the popen handle is closed.
- Add a separate method that could be used for checking if a popen handle is closed.
- Raise a special error instead of `IllegalParams` on an attempt to use a closed popen handle. Usage of a closed popen handle doesn't seem to be an illegal parameters issue anyway (all parameters are valid, the state isn't).

### PR DESCRIPTION
**Pull request by ImeevMA**
This commit adds a method to make it easier to check that popen handle is closed.

Closes #11492

@TarantoolBot document
Title: `popen_handle:is_closed()` method

The new `is_closed()` method returns `true` if the popen handle is closed, and `false` otherwise.

Usage example:

```lua
local ph = popen.new(<...>)
assert(ph:is_closed() == false)
...
ph:close()
assert(ph:is_closed() == true)
```

### CODE REVIEW

File: test/app-luatest/gh_11492_popen_is_closed_test.lua
Comment (locker) [inline test/app-luatest/gh_11492_popen_is_closed_test.lua:1]: I wouldn't add a new file. Instead, I'd add a new test case to `app-luatest/popen_test.lua`.

**Review by locker — APPROVED** [review]

File: test/app-luatest/gh_11492_popen_is_closed_test.lua [hunk 1]
```diff
@@ -0,0 +1,42 @@
+local popen = require('popen')
+
+local t = require('luatest')
+local g = t.group()
+
+g.test_popen_is_closed = function()
+    local ph = popen.new({'true'})
```
Comment (Totktonada) [inline test/app-luatest/gh_11492_popen_is_closed_test.lua]: Sadly, `popen` doesn't perform search in `PATH`, see #5044.

Use `/bin/true` (a path to the executable file) or `popen.shell` (to let the shell perform the `PATH` lookup).

**Review by Totktonada — APPROVED** [review]

File: test/app-luatest/gh_11492_popen_is_closed_test.lua
Comment (ImeevMA) [reply test/app-luatest/gh_11492_popen_is_closed_test.lua:1]: Thanks, fixed.

File: test/app-luatest/gh_11492_popen_is_closed_test.lua (hunk 1 above)
Comment (ImeevMA) [reply test/app-luatest/gh_11492_popen_is_closed_test.lua]: Thanks, fixed by using `popen.shell`.

File: changelogs/unreleased/gh-11492-popen-is-closed-method.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+## feature/lua/popen
+
+* Added `is_closed()` method to popen handle to check if the handle
+  has been closed (gh-11492).
```
Comment (lenkis) [inline changelogs/unreleased/gh-11492-popen-is-closed-method.md]:
```suggestion
* Added a new method, `is_closed()`, to popen handle to check if the handle
  has been closed (gh-11492).
```

**Review by lenkis — APPROVED** [review]

File: changelogs/unreleased/gh-11492-popen-is-closed-method.md (hunk 2 above)
Comment (ImeevMA) [reply changelogs/unreleased/gh-11492-popen-is-closed-method.md]: Thanks, fixed!
