### PR TITLE
box: fix function definition wrong options error message

### LINKED ISSUE #7972: Wrong error message in case invalid options are inserted into `box.space._func`
Reproduced with Tarantool 2.11.0-entrypoint-716-g339ae58fed6a. Tarantool 2.10 is affected as well.

Code:
```
box.space._func:auto_increment{box.session.euid(), 'foo', 0, 'lua', '', 'function', {}, 'any', 'none', 'none', false, false, true, {}, {is_multikey = 'BAD VALUE'}, '', os.date("%Y-%m-%d %H:%M:%S"), os.date("%Y-%m-%d %H:%M:%S")}
```

Result:

```
tarantool> box.space._func:auto_increment{box.session.euid(), 'foo', 0, 'lua', '', 'function', {}, 'any', 'none', 'none', false, false, true, {}, {is_multikey = 'BAD VALUE'}, '', os.date("%Y-%m-%d %H:%M:%S"), os.date("%Y-%m-%d %H:%M:%S")}
---
- error: 'Wrong space options: ''is_multikey'' must be boolean'
...
tarantool> box.error.last():unpack()
---
- code: 111
  base_type: ClientError
  type: ClientError
  message: 'Wrong space options: ''is_multikey'' must be boolean'
  trace:
  - file: ./src/box/opt_def.c
    line: 172
...
```

The error message has the `ER_WRONG_SPACE_OPTIONS` (111) error code, which should only be used in case invalid options are inserted into `box.space._space`. For `box.space._func` options, the error code and message should be different.

*The error handling code of the [`func_def_new_from_tuple()`](https://github.com/tarantool/tarantool/blob/339ae58fed6acf432dc716a56d29ab65ed1c408f/src/box/alter.cc#L3152) function, which raises this error, is very poorly [covered](https://coveralls.io/github/tarantool/tarantool). In particular, this error condition is never checked in our tests. In the scope of this issue, apart from fixing the error message, we should also add a test case for each of the uncovered error conditions in `func_def_new_from_tuple()`.*

Spotted by @Gumix in https://github.com/tarantool/tarantool/pull/7944#discussion_r1030806998.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Closes #7972

### CODE REVIEW

File: test/box-luatest/gh_7972_func_def_err_conditions_test.lua [hunk 1]
```diff
@@ -0,0 +1,194 @@
...
+
+        t.assert_error_msg_equals("Tuple field 3 (name) type does not " ..
+                                  "match one required by operation: " ..
+                                  "expected string, got nil", function()
+            box.space._func:auto_increment{box.session.euid(), nil, 0, 'lua',
+                                           '', 'function', {}, 'any', 'none',
+                                           'none', false, false, true, {},
+                                           setmap{}, '',
+                                           os.date("%Y-%m-%d %H:%M:%S"),
+                                           os.date("%Y-%m-%d %H:%M:%S")}
```
Comment (locker) [inline test/box-luatest/gh_7972_func_def_err_conditions_test.lua:33]: Nit: You could cache the date and then reuse it to save a few lines:

```Lua
local date = os.date("%Y-%m-%d %H:%M:%S")
```

**Review by locker — CHANGES_REQUESTED** [review]

File: test/box-luatest/gh_7972_func_def_err_conditions_test.lua [hunk 2]
```diff
@@ -0,0 +1,194 @@
...
+    cg.server = server:new({alias = 'dflt'})
+    cg.server:start()
+end)
+
+g.after_all(function(cg)
+    cg.server:drop()
+end)
+
+-- Checks uncovered function definition error conditions (see also coverage
+-- report https://coveralls.io/builds/56509110/source?filename=src%2Fbox%2Falter.cc).
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_7972_func_def_err_conditions_test.lua]: Not sure the link will expire, but removed it.

File: test/box-luatest/gh_7972_func_def_err_conditions_test.lua (hunk 1 above)
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_7972_func_def_err_conditions_test.lua]: Fixed.

**Review by locker — APPROVED** [review]
