### PR TITLE
console: fix memory leak

### LINKED ISSUE #6817: ASAN reports memory leak in readline
Tarantool version: 2.10.0-beta2-70-g5adc02f623f8

Steps to reproduce:

1. Build Tarantool with ASAN:
   ```sh
   CC=clang CXX=clang++ cmake -S. -Bbuild/release-asan -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_ASAN=ON
   make -Cbuild/release-asan -j16
   ```
2. Enable ASAN:
   ```sh
   export ASAN=ON
   export LSAN_OPTIONS=suppressions=${PWD}/asan/lsan.supp
   export ASAN_OPTIONS=heap_profile=0:unmap_shadow_on_exit=1:detect_invalid_pointer_pairs=1:symbolize=1:detect_leaks=1:dump_instruction_bytes=1:print_suppressions=0
   ```
3. Start Tarantool and type something in the console, then exit:
   ```
   $ build/release-asan/src/tarantool
   Tarantool 2.10.0-beta2-70-g5adc02f623f8
   type 'help' for interactive help
   tarantool> test
   ---
   - null
   ...
   
   tarantool>
   =================================================================
   ==57860==ERROR: LeakSanitizer: detected memory leaks
   
   Direct leak of 5 byte(s) in 1 object(s) allocated from:
       #0 0x4a79ed in malloc (/home/vlad/src/tarantool/tarantool/build/release-asan/src/tarantool+0x4a79ed)
       #1 0x7f8784c9300c in xmalloc (/lib/x86_64-linux-gnu/libreadline.so.8+0x3c00c)
   
   SUMMARY: AddressSanitizer: 5 byte(s) leaked in 1 allocation(s).
   ```

Looks like the typed-in command was stored in the readline history buffer. We need to either clean up the buffer on exit or add an exception. This blocks https://github.com/tarantool/tarantool-ee/issues/17.

### PR DESCRIPTION
**Pull request by locker**
According to the [readline library documentation](https://tiswww.case.edu/php/chet/readline/readline.html#SEC41), the callback passed to `rl_callback_handler_install` is supposed to free the string passed to it:

> As with readline(), the handler function should free the line when it it finished with it.

Our callback leaks it.

Closes #6817

### CODE REVIEW

File: test/app-luatest/gh_6817_console_memory_leak_test.lua [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+    int pipe(int pipefd[2]);
+    int dup2(int oldfd, int newfd);
+    ssize_t write(int fd, const void* buf, size_t count);
+]])
+
+-- Checks that ASAN doesn't detect any memory leaks when console is used.
+g.test_console_mem_leak = function()
+    local fd = ffi.new([[ int[2] ]])
+    t.assert_equals(ffi.C.pipe(fd), 0)
+    t.assert_equals(ffi.C.dup2(fd[0], 0), 0)
```
Comment (Totktonada) [inline test/app-luatest/gh_6817_console_memory_leak_test.lua:17]: Shouldn't we return the real stdin in, say, after_all() callback?

Comment (locker) [reply test/app-luatest/gh_6817_console_memory_leak_test.lua]: luatest shouldn't use stdin so I think it's okay to close it after the test (don't want to complicate things with dup). Done.

Comment (Totktonada) [reply test/app-luatest/gh_6817_console_memory_leak_test.lua]: Okay.

Ideally we should make this test isolated (when will implement https://github.com/tarantool/luatest/issues/191).

**Review by alyapunov — APPROVED** [review]
