### PR TITLE
relay: fix unterminated final_join thread

### LINKED ISSUE #8082: Assertion failed: (pm_atomic_load(&cord_count) == 0), function fiber_free, file fiber.c, line 2036
Caught while running the tests on Tarantool 2.11.0-entrypoint-805-g5493db7c7 with some additional patches. 
I'm not sure if the failure was induced by my changes or not, but still paste the output here for reference.
At first glance, my changes were unrelated to fiber cleanup or cord creation.

```
[008] replication/replicaset_ro_mostly.test.lua       memtx           
[008] 
[008] [Instance "replica_uuid_ro1" killed by signal: 6 (SIGABRT)]
[008] 
[008] Last 15 lines of Tarantool Log file [Instance "replica_uuid_ro1"][/tmp/t/008_replication/replica_uuid_ro1.log]:
[008] 2022-12-20 17:27:51.568 [94744] main/112/main I> subscribed replica 16d31a86-20f1-4654-b135-772898d319be at fd 24, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
[008] 2022-12-20 17:27:51.568 [94744] main/112/main I> remote vclock {1: 10} local vclock {1: 10}
[008] 2022-12-20 17:27:51.570 [94744] relay/unix/:(socket)/101/main I> recover from `/tmp/t/008_replication/replica_uuid_ro1/00000000000000000000.xlog'
[008] 2022-12-20 17:27:52.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> authenticated
[008] 2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> subscribed
[008] 2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> remote vclock {1: 10} local vclock {1: 10}
[008] 2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> RAFT: message {term: 1, state: follower} from 2
[008] 2022-12-20 17:27:52.128 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> leaving orphan mode
[008] 2022-12-20 17:27:52.816 [94744] main/179/main I> joining replica 4353153e-4195-423c-a89c-1011f48cd8e7 at fd 29, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
[008] 2022-12-20 17:27:52.960 [94744] main/179/main I> initial data sent.
[008] 2022-12-20 17:27:52.960 [94744] main/179/main I> assigned id 3 to replica 4353153e-4195-423c-a89c-1011f48cd8e7
[008] 2022-12-20 17:27:52.961 [94744] main/179/main I> update replication_synchro_quorum = 2
[008] 2022-12-20 17:27:52.994 [94744] main C> got signal 15 - Terminated: 15
[008] 2022-12-20 17:27:52.994 [94744] main/233/iproto.shutdown I> tx_binary: stopped
[008] Assertion failed: (pm_atomic_load(&cord_count) == 0), function fiber_free, file fiber.c, line 2036
[008] 
[008] Test.run() received the following error:
[008] Traceback (most recent call last):
[008]   File "/Users/s.petrenko/Source/sptnt/test-run/lib/test.py", line 195, in run
[008]     self.execute(server)
[008]   File "/Users/s.petrenko/Source/sptnt/test-run/lib/tarantool_server.py", line 390, in execute
[008]     ts.stop_nondefault(signal=signal.SIGKILL)
[008]   File "/Users/s.petrenko/Source/sptnt/test-run/lib/preprocessor.py", line 441, in stop_nondefault
[008]     for k, v in self.servers.items():
[008] RuntimeError: dictionary changed size during iteration
[008] 
[008] [ fail ]

```

Here are <details><summary>full replica_uuid_ro1 logs</summary>

```
Starting instance replica_uuid_ro1...
started
Run console at unix/:/tmp/t/008_replication/replica_uuid_ro1.control
started
mkdir /tmp/t/008_replication/replica_uuid_ro1
'strip_core' is set but unsupported
2022-12-20 17:27:49.844 [94744] main/103/replica_uuid_ro1 I> Tarantool 2.11.0-entrypoint-820-g16b42228c
2022-12-20 17:27:49.846 [94744] main/103/replica_uuid_ro1 I> log level 5
2022-12-20 17:27:49.846 [94744] main/103/replica_uuid_ro1 I> wal/engine cleanup is paused
2022-12-20 17:27:49.850 [94744] main/103/replica_uuid_ro1 I> mapping 268435456 bytes for memtx tuple arena...
2022-12-20 17:27:49.850 [94744] main/103/replica_uuid_ro1 I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2022-12-20 17:27:49.850 [94744] main/103/replica_uuid_ro1 I> mapping 134217728 bytes for vinyl tuple arena...
2022-12-20 17:27:49.866 [94744] main/103/replica_uuid_ro1 I> update replication_synchro_quorum = 1
2022-12-20 17:27:49.866 [94744] main/103/replica_uuid_ro1 I> instance uuid e684ab64-158d-4a1c-9784-fafa0452c555
2022-12-20 17:27:49.867 [94744] main/103/replica_uuid_ro1 I> tx_binary: bound to unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock
2022-12-20 17:27:49.867 [94744] main/103/replica_uuid_ro1 I> connecting to 2 replicas
2022-12-20 17:27:49.868 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> can't connect to master
2022-12-20 17:27:49.868 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock sio.c:210 E> SocketError: connect to unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock, called on fd 25, aka unix/:(socket): No such file or directory
2022-12-20 17:27:49.868 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> will retry every 1.00 second
2022-12-20 17:27:49.872 [94744] main/113/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock I> remote master e684ab64-158d-4a1c-9784-fafa0452c555 at unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock running Tarantool 2.11.0
2022-12-20 17:27:50.867 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> remote master 16d31a86-20f1-4654-b135-772898d319be at unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock running Tarantool 2.11.0
2022-12-20 17:27:50.868 [94744] main/103/replica_uuid_ro1 I> connected to 2 replicas
2022-12-20 17:27:50.868 [94744] main/103/replica_uuid_ro1 I> Checking if 16d31a86-20f1-4654-b135-772898d319be at cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock chose this instance as bootstrap leader
2022-12-20 17:27:50.868 [94744] main/103/replica_uuid_ro1 I> Checking if e684ab64-158d-4a1c-9784-fafa0452c555 at cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock chose this instance as bootstrap leader
2022-12-20 17:27:50.868 [94744] main/103/replica_uuid_ro1 I> initializing an empty data directory
2022-12-20 17:27:51.112 [94744] main/103/replica_uuid_ro1 I> assigned id 1 to replica e684ab64-158d-4a1c-9784-fafa0452c555
2022-12-20 17:27:51.112 [94744] main/103/replica_uuid_ro1 I> update replication_synchro_quorum = 1
2022-12-20 17:27:51.113 [94744] main/103/replica_uuid_ro1 I> cluster uuid c555db93-0ebb-444d-be07-360c9c8e01ee
2022-12-20 17:27:51.116 [94744] snapshot/101/main I> saving snapshot `/tmp/t/008_replication/replica_uuid_ro1/00000000000000000000.snap.inprogress'
2022-12-20 17:27:51.122 [94744] snapshot/101/main I> done
2022-12-20 17:27:51.123 [94744] main/103/replica_uuid_ro1 I> ready to accept requests
2022-12-20 17:27:51.123 [94744] main/107/gc I> wal/engine cleanup is resumed
2022-12-20 17:27:51.123 [94744] main/115/applier_ballot_watcher I> fiber `applier_ballot_watcher' has been cancelled
2022-12-20 17:27:51.123 [94744] main/115/applier_ballot_watcher I> fiber `applier_ballot_watcher': exiting
2022-12-20 17:27:51.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> failed to authenticate
2022-12-20 17:27:51.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock box.cc:3335 E> ER_LOADING: Instance bootstrap hasn't finished yet
2022-12-20 17:27:51.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> will retry every 1.00 second
2022-12-20 17:27:51.124 [94744] main/146/applier_ballot_watcher I> fiber `applier_ballot_watcher' has been cancelled
2022-12-20 17:27:51.124 [94744] main/146/applier_ballot_watcher I> fiber `applier_ballot_watcher': exiting
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'replication_sync_timeout' configuration option to 100
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'log' configuration option to "\/tmp\/t\/008_replication\/replica_uuid_ro1.log"
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'replication' configuration option to ["cluster@unix\/:\/private\/tmp\/t\/008_replication\/replica_uuid_ro1.sock","cluster@unix\/:\/private\/tmp\/t\/008_replication\/replica_uuid_ro2.sock"]
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'listen' configuration option to "\/private\/tmp\/t\/008_replication\/replica_uuid_ro1.sock"
2022-12-20 17:27:51.124 [94744] main/103/replica_uuid_ro1/box.load_cfg I> set 'instance_uuid' configuration option to "e684ab64-158d-4a1c-9784-fafa0452c555"
2022-12-20 17:27:51.125 [94744] main/108/checkpoint_daemon I> scheduled next checkpoint for Tue Dec 20 19:27:11 2022
2022-12-20 17:27:51.167 [94744] main I> entering the event loop
2022-12-20 17:27:51.390 [94744] main/112/main I> joining replica 16d31a86-20f1-4654-b135-772898d319be at fd 24, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
2022-12-20 17:27:51.448 [94744] main/112/main I> initial data sent.
2022-12-20 17:27:51.448 [94744] main/112/main I> assigned id 2 to replica 16d31a86-20f1-4654-b135-772898d319be
2022-12-20 17:27:51.448 [94744] main/112/main I> update replication_synchro_quorum = 2
2022-12-20 17:27:51.448 [94744] main/112/main I> RAFT: fencing paused
2022-12-20 17:27:51.553 [94744] relay/unix/:(socket)/101/main I> recover from `/tmp/t/008_replication/replica_uuid_ro1/00000000000000000000.xlog'
2022-12-20 17:27:51.554 [94744] main/112/main I> final data sent.
2022-12-20 17:27:51.568 [94744] main/112/main I> subscribed replica 16d31a86-20f1-4654-b135-772898d319be at fd 24, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
2022-12-20 17:27:51.568 [94744] main/112/main I> remote vclock {1: 10} local vclock {1: 10}
2022-12-20 17:27:51.570 [94744] relay/unix/:(socket)/101/main I> recover from `/tmp/t/008_replication/replica_uuid_ro1/00000000000000000000.xlog'
2022-12-20 17:27:52.124 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> authenticated
2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> subscribed
2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> remote vclock {1: 10} local vclock {1: 10}
2022-12-20 17:27:52.125 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> RAFT: message {term: 1, state: follower} from 2
2022-12-20 17:27:52.128 [94744] main/114/applier/cluster@unix/:/private/tmp/t/008_replication/replica_uuid_ro2.sock I> leaving orphan mode
2022-12-20 17:27:52.816 [94744] main/179/main I> joining replica 4353153e-4195-423c-a89c-1011f48cd8e7 at fd 29, aka unix/:/private/tmp/t/008_replication/replica_uuid_ro1.sock, peer of unix/:(socket)
2022-12-20 17:27:52.960 [94744] main/179/main I> initial data sent.
2022-12-20 17:27:52.960 [94744] main/179/main I> assigned id 3 to replica 4353153e-4195-423c-a89c-1011f48cd8e7
2022-12-20 17:27:52.961 [94744] main/179/main I> update replication_synchro_quorum = 2
2022-12-20 17:27:52.994 [94744] main C> got signal 15 - Terminated: 15
2022-12-20 17:27:52.994 [94744] main/233/iproto.shutdown I> tx_binary: stopped
Assertion failed: (pm_atomic_load(&cord_count) == 0), function fiber_free, file fiber.c, line 2036.
```

</details>

### PR DESCRIPTION
**Pull request by Serpentian**
Currently if tarantool exits during relay's final join stage,
corresponding thread isn't terminated. This cause the flakiness
of the replicaset_ro_mostly.test.lua.

Let's make a pointer to a relay, which is started during final join
stage, in the replica structure and cancel it, if it exists, via
replication_free() alongside with the subscribe thread.

Closes https://github.com/tarantool/tarantool/issues/8082
Closes https://github.com/tarantool/tarantool-qa/issues/272

NO_DOC=not user-visible
NO_TEST=fix flaky test
NO_CHANGELOG=not user-visible

### CODE REVIEW

**Comment by Serpentian** [comment]
I'm not sure if this patch needs or not separate test and changelog. It doesn't looks like it affects users in any way, as when the main thread returns, it kills the entire process and all associated threads. So threads were anyway cleared in release, but, of course, assertion failed and asan didn't like that.

As for the test, we cannot remove it from the fragile section and close https://github.com/tarantool/tarantool-qa/issues/272. When run thousands of times this one is reproduced:

<details><summary>Fail of replicaset_ro_mostly </summary>

```
[010] replication/replicaset_ro_mostly.test.lua       vinyl
[010]
[010] [Instance "replica_uuid_ro1" killed by signal: 6 (SIGABRT)]
[010]
[010] [test-run server "replica_uuid_ro1"] Last 15 lines of the log file /home/serpentian/Programming/tnt/tarantool/test/var/010_replication/replica_uuid_ro1.log:
[010] 2023-06-19 15:36:17.539 [175661] main/111/main I> remote vclock {1: 9} local vclock {1: 9}
[010] 2023-06-19 15:36:17.539 [175661] relay/unix/:(socket)/101/main I> recover from `/home/serpentian/Programming/tnt/tarantool/test/var/010_replication/replica_uuid_ro1/00000000000000000000.xlog'
[010] 2023-06-19 15:36:18.325 [175661] main/113/applier/cluster@unix/:/home/serpentian/Programming/tnt/tarantool/test/var/010_replication/replica_uuid_ro2.sock I> authenticated
[010] 2023-06-19 15:36:18.325 [175661] main/113/applier/cluster@unix/:/home/serpentian/Programming/tnt/tarantool/test/var/010_replication/replica_uuid_ro2.sock I> subscribed
[010] 2023-06-19 15:36:18.325 [175661] main/113/applier/cluster@unix/:/home/serpentian/Programming/tnt/tarantool/test/var/010_replication/replica_uuid_ro2.sock I> remote vclock {1: 9} local vclock {1: 9}
[010] 2023-06-19 15:36:18.325 [175661] main/113/applier/cluster@unix/:/home/serpentian/Programming/tnt/tarantool/test/var/010_replication/replica_uuid_ro2.sock I> RAFT: message {term: 1, state: follower} from 2
[010] 2023-06-19 15:36:18.326 [175661] main/113/applier/cluster@unix/:/home/serpentian/Programming/tnt/tarantool/test/var/010_replication/replica_uuid_ro2.sock I> leaving orphan mode
[010] 2023-06-19 15:36:18.571 [175661] main/302/main I> joining replica d984dfb3-e00e-4466-a359-a491a9e60276 at fd 33, aka unix/:(socket), peer of unix/:(socket)
[010] 2023-06-19 15:36:18.604 [175661] main/302/main I> initial data sent.
[010] 2023-06-19 15:36:18.604 [175661] main/302/main I> assigned id 3 to replica d984dfb3-e00e-4466-a359-a491a9e60276
[010] 2023-06-19 15:36:18.604 [175661] main/302/main I> update replication_synchro_quorum = 2
[010] 2023-06-19 15:36:18.621 [175661] relay/unix/:(socket)/101/main I> recover from `/home/serpentian/Programming/tnt/tarantool/test/var/010_replication/replica_uuid_ro1/00000000000000000000.xlog'
[010] 2023-06-19 15:36:18.623 [175661] main C> got signal 15 - Terminated
[010] 2023-06-19 15:36:18.623 [175661] main/480/iproto.shutdown I> tx_binary: stopped
[010] terminate called without an active exception
[001] replication/replicaset_ro_mostly.test.lua       memtx           [ pass ]
[010] 0] [pass: 59]
[010] Test.run() received the following error:
[010] Traceback (most recent call last):
[010]   File "/home/serpentian/Programming/tnt/tarantool/test-run/lib/test.py", line 200, in run
[010]     self.execute(server)
[010]   File "/home/serpentian/Programming/tnt/tarantool/test-run/lib/tarantool_server.py", line 390, in execute
[010]     ts.stop_nondefault(signal=signal.SIGKILL)
[010]   File "/home/serpentian/Programming/tnt/tarantool/test-run/lib/preprocessor.py", line 441, in stop_nondefault
[010]     for k, v in self.servers.items():
[010] RuntimeError: dictionary changed size during iteration
[010]
[010] [ fail ]
[010] Test "replication/replicaset_ro_mostly.test.lua", conf: "vinyl"
[010] 	from "fragile" list failed, rerunning ...

```

</details>

Which actually looks like a test-run problem, but I'm not sure. It says ` terminate called without an active exception` and kills the instance.

**Comment by sergepetrenko** [comment]
> Which actually looks like a test-run problem, but I'm not sure. It says  terminate called without an active exception and kills the instance.

But what about the 
```
[010] [Instance "replica_uuid_ro1" killed by signal: 6 (SIGABRT)]
```
?

Looks like it's a tarantool crash, not test-run problem

**Comment by Serpentian** [comment]
The test is stable from now on, I ran it 6k times. So, we can close two issues alongside. As I already said, It seems, that the patch needs neither test, as it was already tested in `replicaset_ro_mostly`, nor changelog, unterminated thread doesn't affect build release. Please, correct me, if I'm wrong.

File: src/box/replication.h [hunk 1]
```diff
@@ -401,6 +401,8 @@ struct replica {
 	struct applier *applier;
 	/** Relay thread. */
 	struct relay *relay;
+	/** Relay final join thread */
+	struct relay *relay_join;
```
Comment (sergepetrenko) [inline src/box/replication.h:405]: IMO storing the "join relay" separately from "normal relay" looks rather ugly. I'd suggest to resort to this hack only if reusing the normal "relay" field didn't work for some reason.

But it works: I tried the following dirty patch, and everything seems fine. Be careful when applying: you have to find a better way for determining that relay is joining (along the lines where `relay->replica == NULL` is replaced with `relay->stream.yield != relay_yield_and_send_heartbeat`)
<details><summary>diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 4a0536f7b..4dea8b62e 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -4203,6 +4203,13 @@ box_process_register(struct iostream *io, const struct xrow_header *header)
 			  "registration of non-anonymous nodes.");
 	}
 
+	/* Don't allow multiple relays for the same replica */
+	if (replica != NULL &&
+	    relay_get_state(replica->relay) == RELAY_FOLLOW) {
+		tnt_raise(ClientError, ER_CFG, "replication",
+			  "duplicate connection with the same replica UUID");
+	}
+
 	/* See box_process_join() */
 	box_check_writable_xc();
 	struct space *space = space_cache_find_xc(BOX_CLUSTER_ID);
@@ -4240,7 +4247,7 @@ box_process_register(struct iostream *io, const struct xrow_header *header)
 	 * (req.vclock, stop_vclock) so that it gets its
 	 * registration.
 	 */
-	relay_final_join(io, header->sync, &req.vclock, &stop_vclock);
+	relay_final_join(replica, io, header->sync, &req.vclock, &stop_vclock);
 	say_info("final data sent.");
 
 	RegionGuard region_guard(&fiber()->gc);
@@ -4403,7 +4410,8 @@ box_process_join(struct iostream *io, const struct xrow_header *header)
 	 * Final stage: feed replica with WALs in range
 	 * (start_vclock, stop_vclock).
 	 */
-	relay_final_join(io, header->sync, &start_vclock, &stop_vclock);
+	relay_final_join(replica, io, header->sync, &start_vclock,
+			 &stop_vclock);
 	say_info("final data sent.");
 
 	/* Send end of WAL stream marker */
diff --git a/src/box/relay.cc b/src/box/relay.cc
index a231018d6..27b43a59c 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -526,17 +526,20 @@ relay_final_join_f(va_list ap)
 }
 
 void
-relay_final_join(struct iostream *io, uint64_t sync,
+relay_final_join(struct replica *replica, struct iostream *io, uint64_t sync,
 		 struct vclock *start_vclock, struct vclock *stop_vclock)
 {
-	struct relay *relay = relay_new(NULL);
-	if (relay == NULL)
-		diag_raise();
-
+	struct relay *relay = replica->relay;
+	assert(relay->state != RELAY_FOLLOW);
+	/*
+	 * As a new thread is started for the final join stage, its cancellation
+	 * should be handled properly during unexpected shutdown, so, the
+	 * relay's pointer is saved in the replica structure and the thread is
+	 * cancelled during replication_free().
+	 */
 	relay_start(relay, io, sync, relay_send_row, relay_yield, UINT64_MAX);
 	auto relay_guard = make_scoped_guard([=] {
 		relay_stop(relay);
-		relay_delete(relay);
 	});
 	/*
 	 * Save the first vclock as 'received'. Because it was really received.
@@ -1212,7 +1215,7 @@ relay_send_row(struct xstream *stream, struct xrow_header *packet)
 {
 	struct relay *relay = container_of(stream, struct relay, stream);
 	/* Do not send heartbeats during a final join. */
-	if (relay->replica != NULL)
+	if (relay->stream.yield == relay_yield_and_send_heartbeat)
 		relay_send_heartbeat_on_timeout(relay);
 	if (packet->group_id == GROUP_LOCAL) {
 		/*
@@ -1247,7 +1250,7 @@ relay_send_row(struct xstream *stream, struct xrow_header *packet)
 	 * it). In the latter case packet's LSN is less than or equal to
 	 * local master's LSN at the moment it received 'SUBSCRIBE' request.
 	 */
-	if (relay->replica == NULL ||
+	if (relay->stream.yield != relay_yield_and_send_heartbeat ||
 	    packet->replica_id != relay->replica->id ||
 	    packet->lsn <= vclock_get(&relay->local_vclock_at_subscribe,
 				      packet->replica_id)) {
diff --git a/src/box/relay.h b/src/box/relay.h
index 733d6bc31..5bbc87e46 100644
--- a/src/box/relay.h
+++ b/src/box/relay.h
@@ -138,7 +138,7 @@ relay_initial_join(struct iostream *io, uint64_t sync, struct vclock *vclock,
  * @param sync      sync from incoming JOIN request
  */
 void
-relay_final_join(struct iostream *io, uint64_t sync,
+relay_final_join(struct replica *replica, struct iostream *io, uint64_t sync,
 		 struct vclock *start_vclock, struct vclock *stop_vclock);
 
 /**
```
</details>

**Comment by sergepetrenko** [comment]
> As I already said, It seems, that the patch needs neither test, as it was already tested in replicaset_ro_mostly, nor changelog, unterminated thread doesn't affect build release. Please, correct me, if I'm wrong.

I agree.

File: src/box/relay.cc [hunk 2]
```diff
@@ -1211,8 +1215,11 @@ static void
 relay_send_row(struct xstream *stream, struct xrow_header *packet)
 {
 	struct relay *relay = container_of(stream, struct relay, stream);
+	assert(relay->cord.id != 0);
+	assert(relay->cord.fiber->f == relay_subscribe_f ||
+	       relay->cord.fiber->f == relay_final_join_f);
 	/* Do not send heartbeats during a final join. */
-	if (relay->replica != NULL)
+	if (relay->cord.fiber->f == relay_subscribe_f)
```
Comment (Serpentian) [inline src/box/relay.cc:1222]: There're other ways to check whether the function is executed during join or subscribe, but this one seems to be the best from the side of code readability.

1. We can set different cord's names for join and subscribe (now it's the same on, which is created from fd). This one is not selected, as comparing strings is very costly.
2. We can check `replica->is_relay_healthy` as the status is not updated during final join, so it'll equal to false. It so no-obvious, don't really like that solution

File: src/box/replication.h (hunk 1 above)
Comment (Serpentian) [reply src/box/replication.h]: Reusing the same relay was am initial idea, however, it didn't work, as I didn't came with idea of fully prohibiting register while the relay is still alive.

File: src/box/relay.cc (hunk 2 above)
Comment (sergepetrenko) [reply src/box/relay.cc:1222]: I like the current approach.
Just let's rewrite it a bit:
```diff
diff --git a/src/box/relay.cc b/src/box/relay.cc
index d841db0b6..9f83bfecd 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -1215,11 +1215,12 @@ static void
 relay_send_row(struct xstream *stream, struct xrow_header *packet)
 {
        struct relay *relay = container_of(stream, struct relay, stream);
-       assert(relay->cord.id != 0);
-       assert(relay->cord.fiber->f == relay_subscribe_f ||
-              relay->cord.fiber->f == relay_final_join_f);
+       assert(cord() == &relay->cord);
+       assert(fiber()->f == relay_subscribe_f ||
+              fiber()->f == relay_final_join_f);
+       bool is_subscribe = fiber()->f == relay_subscribe_f;
        /* Do not send heartbeats during a final join. */
-       if (relay->cord.fiber->f == relay_subscribe_f)
+       if (is_subscribe)
                relay_send_heartbeat_on_timeout(relay);
        if (packet->group_id == GROUP_LOCAL) {
                /*
@@ -1254,8 +1255,7 @@ relay_send_row(struct xstream *stream, struct xrow_header *packet)
         * it). In the latter case packet's LSN is less than or equal to
         * local master's LSN at the moment it received 'SUBSCRIBE' request.
         */
-       if (relay->cord.fiber->f == relay_final_join_f ||
-           packet->replica_id != relay->replica->id ||
+       if (!is_subscribe || packet->replica_id != relay->replica->id ||
            packet->lsn <= vclock_get(&relay->local_vclock_at_subscribe,
                                      packet->replica_id)) {
                struct errinj *inj = errinj(ERRINJ_RELAY_BREAK_LSN,
```

**Review by sergepetrenko — COMMENTED** [review]
Looking good! Just one comment from me.

**Comment by Serpentian** [comment]
The failed test doesn't seem to be related to the patch. Cannot reproduce it on linux(

**Review by sergepetrenko — APPROVED** [review]
Thanks for the fixes!

Typo in the commit message:

`This cause the flakiness` -> `This causes the flakiness`

**Review by Gerold103 — APPROVED** [review]
Thanks for the patch!

**Comment by Serpentian** [comment]
Rebased, fixed commit message and rechecked, that the flaky test is fixed
