### PR TITLE
Authentication fixes

### LINKED ISSUE #8017: `box.session.on_auth` isn't triggered if the user doesn't exist
Reproduced with Tarantool 2.11.0-entrypoint-754-g2ed06651c317. Tarantool 2.10 is affected as well.

Reproducer:

```Lua
local net = require('net.box')

box.cfg{log_level = 'error', listen = 3301}

box.once('init', function()
    box.schema.user.create('bob')
    box.schema.user.passwd('bob', 'secret')
end)

box.session.on_auth(function(user, ok)
    print(string.format("auth user '%s': %s", user, ok and 'ok' or 'fail'))
end)

net.connect(box.cfg.listen, {user = 'bob', password = 'secret'}):close()
net.connect(box.cfg.listen, {user = 'bob', password = 'foobar'}):close()
net.connect(box.cfg.listen, {user = 'eve', password = 'foobar'}):close()

os.exit(0)
```

Result:

```
auth user 'bob': ok
auth user 'bob': fail
```

Note, there's no message about the failed authentication attempt for 'eve'.

### PR DESCRIPTION
**Pull request by locker**
This PR fixes two authentication-related issues:
- `box.session.on_auth` not invoked if the user doesn't exist.
- Different error is raised for existing and non-existing users if the authentication request is malformed.

Closes #8017
Closes https://github.com/tarantool/security/issues/21

### CODE REVIEW

File: src/box/authentication.cc [hunk 1]
```diff
@@ -36,22 +36,26 @@
...
+	struct on_auth_trigger_ctx auth_res = {
+		.user_name = user_name,
+		.user_name_len = user_name_len,
+		.is_authenticated = true,
+	};
+	struct user *user = user_find_by_name(user_name, user_name_len);
 	if (user == NULL) {
 		if (diag_get()->last->code == ER_NO_SUCH_USER) {
 			diag_clear(diag_get());
 			diag_set(ClientError, ER_CREDS_MISMATCH);
```
Comment (alyapunov) [inline src/box/authentication.cc]: Seems to be excess line.

**Review by alyapunov — APPROVED** [review]

**Comment by locker** [comment]
Also added a test for the case when the user exists, but is disabled (doesn't have "session" privilege):

<details><summary>diff</summary>

```diff
diff --git a/test/box-luatest/ghs_16_user_enumeration_test.lua b/test/box-luatest/ghs_16_user_enumeration_test.lua
index be68c64acb0f..d66207a3e897 100644
--- a/test/box-luatest/ghs_16_user_enumeration_test.lua
+++ b/test/box-luatest/ghs_16_user_enumeration_test.lua
@@ -47,6 +47,8 @@ g.before_all = function()
     g.server:start()
     g.server:exec(function()
         box.schema.user.create('test', {password = '1111'})
+        box.schema.user.create('disabled')
+        box.schema.user.revoke('disabled', 'session', 'universe')
     end)
 end
 
@@ -75,7 +77,7 @@ end
 -- https://github.com/tarantool/security/issues/21
 g.test_user_enum_on_malformed_auth = function()
     local uri = g.server.net_box_uri
-    for _, user in ipairs({'admin', 'test', 'no_such_user'}) do
+    for _, user in ipairs({'admin', 'test', 'disabled', 'no_such_user'}) do
         local msg = string.format("Invalid error for user '%s'", user)
         t.assert_equals(auth(uri, user, 42), {
             box.error.INVALID_MSGPACK,
```

</details>

**Comment by locker** [comment]
Cherry-picked to 2.10.
