### PR TITLE
memtx: fix use-after-free on background index build

### LINKED ISSUE #10620: Segfault in `index_replace`
See the following workflow run:
https://github.com/tarantool/tarantool/actions/runs/10964314154/job/30447684362
Seed: 74203

--- 
Backtrace
```
2024-09-20T18:31:23.8137880Z #1  0x5564606dd5e8 in crash_collect+256
2024-09-20T18:31:23.8138184Z #2  0x5564606ddffa in crash_signal_cb+100
2024-09-20T18:31:23.8138423Z #3  0x7fefbc7d8420 in __restore_rt+0
2024-09-20T18:31:23.8138631Z #4  0x556460488c21 in index_replace+77
2024-09-20T18:31:23.8138891Z #5  0x55646048d4fe in memtx_build_on_replace_rollback+250
2024-09-20T18:31:23.8139119Z #6  0x5564607145a5 in trigger_run_list(rlist*, void*)+126
2024-09-20T18:31:23.8139276Z #7  0x556460714671 in trigger_run+169
2024-09-20T18:31:23.8139459Z #8  0x55646054b300 in txn_rollback_one_stmt+58
2024-09-20T18:31:23.8139635Z #9  0x55646054cf21 in txn_complete_fail+420
2024-09-20T18:31:23.8139955Z #10 0x55646054d66b in txn_on_journal_write+765
2024-09-20T18:31:23.8140178Z #11 0x5564605b475c in journal_async_complete+93
2024-09-20T18:31:23.8140338Z #12 0x5564605b51ab in tx_schedule_queue+54
2024-09-20T18:31:23.8140528Z #13 0x5564605b526a in tx_complete_rollback+95
2024-09-20T18:31:23.8140836Z #14 0x5564605b5300 in tx_complete_batch+87
2024-09-20T18:31:23.8140980Z #15 0x5564606f30fb in cmsg_deliver+52
2024-09-20T18:31:23.8141212Z #16 0x5564606f3a71 in cbus_process+100
2024-09-20T18:31:23.8141485Z #17 0x556460574067 in tx_prio_cb(ev_loop*, ev_watcher*, int)+176
2024-09-20T18:31:23.8141687Z #18 0x556460aa9e09 in ev_invoke_pending+205
2024-09-20T18:31:23.8141839Z #19 0x556460aaad66 in ev_run+1501
2024-09-20T18:31:23.8142036Z #20 0x5564606ad26e in tarantool_lua_run_script+435
2024-09-20T18:31:23.8142166Z #21 0x55646041bb7d in main+2656
2024-09-20T18:31:23.8142403Z #22 0x7fefbc2aa083 in __libc_start_main+243
2024-09-20T18:31:23.8142531Z #23 0x556460418a2e in _start+46
```
Can't reproduce the issue locally.

### PR DESCRIPTION
**Pull request by drewdzzz**
When building an index in background, we create on_rollback triggers for tuples inserted concurrently. The problem here is on_rollback trigger has independent from `index` and `memtx_ddl_state` lifetime - it can be called after the index was build (and `memtx_ddl_state` is destroyed) and even after the index was altered. So, in order to avoid use-after-free in on_rollback trigger, let's drop all on_rollback triggers when the DDL is over. It's OK because all owners of triggers are already prepared, hence, in WAL or replication queue (since we build indexes in background only without MVCC so the transactions cannot yield), so if they are rolled back, the same will happen to the DDL.

Closes #10620

### CODE REVIEW

File: src/box/memtx_space.c [hunk 1]
```diff
@@ -1135,33 +1139,26 @@ memtx_build_on_replace_rollback(struct trigger *trigger, void *event)
...
-	state->rc = index_replace(state->index, stmt->new_tuple,
-				  stmt->old_tuple, DUP_REPLACE_OR_INSERT,
-				  &delete, &successor);
-	if (state->rc != 0) {
-		diag_move(diag_get(), &state->diag);
-		return 0;
-	}
+	int rc = index_replace(index, stmt->new_tuple, stmt->old_tuple,
+			       DUP_REPLACE_OR_INSERT, &delete, &successor);
+	VERIFY(rc == 0);
```
Comment (locker) [inline src/box/memtx_space.c:1155]: There's no point in using `VERIFY` instead of `assert` if the asserted statement has no side effects.

Anyway, why do you ignore the possible failure? Maybe, better return -1 in this case to make `txn_rollback_one_stmt()` panic?

File: src/box/memtx_space.c [hunk 2]
```diff
@@ -1125,7 +1125,11 @@ memtx_init_ephemeral_space(struct space *space)
  * corresponding on_rollback triggers to prevent rollbacked changes appearance.
  */
 struct index_build_on_rollback_data {
-	struct memtx_ddl_state *state;
+	/*
+	 * Weak reference to the index. Cannot store usual reference
+	 * since the index can be altered before rollback.
+	 */
+	struct index_weak_ref index_ref;
```
Comment (locker) [inline src/box/memtx_space.c:1132]: Using `index_weak_ref` for this is an overkill IMO. Let's just store `index->def->iid` and look up the index in `txn_stmt::space`.

File: changelogs/unreleased/gh-10620-crash-on-rollback-after-background-index-build.md [hunk 3]
```diff
@@ -0,0 +1,4 @@
+## bugfix/memtx
+
+* Fixed a crash when transaction concurrent with background index build
+  was rolled back due to WAL failure (gh-10620).
```
Comment (lenkis) [inline changelogs/unreleased/gh-10620-crash-on-rollback-after-background-index-build.md:4]:
```suggestion
* Fixed a crash when a transaction that was processed concurrently with background
   index build was rolled back due to WAL failure (gh-10620).
```

**Review by lenkis — APPROVED** [review]

File: src/box/memtx_space.c (hunk 1 above)
Comment (drewdzzz) [reply src/box/memtx_space.c]: > There's no point in using VERIFY instead of assert if the asserted statement has no side effects.

I used it to avoid `assert(rc == 0); (void)rc;` construction.
Anyway, the whole comment is outdated since I significantly reworked the patch.

File: src/box/memtx_space.c (hunk 2 above)
Comment (drewdzzz) [reply src/box/memtx_space.c]: I realised that it doesn't work - space cache contains the old space (the new one will be put there only when the new index is built). It worked only because `space_cache_version` wasn't updated and the `index_weak_ref` used to passed pointer and didn't lookup in the space cache.

I completely reworked the patch - the new approach is used.

File: src/box/memtx_space.c [hunk 4]
```diff
@@ -1171,13 +1198,37 @@ memtx_build_on_replace_rollback(struct trigger *trigger, void *event)
...
+	return 0;
+}
+
 /*
  * Struct to allocate by memtx_build_on_replace trigger
- * (on_rollback trigger with its data).
+ * (transactional triggers with their data).
  */
-struct on_rollback_trigger_with_data {
+struct txn_triggers_with_data {
```
Comment (locker) [inline src/box/memtx_space.c:1219]: I think `txn_trigger_with_data` and `index_build_txn_trigger_data` should be merged. You can access the structure form the trigger with `container_of` and `txn_stmt` is passed in `event`.

File: test/box-luatest/gh_10620_crash_on_rollback_after_background_index_build_test.lua
Comment (locker) [inline test/box-luatest/gh_10620_crash_on_rollback_after_background_index_build_test.lua:1]: Please move this test to `engine-luatest` suite and enable it for Vinyl.

File: src/box/memtx_space.c [hunk 5]
```diff
@@ -1231,30 +1282,38 @@ memtx_build_on_replace(struct trigger *trigger, void *event)
 	 * problem when rollbacked changes appears in
 	 * built-in-background index.
 	 */
-	struct on_rollback_trigger_with_data *on_rollback_associates = NULL;
+	struct txn_triggers_with_data *txn_triggers = NULL;
 	struct errinj *inj = errinj(ERRINJ_BUILD_INDEX_ON_ROLLBACK_ALLOC,
 				    ERRINJ_BOOL);
 	if (inj == NULL || inj->bparam == false) {
-		on_rollback_associates = region_aligned_alloc(
+		txn_triggers = region_aligned_alloc(
```
Comment (locker) [inline src/box/memtx_space.c:1289]: Let's use `xregion_aligned_alloc` here and drop the error injection.

File: test/box-luatest/gh_10620_crash_on_rollback_after_background_index_build_test.lua
Comment (drewdzzz) [reply test/box-luatest/gh_10620_crash_on_rollback_after_background_index_build_test.lua:1]: Good idea, done.

File: src/box/memtx_space.c (hunk 5 above)
Comment (drewdzzz) [reply src/box/memtx_space.c]: Done.

File: src/box/memtx_space.c [hunk 6]
```diff
@@ -1121,21 +1135,32 @@ memtx_init_ephemeral_space(struct space *space)
...
 
 /*
- * Ongoing index build state with statement used by
- * corresponding on_rollback triggers to prevent rollbacked changes appearance.
+ * Struct to allocate by memtx_build_on_replace trigger, contains
+ * transactional triggers with their data.
  */
-struct index_build_on_rollback_data {
+struct memtx_build_txn_triggers {
+	/** Link in memtx_ddl_state::txn_triggers. */
```
Comment (locker) [inline src/box/memtx_space.c:1142]: Let's rename the struct to `memtx_build_stmt_trigger`:
- No 's' at the end so as not to confuse it with an array/list. It's basically one trigger object executed on transaction statement commit or rollback.
- `stmt` to emphasize that it's a transaction statement trigger.

Let's also rename `memtx_ddl_state::txn_triggers` to `memtx_ddl_state::stmt_triggers` for consistency.

File: src/box/memtx_space.c [hunk 7]
```diff
@@ -1171,14 +1196,18 @@ memtx_build_on_replace_rollback(struct trigger *trigger, void *event)
...
-	struct index_build_on_rollback_data data;
-};
+static int
+memtx_build_on_replace_commit(struct trigger *trigger, void *event)
+{
+	(void)event;
+	struct memtx_build_txn_triggers *data = trigger->data;
+	rlist_del_entry(data, in_state);
+	return 0;
+}
```
Comment (locker) [inline src/box/memtx_space.c:1210]: We usually use `container_of` instead of passing a pointer to self in the trigger argument. The code below would look more familiar and clean to me:

```C
static int
memtx_build_on_replace_commit(struct trigger *base, void *event)
{
	(void)event;
	struct memtx_build_stmt_trigger *trigger =
		container_of(base, struct memtx_build_stmt_trigger, on_commit);
	rlist_del_entry(trigger, in_state);
	return 0;
}
```

Comment (drewdzzz) [reply src/box/memtx_space.c]: Hm, OK, done - now I don't pass any data to the trigger.

File: src/box/memtx_space.c (hunk 6 above)
Comment (drewdzzz) [reply src/box/memtx_space.c]: Thanks, looks better! Done.

**Review by locker — APPROVED** [review]

**Review by ligurio — APPROVED** [review]
