### PR TITLE
engine: abort writing transactions after ro switch

### LINKED ISSUE #9937: It's possible to commit a write transaction after becoming read-only with mvcc
**Bug description**

Tarantool version: 3.1.0-entrypoint-234-g4466deafee

Our read-only checks only work when corresponding write statements are executed, and not on transaction commit.
So if code executing a transaction writes something and then yields before commit (which's possible with MVCC), and the node becomes read-only during this yield, the commit will happen anyway, writing data on a read-only node.

Since the WAL write is initiated only on transaction commit, this means a node may continue writing data after becoming read-only, breaking all the expectations about being read-only.

**Steps to reproduce**

Run a single tarantool instance in interactive mode and issue:

```lua
-- Step 1.
box.cfg{memtx_use_mvcc_engine = true}
s = box.schema.space.create('test')
_ = s:create_index('pk')

-- Step 2.
fiber = require('fiber')
log = require('log')
fiber.new(function()
    box.begin()
    log.info("read-only status before yield is %s", box.info.ro)
    s:insert{1}
    fiber.sleep(5)
    log.info("read-only status after yield is %s", box.info.ro)
    box.commit()
end)
box.cfg{read_only = true}

-- Step 3. Wait a bit (until the transaction above is committed), then do:
s:fselect{}
```
**Actual behavior**

During step 2 the logs will show:
```
2024-04-11 13:47:18.040 [30674] main/117/lua/tarantool I> read-only status before yield is false
tarantool> box.cfg{read_only = true}
2024-04-11 13:47:18.345 [30674] main/104/interactive/box.load_cfg I> set 'read_only' configuration option to true
2024-04-11 13:47:23.038 [30674] main/117/lua/tarantool I> read-only status after yield is true
```
And step 3 output:
```

tarantool> s:fselect{}
---
- |-
  +-----+
  |col1 |
  +-----+
  |  1  |
  +-----+
...
```

**Expected behavior**

`box.commit()` from the example above should fail and throw an error.
Something like: `The node became read-only while the transaction was processed`.

### PR DESCRIPTION
**Pull request by LevKats**
The `switch_to_ro` callback was first introduced in the `engine_vtab` as a solution to the issue in vinyl, where it was possible to commit a transaction after becoming read-only. Since mvcc was introduced in the memtx engine, a similar issue became possible. A possible solution in the memtx engine with implementing the `switch_to_ro` callback would just abort all writing transactions related to memtx, so cross-engine transactions would be aborted in vinyl and memtx, which doesn't introduce a bug but seems redundant. So now we just abort all writing transactions disregarding the engine which resulted in the `switch_to_ro` callback becoming useless. It is now impossible for a fiber to awake and commit after switching the node to read-only. Also more explicit error messages were implemented to address this situation.

Fixes https://github.com/tarantool/tarantool/issues/9937
NO_DOC=bugfix

### CODE REVIEW

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+            t.assert_equals(insert_fiber:status(), "dead")
+        end)
+        t.assert_equals(#s:select(), 0)
+    end)
+    t.helpers.retrying({}, function()
+        t.assert(
+            cg.server:grep_log("ER_READONLY.*the node became read%-only.*")
+        )
+    end)
+end
```
Comment (Serpentian) [inline test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:41]: Let's add a test, that temporary and local txns are not aborted by switch to RO

File: src/box/txn.h [hunk 2]
```diff
@@ -576,18 +581,26 @@ txn_clear_flags(struct txn *txn, unsigned int flags)
...
-		return ER_TRANSACTION_YIELD;
-	else if (txn_has_flag(txn, TXN_IS_ABORTED_BY_TIMEOUT))
-		return ER_TRANSACTION_TIMEOUT;
-	else if (txn_has_flag(txn, TXN_IS_ROLLED_BACK))
-		return ER_TXN_ROLLBACK;
-	return ER_UNKNOWN;
+	if (txn_has_flag(txn, TXN_IS_ABORTED_RO_NODE)) {
+		struct error *e = diag_set(ClientError, ER_READONLY);
+		error_append_msg(e, " - ");
+		error_append_msg(e,
```
Comment (Serpentian) [inline src/box/txn.h:590]: I'd rather not do that, the message is pretty clear itself. Moreover, you won't have to change the function so dramatically, if just `ER_READONLY` will be returned. Up to you

File: src/box/memtx_engine.cc [hunk 3]
```diff
@@ -1552,6 +1552,12 @@ memtx_engine_memory_stat(struct engine *engine, struct engine_memory_stat *stat)
 							MEMTX_EXTENT_SIZE;
 }
 
+static void
+memtx_engine_switch_to_ro(struct engine *engine)
+{
+	memtx_tx_abort_writers_for_ro(engine);
+}
```
Comment (Serpentian) [inline src/box/memtx_engine.cc:1559]: Will applier txns be aborted, when e.g. the node switches from multimaster to single master? They should not and AFAICS, they'll now

And it'd be great to add that to tests also

**Review by Serpentian — COMMENTED** [review]
I really like the solution, beautiful one!

File: src/box/txn.h (hunk 2 above)
Comment (Serpentian) [reply src/box/txn.h:590]: After verbal discussion with @LevKats:

Actually, we should, the reason is added in box:

https://github.com/tarantool/tarantool/blob/413e4e2bb98cace8a4ed10b9d41043ffff4bc0ce/src/box/box.cc#L390-L393

We probably can export new function from box and call it here, if we wanna use `ER_READONLY`. The reason in returned error should be as in `box_check_writable` and not some abstract "the node became read-only while the transaction was processed".

Or we can consider introducing new errcode for ER_TRANSACTION_RO or smth like that

File: src/box/memtx_engine.cc (hunk 3 above)
Comment (Serpentian) [reply src/box/memtx_engine.cc:1559]: They won't, appliers use `n_applier_rows` instead of `n_new_rows`, as stated by @LevKats

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua (hunk 1 above)
Comment (LevKats) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:41]: Done

File: src/box/memtx_tx.c [hunk 4]
```diff
@@ -769,6 +769,22 @@ memtx_tx_abort_with_conflict(struct txn *txn)
...
 
+void
+memtx_tx_abort_writers_for_ro(struct engine *engine)
+{
+	struct txn *txn;
+	rlist_foreach_entry(txn, &txns, in_txns) {
+		if (txn->engines[engine->id] == NULL ||
+		    stailq_empty(&txn->stmts))
+			continue;
+		if (txn->n_new_rows != txn->n_local_rows &&
```
Comment (nshy) [inline src/box/memtx_tx.c:780]: AFAIU we should not abort for temporary and local spaces. Let's state the first condition explicitly. 

```c
`txn->n_new_rows != 0 && txn->n_new_rows != txn->n_local_rows`
```
It is logically same as in the PR but I guess explicit is preferable.

**Review by nshy — CHANGES_REQUESTED** [review]

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+
+g.test_try_commit_local_temporary_after_readonly = function(cg)
+    t.skip_if(cg.params.engine ~= 'memtx')
+    cg.server:exec(function(engine)
+        local st = box.schema.space.create('test_temp',
+                                           {engine = engine, temporary=true})
+        st:create_index('pk')
+        local sl = box.schema.space.create('test_local',
+                                           {engine = engine, is_local=true})
```
Comment (nshy) [inline test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:50]: Vinyl supports local spaces so we should check there is no abort with vinyl too. Looks like currently is not the case.

File: src/box/memtx_tx.c [hunk 6]
```diff
@@ -769,6 +769,22 @@ memtx_tx_abort_with_conflict(struct txn *txn)
 		rlist_del(&txn->in_read_view_txs);
 }
 
+void
+memtx_tx_abort_writers_for_ro(struct engine *engine)
+{
+	struct txn *txn;
+	rlist_foreach_entry(txn, &txns, in_txns) {
+		if (txn->engines[engine->id] == NULL ||
+		    stailq_empty(&txn->stmts))
```
Comment (nshy) [inline src/box/memtx_tx.c:778]: We don't need to check for `txn->stmts` I guess because we account rows below. Also let's leave only one if.

Looks like aborting should be done somewhere in common place because below we account rows for all engines.

**Review by nshy — CHANGES_REQUESTED** [review]

File: src/box/memtx_engine.cc (hunk 3 above)
Comment (Serpentian) [reply src/box/memtx_engine.cc:1559]: SInce the first yield will be when txn is already in prepared state and cannot be aborted (during commit), this cannot be reproduced, applier transactions won't be aborted, test is not needed

Comment (Serpentian) [reply src/box/memtx_engine.cc:1559]: There's a yield during checking format in `on_replace` for `_space`. We can try to abuse that and make the test independent from the engine: create two masters, set `ERRINJ_CHECK_FORMAT_DELAY_COUNTDOWN` to 1 on the first one, on the second one - `space:alter`, wait on the first one until `ERRINJ_CHECK_FORMAT_DELAY` is `true`, call` box.cfg{read_only = true}` there and make sure, that the txn is applied.

File: src/box/memtx_tx.c (hunk 6 above)
Comment (LevKats) [reply src/box/memtx_tx.c]: Fixed. See `engine_switch_to_ro` which became the common place.

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua (hunk 5 above)
Comment (LevKats) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua]: Fixed. See `test_try_commit_local_after_readonly`.

File: src/box/memtx_tx.c (hunk 4 above)
Comment (LevKats) [reply src/box/memtx_tx.c]: Fixed.

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+        t.helpers.retrying({}, function()
+            t.assert_equals(insert_fiber:status(), "dead")
+        end)
+        t.assert_equals(#s:select(), 0)
+    end)
+    t.helpers.retrying({}, function()
+        t.assert(
+            cg.server:grep_log("ER_READONLY.*")
+        )
+    end)
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:67]: Fixed: now we join the fiber in all tests and validate the error with `t.assert_error_covers`

File: src/box/txn.h (hunk 2 above)
Comment (LevKats) [reply src/box/txn.h]: Fixed. See `box_ro_state_msg`

File: src/box/vinyl.c [hunk 8]
```diff
@@ -2629,12 +2629,6 @@ vinyl_engine_abort_with_conflict(struct engine *engine, struct txn *txn)
 	vy_tx_abort_with_conflict_impl(tx);
 }
 
-static void
-vinyl_engine_switch_to_ro(struct engine *engine)
-{
-	vy_tx_manager_abort_writers_for_ro(engine);
```
Comment (Serpentian) [inline src/box/vinyl.c:2635]: It seems, that func is not used anymore, let's delete it

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+        t.helpers.retrying({}, function()
+            t.assert(inserted_before_ro)
+        end)
+        box.cfg{read_only = true}
+        insert_fiber:join()
+        t.assert_equals(#sl:select(), 1)
+    end)
+end
+
+g.test_try_commit_temporary_after_readonly = function(cg)
```
Comment (Serpentian) [inline test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:70]: `test_try_commit_temporary_after_readonly` and `test_try_commit_local_after_readonly` are almost the same, we can make a separate function, template, to which we'll pass the name of the space to use

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+    t.skip_if(cg.params.engine ~= 'memtx')
+    cg.server:exec(function(engine)
+        local fiber = require('fiber')
+        local st = box.schema.space.create('test_temp',
```
Comment (Serpentian) [inline test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:74]: It's also better to define all needed spaces in `before_all`

File: src/box/box.cc [hunk 11]
```diff
@@ -344,6 +344,61 @@ title(const char *new_status)
 	box_broadcast_status();
 }
 
+static int
```
[the remark this answers is not in the document]
Comment (Serpentian) [reply src/box/box.cc:347]: And let's also properly explain the motivation in the commit msg. If I'm not mistaken, we're triying to make ro-rw msgs more unified

**Review by nshy — CHANGES_REQUESTED** [review]

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua (hunk 9 above)
Comment (Serpentian) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:70]: But in that case we won't need `_G`, just the name of the space. And it'll be more straightforward, that the tests are almost the same. Let's leave it to Lev, I'm ok with whatever solution he'll do)

Comment (nshy) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:70]: This kind of code reuse I like)

File: src/box/vinyl.c (hunk 8 above)
Comment (LevKats) [reply src/box/vinyl.c:2635]: Do you mean `vy_tx_manager_abort_writers_for_ro` or `vinyl_engine_switch_to_ro`? Looks like both were deleted...

File: src/box/box.cc (hunk 11 above)
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/box.cc:351]: It is 3 commits now:

1. unified logging logic
2. bugfix
3. callback deletion refactoring.

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua (hunk 9 above)
Comment (LevKats) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua:81]: I decided to create the `test` space with proper parameters in each test and drop it after the test. So we don't need to pass the space name into template which I implemented too. Another advantage is that we need some logic for test skipping only in one place.

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua (hunk 10 above)
Comment (LevKats) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua]: I understand the idea but I hope you would find the current approach better since the temporary space won't be created in vinyl which is not supported.

File: src/box/engine.c [hunk 12]
```diff
@@ -85,9 +86,15 @@ engine_free(void)
...
-		engine->vtab->switch_to_ro(engine);
+	struct txn *txn;
+	rlist_foreach_entry(txn, &txns, in_txns) {
+		if (txn->n_new_rows != 0 &&
+		    txn->n_new_rows != txn->n_local_rows &&
+		    txn->status == TXN_INPROGRESS) {
+			txn_abort_with_conflict(txn);
+			txn_set_flags(txn, TXN_IS_ABORTED_RO_NODE);
+		}
+	}
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/engine.c]: Done

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua [hunk 13]
```diff
@@ -0,0 +1,101 @@
...
+            inserted_before_ro = true
+            box.ctl.wait_ro()
+            box.commit()
+        end)
+        insert_fiber:set_joinable(true)
+        t.helpers.retrying({}, function()
+            t.assert(inserted_before_ro)
+        end)
+        box.cfg{read_only = true}
+        insert_fiber:join()
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua]: I completely forgot about error handling here, thanks. Fixed.

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua [hunk 14]
```diff
@@ -0,0 +1,101 @@
...
+
+g.before_all(function(cg)
+    cg.server = server:new({box_cfg = {memtx_use_mvcc_engine = true}})
+    cg.server:start()
+    cg.server:exec(function(engine)
+        local s = box.schema.space.create('test', {engine = engine})
+        s:create_index('pk')
+        local sl = box.schema.space.create('test_local',
+                                           {engine = engine, is_local=true})
+        sl:create_index('pk')
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua]: It is `test` time each time now with different parameters. Fixed.

File: test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua [hunk 15]
```diff
@@ -0,0 +1,101 @@
...
+    end, {cg.params.engine})
+end
+
+g.after_each(function(cg)
+    cg.server:update_box_cfg{read_only = false}
+end)
+
+g.after_all(function(cg)
+    cg.server:drop()
+end)
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/engine-luatest/gh_9937_commit_transaction_after_readonly_test.lua]: Fixed.

**Review by Serpentian — COMMENTED** [review]
The patch looks great to me, just 2 last comments

File: src/box/box.cc [hunk 16]
```diff
@@ -345,6 +345,64 @@ title(const char *new_status)
...
+					" and is frozen until promotion");
+		}
+	} else {
+		if (is_ro)
+			SNPRINT(total, snprintf, buf, size,
+				"box.cfg.read_only is true");
+		else if (is_orphan)
+			SNPRINT(total, snprintf, buf, size, "it is an orphan");
+		else
+			return -1;
```
Comment (nshy) [inline src/box/box.cc:400]: I guess it is better to make function `void` and leave assertion here. We should make it return -1 for case which is considered impossible.

File: src/box/box.cc [hunk 17]
```diff
@@ -354,9 +412,14 @@ box_update_ro_summary(void)
 	/* In 99% nothing changes. Filter this out first. */
 	if (is_ro_summary == old_is_ro_summary)
 		return;
-
-	if (is_ro_summary)
-		engine_switch_to_ro();
```
Comment (nshy) [inline src/box/box.cc:359]: Let's keep drop this call in the next patch.

File: src/box/box.cc [hunk 18]
```diff
@@ -354,9 +412,14 @@ box_update_ro_summary(void)
...
+	if (is_ro_summary) {
+		const int buf_size = 256;
+		char buf[buf_size];
+		if (box_ro_state_msg(buf, buf_size) == 0)
```
Comment (nshy) [inline src/box/box.cc:427]: We can use `tt_static_buf` and `TT_STATIC_BUF_LEN` for buffer and size.

**Review by nshy — CHANGES_REQUESTED** [review]

File: src/box/box.cc (hunk 18 above)
Comment (LevKats) [reply src/box/box.cc]: It's better indeed. I forgot that the static allocator is cyclic and therefore can be used each time the node becomes read-only. Fixed.

File: src/box/box.cc (hunk 17 above)
Comment (LevKats) [reply src/box/box.cc:360]: Moved to the last commit where the callback is deleted.

File: src/box/box.cc (hunk 16 above)
Comment (LevKats) [reply src/box/box.cc]: Can't make it void since the `SNPRINT` macro returns -1 but now -1 is returned only in impossible cases.

File: src/box/txn.h [hunk 19]
```diff
@@ -119,6 +119,11 @@ enum txn_flag {
 	TXN_IS_STARTED_IN_ENGINE = 0x400,
 	/** Transaction supports multiversion concurrency control. */
 	TXN_SUPPORTS_MVCC = 0x800,
+	/**
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/txn.h:122]: Moved to the commit with the bugfix.

File: src/box/box.cc [hunk 20]
```diff
@@ -355,9 +413,14 @@ box_update_ro_summary(void)
 	/* In 99% nothing changes. Filter this out first. */
 	if (is_ro_summary == old_is_ro_summary)
 		return;
-
-	if (is_ro_summary)
+	if (is_ro_summary) {
 		engine_switch_to_ro();
+		char *buf = tt_static_buf();
+		if (box_ro_state_msg(buf, TT_STATIC_BUF_LEN) == 0)
+			say_info("box switched to read-only - %s", buf);
```
Comment (nshy) [inline src/box/box.cc:428]: Let's just add use `VERIFY` to check `box_ro_state_msg` return code. I does not benefit to branch on impossible case.

File: src/box/box.cc [hunk 21]
```diff
@@ -391,7 +454,11 @@ box_check_writable(void)
 		return 0;
 	struct error *e = diag_set(ClientError, ER_READONLY);
 	struct raft *raft = box_raft();
-	error_append_msg(e, " - ");
+	char *buf = tt_static_buf();
+	bool ok = box_ro_state_msg(buf, TT_STATIC_BUF_LEN) == 0;
+	assert(ok);
+	if (ok)
+		error_append_msg(e, " - %s", buf);
```
Comment (nshy) [inline src/box/box.cc:469]: Here too.

**Review by nshy — APPROVED** [review]

File: src/box/box.cc (hunk 20 above)
Comment (LevKats) [reply src/box/box.cc]: Fixed

File: src/box/box.cc (hunk 21 above)
Comment (LevKats) [reply src/box/box.cc]: Fixed

File: src/box/box.cc [hunk 22]
```diff
@@ -346,6 +346,64 @@ title(const char *new_status)
...
+			SNPRINT(total, snprintf, buf, size,
+				"box.cfg.read_only is true");
+		else if (is_orphan)
+			SNPRINT(total, snprintf, buf, size, "it is an orphan");
+		else
+			unreachable();
+	}
+	(void)total;
+	return 0;
+}
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/box.cc:406]: I thought about that. I see the problem with this approach that in most cases it is used not in an error condition so we create an error object, assign some error code but we just switched node to read-only.

**Review by nshy — APPROVED** [review]

File: src/box/box.cc (hunk 22 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:406]: Resolving since the PR is approved.

File: src/box/engine.c [hunk 23]
```diff
@@ -82,14 +82,6 @@ engine_free(void)
 	engine_count = 0;
 }
 
-void
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/engine.c:87]: [Done](https://github.com/tarantool/tarantool-ee/pull/1241).

**Comment by sergepetrenko** [comment]
@LevKats, please, prepare backports for 2.11, 3.2, 3.3 branches manually.

**Comment by sergepetrenko** [comment]
> @LevKats, please, prepare backports for 2.11, 3.2, 3.3 branches manually.

Backport turned out to be non-trivial, so we'll leave this patch in 3.4 and master only.
