### PR TITLE
box: fix typo in pagination `after` position option validation

### LINKED ISSUE #8716: builtin/box/schema.lua:1957: box.error(): bad arguments
```log
builtin/box/schema.lua:1957: box.error(): bad arguments
WARNING  localhost:50609:server.py:42 stack traceback:
WARNING  localhost:50609:server.py:42 	builtin/box/schema.lua:1957: in function 'check_pairs_opts'
WARNING  localhost:50609:server.py:42 	builtin/box/schema.lua:2386: in function 'pairs'
...
WARNING  localhost:50609:server.py:42 	[C]: in function 'xpcall'
```

```lua
tarantool> box.space.test:select({}, {after = 123})
---
- error: 'builtin/box/schema.lua:2479: box.error(): bad arguments'
...
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Closes #8716

NO_DOC=bugfix

### CODE REVIEW

File: test/box-luatest/gh_8716_pagination_invalid_after_pos_bug_test.lua [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+-- Checks that spaces with `_stream` and `_stream_space_cache` can be accessed
+-- from net.box streams.
+g.test_net_box_conn_with_disabled_schema_fetching = function(cg)
+    cg.server:exec(function()
+        local err_msg = "Iterator position is invalid"
+        t.assert_error_msg_content_equals(err_msg, function()
+            box.space.s:select(nil, {after = 777})
+            box.space.s:pairs(nil, {after = 777})
+        end)
```
Comment (olegrok) [inline test/box-luatest/gh_8716_pagination_invalid_after_pos_bug_test.lua:27]: I guess you need to call this function twice since (for pairs and select). Currently `box.space.s:pairs(nil, {after = 777})` row is unreachable.

File: test/box-luatest/gh_8716_pagination_invalid_after_pos_bug_test.lua [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+    end)
+end)
+
+g.after_all(function(cg)
+    cg.server:drop()
+end)
+
+-- Checks that spaces with `_stream` and `_stream_space_cache` can be accessed
+-- from net.box streams.
+g.test_net_box_conn_with_disabled_schema_fetching = function(cg)
```
Comment (locker) [inline test/box-luatest/gh_8716_pagination_invalid_after_pos_bug_test.lua:21]: The comment and the test case name are obviously wrong. Also, I'd test pagination over net.box as well.

Anyway, it'd probably be better to add the test cases to the existing files `test/engine-luatest/pagination_test.lua` and `box-luatest/pagination_netbox_test.lua` so as to keep all pagination-related tests together.

File: test/box-luatest/gh_8716_pagination_invalid_after_pos_bug_test.lua (hunk 1 above)
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_8716_pagination_invalid_after_pos_bug_test.lua]: Yeah, that's a typo, thanks!

**Review by locker — CHANGES_REQUESTED** [review]

File: test/box-luatest/gh_8716_pagination_invalid_after_pos_bug_test.lua (hunk 2 above)
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_8716_pagination_invalid_after_pos_bug_test.lua]: Fixed.

**Review by locker — APPROVED** [review]

File: changelogs/unreleased/gh-8716-pagination-invalid-after-pos-bug.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+## bugfix/box
+
+* Fixed bug (bad error message) in pagination related to validation of `after`
+  position option of space and index objects `:select` and `:pairs` methods
+  (gh-8716).
```
Comment (xuniq) [inline changelogs/unreleased/gh-8716-pagination-invalid-after-pos-bug.md:5]:
```suggestion
* Fixed a bug (bad error message) in pagination related to the validation of the `after`
  position option of space and the `:select` and `:pairs` methods of the index object
  (gh-8716).
```

**Review by xuniq — APPROVED** [review]

File: changelogs/unreleased/gh-8716-pagination-invalid-after-pos-bug.md (hunk 3 above)
Comment (xuniq) [reply changelogs/unreleased/gh-8716-pagination-invalid-after-pos-bug.md]: Ok, your suggestion looks good to me.

**Comment by locker** [comment]
Cherry-picked to 2.11.
