### PR TITLE
test/fuzz: fix error injections in engine test

### LINKED ISSUE #10531: tarantool stuck after running a test
**Bug description**

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool 3.3.0-entrypoint-35-g9519fe930
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

```
./build/src/tarantool ./test/fuzz/lua/test_engine.lua --workers 5000 --test_duration $((60*60)) --engine vinyl --verbose --seed 14533
```

**Actual behavior**

tarantool process should finish execution at the end of the test, but it is stuck and prints messages in console:

```
<snipped>

2024-09-06 07:04:45.054 [1721366] main/107/checkpoint_daemon xlog.c:1374 E> ER_INJECTION: Error injection 'xlog write injection'
2024-09-06 07:04:45.059 [1721366] main/107/checkpoint_daemon xlog.c:1374 E> ER_INJECTION: Error injection 'xlog write injection'
2024-09-06 07:04:45.059 [1721366] main/107/checkpoint_daemon I> scheduled next checkpoint for Fri Sep  6 07:04:46 2024                
2024-09-06 07:04:46.052 [1721366] snapshot/101/main I> saving snapshot `./00000000000000061119.snap.inprogress'                       
2024-09-06 07:04:46.059 [1721366] main/107/checkpoint_daemon xlog.c:1374 E> ER_INJECTION: Error injection 'xlog write injection'       
2024-09-06 07:04:46.065 [1721366] main/107/checkpoint_daemon xlog.c:1374 E> ER_INJECTION: Error injection 'xlog write injection'                   
2024-09-06 07:04:46.065 [1721366] main/107/checkpoint_daemon I> scheduled next checkpoint for Fri Sep  6 07:04:47 2024                             
2024-09-06 07:04:47.046 [1721366] snapshot/101/main I> saving snapshot `./00000000000000061119.snap.inprogress'                                    
2024-09-06 07:04:47.051 [1721366] main/107/checkpoint_daemon xlog.c:1374 E> ER_INJECTION: Error injection 'xlog write injection'                   
2024-09-06 07:04:47.056 [1721366] main/107/checkpoint_daemon xlog.c:1374 E> ER_INJECTION: Error injection 'xlog write injection'                   
2024-09-06 07:04:47.056 [1721366] main/107/checkpoint_daemon I> scheduled next checkpoint for Fri Sep  6 07:04:48 2024                             
2024-09-06 07:04:48.054 [1721366] snapshot/101/main I> saving snapshot `./00000000000000061119.snap.inprogress'                                    
2024-09-06 07:04:48.060 [1721366] main/107/checkpoint_daemon xlog.c:1374 E> ER_INJECTION: Error injection 'xlog write injection'                   
2024-09-06 07:04:48.066 [1721366] main/107/checkpoint_daemon xlog.c:1374 E> ER_INJECTION: Error injection 'xlog write injection'                   
2024-09-06 07:04:48.066 [1721366] main/107/checkpoint_daemon I> scheduled next checkpoint for Fri Sep  6 07:04:49 2024

<snipped>
```

Backtrace:

```c++
#0  0x0000588dc976d3f7 in coro_transfer () at /home/ubuntu/tarantool/third_party/coro/coro.c:138
#1  0x0000588dc938cc65 in fiber_yield_impl (will_switch_back=true) at /home/ubuntu/tarantool/src/lib/core/fiber.c:859
#2  0x0000588dc938cc7e in fiber_yield () at /home/ubuntu/tarantool/src/lib/core/fiber.c:866
#3  0x0000588dc938ceeb in fiber_yield_timeout (delay=0.001) at /home/ubuntu/tarantool/src/lib/core/fiber.c:910
#4  0x0000588dc938d0f2 in fiber_sleep (delay=0.001) at /home/ubuntu/tarantool/src/lib/core/fiber.c:938
#5  0x0000588dc91a1c0b in vy_quota_use (q=0x588dca681f80, type=VY_QUOTA_CONSUMER_TX, size=144, timeout=3)
    at /home/ubuntu/tarantool/src/box/vy_quota.c:318
#6  0x0000588dc913472b in vinyl_engine_prepare (engine=0x588dca681ed0, txn=0x7d6f1703a038) at /home/ubuntu/tarantool/src/box/vinyl.c:2458
#7  0x0000588dc91e1279 in engine_prepare (engine=0x588dca681ed0, txn=0x7d6f1703a038) at /home/ubuntu/tarantool/src/box/engine.h:414
#8  0x0000588dc91e6480 in txn_prepare (txn=0x7d6f1703a038) at /home/ubuntu/tarantool/src/box/txn.c:1081
#9  0x0000588dc91e6864 in txn_commit_impl (txn=0x7d6f1703a038, wait_mode=TXN_COMMIT_WAIT_MODE_COMPLETE)
    at /home/ubuntu/tarantool/src/box/txn.c:1154
#10 0x0000588dc91e7034 in txn_commit (txn=0x7d6f1703a038) at /home/ubuntu/tarantool/src/box/txn.c:1272
#11 0x0000588dc91f8cd2 in box_process_rw (request=0x7d7153880c40, space=0x588dda1d3900, result=0x7d7153880d48)
    at /home/ubuntu/tarantool/src/box/box.cc:521
#12 0x0000588dc9205f77 in box_process1 (request=0x7d7153880c40, result=0x7d7153880d48) at /home/ubuntu/tarantool/src/box/box.cc:3754
#13 0x0000588dc9206bc0 in box_replace (space_id=512, tuple=0x7d715c153240 "\233\313B.\331n\364\375\355", <incomplete sequence \317>, 
    tuple_end=0x7d715c1532ac 'P' <repeats 200 times>..., result=0x7d7153880d48) at /home/ubuntu/tarantool/src/box/box.cc:3954
#14 0x0000588dc93148df in lbox_replace (L=0x409754b0) at /home/ubuntu/tarantool/src/box/lua/index.c:84
#15 0x0000588dc93ec217 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#16 0x0000588dc93f9d5b in lua_pcall (L=0x409754b0, nargs=4, nresults=-1, errfunc=0) at /home/ubuntu/tarantool/third_party/luajit/src/lj_api.c:1173
#17 0x0000588dc935d775 in luaT_call (L=0x409754b0, nargs=4, nreturns=-1) at /home/ubuntu/tarantool/src/lua/utils.c:695
#18 0x0000588dc93524a1 in lua_fiber_run_f (ap=0x7d715c125218) at /home/ubuntu/tarantool/src/lua/fiber.c:435
#19 0x0000588dc90ab143 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x588dc93523e4 <lua_fiber_run_f>, 
    ap=0x7d715c125218) at /home/ubuntu/tarantool/src/lib/core/fiber.h:1324
#20 0x0000588dc938e310 in fiber_loop (data=0x0) at /home/ubuntu/tarantool/src/lib/core/fiber.c:1162
#21 0x0000588dc976d3f1 in coro_init () at /home/ubuntu/tarantool/third_party/coro/coro.c:108
```

tarantool binary + test log + `fiber.info` log + coredump: https://drive.google.com/file/d/1QYOADvxKFHqI78qaypN71hFPQLPe6zQJ/view?usp=sharing

**Expected behavior**

tarantool is exited when test is finished.

### PR DESCRIPTION
**Pull request by locker**
Closes #10531

### CODE REVIEW

**Review by ligurio — APPROVED** [review]
Thanks!

File: test/fuzz/lua/test_engine.lua [hunk 1]
```diff
@@ -1320,20 +1331,28 @@ local errinj_set = {
...
+            return -1
+        end,
     },
     -- Set to true to fail xlog meta read.
     ERRINJ_XLOG_META = {
         enable = enable_errinj_boolean,
         disable = disable_errinj_boolean,
     },
-    -- Set to timeout to fail xlog data read.
+    -- Set to number of bytes to read before failing xlog data read.
```
Comment (ligurio) [inline test/fuzz/lua/test_engine.lua:1348]: > ERRINJ_XLOG_READ: set to true to fail xlog data read [^1]

:)

[^1]: https://github.com/tarantool/tarantool/issues/10236#issuecomment-2225347088

**Comment by locker** [comment]
Cherry-picked to 3.2.
