### PR TITLE
Fix crash in functional index iterator

### LINKED ISSUE #6786: Iteration by a functional index is not stable
Known affected tarantool versions:

2.4.1-57-g339ad6289
2.10.0-beta2-5-gdc19be406
2.10.0-beta2-40-g5cd399b77

The problem can be reproduced in the debug build:

> cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF && make -j

Reproducer:

```lua
box.cfg()

local findex_code = [[function(tuple)
    return {tuple[2]}
end]]
box.schema.func.create('findex_func', {
    body = findex_code,
    is_deterministic = true,
    is_sandboxed = true,
})

local space = box.schema.create_space('s', {
    engine = 'memtx',
    format = {
        {
            name = 'id',
            type = 'number',
        },
        {
            name = 'data',
            type = 'string',
        },
    }
})

space:create_index('primary', {
    type = 'TREE',
    parts = {
        {
            field = 1,
        }
    }
})
space:create_index('functional_index', {
    type = 'TREE',
    parts = {
        {
            field = 1,
            type = 'string',
        },
    },
    func = 'findex_func',
})

space:insert({1, '12'})
space:insert({2, '21'})

for _, tuple in space.index.functional_index:pairs() do
    space:delete({tuple[1]})
end
```

(The reproducer is extracted from expirationd 1.1.1-44-g838c2d1, from the `test_memtx_tree_functional_index` test case.)

Result (those particular line numbers are from 2.10.0-beta2-40-g5cd399b77):

> tarantool: /home/alex/p/tarantool-meta/r/t-6/src/box/tuple_compare.cc:1394: int func_index_compare(tuple*, hint_t, tuple*, hint_t, key_def*) [with bool is_nullable = false; hint_t = long unsigned int]: Assertion `mp_typeof(*key_b) == MP_ARRAY' failed.
> Aborted (core dumped)

C and Lua backtraces from the coredump:

```c
(gdb) bt
#0  0x00007f3c941581cc in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f3c9410c982 in raise () from /lib64/libc.so.6
#2  0x00007f3c940f7449 in abort () from /lib64/libc.so.6
#3  0x00007f3c940f7375 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007f3c94105af2 in __assert_fail () from /lib64/libc.so.6
#5  0x000055b88deb24c8 in func_index_compare<false> (tuple_a=0x7f3c83007824, tuple_a_hint=139897872611420, tuple_b=0x7f3c830077b4, tuple_b_hint=139897872611308, cmp_def=0x55b88e6dd650)
    at /home/alex/p/tarantool-meta/r/t-6/src/box/tuple_compare.cc:1394
#6  0x000055b88db1a7ef in tuple_compare (tuple_a=0x7f3c83007824, tuple_a_hint=139897872611420, tuple_b=0x7f3c830077b4, tuple_b_hint=139897872611308, key_def=0x55b88e6dd650)
    at /home/alex/p/tarantool-meta/r/t-6/src/box/key_def.h:971
#7  0x000055b88db24edd in NS_USE_HINT::bps_tree_memtx_tree_find_after_ins_point_elem (tree=0x55b88e6df158, arr=0x7f3c84128010, size=1, elem=..., exact=0x7f3c935ff814)
    at /home/alex/p/tarantool-meta/r/t-6/src/lib/salad/bps_tree.h:1517
#8  0x000055b88db25741 in NS_USE_HINT::memtx_tree_upper_bound_elem (tree=0x55b88e6df158, key=..., exact=0x7f3c935ff815) at /home/alex/p/tarantool-meta/r/t-6/src/lib/salad/bps_tree.h:1880
#9  0x000055b88db341e6 in tree_iterator_next_base<true> (iterator=0x7f3c9341c078, ret=0x41a6a418) at /home/alex/p/tarantool-meta/r/t-6/src/box/memtx_tree.cc:287
#10 0x000055b88db32f36 in tree_iterator_next<true> (iterator=0x7f3c9341c078, ret=0x41a6a418) at /home/alex/p/tarantool-meta/r/t-6/src/box/memtx_tree.cc:497
#11 0x000055b88db1368e in iterator_next (it=0x7f3c9341c078, ret=0x41a6a418) at /home/alex/p/tarantool-meta/r/t-6/src/box/index.cc:472
#12 0x000055b88db1344c in box_iterator_next (itr=0x7f3c9341c078, result=0x41a6a418) at /home/alex/p/tarantool-meta/r/t-6/src/box/index.cc:400
#13 0x000055b88dd79889 in lj_vm_ffi_call () at buildvm_x86.dasc:2629
#14 0x000055b88de2c0f0 in lj_ccall_func (L=0x41145378, cd=0x41c20500) at /home/alex/p/tarantool-meta/r/t-6/third_party/luajit/src/lj_ccall.c:1150
#15 0x000055b88ddb7560 in lj_cf_ffi_meta___call (L=0x41145378) at /home/alex/p/tarantool-meta/r/t-6/third_party/luajit/src/lib_ffi.c:230
#16 0x000055b88dd7760f in lj_BC_FUNCC () at buildvm_x86.dasc:811
#17 0x000055b88dd8281b in lua_pcall (L=0x41145378, nargs=0, nresults=0, errfunc=0) at /home/alex/p/tarantool-meta/r/t-6/third_party/luajit/src/lj_api.c:1187
#18 0x000055b88dd1135c in luaT_call (L=0x41145378, nargs=0, nreturns=0) at /home/alex/p/tarantool-meta/r/t-6/src/lua/utils.c:464
#19 0x000055b88dd094bc in lua_main (L=0x41145378, argc=1, argv=0x55b88e5bef58) at /home/alex/p/tarantool-meta/r/t-6/src/lua/init.c:797
#20 0x000055b88dd09a31 in run_script_f (ap=0x7f3c934004f0) at /home/alex/p/tarantool-meta/r/t-6/src/lua/init.c:886
#21 0x000055b88db00d5e in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55b88dd094d5 <run_script_f>, ap=0x7f3c934004f0)
    at /home/alex/p/tarantool-meta/r/t-6/src/lib/core/fiber.h:922
#22 0x000055b88dd373fe in fiber_loop (data=0x0) at /home/alex/p/tarantool-meta/r/t-6/src/lib/core/fiber.c:918
#23 0x000055b88dffbef3 in coro_init () at /home/alex/p/tarantool-meta/r/t-6/third_party/coro/coro.c:110
(gdb) lj-stack
0x41c1c760:0x41c1c780 [    ] 5 slots: Red zone
0x41c1c758            [   M]
0x41c1c298:0x41c1c750 [    ] 152 slots: Free stack slots
0x41c1c290            [  T ]
0x41c1c288            [    ] VALUE: cdata @ 0x41a6a410
0x41c1c280            [    ] VALUE: cdata @ 0x41c20430
0x41c1c278            [ B  ] VALUE: cdata @ 0x41c20500
0x41c1c270            [    ] FRAME: [L] delta=3, fast function #170
0x41c1c268            [    ] VALUE: cdata @ 0x41c20430
0x41c1c260            [    ] VALUE: string "\220" @ 0x41c203b0
0x41c1c258            [    ] FRAME: [L] delta=6, Lua function @ 0x41a6a530, 5 upvalues, "@builtin/box/schema.lua":1442
0x41c1c250            [    ] VALUE: cdata @ 0x41c20430
0x41c1c248            [    ] VALUE: string "\220" @ 0x41c203b0
0x41c1c240            [    ] VALUE: table @ 0x41c20470 (asize: 0, hmask: 0x3)
0x41c1c238            [    ] VALUE: table @ 0x41c1a4c8 (asize: 0, hmask: 0xf)
0x41c1c230            [    ] VALUE: string "function(tuple)\n    return {tuple[2]}\nend" @ 0x41d9be28
0x41c1c228            [    ] FRAME: [V] delta=1, Lua function @ 0x41bed088, 0 upvalues, "@case.lua":0
0x41c1c220            [    ] FRAME: [CP] delta=1, Lua function @ 0x41bed088, 0 upvalues, "@case.lua":0
0x41c1c218            [S   ] FRAME: dummy L
```

If my diagnostics is correct (and the iteration is truthly not stable) and it is not supposed to be fixed soon, please, at least file an issue against the documentation to highlight this detail for users. It would be also good to leave a note in https://github.com/tarantool/doc/issues/2102.

If it is not correct, please, rename the issue appropriately.

### PR DESCRIPTION
**Pull request by locker**
A memtx tree iterator remembers the last tuple returned to the user and its hint so that it can restore iteration if the index is changed. To prevent the tuple from being freed, it references it. The problem is it's not enough for a functional index, because the latter allocates key parts separately from tuples (it stores pointers to them in memtx tree hints). As a result, if a tuple is deleted from the tree, its key parts will be immediately freed, even if the tuple itself is referenced. Since key parts are necessary to restore an iterator, this results in a use after free bug.

To fix the issue, let's store a copy of the current tuple key part in the iterator along with the tuple. If a key part is small, the copy is stored in a preallocated fixed-size buffer, otherwise it's allocated with malloc.

Closes #6786

### CODE REVIEW

File: src/box/memtx_tree.cc [hunk 1]
```diff
@@ -289,25 +322,20 @@ tree_iterator_next_base(struct iterator *iterator, struct tuple **ret)
...
-		it->current = *res;
-	}
 	struct index *idx = iterator->index;
 	struct space *space = space_by_id(iterator->space_id);
 	/*
 	 * Pass no key because any write to the gap between that
 	 * two tuples must lead to conflict.
 	 */
-	memtx_tx_track_gap(in_txn(), space, idx, *ret, ITER_GE, NULL, 0);
+	memtx_tx_track_gap(in_txn(), space, idx,
```
Comment (alyapunov) [inline src/box/memtx_tree.cc:361]: Pleas don't move the code that handles `currect` and `ret` below memtx_tx_track_gap. It actually can do something with tree and tree iterator would be broken.

File: src/box/memtx_tree.cc [hunk 2]
```diff
@@ -326,26 +354,20 @@ tree_iterator_prev_base(struct iterator *iterator, struct tuple **ret)
...
 	struct space *space = space_by_id(iterator->space_id);
 	/*
 	 * Pass no key because any write to the gap between that
 	 * two tuples must lead to conflict.
 	 */
-	memtx_tx_track_gap(in_txn(), space, idx, successor, ITER_LE, NULL, 0);
-	tuple_unref(successor);
+	memtx_tx_track_gap(in_txn(), space, idx, it->current.tuple, ITER_LE,
+			   NULL, 0);
+	tree_iterator_set_current<USE_HINT>(it, res);
```
Comment (alyapunov) [inline src/box/memtx_tree.cc:395]: Here too

File: src/box/memtx_tree.cc [hunk 3]
```diff
@@ -365,42 +387,37 @@ tree_iterator_next_equal_base(struct iterator *iterator, struct tuple **ret)
...
+		tree_iterator_set_current<USE_HINT>(it, NULL);
 	} else {
 		/*
 		 * Pass no key because any write to the gap between that
 		 * two tuples must lead to conflict.
 		 */
-		memtx_tx_track_gap(in_txn(), space, idx, *ret, ITER_GE,
+		memtx_tx_track_gap(in_txn(), space, idx, res->tuple, ITER_GE,
 				   NULL, 0);
+		tree_iterator_set_current<USE_HINT>(it, res);
```
Comment (alyapunov) [inline src/box/memtx_tree.cc:444]: And here, and below lots of times.

File: src/box/memtx_tree.cc [hunk 4]
```diff
@@ -231,6 +232,17 @@ struct tree_iterator {
...
+	 * For functional indexes only: copy of the functional index key at the
+	 * current iterator position. Allocated from current_func_key_buf or on
+	 * malloc.
+	 *
+	 * Since pinning a tuple doesn't prevent its functional keys from being
+	 * deleted, we need to copy it so that we can use it to restore the
+	 * iterator position.
+	 */
+	void *current_func_key;
+	char current_func_key_buf[128];
```
Comment (alyapunov) [inline src/box/memtx_tree.cc:245]: Please make it no more that 32 bytes. I would make 16. It's enough for numbers and string words.

**Review by alyapunov — CHANGES_REQUESTED** [review]

File: src/box/memtx_tree.cc (hunk 2 above)
Comment (locker) [reply src/box/memtx_tree.cc]: Fixed.

File: src/box/memtx_tree.cc (hunk 3 above)
Comment (locker) [reply src/box/memtx_tree.cc]: Fixed.

File: src/box/memtx_tree.cc (hunk 4 above)
Comment (locker) [reply src/box/memtx_tree.cc]: Set to 32 bytes.

File: src/box/memtx_tree.cc [hunk 5]
```diff
@@ -365,27 +388,20 @@ tree_iterator_next_equal_base(struct iterator *iterator, struct tuple **ret)
...
+	struct index *idx = iterator->index;
+	struct space *space = space_by_id(iterator->space_id);
 	/* Use user key def to save a few loops. */
 	if (res == NULL ||
 	    tuple_compare_with_key(res->tuple, res->hint,
 				   it->key_data.key,
 				   it->key_data.part_count,
 				   it->key_data.hint,
 				   index->base.def->key_def) != 0) {
+		tree_iterator_set_current<USE_HINT>(it, NULL);
```
Comment (EvgenyMekhanik) [inline src/box/memtx_tree.cc:430]: May be use `tree_iterator_set_current_tuple` here to prevent changing hint as it was previously

File: src/box/memtx_tree.cc [hunk 6]
```diff
@@ -420,33 +437,30 @@ tree_iterator_prev_equal_base(struct iterator *iterator, struct tuple **ret)
...
```
Comment (EvgenyMekhanik) [inline src/box/memtx_tree.cc:480]: May be use tree_iterator_set_current_tuple here to prevent changing hint as it was previously

File: src/box/memtx_tree.cc [hunk 7]
```diff
@@ -618,8 +630,7 @@ tree_iterator_start(struct iterator *iterator, struct tuple **ret)
 	if (!res)
 		return 0;
 	*ret = res->tuple;
-	tuple_ref(*ret);
-	it->current = *res;
+	tree_iterator_set_current(it, res);
```
Comment (EvgenyMekhanik) [inline src/box/memtx_tree.cc:661]: May be add assertion that it->current.tuple is NULL here

File: src/box/memtx_tree.cc [hunk 8]
```diff
@@ -1350,6 +1358,8 @@ memtx_tree_index_create_iterator(struct index *base, enum iterator_type type,
 		it->key_data.set_hint(key_hint(key, part_count, cmp_def));
 	invalidate_tree_iterator(&it->tree_iterator);
 	it->current.tuple = NULL;
+	if (USE_HINT)
```
Comment (EvgenyMekhanik) [inline src/box/memtx_tree.cc:1389]: why not `tree_iterator_set_current_hint` ?

File: src/box/memtx_tree.cc (hunk 5 above)
Comment (locker) [reply src/box/memtx_tree.cc:430]: After the next commit, `tree_iterator_set_current`, apart from dereferencing the tuple, will also free the functional index "chunk" so using `tree_iterator_set_current_tuple` wouldn't be enough.

File: src/box/memtx_tree.cc (hunk 6 above)
Comment (locker) [reply src/box/memtx_tree.cc:480]: See my [reply](https://github.com/tarantool/tarantool/pull/6798/commits/714186ed47ee00fd7d1af5b32c66bbfa2e745004#r794646568) in the different thread.

File: src/box/memtx_tree.cc (hunk 8 above)
Comment (locker) [reply src/box/memtx_tree.cc:1389]: This would rely on the fact that `tree_iterator_set_current_hint` doesn't free the old "chunk" if `current_func_key` is NULL. This wouldn't improve readability. This is a constructor so setting fields directly is okay here so I'd prefer to leave it as is - more straightforward to the reader.

File: src/box/memtx_tree.cc (hunk 7 above)
Comment (locker) [reply src/box/memtx_tree.cc:661]: I don't see much point - if it points to a valid tuple, then everything's going to work fine anyway. If it's uninitialized, we'll crash (or this will get caught by asan). There wasn't an assertion here before so I don't think we should add a new one now just for the sake of it.

**Review by EvgenyMekhanik — APPROVED** [review]

**Review by alyapunov — APPROVED** [review]
