### PR TITLE
core: return procedure name hash table to speed up frame resolving

### LINKED ISSUE #7207: Performance degradation after backtrace rework
Linux is mostly affected.

The first part of issue - https://github.com/tarantool/tarantool/issues/7171
Issue appeared after https://github.com/tarantool/tarantool/pull/6927

```
fiber = require('fiber')
clock = require('clock')
for _ = 1, 1000 do
    fiber.new(function() fiber.sleep(100) end)
end
clock.bench(function() fiber.info() end)
```

In some cases users call `fiber.info()[fiber.id()]` and something could break after upgrade.

```
Tarantool 2.11.0-entrypoint-83-g2e067472f
tarantool> clock.bench(function() fiber.info() end)
---
- - 0.99139278
...
```

```
Tarantool 2.8.4-0-g47e6bd362
tarantool> clock.bench(function() fiber.info() end)
---
- - 0.030947828
...
```

Both build with ENABLE_BACKTRACE option. Both build with CMAKE_BUILD_TYPE=RelWithDebInfo. Slowdown in x30 times.

Here I don't see any build type options - https://github.com/tarantool/tarantool/commit/7dc9fe44a5aebc2b44c240221d2a71cd6d97b6b0#diff-ac27a0326fb55d368550e213befffcafea05ec78353d859f74920a903b4df8e6

Do we always build libunwind in debug?

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Procedure name hash table was removed during refactoring in 8ce76364 based
off the interpretation that libunwind caches procedure names internally —
turned out it only caches unwinding info, which causes a severe performance
downgrade (gh-7207): return procedure name hash table to speed up frame
resolving.

Closes #7207

### CODE REVIEW

File: src/lib/core/proc_name_htab.h [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+
+#ifdef ENABLE_BACKTRACE
+#ifdef __cplusplus
+extern "C" {
+#endif /* __cplusplus */
+#include "libunwind.h"
+
+/* Find procedure name and offset in hash table based on RIP register value. */
+char *
+proc_name_htab_find(unw_word_t ip, unw_word_t *offs);
```
Comment (locker) [inline src/lib/core/proc_name_htab.h:19]: Better call it 'cache', not 'htab', because it's a cache, and a cache isn't necessarily implemented using a hash table.

**Review by locker — CHANGES_REQUESTED** [review]

File: cmake/BuildLibUnwind.cmake [hunk 2]
```diff
@@ -23,6 +23,9 @@ macro(libunwind_build)
     set(LIBUNWIND_BUILD_DIR ${PROJECT_BINARY_DIR}/build/libunwind)
     set(LIBUNWIND_BINARY_DIR ${LIBUNWIND_BUILD_DIR}/work)
     set(LIBUNWIND_INSTALL_DIR ${LIBUNWIND_BUILD_DIR}/dest)
+    set(LIBUNWIND_CFLAGS "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELWITHDEBINFO}")
+    set(LIBUNWIND_CXXFLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
+    set(LIBUNWIND_LDFLAGS "${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}")
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply cmake/BuildLibUnwind.cmake:28]: Fixed:
* added only the neccesary compiler flags;
* elaborated on this in the commit message.

File: src/lib/core/proc_name_htab.cc [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+	}
+
+	~ProcNameHtab()
+	{
+		region_destroy(&proc_name_htab_entry_region);
+		mh_proc_name_htab_delete(proc_name_htab);
+	}
+};
+
+char *
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/proc_name_htab.cc:77]: Yeah, I guess since `backtrace_frame_resolve` returns `const char *`, this makes sense.

Fixed: change the return type to `const char`

File: src/lib/core/proc_name_htab.cc [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+ *
+ * Copyright 2010-2022, Tarantool AUTHORS, please see AUTHORS file.
+ */
+
+#include "fiber.h"
+#include "proc_name_htab.h"
+
+#include "small/region.h"
+
+#ifdef ENABLE_BACKTRACE
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/proc_name_htab.cc:12]: Thanks, sounds reasonable! Fixed: added a conditional to the CMake script instead.

File: src/lib/core/proc_name_htab.h (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/lib/core/proc_name_htab.h:19]: Yeah, I noticed that most of the hash tables we have are called _cache_s: the thing that boggled me is that they don't really behave as caches, i.e., they have no eviction.

But I now see that you are right in terms of abstractions.

Fixed: *_htab_* -> *_cache_*.

File: src/lib/core/proc_name_cache.cc [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+};
+
+#define mh_node_t struct mh_proc_name_cache_node_t
+#define mh_arg_t void *
+#define mh_hash(a, arg) ((a)->key)
+#define mh_hash_key(key, arg) (key)
+#define mh_cmp(a, b, arg) ((a)->key != (b)->key)
+#define mh_cmp_key(key, b, arg) ((key) != (b)->key)
+#define MH_SOURCE
+#include "salad/mhash.h"
```
Comment (locker) [inline src/lib/core/proc_name_cache.cc:42]: Why not reuse `mh_i64ptr_t`? It looks like in the old version of the cache we used `mh_i64ptr_t` and didn't define a new hash.

Comment (CuriousGeorgiy) [reply src/lib/core/proc_name_cache.cc]: Fixed: reused `mh_i64ptr_t`

**Comment by CuriousGeorgiy** [comment]
@locker checkpatch is FP on `static_cast`.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.10.
