### PR TITLE
replication: invalid recovery from xlog

### LINKED ISSUE #5158: Coredump on replica rebootstrap
**Tarantool version**:
* tarantool-2.2.3.1-1.el8.x86_64
* _TARANTOOL = 2.2.3-1-g98ecc909a

**OS version**: CentOS Linux release 8.0.1905 (Core) 

**Bug description**: Core on master during replica bootstrap

**Steps led to core**:
* created node1
* bootstrapped node2
* performed several switchovers and conflict resolution in master-master mode (incl. on-conflict trigger)
* bootstrapped node3 in cluster
* stopped node2 during node1 and node3 were working
* removed all xlogs of node2 (rm *.xlog)
* started again node2. during it's rebootstrap node1 got coredump and in replication status were "missing xlog" (logs were not kept)

**Environment**:
* [corefile](https://github.com/tarantool/tarantool/files/4898084/t.core.gz)
* backtrace:
```
#0  0x00007f7d4f7b28df in raise () from /lib64/libc.so.6
#1  0x00007f7d4f79ccf5 in abort () from /lib64/libc.so.6
#2  0x000055f6c0047ae2 in sig_fatal_cb (signo=<optimized out>, siginfo=<optimized out>, context=<optimized out>)
    at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/main.cc:300
#3  <signal handler called>
#4  vclock_lex_compare (b=0x50, a=0x55f6c07884d0) at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/box/vclock.h:375
#5  gc_consumer_cmp (b=0x0, a=0x55f6c0788480) at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/box/gc.c:75
#6  gc_tree_next (rbtree=<optimized out>, node=<optimized out>) at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/box/gc.c:85
#7  gc_tree_next (rbtree=0x55f6c06bb878 <gc+312>, node=0x55f6c0788480) at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/box/gc.c:85
#8  gc_run_cleanup () at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/box/gc.c:207
#9  0x000055f6c0103595 in gc_cleanup_fiber_f (ap=<error reading variable: value has been optimized out>)
    at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/box/gc.c:249
#10 0x000055f6c0046e90 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>)
    at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/lib/core/fiber.h:684
#11 0x000055f6c01533a0 in fiber_loop (data=<optimized out>) at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/src/lib/core/fiber.c:733
#12 0x000055f6c0308d51 in coro_init () at /usr/src/debug/tarantool-2.2.3.1-1.el8.x86_64/third_party/coro/coro.c:110
```
* after catching the core all nodes were gzipped: [cluster.tar.gz](https://github.com/tarantool/tarantool/files/4898087/cluster.tar.gz)

### PR DESCRIPTION
**Pull request by yanshtunder**
If you shut down the replica and delete all xlog files on it, and it reconnect to the master, may occur the restore error. Because there are intermediate xlog files between the snap on the replica and the last xlog on the master. When restoring xlog files on the replica, it can be occurred that `prev_signature < signature` and this will lead to the crash of the master.

Closes #5158

NO_DOC=bugfix

### CODE REVIEW

File: src/box/relay.cc [hunk 1]
```diff
@@ -1042,11 +1042,17 @@ relay_subscribe(struct replica *replica, struct iostream *io, uint64_t sync,
...
-	 * join.
+	 * Reregister the replica with the garbage collector. To
+	 * correctly reregister the replica in gc, it's necessary
+	 * remove the old consumer.
 	 */
+	if (replica->gc != NULL) {
+		gc_consumer_unregister(replica->gc);
+		replica->gc = NULL;
+	}
+
```
Comment (sergepetrenko) [inline src/box/relay.cc:1055]: Let's simplify this a bit:
```diff
diff --git a/src/box/relay.cc b/src/box/relay.cc
index 87fd0a431..de0081367 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -1044,21 +1044,18 @@ relay_subscribe(struct replica *replica, struct iostream *io, uint64_t sync,
        assert(relay->state != RELAY_FOLLOW);
 
        /*
-        * Reregister the replica with the garbage collector. To
-        * correctly reregister the replica in gc, it's necessary
-        * remove the old consumer.
+        * Register the replica with the garbage collector.
+        * In case some of the replica's WAL files were deleted, it might
+        * subscribe with a smaller vclock than the master remembers, so
+        * recreate the gc consumer unconditionally to make sure it holds the
+        * correct vclock.
         */
-       if (replica->gc != NULL) {
-               gc_consumer_unregister(replica->gc);
-               replica->gc = NULL;
-       }
-
-       if (replica->gc == NULL && !replica->anon) {
+       if (!replica->anon) {
+               if (replica->gc != NULL) {
+                       gc_consumer_unregister(replica->gc);
+               }
                replica->gc = gc_consumer_register(replica_clock, "replica %s",
                                                   tt_uuid_str(&replica->uuid));
-               if (replica->gc == NULL)
-                       diag_raise();
-               gc_delay_unref();
        }
 
        if (replica_version_id < version_id(2, 6, 0) || replica->anon)
```

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+local fio = require('fio')
+local log = require('log')
+
+local g = t.group('gh_5158')
+
+g.before_each(function(cg)
+    cg.cluster = cluster:new({})
+    local box_cfg = {
+        checkpoint_count = 5,
+        log_level = 6,
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:13]: Why's `log_level = 6` needed here and below (`pcall(log.cfg, {level = 6}`)?

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+    }
+
+    cg.master = cg.cluster:build_server({alias = 'master', box_cfg = box_cfg})
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:16]: You may use `build_and_add_server` instead of `build_server` + `add_server`.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+    end)
+
+    cg.master:exec(function()
+        box.schema.space.create("test")
+        box.snapshot()
+        box.space.test:create_index("pk")
+        box.snapshot()
+    end)
+
+    cg.replica:start()
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:48]: Why did you stop the replica initially? I don't see why this is needed.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+
+    -- Vclocks are equal 5 on the master and on the replica
+    t.helpers.retrying({}, function()
+        t.assert_equals(cg.master:exec(function()
+            return box.info.vclock
+        end), {5})
+        t.assert_equals(cg.replica:exec(function()
+            return box.info.vclock
+        end), {5})
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:57]: Let's replace this with `cg.replica:wait_vclock_of(cg.master)`.
It's better to avoid waiting for specific values, like you do here (vclock is equal to 5). Later on, when something is changed in how tarantool writes WALs, vclocks will be equal to 6, or 4, or anything else, and the test will fail or will pass but become meaningless.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+
+    -- Delete all *.xlogs on the replica
+    cg.replica:stop()
+    local glob = fio.pathjoin(cg.replica.workdir, '*.xlog')
+    local xlogs = fio.glob(glob)
+    for _, file in pairs(xlogs) do fio.unlink(file) end
+
+    cg.replica:start()
+
+    -- Check that the master isn't die
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:68]: Typo: `isn't dead`.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+    t.assert_equals(cg.master:exec(function()
+        return box.info.status
+    end), 'running')
+    t.helpers.retrying({}, function()
+        t.assert(cg.replica:exec(function()
+            return box.space._cluster:count() == 2
+        end), 'Check that the master is\'t die')
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:75]: Typo: `isn\'t dead`. Also you may use double quotes. Then you won't have to escape `\'`: `"Check that the master isn't dead"`.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+
+    cg.replica:start()
+
+    -- Check that the master isn't die
+    t.assert_equals(cg.master:exec(function()
+        return box.info.status
+    end), 'running')
+    t.helpers.retrying({}, function()
+        t.assert(cg.replica:exec(function()
+            return box.space._cluster:count() == 2
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:74]: This check will be successful even if the master dies.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+        end), 'Check that the master is\'t die')
+        cg.replica:assert_follows_upstream(1)
+    end)
+end
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:78]: I've ran the test on current master (without your patch), and it fails only some of the runs. For example, once I got 1 out of 10 failures, and once even 0 failures. I think it's easy enough to stabilize it, please do so.
The test should fail every run on unpatched tarantool.

File: changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md [hunk 10]
```diff
@@ -0,0 +1,4 @@
+## bugfix/replication
+
+* Fixed replication recovery from the xlogs after rebootstraping replica
```
Comment (sergepetrenko) [inline changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md:3]: Let's be more specific: `Fixed an assertion failure on master when replica resubscribes with a smaller vclock than previously seen`.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Hi! Thanks for the patch!

Please see my comments below.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 3 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:16]: Done

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 5 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:57]: I agree

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 7 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:75]: Done

File: changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md (hunk 10 above)
Comment (yanshtunder) [reply changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md:3]: Done

File: src/box/relay.cc (hunk 1 above)
Comment (yanshtunder) [reply src/box/relay.cc:1055]: `gc_consumer_register()` can return NULL. Should this part be removed?
```
    if (replica->gc == NULL)
            diag_raise();
    gc_delay_unref();
```

Comment (sergepetrenko) [reply src/box/relay.cc:1055]: > gc_consumer_register() can return NULL. Should this part be removed?

Good catch, I removed it by mistake. It should stay.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 9 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:88]: Fixed

File: src/box/relay.cc [hunk 11]
```diff
@@ -1050,11 +1050,16 @@ relay_subscribe(struct replica *replica, struct iostream *io, uint64_t sync,
...
+	 * In case some of the replica's WAL files were deleted, it might
+	 * subscribe with a smaller vclock than the master remembers, so
+	 * recreate the gc consumer unconditionally to make sure it holds
+	 * the correct vclock.
 	 */
-	if (replica->gc == NULL && !replica->anon) {
+	if (!replica->anon) {
+		if (replica->gc != NULL) {
+			gc_consumer_unregister(replica->gc);
+		}
```
Comment (sergepetrenko) [inline src/box/relay.cc:1062]: We've changed the behaviour here a bit: note the `gc_delay_unref()` a couple of lines below.
Previously in ran only when the replica came for the first time (`replica->gc == NULL`). And now it runs on every replica subscribe. Even if the replica resubscribes multiple times.

This is not good, one replica might trick the master into thinking that enough consumers are registered and make it delete still needed xlogs.

Let's return the old behaviour:
```c
bool had_gc = false;
if (replica->gc != NULL) {
    gc_consumer_unregister(replica->gc);
    had_gc = true;
}
```

And below:
```c
if (!had_gc)
    gc_delay_unref();
```

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 12]
```diff
@@ -0,0 +1,88 @@
+local t = require('luatest')
+local cluster = require('test.luatest_helpers.cluster')
+local server = require('test.luatest_helpers.server')
+local fio = require('fio')
+
+local g = t.group('gh_5158')
+
+g.before_each(function(cg)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:8]: nit: might as well be `before_all` and `after_all` instead of `after_each` below.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 4 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:46]: I still don't understand why these stop and start are needed. I removed that part and the test worked just fine. It passed every time with the patch and failed every time without it:
```diff
diff --git a/test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua b/test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua
index c3f562ded..e50df5f75 100644
--- a/test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua
+++ b/test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua
@@ -29,13 +29,6 @@ g.after_each(function(cg)
 end)
 
 g.test_invalid_recovery_from_xlog = function(cg)
-    cg.replica:stop()
-    t.helpers.retrying({}, function()
-        t.assert_str_matches(cg.master:exec(function()
-            return box.info.replication[2].downstream["status"]
-        end), 'stopped')
-    end)
-
     cg.master:exec(function()
         box.schema.space.create("test")
         box.snapshot()
@@ -43,8 +36,6 @@ g.test_invalid_recovery_from_xlog = function(cg)
         box.snapshot()
     end)
 
-    cg.replica:start()
-
     -- Wait until everything is replicated from the master to the replica
     t.helpers.retrying({}, function()
         cg.replica:wait_vclock_of(cg.master)
```

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua [hunk 13]
```diff
@@ -0,0 +1,88 @@
...
+    -- The replica acknowledges that it has received part of the data
+    -- due to ERRINJ_WAL_DELAY_COUNTDOWN. As a result, on the intermediate
+    -- xlog on which the assert is fired (signature < prev_signature),
+    -- the GC is started.
+    --
+    -- A batch from WAL can immediately come to the replica. Accordingly,
+    -- ERRINJ_WAL_DELAY_COUNTDOWN stops the entire batch (the test
+    -- freezes), because the entire batch has arrived and the vclock
+    -- will catch up to the maximum value. Therefore, it is necessary
+    -- to use wal_queue_max_size
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:71]: Nice explanation of what's happening below.
Please, also mention why `wal_queue_max_size` is exactly 96, and why `replication_sync_timeout = 0.1` is needed.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 9 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:88]: Good job with stabilising the test!

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the fixes!

Some more comments from my side.

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 13 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:71]: Done

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 12 above)
Comment (yanshtunder) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:8]: If i want to use repeat test then 22 is not working properly.
I run the test like this: `.rocks/bin/luatest test/replication-luatest/xxx.lua -r 50

File: changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md [hunk 14]
```diff
@@ -0,0 +1,4 @@
+## bugfix/replication
+
+* Fixed an assertion failure on master when replica resubscribes with a
+smaller vclock than previously seen (gh-5158).
```
[the remark this answers is not in the document]
Comment (yanshtunder) [reply changelogs/unreleased/gh-5158-invalid-recovery-from-xlog.md:4]: Done

File: src/box/relay.cc (hunk 11 above)
Comment (yanshtunder) [reply src/box/relay.cc:1077]: Done

File: test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua (hunk 12 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_5158_invalid_recovery_from_xlog_test.lua:8]: Thanks for the explanation! I see now.

**Review by sergepetrenko — APPROVED** [review]
Thanks! LGTM.

**Review by sergos — APPROVED** [review]
