### PR TITLE
core: use `malloc` instead of `region` allocator in procedure name cache

### LINKED ISSUE #8777: ASAN: heap-use-after-free in ProcNameCache
```console
Tarantool 3.0.0-entrypoint-256-g088b32f38
type 'help' for interactive help
```

Issue on ASAN run of `app/socket.test.lua` with ASAN friendly small allocators (not yet in upsteam, WIP in scope of #7327):
```
==3272664==ERROR: AddressSanitizer: heap-use-after-free on address 0x60c000049cd0 at pc 0x5627471b6d5a bp 0x7ffc7f111f50 sp 0x7ffc7f111f48
READ of size 8 at 0x60c000049cd0 thread T0
    #0 0x5627471b6d59 in rlist_next /home/shiny/dev/tarantool/src/lib/small/include/small/rlist.h:144:15
    #1 0x5627471b6d59 in region_free /home/shiny/dev/tarantool/src/lib/small/small/region.c:61:2
    #2 0x562746956969 in region_destroy(region*) /home/shiny/dev/tarantool/src/lib/small/include/small/region.h:154:9
    #3 0x562746956969 in ProcNameCache::~ProcNameCache() /home/shiny/dev/tarantool/src/lib/core/proc_name_cache.cc:54:3
    #4 0x7f694e451d2e in __call_tls_dtors /usr/src/debug/glibc/glibc/stdlib/cxa_thread_atexit_impl.c:156:7
    #5 0x7f694e45215d in __run_exit_handlers /usr/src/debug/glibc/glibc/stdlib/exit.c:44:7
    #6 0x7f694e4521af in exit /usr/src/debug/glibc/glibc/stdlib/exit.c:141:3
    #7 0x7f694e439856 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:74:3
    #8 0x7f694e439909 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #9 0x5627460359e4 in _start (/home/shiny/dev/tarantool/build-asan-release/src/tarantool+0x8799e4) (BuildId: 877b05fdd0f5ebc3a9a95f1b78a51e8865e0b97b)

0x60c000049cd0 is located 16 bytes inside of 127-byte region [0x60c000049cc0,0x60c000049d3f)
freed by thread T0 here:
    #0 0x5627460e8d92 in __interceptor_free.part.0 asan_malloc_linux.cpp.o
    #1 0x5627468bcaf7 in slab_cache_destroy /home/shiny/dev/tarantool/src/lib/small/include/small/slab_cache_malloc.h:102:3
    #2 0x5627468bcaf7 in cord_destroy /home/shiny/dev/tarantool/src/lib/core/fiber.c:1716:2
    #3 0x5627461369b5 in tarantool_free() /home/shiny/dev/tarantool/src/main.cc:600:2
    #4 0x5627461369b5 in main /home/shiny/dev/tarantool/src/main.cc:875:2
    #5 0x7f694e43984f in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16

previously allocated by thread T0 here:
    #0 0x5627460e9dc9 in malloc (/home/shiny/dev/tarantool/build-asan-release/src/tarantool+0x92ddc9) (BuildId: 877b05fdd0f5ebc3a9a95f1b78a51e8865e0b97b)
    #1 0x5627471b60e1 in slab_get /home/shiny/dev/tarantool/src/lib/small/include/small/slab_cache_malloc.h:113:37
    #2 0x5627471b60e1 in region_reserve_slow /home/shiny/dev/tarantool/src/lib/small/small/region.c:43:26
    #3 0x5627469558b8 in region_reserve(region*, unsigned long) /home/shiny/dev/tarantool/src/lib/small/include/small/region.h:206:9
    #4 0x5627469558b8 in region_aligned_reserve(region*, unsigned long, unsigned long) /home/shiny/dev/tarantool/src/lib/small/include/small/region.h:232:14
    #5 0x5627469558b8 in region_aligned_alloc(region*, unsigned long, unsigned long) /home/shiny/dev/tarantool/src/lib/small/include/small/region.h:240:14
    #6 0x5627469558b8 in proc_name_cache_insert /home/shiny/dev/tarantool/src/lib/core/proc_name_cache.cc:80:3
    #7 0x5627468c53e9 in backtrace_frame_resolve /home/shiny/dev/tarantool/src/lib/core/backtrace.c:278:2
    #8 0x562746882158 in backtrace_lua_stack_push /home/shiny/dev/tarantool/src/lua/backtrace.c:171:5
    #9 0x56274683e94b in lbox_fiber_statof_map /home/shiny/dev/tarantool/src/lua/fiber.c:226:3
    #10 0x56274683e0fc in lbox_fiber_statof /home/shiny/dev/tarantool/src/lua/fiber.c:239:2
    #11 0x56274683dfc5 in lbox_fiber_statof_bt /home/shiny/dev/tarantool/src/lua/fiber.c:249:9
    #12 0x5627468c2054 in fiber_stat /home/shiny/dev/tarantool/src/lib/core/fiber.c:2107:9
    #13 0x56274683b6d7 in lbox_fiber_info /home/shiny/dev/tarantool/src/lua/fiber.c
    #14 0x5627469c40e2 in lj_BC_FUNCC /home/shiny/dev/tarantool/build-asan-release/third_party/luajit/src/lj_vm.S:811

SUMMARY: AddressSanitizer: heap-use-after-free /home/shiny/dev/tarantool/src/lib/small/include/small/rlist.h:144:15 in rlist_next
Shadow bytes around the buggy address:
  0x0c1880001340: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c1880001350: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c1880001360: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c1880001370: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c1880001380: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c1880001390: fa fa fa fa fa fa fa fa fd fd[fd]fd fd fd fd fd
  0x0c18800013a0: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c18800013b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c18800013c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c18800013d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c18800013e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3272664==ABORTING
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Benchmark from #7207 shows that this change does not effect performance.

Closes #8777

### CODE REVIEW

File: src/lib/core/backtrace.h [hunk 1]
```diff
@@ -48,6 +48,9 @@ struct backtrace {
 
 struct fiber;
 
+void
+backtrace_init(void);
+
```
Comment (locker) [inline src/lib/core/backtrace.h:53]: What's this needed for?

Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Sorry, this accidentally got into the diff.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.11 and 2.10.
