### PR TITLE
lua: track memory occupied by runtime tuples

### LINKED ISSUE #5872: box.tuple.new: hidden memory usage
**Bug description**

In case when using `box.tuple.new` there is no place to understand how many memory is used.

**Initial state:**

```
tarantool> box.cfg{}
---
...

tarantool> collectgarbage('collect') collectgarbage('collect')
---
...

tarantool> box.info().memory()
---
- cache: 0
  data: 37824
  index: 1196032
  lua: 1013538
  net: 589824
  tx: 0
...

tarantool> box.slab.info()
---
- items_size: 554560
  items_used_ratio: 6.82%
  quota_size: 268435456
  quota_used_ratio: 12.50%
  arena_used_ratio: 3.7%
  items_used: 37824
  quota_used: 33554432
  arena_size: 33554432
  arena_used: 1233856
...
```

**pmap**

```
pmap -x -p `pidof tarantool` | tail -n2
---------------- ------- ------- ------- 
total kB          796532   57180   40816
```

**"hidden" allocation**

```
r = {} for i = 1, 500 do table.insert(r, box.tuple.new{('x'):rep(1024*1024)}) end
```

**after state**

```
tarantool> box.info().memory()
---
- cache: 0
  data: 37824
  index: 1196032
  lua: 2650930
  net: 589824
  tx: 0
...

tarantool> box.slab.info()
---
- items_size: 554560
  items_used_ratio: 6.82%
  quota_size: 268435456
  quota_used_ratio: 12.50%
  arena_used_ratio: 3.7%
  items_used: 37824
  quota_used: 33554432
  arena_size: 33554432
  arena_used: 1233856
...
```

**the only pmap can show us the memory metrics**

```
pmap -x -p `pidof tarantool` | tail -n2
---------------- ------- ------- ------- 
total kB         1310132  571248  554884
```

Consider to expose box.tuple pool memory metric

https://gist.github.com/Totktonada/08219ca0cc014a66b83dee6539b80348

### PR DESCRIPTION
**Pull request by Totktonada**
It allows to track memory allocated for tuples on runtime arena. It does
not count tuples owned by memtx and vinyl, but tracks so called runtime
tuples. The most common example is a tuple created by the
`box.tuple.new(<...>)` function.

Example:

```lua
tarantool> box.runtime.info().tuple -- 0
tarantool> box.tuple.new({})
tarantool> box.runtime.info().tuple -- 160
tarantool> box.tuple.new({})
tarantool> box.runtime.info().tuple -- 320
tarantool> collectgarbage()
tarantool> box.runtime.info().tuple -- 160
```

Fixes #5872

### CODE REVIEW

File: test/box-luatest/box_info_memory_runtime_test.lua [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+        for i = 1, 100 do
+            table.insert(tuples, box.tuple.new({1, 2, 3}))
+        end
+    end]])
+end
+
+local function deallocate_tuples()
+    return g.server:eval([[do
+        rawset(_G, 'tuples', nil)
+        collectgarbage()
```
Comment (olegrok) [inline test/box-luatest/box_info_memory_runtime_test.lua:34]: Probably, it's better to call it twice.

https://stackoverflow.com/questions/28320213/why-do-we-need-to-call-luas-collectgarbage-twice

File: src/box/lua/info.c [hunk 2]
```diff
@@ -423,6 +424,9 @@ lbox_info_memory_call(struct lua_State *L)
 	lua_pushinteger(L, G(L)->gc.total);
 	lua_settable(L, -3);
 
+	luaL_pushuint64(L, tuple_runtime_memory_used());
```
Comment (locker) [inline src/box/lua/info.c:427]: Maybe, better report the amount of memory used by the [`runtime`](https://github.com/tarantool/tarantool/blob/cbc3daed35068ea5412aa1692e2bd5f7e2153f29/src/lib/core/memory.h#L46) arena? It includes both runtime tuples and fiber stacks. It's shown by [`box.info.runtime.info()`](https://github.com/tarantool/tarantool/blob/cbc3daed35068ea5412aa1692e2bd5f7e2153f29/src/box/lua/slab.cc#L240).

File: test/box-luatest/box_info_memory_runtime_test.lua (hunk 1 above)
Comment (Totktonada) [reply test/box-luatest/box_info_memory_runtime_test.lua:34]: I'm aware of this recipe, but I never saw a real need.

File: test/box-luatest/box_info_memory_runtime_test.lua [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+g.after_each(function()
+    g.server:drop()
+end)
+
+local function runtime_memory()
+    return g.server:call('box.info.memory').runtime
+end
+
+local function allocate_tuples()
+    return g.server:eval([[do
```
Comment (locker) [inline test/box-luatest/box_info_memory_runtime_test.lua:19]: Please use `exec` instead of `eval`. BTW, you can use `require('luatest').assert()` from `exec`, e.g.

https://github.com/tarantool/tarantool/blob/cbc3daed35068ea5412aa1692e2bd5f7e2153f29/test/box-luatest/gh_7005_session_on_commit_rollback_test.lua#L23-L38

This could simplify the test.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/lua/info.c (hunk 2 above)
Comment (Totktonada) [reply src/box/lua/info.c:427]: `box.runtime.info().used` is not so directly connected to amount of memory occupied by tuples allocated on runtime arena. I need a half of million of `box.tuple.new({})` calls to see a change in this metric.

Both are useful IMHO. I would like to offer a metric that specifically tracks runtime tuples. A large amount of runtime tuples (or wrong refcounting) is not rare source of problems and it would be nice to spot such situations easily (and easily reproduce with small amount of data).

TBH, I looked at possibly related client's problem today and it is why I resurrected this old patch.

Comment (locker) [reply src/box/lua/info.c:427]: "Runtime" sounds like all runtime memory, and the fact that `box.runtime.info().used` and `box.info.memory().runtime` show different values looks confusing. Maybe, make `runtime` a table?
```
runtime:
  tuple
  fiber
  ...
```

Or show the total runtime memory in `box.info.memory().runtime` and add a different function to get the details, e.g. `box.info.memory.runtime()` would return a table showing memory usage per kind?

Anyway, this needs to be discussed with @alyapunov.

Comment (Totktonada) [reply src/box/lua/info.c:427]: I agree on `box.info.memory().runtime.{tuple,fiber}`, but I find `box.info.memory().runtime` callable that serializes to a number quite unusual and maybe even confusing.

How about the following?

```yaml
tarantool> box.info.memory().runtime
...
- tuple: <number>
  fiber: <number>
  sum: <number>
---
```

Comment (Totktonada) [reply src/box/lua/info.c:428]: Updated to `box.info.memory().runtime.tuple` in the meanwhile.

File: test/box-luatest/box_info_memory_runtime_test.lua (hunk 3 above)
Comment (Totktonada) [reply test/box-luatest/box_info_memory_runtime_test.lua]: The idea to wrap the whole test into `:exec()` didn't came into my head. I rewrote it and I agree: it is simpler now. Thanks for the suggestion!

File: src/box/lua/info.c (hunk 2 above)
Comment (Totktonada) [reply src/box/lua/info.c:428]: We discussed it with @alyapunov and @locker and agreed to add the `tuple` field to `box.runtime.info()`, because this call already returns information related to runtime arena. I'll adjust the patch accordingly.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
@Totktonada The issue (#5872) doesn't have a milestone. Should we back port this PR for 2.8 and 1.10?

**Comment by Totktonada** [comment]
Technically speaking we should not backport features.

In this particular case we can consider an exception: it is simple and safe monitoring feature, which may help us to investigate incidents.

OTOH, new features could be a gentle way to push existing users to update (that decreases our support effort).

I think we can proceed with OK from the product team. I know that @Mons was interested in monitoring features, so I'll ask him.

**Comment by Totktonada** [comment]
@Mons said (the translation to English is mine):

> Don't think that we should backport it. Definitely not to 1.10.
