### PR TITLE
box: make the `PRIV_GRANT` work as it should

### LINKED ISSUE #11528: Can't give all the privileges to a user different from `admin`
There is a `super` role, which grants a user all the privileges that are possible to grant:

```lua
tarantool> box.schema.role.info('super')
---
- - - read,write,execute,session,usage,create,drop,alter,reference,trigger,insert,update,delete
    - universe
    -
...
```

(`reference`, `trigger`, `insert` , `update`, `delete` are [no-op](https://github.com/tarantool/tarantool/blob/417865a51ba2db7dad91dff7196d0492e66bb0a7/src/box/user_def.h#L63-L72).)

However, a user with the `super` role is not allowed to do some actions that `admin` can do. For example, it can't grant or revoke permissions for an object that it doesn't own or for a class of objects (so called entities):

https://github.com/tarantool/tarantool/blob/417865a51ba2db7dad91dff7196d0492e66bb0a7/src/box/alter.cc#L4061-L4067

There are other direct `== ADMIN` checks in `alter.cc`. We need to look over them and find other `admin`-only actions if there are ones.

I propose to fill the gap between the `super` role and the `admin` user: add the needed individual privileges and attach them to the `super` role.

### LINKED ISSUE #12088: The sequence name is acquired via the system space instead of a view
This has a side-effect of inability to see the privileges granted to the sequences by other users:

```lua
#!/usr/bin/env tarantool

box.cfg{}

box.schema.user.create('u')
box.schema.sequence.create('seq')
box.schema.user.grant('u', 'write', 'sequence', 'seq')
box.session.su('u', box.schema.user.info, 'u')
```

A successful exit expected, actual output:</summary>

```
2025-11-30 13:23:45.489 [19586] main schema.lua:3438 E> Read access to space '_sequence' is denied for user 'u' {"type":"AccessDeniedError","code":42,"object_type":"space","object_name":"_sequence","access_type":"Read","user":"u","trace":[{"file":"builtin/box/schema.lua","line":3438}]}
2025-11-30 13:23:45.489 [19586] main say.c:85 F> fatal error, exiting the event loop
```

### LINKED ISSUE #12089: No user access allowed if an entity privilege exists
We lack an entity check in the `_vuser` space filter cause the checks had been introduced in the commit af35de967b084d6731952eea61497a40590bdc13, but only for spaces, functions and sequences. So when we've introduced user and role entity accesses in c46702ff499fd50fcffdb854ccb36639bd97c885 the filter had not been updated.

The side effect is the following code failing.

```lua
box.cfg{}
box.schema.user.create('password_updater')
box.schema.user.create('to_update_password_of')
box.schema.user.grant('password_updater', 'write', 'space', '_user')
box.schema.user.grant('password_updater', 'alter', 'user')
box.session.su('password_updater', box.schema.user.passwd, 'to_update_password_of', '1234')
```

Expected a successful exit, but the following error received:

```
2025-11-30 13:45:56.150 [22189] main [C]:-1 E> User 'to_drop' is not found {"type":"ClientError","code":45,"name":"NO_SUCH_USER","user":"to_drop","trace":[{"file":"[C]","line":4294967295}]}
2025-11-30 13:45:56.150 [22189] main say.c:85 F> fatal error, exiting the event loop
```

### PR DESCRIPTION
**Pull request by mkostoevr**
Introduced a new `grant` privilege. The privilege is only grantable on the "universe". It allows a user to grant any privilege, excepting "grant" and "metagrant", on an object, object class or the "universe" to any available user excepting oneself.

Introduced a new `metagrant` privilege. The privilege is only grantable on the "universe". It allows a user to grant "grant" and "metagrant" access to to any available user excepting oneself.

Found and fixed a number of small issues by the way.

Closes #11528
Closes #12088
Closes #12089
Closes tarantool/security#150
Closes tarantool/security#152

### CODE REVIEW

File: src/box/alter.cc [hunk 1]
```diff
@@ -3932,8 +3946,15 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
 			  int2str(priv->grantee_id));
 		return -1;
 	}
+	/* Disallow grant oneself (except for admin). */
+	if (grantee == grantor && grantor->def->uid != ADMIN) {
+		diag_set(ClientError, ER_GRANT_ONESELF);
+		return -1;
+	}
```
Comment (mkostoevr) [inline src/box/alter.cc]: This should only be done after recovery it seems.

File: src/box/lua/schema.lua [hunk 2]
```diff
@@ -3427,7 +3427,7 @@ local function object_name(object_type, object_id, level)
     if object_type == 'space' then
         space = box.space._vspace
     elseif object_type == 'sequence' then
-        space = box.space._sequence
+        space = box.space._vsequence
```
Comment (locker) [inline src/box/lua/schema.lua:3438]: I don't understand the purpose of this change. If a sequence is inaccessible, we won't raise an error, instead we will fail trying to access `name` field in `nil` below. Looks like it doesn't matter if we use `_sequece` or `_vsequence` in this particular case.

File: src/box/alter.cc [hunk 3]
```diff
@@ -4087,26 +4087,26 @@ grant_or_revoke(struct priv_def *priv, struct txn_stmt *rolled_back_stmt)
...
+			/* The rest is regular rights. */
+			priv->access &= ~PRIV_X;
 		}
-	} else {
-		if (priv_grant(grantee, priv, rolled_back_stmt) != 0)
-			return -1;
 	}
-	return 0;
+	/* Manage the rest of the rights. */
+	if (priv_grant(grantee, priv) != 0)
```
Comment (locker) [inline src/box/alter.cc]: What happens if `priv_grant` fails? Shouldn't we rollback `role_grant` in this case?

File: test/box-luatest/gh_6530_net_box_opts_check_test.lua [hunk 4]
```diff
@@ -15,7 +15,8 @@ g.before_all(function()
                   {name = 'data', type = 'string'},
                  })
         s:create_index('primary', {parts = {'id'}})
-        box.schema.user.grant('guest', 'read,write', 'space', 'test')
+        box.session.su('admin', box.schema.user.grant,
```
Comment (locker) [inline test/box-luatest/gh_6530_net_box_opts_check_test.lua]: This looks like a breaking change.

File: src/box/alter.cc [hunk 5]
```diff
@@ -3932,8 +3946,14 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
 			  int2str(priv->grantee_id));
 		return -1;
 	}
+	/* Disallow grant oneself (except for admin). */
+	if (grantee == grantor && grantor->def->uid != ADMIN) {
+		diag_set(ClientError, ER_GRANT_ONESELF);
```
Comment (locker) [inline src/box/alter.cc]: This looks weird. Can't we drop privileges in the right order instead?

File: src/box/alter.cc [hunk 6]
```diff
@@ -4045,27 +4037,21 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
...
+	struct credentials grantor_cr;
+	credentials_create(&grantor_cr, grantor);
+	auto _ = make_scoped_guard([&] { credentials_destroy(&grantor_cr); });
+	if (access_check_ddl_cr(&grantor_cr, name, owner, object,
+				priv->object_type, priv_type) != 0)
 		return -1;
-	}
-	if (access_check_ddl(name, grantor->def->uid, object,
+	/* Check the logged-in user. */
+	if (access_check_ddl(name, owner, object,
```
Comment (locker) [inline src/box/alter.cc]: Looking at the code, I fail to understand what's going on here. What's the difference between the "grantor" and "logged-in user"?

File: test/box-luatest/gh_11528_grant_access_test.lua [hunk 7]
```diff
@@ -44,3 +50,197 @@ g.test_dropped_grants = function(cg)
...
+        box.session.su('admin', box.schema.space.create, 's')
+        box.session.su('admin', box.schema.role.create, 'r')
+        box.session.su('admin', box.schema.role.grant,
+                       'r', 'alter', 'space', 's')
+        box.session.su('admin', box.schema.role.grant,
+                       'r', 'read,write,create', 'universe')
+
+        -- Create a user and grant accesses to the role.
+        box.schema.user.create('u')
+        box.schema.user.grant('u', 'execute,grant', 'role', 'r')
```
Comment (locker) [inline test/box-luatest/gh_11528_grant_access_test.lua]: Do we really need such a fine-grained privilege control system? Maybe, a privilege to grant access to any object would be enough? In MySQL, they have the [`GRANT OPTION`](https://dev.mysql.com/doc/mysql-security-excerpt/5.7/en/privileges-provided.html#priv_grant-option) that allows the user to grant access to the same objects they have access to, which seems logical. What about other databases?

File: src/box/alter.cc [hunk 8]
```diff
@@ -4040,6 +4041,17 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
...
 	}
+	case SC_LUA_CALL:
+		if (priv->is_entity_access)
+			break;
+		name = (char *)xstrndup(priv->object_name,
+					priv->object_name_len);
+		free_name.is_active = true;
+		object = access_lua_call_find(priv->object_name,
+					      priv->object_name_len);
+		/* Object can be NULL if no access had been granted yet. */
```
Comment (locker) [inline src/box/alter.cc]: So we can grant the `execute` access to any `lua_call` object but we can grant  the`grant` access only if `execute` was granted, right? This looks weird...

File: test/box-luatest/session_test.lua
Comment (locker) [inline test/box-luatest/session_test.lua:1]: The test is reported to be flaky. Please fix.

File: src/box/lua/schema.lua (hunk 2 above)
Comment (mkostoevr) [reply src/box/lua/schema.lua:3438]: Without this change a user might not be able see its own privileges for a sequence (if they were granted from outside):

```
box.schema.sequence.create('seq')
box.schema.user.create('u')
box.schema.user.grant('u', 'write', 'sequence', box.sequence.seq.id)
box.session.su('u', box.schema.user.info, 'u') -- Read access to space '_sequence' is denied for user 'u'.
```

File: src/box/alter.cc (hunk 3 above)
Comment (mkostoevr) [reply src/box/alter.cc]: It's not a problem as the `priv_grant` only raises if the object is `SC_UNIVERSE`, whereas the roles are olny handled if it's `SC_ROLE`. There's still a problem though (that has existed before this patch): if a role grant has failed during `rebuild_effective_grants`, the bits set in `role->users` and `user->roles` remain set, so a next successfull grant applies the role accesses nevertheless. Fixed by simply moving the `grant_or_revoke` below the trigger installation, see the third commit in the patch ("box: do not apply rebulid-failed grants").

File: test/box-luatest/gh_6530_net_box_opts_check_test.lua (hunk 4 above)
Comment (mkostoevr) [reply test/box-luatest/gh_6530_net_box_opts_check_test.lua]: Dropped as now its only disallowed to grant oneself if it wasn't allowed previously (that is, if the grant access to the object is provided neither by the fact you're the owner of the object nor by the fact you're the admin).

File: src/box/alter.cc (hunk 5 above)
Comment (mkostoevr) [reply src/box/alter.cc]: That's a side effect fixed by fixing another problem: one must not be able to grant oneself if the only reason he could grant is having the "grant" privilege (e. g. the user is not the object owner nor admin). Otherwise having "grant" access could mean having them all.

Updated so that granting oneself it only denied if the "grant" access is the only reason the grant is possible (i. e. the user is not "admin" nor owner of the role).

File: src/box/alter.cc (hunk 6 above)
Comment (mkostoevr) [reply src/box/alter.cc]: The "grantor" is the user specified in the "grantor" field of `_priv` space tuple (it's the effective user by default). The logged-in user is the effective user, calling the API.

Before this patch, we've checked both of them: the grantor was checked in the switch block above, the effective user was checked in the `access_check_ddl`. Both effectively checked if the user is owner of the object or "admin".

Now we still check both of them, but we do it in the same function `access_check_ddl[_cr]` and also check if both have the `PRIV_GRANT` privilege. And now it's also done in case of the entity grant, cause now not only "admin" can grant entities.

File: test/box-luatest/gh_11528_grant_access_test.lua (hunk 7 above)
Comment (mkostoevr) [reply test/box-luatest/gh_11528_grant_access_test.lua]: Created an RFC to solve the problem.

File: src/box/alter.cc (hunk 8 above)
Comment (mkostoevr) [reply src/box/alter.cc]: Made it create a new lua call access entry on demand (as in `user.cc`) so it works as expected.

<details><summary>diff</summary>

```diff
diff --git a/src/box/alter.cc b/src/box/alter.cc
index 95c6fa5d9f..42eaf70c39 100644
--- a/src/box/alter.cc
+++ b/src/box/alter.cc
@@ -3947,9 +3947,12 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
                return -1;
        }
        const char *name = "";
-       auto free_name = make_scoped_guard([&] { free((char *)name); }, false);
        struct access *object = NULL;
        uint32_t owner = BOX_ID_NIL;
+       auto lua_call_cleanup = make_scoped_guard([&] {
+               free((char *)name);
+               access_lua_call_delete_if_empty(object);
+       }, false);
        switch (priv->object_type) {
        case SC_SPACE:
        {
@@ -4041,11 +4044,10 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
                        break;
                name = (char *)xstrndup(priv->object_name,
                                        priv->object_name_len);
-               free_name.is_active = true;
-               object = access_lua_call_find(priv->object_name,
-                                             priv->object_name_len);
-               /* Object can be NULL if no access had been granted yet. */
-               /* Also, no ownership check here. */
+               object = access_lua_call_find_or_create(
+                       priv->object_name, priv->object_name_len);
+               lua_call_cleanup.is_active = true;
+               /* No owner for the object. */
                break;
        default:
                break;
diff --git a/src/box/user.cc b/src/box/user.cc
index 3264f48336..b84bf83114 100644
--- a/src/box/user.cc
+++ b/src/box/user.cc
@@ -246,11 +246,7 @@ access_lua_call_find(const char *name, uint32_t name_len)
        return NULL;
 }
 
-/**
- * Returns cached runtime access information for the given Lua function name.
- * Creates one if it doesn't exist.
- */
-static struct access *
+struct access *
 access_lua_call_find_or_create(const char *name, uint32_t name_len)
 {
        uint32_t name_hash = mh_strn_hash(name, name_len);
@@ -277,11 +273,7 @@ access_lua_call_find_or_create(const char *name, uint32_t name_len)
        return node->access;
 }
 
-/**
- * Deletes cached runtime access information for a Lua function if it's empty
- * (i.e. grants no access to any user).
- */
-static void
+void
 access_lua_call_delete_if_empty(struct access *object)
 {
        for (int i = 0; i < BOX_USER_MAX; ++i) {
diff --git a/src/box/user.h b/src/box/user.h
index 69fc8218c7..771d1221f0 100644
--- a/src/box/user.h
+++ b/src/box/user.h
@@ -167,6 +167,20 @@ extern struct user *guest_user, *admin_user;
 struct access *
 access_lua_call_find(const char *name, uint32_t name_len);
 
+/**
+ * Returns cached runtime access information for the given Lua function name.
+ * Creates one if it doesn't exist.
+ */
+struct access *
+access_lua_call_find_or_create(const char *name, uint32_t name_len);
+
+/**
+ * Deletes cached runtime access information for a Lua function if it's empty
+ * (i.e. grants no access to any user).
+ */
+void
+access_lua_call_delete_if_empty(struct access *object);
+
 /**
  * Check if a role is granted to a user or role with the given auth_token.
  */
```

</details>

File: test/box-luatest/session_test.lua
Comment (mkostoevr) [reply test/box-luatest/session_test.lua:1]: The guilty change is dropped from the commit (the test can't run in parallel it seems, so the "don't grant oneself" update broke the `catch_flaky` workdlow).

File: changelogs/unreleased/gh-11528-grant-access.md [hunk 9]
```diff
@@ -0,0 +1,5 @@
+## feature/box
+
+* Introduced a new `grant` privilege that allows non-owners and non-admin
+  users to grant and revoke accesses to an object or object class the access
+  is granted for to other available users (gh-11528).
```
Comment (AArdeev) [inline changelogs/unreleased/gh-11528-grant-access.md]: * Introduced a new `grant` privilege that allows non-owners and non-admin
users to grant and revoke access to an object or object class for which
they have permissions, to other available users (gh-11528).

File: src/box/alter.cc (hunk 8 above)
Comment (mkostoevr) [reply src/box/alter.cc]: The changes are dropped from the commit.

File: test/box-luatest/gh_11528_grant_access_test.lua (hunk 7 above)
Comment (mkostoevr) [reply test/box-luatest/gh_11528_grant_access_test.lua]: Decided to create a pair of new privileges:
1. "grant" allowing to grant anything except "grant" and "metagrant";
2. "metagrant" allowing to grant "grant" and "metagrant".

None of the privilege allow granting oneself (it's only allowed if a user is owner of the granted object or admin, this behaviour is not changed).

File: test/box-luatest/gh_12089_user_entity_access_sysview_test.lua
Comment (locker) [inline test/box-luatest/gh_12089_user_entity_access_sysview_test.lua:1]: Please add a changelog for this bug fix.

File: test/box-luatest/gh_12088_sequence_name_test.lua
Comment (locker) [inline test/box-luatest/gh_12088_sequence_name_test.lua:1]: Please add a changelog for this bug fix.

File: src/box/memtx_tree.cc [hunk 10]
```diff
@@ -1978,6 +1978,10 @@ memtx_tree_index_create_iterator_with_offset(
 
 	canonicalize_lookup(&type, &key, part_count);
 
+	ERROR_INJECT_BOOL_ONCE(ERRINJ_INDEX_ITERATOR_NEW_ONCE, {
```
Comment (locker) [inline src/box/memtx_tree.cc]: This is a very artificial error injection. In practice, iterator creation never fails in memtx. Other ways where `rebuild_effective_grants` may fail are only caused by invalid schema AFAICS, which must never happen. That said, I don't think this a security issue: even if one could trigger it (which looks impossible), there's no way to exploit it, really. I don't think we need a changelog or a test for it. Moreover, I think that panicking in `rebuild_effective_grants` instead of returning an error would be just fine.

File: test/box-luatest/gh_11528_grant_access_test.lua [hunk 11]
```diff
@@ -59,3 +59,27 @@ g.test_fail_on_rebuild_effective_grants = function(cg)
             box.session.su, 'u', box.schema.space.create, 's')
     end)
 end
+
+-- Test that the dropped grants don't remain on the role.
+g.test_dropped_grants = function(cg)
```
Comment (locker) [inline test/box-luatest/gh_11528_grant_access_test.lua:31]: This doesn't look like an "internal" fix. Please add a changelog.

Anyway, I wouldn't call it a "security" issue because it's unclear how to exploit it.

File: src/box/alter.cc [hunk 12]
```diff
@@ -4045,29 +4032,45 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
...
-		diag_set(AccessDeniedError, priv_name(priv_type),
-			 schema_object_name(priv->object_type), name,
-			 grantor->def->name);
+	/*
+	 * Check the access grantor has the ability to grant: he is the object
+	 * owner or someone having the "grant" privilege. Please note that the
+	 * "admin" user has all possible privileges set.
+	 */
+	struct credentials grantor_cr;
+	credentials_create(&grantor_cr, grantor);
```
Comment (locker) [inline src/box/alter.cc]: Creating a temporary credentials object just to check access looks ugly. Anyway, checking both grantor and effective user is weird. I think we should check only the effective user. The grantor must be the same. Only the admin should be able to override the grantor.

BTW I don't see a single test where the ability to override the grantor would be tested.

File: changelogs/unreleased/gh-11528-grant-access.md [hunk 13]
```diff
@@ -0,0 +1,9 @@
+## feature/box
+
+* Introduced a new `grant` privilege. The privilege is only grantable on the
+  "universe". It allows a user to grant any privilege, excepting "grant" and
+  "metagrant", on an object, object class or the "universe" to any available
+  user excepting oneself (gh-11528).
+* Introduced a new `metagrant` privilege. The privilege is only grantable on
+  the "universe". It allows a user to grant "grant" and "metagrant" access to
+  to any available user excepting oneself (gh-11528).
```
Comment (locker) [inline changelogs/unreleased/gh-11528-grant-access.md]: One changelog entry would be enough.

File: src/box/alter.cc [hunk 14]
```diff
@@ -4066,11 +4076,6 @@ priv_def_check(struct priv_def *priv)
 			 "only object owner or admin can grant oneself");
 		return -1;
 	}
-	if (priv->access & PRIV_GRANT && grantor->def->uid != ADMIN) {
```
Comment (locker) [inline src/box/alter.cc]: Splitting this patch in two looks pointless. You have to remove the code added in the previous patch. This only complicates review IMO.

File: test/box-luatest/gh_12089_user_entity_access_sysview_test.lua
Comment (mkostoevr) [reply test/box-luatest/gh_12089_user_entity_access_sysview_test.lua:1]: <details><summary>Done.</summary>

```diff
diff --git a/changelogs/unreleased/gh-12089-user-entity-acces-sysview.md b/changelogs/unreleased/gh-12089-user-entity-acces-sysview.md
new file mode 100644
index 0000000000..e7218cff54
--- /dev/null
+++ b/changelogs/unreleased/gh-12089-user-entity-acces-sysview.md
@@ -0,0 +1,4 @@
+## bugfix/memtx
+
+* Fixed an invisibility of entries in the `_vuser` space view if a user has a
+  privilege on the `user` entity granted (gh-12089).
```

</details>

File: test/box-luatest/gh_12088_sequence_name_test.lua
Comment (mkostoevr) [reply test/box-luatest/gh_12088_sequence_name_test.lua:1]: <details><summary>Done.</summary>

```diff
diff --git a/changelogs/unreleased/gh-12088-sequence-name-access-fail.md b/changelogs/unreleased/gh-12088-sequence-name-access-fail.md
new file mode 100644
index 0000000000..453d994ea6
--- /dev/null
+++ b/changelogs/unreleased/gh-12088-sequence-name-access-fail.md
@@ -0,0 +1,4 @@
+## bugfix/memtx
+
+* Fixed a bug when a sequence name could be inaccessible to a user if he had an
+  access granted on the sequence by another user (gh-12088).
```

</details>

File: src/box/memtx_tree.cc (hunk 10 above)
Comment (mkostoevr) [reply src/box/memtx_tree.cc]: <details><summary>Made the function panic on an error.</summary>

```diff
diff --git a/src/box/alter.cc b/src/box/alter.cc
index 2bbab11a7a..fb33fd3e8d 100644
--- a/src/box/alter.cc
+++ b/src/box/alter.cc
@@ -4111,7 +4089,8 @@ grant_or_revoke(struct priv_def *priv, struct txn_stmt *rolled_back_stmt)
        if (priv_grant(grantee, priv) != 0)
                return -1;
        /* Apply the changes. */
-       return rebuild_effective_grants(grantee, rolled_back_stmt);
+       rebuild_effective_grants(grantee, rolled_back_stmt);
+       return 0;
 }
 
 /** A trigger called on rollback of grant. */
@@ -4155,39 +4134,37 @@ on_replace_dd_priv(struct trigger * /* trigger */, void *event)
 
        if (new_tuple != NULL && old_tuple == NULL) {   /* grant */
                if (priv_def_create_from_tuple(&priv, new_tuple) != 0 ||
-                   priv_def_check(&priv) != 0)
+                   priv_def_check(&priv) != 0 ||
+                   grant_or_revoke(&priv, NULL) != 0)
                        return -1;
                struct trigger *on_rollback =
                        txn_alter_trigger_new(revoke_priv, new_tuple);
                if (on_rollback == NULL)
                        return -1;
                txn_stmt_on_rollback(stmt, on_rollback);
-               if (grant_or_revoke(&priv, NULL) != 0)
-                       return -1;
        } else if (new_tuple == NULL) {                /* revoke */
                assert(old_tuple);
                if (priv_def_create_from_tuple(&priv, old_tuple) != 0 ||
                    priv_def_check(&priv) != 0)
                        return -1;
+               priv.access = 0;
+               if (grant_or_revoke(&priv, NULL) != 0)
+                       return -1;
                struct trigger *on_rollback =
                        txn_alter_trigger_new(modify_priv, old_tuple);
                if (on_rollback == NULL)
                        return -1;
                txn_stmt_on_rollback(stmt, on_rollback);
-               priv.access = 0;
-               if (grant_or_revoke(&priv, NULL) != 0)
-                       return -1;
        } else {                                       /* modify */
                if (priv_def_create_from_tuple(&priv, new_tuple) != 0 ||
-                   priv_def_check(&priv) != 0)
+                   priv_def_check(&priv) != 0 ||
+                   grant_or_revoke(&priv, NULL) != 0)
                        return -1;
                struct trigger *on_rollback =
                        txn_alter_trigger_new(modify_priv, old_tuple);
                if (on_rollback == NULL)
                        return -1;
                txn_stmt_on_rollback(stmt, on_rollback);
-               if (grant_or_revoke(&priv, NULL) != 0)
-                       return -1;
        }
        return 0;
 }
diff --git a/src/box/memtx_tree.cc b/src/box/memtx_tree.cc
index 3007e1a1af..160d942fe0 100755
--- a/src/box/memtx_tree.cc
+++ b/src/box/memtx_tree.cc
@@ -1978,10 +1978,6 @@ memtx_tree_index_create_iterator_with_offset(
 
        canonicalize_lookup(&type, &key, part_count);
 
-       ERROR_INJECT_BOOL_ONCE(ERRINJ_INDEX_ITERATOR_NEW_ONCE, {
-               diag_set(ClientError, ER_INJECTION, "iterator fail once");
-               return NULL;
-       });
        ERROR_INJECT(ERRINJ_INDEX_ITERATOR_NEW, {
                diag_set(ClientError, ER_INJECTION, "iterator fail");
                return NULL;
diff --git a/src/box/user.cc b/src/box/user.cc
index 3264f48336..9b722c589a 100644
--- a/src/box/user.cc
+++ b/src/box/user.cc
@@ -405,19 +405,18 @@ user_set_effective_access(struct user *user)
 /**
  * Reload a single user privilege from a privilege tuple.
  */
-static int
+static void
 user_reload_priv(struct user *user, struct tuple *tuple)
 {
        struct priv_def priv;
        if (priv_def_create_from_tuple(&priv, tuple) != 0)
-               return -1;
+               panic("Failed to reload a privilege");
        /* Skip role grants, we're only interested in real objects. */
        if (priv.object_type == SC_ROLE && priv.access & PRIV_X)
                priv.access &= ~PRIV_X;
        /* Assign the rest of privileges if any. */
        if (priv.access != 0)
                user_grant_priv(user, &priv);
-       return 0;
 }
 
 /**
@@ -426,11 +425,11 @@ user_reload_priv(struct user *user, struct tuple *tuple)
  * must account for the changes made by the statement and use the old data
  * (which will be the actual data after rollback).
  */
-static int
+static void
 user_reload_privs(struct user *user, struct txn_stmt *rolled_back_stmt)
 {
        if (user->is_dirty == false)
-               return 0;
+               return;
        struct priv_def *priv;
        /**
         * Reset effective access of the user in the
@@ -449,23 +448,20 @@ user_reload_privs(struct user *user, struct txn_stmt *rolled_back_stmt)
        {
                struct space *space = space_cache_find(BOX_PRIV_ID);
                if (space == NULL)
-                       return -1;
+                       panic("_priv space not found");
                char key[6];
                /** Primary key - by user id */
-               if (!space_is_memtx(space)) {
-                       diag_set(ClientError, ER_UNSUPPORTED,
-                                 space->engine->name, "system data");
-                       return -1;
-               }
+               if (!space_is_memtx(space))
+                       panic("_priv is not a MemTX space");
                struct index *index = index_find(space, 0);
                if (index == NULL)
-                       return -1;
+                       panic("PK of the _priv space not found");
                mp_encode_uint(key, user->def->uid);
 
                struct iterator *it = index_create_iterator(index, ITER_EQ,
                                                               key, 1);
                if (it == NULL)
-                       return -1;
+                       panic("Failed to create a _priv space iterator");
                IteratorGuard iter_guard(it);
                bool in_rollback = rolled_back_stmt != NULL;
                struct tuple *old_tuple = in_rollback ?
@@ -487,22 +483,20 @@ user_reload_privs(struct user *user, struct txn_stmt *rolled_back_stmt)
                                     key_def) == 0);
                struct tuple *tuple;
                if (iterator_next(it, &tuple) != 0)
-                       return -1;
+                       panic("Failed to advance a privilege iterator");
                while (tuple != NULL) {
                        if (in_rollback && tuple == new_tuple) {
                                tuple = old_tuple;
                                if (tuple == NULL)
                                        goto next_tuple;
                        }
-                       if (user_reload_priv(user, tuple) != 0)
-                               return -1;
+                       user_reload_priv(user, tuple);
 next_tuple:
                        if (iterator_next(it, &tuple) != 0)
-                               return -1;
+                               panic("Failed to advance a privilege iterator");
                }
-               if (in_rollback && new_tuple == NULL &&
-                   user_reload_priv(user, old_tuple) != 0)
-                       return -1;
+               if (in_rollback && new_tuple == NULL)
+                       user_reload_priv(user, old_tuple);
        }
        {
                /* Take into account privs granted through roles. */
@@ -523,7 +517,6 @@ user_reload_privs(struct user *user, struct txn_stmt *rolled_back_stmt)
        user_access_t new_access = universe.access[user->auth_token].effective;
        rlist_foreach_entry(creds, &user->credentials_list, in_user)
                creds->universal_access = new_access;
-       return 0;
 }
 
 /** }}} */
@@ -800,7 +793,7 @@ role_check(struct user *grantee, struct user *role)
  * part of. For the purpose of the rolled back statement, please refer to
  * `user_reload_privs`.
  */
-int
+void
 rebuild_effective_grants(struct user *grantee,
                         struct txn_stmt *rolled_back_stmt)
 {
@@ -853,9 +846,7 @@ rebuild_effective_grants(struct user *grantee,
                        struct user_map indirect_edges = user->roles;
                        user_map_minus(&indirect_edges, &transitive_closure);
                        if (user_map_is_empty(&indirect_edges)) {
-                               if (user_reload_privs(user,
-                                                     rolled_back_stmt) != 0)
-                                       return -1;
+                               user_reload_privs(user, rolled_back_stmt);
                                user_map_union(&next_layer, &user->users);
                        } else {
                                /*
@@ -876,7 +867,6 @@ rebuild_effective_grants(struct user *grantee,
                user_map_union(&transitive_closure, &current_layer);
                current_layer = next_layer;
        }
-       return 0;
 }
 
 
--- a/src/lib/core/errinj.h
+++ b/src/lib/core/errinj.h
@@ -105,7 +105,6 @@ struct errinj {
        _(ERRINJ_INDEX_OOM_COUNTDOWN, ERRINJ_INT, {.iparam = -1}) \
        _(ERRINJ_INDEX_RESERVE, ERRINJ_BOOL, {.bparam = false})\
        _(ERRINJ_INDEX_ITERATOR_NEW, ERRINJ_BOOL, {.bparam = false}) \
-       _(ERRINJ_INDEX_ITERATOR_NEW_ONCE, ERRINJ_BOOL, {.bparam = false}) \
        _(ERRINJ_IPROTO_CFG_LISTEN, ERRINJ_INT, {.iparam = 0}) \
        _(ERRINJ_IPROTO_DISABLE_ID, ERRINJ_BOOL, {.bparam = false}) \
        _(ERRINJ_IPROTO_DISABLE_WATCH, ERRINJ_BOOL, {.bparam = false}) \
@@ -303,9 +302,6 @@ void errinj_set_with_environment_vars(void);
 #define ERROR_INJECT_DOUBLE(ID, COND, CODE) ERROR_INJECT_COND(ID, ERRINJ_DOUBLE, COND, CODE)
 #define ERROR_INJECT_SLEEP_FOR(ID) \
        ERROR_INJECT_DOUBLE(ID, inj->dparam > 0, usleep(inj->dparam * 1000000))
-#define ERROR_INJECT_BOOL_ONCE(ID, CODE) \
-       ERROR_INJECT_COND(ID, ERRINJ_BOOL, inj->bparam, \
-                         { inj->bparam = false; } CODE)
 
 #if defined(__cplusplus)
 } /* extern "C" */
diff --git a/test/box-luatest/gh_11528_grant_access_test.lua b/test/box-luatest/gh_11528_grant_access_test.lua
index ccf8b4d507..a7b2886658 100644
--- a/test/box-luatest/gh_11528_grant_access_test.lua
+++ b/test/box-luatest/gh_11528_grant_access_test.lua
@@ -27,44 +27,6 @@ g.after_each(function(cg)
     end)
 end)
 
--- Test that grant rollback does not keep unwanted artifacts.
-g.test_fail_on_rebuild_effective_grants = function(cg)
-    cg.server:exec(function()
-        t.tarantool.skip_if_not_debug()
-
-        -- Create a user and two roles.
-        box.schema.user.create('u')
-        box.schema.role.create('r')
-        box.schema.role.create('r2')
-
-        -- Make the first role able to create a space.
-        box.session.su('admin', box.schema.role.grant,
-                       'r', 'create,write', 'universe')
-
-        -- Fail to grant the first role.
-        box.error.injection.set('ERRINJ_INDEX_ITERATOR_NEW_ONCE', true)
-        t.assert_error_msg_equals(
-            "Error injection 'iterator fail once'",
-            box.schema.user.grant, 'u', 'execute', 'role', 'r')
-
-        -- Successfully grant the second one.
-        box.schema.user.grant('u', 'execute', 'role', 'r2')
-
-        -- Check the first role is not assigned.
-        t.assert_equals(box.schema.user.info('u'), {
-            {'execute', 'role', 'public'},
-            {'execute', 'role', 'r2'},
-            {'session,usage', 'universe', ''},
-            {'alter', 'user', 'u'},
-        })
-
-        -- Check the user can't create a space as the first role would allow.
-        t.assert_error_msg_equals(
-            "Write access to space '_space' is denied for user 'u'",
-            box.session.su, 'u', box.schema.space.create, 's')
-    end)
-end
-
 -- Test that the dropped grants don't remain on the role.
 g.test_dropped_grants = function(cg)
     cg.server:exec(function()
```

</details>

File: test/box-luatest/gh_11528_grant_access_test.lua (hunk 11 above)
Comment (mkostoevr) [reply test/box-luatest/gh_11528_grant_access_test.lua:31]: <details><summary>Done.</summary>

```diff
diff --git a/changelogs/unreleased/gh-11528-drop-of-last-privs.md b/changelogs/unreleased/gh-11528-drop-of-last-privs.md
new file mode 100644
index 0000000000..cfa8c22719
--- /dev/null
+++ b/changelogs/unreleased/gh-11528-drop-of-last-privs.md
@@ -0,0 +1,4 @@
+## bugfix/memtx
+
+* Fixed a bug when object privileges could remain granted on revoke if they were
+  the last ones in the `_priv` entry (gh-11528).
```

</details>

File: src/box/alter.cc (hunk 12 above)
Comment (mkostoevr) [reply src/box/alter.cc]: Done (the `access_check_ddl` function is kept as is with the new commit, except for replacing the `user_access_t priv_type` argument with `user_access_t access_required`).

<details><summary>diff</summary>

```diff
diff --git a/src/box/alter.cc b/src/box/alter.cc
index 96e5cbacf8..fb33fd3e8d 100644
--- a/src/box/alter.cc
+++ b/src/box/alter.cc
@@ -75,21 +75,19 @@ box_schema_version_bump(void)
 }
 
 /**
- * Checks if the given user can perform a DDL operation on an object with
+ * Checks if the current user can perform a DDL operation on an object with
  * the given name, owner id, and cached runtime access information.
  * Returns 0 on success, -1 on failure.
  */
 static int
-access_check_ddl_cr(struct credentials *cr, const char *name,
-                   uint32_t owner_uid, struct access *object,
-                   enum schema_object_type type, user_access_t priv_type)
+access_check_ddl(const char *name, uint32_t owner_uid, struct access *object,
+                enum schema_object_type type, user_access_t access_required)
 {
-       /*
-        * If the user has universal access, don't bother
-        * with checks. No special check for ADMIN user is
-        * necessary since ADMIN has universal access.
-        */
-       user_access_t access = (user_access_t)priv_type & ~cr->universal_access;
+       struct credentials *cr = effective_user();
+       user_access_t has_access = cr->universal_access;
+
+       user_access_t access = ((PRIV_U | access_required) & ~has_access);
+       bool is_owner = owner_uid == cr->uid || cr->uid == ADMIN;
        if (access == 0)
                return 0; /* Access granted. */
        /* Check for specific entity access. */
@@ -105,7 +103,6 @@ access_check_ddl_cr(struct credentials *cr, const char *name,
         * the owner of the object, but this should be ignored --
         * CREATE privilege is required.
         */
-       bool is_owner = owner_uid == cr->uid;
        if (access == 0 || (is_owner && !(access & (PRIV_U | PRIV_C))))
                return 0; /* Access granted. */
        /*
@@ -136,18 +133,6 @@ access_check_ddl_cr(struct credentials *cr, const char *name,
        return -1;
 }
 
-/**
- * Same as `access_check_ddl_cr`, but the user is the current one and required
- * to have a global "usage" access.
- */
-static int
-access_check_ddl(const char *name, uint32_t owner_uid, struct access *object,
-                enum schema_object_type type, user_access_t priv_type)
-{
-       return access_check_ddl_cr(effective_user(), name, owner_uid,
-                                  object, type, priv_type | PRIV_U);
-}
-
 /**
  * Return an error if the given index definition
  * is incompatible with a sequence.
@@ -4049,17 +4034,10 @@ priv_def_check(struct priv_def *priv)
                (priv->access & grant_mask ? PRIV_GRANT : 0) |
                (priv->access & metagrant_mask ? PRIV_METAGRANT : 0);
        /*
-        * Check the access grantor has the ability to grant: he is the object
+        * Check the effective user has the ability to grant: he is the object
         * owner or someone having the privileges required. Please note that the
         * "admin" user has all possible privileges set.
         */
-       struct credentials grantor_cr;
-       credentials_create(&grantor_cr, grantor);
-       auto _ = make_scoped_guard([&] { credentials_destroy(&grantor_cr); });
-       if (access_check_ddl_cr(&grantor_cr, name, owner, object,
-                               priv->object_type, access_required) != 0)
-               return -1;
-       /* Check the effective user has the ability to grant. */
        if (access_check_ddl(name, owner, object,
                             priv->object_type, access_required) != 0)
                return -1;
```

</details>

File: changelogs/unreleased/gh-11528-grant-access.md (hunk 13 above)
Comment (mkostoevr) [reply changelogs/unreleased/gh-11528-grant-access.md]: <details><summary>Done.</summary>

```diff
--- a/changelogs/unreleased/gh-11528-grant-access.md
+++ b/changelogs/unreleased/gh-11528-grant-access.md
@@ -1,9 +1,7 @@
 ## feature/box
 
-* Introduced a new `grant` privilege. The privilege is only grantable on the
-  "universe". It allows a user to grant any privilege, excepting "grant" and
-  "metagrant", on an object, object class or the "universe" to any available
-  user excepting oneself (gh-11528).
-* Introduced a new `metagrant` privilege. The privilege is only grantable on
-  the "universe". It allows a user to grant "grant" and "metagrant" access to
-  to any available user excepting oneself (gh-11528).
+* Introduced new `grant` and `metagrant` privileges. They're only grantable on
+  the `universe`. The `grant` privilege allows a user to grant any privilege,
+  excepting `grant` and `metagrant`, on an object, object class or `universe`.
+  The `metagrant` allows to grant `grant` and `metagrant` privileges. Both only
+  allow granting to other users, no granting oneself allowed by them (gh-11528).
```

</details>

File: src/box/alter.cc (hunk 14 above)
Comment (mkostoevr) [reply src/box/alter.cc]: Merged the last two commits.

File: changelogs/unreleased/gh-12088-sequence-name-access-fail.md [hunk 15]
```diff
@@ -0,0 +1,4 @@
+## bugfix/memtx
```
Comment (locker) [inline changelogs/unreleased/gh-12088-sequence-name-access-fail.md]: It isn't memtx. It's box or core. Same comment for other changelog entries.

File: src/box/user.cc [hunk 16]
```diff
@@ -487,22 +483,20 @@ user_reload_privs(struct user *user, struct txn_stmt *rolled_back_stmt)
 				     key_def) == 0);
 		struct tuple *tuple;
 		if (iterator_next(it, &tuple) != 0)
-			return -1;
+			panic("Failed to advance a privilege iterator");
```
Comment (locker) [inline src/box/user.cc]: Let's add panic in one place with `diag_log` instead of patching all the error paths.

File: src/box/user.cc [hunk 17]
```diff
@@ -942,8 +930,7 @@ role_is_granted(struct user *role, uint8_t auth_token)
 }
 
 int
-priv_grant(struct user *grantee, struct priv_def *priv,
-	   struct txn_stmt *rolled_back_stmt)
+priv_grant(struct user *grantee, struct priv_def *priv)
```
Comment (locker) [inline src/box/user.cc:944]: Can you move the check done in this function to `priv_def_check`? Then we could turn its return value type to `void` as well.

File: src/box/alter.cc [hunk 18]
```diff
@@ -4045,29 +4017,43 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
...
+	 * The idea of the "grant" privilege is granularity: a user must be able
+	 * to grant, but no other operation is allowed with the priv. So making
+	 * him able to grant privileges oneself breaks the concept. We need to
+	 * prohibit granting a privilege oneself in case if it's not allowed by
+	 * being the "admin" user nor by being an owner of the object.
+	 */
+	if (grantee == grantor && grantor->def->uid != ADMIN &&
+	    (object == NULL || grantor->def->uid != owner)) {
+		diag_set(ClientError, ER_GRANT,
+			 "only object owner or admin can grant oneself");
```
Comment (locker) [inline src/box/alter.cc:4059]: That is, one can circumvent this limitation by specifying a custom grantor?

File: changelogs/unreleased/gh-12088-sequence-name-access-fail.md (hunk 15 above)
Comment (mkostoevr) [reply changelogs/unreleased/gh-12088-sequence-name-access-fail.md]: Changed to "box".

File: src/box/user.cc (hunk 17 above)
Comment (mkostoevr) [reply src/box/user.cc:944]: <details><summary>Yes.</summary>

```diff
diff --git a/src/box/alter.cc b/src/box/alter.cc
index 4b62a3e798..1cb03f0a98 100644
--- a/src/box/alter.cc
+++ b/src/box/alter.cc@@ -3922,6 +3922,7 @@ priv_def_create_from_tuple(struct priv_def *priv, struct tuple *tuple)
 static int
 priv_def_check(struct priv_def *priv, enum priv_type priv_type)
 {
+       bool on_revoke = (priv_type == PRIV_REVOKE);
        struct user *grantor = user_find(priv->grantor_id);
        if (grantor == NULL)
                return -1;
@@ -4073,6 +4074,12 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
                          "the grant tuple has no privileges");
                return -1;
        }
+       if (grantee->auth_token == ADMIN && priv->object_type == SC_UNIVERSE &&
+           (priv->access != (user_access_t)PRIV_ALL || on_revoke)) {
+               diag_set(ClientError, ER_GRANT,
+                        "can't revoke universe from the admin user");
+               return -1;
+       }
        return 0;
 }
 
@@ -4081,12 +4088,12 @@ priv_def_check(struct priv_def *priv, enum priv_type priv_type)
  * data. For the purpose of the rolled back statement, please refer to
  * `user_reload_privs`.
  */
-static int
+static void
 grant_or_revoke(struct priv_def *priv, struct txn_stmt *rolled_back_stmt)
 {
        struct user *grantee = user_by_id(priv->grantee_id);
        if (grantee == NULL)
-               return 0;
+               return;
        /* Manage the role if required. */
        if (priv->object_type == SC_ROLE) {
                struct user *role = user_by_id(priv->object_id);
@@ -4099,12 +4106,9 @@ grant_or_revoke(struct priv_def *priv, struct txn_stmt *rolled_back_stmt)
                        priv->access &= ~PRIV_X;
                }
        }
-       /* Manage the rest of the rights. */
-       if (priv_grant(grantee, priv) != 0)
-               return -1;
-       /* Apply the changes. */
+       /* Manage the rest of the rights and apply the changes. */
+       priv_grant(grantee, priv);
        rebuild_effective_grants(grantee, rolled_back_stmt);
-       return 0;
 }
 
 /** A trigger called on rollback of grant. */
@@ -4116,8 +4120,7 @@ revoke_priv(struct trigger *trigger, void *event)
        if (priv_def_create_from_tuple(&priv, tuple) != 0)
                return -1;
        priv.access = 0;
-       if (grant_or_revoke(&priv, (struct txn_stmt *)event) != 0)
-               return -1;
+       grant_or_revoke(&priv, (struct txn_stmt *)event);
        return 0;
 }
 
@@ -4127,9 +4130,9 @@ modify_priv(struct trigger *trigger, void *event)
 {
        struct tuple *tuple = (struct tuple *)trigger->data;
        struct priv_def priv;
-       if (priv_def_create_from_tuple(&priv, tuple) != 0 ||
-           grant_or_revoke(&priv, (struct txn_stmt *)event) != 0)
+       if (priv_def_create_from_tuple(&priv, tuple) != 0)
                return -1;
+       grant_or_revoke(&priv, (struct txn_stmt *)event);
        return 0;
 }
 
@@ -4148,9 +4151,9 @@ on_replace_dd_priv(struct trigger * /* trigger */, void *event)
 
        if (new_tuple != NULL && old_tuple == NULL) {   /* grant */
                if (priv_def_create_from_tuple(&priv, new_tuple) != 0 ||
-                   priv_def_check(&priv, PRIV_GRANT) != 0 ||
-                   grant_or_revoke(&priv, NULL) != 0)
+                   priv_def_check(&priv, PRIV_GRANT) != 0)
                        return -1;
+               grant_or_revoke(&priv, NULL);
                struct trigger *on_rollback =
                        txn_alter_trigger_new(revoke_priv, new_tuple);
                if (on_rollback == NULL)
@@ -4162,8 +4165,7 @@ on_replace_dd_priv(struct trigger * /* trigger */, void *event)
                    priv_def_check(&priv, PRIV_REVOKE) != 0)
                        return -1;
                priv.access = 0;
-               if (grant_or_revoke(&priv, NULL) != 0)
-                       return -1;
+               grant_or_revoke(&priv, NULL);
                struct trigger *on_rollback =
                        txn_alter_trigger_new(modify_priv, old_tuple);
                if (on_rollback == NULL)
@@ -4171,9 +4173,9 @@ on_replace_dd_priv(struct trigger * /* trigger */, void *event)
                txn_stmt_on_rollback(stmt, on_rollback);
        } else {                                       /* modify */
                if (priv_def_create_from_tuple(&priv, new_tuple) != 0 ||
-                   priv_def_check(&priv, PRIV_GRANT) != 0 ||
-                   grant_or_revoke(&priv, NULL) != 0)
+                   priv_def_check(&priv, PRIV_GRANT) != 0)
                        return -1;
+               grant_or_revoke(&priv, NULL);
                struct trigger *on_rollback =
                        txn_alter_trigger_new(modify_priv, old_tuple);
                if (on_rollback == NULL)
diff --git a/src/box/user.cc b/src/box/user.cc
index 9b722c589a..435151a7ae 100644
@@ -929,23 +940,15 @@ role_is_granted(struct user *role, uint8_t auth_token)
        return user_map_is_set(&transitive_closure, auth_token);
 }
 
-int
+void
 priv_grant(struct user *grantee, struct priv_def *priv)
 {
        struct access *object = access_get(priv);
        if (object == NULL)
-               return 0;
-       if (grantee->auth_token == ADMIN && priv->object_type == SC_UNIVERSE &&
-           priv->access != USER_ACCESS_FULL) {
-               diag_set(ClientError, ER_GRANT,
-                        "can't revoke universe from the admin user");
-               access_put(priv, object);
-               return -1;
-       }
+               return;
        struct access *access = &object[grantee->auth_token];
        access->granted = priv->access;
        access_put(priv, object);
-       return 0;
 }
 
 /** }}} */
```

</details>

<details><summary>Introduced the <code>on_revoke</code> parameter in the last commit for that.</summary>

```diff
diff --git a/src/box/alter.cc b/src/box/alter.cc
index b9805975ab..e529406ca5 100644
--- a/src/box/alter.cc
+++ b/src/box/alter.cc
@@ -3920,7 +3919,7 @@ priv_def_create_from_tuple(struct priv_def *priv, struct tuple *tuple)
  * In the future we must protect grant/revoke with a logical lock.
  */
 static int
-priv_def_check(struct priv_def *priv, enum priv_type priv_type)
+priv_def_check(struct priv_def *priv, bool on_revoke)
 {
        struct user *grantor = user_find(priv->grantor_id);
        if (grantor == NULL)
@@ -4150,7 +4136,7 @@ on_replace_dd_priv(struct trigger * /* trigger */, void *event)
 
        if (new_tuple != NULL && old_tuple == NULL) {   /* grant */
                if (priv_def_create_from_tuple(&priv, new_tuple) != 0 ||
-                   priv_def_check(&priv, PRIV_GRANT) != 0)
+                   priv_def_check(&priv, false) != 0)
                        return -1;
                grant_or_revoke(&priv, NULL);
                struct trigger *on_rollback =
@@ -4163,7 +4149,7 @@ on_replace_dd_priv(struct trigger * /* trigger */, void *event)
                if (priv_def_create_from_tuple(&priv, old_tuple) != 0)
                        return -1;
                priv.access = 0;
-               if (priv_def_check(&priv, PRIV_REVOKE) != 0)
+               if (priv_def_check(&priv, true) != 0)
                        return -1;
                grant_or_revoke(&priv, NULL);
                struct trigger *on_rollback =
@@ -4173,7 +4159,7 @@ on_replace_dd_priv(struct trigger * /* trigger */, void *event)
                txn_stmt_on_rollback(stmt, on_rollback);
        } else {                                       /* modify */
                if (priv_def_create_from_tuple(&priv, new_tuple) != 0 ||
-                   priv_def_check(&priv, PRIV_GRANT) != 0)
+                   priv_def_check(&priv, false) != 0)
                        return -1;
                grant_or_revoke(&priv, NULL);
                struct trigger *on_rollback =
```

</details>

File: src/box/user.cc (hunk 16 above)
Comment (mkostoevr) [reply src/box/user.cc]: <details><summary>Done.</summary>

```diff
diff --git a/src/box/user.cc b/src/box/user.cc
index 9b722c589a..435151a7ae 100644
@@ -846,7 +853,11 @@ rebuild_effective_grants(struct user *grantee,
                        struct user_map indirect_edges = user->roles;
                        user_map_minus(&indirect_edges, &transitive_closure);
                        if (user_map_is_empty(&indirect_edges)) {
-                               user_reload_privs(user, rolled_back_stmt);
+                               if (user_reload_privs(user,
+                                                     rolled_back_stmt) != 0) {
+                                       diag_log();
+                                       panic("Failed to reload privileges");
+                               }
                                user_map_union(&next_layer, &user->users);
                        } else {
                                /*
```

</details>

File: src/box/alter.cc (hunk 18 above)
Comment (mkostoevr) [reply src/box/alter.cc:4059]: <details><summary>Switched to the effective user check.</summary>

```diff
diff --git a/src/box/alter.cc b/src/box/alter.cc
index 887c4cbb5c..5293b6a352 100644
--- a/src/box/alter.cc
+++ b/src/box/alter.cc
@@ -4047,9 +4047,14 @@ priv_def_check(struct priv_def *priv)
         * him able to grant privileges oneself breaks the concept. We need to
         * prohibit granting a privilege oneself in case if it's not allowed by
         * being the "admin" user nor by being an owner of the object.
         *
         * Ignore the rule during the schema upgrade and downgrade (and so, the
         * replication and WAL recovery) so that we can alter user grants during
         * the procedure.
         */
-       if (grantee == grantor && grantor->def->uid != ADMIN &&
-           (object == NULL || grantor->def->uid != owner)) {
+       uint32_t effective_user_id = effective_user()->uid;
+       if (!dd_check_is_disabled() && effective_user_id == grantee->def->uid &&
+           effective_user_id != ADMIN && effective_user_id != owner) {
                diag_set(ClientError, ER_GRANT,
                         "only object owner or admin can grant oneself");
                return -1;
diff --git a/test/box-luatest/gh_11528_grant_access_test.lua b/test/box-luatest/gh_11528_grant_access_test.lua
index a7b2886658..79b87f6265 100644
--- a/test/box-luatest/gh_11528_grant_access_test.lua
+++ b/test/box-luatest/gh_11528_grant_access_test.lua
@@ -202,19 +202,20 @@ g.test_grant_oneself = function(cg)
                        'u', 'write', 'space', '_priv')
 
         -- Can't grant a privilege oneself with the "grant" access.
+        local cant_grant_oneself = 'Incorrect grant arguments: only object' ..
+                                   ' owner or admin can grant oneself'
         box.session.su('admin', box.schema.user.grant,
                        'u', 'grant', 'universe')
-        t.assert_error_msg_equals(
-            'Incorrect grant arguments:' ..
-            ' only object owner or admin can grant oneself',
-            box.session.su, 'u', box.schema.user.grant,
-            'u', 'execute', 'lua_call')
+        t.assert_error_msg_equals(cant_grant_oneself, box.session.su, 'u',
+                                  box.schema.user.grant, 'u',
+                                  'execute', 'lua_call')
 
-        -- Can revoke the privilege granted by "admin" though.
+        -- Can't revoke the privilege if it's granted by someone else either.
         box.session.su('admin', box.schema.user.grant,
                        'u', 'execute', 'lua_call')
-        box.session.su('u', box.schema.user.revoke,
-                       'u', 'execute', 'lua_call')
+        t.assert_error_msg_equals(cant_grant_oneself, box.session.su, 'u',
+                                  box.schema.user.revoke, 'u',
+                                  'execute', 'lua_call')
 
         -- The "metagrant" access required to grant "grant" or "metagrant".
         local need_metagrant = "Metagrant access to universe" ..
```

</details>

File: changelogs/unreleased/gh-12088-sequence-name-access-fail.md (hunk 15 above)
Comment (locker) [reply changelogs/unreleased/gh-12088-sequence-name-access-fail.md]: You missed other changelog entries - they need to be fixed, too.

Comment (mkostoevr) [reply changelogs/unreleased/gh-12088-sequence-name-access-fail.md]: <details><summary>Done.</summary>

```diff
diff --git a/changelogs/unreleased/gh-11528-drop-of-last-privs.md b/changelogs/unreleased/gh-11528-drop-of-last-privs.md
index cfa8c22719..f9d9dde862 100644
--- a/changelogs/unreleased/gh-11528-drop-of-last-privs.md
+++ b/changelogs/unreleased/gh-11528-drop-of-last-privs.md
@@ -1,4 +1,4 @@
-## bugfix/memtx
+## bugfix/box
 
 * Fixed a bug when object privileges could remain granted on revoke if they were
   the last ones in the `_priv` entry (gh-11528).
diff --git a/changelogs/unreleased/gh-12089-user-entity-acces-sysview.md b/changelogs/unreleased/gh-12089-user-entity-acces-sysview.md
index e7218cff54..e63d885162 100644
--- a/changelogs/unreleased/gh-12089-user-entity-acces-sysview.md
+++ b/changelogs/unreleased/gh-12089-user-entity-acces-sysview.md
@@ -1,4 +1,4 @@
-## bugfix/memtx
+## bugfix/box
 
 * Fixed an invisibility of entries in the `_vuser` space view if a user has a
   privilege on the `user` entity granted (gh-12089).
```

</details>
