### PR TITLE
console: fix `-i` being overruled by `!isatty()`

### LINKED ISSUE #5064: console tarantool ignores -i flag in case stdin is not a tty.
Tarantool version:
all
OS version:
all
Bug description:
When we executing some_command | tarantool -i. -i flag will be ignored, and command will be pars not by console.
Steps to reproduce:
Will be easy to reproduce after  #4317 will be fixed.

### PR DESCRIPTION
**Pull request by Lord-KA**
The interactive mode has been overruled by isatty check and is no more.
Now results of another command can be handled by tarantool.
For example:
```
$ echo 42 | tarantool -i
Tarantool 2.5.0-130-ge3cf64a6c
type 'help' for interactive help
tarantool> 42
---
- 42
...

tarantool> $
```
NO_DOC=bugfix
Closes #5064

### CODE REVIEW

File: test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+local g = t.group()
+
+local result_str =  [[tarantool> 42
+---
+- 42
+...
+
+tarantool> ]]
+
+g.test_local_console = function()
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua:11]: It is a local console problem. I can't imagine a test case for a remote connection.

**Review by igormunkin — APPROVED** [review]
@Lord-KA, thanks for the patch! LGTM, except the typo in the last line of the commit message: `s/'\'/'\n'/`.

Side note: I believe it's openSUSE, but I don't insist since I'm not sure I'm right.

File: src/lua/init.c [hunk 2]
```diff
@@ -936,7 +936,8 @@ run_script_f(va_list ap)
 			goto luajit_error;
 		if (lua_main(L, argc, argv) != 0)
 			goto error;
-	} else if (!is_a_tty || (path && strcmp(path, "-") == 0)) {
+	} else if ((!interactive && !is_a_tty) ||
+			((path && strcmp(path, "-") == 0))) {
```
Comment (igormunkin) [inline src/lua/init.c:940]: Looks like the outer pair of parentheses is excess, doesn't it?

**Review by igormunkin — CHANGES_REQUESTED** [review]
@Lord-KA, thanks for the patch! Please consider my comments below.

Re commit message: I agree with @ligurio, it might be nice to explicitly mention the fact that `-i` is ignored if the input source is not a tty ("overrulled" is unclear a bit at least to me).

**Comment by Lord-KA** [comment]
Removed the line in commit msg as irrelevant.

File: test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+
+local result_str =  [[tarantool> 42
+---
+- 42
+...
+
+tarantool> ]]
+
+g.test_console_ignores_i_flag_without_tty = function()
+    local cmd = [[printf '42\n' | tarantool -i 2>/dev/null]]
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua]: Fixed.

**Comment by Lord-KA** [comment]
```

File: test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+---
+- 42
+...
+
+tarantool> ]]
+
+local TARANTOOL_PATH = arg[-1]
+
+g.test_console_ignores_i_flag_without_tty = function()
+    local cmd = [[printf '42\n' | ]].. TARANTOOL_PATH .. [[ -i 2>/dev/null]]
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua]: Fixed.

File: test/box/gh-4703-on_shutdown-bug.result [hunk 5]
```diff
@@ -20,9 +20,10 @@ test_run:cmd("setopt delimiter ';'");
  | ---
  | - true
  | ...
+-- Extra \n is required on openSUSE.
```
Comment (Totktonada) [inline test/box/gh-4703-on_shutdown-bug.result:23]: How exactly it relates to openSUSE? Specific readline version? It would be good to reveal some details, if possible.

File: test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua [hunk 6]
```diff
@@ -0,0 +1,22 @@
...
+---
+- 42
+...
+
+tarantool> ]]
+
+local TARANTOOL_PATH = arg[-1]
+
+g.test_console_ignores_i_flag_without_tty = function()
+    local cmd = [[printf '42\n' | ]] .. TARANTOOL_PATH .. [[ -i 2>/dev/null]]
```
Comment (Totktonada) [inline test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua:14]: Nit: I think it would be good to hold `echo <...> | tarantool -i script.lua` behavior as well.

File: src/lua/init.c [hunk 7]
```diff
@@ -936,7 +936,8 @@ run_script_f(va_list ap)
 			goto luajit_error;
 		if (lua_main(L, argc, argv) != 0)
 			goto error;
-	} else if (!is_a_tty || (path && strcmp(path, "-") == 0)) {
+	} else if ((!interactive && !is_a_tty) ||
+			(path && strcmp(path, "-") == 0)) {
```
Comment (Totktonada) [inline src/lua/init.c:940]: How about removing `ERRINJ_STDIN_ISATTY` in a separate commit? It was added only because we had no option to enable the interactive mode unconditionally.

Comment (Totktonada) [reply src/lua/init.c:940]: (We can do it in a separate pull request.)

**Review by Totktonada — APPROVED** [review]
The new logic seems correct for me.

File: test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua (hunk 6 above)
Comment (Lord-KA) [reply test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua:14]: The behavior in this case is unchanged by the patch, as it follows different if-else branch. It seems unfit to add such test in this commit.

Comment (Totktonada) [reply test/app-luatest/gh_5064_console_ignore_i_flag_without_tty_test.lua:14]: I would like to see it in this commit or a separate one, but I don't insist here.

**Review by igormunkin — APPROVED** [review]
@Lord-KA, thanks for the fixes. LGTM now for both patches.

File: test/box/gh-4703-on_shutdown-bug.result (hunk 5 above)
Comment (Lord-KA) [reply test/box/gh-4703-on_shutdown-bug.result:23]: I didn't manage to find out what exactly caused it, but quite possible it is readline6 that is standard on openSUSE.

File: src/lua/init.c (hunk 7 above)
Comment (Totktonada) [reply src/lua/init.c:940]: PR #7555.
