### PR TITLE
Fix transaction boundaries in WAL and replication

### LINKED ISSUE #8746: Сannot recover from an anonymous replica after writing to a local space due to an on_replace trigger for a global space.
If at an anonymous replica due to an on_replace trigger on the global space write is made  to the local space, then recovering will be impossible. Run the tarantool like below:

```LUA
------------
-- Master
------------

-- Step 1
box.cfg{
    listen = 3301,
    replication = {3301, 3302},
}
box.schema.user.grant('guest', 'replication')

-- Step 3   
box.schema.space.create('loc', {is_local = true})
box.space.loc:create_index('pk')
box.schema.space.create('glob')
box.space.glob:create_index('pk')

-- Step 5
box.space.glob:insert{1}


---------------------
-- Anonymous replica
---------------------

-- Step 2
box.cfg{
    listen = 3302,
    replication = {3301, 3302},
    replication_anon = true,
    read_only = true,
}

-- Step 4
box.space.glob:on_replace(function()
    box.space.loc:replace{42}
end)
```
Now try to recover from the anonymous replica. If you recover without `force_recovery`, you will get error:
```
2023-06-07 10:53:32.787 [8125] main/103/interactive I> recover from `./00000000000000000004.xlog'
2023-06-07 10:53:32.788 [8125] main/103/interactive box.cc:822 E> error at request: {type: 'INSERT', replica_id: 1, lsn: 6, space_id: 513, index_id: 0, tuple: [42]}
2023-06-07 10:53:32.788 [8125] main/103/interactive box.cc:765 E> XlogError: found a first global row in a transaction with LSN/TSN mismatch
2023-06-07 10:53:32.788 [8125] main/103/interactive F> can't initialize storage: found a first global row in a transaction with LSN/TSN mismatch
```
 If you recover with `force_recovery = true`, you will get error:
```
2023-06-07 12:32:19.031 [16600] main/103/interactive I> recover from `./00000000000000000004.xlog'
2023-06-07 12:32:19.031 [16600] main/103/interactive box.cc:822 E> error at request: {type: 'INSERT', replica_id: 1, lsn: 6, space_id: 513, index_id: 0, tuple: [42]}
2023-06-07 12:32:19.031 [16600] main/103/interactive recovery.cc:292 E> skipping row {1: 6}
2023-06-07 12:32:19.031 [16600] main/103/interactive box.cc:765 E> XlogError: found a first global row in a transaction with LSN/TSN mismatch
tarantool: ./src/box/recovery.cc:280: void recover_xlog(recovery*, xstream*, const vclock*): Assertion `row.replica_id != 0 || row.group_id == GROUP_LOCAL' failed.
```

### LINKED ISSUE #8958: Tarantool 2.11.0: ER_PROTOCOL: Transaction id must be equal to LSN of the first row in the transaction.
**Bug description**

I caught misterious bug in asynchronous replication Tarantool 2.11.0:
`ER_PROTOCOL: Transaction id must be equal to LSN of the first row in the transaction.`

* OS: MacOS M1, Macos M1 (docker alpine)
* Architecture: arm, amd64?

```
Tarantool 2.11.0-0-g247a9a4
Target: Darwin-arm64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/tarantool/2.11.0_1 -DENABLE_BACKTRACE=TRUE
Compiler: /usr/bin/clang /usr/bin/clang++
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool-20230615-7295-5x7z7g/tarantool-2.11.0=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool-20230615-7295-5x7z7g/tarantool-2.11.0=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

It is quite hard to ease reproducer. Complete reproducer with steps is described in this repo/branch:
https://github.com/ochaton/hunting/tree/mmm-er-protocol

In general we setup 3 nodes in full-mesh master-master replication and create 2 spaces `bus` (ordinary space) and `inbox` (local space). We setup `bus:on_replace` trigger which filters tuples inside applier and inserts some tuples into local `inbox` space.

We have background fiber which atomically removes tuples from local space `inbox` and inserts tuples into ordinary `bus`.

**Actual behavior**

After sending single message via this mechanism 3rd node (not participating in logical communication) stops replication from replicaset. But other 2 nodes continue playing with each other.

Bug is reproduced when we mix local spaces with ordinary spaces in full-mesh master-master replication. Bug reproduced only with 3 instances or greater.

**Expected behavior**

Replication should continue running, because we do not violate any constraint in asynchronous replication

@sergepetrenko @sergos Please take a look

### PR DESCRIPTION
**Pull request by sergepetrenko**
commit 04aef9a9e0b9e6e3550e9413a0022cf3956f48d6
Author: Serge Petrenko <sergepetrenko@tarantool.org>
Date:   Thu Aug 24 11:28:39 2023 +0300

    box: fix force recovery for transactions with local rows
    
    Force recovery first tries to collect all rows of a transaction into a
    single list, and only then applies those rows.
    
    The problem was that it collected rows based on the row replica_id. For
    local rows replica_id is set to 0, but actually such rows can be part
    of a transaction coming from any instance.
    
    Fix recovery of such rows
    
    Follow-up #8746
    Follow-up #7932
    
    NO_DOC=bugfix
    NO_CHANGELOG=the broken behaviour couldn't be seen due to bug #8746

commit ce9444bfee4ccc08c6629d064a9a28393cccfaf5
Author: Serge Petrenko <sergepetrenko@tarantool.org>
Date:   Wed Aug 23 14:10:59 2023 +0300

    box: get rid of dummy NOPs after transactions ending with local rows
    
    In order to preserve transaction boundaries over replication, Tarantool
    writes a global NOP row after the last transaction row, if this row
    happens to be local. This is done to make sure that the is_commit flag,
    which is set only in the last transaction row, reaches the replica. This
    wouldn't happen if the last row was local.
    
    This workaround works fine for transactions completely authored by one
    instance: when both global and local rows come from operations of a
    single master.
    
    However, it's possible to append local rows to a remote master's
    transaction on a replica. For example, one can use on_replace triggers
    to write to replica's local space on each new transaction coming from
    master.
    
    In this case essentially a global NOP entry is added at the end of a
    remote master's transaction. This leads to several problems.
    
    First of all, this bumps replica's LSN, which is counter-intuitive,
    given that the replica might even be read-only. Besides, in a star
    topology this leads to master being unable to connect to the replica
    later on due to their vclocks becoming incompatible.
    
    Secondly, even if replication channel between master and replica is
    bidirectional, it creates a new row which should be replicated from
    replica to master, but at the same time is the last row of the master's
    transaction. Once master receives this row, it breaks its connection to
    replica due to transaction boundary violation (the last row of the
    transaction is received without its beginning).
    
    Adding a NOP row became extraneous since the previous commit, which made
    relay find transaction boundaries by itself.
    
    Closes #8958
    
    NO_DOC=bugfix

commit 4f16ab8f080ebe827f6eabbff37d026403e47203
Author: Serge Petrenko <sergepetrenko@tarantool.org>
Date:   Thu Sep 7 17:47:44 2023 +0300

    relay: send rows transactionally
    
    Some time ago we started writing transaction boundaries to WAL and
    respecting them in the replication stream: replicas wait for a full
    transaction receipt before applying it.
    
    However, during all these changes relay remained transaction-agnostic:
    it simply read single rows from WAL and sent them over to the receiver.
    
    This lead to a handful of ugly crutches: for example, tsn is not always
    equal to the lsn of the first global row of the transaction: if the
    first low is local, tsn is deduced from the first global row of the
    transaction.
    
    Also a dummy NOP was appended to the end of a transaction ending by a
    local row, so that is_commit flag wasn't lost by the replication.
    
    Let's make relay read a full transaction, filter out all the unnecessary
    rows, set the transaction boundaries accordingly and then send the
    transaction at once.
    
    Since in relay a single fiber sends data to the remote peer, there is no
    chance for a heartbeat to get in between rows of a single transaction:
    they're all sent at once. Hence the deletion of a corresponding guard
    `relay->is_sending_tx`.
    
    Prerequisite #8958
    
    NO_DOC=internal change
    NO_CHANGELOG=internal change
    NO_TEST=covered by existing tests

commit 5756f956bcda75b561ca5897d0c1f65a398527c5
Author: Serge Petrenko <sergepetrenko@tarantool.org>
Date:   Thu Jul 27 14:36:56 2023 +0300

    wal: fix transaction boundaries for replicated transactions
    
    Transaction boundaries were not updated correctly for transactions in
    which local space writes were made from a replication trigger. Existing
    transaction boundaries and row flags from the master were written as is
    on the replica. Actually, the replica should recalculate transaction
    boundaries and even WAIT_SYNC/WAIT_ACK flags.
    
    Transaction boundaries should be recalculated when a replica appends a
    local write at the end of the master's transaction, and
    WAIT_SYNC/WAIT_ACK should be overwritten when nopifying synchronous
    transactions coming from an old term.
    
    The latter fix has uncovered the bug in skipping outdated synchronous
    transactions: if one replica replaces a transaction from an old term
    with NOPs and then passes that transaction to the other replica, the
    other replica raises a split brain error. It believes the NOPs are an
    async transaction form an old term. This worked before the fix, because
    the rows were written with the original WAIT_ACK = true bit. Now this
    is fixed properly: we allow fully NOP async tranasctions from the old
    term.
    
    Closes #8746
    
    NO_DOC=bugfix
    NO_CHANGELOG=covered by the next commit

Closes #8746
Closes #8958

### CODE REVIEW

File: test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+    cg.replica_set = replica_set:new{}
+end)
+
+g.after_each(function(cg)
+    cg.replica_set:drop()
+end)
+
+local function prepare(cg)
+    cg.replica_set:start()
+    cg.master:exec(function()
```
Comment (Serpentian) [inline test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua:17]: The test is flaky. Orphan state:
```
[001] replication-luatest/gh_8746_replica_transactio>                 [ fail ]
[001] Test failed! Output from reject file /tmp/t/rejects/replication-luatest/gh_8746_replica_transaction_boundary.reject:
[001] Tarantool version is 3.0.0-alpha2-38-g5c6d83159
[001] TAP version 13
[001] 1..3
[001] # Started on Thu Aug 31 15:49:21 2023
[001] # Starting group: gh-8746-transaction-boundaries
[001] ok     1	gh-8746-transaction-boundaries.test_replica_recovery
[001] not ok 2	gh-8746-transaction-boundaries.test_replication_to_master
[001] #   Can't modify data on a read-only instance - it is an orphan
[001] #   stack traceback:
[001] #   	...on-luatest/gh_8746_replica_transaction_boundary_test.lua:17: in function 'prepare'
[001] #   	...on-luatest/gh_8746_replica_transaction_boundary_test.lua:77: in function 'gh-8746-transaction-boundaries.test_replication_to_master'
[001] #   	...
[001] #   	[C]: in function 'xpcall'
[001] #   artifacts:
[001] #   master -> /tmp/t/001_replication-luatest/artifacts/rs-7LOVjZBt2xAa/master-szUBIBOHrp_4
[001] #   replica -> /tmp/t/001_replication-luatest/artifacts/rs-7LOVjZBt2xAa/replica-MKQXDNdzjZy5
[001] ok     3	gh-8746-transaction-boundaries.test_replica_force_recovery
[001] # Ran 3 tests in 3.281 seconds, 2 succeeded, 1 errored
```

**Review by p7nov — APPROVED** [review]

File: test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua (hunk 1 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua:17]: Thanks for noticing!

Doesn't flake on my machine, so I can't check, but hope this helps:
```diff
diff --git a/test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua b/test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua
index d0a2f73dfb..4fac79bb51 100644
--- a/test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua
+++ b/test/replication-luatest/gh_8746_replica_transaction_boundary_test.lua
@@ -15,6 +15,7 @@ end)
 local function prepare(cg)
     cg.replica_set:start()
     cg.master:exec(function()
+        box.ctl.wait_rw()
         box.schema.space.create('test')
         box.space.test:create_index('pk')
         box.schema.space.create('loc', {is_local = true})
```

**Review by ochaplashkin — APPROVED** [review]
LGTM :rocket:

File: src/box/wal.c [hunk 2]
```diff
@@ -971,30 +972,16 @@ wal_assign_lsn(struct vclock *vclock_diff, struct vclock *base,
 			 * only capable of writing to local and
 			 * temporary spaces.
 			 */
-			if ((*row)->group_id != GROUP_LOCAL)
+			if ((*row)->group_id != GROUP_LOCAL) {
 				(*row)->replica_id = instance_id;
+				last_glob_row = row;
```
Comment (Serpentian) [inline src/box/wal.c:977]: This is the question of code readability, it's up to you, to fix it or not. I don't like, that we duplicate assigning `last_glob_row` in two mutually exclusive `if` code blocks. We can do it below, alongside with `first_glob_row`.

<details><summary>Diff</summary>

```diff
diff --git a/src/box/wal.c b/src/box/wal.c
index f28d6211e..dd65e34ed 100644
--- a/src/box/wal.c
+++ b/src/box/wal.c
@@ -974,14 +974,12 @@ wal_assign_lsn(struct vclock *vclock_diff, struct vclock *base,
 			 */
 			if ((*row)->group_id != GROUP_LOCAL) {
 				(*row)->replica_id = instance_id;
-				last_glob_row = row;
 			}
 
 			(*row)->lsn = vclock_inc(vclock_diff, (*row)->replica_id) +
 				      vclock_get(base, (*row)->replica_id);
 		} else {
 			int64_t diff = (*row)->lsn - vclock_get(base, (*row)->replica_id);
-			last_glob_row = row;
 			if (diff <= vclock_get(vclock_diff,
 					       (*row)->replica_id)) {
 				int64_t confirmed_lsn =
@@ -999,16 +997,18 @@ wal_assign_lsn(struct vclock *vclock_diff, struct vclock *base,
 			/* Reset row flags taken from the remote instance. */
 			(*row)->flags = 0;
 		}
+
 		/*
 		 * Use lsn of the first global row as
 		 * transaction id.
 		 */
-		if ((*row)->group_id != GROUP_LOCAL && tsn == 0) {
-			tsn = (*row)->lsn;
-			/*
-			 * Remember the tail being processed.
-			 */
-			first_glob_row = row;
+		if ((*row)->group_id != GROUP_LOCAL) {
+			last_glob_row = row;
+			if (tsn == 0) {
+				tsn = (*row)->lsn;
+				/** Remember the tail being processed. */
+				first_glob_row = row;
+			}
 		}
 		(*row)->tsn = tsn == 0 ? (*start)->lsn : tsn;
 	}

```

</details>

**Review by Serpentian — APPROVED** [review]
Thank you for the patch. Looks great. Only one minor comment from me

File: src/box/applier.cc [hunk 3]
```diff
@@ -1536,15 +1536,21 @@ applier_synchro_filter_tx(struct stailq *rows)
 	 */
```
Comment (Gerold103) [inline src/box/applier.cc:1536]: Can you apply this to the first commit?
```Diff
@@ -999,15 +999,16 @@ wal_assign_lsn(struct vclock *vclock_diff, struct vclock *base,
 		 * Use lsn of the first global row as
 		 * transaction id.
 		 */
-		if ((*row)->group_id != GROUP_LOCAL && tsn == 0) {
+		if (tsn == 0 && (*row)->group_id != GROUP_LOCAL) {
 			tsn = (*row)->lsn;
 			/*
 			 * Remember the tail being processed.
 			 */
 			first_glob_row = row;
 		}
-		(*row)->tsn = tsn == 0 ? (*start)->lsn : tsn;
 	}
+	if (tsn == 0)
+		tsn = (*start)->lsn;
 
 	/*
```
Now you set `row->tsn` 2 times for each row. The diff suggests to only find the target value in the first loop, fallback to `start->tsn` in a branch, and then set all in the second loop (which is already present below this diff). It should help to avoid 1 write for each row.

Also I swapped the condition parts - it is more likely to fail on `tsn == 0`, should help to avoid the second check most of the times.

File: changelogs/unreleased/gh-8958-remove-transaction-nop.md [hunk 4]
```diff
@@ -0,0 +1,6 @@
+## bugfix/replication
```
Comment (Gerold103) [inline changelogs/unreleased/gh-8958-remove-transaction-nop.md:1]: Speaking of the second commit. I just had an idea now. Have you considered hacking the transaction flags inside the relay? So it would read the whole txn into memory, find the last global row, and send it with `is_commit`. So no need to store this flag on disk. We simply stop writing NOPs, and the relay will find the last global row itself. Would it work?

**Review by Gerold103 — COMMENTED** [review]
Thanks for the patch!

File: src/box/applier.cc (hunk 3 above)
Comment (sergepetrenko) [reply src/box/applier.cc:1536]: > Now you set row->tsn 2 times for each row. The diff suggests to only find the target value in the first loop, fallback to start->tsn in a branch, and then set all in the second loop (which is already present below this diff). It should help to avoid 1 write for each row.

I don't understand. Why?

In the first loop (`for (struct xrow_header **row = start; row <= end; row++) {`) I set a valid tsn for all rows after the first glob row. And all the local rows before that get `start->tsn`.

In the second loop (`for (struct xrow_header **row = start; row < first_glob_row; row++)`) I only set tsns to the first couple of local rows, which came before first glob row. Not to all rows.

So if you hae a transaction [l, l, ... l, g, ...] where `l` stands for a local row and `g` stands for a global row, the rows up to the first `g` will receive a `(*start)->tsn`, while all the rows after the first `g` will receive a valid tsn. The second loop will rewrite tsns of the rows up to the first `g`,  but not of all the rows.

If I understood you correctly, you want to assign all tsns in the second loop. But then I'll always have to go through two loops. Even if tsn is known right in the first transaction row. And even if there are no global rows in the transaction.

With the current approach both cases above require a single loop (the first one), and the second one is skipped. Meaning there is only one tsn assignment per row. The only case when we write tsn twice happens only for the first local rows of a transaction, up to the first global row.

> Also I swapped the condition parts - it is more likely to fail on tsn == 0, should help to avoid the second check most of the times.

Applied:
```diff
diff --git a/src/box/wal.c b/src/box/wal.c
index ac30de209a..13ed7a0184 100644
--- a/src/box/wal.c
+++ b/src/box/wal.c
@@ -999,7 +999,7 @@ wal_assign_lsn(struct vclock *vclock_diff, struct vclock *base,
                 * Use lsn of the first global row as
                 * transaction id.
                 */
-               if ((*row)->group_id != GROUP_LOCAL && tsn == 0) {
+               if (tsn == 0 && (*row)->group_id != GROUP_LOCAL) {
                        tsn = (*row)->lsn;
                        /*
                         * Remember the tail being processed.
```

File: changelogs/unreleased/gh-8958-remove-transaction-nop.md (hunk 4 above)
Comment (sergepetrenko) [reply changelogs/unreleased/gh-8958-remove-transaction-nop.md:1]: Good idea, I didn't think of it, actually. Sounds much better than the current approach. Although there will be an added cost of finding the last global row after reading the transaction into memory.

It seems we'll have to read full transactions in relay for the sake of replication filters anyway. To preserve transaction boundaries in filtered streams. So I think it's worth choosing the same approach here. Will try.

File: src/box/wal.c (hunk 2 above)
Comment (sergepetrenko) [reply src/box/wal.c:977]: It seems I'll have to dump this commit and instead make relay transactional.

File: src/box/applier.cc (hunk 3 above)
Comment (Gerold103) [reply src/box/applier.cc:1536]: Sorry, I made a mistake, all is much simpler. I just didn't notice that the 2 loops have different end condition.

**Comment by sergepetrenko** [comment]
To be sure that such relay rewriting won't hurt replication performance, I conducted some tests with [1mops_write](https://github.com/tarantool/tarantool/blob/master/perf/lua/1mops_write.lua) test.

I ran Tarantool 3.0.0-alpha3-24-g74f723bb26 (labeled master in csv) and the same version with this patch applied on top (labeled relay in csv). I also tried various `--fibers` and `--transaction` settings and collected the data for 2 and 3 nodes (1 and 2 replicas).

Here are the results in csv:

File: src/box/relay.cc [hunk 5]
```diff
@@ -37,6 +37,7 @@
 #include "cbus.h"
```
Comment (Serpentian) [inline src/box/relay.cc:37]: Typo in the commit msg:

> if the first ~~low~~ row is local,

**Review by Serpentian — APPROVED** [review]
Thank you for your patch. It'll be much easier to integrate replication filters here. I have no objections

File: src/box/relay.cc (hunk 5 above)
Comment (sergepetrenko) [reply src/box/relay.cc:37]: Thanks for noticing!
Fixed.

File: src/box/relay.cc [hunk 6]
```diff
@@ -1255,9 +1238,104 @@ relay_send_row(struct xstream *stream, struct xrow_header *packet)
...
+
+/** Save a single transaction row for the future use. */
+static void
+relay_save_row(struct relay *relay, struct rlist *tx,
+	       struct xrow_header *packet)
+{
+	struct relay_row *tx_row = lsregion_alloc_object(&relay->lsregion,
+							 ++relay->lsr_id,
+							 struct relay_row);
+	if (tx_row == NULL) {
```
Comment (Gerold103) [inline src/box/relay.cc:1310]: Maybe use `xlsregion_alloc()`? Same in the other place.

File: src/box/relay.cc [hunk 7]
```diff
@@ -1266,27 +1344,43 @@ relay_send_row(struct xstream *stream, struct xrow_header *packet)
...
+	rlist_create(tx);
+	lsregion_gc(&relay->lsregion, relay->lsr_id);
+}
+
+static void
+relay_process_row(struct xstream *stream, struct xrow_header *packet)
+{
+	struct relay *relay = container_of(stream, struct relay, stream);
+	static __thread int64_t read_tsn = 0;
+	static __thread struct rlist current_tx;
```
Comment (Gerold103) [inline src/box/relay.cc:1359]: I would suggest to avoid global variables where possible, and move them into `struct relay`.

**Review by Gerold103 — APPROVED** [review]
Thanks for the fixes!

**Comment by sergepetrenko** [comment]
Cherry-picked to 2.11: c8594fbd80 .. 4643a26a2d

**Comment by sergepetrenko** [comment]
Cherry-picked to 2.10: 14e1d055a1 .. 4753208cf7

Didn't cherry-pick the last commit, it fixes a system nonexistent in 2.10
Cherry-picked an additional auxiliary commit (14e1d055a1)
