### PR TITLE
core: rework backtrace

### LINKED ISSUE #4002: Include fiber creation stack in fiber.info()
This is a follow up for #3538.

Currently `fiber.info()` backtrace starts with `coro_init` frame.

Example:

```lua
-- script.lua
local yaml = require('yaml')
local fiber = require('fiber')

function foo()
	local fiber_info = fiber.info()
	local fiber_id = fiber.self():id()
	local stack = fiber_info[fiber_id].backtrace
	print(yaml.encode(stack))
end

function bar()
	fiber.create(foo)
end

bar()
```

```console
$ tarantool ./script.lua 
---
- C: '#0  0x56199681b416 in fiber_stat+70'
- C: '#1  0x561996802514 in lbox_fiber_info+52'
- L: info in =[C] at line -1
- L: (unnamed) in @./test.lua at line 6
- C: '#2  0x561996834a57 in lj_BC_FUNCC+52'
- C: '#3  0x561996846534 in lua_pcall+100'
- C: '#4  0x561996808113 in luaT_call+19'
- C: '#5  0x561996802476 in lua_fiber_run_f+86'
- C: '#6  0x56199673a43c in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+12'
- C: '#7  0x561996819610 in fiber_loop+48'
- C: '#8  0x5619969607ff in coro_init+63'
...
```

From this stack I can't determine who created the fiber.

I think it would be useful to capture a part of stack prior to fiber creation.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
# core: refactor subsystem
Split backtrace component into two parts: Core and Lua — Core backtrace
is now completely independent from Lua.

Remove `proc_cache` from backtrace, as libunwind caches unwinding
information internally, see:
https://www.nongnu.org/libunwind/man/libunwind(3).html.

Rework backtrace implementation: instead of in-place unwinding, collect
sufficient unwinding information using fast `unw_backtrace` function in
order to resolve function names and locations on-demand later on — split
collection and processing of stack frames.

GNU libunwind does not support macOS platform, so we have to stick with
LLVM libunwind, which has a lot more limited API: because of this we
have to use some workarounds.

Drop support of architectures other than x86_64 and AARCH64 for context
switching.

Needed for #4002

# core: re-enable backtrace feature on AARCH64
After fixing libunwind issues in https://github.com/tarantool/tarantool/commit/7dc9fe44a5aebc2b44c240221d2a71cd6d97b6b0, libcoro fibers issues in
https://github.com/tarantool/tarantool/commit/28f9bd6f1e4827f977f33639199b020fb4b72ae8 and https://github.com/tarantool/tarantool/commit/997f4e045a381c4dbef847c33d641c17ad14d01a, we can now re-enable backtrace feature on AARCH64.

For some not investigated reason `unw_backtrace` does not collect any
ips when "-mbranch-protection" compile feature is enabled: provide a
workaround for this case.

Closes https://github.com/tarantool/tarantool/issues/6060

# core: introduce parent backtrace collection
With backtrace implementation reworked in afc100d, we can now
efficiently collect unwinding information about parents at fiber
creation time:

* Add `backtrace_cat` helper for concatenating backtraces.
* Add 'parent_bt' field to `struct fiber` for storing fiber parent's backtrace.
* Add `fiber_parent_backtrace_enabled` and corresponding C/Lua toggles for controlling parent backtrace collection for newly created fibers.

Closes #4002

### CODE REVIEW

**Review by locker — CHANGES_REQUESTED** [review]
Please see a few comments inline. Mostly, coding style related. I haven't looked the patch thoroughly enough yet so there may be more. The main concern is that you make core depend on Lua, which doesn't look right.

File: third_party/coro/coro.c [hunk 1]
```diff
@@ -103,9 +105,20 @@ coro_init (void)
...
-  asm (".cfi_undefined rip");
-#endif
+  /*
+   * Call-chain ends here: we need to invalidate this frame's return
+   * address to make unwinding stop here.
+   * Some nuances on x86_64, see:
+   * https://github.com/libunwind/libunwind/blob/ec171c9ba7ea3abb2a1383cee2988a7
+   * abd483a1f/src/x86_64/Gstep.c#L91-L92
+   * https://github.com/libunwind/libunwind/blob/ec171c9ba7ea3abb2a1383cee2988a7
+   * abd483a1f/src/dwarf/Gparser.c#L877
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply third_party/coro/coro.c]: Fixed in scope of #6889: https://github.com/tarantool/tarantool/pull/6889/files#diff-2726d9b23d82cd2fa27d3a7636fcd6748b30ac46fca458e6bf3da72f8220e330R113-R114.

File: src/lib/core/backtrace.cc [hunk 2]
```diff
@@ -186,49 +201,208 @@ backtrace(char *start, size_t size)
 	return start;
 }
 
+void
+backtrace_init(void)
+{
+#ifndef __APPLE__
+	unw_proc_info_t proc_info;
+	if (backtrace_lua_stk_start_ip != NULL) {
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: Removed this code during patch refactoring.

File: src/lib/core/backtrace.cc [hunk 3]
```diff
@@ -44,21 +44,36 @@
...
 
 #define BACKTRACE_NAME_MAX 200
 
 static __thread struct region cache_region;
 static __thread struct mh_i64ptr_t *proc_cache = NULL;
 
+/* Lua stack beginning, used for detecting Lua frames. */
+static void *backtrace_lua_stk_start_ip = (void *)lj_BC_FUNCC;
+/* Lua stack ending, ditto. */
+static void *backtrace_lua_stk_end_ip;
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: Fixed:
* changed `stk` to `stack`
* removed redundant prefixes for static variables and function

File: src/lib/core/backtrace.cc [hunk 4]
```diff
@@ -186,49 +201,208 @@ backtrace(char *start, size_t size)
...
+	}
+#else /* __APPLE__ */
+	backtrace_lua_stk_start_ip = (void *)lj_BC_FUNCC;
+	backtrace_lua_stk_end_ip = NULL;
+#endif /* __APPLE__ */
+}
+
+/* Resolve function name and offset based on `ip`. */
+int
+backtrace_resolve_from_ip(unw_word_t ip, const char **proc_name,
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: This function is now exposed as `core_backtrace_resolve_frame`.

File: src/lua/init.c [hunk 5]
```diff
@@ -724,6 +724,9 @@ tarantool_lua_init(const char *tarantool_bin, int argc, char **argv)
 	rl_catch_signals = 0;
 	rl_catch_sigwinch = 0;
 #endif
+#ifdef ENABLE_BACKTRACE
+	backtrace_init();
+#endif
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lua/init.c]: Now only the Lua backtrace component is initialized here.

File: src/lib/core/backtrace.h [hunk 6]
```diff
@@ -40,20 +40,103 @@ extern "C" {
...
+ *
+ * Nota bene: requires its own stack frame — hence, NOINLINE.
+ *
+ * Returns the number of frames collected.
+ */
+void
+backtrace_collect(struct backtrace *bt, struct fiber *fiber);
 
+/*
+ * Run 'c_cb' and 'lua_cb' on each C/C++ and Lua frame of 'bt' correspondingly.
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Fixed: updated all comments.

File: src/lib/core/backtrace.h [hunk 7]
```diff
@@ -40,20 +40,103 @@ extern "C" {
...
+/*
+ * Initialize backtrace subsystem: set callback for Lua frame collection.
+ */
+void
+backtrace_init(void);
+
+/*
+ * Collect current stack snapshot of a current context of 'fiber' to 'bt'.
+ *
+ * Nota bene: requires its own stack frame — hence, NOINLINE.
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h:76]: Ditto.

File: src/lib/core/backtrace.h [hunk 8]
```diff
@@ -40,20 +40,103 @@ extern "C" {
...
+ *
+ * Returns the number of frames collected.
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Ditto.

File: src/lib/core/backtrace.cc [hunk 9]
```diff
@@ -44,21 +44,36 @@
 #define CRLF "\n"
 
 #ifdef ENABLE_BACKTRACE
+#define UNW_LOCAL_ONLY
 #include <libunwind.h>
+#undef UNW_LOCAL_ONLY
+
+#include "lua/fiber.h"
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: Fixed: split backtrace component into Core and Lua parts.

File: src/lib/core/backtrace.cc [hunk 10]
```diff
@@ -186,49 +201,208 @@ backtrace(char *start, size_t size)
...
+	for (int frame_no = 0; frame_no < BACKTRACE_FRAMES_CNT_MAX + 2;
+	     ++frame_no) {
+		if (frame_no >= 2) {
+			if (backtrace_append_ip(bt, fiber, &unw_cur) != 0)
+				break;
+		}
+		int rc = unw_step(&unw_cur);
+		if (rc < 0) {
+#ifndef __APPLE__
+			say_error("unwinding error: unw_step_failed with: %s",
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: Fixed: typo.

File: src/lib/core/backtrace.h [hunk 11]
```diff
@@ -40,20 +40,103 @@ extern "C" {
...
+		void *ip;
+		/** Lua frame */
+		struct {
+			/* Current line inside Lua function. */
+			int line;
+			/* Lua function name. */
+			char proc_name[BACKTRACE_LUA_LEN_MAX];
+			/* Lua source file name. */
+			char src_name[BACKTRACE_LUA_LEN_MAX];
+		};
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Fixed: made Lua backtrace inherit from Core backtrace base class.

File: src/lib/core/backtrace.h [hunk 12]
```diff
@@ -40,20 +40,103 @@ extern "C" {
...
+	};
+};
+
+/*
+ * Context for storing an array of 'struct backtrace_frame's along with context
+ * for pushing them to Lua.
+ */
+struct backtrace {
+	/* Number of frames collected. */
+	int frames_cnt;
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Fixed: changed all abbreviations to full words.

File: src/lib/core/backtrace.h [hunk 13]
```diff
@@ -40,20 +40,103 @@ extern "C" {
...
+};
+
+/*
+ * Each language used in our runtime can have its own specific frame
+ * information.
+ */
+enum {
+	BACKTRACE_FRAME_TYPE_C,
+	BACKTRACE_FRAME_TYPE_LUA,
+};
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h:35]: Fixed: addressed this issue with inheritance.

File: src/lib/core/backtrace.cc [hunk 14]
```diff
@@ -186,49 +201,208 @@ backtrace(char *start, size_t size)
...
+		backtrace_collect_lua_frames_cb(bt, fiber);
+	backtrace_append_c_frame(bt, ip);
+}
+#else /* __APPLE__ */
+/*
+ * Ditto.
+ */
+static int
+backtrace_append_ip(struct backtrace *bt, struct fiber *fiber,
+		    unw_cursor_t *unw_cur)
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: Technically, this wasn't function overloading :)

Removed this code during patch refactoring.

File: third_party/coro/coro.c [hunk 15]
```diff
@@ -320,21 +338,32 @@ trampoline (int sig)
...
+#else /* __APPLE__ */
          "\tb abort\n"
-# endif
+#endif /* __APPLE__ */
          ".cfi_endproc\n"
+#else /* ENABLE_BACKTRACE */
+	 "\tmov x0, x20\n"
+         "\tblr x19\n"
+#ifdef __APPLE__
+         "\tb _abort\n"
```
Comment (alyapunov) [inline third_party/coro/coro.c:362]: It seem that there several lines identical in both branches `#ifdef ENABLE_BACKTRACE`. Could we make it outside of `#ifdef ENABLE_BACKTRACE`?

File: src/lua/backtrace.h [hunk 16]
```diff
@@ -0,0 +1,110 @@
...
+ */
+struct lua_backtrace {
+	/* Core backtrace information. */
+	struct core_backtrace core_bt;
+	/* Ordinal number of first Lua frame in backtrace. */
+	int first_lua_frame_no;
+	/* Number of Lua frames collected. */
+	int frame_count;
+	/* Array of Lua frame data. */
+	struct lua_frame frames[LUA_BACKTRACE_FRAME_COUNT_MAX];
```
Comment (locker) [inline src/lua/backtrace.h:53]: I may be wrong, but AFAIK there may be several Lua stacks within a stack: a C function may call a Lua function (see [`luaL_loadstring`](https://www.lua.org/manual/5.1/manual.html#luaL_loadstring)), which in turn may call another C function, and so on. AFAICS this backtrace implementation wouldn't work in this case.

File: test/app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua [hunk 17]
```diff
@@ -41,10 +41,9 @@ if #arg == 0 then
                           '<LUABIN> 2>&1 <SCRIPT>', '%<(%w+)>', vars)
 
   for _, ch in pairs(checks) do
-    local res
     local proc = io.popen((cmd .. (' %s'):rep(#ch.arg)):format(unpack(ch.arg)))
-    for s in proc:lines() do res = s end
-    assert(res, 'proc:lines failed')
+    local res = proc:read()
+    assert(res, 'proc:read failed')
```
Comment (locker) [inline test/app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua:46]: Why do you need to update the test?

File: changelogs/unreleased/fiber-parent-backtrace.md [hunk 18]
```diff
@@ -0,0 +1,5 @@
+## feature/core
+
+* Introduce new `fiber.parent_backtrace_enable` and
+  `fiber.parent_backtrace_disable` handles for toggling collection of parent
+  backtraces for newly created fibers (disabled by default).
```
Comment (locker) [inline changelogs/unreleased/fiber-parent-backtrace.md:5]: Nit: A changelog should be in Past Simple. The ticket number is missing. Better emphasize the feature you introduced, not the handles:

```
* Implemented collection of parent backtrace for newly created fibers.
  To enable the feature, call `fiber.parent_backtrace_enable` (gh-4302).
```

Also, please improve the doc bot request: write a code example for tech writers.

File: src/lua/backtrace.h (hunk 16 above)
Comment (locker) [reply src/lua/backtrace.h:53]: To illustrate the problem, I ran the following script before and after the first commit of this PR:

<details><summary>Test script</summary>

```lua
local fiber = require('fiber')
local net = require('net.box')
local yaml = require('yaml')

box.cfg{listen = 3301, log_level = 'warn'}

local c = net.connect(box.cfg.listen)
local info
c:on_disconnect(function()
    info = fiber.self():info()
end)
c:close()

print(yaml.encode(info))
os.exit(0)
```

</details>

BTW the first commit doesn't build. To fix it I had to apply the following patch:

<details><summary>Build fix</summary>

```diff
diff --git a/src/lib/core/backtrace.cc b/src/lib/core/backtrace.cc
index 10498e25216a..1e28cdbc6048 100644
--- a/src/lib/core/backtrace.cc
+++ b/src/lib/core/backtrace.cc
@@ -43,6 +43,7 @@ __attribute__ ((__force_align_arg_pointer__))
 static NOINLINE void *
 collect_current_stack(struct core_backtrace *bt, void *stack)
 {
+#ifndef __APPLE__
 	bt->frame_count = unw_backtrace((void **)bt->frames,
 					CORE_BACKTRACE_FRAME_COUNT_MAX);
 #else /* __APPLE__ */
```

</details>

Here are the results:

<details><summary>Before</summary>

```
---
csw: 26
backtrace:
- C: '#0  0x5616c8366603 in lbox_fiber_object_info+130'
- L: info in =[C] at line -1
- L: func in @../test.lua at line 10
- L: run in @builtin/internal.trigger.lua at line 61
- L: (unnamed) in @builtin/box/net_box.lua at line 289
- C: '#1  0x5616c83d89bf in lj_BC_FUNCC+52'
- C: '#2  0x5616c83db419 in jit_secure_call+445'
- C: '#3  0x5616c83e3240 in lua_call+199'
- C: '#4  0x5616c8351be5 in netbox_transport_on_state_change+229'
- C: '#5  0x5616c8353338 in luaT_netbox_transport_stop+302'
- L: stop in =[C] at line -1
- L: close in @builtin/box/net_box.lua at line 665
- L: (unnamed) in @../test.lua at line 12
- C: '#6  0x5616c83d89bf in lj_BC_FUNCC+52'
- C: '#7  0x5616c83e3597 in lua_pcall+849'
- C: '#8  0x5616c836c588 in luaT_call+45'
- C: '#9  0x5616c8364210 in lua_main+189'
- C: '#10 0x5616c836475d in run_script_f+1332'
- C: '#11 0x5616c8140977 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34'
- C: '#12 0x5616c8393ad6 in fiber_loop+136'
- C: '#13 0x5616c870944a in coro_init+88'
memory:
  total: 516480
  used: 0
time: 0
name: test.lua
fid: 103
...
```

</details>

<details><summary>After</summary>

```
---
csw: 26
backtrace:
- C: '#1  0x561df602256b in lbox_fiber_statof_map+808'
- C: '#2  0x561df60230f5 in lbox_fiber_object_info+130'
- L: '#3  info in =[C]:-1'
- L: '#4  func in @../test.lua:10'
- L: '#5  run in @builtin/internal.trigger.lua:61'
- L: '#6  (unnamed) in @builtin/box/net_box.lua:289'
- C: '#7  0x561df60959df in lj_BC_FUNCC+52'
- C: '#8  0x561df6098439 in jit_secure_call+445'
- C: '#9  0x561df60a0260 in lua_call+199'
- C: '#10 0x561df600ebf5 in netbox_transport_on_state_change+229'
- C: '#11 0x561df6010348 in luaT_netbox_transport_stop+302'
- C: '#12 0x561df60959df in lj_BC_FUNCC+52'
- C: '#13 0x561df60a05b7 in lua_pcall+849'
- C: '#14 0x561df602907a in luaT_call+45'
- C: '#15 0x561df602119f in lua_main+189'
- C: '#16 0x561df60216ec in run_script_f+1332'
- C: '#17 0x561df5dfd987 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34'
- C: '#18 0x561df60515b6 in fiber_loop+136'
- C: '#19 0x561df63c648a in coro_init+88'
memory:
  total: 516480
  used: 0
time: 0
name: test.lua
fid: 103
...
```

</details>

It doesn't look like mere refactoring.

File: src/lib/core/backtrace.cc [hunk 19]
```diff
@@ -1,336 +1,172 @@
...
- * 4. Restore old stack pointer from wrapper return and restore old fiber
- *    contex.
- *
- * @param @unw_context unwind context to store execution state.
- * @param @coro_ctx fiber context to unwind.
- *
- * Note, this function needs a separate stack frame and therefore
- * MUST NOT be inlined.
+ * Restore target fiber context (if needed) and call
+ * `backtrace_collect_curr_stk` over it.
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: Fixed: updated comment.

File: src/lib/core/backtrace.cc [hunk 20]
```diff
@@ -1,336 +1,172 @@
...
+	: "rax", "rcx", "rdx", "rsi", "rdi", "r8", "r9", "r10", "r11", "xmm0",
+	  "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7", "xmm8",
+	  "xmm9", "xmm10", "xmm11", "xmm12", "xmm13", "xmm14", "xmm15",
+#ifdef __AVX512F__
+	  "xmm16", "xmm17", "xmm18", "xmm19", "xmm20", "xmm21", "xmm22",
+	  "xmm23", "xmm24", "xmm25", "xmm26", "xmm27", "xmm28", "xmm29",
+	  "xmm30", "xmm31", "k0", "k1", "k2", "k3", "k4", "k5", "k6", "k7",
+#endif /* __AVX512F__ */
+	  "mm0", "mm1", "mm2", "mm3", "mm4", "mm5", "mm6", "mm7", "st",
+	  "st(1)", "st(2)", "st(3)", "st(4)", "st(5)", "st(6)", "st(7)");
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc:177]: Here I make this inline assembly ABI compatible: please check this [out](https://stackoverflow.com/a/37503773) for details.

Same case:
https://github.com/tarantool/tarantool/blob/bb3ed32166688be0b1410a2971bc8380a47be74c/third_party/coro/coro.c#L128-L137

I believe this is called "while we are at it": it's not suppose to change any existing behavior — only make this code safer. I can pick it out into a separate commit, if you insist.

File: src/lua/backtrace.h [hunk 21]
```diff
@@ -0,0 +1,110 @@
...
+struct lua_State;
+
+/*
+ * Callback for processing Lua frames.
+ *
+ * Returns status:
+ * 0 - continue processing.
+ * -1 - stop processing
+ */
+typedef int (lua_frame_cb)(const struct lua_frame *,
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lua/backtrace.h]: I didn't even know myself.. It was actually a typo.

Fixed: changed to conventional style.

Please review handling of typedefs in _checkpatch_.

File: src/lib/core/backtrace.h [hunk 22]
```diff
@@ -1,64 +1,118 @@
...
-backtrace_proc_cache_clear(void);
+core_backtrace_foreach(const struct core_backtrace *bt, int begin, int end,
+		       core_resolved_frame_cb core_resolved_frame_cb,
+		       void *ctx);
 
+/*
+ * Dump collected frames to `buf`.
+ */
+void
+core_backtrace_dump_frames(const struct core_backtrace *bt, char *buf,
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h:102]: I would stick to this naming convention.

The reason is we came up with two related components: _Core_ backtrace and _Lua_ backtrace — with the relation that _Lua_ backtrace extends _Core_ backtrace functionality.

File: src/lua/backtrace.h (hunk 16 above)
Comment (CuriousGeorgiy) [reply src/lua/backtrace.h:58]: Fixed: 
* redesigned `struct lua_frame`: now it is union plus a enum for reflection — I guess its the best way to express the derived relationship between it and `struct core_frame`;
* fixed up refactoring commit (it contained a line from the next commit).

Now your script shows the same results.

File: test/app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua (hunk 17 above)
Comment (CuriousGeorgiy) [reply test/app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua:46]: Check out this diff:
https://github.com/tarantool/tarantool/pull/6927/files#diff-0724515e6d62d9c2b0fdf3185945a73b24d5fe41ec8941b91e95b5f918635b0aL594-L596.

This test doesn't expect the backtrace to be printed to `STDOUT`.

File: changelogs/unreleased/fiber-parent-backtrace.md (hunk 18 above)
Comment (CuriousGeorgiy) [reply changelogs/unreleased/fiber-parent-backtrace.md]: Fixed: 
* changed the changelog tense to _Past Simple_;
* improved the changelog to emphasize the parent backtrace collection feature;
* doc bot request now consists of code supplied with comments.

If the doc bot request still doesn't satisfy you, I would be grateful if you provided  a relevant example.

File: src/lib/core/backtrace.cc [hunk 23]
```diff
@@ -375,97 +211,144 @@ __asm__ volatile(
...
-	} else {
-		/*
-		 * Execution context is stored in the coro_ctx
-		 * so use special context-switching handler to
-		 * capture an unwind context.
-		 */
-		coro_unwcontext(&unw_ctx_bt, coro_ctx);
+	assert(offset != nullptr);
+	assert(demangle_buf != nullptr);
+	assert(demangle_buf_len != nullptr);
```
Comment (locker) [inline src/lib/core/backtrace.cc:250]: I wouldn't use `nullptr`, as well as lambdas, auto keyword, aggregate initialization, and other C++-specific syntactic sugaring, because it doesn't simplify the code or make it easier to read, but only makes it incompatible with C, which is still the main language in Tarantool. In general, IMO it looks ugly when the code is written conceptually in C (i.e. with structs + functions), but uses some features from C++ for no real reason. AFAICS the only reason why `backtrace.cc` is a C++ file is the need to use `abi::__cxa_demangle`. I'd add a C wrapper around this function and convert `backtrace.cc` to C.

File: src/lib/core/backtrace.h [hunk 24]
```diff
@@ -1,64 +1,106 @@
...
+			      int skip_frames /* = 2 by default. */);
+
+/*
+ * Process Core frame.
+ *
+ * An additional buffer is needed for demangling C++ names, see `output_buf`
+ * and `length` parameters of `abi::__cxa_demangle`: https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-4.3/a01696.html.
+ *
+ * The caller is responsible for freeing the pointer stored in `demangle_buf`.
+ * `demangle_buf` and `demangle_buf_len` can be reused for multiple calls.
```
Comment (locker) [inline src/lib/core/backtrace.h:77]: Do we really need to pass this buffer around? Can't we make it a static per-thread variable defined in `backtrace.cc` to simplify the function API?

File: src/lua/backtrace.h [hunk 25]
```diff
@@ -0,0 +1,113 @@
...
+ */
+void
+lua_backtrace_init(void);
+#endif /* __APPLE__ */
+
+/*
+ * Collect call stack of `fiber` (both C/C++ and Lua frames) to `bt`.
+ */
+void
+lua_backtrace_collect_frames(struct lua_backtrace *lua_bt, struct fiber *fiber,
```
Comment (locker) [inline src/lua/backtrace.h:86]: Using the `lua_` prefix might not be a good idea, because this prefix is used by the Lua library. This may result in name conflicts in future. May be better call `frame_lua`, `backtrace_lua`, etc.

File: src/lua/backtrace.h [hunk 26]
```diff
@@ -0,0 +1,113 @@
...
+			     int skip_frames /* = 3 by default. */);
+
+/*
+ * Process collected Lua frames.
+ */
+void
+lua_backtrace_foreach(const struct lua_backtrace *lua_bt,
+		      core_frame_cb core_frame_cb,
+		      lua_frame_cb lua_frame_cb,
```
Comment (locker) [inline src/lua/backtrace.h:101]: Why two callbacks? Can't you process both Lua and C frames in the same callback by passing `struct lua_frame` as an argument?

**Review by locker — CHANGES_REQUESTED** [review]

File: test/app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua (hunk 17 above)
Comment (locker) [reply test/app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua:46]: I don't understand. This patch is supposed to just refactor the code so it should have no visible user changes. In particular, all tests should continue to work without any modifications.

File: src/lib/core/backtrace.h (hunk 22 above)
[the remark this answers is not in the document]
Comment (locker) [reply src/lib/core/backtrace.h:101]: IMO it's clear that `backtrace` is a core/base backtrace implementation, even without the `core_` prefix. There's no need to lengthen the name.

From my experience, they usually don't add "Base" or "Core" prefix to a base class name. Example: In Python, class [UserWarning](https://docs.python.org/3/library/exceptions.html#UserWarning) extends class [Warning](https://docs.python.org/3/library/exceptions.html#Warning). The latter is still called "Warning", not "CoreWarning" or "BaseWarning". In our code, we follow the same convention AFAICS.

File: src/lua/backtrace.h (hunk 26 above)
Comment (CuriousGeorgiy) [reply src/lua/backtrace.h]: Because I want to reuse `backtrace_process_frame`.

File: src/lua/backtrace.h (hunk 25 above)
Comment (CuriousGeorgiy) [reply src/lua/backtrace.h]: Fixed: changed all prefixes to `backtrace_lua_`.

File: src/lib/core/backtrace.cc (hunk 23 above)
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: Fixed: 
* wrapped `abi::__cxa_demangle` into `cxx_abi.{cc, h}`
* changed `backtrace.cc` to `backtrace.c`

File: src/lib/core/backtrace.h (hunk 24 above)
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Fixed:
* see response above about `abi::__cxa_demangle`;
* encapsulated `demangle_buf` and `demangle_buf_len` into `thread_local` variables in `cxx_abi.cc`.

File: src/lib/core/backtrace.cc [hunk 27]
```diff
@@ -1,336 +1,171 @@
...
+	assert(fiber != nullptr);
+
+	if (fiber == fiber()) {
+		collect_current_stack(bt, nullptr);
+		goto skip_frames;
+	}
+	if ((fiber->flags & FIBER_IS_CANCELLABLE) == 0) {
+		/*
+		 * Fiber stacks can't be traced for non-cancellable fibers
+		 * due to the limited capabilities of libcoro in CORO_ASM mode.
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: I beg your pardon: this came from Egor's original patch and I didn't really pay attention to it — turned out their was a problem with the `on_shutdown` _fiber_, which never gets scheduled until `tarantool_exit`.

Fixed: changed condition to `fiber->caller == NULL`.

File: src/lua/backtrace.h (hunk 26 above)
Comment (locker) [reply src/lua/backtrace.h]: I don't think it justifies complication of the final API. For me, as an API user, it's easier to pass one callback function rather than two. IMO better make `resolve_frame()` public.

Comment (CuriousGeorgiy) [reply src/lua/backtrace.h]: But you would still have to process frames differently, depending on their type.

File: src/lib/core/backtrace.cc [hunk 28]
```diff
@@ -1,336 +1,171 @@
...
+		append_frame(bt, (void *)ip);
+		rc = unw_step(&unw_cur);
+		if (rc < 0)
+			say_error("unwinding error: unw_step failed with "
+				  "status: %d", rc);
+		if (rc == 0) {
+			break;
+		}
+	}
+#endif /* __APPLE__ */
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.cc]: A thousand apologies: fixed this and personally ensured every commit builds independently.

File: test/app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua (hunk 17 above)
Comment (CuriousGeorgiy) [reply test/app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua]: Fixed: the backtrace in `tarantool_panic_handler` is printed to STDERR, as it was originally — this test works again.

File: src/lua/backtrace.h (hunk 26 above)
Comment (locker) [reply src/lua/backtrace.h]: Yes, but IMO it's eaiser to add a switch-case than define a new function. Besides, you already pass the frame to both of the callbacks so passing some extra information extracted from the frame looks confusing.

File: src/lib/core/backtrace.h (hunk 22 above)
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Fixed: removed `core_` prefixes.

File: src/lua/backtrace.h (hunk 26 above)
Comment (CuriousGeorgiy) [reply src/lua/backtrace.h]: Fixed: removed all _foreach_ and _callback_ abstractions.

File: src/lua/backtrace.h [hunk 29]
```diff
@@ -0,0 +1,87 @@
...
+			char proc_name[BACKTRACE_LUA_PROC_NAME_LEN_MAX];
+			/* Lua source file name. */
+			char src_name[BACKTRACE_LUA_SRC_NAME_LEN_MAX];
+			/* Line number inside Lua function. */
+			int line_no;
+		};
+	};
+	enum backtrace_lua_frame_type {
+		BACKTRACE_FRAME,
+		BACKTRACE_LUA_FRAME,
```
Comment (locker) [inline src/lua/backtrace.h:47]: I suggest reworking this structure a bit to make the correspondence between types and data clearer:

```C
struct backtrace_lua_frame {
    union {
        struct backtrace_frame c;
        struct { ... } lua;
    };
    enum backtrace_lua_frame_type {
        BACKTRACE_LUA_FRAME_C,
        BACKTRACE_LUA_FRAME_LUA,
    };
};
```

File: src/lua/init.c [hunk 30]
```diff
@@ -592,7 +594,11 @@ static int
 tarantool_panic_handler(lua_State *L) {
 	const char *problem = lua_tostring(L, -1);
 #ifdef ENABLE_BACKTRACE
-	print_backtrace();
+	struct backtrace bt;
+	backtrace_collect_frames(&bt, fiber(), 2);
+	char *bt_buf = tt_static_buf();
```
Comment (locker) [inline src/lua/init.c:599]: `tt_static_buf` is fairly small (1024 bytes) - the backtrace may not fit. The old version used `SMALL_STATIC_SIZE` (12 Kbytes), which should be enough. However, IMO ideally the function should print to stderr directly, without a temporary buffer.

File: src/trivia/config.h.cmake [hunk 31]
```diff
@@ -61,6 +61,13 @@
  * showing fiber call stack.
  */
 #cmakedefine ENABLE_BACKTRACE 1
+
+/*
+ * Defined if configured with ENABLE_BACKTRACE on AARCH64 and
+ * '-mbranch-protection' compile flag is passed.
+ */
+#cmakedefine ENABLED_BRANCH_PROTECTION
```
Comment (locker) [inline src/trivia/config.h.cmake:69]: I don't like that we have `ENABLE_` and `ENABLED_` prefixes - this is confusing. Maybe, name it `HAVE_BRANCH_PROTECTION`?

**Review by locker — CHANGES_REQUESTED** [review]

File: src/trivia/config.h.cmake (hunk 31 above)
Comment (CuriousGeorgiy) [reply src/trivia/config.h.cmake:69]: IMO, the `HAVE_` prefix is used for marking availability of compiler options.

Whereas here we have to deal with the case that a specific compiler option _was passed_, i.e., a specific compiler feature is enabled.

Comment (locker) [reply src/trivia/config.h.cmake:69]: Who sets this option? I don't see any strings matching `branch-protection` in the source.

Comment (locker) [reply src/trivia/config.h.cmake:69]: Discussed offline:
- The flag can be set by some distributions (e.g. Fedora).
- `ENABLED_` name is fine.

File: src/lua/init.c (hunk 30 above)
Comment (CuriousGeorgiy) [reply src/lua/init.c]: Fixed: added `backtrace_print` for this case.

File: src/lua/backtrace.h (hunk 29 above)
Comment (CuriousGeorgiy) [reply src/lua/backtrace.h]: _Polymorphism_ looks quite ugly in C anyways...

Fixed: made the union members and enum elements conform to the corresponding language types.

File: src/lua/backtrace.c [hunk 32]
```diff
@@ -0,0 +1,181 @@
...
+			BACKTRACE_LUA_PROC_NAME_LEN_MAX);
+		strlcpy(frame->src_name, src_name,
+			BACKTRACE_LUA_PROC_NAME_LEN_MAX);
+		frame->line_no = line_no;
+	}
+}
+
+/*
+ * Collect Lua frames from fiber's Lua stack.
+ */
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lua/backtrace.c:87]: Fixed: elaborated about the function flow in the comment and described the `lua_stack_depth` parameter's purpose.

File: src/lua/backtrace.c [hunk 33]
```diff
@@ -0,0 +1,181 @@
...
+static void
+collect_lua_frames(struct backtrace_lua *bt, struct fiber *fiber,
+		   int *lua_stack_depth)
+{
+	struct lua_State *L = fiber->storage.lua.stack;
+	if (L == NULL) {
+		append_lua_frame(bt, "<Lua stack>",
+				 "<Lua stack>", -1);
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lua/backtrace.c]: Fair enough: changed to no-op if the Lua stack is not present.

File: src/lua/backtrace.c [hunk 34]
```diff
@@ -0,0 +1,181 @@
...
+void
+lj_BC_FUNCC(void);
+
+static void *lua_stack_entry_start_ip = (void *)lj_BC_FUNCC;
+/* See lj_vm.s */
+static void *lua_stack_entry_end_ip = (char *)lj_BC_FUNCC + 72;
+
+static const char *const lua_frame_str_fmt = "#%-2d %s in %s:%d";
+
+#ifndef __APPLE__
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lua/backtrace.c]: Fixed: put the conditional compilation inside the function's body.

File: src/lib/core/fiber.c [hunk 35]
```diff
@@ -1600,6 +1606,7 @@ void *cord_thread_func(void *p)
 	                                            CORD_ON_EXIT_WONT_RUN);
 	if (!changed)
 		handler->callback(handler->argument);
+	pthread_cleanup_pop(1);
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/fiber.c]: Fixed: added a `DemangleBuf` RAII wrapper for the demangling buffer.

File: src/lib/core/backtrace.h [hunk 36]
```diff
@@ -1,64 +1,73 @@
...
-backtrace_foreach(backtrace_cb cb, coro_context *coro_ctx, void *cb_ctx);
+/*
+ * Collect call stack of `fiber` (only C/C++ frames) to `bt`.
+ *
+ * Nota bene: requires its own stack frame — hence, NOINLINE.
+ */
+NOINLINE void
+backtrace_collect_frames(struct backtrace *bt,
+			 const struct fiber *fiber,
+			 int skip_frames /* = 2 by default. */);
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Fixed: removed the default value comments and described the `skip_frame` parameter usage in the comment.

File: src/lib/core/backtrace.h [hunk 37]
```diff
@@ -1,64 +1,73 @@
...
+ * Resolve function name and offset based on `ip`.
+ */
+const char *
+backtrace_resolve_frame(unw_word_t ip, unw_word_t *offset);
 
+/*
+ * Dump collected frames to `buf`.
+ */
+void
+backtrace_dump_frames(const struct backtrace *bt, char *buf, size_t buf_len);
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Wow, I didn't know about this, looks quite neat!

Fixed: make `backtrace_dump` `SNPRINT` compatible and reused `SNPRINT in the implementation.

[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Fixed: dropped the `_frames` suffix from function names.

File: src/lib/core/backtrace.h [hunk 38]
```diff
@@ -1,64 +1,73 @@
...
+			 const struct fiber *fiber,
+			 int skip_frames /* = 2 by default. */);
 
-void
-backtrace_proc_cache_clear(void);
+/*
+ * Resolve function name and offset based on `ip`.
+ */
+const char *
+backtrace_resolve_frame(unw_word_t ip, unw_word_t *offset);
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h]: Fixed:
* changed function signature to take `bacctrace_frame` as first parameter;
* renamed to `backtrace_frame_resolve`,

File: src/lib/core/backtrace.c [hunk 39]
```diff
@@ -0,0 +1,289 @@
...
+#ifdef __APPLE__
+#include <dlfcn.h>
+#endif /* __APPLE__ */
+
+#include "cxx_abi.h"
+
+#define C_FRAME_STR_FMT "#%-2d %p in %s+%zu"
+#define CRLF "\n"
+
+const char *const backtrace_frame_str_fmt = C_FRAME_STR_FMT;
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.c]: Didn't think about the fact that the format needs to be exposed anyways.

Fixed: move the macro to the header file.

File: src/lib/core/backtrace.c [hunk 40]
```diff
@@ -0,0 +1,289 @@
...
+	"\tldp d14, d15, [x0, #16 * 9]\n"
+	"\tadd sp, x0, #8 * 20\n"
+	: "=m" (*bt)
+	: "m" (bt), "r" (&fiber->ctx), "S" (collect_current_stack)
+	: "x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10",
+	  "x11", "x12", "x13", "x14", "x15", "x16", "x17", "x18",
+	  "s0", "s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10",
+	  "s11", "s12", "s13", "s14", "s15", "s16", "s17", "s18", "s19", "s20",
+	  "s21", "s22", "s23", "s24", "s25", "s26", "s27", "s28", "s29", "s30",
+	  "s31", "d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7");
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.c:238]: Unfortunately, `git mv` works only for relatively small diffs.

Fixed: added a separate commit for refactoring the C++ ABI and renaming the `backtrace` component file

File: src/lib/core/cxx_abi.h [hunk 41]
```diff
@@ -0,0 +1,33 @@
...
+
+/*
+ * Free resources used by C++ ABI.
+ */
+void
+cxx_abi_cleanup(void *unused);
+#ifdef __cplusplus
+} /* extern "C" */
+#endif /* __cplusplus */
+#endif /* ENABLE_BACKTRACE */
```
Comment (locker) [inline src/lib/core/cxx_abi.h:33]: This won't compile if `ENABLE_BACKTRACE` is unset because of unterminated `{`.

File: src/lib/core/cxx_abi.h [hunk 42]
```diff
@@ -0,0 +1,33 @@
...
+ * the caller is responsible for making a copy of it.
+ */
+const char *
+cxx_abi_demangle(const char *mangled_name);
+
+/*
+ * Free resources used by C++ ABI.
+ */
+void
+cxx_abi_cleanup(void *unused);
```
Comment (locker) [inline src/lib/core/cxx_abi.h:29]: The function is unused.

File: src/lib/core/backtrace.h [hunk 43]
```diff
@@ -1,64 +1,86 @@
...
 
+struct fiber;
 
-void
-backtrace_foreach(backtrace_cb cb, coro_context *coro_ctx, void *cb_ctx);
+/*
+ * Collect call stack of `fiber` (only C/C++ frames) to `bt`.
+ *
+ * `skip_frames` determines the number of frames skipped, starting from the
+ * frame of `backtrace_collect`. It is expected to have a non-negative value.
```
Comment (locker) [inline src/lib/core/backtrace.h:53]: Please add an example for clarity. Something like this:

```
For example, if skip_frames is 0, then the function will include backtrace_collect
and every calling function into the stack. If it's 1, it will skip backtrace_collect.
```

File: src/lib/core/fiber.c [hunk 44]
```diff
@@ -43,6 +43,10 @@
 #include "trigger.h"
 #include "errinj.h"
 
+#ifdef ENABLE_BACKTRACE
+#include "core/cxx_abi.h"
+#endif /* ENABLE_BACKTRACE */
+
```
Comment (locker) [inline src/lib/core/fiber.c:49]: This include is not needed anymore.

File: src/lua/backtrace.c [hunk 45]
```diff
@@ -0,0 +1,186 @@
...
+	lua_stack_entry_start_ip = (void *)proc_info.start_ip;
+	lua_stack_entry_end_ip = (void *)proc_info.end_ip;
+#endif /* __APPLE__ */
+}
+
+/*
+ * Append frame to backtrace.
+ */
+static void
+append_frame(struct backtrace_lua *bt, struct backtrace_frame *c_frame)
```
Comment (locker) [inline src/lua/backtrace.c:51]: Nit: `append_c_frame` would be a better name, otherwise one might think that `append_lua_frame` calls `append_frame`.

File: src/lua/backtrace.h [hunk 46]
```diff
@@ -0,0 +1,88 @@
...
+
+/*
+ * Push collected Lua backtrace onto Lua stack.
+ */
+void
+backtrace_lua_stack_push(const struct backtrace_lua *bt, struct lua_State *L);
+#ifdef __cplusplus
+} /* extern "C" */
+#endif /* __cplusplus */
+#endif /* ENABLE_BACKTRACE */
```
Comment (locker) [inline src/lua/backtrace.h:94]: Same comment as for `core/backtrace.h` - this code won't compile if `ENABLE_BACKTRACE` is unset.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/lua/backtrace.c (hunk 45 above)
Comment (CuriousGeorgiy) [reply src/lua/backtrace.c]: Agree, sounds reasonable.

Fixed: renamed `append_frame` to distinguish the frame type.

File: src/lib/core/fiber.c (hunk 44 above)
Comment (CuriousGeorgiy) [reply src/lib/core/fiber.c]: Fixed: removed dead include.

File: src/lib/core/backtrace.h (hunk 43 above)
Comment (CuriousGeorgiy) [reply src/lib/core/backtrace.h:53]: Fixed: supplied an example.

File: src/lib/core/cxx_abi.h (hunk 42 above)
Comment (CuriousGeorgiy) [reply src/lib/core/cxx_abi.h]: Fixed: removed dead declaration.

File: src/lib/core/cxx_abi.h (hunk 41 above)
Comment (CuriousGeorgiy) [reply src/lib/core/cxx_abi.h:27]: Fixed: move the `if ENABLE_BACKTRACE` out of the `ifdef __cplusplus_`.

File: src/lua/backtrace.h (hunk 46 above)
Comment (CuriousGeorgiy) [reply src/lua/backtrace.h:94]: Double-checked: builds with -DENABLE_BACKTRACE=OFF.

File: src/lib/core/cxx_abi.h (hunk 41 above)
Comment (CuriousGeorgiy) [reply src/lib/core/cxx_abi.h:27]: Sorry for this nuisance.

File: src/lib/core/cxx_abi.h [hunk 47]
```diff
@@ -21,12 +21,6 @@ extern "C" {
  */
 const char *
 cxx_abi_demangle(const char *mangled_name);
-
-/*
- * Free resources used by C++ ABI.
- */
-void
-cxx_abi_cleanup(void *unused);
```
Comment (locker) [inline src/lib/core/cxx_abi.h]: This should be in the previous patch. Please rebase. Move of `ENABLE_BACKTRACE` too.

File: src/trivia/config.h.cmake (hunk 31 above)
Comment (locker) [inline src/trivia/config.h.cmake:69]: Nit: should be

```
#cmakedefine ENABLED_BRANCH_PROTECTION 1
```

?

**Review by locker — CHANGES_REQUESTED** [review]

File: src/lib/core/cxx_abi.h (hunk 47 above)
Comment (CuriousGeorgiy) [reply src/lib/core/cxx_abi.h]: I beg your pardon, Friday evening...

Fixed: moved these diffs to C++ ABI refactoring patch.

File: src/trivia/config.h.cmake (hunk 31 above)
Comment (CuriousGeorgiy) [reply src/trivia/config.h.cmake:69]: I prefer using `#ifdef`, when possible, rather than `#if`: according to CMake [docs](https://cmake.org/cmake/help/latest/command/configure_file.html) this will be replaced with 
```C
#define ENABLED_BRANCH_PROTECTION
```
or
```C
/* #undef ENABLED_BRANCH_PROTECTION */
```

Comment (CuriousGeorgiy) [reply src/trivia/config.h.cmake:69]: I also decided to change the prefix to `WITH_` — sounds more suitable.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
@CuriousGeorgiy please fix build errors caught by CI.

**Review by alyapunov — APPROVED** [review]
Great
