### PR TITLE
lua_cjson: fix encode() escaping slash

### LINKED ISSUE #6200: json.encode() escapes '/'
Приветствую, столкнулся с неожиданным экранированием в json модуле.
```
localhost:3501> t = {url = "https://srv:7777"}
---
...
localhost:3501> require('json').encode(t)
---
- '{"url":"https:\/\/srv:7777"}'
...
```

`Json.encode` экранирует `/`, по спеке это не обязательно. [rfc4627]

```
 All Unicode characters may be placed within the
   quotation marks except for the characters that must be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).
```

https://github.com/tarantool/tarantool/blob/4b2016ab3d35b505ea4712998458c2cd553b0271/third_party/lua-cjson/lua_cjson.c#L135

**Ожидаемое поведение:**
```
localhost:3501> t = {url = "https://srv:7777"}
---
...
localhost:3501> require('json').encode(t)
---
- '{"url":"https://srv:7777"}'
...
```

### PR DESCRIPTION
**Pull request by Lord-KA**
For unknown reason in upstream lua_cjson '/' was escaped
while according to the standard [rfc4627] it is unnecessary and is
questionably compatible with other implementations.

It was decided that the change will be introduced using
tarantool.compat (https://github.com/tarantool/tarantool/issues/7000). The patch adds json-escape-forward-slash
option to compat and its logic in lua_cjson and msgpuck.

Requires changes in tarantool.compat [1].
[1]: https://github.com/tarantool/tarantool/pull/7060

Fixes https://github.com/tarantool/tarantool/issues/6200
See also https://github.com/tarantool/tarantool/issues/7000
NO_DOC=[docs on tarantool.wiki](https://github.com/tarantool/tarantool/wiki/compat%3Ajson_escape_forward_slash)

### CODE REVIEW

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua [hunk 1]
```diff
@@ -0,0 +1,10 @@
+local json = require('json')
+local t = require('luatest')
+local g = t.group()
+
+g.test_encode_link = function()
+    t.assert_equals(json.encode({url = "https://srv:7777"}), '{\"url\":\"https://srv:7777\"}')
+    t.assert_equals(json.encode("\ttable[]"), '\"\\ttable[]\"')
+    t.assert_equals(json.encode("\\"), "\"\\\\\"")
+    t.assert_equals(json.encode("/home/user/Code/tarantool"), "\"/home/user/Code/tarantool\"")
```
Comment (Totktonada) [inline test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:9]: 1. I would use double square brackets (`[[blah blah]]`) for expected values to don't bother with escaping and make the text more readable.
2. `\t` (tab symbol) seems not related to the problem. Or I missed something?

File: third_party/lua-cjson/lua_cjson.c [hunk 2]
```diff
@@ -134,7 +134,7 @@ static const char *char2escape[256] = {
     "\\u0018", "\\u0019", "\\u001a", "\\u001b",
     "\\u001c", "\\u001d", "\\u001e", "\\u001f",
     NULL, NULL, "\\\"", NULL, NULL, NULL, NULL, NULL,
-    NULL, NULL, NULL, NULL, NULL, NULL, NULL, "\\/",
+    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
```
Comment (Totktonada) [inline third_party/lua-cjson/lua_cjson.c:137]: I'll leave here a comment, but, to be honest, I have no strict vision, whether/how it should be resolved.

Should we provide an option for that? If so, should we change a default behaviour? Should the option be global, encoder instance specific or both? (Similar questions appear in the upstream — I summarized it briefly in #6200.)

Or we should go on the long way with some more general behaviour control mechanish, like one I described [here](https://github.com/tarantool/tarantool/discussions/6912)?

File: changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md [hunk 3]
```diff
@@ -0,0 +1,3 @@
+## bugfix/lua-cjson
```
Comment (Totktonada) [inline changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md:1]: `bugfix/lua` or `bugfix/lua/json`. Our built-in module is called just `json` from a user's perspective.

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua (hunk 1 above)
Comment (Lord-KA) [reply test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:9]: 1. Got it.
2. The logic behind it was to check if for whatever reason some other escape sequences would stop working, otherwise the possible test cases a very limited.

File: changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md (hunk 3 above)
Comment (Lord-KA) [reply changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md]: Done

File: third_party/lua-cjson/lua_cjson.c (hunk 2 above)
Comment (Lord-KA) [reply third_party/lua-cjson/lua_cjson.c:176]: We decided to use tarantool.compat (#7060), it is now required to merge the patch.

**Comment by Lord-KA** [comment]
CI will fail, until we merge tarantool/msgpuck#20.

**Comment by Totktonada** [comment]
1. No wiki page you linked to. (`NO_DOC=docs on tarantool.wiki` -- they do not.)
2. No brief description (see the original discussion for example).
3. FIXME comments. 'Do not touch' comments (we can't accept write-only code -- the comment inevitably means that you should rewrite the code).
4. Failed tests in CI (I would bump the submodule module to your branch and set `do not merge` label to show that the code actually pass all tests).
5. Commands in `help` calls or sets some globals (or looks so).
6. Examples in commit messages just sets some local variables, they're unclear for a reader, which didn't read your patch.
7. `doc = "https://tarantool.io/"` -- we agreed to use the wiki, no?
8. I don't see anywhere a user guide: how and where should I use the module? Not how to add a new option (audience: tarantool developer, module developer), but how to deal with existing options (audience: application developer).
9. The code does not adhere our style guides ([C](https://www.tarantool.io/en/doc/latest/dev_guide/c_style_guide/), [Lua](https://www.tarantool.io/en/doc/latest/dev_guide/lua_style_guide/)). At least I see comments at the same line as the code and comments longer than 80 symbols.
10. The changelog entries do not adhere our [release notes style](https://www.tarantool.io/en/doc/latest/contributing/release_notes/) guide (at least use imperative mood).

I need all documentation finished to imagine myself an application developer, who uses the module. Otherwise I can't, so I can't give you a feedback on how good the implementation fits the developer expectations.

When you'll write the documentation, keep the following scenarious in the mind:

* A developer, which wants to expilicitly freeze everything on the old behavior to minimize risks of tarantool update in existing application.
* A developer, which wants to set all defaults provided by current tarantool version to a new behavior to start from the best options, but all future options should be set to 'old'. It is for new applications.
* What actions the developer should perform to get suggested configuration update (what new options can be set to 'new'). How to incorporate the suggested updates to the existing applciation?
* How the developer will be notified about options that (s)he should consider to update. (A linter for `tt`? Let's start the [discussion](https://github.com/tarantool/tt/discussions) regarding its behavior at least.)

Regarding the implementation:

* FFI / exported symbols.

  We export extra symbols just to use them with FFI. It seems, it is not necessary. We can set default json encoder option from Lua. We can add Lua/C part to the compat module to reach symbols with hidden visibility.

* Excessive macroprocessor usage.

  I don't see a reason, why don't just set the option for the default json encoder. It'll inherited by all json encoder instance created afterwards, not?

  Even if we need to hold the default option value separately from current default json encoder options, why don't just handle it in the serializer initialization function?

* `print()` in the help command.

  Result of `print()` will not be shown on the terminal if you connected to a remote instance. We should either return the help (it is how `tutorial()` function works) or use `box.session.push()` (it is the last resort).

Wording:

> - old behavior is frozen and its logic is removed

There is no sense to freeze an old behavior. I guess you meant that the new behavior is frozen/hold/enabled and the old one is not supported anymore.

**Comment by Lord-KA** [comment]
1. Wiki page is a work in progress.
2. Will fix soon. 
3. 1. FIXME mark questions that are open, and reviewer input is required. 
    2. Maybe 'do not touch' was a bit excessive, but the use of preprocessor seems to me justified. New json instance is created by `luaL_newserializer()`, that doesn't copy the instance that called it, but creates a brand new one with settings from OPTIONS table. The OPTIONS table is defined in src, but in previous version we had no knowledge of where exactly in the table the desired option is placed. Thus there were several ways to solve the problem: 
        1) by using linear search that compares an option with the desired
        2) by setting forced position to the desired option and writing an angry 'do not change the order' comment
        3) by using preprocessor to create a union, so that options can be accessed by position as usual, or as a field
    3. As I've mentioned in 3.2, `luaL_newserializer()` doesn't copy serializer, so to enforce new behavior we have to change the existing serializer's (available by `require 'json'`) cfg and change the contents of OPTIONS so all new serializers follow the same new behavior until configured otherwise.

**Comment by Lord-KA** [comment]
> checkpatch failed: https://github.com/tarantool/tarantool/actions/runs/3054424665/jobs/4926326306

It's a false positive, I filed an [issue](https://github.com/tarantool/checkpatch/issues/24).

**Comment by Lord-KA** [comment]
Created alternative version, that doesn't trigger checkpatch false positive.

File: test/box-luatest/gh_7000_compat_module_test.lua [hunk 4]
```diff
@@ -0,0 +1,295 @@
+local t = require('luatest')
+local g = t.group()
+local compat = require('compat')
+
+local NEW = 'new'
+local OLD = 'old'
+local DEFAULT = 'default'
+
+g.before_all(function() compat.reset() end)
+g.after_all( function() compat.reset() end)
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply test/box-luatest/gh_7000_compat_module_test.lua:10]: It just looks better. I will remove it if you insist.

File: src/lua/compat.c [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+ *
+ * Copyright 2010-2022, Tarantool AUTHORS, please see AUTHORS file.
+ */
+
+#include <lua/compat.h>
+
+static const char escaped_slash[] = "\\/";
+
+int
+msgpuck_esc_slash_toggle(struct lua_State *L)
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:12]: The one and only purpose of `compat.{c,h}` is to contain LuaC functions for the options. Lua postaction functions are stored in `compat.lua`, so one can expect that LuaC postaction functions are stored in LuaC part of compat. 

> Or put function msgpuck_esc_slash_toggle to source code of msgpuck like you did with json_esc_slash_toggle.

It would require a patch to msgpuck tarantool fork, and would unnecessary complicate the patchset.

File: src/lua/compat.lua [hunk 6]
```diff
@@ -0,0 +1,315 @@
...
+        obsolete = false,
+        brief = JSON_ESCAPE_BRIEF,
+    },
+}
+
+-- Contains postaction functions for each non obsolete option from `options`.
+local postaction = {
+    json_escape_forward_slash = function(value)
+        value = not value
+        require('json').cfg{encode_esc_slash = value}
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.lua:35]: This will affect the global json instance that is returned with `require 'json'`. The function in `serializer.c` affects only new serializers that are created with `json.new()` after option is selected.

File: src/lua/compat.h [hunk 7]
```diff
@@ -0,0 +1,36 @@
+/*
+ * SPDX-License-Identifier: BSD-2-Clause
+ *
+ * Copyright 2010-2022, Tarantool AUTHORS, please see AUTHORS file.
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.h:4]: `./src/lua/backtrace.h` contains the exact comment.

File: test/box-luatest/gh_7000_compat_module_test.lua [hunk 8]
```diff
@@ -0,0 +1,295 @@
...
+        default = 'new',
+        brief = "option_1",
+        action = function()
+            option_1_called = true
+        end
+    },
+    option_2_policy = {
+        name = 'option_2',
+        default = 'old',
+        brief = "option_2",
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply test/box-luatest/gh_7000_compat_module_test.lua:29]: Fixed.

File: test/box-luatest/gh_7000_compat_module_test.lua [hunk 9]
```diff
@@ -0,0 +1,295 @@
...
+        action = function()
+            option_2_called = true
+        end
+  },
+}
+
+local obsolete_policy = {
+    name = 'obsolete_option',
+    default = 'new',
+    brief = "obsolete_option",
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply test/box-luatest/gh_7000_compat_module_test.lua:40]: Fixed

File: test/box-luatest/gh_7000_compat_module_test.lua [hunk 10]
```diff
@@ -0,0 +1,295 @@
...
+    }
+
+    t.assert_error(compat.add_option, bad_policy)
+
+    bad_policy = {                              -- Non obsolete option with bad action.
+        name ='bad_option_2',
+        default = false,
+        obsolete = false,
+        brief = 'bad_option',
+        action = "not a function"
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply test/box-luatest/gh_7000_compat_module_test.lua:73]: Fixed.

File: src/lua/compat.lua [hunk 11]
```diff
@@ -0,0 +1,315 @@
...
+
+local NEW = true
+local OLD = false
+
+local internals = require('compat_internals')
+
+local options_format = {
+    brief    = 'string',
+    obsolete = 'boolean',
+}
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.lua:12]: You are right. No reason to remove `default = 'string'`.

File: src/lua/compat.lua [hunk 12]
```diff
@@ -0,0 +1,315 @@
...
+
+local JSON_ESCAPE_BRIEF = [[
+Whether to escape the forward slash symbol '/' using a backslash in a json.encode()
+result. The old and the new behaviour produce a result, which is compatible
+with the JSON specification. However most of other JSON encoders don't escape
+the forward slash, so we consider the new behaviour as more safe one.
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.lua:18]: Fixed.

File: src/lua/compat.lua [hunk 13]
```diff
@@ -0,0 +1,315 @@
...
+
+-- Array with option names in order of addition.
+local options_order = { }
+
+-- Contains dynamic values: current state of an option and is it selected.
+local cfg = { }
+
+local help = [[
+
+This is Tarantool compatibility module.
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.lua:49]: Updated help.

File: src/lua/compat.lua [hunk 14]
```diff
@@ -0,0 +1,315 @@
...
+local internals = require('compat_internals')
+
+local options_format = {
+    brief    = 'string',
+    obsolete = 'boolean',
+}
+
+local JSON_ESCAPE_BRIEF = [[
+Whether to escape the forward slash symbol '/' using a backslash in a json.encode()
+result. The old and the new behaviour produce a result, which is compatible
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.lua:17]: Fixed.

File: src/lua/serializer.c [hunk 15]
```diff
@@ -76,12 +76,30 @@ static struct {
...
 	OPTION(LUA_TNUMBER,  decode_max_depth, 128),
 	{ NULL, 0, 0, 0},
 };
 
+/** toggler for json.encode behavior change with tarantool.compat (gh-7000) */
+int
+json_esc_slash_toggle(struct lua_State *L)
+{
+	int top = lua_gettop(L);
+	assert(lua_type(L, top) == LUA_TBOOLEAN);
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/serializer.c:91]: `luaL_error()` as well as `assert()` don't work when no arguments are passed to the function (I think, it somehow breaks the stack). As it is a very much internal error, I leave `assert()`, but thanks for the hint about `lua_isboolean()`.

File: src/lua/compat.lua [hunk 16]
```diff
@@ -0,0 +1,315 @@
...
+with the JSON specification. However most of other JSON encoders don't escape
+the forward slash, so we consider the new behaviour as more safe one.
+https://github.com/tarantool/tarantool/wiki/compat%3Ajson_escape_forward_slash
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.lua:20]: Uploaded page to tarantool.wiki.

File: changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md [hunk 17]
```diff
@@ -0,0 +1,4 @@
+## bugfix/lua/json
+
+* Added `json_escape_forward_slash` option to tarantool.compat and implemented
+  corresponding changes in lua-cjson and msgpuck (gh-6200).
```
Comment (Totktonada) [inline changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md:4]: Our json built-in Lua module is based on lua-cjson, but was reworked. Anyway, it is an implementation detail. How about calling it '`json` built-in module' or '`json` Lua module' or just '`json`' in a text for a user?

File: changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md [hunk 18]
```diff
@@ -0,0 +1,4 @@
+## bugfix/lua/json
```
Comment (Totktonada) [inline changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md:1]: In the PR description:

> NO_DOC=[docs on tarantool.wiki](https://github.com/Totktonada/test-wiki-subpages/wiki/compat%3Ajson_escape_forward_slash)

The link should be https://github.com/tarantool/tarantool/wiki/compat%3Ajson_escape_forward_slash, I guess.

File: src/lua/compat.c [hunk 19]
```diff
@@ -6,6 +6,24 @@
...
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool val = lua_toboolean(L, -1);
+	lua_pop(L, 1);
+	lua_pushnumber(L, 0);
+
+	if (val)
+		mp_char2escape['/'] = escaped_slash;
```
Comment (Totktonada) [inline src/lua/compat.c:20]: Just `mp_char2escape['/'] = "\\/";` should be enough.

File: src/lua/compat.c [hunk 20]
```diff
@@ -6,6 +6,24 @@
...
 
+static const char escaped_slash[] = "\\/";
+
+int
+msgpuck_esc_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool val = lua_toboolean(L, -1);
+	lua_pop(L, 1);
+	lua_pushnumber(L, 0);
```
Comment (Totktonada) [inline src/lua/compat.c:17]: Why we need to push zero?

File: src/lua/serializer.c [hunk 21]
```diff
@@ -76,12 +76,32 @@ static struct {
...
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool value = lua_toboolean(L, -1);
+	lua_pop(L, 1);
+
+	for (int i = 0; OPTIONS[i].name != NULL; i++) {
+		if (!strcmp(OPTIONS[i].name, "encode_esc_slash")) {
+			OPTIONS[i].defvalue = value;
+			lua_pushnumber(L, 0);
+			return 1;
```
Comment (Totktonada) [inline src/lua/serializer.c:98]: Why we need to push zero?

File: src/lua/serializer.c [hunk 22]
```diff
@@ -76,12 +76,32 @@ static struct {
...
 	OPTION(LUA_TBOOLEAN, encode_invalid_as_nil, 0),
 	OPTION(LUA_TBOOLEAN, encode_error_as_ext, 1),
+	OPTION(LUA_TBOOLEAN, encode_esc_slash, 0),
 	OPTION(LUA_TBOOLEAN, decode_invalid_numbers, 1),
 	OPTION(LUA_TBOOLEAN, decode_save_metatables, 1),
 	OPTION(LUA_TNUMBER,  decode_max_depth, 128),
 	{ NULL, 0, 0, 0},
 };
 
+/** toggler for json.encode behavior change with tarantool.compat (gh-7000) */
```
Comment (Totktonada) [inline src/lua/serializer.c:86]: Nit: We start a comment from a capital letter and end it with a period. Please, adjust according to the style over the whole patch.

File: src/lua/serializer.c [hunk 23]
```diff
@@ -76,12 +76,32 @@ static struct {
...
+int
+json_esc_slash_toggle(struct lua_State *L)
```
Comment (Totktonada) [inline src/lua/serializer.c:88]: I doubt that 'toogle' is a good term here: a toogle would allow to switch from 'off' to 'on' and vice verse. Here we have a usual setter.

Following our usual naming conventions we should name it, for example, `lbox_serializer_encode_forward_slash_default()`. `lbox_` is here, because it is supposed to be called from the Lua land. `serializer` is here instead of `json`, because, in fact, the function changes a default for a serializer option. Sure, this option affects only json encoder, but the list of options is owned by the serializer module.

However this name looks too wordy. I would rather implement the same for any option: `lbox_serializer_default_cfg()`. I remember that there was something of this kind in a previous version of the patch and I was against a complicated macro usage. I think that it is possible to generalize the implementation and don't miss readability.

Next, we usually expose `lbox_foo_bar` from module `foo` as field `bar`. I don't see a reason to go in another way here. I would add `internal.serializer.default_cfg()`, which accepts a table of option names as keys and its default values as values.

What do you think?

File: src/lua/compat.lua [hunk 24]
```diff
@@ -4,19 +4,40 @@
...
     brief    = 'string',
     obsolete = 'boolean',
 }
 
+local JSON_ESCAPE_BRIEF = [[
+Whether to escape the forward slash symbol '/' using a backslash in a json.encode()
+result. The old and the new behavior produce a result, which is compatible
+with the JSON specification. However most of other JSON encoders don't escape
+the forward slash, so the new behavior is considered more safe.
+https://github.com/tarantool/tarantool/wiki/compat%3Ajson_escape_forward_slash
```
Comment (Totktonada) [inline src/lua/compat.lua:20]: Nit: I would place the URL in its own paragraph. IOW, I would add an empty line before it.

File: src/lua/compat.lua [hunk 25]
```diff
@@ -4,19 +4,40 @@
...
+        obsolete = false,
+        brief = JSON_ESCAPE_BRIEF,
+    },
+}
 
 -- Contains postaction functions for each non obsolete option from `options`.
-local postaction = { }
+local postaction = {
+    json_escape_forward_slash = function(value)
+        value = not value
```
Comment (Totktonada) [inline src/lua/compat.lua:35]: Isn't the value either `'old'` or `'new'`?

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua [hunk 26]
```diff
@@ -0,0 +1,104 @@
...
+end
+
+-- log.info in json format mode uses internal encoder that takes msgpuck
+-- char2escape table, while mp_char2escape is changed by compat.
+g.test_mp_encode = function()
+    misc.skip_if_not_debug()
+    t.skip_if(jit.os == 'OSX', 'popen is broken on OSX.')
+    -- Start external tarantool session.
+    local TARANTOOL_PATH = arg[-1]
+    local cmd = 'ERRINJ_STDIN_ISATTY=1 ' .. TARANTOOL_PATH .. ' -i 2>&1'
```
Comment (Totktonada) [inline test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:58]: This error injection was removed in 16d6e9d2e272e3c7fba807ef64a8aac791e2c427.

BTW, you can find `interactive_tarantool.lua` from PR #7170 convenient.

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua [hunk 27]
```diff
@@ -0,0 +1,104 @@
...
+
+    -- Restore options defaults.
+    compat.json_escape_forward_slash = 'default'
+end
+
+-- log.info in json format mode uses internal encoder that takes msgpuck
+-- char2escape table, while mp_char2escape is changed by compat.
+g.test_mp_encode = function()
+    misc.skip_if_not_debug()
+    t.skip_if(jit.os == 'OSX', 'popen is broken on OSX.')
```
Comment (Totktonada) [inline test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:55]: Both skips are not actual anymore.

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua [hunk 28]
```diff
@@ -0,0 +1,104 @@
...
+    -- Restore options defaults.
+    compat.json_escape_forward_slash = 'default'
+end
+
+g.test_json_new_encode = function()
+    compat.json_escape_forward_slash = 'old'
+    -- Test that '/' is escaped with 'old' setting.
+    t.assert_equals(json.encode('/'), [["\/"]])
+
+    -- Create new serializer and check that it has correct defaults and doesn't change behavior.
```
Comment (Totktonada) [inline test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:36]: Nit: A comment is over 80 symbols long.

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua [hunk 29]
```diff
@@ -0,0 +1,104 @@
...
+local jit = require('jit')
+local json = require('json')
+local popen = require('popen')
+local clock = require('clock')
+local t = require('luatest')
+local g = t.group()
+
+g.test_json_encode = function()
+    compat.json_escape_forward_slash = 'old'
+    -- Test that '/' is escaped with 'old' setting.
```
Comment (Totktonada) [inline test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:12]: Shouldn't we also check the default behavior here?

File: src/lua/compat.h [hunk 30]
```diff
@@ -14,7 +14,17 @@ extern "C" {
...
+int
+msgpuck_esc_slash_toggle(struct lua_State *L);
+
+/* toggler for json.encode behavior change */
+int
+json_esc_slash_toggle(struct lua_State *L);
+
 static const struct luaL_Reg compat_internals[] = {
+	{"msgpuck_esc_slash_toggle", msgpuck_esc_slash_toggle},
+	{"json_esc_slash_toggle", json_esc_slash_toggle},
```
Comment (Totktonada) [inline src/lua/compat.h:27]: It is defined in the serializer module, so it is better to expose it from the serializer module. See the review comment for the definition of the function regarding its name. Don't forget to adjust the comment to tarantool's style.

File: src/lua/compat.h [hunk 31]
```diff
@@ -14,7 +14,17 @@ extern "C" {
 
 struct lua_State;
 
+/* toggler of mp_char2escape */
+int
+msgpuck_esc_slash_toggle(struct lua_State *L);
```
Comment (Totktonada) [inline src/lua/compat.h:19]: Here I also don't like 'toogle' name. Something like `lbox_cfg_msgpuck` would be better, IMHO. Maybe it also worth to expose this function (as internal) from `msgpack` built-in module.

File: changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md (hunk 18 above)
Comment (Lord-KA) [reply changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md:1]: Fixed.

File: src/lua/compat.c (hunk 19 above)
Comment (Lord-KA) [reply src/lua/compat.c:20]: Fixed.

File: src/lua/compat.lua (hunk 25 above)
Comment (Lord-KA) [reply src/lua/compat.lua:35]: No. Action should handle only boolean values, `true` for `'new'`; `false` for `'old'`.

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua (hunk 28 above)
Comment (Lord-KA) [reply test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:36]: It's ok in Lua. Otherwise CI would fail.

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua (hunk 29 above)
Comment (Lord-KA) [reply test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:12]: Fixed.

File: src/lua/compat.lua (hunk 24 above)
Comment (Lord-KA) [reply src/lua/compat.lua:20]: Fixed.

File: src/lua/serializer.c (hunk 22 above)
Comment (Lord-KA) [reply src/lua/serializer.c:86]: Isn't that just for Lua code style?

File: src/lua/compat.h (hunk 30 above)
Comment (Lord-KA) [reply src/lua/compat.h:27]: > It is defined in the serializer module, so it is better to expose it from the serializer module.

I've tried that. The built-in registration doesn't work as intended (or isn't initialized when required).

File: src/lua/serializer.c (hunk 22 above)
Comment (Lord-KA) [reply src/lua/serializer.c:86]: Fixed anyway.

File: changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md (hunk 18 above)
[the remark this answers is not in the document]
Comment (Lord-KA) [reply changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md:1]: > I see now:
> 
> ```lua
> json.cfg({encode_esc_slash = <boolean>})
> require('tarantool').compat.json_escape_forward_slash = 'old' / 'new'
> ```
> 
> Why 'esc' in one case and 'escape' in the other? Why 'forward' is said in one case, but not in the other? There should be a consistency.
> 
> I would rename it so:
> 
> ```lua
> json.cfg({encode_escape_forward_slash = <boolean>})
> ```

Fixed.

File: src/lua/serializer.c (hunk 23 above)
Comment (Lord-KA) [reply src/lua/serializer.c:88]: Currently, we don't have `internal.serializer` module. I don't think this is the time or the PR to introduce it.

File: src/lua/compat.h (hunk 31 above)
Comment (Lord-KA) [reply src/lua/compat.h:19]: I don't want to introduce dependency on another patch to a [different repository](https://github.com/tarantool/msgpuck/).

Comment (Lord-KA) [reply src/lua/compat.h:19]: Also, we don't change msgpuck cfg with the toggler, I am even not sure if there is one. Thus, the naming is weird, `lbox_msgpuck_esc_slash()` would be better, but it doesn't seem too different from the current.

File: src/lua/serializer.c (hunk 23 above)
Comment (Lord-KA) [reply src/lua/serializer.c:88]: Added `lbox_serializer_default_cfg()` and moved `json_escape_forward_slash_toggle()` to `compat.c`.

File: src/lua/compat.lua (hunk 25 above)
Comment (Lord-KA) [reply src/lua/compat.lua:35]: We identify `'new'` as `true` in other parts of compat too (see `NEW` and `OLD` vars). We would have to convert 'new' and 'old' to bool in every postaction anyway, thus I don't see the point.

Comment (Lord-KA) [reply src/lua/compat.lua:35]: I've consulted with @igormunkin on the subject, and he agrees.

File: test/box-luatest/gh_7000_compat_module_test.lua (hunk 4 above)
[the remark this answers is not in the document]
Comment (Lord-KA) [reply test/box-luatest/gh_7000_compat_module_test.lua:10]: And it's OK in terms of Lua style-guide.

File: test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua (hunk 28 above)
Comment (Totktonada) [reply test/app-luatest/gh_6200_lua_cjson_escapes_slash_test.lua:44]: Hm. I always think that we have 80 charachers limit. Anyway, it is not so important to spin here around.

File: src/lua/compat.lua (hunk 25 above)
Comment (Totktonada) [reply src/lua/compat.lua:36]: No problem, okay. It would be good to have it documented somewhere for module developers.

File: src/lua/serializer.c (hunk 21 above)
Comment (Totktonada) [reply src/lua/serializer.c]: Sure, it means `return N`, not pushing a value. IOW, you can replace

```c
lua_pushnumber(L, 0);
return 1;
```

with

```c
return 0;
```

The function will push zero values to the Lua stack (will return nothing from a Lua caller perspective).

File: src/lua/compat.c (hunk 20 above)
Comment (Totktonada) [reply src/lua/compat.c:15]: Answered in https://github.com/tarantool/tarantool/pull/6910#discussion_r981081727.

Comment (Lord-KA) [reply src/lua/compat.c:15]: Still, segfault.

File: src/lua/serializer.c (hunk 23 above)
Comment (Lord-KA) [reply src/lua/serializer.c]: We discussed naming with @Totktonada and I changed them accordingly

File: changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md (hunk 17 above)
Comment (Totktonada) [reply changelogs/unreleased/gh-6200-lua_cjson-encode-escapes-slash.md]: I still see it in the commit message title prefix (I would make it `lua/json:`), in the changelog entry file name, in the test file name. Not a big problem, but I would polish it for accuracy and consistency.

BTW, json is Lua built-in module, but msgpuck is not:

> in json and msgpuck built-in modules

I would say 'json built-in module and msgpuck library' or, better (from a user perspective) 'json built-in module and JSON logger type'.

File: src/lua/compat.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/lua/compat.h:4]: I think 2010-2022 across all the sources should be okay. Closing the discussion.

File: src/lua/compat.lua (hunk 6 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/lua/compat.lua]: I can approve Gleb's answer. Closing the discussion.

File: src/lua/compat.c (hunk 20 above)
Comment (Lord-KA) [reply src/lua/compat.c]: U were right, removed pushnull and changed `return 1` to `return 0`

File: src/lua/compat.lua [hunk 32]
```diff
@@ -4,19 +4,41 @@
...
```
Comment (Totktonada) [inline src/lua/compat.lua:36]: Nit: I would write it like:

```lua
function(is_new)
    local escape_slash = not is_new
    <...>
```

File: src/lua/compat.lua [hunk 33]
```diff
@@ -4,19 +4,41 @@
...
+        require('json').cfg{encode_escape_forward_slash = value}
+        internals.json_escape_forward_slash_toggle(value);
+        internals.msgpuck_escape_forward_slash_toggle(value);
```
Comment (Totktonada) [inline src/lua/compat.lua:39]: Nit: Semicolons are redundant.

File: src/lua/serializer.c [hunk 34]
```diff
@@ -76,12 +76,26 @@ static struct {
...
 	OPTION(LUA_TBOOLEAN, encode_error_as_ext, 1),
+	OPTION(LUA_TBOOLEAN, encode_escape_forward_slash, 0),
 	OPTION(LUA_TBOOLEAN, decode_invalid_numbers, 1),
 	OPTION(LUA_TBOOLEAN, decode_save_metatables, 1),
 	OPTION(LUA_TNUMBER,  decode_max_depth, 128),
 	{ NULL, 0, 0, 0},
 };
 
+int
+serializer_set_option_default(char *name, int value)
```
Comment (Totktonada) [inline src/lua/serializer.c:87]: Nit: `char *` -> `const char *`?

File: src/lua/serializer.c [hunk 35]
```diff
@@ -76,12 +76,26 @@ static struct {
...
+{
+	assert(name != NULL);
+	for (int i = 0; OPTIONS[i].name != NULL; i++) {
+		if (!strcmp(OPTIONS[i].name, name)) {
+			OPTIONS[i].defvalue = value;
+			return 0;
+		}
+	}
+	return 1;
```
Comment (Totktonada) [inline src/lua/serializer.c:96]: Usually we return `0/-1` for success/error.

**Comment by Totktonada** [comment]
I would like to move Lua/C function definitions into (more or less) corresponding modules from `compat.c` and just call it from `compat.lua`:

```lua
require('json').cfg({encode_escape_forward_slash = <boolean>})
require('internal.serializer').default_cfg({encode_escape_forward_slash = <boolean>})
require('msgpack')._internal.msgpuck_cfg({encode_escape_forward_slash = <boolean>})
```

It is not a blocker, current solution is okay for me too.

File: src/lua/serializer.c (hunk 23 above)
Comment (Totktonada) [reply src/lua/serializer.c]: Summarized my opinion in https://github.com/tarantool/tarantool/pull/6910#issuecomment-1260924239.

File: src/lua/serializer.c (hunk 21 above)
Comment (Totktonada) [reply src/lua/serializer.c]: It is fixed now.

File: src/lua/compat.c (hunk 20 above)
Comment (Totktonada) [reply src/lua/compat.c]: It is fixed now.

File: src/lua/compat.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/lua/compat.c]: Summarized my opinion in https://github.com/tarantool/tarantool/pull/6910#issuecomment-1260924239.

**Review by Totktonada — APPROVED** [review]
LGTM for the JSON patch (I didn't looked into the compat part, it is reviewed in PR #7060). There are a few nits: feel free to accept or ignore.

File: src/lua/compat.lua (hunk 33 above)
Comment (Lord-KA) [reply src/lua/compat.lua:39]: My bad, missed that. Fixed.

File: src/lua/compat.lua (hunk 32 above)
Comment (Lord-KA) [reply src/lua/compat.lua:36]: Good idea, applied.

File: src/lua/serializer.c (hunk 34 above)
Comment (Lord-KA) [reply src/lua/serializer.c:87]: Fixed.

File: src/lua/serializer.c (hunk 35 above)
Comment (Lord-KA) [reply src/lua/serializer.c:96]: Fixed.

**Comment by Totktonada** [comment]
There were no significant changes -- let's take my past approve as actual.

File: src/lua/compat.c [hunk 36]
```diff
@@ -5,8 +5,40 @@
...
 
 #include <lua/compat.h>
+#include "serializer.h"
+
+int
+lbox_msgpuck_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool esc_slash = lua_toboolean(L, -1);
+	lua_pop(L, 1);
```
Comment (igormunkin) [inline src/lua/compat.c:15]: Minor: there is no need to explicitly pop this argument from Lua stack; `return 0;` below signals Lua VM to do it later.

File: src/lua/compat.c [hunk 37]
```diff
@@ -5,8 +5,40 @@
...
+
+	return 0;
+}
+
+int
+lbox_json_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool esc_slash = lua_toboolean(L, -1);
+	lua_pop(L, 1);
```
Comment (igormunkin) [inline src/lua/compat.c:30]: Ditto.

**Review by igormunkin — COMMENTED** [review]
@Lord-KA, thanks for the patch! Just a couple of nits regarding Lua API.

File: src/lua/compat.c [hunk 38]
```diff
@@ -5,8 +5,40 @@
...
+#include "serializer.h"
+
+int
+lbox_msgpuck_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool esc_slash = lua_toboolean(L, -1);
+	lua_pop(L, 1);
+
+	if (esc_slash)
```
Comment (igormunkin) [inline src/lua/compat.c:17]: I just wonder whether there is an option to implement the similar approach you've provided for JSON below? I hardly remember the reasons why do we need to change `char2escape` in place in this case.

File: src/lua/compat.c [hunk 39]
```diff
@@ -5,8 +5,40 @@
...
+
+	if (serializer_set_option_default("encode_escape_forward_slash", esc_slash))
+		assert(!"There is no encode_escape_forward_slash option"
+			" in serializer defaults.");
+
+	return 0;
+}
 
 static const struct luaL_Reg internal_compat[] = {
+	{"msgpuck_escape_forward_slash_toggle", lbox_msgpuck_escape_forward_slash_toggle},
```
Comment (ImeevMA) [inline src/lua/compat.c:40]: The line length is more than 80 characters.

File: src/lua/compat.c [hunk 40]
```diff
@@ -5,8 +5,40 @@
...
+	{"json_escape_forward_slash_toggle", lbox_json_escape_forward_slash_toggle},
```
Comment (ImeevMA) [inline src/lua/compat.c:41]: The line length is more than 80 characters.

File: src/lua/compat.lua [hunk 41]
```diff
@@ -15,14 +14,36 @@ local options_format = {
     action         = 'function/nil',
 }
 
+local JSON_ESCAPE_BRIEF = [[
+Whether to escape the forward slash symbol '/' using a backslash in a
+json.encode() result. The old and the new behavior produce a result, which
+is compatible ith the JSON specification. However most of other JSON encoders
+don't escape the forward slash, so the new behavior is considered more safe.
+
+https://github.com/tarantool/tarantool/wiki/compat%3Ajson_escape_forward_slash
```
Comment (ImeevMA) [inline src/lua/compat.lua:23]: It's quite strange for me to see the URL in the code. Do we really need it here?

File: src/lua/serializer.c [hunk 42]
```diff
@@ -76,12 +76,26 @@ static struct {
...
 	{ NULL, 0, 0, 0},
 };
 
+int
+serializer_set_option_default(const char *name, int value)
+{
+	assert(name != NULL);
+	for (int i = 0; OPTIONS[i].name != NULL; i++) {
+		if (!strcmp(OPTIONS[i].name, name)) {
+			OPTIONS[i].defvalue = value;
```
Comment (ImeevMA) [inline src/lua/serializer.c:92]: Changing the defaults in this way is a rather strange concept for me. But I think it's already been properly discussed, right?

File: src/lua/serializer.c [hunk 43]
```diff
@@ -76,12 +76,26 @@ static struct {
...
+			return 0;
+		}
+	}
+	return -1;
```
Comment (ImeevMA) [inline src/lua/serializer.c:96]: May be it would be right to add `diag_set()` here instead of the assert that you use on this function failure.

File: src/lua/serializer.h [hunk 44]
```diff
@@ -165,6 +167,15 @@ struct luaL_serializer {
 	struct rlist on_update;
 };
 
+/**
+ * @brief helper that sets cfg options default to value.
+ * @param name option to change
+ * @param value new default value
+ * @return non-zero when no option with the name found.
```
Comment (ImeevMA) [inline src/lua/serializer.h:174]: I think it's better to say that `-1` is returned on error and 0 on success.

File: src/lua/compat.c [hunk 45]
```diff
@@ -5,8 +5,40 @@
...
+int
+lbox_json_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool esc_slash = lua_toboolean(L, -1);
+	lua_pop(L, 1);
+
+	if (serializer_set_option_default("encode_escape_forward_slash", esc_slash))
+		assert(!"There is no encode_escape_forward_slash option"
+			" in serializer defaults.");
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:34]: As every other assertion, it is used in cases when the error is fatal and internal. I don't see anything bad in making it more verbose. If you do, please describe the issue in more detail.

File: src/lua/compat.lua (hunk 41 above)
Comment (Lord-KA) [reply src/lua/compat.lua:23]: We do, it is an agreed part of brief. We need to give user an easy way to access option wiki.

File: src/lua/serializer.c (hunk 42 above)
Comment (Lord-KA) [reply src/lua/serializer.c:92]: Yes we had two alternative implementations of such setter and selected the current as more simple one.

File: src/lua/serializer.h (hunk 44 above)
Comment (Lord-KA) [reply src/lua/serializer.h:174]: What is the difference?

File: src/lua/compat.c [hunk 46]
```diff
@@ -5,8 +5,40 @@
...
+	if (esc_slash)
+		mp_char2escape['/'] = "\\/";
+	else
+		mp_char2escape['/'] = NULL;
+
+	return 0;
+}
+
+int
+lbox_json_escape_forward_slash_toggle(struct lua_State *L)
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:26]: Will do.

File: src/lua/compat.c (hunk 36 above)
Comment (Lord-KA) [reply src/lua/compat.c:15]: Fixed.

File: src/lua/compat.c [hunk 47]
```diff
@@ -5,8 +5,40 @@
  */
 
 #include <lua/compat.h>
+#include "serializer.h"
+
+int
+lbox_msgpuck_escape_forward_slash_toggle(struct lua_State *L)
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:11]: Done.

File: src/lua/serializer.c (hunk 43 above)
Comment (Lord-KA) [reply src/lua/serializer.c:96]: The function is very internal, I feel that assert fits just as well.

File: src/lua/compat.c (hunk 40 above)
Comment (Lord-KA) [reply src/lua/compat.c:41]: Fixed.

File: src/lua/compat.c [hunk 48]
```diff
@@ -5,8 +5,40 @@
...
+}
+
+int
+lbox_json_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool esc_slash = lua_toboolean(L, -1);
+	lua_pop(L, 1);
+
+	if (serializer_set_option_default("encode_escape_forward_slash", esc_slash))
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:32]: Fixed.

File: src/lua/compat.c (hunk 45 above)
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:30]: Ok, we talked privately, and I agree, that it's not really needed here. Removed.

File: src/lua/compat.c (hunk 46 above)
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:28]: Done.

**Review by ImeevMA — CHANGES_REQUESTED** [review]
Hi! I saw the new version of the patch, but I think we still have some issues to resolve.

File: src/lua/compat.c [hunk 49]
```diff
@@ -5,8 +5,42 @@
...
+
+	assert(serializer_set_option_default("encode_escape_forward_slash",
+					     esc_slash) == 0);
+
+	return 0;
+}
 
 static const struct luaL_Reg internal_compat[] = {
+	{"msgpuck_escape_forward_slash_toggle",
+		lbox_msgpuck_escape_forward_slash_toggle},
```
Comment (ImeevMA) [inline src/lua/compat.c:41]: This is a rather strange indent. I think it should something like this:

```Diff
diff --git a/src/lua/compat.c b/src/lua/compat.c
index 0c3877f98..22d46b1ea 100644
--- a/src/lua/compat.c
+++ b/src/lua/compat.c
@@ -38,9 +38,9 @@ lbox_json_escape_forward_slash_toggle(struct lua_State *L)
 
 static const struct luaL_Reg internal_compat[] = {
        {"msgpuck_escape_forward_slash_toggle",
-               lbox_msgpuck_escape_forward_slash_toggle},
+        lbox_msgpuck_escape_forward_slash_toggle},
        {"json_escape_forward_slash_toggle",
-               lbox_json_escape_forward_slash_toggle},
+        lbox_json_escape_forward_slash_toggle},
        {NULL, NULL},
 };
 
```

File: src/lua/compat.c [hunk 50]
```diff
@@ -5,8 +5,42 @@
...
+	return 0;
+}
+
+static int
+lbox_json_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
+	bool esc_slash = lua_toboolean(L, -1);
+
+	assert(serializer_set_option_default("encode_escape_forward_slash",
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:33]: This won't, hot fix gone horribly wrong moment.

[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:33]: Will fix in the next iteration.

File: src/lua/compat.c [hunk 51]
```diff
@@ -5,8 +5,40 @@
...
+	else
+		mp_char2escape['/'] = NULL;
+
+	return 0;
+}
+
+int
+lbox_json_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:30]: Done.

File: src/lua/compat.c [hunk 52]
```diff
@@ -5,8 +5,40 @@
  */
 
 #include <lua/compat.h>
+#include "serializer.h"
+
+int
+lbox_msgpuck_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1) && "boolean argument expected");
```
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:13]: Done.

File: src/lua/compat.c (hunk 49 above)
Comment (Lord-KA) [reply src/lua/compat.c:41]: Fixed.

File: src/lua/compat.c (hunk 46 above)
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:28]: Done.

File: src/lua/serializer.c (hunk 43 above)
Comment (Lord-KA) [reply src/lua/serializer.c:96]: Changed to `unreachable()`.

File: src/lua/serializer.h (hunk 44 above)
Comment (Lord-KA) [reply src/lua/serializer.h:174]: Changed to `void`.

File: src/lua/compat.c (hunk 50 above)
[the remark this answers is not in the document]
Comment (Lord-KA) [reply src/lua/compat.c:33]: Done.

File: src/lua/compat.c [hunk 53]
```diff
@@ -5,8 +5,43 @@
...
+/* Toggler for msgpuck escaping change. */
+static int
+lbox_msgpuck_escape_forward_slash_toggle(struct lua_State *L)
+{
+	assert(lua_isboolean(L, -1));
+	bool esc_slash = lua_toboolean(L, -1);
+
+	/*
+	 * The table is changed outright, because runtime check (like one in
+	 * json serializer) is slower, more comolicated and is not required here
```
Comment (ImeevMA) [inline src/lua/compat.c:19]: Do you mean 'complicated'?

**Review by ImeevMA — APPROVED** [review]
Hi! Thank you for the fixes! I found an error in the comment and still think there is no need for `Requires #...`, but I don't think it should be a problem.

File: src/lua/compat.c (hunk 53 above)
Comment (Lord-KA) [reply src/lua/compat.c:19]: I did, thanks.

Comment (Lord-KA) [reply src/lua/compat.c:19]: Fixed.

**Review by igormunkin — APPROVED** [review]
@Lord-KA, thanks for the patch and all fixes made! LGTM now.
