### PR TITLE
test: box_promote and box_demote

### LINKED ISSUE #6033: box.ctl.promote() code in some simple places is not tested at all
I applied this diff:
```Diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 59925962d..b026dfe05 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1582,16 +1582,21 @@ box_promote(void)
 		 */
 		if (box_election_mode == ELECTION_MODE_MANUAL)
 			raft_stop_candidate(box_raft(), false);
+		else
+			assert(false);
 		if (rc != 0) {
+			assert(false);
 			in_promote = false;
 			return -1;
 		}
 		if (!box_raft()->is_enabled) {
+			assert(false);
 			diag_set(ClientError, ER_RAFT_DISABLED);
 			in_promote = false;
 			return -1;
 		}
 		if (box_raft()->state != RAFT_STATE_LEADER) {
+			assert(false);
 			diag_set(ClientError, ER_INTERFERING_PROMOTE,
 				 box_raft()->leader);
 			in_promote = false;
```
And all the tests passed. It is not something hard to reproduce. For example:
```Lua
box.cfg{
    replication_synchro_timeout = 1,
    election_mode = 'manual',
}
box.error.injection.set('ERRINJ_WAL_DELAY', true)
f = require('fiber').create(function() box.ctl.promote() end)
box.cfg{election_mode = 'voter'}
box.error.injection.set('ERRINJ_WAL_DELAY', false)
f:cancel()
```
Helps to test election mode change during elections:
```
Process 70218 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x0000000100123d13 tarantool`::box_promote() at box.cc:1586:4
   1583			if (box_election_mode == ELECTION_MODE_MANUAL)
   1584				raft_stop_candidate(box_raft(), false);
   1585			else
-> 1586				assert(false);
   1587			if (rc != 0) {
   1588				assert(false);
   1589				in_promote = false;
Target 0: (tarantool) stopped.
```

### PR DESCRIPTION
**Pull request by grafin**
Covered most of box_promote and box_demote with tests.
Didn’t find a way to test failing box_wait_limbo_acked in box_demote without adding dedicated ERRINJ.
IMO box_wait_limbo_acked should be covered by its own tests.

Also found interesting behaviour when simultaneously promoting two servers with election_mode = 'off' for the first time - sometimes they can both become limbo owners for some time.

<details><summary>wip_test.lua</summary>

```lua
local luatest = require('luatest')
local helpers = require('test.luatest_helpers')
local cluster = require('test.luatest_helpers.cluster')
local g = luatest.group('gh-6033-box-promote-demote')

g.before_each(function(g)
    g.cluster = cluster:new({})

    g.box_cfg = {
        election_mode = 'off';
        replication = {
            helpers.instance_uri('server_', 1);
            helpers.instance_uri('server_', 2);
        };
    }

    g.server_1 = g.cluster:build_and_add_server(
        {alias = 'server_1', box_cfg = g.box_cfg})
    g.server_2 = g.cluster:build_and_add_server(
        {alias = 'server_2', box_cfg = g.box_cfg})
    g.cluster:start()
end)

g.after_each(function(g)
    g.cluster:stop()
    g.cluster.servers = nil
end)

g.test_interfering_promote_in_wal = function(g)
    local wal_write_count = g.server_1:exec(function()
        box.error.injection.set('ERRINJ_WAL_DELAY', true)
        return box.error.injection.get('ERRINJ_WAL_WRITE_COUNT')
    end)

    g.server_2:exec(function()
        box.ctl.promote()
        box.error.injection.set('ERRINJ_WAL_DELAY', true)
    end)
    g.server_1:wait_wal_write_count(wal_write_count + 1)

    local ok, err = g.server_1:exec(function()
        local f = require('fiber').new(box.ctl.promote); f:set_joinable(true)
        box.error.injection.set('ERRINJ_WAL_DELAY', false)
        return f:join()
    end)

    print(string.format("Server %d thinks that limbo is owned by %d",
        g.server_1:exec(function()
            return box.info.id, box.info.synchro.queue.owner
    end)))

    print(string.format("Server %d thinks that limbo is owned by %d",
        g.server_2:exec(function()
            return box.info.id, box.info.synchro.queue.owner
    end)))

    g.server_2:exec(function()
        box.error.injection.set('ERRINJ_WAL_DELAY', false)
    end)

    luatest.assert(
        not ok and err.code == box.error.INTERFERING_PROMOTE,
        'interfering promote not handled')
end
```

</details>

Can lead to following result:
```
TAP version 13
1..1
# Started on Wed Dec 29 08:18:31 2021
# Starting group: gh-6033-box-promote-demote
Server 1 thinks that limbo is owned by 1
Server 2 thinks that limbo is owned by 2
not ok 1        gh-6033-box-promote-demote.test_interfering_promote_in_wal
#   ...v/github/tarantool/test/replication-luatest/wip_test.lua:63: interfering promote not handled
#   expected: a value evaluating to true, actual: false
#   stack traceback:
#       ...v/github/tarantool/test/replication-luatest/wip_test.lua:63: in function 'gh-6033-box-promote-demote.test_interfering_promote_in_wal'
#       ...
#       [C]: in function 'xpcall'
# Ran 1 tests in 2.703 seconds, 0 successes, 1 fail
```

Adding 3rd server, who calls box.ctl.promote before test starts fixes flack in the test, but there might be a problem with possibility of two simultaneous limbo owners. 

Closes #6033

### CODE REVIEW

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Hi! Good job on covering all the corner cases!

The tests are fine, my comments are mostly about the test setup.

**Comment by grafin** [comment]
Thanks for your comments and proposed fixes. I've fixed everything you mentioned. Strangely enough test_fail_limbo_acked_promote didn't flack for me at all before your patch.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 1]
```diff
@@ -0,0 +1,365 @@
...
+        return pcall(box.ctl.promote)
+    end)
+    luatest.assert(
+        not ok and err.code == box.error.UNSUPPORTED,
+        'error while promoting voter')
+end
+
+-- Test interfering promotion for election_mode = 'off'
+-- while in WAL delay
+g.test_wal_interfering_promote = function(g)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:174]: Let's unify this test with `test_wal_interfering_demote`.
They only differ in a single `promote/demote` call and can be parametrized.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 2]
```diff
@@ -0,0 +1,365 @@
...
+        return f:join()
+    end)
+    luatest.assert(
+        not ok and err.code == box.error.INTERFERING_PROMOTE,
+        'interfering promote not handled')
+end
+
+-- Test interfering promotion for election_mode = 'off'
+-- while in txn_limbo delay
+g.test_limbo_empty_interfering_promote = function(g)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:200]: Same. Let's unify this test with `test_limbo_empty_interfering_demote`

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 3]
```diff
@@ -0,0 +1,365 @@
...
+        'interfering demote not handled')
+end
+
+-- Test that box_demote will return 0 when demoting raft leader
+g.before_test('test_raft_leader_demote', function(g)
+    g.server_1:box_config({election_mode = 'manual'})
+    make_leader(g.server_1)
+end)
+
+g.test_raft_leader_demote = function(g)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:360]: I don't understand why is this test needed. Wasn't this case covered before your test?
Maybe you meant to demote server_2 and check that there is no error?

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the fixes!

It's much easier to see what's happening when the `before_` helpers are near the test they prepare.

Please, see my remaining comments and squash everything into a single commit once you're done.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 2 above)
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:243]: This one was broken before. It was doing box.ctl.promote in both tests, and the demote branch wasn't covered. I've fixed it. I've ran this test a lot and sometimes (less than once per 1000 runs) it fails on an assert. I am investigating this problem.

```
TAP version 13
1..1
# Started on Mon Jan 10 18:23:28 2022
# Starting group: gh-6033-box-promote-demote
server_1 | tarantool: /home/boris/dev/github/tarantool/src/box/box.cc:1810: void box_issue_demote(uint32_t, int64_t): Assertion `box_raft()->volatile_term == box_raft()->term' failed.
not ok 1        gh-6033-box-promote-demote.test_limbo_empty_interfering_demote
#   Peer closed
#   stack traceback:
#       builtin/box/net_box.lua:676: in function '_request'
#       builtin/box/net_box.lua:728: in function 'eval'
#       ...v/github/tarantool/test/replication-luatest/wip_test.lua:106: in function 'gh-6033-box-promote-demote.test_limbo_empty_interfering_demote'
#       ...
#       [C]: in function 'xpcall'
# Ran 1 tests in 2.528 seconds, 0 successes, 1 error
```

**Review by sergepetrenko — APPROVED** [review]
Thanks for the fixes!
LGTM.
Please, ask @Gerold103 to review this once you're ready.

**Comment by grafin** [comment]
@sergepetrenko I've commited some minor changes, take a look pls.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 4]
```diff
@@ -0,0 +1,325 @@
...
+    luatest.assert(ok, 'error while promoting unconfigured server')
+
+    local ok, _ = pcall(box.ctl.demote)
+    luatest.assert(ok, 'error while demoting unconfigured server')
+end
+
+-- Test that box_promote will return 0
+-- if server is already raft leader and limbo owner.
+g.test_leader_promote = function(g)
+    local ok, _ = g.server_1:exec(function()
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:87]: So, here in the test code it is more obvious - in the comment you said "server is already raft leader" but from the test code it is hardly visible. Because the first promotion is done somewhere above in a `before_test` function. Please, move the preparations into the test cases themselves.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 5]
```diff
@@ -0,0 +1,325 @@
...
+    end)
+
+    g.server_2:exec(function()
+        box.ctl.promote()
+    end)
+    g.server_2:wait_synchro_queue_owner()
+    g.server_1:wait_wal_write_count(wal_write_count + 1)
+
+    local ok, err = g.server_1:exec(function()
+        local f = require('fiber').new(box.ctl.promote); f:set_joinable(true)
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:206]: `fiber.new()` does not yield. It means that you will set the delay to `false` below before `box.ctl.promote()` is called in your new fiber. That in turn raises 2 questions - why do you need to start the promote before turning off the injection and are you sure the test works as intended then?

Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:206]: Lets write statements on separate lines and not use `;`. `;` is not needed in Lua.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 6]
```diff
@@ -0,0 +1,325 @@
...
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
+        return f:join()
+    end)
+    luatest.assert(
+        not ok and err.code == box.error.INTERFERING_PROMOTE,
+        'interfering promote not handled')
+end
+
+-- Test interfering promotion for election_mode = 'off'
+-- while in txn_limbo delay
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:256]: What is that "`txn_limbo` delay"? It has plenty of waits in its API. I would suggest to be a bit more specific here and less about low level details. They might change and the test still should have relevant comments.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 7]
```diff
@@ -0,0 +1,325 @@
...
+g.test_limbo_empty_interfering_promote = function(g)
+    local wal_write_count, f = g.server_1:exec(function()
+        box.error.injection.set('ERRINJ_TXN_LIMBO_EMPTY_DELAY', true)
+        local f = require('fiber').new(box.ctl.promote); f:set_joinable(true)
+        return box.error.injection.get('ERRINJ_WAL_WRITE_COUNT'), f:id()
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua]: Lets write statements on separate lines and without `;`'.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 8]
```diff
@@ -0,0 +1,375 @@
...
+        box.error.injection.set('ERRINJ_TXN_LIMBO_EMPTY_DELAY', false)
+        return require('fiber').find(f):join()
+    end, {f})
+    luatest.assert(
+        not ok and err.code == box.error.INTERFERING_PROMOTE,
+        'interfering promote not handled')
+end
+
+-- Test failing box_wait_limbo_acked in box_promote for election_mode = 'off'
+g.test_fail_limbo_acked_promote = function(g)
```
[the remark this answers is not in the document]
Comment (Gerold103) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua]: I now get this crash:
```
[32mserver_1 | [0mAssertion failed: (replicaset.applier.loading > 0), function replica_on_applier_reconnect, file /Users/gerold/Work/Repositories/tarantool/src/box/replication.cc, line 396.[0m
```
But I don't think it is related to this patch. It happens only when I run 30 tests in parallel like that: `python test-run.py $(yes 6033 | head -30)`. It is not a blocker. We could deal with it later. Just letting you know.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 9]
```diff
@@ -0,0 +1,325 @@
...
+g.before_each(function(g)
+    g.cluster = cluster:new({})
+
+    g.box_cfg = {
+        election_mode = 'off';
+        replication_timeout = 0.1,
+        replication = {
+            helpers.instance_uri('server_', 1);
+            helpers.instance_uri('server_', 2);
+            helpers.instance_uri('server_', 3);
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua]: I suggest to make it just `server_1`, `server_2` and `server_3`. It is the same as you wrote, but consistent with how you use `server_1`/`server_2`/`server_3` everywhere else as a member of `g`. The same in all the other places where `instance_uri` is used.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 10]
```diff
@@ -0,0 +1,325 @@
...
+        return box.error.injection.get('ERRINJ_WAL_WRITE_COUNT')
+    end, {helpers.instance_uri('server_', 3)})
+
+
+    g.server_3:exec(function()
+        local s = box.schema.create_space('test', {is_sync = true})
+        s:create_index('pk')
+        require('fiber').create(s.replace, s, {1})
+    end)
+    g.server_3:wait_synchro_queue_owner()
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua]: Why do you need this line? You already did `g.server_3:wait_synchro_queue_owner()` in `before_each` call and there was no a reason for `server_3` to stop being the owner since the test case started.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 11]
```diff
@@ -0,0 +1,325 @@
...
+
+    local ok, err = g.server_1:exec(function()
+        box.cfg{replication_synchro_timeout = 0.1}
+        return pcall(box.ctl.promote)
+    end)
+
+    g.server_2:exec(function()
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
+    end)
+    print(ok, err)
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua]: Lets drop debug prints.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 12]
```diff
@@ -0,0 +1,325 @@
...
+    g.server_3:box_config({
+        replication_synchro_quorum = 3,
+        replication_timeout = 0.5,
+        replication = {
+            helpers.instance_uri('server_', 1),
+        },
+    })
+
+    local wal_write_count = g.server_1:exec(function(r)
+        box.cfg{replication = {r}}
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua]: Why do you need to change replication uris? It seems you could just block WAL on one node, start limbo write on one, and call promote on third with quorum = 3. It would give the same result, wouldn't it?

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 13]
```diff
@@ -0,0 +1,325 @@
...
+    g.server_2:exec(function()
+        box.ctl.promote()
+    end)
+    g.server_2:wait_synchro_queue_owner()
+    g.server_3:wait_wal_write_count(wal_write_count + 1)
+
+    local ok, err = g.server_3:exec(function()
+        local f = require('fiber').new(box.ctl.demote); f:set_joinable(true)
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
+        return f:join()
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua]: The same comment as for a similar test about promote.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 14]
```diff
@@ -0,0 +1,325 @@
...
+        return require('fiber').find(f):join()
+    end, {f})
+    luatest.assert(
+        not ok and err.code == box.error.INTERFERING_PROMOTE,
+        'interfering demote not handled')
+end
+
+-- Test that box_demote will return 0 when demoting raft leader
+g.test_raft_leader_demote = function(g)
+    local ok, _ = g.server_1:exec(function()
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua]: No need for `_`. Just drop it. In Lua it is not necessary to have the same number of variables on the left side as there are values on the right side. The same in other similar places.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 15]
```diff
@@ -27,24 +27,14 @@ g.before_each(function(g)
         replication = {
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:52]: Lets squash commits which fix problems of the previous commits. To make them cleaner. Otherwise making a review is really hard - I review some code and then in the next commit it is just rewritten/fixed.

I will be back when the commits fixing older commits are squashed.

**Review by Gerold103 — CHANGES_REQUESTED** [review]

File: src/box/raft.c [hunk 16]
```diff
@@ -29,6 +29,7 @@
  * SUCH DAMAGE.
  */
```
[the remark this answers is not in the document]
Comment (grafin) [reply src/box/raft.c:30]: If you have time, I would appreciate a proper review for several first PRs.

File: test/luatest_helpers/server.lua [hunk 17]
```diff
@@ -160,6 +187,10 @@ function Server:instance_uuid()
     return uuid
 end
 
+function Server:box_config(config)
```
[the remark this answers is not in the document]
Comment (grafin) [reply test/luatest_helpers/server.lua:196]: That was my first thought, but there is box_cfg table member in Server. I've searched if it was used anywhere, and didn't find anything except:
```lua
if self.box_cfg ~= nil then
    res.TARANTOOL_BOX_CFG = json.encode(self.box_cfg)
end
```
in Server:build_env. AFAIK it is not used in any test, if it's ok to remove it - I can do that and rename box_config to box_cfg.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 18]
```diff
@@ -335,14 +331,14 @@ g.test_fail_limbo_acked_promote = function(g)
...
-
     g.server_3:exec(function()
+        box.ctl.promote()
         local s = box.schema.create_space('test', {is_sync = true})
         s:create_index('pk')
         require('fiber').create(s.replace, s, {1})
     end)
-    g.server_1:wait_wal_write_count(wal_write_count + 1)
 
+    g.server_1:wait_wal_write_count(wal_write_count + 6)
```
[the remark this answers is not in the document]
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:329]: there is an update for key max_id before space insertation.
<details><summary>xlog:</summary>

```
---
HEADER:
  lsn: 1
  replica_id: 3
  type: PROMOTE
  timestamp: 1642698926.0176
BODY:
  2: 0
  3: 0
  83: 2
---
HEADER:
  lsn: 1
  group_id: 1
  type: RAFT
  timestamp: 1642698926.0178
BODY:
  0: 2
---
HEADER:
  lsn: 2
  replica_id: 3
  type: UPDATE
  timestamp: 1642698926.018
BODY:
  space_id: 272
  index_base: 1
  key: ['max_id']
  tuple: [['+', 2, 1]]
---
HEADER:
  lsn: 3
  replica_id: 3
  type: INSERT
  timestamp: 1642698926.0184
BODY:
  space_id: 280
  tuple: [512, 0, 'test', 'memtx', 0, {'is_sync': true}, []]
---
HEADER:
  lsn: 4
  replica_id: 3
  type: INSERT
  timestamp: 1642698926.0192
BODY:
  space_id: 288
  tuple: [512, 0, 'pk', 'tree', {'unique': true}, [[0, 'unsigned']]]
---
HEADER:
  lsn: 5
  replica_id: 3
  type: REPLACE
  timestamp: 1642698926.0192
BODY:
  space_id: 512
  tuple: [1]
```

</details>

[the remark this answers is not in the document]
Comment (sergepetrenko) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:329]: Yes, indeed, thanks for digging into this!

**Comment by grafin** [comment]
@sergepetrenko, @Gerold103 thanks for your replies, I've completely overhauled all the tests, please take a look.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Hi! Thanks for working on this!

There are some set-up related comments left. Please, address them.

File: test/luatest_helpers/server.lua [hunk 19]
```diff
@@ -273,4 +346,62 @@ function Server:grep_log(what, bytes, opts)
...
+function Server:promote()
+    self:exec(function(delay, timeout)
+        local old_election_term = box.info.election.term
+        local deadline = require('clock').time() + timeout
+        repeat
+            if require('clock').time() > deadline then
+                error(('Promoting server %d timed out'):format(box.info.id))
+            end
+            pcall(box.ctl.promote)
+            require('fiber').sleep(delay)
```
[the remark this answers is not in the document]
Comment (grafin) [reply test/luatest_helpers/server.lua]: Using fiber.yield() here instead of sleep leads to more tries overall, because promote/demote usually fail because of interrupt from another node and it's better to wait until all interrupting negotiations end. I rewrote those loops and now they are fast enough IMO.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 20]
```diff
@@ -0,0 +1,444 @@
...
+
+    g.server_1:wait_lsn(g.server_2)
+    g.server_2:wait_lsn(g.server_1)
+
+    g.server_1:box_config(g.box_cfg)
+    g.server_2:box_config(g.box_cfg)
+
+    -- Best way to make sure no one is leader: promote and then demote someone
+    g.cluster:promote(g.server_2)
+    g.cluster:demote(g.server_2)
```
[the remark this answers is not in the document]
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua]: I've divided tests into 3 groups: unconfigured, test where space is created (will be tested with memtx and vinyl), and tests without user-defined spaces (will be tested only with memtx)

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 21]
```diff
@@ -0,0 +1,501 @@
...
+        },
+    }
+
+    g.server_1 = g.cluster:build_and_add_server(
+        {alias = 'server_1', engine = engine, box_cfg = g.box_cfg})
+    g.server_2 = g.cluster:build_and_add_server(
+        {alias = 'server_2', engine = engine, box_cfg = g.box_cfg})
+    g.cluster:start()
+
+    g.current_test = 1
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:76]: Why do you need that?

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 22]
```diff
@@ -0,0 +1,501 @@
...
+    end)
+    g.server_2:wait_lsn(g.server_1)
+    luatest.assert(ok, string.format(
+        'error while demoting with elections on: %s', err))
+end
+
+g_nspaces.after_test('test_ok', function(g)
+    g.server_1:box_config({election_mode = 'off'})
+    g.cluster:promote(g.server_2)
+    g.cluster:demote(g.server_2)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:216]: Are you sure this promote + demote pair is needed? It looks like a workaround for waiting for some state, or something.

You demote `server1` right in the test, so this promote + demote shouldn't be necessary.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 23]
```diff
@@ -0,0 +1,501 @@
...
+
+    wal_delay_end(g.server_2)
+    local ok, err = fiber_join(g.server_2, f)
+
+    luatest.assert(not ok and err.code == box.error.INTERFERING_PROMOTE,
+        'interfering demote not handled')
+end
+
+g_nspaces.after_test('test_wal_interfering_demote', function(g)
+    g.cluster:promote(g.server_2)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:309]: Same question as in the previous test.
Here we know that server_2 has failed demotion because it received server1 promote first.
So let's simply demote it now.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 24]
```diff
@@ -0,0 +1,501 @@
...
+        'wait quorum failure not handled')
+end
+
+g_spaces.after_test('test_fail_limbo_ack_promote', function(g)
+    g.server_2:exec(function()
+        -- Timeout for rollback
+        box.cfg{replication_synchro_timeout = 0.1}
+        -- Wait for rollback to happen
+        require('fiber').sleep(0.1)
+        -- Just in case we are not leader somehow
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:494]: Is it possible?

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 25]
```diff
@@ -0,0 +1,501 @@
...
+    g.server_1:wait_lsn(g.server_2)
+
+    -- Start promoting with default replication_synchro_timeout,
+    -- wait until promote reaches waiting for limbo_acked,
+    -- make it timeout by lowering replication_synchro_timeout
+    local ok, err = g.server_1:exec(function()
+        local fiber = require('fiber')
+        local f = fiber.new(function() box.ctl.promote() end)
+        f:set_joinable(true)
+        box.cfg{replication_synchro_timeout = 0.1}
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:480]: I suggest you set a smaller timeout here. 0.01 seconds looks harmless.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 26]
```diff
@@ -0,0 +1,501 @@
...
+    luatest.assert(not ok and err.code == box.error.QUORUM_WAIT,
+        'wait quorum failure not handled')
+end
+
+g_spaces.after_test('test_fail_limbo_ack_promote', function(g)
+    g.server_2:exec(function()
+        -- Timeout for rollback
+        box.cfg{replication_synchro_timeout = 0.1}
+        -- Wait for rollback to happen
+        require('fiber').sleep(0.1)
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:493]: Let's set the timeout to 0.01

**Review by sergepetrenko — COMMENTED** [review]
Thanks for the fixes!
I still have some comments regarding test teardown, but otherwise the patch looks good.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 22 above)
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:216]: Thanks for review! Yeah, demoted it, with election_mode='manual', between tests election_mode is set to 'off', and we will have #6860. I have no real idea how to fix it here without promote/demote pair. I can add a comment on why that's the case.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 27]
```diff
@@ -0,0 +1,501 @@
...
+    wal_delay_end(g.server_1)
+    local ok, err = fiber_join(g.server_1, f)
+
+    luatest.assert(not ok and err.code == box.error.INTERFERING_PROMOTE,
+        'interfering promote not handled')
+end
+
+g_nspaces.after_test('test_wal_interfering_promote', function(g)
+    g.cluster:promote(g.server_1)
+    g.cluster:demote(g.server_1)
```
[the remark this answers is not in the document]
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:283]: The problem is server_1 has incremented term successfully, but didn't promote, and now server_2 isn't current leader but still limbo owner (leader of previous term). So demoting server_2 won't do anything.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 23 above)
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:309]: Same here. But now server_1 has limbo, but isn't leader in new term (server_2 demote one)

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 24 above)
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:494]: bad comment here. It is not only possible, it will happen. server_1 will increment term and then fail its promote.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 21 above)
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua]: Whoops, left it behind after deleting debug prints.

**Comment by grafin** [comment]
Thanks for review, I've fixed or commented every problem. I don't really have any ideas on how to remove those promote-demote pairs, they seem odd to me too, but it's the only way I've found to get around it.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 22 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:216]: Thanks for the explanation! I see now.
Ok, let it be then, but please add some comment mentioning this issue

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 27 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:285]: I see, thanks!

**Review by sergepetrenko — APPROVED** [review]
Thanks for working on this!
LGTM.

**Review by sergepetrenko — DISMISSED** [review]
Nothing changed since my last review, so LGTM.

**Comment by sergepetrenko** [comment]
@Gerold103, please, take a look.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 28]
```diff
@@ -0,0 +1,505 @@
...
+g_spaces.after_all(function(g) g.cluster:drop() end)
+
+g_nspaces.after_each(cluster_reinit)
+g_spaces.after_each(cluster_reinit)
+
+-- Promoting/demoting should succeed if server is not configured.
+g_unconfigured.test_unconfigured = function()
+    local ok, err = pcall(box.ctl.promote)
+    luatest.assert(ok, string.format(
+        'error while promoting unconfigured server: %s', err))
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:98]: Message in assertion should say what you expect. Not what you do not expect. Here you assert `ok` but say it is an error. It should be just *"promoting unconfigured server"*. Not an error. If you want to specifically test the error and get its value in case of failure, you can add a line `luatest.assert_equals(err, nil, 'no error')`. Then when fails, it will print the value of `err`. Same in other places.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 29]
```diff
@@ -0,0 +1,505 @@
...
+end
+
+-- Promoting current raft leader should succeed,
+-- even if he doesn't own synchro queue with elections enabled.
+g_nspaces.test_raft_leader_promote = function(g)
+    g.server_1:box_config({election_mode = 'manual'})
+
+    -- Promote server, but get stuck before obtaining synchro queue
+    -- (write term bump to wal, get stuck on promote)
+    wal_delay_start(g.server_1, 2)
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:153]: You here again rely on exact WAL write count when PROMOTE is written. You should better allow WAL writes one by one until you get both WAL_DELAY active + queue being busy. That would mean PROMOTE is currently stuck in WAL. I made a function for my own patch in another ticket which you could use:
```Lua
-- Allow WAL writes one by one until the synchro queue becomes busy. The
-- function is needed, because during box.ctl.promote() it is not known for sure
-- which WAL write is PROMOTE - first, second, third? Even if known, it might
-- change in the future.
local function play_wal_until_synchro_queue_is_busy(server)
    luatest.helpers.retrying({timeout = wait_timeout}, server.exec, server,
                             function()
        if not box.error.injection.get('ERRINJ_WAL_DELAY') then
            error('WAL did not reach the delay yet')
        end
        if box.info.synchro.queue.busy then
            return
        end
        -- Allow 1 more WAL write.
        box.error.injection.set('ERRINJ_WAL_DELAY_COUNTDOWN', 0)
        box.error.injection.set('ERRINJ_WAL_DELAY', false)
        error('Not busy yet')
    end)
end
```
Usage is to make `box.error.injection.set('ERRINJ_WAL_DELAY_COUNTDOWN', 0)`, then `require('fiber').create(box.ctl.promote)`, then `play_wal_until_synchro_queue_is_busy(server)`.

If you don't want to bother, then at least there should be an assertion that `box.info.synchro.queue.busy` is true. Then it probably will fail if PROMOTE WAL write won't be number 2 in the future.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 30]
```diff
@@ -0,0 +1,505 @@
...
+    local ok, err = g.server_1:exec(function()
+        return pcall(box.ctl.promote)
+    end)
+    luatest.assert(ok, string.format(
+        'error while promoting leader with elections off: %s', err))
+end
+
+g_nspaces.after_test('test_leader_promote', function(g)
+    g.cluster:demote(g.server_1)
+    g.server_2:wait_synchro_queue_owner_id(0)
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:127]: Why can't these `after_test` just be moved into the test's body? Same in all the other places. IMO these are not kind of tests which can restore their state after any moment of a test case. It is not just a space removal or something. I would just let it fail with all the colors in case of a bug instead of complicating the code.
Up to you.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 31]
```diff
@@ -0,0 +1,505 @@
...
+    g.server_1:box_config({election_mode = 'off'})
+    g.cluster:demote(g.server_1)
+    g.server_2:wait_synchro_queue_owner_id(0)
+end)
+
+-- Promoting and demoting should work when everything is ok.
+g_nspaces.test_ok = function(g)
+    local ok, err = g.server_1:exec(function()
+        return pcall(box.ctl.promote)
+    end)
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:182]: Why didn't you use `g.server_1:promote()`? Same in other places where you do `exec` manually and without that retry loop which is present in `server:promote()`.
Same for demotion.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 32]
```diff
@@ -0,0 +1,505 @@
...
+    g.server_1:wait_synchro_queue_owner_id(0)
+end)
+
+-- Simultaneous promoting/demoting should fail.
+g_nspaces.test_simultaneous = function(g)
+    wal_delay_start(g.server_1)
+
+    local wal_write_count = g.server_1:wal_write_count()
+    g.f = promote_start(g.server_1)
+    g.server_1:wait_wal_write_count(wal_write_count + 1)
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:226]: Are you waiting for a term bump here? Then I would suggest to wait for it explicitly. WAL write count is a fragile thing when it comes to procedures which might make multiple WAL writes.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 33]
```diff
@@ -0,0 +1,505 @@
...
+    server_3:box_config({
+        replication_synchro_quorum = 4,
+        replication_synchro_timeout = 1000,
+    })
+
+    -- Server_3 fills synchro queue and dies
+    local lsn = server_3:lsn()
+    server_3:exec(function()
+        local s = box.space.test
+        require('fiber').create(s.replace, s, {1}):id()
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:366]: You don't need `:id()` in the end. You never use it.

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Thanks for the fixes!
I was asked to make a next review. But the problem is that this PR depends on your other PR: https://github.com/tarantool/tarantool/pull/6858. And the latter still has not addressed comments. In particular you said: *@sergepetrenko suggested that relay_restart_recovery may be dead code and can be removed, we will try to do it, if it is not too complicated to do so, I'll open second PR soon*. So what is the status? Even if we reach an approve on this PR, it is still blocked by #6858 AFAIU.

**Comment by grafin** [comment]
Thanks for review! Quick reply so that you don't waste your time on investigating #6858 right now.
@sergepetrenko did get an alternative working patchset #6858  https://github.com/sergepetrenko/tarantool/tree/sp/experiment
I will open PR for it ASAP.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 34]
```diff
@@ -0,0 +1,516 @@
...
+    local term = g.server_1:election_term()
+    local f = promote_start(g.server_1)
+    g.server_1:wait_election_term(term + 1)
+
+    g.server_1:exec(function()
+        box.error.injection.set('ERRINJ_RAFT_WAIT_TERM_PERSISTED_DELAY', true)
+    end)
+    promote(g.server_2)
+    wal_delay_end(g.server_1)
+    g.server_1:wait_synchro_queue_term(g.server_2:synchro_queue_term())
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:325]: I don't think you need an injection here. You can wait for `box.info.election.leader == g.server_2:instance_id()` after `promote(g.server_2)` and it will have the same effect. Same with the demote test.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 35]
```diff
@@ -0,0 +1,516 @@
...
+        server.build_instance_uri('server_3'),
+    }
+
+    local server_3 = g.cluster:build_server(
+        {alias = 'server_3', box_cfg = g.box_cfg})
+    server_3:start()
+    box_cfg_update(g.cluster.servers, box_cfg)
+
+    promote(server_3)
+    wait_sync({g.server_1, g.server_2, server_3})
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:394]: You don't need this `wait_sync()` if you have another one below anyway.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 36]
```diff
@@ -0,0 +1,516 @@
...
+    promote(g.server_2)
+    g.server_2:exec(function()
+        local s = box.schema.create_space('test', {is_sync = true})
+        s:create_index('pk')
+        require('fiber').create(s.replace, s, {1})
+    end)
+    wait_sync(g.cluster.servers)
+
+    -- start promoting with default replication_synchro_timeout,
+    -- wait until promote reaches waiting for limbo_acked,
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:493]: I don't see the waiting.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 37]
```diff
@@ -0,0 +1,516 @@
...
+    -- make it timeout by lowering replication_synchro_timeout
+    local ok, err = g.server_1:exec(function()
+        local fiber = require('fiber')
+        local f = fiber.new(function() box.ctl.promote() end)
+        f:set_joinable(true)
+        box.cfg{replication_synchro_timeout = 0.01}
```
Comment (Gerold103) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:499]: Updating the synchro timeout won't yield. Which means this is the same as doing:
```Lua
box.cfg{replication_synchro_timeout = 0.01}
box.ctl.promote()
```
without any fibers. Are you sure this is what you intended to do?

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Thanks for the patch!

File: src/box/raft.c [hunk 38]
```diff
@@ -521,6 +522,7 @@ box_raft_wait_term_persisted(void)
 	do {
 		fiber_yield();
 	} while (raft->term < data.term && !fiber_is_cancelled());
+	ERROR_INJECT_YIELD(ERRINJ_RAFT_WAIT_TERM_PERSISTED_DELAY);
```
[the remark this answers is not in the document]
Comment (grafin) [reply src/box/raft.c]: My bad, fixed by moving error injection yield right before the loop.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 39]
```diff
@@ -0,0 +1,516 @@
...
+            if server_1 ~= server_2 then
+                server_1:wait_election_term(server_2:election_term())
+                server_1:wait_vclock_of(server_2)
+            end
+        end
+    end
+end
+
+-- Run box.ctl.promote until server is RAFT leader and limbo owner.
+-- Might need to run several promotes because of some error. After this
```
[the remark this answers is not in the document]
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua]: I've tried removing those retries and everything still works fine. I guess I've added them to handle some missing synchronization, when previous promote/demote from neighbor could have interrupted ongoing promote/demote. Same for demote.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 40]
```diff
@@ -0,0 +1,516 @@
...
+
+g_common.before_all(cluster_init)
+g_common.after_all(cluster_stop)
+g_common.before_each(cluster_reinit)
+
+-- Promoting/demoting should succeed if server is not configured.
+g_unconfigured.test_unconfigured = function()
+    local ok, err = pcall(box.ctl.promote)
+    luatest.assert(ok, string.format(
+        'Promoting unconfigured server is always successful: %s', err))
```
[the remark this answers is not in the document]
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:143]: I prefer to leave it as is, because it breaks into two lines more clearly.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 35 above)
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua]: Fixed.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 37 above)
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua]: After term has been written to WAL promote() waits until limbo is acked for 2*replication_synchro_timeout, during this wait i I change replication_synchro_timeout to lower value, which makes waiting transactions to timeout, leading to promote failure.

Comment (Gerold103) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua]: You are missing the point - I meant that you didn't need `fiber.new()` in the old code. It won't start the fiber immediately. Hence in your old code you didn't change the timeout *during* promote. You changed it *before* the promote. Because the fiber created with `fiber.new()` will actually start only after a yield, which you didn't have before the `box.cfg` below.

**Review by Gerold103 — COMMENTED** [review]
Good work! Some important places are covered. But I found a couple of new ones:
```Diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 881932727..e7b5b853e 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -1975,9 +1975,12 @@ box_promote_qsync(void)
 	if (txn_limbo_replica_term(&txn_limbo, instance_id) == raft->term)
 		return 0;
 	int64_t wait_lsn = box_wait_limbo_acked(TIMEOUT_INFINITY);
-	if (wait_lsn < 0)
+	if (wait_lsn < 0) {
+		assert(false);
 		return -1;
+	}
 	if (raft->state != RAFT_STATE_LEADER) {
+		assert(false);
 		diag_set(ClientError, ER_NOT_LEADER, raft->leader);
 		return -1;
 	}
```
with these the tests pass. Can they be covered in this patch too?

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua [hunk 41]
```diff
@@ -0,0 +1,501 @@
...
+    demote(g.server_1)
+end
+
+-- Promoting and demoting should work when everything is ok.
+g_common.test_ok = function(g)
+    local ok, err = g.server_1:exec(function()
+        return pcall(box.ctl.promote)
+    end)
+    luatest.assert(ok, string.format(
+        'Promoting succeeds with elections off: %s', err))
```
Comment (sergepetrenko) [inline test/replication-luatest/gh_6033_box_promote_demote_test.lua:225]: This place flaky fails when I run the test a lot:
```
[031] Test failed! Output from reject file /tmp/t/rejects/replication-luatest/gh_6033_box_promote_demote.reject:
[031] TAP version 13
[031] 1..12
[031] # Started on Thu Jun 16 21:20:25 2022
[031] # Starting group: gh-6033-box-promote-demote
[031] ok     1	gh-6033-box-promote-demote.test_leader_promote
[031] ok     2	gh-6033-box-promote-demote.test_follower_demote
[031] ok     3	gh-6033-box-promote-demote.test_raft_leader_promote
[031] not ok 4	gh-6033-box-promote-demote.test_ok
[031] #   .../replication-luatest/gh_6033_box_promote_demote_test.lua:224: Promoting succeeds with elections off: Instance with replica id 1 was promoted first
[031] #   expected: a value evaluating to true, actual: false
[031] #   stack traceback:
[031] #   	.../replication-luatest/gh_6033_box_promote_demote_test.lua:224: in function 'gh-6033-box-promote-demote.test_ok'
[031] #   	...
[031] #   	[C]: in function 'xpcall'
[031] ok     5	gh-6033-box-promote-demote.test_simultaneous
[031] ok     6	gh-6033-box-promote-demote.test_voter_promote
[031] ok     7	gh-6033-box-promote-demote.test_wal_interfering_promote
[031] ok     8	gh-6033-box-promote-demote.test_wal_interfering_demote
[031] ok     9	gh-6033-box-promote-demote.test_limbo_full_interfering_promote
[031] ok     10	gh-6033-box-promote-demote.test_limbo_full_interfering_demote
[031] ok     11	gh-6033-box-promote-demote.test_fail_limbo_ack_promote
[031] # Starting group: gh-6033-box-promote-demote-unconfigured
[031] ok     12	gh-6033-box-promote-demote-unconfigured.test_unconfigured
[031] # Ran 12 tests in 2.097 seconds, 11 succeeded, 1 failed

```

Comment (sergepetrenko) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:225]: I guess a `wait_sync` is missing before the promotion?

**Review by sergepetrenko — COMMENTED** [review]
Thanks for working on this!
We are close to the finish line, I hope.

File: test/replication-luatest/gh_6033_box_promote_demote_test.lua (hunk 41 above)
Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:225]: I've tried my best to reproduce, on my machine i didn't fail once in like 5k runs:(. Adding wait_sync shouldn't help, because there is a wait_sync in the end of before_each. But you can try it. Also you can try the following patch:
<details>
<summary>patch</summary>

```diff
diff --git a/test/replication-luatest/gh_6033_box_promote_demote_test.lua b/test/replication-luatest/gh_6033_box_promote_demote_test.lua
index 81523de47..1a88e7934 100644
--- a/test/replication-luatest/gh_6033_box_promote_demote_test.lua
+++ b/test/replication-luatest/gh_6033_box_promote_demote_test.lua
@@ -22,15 +22,39 @@ local function wait_sync(servers)
     end
 end

+-- Run box.ctl.promote until server is RAFT leader and limbo owner.
+-- Might need to run several promotes because of some error. After this
+-- function returns we can be 100% sure, that server considers itself leader.
+-- After that wait until server is RW.
 local function promote(server)
-    server:exec(function()
-        box.ctl.promote()
-        box.ctl.wait_rw()
+    luatest.helpers.retrying({}, function()
+        return server:exec(function()
+            pcall(box.ctl.promote)
+            if box.info.election.state ~= 'leader' then
+                return false
+            end
+            if box.info.synchro.queue.owner ~= box.info.id then
+                return false
+            end
+            return true
+        end)
     end)
+    server:exec(function() box.ctl.wait_rw() end)
 end

+-- Run box.ctl.demote until server is not RAFT leader.
+-- Server might still be RW and/or limbo owner, if elections are turned off.
+-- See https://github.com/tarantool/tarantool/issues/6860
 local function demote(server)
-    server:exec(function() box.ctl.demote() end)
+    luatest.helpers.retrying({}, function()
+        return server:exec(function()
+            pcall(box.ctl.demote)
+            if box.info.election.state == 'leader' then
+                return false
+            end
+            return true
+        end)
+    end)
 end

 -- Allow WAL writes one by one until the synchro queue becomes busy. The
```
</details>

Sometime ago promoting and demoting like that solved similar problems.

Comment (grafin) [reply test/replication-luatest/gh_6033_box_promote_demote_test.lua:225]: Thanks @sergepetrenko for investigating this problem. Found out that previous promote from same instance from previous test was interfering with promote in test_ok. Fixed. Also added waiting for new synchro queue term in similar place.

<details>
<summary>fix</summary>

```diff
diff --git a/test/replication-luatest/gh_6033_box_promote_demote_test.lua b/test/replication-luatest/gh_6033_box_promote_demote_test.lua
index 81523de47..d3a48a046 100644
--- a/test/replication-luatest/gh_6033_box_promote_demote_test.lua
+++ b/test/replication-luatest/gh_6033_box_promote_demote_test.lua
@@ -198,6 +198,7 @@ g_common.test_raft_leader_promote = function(g)
     -- Promote server, but get stuck while writing PROMOTE
     -- (become RAFT leader without obtaining synchro queue)
     wal_delay_start(g.server_1, 0)
+    local term = g.server_1:election_term()
     local f = promote_start(g.server_1)
     play_wal_until_synchro_queue_is_busy(g.server_1)
     g.server_1:wait_election_leader()
@@ -210,6 +211,7 @@ g_common.test_raft_leader_promote = function(g)

     wal_delay_end(g.server_1)
     fiber_join(g.server_1, f)
+    g.server_1:wait_synchro_queue_term(term + 1)
     wait_sync(g.cluster.servers)

     box_cfg_update({g.server_1}, {election_mode = 'off'})
```
</details>

**Review by sergepetrenko — APPROVED** [review]
Thanks for the fixes!
Good job on going through all the reviews.
LGTM.

**Review by Gerold103 — APPROVED** [review]
Thanks for the patch!
> As for box_promote_qsync coverage - I didn't find an easy way to test those lines. I can create new issues for testing box_promote_qsync and box_wait_limbo_acked.

yes, please.

**Comment by grafin** [comment]
Follow-up issues:
box_promote_qsync coverage: #7317 
box_wait_limbo_acked coverage: #7318

**Comment by kyukhin** [comment]
Backported to 2.10.
