### PR TITLE
config: fail startup on credential errors

### LINKED ISSUE #9689: Unexpected config status during startup and unexpected config status after applying credentials
Currently it is possible to get `check_errors` status during startup:
Config:
```yaml
credentials:
  users:
    guest:
      roles: [super]
    someone:
      privileges:
      - permissions: [execute]
        spaces: [first]

log:
  level: 0

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
```
Reproducer:
```yaml
started
tarantool> require('config'):info()
---
- status: check_errors
  meta: []
  alerts:
  - type: error
    message: 'credentials.apply: box.schema.user.grant("someone", "execute", "space",
      "first") failed: Unsupported space privilege ''execute'''
    timestamp: 2024-02-14T13:42:59.431903+0300
  - type: warn
    message: box.schema.user.grant("someone", "execute", "space", "first") has failed
      because either the object has not been created yet, or the privilege write has
      failed (separate alert reported)
    timestamp: 2024-02-14T13:42:59.432832+0300
...

```

It is also possible to get the status `ready` while simultaneously having pending alerts:
Config:
```yaml
credentials:
  users:
    guest:
      roles: [super]
    someone:
      privileges:
      - permissions: [read]
        spaces: [first, second]

log:
  level: 0

iproto:
  listen:
  - uri: 'unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001: {}
```
Reproducer:
```yaml
started
tarantool> require('config'):info()
---
- status: check_warnings
  meta: []
  alerts:
  - type: warn
    message: box.schema.user.grant("someone", "read", "space", "second") has failed
      because either the object has not been created yet, or the privilege write has
      failed (separate alert reported)
    timestamp: 2024-02-14T13:37:53.375946+0300
  - type: warn
    message: box.schema.user.grant("someone", "read", "space", "first") has failed
      because either the object has not been created yet, or the privilege write has
      failed (separate alert reported)
    timestamp: 2024-02-14T13:37:53.375959+0300
...

tarantool> _ = box.schema.space.create('first')
---
...

tarantool> require('config'):info()
---
- status: ready
  meta: []
  alerts:
  - type: warn
    message: box.schema.user.grant("someone", "read", "space", "second") has failed
      because either the object has not been created yet, or the privilege write has
      failed (separate alert reported)
    timestamp: 2024-02-14T13:37:58.733120+0300
...
```

### PR DESCRIPTION
**Pull request by mandesero**
This patch fixes the issue where configuration-driven credential errors did not stop startup. Now the first alert from the credential applier is returned to the blocking sync caller, so an invalid grant aborts startup as expected.

Closes #9689

NO_DOC=bugfix
NO_CHANGELOG=bugfix

### CODE REVIEW

File: src/box/lua/config/applier/credentials.lua [hunk 1]
```diff
@@ -1006,13 +1015,17 @@ local function sync_credentials_worker()
     while true do
         local obj_to_sync = sync_tasks:get()
 
-        local _, err = pcall(sync_object, obj_to_sync)
+        local ok, err = pcall(sync_object, obj_to_sync)
 
         fiber.testcancel()
 
+        if ok and config._aboard:status() == 'check_errors' then
+            err = first_error_alert_message()
```
Comment (georgiy-belyanin) [inline src/box/lua/config/applier/credentials.lua:1023]: Minor: consider adding a check that there is at least one error.

```suggestion
            err = first_error_alert_message()
            assert(err ~= nil)
```

Or consider making a call `first_error_alert_message()` always return a value.

```lua
local function first_error_alert_message()
    assert(config._aboard:status() == 'check_errors')
    local alerts = config._aboard:alerts()
    for _, alert in ipairs(alerts) do
        if alert.type == 'error' then
            return alert.message
        end
    end
    assert(false)
end
```

Feel free to close & ignore.

File: src/box/lua/config/applier/credentials.lua [hunk 2]
```diff
@@ -1006,13 +1015,17 @@ local function sync_credentials_worker()
...
+        end
+
         if obj_to_sync.type == 'BLOCKING_FULL_SYNC' then
             wait_sync:put(err or 'Done')
-        elseif err then
+        elseif not ok and err then
```
Comment (georgiy-belyanin) [inline src/box/lua/config/applier/credentials.lua:1033]: Minor: probably, this lines deserves a comment now. Something like:
```lua
-- There are to possible cases when err is not nil:
-- * `ok = false` -- in that case an extra error log 
--   message should be issued.
-- * `ok = true` -- in that case the error has already
--   been reported as an alert.
```

File: src/box/lua/config/applier/credentials.lua (hunk 1 above)
Comment (mandesero) [reply src/box/lua/config/applier/credentials.lua:1023]: Good point, added.

File: src/box/lua/config/applier/credentials.lua (hunk 2 above)
Comment (mandesero) [reply src/box/lua/config/applier/credentials.lua:1033]: Ok, let's add this. Done.

Comment (georgiy-belyanin) [reply src/box/lua/config/applier/credentials.lua:1033]: There is an extra grave though :)

```lua
-- `ok == true``
```

Comment (mandesero) [reply src/box/lua/config/applier/credentials.lua:1033]: Oops :) fixed it
