### PR TITLE
replication: add early and graceful make_bootstrap_leader()

### LINKED ISSUE #10858: Allow to call box.ctl.make_bootstrap_leader() before box.cfg()
The `supervised` failover strategy doesn't allow to choose a bootstrap leader until `box.cfg()` is called. It is not very convenient: a user has to call `box.cfg()` in a fiber and has to place the `box.ctl.make_bootstrap_leader()` call afterwards. This way we need an additional code to couple the replicaset bootstrap leader determination logic with the `box.cfg()` call.

```yaml
# tarantool> box.ctl.make_bootstrap_leader()
---
- error: box.ctl.make_bootstrap_leader() does not support promoting this instance
    before box.cfg() is called
...
```

Next, we can't bootstrap a singleton replicaset (one that has just one instance) in this strategy unless it has iproto enabled (`box.cfg.listen`) and has itself in the upstreams (`box.cfg.replication`).

```yaml
# tarantool> box.cfg({bootstrap_strategy = 'supervised'})
<...>
<...> replication.cc:1513 E> ER_CFG: Incorrect value for option 'bootstrap_strategy': failed to connect to the bootstrap leader
<...> box.cc:5892 F> can't initialize storage: Incorrect value for option 'bootstrap_strategy': failed to connect to the bootstrap leader
```

It seems possible to overcome these contraints by using `auto` or `config` strategy to bootstrap a replicaset and switch to `supervised` afterwards, but it seems more convenient to handle these situations within the `supervised` strategy itself.

The proposal is to allow to call `box.ctl.make_boostrap_leader()` before `box.cfg()`, save the user's choice and bootstrap the replicaset on `box.cfg()` on the given instance. Later, when this or another instance calls `box.ctl.make_bootstrap_leader()`, discard the choice saved on the replicaset bootstrap.

Needed for #10857

### LINKED ISSUE #11272: replication: graceful bootstrap in the supervised bootstrap strategy
## Context

The `supervised` bootstrap strategy gives a user more control about the replicaset bootstrap process (and about joining new replicas) comparing to the default `auto` strategy.

For example, in the `auto` strategy:

* If one starts iproto listening port (using `box.cfg({listen = <...>})`) to receive commands from an external agent and make all the instances waiting the bootstrap leader (using `read_only = true` option), it is not possible to assign one of the instances as a bootstrap leader, because the next `box.cfg({read_only = true})` waits until the previous one is finished, but it still waits the bootstrap leader.
* The strategy requires a new replica to connect to all instances registered in `_cluster` to anticipate a situation, when different leaders assign the same ID to different new replicas. It is possible in the multi-master mode. Sometimes this check may raise an error, when everything is OK: there is a single master, but some stopped replica resides in `_cluster`. See details in #10857.
* However, if the initial configuration marks the instance as possible bootstrap leader (using `box.cfg({read_only = false})`), the instance connects to other peers first and checks, whether there is already a bootstrap leader. This is very convenient safety feature, prevents bootstrapping two separate databases due to a mistake or timing issues.

So, the `supervised` strategy allows to overcome limitations of the `auto` strategy, but, at the same time, there are safety measures in the `auto` strategy that would be convenient in the `supervised` strategy too.

## Proposal

Add an option to the `box.ctl.make_bootstrap_leader()` function:

```lua
box.ctl.make.bootstrap_leader({graceful = true})
```

The idea is that it checks a presence of a bootstrap leader across other peers first and, if there are no one, bootstraps the initial database on the current instance.

Strictly speaking:

* If there are no local database:
  * Start connecting to all the peers from `box.cfg.replication` (without waiting).
  * Wait for one of the three situations:
    * Found a peer with the bootstrap leader flag.
    * Connected to all the peers from `box.cfg.replication`, but there is no one with the bootstrap leader flag.
    * `box.cfg.replication_connect_timeout` is over.
  * If the bootstrap leader is found, go as a replica. Otherwise, assign itself as a bootstrap leader.
* If there is a local database, the call is no-op.

This feature should be useful to implement #10857.

### PR DESCRIPTION
**Pull request by Totktonada**
This patchset contains a few tightly coupled features.

## Early `box.ctl.make_bootstrap_leader()`

Now, it is allowed to call `box.ctl.make_bootstrap_leader()` before a first `box.cfg()` call to mark the instance as a bootstrap leader.

It works if `box.cfg({bootstrap_strategy = 'supervised'})` is set, ignored otherwise.

So, the following code is now possible:

```lua
box.ctl.make_bootstrap_leader()
box.cfg({
    bootstrap_strategy = 'supervised',
})
```

In earlier Tarantool version a user has to call `box.cfg()` in a separate fiber first and then call `box.ctl.make_bootstrap_leader()`.

Also, earlier Tarantool versions do not allow to bootstrap a database using the `'supervised'` bootstrap strategy if there are no upstreams configured (empty `box.cfg.replication`). It means that there were no way to bootstrap the database without iproto listening port configured (`box.cfg.listen`) except using another bootstrap strategy.

Now, the `'supervised'` bootstrap strategy let a user a full control over the replicaset bootstrapping process.

Fixes #10858

## `box.ctl.make_bootstrap_leader({graceful = true})`

The new option is added to the `box.ctl.make_bootstrap_leader()` call:

```lua
box.ctl.make_bootstrap_leader({graceful = true})
```

It checks a presence of a bootstrap leader across other peers first and, if there are no one, bootstraps the initial database on the current instance.

Strictly speaking:

* If there are no local database:
  * Start connecting to all the peers from `box.cfg.replication` (without waiting).
  * Wait for one of the three situations:
    * Found a peer with the bootstrap leader flag.
    * Connected to all the peers from `box.cfg.replication`, but there is no one with the bootstrap leader flag.
    * `box.cfg.replication_connect_timeout` is over.
  * If the bootstrap leader is found, go as a replica. Otherwise, assign itself as a bootstrap leader.
* If there is a local database, the call is no-op.

The motivating scenario is when we don't really know, whether the replicaset is already bootstrapped and want to bootstrap it from the given instance if not.

The new option doesn't give any protection in the situation, when the replicaset is not bootstrapped and two instances are simultaneously trying to gracefully bootstrap it.

Fixes #11272

## Allow to bootstrap in RO in the `supervised` bootstrap strategy

It allows to run `box.cfg({read_only = true})` on all the instances and wait for an external coordinator to choose one of the instances as the bootstrap leader:

```lua
box.ctl.make_bootstrap_leader({graceful = true})
box.cfg({read_only = false})
```

Needed for #10857

## Wait for bootstrap leader if there are no configured upstreams in the `supervised` bootstrap strategy

It allows to follow the same startup flow for multi-instance and single-instance replicasets:

```lua
box.cfg({
    bootstrap_strategy = 'supervised',
    replication = <...>, -- exists or not
})
```

Then via iproto or the admin console:

```lua
box.ctl.make_bootstrap_leader({graceful = true})
box.cfg({read_only = false})
```

Needed for #10857

### CODE REVIEW

File: src/box/box.cc [hunk 1]
```diff
@@ -5381,10 +5421,20 @@ bootstrap(bool *is_bootstrap_leader)
...
+		 *
+		 * Otherwise, find who is the bootstrap leader.
+		 */
+		if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED ||
+		    !am_i_bootstrap_leader) {
+			master = replicaset_find_join_master();
+			bootstrap_leader_uuid = master == NULL ? INSTANCE_UUID :
+								 master->uuid;
+			box_broadcast_ballot();
+		}
```
Comment (Totktonada) [inline src/box/box.cc:5437]: I'm not very confident about this part.

First of all, it seems that `replicaset_find_join_master` and underneath `replicaset_find_join_master_*` functions incapsulate all the related logic and I ruin this idea to some extent. However, it is attractive to make `am_i_bootstrap_leader` local for this compilation unit. This way it is easier to spot that it is needed just to pass some information from `box_make_bootstrap_leader` to `bootstrap`.

Next, it seems meaningful to wait till `replication_connect_timeout` or till all the upstreams are connected and verify, whether the remote peers have a database bootstrapped. OTOH, `replicaset_find_join_master` doesn't do it. At least, if there is another instance that advertizes itself as a bootstrap leader, we can choose our own applier object anyway. And we only look for the bootstrap leader flag, not whether the database is bootstraped.

So, it seems that `replicaset_find_join_master` is not about such safety checks. If we decide to add them, they're likely will be separated from the master finding procedure.

Taking all that, I've implemented in the given way. However, I'm not very in context about this code and if I missed something, please, let me know.

File: src/box/box.cc [hunk 2]
```diff
@@ -205,6 +205,20 @@ struct event *box_on_recovery_state_event;
...
+ *
+ * Has an effect only in the supervised bootstrap strategy.
+ *
+ * Has effect only on bootstrap, ignored afterwards. This way we
+ * don't have to clear the flag.
+ *
+ * Use bootstrap_leader_uuid to judge about an actual bootstrap
+ * leader.
+ */
+static bool am_i_bootstrap_leader;
```
Comment (grafin) [inline src/box/box.cc:220]: nit: as always, I have doubts about the naming) something like `is_forced_bootstrap_leader` or `is_configured_bootstrap_leader` sounds better to me, but is see that in https://github.com/tarantool/tarantool/blob/265c74763843f4a71613d592a884536c848f3b4d/src/box/lua/config/applier/box_cfg.lua#L747 you already used this name, so I guess I'm fine with it.

File: src/box/box.cc (hunk 1 above)
Comment (grafin) [reply src/box/box.cc:5437]: I'm not fully in context, but you removed those lines:
```c
		master = replicaset_find_join_master();
		bootstrap_leader_uuid = master == NULL ? INSTANCE_UUID :
							 master->uuid;
		box_broadcast_ballot();
```
why didn't you move them under an `else` statement?

File: src/box/box.cc (hunk 2 above)
Comment (Totktonada) [reply src/box/box.cc:220]: I spin around naming for a while, but I didn't find anything better, to be honest.

'configured' sounds like something from the `box.cfg` table, but it is from a `box.ctl.<...>()` call.

'Forced' seems OK, though. OTOH, it doesn't look more forced than when we call `make_bootstrap_leader` during `box.cfg()`.

Maybe it is better to highlight that it is a kind of a message from `make_bootstrap_leader()`? `make_bootstrap_leader_result`, for example?

I would hear opinions here :)

File: src/box/box.cc (hunk 1 above)
Comment (Totktonada) [reply src/box/box.cc:5437]: It seems, you were confused by the identation change. The `-b` diff looks so:

```diff
@@ -5381,10 +5421,20 @@ bootstrap(bool *is_bootstrap_leader)

        while (true) {
                box_restart_replication();
+               /*
+                * If the bootstrap strategy is 'supervised' and
+                * it is known that the given instance is the
+                * bootstrap leader, just bootstrap the database.
+                *
+                * Otherwise, find who is the bootstrap leader.
+                */
+               if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED ||
+                   !am_i_bootstrap_leader) {
                        master = replicaset_find_join_master();
                        bootstrap_leader_uuid = master == NULL ? INSTANCE_UUID :
                                                                 master->uuid;
                        box_broadcast_ballot();
+               }

                if (master == NULL ||
                    tt_uuid_is_equal(&master->uuid, &INSTANCE_UUID)) {
```

File: src/box/box.cc (hunk 2 above)
Comment (grafin) [reply src/box/box.cc:220]: possibly `is_made_bootstrap_leader` or `is_user_made_bootstrap_leader`?

File: src/box/box.cc (hunk 1 above)
Comment (grafin) [reply src/box/box.cc:5437]: Yeap, you're correct)

File: test/replication-luatest/bootstrap_strategy_test.lua [hunk 3]
```diff
@@ -774,3 +779,87 @@ g_supervised.test_no_bootstrap_without_replication = function(cg)
...
+    t.assert_equals(cg.server2:get_instance_id(), 1,
+                    'Server 2 is the bootstrap leader')
+    cg.server2:exec(function()
+        local tup = box.space._schema:get{'bootstrap_leader_uuid'}
+        t.assert(tup ~= nil, 'Bootstrap leader uuid is persisted')
+        t.assert_equals(tup[2], box.info.uuid,
+                        'Bootstrap leader uuid is correct')
+    end)
+    t.helpers.retrying({}, cg.server1.assert_follows_upstream, cg.server1, 1)
+end
```
Comment (Serpentian) [inline test/replication-luatest/bootstrap_strategy_test.lua:865]: I suppose, we also need a test, where several `box.ctl.make_bootstrap_leader` are called before box.cfg. But let's firstly discuss, what the expected behavior in such case

File: src/box/box.cc (hunk 1 above)
Comment (Serpentian) [reply src/box/box.cc:5437]: > Next, it seems meaningful to wait till replication_connect_timeout or till all the upstreams are connected

But we already do that in `box_restart_replication` right before searching for `bootstrap_leader`.

> verify, whether the remote peers have a database bootstrapped

Why do we want to do that? If replica advertises itself as bootstrap leader in ballot, we'll bootstrap from it.

File: changelogs/unreleased/early-make-bootstrap-leader.md [hunk 4]
```diff
@@ -0,0 +1,4 @@
+## feature/replication
+
+* Allowed to call `box.ctl.make_bootstrap_leader()` before a first `box.cfg()`
```
Comment (lenkis) [inline changelogs/unreleased/early-make-bootstrap-leader.md:3]:
```suggestion
* Allowed to call `box.ctl.make_bootstrap_leader()` before the first `box.cfg()`
```

**Review by lenkis — APPROVED** [review]

File: src/box/box.cc (hunk 1 above)
Comment (Totktonada) [reply src/box/box.cc:5437]: > > Next, it seems meaningful to wait till replication_connect_timeout or till all the upstreams are connected
>
> But we already do that in `box_restart_replication` right before searching for `bootstrap_leader`.

It seems, we don't (in this bootstrap strategy).

https://github.com/tarantool/tarantool/blob/89cd7f43fd37e7afa459bf1a8f0e5159085c73ae/src/box/replication.cc#L1010-L1015

> > verify, whether the remote peers have a database bootstrapped
>
> Why do we want to do that? If replica advertises itself as bootstrap leader in ballot, we'll bootstrap from it.

As a safety measure. For example, look on this logic:

https://github.com/tarantool/tarantool/blob/89cd7f43fd37e7afa459bf1a8f0e5159085c73ae/src/box/lua/config/applier/box_cfg.lua#L717-L784

In the `auto` bootstrap strategy we just make the instance RW for a short period of time. In the `supervised` strategy without the safety checks we initialize a new replicaset.

I think that we can pass it over here, but I would return to these checks later.

File: src/box/box.cc [hunk 5]
```diff
@@ -5381,10 +5421,20 @@ bootstrap(bool *is_bootstrap_leader)
...
-							 master->uuid;
-		box_broadcast_ballot();
+		/*
+		 * If the bootstrap strategy is 'supervised' and
+		 * it is known that the given instance is the
+		 * bootstrap leader, just bootstrap the database.
+		 *
+		 * Otherwise, find who is the bootstrap leader.
+		 */
+		if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED ||
```
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:5431]: > If I have two instances, where I called box.ctl.make_bootstrap_leader() before box.cfg, they won't be able to join with each other, since each of them supposes itself as bootstrap leader, they will be bootstrapped independently and then fail to join with ER_REPLICASET_UUID_MISMATCH. The question here, are we ok with this behavior? @sergepetrenko @Totktonada

This matches current `make_bootstrap_leader()` behavior. The only difference is that now you may call `box.ctl.make_bootstrap_leader()` before issuing `box.cfg`. But otherwise the user can shoot off his legs even now: nothing prevents him from issuing `make_bootstrap_leader()` on both nodes while they are still trying to connect to each other.

[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc:5431]: > they will be bootstrapped independently and then fail to join with `ER_REPLICASET_UUID_MISMATCH`. The question here, are we ok with this behavior?

I'm not really OK, but OK as a temporary state.

I would like to have some safety checks, but since we have no them now (in this bootstrap strategy), I think it is OK to go step-by-step.

> @Totktonada Did you consider introducing a function in config module, which will save, whether we're supposed to be a bootstrap leader and then call `make_bootstrap_leader()` right after launching box.cfg in a separate fiber? 

Sure. I don't like how much logic is coupled with a certain point in the code, where we call `box.cfg()`. Letting box remember the choice allows to write the same logic simpler.

But it is not the only reason to propose this patch. I also can't bootstrap a single instance replicaset without an iproto port in the supervised strategy and need to switch between config/supervised depending on some conditions.

To sum up: I don't like how complicated/fragile config's code would be without this change. I'm afraid that I'll miss more scenarios in attempting to work around current supervised strategy constraints.

File: test/replication-luatest/bootstrap_strategy_test.lua (hunk 3 above)
Comment (Totktonada) [reply test/replication-luatest/bootstrap_strategy_test.lua:865]: Judging from Sergey's answer in the above thread, it seems that we expect `ER_REPLICASET_UUID_MISMATCH` for now.

I think that the best course is to verify this behavior and link an issue with proposal to add the safety checks. I'll create the issue.

@Serpentian @sergepetrenko Are you OK?

File: src/box/box.cc (hunk 1 above)
Comment (sergepetrenko) [reply src/box/box.cc:5437]: @Totktonada 
It seems you don't need this particular change at all.
I'd rather put the `am_i_bootstrap_leader` logic into `replicaset_find_join_master`. Besides, there's a designated check `replicaset_find_join_master_supervised`. It feels logical to check `am_i_bootstrap_leader` there, rather than in the calling code.

So, I suggest the following incremental diff:
```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index a198d6587f..ec0af2f8e1 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -5421,20 +5421,10 @@ bootstrap(bool *is_bootstrap_leader)
 
        while (true) {
                box_restart_replication();
-               /*
-                * If the bootstrap strategy is 'supervised' and
-                * it is known that the given instance is the
-                * bootstrap leader, just bootstrap the database.
-                *
-                * Otherwise, find who is the bootstrap leader.
-                */
-               if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED ||
-                   !am_i_bootstrap_leader) {
-                       master = replicaset_find_join_master();
-                       bootstrap_leader_uuid = master == NULL ? INSTANCE_UUID :
-                                                                master->uuid;
-                       box_broadcast_ballot();
-               }
+               master = replicaset_find_join_master();
+               bootstrap_leader_uuid = master == NULL ? INSTANCE_UUID :
+                                                        master->uuid;
+               box_broadcast_ballot();
 
                if (master == NULL ||
                    tt_uuid_is_equal(&master->uuid, &INSTANCE_UUID)) {
diff --git a/src/box/replication.cc b/src/box/replication.cc
index ac4d8cbe3e..f4cb7518fa 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1509,7 +1509,7 @@ replicaset_find_join_master_supervised(void)
                if (applier_is_bootstrap_leader(applier))
                        leader = replica;
        }
-       if (leader == NULL) {
+       if (leader == NULL && !am_i_bootstrap_leader) {
                tnt_raise(ClientError, ER_CFG, "bootstrap_strategy",
                          "failed to connect to the bootstrap leader");
        }
```

File: src/box/box.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (Serpentian) [reply src/box/box.cc:5431]: > This matches current make_bootstrap_leader() behavior. The only difference is that now you may call box.ctl.make_bootstrap_leader() before issuing box.cfg. But otherwise the user can shoot off his legs even now: nothing prevents him from issuing make_bootstrap_leader() on both nodes while they are still trying to connect to each other.

Now they must be called almost simultaneously for that to happen. When it's done before box.cfg it so much easier to shoot off the legs. Moreover, user don't have any way to remove that `am_i_bootstrap_leader` flag, he cannot check, whether the instance will become bootstrap_leader before box.cfg.

We may consider adding internal function for now, which will set this flag. But If everyone is ok with how it works now, then I don't mind.

@Totktonada, can we consider logging, when `box.ctl.make_bootstrap_leader` is called? It won't be very fun to debug on prod, when some failover calls `make_bootstrap_leader` on several instances.

File: src/box/box.cc (hunk 1 above)
Comment (Totktonada) [reply src/box/box.cc:5437]: @sergepetrenko Are you agree with Nikita? Should I incorporate the logic into `replicaset_find_join_master`?

File: src/box/box.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc:5431]: > @Totktonada, can we consider logging, when `box.ctl.make_bootstrap_leader` is called? It won't be very fun to debug on prod, when some failover calls `make_bootstrap_leader` on several instances.

I like this idea. Will add.

File: test/replication-luatest/bootstrap_strategy_test.lua (hunk 3 above)
Comment (Serpentian) [reply test/replication-luatest/bootstrap_strategy_test.lua:865]: I'm ok

File: src/box/box.cc (hunk 2 above)
Comment (sergepetrenko) [reply src/box/box.cc:220]: > Let's just make is_bootsrap_leader not an argument in bootstrap() but a variable in replication.cc and set it from box.cc. This way replicaset_find_join_master will return NULL, when is_bootstrap_leader is set. No changes in bootstrap() will be needed.

Agreed.
Speaking about the name, it should be less general then. I think `is_made_bootstrap_leader` is a good one.

Probably `is_supervised_bootstrap_leader`?

Comment (Totktonada) [reply src/box/box.cc:220]: > Let's just make `is_bootsrap_leader` not an argument in `bootstrap()` but a variable in `replication.cc` and set it from `box.cc`.

If I understood you correctly, you propose to set it from `make_bootstrap_leader()` as well. I would prefer to don't do that, at least because we should take it into account only in the supervised bootstrap strategy. This way, we need separate 'leadership requested' and 'leadership is in effect' variables. In future, if we add some checks against two bootstrap leaders, there may be more situations, when the leadership request is refused.

Taking into account that I anyway need a separate `is_supervised_bootstrap_leader` variable, I wouldn't touch `is_bootsrap_leader`.

I like the `is_supervised_bootstrap_leader` name more than others. At least it explicitly states that it is related to the supervised bootstrap strategy.

I'm going to rename the variable, move it to `replication.{h,cc}`, take into account in `replicaset_find_join_master_supervised`.

File: src/box/box.cc [hunk 6]
```diff
@@ -2186,10 +2200,19 @@ int
...
+		 * the bootstrap leader UUID at this moment,
+		 * because there is no instance UUID yet.
+		 *
+		 * Postpone this action till bootstrap. The
+		 * bootstrap() function assigns the bootstrap
+		 * leader UUID to the UUID of this instance on its
+		 * own if the flag is set (and the bootstrap
+		 * strategy is 'supervised')
+		 */
+		am_i_bootstrap_leader = true;
```
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc:2214]: TBH, I think that keeping it consistent is not a goal and extra code to do so wouldn't make things simpler or better. The goal is to pass some information from `make_bootstrap_leader` to `bootstrap`.

But if we move the check to `replicaset_find_join_master_supervised`, it seems that we should clean it up or keep actual.

OK, I'll look around the relevant code and try to keep things consistent.

File: src/box/box.cc (hunk 2 above)
Comment (Totktonada) [reply src/box/box.cc:220]: OTOH, if I anyway trying to keep the flag consistent, maybe it has sense to coalesce it with `is_bootsrap_leader`.

Will look around the relevant code, no sure.

File: src/box/box.cc (hunk 1 above)
Comment (Totktonada) [reply src/box/box.cc]: I've pushed an intermediate update that reflects everything we discussed except that I'll add logs a bit later today.

File: src/box/box.cc (hunk 2 above)
Comment (Totktonada) [reply src/box/box.cc]: Renamed the flag to `is_supervised_bootstrap_leader`. I'm afraid of merging it with `is_bootstrap_leader` and more consistency questions you would ask me if I do :)

File: src/box/box.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc]: Added a test for `ER_REPLICASET_UUID_MISMATCH`. Logs are to be added (later today).

[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc]: Now I handle it in `replicaset_find_join_master_supervised`.

File: test/replication-luatest/bootstrap_strategy_test.lua (hunk 3 above)
Comment (Totktonada) [reply test/replication-luatest/bootstrap_strategy_test.lua:866]: Added `test_early_leader_several_leaders`, please, take a look.

I also decided to refuse to look into applier state in `replicaset_find_join_master_supervised` if the given instance is assigned as a bootstrap leader, because even in local testing it catches ~3% of situations and adds instability to testing. These 3% (or even less in real network conditions) don't look valuable for a user.

If we need the checks of this kind, we should guarantee some wait interval, I think.

Now the function looks as follows.

```c
/**
 * Out of all the replicas find the one which was promoted via
 * box.ctl.make_bootstrap_leader()
 */
static struct replica *
replicaset_find_join_master_supervised(void)
{
        /*
         * If we're known as a bootstrap leader, just bootstrap
         * the database.
         *
         * Unlike the 'auto' bootstrap strategy, the 'supervised'
         * one has no safety checks with waiting for ballots from
         * other replicaset members.
         *
         * NB: It is possible to run the cycle below first and
         * verify other members status known at this moment.
         * However, since we don't wait for connecting to all the
         * instances, it has a low chance to catch a problem.
         * As result, it would just make the result of calling
         * this function less predictable without visible gains
         * for a user.
         */
        if (is_supervised_bootstrap_leader)
                return NULL;

        struct replica *leader = NULL;
        replicaset_foreach(replica) {
                struct applier *applier = replica->applier;
                if (applier == NULL)
                        continue;
                if (applier_is_bootstrap_leader(applier))
                        leader = replica;
        }
        if (leader == NULL) {
                tnt_raise(ClientError, ER_CFG, "bootstrap_strategy",
                          "failed to connect to the bootstrap leader");
        }
        return leader;
}
```

File: changelogs/unreleased/early-make-bootstrap-leader.md (hunk 4 above)
Comment (Totktonada) [reply changelogs/unreleased/early-make-bootstrap-leader.md]: Pushed.

File: src/box/box.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc]: I've pushed my attempt to keep `is_supervised_bootstrap_leader` and `bootstrap_leader_uuid` consistent. Not very confident here, to be honest, and would appreciate another glance from you.

File: src/box/box.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc]: Added the logs in the second commit.

I didn't bother about other bootstrap strategies, only adjusted code that seems relevant to the supervised strategy. I hope it is enough in context of this PR.

File: src/box/box.cc (hunk 1 above)
Comment (Totktonada) [reply src/box/box.cc]: > except that I'll add logs a bit later today.

Done.

File: src/box/replication.cc [hunk 7]
```diff
@@ -996,6 +997,12 @@ bootstrap_leader_is_connected(struct applier **appliers, int count)
 			return true;
 		}
 	}
+	/*
```
Comment (Serpentian) [inline src/box/replication.cc:1000]: Nit: we probably don't want to check appliers at all in `supervised`. The result will anyway depend on `is_supervised_bootstrap_leader`. Should be moved to the beginning of the function

File: changelogs/unreleased/early-make-bootstrap-leader.md [hunk 8]
```diff
@@ -0,0 +1,4 @@
+## feature/replication
```
Comment (Serpentian) [inline changelogs/unreleased/early-make-bootstrap-leader.md:1]: Nit: let's warn in the Doc request, that several `box.cfg.make_bootstrap_leader()` will lead to JOIN failure

File: src/box/box.cc [hunk 9]
```diff
@@ -2213,6 +2214,8 @@ box_make_bootstrap_leader(void)
 	} else {
 		bootstrap_leader_uuid = INSTANCE_UUID;
 		is_supervised_bootstrap_leader = true;
+		say_info("instance %s (this one) is assigned as a bootstrap "
```
Comment (Serpentian) [inline src/box/box.cc:2217]: No need for this message. It's duplicated, since in `bootstrap_master -> box_populate_schema_space -> box_set_bootstrap_leader_record` it'll be written to `_schema` and the message will be logged from the `on_commit` trigger

File: src/box/alter.cc [hunk 10]
```diff
@@ -4299,6 +4299,12 @@ on_commit_schema_set_bootstrap_leader_uuid(struct trigger *trigger, void *event)
 	struct tt_uuid *uuid = (struct tt_uuid *)trigger->data;
 	bootstrap_leader_uuid = *uuid;
 	is_supervised_bootstrap_leader = tt_uuid_is_equal(uuid, &INSTANCE_UUID);
+	if (is_supervised_bootstrap_leader)
```
Comment (Serpentian) [inline src/box/alter.cc:4302]: I'd rather not make any condition here. `instance %s is assigned as a bootstrap leader` is enough, IMHO. We never say, whether UUID is our own or not in other log messages

File: src/box/box.cc [hunk 11]
```diff
@@ -2208,6 +2212,7 @@ box_make_bootstrap_leader(void)
 		return box_set_bootstrap_leader_record();
 	} else {
 		bootstrap_leader_uuid = INSTANCE_UUID;
+		is_supervised_bootstrap_leader = true;
```
Comment (Serpentian) [inline src/box/box.cc:2216]: The same comment, as in message logging. AFAICS, we don't need that

File: src/box/replication.cc (hunk 7 above)
Comment (Totktonada) [reply src/box/replication.cc]: Seems valid. Moved the check:

```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index cdbe424a95..627e749651 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -990,6 +990,14 @@ applier_is_bootstrap_leader(const struct applier *applier)
 static bool
 bootstrap_leader_is_connected(struct applier **appliers, int count)
 {
+       /*
+        * In the supervised strategy it is possible that we know
+        * locally that the given instance is a bootstrap leader.
+        */
+       if (bootstrap_strategy == BOOTSTRAP_STRATEGY_SUPERVISED &&
+           is_supervised_bootstrap_leader)
+               return true;
+
        for (int i = 0; i < count; i++) {
                struct applier *applier = appliers[i];
                if (applier->state == APPLIER_CONNECTED &&
@@ -997,12 +1005,6 @@ bootstrap_leader_is_connected(struct applier **appliers, int count)
                        return true;
                }
        }
-       /*
-        * In the supervised strategy it is possible that we know
-        * locally that the given instance is a bootstrap leader.
-        */
-       if (bootstrap_strategy == BOOTSTRAP_STRATEGY_SUPERVISED)
-               return is_supervised_bootstrap_leader;
        return false;
 }
```

File: src/box/box.cc (hunk 9 above)
Comment (Totktonada) [reply src/box/box.cc]: Agree, removed.

File: src/box/alter.cc (hunk 10 above)
Comment (Totktonada) [reply src/box/alter.cc]: OK, changed:

```diff
diff --git a/src/box/alter.cc b/src/box/alter.cc
index 9eb59852a9..6db60115e2 100644
--- a/src/box/alter.cc
+++ b/src/box/alter.cc
@@ -4299,12 +4299,8 @@ on_commit_schema_set_bootstrap_leader_uuid(struct trigger *trigger, void *event)
 	struct tt_uuid *uuid = (struct tt_uuid *)trigger->data;
 	bootstrap_leader_uuid = *uuid;
 	is_supervised_bootstrap_leader = tt_uuid_is_equal(uuid, &INSTANCE_UUID);
-	if (is_supervised_bootstrap_leader)
-		say_info("instance %s (this one) is assigned as a bootstrap "
-			 "leader", tt_uuid_str(uuid));
-	else
-		say_info("instance %s is assigned as a bootstrap leader",
-			 tt_uuid_str(uuid));
+	say_info("instance %s is assigned as a bootstrap leader",
+		 tt_uuid_str(uuid));
 	box_broadcast_ballot();
 	return 0;
 }
diff --git a/test/replication-luatest/bootstrap_strategy_test.lua b/test/replication-luatest/bootstrap_strategy_test.lua
index 7ac56f12d3..1a510a42e0 100644
--- a/test/replication-luatest/bootstrap_strategy_test.lua
+++ b/test/replication-luatest/bootstrap_strategy_test.lua
@@ -871,21 +871,8 @@ g_supervised.test_early_leader_with_replica = function(cg)
     end)
     t.helpers.retrying({}, cg.server1.assert_follows_upstream, cg.server1, 1)
 
-    -- There are three related log messages:
-    --
-    -- I> this instance is assigned as a bootstrap leader
-    -- I> instance <uuid> (this one) is assigned as a bootstrap leader
-    -- I> instance <uuid> is assigned as a bootstrap leader
-    --
-    -- The first one is issued before the logger is configured, so
-    -- goes to stderr. As far, as I know, luatest has no API to
-    -- catch it.
-    --
-    -- Two others are verified below.
-
     -- Verify a log message on a bootstrap leader.
-    local exp_msg = 'instance [0-9a-f-]+ %(this one%) is assigned as a ' ..
-        'bootstrap leader'
+    local exp_msg = 'instance [0-9a-f-]+ is assigned as a bootstrap leader'
     local found = grep_log(cg.server2, exp_msg)
     t.assert(found)
     t.assert_str_contains(found, leader_uuid)
```

File: src/box/box.cc (hunk 11 above)
Comment (Totktonada) [reply src/box/box.cc]: OK, removed and things seems working, but I'm a bit afraid that there is a point, when `bootstrap_leader_uuid` is not consistent with `is_supervised_bootstrap_leader`. That's how I described this contraint:

```c
/**
 * Whether the given instance is configured to make bootstrap of
 * the replicaset.
 *
 * Has an effect only in the supervised bootstrap strategy.
 *
 * This flag have to be consistent with bootstrap_leader_uuid
 * except the following cases:
 *
 * - INSTANCE_UUID is zero UUID
 * - the bootstrap strategy is not 'supervised'
 */
extern bool is_supervised_bootstrap_leader;
```

File: changelogs/unreleased/early-make-bootstrap-leader.md (hunk 8 above)
Comment (Totktonada) [reply changelogs/unreleased/early-make-bootstrap-leader.md:1]: Ouch, missed in this push. Will do now.

File: src/box/box.cc (hunk 11 above)
Comment (Serpentian) [reply src/box/box.cc]: > when bootstrap_leader_uuid is not consistent with is_supervised_bootstrap_leader

I was wrong. Not only the flag is not consistent with `bootstrap_leader_uuid`, but it's also looks like that it's not guaranteed, that we become a bootsrap leader, since `replicaset_find_join_master` may return another instance, not NULL or ourselves (especially, when applier to the current instance doesn't exist), `is_supervised_bootstrap_leader` will be `false` at that point.

The tests are stable, since this situation is not covered: we have only the test before the `box.cfg` but not during it (as it's done in `test_bootstrap`, but there only one `make_bootstrap_leader` is called). I won't insist on adding this test, since it seems it will be difficult to stabilize.

However, let's revert that change, flag should be set here. Sorry

**Review by Serpentian — APPROVED** [review]
Let's resolve the last comment and we're good to go. Thank you for the patch!

File: src/box/box.cc (hunk 11 above)
Comment (Totktonada) [reply src/box/box.cc:2216]: Thank you for another glance!

I've tried to create a test case and found that it actually depends on an exact point of time, when we call `box.ctl.make_bootstrap_leader()` via console.

It mostly fails before the update, but passes 3/4 times afterwards.

I'll not add it into the pull request (don't know how to stabilize), but here it is:

<details>
<summary><code>test_several_leaders</code></summary>

```lua
g_supervised.before_test('test_several_leaders', function(cg)
    cg.replica_set = replica_set:new{}
    cg.box_cfg_1 = {
        bootstrap_strategy = 'supervised',
        -- Has only itself in upstreams and can bootstrap on its
        -- own.
        replication = {
            server.build_listen_uri('server1', cg.replica_set.id),
        },
        replication_timeout = 0.1,
    }
    cg.box_cfg_2 = {
        bootstrap_strategy = 'supervised',
        -- Has no itself in upstreams, but has another instance
        -- that advertises itself as a bootstrap leader.
        --
        -- The expectation is that server2 anyway bootstraps its
        -- own database, because box.ctl.make_bootstrap_leader()
        -- is called before box.cfg().
        replication = {
            server.build_listen_uri('server1', cg.replica_set.id),
        },
        replication_timeout = 0.1,
    }
    for i = 1, 2 do
        local alias = 'server' .. i
        cg[alias] = cg.replica_set:build_and_add_server{
            alias = alias,
            box_cfg = cg['box_cfg_' .. i],
        }
        cg['admin' .. i] = fio.pathjoin(cg[alias].workdir, 'server.admin')
        local run_before_cfg = string.format([[
            local console = require('console')
            console.listen('unix/:%s')
        ]], cg['admin' .. i])
        cg[alias].env.TARANTOOL_RUN_BEFORE_BOX_CFG = run_before_cfg
    end
end)

-- XXX
g_supervised.test_several_leaders = function(cg)
    cg.server1:start({wait_until_ready = false})
    t.helpers.retrying({}, make_bootstrap_leader_initial, cg.admin1)

    cg.server2:start({wait_until_ready = false})
    t.helpers.retrying({}, make_bootstrap_leader_initial, cg.admin2)

    local query = 'ER_REPLICASET_UUID_MISMATCH'
    t.helpers.retrying({}, function()
        local found = grep_log(cg.server2, query)
        t.assert(found, ('Found %s'):format(query))
    end)
end
```
</details>

Comment (Serpentian) [reply src/box/box.cc:2216]: Here's the stable version. Note, that in your version `box_cfg_1.replication` is incorrect.

<details><summary>Details</summary>
<p>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index f4761f283f..f15df94f42 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -5386,6 +5386,7 @@ bootstrap(bool *is_bootstrap_leader)
 	bool say_once = false;
 
 	while (true) {
+		ERROR_INJECT_YIELD(ERRINJ_BOOTSTRAP_DELAY);
 		box_restart_replication();
 		master = replicaset_find_join_master();
 		bootstrap_leader_uuid = master == NULL ? INSTANCE_UUID :
diff --git a/src/lib/core/errinj.h b/src/lib/core/errinj.h
index b2b8ffa9e2..39ab38c10a 100644
--- a/src/lib/core/errinj.h
+++ b/src/lib/core/errinj.h
@@ -79,6 +79,7 @@ struct errinj {
 	_(ERRINJ_APPLIER_SLOW_ACK, ERRINJ_BOOL, {.bparam = false}) \
 	_(ERRINJ_APPLIER_STOP_DELAY, ERRINJ_BOOL, {.bparam = false}) \
 	_(ERRINJ_APPLIER_SUBSCRIBE_DELAY, ERRINJ_BOOL, {.bparam = false}) \
+	_(ERRINJ_BOOTSTRAP_DELAY, ERRINJ_BOOL, {.bparam = true}) \
 	_(ERRINJ_BUILD_INDEX, ERRINJ_INT, {.iparam = -1}) \
 	_(ERRINJ_BUILD_INDEX_DELAY, ERRINJ_BOOL, {.bparam = false}) \
 	_(ERRINJ_BUILD_INDEX_DISABLE_YIELD, ERRINJ_BOOL, {.bparam = false}) \
diff --git a/test/replication-luatest/bootstrap_strategy_test.lua b/test/replication-luatest/bootstrap_strategy_test.lua
index 1a510a42e0..a63f850101 100644
--- a/test/replication-luatest/bootstrap_strategy_test.lua
+++ b/test/replication-luatest/bootstrap_strategy_test.lua
@@ -539,18 +539,22 @@ local g_supervised = t.group('gh-8509-bootstrap-strategy-supervised')
 local server2_admin
 local SOCKET_TIMEOUT = 5
 
-local function make_bootstrap_leader_initial(sockname)
+local function make_socket_exec(sockname, command, resp)
     local sock, err = socket.tcp_connect('unix/', sockname)
     t.assert_equals(err, nil, 'Connection successful')
     local greeting = sock:read(128, SOCKET_TIMEOUT)
     t.assert_str_contains(greeting, 'Tarantool', 'Connected to console')
     t.assert_str_contains(greeting, 'Lua console', 'Connected to console')
-    sock:write('box.ctl.make_bootstrap_leader()\n', SOCKET_TIMEOUT)
+    sock:write(command, SOCKET_TIMEOUT)
     local response = sock:read(8, SOCKET_TIMEOUT)
-    t.assert_equals(response, '---\n...\n', 'The call succeeded')
+    t.assert_equals(response, resp, 'The call succeeded')
     sock:close()
 end
 
+local function make_bootstrap_leader_initial(sockname)
+    make_socket_exec(sockname, 'box.ctl.make_bootstrap_leader()\n', '---\n...\n')
+end
+
 g_supervised.after_each(function(cg)
     cg.replica_set:drop()
 end)
@@ -889,24 +893,34 @@ g_supervised.before_test('test_early_leader_several_leaders', function(cg)
     cg.box_cfg = {
         bootstrap_strategy = 'supervised',
         replication = {
-            server.build_listen_uri('server1', cg.replica_set.id),
             server.build_listen_uri('server2', cg.replica_set.id),
         },
         replication_timeout = 0.1,
     }
-    for i = 1, 2 do
-        local alias = 'server' .. i
-        cg[alias] = cg.replica_set:build_and_add_server{
-            alias = alias,
-            box_cfg = cg.box_cfg,
-            -- Both instances advertise itself as bootstrap
-            -- leaders.
-            env = {
-                ['TARANTOOL_RUN_BEFORE_BOX_CFG'] =
-                    'box.ctl.make_bootstrap_leader()',
-            },
-        }
-    end
+    cg['server1'] = cg.replica_set:build_and_add_server{
+        alias = 'server1',
+        box_cfg = cg.box_cfg,
+        -- Both instances advertise itself as bootstrap
+        -- leaders.
+        env = {
+            ['TARANTOOL_RUN_BEFORE_BOX_CFG'] =
+                'box.ctl.make_bootstrap_leader()',
+        },
+    }
+
+    cg.box_cfg.replication = {
+        server.build_listen_uri('server1', cg.replica_set.id),
+    }
+    cg['server2'] = cg.replica_set:build_and_add_server{
+        alias = 'server2',
+        box_cfg = cg.box_cfg,
+        -- Both instances advertise itself as bootstrap
+        -- leaders.
+        env = {
+            ['TARANTOOL_RUN_BEFORE_BOX_CFG'] =
+                'box.ctl.make_bootstrap_leader()',
+        },
+    }
 end)
 
 -- For the sake of completeness verify behavior in the incorrect
@@ -921,3 +935,63 @@ g_supervised.test_early_leader_several_leaders = function(cg)
         t.assert(found, ('Found %s'):format(query))
     end)
 end
+
+g_supervised.before_test('test_several_leaders', function(cg)
+    cg.replica_set = replica_set:new{}
+    cg.box_cfg_1 = {
+        bootstrap_strategy = 'supervised',
+        -- Has only itself in upstreams and can bootstrap on its
+        -- own.
+        replication = {
+            server.build_listen_uri('server2', cg.replica_set.id),
+        },
+        replication_timeout = 0.1,
+    }
+    cg.box_cfg_2 = {
+        bootstrap_strategy = 'supervised',
+        -- Has no itself in upstreams, but has another instance
+        -- that advertises itself as a bootstrap leader.
+        --
+        -- The expectation is that server2 anyway bootstraps its
+        -- own database, because box.ctl.make_bootstrap_leader()
+        -- is called before box.cfg().
+        replication = {
+            server.build_listen_uri('server1', cg.replica_set.id),
+        },
+        replication_timeout = 0.1,
+    }
+    for i = 1, 2 do
+        local alias = 'server' .. i
+        cg[alias] = cg.replica_set:build_and_add_server{
+            alias = alias,
+            box_cfg = cg['box_cfg_' .. i],
+        }
+        cg['admin' .. i] = fio.pathjoin(cg[alias].workdir, 'server.admin')
+        local run_before_cfg = string.format([[
+            box.error.injection.set('ERRINJ_BOOTSTRAP_DELAY', true)
+            local console = require('console')
+            console.listen('unix/:%s')
+        ]], cg['admin' .. i])
+        cg[alias].env.TARANTOOL_RUN_BEFORE_BOX_CFG = run_before_cfg
+    end
+end)
+
+-- XXX
+g_supervised.test_several_leaders = function(cg)
+    cg.server1:start({wait_until_ready = false})
+    t.helpers.retrying({}, make_bootstrap_leader_initial, cg.admin1)
+
+    cg.server2:start({wait_until_ready = false})
+    t.helpers.retrying({}, make_bootstrap_leader_initial, cg.admin2)
+
+    local cmd = "box.error.injection.set('ERRINJ_BOOTSTRAP_DELAY', false)\n"
+    local response = '---\n- ok'
+    t.helpers.retrying({}, make_socket_exec, cg.admin1, cmd, response)
+    t.helpers.retrying({}, make_socket_exec, cg.admin2, cmd, response)
+
+    local query = 'ER_REPLICASET_UUID_MISMATCH'
+    t.helpers.retrying({}, function()
+        local found = grep_log(cg.server2, query)
+        t.assert(found, ('Found %s'):format(query))
+    end)
+end

```

</p>
</details>

File: src/box/box.cc (hunk 2 above)
Comment (Totktonada) [reply src/box/box.cc]: The variable is renamed now, so I think I can close this discussion.

File: src/box/box.cc (hunk 11 above)
Comment (Totktonada) [reply src/box/box.cc:2279]: Well, I spins here for a while, and it seems that it is too cumbersome for me to create such a test. I hope it is OK to pass it over.

File: changelogs/unreleased/early-make-bootstrap-leader.md (hunk 8 above)
Comment (sergepetrenko) [inline changelogs/unreleased/early-make-bootstrap-leader.md:1]: Typo in the docbot request:
```
So, the following code is now possible:

```lua
box.cfg.make_bootstrap_leader()
```
^ `box.ctl.make_bootstrap_leader()`

File: src/box/replication.cc [hunk 12]
```diff
@@ -1664,6 +1673,25 @@ replicaset_find_join_master_cfg(void)
...
+	 *
+	 * NB: It is possible to run the cycle below first and
+	 * verify other members status known at this moment.
+	 * However, since we don't wait for connecting to all the
+	 * instances, it has a low chance to catch a problem.
+	 * As result, it would just make the result of calling
+	 * this function less predictable without visible gains
+	 * for a user.
+	 */
+	if (is_supervised_bootstrap_leader)
```
Comment (sergepetrenko) [inline src/box/replication.cc:1692]: I suppose you'll have to move this check below once you introduce #11272. Otherwise you'd always choose yourself even when there is some other bootstrap leader.

TBH, I'd rather look at this whole patchset together with #11272 to better understand how it'll all turn out together.

AFAIU you're planning to implement #11272 right after this patch anyway?

File: src/box/alter.cc [hunk 13]
```diff
@@ -4325,6 +4325,8 @@ on_commit_schema_set_bootstrap_leader_uuid(struct trigger *trigger, void *event)
 	struct tt_uuid *uuid = (struct tt_uuid *)trigger->data;
 	bootstrap_leader_uuid = *uuid;
 	is_supervised_bootstrap_leader = tt_uuid_is_equal(uuid, &INSTANCE_UUID);
+	say_info("instance %s is assigned as a bootstrap leader",
```
Comment (sergepetrenko) [inline src/box/alter.cc:4328]: Let's add some details here:

You could print `This instance (uuid) is assigned as a bootstrap leader` judging by `is_supervised_bootstrap_leader`. Would be  bit more informative IMO and more similar to the other message from `make_bootstrap_leader` itself.

File: src/box/replication.cc (hunk 12 above)
Comment (sergepetrenko) [reply src/box/replication.cc:1692]: Probably a comment is needed here that by returning `NULL` we mean `self`, and not `none`.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the patch!

I have no objections regarding this part, although I'd like to see it together with the patch for #11272.

File: src/box/alter.cc (hunk 13 above)
Comment (Totktonada) [reply src/box/alter.cc:4328]: @Serpentian suggested the opposite :) See https://github.com/tarantool/tarantool/pull/10859#discussion_r1861378859.

I don't mind any option, TBH.

File: changelogs/unreleased/early-make-bootstrap-leader.md (hunk 8 above)
Comment (Totktonada) [reply changelogs/unreleased/early-make-bootstrap-leader.md:1]: Thanks! Will fix with the next push.

File: src/box/replication.cc (hunk 12 above)
Comment (Totktonada) [reply src/box/replication.cc:1692]: OK, it is easier to look these patches together, I agree.

In fact, I'm going to add a separate flag for the graceful bootstrap request -- things look more orthogonal this way for me. So, I'll check `is_supervised_bootstrap_leader` first and then the new graceful bootstrap leader flag.

However, other changes are needed in this function. Let's discuss, when I'll prepare the patch (I've a working draft for now, will polish it a bit).

Also, I've added `return NULL` comment in the graceful bootstrap patch, because I also found that this is not very obvious what the `NULL` retval means.

Will ping.

File: changelogs/unreleased/early-make-bootstrap-leader.md (hunk 8 above)
Comment (Totktonada) [reply changelogs/unreleased/early-make-bootstrap-leader.md:1]: Done.

File: src/box/replication.cc (hunk 12 above)
Comment (Totktonada) [reply src/box/replication.cc:1731]: Pushed the graceful bootstrap implementation as the third commit here. I do it as early as possible to let you know, what I'm going to do, and some things may be inaccurate. Maybe I'll change some minor details tomorrov.

(And I'll update the PR description tomorrow.)

TBH, I don't like how it is going to evolve:

* Separate waiting and decision-making functions, both customized for a strategy.
* Controlling these two functions using global flags (and, again, differently for each strategy).
* A need for synchronizing the flag values with each other and with the database initialization/recovery flow.

I think that the bootstrap/recovery decision process should be like a state machine, while the bootstrap request/graceful bootstrap request should be a kind of limited lifespan object or, maybe, a state of this state machine.

However, I think that it is better to leave more-or-less architectural solutions to the core team and provide the needed behavior in some direct way (plus some tests). Also, if I would go actually implement it, it is likely takes an order of magnitude more time for me.

File: src/box/alter.cc (hunk 10 above)
Comment (sergepetrenko) [reply src/box/alter.cc]: > I'd rather not make any condition here. instance %s is assigned as a bootstrap leader is enough, IMHO. We never say, whether UUID is our own or not in other log messages

Personally I find it inconvenient determining if a particular identifier belongs to the instance we are looking at or not.

For example, messages like `got a request {term: 2, vote: 3, state = 'follower} from 2`. Who is `3`? It would be much more convenient if places like this mentioned `vote: 3 (us)` or something similar.

Same here: `Instance <uuid> is assigned as a bootstrap leader`. Which instance is this? Should I really go over all the logs and match the string `Instance uuid ...` to see if this is us or not?

What do you think @Serpentian ?

File: src/box/alter.cc (hunk 13 above)
Comment (sergepetrenko) [reply src/box/alter.cc:4346]: Oh, ok. Let's see what @Serpentian thinks.

Comment (sergepetrenko) [reply src/box/alter.cc:4346]: Nit: 
I'd print `This instance (uuid)`, not simply `This instance ...`

File: src/box/replication.cc [hunk 14]
```diff
@@ -1690,21 +1729,101 @@ replicaset_find_join_master_supervised(void)
...
 		struct applier *applier = replica->applier;
 		if (applier == NULL)
 			continue;
 		if (applier_is_bootstrap_leader(applier))
 			leader = replica;
 	}
-	if (leader == NULL) {
-		tnt_raise(ClientError, ER_CFG, "bootstrap_strategy",
-			  "failed to connect to the bootstrap leader");
+
```
Comment (sergepetrenko) [inline src/box/replication.cc:1741]: The diff in `replicaset_find_join_master_supervised` looks too complicated, TBH.

I'd suggest something along these lines (an incremental diff on top of your patch). I didn't try it out, it's just to illustrate my idea.

<details><summary>diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index fbec28fad3..878226a2b3 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -5360,6 +5360,10 @@ bootstrap_master(void)
 	 */
 	if (bootstrap_strategy == BOOTSTRAP_STRATEGY_AUTO)
 		check_bootstrap_unanimity();
+	else if (bootstrap_strategy == BOOTSTRAP_STRATEGY_SUPERVISED &&
+		 is_graceful_supervised_bootstrap_requested) {
+		say_info("Graceful bootstrap succeeded");
+	}
 	engine_bootstrap_xc();
 	if (box_set_replication_synchro_queue_max_size() != 0)
 		diag_raise();
@@ -5402,6 +5406,10 @@ bootstrap_from_master(struct replica *master)
 {
 	struct applier *applier = master->applier;
 	assert(applier != NULL);
+	if (bootstrap_strategy == BOOTSTRAP_STRATEGY_SUPERVISED &&
+	    is_graceful_supervised_bootstrap_requested) {
+		say_info("Graceful bootsrtap didn't work.");
+	}
 	try {
 		applier_resume_to_state(applier, APPLIER_READY,
 					TIMEOUT_INFINITY);
diff --git a/src/box/replication.cc b/src/box/replication.cc
index 103cb6b7ae..ffadf147bc 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1694,31 +1694,13 @@ replicaset_find_join_master_cfg(void)
 static struct replica *
 replicaset_find_join_master_supervised(void)
 {
-	/*
-	 * Drop the graceful bootstrap request, if any.
-	 *
-	 * Whether we're going to act as a bootstrap leader or
-	 * not, whether the request is taken into account or not,
-	 * the die is cast and the graceful bootstrap request
-	 * is not actual after execution of this function.
-	 *
-	 * Don't give a chance for code executed afterwards to see
-	 * this flag.
-	 */
-	bool graceful = is_graceful_supervised_bootstrap_requested;
-	if (graceful)
-		is_graceful_supervised_bootstrap_requested = false;
-
-	struct replica *leader = NULL;
-
 	/*
 	 * If we're known as a bootstrap leader, just bootstrap
 	 * the database.
 	 *
 	 * Unlike the 'auto' bootstrap strategy, the 'supervised'
 	 * one has no safety checks with waiting for ballots from
-	 * other replicaset members (except when the graceful
-	 * bootstrap is requested).
+	 * other replicaset members.
 	 *
 	 * NB: It is possible to run the cycle below first and
 	 * verify other members status known at this moment.
@@ -1729,8 +1711,9 @@ replicaset_find_join_master_supervised(void)
 	 * for a user.
 	 */
 	if (is_supervised_bootstrap_leader)
-		goto do_bootstrap;
+		return NULL;
 
+	struct replica *leader = NULL;
 	replicaset_foreach(replica) {
 		struct applier *applier = replica->applier;
 		if (applier == NULL)
@@ -1738,92 +1721,11 @@ replicaset_find_join_master_supervised(void)
 		if (applier_is_bootstrap_leader(applier))
 			leader = replica;
 	}
-
-	/* If the leader is found, just return it. */
-	if (leader != NULL) {
-		if (tt_uuid_is_equal(&leader->uuid, &INSTANCE_UUID))
-			goto do_bootstrap;
-		goto do_recovery;
-	}
-
-	/*
-	 * If we see this flag at this point, it means that the
-	 * waiting logic from replicaset_is_connected() is
-	 * finished. There are three situations, when it is
-	 * possible:
-	 *
-	 * 1. A bootstrap leader is found.
-	 * 2. All the instances from box.cfg.replication are
-	 *    connected, but no one is a bootstrap leader.
-	 * 3. box.cfg.replication_connect_timeout is reached.
-	 *
-	 * The logic above covers bullet 1. We either in 2 or 3.
-	 * In any of these cases, let's continue as a bootstrap
-	 * leader.
-	 */
-	if (graceful)
-		goto do_bootstrap;
-
-	goto do_error;
-
-do_bootstrap:
-	/*
-	 * Keep is_supervised_bootstrap_leader and
-	 * bootstrap_leader_uuid is sync. The latter
-	 * is set in bootstrap() (from box.cc) after
-	 * returning from this function.
-	 */
-	is_supervised_bootstrap_leader = true;
-	/*
-	 * If there is a graceful bootstrap request, report how it
-	 * is finished.
-	 */
-	if (graceful) {
-		say_info("graceful bootstrap request succeeds: no bootstrap "
-			 "leader is found in connected peers, so the current "
-			 "instance proceeds as a bootstrap leader");
-	}
-	/*
-	 * Assign the current instance as a bootstrap
-	 * leader.
-	 */
-	return NULL;
-do_recovery:
-	assert(leader != NULL);
-	/* Sync the flag. */
-	is_supervised_bootstrap_leader = false;
-	/*
-	 * If there is a graceful bootstrap request, report how it
-	 * is finished.
-	 */
-	if (graceful) {
-		say_info("graceful bootstrap request failed: other bootstrap "
-			 "leader is found within connected peers, proceed as a "
-			 "regular replica");
+	if (leader == NULL && !is_graceful_supervised_bootstrap_requested) {
+		tnt_raise(ClientError, ER_CFG, "bootstrap_strategy",
+			  "failed to connect to the bootstrap leader");
 	}
-	/* Return the bootstrap leader. */
 	return leader;
-do_error:
-	/* Sync the flag. */
-	is_supervised_bootstrap_leader = false;
-	/*
-	 * If the graceful bootstrap was requested, we go to
-	 * do_bootstrap or do_recovery.
-	 */
-	assert(!graceful);
-	/*
-	 * This error is reported if replicaset_connect() reaches
-	 * the end of box.cfg.replication_connect_timeout timeout
-	 * and no bootstrap leader is found across the peers
-	 * (including the current instance).
-	 *
-	 * Also, it is reported immediately if box.cfg() is called
-	 * without configured upstreams and
-	 * box.ctl.make_bootstrap_leader(<...>) is not called
-	 * beforehand.
-	 */
-	tnt_raise(ClientError, ER_CFG, "bootstrap_strategy",
-		  "failed to connect to the bootstrap leader");
 }
 
 struct replica *
```

</details>

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks!

The general implementation idea looks good to me although I'd like to simplify some places here and there.

File: src/box/box.cc [hunk 15]
```diff
@@ -2246,8 +2246,21 @@ box_set_bootstrap_leader_record(void)
...
 
 int
-box_make_bootstrap_leader(void)
+box_make_bootstrap_leader(bool graceful)
 {
+	is_graceful_supervised_bootstrap_requested = graceful;
+	if (graceful && is_box_configured) {
+		say_info("graceful bootstrap request is discarded: the "
+			 "instance is already bootstrapped");
+		return 0;
```
Comment (Totktonada) [inline src/box/box.cc:2255]: We shouldn't set `is_graceful_supervised_bootstrap_requested = true` in the case, I think. Will fix.

File: src/box/box.cc [hunk 16]
```diff
@@ -2246,8 +2246,21 @@ box_set_bootstrap_leader_record(void)
...
+	} else if (graceful) {
+		say_info("graceful bootstrap is requested: the instance "
+			 "is going to check whether a bootstrap leader "
+			 "already exists and if the check fails the instance "
+			 "takes this role");
+		return 0;
```
Comment (Totktonada) [inline src/box/box.cc:2261]: We need to call `box_broadcast_ballot()` here. Otherwise `replicaset_connect()` freezes infinitely on the fiber cond and doesn't repeat the `replicaset_is_connected()` call.

File: changelogs/unreleased/graceful-make-bootstrap-leader.md
Comment (Totktonada) [inline changelogs/unreleased/graceful-make-bootstrap-leader.md:1]: Also I need an exception for 037bd58cdb4b2aaebeacffddd49e731d311d6638 for the supervised bootstrap strategy.

Otherwise I can't run `box.cfg(<...>)` with all my configuration and `read_only = false` and make something like this from the coordinator:

```lua
box.ctl.make_bootstrap_leader({graceful = true})
box.cfg({read_only = false})
```

Proposal:

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 4aa584c3df..df3f8ee1fd 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -5350,8 +5352,17 @@ check_global_ids_integrity(void)
 static void
 bootstrap_master(void)
 {
-       /* Do not allow to bootstrap a readonly instance as master. */
-       if (cfg_geti("read_only") == 1) {
+       /*
+        * Do not allow to bootstrap a readonly instance as master.
+        *
+        * Allow an exception for the supervised bootstrap
+        * strategy, because the commmand to bootstrap may be
+        * received during the in progress box.cfg() call and
+        * there is no way to change box.cfg.read_only at this
+        * time.
+        */
+       if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED &&
+           cfg_geti("read_only") == 1) {
                tnt_raise(ClientError, ER_BOOTSTRAP_READONLY);
        }
        /*
```

Comment (Totktonada) [inline changelogs/unreleased/graceful-make-bootstrap-leader.md:1]: In the scenario, when I run `box.cfg()` with all my configuration as part of the YAML config startup flow and wait for coordinator's command, I've a problem with a replicaset that contains just one instance.

First, we lean on `box_broadcast_ballot()`, but if `box.cfg.replication` doesn't contain the current instance (that is completely OK, because we can lack `box.cfg.listen` too), the `replicaset_connect()` code will not wake up.

We possibly need something like the following:

<details>
<summary>Diff</summary>

```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index a8156c33dd..6fd8718664 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -225,6 +225,15 @@ struct replicaset_connect_state {
        struct fiber_cond wakeup;
 };

+static struct fiber_cond *replicaset_connect_wakeup_cond = NULL;
+
+void
+replicaset_connect_wakeup(void)
+{
+       if (replicaset_connect_wakeup_cond != NULL)
+               fiber_cond_signal(replicaset_connect_wakeup_cond);
+}
+
 static void
 replicaset_set_sync_quorum(const struct replicaset_connect_state *state)
 {
@@ -1333,6 +1351,7 @@ replicaset_connect(const struct uri_set *uris,
                        trigger_clear(&trigger->base);
                }
        });
+       replicaset_connect_wakeup_cond = &state.wakeup;
        while (!replicaset_is_connected(&state, appliers, count,
                                        connect_quorum)) {
                double wait_start = ev_monotonic_now(loop());
@@ -1342,6 +1361,7 @@ replicaset_connect(const struct uri_set *uris,
                }
                timeout -= ev_monotonic_now(loop()) - wait_start;
        }
+       replicaset_connect_wakeup_cond = NULL;
        if (state.connected < count) {
                say_crit("failed to connect to %d out of %d replicas",
                         count - state.connected, count);
diff --git a/src/box/replication.h b/src/box/replication.h
index bb8ade1ea6..9da99b820c 100644
--- a/src/box/replication.h
+++ b/src/box/replication.h
@@ -705,6 +705,12 @@ void
 replicaset_connect(const struct uri_set *uris,
                   bool connect_quorum, bool keep_connect);

+/**
+ * XXX
+ */
+void
+replicaset_connect_wakeup(void);
+
 /**
  * Reload replica URIs.
  *
diff --git a/src/box/box.cc b/src/box/box.cc
index 4aa584c3df..df3f8ee1fd 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -2248,7 +2248,6 @@ box_set_bootstrap_leader_record(void)
 int
 box_make_bootstrap_leader(bool graceful)
 {
-       is_graceful_supervised_bootstrap_requested = graceful;
        if (graceful && is_box_configured) {
                say_info("graceful bootstrap request is discarded: the "
                         "instance is already bootstrapped");
@@ -2258,6 +2257,9 @@ box_make_bootstrap_leader(bool graceful)
                         "is going to check whether a bootstrap leader "
                         "already exists and if the check fails the instance "
                         "takes this role");
+               is_graceful_supervised_bootstrap_requested = graceful;
+               //box_broadcast_ballot();
+               replicaset_connect_wakeup();
                return 0;
        }
```
</details>

Second, we don't even step into this code, because `replicaset_connect()` just exits if there are no upstreams. I propose an exception for the supervised strategy:

<details>
<summary>Diff</summary>

```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index a8156c33dd..6fd8718664 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1251,7 +1265,11 @@ replicaset_connect(const struct uri_set *uris,
        memset(&state, 0, sizeof(state));
        fiber_cond_create(&state.wakeup);

-       if (uris->uri_count == 0) {
+       /*
+        * An exception for supervised XXX.
+        */
+       if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED &&
+           uris->uri_count == 0) {
                replicaset_set_sync_quorum(&state);
                /* Cleanup the replica set. */
                replicaset_update(NULL, 0, false);
```
</details>

File: src/box/alter.cc (hunk 10 above)
Comment (Serpentian) [reply src/box/alter.cc]: > Personally I find it inconvenient determining if a particular identifier belongs to the instance we are looking at or not.

I agree, but we should not solve that in the scope of this PR. IMHO, it should be done on the lower level, for example in `tt_uuid_str`, so that it prints `<uuid> (current)` instead of just `<uuid>`? This condition so high in the code looks crutchy and it'll require patching a lot of log messages, if we go this way and decide to change all log msgs.

File: changelogs/unreleased/graceful-make-bootstrap-leader.md
Comment (sergepetrenko) [reply changelogs/unreleased/graceful-make-bootstrap-leader.md:1]: Makes sense, I agree.

File: src/box/box.cc (hunk 15 above)
Comment (Totktonada) [reply src/box/box.cc]: Fixed this way:

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 2b65ff26ec..834f9f3717 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -2248,12 +2248,13 @@ box_set_bootstrap_leader_record(void)
 int
 box_make_bootstrap_leader(bool graceful)
 {
-	is_graceful_supervised_bootstrap_requested = graceful;
 	if (graceful && is_box_configured) {
+		is_graceful_supervised_bootstrap_requested = false;
 		say_info("graceful bootstrap request is discarded: the "
 			 "instance is already bootstrapped");
 		return 0;
 	} else if (graceful) {
+		is_graceful_supervised_bootstrap_requested = true;
 		say_info("graceful bootstrap is requested: the instance "
 			 "is going to check whether a bootstrap leader "
 			 "already exists and if the check fails the instance "
@@ -2261,6 +2262,8 @@ box_make_bootstrap_leader(bool graceful)
 		return 0;
 	}
 
+	is_graceful_supervised_bootstrap_requested = false;
+
 	if (tt_uuid_is_nil(&INSTANCE_UUID)) {
 		/*
 		 * Can't store the UUID of the given instance as
```

TBH, it is for consistency and I don't know any scenario, where `is_graceful_supervised_bootstrap_requested == true` would affect anything in case of already configured database:

* We don't go to `bootstrap_master()` or `bootstrap_from_master()`, do we? Well, maybe in some rebootstrap scenario.
* If some other bootstrap leader appears, we just make the flag `false` in alter.cc.

So, I have no test case for this change.

File: src/box/box.cc (hunk 16 above)
Comment (Totktonada) [reply src/box/box.cc]: Added the `box_broadcast_ballot()` call (if there is an instance uuid), wrote a test case. The incremental diff is below.

<details>
<summary>Diff</summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 834f9f3717..add6c255a8 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -2248,6 +2248,18 @@ box_set_bootstrap_leader_record(void)
 int
 box_make_bootstrap_leader(bool graceful)
 {
+	/* Bootstrap strategy is read by the time instance uuid is known. */
+	if (!tt_uuid_is_nil(&INSTANCE_UUID) &&
+	    bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED) {
+		assert(bootstrap_strategy != BOOTSTRAP_STRATEGY_INVALID);
+		diag_set(ClientError, ER_UNSUPPORTED,
+			 tt_sprintf("bootstrap_strategy = '%s'",
+				    cfg_gets("bootstrap_strategy")),
+			 "promoting the bootstrap leader via "
+			 "box.ctl.make_bootstrap_leader()");
+		return -1;
+	}
+
 	if (graceful && is_box_configured) {
 		is_graceful_supervised_bootstrap_requested = false;
 		say_info("graceful bootstrap request is discarded: the "
@@ -2259,6 +2271,8 @@ box_make_bootstrap_leader(bool graceful)
 			 "is going to check whether a bootstrap leader "
 			 "already exists and if the check fails the instance "
 			 "takes this role");
+		if (!tt_uuid_is_nil(&INSTANCE_UUID))
+			box_broadcast_ballot();
 		return 0;
 	}
 
@@ -2275,16 +2289,6 @@ box_make_bootstrap_leader(bool graceful)
 		say_info("this instance is assigned as a bootstrap leader");
 		return 0;
 	}
-	/* Bootstrap strategy is read by the time instance uuid is known. */
-	assert(bootstrap_strategy != BOOTSTRAP_STRATEGY_INVALID);
-	if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED) {
-		diag_set(ClientError, ER_UNSUPPORTED,
-			 tt_sprintf("bootstrap_strategy = '%s'",
-				    cfg_gets("bootstrap_strategy")),
-			 "promoting the bootstrap leader via "
-			 "box.ctl.make_bootstrap_leader()");
-		return -1;
-	}
 	if (is_box_configured) {
 		if (box_check_writable() != 0)
 			return -1;
diff --git a/test/replication-luatest/bootstrap_strategy_test.lua b/test/replication-luatest/bootstrap_strategy_test.lua
index 009f10dfa2..0201c5b2f5 100644
--- a/test/replication-luatest/bootstrap_strategy_test.lua
+++ b/test/replication-luatest/bootstrap_strategy_test.lua
@@ -539,13 +539,21 @@ local g_supervised = t.group('gh-8509-bootstrap-strategy-supervised')
 local server2_admin
 local SOCKET_TIMEOUT = 5
 
-local function make_bootstrap_leader_initial(sockname)
+local function make_bootstrap_leader_initial(sockname, opts)
+    opts = opts or {}
+    local command
+    if opts.graceful then
+        command = 'box.ctl.make_bootstrap_leader({graceful = true})'
+    else
+        command = 'box.ctl.make_bootstrap_leader()'
+    end
+
     local sock, err = socket.tcp_connect('unix/', sockname)
     t.assert_equals(err, nil, 'Connection successful')
     local greeting = sock:read(128, SOCKET_TIMEOUT)
     t.assert_str_contains(greeting, 'Tarantool', 'Connected to console')
     t.assert_str_contains(greeting, 'Lua console', 'Connected to console')
-    sock:write('box.ctl.make_bootstrap_leader()\n', SOCKET_TIMEOUT)
+    sock:write(command .. '\n', SOCKET_TIMEOUT)
     local response = sock:read(8, SOCKET_TIMEOUT)
     t.assert_equals(response, '---\n...\n', 'The call succeeded')
     sock:close()
@@ -1099,3 +1107,75 @@ g_graceful_supervised.test_other_leader = function(cg)
         t.assert(found)
     end)
 end
+
+g_graceful_supervised.before_test('test_after_box_cfg', function(cg)
+    cg.replica_set = replica_set:new{}
+    cg.box_cfg = {
+        bootstrap_strategy = 'supervised',
+        replication = {
+            server.build_listen_uri('server1', cg.replica_set.id),
+            server.build_listen_uri('server2', cg.replica_set.id),
+        },
+        replication_timeout = 0.1,
+    }
+    for i = 1, 2 do
+        local alias = 'server' .. i
+        local box_cfg = table.copy(cg.box_cfg)
+        box_cfg.instance_uuid = ({uuid1, uuid2})[i]
+        cg[alias] = cg.replica_set:build_and_add_server{
+            alias = alias,
+            box_cfg = box_cfg,
+        }
+    end
+
+    cg.server1_admin = fio.pathjoin(cg.server1.workdir, 'server1.admin')
+    local run_before_cfg = string.format([[
+        local console = require('console')
+        console.listen('unix/:%s')
+    ]], cg.server1_admin)
+
+    cg.server1.env.TARANTOOL_RUN_BEFORE_BOX_CFG = run_before_cfg
+end)
+
+-- Run box.cfg() first, wait until server1 connects to all the
+-- peers and then issue the graceful bootstrap request.
+--
+-- Similar to test_no_leader, but the graceful bootstrap request
+-- is issued after box.cfg() (and after all the peers are
+-- connected).
+--
+-- This way we verify that the graceful bootstrap request wakes up
+-- replicaset_connect(), where we wait for new connected peers, a
+-- new bootstrap leader, a change in the local supervised
+-- bootstrap flags (set by box.cfg.make_bootstrap_leader(<...>)).
+g_graceful_supervised.test_after_box_cfg = function(cg)
+    -- Start both instances, run box.cfg() on them.
+    cg.replica_set:start({wait_until_ready = false})
+
+    -- Wait until server1 connects to itself and server2.
+    t.helpers.retrying({}, function()
+        local found_1 = grep_log(cg.server1, 'remote master 11111111')
+        local found_2 = grep_log(cg.server1, 'remote master 22222222')
+        t.assert(found_1 ~= nil and found_2 ~= nil)
+    end)
+
+    -- Run box.cfg.make_bootstrap_leader({graceful = true}).
+    t.helpers.retrying({}, function()
+        make_bootstrap_leader_initial(cg.server1_admin, {graceful = true})
+    end)
+
+    -- Now the database should be bootstrapped.
+    cg.server1:wait_until_ready()
+    cg.server2:wait_until_ready()
+
+    -- Verify that server1 was the bootstrap leader.
+    t.assert_equals(cg.server1:get_instance_id(), 1)
+
+    -- Verify that a message about the reason why this instance
+    -- is a bootstrap leader is issued.
+    local exp_msg = 'graceful bootstrap request succeeded: no bootstrap ' ..
+        'leader is found in connected peers, so the current instance ' ..
+        'proceeds as a bootstrap leader'
+    local found = grep_log(cg.server1, exp_msg)
+    t.assert(found)
+end
```
</details>

File: changelogs/unreleased/graceful-make-bootstrap-leader.md
Comment (Totktonada) [reply changelogs/unreleased/graceful-make-bootstrap-leader.md:1]: I've added a commit that adds this exception (as shown above). The test cases are scary and have a lot of boilerplace code. But at least we have some regression testing.

**Comment by Totktonada** [comment]
@sergepetrenko @Serpentian I'm still working on bootstrapping a singleton replicaset ([discussion](https://github.com/tarantool/tarantool/pull/10859#discussion_r2009368023)), but all the other parts seems ready for review. I would appreciate a glance on these parts.

File: src/box/box.cc [hunk 17]
```diff
@@ -2246,8 +2246,38 @@ box_set_bootstrap_leader_record(void)
 }
 
 int
-box_make_bootstrap_leader(void)
+box_make_bootstrap_leader(bool graceful)
 {
+	/* Bootstrap strategy is read by the time instance uuid is known. */
```
Comment (sergepetrenko) [inline src/box/box.cc:2251]: I think you should also reset `is_graceful_supervised_bootstrap_requested` and `is_supervised_bootstrap_leader` flags in `box_set_bootstrap_strategy()`, if strategy happens to be not 'supervised'.

File: src/box/box.cc [hunk 18]
```diff
@@ -2246,8 +2246,38 @@ box_set_bootstrap_leader_record(void)
...
+			 "instance is already bootstrapped");
+		return 0;
+	} else if (graceful) {
+		is_graceful_supervised_bootstrap_requested = true;
+		say_info("graceful bootstrap is requested: the instance "
+			 "is going to check whether a bootstrap leader "
+			 "already exists and if the check fails the instance "
+			 "takes this role");
+		if (!tt_uuid_is_nil(&INSTANCE_UUID))
+			box_broadcast_ballot();
```
Comment (sergepetrenko) [inline src/box/box.cc:2275]: Why do you need a `box_broadcast_ballot()` here?

File: src/box/box.cc [hunk 19]
```diff
@@ -2246,8 +2246,38 @@ box_set_bootstrap_leader_record(void)
 }
 
 int
-box_make_bootstrap_leader(void)
+box_make_bootstrap_leader(bool graceful)
 {
+	/* Bootstrap strategy is read by the time instance uuid is known. */
+	if (!tt_uuid_is_nil(&INSTANCE_UUID) &&
```
Comment (sergepetrenko) [inline src/box/box.cc:2252]: I suggest the following incremental diff here. Would look simpler IMO:
```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 0db30a1ddf..8d38a72bd8 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -2245,39 +2245,27 @@ box_set_bootstrap_leader_record(void)
 		    tt_uuid_str(&INSTANCE_UUID), fiber_time64(), instance_id);
 }
 
-int
-box_make_bootstrap_leader(bool graceful)
+static int
+box_make_bootstrap_leader_graceful(void)
 {
-	/* Bootstrap strategy is read by the time instance uuid is known. */
-	if (!tt_uuid_is_nil(&INSTANCE_UUID) &&
-	    bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED) {
-		assert(bootstrap_strategy != BOOTSTRAP_STRATEGY_INVALID);
-		diag_set(ClientError, ER_UNSUPPORTED,
-			 tt_sprintf("bootstrap_strategy = '%s'",
-				    cfg_gets("bootstrap_strategy")),
-			 "promoting the bootstrap leader via "
-			 "box.ctl.make_bootstrap_leader()");
-		return -1;
-	}
-
-	if (graceful && is_box_configured) {
-		is_graceful_supervised_bootstrap_requested = false;
-		say_info("graceful bootstrap request is discarded: the "
-			 "instance is already bootstrapped");
-		return 0;
-	} else if (graceful) {
-		is_graceful_supervised_bootstrap_requested = true;
-		say_info("graceful bootstrap is requested: the instance "
-			 "is going to check whether a bootstrap leader "
-			 "already exists and if the check fails the instance "
-			 "takes this role");
-		if (!tt_uuid_is_nil(&INSTANCE_UUID))
-			box_broadcast_ballot();
+	if (is_box_configured) {
+		say_info("Graceful bootstrap request is discarded: the "
+			 "instance is already bootstrapped.");
 		return 0;
 	}
+	is_graceful_supervised_bootstrap_requested = true;
+	say_info("Graceful bootstrap is requested: the instance "
+		 "is going to check whether a bootstrap leader "
+		 "already exists and if the check fails the instance "
+		 "takes this role.");
+	if (!tt_uuid_is_nil(&INSTANCE_UUID))
+		box_broadcast_ballot();
+	return 0;
+}
 
-	is_graceful_supervised_bootstrap_requested = false;
-
+static int
+box_make_bootstrap_leader_nongraceful(void)
+{
 	if (tt_uuid_is_nil(&INSTANCE_UUID)) {
 		/*
 		 * Can't store the UUID of the given instance as
@@ -2286,22 +2274,40 @@ box_make_bootstrap_leader(bool graceful)
 		 * this action till the bootstrap.
 		 */
 		is_supervised_bootstrap_leader = true;
-		say_info("this instance is assigned as a bootstrap leader");
+		say_info("This instance is assigned as a bootstrap leader.");
 		return 0;
-	}
-	if (is_box_configured) {
-		if (box_check_writable() != 0)
-			return -1;
-		/* Ballot broadcast will happen in an on_commit trigger. */
-		return box_set_bootstrap_leader_record();
-	} else {
+	} else if (!is_box_configured) {
 		bootstrap_leader_uuid = INSTANCE_UUID;
 		is_supervised_bootstrap_leader = true;
 		box_broadcast_ballot();
 		return 0;
+	} else {
+		if (box_check_writable() != 0)
+			return -1;
+		/* Ballot broadcast will happen in an on_commit trigger. */
+		return box_set_bootstrap_leader_record();
 	}
 }
 
+int
+box_make_bootstrap_leader(bool graceful)
+{
+	if (!tt_uuid_is_nil(&INSTANCE_UUID) &&
+	    botstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED) {
+		assert(bootstrap_strategy != BOOTSTRAP_STRATEGY_INVALID);
+		diag_set(ClientError, ER_UNSUPPORTED,
+			 tt_sprintf("bootstrap_strategy = '%s'",
+				    cfg_gets("bootstrap_strategy")),
+			 "promoting the bootstrap leader via "
+			 "box.ctl.make_bootstrap_leader()");
+		return -1;
+	}
+	if (graceful)
+		return box_make_bootstrap_leader_graceful();
+	else
+		return box_make_bootstrap_leader_nongraceful();
+}
+
 void
 box_set_replication_sync_lag(void)
 {
```

**Review by sergepetrenko — COMMENTED** [review]
Thanks! Looks fine overall, just a couple of places need attention.

File: src/box/box.cc (hunk 17 above)
Comment (Totktonada) [reply src/box/box.cc:2251]: I think it worth to do. It doesn't affect usual scenarios, where the strategy is not changed. However, it brings more expected behavior in some unusual ones, where the strategy is changed. Thanks for the idea!

File: src/box/box.cc (hunk 15 above)
Comment (Totktonada) [reply src/box/box.cc]: OTOH, we don't have to turn off the flag within this logic and it becomes simpler. The flag is dropped after the request is finished. I'll update this code a bit on the next push.

File: src/box/box.cc (hunk 19 above)
Comment (Totktonada) [reply src/box/box.cc]: I mostly took it, but in a bit more conservative way (without switching if branches and so on). In particular:

* splitted to the two functions
* titlecased the log messages

I agree, now it looks simpler.

File: src/box/box.cc (hunk 18 above)
Comment (Totktonada) [reply src/box/box.cc]: Added a short remark:

```c
/* Wake up replicaset_connect() if the flag is turn on. */
if (!tt_uuid_is_nil(&INSTANCE_UUID))
        box_broadcast_ballot();
```

File: src/box/box.cc (hunk 17 above)
Comment (Totktonada) [reply src/box/box.cc]: Added in the corresponding commits.

File: src/box/box.cc (hunk 15 above)
Comment (Totktonada) [reply src/box/box.cc]: So, irrelevant now.

File: src/box/box.cc (hunk 11 above)
Comment (Serpentian) [reply src/box/box.cc:2302]: I don't mind passing it over

File: src/box/alter.cc (hunk 13 above)
Comment (Serpentian) [reply src/box/alter.cc:4349]: https://github.com/tarantool/tarantool/pull/10859#discussion_r2023182732

File: changelogs/unreleased/graceful-make-bootstrap-leader.md
Comment (Totktonada) [reply changelogs/unreleased/graceful-make-bootstrap-leader.md:1]: Added as a separate commit on top of the patchset.

File: src/box/box.cc [hunk 20]
```diff
@@ -5385,8 +5385,17 @@ check_global_ids_integrity(void)
 static void
 bootstrap_master(void)
 {
-	/* Do not allow to bootstrap a readonly instance as master. */
-	if (cfg_geti("read_only") == 1) {
+	/*
+	 * Do not allow to bootstrap a readonly instance as master.
+	 *
+	 * Allow an exception for the supervised bootstrap
```
Comment (Serpentian) [inline src/box/box.cc:5391]: Nit: it'd be also great to add motivation to the commit msg

File: src/box/replication.cc [hunk 21]
```diff
@@ -1251,7 +1260,13 @@ replicaset_connect(const struct uri_set *uris,
 	memset(&state, 0, sizeof(state));
 	fiber_cond_create(&state.wakeup);
 
-	if (uris->uri_count == 0) {
+	/*
+	 * The supervised bootstrap strategy has an exception
+	 * here, because it waits not only for replicas, but also
+	 * for local bootstrap leadership flags.
+	 */
+	if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED &&
```
Comment (Serpentian) [inline src/box/replication.cc:1268]: A meaningful log msg would be great here. This is not very self explanatory:

```
2025-04-09 19:29:06.848 [378076] main/104/interactive box.cc:5573 I> instance uuid 28e82fd7-34f9-41f7-8595-710acc2ed917
2025-04-09 19:29:06.848 [378076] main/104/interactive replication.cc:1294 I> connecting to 0 replicas
```

File: changelogs/unreleased/single-instance-in-supervised-bs.md [hunk 22]
```diff
@@ -0,0 +1,5 @@
+## feature/replication
+
+* Now `box.cfg({bootstrap_strategy = 'supervised'})` without upstreams waits
+  for the `box.ctl.make_bootstrap_leader(<...>)` command till the replication
+  connect timeout instead of an immediate fail.
```
Comment (Serpentian) [inline changelogs/unreleased/single-instance-in-supervised-bs.md:5]: Motivatiom in the commit msg. Ditto

**Review by Serpentian — APPROVED** [review]
I didn't manage to find any flaws. The patch is extensively tested and the tests're stable. They seem a little bit difficult to understand. but I see no sense in rewriting the tests now, when we have several before release left. Great work

File: src/box/box.cc [hunk 23]
```diff
@@ -2253,8 +2255,31 @@ box_set_bootstrap_leader_record(void)
...
+		say_info("Graceful bootstrap request is discarded: the "
+			 "instance is already bootstrapped");
+		return 0;
+	}
+
+	is_graceful_supervised_bootstrap_requested = true;
+	say_info("Graceful bootstrap is requested: the instance "
+		 "is going to check whether a bootstrap leader "
+		 "already exists and if the check fails the instance "
+		 "takes this role");
```
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc:2272]: > Nit: it should be in docs, not in the logs, IMHO. "Graceful bootstrap is requested" seems enough

I'm OK to re-write it in any way you and Serge want (so I would like to hear him first), but personally I found it nice to let a user know what is going on. I see nothing bad in self-explanatory log messages, alerts, errors.

There are different variants to achieve this goal, in fact. We can add IDs or URIs to log messages and have a website section that explains them. That would be even better, because it allows to add some details after a release.

Just 'find it somewhere in docs' feels unfriendly for me.

But, again, that's just my feelings, while the component is not mine and the decisions are on you and Serge.

> And it seems we don't start log msgs with capital letters

Hm. I did it after Serge's [comment](https://github.com/tarantool/tarantool/pull/10859#discussion_r2032976216). Don't know, whether we have some consistent approach here. The sensence-alive formatting feels a bit better for my taste. I'll change it (if needed) once you and Serge got a decision :)

File: src/box/box.cc (hunk 20 above)
Comment (Totktonada) [reply src/box/box.cc:5391]: Sorry for that. I had feeling that the documentation request gives enough details. But after your remark I looked on it once again and added the following context information into the commit message:

> The idea of the `supervised` bootstrap strategy spins around some external logic/agent/coordinator that makes decisions about a bootstrap leader.
>
> There are two possible approaches to bootstrap a replicaset:
>
> 1. At first, wait for the agent's decision. Do the first `box.cfg()` on all the instances after this. The bootstrap leader receives the desired configuration plus `read_only = false` (and the command to go to bootstrap). All the other replicaset peers receives the desired configuration plus `read_only = true`.
>
>    This way we can't use iproto to receive the decision and there are different ways to overcome it. For example, cartridge has its own implementation of a subset of the iproto protocol to receive such pre-box-cfg commands.
>
>    Another possible approach is to implement a separate daemon that receives remote commands and feeds them to tarantool admin console.
> 2. Call `box.cfg()` first with a desired configuration plus `read_only = true` on all the peers. Wait for the agent's decision. The chosen bootstrap leader receives the command to go to bootstrap plus `box.cfg({read_only = false})`.
>
> The second approach feels more native to tarantool and just simpler. This commit allows it. It is going to be used in the `native` bootstrap strategy in #10857.
>
> There are alternatives, in fact: see #11286 for some of them. However, I still think that the given one-line solution worth it (at least until we have something better designed and implemented).

I hope it brings enough background to have a vision about cons and pros behind the idea of the commit.

File: src/box/replication.cc (hunk 21 above)
Comment (Totktonada) [reply src/box/replication.cc:1268]: Good point, thanks!

Done this way:

```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index 347c0b62de..d74a3a028f 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1291,7 +1291,11 @@ replicaset_connect(const struct uri_set *uris,
 	for (; count < uris->uri_count; count++)
 		appliers[count] = applier_new(&uris->uris[count]);
 
-	say_info("connecting to %d replicas", count);
+	if (count == 0)
+		say_info("no upstreams are configured, waiting for the "
+			 "bootstrap command");
+	else
+		say_info("connecting to %d replicas", count);
 
 	if (!connect_quorum) {
 		/*
```

File: changelogs/unreleased/single-instance-in-supervised-bs.md (hunk 22 above)
Comment (Totktonada) [reply changelogs/unreleased/single-instance-in-supervised-bs.md:5]: I've added some context information. Sorry that I didn't do that from scratch.

> The `supervised` bootstrap strategy allows to run `box.cfg()` with desired initial configuration first and then issue a command to bootstrap the database on a particular instance. The instances are waiting for the bootstrap command during the replication connect timeout period (30 seconds by default).
>
> However, before this commit this flow doesn't work for a single-instance replicaset without itself in `box.cfg.replication` (which is fine, because it is fine to don't have `box.cfg.listen` at all).
>
> This difference requires to implement two different replicaset bootstrap flows that would significantly complicate a logic in #10857 that implements the `native` bootstrap strategy.
>
> However, we can eliminate the difference on the lower level and follow the same logic for the single-instance replicaset as we do for the multi-instance replicaset. And it magically simplifies the upper level logic too. Win-win.
>
> This commit makes the initial `box.cfg()` wait for the bootstrap leader in the `supervised` bootstrap strategy even if `box.cfg.replication` is `nil` or empty.

**Comment by Totktonada** [comment]
@Serpentian, thank you for the warm words!

The tests are actually... to be honest, they're messy. I guess I can do them a bit more structured, but it requires some significant work. For my taste, I'm close to the framework limits here and, in fact, I already did someting to solve that.

I wrote the cbuilder/cluster/interactive_tarantool helpers to solve problems like this. The tests that are written for the YAML config part of these changes (PR #11287) are based on these helpers and I like these tests much more.

In fact, I can rewrite some (or even all) the test cases from this PR using these helpers too. When I started to work on this PR it looked like I should use the usual `replication-luatest` tools (mimic the format of other test cases) and shouldn't use my helpers here. However, if I would know about all the cases I finally need to cover, I would likely just use the new helpers and things would be more structured.

Anyway, we have some regression tests. And I'll take this experience into account for future patches :)

File: src/box/box.cc (hunk 23 above)
[the remark this answers is not in the document]
Comment (Serpentian) [reply src/box/box.cc:2272]: @sergepetrenko

File: src/box/box.cc [hunk 24]
```diff
@@ -5357,8 +5393,15 @@ bootstrap_master(void)
 	 * With "auto" bootstrap strategy refuse to boot unless everyone agrees
 	 * this node is the bootstrap leader.
 	 */
-	if (bootstrap_strategy == BOOTSTRAP_STRATEGY_AUTO)
+	if (bootstrap_strategy == BOOTSTRAP_STRATEGY_AUTO) {
 		check_bootstrap_unanimity();
+	} else if (bootstrap_strategy == BOOTSTRAP_STRATEGY_SUPERVISED &&
+		 is_graceful_supervised_bootstrap_requested) {
```
Comment (sergepetrenko) [inline src/box/box.cc:5408]: Nit: wrong indentation:
```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 67dfe2e357..d9ed828f5f 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -5396,7 +5396,7 @@ bootstrap_master(void)
        if (bootstrap_strategy == BOOTSTRAP_STRATEGY_AUTO) {
                check_bootstrap_unanimity();
        } else if (bootstrap_strategy == BOOTSTRAP_STRATEGY_SUPERVISED &&
-                is_graceful_supervised_bootstrap_requested) {
+                  is_graceful_supervised_bootstrap_requested) {
                say_info("Graceful bootstrap request succeeded: no bootstrap "
                         "leader is found in connected peers, so the current "
                         "instance proceeds as a bootstrap leader");

```

File: src/box/box.cc [hunk 25]
```diff
@@ -2273,7 +2273,7 @@ box_make_bootstrap_leader_graceful(void)
 
 	/* Wake up replicaset_connect() if the flag is turn on. */
 	if (!tt_uuid_is_nil(&INSTANCE_UUID))
-		box_broadcast_ballot();
+		replicaset_connect_wakeup();
```
Comment (sergepetrenko) [inline src/box/box.cc:2276]: Nit: let's drop `box_broadcast_ballot()` here and below in a separate commit with a proper explanation on why it isn't needed or at least mention it in this commit message.

File: src/box/replication.cc (hunk 21 above)
Comment (sergepetrenko) [inline src/box/replication.cc:1268]: Let's please also check for `replicaset_state == REPLICASET_BOOTSRTAP || replicaset_state == REPLICASET_JOIN` here. Otherwise you'll log the 'waiting for the bootstrap command' line even if it's just a replication reconfiguration on a working instance.
```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index d74a3a028f..e926e5b254 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1265,8 +1265,10 @@ replicaset_connect(const struct uri_set *uris,
         * here, because it waits not only for replicas, but also
         * for local bootstrap leadership flags.
         */
-       if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED &&
-           uris->uri_count == 0) {
+       if (uris->uri_count == 0 &&
+           (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED ||
+            (replicaset_state != REPLICASET_BOOTSTRAP &&
+             replicaset_state != REPLICASET_JOIN))) {
                replicaset_set_sync_quorum(&state);
                /* Cleanup the replica set. */
                replicaset_update(NULL, 0, false);
```

File: src/box/replication.cc [hunk 26]
```diff
@@ -1342,6 +1362,7 @@ replicaset_connect(const struct uri_set *uris,
 		}
 		timeout -= ev_monotonic_now(loop()) - wait_start;
 	}
+	replicaset_connect_wakeup_cond = NULL;
```
Comment (sergepetrenko) [inline src/box/replication.cc:1365]: Leaking a pointer to `state.wakeup` in case `fiber_testcancel()` throws an error above.
```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index d74a3a028f..ff5136b9cf 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1353,6 +1353,9 @@ replicaset_connect(const struct uri_set *uris,
                }
        });
        replicaset_connect_wakeup_cond = &state.wakeup;
+       auto cond_guard = make_scoped_guard([&]{
+               replicaset_connect_wakeup_cond = NULL;
+       });
        while (!replicaset_is_connected(&state, appliers, count,
                                        connect_quorum)) {
                double wait_start = ev_monotonic_now(loop());
@@ -1363,6 +1366,7 @@ replicaset_connect(const struct uri_set *uris,
                timeout -= ev_monotonic_now(loop()) - wait_start;
        }
        replicaset_connect_wakeup_cond = NULL;
+       cond_guard.is_active = false;
        if (state.connected < count) {
                say_crit("failed to connect to %d out of %d replicas",
                         count - state.connected, count);
```

**Review by sergepetrenko — APPROVED** [review]
Thanks for the patch!
I've left some suggestions below, everything else LGTM.

File: src/box/box.cc (hunk 17 above)
Comment (sergepetrenko) [reply src/box/box.cc]: Thanks!

File: src/box/alter.cc (hunk 13 above)
Comment (sergepetrenko) [reply src/box/alter.cc:4349]: > [#10859 (comment)](https://github.com/tarantool/tarantool/pull/10859#discussion_r2023182732)

Haven't thought of this, that's a nice idea.

File: src/box/box.cc (hunk 19 above)
Comment (sergepetrenko) [reply src/box/box.cc]: Thanks! Looks much cleaner this way.

File: src/box/box.cc (hunk 23 above)
[the remark this answers is not in the document]
Comment (sergepetrenko) [reply src/box/box.cc:2272]: > Hm. I did it after Serge's https://github.com/tarantool/tarantool/pull/10859#discussion_r2032976216. Don't know, whether we have some consistent approach here. The sensence-alive formatting feels a bit better for my taste. I'll change it (if needed) once you and Serge got a decision :)

It seems we don't have a single way of doing this. Also it seems more log messages start with a lowercase letter.
I formatted the message like we format comments for some reason, so I'm fine with any approach. Let's just keep it as it already is now, no need to change it back and forth at the last minute.

> Nit: it should be in docs, not in the logs, IMHO. "Graceful bootstrap is requested" seems enough

I like the longer message here. Let's keep Alexander's variant.

File: src/box/box.cc (hunk 24 above)
Comment (Totktonada) [reply src/box/box.cc]: Fixed.

File: src/box/box.cc (hunk 25 above)
Comment (Totktonada) [reply src/box/box.cc:2280]: I had a thought that `box_broadcast_ballot()` here is purely to wake up `replicaset_connect()`. Yesterday you pointed me out that it also may be needed to send the new bootstrap leader UUID in a ballot to other peers.

It seems like we anyway call `box_broadcast_ballot()` later after `replicaset_connect()`. However, I'm not 100% sure and I've no goal to eliminate the call. I need to add `replicaset_connect_wakeup()`, so I'll just do that (without a removal of the ballot sending).

The incremental diff:

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index b62fd40b07..f94388979d 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -2272,8 +2272,10 @@ box_make_bootstrap_leader_graceful(void)
 		 "takes this role");
 
 	/* Wake up replicaset_connect() if the flag is turn on. */
-	if (!tt_uuid_is_nil(&INSTANCE_UUID))
+	if (!tt_uuid_is_nil(&INSTANCE_UUID)) {
+		box_broadcast_ballot();
 		replicaset_connect_wakeup();
+	}
 
 	return 0;
 }
@@ -2300,6 +2302,7 @@ box_make_bootstrap_leader_nongraceful(void)
 	} else {
 		bootstrap_leader_uuid = INSTANCE_UUID;
 		is_supervised_bootstrap_leader = true;
+		box_broadcast_ballot();
 		replicaset_connect_wakeup();
 		return 0;
 	}
```

File: src/box/replication.cc (hunk 21 above)
Comment (Totktonada) [reply src/box/replication.cc]: Seems worthful, thanks. I also updated the remarks above.

The incremental diff:

```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index d74a3a028f..3b2a0ac66b 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1261,12 +1261,18 @@ replicaset_connect(const struct uri_set *uris,
 	fiber_cond_create(&state.wakeup);
 
 	/*
+	 * Return immediately if there are no configured
+	 * upstreams to wait.
+	 *
 	 * The supervised bootstrap strategy has an exception
 	 * here, because it waits not only for replicas, but also
-	 * for local bootstrap leadership flags.
+	 * for local bootstrap leadership flags (it is relevant on
+	 * bootstrap/join and irrelevant on a reconfiguration).
 	 */
-	if (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED &&
-	    uris->uri_count == 0) {
+	if (uris->uri_count == 0 &&
+	    (bootstrap_strategy != BOOTSTRAP_STRATEGY_SUPERVISED ||
+	     (replicaset_state != REPLICASET_BOOTSTRAP &&
+	      replicaset_state != REPLICASET_JOIN))) {
 		replicaset_set_sync_quorum(&state);
 		/* Cleanup the replica set. */
 		replicaset_update(NULL, 0, false);
```

File: src/box/replication.cc (hunk 26 above)
Comment (Totktonada) [reply src/box/replication.cc:1374]: Wow, totally overlooked it. Thank you!

Applied your diff here.

File: src/box/box.cc (hunk 23 above)
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/box.cc:2275]: I hope Nikita doesn't mind. I'm going to resolve this last open discussion.
