### PR TITLE
replication.boostrap_strategy = native

### LINKED ISSUE #10857: config: add replication.bootstrap_strategy = native
## Context

Now, the YAML configuration flow supports all the four bootstrap strategies supported by tarantool itself: `auto`, `config`, `supervised` and `legacy`. A user able to configure and use them.

However, neither of them suits all the needs.

First of all, there are two topics: bootstrapping a replicaset and joining a new replica. Both have so called bootstrap leader, but the meaning is slightly different.

When we bootstrap a replicaset, we should decide which instance creates the initial snapshot and fed it to others. This instance is the bootstrap leader.

When the replicaset already bootstrapped and a new replica is joining, it chooses an instance to register the replica in the `_cluster` system space and from where to fetch a snapshot. This instance is the bootstrap leader.

The bootstrap leader is determined in both cases using an algorithm configured by the `replication.bootstrap_strategy` option. It affects both cases.

Let's look on these two topics separately and highlight problems we met in cluster administration.

## Joining a new replica

The default `auto` bootstrap strategy needs to correctly handle multi-master setup, when different simultaneously joining replicas may choose different bootstrap leaders to register in the `_cluster` system space. If it occurs, they may incorrectly receive the same replica ID.

In order to prevent this situation, when a new replica joins the replicaset, the `auto` bootstrap strategy requires it to connect to all the *registered replicaset members*. If this condition is met, the algorithm works in the same way on the joining replicas and the same bootstrap leader is chosen. If this condition is not met, an error is reported.

The problematic part here is the registered replicaset members are ones that are in the `_cluster` system space[^1]. It is possible that one of them is temporarily stopped (say, to perform OS/host upgrade) or isolated to perform repairing activities (see #10796). Or the `_cluster` clean up is just not instant and occurs after some delay (see #10823). Or we have a CDC tool also registered in `_cluster`, but not accepting incoming connections.

In these cases we can meet the following error:

> Some replica set members were not specified in box.cfg.replication

<details>
<summary>The source code of the check in tarantool</summary>

https://github.com/tarantool/tarantool/blob/6a87c45deeb49e4e17ae2cc0eeb105cc9ee0f413/src/box/replication.cc#L800-L817

https://github.com/tarantool/tarantool/blob/6a87c45deeb49e4e17ae2cc0eeb105cc9ee0f413/src/box/errcode.h#L406
</details>

However,

1. We have cluster configuration, from which we can deduce that all the instances we need to connect are actually connected.
2. We can even deduce that the setup is not multi-master.
3. We can define a logic based on instance names in the cluster configuration, when the choice of a bootstrap leader is quite unambiguous.

We can implement our own bootstrap strategy based on the cluster configuration and solve the problems of the `auto` bootstrap strategy for users of the new YAML configuration flow.

[^1]: This logic was implemented before the cluster configuration is supported in tarantool. Taking it into account, the `_cluster` records are the best source of truth available.

## Bootstrapping a replicaset

If an external failover coordinator is in use, the default strategy should be `supervised`, not `auto`. This way only the coordinator appoints an instance to be RW and there are less chances to step into the split-brain situation.

It is solved with some timeout-based fencing in our failover coordinator for the `auto` strategy (https://github.com/tarantool/tarantool-ee/issues/854), but the key problem is that the instance goes to RW to bootstrap the replicaset on its own, without the coordinator's command.

## Proposal

Implement a new bootstrap strategy on the cluster config level: `native`. It uses the `supervised` bootstrap strategy under the hood, but implements an own logic based on the cluster configuration information.

* `replication.failover` = `off`/`manual`
  * On replicaset bootstrap (if there is no local snapshot): call `box.ctl.make_bootstrap_leader()` on a configured RW instance. In the multi-master mode: on the first one lexicographically.
  * On changing the database mode to RW: call `box.ctl.make_bootstrap_leader()`.
  * The last instance that go to RW is the bootstrap leader. So, there is a single bootstrap leader even if there are several RW instances (that is possible in `replication.failover` = `off`).
* `replication.failover` = `election`
  * Same, but the replicaset bootstrap leader is determined as an instance with the lowest name (lexicographically, excluding anonymous replicas).
* `replication.failover` = `supervised`
  * It is in coordinator's responsibility to call `box.ctl.make_bootstrap_leader()` to bootstrap the replicaset.
  * Same as the previous in other regards.

Jira: TNTP-366

### PR DESCRIPTION
**Pull request by Totktonada**
The new bootstrap strategy `native` is added here. It can be enabled using the `replication.bootstrap_strategy` option in the YAML configuration.

The new strategy acts more or less similar to the `auto` strategy, but relaxes its limitations (see details in #10857).

It is based on the `supervised` strategy and mainly performs two things:

* issues `box.ctl.make_bootstrap_leader({graceful = true})` to bootstrap a replicaset
* issues `box.ctl.make_bootstrap_leader()` to keep the bootstrap leader record pointing to the instance that is currently in the RW mode (to register new replicas)

The choice how to choose a bootstrap leader to initialize the replicaset depends on the `replication.failover` option. See details in #10857 or commit descriptions.

Fixes #10857

### CODE REVIEW

File: src/box/lua/config/applier/box_cfg.lua [hunk 1]
```diff
@@ -273,6 +259,22 @@ local function set_ro_rw(config, box_cfg)
...
+        local bootstrap_strategy = configdata:get(
+            'replication.bootstrap_strategy', {use_default = true})
+        local no_op_strategies = {
+            supervised = true,
+            native = true,
+        }
+        if no_op_strategies[bootstrap_strategy] then
+            box_cfg.read_only = true
+            return
+        end
```
Comment (georgiy-belyanin) [inline src/box/lua/config/applier/box_cfg.lua:276]: I'd like the user to perform less configuration.
Thus, I want the `box_cfg` applier automatically perform `box.internal.runtime_priv.grant('guest', 'execute', 'lua_call', 'failover.execute')` when working with `replication.bootstrap_strategy: supervised/native` and `replication.failover: supervised`. At first, I'd like to know your opinion on this to reduce the amount of configuration needed. 

Also, this seems like a perfect place for such logic, but `no_op_strategies` name seems kinda strange for any actions other than `box_cfg.read_only = true`. Thus, I suggest changing the name somehow.

```suggestion
        local supervised_strategies = {
            supervised = true,
            native = true,
        }
        if supervised_strategies[bootstrap_strategy] then
            box_cfg.read_only = true
            return
        end
```

Comment (Totktonada) [reply src/box/lua/config/applier/box_cfg.lua:276]: Even if it works to some extent, I'm against of calling `box.internal.runtime_priv.grant()` from anywhere outside of the `runtime_priv` configuration applier. They reason is that we do the following in the applier:

* collect *all* the needed runtime privileges
* reset the runtime privileges
* set the new privileges

This way we don't have to calculate a difference between actual and target privileges. It simplifies the implementation of the applier and *also* simplifies the underlying API (this way we have just two functions `reset` and `grant`, where `reset` just drops everything).

However, it adds a little constraint: we have to assign all the privileges in one pass or, at least, within one configuration applying iteration. But it is much more clear to keep everything within the relevant applier.

File: src/box/lua/config/applier/box_cfg.lua [hunk 2]
```diff
@@ -1024,6 +1010,138 @@ end
...
+    if not is_startup then
+        return
+    end
+
+    -- If there is a local snapshot, then the replicaset is
+    -- already bootstrapped. Nothing to do.
+    local has_snap = snapshot.get_path(configdata._iconfig_def) ~= nil
+    if has_snap then
+        return
+    end
```
Comment (georgiy-belyanin) [inline src/box/lua/config/applier/box_cfg.lua:1211]: Nit: this non-trivial check is now used in four distinct places. I suppose it deserves its own method `has_snap()`.

File: src/box/lua/config/applier/box_cfg.lua (hunk 1 above)
Comment (Totktonada) [reply src/box/lua/config/applier/box_cfg.lua]: Renamed the strategies list. Also, found that we shouldn't go to RO on reconfiguration, fixed, covered with a test.

```diff
diff --git a/src/box/lua/config/applier/box_cfg.lua b/src/box/lua/config/applier/box_cfg.lua
index ce7eabd8a5..d8ec06666a 100644
--- a/src/box/lua/config/applier/box_cfg.lua
+++ b/src/box/lua/config/applier/box_cfg.lua
@@ -268,12 +268,19 @@ local function set_ro_rw(config, box_cfg)
         -- an RW instance.
         local bootstrap_strategy = configdata:get(
             'replication.bootstrap_strategy', {use_default = true})
-        local startup_in_ro_strategies = {
+        local externally_managed_mode_strategies = {
             supervised = true,
             native = true,
         }
-        if startup_in_ro_strategies[bootstrap_strategy] then
-            box_cfg.read_only = true
+        if externally_managed_mode_strategies[bootstrap_strategy] then
+            if is_startup then
+                box_cfg.read_only = true
+            else
+                -- Don't change the read_only flag on the
+                -- reconfiguration. It is managed by an external
+                -- agent.
+                box_cfg.read_only = nil
+            end
             return
         end
 
diff --git a/test/config-luatest/native_bootstrap_strategy_test.lua b/test/config-luatest/native_bootstrap_strategy_test.lua
index 544ba703b5..0a2566686f 100644
--- a/test/config-luatest/native_bootstrap_strategy_test.lua
+++ b/test/config-luatest/native_bootstrap_strategy_test.lua
@@ -417,6 +417,14 @@ g_supervised_and_native.test_failover_supervised = function(g)
     end)
     verify_cluster_mode(cluster, {'rw', 'ro', 'ro'})
     verify_bootstrap_leader(cluster, 'i-001')
+
+    -- Reconfiguration doesn't drop the RW mode to RO.
+    cluster['i-001']:exec(function()
+        local config = require('config')
+
+        config:reload()
+        t.assert_equals(box.info.ro, false)
+    end)
 end
 
 -- Same as the previous test case, but cover a replicaset with one
@@ -469,4 +477,12 @@ g_supervised_and_native.test_failover_supervised_singleton = function(g)
     end)
     verify_cluster_mode(cluster, {'rw'})
     verify_bootstrap_leader(cluster, 'i-001')
+
+    -- Reconfiguration doesn't drop the RW mode to RO.
+    cluster['i-001']:exec(function()
+        local config = require('config')
+
+        config:reload()
+        t.assert_equals(box.info.ro, false)
+    end)
 end
```

File: src/box/lua/config/applier/box_cfg.lua (hunk 2 above)
Comment (Totktonada) [reply src/box/lua/config/applier/box_cfg.lua:1220]: I agree, but I would look into it separately from these changes, if you don't mind. I'm kinda feature-thinking now, not refactoring-thinking.

**Comment by Totktonada** [comment]
It is on top of a fresh #10859 now.

File: src/box/lua/config/applier/box_cfg.lua [hunk 3]
```diff
@@ -1024,6 +1010,138 @@ end
...
+        -- Don't do anything on early database loading stages or
+        -- if we're in the 'orphan' status.
+        --
+        -- The latter anyway assumes RO.
+        if status.status ~= 'running' then
+            return
+        end
+
+        -- TODO: Move synchro queue owner together with the RW
+        -- mode.
```
[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/lua/config/applier/box_cfg.lua]: Rewrote it as a question for later consideration.

```diff
diff --git a/src/box/lua/config/applier/box_cfg.lua b/src/box/lua/config/applier/box_cfg.lua
index bcdb493fa9..65ed6bd207 100644
--- a/src/box/lua/config/applier/box_cfg.lua
+++ b/src/box/lua/config/applier/box_cfg.lua
@@ -1044,8 +1044,11 @@ local function start_native_bs_watcher()
             return
         end
 
-        -- TODO: Move synchro queue owner together with the RW
-        -- mode.
+        -- NB: Should we move the synchro queue owner together
+        -- with the RW mode? It is done automatically with
+        -- replication.failover=election. Should we provide a
+        -- support for the synchronous replication in other
+        -- failover modes?
 
         -- Move the bootstrap leader flag together with the RW
         -- mode.
```

**Comment by Totktonada** [comment]
Rebased after PR #10859 lands to `master`.

**Review by maryiaLichko — APPROVED** [review]

File: test/config-luatest/native_bootstrap_strategy_test.lua [hunk 4]
```diff
@@ -45,11 +50,178 @@ local function verify_bootstrap_leader(cluster, exp_leader)
...
+    -- Ensure that now it is the bootstrap leader.
+    wait(function()
+        cluster[new_leader]:exec(function()
+            local leader_uuid =
+                box.space._schema:get({'bootstrap_leader_uuid'})[2]
+            t.assert_equals(leader_uuid, box.info.uuid)
+        end)
+    end)
+end
+
```
Comment (georgiy-belyanin) [inline test/config-luatest/native_bootstrap_strategy_test.lua:256]: Minor: I suppose `verify_bootstrap_leader` might be reused here if it's supplied with the check the server is alive.

Feel free to ignore.

File: changelogs/unreleased/bootstrap-strategy-native.md [hunk 5]
```diff
@@ -0,0 +1,3 @@
+## feature/config
+
+* Added `replication.bootstrap_strategy` = `native` (gh-10857).
```
Comment (georgiy-belyanin) [inline changelogs/unreleased/bootstrap-strategy-native.md:3]: I suppose doc request should have title "`replication.bootstrap_strategy` = `native`" instead of Title: "`replication.bootstrap_strategy` = `supervised`"

File: test/config-luatest/native_bootstrap_strategy_test.lua (hunk 4 above)
Comment (Totktonada) [reply test/config-luatest/native_bootstrap_strategy_test.lua]: Good idea. Changed this way:

```diff
diff --git a/test/config-luatest/native_bootstrap_strategy_test.lua b/test/config-luatest/native_bootstrap_strategy_test.lua
index c8f17dca71..2e8c987a10 100644
--- a/test/config-luatest/native_bootstrap_strategy_test.lua
+++ b/test/config-luatest/native_bootstrap_strategy_test.lua
@@ -32,6 +32,10 @@ local function verify_bootstrap_leader(cluster, exp_leader)
     local uuid2name = {}
     local leader_uuid
     cluster:each(function(server)
+        if server.process == nil then
+            return
+        end
+
         local uuid, name, leader_uuid_tmp = server:exec(function()
             local leader_uuid_tmp =
                 box.space._schema:get({'bootstrap_leader_uuid'})[2]
@@ -213,13 +217,7 @@ g.test_failover_off_multimaster = function()
     end)
 
     -- Ensure that now it is the bootstrap leader.
-    wait(function()
-        cluster[new_leader]:exec(function()
-            local leader_uuid =
-                box.space._schema:get({'bootstrap_leader_uuid'})[2]
-            t.assert_equals(leader_uuid, box.info.uuid)
-        end)
-    end)
+    wait(verify_bootstrap_leader, cluster, new_leader)
 end
 
 g.test_failover_manual = function()
```

File: changelogs/unreleased/bootstrap-strategy-native.md (hunk 5 above)
Comment (Totktonada) [reply changelogs/unreleased/bootstrap-strategy-native.md:3]: Wow, really. Thanks!

Fixed.

File: test/config-luatest/native_bootstrap_strategy_test.lua (hunk 4 above)
Comment (georgiy-belyanin) [reply test/config-luatest/native_bootstrap_strategy_test.lua]: Nice

File: src/box/lua/config/applier/box_cfg.lua (hunk 1 above)
Comment (georgiy-belyanin) [reply src/box/lua/config/applier/box_cfg.lua]: Thanks. Closing and the related logic will be added in #11381

**Review by georgiy-belyanin — APPROVED** [review]
