### PR TITLE
memtx: fix MVCC breaking TREE index iterators

### LINKED ISSUE #6344: Vshard rebalancing fails with MVCC on
**Bug description**

Vshard rebalancing fails to complete when MVCC engine in enabled.

```console
$ tarantool -v
Tarantool 2.8.1-199-g2c35568af
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/tarantool-install -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Use this cartridge branch:

https://github.com/tarantool/cartridge/tree/reproduce-rebalancer-failure

```bash
git clone git@github.com:tarantool/cartridge.git -b  reproduce-rebalancer-failure
cd cartridge
CMAKE_DUMMY_WEBUI=true tarantoolctl rocks make
tarantoolctl rocks install luatest
.rocks/bin/luatest -v -c integration.rebalancing.test
```

```console
$ .rocks/bin/luatest -v -c integration.rebalancing.test

sA-1 | 2021-08-18 13:00:21.400 [959018] main/141/vshard.rebalancer I> The cluster is balanced ok. Schedule next rebalancing after 3600.000000 seconds
sA-1 | 2021-08-18 13:00:21.503 [959018] main/141/vshard.rebalancer I> The cluster is balanced ok. Schedule next rebalancing after 3600.000000 seconds
sA-1 | 2021-08-18 13:00:21.606 [959018] main/141/vshard.rebalancer I> The cluster is balanced ok. Schedule next rebalancing after 3600.000000 seconds
sA-1 | 2021-08-18 13:00:21.709 [959018] main/141/vshard.rebalancer I> The cluster is balanced ok. Schedule next rebalancing after 3600.000000 seconds
    integration.rebalancing.test ... (5.084s) fail 
...m5RqcmoA/cartridge/test/integration/rebalancing_test.lua:152: expected: 0, actual: 21 

```

<details>
<summary>Test source</summary>

```lua
    g.sA1:call('vshard.storage.rebalancer_enable')
    helpers.retrying({}, function()
        g.sA1:call('vshard.storage.rebalancer_wakeup')

        t.assert_equals(g.sA1:call('vshard.storage.buckets_count'), 0)
        t.assert_equals(g.sB1:call('vshard.storage.buckets_count'), 300)
        t.assert_equals(g.sA1:call('box.space.test:len'), 0)
        t.assert_equals(g.sB1:call('box.space.test:len'), 300)
    end)
```

https://github.com/tarantool/cartridge/blob/fcc5bef36126bfcd9e11cffd08ff26f2539d8533/test/integration/rebalancing_test.lua#L146-L154

</details>

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
The MVCC transaction manager story garbage collection introduced a
subtle code dependency: TREE index iterators can get broken (see
definition of “broken” at struct bps_tree_iterator), because the
elements they are referencing can change during story garbage
collection.

We coined the notion “MVCC TRANSACTION MANAGER STORY GARBAGE
COLLECTION BOUND” to refer to this issue explicitly: iterators must not
be used after this point in code.

Closes #6344

### CODE REVIEW

**Comment by Totktonada** [comment]
Can it also be related to #6786? Or it is only about MVCC?

**Comment by CuriousGeorgiy** [comment]
@Totktonada AFAIC, this only affects memtx TREE indexes with MVCC enabled.

File: src/box/memtx_tree.cc [hunk 1]
```diff
@@ -611,15 +634,38 @@ tree_iterator_start(struct iterator *iterator, struct tuple **ret)
 		 * last position in the tree, that's what we need.
 		 */
 		memtx_tree_iterator_prev(tree, &it->tree_iterator);
+		res = memtx_tree_iterator_get_elem(tree, &it->tree_iterator);
+	}
+
+	/*
+	 * We need to use value semantics here, as the result's underlying data
```
Comment (alyapunov) [inline src/box/memtx_tree.cc:641]: Is it possible to just set here `it->current = *res;` ?

Comment (alyapunov) [reply src/box/memtx_tree.cc:641]: And set `*ret` here too. It seem that it would be shorter and will not require that comment.

Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:641]: No, it’s not possible: see line 656 and corresponding branch.

**Review by Korablev77 — COMMENTED** [review]
Overall LGTM, just a few nits to be optionally fixed

File: src/box/memtx_tree.cc [hunk 2]
```diff
@@ -385,12 +412,15 @@ tree_iterator_next_equal_base(struct iterator *iterator, struct tuple **ret)
 	}
 	struct index *idx = iterator->index;
 	struct space *space = space_by_id(iterator->space_id);
+	struct tuple *nearby_tuple = res == NULL ? NULL : res->tuple;
```
Comment (Korablev77) [inline src/box/memtx_tree.cc:415]: What's the point of moving nearby_tuples var?

File: src/box/memtx_tree.cc [hunk 3]
```diff
@@ -439,6 +469,9 @@ tree_iterator_prev_equal_base(struct iterator *iterator, struct tuple **ret)
 	}
 	struct index *idx = iterator->index;
 	struct space *space = space_by_id(iterator->space_id);
+
+/***********MVCC TRANSACTION MANAGER STORY GARBAGE COLLECTION BOUND************/
```
Comment (Korablev77) [inline src/box/memtx_tree.cc:473]: I'd move this comment right after brace closing if else block. Also I'd change these lines to "start of the bound" and "end of the bound" to improve their readability:)

File: src/box/memtx_tree.cc [hunk 4]
```diff
@@ -611,15 +634,38 @@ tree_iterator_start(struct iterator *iterator, struct tuple **ret)
...
+		res = memtx_tree_iterator_get_elem(tree, &it->tree_iterator);
+	}
+
+	/*
+	 * We need to use value semantics here, as the result's underlying data
+	 * can change after we cross the “MVCC TRANSACTION MANAGER STORY GARBAGE
+	 * COLLECTION BOUND”.
+	 */
+	struct memtx_tree_data<USE_HINT> res_val;
+	if (res != NULL) {
```
Comment (Korablev77) [inline src/box/memtx_tree.cc:646]: Nit: afaik one-like body is not enclosed with braces

File: src/box/memtx_tree.cc (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:415]: It accesses the res variable (pointer to BPS tree element): it was decided to move all such operations before the “MVCC TRANSACTION MANAGER STORY GARBAGE COLLECTION BOUND” line to get rid of possible garbage collection side effects.

File: src/box/memtx_tree.cc (hunk 4 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:646]: I would argue about this: in my experience, there were several times, when I encountered a bug, caused by missing if-block braces, and the assumption, that all the indented lines after the if will get executed — I would rather be explicit and verbose. 

> Better safe than sorry.

File: src/box/memtx_tree.cc (hunk 2 above)
Comment (Korablev77) [reply src/box/memtx_tree.cc:415]: Ok, get it

**Review by Korablev77 — APPROVED** [review]

File: src/box/memtx_tree.cc [hunk 5]
```diff
@@ -303,6 +324,9 @@ tree_iterator_next_base(struct iterator *iterator, struct tuple **ret)
 	}
 	struct index *idx = iterator->index;
 	struct space *space = space_by_id(iterator->space_id);
+
+/***********MVCC TRANSACTION MANAGER STORY GARBAGE COLLECTION BOUND************/
+
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:329]: /cc @Korablev77

[the remark this answers is not in the document]
Comment (alyapunov) [reply src/box/memtx_tree.cc:329]: `memtx_tx_track_gap` should not depend on `tree_iterator`.

File: src/box/memtx_tree.cc (hunk 4 above)
Comment (alyapunov) [reply src/box/memtx_tree.cc:646]: We should not argue about code style in PR. There's a [directive](https://www.tarantool.io/en/doc/latest/dev_guide/c_style_guide/):
> Do not unnecessarily use braces where a single statement will do.

Please respect and fix.

**Review by alyapunov — CHANGES_REQUESTED** [review]

File: src/box/memtx_tree.cc (hunk 3 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc]: > I'd move this comment right after brace closing if else block
Could you elaborate, please? I don't understand the point.

> Also I'd change these lines to "start of the bound" and "end of the bound" to improve their readability
Fixed.

File: src/box/memtx_tree.cc (hunk 4 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc]: Fixed.

File: src/box/memtx_tree.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (locker) [reply src/box/memtx_tree.cc]: FWIW we don't need to make `memtx_tx_track_gap` depend on `tree_iterator`. We could instead add an inline wrapper function to track gaps specially for the tree iterator - `tree_iterator_track_gap`. The wrapper function would nullify the iterator pointer and then call `memtx_tx_track_gap` as usual.

**Review by alyapunov — APPROVED** [review]

**Comment by alyapunov** [comment]
Actually I don't like the patch, it seems that the code becomes more chaotic. But I didn't invent how make it clean and correct with small amount of changes. So I think we need this bugfix now, and more refactoring in future.

**Comment by CuriousGeorgiy** [comment]
> Nit: The problem is that value should be called nearby_tuple only in case *ret == NULL.. In the other case *ret != NULL this value - is the tuple itself. NIT.

Removed this change.

**Comment by CuriousGeorgiy** [comment]
> Actually I don't like the patch, it seems that the code becomes more chaotic. 

I agree: but as practice shows, if not the attention drawn, we would have stumbled against the same issue in #6798.


> So I think we need this bugfix now, and more refactoring in future.

Indeed.
