### PR TITLE
Alyapunov/gh 5628 fix bug in tx manager

### LINKED ISSUE #5972: space:count() does not work with mvcc
Here is a couple of tests. First one shows that rows created in a transaction are visible everywhere via `count()`:
```Lua
fiber = require('fiber')
box.cfg{memtx_use_mvcc_engine = true}
s = box.schema.create_space('test')
_ = s:create_index('pk')

fiber.create(function()
    box.begin()
    s:replace{1}
    print(s:count())
    fiber.sleep(10000000)
end) print(s:count())
```
Both print `1`. But it should be `1` in the transaction, and `0` out of it.

The second test shows that even inside of the transaction it is possible to see the wrong `count()`:
```Lua
fiber = require('fiber')
box.cfg{memtx_use_mvcc_engine = true}
s = box.schema.create_space('test')
_ = s:create_index('pk')
s:replace{1}

fiber.create(function()
    box.begin()
    s:delete{1}
    print(s:count())
    fiber.sleep(10000000)
end) print(s:count())
```
Both print `1` again. But it should be `0` in the transaction.

### PR DESCRIPTION
**Pull request by alyapunov**
Lost of issues solved.
Fixes #5972
Part of  #5628

### CODE REVIEW

File: src/box/index.cc [hunk 1]
```diff
@@ -693,12 +695,13 @@ generic_index_get(struct index *index, const char *key,
 int
 generic_index_replace(struct index *index, struct tuple *old_tuple,
 		      struct tuple *new_tuple, enum dup_replace_mode mode,
-		      struct tuple **result)
+		      struct tuple **result, struct tuple **successor)
```
Comment (EvgenyMekhanik) [inline src/box/index.cc:698]: Here and in all other places i don't see where successr field is used.

**Review by EvgenyMekhanik — APPROVED** [review]
