### PR TITLE
[2.11] sql: properly check result of decimal parsing

### LINKED ISSUE #9469: Error in SQL if too big decimal is parsed
Reproducer:
```
tarantool> box.execute([[SELECT 111111111111111111111111111111111111111.0;]])
tarantool: ./src/lua/error.c:111: luaT_push_nil_and_error: Assertion `e != NULL' failed.
Aborted (core dumped)
```

Also:
```
tarantool> box.execute([[CREATE TABLE T(i DECIMAL PRIMARY KEY DEFAULT(111111111111111111111111111111111111111.0);]])
tarantool: ./src/lib/core/decimal.c:446: decimal_pack: Assertion `tmp == data' failed.
Aborted (core dumped)
```

The problem was discovered by fuzzer.

### PR DESCRIPTION
**Pull request by ImeevMA**
This patch fixes a crash that can occur when SQL parses a decimal literal that represents a number greater than or equal to 10^38.

Closes #9469

NO_DOC=bugfix

(cherry picked from commit 05551a556bbca9e4aa5fa910e1b62ea67e6177e6)

### CODE REVIEW

**Review by xuniq — APPROVED** [review]

File: test/sql-luatest/gh_9469_too_big_decimals_test.lua [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+        local dec = '111111111111111111111111111111111111111.0'
+        local sql = ([[SELECT %s;]]):format(dec)
+        local exp = ([[Invalid decimal: '%s']]):format(dec)
+        local res, err = box.execute(sql)
+        t.assert(res == nil)
+        t.assert_equals(err.message, exp)
+
+        sql = ([[SELECT -%s;]]):format(dec)
+        res, err = box.execute(sql)
+        t.assert(res == nil)
```
Comment (ochaplashkin) [inline test/sql-luatest/gh_9469_too_big_decimals_test.lua:26]: You can use this in the future
```suggestion
        t.assert_not(res)
```

**Review by ochaplashkin — APPROVED** [review]

File: test/sql-luatest/gh_9469_too_big_decimals_test.lua (hunk 1 above)
Comment (ImeevMA) [reply test/sql-luatest/gh_9469_too_big_decimals_test.lua:26]: Thanks, good to know.

**Review by igormunkin — APPROVED** [review]
@ImeevMA, thanks for the patch! LGTM.
