### PR TITLE
vinyl: fix deferred delete reader not aborted on WAL error

### LINKED ISSUE #11969: vinyl: rollback may cause duplicate in secondary index with deferred deletes
Consider the script:
```lua
-- Cleanup.
os.execute('rm 00*')

fiber = require('fiber')

box.cfg{vinyl_defer_deletes=true}

box.schema.space.create("test", {engine = 'vinyl'})
box.space.test:format{{'a', type='unsigned'}, {'b', type='unsigned'}}
box.space.test:create_index("pk", {parts={{'a'}}})
box.space.test:create_index("sk", {parts={{'b'}}, unique=true})

box.space.test:insert{1, 1}
box.space.test:insert{2, 2}

-- block WAL queue
box.cfg{wal_queue_max_size=1}
box.begin()
	box.space.test:insert{10000, 10000}
box.error.injection.set('ERRINJ_WAL_DELAY', true)
box.commit({wait='none'})

-- Delete tuple with secondary key `2`. It will be rolled back due to WAL error.
f1 = fiber.create(function()
	box.space.test:delete(2)
end)
f1:set_joinable(true)

-- Write a tuple with secondary key `2`.
f2 = fiber.create(function()
	box.begin()
		box.space.test:replace{1, 2}
		fiber.sleep(2)
	box.commit()
end)
f2:set_joinable(true)

box.error.injection.set('ERRINJ_WAL_IO', true)
box.error.injection.set('ERRINJ_WAL_DELAY', false)

local ok, err = f1:join()
print('f1: ', ok, err)

box.error.injection.set('ERRINJ_WAL_IO', false)

ok, err = f2:join()
print('f2: ', ok, err)

print(require('yaml').encode(box.space.test.index.sk:select{}))

box.space.test:drop()
os.exit()
```

The result:
```
f2: 	true	nil
---
- [1, 2]
- [2, 2]
- [10000, 10000]
...
```

We observe a duplicate in unique index!

(Actually, this is adaptation of https://github.com/tarantool/tarantool/issues/11660 for vinyl).

### PR DESCRIPTION
**Pull request by locker**
With deferred DELETEs enabled, `space.delete()` writes the DELETE statement to the primary index write set only while statements for secondary indexes are generated either when the transaction is prepared (if the deleted tuple is found in the memory layer or cache) or on compaction.

Now imagine the following scenario:

1. There are tuples `{1,1}` and `{2,2}` in the memory layer of a space with enabled deferred DELETEs, the primary index over field 1, and a unique secondary index over field 2.
2. A transaction deletes `{2,2}` by the primary key and blocks on WAL. When the statement is executed, the DELETE statement is written only to the primary index write set because of enabled deferred DELETEs, but when the transaction is prepared (`vy_tx_prepare()`), the corresponding statement for the secondary index is generated because the deleted tuple is found in the in-memory layer, see `vy_tx_handle_deferred_delete()`.
3. In the meantime, another transaction replaces `{1,1}` with `{1,2}` and yields execution. It doesn't violate the unique constraint of the secondary index because `{2,2}` was deleted although not yet confirmed.
4. Imagine a transient WAL error happens and the first transaction is rolled back. The second transaction must be aborted too in this case because it implicitly read the DELETE statement prepared but not confirmed by the first transaction, but it is successfully committed, resulting in the unique constraint violation!

When a transaction is rolled back due to a WAL write error, we do abort all transactions that read statements prepared by it, see `vy_tx_rollback_after_prepare()`, but to do that, we iterate over statements that were inserted into the transaction write set. The problem is, we don't insert deferred DELETE statements generated when a transaction is prepared in `vy_tx_handle_deferred_delete()` into the write set because we don't need them for lookups at that point. As a result, we don't abort transactions that read deferred DELETE statements from secondary indexes.

Let's fix this issue by aborting all dependent transactions for each statement inserted/deleted from the LSM tree. We already loop over all transaction statements in `vy_tx_rollback_after_prepare()` and `vy_tx_prepare` so there's no need to iterate over the write set entries separately.

There's another related issue that may result in the same anomaly. The problem is that we don't track the non-matching primary index statement in the transaction write set when we look up the full tuple by a key found in a secondary index, see `vy_get_by_secondary_tuple()`. Normally, this is fine because we don't care if the primary index statement is overwritten - we never returned it to the user. However, if the statement hasn't been confirmed, it may still be rolled back due to a WAL error reinstantiating the tuple matching the secondary index key and making the lookup invalid. Note that this may happen only if generation of the deferred DELETE is postponed to compaction. Let's fix this issue by tracking unconfirmed primary index statements in `vy_get_by_secondary_tuple()` even if they don't match the secondary index key.

Closes #11969

### CODE REVIEW

File: src/box/vy_tx.c [hunk 1]
```diff
@@ -716,6 +709,7 @@ vy_tx_prepare(struct vy_tx *tx)
 		if (vy_lsm_set(lsm, v->mem, v->entry, region_stmt) != 0)
 			return -1;
 		v->region_stmt = *region_stmt;
+		vy_tx_send_readers_to_read_view(tx, v);
```
Comment (drewdzzz) [inline src/box/vy_tx.c:712]: Such test modification:
```diff
diff --git a/test/vinyl-luatest/gh_11969_deferred_delete_reader_abort_on_wal_error_test.lua b/test/vinyl-luatest/gh_11969_deferred_delete_reader_abort_on_wal_error_test.lua
index b08e5653bd..e22f687bb8 100644
--- a/test/vinyl-luatest/gh_11969_deferred_delete_reader_abort_on_wal_error_test.lua
+++ b/test/vinyl-luatest/gh_11969_deferred_delete_reader_abort_on_wal_error_test.lua
@@ -42,6 +42,7 @@ g.test_deferred_delete_reader_abort_on_wal_error = function(cg)
         s:create_index('secondary', {parts = {2, 'unsigned'}})
         s:insert({1, 1})
         s:insert({2, 2})
+        box.snapshot()
 
         box.error.injection.set('ERRINJ_WAL_DELAY', true)
 
@@ -61,8 +62,9 @@ g.test_deferred_delete_reader_abort_on_wal_error = function(cg)
 
         box.error.injection.set('ERRINJ_WAL_WRITE', false)
         ch:put(true)
-        t.assert_error_covers({name = 'TRANSACTION_CONFLICT'}, join, f2)
+        -- t.assert_error_covers({name = 'TRANSACTION_CONFLICT'}, join, f2)
 
+        box.snapshot()
         local expected = {{1, 1}, {2, 2}}
         t.assert_equals(s.index.primary:select(), expected)
         t.assert_equals(s.index.secondary:select(), expected)
```

Leads to such result:
```
expected: {{1, 1}, {2, 2}}
actual: {[1, 2], [2, 2]}
```

(Or transaction conflict check fails if it wouldn't be commented out).

I think we should handle deferred deletion of data from disk in this PR as well.

Comment (locker) [reply src/box/vy_tx.c:712]: Good catch, thanks! The problem here is that we don't track primary index statements that don't match the secondary index key in `vy_get_by_secondary_tuple()`. Normally, this is okay because we don't care if this statement is updated - we never returned it to the user. However, if the statement hasn't been confirmed, it may still be rolled back due to a WAL error, in which case the tuple matching the secondary key may become visible. Fixed in the same commit with a comment and added a test case.

<details><summary>fix</summary>

```diff
diff --git a/src/box/vinyl.c b/src/box/vinyl.c
index 92f981f3de9d..81a0d437dfe9 100644
--- a/src/box/vinyl.c
+++ b/src/box/vinyl.c
@@ -1412,6 +1412,17 @@ vy_get_by_secondary_tuple(struct vy_lsm *lsm, struct vy_tx *tx,
 		}
 	}
 	if (!match) {
+		/*
+		 * If the primary index statement deleting the target
+		 * key from the secondary index hasn't been confirmed,
+		 * we must track it in the transaction write set because
+		 * it may still be rolled back due to a WAL error, in which
+		 * case the overwritten tuple matching the secondary index
+		 * key can be reinstantiated.
+		 */
+		if (tx != NULL && pk_entry.stmt != NULL &&
+		    vy_stmt_is_prepared(pk_entry.stmt))
+			vy_tx_track_point(tx, lsm->pk, pk_entry);
 		/*
 		 * If a tuple read from a secondary index doesn't
 		 * match the tuple corresponding to it in the
```

</details>

File: src/box/vy_tx.c [hunk 2]
```diff
@@ -618,21 +618,14 @@ vy_tx_prepare(struct vy_tx *tx)
 		return 0;
 	assert(!vy_tx_is_in_read_view(tx));
 	assert(tx->read_view == &xm->global_read_view);
-
-	/** Send to read view read intersection and abort write intersection. */
-	struct txv *v;
-	struct write_set_iterator it;
-	write_set_ifirst(&tx->write_set, &it);
-	while ((v = write_set_inext(&it)) != NULL)
-		vy_tx_send_readers_to_read_view(tx, v);
```
Comment (drewdzzz) [inline src/box/vy_tx.c:627]: I wonder why did we iterate over write set at all if we already iterate over all the statements just below.

File: src/box/vinyl.c [hunk 3]
```diff
@@ -1412,6 +1412,17 @@ vy_get_by_secondary_tuple(struct vy_lsm *lsm, struct vy_tx *tx,
 		}
 	}
 	if (!match) {
+		/*
+		 * If the primary index statement deleting the target
+		 * key from the secondary index hasn't been confirmed,
+		 * we must track it in the transaction write set because
```
Comment (drewdzzz) [inline src/box/vinyl.c]: Nit: isn't it read set, not write set?

Comment (locker) [reply src/box/vinyl.c]: Read set, of course. Fixed, thanks!

File: src/box/vy_tx.c (hunk 2 above)
Comment (locker) [reply src/box/vy_tx.c:627]: Historical reasons I guess. Initially, we applied statements while iterating over the write set index. Then we introduced the write log list in a0d27684a6d6ab9299398f4ea5a9462ee15deefe but still continued using the write set index for aborting conflicting transactions. Maybe because we thought the code would look more readable that way, don't know.

**Review by lenkis — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 3.2, 3.3, 3.4, 3.5.
