### PR TITLE
vinyl: fix `vinyl_memory` overrun on recovery

### LINKED ISSUE #12390: vinyl may exceed vinyl memory limit on recovery
First let's patch vinyl a bit so we able to see vinyl memory watermarks:

```diff
--- a/src/box/vy_quota.c
+++ b/src/box/vy_quota.c
@@ -292,6 +292,7 @@ vy_quota_force_use(struct vy_quota *q, enum vy_quota_consumer_type type,
 void
 vy_quota_release(struct vy_quota *q, size_t size)
 {
+       say_info("---------------qouta before release -----------------%zd", q->used);
        /*
         * Don't use vy_quota_do_unuse(), because it affects
         * the rate limit state.
```

Now let's run next script to create test setup:
```lua
os.execute('rm -rf 0000* 512')
box.cfg{
    vinyl_memory = 1024 * 1024 * 1024,
    vinyl_max_tuple_size = 2 * 1024 * 1024,
}

local s = box.schema.create_space('test', {engine = 'vinyl'})
s:create_index('pk')

local d = string.rep('x', 1024 * 1024)

for i = 1, 768 do
    s:insert({i, d})
end

os.exit()
```

<details>
<summary>test logs</summary>

```
2026-03-10 10:39:14.959 [317633] main/104/test2.lua main.cc:522 I> Tarantool 3.7.0-entrypoint-112-g7c0637e748 Linux-x86_64-Debug
2026-03-10 10:39:14.959 [317633] main/104/test2.lua main.cc:525 I> log level 5 (INFO)
2026-03-10 10:39:14.959 [317633] main/104/test2.lua gc.c:132 I> wal/engine cleanup is paused
2026-03-10 10:39:14.960 [317633] main/104/test2.lua tuple.c:410 I> mapping 268435456 bytes for memtx tuple arena...
2026-03-10 10:39:14.960 [317633] main/104/test2.lua memtx_engine.cc:2037 I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2026-03-10 10:39:14.960 [317633] main/104/test2.lua tuple.c:410 I> mapping 1073741824 bytes for vinyl tuple arena...
2026-03-10 10:39:14.967 [317633] main/104/test2.lua box.cc:2600 I> update replication_synchro_quorum = 1
2026-03-10 10:39:14.967 [317633] main/104/test2.lua box.cc:2566 I> update replication_linearizable_quorum = 1
2026-03-10 10:39:14.967 [317633] main/104/test2.lua box.cc:3502 I> The option replication_synchro_queue_max_size will actually take effect after the recovery is finished
2026-03-10 10:39:14.967 [317633] main/104/test2.lua box.cc:5695 I> instance uuid fc73d433-2339-4f5b-bb80-b90d223b0cbe
2026-03-10 10:39:14.967 [317633] main/104/test2.lua memtx_engine.cc:932 I> initializing an empty data directory
2026-03-10 10:39:14.992 [317633] main/104/test2.lua replication.cc:610 I> assigned id 1 to replica fc73d433-2339-4f5b-bb80-b90d223b0cbe
2026-03-10 10:39:14.992 [317633] main/104/test2.lua box.cc:2600 I> update replication_synchro_quorum = 1
2026-03-10 10:39:14.992 [317633] main/104/test2.lua box.cc:2566 I> update replication_linearizable_quorum = 1
2026-03-10 10:39:14.992 [317633] main/104/test2.lua alter.cc:4277 I> replicaset uuid f8ba44b4-a106-46f9-aaf4-012095aac896
2026-03-10 10:39:14.994 [317633] snapshot/101/main memtx_engine.cc:1346 I> saving snapshot `./00000000000000000000.snap.inprogress'
2026-03-10 10:39:15.005 [317633] snapshot/101/main memtx_engine.cc:1509 I> done
2026-03-10 10:39:15.006 [317633] main/104/test2.lua box.cc:687 I> leaving waiting_for_own_rows mode
2026-03-10 10:39:15.006 [317633] main/104/test2.lua box.cc:6221 I> ready to accept requests
2026-03-10 10:39:15.006 [317633] main/105/gc gc.c:320 I> wal/engine cleanup is resumed
2026-03-10 10:39:15.006 [317633] main/104/test2.lua/box.load_cfg load_cfg.lua:1001 I> set 'vinyl_memory' configuration option to 1073741824
2026-03-10 10:39:15.006 [317633] main/104/test2.lua/box.load_cfg load_cfg.lua:1001 I> set 'vinyl_max_tuple_size' configuration option to 2097152
2026-03-10 10:39:15.006 [317633] main/106/checkpoint_daemon gc.c:614 I> scheduled next checkpoint for Tue Mar 10 12:04:00 2026
2026-03-10 10:39:15.007 [317633] main/104/test2.lua box.cc:449 I> box switched to rw
2026-03-10 10:40:05.991 [317633] main/104/test2.lua vy_regulator.c:117 I> dumping 536938370 bytes, expected rate 10.0 MB/s, ETA 51.2 s, write rate (avg/max) 10.0/12.0 MB/s
2026-03-10 10:40:05.995 [317633] vinyl.dump.0/102/task vy_run.c:2213 I> writing `./512/0/00000000000000000002.run'
2026-03-10 10:40:06.634 [317633] vinyl.dump.0/102/task vy_run.c:2116 I> writing `./512/0/00000000000000000002.index'
2026-03-10 10:40:06.635 [317633] main/109/vinyl.scheduler vy_regulator.c:295 I> dumped 534841145 bytes in 0.6 s, rate 789.4 MB/s
2026-03-10 10:40:06.635 [317633] main/109/vinyl.scheduler vy_quota.c:295 I> ---------------qouta before release -----------------543279218
```

</details>

Finally let's run Tarantool again to recover it's state but with lower `vinyl_memory` (default is 128 MiB):

<details>
<summary>recovery logs</summary>

```
 tarantool> box.cfg{vinyl_max_tuple_size = 2 * 1024 * 1024}
2026-03-10 10:47:31.257 [318000] main/104/interactive main.cc:522 I> Tarantool 3.7.0-entrypoint-112-g7c0637e748 Linux-x86_64-Debug
2026-03-10 10:47:31.257 [318000] main/104/interactive main.cc:525 I> log level 5 (INFO)
2026-03-10 10:47:31.257 [318000] main/104/interactive gc.c:132 I> wal/engine cleanup is paused
2026-03-10 10:47:31.260 [318000] main/104/interactive tuple.c:410 I> mapping 268435456 bytes for memtx tuple arena...
2026-03-10 10:47:31.260 [318000] main/104/interactive memtx_engine.cc:2037 I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
2026-03-10 10:47:31.260 [318000] main/104/interactive tuple.c:410 I> mapping 134217728 bytes for vinyl tuple arena...
2026-03-10 10:47:31.261 [318000] main/104/interactive/box.upgrade upgrade.lua:1602 I> Recovering snapshot with schema version 3.3.0
2026-03-10 10:47:31.266 [318000] main/104/interactive box.cc:2600 I> update replication_synchro_quorum = 1
2026-03-10 10:47:31.266 [318000] main/104/interactive box.cc:2566 I> update replication_linearizable_quorum = 1
2026-03-10 10:47:31.266 [318000] main/104/interactive box.cc:3502 I> The option replication_synchro_queue_max_size will actually take effect after the recovery is finished
2026-03-10 10:47:31.266 [318000] main/104/interactive box.cc:5780 I> instance uuid fc73d433-2339-4f5b-bb80-b90d223b0cbe
2026-03-10 10:47:31.266 [318000] main/104/interactive box.cc:5812 I> instance vclock {1: 770}
2026-03-10 10:47:31.267 [318000] main/104/interactive memtx_engine.cc:393 I> recovery start
2026-03-10 10:47:31.267 [318000] main/104/interactive memtx_engine.cc:398 I> recovering from `./00000000000000000000.snap'
2026-03-10 10:47:31.274 [318000] main/104/interactive alter.cc:4277 I> replicaset uuid f8ba44b4-a106-46f9-aaf4-012095aac896
2026-03-10 10:47:31.294 [318000] main/104/interactive replication.cc:610 I> assigned id 1 to replica fc73d433-2339-4f5b-bb80-b90d223b0cbe
2026-03-10 10:47:31.294 [318000] main/104/interactive box.cc:2600 I> update replication_synchro_quorum = 1
2026-03-10 10:47:31.294 [318000] main/104/interactive box.cc:2566 I> update replication_linearizable_quorum = 1
2026-03-10 10:47:31.294 [318000] main/104/interactive recovery.cc:373 I> recover from `./00000000000000000000.xlog'
2026-03-10 10:47:31.796 [318000] main/104/interactive recovery.cc:162 I> done `./00000000000000000000.xlog'
2026-03-10 10:47:31.796 [318000] main/104/interactive recovery.cc:373 I> recover from `./00000000000000000770.xlog'
2026-03-10 10:47:31.796 [318000] main/104/interactive recovery.cc:162 I> done `./00000000000000000770.xlog'
2026-03-10 10:47:31.797 [318000] main/104/interactive vy_regulator.c:117 I> dumping 268494722 bytes, expected rate 10.0 MB/s, ETA 25.6 s, write rate (avg/max) 0.0/0.0 MB/s
2026-03-10 10:47:31.798 [318000] main/104/interactive box.cc:687 I> leaving waiting_for_own_rows mode
2026-03-10 10:47:31.798 [318000] main/104/interactive box.cc:6221 I> ready to accept requests
2026-03-10 10:47:31.798 [318000] main/104/interactive box.cc:674 I> leaving orphan mode
2026-03-10 10:47:31.799 [318000] main/105/gc gc.c:320 I> wal/engine cleanup is resumed
2026-03-10 10:47:31.799 [318000] main/104/interactive/box.load_cfg load_cfg.lua:1001 I> set 'vinyl_max_tuple_size' configuration option to 2097152
2026-03-10 10:47:31.799 [318000] main/106/checkpoint_daemon gc.c:614 I> scheduled next checkpoint for Tue Mar 10 11:48:37 2026
2026-03-10 10:47:31.799 [318000] main/104/interactive box.cc:449 I> box switched to rw
2026-03-10 10:47:31.799 [318000] vinyl.dump.0/102/task vy_run.c:2213 I> writing `./512/0/00000000000000000004.run'
2026-03-10 10:47:32.073 [318000] vinyl.dump.0/102/task vy_run.c:2116 I> writing `./512/0/00000000000000000004.index'
2026-03-10 10:47:32.075 [318000] main/109/vinyl.scheduler vy_regulator.c:295 I> dumped 268494722 bytes in 0.3 s, rate 919.8 MB/s
2026-03-10 10:47:32.075 [318000] main/109/vinyl.scheduler vy_quota.c:295 I> ---------------qouta before release -----------------268494722
 tarantool> 2026-03-10 10:47:32.083 [318000] vinyl.compaction.0/102/task vy_run.c:2213 I> writing `./512/0/00000000000000000006.run'
2026-03-10 10:47:32.840 [318000] vinyl.compaction.0/102/task vy_run.c:2116 I> writing `./512/0/00000000000000000006.index'
2026-03-10 10:47:32.842 [318000] coio xlog.c:2139 I> removed ./512/0/00000000000000000002.index
2026-03-10 10:47:32.842 [318000] coio xlog.c:2139 I> removed ./512/0/00000000000000000002.run
2026-03-10 10:47:32.842 [318000] coio xlog.c:2139 I> removed ./512/0/00000000000000000004.index
2026-03-10 10:47:32.842 [318000] coio xlog.c:2139 I> removed ./512/0/00000000000000000004.run
```

</details>

According to the logs the maximal memory consumption was 256MiB. 

The issue is also related to the way we are going to enhance Tarantool backup. We will add rotated xlog to the backup without any other changes for vinyl, as a result on recovery `vinyl_memory` limit may be exceeded.

### PR DESCRIPTION
**Pull request by nshy**
Currently we start to apply memory limit only when recovery is finished. So if for example `vinyl_memory` is less than on the previous start then we can overrun the limit. Let's start quota tracking right from the beginning of the recovery.

Closes #12390

### CODE REVIEW

File: src/box/vinyl.c [hunk 1]
```diff
@@ -3023,22 +3023,12 @@ vinyl_engine_begin_initial_recovery(struct engine *engine,
...
-		 * can't consume more memory than it used before
-		 * restart and hence memory dumps are not necessary.
-		 */
 		e->status = VINYL_INITIAL_RECOVERY_LOCAL;
+		vy_env_start(e);
 	} else {
 		if (vy_log_bootstrap() != 0)
 			return -1;
-		vy_env_complete_recovery(e);
+		vy_env_start(e);
```
Comment (locker) [inline src/box/vinyl.c]: This could be placed outside if-else and inlined.

File: test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+
+        box.error.injection.set('ERRINJ_VY_RUN_WRITE', true)
+        local d = string.rep('x', 10 * 1024)
+        for i = 1, 768 do
+            s:insert({i, d})
+        end
+    end)
+    cg.server:restart({box_cfg = {vinyl_memory = 1024 * 1024}})
+    cg.server:exec(function()
+        t.assert_le(box.info.vinyl().regulator.used_max, 1024 * 1024)
```
Comment (locker) [inline test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua]: Let's check that memory has been dumped (via stats) and do one more restart and check the content.

File: src/box/vinyl.c [hunk 3]
```diff
@@ -263,6 +263,7 @@ vy_info_append_regulator(struct vy_env *env, struct info_handler *h)
 	info_append_int(h, "rate_limit", vy_quota_get_rate_limit(r->quota,
 							VY_QUOTA_CONSUMER_TX));
 	info_append_int(h, "blocked_writers", r->quota->n_blocked);
+	info_append_int(h, "used_max", r->quota->used_max);
```
Comment (locker) [inline src/box/vinyl.c]: Don't quite like the name of the new statistic. Maybe, we can come up with something better?

File: test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+
+local g = t.group()
+
+g.after_all(function(cg)
+    if cg.server ~= nil then
+        cg.server:drop()
+    end
+end)
+
+g.test_recovery_memory_limit = function(cg)
```
Comment (locker) [inline test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua:13]: We should also check that if we fail to recover for some reason, incomplete files written during recovery are removed on the next restart.

File: src/box/vinyl.c (hunk 1 above)
Comment (nshy) [reply src/box/vinyl.c]: Done.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/vinyl.c b/src/box/vinyl.c
index 11d5b12871..aec0af69e7 100644
--- a/src/box/vinyl.c
+++ b/src/box/vinyl.c
@@ -2815,17 +2815,6 @@ vy_env_delete(struct vy_env *e)
 	free(e);
 }
 
-/**
- * Start vinyl engine.
- */
-static void
-vy_env_start(struct vy_env *env)
-{
-	vy_scheduler_start(&env->scheduler);
-	vy_quota_enable(&env->quota);
-	vy_regulator_start(&env->regulator);
-}
-
 struct engine *
 vinyl_engine_new(const char *dir, size_t memory,
 		 int read_threads, int write_threads, bool force_recovery)
@@ -3004,8 +2993,10 @@ vinyl_engine_bootstrap(struct engine *engine)
 	assert(e->status == VINYL_OFFLINE);
 	if (vy_log_bootstrap() != 0)
 		return -1;
-	vy_env_start(e);
 	e->status = VINYL_ONLINE;
+	vy_scheduler_start(&e->scheduler);
+	vy_quota_enable(&e->quota);
+	vy_regulator_start(&e->regulator);
 	return 0;
 }
 
@@ -3024,14 +3015,15 @@ vinyl_engine_begin_initial_recovery(struct engine *engine,
 		if (e->recovery == NULL)
 			return -1;
 		e->status = VINYL_INITIAL_RECOVERY_LOCAL;
-		vy_env_start(e);
 	} else {
 		if (vy_log_bootstrap() != 0)
 			return -1;
-		vy_env_start(e);
 		e->status = VINYL_INITIAL_RECOVERY_REMOTE;
 		e->run_env.initial_join = true;
 	}
+	vy_scheduler_start(&e->scheduler);
+	vy_quota_enable(&e->quota);
+	vy_regulator_start(&e->regulator);
 	return 0;
 }
 
```

File: test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua (hunk 2 above)
Comment (nshy) [reply test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua]: Done.

<details>
<summary>diff</summary>

```diff
diff --git a/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua b/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
index 39cda6714c..e79b507b2b 100644
--- a/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
+++ b/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
@@ -13,17 +13,46 @@ g.test_recovery_memory_limit = function(cg)
     cg.server = server:new({box_cfg = {vinyl_memory = 10 * 1024 * 1024}})
     cg.server:start()
     cg.server:exec(function()
+        local fiber = require('fiber')
+
         local s = box.schema.create_space('test', {engine = 'vinyl'})
         s:create_index('pk')
 
         box.error.injection.set('ERRINJ_VY_RUN_WRITE', true)
         local d = string.rep('x', 10 * 1024)
+        fiber.set_max_slice(100)
         for i = 1, 768 do
             s:insert({i, d})
         end
     end)
     cg.server:restart({box_cfg = {vinyl_memory = 1024 * 1024}})
     cg.server:exec(function()
-        t.assert_le(box.info.vinyl().regulator.used_max, 1024 * 1024)
+        local fiber = require('fiber')
+
+        local stats = box.info.vinyl()
+        t.assert_le(stats.regulator.used_max, 1024 * 1024)
+        t.assert_ge(stats.scheduler.dump_count, 7)
+
+        local s = box.space.test
+        local d = string.rep('x', 10 * 1024)
+        local expected = {}
+        for i = 1, 768 do
+            table.insert(expected, {i, d})
+        end
+        fiber.set_max_slice(100)
+        t.assert_equals(s:select(), expected)
+    end)
+    cg.server:restart({box_cfg = {vinyl_memory = 1024 * 1024}})
+    cg.server:exec(function()
+        local fiber = require('fiber')
+
+        local s = box.space.test
+        local d = string.rep('x', 10 * 1024)
+        local expected = {}
+        for i = 1, 768 do
+            table.insert(expected, {i, d})
+        end
+        fiber.set_max_slice(100)
+        t.assert_equals(s:select(), expected)
     end)
 end

```

</details>

File: test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua (hunk 4 above)
Comment (nshy) [reply test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua:13]: Done. More details in the commit message.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/vy_log.c b/src/box/vy_log.c
index 6cef631865..420caaf9f1 100644
--- a/src/box/vy_log.c
+++ b/src/box/vy_log.c
@@ -791,7 +791,14 @@ vy_log_tx_flush(struct vy_log_tx *tx)
 		struct xrow_header *row = &rows[i];
 		vy_log_record_encode(record, row);
 		entry->rows[i] = row;
+		/*
+		 * Update the recovery context with records written during
+		 * recovery - we will need them for garbage collection.
+		 */
+		if (vy_log.recovery != NULL)
+			vy_recovery_process_record(vy_log.recovery, record);
 		i++;
+
 	}
 	assert(i == tx_size);
 
@@ -851,8 +858,7 @@ vy_log_flusher_f(va_list va)
 		 * Disable writes during local recovery.
 		 * See vy_log_tx_commit().
 		 */
-		if (vy_log.recovery != NULL ||
-		    stailq_empty(&vy_log.pending_tx)) {
+		if (stailq_empty(&vy_log.pending_tx)) {
 			fiber_cond_wait(&vy_log.flusher_cond);
 			continue;
 		}
@@ -1147,17 +1153,6 @@ vy_log_end_recovery(void)
 {
 	assert(vy_log.recovery != NULL);
 
-	/*
-	 * Update the recovery context with records written during
-	 * recovery - we will need them for garbage collection.
-	 */
-	struct vy_log_tx *tx;
-	stailq_foreach_entry(tx, &vy_log.pending_tx, in_pending) {
-		struct vy_log_record *record;
-		stailq_foreach_entry(record, &tx->records, in_tx)
-			vy_recovery_process_record(vy_log.recovery, record);
-	}
-
 	/* Flush all pending records. */
 	if (vy_log_flush() < 0) {
 		diag_log();
@@ -1299,17 +1294,6 @@ vy_log_tx_begin(void)
 int
 vy_log_tx_commit(void)
 {
-	/*
-	 * During recovery, we may replay records we failed to commit
-	 * before restart (e.g. drop LSM tree). Since the log isn't open
-	 * yet, simply leave them in the tx buffer to be flushed upon
-	 * recovery completion.
-	 */
-	if (vy_log.recovery != NULL) {
-		vy_log_tx_try_commit();
-		return 0;
-	}
-
 	struct vy_log_tx *tx = vy_log.tx;
 	vy_log.tx = NULL;
 	assert(tx != NULL);
diff --git a/src/box/vy_scheduler.c b/src/box/vy_scheduler.c
index 8252995add..e04d10edcb 100644
--- a/src/box/vy_scheduler.c
+++ b/src/box/vy_scheduler.c
@@ -1091,6 +1091,9 @@ vy_task_write_run(struct vy_task *task, bool no_compression)
 	struct vy_lsm *lsm = task->lsm;
 	struct vy_stmt_stream *wi = task->wi;
 
+	ERROR_INJECT_COUNTDOWN(ERRINJ_VY_RUN_WRITE_CRASH_COUNTDOWN, {
+		panic("injected crash");
+	});
 	ERROR_INJECT(ERRINJ_VY_RUN_WRITE,
 		     {diag_set(ClientError, ER_INJECTION,
 			       "vinyl dump"); return -1;});
diff --git a/src/lib/core/errinj.h b/src/lib/core/errinj.h
index e17b50dbff..ee49e4e617 100644
--- a/src/lib/core/errinj.h
+++ b/src/lib/core/errinj.h
@@ -184,6 +184,7 @@ struct errinj {
 	_(ERRINJ_VY_RUN_FILE_RENAME, ERRINJ_BOOL, {.bparam = false}) \
 	_(ERRINJ_VY_RUN_RECOVER_COUNTDOWN, ERRINJ_INT, {.iparam = -1})\
 	_(ERRINJ_VY_RUN_WRITE, ERRINJ_BOOL, {.bparam = false}) \
+	_(ERRINJ_VY_RUN_WRITE_CRASH_COUNTDOWN, ERRINJ_INT, {.iparam = -1}) \
 	_(ERRINJ_VY_RUN_WRITE_DELAY, ERRINJ_BOOL, {.bparam = false}) \
 	_(ERRINJ_VY_RUN_WRITE_STMT_TIMEOUT, ERRINJ_DOUBLE, {.dparam = 0}) \
 	_(ERRINJ_VY_SCHED_TIMEOUT, ERRINJ_DOUBLE, {.dparam = 0}) \
diff --git a/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua b/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
index e79b507b2b..0ee43fc6cb 100644
--- a/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
+++ b/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
@@ -1,9 +1,10 @@
 local server = require('luatest.server')
+local fio = require('fio')
 local t = require('luatest')
 
 local g = t.group()
 
-g.after_all(function(cg)
+g.after_each(function(cg)
     if cg.server ~= nil then
         cg.server:drop()
     end
@@ -56,3 +57,59 @@ g.test_recovery_memory_limit = function(cg)
         t.assert_equals(s:select(), expected)
     end)
 end
+
+-- Check that recovery can be continued after crash and there is no stalls.
+g.test_recovery_after_recovery_crash = function(cg)
+    cg.server = server:new({box_cfg = {vinyl_memory = 10 * 1024 * 1024}})
+    cg.server:start()
+    cg.server:exec(function()
+        local fiber = require('fiber')
+
+        local s = box.schema.create_space('test', {engine = 'vinyl'})
+        s:create_index('pk')
+
+        box.error.injection.set('ERRINJ_VY_RUN_WRITE', true)
+        local d = string.rep('x', 10 * 1024)
+        fiber.set_max_slice(100)
+        for i = 1, 768 do
+            s:insert({i, d})
+        end
+    end)
+
+    local before_box_cfg = [[
+        box.error.injection.set('ERRINJ_VY_RUN_WRITE_CRASH_COUNTDOWN', 3)
+    ]]
+    t.assert_error(cg.server.restart, cg.server, {
+        box_cfg = {vinyl_memory = 1024 * 1024},
+        env = {TARANTOOL_RUN_BEFORE_BOX_CFG = before_box_cfg},
+    })
+    t.assert(cg.server:grep_log('injected crash'))
+
+    local path = fio.pathjoin(cg.server.workdir, 512, 0)
+    t.assert(fio.path.is_dir(path))
+    local old_files = fio.listdir(path)
+    t.assert_gt(#old_files, 0)
+
+    cg.server:restart({
+        box_cfg = {vinyl_memory = 1024 * 1024},
+        env = {},
+    })
+    -- Check there was no throttling due unexpected run/index files.
+    t.assert_not(cg.server:grep_log('throttling scheduler'))
+    local new_files = fio.listdir(path)
+    -- Check old run/index files are deleted.
+    t.assert_not_covers(new_files, old_files)
+
+    cg.server:exec(function()
+        local fiber = require('fiber')
+
+        local s = box.space.test
+        local d = string.rep('x', 10 * 1024)
+        local expected = {}
+        for i = 1, 768 do
+            table.insert(expected, {i, d})
+        end
+        fiber.set_max_slice(100)
+        t.assert_equals(s:select(), expected)
+    end)
+end
```

</details>

File: src/box/vinyl.c (hunk 3 above)
Comment (nshy) [reply src/box/vinyl.c]: Dropped this metric as discussed f2f. Decided to just check dump count in the test.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/vinyl.c b/src/box/vinyl.c
index aec0af69e7..76aecef4bf 100644
--- a/src/box/vinyl.c
+++ b/src/box/vinyl.c
@@ -263,7 +263,6 @@ vy_info_append_regulator(struct vy_env *env, struct info_handler *h)
 	info_append_int(h, "rate_limit", vy_quota_get_rate_limit(r->quota,
 							VY_QUOTA_CONSUMER_TX));
 	info_append_int(h, "blocked_writers", r->quota->n_blocked);
-	info_append_int(h, "used_max", r->quota->used_max);
 	info_table_end(h); /* regulator */
 }
 
diff --git a/src/box/vy_quota.c b/src/box/vy_quota.c
index ebc2aacae0..ebbbde0960 100644
--- a/src/box/vy_quota.c
+++ b/src/box/vy_quota.c
@@ -139,7 +139,6 @@ vy_quota_do_use(struct vy_quota *q, enum vy_quota_consumer_type type,
 		size_t size)
 {
 	q->used += size;
-	q->used_max = MAX(q->used, q->used_max);
 	for (int i = 0; i < vy_quota_resource_type_MAX; i++) {
 		struct vy_rate_limit *rl = &q->rate_limit[i];
 		if (vy_rate_limit_is_applicable(type, i))
@@ -229,7 +228,6 @@ vy_quota_create(struct vy_quota *q, size_t limit,
 	q->n_blocked = 0;
 	q->limit = limit;
 	q->used = 0;
-	q->used_max = 0;
 	q->too_long_threshold = TIMEOUT_INFINITY;
 	q->quota_exceeded_cb = quota_exceeded_cb;
 	q->wait_ticket = 0;
diff --git a/src/box/vy_quota.h b/src/box/vy_quota.h
index c3f86feee6..101681e542 100644
--- a/src/box/vy_quota.h
+++ b/src/box/vy_quota.h
@@ -186,8 +186,6 @@ struct vy_quota {
 	size_t limit;
 	/** Current memory consumption. */
 	size_t used;
-	/** Maximum observed (watermark) memory consumption. */
-	size_t used_max;
 	/**
 	 * If vy_quota_use() takes longer than the given
 	 * value, warn about it in the log.
diff --git a/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua b/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
index 0ee43fc6cb..2ac0840f1a 100644
--- a/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
+++ b/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
@@ -31,7 +31,6 @@ g.test_recovery_memory_limit = function(cg)
         local fiber = require('fiber')
 
         local stats = box.info.vinyl()
-        t.assert_le(stats.regulator.used_max, 1024 * 1024)
         t.assert_ge(stats.scheduler.dump_count, 7)
 
         local s = box.space.test
```

</details>

File: src/box/vy_log.c [hunk 5]
```diff
@@ -851,8 +876,7 @@ vy_log_flusher_f(va_list va)
 		 * Disable writes during local recovery.
 		 * See vy_log_tx_commit().
 		 */
-		if (vy_log.recovery != NULL ||
-		    stailq_empty(&vy_log.pending_tx)) {
+		if (stailq_empty(&vy_log.pending_tx)) {
```
Comment (locker) [inline src/box/vy_log.c:850]: This makes the comment right above outdated.

File: src/box/vy_log.c [hunk 6]
```diff
@@ -791,7 +806,17 @@ vy_log_tx_flush(struct vy_log_tx *tx)
...
 		entry->rows[i] = row;
+		/*
+		 * Update the recovery context with records written during
+		 * recovery - we will need them for garbage collection. But
+		 * skip run related records, so we don't collect runs which
+		 * dump is started during recovery.
+		 */
+		if (vy_log.recovery != NULL &&
+		    !vy_log_is_run_record(record->type))
+			vy_recovery_process_record(vy_log.recovery, record);
```
Comment (locker) [inline src/box/vy_log.c]: This looks suspicious. Can't we collect garbage before starting recovery instead?

File: test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua [hunk 7]
```diff
@@ -0,0 +1,165 @@
...
+
+    cg.server:restart({
+        box_cfg = {vinyl_memory = 1024 * 1024},
+        env = {},
+    })
+    -- Check there was no throttling due unexpected run/index files.
+    t.assert_not(cg.server:grep_log('throttling scheduler'))
+    local new_files = fio.listdir(path)
+    -- Check old run/index files are deleted.
+    t.assert_not_covers(new_files, old_files)
```
Comment (locker) [inline test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua]: `assert_covers` isn't going to work with arrays. Should be `assert_items_include` or something like that I guess.

File: src/box/vy_log.c (hunk 6 above)
Comment (nshy) [reply src/box/vy_log.c]: Fixed as discussed f2f.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/vinyl.c b/src/box/vinyl.c
index 76aecef4bf..0645becbb4 100644
--- a/src/box/vinyl.c
+++ b/src/box/vinyl.c
@@ -857,7 +857,7 @@ vinyl_index_commit_create(struct index *index, int64_t lsn)
 	 */
 	vy_log_tx_begin();
 	vy_log_create_lsm(lsm->id, lsn);
-	vy_log_tx_try_commit();
+	vy_log_tx_try_commit_recoverable();
 }
 
 static void
@@ -912,7 +912,7 @@ vinyl_index_commit_modify(struct index *index, int64_t lsn)
 
 	vy_log_tx_begin();
 	vy_log_modify_lsm(lsm->id, lsm->key_def, lsn);
-	vy_log_tx_try_commit();
+	vy_log_tx_try_commit_recoverable();
 }
 
 static void
@@ -936,7 +936,7 @@ vinyl_index_commit_drop(struct index *index, int64_t lsn)
 
 	vy_log_tx_begin();
 	vy_log_drop_lsm(lsm->id, lsn);
-	vy_log_tx_try_commit();
+	vy_log_tx_try_commit_recoverable();
 }
 
 static void
diff --git a/src/box/vy_log.c b/src/box/vy_log.c
index c969919a2d..38dab5dcc5 100644
--- a/src/box/vy_log.c
+++ b/src/box/vy_log.c
@@ -747,21 +747,6 @@ vy_log_tx_delete(struct vy_log_tx *tx)
 	mempool_free(&vy_log.tx_pool, tx);
 }
 
-/** Return whether record type is related to run file. */
-static bool
-vy_log_is_run_record(enum vy_log_record_type type)
-{
-	switch (type) {
-	case VY_LOG_PREPARE_RUN:
-	case VY_LOG_CREATE_RUN:
-	case VY_LOG_DROP_RUN:
-	case VY_LOG_FORGET_RUN:
-		return true;
-	default:
-		return false;
-	}
-}
-
 /**
  * Write a given transaction to disk.
  */
@@ -806,15 +791,6 @@ vy_log_tx_flush(struct vy_log_tx *tx)
 		struct xrow_header *row = &rows[i];
 		vy_log_record_encode(record, row);
 		entry->rows[i] = row;
-		/*
-		 * Update the recovery context with records written during
-		 * recovery - we will need them for garbage collection. But
-		 * skip run related records, so we don't collect runs which
-		 * dump is started during recovery.
-		 */
-		if (vy_log.recovery != NULL &&
-		    !vy_log_is_run_record(record->type))
-			vy_recovery_process_record(vy_log.recovery, record);
 		i++;
 
 	}
@@ -1346,6 +1322,19 @@ vy_log_tx_try_commit(void)
 	say_verbose("commit vylog transaction");
 }
 
+void
+vy_log_tx_try_commit_recoverable(void)
+{
+	assert(vy_log.tx != NULL);
+	if (vy_log.recovery != NULL) {
+		struct vy_log_record *record;
+		stailq_foreach_entry(record, &vy_log.tx->records, in_tx)
+			VERIFY(vy_recovery_process_record(vy_log.recovery,
+							  record) == 0);
+	}
+	vy_log_tx_try_commit();
+}
+
 void
 vy_log_write(const struct vy_log_record *record)
 {
diff --git a/src/box/vy_log.h b/src/box/vy_log.h
index a4347fb8f3..57e0193f7b 100644
--- a/src/box/vy_log.h
+++ b/src/box/vy_log.h
@@ -535,6 +535,17 @@ vy_log_tx_commit(void);
 void
 vy_log_tx_try_commit(void);
 
+/**
+ * Similar vy_log_tx_try_commit() but additionally updates recovery
+ * context during recovery (see vy_log_begin_recovery()), fixing
+ * it with records we fail to save on previous starts.
+ *
+ * It is expected to be called when missing vy_log changes can be recovered
+ * from xlog.
+ */
+void
+vy_log_tx_try_commit_recoverable(void);
+
 /**
  * Write a record to the metadata log.
  *
diff --git a/src/box/vy_lsm.c b/src/box/vy_lsm.c
index aa25269b8f..e3834d9464 100644
--- a/src/box/vy_lsm.c
+++ b/src/box/vy_lsm.c
@@ -329,7 +329,7 @@ vy_lsm_create(struct vy_lsm *lsm)
 	vy_log_prepare_lsm(id, lsm->space_id, lsm->index_id,
 			   lsm->group_id, lsm->key_def);
 	vy_log_insert_range(id, range->id, NULL, NULL);
-	vy_log_tx_try_commit();
+	vy_log_tx_try_commit_recoverable();
 
 	/* Assign the id. */
 	assert(lsm->id < 0);
diff --git a/test/unit/vy_log_stub.c b/test/unit/vy_log_stub.c
index be73adc7af..6815749359 100644
--- a/test/unit/vy_log_stub.c
+++ b/test/unit/vy_log_stub.c
@@ -45,6 +45,9 @@ vy_log_tx_begin(void) {}
 void
 vy_log_tx_try_commit(void) {}
 
+void
+vy_log_tx_try_commit_recoverable(void) {}
+
 int
 vy_log_tx_commit(void)
 {

```

</details>

File: src/box/vy_log.c (hunk 5 above)
Comment (nshy) [reply src/box/vy_log.c:850]: Deleted.

```diff
diff --git a/src/box/vy_log.c b/src/box/vy_log.c
index 38dab5dcc5..47c6c438c2 100644
--- a/src/box/vy_log.c
+++ b/src/box/vy_log.c
@@ -848,10 +848,6 @@ vy_log_flusher_f(va_list va)
        (void)va;
        while (!fiber_is_cancelled()) {
                fiber_check_gc();
-               /*
-                * Disable writes during local recovery.
-                * See vy_log_tx_commit().
-                */
                if (stailq_empty(&vy_log.pending_tx)) {
                        fiber_cond_wait(&vy_log.flusher_cond);
                        continue;
```

File: test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua (hunk 7 above)
Comment (nshy) [reply test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua]: Fixed. 

```diff
-    t.assert_not_covers(new_files, old_files)
+    t.assert_items_exclude(new_files, old_files)
```

**Comment by nshy** [comment]
Have to change the test a bit to handle race condition on injected crash:

<details>
<summary>diff</summary>

```diff
diff --git a/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua b/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
index ef79340f04..6fd76db6d5 100644
--- a/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
+++ b/test/vinyl-luatest/gh_12390_memory_limit_on_recovery_test.lua
@@ -98,9 +98,6 @@ g.test_recovery_after_recovery_crash = function(cg)
     })
     -- Check there was no throttling due unexpected run/index files.
     t.assert_not(cg.server:grep_log('throttling scheduler'))
-    local new_files = fio.listdir(path)
-    -- Check old run/index files are deleted.
-    t.assert_items_exclude(new_files, old_files)
 
     cg.server:exec(function()
         local fiber = require('fiber')
@@ -113,7 +110,16 @@ g.test_recovery_after_recovery_crash = function(cg)
         end
         fiber.set_max_slice(100)
         t.assert_equals(s:select(), expected)
+        -- Forget unused run files.
+        -- We may fail to remove them due injected crash.
+        box.snapshot()
+        s:insert({1000})
+        box.snapshot()
     end)
+
+    local new_files = fio.listdir(path)
+    -- Check old run/index files are deleted.
+    t.assert_items_exclude(new_files, old_files)
 end
 
 g.test_recovery_respect_inprogress_tasks = function(cg)
```

</details>

File: src/box/vy_log.c [hunk 8]
```diff
@@ -792,6 +792,7 @@ vy_log_tx_flush(struct vy_log_tx *tx)
 		vy_log_record_encode(record, row);
 		entry->rows[i] = row;
 		i++;
+
```
Comment (locker) [inline src/box/vy_log.c]: Nit: redundant change

Comment (nshy) [reply src/box/vy_log.c]: Fixed.

File: changelogs/unreleased/gh-12390-vinyl-recovery-memory-limit.md [hunk 9]
```diff
@@ -0,0 +1,4 @@
+## bugfix/vinyl
+
+* Fixed `vinyl_memory` overrun on recovery if the memory limit is less than on
+  the previous start (gh-12390).
```
Comment (AArdeev) [inline changelogs/unreleased/gh-12390-vinyl-recovery-memory-limit.md]: Fixed `vinyl_memory` overrun during recovery when the memory limit is lower than
at the previous start (gh-12390).

Comment (nshy) [reply changelogs/unreleased/gh-12390-vinyl-recovery-memory-limit.md]: Thanx! Fixed.
