### PR TITLE
vinyl: fix crash when empty PK DDL races with DML

### LINKED ISSUE #10603: Assertion `lsm->index_id > 0` failed in `vy_check_is_unique_secondary_one`
**Bug description**

Fuzzing test triggered the assertion:

```
tarantool: ./src/box/vinyl.c:1572: vy_check_is_unique_secondary_one: Assertion `lsm->index_id > 0' failed.
```

* OS: Linux
* OS Version: Ubuntu 24.04
* Architecture: amd64

Place `tarantool --version` output here.

```
Tarantool 3.3.0-entrypoint-105-gea6062964828
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/vlad/src/tarantool/tarantool/build/debug/install -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
```

**Steps to reproduce**

```sh
tarantool test/fuzz/lua/test_engine.lua --test_duration 5 --engine vinyl --test_dir t
```

**Actual behavior**

Crash caused by the assertion failure.

```gdb
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007bbced44526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007bbced4288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007bbced42881b in __assert_fail_base (fmt=0x7bbced5d01e8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5a5e617f2b08 "lsm->index_id > 0",
    file=file@entry=0x5a5e617f2456 "./src/box/vinyl.c", line=line@entry=1572,
    function=function@entry=0x5a5e617f36a0 <__PRETTY_FUNCTION__.60> "vy_check_is_unique_secondary_one") at ./assert/assert.c:94
#6  0x00007bbced43b507 in __assert_fail (assertion=0x5a5e617f2b08 "lsm->index_id > 0", file=0x5a5e617f2456 "./src/box/vinyl.c", line=1572,
    function=0x5a5e617f36a0 <__PRETTY_FUNCTION__.60> "vy_check_is_unique_secondary_one") at ./assert/assert.c:103
#7  0x00005a5e61189909 in vy_check_is_unique_secondary_one (tx=0x7bbceac9c070, rv=0x7bbceac9c0d8, lsm=0x5a5e625e4b30, stmt=0x5a5e6272a050, multikey_idx=-1)
    at /home/vlad/src/tarantool/tarantool/src/box/vinyl.c:1572
#8  0x00005a5e61189c2d in vy_check_is_unique_secondary (tx=0x7bbceac9c070, rv=0x7bbceac9c0d8, lsm=0x5a5e625e4b30, stmt=0x5a5e6272a050)
    at /home/vlad/src/tarantool/tarantool/src/box/vinyl.c:1632
#9  0x00005a5e611908c1 in vy_build_on_replace (trigger=0x7bbc5e380600, event=0x7bbceacd6038) at /home/vlad/src/tarantool/tarantool/src/box/vinyl.c:3993
#10 0x00005a5e61412e69 in trigger_run_list (list=0x7bbc5d880ac0, event=0x7bbceacd6038) at /home/vlad/src/tarantool/tarantool/src/lib/core/trigger.cc:100
#11 0x00005a5e61412f7b in trigger_run (list=0x5a5e6271c0d0, event=0x7bbceacd6038) at /home/vlad/src/tarantool/tarantool/src/lib/core/trigger.cc:133
#12 0x00005a5e6120106c in space_on_replace (space=0x5a5e6271c030, txn=0x7bbceacd6038) at /home/vlad/src/tarantool/tarantool/src/box/space.c:1035
#13 0x00005a5e6123cd53 in txn_commit_stmt (txn=0x7bbceacd6038, request=0x7bbc5d880c40) at /home/vlad/src/tarantool/tarantool/src/box/txn.c:745
#14 0x00005a5e61250bfa in box_process_rw (request=0x7bbc5d880c40, space=0x5a5e6271c030, result=0x7bbc5d880d48) at /home/vlad/src/tarantool/tarantool/src/box/box.cc:519
#15 0x00005a5e6125deb9 in box_process1 (request=0x7bbc5d880c40, result=0x7bbc5d880d48) at /home/vlad/src/tarantool/tarantool/src/box/box.cc:3755
#16 0x00005a5e6125eaf6 in box_replace (space_id=512, tuple=0x7bbceac99240 "\233\313Bi\343\225\314\3360", <incomplete sequence \317>,
    tuple_end=0x7bbceac992a4 'P' <repeats 200 times>..., result=0x7bbc5d880d48) at /home/vlad/src/tarantool/tarantool/src/box/box.cc:3951
#17 0x00005a5e6136dab8 in lbox_replace (L=0x407d77c8) at /home/vlad/src/tarantool/tarantool/src/box/lua/index.c:84
#18 0x00005a5e61447557 in lj_BC_FUNCC () at buildvm_x86.dasc:811
#19 0x00005a5e6145509b in lua_pcall (L=0x407d77c8, nargs=4, nresults=-1, errfunc=0) at /home/vlad/src/tarantool/tarantool/third_party/luajit/src/lj_api.c:1173
#20 0x00005a5e613b69e6 in luaT_call (L=0x407d77c8, nargs=4, nreturns=-1) at /home/vlad/src/tarantool/tarantool/src/lua/utils.c:695
#21 0x00005a5e613ab712 in lua_fiber_run_f (ap=0x7bbceac176f8) at /home/vlad/src/tarantool/tarantool/src/lua/fiber.c:435
#22 0x00005a5e61101143 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x5a5e613ab655 <lua_fiber_run_f>, ap=0x7bbceac176f8)
    at /home/vlad/src/tarantool/tarantool/src/lib/core/fiber.h:1324
#23 0x00005a5e613e7572 in fiber_loop (data=0x0) at /home/vlad/src/tarantool/tarantool/src/lib/core/fiber.c:1162
#24 0x00005a5e617c8758 in coro_init () at /home/vlad/src/tarantool/tarantool/third_party/coro/coro.c:108
```

[Link](https://drive.google.com/file/d/1ZgXdBgTnqI4whUUgIPHGyBKZ5XM0AAmX) to the core dump and data.

**Expected behavior**

No crash.

### PR DESCRIPTION
**Pull request by locker**
Vinyl doesn't support altering the primary index of a non-empty space, but the check forbidding this isn't entirely reliable - the DDL function may yield to wait for pending WAL writes to finish after ensuring that the space doesn't contain any tuples. If a new tuples is inserted into the space in the meantime, the DDL operation will proceed rebuilding the primary index and trigger a crash because the code is written on the assumption that it's rebuilding a secondary index:

```
./src/box/vinyl.c:1572: vy_check_is_unique_secondary_one: Assertion `lsm->index_id > 0' failed.
```

Let's fix this by moving the check after syncing on WAL.

Closes #10603

### CODE REVIEW

File: test/vinyl-luatest/gh_10603_pk_alter_vs_dml_test.lua [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+    cg.server:exec(function()
+        local fiber = require('fiber')
+        local timeout = 10 -- seconds
+
+        local s = box.schema.space.create('test', {engine = 'vinyl'})
+        s:create_index('pk')
+
+        local c1 = fiber.channel(1)
+        local f1 = fiber.new(function()
+            s:replace({1, 10})
```
Comment (nshy) [inline test/vinyl-luatest/gh_10603_pk_alter_vs_dml_test.lua:35]: Nit. Let's read from `c1` or let's get rid of it. Now it is redundant.

Comment (locker) [reply test/vinyl-luatest/gh_10603_pk_alter_vs_dml_test.lua:36]: Missed that. Fixed, thanks!

<details><summary>diff</summary>

```diff
diff --git a/test/vinyl-luatest/gh_10603_pk_alter_vs_dml_test.lua b/test/vinyl-luatest/gh_10603_pk_alter_vs_dml_test.lua
index 1b37f68f90dd..a6fdf28d88a2 100644
--- a/test/vinyl-luatest/gh_10603_pk_alter_vs_dml_test.lua
+++ b/test/vinyl-luatest/gh_10603_pk_alter_vs_dml_test.lua
@@ -32,6 +32,7 @@ g.test_empty_pk_alter = function(cg)
 
         local c1 = fiber.channel(1)
         local f1 = fiber.new(function()
+            c1:get()
             s:replace({1, 10})
         end)
         f1:set_joinable(true)
```

</details>

**Review by xuniq — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.11 and 3.2.
