### PR TITLE
vfork on macOS

### LINKED ISSUE #6576: Unable to build Tarantool on MacOS
```
-- Performing Test MACOS_V1012 - Success
-- Looking for gethostbyname in nsl
[ 32%] Built target module_api
[ 32%] Generating sql/opcodes.h
[ 32%] Linking C executable uri.test
-- Looking for gethostbyname in nsl - not found
-- Looking for gethostbyname in socket
[ 32%] Built target uri.test
In file included from /Users/o.babin/Projects/tarantool/test/unit/bloom.cc:2:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/unordered_set:390:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/__hash_table:15:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/c++/v1/memory:2666:26: error: unexpected type name '_CompressedPair': expected expression
    struct _ALIGNAS_TYPE(_CompressedPair) _Storage {
                         ^
/Users/o.babin/Projects/tarantool/src/lib/core/crash.c:400:14: error: 'vfork' is deprecated: Use posix_spawn or fork [-Werror,-Wdeprecated-declarations]
        pid_t pid = vfork();
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/unistd.h:604:1: note: 'vfork' has been explicitly marked deprecated here
__deprecated_msg("Use posix_spawn or fork")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/sys/cdefs.h:208:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
make[2]: *** [src/lib/core/CMakeFiles/core.dir/crash.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
-- Looking for gethostbyname in socket - not found
-- Looking for socket in socket
[ 32%] Linking CXX executable bps_tree_iterator.test
/Users/o.babin/Projects/tarantool/src/lib/core/popen.c:1184:16: error: 'vfork' is deprecated: Use posix_spawn or fork [-Werror,-Wdeprecated-declarations]
        handle->pid = vfork();
                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/unistd.h:604:1: note: 'vfork' has been explicitly marked deprecated here
__deprecated_msg("Use posix_spawn or fork")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include/sys/cdefs.h:208:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
make[2]: *** [src/lib/core/CMakeFiles/core.dir/popen.c.o] Error 1
```

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
`vfork` got deprecated on macOS:

* refactor crash signal hander: change `vfork` to more portable `posix_spawn`.
* `popen`: for now, change `vfork` deprecation error to a warning until we find a suitable solution. We plan to review
`popen`'s design and get rid of `vfork` completely, or change `vfork` to `posix_spawn` only on macOS (#6674).

Closes #6576

### CODE REVIEW

**Comment by Totktonada** [comment]
Nit: Two commits, each of them closes the issue. Also there is no issue to actually refactor vfork usage in popen.

File: src/lib/core/crash.c [hunk 1]
```diff
@@ -392,32 +393,17 @@ crash_report_feedback_daemon(struct crash_info *cinfo)
...
-			exec_argv[0], exec_argv[0],
-			exec_argv[1], exec_argv[2],
-			exec_argv[3], exec_argv[4],
-			exec_argv[5], exec_argv[6]);
-		_exit(1);
-	} else if (pid < 0) {
-		pr_crit("unable to vfork (errno %d)", errno);
+#ifdef TARGET_OS_DARWIN
+	extern char **environ;
+#endif
```
Comment (locker) [inline src/lib/core/crash.c:398]: Nit: let's drop the ifdef and declare `envion` unconditionally, like it's done in other places, e.g. in [src/proc_title.c](https://github.com/tarantool/tarantool/blob/d9b8c0db79e7df4a024ca3273f663fd7d68a2d51/src/proc_title.c#L47)

File: src/lib/core/popen.c [hunk 2]
```diff
@@ -1178,7 +1178,13 @@ popen_new(struct popen_opts *opts)
 	 * vfork to complete. Also we try to do as minimum
 	 * operations before the exec() as possible.
 	 */
+#pragma GCC diagnostic push
+	/*
+	 * FIXME: we need to review popen's design and refactor this part.
+	 */
```
Comment (locker) [inline src/lib/core/popen.c:1184]: Nit: please file a ticket with a proper description and mention it here for the reference:

```C
/* TODO(gh/XXXX): Rework popen so that it doesn't need to fork the main process. */
```

File: src/lib/core/popen.c [hunk 3]
```diff
@@ -1178,7 +1178,13 @@ popen_new(struct popen_opts *opts)
 	 * vfork to complete. Also we try to do as minimum
 	 * operations before the exec() as possible.
 	 */
+#pragma GCC diagnostic push
```
Comment (locker) [inline src/lib/core/popen.c:1181]: What about clang compiler?

**Review by locker — CHANGES_REQUESTED** [review]

File: src/lib/core/crash.c (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/lib/core/crash.c:398]: @locker the point is that, on Linux, `environ` is declared in unistd.h, and declaring it in source code on that platform is  redundant.

File: src/lib/core/popen.c (hunk 3 above)
Comment (CuriousGeorgiy) [reply src/lib/core/popen.c:1181]: @locker clang's diagnostic pragmas are [backwards compatible](https://clang.llvm.org/docs/UsersManual.html#controlling-diagnostics-via-pragmas) with those of GCC .

**Comment by CuriousGeorgiy** [comment]
> Nit: Two commits, each of them closes the issue. Also there is no issue to actually refactor vfork usage in popen.

@Totktonada thank you! Changed one commit to 'needed' for this issue and created a new issue regarding vfork in popen.

File: src/lib/core/popen.c (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/lib/core/popen.c:1186]: Fixed: created a new issue regarding `vfork` in `popen` and mentioned it in the TODO.

**Review by locker — APPROVED** [review]

**Review by cyrillos — APPROVED** [review]
I didn't dive pretty much into but from a glance the changes are good, lets give them a spin.

**Review by locker — CHANGES_REQUESTED** [review]
@CuriousGeorgiy Tarantool [fails](https://github.com/tarantool/tarantool/runs/4427714455) to build on FreeBSD after your change. Please fix.

```
error: use of undeclared identifier 'environ'; did you mean 'ev_run'?
        int rc = posix_spawn(NULL, exec_argv[0], NULL, NULL, exec_argv, environ);
                                                                        ^~~~~~~
```

File: src/lib/core/crash.c (hunk 1 above)
Comment (locker) [reply src/lib/core/crash.c:398]: But it wouldn't hurt, would it? Besides, it would fix the [build failure](https://github.com/tarantool/tarantool/runs/4427714455) on FreeBSD.

Comment (CuriousGeorgiy) [reply src/lib/core/crash.c]: @locker I think it's better to keep code platform-specific, i.e.
```c
#if defined(TARGET_OS_FREEBSD) || defined(TARGET_OS_NETBSD) || defined(TARGET_OS_DARWIN)
        extern char **environ;
#endif
```

But perhaps it's a matter of taste — just that my clang-tidy is complaining about a redundant declaration on the Linux platform.

Fixed: declared environ unconditionally.

**Review by locker — APPROVED** [review]

**Comment by Totktonada** [comment]
@locker The problem hits 2.8 as well.

**Comment by locker** [comment]
> @locker The problem hits 2.8 as well.

Cherry-picked in 2.8.
