### PR TITLE
wal: use existing logs sizes after restart

### LINKED ISSUE #9811: checkpoint_wal_threshold doesn't account WALs created before a restart
**Bug description**
The wal size counter since last checkpoint is reset to 0 on instance restart.
**Steps to reproduce**

1. Set `box.cfg{wal_max_size=512, checkpoint_wal_threshold=10*512}` -- there should be approximately 10 xlogs between checkpoints.
2. write some data, restart the instance, write some more data.
3. Check the created xlogs and snaps:
```
-rw-r--r--  1 s.petrenko  staff   5,0K 14 мар 11:22 00000000000000001426.snap <-- first snap
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001426.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001434.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001442.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001450.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001458.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001466.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001474.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001482.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:22 00000000000000001490.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001498.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001506.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001514.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001522.xlog
-rw-r--r--  1 s.petrenko  staff   379B 14 мар 11:23 00000000000000001530.xlog
-rw-r--r--  1 s.petrenko  staff   5,0K 14 мар 11:23 00000000000000001535.snap <-- next snap after 14 xlogs (it's not clear why 14 and not 10)
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001535.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001543.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001551.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001559.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001567.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001575.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001583.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001591.xlog
-rw-r--r--  1 s.petrenko  staff   191B 14 мар 11:23 00000000000000001599.xlog <-- restart happened here
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001600.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001608.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001616.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001624.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001632.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001640.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001648.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001656.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001664.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001672.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001680.xlog
-rw-r--r--  1 s.petrenko  staff   520B 14 мар 11:23 00000000000000001688.xlog
-rw-r--r--  1 s.petrenko  staff   328B 14 мар 11:23 00000000000000001696.xlog <-- no snap for 22 xlogs.
```

### PR DESCRIPTION
**Pull request by LevKats**
During the `checkpoint_wal_threshold` exceedance checks tarantool used to ignore the sizes of files created prior to the server restart which resulted in cases when the server didn't create any checkpoints and generate a huge amount of logs which were replayed each server restart. Now the `wal_dir` is scanned for proper `writer->checkpoint_wal_size` calculation after the recovery process.

Fixes #9811
NO_DOC=bugfix

### CODE REVIEW

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+end)
+
+g.before_each(function(g)
+    g.server:exec(function()
+        box.space.test:truncate()
+    end)
+end)
+
+g.test_box_checkpoint_wal_threshold_contract = function(g)
+    define_xlog_size_and_gc_trigger(g.server)
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:58]: Let rename function to `define_helpers`.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+    -- let's test our assumptions about wal size compared
+    -- to tuples first
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:60]: Please describe the assumption in the comment.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+        local s = box.space.test
+        _G.manual_gc_trigger()
+        local size_before = _G.measure_xlog_size_sum()
+        for _=1,tuples_per_batch do
+            s:insert{box.NULL}
+        end
+        local size_after = _G.measure_xlog_size_sum()
+        t.assert(size_after > size_before)
+        t.assert(size_after - size_before < wal_max_size)
+        t.assert(2 * (size_after - size_before) >= wal_max_size)
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:74]: It is better to use specific assertions. They are able to provide more information if test fails. I mean `assert_lt` etc.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+    define_xlog_size_and_gc_trigger(g.server)
+    g.server:exec(function(tuples_per_batch, max_wal_files)
+        local s = box.space.test
+        _G.manual_gc_trigger()
+        local size_before = _G.measure_xlog_size_sum()
+        local wal_max_size = box.cfg.wal_max_size
+        t.assert(size_before < wal_max_size)
+        t.assert_equals(box.cfg.checkpoint_wal_threshold,
+                        wal_max_size * max_wal_files)
+        t.assert(max_wal_files > 1)
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:90]: Not sure why we need to test `box.cfg.checkpoint_wal_threshold` or `max_wal_files`, we set them by ourself. Also it is not clear why we test `size_before`.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+        while (_G.measure_xlog_size_sum() <=
+               (max_wal_files - 1) * wal_max_size) do
+            for _=1,tuples_per_batch do
+                s:insert{box.NULL}
+            end
+        end
+        local size_after = _G.measure_xlog_size_sum()
+        t.assert((max_wal_files - 1) * wal_max_size < size_after)
+        -- I suppose, size_after < checkpoint_wal_threshold
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:99]: It is not clear why we need this test also. It the condition of the loop.

I guess it worth just put `tuples_per_batch * 2 *  (max_wal_files - 1)` and then check xlog sizes on disk. Also to make test more robust I'd put `tuples_per_batch * 2 *  (max_wal_files) * 3/4` before restart and `tuples_per_batch * 2 *  (max_wal_files) * 1/2` after restart.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 6]
```diff
@@ -0,0 +1,126 @@
...
+        box.cfg{checkpoint_wal_threshold = checkpoint_wal_threshold}
+    end, {wal_max_size, tuples_per_batch})
+end
+
+g.test_box_checkpoint_wal_threshold_after_restart = function(g)
+    define_xlog_size_and_gc_trigger(g.server)
+    g.server:exec(function(tuples_per_batch, max_wal_files)
+        local s = box.space.test
+        _G.manual_gc_trigger()
+        local size_before = _G.measure_xlog_size_sum()
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:85]: Let's add line `local xlog_total_size = _G.measure_xlog_size_sum` and use `xlog_size` name. This will make easier the rest of the code for eyes.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 7]
```diff
@@ -0,0 +1,126 @@
...
+        end
+        -- wait for checkpoint finish
+        require("fiber").sleep(1)
+        local found = false
+        for _, chpt in ipairs(box.info.gc().checkpoints) do
+            if chpt.signature > signature_before then
+                found = true
+            end
+        end
+        t.assert(found)
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:124]: Let's instead check checkpoint count (#box.info.gc().checkpoints) is changed. We need to reset `box_cfg.checkpoint_count` to the large value before yet. Or we can just check that signature is changed on the first checkpoint if `box_cfg.checkpoint_count == 1`.

File: src/box/wal.c [hunk 8]
```diff
@@ -579,12 +590,37 @@ wal_enable(void)
...
+	for (struct vclock *vclock = vclockset_first(&writer->wal_dir.index);
+	     vclock != NULL;
+	     vclock = vclockset_next(&writer->wal_dir.index, vclock)) {
+		const char *name = xdir_format_filename(&writer->wal_dir,
+							vclock_sum(vclock),
+							NONE);
+		uint64_t wal_size;
+		if (file_size(&wal_size, name) != 0)
+			return -1;
+		sum_already_on_disk += wal_size;
```
Comment (nshy) [inline src/box/wal.c:603]: Looks like we count size of all xlogs. Not only those done after the last snapshot.

**Review by nshy — CHANGES_REQUESTED** [review]

**Review by lenkis — APPROVED** [review]

File: src/box/wal.c (hunk 8 above)
Comment (LevKats) [reply src/box/wal.c]: Now only logs newer than the last checkpoint are selected. The only possible problem is that I can't find the place where the `writer->checkpoint_vclock` is set after server restart. Should we open an issue for that if this is the case?
```diff
for (struct vclock *vclock = vclockset_first(&writer->wal_dir.index);
    vclock != NULL;
    vclock = vclockset_next(&writer->wal_dir.index, vclock)) {
+       if (vclock_compare(&writer->checkpoint_vclock, vclock) >= 0)
+               continue;
	const char *name = xdir_format_filename(&writer->wal_dir,
                                                vclock_sum(vclock),
						NONE);
```

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 7 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Fixed. Now only the existence of one checkpoint is assumed.
```diff
- local found = false
- for _, chpt in ipairs(box.info.gc().checkpoints) do
-     if chpt.signature > signature_before then
-         found = true
-     end
- end
- t.assert(found)
+ t.assert_gt(box.info.gc().checkpoints[1].signature, signature_before)
```

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 6 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Fixed as far as I understand. Or I should use something like xlog_size_after as well?

File: changelogs/unreleased/gh-9811-checkpoint-wal-threshold-after-restart.md [hunk 9]
```diff
@@ -0,0 +1,5 @@
+## bugfix/core
```
[the remark this answers is not in the document]
Comment (LevKats) [reply changelogs/unreleased/gh-9811-checkpoint-wal-threshold-after-restart.md]: Fixed

File: src/box/wal.c [hunk 10]
```diff
@@ -579,12 +590,37 @@ wal_enable(void)
...
+		static struct cmsg_hop route[] = {
+			{ tx_notify_checkpoint, NULL },
+		};
+		struct cmsg *msg = xmalloc(sizeof(*msg));
+		cmsg_init(msg, route);
+		cpipe_push(&writer->tx_prio_pipe, msg);
+		writer->checkpoint_triggered = true;
+	}
 	return 0;
 }
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c]: Done.

File: src/box/wal.c [hunk 11]
```diff
@@ -563,6 +563,17 @@ wal_init(enum wal_mode wal_mode, const char *wal_dirname,
...
 
+static int
+file_size(uint64_t *filesize, const char *filename)
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c]: Fixed. Also diag is provided.
```diff
  const char *name = xdir_format_filename(&writer->wal_dir, 
                                          vclock_sum(vclock),
                                          NONE);
- uint64_t wal_size;
- if (file_size(&wal_size, name) != 0)
-         return -1;
+ struct stat attr;
+ if (stat(name, &attr) == -1) {
+         diag_set(SystemError,
+			 "failed to get file size %s",
+                         name);
+ 			  return -1;
+ }
+ uint64_t wal_size = (uint64_t)attr.st_size;
  sum_already_on_disk += wal_size;
```

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 12]
```diff
@@ -0,0 +1,126 @@
...
+                    result = result + fio.stat(fname).size
+                end
+            end
+            return result
+        end)
+        rawset(_G, 'manual_gc_trigger', function()
+            -- that should erase all existed xlogs
+            for _=1,box.cfg.checkpoint_count + 1 do
+                box.snapshot()
+            end
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:42]: Single `box.snapshot` is not enough to trigger gc. To delete all existing logs one should create a situation where there was a checkpoint after them and it was deleted. So I suggest keeping this snippet since double snapshotting is going to look even more suspicious.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 1 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Done

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 2 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Done
```diff
  -- let's test our assumptions about wal size compared
- -- to tuples
+ -- to tuples and manual_gc_trigger first:
+ -- 1. tupls_per_batch tuples produce log file so its
+ --    length 1/2 <= xlog_size / wal_max_size < 1
+ -- 2. manual_gc_trigger deletes all existing xlogs
```

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 3 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Fixed

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 4 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Fixed

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 5 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Well, `tuples_per_batch * 2 *  (max_wal_files) * 3/4` doesn't guarantee that checkpoint won't be created. But I found a way to get rid of that while loop with new assumptions in the previous test. This check was needed to test that no checkpoint was created, now the check is changed a bit. Fixed, I guess.

File: src/box/wal.c (hunk 8 above)
Comment (nshy) [reply src/box/wal.c]: Yes it is set only when checkpoint is created. Is there an issue with existing code caused by that? If yes then we surely should file an issue. Here we need to have last checkpoint vclock for this hunk. Looks like can pass it as `wal_enable()` parameter. The value can be obtained from gc subsystem.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 13]
```diff
@@ -0,0 +1,124 @@
...
+        end)
+    end)
+end
+
+g.after_all(function(g)
+    g.server:drop()
+end)
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:49]: Please move `after_all` after `before_all`.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 12 above)
[the remark this answers is not in the document]
Comment (nshy) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:42]: Ok, lets name it `remove_xlogs`.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 14]
```diff
@@ -0,0 +1,124 @@
...
+        local xlog_size_after = xlog_total_size()
+        t.assert_lt(xlog_size_after,  wal_max_size)
+        t.assert_ge(2 * xlog_size_after, wal_max_size)
+        -- return the previous configuration
+        box.cfg{checkpoint_wal_threshold = checkpoint_wal_threshold}
+        trigger_gc()
+        local signature_before = box.info.signature
+        -- no checkpoint should be created with these tuples alone
+        for _=1,max_wal_files * tuples_per_batch + 1 do
+            s:insert{box.NULL}
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:89]: Nit. We tend to use full syntax `s:insert({})`.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 15]
```diff
@@ -0,0 +1,124 @@
...
+        -- no checkpoints during the test except explicit ones
+        local checkpoint_wal_threshold = box.cfg.checkpoint_wal_threshold
+        box.cfg{checkpoint_wal_threshold = 1e18}
+        local s = box.space.test
+        s:insert{box.NULL}
+        local trigger_gc =_G.manual_gc_trigger
+        trigger_gc()
+        local xlog_total_size = _G.measure_xlog_size_sum
+        t.assert_equals(xlog_total_size(), 0)
+        for _=1,tuples_per_batch do
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:77]: Nit. Please add spaces around `=`.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 16]
```diff
@@ -0,0 +1,124 @@
...
+        -- no checkpoint should be created with these tuples alone
+        for _=1,max_wal_files * tuples_per_batch + 1 do
+            s:insert{box.NULL}
+        end
+        -- wait for possible (but unwanted) checkpoint finish
+        require("fiber").sleep(1)
+        t.assert_equals(box.info.gc().checkpoints[1].signature,
+                        signature_before)
+    end, {max_wal_files, tuples_per_batch})
+end
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:96]: Frankly speaking I don't see the point of this test. It is much simpler in the below test just add insert some number of tuples, then check that no new snapshot appeared. Then restart and again insert same number of tuples (so that without patch no snapshot should be triggered) and check that this time snapshot is done. Don't need to introduce `tuples_per_batch`.

Also let's just use magic numbers in the test instead of global constants which we need to pass over and over again. It perfectly ok for the test. The test will be easier to follow and more local. Best test is that you can read entirely without navigating the test file I guess.

Also let's add test for:
- we don't account xlogs done before the last snapshot
- we account xlog that is done after the last snapshot (as already mentioned in the other conversation).

File: src/box/wal.c [hunk 17]
```diff
@@ -478,11 +478,44 @@ wal_open_f(struct cbus_call_msg *msg)
...
+	if (!writer->checkpoint_triggered &&
+	    writer->checkpoint_wal_size > writer->checkpoint_threshold) {
+		static struct cmsg_hop route[] = {
+			{ tx_notify_checkpoint, NULL },
+		};
+		struct cmsg *msg = xmalloc(sizeof(*msg));
+		cmsg_init(msg, route);
+		cpipe_push(&writer->tx_prio_pipe, msg);
+		writer->checkpoint_triggered = true;
+	}
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c:511]: What If we are not going to do any writes after that? For some reasons during the previous restart checkpoint was not created successfully and now we would constantly replay xlogs each restart. Also this is an example of different behaviour with and without server restart which we tend to dislike.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 16 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:96]: This test was intended to simplify future debugging after possible xlogs format change so the magical numbers irrelevance would be easier to find and use the test after possible changes in that constants. Well, to be honest the test also assumes that the size of xlog depends linearly on the number of inserted tuples which is not the case with some hypothetical future compression algorithms for example.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 12 above)
[the remark this answers is not in the document]
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: After the radical test simplification it is not needed as a separate function. Fixed, I guess.

File: src/box/wal.c (hunk 8 above)
Comment (LevKats) [reply src/box/wal.c]: Done in wal_init. Looks like everything needed is known at that moment and we don't encounter any race conditions there.

File: src/box/wal.c [hunk 18]
```diff
@@ -579,7 +612,10 @@ wal_enable(void)
 	if (xdir_scan(&writer->wal_dir, true))
 		return -1;
 
-	/* Open the most recent WAL file. */
+	/*
+	 * Open the most recent WAL file and set
+	 * writer->checkpoint_wal_size.
+	 */
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c]: Returned its original look. Fixed.

File: src/box/wal.c (hunk 17 above)
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c]: Sounds reasonable. Deleted that code.

File: src/box/wal.c [hunk 19]
```diff
@@ -478,11 +478,44 @@ wal_open_f(struct cbus_call_msg *msg)
...
+		if (stat(name, &attr) == -1) {
+			diag_set(SystemError,
+				 "failed to get file size %s",
+				 name);
+			return -1;
+		}
+		uint64_t wal_size = (uint64_t)attr.st_size;
+		sum_already_on_disk += wal_size;
+	}
+	writer->checkpoint_wal_size += sum_already_on_disk;
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c]: First option was chosen. Fixed.

File: src/box/wal.c [hunk 20]
```diff
@@ -478,11 +478,44 @@ wal_open_f(struct cbus_call_msg *msg)
...
+		if (vclock_compare(&writer->checkpoint_vclock, vclock) >= 0)
+			continue;
+		const char *name = xdir_format_filename(&writer->wal_dir,
+							vclock_sum(vclock),
+							NONE);
+		struct stat attr;
+		if (stat(name, &attr) == -1) {
+			diag_set(SystemError,
+				 "failed to get file size %s",
+				 name);
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c:497]: Done

File: src/box/wal.c [hunk 21]
```diff
@@ -478,11 +478,44 @@ wal_open_f(struct cbus_call_msg *msg)
 	const char *path = xdir_format_filename(&writer->wal_dir,
 				vclock_sum(&writer->vclock), NONE);
 	assert(!xlog_is_open(&writer->current_wal));
+
+	uint64_t sum_already_on_disk = 0;
+	for (struct vclock *vclock = vclockset_first(&writer->wal_dir.index);
+	     vclock != NULL;
+	     vclock = vclockset_next(&writer->wal_dir.index, vclock)) {
+		if (vclock_compare(&writer->checkpoint_vclock, vclock) >= 0)
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c]: You are right. Effectively now there are 2 tests and one is intended to cover the case when there was only one (long) xlog after the last snapshot so use its size too.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 13 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Fixed

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 15 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Done. I expected luacheck to cover that for some reason.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 16 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Deleted the test with assumptions. Now there are 2 tests:
1. many short xlogs
2. one long slog

Also now we test that only xlogs after the last snapshots are taken into account.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 22]
```diff
@@ -0,0 +1,77 @@
...
+        local signature_before = box.info.signature
+        for _ = 1, 81 do
+            s:insert({box.NULL})
+        end
+        -- result must be the same -- no new checkpoint
+        require("fiber").sleep(1)
+        t.assert_equals(box.info.gc().checkpoints[1].signature,
+                        signature_before,
+                        "old xlogs may be used")
+    end)
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:61]: Looks like we don't test that we do not account logs before the last snapshot.

**Review by nshy — CHANGES_REQUESTED** [review]

File: src/box/wal.c [hunk 23]
```diff
@@ -478,11 +481,32 @@ wal_open_f(struct cbus_call_msg *msg)
...
+		const char *name = xdir_format_filename(&writer->wal_dir,
+							vclock_sum(vclock),
+							NONE);
+		struct stat attr;
+		if (stat(name, &attr) == -1) {
+			diag_set(SystemError, "failed to get file size %s",
+				 name);
+			return -1;
+		}
+		uint64_t wal_size = (uint64_t)attr.st_size;
```
[the remark this answers is not in the document]
Comment (LevKats) [reply src/box/wal.c]: Deleted

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 24]
```diff
@@ -0,0 +1,77 @@
...
+
+local group_config = {{wal_max_size = 512}, {wal_max_size = 512 * 10}}
+local g = t.group("wal_max_size", group_config)
+
+g.before_all(function(cg)
+    cg.server = server:new({box_cfg = {
+        wal_max_size = cg.params.wal_max_size,
+        checkpoint_wal_threshold = 10 * 512,
+        checkpoint_count = 1,
+        wal_mode = 'fsync',  -- we measure xlog files sizes
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Fixed

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua (hunk 22 above)
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:87]: I got rid of almost all magic with GC and now the number of checkpoints is used instead of signatures.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 25]
```diff
@@ -0,0 +1,101 @@
...
+            s:insert({box.NULL})
+        end
+        require("fiber").sleep(1)
+        t.assert_gt(#box.info.gc().checkpoints, checkpoints_before)
+    end)
+end
+
+g.after_each(function(cg)
+    cg.server:drop()
+end)
```
Comment (nshy) [inline test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:101]: Please, write comments like sentences, starting from capital letter and ending with dot. Even for single line comment.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 26]
```diff
@@ -0,0 +1,101 @@
+local t = require('luatest')
+local server = require('luatest.server')
+
+local group_config = {{wal_max_size = 50000}, {wal_max_size = 50000 * 10}}
+-- 1. Many small xlogs. Let's check that threshold check indeed use
+--    the sum of xlog sizes
+-- 2. One big xlog. Let's check that xlog right after the snapshot is
+--    taken into account.
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua:7]: Fixed

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 27]
```diff
@@ -0,0 +1,101 @@
...
+        require("fiber").sleep(1)
+        t.assert_equals(#box.info.gc().checkpoints, checkpoints_before,
+                        "Wrong batch size. Check the test above")
+        box.snapshot()
+    end)
+    cg.server:restart()
+    cg.server:exec(function()
+        local s = box.space.test
+        -- There are xlogs created before the snapshot.
+        -- Ignore them when calculating the threshold.
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: Fixed. Also moved the comment out of the function so it should be less confusing now.

File: test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua [hunk 28]
```diff
@@ -0,0 +1,101 @@
...
+        t.assert_equals(#box.info.gc().checkpoints, checkpoints_before,
+                        "too large batch")
+        for _ = 1, 7000 do
+            s:insert({box.NULL})
+        end
+        fiber.sleep(1)
+        t.assert_gt(#box.info.gc().checkpoints, checkpoints_before,
+                    "too small batch")
+    end)
+end
```
[the remark this answers is not in the document]
Comment (LevKats) [reply test/box-luatest/gh_9811_checkpoint_wal_threshold_after_restart_test.lua]: The test has been deleted. Fixed.

**Review by nshy — APPROVED** [review]

File: src/box/wal.c [hunk 29]
```diff
@@ -478,11 +481,31 @@ wal_open_f(struct cbus_call_msg *msg)
...
+		if (vclock_compare(&writer->checkpoint_vclock, vclock) > 0)
+			continue;
+		const char *name = xdir_format_filename(&writer->wal_dir,
+							vclock_sum(vclock),
+							NONE);
+		struct stat attr;
+		if (stat(name, &attr) == -1) {
+			diag_set(SystemError, "failed to get file size %s",
+				 name);
+			return -1;
```
Comment (Serpentian) [inline src/box/wal.c:498]: Are we sure, we want to exit here? There're a whole bunch of errors, which can happen during `stat` (see `ERRORS` [here](https://www.man7.org/linux/man-pages/man2/stat.2.html)) but we already recovered and ready to start. Shouldn't we just warn in logs and continue to the next vclock here?

Even if we want to fail here, we should probably continue if `force_recovery` is set. But I'd rather warn in all cases, not so critcal, that we'll take a little bit more space.

Comment (LevKats) [reply src/box/wal.c]: Sounds reasonable. Now it does not exit here but warns and we assume that the size of file is zero.

**Review by Serpentian — APPROVED** [review]
Thank you for addressing the comment) I have no more objections

**Review by nshy — APPROVED** [review]
