### PR TITLE
iproto: fix dropping messages when connection is closed with SHUT_RDWR.

### LINKED ISSUE #6292: Tarantool drops incoming messages when connection is closed with SHUT_RDWR and net_msg_max is reached
Tarantool version: 2.9.0-203-gecd8231b698f

Server config:
```Lua
box.cfg{listen = 3301, net_msg_max = 500 log = 'tarantool.txt'}
box.once('init', function() box.schema.user.grant('guest', 'super') end)
require('console').start()
```

The client code is available by the [link](https://gist.github.com/locker/04c72c39ff2454b62c2820225d1769ae). It sends N messages to the server and then closes connection for either RD or WR or RDWR, without waiting for replies. Under certain circumstances, the server doesn't process all sent messages.

1. Send 200 messages. `box.cfg.net_msg_max` isn't reached.
   1. `./tnt-lost-msg 200 RD # send 200 messages and call shutdown(SHUT_RD)`
   1. `./tnt-lost-msg 200 WR # send 200 messages and call shutdown(SHUT_WR)`
   1. `./tnt-lost-msg 200 RDWR # send 200 messages and call shutdown(SHUT_RDWR)`
   In all the three cases all sent messages are processed: `box.stat.EVAL` is increased by 200 on the server.

2. Send 2000 messages. `box.cfg.net_msg_max` is reached.
   1. `./tnt-lost-msg 2000 RD # send 2000 messages and call shutdown(SHUT_RD)`
   1. `./tnt-lost-msg 2000 WR # send 2000 messages and call shutdown(SHUT_WR)`
   In these two cases all sent messages are processed: `box.stat.EVAL` is increased by 2000 on the server.
   1. `./tnt-lost-msg 2000 RDWR # send 2000 messages and call shutdown(SHUT_RDWR)`
   In this case, however, only about 1000 messages are processed while the rest is dropped.

### PR DESCRIPTION
**Pull request by EvgenyMekhanik**
Fixed dropping incoming messages when connection is closed or SHUT_RDWR
received and net_msg_max or readahead limit is reached. Now we don't close
connection if an error occurred while writing response, but only set a
special flag to stop further writing. Connection will be closed when we
read 0 from socket and process all requests. 
Closes #6292

### CODE REVIEW

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/iproto.cc [hunk 1]
```diff
@@ -1280,6 +1286,18 @@ iproto_flush(struct iproto_connection *con)
...
+	if (!con->can_write) {
+		/* Receiving end was closed. Discard the output. */
+		*end = *begin;
+		/*
+		 * We should activate `con->input` in case it was stopped,
+		 * because of readahead limit is reached.
+		 */
+		if (! ev_is_active(&con->input) &&
+		    rlist_empty(&con->in_stop_list))
+			ev_feed_event(con->loop, &con->input, EV_READ);
```
Comment (locker) [inline src/box/iproto.cc:1298]: Let's return 0 instead of 1 in this case. Then this will be done by the calling function (iproto_connection_on_output).

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+old_readahead = box.cfg.readahead
+old_net_msg_max = box.cfg.net_msg_max
+
+--
+-- Check that tarantool process all requests when connection is closing,
+-- net_msg_max limit is reached and readahead limit is not reached:
+--
+box.cfg ({ net_msg_max = 2, readahead = 4 * old_readahead })
+counter = 0
+expected_counter = old_net_msg_max * 5
```
Comment (locker) [inline test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua:15]: Shouldn't you use box.cfg.net_msg_max here?

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+conn = net.connect(box.cfg.listen)
+for i = 1, expected_counter do \
+    conn:eval('counter = counter + 1', {}, {is_async = true}) \
+end
+conn:close()
+test_run:wait_cond(function() return box.stat.net().CONNECTIONS.current == 0 end)
+test_run:wait_cond(function() return box.stat.net().REQUESTS.current == 0 end)
```
Comment (locker) [inline test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua:22]: Better wait for the counter to be equal to expected_counter. Here and below.

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+
+box.schema.user.grant('guest', 'execute', 'universe')
+old_readahead = box.cfg.readahead
+old_net_msg_max = box.cfg.net_msg_max
+
+--
+-- Check that tarantool process all requests when connection is closing,
+-- net_msg_max limit is reached and readahead limit is not reached:
+--
+box.cfg ({ net_msg_max = 2, readahead = 4 * old_readahead })
```
Comment (locker) [inline test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua:13]: Better not depend on old_readahead here, because we don't know its value. Just set it to a very big value (say 100 MB).

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+conn:close()
+test_run:wait_cond(function() return box.stat.net().CONNECTIONS.current == 0 end)
+test_run:wait_cond(function() return box.stat.net().REQUESTS.current == 0 end)
+assert(counter == expected_counter) -- (because all requests have been executed)
+
+--
+-- Check that tarantool process all requests when connection is closing
+-- readahead limit is reached and net_msg_max limit is not reached:
+--
+box.cfg ({ net_msg_max = 4 * old_net_msg_max, readahead = 128 })
```
Comment (locker) [inline test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua:29]: Again, please don't make this code depend on old_net_msg_max. Instead set it to a very big value and send such a number of requests that won't fit in the readahead limit, say 1000.

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+    conn:eval('counter = counter + 1', {}, {is_async = true}) \
+end
+conn:close()
+test_run:wait_cond(function() return box.stat.net().CONNECTIONS.current == 0 end)
+test_run:wait_cond(function() return box.stat.net().REQUESTS.current == 0 end)
+assert(counter == expected_counter) -- (because all requests have been executed)
+
+--
+-- Check that tarantool process all requests when connection is closing
+-- and readahead and net_msg_max limit is reached:
```
Comment (locker) [inline test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua:43]: This is not needed. The two cases above should cover all the code you added.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/iproto.cc (hunk 1 above)
Comment (EvgenyMekhanik) [reply src/box/iproto.cc:1298]: Fixed

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua (hunk 4 above)
Comment (EvgenyMekhanik) [reply test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua]: Fixed

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua (hunk 5 above)
Comment (EvgenyMekhanik) [reply test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua]: Fixed

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua (hunk 6 above)
Comment (EvgenyMekhanik) [reply test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua]: Fixed

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua (hunk 3 above)
Comment (EvgenyMekhanik) [reply test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua]: Fixed

File: test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua (hunk 2 above)
Comment (EvgenyMekhanik) [reply test/box/gh-6292-fix-dropping-msg-when-connection-closing.test.lua]: It's better to use big value, like 1024, because, if it's small, all requests can be processed before connection closed.

File: src/box/iproto.cc [hunk 7]
```diff
@@ -1325,24 +1343,21 @@ iproto_connection_on_output(ev_loop *loop, struct ev_io *watcher,
...
-			ev_io_stop(con->loop, &con->output);
-	} catch (Exception *e) {
-		e->log();
-		iproto_connection_close(con);
+		if (! ev_is_active(&con->input) &&
+		    rlist_empty(&con->in_stop_list)) {
+			ev_feed_event(loop, &con->input, EV_READ);
+		}
+		if (!con->can_write)
+			break;
```
Comment (locker) [inline src/box/iproto.cc:1357]: This break is redundant. The next iproto_flush() call will return 1, because begin == end. Please remove.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/iproto.cc (hunk 7 above)
Comment (EvgenyMekhanik) [reply src/box/iproto.cc:1357]: No, it will be infinite loop or broken logic without it. Currently we return 0 if `can_write == false`, so loop is infinite. If we return 1 in this case, we not call `ev_feed_event` EV_READ, and connection will never closed.

Comment (EvgenyMekhanik) [reply src/box/iproto.cc:1357]: We can move
````
		if (! ev_is_active(&con->input) &&
		    rlist_empty(&con->in_stop_list)) {
			ev_feed_event(loop, &con->input, EV_READ);
		}
```
to iproto_flush and return 1, or we need this break

Comment (locker) [reply src/box/iproto.cc:1357]: You can move the can_write check after the (begin->used == end->used) check. Then it should work just fine: first we return 0 because of can_write, which will trigger ev_feed_event; on the next iteration of the loop, we return 1, because begin->used == end->used.

Comment (EvgenyMekhanik) [reply src/box/iproto.cc]: Fixed, it was child mistake: i write `*end = *begin` instead of `*begin = *end` in `iproto_flush`, that's why it's not work fine

File: src/box/iproto.cc [hunk 8]
```diff
@@ -1314,7 +1325,14 @@ iproto_flush(struct iproto_connection *con)
...
+		/*
+		 * Don't close the connection on write error. Log the error and
+		 * don't write to the socket anymore. Continue processing
+		 * requests as usual, because the client might have closed the
+		 * socket, but still expect pending requests to complete.
+		*/
+		diag_log();
+		con->can_write = false;
 	}
 	return -1;
```
Comment (locker) [inline src/box/iproto.cc:1337]: One more thing: this function is expected to return -1 only if the socket is blocked. You should set *begin to *end here and return 0 in case of socket write error. Please also move `return -1` upper, to the `if(){}` block where it belongs:

```c
if (nwr > 0) {
    /* ... */
    return -1;
} else if (nwr < 0 && ! sio_wouldblock(errno)) {
    /* ... */
    *begin = *end;
    return 0;
}
```

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/iproto.cc (hunk 8 above)
Comment (EvgenyMekhanik) [reply src/box/iproto.cc:1337]: Yes i see this, may be `goto` in if(!con->can_write)?

Comment (locker) [reply src/box/iproto.cc:1337]: `*begin = *end` is a self-explaining statement (resets the buffers) and it occupies just one line of code so using a goto here would make the code neither easier for understanding nor shorter, hence it's not necessary. IMO in general it's better to avoid using goto except for error reporting, because it breaks the code flow, thus making the code more difficult for understanding.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/iproto.cc (hunk 8 above)
Comment (EvgenyMekhanik) [reply src/box/iproto.cc:1340]: fixed

File: src/box/iproto.cc [hunk 9]
```diff
@@ -1313,8 +1324,18 @@ iproto_flush(struct iproto_connection *con)
...
 		assert(begin->pos <= end->pos);
+		return -1;
 	} else if (nwr < 0 && ! sio_wouldblock(errno)) {
-		diag_raise();
+		/*
+		 * Don't close the connection on write error. Log the error and
+		 * don't write to the socket anymore. Continue processing
+		 * requests as usual, because the client might have closed the
+		 * socket, but still expect pending requests to complete.
+		*/
```
Comment (locker) [inline src/box/iproto.cc:1334]: Bad formatting. Please fix.

**Review by locker — APPROVED** [review]
Please fix the formatting issue (see my only unresolved comment). Otherwise LGTM.

File: changelogs/unreleased/gh-6292-fix-dropping-messages-in-case-when-connection-closing.md [hunk 10]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
```
Comment (Gerold103) [inline changelogs/unreleased/gh-6292-fix-dropping-messages-in-case-when-connection-closing.md:1]: In the commit message please add an empty line before `Closes`.

File: src/box/iproto.cc [hunk 11]
```diff
@@ -1325,24 +1346,19 @@ iproto_connection_on_output(ev_loop *loop, struct ev_io *watcher,
...
-			    rlist_empty(&con->in_stop_list)) {
-				ev_feed_event(loop, &con->input, EV_READ);
-			}
+	int rc;
+	while ((rc = iproto_flush(con)) <= 0) {
+		if (rc != 0) {
+			ev_io_start(loop, &con->output);
+			return;
+		}
+		if (! ev_is_active(&con->input) &&
```
Comment (Gerold103) [inline src/box/iproto.cc:1355]: In new code we do not put whitespace after unary operators.

**Review by Gerold103 — COMMENTED** [review]
2 small comments. Other than that LGTM.

**Review by Gerold103 — APPROVED** [review]

File: src/box/iproto.cc (hunk 11 above)
Comment (EvgenyMekhanik) [reply src/box/iproto.cc]: fixed, thanks

File: changelogs/unreleased/gh-6292-fix-dropping-messages-in-case-when-connection-closing.md (hunk 10 above)
Comment (EvgenyMekhanik) [reply changelogs/unreleased/gh-6292-fix-dropping-messages-in-case-when-connection-closing.md:1]: fixed
