### PR TITLE
test: add test for #7394 (`space:count` bug in memtx MVCC)

### LINKED ISSUE #7394: `space:count()` with mvcc returns not the same as `space:select()`
Here is what I observe in one of vshard tests exclusively when mvcc is enabled:
```
578: ilt.assert_equals(s:select{}, {{1, 1}, {2, 2}, {3, 1}, {4, 2}})
579: ilt.assert_equals(s:count(), 4)
```
the first line passes, the second one doesn't. I couldn't reproduce it on bare tarantool with some simple script, sorry. But it reproduces 100% on this vshard branch: https://github.com/tarantool/vshard/tree/gerold103/mvcc-count-bug if you run `python test-run.py storage-luatest/garbage_collector_test.lua`. The result file shows:
```
not ok 13	bucket_gc.engine:"memtx".memtx_use_mvcc_engine:true.test_unit_bucket_delete_garbage
#   ...s/vshard/test/storage-luatest/garbage_collector_test.lua:579: expected: 4, actual: 3
```
So as you can see, `count()` returns less than `select()` at line 579 of the test. There are no yields between those lines. It didn't fail at the line 578 which checks 4 tuples. Tarantool version was the latest at the moment of doing the test: `2.11.0-entrypoint-232-ged629224f`.

The unusual things which I have here are `on_replace` triggers in `_bucket` space which install an `on_commit` trigger. Could be related. Also the bug doesn't happen without the last commit of the branch. Can't imagine how could it affect the behaviour though.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Closes #7394

# :bangbang: NOTA BENE :bangbang:
If you want to verify that this test fails, you need to checkout commit 88203d4f or older.

# :bangbang: NOTA BENE :bangbang:

### CODE REVIEW

**Review by drewdzzz — COMMENTED** [review]
Is there a way to delete only top stories? Maybe a handle that sets gc in the beginning of story list would be helpful? Then the test would be more reliable - now it depends on gc constants AFAIU.

File: test/box-luatest/gh_7394_memtx_mvcc_space_cnt_bug_test.lua [hunk 1]
```diff
@@ -0,0 +1,38 @@
+local server = require('luatest.server')
```
Comment (Gerold103) [inline test/box-luatest/gh_7394_memtx_mvcc_space_cnt_bug_test.lua:1]: The test seem to belong to `engine-luatest/`, because it is memtx-specific. Otherwise looks good.

**Review by Gerold103 — APPROVED** [review]
Thanks for the patch!

**Comment by drewdzzz** [comment]
I think that this test needs randomization - let's make it nondeterministic to always cover the case, even with other gc parameters

File: test/box-luatest/gh_7394_memtx_mvcc_space_cnt_bug_test.lua (hunk 1 above)
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_7394_memtx_mvcc_space_cnt_bug_test.lua:1]: I guess you are right, but we traditionally add memtx transaction manager tests to `box` suites, so I think we should stick to it. BTW, this test can actually be made multi-engine.

**Review by alyapunov — APPROVED** [review]

**Comment by alyapunov** [comment]
CI alpine is always read, but it should not stop us.

**Comment by alyapunov** [comment]
Cherry-picked to 2.10.
