### PR TITLE
raft: fix an assertion failure in raft_stop_candidate

### LINKED ISSUE #8169: Assertion failure in `raft_stop_candidate` during an ongoing WAL write
**Bug description**

Reproduced on Tarantool 2.11.0-entrypoint-880-g493870ef5.
Reproduced on Tarantool 2.10.4-0-g816000e10.
`Assertion failed: (raft_ev_timer_is_active(&raft->timer)), function raft_stop_candidate, file raft.c, line 1168.`
`raft_stop_candidate` asserts that raft timer should be active when leader is seen (to track the moment of leader death). However this is not true during a WAL write. At such times timer is stopped.

**Steps to reproduce**

Only reproduced in debug mode. Nothing bad happens in release, since the assertion is followed by a no-op.

```lua
-- Instance 1.
-- Step 1.
box.cfg{listen = 3301, replication = {3301, 3302}, election_mode = 'candidate', replication_timeout = 4}

-- Step 3.
box.schema.user.grant('guest', 'replication')

-- Step 4. Wait until the 2nd instance connects before running.
box.error.injection.set('ERRINJ_WAL_DELAY', true)

-- Step 6.
box.cfg{election_mode = 'voter'}

-- Instance 2.
-- Step 2.
box.cfg{listen = 3302, replication = {3301, 3302}, election_mode = 'candidate', replication_timeout = 4, replication_synchro_quorum = 1, read_only = true}

-- Step 5.
box.ctl.promote()

```

After step 6 the 1st instance will fail with an assertion failure:
```
tarantool> box.cfg{election_mode = 'voter'}
Assertion failed: (raft_ev_timer_is_active(&raft->timer)), function raft_stop_candidate, file raft.c, line 1168.
```

The issue was found while debugging the `gh_6036_qsync_order_test.lua` test (#7785).

### PR DESCRIPTION
**Pull request by sergepetrenko**
There is a false assertion in raft_stop_candidate(): it assumes that the node must always have a running timer whenever it sees the leader. This is not true when the node is busy writing the new term on disk.

Cover the mentioned case in the assertion.

Closes #8169

NO_DOC=bugfix

Co-authored-by: Sergey Ostanevich <sergos@tarantool.org>

### CODE REVIEW

File: src/lib/raft/raft.c [hunk 1]
```diff
@@ -1165,7 +1165,8 @@ raft_stop_candidate(struct raft *raft)
 		 * Leader is seen and node is waiting for its death. Do not stop
```
Comment (grafin) [inline src/lib/raft/raft.c:1165]: IMO this comment needs to be updated and include brief description why is_write_in_progress is also checked.

**Review by grafin — APPROVED** [review]
Thanks for the patch! LGTM, consider updating comment near the assertion.

File: changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+## bugfix/raft
+
+* Fixed an assertion failure in case a raft candidate is reconfigured to a voter
```
Comment (Gerold103) [inline changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md:3]: Nit: we usually use term 'election' instead of 'raft' in public texts. Many people don't know what 'raft' is.

**Review by Gerold103 — APPROVED** [review]
Thanks for the fix!

File: changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md (hunk 2 above)
Comment (sergepetrenko) [reply changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md:3]: Ok, fixed:
```diff
diff --git a/changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md b/changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md
index 9db961d16..e7f875280 100644
--- a/changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md
+++ b/changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md
@@ -1,4 +1,4 @@
 ## bugfix/raft
 
-* Fixed an assertion failure in case a raft candidate is reconfigured to a voter
-  during an ongoning WAL write (gh-8169).
+* Fixed an assertion failure in case an election candidate is reconfigured to a
+  voter during an ongoning WAL write (gh-8169).
```

I didn't change the heading though, because we always use `bugfix/raft` and never `bugfix/elections`:
```
➜  sptnt git:(raft-wal-write-assert) grep -r '/raft' ./changelogs 
./changelogs/unreleased/promote-hang.md:## bugfix/raft
./changelogs/unreleased/promote-multiple-infinite.md:## bugfix/raft
./changelogs/unreleased/strict_fencing.md:## feature/raft
./changelogs/unreleased/gh-8169-raft-assert-on-wal-write.md:## bugfix/raft
./changelogs/unreleased/gh-7253-split-brain-early-vote.md:## bugfix/raft
./changelogs/unreleased/gh-7253-split-brain-old-term-txn.md:## bugfix/raft                                                      /0,04s
➜  sptnt git:(raft-wal-write-assert) grep -r '/election' ./changelogs                                                           /0,03s
➜  sptnt git:(raft-wal-write-assert) 
```

File: src/lib/raft/raft.c (hunk 1 above)
Comment (sergepetrenko) [reply src/lib/raft/raft.c:1165]: Sure:
```diff
diff --git a/src/lib/raft/raft.c b/src/lib/raft/raft.c
index 11369e844..4dccc7aea 100644
--- a/src/lib/raft/raft.c
+++ b/src/lib/raft/raft.c
@@ -1163,7 +1163,8 @@ raft_stop_candidate(struct raft *raft)
        } else {
                /*
                 * Leader is seen and node is waiting for its death. Do not stop
-                * the timer.
+                * the timer. If there is a write in progress the timer is
+                * stopped now, but will be re-started once the write completes.
                 */
                assert(raft_ev_timer_is_active(&raft->timer) ||
                       raft->is_write_in_progress);   
```

**Review by grafin — APPROVED** [review]

**Comment by sergepetrenko** [comment]
Forgot to free resources in the unit test. Fixed:
```diff
diff --git a/test/unit/raft.c b/test/unit/raft.c
index d04d9c06f..923eac192 100644
--- a/test/unit/raft.c
+++ b/test/unit/raft.c
@@ -2384,6 +2384,9 @@ raft_test_candidate_disable_during_wal_write(void)
                0 /* Volatile vote. */,
                "{0: 1}" /* Vclock. */
        ), "State is persisted");
+
+       raft_node_destroy(&node);
+       raft_finish_test();
 }
 
 static int
```

**Review by Gerold103 — APPROVED** [review]
Thanks for the fixes!
