### PR TITLE
decimal: fix index comparison with Inf, NaN

### LINKED ISSUE #6377: Assertion when inserting a decimal number in a scalar column containing 1.8e308
I have Ubuntu 20.04. I have Tarantool 2.10, pulled from source today.

I say:
CREATE TABLE t (s1 SCALAR PRIMARY KEY);
INSERT INTO t VALUES (1.8e308),(CAST(1.1 AS DECIMAL));
Result:
tarantool: /home/pgulutzan/tarantool-master/src/lib/core/decimal.c:237: decimal_compare: Assertion `decimal_check_status(&res, &decimal_context) != NULL' failed.
Aborted (core dumped)

### PR DESCRIPTION
**Pull request by sergepetrenko**
There was an assertion failure when inserting  a decimal into an index
which contained double Inf or NaN.

The reason for that was never checking decimal_from_*() return values,
and decimal_from_double() not being able to handle NaN or Inf, because
these values are not representable in decimal numbers.

Start handling decimal_from_<type> return values and fix decimal
comparison with Inf, NaN.

Closes #6377

### CODE REVIEW

**Comment by Totktonada** [comment]
Whether it is possible that ordering within an existing index is changed by this patch? If it is so, I think the upgrade path for some vinyl users should include index rebuilding (or we should do this automatically).

**Comment by sergepetrenko** [comment]
> Whether it is possible that ordering within an existing index is changed by this patch? If it is so, I think the upgrade path for some vinyl users should include index rebuilding (or we should do this automatically).

Looks like it is. I've ran the test from this patch on the current master build in release.

I got the following output for vinyl:
```
Error in decimal     comarison with Inf/NaN
#   expected: {"nan", "-inf", "1", "inf"}
#   actual: {"1", "-inf", "inf"}
```

And for memtx -
```
Duplicate key exists in unique index "pk" in space "test" with old tuple - [-inf]    and new tuple - [1]
```

I'm not sure how we could trigger index rebuilding for vinyl though.

File: src/box/tuple_compare.cc [hunk 1]
```diff
@@ -232,34 +232,53 @@ mp_compare_decimal(const char *lhs, const char *rhs)
...
 			      enum mp_type rhs_type, int k)
 {
 	decimal_t rhs_dec;
+	decimal_t *rc;
 	switch (rhs_type) {
 	case MP_FLOAT:
 	{
 		double d = mp_decode_float(&rhs);
-		decimal_from_double(&rhs_dec, d);
+		int res = compare_decimal_double_infinite(d);
```
Comment (Gerold103) [inline src/box/tuple_compare.cc:257]: Doing the special case handling before trying to convert the value to decimal means you check `isinf/isfinite` twice - first time in your function, second time in `decimal_from_double()`. It might be better to try the conversion first, and handle special cases only if it fails. See the diff (I didn't test it). But I don't mind your version too.
<details><summary>diff</summary>

```Diff
diff --git a/src/box/tuple_compare.cc b/src/box/tuple_compare.cc
index c387af4fa..0e58eba2e 100644
--- a/src/box/tuple_compare.cc
+++ b/src/box/tuple_compare.cc
@@ -232,15 +232,17 @@ mp_compare_decimal(const char *lhs, const char *rhs)
 
 }
 
+/**
+ * Compare decimal to 'not a number' which is either NaN or inf. Decimal value
+ * does not matter then. It is always a valid number.
+ */
 static inline int
-compare_decimal_double_infinite(double rhs)
+decimal_compare_nan(double rhs)
 {
-	if (isfinite(rhs))
-		return 0;
 	/* We assume NaN is less than everything else. */
 	if (isnan(rhs))
 		return 1;
-	/* d is either +Inf or -Inf. */
+	assert(isinf(rhs));
 	return (rhs < 0) - (rhs > 0);
 }
 
@@ -254,19 +256,17 @@ mp_compare_decimal_any_number(decimal_t *lhs, const char *rhs,
 	case MP_FLOAT:
 	{
 		double d = mp_decode_float(&rhs);
-		int res = compare_decimal_double_infinite(d);
-		if (res != 0)
-			return res * k;
 		rc = decimal_from_double(&rhs_dec, d);
+		if (rc == NULL)
+			return decimal_compare_nan(d) * k;
 		break;
 	}
 	case MP_DOUBLE:
 	{
 		double d = mp_decode_double(&rhs);
-		int res = compare_decimal_double_infinite(d);
-		if (res != 0)
-			return res * k;
 		rc = decimal_from_double(&rhs_dec, d);
+		if (rc == NULL)
+			return decimal_compare_nan(d) * k;
 		break;
 	}
 	case MP_INT:
```
</details>

File: src/box/tuple_compare.cc [hunk 2]
```diff
@@ -232,34 +232,53 @@ mp_compare_decimal(const char *lhs, const char *rhs)
 
 }
 
+static inline int
+compare_decimal_double_infinite(double rhs)
```
Comment (Gerold103) [inline src/box/tuple_compare.cc:236]: The function also handles `nan`. "Infinity" is "not a number", but "not a number" is not "infinity". It means it might be better to use `nan` in the name instead of `infinite`.

File: test/engine-luatest/gh_6377_decimal_compare_inf_crash_test.lua [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+g.test_decimal_compare_inf_crash = function(cg)
+    local minf = -1 / 0
+    local inf = 1 / 0
+    local nan = 0 / 0
+    local val = decimal.new(1)
+    local ordered_ret = {
+        tostring(nan),
+        tostring(minf),
+        tostring(val),
+        tostring(inf),
```
Comment (Gerold103) [inline test/engine-luatest/gh_6377_decimal_compare_inf_crash_test.lua:45]: Why do you need to convert everything to string? Shouldn't `exec` return values as is without any problems?

**Review by Gerold103 — DISMISSED** [review]

File: test/engine-luatest/gh_6377_decimal_compare_inf_crash_test.lua (hunk 3 above)
Comment (sergepetrenko) [reply test/engine-luatest/gh_6377_decimal_compare_inf_crash_test.lua:45]: `exec` returns everything correctly, but `nan != nan`, so I can't use the luatest's builtin `assert_equals`.
As an alternative to returning strings, I could check every field explicitly and check `isnan(ret[1])`, but I didn't like that approach.

File: src/box/tuple_compare.cc (hunk 2 above)
Comment (sergepetrenko) [reply src/box/tuple_compare.cc:236]: Agree.

File: src/box/tuple_compare.cc (hunk 1 above)
Comment (sergepetrenko) [reply src/box/tuple_compare.cc]: Thanks for the review and for the proposed changes!
I've applied your diff and force-pushed the updated patch.

**Review by kyukhin — APPROVED** [review]

**Comment by kyukhin** [comment]
Backported to 2.10 as well.
