### PR TITLE
box: support brackets in name resolution for Lua calls

### LINKED ISSUE #8604: Cannot use square brackets in procedure resolution for Lua calls
I have the following schema:

```lua
box.cfg{}

s = box.schema.space:create('s')
s:create_index('i')

rawset(_G, {bar = function() return 777 end, [777] = function() return 777 end}, 'foo')
```

The following calls succeed:
```lua
nb = require('net.box')

nb.self:call('box.space.s:select')
-- []
nb.self:call('foo.bar')
-- 777
```

While the following calls return an error:
```lua
nb = require('net.box')

nb.self:call('box.space['s']:select')
-- error: Procedure 'box.space['s']:select()' is not defined
nb.self:call('box.space[512]:select')
-- error: Procedure 'box.space[512]:select()' is not defined
nb.self:call('foo[777]')
-- error: Procedure 'foo[777]' is not defined
```

### PR DESCRIPTION
**Pull request by alyapunov**
Fefactor lua name resolution, simplify and comment. Add an ability to specify path with brackets, for example in 'box.space[512]:get' or 'box.space["test"]:get'.
Only literals (strings and numbers) are supported.

Closes #8604

@TarantoolBot document
Title: square brackets in procedure resolution for Lua calls

Square brackets are now supported in Lua call procedure resolution. This is applicable to `net.box` connection objects `call` method as well as `box.schema.func.call`.

Examples of function calls with square brackets can be found in the test to this patch.

### CODE REVIEW

File: src/box/lua/call.c [hunk 1]
```diff
@@ -93,74 +93,80 @@ get_call_serializer(void)
...
+
+			if (end - start >= 2 && start[0] == end[-1] &&
+			    (start[0] == '"' || start[0] == '\'')) {
+				/* Quoted string, just extract it. */
+				lua_pushlstring(L, start + 1, end - start - 2);
+			} else {
+				/* Must be a number, convert from string. */
+				lua_getfield(L, LUA_GLOBALSINDEX, "tonumber");
+				lua_pushlstring(L, start, end - start);
+				lua_call(L, 1, 1);
```
Comment (locker) [inline src/box/lua/call.c:148]: I'd rather use `lua_isnumber` and `lua_tonumber` here.

Comment (alyapunov) [reply src/box/lua/call.c]: Thanks, applied the following patch:
```diff
diff --git a/src/box/lua/call.c b/src/box/lua/call.c
index e0e4cbd34f..05780ab93d 100644
--- a/src/box/lua/call.c
+++ b/src/box/lua/call.c
@@ -101,7 +101,7 @@ get_call_serializer(void)
 static int
 box_lua_find(lua_State *L, const char *name, const char *name_end)
 {
-       lua_checkstack(L, 3); /* No more than 3 entries are needed. */
+       lua_checkstack(L, 2); /* No more than 2 entries are needed. */
        int top = lua_gettop(L);
 
        /* Take the first token. */
@@ -143,9 +143,13 @@ box_lua_find(lua_State *L, const char *name, const char *name_end)
                                lua_pushlstring(L, start + 1, end - start - 2);
                        } else {
                                /* Must be a number, convert from string. */
-                               lua_getfield(L, LUA_GLOBALSINDEX, "tonumber");
                                lua_pushlstring(L, start, end - start);
-                               lua_call(L, 1, 1);
+                               int success;
+                               lua_Number num = lua_tonumberx(L, -1, &success);
+                               if (!success)
+                                       goto no_such_proc;
+                               lua_pop(L, 1);
+                               lua_pushnumber(L, num);
                        }
                        start = end + 1; /* skip closing bracket. */
                }
```

File: src/box/lua/call.c [hunk 2]
```diff
@@ -93,74 +93,84 @@ get_call_serializer(void)
...
+
+			if (end - start >= 2 && start[0] == end[-1] &&
+			    (start[0] == '"' || start[0] == '\'')) {
+				/* Quoted string, just extract it. */
+				lua_pushlstring(L, start + 1, end - start - 2);
+			} else {
+				/* Must be a number, convert from string. */
+				lua_pushlstring(L, start, end - start);
+				int success;
+				lua_Number num = lua_tonumberx(L, -1, &success);
```
Comment (CuriousGeorgiy) [inline src/box/lua/call.c:148]: I have a concern this is not optimal in terms of performance.

File: src/box/lua/call.c [hunk 3]
```diff
@@ -93,74 +93,84 @@ get_call_serializer(void)
...
 
-
-	lua_pushlstring(L, start, name_end - start);
-	lua_gettable(L, index);
-	if (!lua_isfunction(L, -1) && !lua_istable(L, -1)) {
+	/* Now at top+1 must be the function, and at top+2 may be the object. */
+	assert(lua_gettop(L) - top >= 1 && lua_gettop(L) - top <= 2);
+	if (!lua_isfunction(L, top + 1) && !lua_istable(L, top + 1)) {
 		/* lua_call or lua_gettable would raise a type error
 		 * for us, but our own message is more verbose. */
```
Comment (CuriousGeorgiy) [inline src/box/lua/call.c:165]: Looks like you need to move this comment to `no_such_proc` label.

File: test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+        test('a[333]:ping')
+        test('a.f')
+        test('a.g:ping')
+    end)
+end
+
+-- Checks that error detection in procedure resolution for Lua calls works
+-- correctly.
+g.test_procedure_resolution_errors = function(cg)
+    cg.server:exec(function()
```
Comment (CuriousGeorgiy) [inline test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua:66]: Nit: AFAIC, you don't need to create a server for this test.

File: test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+    end)
+end)
+
+g.after_all(function(cg)
+    cg.server:drop()
+end)
+
+-- Checks that procedure resolution for Lua calls works correctly.
+g.test_procedure_resolution = function(cg)
+    cg.server:exec(function()
```
Comment (CuriousGeorgiy) [inline test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua:39]: Nit: AFAIC, you don't need to create a server for this test.

File: test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua [hunk 6]
```diff
@@ -0,0 +1,117 @@
+local server = require('luatest.server')
+local t = require('luatest')
+
+local g = t.group()
+g.before_all(function(cg)
+    cg.server = server:new()
+    cg.server:start()
+    cg.server:exec(function()
```
Comment (CuriousGeorgiy) [inline test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua:8]: Nit: AFAIC, you don't need to create a server for this test.

File: src/box/lua/call.c [hunk 7]
```diff
@@ -93,74 +93,84 @@ get_call_serializer(void)
...
+				lua_pushnumber(L, num);
+			}
+			start = end + 1; /* skip closing bracket. */
 		}
 
-		start = end + 1; /* next piece of a.b.c */
-		index = lua_gettop(L); /* top of the stack */
-		objstack = index - top;
+		lua_gettable(L, -2); /* get child object from parent object. */
+		lua_remove(L, -2); /* drop previous parent object. */
```
Comment (CuriousGeorgiy) [inline src/box/lua/call.c:158]: I have a concern your stack manipulation is not optimal: I think the original implementation used stack indices for a reason.

**Comment by alyapunov** [comment]
After perf analysis I've decided to remove strchr from my code, here is diff:
```diff
diff --git a/src/box/lua/call.c b/src/box/lua/call.c
index 05780ab93d..9fbd35c09b 100644
--- a/src/box/lua/call.c
+++ b/src/box/lua/call.c
@@ -106,7 +106,8 @@ box_lua_find(lua_State *L, const char *name, const char *name_end)
 
        /* Take the first token. */
        const char *start = name;
-       while (start != name_end && strchr(".:[", *start) == NULL)
+       while (start != name_end && *start != '.' &&
+              *start != ':' && *start != '[')
                start++;
        lua_pushlstring(L, name, start - name);
        lua_gettable(L, LUA_GLOBALSINDEX);
@@ -121,7 +122,8 @@ box_lua_find(lua_State *L, const char *name, const char *name_end)
                if (delim == '.') {
                        /* Look for the next token. */
                        const char *end = start;
-                       while (end != name_end && strchr(".:[", *end) == NULL)
+                       while (end != name_end && *end != '.' &&
+                              *end != ':' && *end != '[')
                                end++;
                        lua_pushlstring(L, start, end - start);
                        start = end;
@@ -130,11 +132,9 @@ box_lua_find(lua_State *L, const char *name, const char *name_end)
                        lua_gettable(L, -2); /* get function from object. */
                        lua_insert(L, -2); /* swap function and object. */
                        break;
-               } else {
-                       assert(delim == '[');
+               } else if (delim == '[') {
                        const char *end = memchr(start, ']', name_end - start);
-                       if (end == NULL ||
-                           (end != name_end && strchr(".:[", end[1]) == NULL))
+                       if (end == NULL)
                                goto no_such_proc;
 
                        if (end - start >= 2 && start[0] == end[-1] &&
@@ -152,6 +152,8 @@ box_lua_find(lua_State *L, const char *name, const char *name_end)
                                lua_pushnumber(L, num);
                        }
                        start = end + 1; /* skip closing bracket. */
+               } else {
+                       goto no_such_proc;
                }
 
                lua_gettable(L, -2); /* get child object from parent object. */
```

File: src/box/lua/call.c (hunk 7 above)
Comment (alyapunov) [reply src/box/lua/call.c:160]: I terms of stack I make N operations with O(1) cost here, while the original code makes one O(N) operation.  Perhaps we could save the time of foreign call itself, but the original code has to call `lua_checkstack` each round, so I bet it's a fair trade.

File: test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua (hunk 6 above)
Comment (alyapunov) [reply test/box-luatest/gh_8604_support_square_brackets_in_procedure_resolution_for_lua_calls_test.lua:8]: Thanks, rewrote the test to use main instance.

File: src/box/lua/call.c (hunk 3 above)
Comment (alyapunov) [reply src/box/lua/call.c:167]: Originally this comment was in the same place, where lua_isfunction check is..
Now I think we should simply remove this comment as meaningless.

**Review by CuriousGeorgiy — APPROVED** [review]

**Comment by locker** [comment]
I don't think we should push this to 2.11 because it's a new feature. Also, we add the version label to issues, not to PRs. I added 3.0 to #8604 a while back.

**Review by p7nov — APPROVED** [review]
