### PR TITLE
net.box: reference the connection object from asynchronous requests

### LINKED ISSUE #9629: Active connection is closed, when Lua GC is invoked
**Bug description**

The connection is closed, when it's active but it doesn't have any strong references. It's caused by Lua GC. Related: https://github.com/tarantool/vshard/pull/469

* OS: Linux
* OS Version: NixOS
* Architecture: amd64

```
Tarantool 3.1.0-entrypoint-51-g47940311e
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/var/empty/local -DENABLE_BACKTRACE=FALSE
Compiler: GNU-12.3.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/serpentian/Programming/tnt/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/serpentian/Programming/tnt/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb **-O0**
```

**Steps to reproduce**

```lua
local t = require('luatest')
local server = require('luatest.server')
local nb = require('net.box')
local g = t.group()

g.before_all = function(lg)
    lg.master = server:new({alias = 'master'})
    lg.master:start()
    lg.master:exec(function()
        rawset(_G, 'echo', function(arg)
            return arg
        end)
    end)
end

g.after_all = function(lg)
    lg.master:drop()
end

g.test_conn_not_deleted_without_ref = function(lg)
    local a = string.rep('a', 1024 * 1024 * 500)
    local opts = {is_async = true}
    local f = nb.connect(lg.master.net_box_uri):call('_G.echo', {a}, opts)
    collectgarbage()
    local res, err = f:wait_result(10)
    t.assert_equals(err, nil)
    t.assert_equals(#res[1], #a)
end
```

**Actual behavior**

```text
[001] not ok 1	replication-luatest.lua_gc.test_conn_not_deleted_without_ref
[001] #   ...g/tnt/tarantool/test/replication-luatest/lua_gc_test.lua:26: expected: nil, actual: Connection closed
[001] #   stack traceback:
[001] #   	...g/tnt/tarantool/test/replication-luatest/lua_gc_test.lua:26: in function 'replication-luatest.lua_gc.test_conn_not_deleted_without_ref'
[001] #   	...
[001] #   	[C]: in function 'xpcall'
[001] # Ran 1 tests in 1.849 seconds, 0 succeeded, 1 failed
```

If you'll delete `collectgarbage` the test will probably pass. If you'll create ref to conn, test also passes e.g:

```diff
diff --git a/test/replication-luatest/lua_gc_test.lua b/test/replication-luatest/lua_gc_test.lua
index 77052385c..0fda9f62e 100644
--- a/test/replication-luatest/lua_gc_test.lua
+++ b/test/replication-luatest/lua_gc_test.lua
@@ -20,7 +20,8 @@ end
 g.test_conn_not_deleted_without_ref = function(lg)
     local a = string.rep('a', 1024 * 1024 * 500)
     local opts = {is_async = true}
-    local f = nb.connect(lg.master.net_box_uri):call('_G.echo', {a}, opts)
+    local conn = nb.connect(lg.master.net_box_uri)
+    local f = conn:call('_G.echo', {a}, opts)
     collectgarbage()
     local res, err = f:wait_result(10)
     t.assert_equals(err, nil)

```

**Expected behavior**

Connection should be active while request is done.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
This patch fixes a bug that caused a connection with asynchronous requests to get garbage collected prematurely.

Closes #9629

### CODE REVIEW

**Review by ochaplashkin — APPROVED** [review]

**Review by Serpentian — APPROVED** [review]
Thank you for the patch! Looks great to me

File: test/box-luatest/gh_9629_netbox_async_request_connection_gc_test.lua [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+end)
+
+-- Tests that a connection with asynchronous requests does not get garbage
+-- collected.
+g.test_async_request_connection_gc = function(cg)
+    local c = net_box.connect(cg.server.net_box_uri)
+    local f = c:eval('return 777', {}, {is_async = true})
+    c = nil -- luacheck: no unused
+    collectgarbage()
+    local res, err = f:wait_result(0.1)
```
Comment (sergepetrenko) [inline test/box-luatest/gh_9629_netbox_async_request_connection_gc_test.lua:23]: Please increase the timeout. For example, to 1 second.
I was able to get the following error, when ran the test a ton of times in parallel:
```
[046] box-luatest/gh_9629_netbox_async_request_conne>                 [ fail ]
[046] Test failed! Output from reject file /tmp/t/rejects/box-luatest/gh_9629_netbox_async_request_connection_gc.reject:
[046] Tarantool version is 3.1.0-entrypoint-161-g4a5b793639
[046] TAP version 13
[046] 1..1
[046] # Started on Fri Mar 22 15:04:19 2024
[046] # Starting group: box-luatest.gh_9629_netbox_async_request_connection_gc
[046] not ok 1	box-luatest.gh_9629_netbox_async_request_connection_gc.test_async_request_connection_gc
[046] #   ...test/gh_9629_netbox_async_request_connection_gc_test.lua:24: expected: nil, actual: timed out
[046] #   stack traceback:
[046] #   	...test/gh_9629_netbox_async_request_connection_gc_test.lua:24: in function 'box-luatest.gh_9629_netbox_async_request_connection_gc.test_async_request_connection_gc'
[046] #   	...
[046] #   	[C]: in function 'xpcall'
[046] # Ran 1 tests in 3.030 seconds, 0 succeeded, 1 failed
[046] 
[046] [test-run server "luatest_server"] The log file /private/tmp/t/046_box-luatest/gh_9629_netbox_async_request_connection_gc_test.log has zero size
```
I was able to achieve this on my machine, meaning this error will be rather frequent in CI.

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the patch!

I only have one comment regarding the test. Otherwise LGTM.

File: test/box-luatest/gh_9629_netbox_async_request_connection_gc_test.lua (hunk 1 above)
Comment (CuriousGeorgiy) [reply test/box-luatest/gh_9629_netbox_async_request_connection_gc_test.lua]: Sorry, I haven't thought about this previously. Set the timeout to 10 seconds.

File: changelogs/unreleased/gh-9629-netbox-async-request-connection-gc.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+## bugfix/lua
+
+* Fixed a bug in `net.box` the allowed a connection with asynchronous requests
+  to get garbage collected (gh-9629).
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply changelogs/unreleased/gh-9629-netbox-async-request-connection-gc.md]: Fixed.

**Review by sergepetrenko — APPROVED** [review]
Thanks! LGTM.

**Comment by sergepetrenko** [comment]
Backports:
2.11 https://github.com/tarantool/tarantool/pull/9880
3.0 https://github.com/tarantool/tarantool/pull/9881
