### PR TITLE
fiber: use alternative signal stack

### LINKED ISSUE #9222: Use alternate stack (sigaltstack) for signal handlers
We use guard page at the end of the stack protected with `mprotect` to get a signal and crash on stack overflow instead of memory corruption. In a signal handler we use same stack which will probably generate signal again. Let's use alternate stack for signal handlers.

### PR DESCRIPTION
**Pull request by locker**
We install a signal handler that prints the stack trace on SIGSEGV, SIGBUS, SIGILL, SIGFPE. The signal handler uses the current stack. This works fine for most issues, but not for stack overflow, because the latter makes the current stack unusable, leading to a crash in the signal handler. Let's install an alternative signal stack in each thread so that we can print the stack trace on stack overflow.

Closes #9222

### CODE REVIEW

**Review by nshy — APPROVED** [review]

**Review by p7nov — APPROVED** [review]

**Review by ochaplashkin — APPROVED** [review]

File: src/lib/core/fiber.c [hunk 1]
```diff
@@ -223,6 +223,48 @@ fiber_mprotect(void *addr, size_t len, int prot)
...
+ * this function.
+ */
+static void
+signal_stack_init(void)
+{
+	stack_t stack;
+	stack.ss_flags = 0;
+	/*
+	 * It is said that SIGSTKSZ is not enough for one of llvm sanitizers
+	 * (probably asan, because this test fails with segmentation fault if
```
Comment (Totktonada) [inline src/lib/core/fiber.c:242]: Nit: It seems, 'this test' lost its sense in the new context.

**Comment by locker** [comment]
Added `use_sigaltstack=0` to `ASAN_OPTIONS` to fix ASAN CI failures:

```diff
diff --git a/.test.mk b/.test.mk
index bbf75d649167..9d79b06ef1e1 100644
--- a/.test.mk
+++ b/.test.mk
@@ -100,7 +100,7 @@ TEST_RUN_ENV_ASAN = ASAN=ON \
                     ASAN_OPTIONS=heap_profile=0:unmap_shadow_on_exit=1:$\
                                  detect_invalid_pointer_pairs=1:symbolize=1:$\
                                  detect_leaks=1:dump_instruction_bytes=1:$\
-                                 print_suppressions=0
+                                 print_suppressions=0:use_sigaltstack=0
 LUAJIT_TEST_ENV_ASAN = LSAN_OPTIONS=suppressions=${PWD}/asan/lsan.supp \
                        ASAN_OPTIONS=detect_invalid_pointer_pairs=1:$\
                                     detect_leaks=1:$\
```

**Comment by locker** [comment]
Change of plan. Let's skip `sigaltstack` for ASAN builds because ASAN installs a signal stack by itself.

```diff
diff --git a/src/lib/core/fiber.c b/src/lib/core/fiber.c
index 1f8b0ea40905..1437036062d1 100644
--- a/src/lib/core/fiber.c
+++ b/src/lib/core/fiber.c
@@ -231,24 +231,23 @@ fiber_mprotect(void *addr, size_t len, int prot)
  * be called in each thread because the SIGSEGV signal is thread-directed.
  * At thread exit, one should call signal_stack_free() to free the stack set by
  * this function.
+ *
+ * We skip this for ASAN because it installs its own signal stack.
  */
 static void
 signal_stack_init(void)
 {
+#ifndef ENABLE_ASAN
 	stack_t stack;
 	stack.ss_flags = 0;
-	/*
-	 * It is said that SIGSTKSZ is not enough for one of llvm sanitizers
-	 * (probably asan, because this test fails with segmentation fault if
-	 * we use SIGSTKSZ as alternative signal stack size when we use it).
-	 * https://github.com/llvm/llvm-project/blame/699231ab3c7dd8f028d868b103481fa901f3c721/compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp#L169
-	 */
+	/* SIGSTKSZ doesn't seem to be enough for libunwind. */
 	stack.ss_size = 4 * SIGSTKSZ;
 	stack.ss_sp = xmalloc(stack.ss_size);
 	if (sigaltstack(&stack, NULL) != 0) {
 		say_syserror("sigaltstack");
 		free(stack.ss_sp);
 	}
+#endif
 }
 
 /**
@@ -257,12 +256,14 @@ signal_stack_init(void)
 static void
 signal_stack_free(void)
 {
+#ifndef ENABLE_ASAN
 	stack_t stack;
 	if (sigaltstack(NULL, &stack) != 0) {
 		say_syserror("sigaltstack");
 	} else {
 		free(stack.ss_sp);
 	}
+#endif
 }
 
 static __thread bool fiber_top_enabled = false;
```

File: src/lib/core/fiber.c (hunk 1 above)
Comment (locker) [reply src/lib/core/fiber.c]: True. I removed this comment because we decided to disable this feature for ASAN, see https://github.com/tarantool/tarantool/pull/9280#issuecomment-1772554850.

**Comment by locker** [comment]
Cherry-picked to 2.11.
