### PR TITLE
sql: fix use-after-poison in variable binding

### LINKED ISSUE #10398: asan: use after free (found in sql-luatest)
Found within https://github.com/tarantool/tarantool/pull/10232 (see [failed job](https://github.com/tarantool/tarantool/actions/runs/10352988325/job/28654816793?pr=10232]))

Branch [mandesero:mandesero/asan-build-with-gc64-on](https://github.com/mandesero/tarantool/tree/mandesero/asan-build-with-gc64-on)

Can be reproduced without test-run.

```test.lua
-- test.lua
local varbinary = require('varbinary')
local val = varbinary.new('asd')
print(box.execute([[SELECT ?;]], {val}).rows[1][1], val)

val = box.execute([[SELECT RANDOMBLOB(10);]]).rows[1][1]
print(varbinary.is(val))
print(box.execute([[SELECT ?;]], {val}).rows[1][1], val)
```

Build and run.
```bash
cmake -S . -B . -DENABLE_WERROR=ON -DENABLE_ASAN=ON -DENABLE_UB_SANITIZER=ON -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=OFF -DENABLE_FUZZER=ON -DTEST_BUILD=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFIBER_STACK_SIZE=640Kb -DLUAJIT_ENABLE_GC64=ON -DCMAKE_BUILD_TYPE=Debug -DLUAJIT_USE_ASAN_HARDENING=ON && make -j
./src/tarantool  --name instance-001 --config ./doc/examples/config/single.yaml -i test.lua
```

Actual behavior.
```
[001] sql-luatest/gh_10243_varbinary_bound_variable_>                                                                                             [ fail ]
[001] Test failed! Output from reject file /tmp/t/rejects/sql-luatest/gh_10243_varbinary_bound_variable.reject:
[001] Tarantool version is 3.2.0-entrypoint-218-g1dc136028
[001] TAP version 13
[001] 1..1
[001] # Started on Mon Aug 12 14:47:44 2024
[001] # Starting group: sql-luatest.gh_10243_varbinary_bound_variable
[001] luatest | started logging into a pipe, SIGHUP log rotation disabled
[001] master | started logging into a pipe, SIGHUP log rotation disabled
[001] master | 2024-08-12 14:47:44.587 [157013] main/104/server_instance.lua I> Tarantool 3.2.0-entrypoint-218-g1dc136028 Linux-x86_64-Debug
[001] master | 2024-08-12 14:47:44.587 [157013] main/104/server_instance.lua I> log level 5 (INFO)
[001] master | 2024-08-12 14:47:44.588 [157013] main/104/server_instance.lua I> wal/engine cleanup is paused
[001] master | 2024-08-12 14:47:44.588 [157013] main/104/server_instance.lua I> mapping 268435456 bytes for memtx tuple arena...
[001] master | 2024-08-12 14:47:44.588 [157013] main/104/server_instance.lua I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.050000
[001] master | 2024-08-12 14:47:44.588 [157013] main/104/server_instance.lua I> mapping 134217728 bytes for vinyl tuple arena...
[001] master | 2024-08-12 14:47:44.603 [157013] main/104/server_instance.lua I> update replication_synchro_quorum = 1
[001] master | 2024-08-12 14:47:44.604 [157013] main/104/server_instance.lua I> instance uuid 8c16417a-fa45-44bc-8387-6fb4b7fc1417
[001] master | 2024-08-12 14:47:44.604 [157013] main/104/server_instance.lua I> tx_binary: bound to unix/:(socket)
[001] master | 2024-08-12 14:47:44.604 [157013] main/104/server_instance.lua I> initializing an empty data directory
[001] master | 2024-08-12 14:47:44.690 [157013] main/104/server_instance.lua I> assigned id 1 to replica 8c16417a-fa45-44bc-8387-6fb4b7fc1417
[001] master | 2024-08-12 14:47:44.691 [157013] main/104/server_instance.lua I> update replication_synchro_quorum = 1
[001] master | 2024-08-12 14:47:44.691 [157013] main/104/server_instance.lua I> replicaset uuid 6a52c40a-22f1-47e1-bb4b-1de9a488e497
[001] master | 2024-08-12 14:47:44.693 [157013] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
[001] master | 2024-08-12 14:47:44.699 [157013] snapshot/101/main I> done
[001] master | 2024-08-12 14:47:44.700 [157013] main/104/server_instance.lua I> ready to accept requests
[001] master | 2024-08-12 14:47:44.700 [157013] main/105/gc I> wal/engine cleanup is resumed
[001] master | 2024-08-12 14:47:44.701 [157013] main/104/server_instance.lua/box.load_cfg I> set 'log' configuration option to "| tee /tmp/t/001_sql-luatest/master-VULXhj2nmVJe/master.log"
[001] master | 2024-08-12 14:47:44.701 [157013] main/104/server_instance.lua/box.load_cfg I> set 'listen' configuration option to "/tmp/t/001_sql-luatest/master-VULXhj2nmVJe/master.sock"
[001] master | 2024-08-12 14:47:44.705 [157013] main/106/checkpoint_daemon I> scheduled next checkpoint for Mon Aug 12 16:20:05 2024
[001] master | 2024-08-12 14:47:44.707 [157013] main I> entering the event loop
[001] luatest | 2024-08-12 14:47:44.715 [157001] main/104/luatest/luatest.log I> Server "master" (pid: 157013) started
[001] luatest | 2024-08-12 14:47:44.717 [157001] main/104/luatest/luatest.log I> Start test "sql-luatest.gh_10243_varbinary_bound_variable.test_exists"
[001] master | =================================================================
[001] master | ==157013==ERROR: AddressSanitizer: use-after-poison on address 0x7f487221472b at pc 0x555868569027 bp 0x7f4873784290 sp 0x7f4873783a60
[001] master | READ of size 4 at 0x7f487221472b thread T0
[001] master |     #0 0x555868569026 in __asan_memcpy (/home/mandesero/myforks/tarantool/src/tarantool+0x1351026) (BuildId: 07c00fd52368de007071c7559a6a86cbd1ccfced)
[001] master |     #1 0x5558697822c4 in lua_sql_bind_decode /home/mandesero/myforks/tarantool/src/box/lua/execute.c:349:3
[001] master |     #2 0x55586977fd21 in lua_sql_bind_list_decode /home/mandesero/myforks/tarantool/src/box/lua/execute.c:438:7
[001] master |     #3 0x555869784a36 in lbox_execute /home/mandesero/myforks/tarantool/src/box/lua/execute.c:467:16
[001] master |     #4 0x555869bb9248 in lj_BC_FUNCC /home/mandesero/myforks/tarantool/third_party/luajit/src/lj_vm.S:852
[001] master |     #5 0x555869bc4240 in jit_secure_call /home/mandesero/myforks/tarantool/third_party/luajit/src/lj_api.c:104:3
[001] master |     #6 0x555869be2b2e in lua_call /home/mandesero/myforks/tarantool/third_party/luajit/src/lj_api.c:1148:3
[001] master |     #7 0x5558696a06c1 in execute_lua_eval /home/mandesero/myforks/tarantool/src/box/lua/call.c:459:2
[001] master |     #8 0x555869bb9248 in lj_BC_FUNCC /home/mandesero/myforks/tarantool/third_party/luajit/src/lj_vm.S:852
[001] master |     #9 0x555869be3e0a in lua_pcall /home/mandesero/myforks/tarantool/third_party/luajit/src/lj_api.c:1173:12
[001] master |     #10 0x55586983d0be in luaT_call /home/mandesero/myforks/tarantool/src/lua/utils.c:695:6
[001] master |     #11 0x5558696994a1 in box_process_lua /home/mandesero/myforks/tarantool/src/box/lua/call.c:798:6
[001] master |     #12 0x55586969a0db in box_lua_eval /home/mandesero/myforks/tarantool/src/box/lua/call.c:844:9
[001] master |     #13 0x5558691956a7 in box_process_eval /home/mandesero/myforks/tarantool/src/box/call.c:272:11
[001] master |     #14 0x5558685f05a3 in tx_process_call(cmsg*) /home/mandesero/myforks/tarantool/src/box/iproto.cc:2632:8
[001] master |     #15 0x555869960715 in cmsg_deliver /home/mandesero/myforks/tarantool/src/lib/core/cbus.c:350:2
[001] master |     #16 0x55586996f86c in fiber_pool_f /home/mandesero/myforks/tarantool/src/lib/core/fiber_pool.c:65:3
[001] master |     #17 0x5558685afab3 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*) /home/mandesero/myforks/tarantool/src/lib/core/fiber.h:1324:10
[001] master |     #18 0x55586992339b in fiber_loop /home/mandesero/myforks/tarantool/src/lib/core/fiber.c:1162:18
[001] master |     #19 0x55586a95d3d8 in coro_init /home/mandesero/myforks/tarantool/third_party/coro/coro.c:108:3
[001] master |
[001] master | Address 0x7f487221472b is a wild pointer inside of access range of size 0x000000000004.
[001] master | SUMMARY: AddressSanitizer: use-after-poison (/home/mandesero/myforks/tarantool/src/tarantool+0x1351026) (BuildId: 07c00fd52368de007071c7559a6a86cbd1ccfced) in __asan_memcpy
[001] master | Shadow bytes around the buggy address:
[001] master |   0x0fe98e43a890: 00 00 00 00 00 00 00 00 f7 f7 f7 f7 00 f7 f7 f7
[001] master |   0x0fe98e43a8a0: f7 00 00 00 00 00 00 f7 f7 f7 f7 00 f7 f7 f7 f7
[001] master |   0x0fe98e43a8b0: 00 00 00 00 00 00 f7 f7 f7 f7 00 f7 f7 f7 f7 00
[001] master |   0x0fe98e43a8c0: 00 00 00 00 00 f7 f7 f7 f7 00 f7 f7 f7 f7 00 00
[001] master |   0x0fe98e43a8d0: 00 00 00 00 00 00 00 00 00 f7 f7 f7 f7 00 f7 f7
[001] master | =>0x0fe98e43a8e0: f7 f7 00 00 00[03]f7 f7 f7 f7 00 f7 f7 f7 f7 00
[001] master |   0x0fe98e43a8f0: 00 00 00 00 00 00 00 00 00 00 f7 f7 f7 f7 00 00
[001] master |   0x0fe98e43a900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[001] master |   0x0fe98e43a910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[001] master |   0x0fe98e43a920: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[001] master |   0x0fe98e43a930: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[001] master | Shadow byte legend (one shadow byte represents 8 application bytes):
[001] master |   Addressable:           00
[001] master |   Partially addressable: 01 02 03 04 05 06 07
[001] master |   Heap left redzone:       fa
[001] master |   Freed heap region:       fd
[001] master |   Stack left redzone:      f1
[001] master |   Stack mid redzone:       f2
[001] master |   Stack right redzone:     f3
[001] master |   Stack after return:      f5
[001] master |   Stack use after scope:   f8
[001] master |   Global redzone:          f9
[001] master |   Global init order:       f6
[001] master |   Poisoned by user:        f7
[001] master |   Container overflow:      fc
[001] master |   Array cookie:            ac
[001] master |   Intra object redzone:    bb
[001] master |   ASan internal:           fe
[001] master |   Left alloca redzone:     ca
[001] master |   Right alloca redzone:    cb
[001] master | ==157013==ABORTING
[001] not ok 1	sql-luatest.gh_10243_varbinary_bound_variable.test_exists
[001] #   Peer closed
[001] #   stack traceback:
[001] #   	...t/sql-luatest/gh_10243_varbinary_bound_variable_test.lua:16: in function 'sql-luatest.gh_10243_varbinary_bound_variable.test_exists'
[001] #   	...
[001] #   	[C]: in function 'xpcall'
[001] #   artifacts:
[001] #   	master -> /tmp/t/001_sql-luatest/artifacts/master-VULXhj2nmVJe
[001] # Ran 1 tests in 0.713 seconds, 0 succeeded, 1 errored
```

Expected behavior - no asan errors.

-----
I tried to debug a little, it seems that the memory for `\0` is not allocated, but want to put `\0` into a new buffer:

https://github.com/tarantool/tarantool/blob/90552e55e0921405c43ea086ae418a72c9f000e4/src/box/lua/execute.c#L348C1-L349C52

`field.sval.len` is `3`, but we tried to copy 4 bytes from `field.sval.data`

### PR DESCRIPTION
**Pull request by mandesero**
This patch fixes a bug found by the ASAN instrumentation of LuaJIT allocator [1]. The problem is using `memcpy` beyond the size of the buffer being copied.

Failing tests:
  - ./test/sql-luatest/gh_10243_varbinary_bound_variable_test.lua

[1]: Issue https://github.com/tarantool/tarantool/issues/10231

Closes https://github.com/tarantool/tarantool/issues/10398

NO_DOC=bugfix
NO_CHANGELOG=bugfix
NO_TEST=rely on existing test (run failing tests with tarantool build described in [1]).

### CODE REVIEW

File: src/box/lua/execute.c [hunk 1]
```diff
@@ -346,7 +346,8 @@ lua_sql_bind_decode(struct lua_State *L, struct sql_bind *bind, int idx, int i)
 		 * will be poped from Lua stack.
 		 */
 		buf = xregion_alloc(region, field.sval.len + 1);
-		memcpy(buf, field.sval.data, field.sval.len + 1);
+		memcpy(buf, field.sval.data, field.sval.len);
+		buf[field.sval.len] = '\0';
```
Comment (ImeevMA) [inline src/box/lua/execute.c:350]: I think the `\0` is unnecessary. It's not a C-style string, and its length is described in `bind->bytes`. I think it is better to remove `+1` in the two lines above.

File: src/box/lua/execute.c [hunk 2]
```diff
@@ -346,7 +346,8 @@ lua_sql_bind_decode(struct lua_State *L, struct sql_bind *bind, int idx, int i)
 		 * will be poped from Lua stack.
```
Comment (ImeevMA) [inline src/box/lua/execute.c:346]: Please use `sql:` instead of `c:` in commit-message title. Also, I think it is better to be more specific - for example `sql: fix use-after-poison in variable binding`.

File: src/box/lua/execute.c [hunk 3]
```diff
@@ -346,7 +346,8 @@ lua_sql_bind_decode(struct lua_State *L, struct sql_bind *bind, int idx, int i)
...
 		 */
```
Comment (ImeevMA) [inline src/box/lua/execute.c:347]: Please expand in NO_TEST the description of the test that tests this patch. I, for example, am not sure what this test is.

**Review by ImeevMA — COMMENTED** [review]
Hi! Thank you for the patch! Please see my comments below.

File: src/box/lua/execute.c (hunk 1 above)
Comment (mandesero) [reply src/box/lua/execute.c]: Okay, that makes sense. Done.

File: src/box/lua/execute.c (hunk 2 above)
Comment (mandesero) [reply src/box/lua/execute.c:346]: Commit message replaced.

File: src/box/lua/execute.c (hunk 3 above)
Comment (mandesero) [reply src/box/lua/execute.c:347]: I tried to describe it in a little more detail.

**Review by ImeevMA — APPROVED** [review]

**Review by mkokryashkin — APPROVED** [review]

**Comment by Totktonada** [comment]
Pushed to `master`, a future `3.2.0` release.

Backported to `release/3.1` (a future `3.1.2` release) in PR #10439.

Backported to `release/2.11` (will likely go to `2.11.5`) in PR #10440.
