### PR TITLE
console flavours vs txn

### LINKED ISSUE #7288: Wrong error returned via iproto when transaction was active
If transaction was open and any error has occurred, then upon return from function error text would be completely lost and instead would be emitted `Transaction is active at return from function`.
Error is relevant either with memtx_use_mvcc_engine or without.

Steps to reproduce:

Run any simple tarantool
```
box.cfg{ listen = '127.0.0.1:3301', memtx_use_mvcc_engine = true }
box.schema.user.grant('guest', 'super', nil, nil, {if_not_exists = true})
```

Then, connect to it with any iproto client, for ex tarantoolctl, and execute transaction, that will fail inside
```
$ tarantoolctl connect 127.0.0.1:3301
connected to 127.0.0.1:3301
127.0.0.1:3301> box.begin() error("something") box.commit()
---
- error: Transaction is active at return from function
...
127.0.0.1:3301> box.begin() box.space[513]:select() box.commit()
---
- error: Transaction is active at return from function
...
```

Error `something` is completely missed. It is neither logged into server log nor returned to client.

### Expected behavior

* If an error has occurred, then exactly this error must be returned to the client
* `Transaction is active at return from function` should be logged into server's log, with possible additional information, like name of a function call, calling peer, etc.
```
2022-06-21 14:37:16.247 [82769] main/129/main C> Transaction is active at return from function 'user_function'
 stack traceback:
	simple.lua:120: in function 'user_function'
	[C]: in function 'pcall'
	builtin/box/console.lua:404: in function <builtin/box/console.lua:379>
	[C]: at 0x0102634b34
```
* And only if there were no errors, open transaction at the ond of the function should raise error by itself , return it to the client AND log a message.

### LINKED ISSUE #7413: local/remote txt and remote binary consoles works differently in case of transactions
Suppose we have:

```
box.cfg{ listen = '127.0.0.1:3301', memtx_use_mvcc_engine = true }
box.schema.user.grant('guest', 'super', nil, nil) -- to be able to use remote console
my = box.schema.create_space('my')
my:create_index('primary', {parts = {{field = 1, type = 'unsigned'}}})
```

Then in local console interactive transaction works:
```
 tarantool> box.begin()
---
...

 tarantool> box.space.my:replace{2}
---
- [2]
...

 tarantool> box.commit()
---
...
 tarantool> box.space.my:fselect()
---
- - ​+-----+
  - ​|col1 |
  - ​+-----+
  - ​|  2  |
  - ​+-----+
...
```

Same with text console. That is when you start console on this server with `require('console').listen('127.0.0.1:3303')` and then connect from different instance of tarantool:
```
 tarantool> require('console').connect('127.0.0.1:3303')
connected to 127.0.0.1:3303
---
- true
...

 127.0.0.1:3303> box.begin()
---
...

 127.0.0.1:3303> box.space.my:replace{3}
---
- [3]
...

 127.0.0.1:3303> box.commit()
---
...

 127.0.0.1:3303> box.space.my:fselect()
---
- - ​+-----+
  - ​|col1 |
  - ​+-----+
  - ​|  2  |
  - ​|  3  |
  - ​+-----+
...
```

But with binary console you get:
```
 tarantool> require('console').connect('127.0.0.1:3301')
connected to 127.0.0.1:3301
---
- true
...

 127.0.0.1:3301> box.begin() -- transaction it silently rolled back after execution besides the error message
---
- error: Transaction is active at return from function
...
```

It would be nice if binary console allows interactive transactions too (technically it only possible for DB engines that allows interactive transactions because in case of binary console we have to yield in between evaluating expressions).

### PR DESCRIPTION
**Pull request by nshy**
The issue is if in binary remote console a error is thrown in expression like "box.begin() error('something') box.commit()" then it is overwritten by iproto check for active transactions at the end of eval. The solution is to rollback active transaction in this case in console code before iproto check.

Closes #7288
Closes #7413

### CODE REVIEW

File: test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua [hunk 1]
```diff
@@ -0,0 +1,171 @@
+local server = require('test.luatest_helpers.server')
+local console = require('console')
+local fiber = require('fiber')
+local fio = require('fio')
+local string = require('string')
+local t = require('luatest')
+
+local alocal = {
+    start = function()
+        box.cfg{memtx_use_mvcc_engine = true}
```
Comment (locker) [inline test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua:11]: Let's set `work_dir` to a location inside `VARDIR` so as not to pollute the current directory if the test is run via `luatest`. Also, let's create the test Unix socket (`.gh-7288.sock`) in `VARDIR` as well for the same reason.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/lua/console.lua [hunk 2]
```diff
@@ -401,7 +401,14 @@ local function local_eval(storage, line)
...
     end
-    return format(pcall(fun))
+    local in_txn_before = ffi.C.box_txn()
+    -- with pack/unpack there is issue with trailing nils in multiret
+    return (function(success, ...)
+        if not success and not in_txn_before and ffi.C.box_txn() then
+            box.rollback()
+        end
+        return format(success, ...)
+    end)(pcall(fun))
```
Comment (Totktonada) [inline src/box/lua/console.lua:411]: Nit: We generally avoid creating closures on demand due to extra Lua GC pressure, when it is possible to define a function and call it many times.

File: test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+
+    connect = function(self, console)
+        console:send(string.format('require("console").connect("%s")', self.uri))
+    end,
+
+    disconnect = true,
+}
+
+local flavours = {
+    alocal = alocal,
```
Comment (Totktonada) [inline test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua:45]: 'alocal', because 'local' is the keyword? You can use `{['local'] = <...>}` if you want.

File: src/box/lua/console.lua (hunk 2 above)
Comment (nshy) [reply src/box/lua/console.lua:411]: Ok. Closure unnecessary here in the first place. I failed at first to pass multiret with trailing nils with `unpack({pcall()})`. For example:

```
 tarantool> (function(...) print(unpack{...}) end)(1, nil)
1
---
...
```

They say `table.pack` available in Lua 5.2 allows to handle this situation but we don't have it. Fortunately one can write table.pack in Lua! :)

File: test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua (hunk 3 above)
Comment (nshy) [reply test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua:45]: But I still need to write `{['local'] = alocal}` so I'd like to use same name for both.

Comment (Totktonada) [reply test/app-luatest/gh_7288_console_flavours_vs_txn_test.lua:52]: Okay.

File: src/box/lua/console.lua (hunk 2 above)
Comment (nshy) [reply src/box/lua/console.lua]: I see, you suggested introducing a function and I considered as alternative to pack/unpack as in latest version.

**Review by locker — CHANGES_REQUESTED** [review]
Please always reply to review comments (so that I can see what was fixed and what wasn't and why) and assign the PR to the reviewer(s) when it's ready (otherwise I might overlook it).

See a few comments below.

File: src/lua/table.lua [hunk 4]
```diff
@@ -95,3 +102,15 @@ require('table.new')
...
+
+-- Why pack2? If table.pack present then LuaJIT tests run in compat5.2 mode
+-- trying to load code invalid for Lua5.1 and fail.
+--
+-- See:
+-- third_party/luajit/test/LuaJIT-tests/test.lua
+--  local function default_tags()
+--
+-- Let's lust work it around.
+table.pack2 = table_pack
```
[the remark this answers is not in the document]
Comment (igormunkin) [reply src/lua/table.lua:114]: I don't think that introducing a public function from (strictly saying) another language, to be used in a single spot is a good solution. There is a nice solution proposed by @Totktonada above. There is another by introducing the needed helper as a local function in the module. I suggest proceed with one of these approaches, not with introducing table.pack (and table.unpack). At least until there is a well-elaborated decision regarding these builtins.

File: test/luatest_helpers/server.lua [hunk 5]
```diff
@@ -20,6 +20,7 @@ local Server = luatest.Server:inherit({})
 
 local WAIT_TIMEOUT = 60
 local WAIT_DELAY = 0.1
+local COMMAND = 'test/instances/default.lua'
```
Comment (locker) [inline test/luatest_helpers/server.lua:23]: Nit: I'd make this path absolute right here:

```Lua
local SOURCE_DIR = fio.abspath(os.getenv('SOURCEDIR') or '.')
local DEFAULT_COMMAND = fio.pathjoin(SOURCE_DIR, 'test/instances/default.lua')
```

File: changelogs/unreleased/use-streams-in-binary-console.md [hunk 6]
```diff
@@ -0,0 +1,3 @@
+## feature/console
```
Comment (locker) [inline changelogs/unreleased/use-streams-in-binary-console.md:1]: Nit: Should be `feature/core`. Also, please, for the record, please file a ticket describing the problem you fix.

**Review by locker — CHANGES_REQUESTED** [review]
