### PR TITLE
box: allow to set *_uuid options to NULL

### LINKED ISSUE #8714: Reapplying the instance_uuid and replicaset_uuid parameters with a box.NULL field results in an error.
Prior to https://github.com/tarantool/tarantool/commit/9b2b3e58792fb1d5b079b110d50e7c5803803a4d, reapplying `instance_uuid` and `replicaset_uuid` did not throw an error if the corresponding values were `NULL`:
```
Tarantool 3.0.0-entrypoint-195-g2644add4e
type 'help' for interactive help
tarantool> box.cfg{log_level = 0}
---
...

tarantool> box.cfg.replicaset_uuid
---
- null
...

tarantool> box.cfg.instance_uuid
---
- null
...

tarantool> box.cfg{replicaset_uuid = nil}
---
...

tarantool> box.cfg{instance_uuid = nil}
---
...

tarantool> box.cfg{replicaset_uuid = box.NULL}
---
...

tarantool> box.cfg{instance_uuid = box.NULL}
---
...
```

However this has changed after the patch:
```
Tarantool 3.0.0-entrypoint-272-g2afde5b1d
type 'help' for interactive help
tarantool> box.cfg{log_level = 0}
---
...

tarantool> box.cfg.replicaset_uuid
---
- null
...

tarantool> box.cfg.instance_uuid
---
- null
...

tarantool> box.cfg{replicaset_uuid = nil}
---
...

tarantool> box.cfg{instance_uuid = nil}
---
...

tarantool> box.cfg{replicaset_uuid = box.NULL}
---
- error: Can't set option 'replicaset_uuid' dynamically
...

tarantool> box.cfg{instance_uuid = box.NULL}
---
- error: Can't set option 'instance_uuid' dynamically
...
```

The new behavior is incorrect and should be fixed.

### PR DESCRIPTION
**Pull request by ImeevMA**
This patch allows to set replicaset_uuid and instance_uuid to box.NULL. This fixes the issue described in #8714, however it introduces another change in behavior - we can now set these parameters to NULL even if they weren't NULL before. However, since we still cannot set a different uuid after setting the parameters to NULL, and we can still set the old uuid for them, this behavior is considered acceptable.

Closes #8714

NO_DOC=bugfix
NO_CHANGELOG=the bug was not released

### CODE REVIEW

File: test/box-luatest/gh_8714_set_null_to_xxx_uuid_test.lua [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+    g.server:start()
+    g.server:exec(function()
+        local ok, err = pcall(box.cfg, {instance_uuid = box.NULL})
+        t.assert(ok)
+        t.assert_equals(err, nil)
+        ok, err = pcall(box.cfg, {replicaset_uuid = box.NULL})
+        t.assert(ok)
+        t.assert_equals(err, nil)
+    end)
+    g.server:stop()
```
Comment (locker) [inline test/box-luatest/gh_8714_set_null_to_xxx_uuid_test.lua:23]: If the test fails, the server won't be stopped properly. You should use `before_test` to start the server and `after_test` to stop it, because `after_test` runs even on test failure.

File: test/box-luatest/gh_8714_set_null_to_xxx_uuid_test.lua [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+        t.assert(ok)
+        t.assert_equals(err, nil)
+        ok, err = pcall(box.cfg, {replicaset_uuid = old_uuid})
+        t.assert(ok)
+        t.assert_equals(err, nil)
+
+        -- Another uuid cannot be set if *_uuid is set.
+        ok, err = pcall(box.cfg, {instance_uuid = new_uuid})
+        t.assert(not ok)
+        t.assert_equals(err.message, err_ins)
```
Comment (locker) [inline test/box-luatest/gh_8714_set_null_to_xxx_uuid_test.lua:52]: Better use `t.assert_error_message_equals`:

```Lua
t.assert_error_message_equals(err_ins, box.cfg, {instance_uuid = new_uuid})
```

File: test/box-luatest/gh_8714_set_null_to_xxx_uuid_test.lua (hunk 1 above)
Comment (ImeevMA) [reply test/box-luatest/gh_8714_set_null_to_xxx_uuid_test.lua]: Thank you for the review! Fixed.

File: test/box-luatest/gh_8714_set_null_to_xxx_uuid_test.lua (hunk 2 above)
Comment (ImeevMA) [reply test/box-luatest/gh_8714_set_null_to_xxx_uuid_test.lua]: Fixed.

**Review by locker — APPROVED** [review]

File: src/box/lua/load_cfg.lua [hunk 3]
```diff
@@ -446,13 +446,15 @@ local log_cfg_option = {
 
 
 local function check_instance_uuid()
-    if box.cfg.instance_uuid ~= box.info.uuid then
+    if box.cfg.instance_uuid ~= box.NULL and
+       box.cfg.instance_uuid ~= box.info.uuid then
         box.error(box.error.RELOAD_CFG, 'instance_uuid')
     end
 end
```
Comment (Totktonada) [inline src/box/lua/load_cfg.lua:453]: Shouldn't we handle `nil` and `box.NULL` differently?

* `nil` -> pass over
* `box.NULL` -> check that `box.cfg.instance_uuid == nil`
* anything else -> compare with `box.info.uuid` (BTW, why not `box.cfg.instance_uuid`?)

Comment (ImeevMA) [reply src/box/lua/load_cfg.lua:453]: We don't have the old `box.cfg.instance_uuid` value because it was overwritten by the new one when `box.cfg{instance_uuid = ...}` was executed. I believe this is normal for the options described in `dynamic_cfg` . Because of this, we have no way to compare the old value with the new one.

Comment (locker) [reply src/box/lua/load_cfg.lua:453]: - The option callback isn't invoked if `box.cfg.instance_uuid` is `nil`.
- It'd be complicated because the `box.cfg` option callback currently doesn't have access to the old value. I don't think that fixing it is worthwhile. Semantically, resetting `instance_uuid` to `box.NULL` after it was set to a non-nil value looks correct, which was mentioned in the commit log.
- If the new value stored in `box.cfg.instance_uuid` isn't nil, we compare it with the current value, which is stored in `box.info.uuid`.

File: src/box/lua/load_cfg.lua [hunk 4]
```diff
@@ -446,13 +446,15 @@ local log_cfg_option = {
 
 
 local function check_instance_uuid()
-    if box.cfg.instance_uuid ~= box.info.uuid then
+    if box.cfg.instance_uuid ~= box.NULL and
```
[the remark this answers is not in the document]
Comment (locker) [reply src/box/lua/load_cfg.lua:449]: The option callback isn't invoked in `box.cfg.instance_uuid` is `nil`. The only way to set `box.cfg.instance_uuid` to `nil` is using `box.NULL` so the comparison looks proper.

[the remark this answers is not in the document]
Comment (Totktonada) [reply src/box/lua/load_cfg.lua:449]: This is minor and since the previous comment is resolved, I'll close this too.

**Review by Totktonada — APPROVED** [review]
