### PR TITLE
mvcc: fix reverse tree iterators gap tracking

### LINKED ISSUE #7073: `memtx_tx_tuple_clarify` on tuple which story was previously garbage collected
# Disclaimer
This ticket describes a _theoretical_ scenario (currently _not reproducible_) that can occur with reverse tree iterators — its purpose is to serve as a reference.

# Description
https://github.com/tarantool/tarantool/blob/ed46feb27087247ab5ee47fcf63f28c3ad842099/src/box/memtx_tree.cc#L673-L707

Consider the following scenario for _reverse_ type iterators.
Inside the call to `memtx_track_gap`, `memtx_tx_story_gc` gets invoked and garbage collects the `res` tuple's _story_: `res` becomes _clean_ (i.e., `res->is_dirty == true`).

After that instead of getting `NULL` from `memtx_tx_tuple_clarify` and calling `iterator->next_raw` we will get the same tuple, as if it is in the primary index:
https://github.com/tarantool/tarantool/blob/ed46feb27087247ab5ee47fcf63f28c3ad842099/src/box/memtx_tree.cc#L731-L737

Only _reverse_ iterators are subject to this behaviour, as _forward_ iterator do not require this extra shift:
https://github.com/tarantool/tarantool/blob/ed46feb27087247ab5ee47fcf63f28c3ad842099/src/box/memtx_tree.cc#L673-L686

In the case of _forward_ iterators the `res` tuple is equal to the `successor` tuple, which is used in _tracking_ and hence cannot get garbage collected:
https://github.com/tarantool/tarantool/blob/ed46feb27087247ab5ee47fcf63f28c3ad842099/src/box/memtx_tree.cc#L717-L726

Currently, because of

### LINKED ISSUE #7113: Reverse tree iterators gap tracking bug
Consider the following snippet:
https://github.com/tarantool/tarantool/blob/2d97e4c8cee5a064e2ac4206912d5b03415c7ccf/src/box/memtx_tree.cc#L673-L726

Apparently, it is buggy for reverse iterators: instead of tracking gaps for successors of keys, it tracks gaps for tuples shifted by one to the left of the successor.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Apparently, the current implementation of `tree_iterator_start_raw` is
buggy for reverse iterators: instead of tracking gaps for successors of
keys, it tracks gaps for tuples shifted by one to the left of the
successor: reorder the code of `tree_iterator_start_raw` to get
the successor tuple prior to shifting done for reverse iterators and
simplify the implementation to make it more straightforward and thus
comprehensible.

Closes #7073
Closes #7113

### CODE REVIEW

**Review by alyapunov — COMMENTED** [review]
Waiting for test, and I should recheck that the code is correct in all cases..

File: src/box/memtx_tree.cc [hunk 1]
```diff
@@ -670,6 +670,10 @@ tree_iterator_start_raw(struct iterator *iterator, struct tuple **ret)
 		}
 	}
 
+	/* it->tree_iterator is positioned on successor of a key! */
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:673]: Fixed: changed the comment to reflect the current implementation.

File: src/box/memtx_tree.cc [hunk 2]
```diff
@@ -684,56 +691,31 @@ tree_iterator_start_raw(struct iterator *iterator, struct tuple **ret)
...
-
-/********MVCC TRANSACTION MANAGER STORY GARBAGE COLLECTION BOUND START*********/
-		memtx_tx_track_gap(in_txn(), space, idx, successor, type,
+	if (key_is_full && empty_result)
+		memtx_tx_track_point(txn, space, idx, it->key_data.key);
+	if (!key_is_full || ((type == ITER_GE || type == ITER_LE) && !equals) ||
+	    (type == ITER_GT || type == ITER_LT))
+		memtx_tx_track_gap(txn, space, idx, successor, type,
 				   it->key_data.key, it->key_data.part_count);
-/*********MVCC TRANSACTION MANAGER STORY GARBAGE COLLECTION BOUND END**********/
```
Comment (drewdzzz) [inline src/box/memtx_tree.cc:725]: Why have you removed `MVCC TRANSACTION MANAGER STORY GARBAGE COLLECTION BOUND`? It seems to me it can be useful for further maintenance.

File: test/box-luatest/gh_7113_rev_tree_iters_gap_tracking_test.lua [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+                        {{}})
+        tx:commit()
+        box.space.s:insert{0, 0}
+
+        tx:begin()
+        box.space.s:delete{0, 0}
+        t.assert_equals(tx("box.space.s:select({0, 0}, {iterator = 'LE'})"),
+                        {{}})
+        tx:commit()
+        box.space.s:insert{0, 0}
```
Comment (drewdzzz) [inline test/box-luatest/gh_7113_rev_tree_iters_gap_tracking_test.lua:113]: Could you please explain what this test may catch? (I've run this snippet for 100000 times on master and nothing happened)

**Review by drewdzzz — CHANGES_REQUESTED** [review]

File: src/box/memtx_tree.cc [hunk 4]
```diff
@@ -684,56 +691,31 @@ tree_iterator_start_raw(struct iterator *iterator, struct tuple **ret)
...
-		/* it->tree_iterator is positioned on successor of a key! */
-		struct tuple *successor = res == NULL ? NULL : res->tuple;
-
-/********MVCC TRANSACTION MANAGER STORY GARBAGE COLLECTION BOUND START*********/
-		memtx_tx_track_gap(in_txn(), space, idx, successor, type,
+	if (key_is_full && empty_result)
+		memtx_tx_track_point(txn, space, idx, it->key_data.key);
+	if (!key_is_full || ((type == ITER_GE || type == ITER_LE) && !equals) ||
+	    (type == ITER_GT || type == ITER_LT))
+		memtx_tx_track_gap(txn, space, idx, successor, type,
```
[the remark this answers is not in the document]
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:712]: Thank you for your sharp eye! :)

Strange we do not have a test for this basic case...

> I was surprised when I found out that ITER_ALL have the same behavior as ITER_GE. It's quite odd.

Well, apparently, the [documentation](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_index/pairs/#box-index-iterator-types) states this:
> Same as box.index.GE. 

For what it's worth, I agree that this iterator type is redundant. 🤷‍♂️

File: src/box/memtx_tree.cc (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:725]: Fixed: retained these comments.

File: src/box/memtx_tree.cc [hunk 5]
```diff
@@ -684,56 +691,34 @@ tree_iterator_start_raw(struct iterator *iterator, struct tuple **ret)
...
-				   it->key_data.key, it->key_data.part_count);
-		return 0;
-	}
-
-	struct memtx_tree_data<USE_HINT> *res =
-		memtx_tree_iterator_get_elem(tree, &it->tree_iterator);
-	uint32_t mk_index = 0;
-	if (res != NULL) {
-		*ret = res->tuple;
+	res = memtx_tree_iterator_get_elem(tree, &it->tree_iterator);
```
Comment (alyapunov) [inline src/box/memtx_tree.cc:694]: Please move this line to to the `if` branch above. It will allow to avoid extra iterator dereference in the most common cases. `memtx_tree_iterator_get_elem` is rather cheap but avoiding is free.

File: src/box/memtx_tree.cc [hunk 6]
```diff
@@ -684,56 +691,34 @@ tree_iterator_start_raw(struct iterator *iterator, struct tuple **ret)
...
+	bool empty_result = !equals && (type == ITER_EQ || type == ITER_REQ);
```
Comment (alyapunov) [inline src/box/memtx_tree.cc:695]: I don't like the variable name. If `res == NULL` (or if `clarify` returns NULL) the result of select will be empty even if `empty_result == false`. Also we usually use `is_`, `has_` etc prefix for boolean variable names.
What about `is_empty_eq`?. I'm not sure. I would also be glad if there was a clear comment here.

**Review by alyapunov — CHANGES_REQUESTED** [review]

**Review by drewdzzz — COMMENTED** [review]
That's OK, but the code will change after you fix the other reviewer's remarks. Then request the review again, please.

File: src/box/memtx_tree.cc (hunk 5 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:694]: Great remark, thanks! Didn't pay attention to this.

Fixed: moved it inside the `if` branch.

File: src/box/memtx_tree.cc (hunk 6 above)
Comment (CuriousGeorgiy) [reply src/box/memtx_tree.cc:695]: Fixed: changed the variable name to `eq_match` and supplied it with a comment.

**Review by drewdzzz — APPROVED** [review]

**Review by alyapunov — APPROVED** [review]
