### PR TITLE
memtx: do not pass pagination key to MVCC

### LINKED ISSUE #10448: MVCC SEGV_MAPERR when inserting between tuple from select by `after=b` in not unique index with path (same key in all tuples) and this `b`
**Bug description**

* OS: Linux 6.8.0-39-generic

Tarantool 3.1.1-0-gb65f805
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/tmp/tarantool_install946144238/static-build/build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -static-libstdc++ -fno-common -msse2  -fmacro-prefix-map=/tmp/tarantool_install946144238=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -static-libstdc++ -fno-common -msse2  -fmacro-prefix-map=/tmp/tarantool_install946144238=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2

**Steps to reproduce**

```lua
local dir = "tmp"
assert(require("fio").mktree(dir))

box.cfg({
  memtx_dir = dir,
  vinyl_dir = dir,
  wal_dir = dir,

  memtx_use_mvcc_engine = true,
  log_level = "error",
})

local space = box.schema.space.create("SPACE", {
  format = {
    { is_nullable = false, name = "ID", type = "unsigned" },
    { is_nullable = true, name = "DATA", type = "map" },
  },
  is_sync = false,
})

space:create_index("ID", {
  unique = true,
  type = "TREE",
  parts = {
    { field = "ID", type = "unsigned" },
  },
})

space:create_index("KEY", {
  unique = false,
  type = "TREE",
  parts = {
    { field = "DATA", type = "unsigned", path = "key", is_nullable = false },
  },
})

box.begin({ txn_isolation = "read-committed" })

local key = { key = 0 }

local left_id = 1
local left = space:insert({ left_id, key })

local right_id = 3
local right = space:insert({ right_id, key })

-- EQ, GE, ...
assert(space.index.KEY:select({}, { iterator = "EQ", after = left })[1] == right)
--or
-- LE, REQ
assert(space.index.KEY:select({}, { iterator = "LE", after = right })[1] == left)

-- before `left` - ok
space:insert({ left_id - 1, key })

-- after `right` - ok
space:insert({ right_id + 1, key })

-- between `left` and `right` - crash
space:insert({ left_id + 1, key })

box.commit()

os.exit(0)

```

Initially, I had a problem that arose periodically for the index KEY that have part with `exclude_null = true`

Besides Segmentation fault
also received with varying frequency
```
munmap_chunk(): invalid pointer
malloc(): invalid size (unsorted)
malloc(): smallbin double linked list corrupted
malloc(): unsorted double linked list corrupted
malloc(): memory corruption (fast)
free(): invalid next size (fast)

corrupted size vs. prev_size
```

Not reproduced after 3.1.0, but I didn't see anything similar in changelog
possibly just not related to the above

more difficult to reproduce
 - all time correct without bootstrap vshard (0.1.27)  🤷‍♂
 - index ID created before KEY

```lua
local dir = "tmp"
assert(require("fio").mktree(dir))

local bucket_count = 10
local uuid = "aaaaaaaa-aaaa-aaaa-aaaa-000000000000"

local cfg = {
  memtx_dir = dir,
  vinyl_dir = dir,
  wal_dir = dir,

  sharding = {
    ["aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"] = {
      replicas = {
        [uuid] = { uri = "test:@127.0.0.1:3301", master = true },
      },
    },
  },

  memtx_use_mvcc_engine = true,
  bucket_count = bucket_count,
  log_level = "error",
}

rawset(_G, "vshard", require("vshard"))

vshard.storage.cfg(cfg, uuid)
vshard.router.cfg(cfg)
vshard.router.bootstrap()

local space = box.schema.space.create("VARIABLE", {
  format = {
    { is_nullable = false, name = "bucket_id", type = "unsigned" },
    { is_nullable = false, name = "REVISION", type = "unsigned" },
    { is_nullable = false, name = "ID", type = "unsigned" },

    { is_nullable = true, name = "IS_ACTUAL", type = "boolean" },
    { is_nullable = true, name = "DATA", type = "map" },
  },
  is_sync = false,
})

space:create_index("bucket_id", {
  unique = true,
  type = "TREE",
  parts = {
    { field = "bucket_id", type = "unsigned" },
    { field = "REVISION", type = "unsigned" },
  },
})

space:create_index("KEY", {
  unique = false,
  type = "TREE",
  parts = {
    { field = "DATA", type = "unsigned", path = "key", is_nullable = false },
    { field = "IS_ACTUAL", type = "boolean", exclude_null = true, is_nullable = true },
  },
})

space:create_index("ID", {
  unique = true,
  type = "TREE",
  parts = {
    { field = "bucket_id", type = "unsigned", is_nullable = false },
    { field = "ID", type = "unsigned", is_nullable = false },
    { field = "IS_ACTUAL", type = "boolean", exclude_null = true, is_nullable = true },
  },
})

local offset = -1
local function next_revision(bucket_id)
  offset = offset + 1
  return offset * bucket_count + bucket_id
end

box.begin({ txn_isolation = "read-committed" })

for bucket_id = 1, bucket_count do
  local revision = next_revision(bucket_id)
  local id = revision

  space:insert({ bucket_id, revision, id, true, { key = 0 } })
end

local after
repeat
  local iter = space.index.KEY:pairs({ 0 }, { iterator = "LE", after = after })
  after = nil

  for _, tuple in iter:unwrap() do
    local bucket_id = tuple.bucket_id

    local set_not_actual = { { "=", "IS_ACTUAL", box.NULL } }
    space:update({ bucket_id, tuple.REVISION }, set_not_actual)

    space:insert({ bucket_id, next_revision(bucket_id), tuple.ID, true, { key = 0 } })

    after = tuple
    break
  end
until not after

box.commit()

os.exit(0)

```

**Actual behavior**
```
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x6093d529db40
  siginfo: 0x6093d529dc70
  rax      0x0                0
  rbx      0x700bc8007a26     123195902425638
  rcx      0x0                0
  rdx      0x0                0
  rsi      0x700bdfb041b5     123196299821493
  rdi      0x0                0
  rsp      0x700be08809e8     123196313962984
  rbp      0x6093d544bc60     106188054510688
  r8       0x6093d39f5758     106188026894168
  r9       0x2                2
  r10      0x6093d1c405e0     106187995743712
  r11      0x1                1
  r12      0x6093d52df9a0     106188053019040
  r13      0x6093d52dfa30     106188053019184
  r14      0x700be08809f8     123196313963000
  r15      0x6093d5463ff0     106188054609904
  rip      0x6093d1189264     106187984507492
  eflags   0x10206            66054
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1724149018
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x6093d10e33c2 in crash_signal_cb+162
#2  0x700be1645320 in __sigaction+80
#3  0x6093d1189264 in mp_compare_uint+4
#4  0x6093d18a46ef in int tuple_compare_with_key_slowpath<false, false, true, false, false>(tuple*, unsigned long, char const*, unsigned int, unsigned long, key_def*)+271
#5  0x6093d0f5ebf5 in memtx_tx_history_add_stmt+2677
#6  0x6093d0f6cb04 in memtx_space_replace_all_keys+452
#7  0x6093d0f6a5d3 in memtx_space_execute_replace+163
#8  0x6093d0fbeb79 in space_execute_dml+393
#9  0x6093d0ff41ce in box_process_rw+174
#10 0x6093d0ffa449 in box_insert+89
#11 0x6093d1099b5c in lbox_insert+204
#12 0x6093d1125753 in lj_BC_FUNCC+70
#13 0x6093d112c627 in lua_pcall+119
#14 0x6093d10c875f in luaT_call+15
#15 0x6093d10be041 in lua_main+97
#16 0x6093d10bed17 in run_script_f+2183
#17 0x6093d0f2a840 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+16
#18 0x6093d10ea5d7 in fiber_loop+55
#19 0x6093d19a6968 in coro_init+72
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by drewdzzz**
Currently, when starting an iterator in memtx tree on a range request, we pass key from `start_data` to memtx MVCC. The problem is `start_data` can contain pagination key that is extracted with `cmp_def`, but MVCC performs all comparisons with `key_def`. Fortunately, first parts of `cmp_def` is actually `key_def` of the index, so let's crop `start_data` by passing `part_count` not greater than `key_def->part_count` to MVCC.

Closes #10448

### CODE REVIEW

**Review by mkostoevr — APPROVED** [review]
LGTM. I like that it introduces more MVCC tests.

File: test/box-luatest/gh_10448_pagination_mvcc_non_unique_index_test.lua [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+            parts = {
+                {field = "v", type = "unsigned", is_nullable = false},
+            },
+        })
+
+        space:insert({1, 1})
+        space:insert({5, 5})
+        space:insert({10, 10})
+
+        -- The function inserts given tuple concurrently with pagination
```
Comment (lenkis) [inline test/box-luatest/gh_10448_pagination_mvcc_non_unique_index_test.lua:104]:
```suggestion
        -- The function inserts the given tuple concurrently with pagination
```

**Review by lenkis — APPROVED** [review]

**Review by CuriousGeorgiy — APPROVED** [review]

File: src/box/memtx_tree.cc [hunk 2]
```diff
@@ -869,11 +869,18 @@ tree_iterator_start(struct iterator *iterator, struct tuple **ret)
...
+	 * `part_count` not greater than `key_def->part_count`.
+	 */
+	uint32_t key_part_count = index->base.def->key_def->part_count;
 	if (!key_is_full ||
 	    ((type == ITER_GE || type == ITER_LE) && !equals) ||
 	    (type == ITER_GT || type == ITER_LT))
 		memtx_tx_track_gap(txn, space, index_base, successor, type,
-				   start_data.key, start_data.part_count);
+				   start_data.key,
+				   MIN(start_data.part_count, key_part_count));
```
Comment (CuriousGeorgiy) [inline src/box/memtx_tree.cc:883]: How can `start_data.part_count` be less than `key_part_count`?

Comment (drewdzzz) [reply src/box/memtx_tree.cc:883]: When pagination is not used, passed key is stored there. It can have less parts than `key_def` (empty key, for example).

**Comment by sergepetrenko** [comment]
Backports:
3.1 https://github.com/tarantool/tarantool/pull/10465
2.11 https://github.com/tarantool/tarantool/pull/10466
