### PR TITLE
box: make ffi select work on M1

### LINKED ISSUE #7946: Select FFI does not work on M1
If we call select on memtx space (or another function that calls `select_ffi` under the hood) on M1, it will throw an error `NYI: cannot call this C function (yet)`, just try this simple script:
```lua
box.cfg{}
s = box.schema.create_space('test')
s:create_index('pk')
s:replace{0, 0}
s:select{}
```
The snippet from `schema.lua` that throws an error:
```lua
nok = builtin.box_select(index.space_id, index.id, iterator, offset, limit,
                         key, key_end, iterator_pos, iterator_pos_end,
                         fetch_pos, port) ~= 0
``` 
The problem is in LuaJIT: https://github.com/LuaJIT/LuaJIT/issues/205
We can fix the issue or simply create a wrapper with reordered arguments for `box_select`.

### PR DESCRIPTION
**Pull request by drewdzzz**
Recently, ffi select was broken on M1 - it turned out that ffi on M1 poorly supports a big quantity of arguments, which was used for pagination. Fortunately, there is a workaround - we can pass only 64-bit integer arguments beyond the 8th argument. Let's do it.

Closes #7946

### CODE REVIEW

**Comment by drewdzzz** [comment]
I don't have my own M1, so @Gumix will check manually if the patch is OK.

**Comment by drewdzzz** [comment]
If you don't like this soultion, I came up with another idea - we can simply disable ffi on M1.

File: src/box/lua/schema.lua [hunk 1]
```diff
@@ -2537,9 +2537,9 @@ base_index_mt.select_ffi = function(index, key, opts)
     check_select_safety(index, key_is_nil, iterator, limit, offset, fullscan)
     local region_svp = builtin.box_region_used()
     normalize_position(index, after, iterator_pos, iterator_pos_end)
-    nok = builtin.box_select(index.space_id, index.id, iterator, offset, limit,
-                             key, key_end, iterator_pos, iterator_pos_end,
-                             fetch_pos, port) ~= 0
+    nok = builtin.box_select_ffi(index.space_id, index.id, key, key_end,
```
Comment (locker) [inline src/box/lua/schema.lua:2540]: Is there a ticket for this? #7739? Should we re-enable LuaJIT fro the tests disabled in the scope of this issue?

https://github.com/tarantool/tarantool/blob/e02bc87feba73ce42e00719f1d40f2c0d363dc72/test/engine-luatest/pagination_test.lua#L10-L19

Should we file a ticket to revert this change once the LuaJIT issue is fixed and reference it in the code?

Anyway, I think that this fix should be reviewed by someone from the Lango team.

Comment (Gumix) [reply src/box/lua/schema.lua:2540]: No, #7739 is different. This workaround is for #7946

**Review by Gumix — COMMENTED** [review]
I can confirm that it fixes #7946 on Apple M1.

File: src/box/lua/schema.lua (hunk 1 above)
Comment (drewdzzz) [reply src/box/lua/schema.lua:2540]: This PR will close #7946

Comment (drewdzzz) [reply src/box/lua/schema.lua:2540]: > Anyway, I think that this fix should be reviewed by someone from the Lango team.

Requested a review from @igormunkin

File: extra/exports [hunk 2]
```diff
@@ -101,7 +101,7 @@ box_replace
 box_return_mp
 box_return_tuple
 box_schema_version
-box_select
```
Comment (Gumix) [inline extra/exports:104]: Shouldn't we keep the old version for compatibility?

Comment (locker) [reply extra/exports:104]: `box_select` isn't a part of the public API so I guess not.

Comment (Gumix) [reply extra/exports:104]: It is present here:
https://github.com/tarantool/tarantool/blob/ca58d6c92a10c4ab80f07425c51f20225e5611e8/static-build/test/exports.test.lua#L104-L119

Comment (locker) [reply extra/exports:104]: Maybe by mistake, but we need to check if it's actually used by any of our modules (e.g. tdg).

Comment (drewdzzz) [reply extra/exports:104]: We've changed `box_select` signature (added arguments for pagination), so the compatibility with old `box_select` is already broken.

Comment (drewdzzz) [reply extra/exports:104]: I've searched for its usage across `tarantool` organization - it is not used outside the core part.

File: src/box/lua/schema.lua (hunk 1 above)
Comment (igormunkin) [reply src/box/lua/schema.lua:2540]: > Should we re-enable LuaJIT fro the tests disabled in the scope of this issue?

JIT engine is unrelated for this case. But I wonder, whether we can run all M1 tests with JIT disabled... I'll check if there is nothing left related to JIT for M1 in the queue. All in all, one can just add `-e jit.off() jit.flush()` to the command launching the Tarantool.

> Should we file a ticket to revert this change once the LuaJIT issue is fixed and reference it in the code?

Up to you. Then there will be `N+1` M1-related tickets on GitHub. I have no idea when they are scheduled to RnD plans. Furthermore, I'd rather believe Mike Pall regarding the potential fix for this problem (without M1 ABI spec that is more verbose than [this one](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms)).

File: extra/exports (hunk 2 above)
Comment (igormunkin) [reply extra/exports:104]: Agree with @locker here.

**Review by igormunkin — APPROVED** [review]
@drewdzzz, thanks for the fix! LGTM.

**Comment by drewdzzz** [comment]
Fix static build test:
```diff
diff --git a/static-build/test/exports.test.lua b/static-build/test/exports.test.lua
index 0f6fef439..c503ab53d 100755
--- a/static-build/test/exports.test.lua
+++ b/static-build/test/exports.test.lua
@@ -81,6 +81,7 @@ local check_symbols = {
     'space_run_triggers',
     'space_bsize',
     'box_schema_version',
+    'box_select_ffi',

     'crypto_ERR_error_string',
     'crypto_ERR_get_error',
@@ -114,7 +115,6 @@ local check_symbols = {
     'coio_getaddrinfo',
     'luaT_call',
     'box_txn',
-    'box_select',
     'clock_realtime',
     'string_strip_helper',
```

File: extra/exports (hunk 2 above)
Comment (drewdzzz) [reply extra/exports:104]: AFAIK, `box_select` was in public API until it became to use `port`.

File: static-build/test/exports.test.lua [hunk 3]
```diff
@@ -81,6 +81,7 @@ local check_symbols = {
     'space_run_triggers',
     'space_bsize',
     'box_schema_version',
+    'box_select_ffi',
```
Comment (locker) [inline static-build/test/exports.test.lua:84]: This function isn't public so it shouldn't be checked. Please remove.

File: src/box/box.h [hunk 4]
```diff
@@ -372,6 +372,17 @@ box_select(uint32_t space_id, uint32_t index_id,
...
+ * A special wrapper for FFI - workaround for M1.
+ * Use 64-bit integers beyond the 8th argument.
+ * See https://github.com/LuaJIT/LuaJIT/issues/205 for details.
+ */
+int
+box_select_ffi(uint32_t space_id, uint32_t index_id, const char *key,
+	       const char *key_end, const char **packed_pos,
+	       const char **packed_pos_end, bool update_pos, struct port *port,
+	       int64_t iterator, uint64_t offset, uint64_t limit);
+
```
Comment (locker) [inline src/box/box.h:385]: There's no need to add a function declaration to the header if it'll only be used via Lua FFI. Please remove.

**Review by locker — CHANGES_REQUESTED** [review]

File: static-build/test/exports.test.lua (hunk 3 above)
Comment (drewdzzz) [reply static-build/test/exports.test.lua:84]: But there is plenty of function that aren't part of public API. I see that all symbols are checked, even ones that needed for FFI only.

File: src/box/box.h (hunk 4 above)
Comment (drewdzzz) [reply src/box/box.h]: Done
<details>
<summary> diff </summary>

```diff
diff --git a/src/box/box.cc b/src/box/box.cc
index 09ad27010..362b3df02 100644
--- a/src/box/box.cc
+++ b/src/box/box.cc
@@ -3075,7 +3075,12 @@ fail:
        return -1;
 }

-int
+/**
+ * A special wrapper for FFI - workaround for M1.
+ * Use 64-bit integers beyond the 8th argument.
+ * See https://github.com/LuaJIT/LuaJIT/issues/205 for details.
+ */
+extern "C" int
 box_select_ffi(uint32_t space_id, uint32_t index_id, const char *key,
               const char *key_end, const char **packed_pos,
               const char **packed_pos_end, bool update_pos, struct port *port,
diff --git a/src/box/box.h b/src/box/box.h
index 8d53aaba2..3661322c2 100644
--- a/src/box/box.h
+++ b/src/box/box.h
@@ -372,17 +372,6 @@ box_select(uint32_t space_id, uint32_t index_id,
           const char **packed_pos, const char **packed_pos_end,
           bool update_pos, struct port *port);

-/**
- * A special wrapper for FFI - workaround for M1.
- * Use 64-bit integers beyond the 8th argument.
- * See https://github.com/LuaJIT/LuaJIT/issues/205 for details.
- */
-int
-box_select_ffi(uint32_t space_id, uint32_t index_id, const char *key,
-              const char *key_end, const char **packed_pos,
-              const char **packed_pos_end, bool update_pos, struct port *port,
-              int64_t iterator, uint64_t offset, uint64_t limit);
-
 /** \cond public */

 /*
 ```
 
 </details>

File: static-build/test/exports.test.lua (hunk 3 above)
Comment (locker) [reply static-build/test/exports.test.lua:84]: I assume they're checked because they are used by some tdg modules (static build was initially imported from tarantool-enterprise). Apparently, `box_select_ffi` can't be used by any modules, and we don't want it to ever be used so we don't need to check it.

Comment (drewdzzz) [reply static-build/test/exports.test.lua]: OK, removed it

**Review by locker — APPROVED** [review]
