### PR TITLE
app: fix crash on logrotate and immediate exit

### LINKED ISSUE #4450: test: log_destroy() sometimes segfaults on app-tap/logger.test.lua
Tarantool version: 2.3.0-61-g5b9f207df
OS version: Gentoo Linux.

How to reproduce:

```sh
$ cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON && make -j
$ TEST_RUN_TESTS="$(yes app-tap/logger.test.lua | head -n 1000)" make test # several times
```

Backtrace:

```
(gdb) bt
#0  0x00007fe9392d9f1b in raise () from /lib64/libc.so.6
#1  0x00007fe9392c3535 in abort () from /lib64/libc.so.6
#2  0x0000560611c11ef7 in sig_fatal_cb (signo=11, siginfo=0x7fff252656f0, context=0x7fff252655c0) at /home/alex/p/tarantool-meta/r/t-2/src/main.cc:300
#3  <signal handler called>
#4  0x0000560611d52d13 in fiber_yield () at /home/alex/p/tarantool-meta/r/t-2/src/lib/core/fiber.c:478
#5  0x0000560611d52ed1 in fiber_yield_timeout (delay=3153600000) at /home/alex/p/tarantool-meta/r/t-2/src/lib/core/fiber.c:522
#6  0x0000560611d5b286 in fiber_cond_wait_timeout (c=0x5606122037a0 <log_std+96>, timeout=3153600000) at /home/alex/p/tarantool-meta/r/t-2/src/lib/core/fiber_cond.c:107
#7  0x0000560611d5b354 in fiber_cond_wait (c=0x5606122037a0 <log_std+96>) at /home/alex/p/tarantool-meta/r/t-2/src/lib/core/fiber_cond.c:117
#8  0x0000560611d50af4 in log_destroy (log=0x560612203740 <log_std>) at /home/alex/p/tarantool-meta/r/t-2/src/lib/core/say.c:1178
#9  0x0000560611d4e9d5 in say_logger_free () at /home/alex/p/tarantool-meta/r/t-2/src/lib/core/say.c:714
#10 0x0000560611c12fda in tarantool_free () at /home/alex/p/tarantool-meta/r/t-2/src/main.cc:639
#11 0x0000560611c138cd in main (argc=1, argv=0x560612859f18) at /home/alex/p/tarantool-meta/r/t-2/src/main.cc:864
```

### PR DESCRIPTION
**Pull request by nshy**
`say_logrotate` does not rotate logs synchronously. It posts tasks to
coio which executes them in it's pool thread. On application exit we
destroy logs calling `log_destroy`. This function waits for rotate task
to finish because if it will free resources immediately then unfinished
rotate task can have use-after-free issues. Waiting crashes because at
this moment event loop is not running which is required for
`fiber_cond_wait` to work.

Note that if there is no crash then we will hang forever waiting in
`log_destroy` because event loop is not running and
`log_rotate_async_cb` will never be executed.

Let's use mutexes and conditions instead. It solves both problems with
crash and hang. Thanks Vladimir Davydov for idea.

Fixes #4450

NO_DOC=bugfix

### CODE REVIEW

File: src/lib/core/coio_task.c [hunk 1]
```diff
@@ -150,11 +151,13 @@ coio_enable(void)
 	ev_async_init(&coio_manager.coio_async, coio_async_cb);
 
 	ev_async_start(loop(), &coio_manager.coio_async);
+	coio_is_running = true;
```
Comment (locker) [inline src/lib/core/coio_task.c:154]: `coio_enable` may be called from any thread, not just tx (note `coio_manager` is thread-local) so setting the global flag here is incorrect.

**Comment by locker** [comment]
Discussed f2f. It looks like we don't really need `fiber_cond` here: a `pthread_cond` would be enough, because we signal it rarely (on log rotate) and check it only on shutdown. Let's try to protect `rotating_threads` with a `pthread_mutex` and use a `pthread_cond` instead of `fiber_cond` to signal when it hits zero.

File: src/lib/core/coio_task.c (hunk 1 above)
Comment (nshy) [reply src/lib/core/coio_task.c:154]: Got rid of this flag in new version.

File: src/lib/core/say.c [hunk 2]
```diff
@@ -1252,8 +1252,10 @@ void
 log_destroy(struct log *log)
 {
 	assert(log != NULL);
-	while(log->rotating_threads > 0)
-		fiber_cond_wait(&log->rotate_cond);
+	if (coio_is_running) {
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/lib/core/say.c:1255]: Task is submitted before `coio_shutdown`. I just thought task can be not executed and we got a hang. Actually `eio` thread pool executes all tasks on shutdown.

File: src/lib/core/say.c [hunk 3]
```diff
@@ -342,10 +342,14 @@ static int
...
 {
 	struct rotate_task *task = (struct rotate_task *) ptr;
-	if (log_rotate(task->log) < 0) {
+	struct log *log = task->log;
+	if (log_rotate(log) < 0)
 		diag_log();
-	}
-	ev_async_send(task->loop, &task->log->log_async);
+	tt_pthread_mutex_lock(&log->mutex);
+	log->rotating_threads--;
```
Comment (locker) [inline src/lib/core/say.c:349]: Nit: It'd be nice to have an assertion here that `rotating_threads` never goes below 0.

File: src/lib/core/say.c [hunk 4]
```diff
@@ -1252,17 +1247,17 @@ void
...
+	tt_pthread_mutex_unlock(&log->mutex);
 	pm_atomic_store(&log->type, SAY_LOGGER_BOOT);
 
 	if (log->fd != -1)
 		close(log->fd);
 	free(log->syslog_ident);
 	free(log->path);
 	rlist_del_entry(log, in_log_list);
-	ev_async_stop(loop(), &log->log_async);
-	fiber_cond_destroy(&log->rotate_cond);
```
Comment (locker) [inline src/lib/core/say.c:1265]: You should destroy the mutex and the condition variable here.

File: src/lib/core/say.h [hunk 5]
```diff
@@ -171,17 +171,12 @@ struct log {
...
-	ev_async log_async;
-	/**
-	 * Conditional variable securing variable below
-	 * from concurrent usage.
-	 */
-	struct fiber_cond rotate_cond;
 	/** Counter identifying number of threads executing log_rotate. */
 	int rotating_threads;
+	/** Mutex for critical sections. */
+	pthread_mutex_t mutex;
```
Comment (locker) [inline src/lib/core/say.h:177]: Nit: Let's rename to `rotate_mutex` to match `rotate_cond` - after all it's used solely for log rotation. Also, please add a comment to `rotating_threads` that it's protected by this mutex.

**Review by locker — CHANGES_REQUESTED** [review]

File: src/lib/core/say.c (hunk 4 above)
Comment (nshy) [reply src/lib/core/say.c:1265]: Fixed.

File: src/lib/core/say.h (hunk 5 above)
Comment (nshy) [reply src/lib/core/say.h:177]: Done.

File: src/lib/core/say.h [hunk 6]
```diff
@@ -172,16 +172,14 @@ struct log {
 	/* Application identifier used to group syslog messages. */
 	char *syslog_ident;
 	/**
-	 * Used to wake up the main logger thread from a eio thread.
+	 * Counter identifying number of threads executing log_rotate.
+	 * Protected by @mutex as it is accessed from different threads.
```
Comment (locker) [inline src/lib/core/say.h:176]: Nit: `rotate_mutex`. Also, we don't usually use `@` to refer to variables and functions. Let's also elaborate the comment to `rotate_mutex` - "mutex for critical sections" sounds too vague.

Comment (nshy) [reply src/lib/core/say.h]: Done.

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
integration/tarantool-python failure is unrelated to this PR.

**Comment by locker** [comment]
Cherry-picked to 2.10.
