### PR TITLE
Fix false-positive ER_SPLIT_BRAIN after processing a DEMOTE request.

### LINKED ISSUE #7286: Adding replica makes Tarantool stuck after promote-demote
**Bug description**

Tarantool is stuck after trying to set fullmesh replication if instance was added after box.ctl.promote followed by box.ctl.demote.

* OS: Linux
* OS Version: nixos 21.11
* Architecture: amd64

Tarantool 2.11.0-entrypoint-138-g4e6969837
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/boris/dev/github/tarantool/tarantool/build/install -DENABLE_BACKTRACE=ON
Compiler: /nix/store/myjrqkb583ak29f3r5wmxrazy33i90pi-gcc-wrapper-10.3.0/bin/gcc /nix/store/myjrqkb583ak29f3r5wmxrazy33i90pi-gcc-wrapper-10.3.0/bin/g++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror

**Reproducer**

```lua
-- Step 1: Server 1
box.cfg{
  listen = 3301,
  replication = {
      '127.0.0.1:3301',
      '127.0.0.1:3302',
  },
}
box.once('schema', function()
   box.schema.user.grant('guest', 'super')
end)

-- Step 2: Server 2
box.cfg{
  listen = 3302,
  replication = {
      '127.0.0.1:3301',
      '127.0.0.1:3302',
  },
}

-- Step 3: Server 1
box.ctl.promote()
box.ctl.demote()

-- Step 4: Server 3
box.cfg{
  listen = 3303,
  replication = {
      '127.0.0.1:3302',
      '127.0.0.1:3303',
  },
}
```

Raises following error on Server 1
```log
2022-06-20 16:33:53.641 [1645394] main/111/applier/127.0.0.1:3302 applier.cc:1215 E> ER_SPLIT_BRAIN: Split-Brain discovered: got an async transaction from an old term
```

If after that I try to connect Server 1 to Server 3
```lua
-- Step 5: Server 1
box.cfg{
  replication = {
      '127.0.0.1:3301',
      '127.0.0.1:3302',
      '127.0.0.1:3303',
  },
}
```
Server 1 becomes unresponsive, endlessly trying to subscribe to Server 3 with following messages:
```log
2022-06-20 16:36:42.985 [1646680] main/127/applier/127.0.0.1:3303 I> subscribed
2022-06-20 16:36:42.985 [1646680] main/127/applier/127.0.0.1:3303 I> remote vclock {1: 5, 2: 1} local vclock {0: 2, 1: 5}
2022-06-20 16:36:42.986 [1646680] main/127/applier/127.0.0.1:3303 I> RAFT: message {term: 3, state: follower} from 3
2022-06-20 16:36:42.989 [1646680] main/127/applier/127.0.0.1:3303 I> can't read row
2022-06-20 16:36:42.989 [1646680] main/127/applier/127.0.0.1:3303 recovery.cc:212 E> XlogGapError: Missing .xlog file between LSN 6 {0: 1, 1: 5} and 6 {1: 5, 2: 1}
2022-06-20 16:36:42.989 [1646680] main/127/applier/127.0.0.1:3303 I> will retry every 1.00 second
```

Running following on server 3 after step 4, makes Server 3 stuck, Step 5 on server 1 behaves same way after.
```lua
-- Step 4.5: Server 3
box.cfg{
  replication = {
      '127.0.0.1:3301',
      '127.0.0.1:3302',
      '127.0.0.1:3303',
  },
}
```

**Actual behavior**
Tarantool is stuck.

**Expected behavior**
Tarantool isn't stuck. On tag 2.10.0 (2.10.0-0-g0a5ce0b9c) it works just fine.

### PR DESCRIPTION
**Pull request by sergepetrenko**
Our txn_limbo_is_replica_outdated check works correctly only when there
is a stream of PROMOTE requests. Only the author of the latest PROMOTE
is writable and may issue transactions. No matter synchronous or
asynchronous.

So txn_limbo_is_replica_outdated assumes that everyone but the node with
the greatest PROMOTE/DEMOTE term is outdated.

This isn't true for DEMOTE requests. There is only one server which
issues the DEMOTE request, but once it's written, it's fine to accept
asynchronous transactions from everyone.

Now the check is too strict. Every time there is an asynchronous
transaction from someone, who isn't the author of the latest PROMOTE or
DEMOTE, replication is broken with ER_SPLIT_BRAIN.

Let's relax it: when limbo owner is 0, it's fine to accept asynchronous
transactions from everyone, no matter the term of their latest PROMOTE
and DEMOTE.

This means that now after a DEMOTE we will miss one case of true
split-brain: when old leader continues writing data in an obsolete term,
and the new leader first issues PROMOTE and then DEMOTE.

This is a tradeoff for making async master-master work after DEMOTE.

The completely correct fix would be to write the term the transaction
was written in with each transaction and replace
txn_limbo_is_replica_outdated with txn_limbo_is_request_outdated, so
that we decide whether to filter the request or not judging by the term
it was applied in, not by the term we seen in some past PROMOTE from the
node. This fix seems too costy though, given that we only miss one case
of split-brain at the moment when the user enables master-master
replication (by writing a DEMOTE). And in master-master there is no such
thing as a split-brain.

Follow-up #5295
Closes #7286

### CODE REVIEW

File: src/box/txn_limbo.h [hunk 1]
```diff
@@ -280,6 +280,16 @@ txn_limbo_is_replica_outdated(struct txn_limbo *limbo, uint32_t replica_id)
 	return res;
 }
 
+/** Return id of the node owning the synchro queue. */
+static inline uint32_t
+txn_limbo_owner_id(struct txn_limbo *limbo)
+{
+	latch_lock(&limbo->promote_latch);
+	uint32_t owner_id = limbo->owner_id;
+	latch_unlock(&limbo->promote_latch);
```
Comment (Gerold103) [inline src/box/txn_limbo.h:289]: Why do you need the lock to get the owner?

File: src/box/txn_limbo.h [hunk 2]
```diff
@@ -280,6 +280,16 @@ txn_limbo_is_replica_outdated(struct txn_limbo *limbo, uint32_t replica_id)
...
+	return owner_id;
+}
+
```
Comment (Gerold103) [inline src/box/txn_limbo.h:292]: > The completely correct fix would be to write the term the transaction
was written in with each transaction and replace
txn_limbo_is_replica_outdated with txn_limbo_is_request_outdated, so
that we decide whether to filter the request or not judging by the term
it was applied in, not by the term we seen in some past PROMOTE from the
node. This fix seems too costy though, given that we only miss one case
of split-brain at the moment when the user enables master-master
replication (by writing a DEMOTE). And in master-master there is no such
thing as a split-brain.

Not sure I understand the problem. Writing term with each txn is the same as writing only term change event. You just 'compact' all duplicated term values. When you receive data from a replica, you always know whether it did apply the latest demote or not. Why doesn't it allow to reject the old leader? You know which replica applied which term last. And you know the term of demote - if your limbo owner == 0, then the demote term is `promote_greatest_term`. Hence if you got data from an old leader, you will rightfully reject it by `promote_greatest_term`. We update `promote_greatest_term` even for demotes.

There certainly should be a simpler explanation and a solution to what is happening in the ticket. Or do I miss something obvious?

File: src/box/txn_limbo.h (hunk 1 above)
Comment (sergepetrenko) [reply src/box/txn_limbo.h:289]: I don't need it right now.
Actually `txn_limbo_owner_id` is only called in `applier_synchro_filter_tx`, which doesn't yield after `txn_limbo_is_replica_outdated`.
And `txn_limbo_is_replica_outdated` already takes the lock, so we are fine even without taking the lock again.

But I think this is less error-prone to make owner_id getter take the lock right now.
This way we don't care if there are some new yields added to `applier_synchro_filter_tx` later.

Now, forget `applier_synchro_filter_tx`. Why would `txn_limbo_owner_id` need a lock at all? For the same reason `txn_limbo_is_replica_outdated` needs it. To be sure that there are no ongoing promotions/demotions. Otherwise some tx might pass the owner_id check while there's already a new PROMOTE being written.

File: src/box/txn_limbo.h (hunk 2 above)
Comment (sergepetrenko) [reply src/box/txn_limbo.h:292]: > When you receive data from a replica, you always know whether it did apply the latest demote or not.

That's exactly what I thought, but if I'm not confused here, that's not always true.

You see, in `promote_term_map` we only track terms of PROMOTE/DEMOTE **authored** by a specific node.

So, when you have 3 nodes, PROMOTE node 2 in term 1, PROMOTE node 3 in term 2, PROMOTE node 1 in term 3, `promote_term_map` will look like: `id_1: 3, id_2: 1, id_3: 2`. Even when nodes 2 and 3 receive PROMOTE from node 1 in term 3.
This is okay for filtering after promotions. Because we allow everyone to send us data authored by node 1 in term 3. As long as term 3 is the biggest term.
But this is not fine for demotions. After a DEMOTE node 1 term 4, everyone should be writeable, but `promote_term_map` will look like `id_1: 4, id_2: 1, id_3: 2`. So any data coming not from node1 will be considered malicious.

After understanding this, I thought we might track the biggest term **received** by the node, and not **authored** by it.
But this won't work: imagine node 1 writes DEMOTE node 1 term 4. How is it supposed to know that nodes 2 and 3 received this request? It will never see this request again, because it has already applied it. It will be filtered out by vclock.

So having once applied a PROMOTE/DEMOTE request, we will skip it in replication stream from everyone else. And AFAICS it's impossible to know which node applied which PROMOTE/DEMOTE.

Now you might say we may track PROMOTE/DEMOTE requests even before filtering them by vclock. But this won't work either: if both node 1 and node 2 applied some old PROMOTE long time ago, this PROMOTE won't be present in xlogs of either of them. Imagine node 2 stays in the term of that old PROMOTE and writes a lot of data in the old term. Since the PROMOTE isn't in xlogs anymore (they are already deleted), node1 knows nothing of the term the data is written in.

This all was fine for PROMOTE, because we always know who has done the latest promote and only apply his data. But this is not enough for demote. Because we need to know about every server whether it has applied the demote or not.

I fear my explanations are often a mess. So please let me know if we should discuss this verbally.

Do you want me to add some kind of explanation like this to the commit message?

Comment (Gerold103) [reply src/box/txn_limbo.h:292]: Thanks for the explanation, I see the problem now indeed. In that case the solution in the PR looks fine so far.
As for the proper solution - sure, term per txn would be better. But not perfect still. Because some bad node could emit the txn in the demoted term but before actually receiving the `DEMOTE` itself. It is possible? There is a gap between term bump and `DEMOTE` with that term, right?

The truly proper solution would be to solve this issue: be able to tell for each node its latest applied request type (`PROMOTE` or `DEMOTE`) *and* its term.

For that we could introduce `PROMOTE_ACK`(the name is a bit unfortunate though). Node could write it into WAL under its own vclock in the same WAL write batch as `PROMOTE`/`DEMOTE` (or not same batch - just in the same limbo txn then). It would be replicated and the other nodes would be able to tell whether this node tried to emit any transactions after knowing about demote or not. It allows not to write term per txn and still be able to tell which transaction from a given node was emitted in which term and whether it was after or before `PROMOTE`/`DEMOTE`.

`PROMOTE_ACK` would contain acked request type (`PROMOTE`/`DEMOTE`) and term. I tried to figure out whether we can just rely on vclock, but it is more complicated. By another node's vclock we can't tell how much did it progress in our own vclock component. We would need matrix clock for that, which is a huge overkill.

I also thought about doing it over piggybacking more info in applier acks or just sending new messages or reusing raft messages, but it wouldn't work for non-fullmesh (which should work fine even in some synchronous replication cases and definitely in all non-synchronous replication cases).

Wdyt about this? Might be complicated to do, so I am fine with the current patch as well.

File: src/box/txn_limbo.h (hunk 1 above)
Comment (Gerold103) [reply src/box/txn_limbo.h:289]: Yeah, I see now, thanks for the explanation. I keep forgetting stuff. My worry here is that we just take lock/unlock too often, I am afraid about the perf. Also what if indeed there would be a yield between the is-outdated check and the owner id get? Could the replica during the yield become non-outdated? - I worry about atomicity here. Maybe we could just inline `txn_limbo_is_replica_outdated` call here and get the owner id in the same lock as we took for getting the term? I am fine with the current solution too, for now it works good I suppose.

Comment (sergepetrenko) [reply src/box/txn_limbo.h]: > Also what if indeed there would be a yield between the is-outdated check and the owner id get? Could the replica during the yield become non-outdated? - I worry about atomicity here. 

I think this would be possible, indeed.

> Maybe we could just inline txn_limbo_is_replica_outdated call here and get the owner id in the same lock as we took for getting the term?

This is a good option IMO. Take a look (spread over one new and one existing commit):
```diff
diff --git a/src/box/applier.cc b/src/box/applier.cc
index ccac9098a..c842e44a8 100644
--- a/src/box/applier.cc
+++ b/src/box/applier.cc
@@ -1182,13 +1182,19 @@ apply_final_join_tx(uint32_t replica_id, struct stailq *rows)
 static void
 applier_synchro_filter_tx(struct stailq *rows)
 {
+	latch_lock(&txn_limbo.promote_latch);
+	auto guard = make_scoped_guard([] {
+		latch_unlock(&txn_limbo.promote_latch);
+	});
 	struct xrow_header *row;
 	/*
 	 * It  may happen that we receive the instance's rows via some third
 	 * node, so cannot check for applier->instance_id here.
 	 */
 	row = &stailq_first_entry(rows, struct applier_tx_row, next)->row;
-	if (!txn_limbo_is_replica_outdated(&txn_limbo, row->replica_id))
+	uint64_t term = txn_limbo_replica_term(&txn_limbo, row->replica_id);
+	assert(term <= txn_limbo.promote_greatest_term);
+	if (term == txn_limbo.promote_greatest_term)
 		return;
 
 	/*
@@ -1207,7 +1213,7 @@ applier_synchro_filter_tx(struct stailq *rows)
 		&stailq_last_entry(rows, struct applier_tx_row, next)->row;
 	if (!last_row->wait_sync) {
 		if (iproto_type_is_dml(last_row->type) &&
-		    txn_limbo_owner_id(&txn_limbo) != REPLICA_ID_NIL) {
+		    txn_limbo.owner_id != REPLICA_ID_NIL) {
 			tnt_raise(ClientError, ER_SPLIT_BRAIN,
 				  "got an async transaction from an old term");
 		}
diff --git a/src/box/txn_limbo.h b/src/box/txn_limbo.h
index 99b7e5df8..5fb858295 100644
--- a/src/box/txn_limbo.h
+++ b/src/box/txn_limbo.h
@@ -266,30 +266,6 @@ txn_limbo_replica_term(const struct txn_limbo *limbo, uint32_t replica_id)
 	return vclock_get(&limbo->promote_term_map, replica_id);
 }
 
-/**
- * Check whether replica with id @a source_id is too old to apply synchronous
- * data from it.
- */
-static inline bool
-txn_limbo_is_replica_outdated(struct txn_limbo *limbo, uint32_t replica_id)
-{
-	latch_lock(&limbo->promote_latch);
-	uint64_t v = vclock_get(&limbo->promote_term_map, replica_id);
-	bool res = v < limbo->promote_greatest_term;
-	latch_unlock(&limbo->promote_latch);
-	return res;
-}
-
-/** Return id of the node owning the synchro queue. */
-static inline uint32_t
-txn_limbo_owner_id(struct txn_limbo *limbo)
-{
-	latch_lock(&limbo->promote_latch);
-	uint32_t owner_id = limbo->owner_id;
-	latch_unlock(&limbo->promote_latch);
-	return owner_id;
-}
-
 /**
  * Return the last synchronous transaction in the limbo or NULL when it is
  * empty.

```

File: src/box/txn_limbo.h (hunk 2 above)
Comment (sergepetrenko) [reply src/box/txn_limbo.h]: > Because some bad node could emit the txn in the demoted term but before actually receiving the DEMOTE itself. It is possible? There is a gap between term bump and DEMOTE with that term, right?

Yes. We could sign requests with *limbo term* instead of the raft one, I guess.
This would cause problems too, I think. While a new PROMOTE is written to WAL, we should somehow set its term to all the new requests, shouldn't we?

Looks like `PROMOTE_ACK` would fix the issue, indeed. And we would always know which part of a node's journal belongs to which term. And I think it would be best to write PROMOTE_ACK in the same wal batch, as the PROMOTE/DEMOTE itself. Then we close the gap between PROMOTE and PROMOTE_ACK write. And if PROMOTE write fails it will automatically abort the PROMOTE_ACK write.

This "knowing the exact term of each request" seems important, and we might need this in the future if some not yet discovered bug arises. But TBH I don't want to do this know.

> I also thought about doing it over piggybacking more info in applier acks or just sending new messages or reusing raft messages

AFAICS you would only be able to see if the node has applied the latest PROMOTE/DEMOTE or not.
But you still won't know the term of the currently replicated request. It might come from some old term.

Comment (sergepetrenko) [reply src/box/txn_limbo.h]: > We could sign requests with limbo term instead of the raft one, I guess.

Would this work?

Comment (Gerold103) [reply src/box/txn_limbo.h]: Most likely it would. But I hope this is theoretical - adding a new field to each txn would be too expensive IMO.

**Review by Gerold103 — APPROVED** [review]
Thanks for the patch! In the future we might want to add `PROMOTE_ACK` record, but for now the patch will do the job.

**Comment by kyukhin** [comment]
Backported to 2.10.
