### PR TITLE
box: fix setting box error name

### LINKED ISSUE #10708: Error created with kv version of `box.error` has invalid name
**Bug description**

Tarantool sets the error name to `UNKNOWN` if an error is created via:
- C API `box_error_set` or `box_error_raise`.
- Lua API `box.error` or `box.error.new` using kv arguments.

Note that the public C API is also used internally, for example in `net.box`, so errors raised there lack a proper name, as well.

Reproduced with Tarantool 3.3.0-entrypoint-160-g11145f6a82b1.
The bug was there when the error names first appeared in 3.1.0-entrypoint-236-g2bf957922484.

**Steps to reproduce**

```
tarantool> box.error.new(box.error.NO_CONNECTION):unpack()
---
- name: NO_CONNECTION
  code: 77
  base_type: ClientError
  type: ClientError
  message: Connection is not established
  trace:
  - file: '[string "return box.error.new(box.error.NO_CONNECTION)..."]'
    line: 1
...

tarantool> box.error.new{code = box.error.NO_CONNECTION}:unpack()
---
- name: UNKNOWN
  code: 77
  base_type: ClientError
  type: ClientError
  message: Connection is not established
  trace:
  - file: '[string "return box.error.new{code = box.error.NO_CONN..."]'
    line: 1
...
```

### PR DESCRIPTION
**Pull request by nshy**
Currently we fail to set box error name is some cases. Error name is error payload with key `name`.

Closes #10708

### CODE REVIEW

File: src/box/error.cc [hunk 1]
```diff
@@ -80,6 +80,7 @@ box_error_set(const char *file, unsigned line, uint32_t code,
 	struct error *e = BuildClientError(file, line, ER_UNKNOWN);
 	ClientError *client_error = type_cast(ClientError, e);
 	client_error->code = code;
+	client_error->set_name();
```
Comment (locker) [inline src/box/error.cc]: I don't like this new method. Why can't we use the proper `ClientError` constructor instead?

Comment (nshy) [reply src/box/error.cc]: Done. I also find a chance to cleanup errors even more so diff has grown big. Now the bug is fixed basically due to refactoring, so I squashed changes into the single commit.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/error.cc b/src/box/error.cc
index 6489d42fb8..91ab65ac52 100644
--- a/src/box/error.cc
+++ b/src/box/error.cc
@@ -73,41 +73,30 @@ box_error_clear(void)
 	diag_clear(&fiber()->diag);
 }
 
+static struct error *
+box_error_new_va(const char *file, unsigned line, uint32_t code,
+		 const char *custom_type, const char *fmt, va_list ap)
+{
+	if (custom_type != NULL)
+		return new CustomError(file, line, custom_type, code, fmt, ap);
+	else if (code == ER_ILLEGAL_PARAMS)
+		return new IllegalParams(file, line, fmt, ap);
+	else
+		return new ClientError(file, line, code, fmt, ap);
+}
+
 int
 box_error_set(const char *file, unsigned line, uint32_t code,
-		const char *fmt, ...)
+	      const char *fmt, ...)
 {
-	struct error *e = BuildClientError(file, line, ER_UNKNOWN);
-	ClientError *client_error = type_cast(ClientError, e);
-	client_error->code = code;
-	client_error->set_name();
 	va_list ap;
 	va_start(ap, fmt);
-	error_vformat_msg(e, fmt, ap);
+	struct error *e = box_error_new_va(file, line, code, NULL, fmt, ap);
 	va_end(ap);
 	diag_set_error(&fiber()->diag, e);
 	return -1;
 }
 
-static struct error *
-box_error_new_va(const char *file, unsigned line, uint32_t code,
-		 const char *custom_type, const char *fmt, va_list ap)
-{
-	struct error *e;
-	if (custom_type != NULL) {
-		e = BuildCustomError(file, line, custom_type, code);
-	} else if (code == ER_ILLEGAL_PARAMS) {
-		e = BuildIllegalParams(file, line, "");
-	} else {
-		e = BuildClientError(file, line, ER_UNKNOWN);
-		ClientError *client_error = type_cast(ClientError, e);
-		client_error->code = code;
-		client_error->set_name();
-	}
-	error_vformat_msg(e, fmt, ap);
-	return e;
-}
-
 struct error *
 box_error_new(const char *file, unsigned line, uint32_t code,
 	      const char *custom_type, const char *fmt, ...)
@@ -158,9 +147,15 @@ const char *rmean_error_strings[RMEAN_ERROR_LAST] = {
 
 /** Format client error with arguments in `ap` according to error format. */
 static void
-client_error_create(struct error *e, va_list ap)
+client_error_create(struct error *e, const char *fmt, va_list ap)
 {
 	const struct errcode_record *r = tnt_errcode_record(e->code);
+	assert(strncmp("ER_", r->errstr, 3) == 0);
+	error_set_str(e, "name", r->errstr + 3);
+	if (fmt != NULL) {
+		error_vformat_msg(e, fmt, ap);
+		return;
+	}
 	va_list ap_copy;
 	va_copy(ap_copy, ap);
 	error_vformat_msg(e, r->errdesc, ap_copy);
@@ -255,18 +250,15 @@ ClientError::ClientError(const type_info *type, const char *file, unsigned line,
 
 ClientError::ClientError(const char *file, unsigned line, uint32_t errcode,
 			 va_list ap)
-	:ClientError(&type_ClientError, file, line, errcode)
+	:ClientError(file, line, errcode, /*fmt=*/NULL, ap)
 {
-	client_error_create(this, ap);
-	set_name();
 }
 
-void
-ClientError::set_name()
+ClientError::ClientError(const char *file, unsigned line, uint32_t errcode,
+			 const char *fmt, va_list ap)
+	:ClientError(&type_ClientError, file, line, errcode)
 {
-	const struct errcode_record *r = tnt_errcode_record(code);
-	assert(strncmp("ER_", r->errstr, 3) == 0);
-	error_set_str(this, "name", r->errstr + 3);
+	client_error_create(this, fmt, ap);
 }
 
 struct error *
@@ -393,9 +385,11 @@ const struct type_info type_CustomError =
 	make_type("CustomError", &type_ClientError);
 
 CustomError::CustomError(const char *file, unsigned int line,
-			 const char *custom_type, uint32_t errcode)
+			 const char *custom_type, uint32_t errcode,
+			 const char *fmt, va_list ap)
 	:ClientError(&type_CustomError, file, line, errcode)
 {
+	error_vformat_msg(this, fmt, ap);
 	error_set_str(this, "custom_type", custom_type);
 }
 
@@ -408,7 +402,12 @@ CustomError::log() const
 
 struct error *
 BuildCustomError(const char *file, unsigned int line, const char *custom_type,
-		 uint32_t errcode)
+		 uint32_t errcode, const char *format, ...)
 {
-	return new CustomError(file, line, custom_type, errcode);
+	va_list ap;
+	va_start(ap, format);
+	CustomError *e = new CustomError(file, line, custom_type, errcode,
+					 format, ap);
+	va_end(ap);
+	return e;
 }
diff --git a/src/box/error.h b/src/box/error.h
index d5c1d8b49c..feeb7acaf7 100644
--- a/src/box/error.h
+++ b/src/box/error.h
@@ -55,7 +55,7 @@ BuildXlogGapError(const char *file, unsigned line,
 
 struct error *
 BuildCustomError(const char *file, unsigned int line, const char *custom_type,
-		 uint32_t errcode);
+		 uint32_t errcode, const char *format, ...);
 
 /** \cond public */
 
@@ -235,12 +235,10 @@ class ClientError: public Exception
 		return code;
 	}
 
-	/** Set error name. It is available as error payload with key `name'. */
-	void
-	set_name();
-
 	ClientError(const char *file, unsigned line, uint32_t errcode,
 		    va_list ap);
+	ClientError(const char *file, unsigned line, uint32_t errcode,
+		    const char *fmt, va_list ap);
 
 	ClientError()
 		:Exception(&type_ClientError, NULL, 0)
@@ -335,7 +333,8 @@ class CustomError: public ClientError
 {
 public:
 	CustomError(const char *file, unsigned int line,
-		    const char *custom_type, uint32_t errcode);
+		    const char *custom_type, uint32_t errcode, const char *fmt,
+		    va_list ap);
 
 	CustomError()
 		:ClientError(&type_CustomError, NULL, 0, 0)
diff --git a/src/lib/core/exception.cc b/src/lib/core/exception.cc
index 61c5f1701a..e422350cdd 100644
--- a/src/lib/core/exception.cc
+++ b/src/lib/core/exception.cc
@@ -125,14 +125,11 @@ SystemError::SystemError(const struct type_info *type,
 	saved_errno = errno;
 }
 
-SystemError::SystemError(const char *file, unsigned line,
-			 const char *format, ...)
-	: SystemError(&type_SystemError, file, line)
+SystemError::SystemError(const char *file, unsigned line, const char *format,
+			 va_list ap)
+	:SystemError(&type_SystemError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
 	error_vformat_msg(this, format, ap);
-	va_end(ap);
 	error_append_msg(this, ": %s", tt_strerror(saved_errno));
 }
 
@@ -140,14 +137,10 @@ const struct type_info type_SocketError =
 	make_type("SocketError", &type_SystemError);
 
 SocketError::SocketError(const char *file, unsigned line,
-			 const char *socketname,
-			 const char *format, ...)
+			 const char *socketname, const char *format, va_list ap)
 	: SystemError(&type_SocketError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
 	error_vformat_msg(this, format, ap);
-	va_end(ap);
 	error_append_msg(this, ", called on %s: %s", socketname,
 			 tt_strerror(saved_errno));
 }
@@ -225,101 +218,83 @@ const struct type_info type_IllegalParams =
 	make_type("IllegalParams", &type_Exception);
 
 IllegalParams::IllegalParams(const char *file, unsigned line,
-				     const char *format, ...)
+			     const char *format, va_list ap)
 	: Exception(&type_IllegalParams, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
 	error_vformat_msg(this, format, ap);
-	va_end(ap);
 }
 
 const struct type_info type_CollationError =
 	make_type("CollationError", &type_Exception);
 
 CollationError::CollationError(const char *file, unsigned line,
-			       const char *format, ...)
+			       const char *format, va_list ap)
 	: Exception(&type_CollationError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
 	error_vformat_msg(this, format, ap);
-	va_end(ap);
 }
 
 const struct type_info type_SwimError = make_type("SwimError", &type_Exception);
 
-SwimError::SwimError(const char *file, unsigned line, const char *format, ...)
+SwimError::SwimError(const char *file, unsigned line, const char *format,
+		     va_list ap)
 	: Exception(&type_SwimError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
 	error_vformat_msg(this, format, ap);
-	va_end(ap);
 }
 
 const struct type_info type_CryptoError =
 	make_type("CryptoError", &type_Exception);
 
-CryptoError::CryptoError(const char *file, unsigned line,
-			 const char *format, ...)
+CryptoError::CryptoError(const char *file, unsigned line, const char *format,
+			 va_list ap)
 	: Exception(&type_CryptoError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
 	error_vformat_msg(this, format, ap);
-	va_end(ap);
 }
 
 const struct type_info type_RaftError =
 	make_type("RaftError", &type_Exception);
 
-RaftError::RaftError(const char *file, unsigned line, const char *format, ...)
+RaftError::RaftError(const char *file, unsigned line, const char *format,
+		     va_list ap)
 	: Exception(&type_RaftError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
 	error_vformat_msg(this, format, ap);
-	va_end(ap);
 }
 
 const struct type_info type_FileFormatError =
 	make_type("FileFormatError", &type_Exception);
 
 FileFormatError::FileFormatError(const char *file, unsigned line,
-				 const char *format, ...)
+				 const char *format, va_list ap)
 	: Exception(&type_FileFormatError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
 	error_vformat_msg(this, format, ap);
-	va_end(ap);
 }
 
 const struct type_info type_EncodeError =
 	make_type("EncodeError", &type_Exception);
 
 EncodeError::EncodeError(const char *file, unsigned line, const char *format,
-			 ...)
+			 const char *details)
 	: Exception(&type_EncodeError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
-	error_vformat_msg(this, format, ap);
-	va_end(ap);
+	error_format_msg(this, "%s encode error: %s", format, details);
+	error_set_str(this, "format", format);
+	error_set_str(this, "details", details);
 }
 
 const struct type_info type_DecodeError =
 	make_type("DecodeError", &type_Exception);
 
 DecodeError::DecodeError(const char *file, unsigned line, const char *format,
-			 ...)
+			 const char *details)
 	: Exception(&type_DecodeError, file, line)
 {
-	va_list ap;
-	va_start(ap, format);
-	error_vformat_msg(this, format, ap);
-	va_end(ap);
+	error_format_msg(this, "%s decode error: %s", format, details);
+	error_set_str(this, "format", format);
+	error_set_str(this, "details", details);
 }
 
 struct error *
@@ -363,10 +338,9 @@ BuildLuajitError(const char *file, unsigned line, const char *msg)
 struct error *
 BuildIllegalParams(const char *file, unsigned line, const char *format, ...)
 {
-	IllegalParams *e = new IllegalParams(file, line, "");
 	va_list ap;
 	va_start(ap, format);
-	error_vformat_msg(e, format, ap);
+	IllegalParams *e = new IllegalParams(file, line, format, ap);
 	va_end(ap);
 	return e;
 }
@@ -374,22 +348,19 @@ BuildIllegalParams(const char *file, unsigned line, const char *format, ...)
 struct error *
 BuildSystemError(const char *file, unsigned line, const char *format, ...)
 {
-	SystemError *e = new SystemError(file, line, "");
 	va_list ap;
 	va_start(ap, format);
-	error_vformat_msg(e, format, ap);
+	SystemError *e = new SystemError(file, line, format, ap);
 	va_end(ap);
-	error_append_msg(e, ": %s", tt_strerror(e->saved_errno));
 	return e;
 }
 
 struct error *
 BuildCollationError(const char *file, unsigned line, const char *format, ...)
 {
-	CollationError *e = new CollationError(file, line, "");
 	va_list ap;
 	va_start(ap, format);
-	error_vformat_msg(e, format, ap);
+	CollationError *e = new CollationError(file, line, format, ap);
 	va_end(ap);
 	return e;
 }
@@ -397,10 +368,9 @@ BuildCollationError(const char *file, unsigned line, const char *format, ...)
 struct error *
 BuildSwimError(const char *file, unsigned line, const char *format, ...)
 {
-	SwimError *e = new SwimError(file, line, "");
 	va_list ap;
 	va_start(ap, format);
-	error_vformat_msg(e, format, ap);
+	SwimError *e = new SwimError(file, line, format, ap);
 	va_end(ap);
 	return e;
 }
@@ -408,10 +378,9 @@ BuildSwimError(const char *file, unsigned line, const char *format, ...)
 struct error *
 BuildCryptoError(const char *file, unsigned line, const char *format, ...)
 {
-	CryptoError *e = new CryptoError(file, line, "");
 	va_list ap;
 	va_start(ap, format);
-	error_vformat_msg(e, format, ap);
+	CryptoError *e = new CryptoError(file, line, format, ap);
 	va_end(ap);
 	return e;
 }
@@ -420,23 +389,19 @@ struct error *
 BuildSocketError(const char *file, unsigned line, const char *socketname,
 		 const char *format, ...)
 {
-	SocketError *e = new SocketError(file, line, socketname, "");
 	va_list ap;
 	va_start(ap, format);
-	error_vformat_msg(e, format, ap);
+	SocketError *e = new SocketError(file, line, socketname, format, ap);
 	va_end(ap);
-	error_append_msg(e, ", called on %s: %s", socketname,
-			 tt_strerror(e->saved_errno));
 	return e;
 }
 
 struct error *
 BuildRaftError(const char *file, unsigned line, const char *format, ...)
 {
-	RaftError *e = new RaftError(file, line, "");
 	va_list ap;
 	va_start(ap, format);
-	error_vformat_msg(e, format, ap);
+	RaftError *e = new RaftError(file, line, format, ap);
 	va_end(ap);
 	return e;
 }
@@ -444,10 +409,9 @@ BuildRaftError(const char *file, unsigned line, const char *format, ...)
 struct error *
 BuildFileFormatError(const char *file, unsigned line, const char *format, ...)
 {
-	FileFormatError *e = new FileFormatError(file, line, "");
 	va_list ap;
 	va_start(ap, format);
-	error_vformat_msg(e, format, ap);
+	FileFormatError *e = new FileFormatError(file, line, format, ap);
 	va_end(ap);
 	return e;
 }
@@ -456,20 +420,12 @@ struct error *
 BuildEncodeError(const char *file, unsigned line, const char *format,
 		 const char *details)
 {
-	EncodeError *e = new EncodeError(file, line, "%s encode error: %s",
-					 format, details);
-	error_payload_set_str(&e->payload, "format", format);
-	error_payload_set_str(&e->payload, "details", details);
-	return e;
+	return new EncodeError(file, line, format, details);
 }
 
 struct error *
 BuildDecodeError(const char *file, unsigned line, const char *format,
 		 const char *details)
 {
-	DecodeError *e = new DecodeError(file, line, "%s decode error: %s",
-					 format, details);
-	error_payload_set_str(&e->payload, "format", format);
-	error_payload_set_str(&e->payload, "details", details);
-	return e;
+	return new DecodeError(file, line, format, details);
 }
diff --git a/src/lib/core/exception.h b/src/lib/core/exception.h
index f62146cf49..4adab1e099 100644
--- a/src/lib/core/exception.h
+++ b/src/lib/core/exception.h
@@ -95,8 +95,8 @@ class SystemError: public Exception {
 public:
 	virtual void raise() { throw this; }
 
-	SystemError(const char *file, unsigned line,
-		    const char *format, ...);
+	SystemError(const char *file, unsigned line, const char *format,
+		    va_list ap);
 
 	SystemError()
 		:Exception(&type_SystemError, NULL, 0)
@@ -104,14 +104,15 @@ class SystemError: public Exception {
 	}
 
 protected:
-	SystemError(const struct type_info *type, const char *file, unsigned line);
+	SystemError(const struct type_info *type, const char *file,
+		    unsigned line);
 };
 
 extern const struct type_info type_SocketError;
 class SocketError: public SystemError {
 public:
 	SocketError(const char *file, unsigned line, const char *socketname,
-		    const char *format, ...);
+		    const char *format, va_list ap);
 
 	SocketError()
 		:SystemError(&type_SocketError, NULL, 0)
@@ -210,7 +211,8 @@ class LuajitError: public Exception {
 
 class IllegalParams: public Exception {
 public:
-	IllegalParams(const char *file, unsigned line, const char *format, ...);
+	IllegalParams(const char *file, unsigned line, const char *format,
+		      va_list ap);
 
 	IllegalParams()
 		:Exception(&type_IllegalParams, NULL, 0)
@@ -223,7 +225,7 @@ class IllegalParams: public Exception {
 class CollationError: public Exception {
 public:
 	CollationError(const char *file, unsigned line, const char *format,
-		       ...);
+		       va_list ap);
 
 	CollationError()
 		:Exception(&type_CollationError, NULL, 0)
@@ -235,7 +237,8 @@ class CollationError: public Exception {
 
 class SwimError: public Exception {
 public:
-	SwimError(const char *file, unsigned line, const char *format, ...);
+	SwimError(const char *file, unsigned line, const char *format,
+		  va_list ap);
 
 	SwimError()
 		:Exception(&type_SwimError, NULL, 0)
@@ -247,7 +250,8 @@ class SwimError: public Exception {
 
 class CryptoError: public Exception {
 public:
-	CryptoError(const char *file, unsigned line, const char *format, ...);
+	CryptoError(const char *file, unsigned line, const char *format,
+		    va_list ap);
 
 	CryptoError()
 		:Exception(&type_CryptoError, NULL, 0)
@@ -259,41 +263,48 @@ class CryptoError: public Exception {
 
 class RaftError: public Exception {
 public:
-	RaftError(const char *file, unsigned line, const char *format, ...);
+	RaftError(const char *file, unsigned line, const char *format,
+		  va_list ap);
+
 	virtual void raise() { throw this; }
 };
 
 class FileFormatError: public Exception {
 public:
-	FileFormatError(const char *file, unsigned line,
-			const char *format, ...);
+	FileFormatError(const char *file, unsigned line, const char *format,
+			va_list ap);
 
 	FileFormatError()
 		: Exception(&type_FileFormatError, NULL, 0)
 	{
 	}
+
 	virtual void raise() { throw this; }
 };
 
 class EncodeError: public Exception {
 public:
-	EncodeError(const char *file, unsigned line, const char *format, ...);
+	EncodeError(const char *file, unsigned line, const char *format,
+		    const char *details);
 
 	EncodeError()
 		: Exception(&type_EncodeError, NULL, 0)
 	{
 	}
+
 	virtual void raise() { throw this; }
 };
 
 class DecodeError: public Exception {
 public:
-	DecodeError(const char *file, unsigned line, const char *format, ...);
+	DecodeError(const char *file, unsigned line, const char *format,
+		    const char *details);
 
 	DecodeError()
 		: Exception(&type_DecodeError, NULL, 0)
 	{
 	}
+
 	virtual void raise() { throw this; }
 };
 
diff --git a/test/unit/error.c b/test/unit/error.c
index 7405cc1365..fe21242b45 100644
--- a/test/unit/error.c
+++ b/test/unit/error.c
@@ -580,11 +580,11 @@ test_pthread_f(void *arg)
 {
 	(void)arg;
 	is(box_error_last(), NULL, "last error before set");
-	box_error_raise(ER_ILLEGAL_PARAMS, "Test %d", 42);
+	box_error_raise(ER_UNSUPPORTED, "Test %d", 42);
 	box_error_t *err = box_error_last();
 	isnt(err, NULL, "last error after set");
 	is(strcmp(box_error_type(err), "ClientError"), 0, "last error type");
-	is(box_error_code(err), ER_ILLEGAL_PARAMS, "last error code");
+	is(box_error_code(err), ER_UNSUPPORTED, "last error code");
 	is(strcmp(box_error_message(err), "Test 42"), 0, "last error message");
 	box_error_clear();
 	is(box_error_last(), NULL, "last error after clear");
diff --git a/test/unit/mp_error.cc b/test/unit/mp_error.cc
index 1987ce0cf5..65195a16aa 100644
--- a/test/unit/mp_error.cc
+++ b/test/unit/mp_error.cc
@@ -624,7 +624,7 @@ test_mp_print(void)
 
 	struct error *e1 = BuildClientError("file1", 1, 0);
 	error_ref(e1);
-	struct error *e2 = BuildCustomError("file2", 4, "type", 5);
+	struct error *e2 = BuildCustomError("file2", 4, "type", 5, "");
 	struct error *e3 = BuildAccessDeniedError("file3", 6, "field1",
 						  "field2", "field3", "field4");
 	error_set_prev(e1, e2);
```

</details>

File: src/box/error.cc [hunk 2]
```diff
@@ -156,9 +148,15 @@ const char *rmean_error_strings[RMEAN_ERROR_LAST] = {
 
 /** Format client error with arguments in `ap` according to error format. */
 static void
-client_error_create(struct error *e, va_list ap)
+client_error_create(struct error *e, const char *fmt, va_list ap)
```
Comment (locker) [inline src/box/error.cc]: This function isn't required anymore and could be inlined into the `ClientError` constructor.

**Review by locker — APPROVED** [review]

File: changelogs/unreleased/gh-10708-fix-setting-error-name.md [hunk 3]
```diff
@@ -0,0 +1,3 @@
+## bugfix/box
+
+* Fixed a bug of missed setting box error name is some cases (gh-10708).
```
Comment (maryiaLichko) [inline changelogs/unreleased/gh-10708-fix-setting-error-name.md]:
```suggestion
* Fixed a bug of missed setting box error name in some cases (gh-10708).
```

**Review by maryiaLichko — APPROVED** [review]

File: changelogs/unreleased/gh-10708-fix-setting-error-name.md (hunk 3 above)
Comment (nshy) [reply changelogs/unreleased/gh-10708-fix-setting-error-name.md]: Thanx! Fixed.

File: src/box/error.cc (hunk 2 above)
Comment (nshy) [reply src/box/error.cc]: Done.

**Comment by nshy** [comment]
The PR depends on https://github.com/tarantool/tarantool/pull/11716 it terms of backporting.

**Comment by nshy** [comment]
Rebased on master.

**Comment by locker** [comment]
@nshy Please backport to 3.2, 3.3, and 3.4.
