### PR TITLE
box/lua: don't crash on `box.internal.tuple_format.new()` misuse

### LINKED ISSUE #10529: lbox_tuple_format_new: Assertion `(1 <= top && 2 >= top) && lua_istable(L, 1)' failed.
```
Tarantool 3.3.0-entrypoint-45-g2478f54ba4
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-14.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/git/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/git/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
```

How to reproduce:
```
$ tarantool -e "box.internal.tuple_format.new()"

tarantool: ./src/box/lua/tuple_format.c:62: lbox_tuple_format_new: Assertion `(1 <= top && 2 >= top) && lua_istable(L, 1)' failed.
zsh: IOT instruction (core dumped)
```

### PR DESCRIPTION
**Pull request by Gumix**
Even though `box.internal.tuple_format.new()` is an internal function, it is quite easy to call it from the console using auto completion and to crash Tarantool. Let's replace the assertion with an error.

Closes #10529

### CODE REVIEW

File: test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua [hunk 1]
```diff
@@ -37,6 +37,18 @@ g.test_box_tuple_format_new = function()
     end)
 end
 
+-- Checks that improper use of `box.internal.tuple_format.new` doesn't crash.
+g.test_box_internal_tuple_format_new = function(cg)
+    cg.server:exec(function()
+        t.assert_error_msg_content_equals(
+            "format should be a table",
+            function() box.internal.tuple_format.new() end)
```
Comment (nshy) [inline test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua:45]: We don't need wrappers with error assertions, we can just pass function and its arguments.

File: src/box/lua/tuple_format.c [hunk 2]
```diff
@@ -57,9 +57,8 @@ lbox_tuple_format_gc(struct lua_State *L)
 static int
 lbox_tuple_format_new(struct lua_State *L)
 {
-	int top = lua_gettop(L);
-	(void)top;
-	assert((1 <= top && 2 >= top) && lua_istable(L, 1));
+	if (!lua_istable(L, 1))
+		return luaL_error(L, "format should be a table");
```
Comment (nshy) [inline src/box/lua/tuple_format.c:61]: Event this should not be triggered normally we now use box error instead of Lua. I suggest to introduce `luaT_checktable` (see `luaT_checklstring` for example) and use it. In this case we can use `assert_error_msg_equals` for assertions in the test.

**Review by nshy — CHANGES_REQUESTED** [review]

File: test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua (hunk 1 above)
Comment (Gumix) [reply test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua]: Removed.

File: src/box/lua/tuple_format.c (hunk 2 above)
Comment (Gumix) [reply src/box/lua/tuple_format.c]: Changed to `luaT_checktype(L, 1, LUA_TTABLE);`.

File: src/box/lua/tuple_format.c [hunk 3]
```diff
@@ -57,9 +57,7 @@ lbox_tuple_format_gc(struct lua_State *L)
 static int
 lbox_tuple_format_new(struct lua_State *L)
 {
-	int top = lua_gettop(L);
-	(void)top;
-	assert((1 <= top && 2 >= top) && lua_istable(L, 1));
+	luaT_checktype(L, 1, LUA_TTABLE);
```
Comment (olegrok) [inline src/box/lua/tuple_format.c:60]: Don't you plan to fix other assertion failures here?
```
box.internal.tuple_format.new({type = 'test'})
Assertion failed: (mp_typeof(**data) == MP_ARRAY), function field_def_array_decode, file field_def.c, line 584.
```

Comment (Gumix) [reply src/box/lua/tuple_format.c:60]: Thanks, missed it.

File: test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua [hunk 4]
```diff
@@ -37,6 +37,21 @@ g.test_box_tuple_format_new = function()
...
+            box.internal.tuple_format.new)
+        t.assert_error_msg_equals(
+            "expected table as 1 argument",
+            box.internal.tuple_format.new, 1984)
+        t.assert_error_msg_equals(
+            "Wrong space format",
+            box.internal.tuple_format.new, {type = 'test'})
+    end)
+end
+
```
Comment (nshy) [inline test/box-luatest/gh_4693_formats_for_standalone_tuples_test.lua:54]: It still can be easily crashed. 

```lua
tarantool> box.internal.tuple_format.new({constraint = 1})
tarantool: ./src/box/field_def.c:584: field_def_array_decode: Assertion `mp_typeof(**data) == MP_ARRAY' failed.
Aborted (core dumped)
```

I thought we can hide it like this:

```diff
@@ -2,12 +2,15 @@ local utils = require('internal.utils')

 local internal = box.internal

+local tuple_format_new = box.internal.tuple_format.new
+box.internal.tuple_format.new = nil
+
 -- new() needs a wrapper in Lua, because format normalization needs to be done
 -- in Lua.
 box.tuple.format.new = function(format)
     utils.check_param(format, 'format', 'table')
     format = box.internal.space.normalize_format(nil, nil, format, 2)
-    return box.internal.tuple_format.new(format)
+    return tuple_format_new(format)
 end
```

But unfortunately this function is used from other Lua modules/tests. Also I guess we have a lot of issues of this kind with other internal functions. If the issue we can easily can get this function in auto-completion - may be we'd better to disable auto-completion for `box.internal`. Let's ask also @locker opinion on the topic.

File: src/box/lua/tuple_format.c (hunk 3 above)
Comment (nshy) [inline src/box/lua/tuple_format.c:60]: This is covered by the next check. We can drop it.

File: src/box/lua/tuple_format.c [hunk 5]
```diff
@@ -72,6 +70,11 @@ lbox_tuple_format_new(struct lua_State *L)
 	mpstream_flush(&stream);
 	size_t format_data_len = region_used(region) - region_svp;
 	const char *format_data = xregion_join(region, format_data_len);
+	if (mp_typeof(*format_data) != MP_ARRAY) {
+		diag_set(IllegalParams, "Wrong space format");
```
Comment (nshy) [inline src/box/lua/tuple_format.c:74]: I guess error message should be more specific. Like "format should be an array"

**Review by nshy — CHANGES_REQUESTED** [review]
Not sure if this

File: src/box/lua/tuple_format.c (hunk 3 above)
Comment (Gumix) [reply src/box/lua/tuple_format.c]: Removed.

File: src/box/lua/tuple_format.c (hunk 5 above)
Comment (Gumix) [reply src/box/lua/tuple_format.c]: Changed to "Wrong space format: expected array".

**Review by nshy — APPROVED** [review]

**Review by sergepetrenko — APPROVED** [review]
Thanks for the fix!
LGTM.

**Comment by sergepetrenko** [comment]
Backport to 3.2: https://github.com/tarantool/tarantool/pull/10744
