### PR TITLE
config: expand config:info()

### LINKED ISSUE #9780: Show meta of active configuration
The meta is currently displayed for the last configuration load, even if was the failed reload. It would be helpful to show the meta for the active configuration as well.

### PR DESCRIPTION
**Pull request by ImeevMA**
Closes #9780

@TarantoolBot document
Title: Expansion of `config:info()`

Before this patch, the `meta` field of the `config:info()` function contained the meta data of the last load, even if it was unsuccessful reload. This can be inconvenient because if the reload fails, we expect that the last configuration that was successfully applied is used, but its metadata was lost.

Now `config:info()` can take one argument — the version of the information that should be returned by the function. If no arguments are specified or the argument is the string `v1`, the return value has the same structure as before. If the argument is the string `v2`, the `meta` field in the return value has fields - `active` (meta for the last successfully applied configuration) and `last` (meta of the last loaded configuration). Currently only these values are accepted.

### CODE REVIEW

File: src/box/lua/config/init.lua [hunk 1]
```diff
@@ -450,6 +453,9 @@ function methods._reload_noexc(self, opts)
         self:_store(self:_collect(opts))
         self:_apply()
         self:_set_status_based_on_alerts()
+        if self._status == 'ready' or self._status == 'check_warnings' then
+            self._active_metadata = self._metadata
+        end
```
Comment (Totktonada) [inline src/box/lua/config/init.lua:458]: I think we should do it after the post_apply phase (after roles and the app execution, but before extras.post_apply). This way if a role/app execution failed we don't lie about active configuration.

In fact, this situation means some intermediate active configuration, but I would expect that `active` will show the latest one that was fully and successfuly applied.

Please, hold this property with a test: a fail in role/app applying should lead to different `active` and `last` metadata.

File: changelogs/unreleased/gh-9780-show-active-meta.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+## feature/config
+
+* The `config:info()` functionality has been expanded (gh-9780).
```
Comment (Totktonada) [inline changelogs/unreleased/gh-9780-show-active-meta.md:3]: Nit: As for me, a changelog entry assumes that we point a functionality itself, not just the fact that it is added. For example, 'added active configuration metainformation (usually a revision in a remote source)'.

File: src/box/lua/config/init.lua [hunk 3]
```diff
@@ -474,13 +480,26 @@ function methods.reload(self)
...
+        return {
+            alerts = self._aboard:alerts(),
+            meta = {
+                active = self._active_metadata,
+                last = self._metadata,
+            },
+            status = self._status,
+        }
+    end
+    error(('Expected "v2" or nil as info version, got %q'):format(version), 0)
```
Comment (Totktonada) [inline src/box/lua/config/init.lua:502]: Nit: The error message is a bit inaccurate. I mean the following.

1. It doesn't mention 'v1'.
2. It requires updating with every version change (and it is easy to overlook).

I would update it this way:

```lua
local function set2string(s)
    local list = {}
    for k, _ in pairs(s) do
        table.insert(list)
    end 
    table.sort(list)
    return ('"%s"'):format(table.concat(list, '", "'))
end

function methods.info(self, version)
    selfcheck(self, 'info')
    version = version or 'v1'
    local supported_versions = { 
        v1 = true,
        v2 = true,
    }   
    if supported_versions[version] == nil then
        error(('config:info() expects nil or %s as an argument, got %q'):format(
            set2string(supported_versions), version), 0)
    end 
    <...>
end
```

Or don't mention versions at all (but this information looks useful).

Or just hardcode `nil, "v1" or "v2"` and try to remember to update it next time.

File: test/config-luatest/config_test.lua [hunk 4]
```diff
@@ -1393,3 +1393,180 @@ g.test_non_dynamic_alert = function(g)
...
+        }
+
+        function methods.sync(self, config)
+            local data = file.universal_read('myconf.yaml', 'my config file')
+            local ok, res = pcall(yaml.decode, data)
+            if not ok then
+                error('Unable to parse my config file')
+            end
+            self._values = res
+            config:_meta('myconf', 'revision', self._revision)
```
Comment (Totktonada) [inline test/config-luatest/config_test.lua:1438]: Nit: It is not important for testing, but if we take it as example of a configuration source with metainformation, I would use the same `:_meta()` key as the source name.

**Review by Totktonada — APPROVED** [review]
The patch looks OK for me except a few small comments. Please, take them into account.

File: src/box/lua/config/init.lua (hunk 1 above)
Comment (ImeevMA) [reply src/box/lua/config/init.lua:458]: I am not sure about this. I mean, this way the `active` meta in roles and app will be from the last successful load, but `configdata` will be from the current load.

**Review by ochaplashkin — APPROVED** [review]

File: src/box/lua/config/init.lua (hunk 1 above)
Comment (Totktonada) [reply src/box/lua/config/init.lua:458]: We do the same for statuses.

There is an alternative: we can set the active metadata after `apply`, but revert it back if an error occurs in `post_apply`.

However, I think that it would be too complicated, while it is not necessary that it was expected by a user. I would prefer a simple solution.

Since we provide both `last` and `active` I don't think that it worth to do the tricks like we do for `config:get()`.

Comment (ImeevMA) [reply src/box/lua/config/init.lua:458]: Agree. Fixed.

File: changelogs/unreleased/gh-9780-show-active-meta.md (hunk 2 above)
Comment (ImeevMA) [reply changelogs/unreleased/gh-9780-show-active-meta.md:3]: Fixed.

File: src/box/lua/config/init.lua (hunk 3 above)
Comment (ImeevMA) [reply src/box/lua/config/init.lua:502]: Fixed, rewrote the code.

File: test/config-luatest/config_test.lua (hunk 4 above)
Comment (ImeevMA) [reply test/config-luatest/config_test.lua:1438]: True, fixed.

File: src/box/lua/config/init.lua (hunk 3 above)
Comment (Totktonada) [reply src/box/lua/config/init.lua]: Sorry for nitpicking, but I would highlight two tiny points.

1. `:alerts()` is called twice. It has a cycle inside and it seems easy to avoid it.
2. `pairs(info)` order is arbitrary, so I would add `table.sort(supported_versions)`.

File: test/config-luatest/config_test.lua (hunk 4 above)
Comment (Totktonada) [reply test/config-luatest/config_test.lua]: Sorry for nitpicking, but the source still named as `myfile` (in the `name` field), while placed into `mysource.lua` and reported as `mysource` in the metainformation.

File: src/box/lua/config/init.lua (hunk 3 above)
Comment (ImeevMA) [reply src/box/lua/config/init.lua]: Thanks, fixed.

File: test/config-luatest/config_test.lua (hunk 4 above)
Comment (ImeevMA) [reply test/config-luatest/config_test.lua]: Sorry, fixed.

**Review by filonenko-mikhail — APPROVED** [review]

File: changelogs/unreleased/gh-9780-show-active-meta.md [hunk 5]
```diff
@@ -0,0 +1,4 @@
+## feature/config
+
+* The `config:info()` can now display source metadata from the last
+  successful load along with source metadata from the last load.
```
Comment (p7nov) [inline changelogs/unreleased/gh-9780-show-active-meta.md:4]:
```suggestion

* `config:info()` can now display source metadata from the last successful
  load along with source metadata from the very last load attempt.
```

**Review by p7nov — APPROVED** [review]

File: changelogs/unreleased/gh-9780-show-active-meta.md (hunk 5 above)
Comment (ImeevMA) [reply changelogs/unreleased/gh-9780-show-active-meta.md]: Thank you! Applied.
