### PR TITLE
core: fix testing tuple field count overflow

### LINKED ISSUE #6684: box-tap/gh-6198-max-cnt-of-tuple-fields-insert-overflow-err-msg.test.lua requires a lot of memory
...and fails on our FreeBSD runners in CI.

I tried it manually on a FreeBSD 13 instance with 4 GiB memory:

```sh
$ ./src/tarantool test/box-tap/gh-6198-max-cnt-of-tuple-fields-insert-overflow-err-msg.test.lua
<...>
2021-12-07 18:52:05.894 [802] main/103/gh-6198-max-cnt-of-tuple-fields-insert-overflow-err-msg.test.lua I> set 'log_level' configuration option to 5
2021-12-07 18:52:05.894 [802] main/103/gh-6198-max-cnt-of-tuple-fields-insert-overflow-err-msg.test.lua I> set 'log_format' configuration option to "plain"
2021-12-07 18:52:05.894 [802] main/105/checkpoint_daemon I> scheduled next checkpoint for Tue Dec  7 20:36:51 2021
Killed
$ tail -n 20 /var/log/messages 
<...>
Dec  7 18:52:10 aturenko-freebsd-13 kernel: pid 802 (tarantool), jid 0, uid 1001, was killed: out of swap space
Dec  7 18:52:11 aturenko-freebsd-13 kernel: pid 758 (sendmail), jid 0, uid 0, was killed: out of swap space
Dec  7 18:52:14 aturenko-freebsd-13 kernel: pid 761 (sendmail), jid 0, uid 25, was killed: out of swap space
```

If you're going to reproduce it, the workaround from #6683 may be useful.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
Testing tuple field count overflow handling requires creating a severely
large tuple with box.schema.FIELD_MAX (INT32_MAX) fields: introduce an
error injection for testing this corner case.

Fixes #6684

### CODE REVIEW

File: src/box/xrow_update_array.c [hunk 1]
```diff
@@ -370,8 +370,18 @@ xrow_update_op_do_array_insert(struct xrow_update_op *op,
 
 	struct xrow_update_rope *rope = field->array.rope;
 	uint32_t size = xrow_update_rope_size(rope);
-	assert(size <= BOX_FIELD_MAX);
-	if (size == BOX_FIELD_MAX) {
+	/*
+	 * TODO: if the error injection code hits performance, we must put it
+	 * under conditional compilation.
+	 */
```
Comment (locker) [inline src/box/xrow_update_array.c:376]: AFAIU for release builds the check is compiled out, because `errinj()` returns NULL. Since we only care about performance of release builds, I think you should remove this comment.

File: test/box-tap/suite.ini [hunk 2]
```diff
@@ -4,7 +4,6 @@ description = Database tests with #! using TAP
 is_parallel = True
 use_unix_sockets_iproto = True
 release_disabled = errinj_set_with_enviroment_vars.test.lua
-disabled = gh-6198-max-cnt-of-tuple-fields-insert-overflow-err-msg.test.lua
```
Comment (locker) [inline test/box-tap/suite.ini:7]: Since the test uses error injection, you should append it to the `release_disabled` list.

**Review by locker — CHANGES_REQUESTED** [review]

File: test/box-tap/suite.ini (hunk 2 above)
Comment (CuriousGeorgiy) [reply test/box-tap/suite.ini:7]: Appended to the `release_disabled` list.

Comment (CuriousGeorgiy) [reply test/box-tap/suite.ini:7]: Appended the test to the `release_disabled` list.

File: src/box/xrow_update_array.c (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/xrow_update_array.c]: Agreed on the assumption that compilers eliminate such dead code.

Removed this comment.

**Review by locker — APPROVED** [review]

File: src/box/xrow_update_array.c (hunk 1 above)
Comment (CuriousGeorgiy) [reply src/box/xrow_update_array.c]: Proof: https://godbolt.org/z/bPs6EY9ec
