### PR TITLE
sql: add support of DECIMAL and INTEGER to ROUND()

### LINKED ISSUE #6988: SQL ROUND function doesn't work for legit fractional expressions
**Bug description**

A lot of legitimate fractional expressions are not handled by SQL ROUND function any more. The reasons are:

1. Fractional constants now have 'decimal' type.
2. Implicit typecasts are eliminated for cases when loss of precision may occur.

Possible solution to the problem: we need a decimal overload of SQL ROUND function.

* OS: Linux
* OS Version: Centos 8
* Architecture: amd64

Tarantool 2.10.0-beta2-207-ga5557281c
Target: Linux-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/lib64/ccache/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

**Steps to reproduce**

Run tarantool, box.cfg{}

Run query:
```lua
box.execute([[select round(1.0 / 3)]])
```

**Actual behavior**

```
---
- null
- 'Type mismatch: can not convert decimal(0.33333333333333333333333333333333333333)
  to double'
...
```

**Expected behavior**

```
---
- metadata:
  - name: COLUMN_1
    type: decimal
  rows:
  - [0]
...
```

### PR DESCRIPTION
**Pull request by ImeevMA**
This patch fixes an issue with the implicit cast of INTEGER and DECIMAL
values to DOUBLE when they are passed as the first argument to the
ROUND() function.

Closes #6988

@TarantoolBot document
Title: ROUND() now properly supports INTEGER and DECIMAL

INTEGER and DECIMAL values passed as the first argument now will not be
cast to DOUBLE and the result will be of the same type as the first
argument. Also, the default type for the ROUND() is now DECIMAL.

### CODE REVIEW

File: src/box/sql/func.c [hunk 1]
```diff
@@ -1008,6 +1008,36 @@ func_round(struct sql_context *ctx, int argc, const struct Mem *argv)
...
+		return;
+	assert(mem_is_dec(&argv[0]));
+	assert(argc == 1 || mem_is_int(&argv[1]));
+	uint64_t n = (argc == 2 && mem_is_uint(&argv[1])) ? argv[1].u.u : 0;
+
+	if (n >= DECIMAL_MAX_DIGITS)
+		return mem_set_dec(ctx->pOut, &argv[0].u.d);
+	decimal_t dec = argv[0].u.d;
+	decimal_round(&dec, n);
+	return mem_set_dec(ctx->pOut, &dec);
```
Comment (Gerold103) [inline src/box/sql/func.c:1026]: I suggest this diff to reduce some copying:
<details><summary>diff</summary>

```Diff
 	assert(mem_is_dec(&argv[0]));
 	assert(argc == 1 || mem_is_int(&argv[1]));
 	uint64_t n = (argc == 2 && mem_is_uint(&argv[1])) ? argv[1].u.u : 0;
-
-	if (n >= DECIMAL_MAX_DIGITS)
-		return mem_set_dec(ctx->pOut, &argv[0].u.d);
-	decimal_t dec = argv[0].u.d;
-	decimal_round(&dec, n);
-	return mem_set_dec(ctx->pOut, &dec);
+	mem_set_dec(ctx->pOut, &argv[0].u.d);
+	if (n < DECIMAL_MAX_DIGITS)
+		decimal_round(&ctx->pOut->u.d, n);
 }
```
</details>

File: test/sql-luatest/gh_6988_add_round_implementations_test.lua [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+        t.assert_equals(box.execute(sql).rows, res)
+
+        sql = [[SELECT ROUND(-562323432, -10000000);]]
+        res = {{-562323432}}
+        t.assert_equals(box.execute(sql).rows, res)
+    end)
+end
+
+-- Make sure that the default type for the first argument of ROUND() is DECIMAL.
+g.test_round_dec = function()
```
Comment (Gerold103) [inline test/sql-luatest/gh_6988_add_round_implementations_test.lua:67]: `g.test_round_dec` is assigned 3 times which means only one of them is actually running.

**Review by Gerold103 — CHANGES_REQUESTED** [review]

File: src/box/sql/func.c (hunk 1 above)
Comment (ImeevMA) [reply src/box/sql/func.c]: Thank you for the review and suggestion! Applied.

File: test/sql-luatest/gh_6988_add_round_implementations_test.lua (hunk 2 above)
Comment (ImeevMA) [reply test/sql-luatest/gh_6988_add_round_implementations_test.lua]: Thanks, fixed.

**Review by Gerold103 — APPROVED** [review]
Thanks for the fixes!

**Review by kyukhin — APPROVED** [review]
