### PR TITLE
box: fix set language shared between clients via console.connect

### LINKED ISSUE #8817: Set language is shared between clients via `console.connect`
**Bug description**

Result of `\set language` is shared between clients via `console.connect`, despite the fact that clients have different `box.session.id`. In other words, language changes on one client are applied on another.

* OS: MacOS
* OS Version: 13.2.1 (Darwin Kernel Version 22.3.0)
* Architecture: amd64

Tarantool 2.10.6-0-g3990f97

**Steps to reproduce**

Run 3 tarantool instances iteractively.

Server:

```lua
tarantool> box.cfg{listen=3333}
tarantool> box.schema.user.grant('guest','super')
```

Client1:

```lua
tarantool> require('console').connect('localhost:3333')
connected to localhost:3333
---
- true
...

localhost:3333> box.session.id()
---
- 3
...

localhost:3333> \set language
---
- language: lua
...
```

Client 1 has language `lua`.

Client2:

```lua
tarantool> require('console').connect('localhost:3333')
connected to localhost:3333
---
- true
...

localhost:3333> box.session.id()
---
- 4
...

localhost:3333> \set language sql
---
- true
...
```

Switched language to `sql` for Client2.

But now on Client1:

```lua
localhost:3333> \set language
---
- language: sql
...
```

**Actual behavior**

The selected languages should be independent on the clients.

A quick glance showed that the solution could be to use `box.session.storage.language` instead `box.session.language` in `src/box/lua/console.lua`

### PR DESCRIPTION
**Pull request by GRISHNOV**
Before this fix, result of `\set language` is shared between clients via `console.connect`, despite the fact that clients have different `box.session.id`. Now the parameter of the selected language is stored by each client in his own `box.session.storage`.

Fixes #8817

### CODE REVIEW

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+-- Stop server test instance.
+g.after_all(function()
+    g.server:stop()
+end)
+
+-- Checks that the language setting is not shared between clients.
+g.test_set_language_not_shared_between_clients = function()
+    -- Find tarantoolctl.
+    -- Probably test-run knows the path to tarantoolctl.
+    local TARANTOOLCTL_PATH = os.getenv('TARANTOOLCTL')
```
Comment (ligurio) [inline test/box-luatest/gh_8817_bug_set_language_shared_test.lua:27]: It is not clear to me why do you use tarantoolctl in the test when the same test could be created without it.
In the nearest time tarantoolctl will be gone and after that we will update all tests that require tarantoolctl. I suspect no one wants to do double work, so let's avoid using tarantoolctl and replace it with a two additional tarantool instances and a couple of connections using `console` module (the same way as in a bug description).

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+    result = ph_connect_second_client:read()
+    ph_connect_second_client:close()
+
+    -- The language changes on the first client did not spread to the second.
+    t.assert_equals(
+        result,
+        "---\n- language: lua\n...\n\n"
+    )
+end
```
Comment (ligurio) [inline test/box-luatest/gh_8817_bug_set_language_shared_test.lua:80]: It is not clear what test should check from the first sight. I suggest splitting test body for test setup (setting up connections to tarantool instance), test teardown (closing connections to tarantool instance) and test logic itself (check language in both connections, change language and check on language again). It will make test more clear and concise.

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+        end
+    end
+
+    local cmd_tarantoolctl_connect = {
+        TARANTOOLCTL_PATH,
+        'connect',
+        tostring(g.server_port),
+    }
+
+    -- First connection will be established in a separate process.
```
Comment (ligurio) [inline test/box-luatest/gh_8817_bug_set_language_shared_test.lua:44]: Is it worth to check that `box.session.id` are different for two clients?

**Review by ligurio — COMMENTED** [review]
Ilya, thanks for the patch! Please see my comments.

File: changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+## bugfix/box
+
+* Fixed a bug in the box console implelemtation, because of
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md]: Fixed

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+    g.server:stop()
+end)
+
+-- Checks that the language setting is not shared between clients.
+g.test_set_language_not_shared_between_clients = function()
+    -- Find tarantoolctl.
+    -- Probably test-run knows the path to tarantoolctl.
+    local TARANTOOLCTL_PATH = os.getenv('TARANTOOLCTL')
+    if TARANTOOLCTL_PATH == nil then
+        -- If test-run dose not know the path to tarantoolctl.
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply test/box-luatest/gh_8817_bug_set_language_shared_test.lua]: Deleted

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+        -- Assume that current directory is tarantool's build directory.
+        local BUILDDIR = os.getenv('BUILDDIR')
+        TARANTOOLCTL_PATH = ('%s/extra/dist/tarantoolctl'):format(BUILDDIR)
+        if not fio.path.exists(TARANTOOLCTL_PATH) then
+            error("Can't find tarantoolctl")
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply test/box-luatest/gh_8817_bug_set_language_shared_test.lua]: Done, deleted

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua (hunk 1 above)
Comment (GRISHNOV) [reply test/box-luatest/gh_8817_bug_set_language_shared_test.lua]: Done, now using `require('console').connect` via `test.interactive_tarantool`

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua (hunk 2 above)
Comment (GRISHNOV) [reply test/box-luatest/gh_8817_bug_set_language_shared_test.lua]: Done, part of the logic has been moved to `g.before_all`

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua (hunk 3 above)
Comment (GRISHNOV) [reply test/box-luatest/gh_8817_bug_set_language_shared_test.lua]: Done, added

**Comment by GRISHNOV** [comment]
Thank you for your feedback! I tried to answer all the comments on the code review

**Review by p7nov — APPROVED** [review]
Minor changelog improvement:

File: changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md [hunk 7]
```diff
@@ -0,0 +1,5 @@
+## bugfix/box
+
+* Fixed a bug in the box console implementation, because of
+  which the language parameter was shared between connected
+  clients (gh-8817).
```
[the remark this answers is not in the document]
Comment (GRISHNOV) [reply changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md]: Done

**Review by 0x501D — APPROVED** [review]

File: changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md (hunk 4 above)
[the remark this answers is not in the document]
Comment (ligurio) [reply changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md]: Thank you!

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua (hunk 2 above)
Comment (ligurio) [reply test/box-luatest/gh_8817_bug_set_language_shared_test.lua]: Thank you!

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua [hunk 8]
```diff
@@ -0,0 +1,84 @@
+local t = require('luatest')
```
Comment (ligurio) [inline test/box-luatest/gh_8817_bug_set_language_shared_test.lua:1]: Test passed on tarantool without fix.

File: changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md [hunk 9]
```diff
@@ -0,0 +1,5 @@
+## bugfix/box
+
+* Fixed a bug in the box console implementation because of
+  which the `language` parameter was shared between connected
```
Comment (ligurio) [inline changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md:4]: Nit: current length of lines in commit message is 55, max allowed length is 72 symbols [^1]. I propose to reformat it.

[^1]: https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message

Comment (GRISHNOV) [reply changelogs/unreleased/gh-8817-bug-fix-set-language-shared-between-conn-clients.md:4]: Done

File: test/box-luatest/gh_8817_bug_set_language_shared_test.lua (hunk 8 above)
Comment (GRISHNOV) [reply test/box-luatest/gh_8817_bug_set_language_shared_test.lua:1]: Done, the problem is reproduced only if the server is raised via `box.cfg{listen=...}`, not via `console.listen(...)`. For server with `console.listen(...)` there is no such bug

**Review by ligurio — APPROVED** [review]
LGTM now

**Comment by igormunkin** [comment]
Also backported to 2.11 and 2.10 in scope of 93812b3 and 8aa2bb1 respectively.
