### PR TITLE
sql: fix wrong ephemeral space format

### LINKED ISSUE #7042: SQL temporary fields types mismatch
**Bug description**

A trivial SQL query doesn't work...

* OS: Linux
* OS Version: Centos 8
* Architecture: amd64

```
Tarantool 2.10.0-beta2-286-gb494e762e
Target: Linux-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/lib64/ccache/c++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Run tarantool. Run the following script:

```Lua
box.cfg{}

test1 = box.schema.create_space("test1")

test1:format({
      { name = "id", type = "unsigned" },
      { name = "a", type = "string", is_nullable = true },
      { name = "b", type = "string", is_nullable = true }
})

test1:create_index("primary")

test1:insert({1, "a", "b"})

box.execute([[
    select "a", "b", "id"
    from "test1"
    order by "a", "b"
    limit 1;
]])
```

**Actual behavior**

```
---
- null
- 'Tuple field 4 (_COLUMN_3) type does not match one required by operation: expected
  string, got unsigned'
...
```

**Expected behavior**

```
---
- metadata:
  - name: id
    type: unsigned
  - name: a
    type: string
  - name: b
    type: string
  rows:
  - ['a', 'b', 1]
...
```

### PR DESCRIPTION
**Pull request by ImeevMA**
This patch fixes format building when an ephemeral space was used in
ORDER BY and ORDER BY uses at least two variables from the list of
selected columns.

Closes #7042

NO_DOC=Bugfix

### CODE REVIEW

File: src/box/sql/select.c [hunk 1]
```diff
@@ -270,6 +270,24 @@ sql_key_info_new_from_space_info(const struct sql_space_info *info)
...
+	for (uint32_t j = 0; j < drop_count; ++j) {
+		uint32_t k = 0;
+		for (; k < info->field_count - j - 1; ++k) {
+			if (info->types[k] == field_type_MAX)
+				break;
+		}
+		for (; k < info->field_count - j - 1; ++k) {
+			info->types[k] = info->types[k + 1];
+			info->coll_ids[k] = info->coll_ids[k + 1];
+		}
```
Comment (Gerold103) [inline src/box/sql/select.c:286]: A canonical solution for removal of multiple items from an array is to open 2 iterators - src and dst. Src is copied into dst on each step. If src meets a condition, it is skipped but dst iterator is kept intact. That way you copy the array only once. Can be optimized if you firstly look for a first item to skip and if you don't find it, then you return. In your solution sometimes you do not copy anything indeed but otherwise some of the items can be copied multiples times.

**Review by Gerold103 — APPROVED** [review]
Thanks for the patch!
I don't really understand what was wrong here, but I suppose the patch makes better, LGTM!

**Comment by kyukhin** [comment]
Backported to 2.10.
