### PR TITLE
box: fix first function creation

### LINKED ISSUE #12118: crash on an attempt to create a function after dropping all existing functions
Reproducer:
```lua
box.cfg{}
for k, v in box.space._func:pairs() do box.schema.func.drop(v.name) end
box.schema.func.create('test')
```
On debug build, the last step will result in an assertion failure:
```
Assertion failed: (res != NULL), function box_generate_unique_id, file box.cc, line 6646.
```
On release build, it'll result in a segmentation fault:
```
Segmentation fault
  code: SEGV_ACCERR
  addr: 0x2
  context: 0x1400b7c18
  siginfo: 0x1400b7bb0
Current time: 1765200684
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x102a53b9c in crash_signal_cb+148
#2  0x18f6c56a4 in _sigtramp+56
#3  0x10298779c in box_generate_func_id+196
#4  0x10298779c in box_generate_func_id+196
#5  0x102a14efc in lbox_generate_func_id(lua_State*)+168
```

Related to 95d35505f5784c0d45bc404ef6f0c85471b3ec02

### PR DESCRIPTION
**Pull request by LevKats**
New func id generation algorithm apparently assumed that there are
already some funcs presented, since we expected some tuple to be returned
from the iterator. However, it was possible to remove all `_func` space
entries, resulting in a server crash. Now, we start searching for an
empty id from 1 in this case.

Follows up #11849
Follows up #11851
Fixes #12118

NO_CHANGELOG=was not released
NO_DOC=bugfix

### CODE REVIEW

File: test/box-luatest/gh_12118_generate_first_func_id_test.lua [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+g.after_all(function(g)
+    g.server:drop()
+end)
+
+g.test_function_create_first = function(g)
+    g.server:exec(function()
+        for _, v in box.space._func:pairs() do
+            box.schema.func.drop(v.name)
+        end
+        box.schema.func.create('test')
```
Comment (drewdzzz) [inline test/box-luatest/gh_12118_generate_first_func_id_test.lua]: Nit: let's check its id. Also, let's create several functions (two, for example), just in case (and check id of the second one as well).

File: src/box/box.cc
Comment (drewdzzz) [inline src/box/box.cc:1]: Please, check (locally, at least) that it fixes failing space upgrade test from Tarantool EE.

File: test/box-luatest/gh_12118_generate_first_func_id_test.lua (hunk 1 above)
Comment (LevKats) [reply test/box-luatest/gh_12118_generate_first_func_id_test.lua]: Fixed

File: src/box/box.cc
Comment (LevKats) [reply src/box/box.cc:1]: [Fixed](https://github.com/tarantool/tarantool-ee/pull/1587)

File: test/box-luatest/gh_11849_11851_box_func_no_id_overflow_test.lua [hunk 2]
```diff
@@ -16,25 +16,29 @@ g.test_function_create_drop_multiple = function(g)
...
-        box.commit()
     end)
 end
 
 g.test_sql_execute_query_func_about_to_overflow = function(g)
     g.server:exec(function()
         local fiber = require("fiber")
-        fiber.set_slice(60)
         box.begin()
+        fiber.set_slice(60)
```
Comment (drewdzzz) [inline test/box-luatest/gh_11849_11851_box_func_no_id_overflow_test.lua:36]: Nit: this change is not actually needed since `begin` doesn't yield, also we could set `max_slice` to 120/240 (or even 10000, for example, to basically disable it) if 60 is not enough.
By the way, the previous test could be fixed in this way as well - the commit would be much smaller then.

I'm OK with current patch version though. Fix or not to fix this nitpick - it's up to you. Feel free to resolve this comment.

**Review by drewdzzz — APPROVED** [review]

File: test/box-luatest/gh_11849_11851_box_func_no_id_overflow_test.lua (hunk 2 above)
Comment (LevKats) [reply test/box-luatest/gh_11849_11851_box_func_no_id_overflow_test.lua:36]: Fixed. 
```diff
 while i < BOX_FUNCTION_MAX + 10 do
-    box.begin()
     fiber.set_slice(60)
+    box.begin()
```
```diff
 g.server:exec(function()
     local fiber = require("fiber")
-    box.begin()
     fiber.set_slice(60)
+    box.begin()
     local i = 1
     while true do
```

Comment (drewdzzz) [reply test/box-luatest/gh_11849_11851_box_func_no_id_overflow_test.lua:36]: I meant we could simply extend fiber slice in the first test instead of using batching :)

Comment (LevKats) [reply test/box-luatest/gh_11849_11851_box_func_no_id_overflow_test.lua:36]: Set slice size to 240 seconds. Changed commit the message correspondingly.

Comment (drewdzzz) [reply test/box-luatest/gh_11849_11851_box_func_no_id_overflow_test.lua:36]: See that you've removed batching. Looks nice to me.
