### PR TITLE
box: delete .inprogress files from wal_dir

### LINKED ISSUE #12081: Leftover `.xlog.inprogress` files are not cleared if `wal_dir` is different from `memtx_dir`
**Bug description**
Tarantool only deletes stale `.inprogress` files in `memtx_dir` and `vinyl_dir`, but ignores `wal_dir`.
If `wal_dir` doesn't match `memtx_dir`, the `.xlog.inprogress` files won't be removed and Tarantool will fail creating new xlogs.

**Steps to reproduce**:
1. In a directory where you're going to run Tarantool, create a subdirectory: ```mkdir wals```
2. Start tarantool and issue:
```lua
box.cfg{wal_dir = './wals'}
-- Dummy record to bump vclock and make tarantool open an xlog on exit.
box.space._schema:replace{'asdf'}
-- Graceful exit to make tarantool leave an empty '0000000001.xlog':
os.exit()
```
3. Rename the xlog: ```mv wals/00000000000000000001.xlog wals/00000000000000000001.xlog.inprogress```
4. Start tarantool once again:
```lua
box.cfg{wal_dir = './wals'}
-- An attempt to write anything will fail:
box.space._schema:replace{'asdf'}
```
The console/log output will be
```
tarantool> box.space._schema:replace{'asdf'}
2025-11-27 16:48:49.740 [82133] wal/101/main xlog.c:875 E> failed to create file './wals/00000000000000000001.xlog.inprogress': File exists {"type":"SystemError","errno":17,"trace":[{"file":"./src/box/xlog.c","line":875}]}
2025-11-27 16:48:49.740 [82133] main/104/interactive txn.c:1186 E> Failed to write to disk {"type":"ClientError","code":40,"name":"WAL_IO","trace":[{"file":"./src/box/txn.c","line":1186}]}
---
- error: Failed to write to disk
...
```

JIRA issue: https://jira.vk.team/browse/TNTP-5588

### PR DESCRIPTION
**Pull request by LevKats**
In tarantool, each engine maintains its own files including
`.inprogress`. However, `.xlog` files  do not belong to any particular
engine and are common. When `wal_dir` matches `memtx_dir`, xlogs just
happen to be accidentally deleted by memtx engine.

In this patch, `.inprogress` are explicitly deleted from the `wal_dir`
on the server start.

Fixes https://github.com/tarantool/tarantool/issues/12081

NO_DOC=bugfix

### CODE REVIEW

File: src/box/box.cc [hunk 1]
```diff
@@ -5949,6 +5949,7 @@ local_recovery(const struct vclock *checkpoint_vclock)
 	if (wal_enable() != 0)
 		diag_raise();
 
+	wal_remove_temporary_files();
```
Comment (drewdzzz) [inline src/box/box.cc]: Nit: there is a comment in `memtx_engine.cc`:
https://github.com/tarantool/tarantool/blob/2a13aaeb9873dd2e6f036b79fd2076c4c0961e4a/src/box/memtx_engine.cc#L711-L712

It seems it should become just `Removes *.sortdata.inprogress files.`.

File: src/box/wal.c [hunk 2]
```diff
@@ -1684,3 +1684,10 @@ wal_notify_watchers(struct wal_writer *writer, unsigned events)
 	rlist_foreach_entry(watcher, &writer->watchers, next)
 		wal_watcher_notify(watcher, events);
 }
+
+void
+wal_remove_temporary_files(void)
+{
+	struct wal_writer *writer = &wal_writer_singleton;
+	xdir_remove_temporary_files(&writer->wal_dir);
```
Comment (drewdzzz) [inline src/box/wal.c]: I just glanced over `wal_writer` and it seems to me that `writer->wal_dir` can be updated from WAL thread. Do I miss something or there is a potential data race here?

File: src/box/box.cc (hunk 1 above)
Comment (LevKats) [reply src/box/box.cc]: If I understand correctly, there could also be just .snap.inprogress files that are also deleted.

File: src/box/wal.c (hunk 2 above)
Comment (LevKats) [reply src/box/wal.c]: Fixed. Sorry for long response.

File: src/box/box.cc (hunk 1 above)
Comment (drewdzzz) [reply src/box/box.cc]: Oh, you're right!

File: src/box/wal.c [hunk 3]
```diff
@@ -1684,3 +1684,21 @@ wal_notify_watchers(struct wal_writer *writer, unsigned events)
...
+	return 0;
+}
+
+void
+wal_remove_temporary_files(void)
+{
+	struct wal_writer *writer = &wal_writer_singleton;
+	struct cbus_call_msg msg;
+	cbus_call(&writer->wal_pipe, &writer->tx_prio_pipe, &msg,
```
Comment (drewdzzz) [inline src/box/wal.c]: This call can actually fail.

File: src/box/wal.c [hunk 4]
```diff
@@ -1684,3 +1684,21 @@ wal_notify_watchers(struct wal_writer *writer, unsigned events)
 	rlist_foreach_entry(watcher, &writer->watchers, next)
 		wal_watcher_notify(watcher, events);
 }
+
+static int
+wal_remove_temporary_files_f(struct cbus_call_msg *msg)
+{
+	(void)msg;
+	struct wal_writer *writer = &wal_writer_singleton;
+	xdir_remove_temporary_files(&writer->wal_dir);
```
Comment (drewdzzz) [inline src/box/wal.c]: I'd move it to `wal_enable` (we can put it right to `wal_open_f`):
1. It seems natural that WAL would clean garbage that would break it when it is being enabled.
2. We clean `memtx_dir` and `vinyl_dir` inside `end_recovery` methods. Let's clean WAL inside of a WAL method as well.

Comment (Serpentian) [inline src/box/wal.c]: Hmm, I don't like that `xdir_remove_temporary_files` function. Afaics, it drops all files, which ends with `.inprogress` suffix. Isn't it possible, that wal will drop the files of memtx or vinyl, when they're being written (or vice versa)?

I'd expect the function to drop only the files, which a specific for engine, e.g.

```C
xdir_remove_temporary_files(xdir, "xlog")
```

If it were always like this, we would never have encountered this problem.

Comment (LevKats) [reply src/box/wal.c]: Fixed

Comment (LevKats) [reply src/box/wal.c]: Fixed. Unfortunately, `wal_open_f` in particular is not the right place since it is called only if some `.xlog` (not `xlog.inprogress`) are found, so is is in `wal_enable`.

File: src/box/wal.c (hunk 3 above)
Comment (LevKats) [reply src/box/wal.c]: Fixed, I guess

File: src/box/xlog.c [hunk 5]
```diff
@@ -714,20 +714,36 @@ xdir_remove_file_by_vclock(struct xdir *dir, struct vclock *to_remove)
...
 static bool
-xlog_file_is_temporary_default(const char *filename)
+xlog_file_is_temporary_default(const char *filename,
+			       const char *target_ext)
 {
-	const char *ext = strrchr(filename, '.');
-	return ext != NULL && strcmp(ext, inprogress_suffix) == 0;
+	char buf[PATH_MAX];
+	/**
+	 * Note that both target_ext and inporgess_suffix have a dot.
```
Comment (drewdzzz) [inline src/box/xlog.c]: Nit: We could check it with assertion.

Comment (drewdzzz) [inline src/box/xlog.c]: Nit: This comment would be one-liner.

File: src/box/xlog.c [hunk 6]
```diff
@@ -714,20 +714,36 @@ xdir_remove_file_by_vclock(struct xdir *dir, struct vclock *to_remove)
...
 /** Default implementation of xlog_file_is_temporary(). */
 static bool
-xlog_file_is_temporary_default(const char *filename)
+xlog_file_is_temporary_default(const char *filename,
+			       const char *target_ext)
 {
-	const char *ext = strrchr(filename, '.');
-	return ext != NULL && strcmp(ext, inprogress_suffix) == 0;
+	char buf[PATH_MAX];
+	/**
```
Comment (drewdzzz) [inline src/box/xlog.c]: Nit: we use `/* ... */` comments inside of functions. Let's fix it along the way.

File: src/box/memtx_engine.cc [hunk 7]
```diff
@@ -722,8 +722,10 @@ memtx_engine_end_recovery(struct engine *engine)
 		memtx->on_indexes_built_cb();
 	}
 
-	/* Also removes *.sortdata.inprogress files. */
-	xdir_remove_temporary_files(&memtx->snap_dir);
+	xdir_remove_temporary_files(&memtx->snap_dir,
+				    memtx->snap_dir.filename_ext);
+	/* Removes *.sortdata.inprogress files. */
```
Comment (drewdzzz) [inline src/box/memtx_engine.cc]: Nit: I think, we don't need this comment - it's just obvious.

File: src/box/wal.c [hunk 8]
```diff
@@ -649,6 +671,9 @@ wal_enable(void)
 	if (xdir_scan(&writer->wal_dir, true))
 		return -1;
 
+	if (wal_remove_temporary_files() != 0)
```
Comment (drewdzzz) [inline src/box/wal.c]: Is there any point in pushing this task to WAL thread? We are modifying `wal_dir` right above anyway.

File: test/box-luatest/gh-12081-delete-xlog-inprogress-custom-wal-dir_test.lua [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+    g.server = server:new()
+    -- Start the server so workdir is created.
+    g.server:start()
+end)
+
+g.after_all(function(g)
+    g.server:drop()
+end)
+
+g.test_function_delete_inprogress_custom_location = function(g)
```
Comment (drewdzzz) [inline test/box-luatest/gh-12081-delete-xlog-inprogress-custom-wal-dir_test.lua:16]: We could also add a test that memtx doesn't delete `xlog` files (just copy `.xlog.inprogress` file into memtx directory), just in case.

File: src/box/xlog.c (hunk 5 above)
Comment (LevKats) [reply src/box/xlog.c]: Added  assertion for both `target_ext` and `inprogress_suffix`.

Comment (LevKats) [reply src/box/xlog.c]: Decided to remove the comment as it is obvious from the assertions

File: src/box/xlog.c (hunk 6 above)
Comment (LevKats) [reply src/box/xlog.c]: The comment is removed.

File: src/box/memtx_engine.cc (hunk 7 above)
Comment (LevKats) [reply src/box/memtx_engine.cc]: Fixed.

File: src/box/wal.c (hunk 8 above)
Comment (LevKats) [reply src/box/wal.c]: Looks like we don't have any reasons anymore. Moved back to tx thread.

File: test/box-luatest/gh-12081-delete-xlog-inprogress-custom-wal-dir_test.lua (hunk 9 above)
Comment (LevKats) [reply test/box-luatest/gh-12081-delete-xlog-inprogress-custom-wal-dir_test.lua:16]: Fixed (memtx directory is just the work directory).

File: src/box/xlog.c [hunk 10]
```diff
@@ -714,20 +714,35 @@ xdir_remove_file_by_vclock(struct xdir *dir, struct vclock *to_remove)
...
+	strtolower(buf);
+	const char *target_ext_full = buf;
+	const char *ext = NULL;
+	const char *last = strrchr(filename, '.');
+	if (last != NULL) {
+		for (const char *p = strchr(filename, '.');
+		     p != NULL && p != last; p = strchr(p + 1, '.'))
+			ext = p;
+	}
+	return ext != NULL && strcmp(ext, target_ext_full) == 0;
```
Comment (Serpentian) [inline src/box/xlog.c]: The code for figuring out the extension of the file looks really complicated. Can't we do smth like that?

```c
	size_t filename_len = strlen(filename);
	size_t suffix_len = strlen(buf);
	return filename_len >= suffix_len &&
	       strncmp(filename + filename_len - suffix_len,
		       suffix, suffix_len) == 0;
````

From my understanding all we need to do is get the full suffix (e.g. "xlog.inprogress") and compare it with the end of the `filename`.

File: src/box/xlog.c [hunk 11]
```diff
@@ -714,20 +714,35 @@ xdir_remove_file_by_vclock(struct xdir *dir, struct vclock *to_remove)
...
 xlog_file_is_temporary_f xlog_file_is_temporary =
 				xlog_file_is_temporary_default;
 
 void
-xdir_remove_temporary_files(struct xdir *xdir)
+xdir_remove_temporary_files(struct xdir *xdir, const char *filename_ext)
 {
 	const char *dirname = xdir->dirname;
 	DIR *dh = opendir(dirname);
+
```
Comment (Serpentian) [inline src/box/xlog.c]: Nit: empty line seems not needed

Comment (LevKats) [reply src/box/xlog.c]: Fixed.

File: src/box/xlog.c (hunk 10 above)
Comment (LevKats) [reply src/box/xlog.c]: Thanks, it is indeed better. Fixed.

File: src/box/xlog.c [hunk 12]
```diff
@@ -714,17 +714,27 @@ xdir_remove_file_by_vclock(struct xdir *dir, struct vclock *to_remove)
...
-	return ext != NULL && strcmp(ext, inprogress_suffix) == 0;
+xlog_file_is_temporary_default(const char *filename,
+			       const char *target_ext)
+{
+	assert(inprogress_suffix[0] == '.');
+	assert(target_ext[0] == '.');
+	char buf[PATH_MAX];
+	VERIFY((size_t)snprintf(buf, sizeof(buf), "%s%s", target_ext,
+				inprogress_suffix) < sizeof(buf));
+	strtolower(buf);
```
Comment (Serpentian) [inline src/box/xlog.c]: One more question: why do we need to make the suffix in lower case, when it's already in lower? I'd expect from the function just to compare ending of the filename with `inprogress_suffix`+ `filename_ext` (which is actually already modified in the `xdir_create`)

https://github.com/tarantool/tarantool/blob/84e98e276bb86706bb36cffdb80eaf4fcce2fbb4/src/box/xlog.c#L348

The motivation is that, it's not a cheap function (it goes through every char and changes it if needed) and there's not much sense in wasting cpu time on that .

File: test/box-luatest/gh-12081-delete-xlog-inprogress-custom-wal-dir_test.lua [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+    local fio = require("fio")
+    local wal_dir = fio.pathjoin(g.server.workdir, "custom_wal_dir")
+    fio.mktree(wal_dir)
+    g.server:restart(
+        {box_cfg = {wal_dir = wal_dir}}, {wait_until_ready = true}
```
Comment (Serpentian) [inline test/box-luatest/gh-12081-delete-xlog-inprogress-custom-wal-dir_test.lua:21]: Nit: `wait_until_ready` is true by default, no need to specify it explicitly, it's confusing

**Review by Serpentian — APPROVED** [review]
These are nits, I'm ok in general. But please, let's anyway discuss (and fix if needed) them

File: src/box/xlog.c (hunk 12 above)
Comment (LevKats) [reply src/box/xlog.c]: While the function is not cheap I don't see the `xdir_remove_temporary_files` being used that frequently. Also looks like it is much cheaper than the spintf call above (and it is likely to be cheaper than the directory scan). Do we have any cases when we do have that many files in the work directory?
The reason the call was introduced is that a user tend to operate with uppercase type names (see the [example](https://github.com/tarantool/tarantool/blob/da560474046863198683af9321a008dc0a78f6a6/src/box/wal.c#L479)). While the `target_ext` is not the `dir->filetype` but `dir->filename_ext` (and a dot is required), I think the user does not have to know that we [do](https://github.com/tarantool/tarantool/blob/da560474046863198683af9321a008dc0a78f6a6/src/box/xlog.c#L348) lowercase internally. @Serpentian , what do you think?

Comment (Serpentian) [reply src/box/xlog.c]: Ok

File: test/box-luatest/gh-12081-delete-xlog-inprogress-custom-wal-dir_test.lua (hunk 13 above)
Comment (LevKats) [reply test/box-luatest/gh-12081-delete-xlog-inprogress-custom-wal-dir_test.lua:21]: Fixed

**Review by Serpentian — APPROVED** [review]

File: src/box/memtx_engine.cc
Comment (drewdzzz) [inline src/box/memtx_engine.cc:1]: Wait, why don't we need a changelog? It's a bugfix observable by a user.

File: src/box/xlog.c (hunk 12 above)
Comment (drewdzzz) [reply src/box/xlog.c]: > The reason the call was introduced is that a user tend to operate with uppercase type names (see the example).

AFAIU, the uppercase argument is a file type used in the file header. That's not an extension so we don't tend to operate with uppercase ones. This `strtolower` here is a bit confusing, so let's simply get rid of it. It's wasn't here before anyway.

File: src/box/xlog.c [hunk 14]
```diff
@@ -714,17 +714,27 @@ xdir_remove_file_by_vclock(struct xdir *dir, struct vclock *to_remove)
...
+	size_t filename_len = strlen(filename);
+	size_t suffix_len = strlen(buf);
```
Comment (drewdzzz) [inline src/box/xlog.c]: Let's rename `buf` to `suffix` then?

File: src/box/wal.c [hunk 15]
```diff
@@ -649,6 +649,9 @@ wal_enable(void)
 	if (xdir_scan(&writer->wal_dir, true))
 		return -1;
 
+	xdir_remove_temporary_files(&writer->wal_dir,
+				    writer->wal_dir.filename_ext);
```
Comment (drewdzzz) [inline src/box/wal.c]: Could you remind me, why do we need to pass `writer->wal_dir.filename_ext` at all?

File: src/box/xlog.c (hunk 12 above)
Comment (LevKats) [reply src/box/xlog.c]: Fixed

File: src/box/memtx_engine.cc
Comment (LevKats) [reply src/box/memtx_engine.cc:1]: Fixed

File: src/box/xlog.c (hunk 14 above)
Comment (LevKats) [reply src/box/xlog.c]: Fixed

File: src/box/wal.c (hunk 15 above)
Comment (LevKats) [reply src/box/wal.c]: If your question is about why we need an additional argument while passing the `xdir` object itself (which is supposed to know the extension), the reason is that there are cases where the extension cannot be determined uniquely. For example:
```diff
-       xdir_remove_temporary_files(&vy_log.dir);
+       xdir_remove_temporary_files(&vy_log.dir, ".run");
+       xdir_remove_temporary_files(&vy_log.dir, ".index");
+       xdir_remove_temporary_files(&vy_log.dir, ".vylog");
```
All three of `.run.inprogress`, `.index.inprogress`, `.vylog.inpogress` do exist: [[1]](https://github.com/tarantool/tarantool/blob/d2c5b72ddcb3c7fe4dc828874e030a6b8b06373a/src/box/vy_run.c#L69), [[2]](https://github.com/tarantool/tarantool/blob/d2c5b72ddcb3c7fe4dc828874e030a6b8b06373a/test/box/errinj.test.lua#L527).
We could add some logic to delete `xdir.filename_ext` by default, but do we actually need it?

Comment (drewdzzz) [reply src/box/wal.c]: No, I mean, why don't we just delete all `.inprogress` files?

Yep, the subsystems' files are not encapsulated then. But it's not dangerous since they are called from TX and are blocking, so the deletions will be executed sequentially.

The problem with current approach is `is_temporary` helpers become more complicated, especially when deleting `.inprogress.deleted`. So do we really need it?

Comment (LevKats) [reply src/box/wal.c]: The main (and likely the only) reason is the subsystem encapsulation concerns (introduced [here](https://github.com/tarantool/tarantool/pull/12247#discussion_r2792250948)). @locker , what do you think, does the current approach agree with the `xlog_file_is_temporary` callback idea?

File: changelogs/unreleased/gh-12081-delete-xlog-inprogress.md [hunk 16]
```diff
@@ -0,0 +1,4 @@
+## bugfix/box
+
+* Fixed a bug where `.xlog.inprogress` files were not automatically deleted
+  during server startup if the `wal_dir` value was not the default.
```
Comment (locker) [inline changelogs/unreleased/gh-12081-delete-xlog-inprogress.md]: Ticket is missing.

File: src/box/vy_log.c [hunk 17]
```diff
@@ -1149,7 +1149,9 @@ vy_log_end_recovery(void)
 		return -1;
 	}
 
-	xdir_remove_temporary_files(&vy_log.dir);
+	xdir_remove_temporary_files(&vy_log.dir, ".run");
+	xdir_remove_temporary_files(&vy_log.dir, ".index");
```
Comment (locker) [inline src/box/vy_log.c]: In-progress `.index` and `.run` files should be deleted by the Vinyl garbage collector (information about them is stored in `.vylog`). There's no need to delete them with `xdir_remove_temporary_files`.

File: src/box/memtx_engine.cc [hunk 18]
```diff
@@ -723,8 +723,9 @@ memtx_engine_end_recovery(struct engine *engine)
 		memtx->on_indexes_built_cb();
 	}
 
-	/* Also removes *.sortdata.inprogress files. */
-	xdir_remove_temporary_files(&memtx->snap_dir);
+	xdir_remove_temporary_files(&memtx->snap_dir,
+				    memtx->snap_dir.filename_ext);
+	xdir_remove_temporary_files(&memtx->snap_dir, ".sortdata");
```
Comment (locker) [inline src/box/memtx_engine.cc]: There's no test for this. The ticket doesn't mention `.sortdata` files. Why do you add this code?

File: src/box/wal.c (hunk 15 above)
Comment (locker) [reply src/box/wal.c]: I agree with @drewdzzz. I don't think we should really care about subsystem encapsulation at the cost of code complexity. I don't like passing a filename extension to `xdir_remove_temporary_files` because it's already stored in `xdir`. It's okay to use it if we want to avoid the case when one subsystem deletes in-progress files that belong to another subsystem.

File: src/box/memtx_engine.cc (hunk 18 above)
Comment (LevKats) [reply src/box/memtx_engine.cc]: I do it because `xdir_remove_temporary_files(&memtx->snap_dir);` used to delete both snap.inprogress and sortdata.inprogress and the comment above says that it is intentional. I need to keep the old behavior. The removed comment was introduced in https://github.com/tarantool/tarantool/commit/f7db783f37d3f5182bb00f7b23e8be111ace0b8d . However, i could test this.

File: changelogs/unreleased/gh-12081-delete-xlog-inprogress.md (hunk 16 above)
Comment (LevKats) [reply changelogs/unreleased/gh-12081-delete-xlog-inprogress.md]: Fixed

File: src/box/vy_log.c (hunk 17 above)
Comment (LevKats) [reply src/box/vy_log.c]: Fixed

File: src/box/wal.c (hunk 15 above)
Comment (LevKats) [reply src/box/wal.c]: Ok, the only way I see I can achieve lower code complexity is to reintroduce the old logic, where all temporary files in the directory are deleted by the `xdir_remove_temporary_files` call. The reason is the memtx directory containing both `.snap.inprogress` and `.sortdata.inprogress`. The old logic is returned.

File: src/box/memtx_engine.cc (hunk 18 above)
Comment (LevKats) [reply src/box/memtx_engine.cc]: Fixed (see the discussion above).

**Review by drewdzzz — APPROVED** [review]
LGTM

**Review by lenkis — APPROVED** [review]

**Review by Serpentian — APPROVED** [review]
