### PR TITLE
replication: fix assertion failure on unsuccessful configuration

### LINKED ISSUE #8675: Assertion fail in applier_pause()
Tarantool 3.0.0-entrypoint-214-g96706b7b7 Linux-x86_64-Debug.

Reproducer:

```lua
#!/usr/bin/env tarantool

local fio = require('fio')

local instance_name = 'instance_001'

local wal_dir = instance_name
local memtx_dir = instance_name
local listen = ('unix/:./%s.iproto'):format(instance_name)
local replication = {
    ('replicator:topsecret@unix/:./%s.iproto'):format('instance_001'),
    ('replicator:topsecret@unix/:./%s.iproto'):format('instance_002'),
    ('replicator:topsecret@unix/:./%s.iproto'):format('instance_003'),
}

local function safe_mkdir(dir)
    if not fio.path.exists(dir) then
        fio.mkdir(dir)
    end
end

safe_mkdir(wal_dir)
safe_mkdir(memtx_dir)

box.cfg({
    wal_dir = wal_dir,
    memtx_dir = memtx_dir,
    listen = listen,
    replication = replication,
})
```

Wait for 30 seconds to observe the crash:

```
2023-05-19 19:49:11.386 [12428] main/103/repro.lua I> connecting to 3 replicas
2023-05-19 19:49:11.386 [12428] main/111/applier/replicator@unix/:./instance_002.iproto I> can't connect to master
2023-05-19 19:49:11.386 [12428] main/111/applier/replicator@unix/:./instance_002.iproto sio.c:209 E> SocketError: connect to unix/:./instance_002.iproto, called on fd 24, aka unix/:(socket): No such file or directory
2023-05-19 19:49:11.386 [12428] main/111/applier/replicator@unix/:./instance_002.iproto I> will retry every 1.00 second
2023-05-19 19:49:11.387 [12428] main/112/applier/replicator@unix/:./instance_003.iproto I> can't connect to master
2023-05-19 19:49:11.387 [12428] main/112/applier/replicator@unix/:./instance_003.iproto sio.c:209 E> SocketError: connect to unix/:./instance_003.iproto, called on fd 24, aka unix/:(socket): No such file or directory
2023-05-19 19:49:11.387 [12428] main/112/applier/replicator@unix/:./instance_003.iproto I> will retry every 1.00 second
2023-05-19 19:49:11.388 [12428] main/110/applier/replicator@unix/:./instance_001.iproto I> remote master 6caa5220-8e9c-47ba-8b85-c9a90c5c1cd7 at unix/:./instance_001.iproto running Tarantool 3.0.0
2023-05-19 19:49:41.386 [12428] main/103/repro.lua C> failed to connect to 2 out of 3 replicas
tarantool: ./src/box/applier.cc:2720: void applier_pause(applier*): Assertion `!applier->is_paused' failed.
Aborted (core dumped)
```

Backtrace:

```c
#0  0x00007f25db86051c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f25db811f02 in raise () from /lib64/libc.so.6
#2  0x00007f25db7fc472 in abort () from /lib64/libc.so.6
#3  0x00007f25db7fc395 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007f25db80ae52 in __assert_fail () from /lib64/libc.so.6
#5  0x000055a92c0241b9 in applier_pause (applier=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/applier.cc:2720
#6  0x000055a92c0139f0 in applier_on_connect_f (trigger=0x7f25d91ff2e0, event=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/replication.cc:913
#7  0x000055a92c1808d6 in trigger_run_list (list=0x7f25d317fe20, event=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/trigger.cc:119
#8  0x000055a92c1809bb in trigger_run (list=0x55a92e635a38, event=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/trigger.cc:152
#9  0x000055a92c018db4 in trigger_run_xc (list=0x55a92e635a38, event=0x55a92e635440) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/trigger.h:173
#10 0x000055a92c01ae2a in applier_set_state (applier=0x55a92e635440, state=APPLIER_OFF) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/applier.cc:83
#11 0x000055a92c0233b1 in applier_disconnect (applier=0x55a92e635440, state=APPLIER_OFF) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/applier.cc:2445
#12 0x000055a92c023627 in applier_f(typedef __va_list_tag __va_list_tag *) (ap=0x7f25d9011168) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/box/applier.cc:2511
#13 0x000055a92bec60cd in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=0x55a92c0233fa <applier_f(typedef __va_list_tag __va_list_tag *)>, ap=0x7f25d9011168)
    at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/fiber.h:1233
#14 0x000055a92c158c54 in fiber_loop (data=0x0) at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/src/lib/core/fiber.c:998
#15 0x000055a92c2eb0ff in coro_init () at /usr/src/debug/dev-db/tarantool-9999/tarantool-9999/third_party/coro/coro.c:108
```

The failed `assert()` is on line 2720:

https://github.com/tarantool/tarantool/blob/96706b7b7e860f23ee59913e347f9b5fd306b662/src/box/applier.cc#L2715-L2724

### PR DESCRIPTION
**Pull request by sergepetrenko**
Clear applier on_state triggers before stopping appliers due to configuration failure in replicaset_connect().

This is needed to prevent triggers from running during applier_stop(), when cleaning up after a configuration error.

Closes #8675

NO_CHANGELOG=wasn't released
NO_DOC=bugfix

### CODE REVIEW

File: test/replication-luatest/gh_8675_applier_pause_assert_test.lua [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+                    nil, 'Exit without a crash')
+end
+
+g.test_crash_on_reconfiguration_failure = function(cg)
+    cg.server.box_cfg.replication = {
+        server.build_listen_uri('nonexistent', cg.replica_set.id),
+    }
+    cg.server:start{wait_until_ready = false}
+    assert_normal_exit(cg.server)
+    cg.server.box_cfg.replication = {
```
Comment (Serpentian) [inline test/replication-luatest/gh_8675_applier_pause_assert_test.lua:52]: These tests seems independent from each other and test different assertions. Why do we place it in one function? I suppose, we should apply the following diff here:

```diff
diff --git a/test/replication-luatest/gh_8675_applier_pause_assert_test.lua b/test/replication-luatest/gh_8675_applier_pause_assert_test.lua
index 0daaf06a4..a42e9f793 100644
--- a/test/replication-luatest/gh_8675_applier_pause_assert_test.lua
+++ b/test/replication-luatest/gh_8675_applier_pause_assert_test.lua
@@ -14,7 +14,7 @@ local set_log_before_cfg = [[
     require('log').cfg{log = logfile}
 ]]
 
-g.before_each(function(cg)
+g.before_all(function(cg)
     cg.replica_set = replica_set:new{}
     cg.server = cg.replica_set:build_and_add_server{
         alias = 'server',
@@ -26,7 +26,7 @@ g.before_each(function(cg)
     }
 end)
 
-g.after_each(function(cg)
+g.after_all(function(cg)
     cg.replica_set:drop()
 end)
 
@@ -49,6 +49,9 @@ g.test_crash_on_reconfiguration_failure = function(cg)
     }
     cg.server:start{wait_until_ready = false}
     assert_normal_exit(cg.server)
+end
+
+g.test_other = function(cg)
     cg.server.box_cfg.replication = {
         server.build_listen_uri(cg.server.alias, cg.replica_set.id),
         server.build_listen_uri('nonexistent', cg.replica_set.id),

```

This way the test won't stop on failing assertion `fiber() == applier->fiber` and will test `!applier->is_paused` too, if smth goes wrong.

**Review by Serpentian — APPROVED** [review]
Thanks for the patch. Everything looks great except one minor comment. It's up to you to fix it or not. LGTM

File: test/replication-luatest/gh_8675_applier_pause_assert_test.lua (hunk 1 above)
Comment (sergepetrenko) [reply test/replication-luatest/gh_8675_applier_pause_assert_test.lua:52]: Thanks for paying attention!
Applied the following diff. I didn't touch the `before/after_each`, because if something goes wrong the server might not stop after the first test.
```diff
diff --git a/test/replication-luatest/gh_8675_applier_pause_assert_test.lua b/test/replication-luatest/gh_8675_applier_pause_assert_test.lua
index 0daaf06a4..f07da4a58 100644
--- a/test/replication-luatest/gh_8675_applier_pause_assert_test.lua
+++ b/test/replication-luatest/gh_8675_applier_pause_assert_test.lua
@@ -43,12 +43,15 @@ local function assert_normal_exit(server)
                     nil, 'Exit without a crash')
 end
 
-g.test_crash_on_reconfiguration_failure = function(cg)
+g.test_crash_without_self = function(cg)
     cg.server.box_cfg.replication = {
         server.build_listen_uri('nonexistent', cg.replica_set.id),
     }
     cg.server:start{wait_until_ready = false}
     assert_normal_exit(cg.server)
+end
+
+g.test_crash_with_self = function(cg)
     cg.server.box_cfg.replication = {
         server.build_listen_uri(cg.server.alias, cg.replica_set.id),
         server.build_listen_uri('nonexistent', cg.replica_set.id),
```

File: src/box/replication.cc [hunk 2]
```diff
@@ -1055,8 +1055,11 @@ replicaset_connect(const struct uri_set *uris,
 	}
 	int count = 0;
 	struct applier *appliers[VCLOCK_MAX] = {};
+	/* Memory for on_state triggers registered in appliers */
+	struct applier_on_connect triggers[VCLOCK_MAX];
 	auto appliers_guard = make_scoped_guard([&]{
 		for (int i = 0; i < count; i++) {
+			trigger_clear(&triggers[i].base);
```
Comment (Gerold103) [inline src/box/replication.cc:1062]: If `applier_new()` a few lines below outside of the guard will raise an exception, then the guard will try to clear triggers which were not created yet, i.e. they contain garbage pointers right now.

Comment (sergepetrenko) [reply src/box/replication.cc:1062]: Yes, thanks for noticing!

I tried rearranging the code so that `trigger_clear` works correctly in this guard, but it turned out too bulky:
<details><summary>diff attempt</summary>

```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index 76d4eee78..7db8b1f24 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1065,23 +1065,6 @@ replicaset_connect(const struct uri_set *uris,
 			applier_delete(applier);
 		}
 	});
-	for (; count < uris->uri_count; count++)
-		appliers[count] = applier_new(&uris->uris[count]);
-
-	say_info("connecting to %d replicas", count);
-
-	if (!connect_quorum) {
-		/*
-		 * Enter orphan mode on configuration change and
-		 *
-		 * only leave it when we manage to sync with
-		 * replicaset_quorum instances. Don't change
-		 * title though, it should be 'loading' during
-		 * local recovery.
-		 */
-		box_do_set_orphan(true);
-	}
-
 	/*
 	 * Simultaneously connect to remote peers to receive their UUIDs
 	 * and fill the resulting set:
@@ -1101,21 +1084,36 @@ replicaset_connect(const struct uri_set *uris,
 	state.connected = state.failed = 0;
 	fiber_cond_create(&state.wakeup);
 
-	double timeout = replication_connect_timeout;
-
-	/* Add triggers and start simulations connection to remote peers */
-	for (int i = 0; i < count; i++) {
-		struct applier *applier = appliers[i];
-		struct applier_on_connect *trigger = &triggers[i];
+	for (; count < uris->uri_count; count++) {
+		appliers[count] = applier_new(&uris->uris[count]);
+		struct applier_on_connect *trigger = &triggers[count];
 		/* Register a trigger to wake us up when peer is connected */
 		trigger_create(&trigger->base, applier_on_connect_f, NULL, NULL);
 		trigger->state = &state;
 		trigger->seen_state = APPLIER_CONNECT;
-		trigger_add(&applier->on_state, &trigger->base);
-		/* Start background connection */
-		applier_start(applier);
+		trigger_add(&appliers[count]->on_state, &trigger->base);
 	}
 
+	say_info("connecting to %d replicas", count);
+
+	if (!connect_quorum) {
+		/*
+		 * Enter orphan mode on configuration change and
+		 *
+		 * only leave it when we manage to sync with
+		 * replicaset_quorum instances. Don't change
+		 * title though, it should be 'loading' during
+		 * local recovery.
+		 */
+		box_do_set_orphan(true);
+	}
+
+	double timeout = replication_connect_timeout;
+
+	/* Start simulations connection to remote peers */
+	for (int i = 0; i < count; i++)
+		applier_start(appliers[i]);
+
 	while (!replicaset_is_connected(&state, appliers, count,
 					connect_quorum)) {
 		double wait_start = ev_monotonic_now(loop());
```
</details>

So instead I use 2 guards now. I tried to avoid that in initial patch, and reuse the applier guard, but it's not ok to clear an uninitialized trigger, as you pointed out.
<details><summary>incremental diff</summary>

```diff
diff --git a/src/box/replication.cc b/src/box/replication.cc
index 76d4eee78..feb36c957 100644
--- a/src/box/replication.cc
+++ b/src/box/replication.cc
@@ -1055,11 +1055,8 @@ replicaset_connect(const struct uri_set *uris,
        }
        int count = 0;
        struct applier *appliers[VCLOCK_MAX] = {};
-       /* Memory for on_state triggers registered in appliers */
-       struct applier_on_connect triggers[VCLOCK_MAX];
        auto appliers_guard = make_scoped_guard([&]{
                for (int i = 0; i < count; i++) {
-                       trigger_clear(&triggers[i].base);
                        struct applier *applier = appliers[i];
                        applier_stop(applier);
                        applier_delete(applier);
@@ -1097,6 +1094,9 @@ replicaset_connect(const struct uri_set *uris,
         *   for duplicates, fill the result set, return.
         */
 
+       /* Memory for on_state triggers registered in appliers */
+       struct applier_on_connect triggers[VCLOCK_MAX];
+
        struct replicaset_connect_state state;
        state.connected = state.failed = 0;
        fiber_cond_create(&state.wakeup);
@@ -1116,6 +1116,16 @@ replicaset_connect(const struct uri_set *uris,
                applier_start(applier);
        }
 
+       /*
+        * Guards are run in the order reverse to the order of their
+        * initialization. So triggers_guard will run before appliers_guard.
+        */
+       auto triggers_guard = make_scoped_guard([&]{
+               for (int i = 0; i < count; i++) {
+                       struct applier_on_connect *trigger = &triggers[i];
+                       trigger_clear(&trigger->base);
+               }
+       });
        while (!replicaset_is_connected(&state, appliers, count,
                                        connect_quorum)) {
                double wait_start = ev_monotonic_now(loop());
@@ -1148,6 +1158,7 @@ replicaset_connect(const struct uri_set *uris,
                if (applier->state != APPLIER_CONNECTED)
                        applier_stop(applier);
        }
+       triggers_guard.is_active = false;
 
        /* Now all the appliers are connected, update the replica set. */
        replicaset_update(appliers, count, keep_connect);
```
</details>

Comment (Gerold103) [reply src/box/replication.cc]: An alternative was to create them with `NULL` functions right after the declaration. And then destroy + create with the actual callback later. So the triggers would never be in an invalid state. But I am fine with the present solution too.

**Review by Gerold103 — APPROVED** [review]
Thanks for the patch!
