### PR TITLE
main: fix wrong log level printed during first `box.cfg{}`

### LINKED ISSUE #8287: Wrong log level printed to the log during first `box.cfg{}`
**Bug description**

When log level is set as a string during first `box.cfg{}` call, it is printed as `log level 0`.
This affects 2.11 and newer, in older versions nothing is printed at all in such case.

```
Tarantool 2.11.0-entrypoint-981-gcba4e20aa
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-10.2.1
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/iverbin/git/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/iverbin/git/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
```

**Steps to reproduce**

```
$ tarantool
Tarantool 2.11.0-entrypoint-981-gcba4e20aa
type 'help' for interactive help
tarantool> box.cfg{log_level='info'}
2023-02-09 19:13:20.773 [666] main/103/interactive I> Tarantool 2.11.0-entrypoint-981-gcba4e20aa Linux-x86_64-Debug
2023-02-09 19:13:20.773 [666] main/103/interactive I> log level 0
2023-02-09 19:13:20.773 [666] main/103/interactive I> wal/engine cleanup is paused
-- skipped --
```

**Actual behavior**

The log level is applied correctly, but it is reported as 0.

**Expected behavior**
```
2023-02-09 19:13:20.773 [666] main/103/interactive I> log level 5
```
or
```
2023-02-09 19:13:20.773 [666] main/103/interactive I> log level "info"
```
or
```
2023-02-09 19:13:20.773 [666] main/103/interactive I> log level 5 (INFO)
```

### PR DESCRIPTION
**Pull request by Gumix**
The `log_level` configuration parameter can be set as a number or a string. When it is a string, `cfg_geti()` returns 0.

Closes #8287

### CODE REVIEW

File: src/main.cc [hunk 1]
```diff
@@ -503,7 +503,10 @@ load_cfg(void)
 	 */
 	say_info("%s %s %s", tarantool_package(), tarantool_version(),
 		 BUILD_INFO);
-	say_info("log level %i", cfg_geti("log_level"));
+	if (cfg_isnumber("log_level"))
+		say_info("log level %i", cfg_geti("log_level"));
+	else
+		say_info("log level \"%s\"", cfg_gets("log_level"));
```
Comment (nshy) [inline src/main.cc:509]: I guess we'd better put this log in log.lua. Say after `say_logger_init` call. AFAIK currently we handle different types for log options on Lua level. So let's keep it there.

**Review by nshy — CHANGES_REQUESTED** [review]

File: src/main.cc (hunk 1 above)
Comment (Gumix) [reply src/main.cc]: Changed to `box_say_log_level()`

File: src/box/box.cc [hunk 2]
```diff
@@ -1535,6 +1535,15 @@ box_init_say()
 	return 0;
 }
 
+int
+box_say_log_level()
+{
+	if (luaT_dostring(tarantool_L,
+			  "require('log').box_api.say_log_level()") != 0)
```
Comment (nshy) [inline src/box/box.cc:1542]: Donno. I would just use something like `"require('log').info(require('log').cfg.level)"`. To me introducing the function only for a log line is too much.

**Review by nshy — CHANGES_REQUESTED** [review]

File: src/lua/log.lua [hunk 3]
```diff
@@ -99,20 +99,26 @@ local fmt_str2num = {
...
+local log_level_str2num = {}
+
+for kl, kb in pairs(log_level_num2str) do
+    log_level_str2num[kb] = kl
+end
+
 local function log_level_list()
     local keyset = {}
-    for k in pairs(log_level_keys) do
+    for k in pairs(log_level_str2num) do
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/lua/log.lua:121]: It won't work, because `log_level_num2str` contains an element with `0` index, which is skipped by `ipairs()`.

File: src/lua/log.lua [hunk 4]
```diff
@@ -99,20 +99,26 @@ local fmt_str2num = {
...
+    [ffi.C.S_INFO]     = 'info',
+    [ffi.C.S_VERBOSE]  = 'verbose',
+    [ffi.C.S_DEBUG]    = 'debug',
 }
 
+local log_level_str2num = {}
+
+for kl, kb in pairs(log_level_num2str) do
+    log_level_str2num[kb] = kl
+end
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/lua/log.lua:117]: Done

File: src/main.cc [hunk 5]
```diff
@@ -503,7 +503,10 @@ load_cfg(void)
 	 */
 	say_info("%s %s %s", tarantool_package(), tarantool_version(),
 		 BUILD_INFO);
-	say_info("log level %i", cfg_geti("log_level"));
+	if (box_say_log_level() != 0) {
```
Comment (locker) [inline src/main.cc:506]: I don't understand why we need to invoke a Lua function to get the actual log level. Can't we just print the value of the [`log_level`](https://github.com/tarantool/tarantool/blob/6a3e31333d3a5a10f44da6375e8bae6b1c7f88d8/src/lib/core/say.h#L72) variable, which is defined in C?

Comment (Gumix) [reply src/main.cc:506]: That variable is not very reliable, because:
https://github.com/tarantool/tarantool/blob/6a3e31333d3a5a10f44da6375e8bae6b1c7f88d8/src/lib/core/say.c#L53-L58
That is, currently it can be different from the log_level config option in 2 cases:
1. flightrec log level overrided it;
2. `box.cfg{log_level=1, log_modules={tarantool=2}}`
set log_level variable to 2 (I guess it's ok to print is as `2` in this case).

Comment (locker) [reply src/main.cc:506]: Can we add `say_get_log_level()` function that would return `log_default->level` then? This should be much easier than calling a Lua function from C code.

File: src/main.cc [hunk 6]
```diff
@@ -503,7 +503,10 @@ load_cfg(void)
...
+		diag_log();
+		exit(EXIT_FAILURE);
+	}
```
[the remark this answers is not in the document]
Comment (Gumix) [reply src/main.cc]: Removed this code.

File: src/box/box.cc (hunk 2 above)
Comment (Gumix) [reply src/box/box.cc]: Removed this code.

File: src/main.cc (hunk 5 above)
Comment (Gumix) [reply src/main.cc]: Done.

**Review by locker — APPROVED** [review]

**Review by nshy — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.11.
