### PR TITLE
test: improve `vinyl-luatest/select_consistency_test.lua`

### LINKED ISSUE #11046: vinyl-luatest/select_consistency_test.lua:200: Assertion failed: 4 >= 5
**Bug description**

* OS: Linux
* Architecture: amd64

**Steps to reproduce**

Execute `debug_asan_clang` on a branch with enabled "long" tests, see patch in https://github.com/tarantool/tarantool/pull/11043

**Actual behavior**

```
 [071] vinyl-luatest/select_consistency_test.lua                     [ fail ]
[071] Test failed! Output from reject file /tmp/t/rejects/vinyl-luatest/select_consistency.reject:
[071] Tarantool version is 3.4.0-entrypoint-80-g66b7c971ce1
[071] TAP version 13
[071] 1..2
[071] # Started on Fri Jan 24 11:18:52 2025
[071] # Starting group: vinyl.select_consistency.defer_deletes:false
[071] not ok 1	vinyl.select_consistency.defer_deletes:false.test_select_consistency
[071] #   ...tarantool/test/vinyl-luatest/select_consistency_test.lua:200: Assertion failed: 4 >= 5
[071] #   stack traceback:
[071] #   	...tarantool/test/vinyl-luatest/select_consistency_test.lua:200: in function 'retrying'
[071] #   	...tarantool/test/vinyl-luatest/select_consistency_test.lua:199: in function <...tarantool/test/vinyl-luatest/select_consistency_test.lua:66>
[071] #   	...tarantool/test/vinyl-luatest/select_consistency_test.lua:66: in function 'run_test'
[071] #   	...tarantool/test/vinyl-luatest/select_consistency_test.lua:212: in function 'vinyl.select_consistency.defer_deletes:false.test_select_consistency'
[071] #   artifacts:
[071] #   	master -> /tmp/t/071_vinyl-luatest/artifacts/master-W2l5fcDS3wuv
[071] # Starting group: vinyl.select_consistency.defer_deletes:true
[071] ok     2	vinyl.select_consistency.defer_deletes:true.test_select_consistency
[071] # Ran 2 tests in 308.450 seconds, 1 succeeded, 1 failed
[071] 
[071] [test-run server "luatest_server"] Last 15 lines of the log file /tmp/t/071_vinyl-luatest/select_consistency_test.log:
[071] started logging into a pipe, SIGHUP log rotation disabled
[071] Test "vinyl-luatest/select_consistency_test.lua", conf: "None"
[071] 	failed, rerunning ...
```

`debug_asan_clang`: https://github.com/tarantool/tarantool/actions/runs/12948188871/job/36116313731?pr=11043
Full log: [logs_33472080951.zip](https://github.com/user-attachments/files/18535715/logs_33472080951.zip)

**Expected behavior**

no assertion is triggered

### PR DESCRIPTION
**Pull request by locker**
This PR makes the `vinyl-luatest/select_consistency_test.lua` faster and more thorough at the same time. It also drops the legacy diff test `vinyl/select_consistency.test.lua`, because the new test covers all checks performed by the old test and more.

Closes #11046

**DO NOT MERGE** before #11148, because the updated test fails frequently because of the bugs fixed by that PR.

### CODE REVIEW

File: test/vinyl-luatest/select_consistency_test.lua [hunk 1]
```diff
@@ -111,24 +144,50 @@ g.test_select_consistency = function(cg)
                             })
                         end
                     end
+                    box.commit()
+                    log.info('commit')
```
Comment (nshy) [inline test/vinyl-luatest/select_consistency_test.lua:148]: Looks like it is worth to log commit begin also as it yields.

File: test/vinyl-luatest/select_consistency_test.lua [hunk 2]
```diff
@@ -139,80 +198,63 @@ g.test_select_consistency = function(cg)
...
-                    table.insert(failed, {
-                        iterator = iterator,
-                        idx1 = idx1,
-                        idx2 = idx2,
-                        res1 = res1,
-                        res2 = res2,
-                    })
-                    error('consistency check failed')
+                    log.error(err)
+                    error(err)
```
Comment (nshy) [inline test/vinyl-luatest/select_consistency_test.lua:209]: May be it is worth to stop the test (setting `stop` to true) on read or write error.

File: test/vinyl-luatest/select_consistency_test.lua [hunk 3]
```diff
@@ -139,80 +198,63 @@ g.test_select_consistency = function(cg)
...
-            for _ = 1, WRITE_FIBERS do
-                t.assert_equals(write_fiber_ch:get(5), true)
-            end
-            t.assert_equals(failed, {})
         end)
     end
     run_test()
-    -- Restart and try again.
-    cg.server:restart()
-    run_test()
```
Comment (nshy) [inline test/vinyl-luatest/select_consistency_test.lua:215]: Looks like we can make test more fuzzy if we:
- add random yields when iterating over indexes in `check_select`.
- add random yields between write operations.

**Review by nshy — APPROVED** [review]

File: test/vinyl-luatest/select_consistency_test.lua (hunk 1 above)
Comment (locker) [reply test/vinyl-luatest/select_consistency_test.lua:156]: Makes sense. Added.

<details><summary>diff</summary>

```diff
diff --git a/test/vinyl-luatest/select_consistency_test.lua b/test/vinyl-luatest/select_consistency_test.lua
index 3a5ec7414b7d..cdd73ce233c6 100644
--- a/test/vinyl-luatest/select_consistency_test.lua
+++ b/test/vinyl-luatest/select_consistency_test.lua
@@ -144,8 +144,9 @@ g.test_select_consistency = function(cg)
                             })
                         end
                     end
-                    box.commit()
                     log.info('commit')
+                    box.commit()
+                    log.info('confirm')
                 end)
                 if not ok then
                     box.rollback()
@@ -180,8 +181,8 @@ g.test_select_consistency = function(cg)
                         log.info('read %s', str_tuple(tuple))
                         table.insert(res2, tuple)
                     end
-                    box.commit()
                     log.info('commit')
+                    box.commit()
                 end)
                 if not ok then
                     box.rollback()
```

</details>

File: test/vinyl-luatest/select_consistency_test.lua (hunk 2 above)
Comment (locker) [reply test/vinyl-luatest/select_consistency_test.lua:222]: Test is limited in time by just 5 seconds. Optimizing the error case doesn't seem to be justified.

File: test/vinyl-luatest/select_consistency_test.lua (hunk 3 above)
Comment (locker) [reply test/vinyl-luatest/select_consistency_test.lua:215]: Good idea! Done.

<details><summary>diff</summary>

```diff
diff --git a/test/vinyl-luatest/select_consistency_test.lua b/test/vinyl-luatest/select_consistency_test.lua
index cdd73ce233c6..b7af179fc200 100644
--- a/test/vinyl-luatest/select_consistency_test.lua
+++ b/test/vinyl-luatest/select_consistency_test.lua
@@ -72,6 +72,7 @@ g.test_select_consistency = function(cg)
             math.randomseed(os.time())
             box.stat.reset()
 
+            local YIELD_PROBABILITY = 0.2
             local WRITE_FIBERS = 20
             local READ_FIBERS = 5
             local MAX_TX_STMTS = 10
@@ -109,11 +110,18 @@ g.test_select_consistency = function(cg)
                 return variants[math.random(#variants)]
             end
 
+            local function inject_yield()
+                if math.random(100) / 100 < YIELD_PROBABILITY then
+                    fiber.yield()
+                end
+            end
+
             local function do_write()
                 local ok, err = pcall(function()
                     local txn_isolation = pick_txn_isolation()
                     log.info('begin %s', txn_isolation)
                     box.begin{txn_isolation = txn_isolation}
+                    inject_yield()
                     for _ = 1, math.random(MAX_TX_STMTS) do
                         local op = math.random(4)
                         if op == 1 then
@@ -143,6 +151,7 @@ g.test_select_consistency = function(cg)
                                 {'=', 5, tuple[5]},
                             })
                         end
+                        inject_yield()
                     end
                     log.info('commit')
                     box.commit()
@@ -169,17 +178,20 @@ g.test_select_consistency = function(cg)
                     local txn_isolation = pick_txn_isolation()
                     log.info('begin %s', txn_isolation)
                     box.begin{txn_isolation = txn_isolation}
+                    inject_yield()
                     log.info('select %s %s from %s', iterator, key, idx1)
                     for _, tuple in s.index[idx1]:pairs(key, opts) do
                         tuple = tuple:totable()
                         log.info('read %s', str_tuple(tuple))
                         table.insert(res1, tuple)
+                        inject_yield()
                     end
                     log.info('select %s %s from %s', iterator, key, idx2)
                     for _, tuple in s.index[idx2]:pairs(key, opts) do
                         tuple = tuple:totable()
                         log.info('read %s', str_tuple(tuple))
                         table.insert(res2, tuple)
+                        inject_yield()
                     end
                     log.info('commit')
                     box.commit()
```

</details>

**Comment by locker** [comment]
- Enabled verbose logging to log all compaction actions.
- Reduced the target range size to make vinyl split ranges more intensively.

<details><summary>diff</summary>

```diff
diff --git a/test/vinyl-luatest/select_consistency_test.lua b/test/vinyl-luatest/select_consistency_test.lua
index b7af179fc200..6a54adbb6875 100644
--- a/test/vinyl-luatest/select_consistency_test.lua
+++ b/test/vinyl-luatest/select_consistency_test.lua
@@ -9,12 +9,13 @@ g.before_all(function(cg)
     cg.server = server:new({
         alias = 'master',
         box_cfg = {
+            log_level = 'verbose',
             vinyl_memory = 1024 * 1024,
             vinyl_cache = 512 * 1024,
             vinyl_run_count_per_level = 1,
             vinyl_run_size_ratio = 4,
             vinyl_page_size = 1024,
-            vinyl_range_size = 128 * 1024,
+            vinyl_range_size = 64 * 1024,
             vinyl_bloom_fpr = 0.1,
             vinyl_read_threads = 2,
             vinyl_write_threads = 4,
```

</details>

**Comment by locker** [comment]
Cherry-picked to 2.11, 3.2, 3.3.
