### PR TITLE
box: handle cancelling fiber waiting in wal queue

### LINKED ISSUE #11078: WAL rows order is messed up if fiber waiting for journal size threshold is cancelled
In particular this can happen on shutdown. The application can crash also as transaction commit/rollback order is also messed up. Оne example is https://github.com/tarantool/tarantool-ee/issues/1108 where the issue is originated.

Reproduction:

```lua
local fiber = require('fiber')
os.execute('rm -f *.snap *.xlog *.vylog')
box.cfg{log_level = 'warn', wal_queue_max_size = 100}
local s = box.schema.create_space('test')
s:create_index('pk')
-- Make journal queue size go beyond threshold.
box.error.injection.set('ERRINJ_WAL_DELAY', true)
fiber.create(function()
    s:insert({1, string.rep('a', 1000)})
end)
fiber.sleep(0.01)
fiber.create(function()
    -- This operation will wait on journal queue size.
    s:insert({2})
end)
fiber.sleep(0.01)
local f = fiber.new(function()
    -- This operation will wait on journal queue size too.
    box.begin()
    s:delete({2})
    s:insert({2})
    box.commit()
end)
fiber.sleep(0.01)
-- Wakeup second operation to write to WAL in incorrect order.
f:cancel()
box.error.injection.set('ERRINJ_WAL_DELAY', false)
fiber.sleep(0.01)
os.exit()
```

When we try to start again we got error on loading xlog:
```
{type: 'INSERT', replica_id: 1, lsn: 6, space_id: 512, index_id: 0, tuple: [2]}
2025-02-03 16:13:31.972 [639691] main/104/interactive index.cc:229 E> ER_TUPLE_FOUND: Duplicate key exists in unique index "pk" in space "test" with old tuple - [2] and new tuple - [2]
2025-02-03 16:13:31.972 [639691] main/104/interactive say.c:86 F> can't initialize storage: Duplicate key exi
```

### PR DESCRIPTION
**Pull request by nshy**
Currently if fiber waiting in wal queue is cancelled it will go on writing to all breaking queue order. So wal is corrupted so that even next Tarantool restart may fail. Unfortunately we cancel fibers on Tarantool shutdown so the issue may arise just buy terminating Tarantool instance.

Let's instead fail the cancelled request and all the newer request in the queue.

Work around is to disable wal queue by `box.cfg{wal_queue_max_size = 0}` so that only one write request can be in the queue.

Closes #11078

### CODE REVIEW

**Review by xuniq — APPROVED** [review]

File: src/box/journal.c [hunk 1]
```diff
@@ -94,36 +93,73 @@ journal_entry_fiber_wakeup_cb(struct journal_entry *entry)
...
+	stailq_add_tail_entry(&journal_queue.requests, entry, fifo);
+	assert(entry->fiber == NULL);
+	entry->fiber = fiber();
 	fiber_yield();
-	--journal_queue.waiter_count;
-	journal_queue_wakeup();
+	if (entry->is_complete) {
+		/* Already rolled back on cascade rollback. */
+		diag_set_journal_res(entry->res);
+	} else if (fiber_is_cancelled()) {
```
Comment (locker) [inline src/box/journal.c:122]: Can't we just ignore cancellation while waiting for the journal queue? AFAICS we ignore it while waiting for WAL, i.e. this fix makes the behavior of `box.commit()` inconsistent:

https://github.com/tarantool/tarantool/blob/413e4e2bb98cace8a4ed10b9d41043ffff4bc0ce/src/box/txn.c#L1192-L1193

Comment (nshy) [reply src/box/journal.c:122]: Discussed f2f. Our current vision is to make fibers cancellable, we have a related task #9721. Also we should not continue operation and finish fiber when fiber is cancelled because our waiting primitives may enter busy loop.

Mentioned this place in #9721.

File: src/box/journal.c [hunk 2]
```diff
@@ -94,36 +93,73 @@ journal_entry_fiber_wakeup_cb(struct journal_entry *entry)
...
 		return;
-	struct rlist *list = &journal_queue.waiters;
-	while (!rlist_empty(list))
-		fiber_wakeup(rlist_first_entry(list, struct fiber, state));
-	journal_queue_wait();
+	struct journal_entry *req;
+	stailq_foreach_entry(req, &journal_queue.requests, fifo)
+		fiber_wakeup(req->fiber);
+	/* Schedule after all fibers waiting in journal queue. */
+	fiber_sleep(0);
```
Comment (sergepetrenko) [inline src/box/journal.c:162]: Why is `fiber_sleep(0)` enough here? And why didn't you leave `journal_queue_wait()`?

**Review by sergepetrenko — CHANGES_REQUESTED** [review]
Thanks for the patch!

Just one question.

File: src/box/journal.c (hunk 2 above)
Comment (nshy) [reply src/box/journal.c:162]: `journal_queue_wait()` now takes request so it is not convenient to call it here.

`fiber_sleep(0)` is enough because it will be finished only on next event loop iteration. Above we wakeup all fibers waiting in the queue so they should be executed in current event loop iteration. So flush is correct.

Comment (locker) [reply src/box/journal.c:162]: But if another fiber is added during the current loop iteration, we may wait for it, too. This is probably not going to be a problem though, but still it looks confusing. Also, this change makes the comment to this function misleading.

Comment (locker) [reply src/box/journal.c:162]: Also, the fiber may be cancelled while sleeping, which isn't handled anyhow.

Comment (nshy) [reply src/box/journal.c:162]: > Also, the fiber may be cancelled while sleeping, which isn't handled anyhow.

This issue is already present.

Comment (sergepetrenko) [reply src/box/journal.c:162]: After giving it a second thought - `fiber_sleep(0)` doesn't break the only usage of `journal_queue_flush()` we have now. So I'm ok with it.

**Review by sergepetrenko — APPROVED** [review]

**Comment by nshy** [comment]
Fixed a few nits.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/journal.c b/src/box/journal.c
index b1064c9c93..fcfb492117 100644
--- a/src/box/journal.c
+++ b/src/box/journal.c
@@ -123,7 +123,7 @@ journal_queue_wait(struct journal_entry *entry)
                struct stailq rollback;
                stailq_cut_tail(&journal_queue.requests, &prev_entry->fifo,
                                &rollback);
-               /* Pop this entry. */
+               /* Pop this request. */
                VERIFY(stailq_shift_entry(&rollback,
                                          typeof(*entry), fifo) == entry);
                stailq_reverse(&rollback);
diff --git a/src/box/journal.h b/src/box/journal.h
index d77434266d..d70b861151 100644
--- a/src/box/journal.h
+++ b/src/box/journal.h
@@ -202,7 +202,7 @@ journal_queue_is_full(void)
 int
 journal_queue_wait(struct journal_entry *entry);

-/** Empty the queue by waking everyone in it up and put self to queue tail. */
+/** Flush journal queue. Next wal_sync() will sync flushed requests. */
 void
 journal_queue_flush(void);

diff --git a/test/box-luatest/gh_11078_wal_queue_fiber_cancel_test.lua b/test/box-lua>
index 85b1225f06..12daacc644 100644
--- a/test/box-luatest/gh_11078_wal_queue_fiber_cancel_test.lua
+++ b/test/box-luatest/gh_11078_wal_queue_fiber_cancel_test.lua
@@ -18,8 +18,8 @@ g.after_all(function(cg)
 end)

 g.after_each(function(cg)
-    box.error.injection.set('ERRINJ_WAL_DELAY', false)
     cg.server:exec(function()
+        box.error.injection.set('ERRINJ_WAL_DELAY', false)
         box.space.test:drop()
     end)
 end)
```

</details>
