### PR TITLE
Fix crash in space on_replace triggers.

### LINKED ISSUE #6920: Crash in on_replace triggers
#! /PATH_TO_TARANTOOL

os.execute("rm -rf *.xlog *.snap *.log *.vylog 51*")

box.cfg {}
s = box.schema.space.create('test')
_ = s:create_index('pk')
s:on_replace(function() end)
t = s:on_replace(function () s:format({{'a', 'unsigned'}}) end)
-- s:on_replace(function() s:on_replace(nil, t) end) This make this bug even worse
s:replace({1})

### PR DESCRIPTION
**Pull request by EvgenyMekhanik**
During ddl operations triggers of old space and new created space
are swapped. This leads to crash in case if this swap occurs from
space on_replace triggers. This patch banned all ddl operations
from on_replace triggers.

Closes #6920

### CODE REVIEW

File: src/box/txn.c [hunk 1]
```diff
@@ -447,6 +448,22 @@ txn_is_distributed(struct txn *txn)
...
+	 * Triggers see old_tuple and that tuple
+	 * must remain the same
+	 */
+	stmt->does_require_old_tuple = true;
+	txn->space_on_replace_triggers_depth++;
+	int rc = trigger_run(&stmt->space->on_replace, txn);
+	txn->space_on_replace_triggers_depth--;
+	return rc;
+}
+
```
Comment (locker) [inline src/box/txn.c:466]: I don't see much point in this new function, cause it's called only once. Let's inline it. Same comment for `txn_check_on_replace_triggers_depth` if you manage to put it in `on_replace_dd_system_space`.

File: test/box-luatest/gh_6920_crash_in_on_replace_triggers_test.lua [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+        local s = box.schema.space.create('test')
+        local _ = s:create_index('pk')
+        s:on_replace(function() end)
+        s:on_replace(function () s:format({{'a', 'unsigned'}}) end)
+        t.assert_error_msg_content_equals(
+            "Space on_replace triggers does not support ddl operations",
+            function() return s:replace({1}) end
+        )
+    end)
+end
```
Comment (locker) [inline test/box-luatest/gh_6920_crash_in_on_replace_triggers_test.lua:26]: I don't think we need this test - it's already checked by the existing tests you update in this patch. Let's drop it.

File: test/box/on_replace.result [hunk 3]
```diff
@@ -474,75 +474,67 @@ t = s:on_replace(function () box.schema.space.create('some_space') end)
...
-- [1, 2]
+- error: Space on_replace triggers does not support ddl operations
 ...
 t = s:on_replace(function () s:format({{'a', 'unsigned'}, {'b', 'unsigned'}}) end, t)
 ---
 ...
 s:replace({2, 3})
 ---
-- [2, 3]
+- error: Space on_replace triggers does not support ddl operations
```
Comment (locker) [inline test/box/on_replace.result:484]: Should be "triggers do not support" or "trigger does not support".

**Review by locker — CHANGES_REQUESTED** [review]

File: src/box/txn.c (hunk 1 above)
Comment (EvgenyMekhanik) [reply src/box/txn.c:466]: fixed

File: test/box-luatest/gh_6920_crash_in_on_replace_triggers_test.lua (hunk 2 above)
Comment (EvgenyMekhanik) [reply test/box-luatest/gh_6920_crash_in_on_replace_triggers_test.lua:26]: fixed

File: changelogs/unreleased/gh-6920-fix-crash-in-on-replace-triggers.md [hunk 4]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
+
+* Ban ddl operations from space on_replace triggers, since
+  they can lead to crash of tarantool.
```
[the remark this answers is not in the document]
Comment (EvgenyMekhanik) [reply changelogs/unreleased/gh-6920-fix-crash-in-on-replace-triggers.md]: Fixed, but are you sure that we can close ticket? There is at least one more case which leads to crash: deleting trigger from on_replace trigger.

[the remark this answers is not in the document]
Comment (locker) [reply changelogs/unreleased/gh-6920-fix-crash-in-on-replace-triggers.md]: Yes. Let's close it. We can open another one, specifically for that issue.

File: changelogs/unreleased/gh-6920-fix-crash-in-on-replace-triggers.md [hunk 5]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
+
+* Ban ddl operations from space on_replace triggers, since
```
Comment (locker) [inline changelogs/unreleased/gh-6920-fix-crash-in-on-replace-triggers.md:3]: Nit:
 - [Release notes should be Past Simple](https://www.tarantool.io/en/doc/latest/contributing/release_notes/).
 - DDL is an abbreviation so it should be in CAPs.
 - 'from' doesn't sound right here. Should be 'in'.

```
* Banned DDL operations in space on_replace triggers, since they could lead
  to a crash (gh-6920).
```

File: src/box/schema.cc [hunk 6]
```diff
@@ -260,6 +261,11 @@ on_replace_dd_system_space(struct trigger *trigger, void *event)
 {
 	(void) trigger;
 	struct txn *txn = (struct txn *) event;
+	if (txn->space_on_replace_triggers_depth > 1) {
+		diag_set(ClientError, ER_UNSUPPORTED,
+			 "Space on_replace trigger", "ddl operations");
```
Comment (locker) [inline src/box/schema.cc:266]: Nit: s/ddl/DDL

File: src/box/txn.c [hunk 7]
```diff
@@ -503,8 +504,12 @@ txn_commit_stmt(struct txn *txn, struct request *request)
 			 */
 			stmt->does_require_old_tuple = true;
 
-			if(trigger_run(&stmt->space->on_replace, txn) != 0)
+			txn->space_on_replace_triggers_depth++;
+			if (trigger_run(&stmt->space->on_replace, txn) != 0) {
+				txn->space_on_replace_triggers_depth--;
 				goto fail;
+			}
+			txn->space_on_replace_triggers_depth--;
```
Comment (locker) [inline src/box/txn.c:512]: Nit: better rewrite like this:

```C
			txn->space_on_replace_triggers_depth++;
			int rc = trigger_run(&stmt->space->on_replace, txn);
			txn->space_on_replace_triggers_depth--;
			if (rc != 0)
				goto fail;
```

**Review by locker — CHANGES_REQUESTED** [review]

File: changelogs/unreleased/gh-6920-fix-crash-in-on-replace-triggers.md (hunk 5 above)
Comment (EvgenyMekhanik) [reply changelogs/unreleased/gh-6920-fix-crash-in-on-replace-triggers.md]: Fixed

File: src/box/schema.cc (hunk 6 above)
Comment (EvgenyMekhanik) [reply src/box/schema.cc]: Fixed

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked for 2.8.
