### PR TITLE
compat: add is_new and is_old to options

### LINKED ISSUE #8807: Comparing of compat option to old/new works unexpectedly
```
tarantool> require('compat').yaml_pretty_multiline == 'old'
---
- false
...

tarantool> require('compat').yaml_pretty_multiline == 'new'
---
- false
...

tarantool> require('compat').yaml_pretty_multiline == 'default'
---
- false
...

tarantool> require('compat').yaml_pretty_multiline.current == 'old'
---
- false
...

tarantool> require('compat').yaml_pretty_multiline.current == 'new'
---
- false
...

tarantool> require('compat').yaml_pretty_multiline.current == 'default'
---
- true
...
```

That is, the correct way to figure out whether the option is set to 'new' is:

```Lua
if compat.yaml_pretty_multiline.current == 'new' or
        (compat.yaml_pretty_multiline.current == 'default' and
         compat.yaml_pretty_multiline.default == 'new') then
    ...
end
```

This is confusing and inconvenient. It should be possible to compare the compat option value to 'old' and 'new' directly.

### PR DESCRIPTION
**Pull request by Lord-KA**
It used to be somewhat complicated to check the effective value of a compat option, because `<option_name>.current` could contain 'default' state.
This patch introduces helper functions that take care of that.

The following alternatives were considered:
* `compat.<option_name>.effective` - it is excessive in the presence if `current` and `default`, and is visible in serialization
* `compat.<option_name>.get()` - while it is a function, it does only half of the work required, user still has to compare result to 'new'

Closes #8807

@TarantoolBot document
Title: Add `:is_new/old()` helpers to tarantool.compat options

`compat.<option_name>.current` can be 'new', 'old' or 'default', thus when it is default there must be an additional check if `compat.<option_name>.default` is 'new'. It is handier to have a helper to deal with that instead of complicated `if`:
* check if effective value is 'new' before the patch: 
   ```lua
   if compat.<option_name>.current == 'new'
       or (compat.<option_name>.current == 'default' and
             compat.<option_name>.default == 'new') then 
      ...
  end 
   ```
* after the patch: 
   ```lua
   if compat.<option_name>:is_new() then
      ...
   end 
   ```

Please update [tutorial on using compat], maybe add an example to [Listing options details].

[tutorial on using compat]: https://www.tarantool.io/en/doc/latest/reference/reference_lua/compat/compat_tutorial/
[Listing options details]: https://www.tarantool.io/en/doc/latest/reference/reference_lua/compat/compat_tutorial/#listing-options-details

### CODE REVIEW

File: test/app-luatest/gh_7000_compat_module_test.lua [hunk 1]
```diff
@@ -216,6 +216,26 @@ g.test_help = function()
     t.assert(compat.help())
 end
 
+g.test_is_new_is_old = function()
+    for _, option_def in pairs(definitions) do
+        local name = option_def.name
+        t.assert(compat[name])
+
+        compat[name] = 'new'
```
Comment (Totktonada) [inline test/app-luatest/gh_7000_compat_module_test.lua:224]: I think we shouldn't change compat options in the main testing code, see #8033.

File: changelogs/unreleased/gh-8807-compat-is-new-old.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+## feature/lua
+
+* Introduced `:is_new()` and `:is_old()` helpers to tarantool.compat options
+  for easier effective value checks (gh-8807).
```
Comment (andreyaksenov) [inline changelogs/unreleased/gh-8807-compat-is-new-old.md:4]:
```suggestion
* Added the `:is_new()` and `:is_old()` helpers to `compat` options
  to simplify effective value checks (gh-8807).
```

**Review by andreyaksenov — APPROVED** [review]

File: test/app-luatest/gh_7000_compat_module_test.lua (hunk 1 above)
Comment (Lord-KA) [reply test/app-luatest/gh_7000_compat_module_test.lua:224]: Similar to `test_new_index()`, I switch only dummy options defined in `definitions`, so it is safe.

**Review by Totktonada — APPROVED** [review]
No objections from my side. LGTM.

File: src/lua/compat.lua [hunk 3]
```diff
@@ -446,6 +446,28 @@ function compat_mt.__index(_, key)
...
+        if option.current == 'old' then
+            return false
+        end
+        return option.default == 'new'
+    end
+
+    -- Whether the effective value of the option is `old`.
+    function result.is_old(option)
+        if type(option) ~= 'table' then
+            error('usage: compat.<option_name>:is_old()')
```
Comment (ligurio) [inline src/lua/compat.lua:466]: Nit: we could pass an option name to `is_old` and use option name in a message `error('usage: yaml_pretty_multiline:is_old()')`. I suppose it is more user-friendly.

I'm not insist, feel free to ignore.

**Review by ligurio — APPROVED** [review]
LGTM, however, see a minor comment.

File: src/lua/compat.lua (hunk 3 above)
Comment (Lord-KA) [reply src/lua/compat.lua:466]: I really like the idea! Applied.
```diff
-            error('usage: compat.<option_name>:is_old()')
+            error(('usage: compat.%s:is_old()'):format(key))
```

**Comment by igormunkin** [comment]
Also backported to 2.11 in scope of 380956f.

File: src/lua/compat.lua (hunk 3 above)
Comment (igormunkin) [reply src/lua/compat.lua]: \*Sigh\*

This spot is fixed, but another one in `is_new` is not. Glad, this is not critical thing in this PR.

@Lord-KA, please next time **resolve** all the discussions with their owners and **do not assign** me, until all of them are resolved.

@ligurio, I guess, it's worth mentioning all the spots either via commenting the particular lines or by mentioning everything in the one comment.
