### PR TITLE
net_box: fix a crash when a trigger deletes itself

### LINKED ISSUE #10622: net.box: can't drop `on_connect` trigger inside its handler
## Description

Net.box connection abstraction provides a few triggers. One of them `on_connect` occurs when the connection is established. It seems reasonable to register the trigger processing the first successful connection attempt and then dropping it inside of the trigger handler. Though doing it in a straightforward way causes an unexpected SEGFAULT.

## Hardware
- __OS__: MacOS Sonoma 14.6.1
- __Architecture__: arm
- __Version__:  3.3.0-entrypoint-111-gc61774387

## Reproducing
In order to reproduce the bug use the simple two-instance cluster configuration:

```lua
iproto:
  listen:
    - uri: 'unix/:./{{ instance_name }}.iproto'

groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            database:
              mode: rw
          instance-002: {}
```

Startup the cluster and then run the following script on the master replica:
```lua
local f = function(conn) conn:on_connect(nil, f) end
require('net.box').connect('unix/:./instance-002.iproto', { wait_connected = false }):on_connect(f)
```

Error message received:
```
tarantool> Segmentation fault
  code: SEGV_ACCERR
  addr: 0x81b
  context: 0x1500a7c18
  siginfo: 0x1500a7bb0
Current time: 1727360569
Please file a bug at https://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#1  0x1051d9ea8 in crash_collect+200
#2  0x1051d9d5c in crash_signal_cb+76
#3  0x1a0232584 in _sigtramp+56
#4  0x1051aa55c in luaT_trigger_list_run+288
#5  0x1052598b4 in lj_BC_FUNCC+44
#6  0x10525e08c in jit_secure_call+568
#7  0x105267764 in lua_call+296
#8  0x10517b8b8 in netbox_transport_on_state_change+280
#9  0x10517a024 in netbox_transport_process_requests+232
#10 0x105178ce0 in netbox_connection_handler_f+100
#11 0x1052598b4 in lj_BC_FUNCC+44
#12 0x105267ff4 in lua_cpcall+704
#13 0x1051b1fb4 in luaT_cpcall+40
#14 0x1051784f4 in netbox_worker_f+580
#15 0x104eb5270 in fiber_cxx_invoke(int (*)(char*), char*)+32
#16 0x1051e5c04 in fiber_loop+264
#17 0x1055fde20 in coro_startup+8
```

Running the debug build with lldb turned on finishes with the failed assertion:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x29)
    frame #0: 0x00000001002fe4a4 tarantool`luaT_trigger_list_run(L=0x00000001011a3b60) at trigger.c:374:3
   371          struct lbox_trigger *trigger;
   372          rlist_foreach_entry(trigger, trigger_list, base.link) {
   373                  /* Only lbox_trigger is expected to be here. */
-> 374                  assert(trigger->base.run == lbox_trigger_run);
   375                  lua_rawgeti(L, LUA_REGISTRYINDEX, trigger->ref);
   376                  for (int i = 2; i <= top; i++)
   377                          lua_pushvalue(L, i);
 ```

## Expected behaviour
The scenario seems quite common. It seems that everything should work. Though, if it is a misusage of the trigger, likely it's not documented or handled properly.

### PR DESCRIPTION
**Pull request by drewdzzz**
In https://github.com/tarantool/tarantool/commit/6d882740f3e56b62527fb9a606b748a138090014 we rewrote Lua module `internal.trigger` that is used in
`net.box` and possibly some external modules. Old implementation held
all triggers in a Lua table, so deleting a trigger on the fly wasn't a
problem. Now we store all triggers in a list and simply iterate over it
when the triggers are fired, so the trigger list became non-resistent to
modifications on the fly. In order to fix it, let's simply use
`trigger_run` - it is resistant to the list modifications.

Closes #10622

### CODE REVIEW

File: src/lua/trigger.c [hunk 1]
```diff
@@ -369,15 +369,25 @@ luaT_trigger_list_run(struct lua_State *L)
 	struct rlist *trigger_list = luaT_check_trigger_list(L, 1);
 	int top = lua_gettop(L);
 	struct lbox_trigger *trigger;
-	rlist_foreach_entry(trigger, trigger_list, base.link) {
+	/*
+	 * Firstly save all triggers since they can be deleted. Since we push
+	 * them to the stack, do it in reverse order.
+	 */
+	rlist_foreach_entry_reverse(trigger, trigger_list, base.link) {
```
Comment (locker) [inline src/lua/trigger.c:376]: Why not use `trigger_run`, which is safe against trigger deletion?

File: test/box-luatest/gh_10622_net_box_trigger_crash_on_self_delete_test.lua [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+    g.server:start()
+end)
+
+g.after_all(function()
+    g.server:stop()
+end)
+
+-- Reproducer from the issue
+g.test_net_box_trigger_crash_on_self_delete = function()
+    local server2 = server:new({alias = 'master'})
```
Comment (locker) [inline test/box-luatest/gh_10622_net_box_trigger_crash_on_self_delete_test.lua:17]: Why not use `server` here?

File: changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md [hunk 3]
```diff
@@ -0,0 +1,3 @@
+## bugfix/box
+
+* Fixed a crash when `net.box` triggers deleted itself (gh-10146).
```
[the remark this answers is not in the document]
Comment (drewdzzz) [reply changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md:3]: Fixed - I chose the second option.

File: src/lua/trigger.c (hunk 1 above)
Comment (drewdzzz) [reply src/lua/trigger.c]: Well, I don't know why I haven't come up with this idea 😄
Done.

File: test/box-luatest/gh_10622_net_box_trigger_crash_on_self_delete_test.lua (hunk 2 above)
Comment (drewdzzz) [reply test/box-luatest/gh_10622_net_box_trigger_crash_on_self_delete_test.lua]: Fixed, use server here so that it connects to itself.

File: changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (locker) [reply changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md:3]: Please also fix the ticket reference: it should be `gh-10622`.

**Review by locker — APPROVED** [review]

File: changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (drewdzzz) [reply changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md]: Oh, that's what you meant by ticket reference. Thanks, fixed!

File: changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md [hunk 4]
```diff
@@ -0,0 +1,3 @@
+## bugfix/lua/netbox
+
+* Fixed a crash when `net.box` triggers deleted itself (gh-10622).
```
Comment (lenkis) [inline changelogs/unreleased/gh-10622-net-box-trigger-crash-on-self-delete.md:3]:
```suggestion
* Fixed a crash when `net.box` triggers deleted themselves (gh-10622).
```

**Review by lenkis — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 3.2.
