### PR TITLE
relay: track when last WAL row was sent

### LINKED ISSUE #12025: replication: `healthy_count` is outdated / lagging
`replicaset.healthy_count` seems to be updated incorrectly sometimes. Or too late. Here is a test:
```Lua
--
-- Instance 1
--
-- Step 1
--
fiber = require('fiber')
log = require('log')
box.cfg{
    listen = 3313,
    replication = {3313, 3314, 3315},
    replication_synchro_timeout = 1000,
    election_mode = 'candidate',
    replication_synchro_quorum = 2,
    replication_timeout = 1000,
    replication_reconnect_timeout = 1,
}
box.ctl.promote()
box.ctl.wait_rw()
box.schema.user.grant('guest', 'super')
--
-- Step 4
--
box.cfg{replication = {}}




--
-- Instance 2
--
-- Step 2
--
fiber = require('fiber')
log = require('log')
box.cfg{
    listen = 3314,
    replication = {3313, 3314, 3315},
    replication_synchro_timeout = 1000,
    election_mode = 'voter',
    replication_synchro_quorum = 2,
    replication_timeout = 1000,
    replication_reconnect_timeout = 1,
}
--
-- Step 5
--
box.cfg{replication = {3314, 3315}}



--
-- Instance 3
--
-- Step 3
--
fiber = require('fiber')
log = require('log')
box.cfg{
    listen = 3315,
    replication = {3313, 3314, 3315},
    replication_synchro_timeout = 1000,
    election_mode = 'voter',
    election_timeout = 1000,
    replication_synchro_quorum = 2,
    replication_timeout = 1000,
    replication_reconnect_timeout = 1,
}
--
-- Step 6
--
box.cfg{replication = {3314, 3315}}
box.cfg{election_mode = 'candidate'}
box.ctl.promote()
```

On Step 6 the Instance-3 has itself and Instance-2 connected perfectly to each other. And yet this promote will fail with
```
---
- error: 'Not enough peers connected to start elections: 1 out of minimal required
    2'
...
```
which is clearly not true.

At the same time, the problem miraculously goes away if the Instance-1 does 2 transactions after all is bootstrapped, but before it gets disconnected. This example below works ok:
```Lua
--
-- Instance 1
--
-- Step 1
--
fiber = require('fiber')
log = require('log')
box.cfg{
    listen = 3313,
    replication = {3313, 3314, 3315},
    replication_synchro_timeout = 1000,
    election_mode = 'candidate',
    replication_synchro_quorum = 2,
    replication_timeout = 1000,
    replication_reconnect_timeout = 1,
}
box.ctl.promote()
box.ctl.wait_rw()
box.schema.user.grant('guest', 'super')
--
-- Step 4
--
s = box.schema.create_space('test')
-- Wait a bit.
fiber.sleep(1)
_ = s:create_index('pk')
-- Wait a bit.
fiber.sleep(1)
box.cfg{replication = {}}




--
-- Instance 2
--
-- Step 2
--
fiber = require('fiber')
log = require('log')
box.cfg{
    listen = 3314,
    replication = {3313, 3314, 3315},
    replication_synchro_timeout = 1000,
    election_mode = 'voter',
    replication_synchro_quorum = 2,
    replication_timeout = 1000,
    replication_reconnect_timeout = 1,
}
--
-- Step 5
--
box.cfg{replication = {3314, 3315}}



--
-- Instance 3
--
-- Step 3
--
fiber = require('fiber')
log = require('log')
box.cfg{
    listen = 3315,
    replication = {3313, 3314, 3315},
    replication_synchro_timeout = 1000,
    election_mode = 'voter',
    election_timeout = 1000,
    replication_synchro_quorum = 2,
    replication_timeout = 1000,
    replication_reconnect_timeout = 1,
}
--
-- Step 6
--
box.cfg{replication = {3314, 3315}}
box.cfg{election_mode = 'candidate'}
box.ctl.promote()
```

The only difference is that Instance-1 does 2 random transactions, slowly, giving each of them time to get delivered. And only then breaks the replication with the others.

This doesn't look correct.

### PR DESCRIPTION
**Pull request by Gerold103**
relay: track when last WAL row was sent

The relay's intention was to mark the heartbeats with timestamps
as soon as no WAL rows are sent since the last heartbeat. First
heartbeat after a last WAL row always has timestamp 0.

It is done so the heartbeats wouldn't inject too new real time
timestamps into the stream, making the lag on replica jump up and
down.

On subscribe one heartbeat is forced to be sent after processing
the journal entries which piled up since the replica connected
last time. It was added in order for the applier to immediately
transition its state from 'sync' to 'follow' if it is up to date.

This step was needed because the last sent WAL row could have a
super old timestamp (if master is mostly idle). Forcing a
heartbeat after that tells the applier that the master actually
has no more rows to send and the lag is good.

This seems to get broken when Raft messages entered the picture.
Raft messages are rows which are sent using relay_send(), but
they have no WAL timestamp (because they aren't from WAL). And
yet they bump last_row_time, which was used by the heartbeats to
understand if they are sent between WAL rows or not.

The patch fixes it by moving the tracking of WAL rows sending into
a separate member of relay, not affected by "in-memory" messages
such as the ones from Raft.

Closes #12025

NO_DOC=bugfix

### CODE REVIEW

File: src/box/relay.cc [hunk 1]
```diff
@@ -1193,6 +1195,8 @@ relay_send(struct relay *relay, struct xrow_header *packet)
 	struct xrow_stream *stream = &relay->xrow_stream;
 	packet->sync = relay->sync;
 	relay->last_row_time = ev_monotonic_now(loop());
+	if (packet->lsn > 0)
+		relay->last_wal_time = relay->last_row_time;
```
Comment (Serpentian) [inline src/box/relay.cc:1199]: Did I understood correctly, that we don't wanna use the old 'last_row_time` (probably renamed), because then the relay subscribe loop will wakeup too often, when there're no transactions and only raft sends messages? Did you consider renaming `last_row_time` and patching it instead of introducing new variable?

Comment (Gerold103) [reply src/box/relay.cc:1199]: Sorry, I got confused, not sure what you mean. Can you elaborate?

I will try to answer what I understood. The old `last_row_time` gets bumped on every sent row: from WAL, from Raft (they aren't from WAL), by heartbeats. It then is used to display `idle` field in `box.info.replication`. If we use it as a signal when last WAL row was sent, then sometimes heartbeats will be confused into thinking that there was a fresh WAL row recently, and won't have any timestamp set in them.

Renaming this member won't change its logic, so it won't help really.

If you mean only updating `last_row_time` when `packet->lsn > 0`, then I think it would fix this specific bug indeed, but then would introduce another one - the `idle` field in `box.info.replication` would be growing infinitely (when no WAL rows are being sent) (see `lbox_pushrelay()`).

Comment (Serpentian) [reply src/box/relay.cc:1199]: > If you mean only updating last_row_time when packet->lsn > 0

This is what I've meant.

> but then would introduce another one - the idle

Indeed, I missed the fact, that it's used in `idle`. I'm ok with the new var

Comment (mrForza) [inline src/box/relay.cc:1199]: Can you explain please your piece of commit message?

> The relay's intention was to mark the heartbeats with timestamps as soon as no WAL rows are sent since the last heartbeat. First heartbeat after a last WAL row always has timestamp 0.

Did I understand correctly that if **node1** sends a wal row into **node2** and **node2** responds successfully it can be considered like an analogue of heartbeat message (that is the destination node is alive and we don't need to break a connection with it)? And therefore a heartbeat message after a successful wal row doesn't have a timestamp in order to not increase the latency of system by calling `ev_monotonic_now`.

File: src/box/relay.cc [hunk 2]
```diff
@@ -860,9 +862,9 @@ relay_send_heartbeat(struct relay *relay)
 	xrow_encode_relay_heartbeat(&row, &relay->last_sent_ack);
 	/*
 	 * Do not encode timestamp if this heartbeat is sent in between
-	 * data rows so as to not affect replica's upstream lag.
+	 * WAL rows so as to not affect replica's upstream lag.
 	 */
-	if (relay->last_row_time > relay->last_heartbeat_time)
+	if (relay->last_wal_time > relay->last_heartbeat_time)
```
Comment (mrForza) [inline src/box/relay.cc:867]: Did I understand correctly that `last_row_time` timestamp is being updated very often and consequently we could get a situation when some of volatile messages (e.g. Raft) appeared just right after heartbeat? And the relay thought by mistake that "current heartbeat message is between two data rows" and didn't set a timestamp to it (what caused applier not transfer from `sync` to `follow` state)?

And we could avoid this situation only by decreasing the `replication_timeout` which is used in relay by automatic sending of heartbeats? That is heartbeat messages will send more often.

File: src/box/relay.cc (hunk 1 above)
Comment (Gerold103) [reply src/box/relay.cc:1199]: Sure, I can!

Almost right, but not quite. You are right that it can be considered kind of a heartbeat, but from what I know, we still send the heartbeats explicitly anyway, even between WAL rows. The logic is just simpler this way.

If you mean that `ev_monotonic_now()` is expensive to call and we avoid it for this reason, then it is not the reason. The reason is that it would otherwise change how the receiver (applier) sees its lag. Lag is how far is applier's WAL from catching up with the relay's WAL.

Now consider this example:
- **relay** node has WAL rows with timestamps 10, 20, 30.
- And the current UTC time is 100.
- **applier** node receives WAL row with ts 10. It will show lag as 90 (UTC time - last received WAL time). It will look like the **applier** is 90 secs behind the **relay**.
- **applier** nodes receives WAL row with ts 20. Now its lag is 80. It looks like catching up. The lag is decreasing.
- Now suddenly **relay** sends a heartbeat with the current UTC timestamp. **Applier** receives it and shows lag 0. Looks like it caught up completely. But it is wrong! There is still one more WAL row to receive to catch up!
- Now **relay** sends the last WAL row with ts 90. And **applier** shows lag 10.
- Then **relay** sends a heartbeat again. **Applier** will show lag 0 again.

So what **relay** sent: WAL-10, WAL-20, HB-100, WAL-30
And **applier**'s lag was looking like: 90, 80, 0, 10. Strange and wrong. The last must have been decreasing, not jumping down and up again.

The jumping will happen if **relay**'s journal keeps growing, but the in this example **relay** was static, and we still had the jumps. Not right.

For this reason the HB messages between WAL rows simply have no timestamp. So the **applier** can correctly track its catch-up-progress.

Does it help?

File: src/box/relay.cc (hunk 2 above)
Comment (Gerold103) [reply src/box/relay.cc:867]: Not fully so. `last_row_time` isn't updated too often. Only when any row is sent. In tests it happens like literally just a few times. In prod will be more often, but it won't change the logic.

But you are completely correct, that it is a problem that if a Raft message was sent after a heartbeat, then the relay was confused into thinking that _"we are still sending WAL rows and I don't need to attach timestamps to my next heartbeat"_.

Yes, decreasing `replication_timeout` would speed up sending of a next heartbeat. And it will then attach a timestamp. Unless of course some other Raft message comes.

**Comment by Gerold103** [comment]
@mrForza ping
