### PR TITLE
box: check for existence when resolving privileges

### LINKED ISSUE #6199: Granting a role together with a privilege silently fails
```lua
tarantool> box.cfg{}
tarantool> box.schema.user.info('guest')
---
- - - execute
    - role
    - public
  - - session,usage
    - universe
    -
...
tarantool> box.schema.user.grant('guest','read,replication','universe')
tarantool> box.schema.user.info('guest')
---
- - - execute  -- !! no replication role
    - role
    - public
  - - read,session,usage -- !! added read privilege
    - universe
    -
...
tarantool> box.schema.user.grant('guest','replication','universe') -- hm, it is incorrect for roles
---
- error: Unsupported universe privilege 'replication'
...
tarantool> box.schema.user.grant('guest','write,replication') -- and this is incorrect too
---
- error: Role 'write,replication' is not found
...
tarantool> box.schema.user.grant('guest','replication') -- it is correct
tarantool> box.schema.user.info('guest')
---
- - - execute
    - role
    - public
  - - execute  -- !! now the replication role is here
    - role
    - replication
  - - read,session,usage
    - universe
    -
...
```

It seems, we should validate everything first and apply only if everything is okay (otherwise don't apply anything and give an error).

Found in https://github.com/tarantool/tarantool/pull/6181#discussion_r662022722.

### PR DESCRIPTION
**Pull request by CuriousGeorgiy**
When resolving privileges passed to box.schema.user.grant, we do not
check that all of them have been resolved: check that all privileges
have been resolved and throw an error otherwise.

Closes #6199

### CODE REVIEW

File: test/box-luatest/gh_6199_schema_priv_resolve_existence_check_test.lua [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+g.after_all(function()
+    g.cluster:drop()
+end)
+
+g.test_priv_resolve_existence_check = function()
+    g.default:exec(function()
+        local t = require('luatest')
+
+        local msg = 'role cannot be granted together with a privilege'
```
Comment (Korablev77) [inline test/box-luatest/gh_6199_schema_priv_resolve_existence_check_test.lua:30]: I'd add more test cases, at least one for each privilege. Otherwise LGTM

Comment (CuriousGeorgiy) [reply test/box-luatest/gh_6199_schema_priv_resolve_existence_check_test.lua:30]: Fixed: added test cases for each privilege, added a test case for all privileges combined.

**Review by Korablev77 — APPROVED** [review]
LGTM

**Comment by alyapunov** [comment]
Strange thing started to happen after your patch, there was an error before:
```
tarantool> box.schema.user.grant('guest', 'EXE CUTE', 'universe')
---
...
```

**Comment by alyapunov** [comment]
Oh, the code in master it too tolerant too:
```
2021-12-13 19:30:19.406 [21323] main/122/console/0.0.0.0:3313 I> started
tarantool> box.schema.user.grant('guest', 'readwritexecute', 'universe')
---
...
```

File: src/box/lua/schema.lua [hunk 2]
```diff
@@ -2383,46 +2383,62 @@ end
 local function privilege_resolve(privilege)
     local numeric = 0
     if type(privilege) == 'string' then
-        privilege = string.lower(privilege)
-        if string.find(privilege, 'read') then
+        local privilege_cp = privilege:lower():gsub('[, ]', '')
+        if privilege_cp:find('read') then
```
Comment (alyapunov) [inline src/box/lua/schema.lua:2387]: I think we should refactor this code. It should honestly parse the line and find token. It is strange that privilege 'readwritexecute' did work and 'r e a d w r i t e e x e c u t e' will work.

**Review by alyapunov — CHANGES_REQUESTED** [review]

File: src/box/lua/schema.lua (hunk 2 above)
Comment (CuriousGeorgiy) [reply src/box/lua/schema.lua]: Refactored this code: extracted parsing of the privileges string into privilege_parse and now process it through a generic FSA.

**Review by Korablev77 — APPROVED** [review]

**Review by alyapunov — APPROVED** [review]
