### PR TITLE
config: add `fail_if` tag for roles and scripts

### LINKED ISSUE #10987: Allow to specify min supported Tarantool version in application role code
If an application role uses a new Tarantool feature, it's best not to load it on older Tarantool versions because it may result in confusing failures at runtime. Indeed, a role may check the Tarantool version in the `validate()` callback, like this:

```lua
local tarantool = require('tarantool')
local version = require('version')

return {
    validate = function()
        if version.fromstr(tarantool.version) < version.new(3, 4, 1) then
            error('Cannot run on Tarantool < 3.4.1')
        end
    end,
    apply = function() end,
    stop = function() end,
}
```

However, it's not really convenient. Also, it generates a confusing error message:

```
2024-12-25 14:43:39.817 [87390] main utils.c:700 E> LuajitError: Wrong config for role my_role: /tmp/test/my_role.lua:7: Cannot run on Tarantool < 3.4.1
```

It'd be nice if it a role could specify the minimal supported Tarantool version.

Jira: TNTP-1016

### PR DESCRIPTION
**Pull request by grafin**
Closes #10987
Closes TNTP-1016

@TarantoolBot document
Title: `fail_if` tag for roles and scripts.

If the tag `fail_if` is set to an expression string role/script loading will raise an error, if fail_if expression is evaluated to be `true`.

The syntax for `fail_if` tag is the same as in config `conditional.if` section.

Example:
```lua
-- --- #tarantool.metadata.v1
-- fail_if: "tarantool_version < 3.1.0"
-- ...
```

### CODE REVIEW

File: src/box/lua/config/applier/roles.lua [hunk 1]
```diff
@@ -184,6 +190,18 @@ local function preload(config)
...
     update_roles_metadata(role_names)
 
+    -- Check `fail_if` tag for roles and raise an error if the check fails.
+    for _, role_name in ipairs(role_names) do
+        local md = roles_state.metadata[role_name]
+        if md ~= nil and md['fail_if'] ~= nil then
+            local expr = md['fail_if']
+            if expression.eval(expr, conditional_vars) then
+                error(('Roles %q failed the "fail_if" check: %q')
+                    :format(role_name, expr), 0)
```
Comment (Totktonada) [inline src/box/lua/config/applier/roles.lua:200]: Typo: roles -> role.

File: src/box/lua/config/applier/app.lua [hunk 2]
```diff
@@ -1,5 +1,11 @@
 local log = require('internal.config.utils.log')
 local utils_file = require('internal.config.utils.file')
+local expression = require('internal.config.utils.expression')
+
+local conditional_vars = {
```
Comment (Totktonada) [inline src/box/lua/config/applier/app.lua:5]: Nit: I think that the `conditional_vars` name fits good in `cluster_config.lua` (because it is about conditional sections), but it doesn't fit here. Something like `fail_if_vars` would look more appropriate, I think.

The same for `applier/roles.lua`.

File: src/box/lua/config/applier/roles.lua [hunk 3]
```diff
@@ -184,6 +190,18 @@ local function preload(config)
     roles_state.metadata = {}
     update_roles_metadata(role_names)
 
+    -- Check `fail_if` tag for roles and raise an error if the check fails.
+    for _, role_name in ipairs(role_names) do
+        local md = roles_state.metadata[role_name]
+        if md ~= nil and md['fail_if'] ~= nil then
+            local expr = md['fail_if']
+            if expression.eval(expr, conditional_vars) then
```
Comment (Totktonada) [inline src/box/lua/config/applier/roles.lua:198]: Parsing error (or other similar error) doesn't report the role name, but it would be nice to narrow down the source of the problem.

The same for the `applier/app.lua`.

**Review by Totktonada — APPROVED** [review]
Thank you! The code is OK for me.

I see that there are some repeting block of code. If you see how to reduce repetitions without ruining the readability, nice, I'm for that too. If not, OK, let's proceed as is. I don't want to spin around this on review.

**Review by maryiaLichko — APPROVED** [review]

**Review by georgiy-belyanin — APPROVED** [review]

File: src/box/lua/config/applier/roles.lua (hunk 1 above)
Comment (grafin) [reply src/box/lua/config/applier/roles.lua]: Thanks for noticing, fixed.

File: src/box/lua/config/applier/app.lua (hunk 2 above)
Comment (grafin) [reply src/box/lua/config/applier/app.lua]: ok, renamed.

File: src/box/lua/config/applier/roles.lua (hunk 3 above)
Comment (grafin) [reply src/box/lua/config/applier/roles.lua]: Added error handling and tests for such cases.
