### PR TITLE
box: fix memleak on functional index drop

### LINKED ISSUE #10163: On functional index drop it's functional keys are leaked
Found in `3.2.0-entrypoint-108-g13249eb32` (but looks like it is an old bug).

Repro: 

```lua
local fiber = require('fiber')
box.cfg{
    log_level = 'error',
    memtx_memory = 100 * 1024 * 1024
}
local lua_code = [[
function(tuple)
    return {string.rep('a', 512 * 1024)}
end]]
box.schema.func.create('func', {
    body = lua_code, is_deterministic = true, is_sandboxed = true})

local count = 0
while true do
    local test = box.schema.space.create('test')
    test:create_index('pk')
    test:create_index('fk', {
        unique = false, func = 'func', parts = {{1, 'string'}}})

    for i=1,3 do
        test:insert({count})
        count = count + 1
        print(count)
    end
    test:drop()
    fiber.yield()
    collectgarbage()
end
```

Let's run:
```
$ ./build-dev/src/tarantool test.lua
1
2
3
....
97
98
99
2024-06-24 17:58:42.248 [1019274] main test.lua:16 E> OutOfMemory: Failed to allocate 524304 bytes in slab allocator for memtx_tuple
2024-06-24 17:58:42.248 [1019274] main F> fatal error, exiting the event loop
```

### PR DESCRIPTION
**Pull request by nshy**
We just don't free functional index keys on functional index drop now. Let's approach keys deletion as in the case of primary index drop ie let's drop these keys in background.

Closes #10163

### CODE REVIEW

File: src/box/memtx_tree.cc [hunk 1]
```diff
@@ -910,12 +915,16 @@ memtx_tree_index_gc_run(struct memtx_gc_task *task, bool *done)
 	memtx_tree_t<USE_HINT> *tree = &index->tree;
 	memtx_tree_iterator_t<USE_HINT> *itr = &index->gc_iterator;
 
+	const bool is_func = index->gc_is_func;
```
Comment (locker) [inline src/box/memtx_tree.cc:918]: Why do you need this flag? Why not check `index->def` here to see if the index is functional?

Comment (nshy) [reply src/box/memtx_tree.cc:918]: Index definition is already freed at this moment. See `index_delete`.

File: src/box/memtx_tree.cc [hunk 2]
```diff
@@ -951,14 +960,20 @@ memtx_tree_index_destroy(struct index *base)
...
 		 * in the index, which may take a while. Schedule a
 		 * background task in order not to block tx thread.
+		 *
+		 * Functional index. For every tuple we need to
+		 * free all functional keys associated with this tuple.
+		 * Let's do it in background also.
 		 */
 		index->gc_task.vtab = get_memtx_tree_index_gc_vtab<USE_HINT>();
 		index->gc_iterator = memtx_tree_first(&index->tree);
+		index->gc_is_func = base->def->key_def->func_index_func != NULL;
```
[the remark this answers is not in the document]
Comment (nshy) [reply src/box/memtx_tree.cc:976]: Fixed.

<details>
<summary>diff</summary>

```diff
diff --git a/src/box/memtx_tree.cc b/src/box/memtx_tree.cc
index 5283e3df5..82ae88d50 100644
--- a/src/box/memtx_tree.cc
+++ b/src/box/memtx_tree.cc
@@ -214,11 +214,8 @@ struct memtx_tree_index {
 	size_t build_array_size, build_array_alloc_size;
 	struct memtx_gc_task gc_task;
 	memtx_tree_iterator_t<USE_HINT> gc_iterator;
-	/**
-	 * Whether index is functional. Used on garbage collection
-	 * when index definition is already freed.
-	 */
-	bool gc_is_func;
+	/** Whether index is functional. */
+	bool is_func;
 };
 
 /* {{{ Utilities. *************************************************/
@@ -915,7 +912,7 @@ memtx_tree_index_gc_run(struct memtx_gc_task *task, bool *done)
 	memtx_tree_t<USE_HINT> *tree = &index->tree;
 	memtx_tree_iterator_t<USE_HINT> *itr = &index->gc_iterator;
 
-	const bool is_func = index->gc_is_func;
+	const bool is_func = index->is_func;
 	unsigned int loops = 0;
 	while (!memtx_tree_iterator_is_invalid(itr)) {
 		struct memtx_tree_data<USE_HINT> *res =
@@ -960,8 +957,7 @@ memtx_tree_index_destroy(struct index *base)
 	struct memtx_tree_index<USE_HINT> *index =
 		(struct memtx_tree_index<USE_HINT> *)base;
 	struct memtx_engine *memtx = (struct memtx_engine *)base->engine;
-	if (base->def->iid == 0 ||
-	    base->def->key_def->func_index_func != NULL) {
+	if (base->def->iid == 0 || index->is_func) {
 		/*
 		 * Primary index. We need to free all tuples stored
 		 * in the index, which may take a while. Schedule a
@@ -973,7 +969,6 @@ memtx_tree_index_destroy(struct index *base)
 		 */
 		index->gc_task.vtab = get_memtx_tree_index_gc_vtab<USE_HINT>();
 		index->gc_iterator = memtx_tree_first(&index->tree);
-		index->gc_is_func = base->def->key_def->func_index_func != NULL;
 		memtx_engine_schedule_gc(memtx, &index->gc_task);
 	} else {
 		/*
@@ -2295,6 +2290,7 @@ memtx_tree_index_new_tpl(struct memtx_engine *memtx, struct index_def *def,
 	memtx_tree_create(&index->tree, cmp_def, memtx_index_extent_alloc,
 			  memtx_index_extent_free, memtx,
 			  &memtx->index_extent_stats);
+	index->is_func = def->key_def->func_index_func != NULL;
 	return &index->base;
 }
 

```

</details>

**Review by locker — APPROVED** [review]

**Review by lenkis — APPROVED** [review]

**Review by locker — APPROVED** [review]

**Comment by locker** [comment]
I'd mention the `use_hint` in the commit message.

**Comment by locker** [comment]
Cherry-picked to 2.11 and 3.1.
