### PR TITLE
iproto: don't account message twice in case of override fallback

### LINKED ISSUE #9345: incorrect in progress request accounting with iproto override fallback
Found in `3.0.0-alpha3-150-g24d7c8f3b`

Any iproto request with override fallback is forever reported as in progress request.

For this program:

```lua
local net = require('net.box')
box.cfg{listen = 3301,log_level='error'}
local ping = function()
   return false
end
box.iproto.override(box.iproto.type.PING, ping)
local c = net.connect(3301)
print(box.stat.net().REQUESTS_IN_PROGRESS.current)
for i=1,100 do
    c:ping()
end
print(box.stat.net().REQUESTS_IN_PROGRESS.current)
os.exit()
```

the output is:

```
0
100
```

### PR DESCRIPTION
**Pull request by nshy**
We need to call `tx_accept_msg` in `tx_process_override` before we pass message to the override handler. Unfortunately if handler response with `IPROTO_HANDLER_FALLBACK` we call the builtin handler for message that calls `tx_accept_msg` again which is not expected. Some actions of this function are idempotent and some are not.

Let's make the function NOP if it called once again.

Closes #9345

### CODE REVIEW

File: src/box/iproto.cc [hunk 1]
```diff
@@ -1178,6 +1184,7 @@ iproto_enqueue_batch(struct iproto_connection *con, struct ibuf *in)
 		msg->reqstart = reqstart;
 		msg->wpos = con->wpos;
 		msg->len = reqend - reqstart; /* total request length */
+		msg->accepted = false;
```
Comment (locker) [inline src/box/iproto.cc:1187]: Nit: Better set it in `iproto_msg_new`.

**Review by locker — APPROVED** [review]

File: src/box/iproto.cc (hunk 1 above)
Comment (nshy) [reply src/box/iproto.cc:1187]: Ok.

```diff
diff --git a/src/box/iproto.cc b/src/box/iproto.cc
index eb45f1fab..e3ded904d 100644
--- a/src/box/iproto.cc
+++ b/src/box/iproto.cc
@@ -817,6 +817,7 @@ iproto_msg_new(struct iproto_connection *con)
        msg->close_connection = false;
        msg->connection = con;
        msg->stream = NULL;
+       msg->accepted = false;
        rmean_collect(con->iproto_thread->rmean, IPROTO_REQUESTS, 1);
        return msg;
 }
@@ -1184,7 +1185,6 @@ iproto_enqueue_batch(struct iproto_connection *con, struct ibuf>
                msg->reqstart = reqstart;
                msg->wpos = con->wpos;
                msg->len = reqend - reqstart; /* total request length */
-               msg->accepted = false;
                con->input_msg_count[msg->p_ibuf == &con->ibuf[1]]++;

                iproto_msg_prepare(msg, &pos, reqend, &stop_input);
```

**Review by ochaplashkin — APPROVED** [review]

**Review by p7nov — APPROVED** [review]

File: changelogs/unreleased/gh-9345-fix-iproto-override-double-request-account.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
+
+* Fixed incorrect inprogress request accounting in case of iproto override
+  fallback (gh-9345).
```
[the remark this answers is not in the document]
Comment (nshy) [reply changelogs/unreleased/gh-9345-fix-iproto-override-double-request-account.md]: Fixed.

**Comment by locker** [comment]
Cherry-picked to 2.11.
