### PR TITLE
core: fix crashes after altering trigger list while it is run

### LINKED ISSUE #4264: All triggers, visible to a user, crash on non-trivial changes
```Lua
box.cfg{}
s = box.schema.create_space('test')
pk = s:create_index('pk')
t1 = function() print('t1') end
t2 = function() s:on_replace(nil, t1) s:on_replace(nil, t2) print('t2') end

s:on_replace(t1)
s:on_replace(t2)
s:replace{1}
```

This leads to surprising results. It could be a gamble to bet how that code will crash next time. Or will not crash. The only certain thing is that this code corrupts memory. While the example is not artificial. IMO a user should be able in a trigger to decide to drop all the triggers. Results are:
```
tarantool> s:replace{1}
t2
---
- error: attempt to call a nil value
...
```
Or
```
tarantool> s:replace{1}
t2
---
- [1]
...
```
Or
```
tarantool> s:replace{1}
t2
Process 83468 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000100150004 tarantool`tarantool_lua_init(tarantool_bin="?u\x80\x1d\x01", argc=1, argv=0x0000000104019038) at init.c:486:3
   483 			} else {
   484 				lua_pop(L, 1); /* nil */
   485 			}
-> 486 			lua_pop(L, 1); /* chunkname */
   487 		}
   488 		lua_pop(L, 1); /* _LOADED */
   489 	
```
Or anything else. This is because all public triggers are run with function `trigger_run`, which uses `rlist_foreach_safe`, but the latter can't withstand deletion of an element after current.

Possible solution - introduce `struct rlist_safe`, or even do not use rlist for triggers at all. When a one wants to delete a trigger, it should be marked for deletion, but deleted only on a next attempt to run, for example.

### PR DESCRIPTION
**Pull request by sergepetrenko**
This patch fixes a number of issues with trigger_clear() while the
trigger list is being run:
1) clearing the next-to-be-run trigger doesn't prevent it from being run
2) clearing the next-to-be-run trigger causes an infinite loop or a
   crash
3) swapping trigger list head before the last trigger is run causes an
   infinite loop or a crash (see space_swap_triggers() in alter.cc, which
   had worked all this time by miracle: space _space on_replace trigger
   swaps its own head during local recovery, and that had only worked
   because the trigger by luck was the last to run)

This is fixed by adding triggers in a separate run list on trigger_run.
This list may be iterated by `rlist_shift_entry`, which doesn't suffer
from any of the problems mentioned above.

While being bad in a number of ways, old approach supported practically
unlimited number of concurrent trigger_runs for the same trigger list.
The new approach requires the trigger to be in as many run lists as
there are concurrent trigger_runs, which results in quite a big
refactoring.

Add a luatest-based test and a unit test.

Closes #4264

NO_DOC=bugfix

### CODE REVIEW

**Comment by sergepetrenko** [comment]
Checkpatch fails with the following error:
```
Commit 6c2d50ed1b29 ("core: replace trigger initializers with trigger_create() calls")
--------------------------------------------------------------------------------------
ERROR:UNCOMMENTED_DEFINITION: 'vy_set_deferred_delete_trigger' definition without comment
#247: FILE: src/box/vinyl.c:4564:
+vy_set_deferred_delete_trigger(void)

total: 1 errors, 228 lines checked
Commit 6c2d50ed1b29 ("core: replace trigger initializers with trigger_create() calls") has style problems, please review.
```

However there's a comment right next to declaration. I just didn't move it with the definition to avoid extra unnecessary changes:
https://github.com/tarantool/tarantool/pull/7550/commits/6c2d50ed1b297c53408c3749dabc4f24ba04ae16#diff-e2a70067112560854fbbbf0ea7ad98a6199600109cdd075f74f865c03c374d35L2838-R2841

**Comment by locker** [comment]
@sergepetrenko Apart from requesting a review, please also assign the PR to me - otherwise I might miss it.

File: src/box/alter.cc [hunk 1]
```diff
@@ -5868,68 +5868,67 @@ on_replace_dd_func_index(struct trigger *trigger, void *event)
 	return 0;
 }
 
-struct trigger alter_space_on_replace_space = {
-	RLIST_LINK_INITIALIZER, on_replace_dd_space, NULL, NULL
-};
+struct trigger alter_space_on_replace_space;
```
Comment (locker) [inline src/box/alter.cc:5871]: Initializing a struct statically is convenient. Why not add `TRIGGER_INITIALIZER` macro?

File: src/lib/core/fiber.c [hunk 2]
```diff
@@ -1879,6 +1883,7 @@ fiber_init(int (*invoke)(fiber_func f, va_list ap))
 void
 fiber_free(void)
 {
+	trigger_free_in_thread();
 	cord_destroy(&main_cord);
```
Comment (locker) [inline src/lib/core/fiber.c:1887]: `cord_destroy` is also called by `coio_on_stop`. AFAIU `trigger_free_in_thread` should be called there, as well. Would be nice if you could put it inside `cord_destroy`.

File: src/lib/core/trigger.cc [hunk 3]
```diff
@@ -35,6 +35,8 @@
 
 #include <small/region.h>
 
+#include <small/mempool.h>
```
Comment (locker) [inline src/lib/core/trigger.cc:38]: Nit: redundant empty line between the two includes.

File: test/box-luatest/gh_4264_recursive_trigger_test.lua [hunk 4]
```diff
@@ -41,3 +41,24 @@ g.test_recursive_trigger_invocation = function(cg)
     t.assert_equals(order, {11, 21, 31, 32, 22, 12},
                     "Correct recursive trigger invocation")
 end
+
+g.test_trigger_clear_from_trigger = function(cg)
+    local order = cg.server:exec(function()
+        local order = {}
+        local s = box.space.test
+        rawset(_G, 'f2', function()
```
Comment (locker) [inline test/box-luatest/gh_4264_recursive_trigger_test.lua:49]: Why do you need `f2` to be global? AFAIU it could just as well be local and captured in the functions:

```Lua
local f1, f2
f1 = ...
f2 = ...
```

File: test/unit/trigger.c [hunk 5]
```diff
@@ -0,0 +1,202 @@
...
+};
+
+/* How many times each trigger was run. */
+int was_run[TEST_LENGTH];
+/* Function codes for each trigger. */
+int funcs[TEST_LENGTH];
+struct test_trigger triggers[TEST_LENGTH];
+
+RLIST_HEAD(list_a);
+RLIST_HEAD(list_b);
```
Comment (locker) [inline test/unit/trigger.c:26]: Nit: all global variables should be static.

File: test/unit/trigger.c [hunk 6]
```diff
@@ -0,0 +1,202 @@
...
+{
+	if (pos == TEST_LENGTH)
+		return test_trigger_one();
+	int i = had_clear ? TEST_LENGTH : 0;
+	plan(FUNC_COUNT - i);
+	for (i; i < FUNC_COUNT; i++) {
+		funcs[pos] = i;
+		test_trigger(pos + 1, had_clear || func_type_by_no(i) ==
+						   FUNC_TYPE_CLEAR);
+	}
```
Comment (locker) [inline test/unit/trigger.c:174]: I struggle to understand the test. Can you rework it aiming at readability instead of code reuse? Since it's just a test, code duplication is acceptable. What I'd like to see is a set of independent tests, each of which checks a particular use case:
1. Deletion of self from a trigger callback.
2. Deletion of the next/prev trigger.
3. Swap of the trigger list head.
4. ...

File: src/lib/core/trigger.cc [hunk 7]
```diff
@@ -35,6 +35,8 @@
...
+
 static void
 trigger_fiber_run_timeout(ev_loop *loop, ev_timer *watcher, int revents)
```
Comment (locker) [inline src/lib/core/trigger.cc:41]: What about `trigger_fiber_run`? Isn't it vulnerable to the same issues as normal triggers.

I don't like this function. Since it's used only in one place (`on_shutdown_f`), I think we could inline it there, making sure it's safe against trigger deletion.

File: src/lib/core/trigger.cc [hunk 8]
```diff
@@ -54,24 +56,124 @@ trigger_fiber_f(va_list ap)
...
+
+/** Execute the triggers in an order specified by \a list. */
+static inline int
+trigger_run_list(struct rlist *list, void *event)
+{
+	while (!rlist_empty(list)) {
+		struct trigger *trigger = run_list_take_trigger(list);
+		if (trigger->run(trigger, event) != 0) {
+			while (!rlist_empty(list))
+				run_list_take_trigger(list);
```
Comment (locker) [inline src/lib/core/trigger.cc:116]: This loop is used in three places. Would be nice to put it in a helper function (`run_list_clear`?)

**Review by locker — CHANGES_REQUESTED** [review]
The fix looks viable to me. @Gerold103 PTAL if the general idea is okay for you.

File: src/box/alter.cc (hunk 1 above)
Comment (sergepetrenko) [reply src/box/alter.cc:5871]: I haven't thought of that. Fixed. Looks better, indeed.

File: src/lib/core/fiber.c (hunk 2 above)
Comment (sergepetrenko) [reply src/lib/core/fiber.c:1887]: Missed that one, thanks!
I'd love to keep `trigger_init/free_in_thread` in `cord_create` and `cord_destroy`, but `cord_destroy` may be called from `cord_join`, which's in wrong thread. I could make `run_pool` part of `cord` or at least return a pointer to `run_pool` from `trigger_init_in_thread`, and then pass it to `trigger_free_in_thread`. But this doesn't look right to me.

So here we are now. Tell me if you want something different.
<details><summary>diff</summary>

```diff
diff --git a/src/lib/core/coio_task.c b/src/lib/core/coio_task.c
index bae6acc9e..4a2f74a62 100644
--- a/src/lib/core/coio_task.c
+++ b/src/lib/core/coio_task.c
@@ -39,6 +39,7 @@
 #include <sys/socket.h>
 
 #include "fiber.h"
+#include "trigger.h"
 #include <tarantool_ev.h>
 
 /*
@@ -122,6 +123,7 @@ static int
 coio_on_stop(void *data)
 {
        (void) data;
+       trigger_free_in_thread();
        cord_destroy(cord());
        free(cord());
        return 0;

```

</details>

File: src/lib/core/trigger.cc (hunk 3 above)
Comment (sergepetrenko) [reply src/lib/core/trigger.cc:38]: The whole file's like that. Fixed it all:
<details><summary>diff</summary>

```diff
diff --git a/src/lib/core/trigger.cc b/src/lib/core/trigger.cc
index d714cbb6b..9a53c9284 100644
--- a/src/lib/core/trigger.cc
+++ b/src/lib/core/trigger.cc
@@ -30,11 +30,8 @@
  */
 
 #include "trigger.h"
-
 #include "fiber.h"
-
 #include <small/region.h>
-
 #include <small/mempool.h>
 
 static void

```

</details>

File: test/box-luatest/gh_4264_recursive_trigger_test.lua (hunk 4 above)
Comment (sergepetrenko) [reply test/box-luatest/gh_4264_recursive_trigger_test.lua:49]: That's my oversight. I noticed that with `local f1 = function() ... `   `f1` can't be captured by the function and thought it must be global to work.
```
local f1
f1 = function() ...
```
works just fine.
<details><summary>diff</summary>

```diff
diff --git a/test/box-luatest/gh_4264_recursive_trigger_test.lua b/test/box-luatest/gh_4264_recursive_t>
index 4bfb10f81..a61a774a3 100644
--- a/test/box-luatest/gh_4264_recursive_trigger_test.lua
+++ b/test/box-luatest/gh_4264_recursive_trigger_test.lua
@@ -46,16 +46,17 @@ g.test_trigger_clear_from_trigger = function(cg)
     local order = cg.server:exec(function()
         local order = {}
         local s = box.space.test
-        rawset(_G, 'f2', function()
+        local f2 = function()
             table.insert(order, 2)
-        end)
-        rawset(_G, 'f1', function()
+        end
+        local f1
+        f1 = function()
             table.insert(order, 1)
-            s:on_replace(nil, _G.f2)
-            s:on_replace(nil, _G.f1)
-        end)
-        s:on_replace(_G.f2)
-        s:on_replace(_G.f1)
+            s:on_replace(nil, f2)
+            s:on_replace(nil, f1)
+        end
+        s:on_replace(f2)
+        s:on_replace(f1)
         s:replace{2}
         return order
     end)
```

</details>

File: test/unit/trigger.c (hunk 5 above)
Comment (sergepetrenko) [reply test/unit/trigger.c:26]: Fixed.

File: src/lib/core/fiber.c (hunk 2 above)
Comment (locker) [reply src/lib/core/fiber.c:1887]: AFAICS the only place where we call `cord_destroy` from another thread is `cord_join`, but it should be okay to move `cord_destroy` to `cord_thread_func` from there. I'd do it and add an assertion to `cord_destroy` that it's called from the destroyed cord.

File: test/unit/trigger.c (hunk 6 above)
Comment (sergepetrenko) [reply test/unit/trigger.c:174]: I would rather leave this test, because it checks for some unexpected trigger combinations we wouldn't think of ourselves: like:
1. clearing the next/prev trigger and swapping list head
2. swapping list head and having an errored trigger
3. so on

I don't see how these particular cases could fail now, but they may be broken by some future patches.

IOW cases you propose only cover "bad" triggers one by one, while I propose to cover all their combinations.

Now how the test works:
It iterates over all possible combinations of triggers of length 5, runs them all in direct and reverse order and checks whether what should run is run and what shouldn't run isn't run.

Possible triggers to choose from are (for each position):
1. Clear trigger at position i, i=1..5
2. Swap list head
3. Nothing bad
4. Error

I don't really check **each** possible combination, because it would make the test quite time-consuming. For example, if there is one trigger clearing something, I don't add any more clearing triggers (checking all combinations of clear(1..5) for all the positions would require a lot more iterations).
I chose trigger lists of length 5, because 5 is the first length, where there is a trigger for which clearing self or next or prev isn't the same as clearing first or last trigger (which might also be a special case).j

I can try and rewrite it to be more understandable or add some comments.

File: src/lib/core/trigger.cc (hunk 8 above)
Comment (sergepetrenko) [reply src/lib/core/trigger.cc:116]: Sure:
<details><summary>diff</summary>

```diff
diff --git a/src/lib/core/trigger.cc b/src/lib/core/trigger.cc
index 9a53c9284..a70f4b54d 100644
--- a/src/lib/core/trigger.cc
+++ b/src/lib/core/trigger.cc
@@ -102,6 +102,14 @@ run_list_take_trigger(struct rlist *list)
        return trigger;
 }
 
+/** Empty the run list and free all the links allocated for it. */
+static inline void
+run_list_clear(struct rlist *list)
+{
+       while (!rlist_empty(list))
+               run_list_take_trigger(list);
+}
+
 /** Execute the triggers in an order specified by \a list. */
 static inline int
 trigger_run_list(struct rlist *list, void *event)
@@ -109,8 +117,7 @@ trigger_run_list(struct rlist *list, void *event)
        while (!rlist_empty(list)) {
                struct trigger *trigger = run_list_take_trigger(list);
                if (trigger->run(trigger, event) != 0) {
-                       while (!rlist_empty(list))
-                               run_list_take_trigger(list);
+                       run_list_clear(list);
                        return -1;
                }
        }
@@ -138,8 +145,7 @@ trigger_run(struct rlist *list, void *event)
        struct trigger *trigger;
        rlist_foreach_entry(trigger, list, link) {
                if (run_list_put_trigger(&run_list, trigger) != 0) {
-                       while (!rlist_empty(&run_list))
-                               run_list_take_trigger(&run_list);
+                       run_list_clear(list);
                        return -1;
                }
        }
@@ -153,8 +159,7 @@ trigger_run_reverse(struct rlist *list, void *event)
        struct trigger *trigger;
        rlist_foreach_entry_reverse(trigger, list, link) {
                if (run_list_put_trigger(&run_list, trigger) != 0) {
-                       while (!rlist_empty(&run_list))
-                               run_list_take_trigger(&run_list);
+                       run_list_clear(list);
                        return -1;
                }
        }

```

</diff>

File: test/unit/trigger.c (hunk 6 above)
Comment (locker) [reply test/unit/trigger.c:174]: The problem is the test is way too complicated IMO. In fact, its code is more complicated than the code of the patch itself. If we find another bug in the code, it'll take us a substantial amount of time to extend the test. We'll probably just give up and add a simple independent test case alongside. That's why I can't approve of it. However, I won't block it either if @Gerold103 reviews and approves it.

File: src/lib/core/trigger.cc (hunk 7 above)
Comment (sergepetrenko) [reply src/lib/core/trigger.cc]: Yes, it's affected as well.

Fixed. Thanks for noticing!

File: src/lib/core/fiber.c (hunk 2 above)
Comment (sergepetrenko) [reply src/lib/core/fiber.c:1886]: `cord_destroy` clears cord's slab cache, so `cord_join` can't check `fiber->f_ret` and `fiber->diag` for the joined cord's fiber, because the latter is already cleared.
I would still have to split `cord_destroy` in two for the sake of `cord_join`. The first part would perform the thread-specific deinitialization, and the second one would destroy the cord's slab cache. This doesn't look much simpler than calling `trigger_free_in_thread` in all the needed places manually IMO.
I haven't done it yet, asked for your opinion in chat.

**Comment by sergepetrenko** [comment]
@locker, please, take another look. I've addressed all your comments but the one regarding `cord_destroy`.

File: src/lib/core/fiber.c (hunk 2 above)
Comment (locker) [reply src/lib/core/fiber.c:1886]: I don't like that you call `trigger_free_in_thread` here and there directly. First, this introduces a dependency from `trigger.h`. Second, if we want to do some extra destruction work at thread exit, we'll have to patch all those places where you add `trigger_free_in_thread` now. Let's add a wrapper for this - `cord_exit`.

File: src/box/alter.cc [hunk 9]
```diff
@@ -5868,68 +5868,35 @@ on_replace_dd_func_index(struct trigger *trigger, void *event)
 	return 0;
 }
 
-struct trigger alter_space_on_replace_space = {
-	RLIST_LINK_INITIALIZER, on_replace_dd_space, NULL, NULL
-};
+TRIGGER(alter_space_on_replace_space, on_replace_dd_space);
```
Comment (locker) [inline src/box/alter.cc:5872]: Nit: Let's remove empty lines between triggers? This would look better IMO:

```C
TRIGGER(alter_space_on_replace_space, on_replace_dd_space);
TRIGGER(alter_space_on_replace_index, on_replace_dd_index);
TRIGGER(on_replace_truncate, on_replace_dd_truncate);
```

File: src/lib/core/trigger.cc [hunk 10]
```diff
@@ -54,24 +53,129 @@ trigger_fiber_f(va_list ap)
...
+	 *  * the current element might be removed from the list
+	 *    (rlist_foreach_entry_safe helps with that)
+	 *  * the next element might be removed from the list
+	 *    (rlist_foreach_entry_safe fails to handle that, but plain
+	 *    rlist_foreach_entry works just fine)
+	 *  * trigger lists might be swapped (for example see
+	 *    space_swap_triggers() in alter.cc), in which case neither
+	 *    rlist_foreach_entry nor rlist_foreach_entry_safe can help
+	 */
+	struct rlist run_list = RLIST_HEAD_INITIALIZER(run_list);
```
Comment (locker) [inline src/lib/core/trigger.cc:124]: Nit: You could just as well write:

```C
RLIST_HEAD(run_list);
```

File: src/lib/core/trigger.cc [hunk 11]
```diff
@@ -54,24 +53,129 @@ trigger_fiber_f(va_list ap)
...
+/** Empty the run list and free all the links allocated for it. */
+static inline void
+run_list_clear(struct rlist *list)
+{
+	while (!rlist_empty(list))
+		run_list_take_trigger(list);
+}
+
+/** Execute the triggers in an order specified by \a list. */
+static inline int
```
Comment (locker) [inline src/lib/core/trigger.cc:94]: Nit: Please avoid using `inline` in C files. The compiler will probably ignore it anyway. If you really need a function to be inlined (obviously, not in this case) you should use `ALWAYS_INLINE`.

File: src/main.cc [hunk 12]
```diff
@@ -135,12 +135,81 @@ sig_checkpoint(ev_loop * /* loop */, struct ev_signal * /* w */,
...
+{
+	(void)loop;
+	(void)revents;
+	bool *expired = (bool *)watcher->data;
+	assert(expired != NULL);
+	*expired = true;
+}
+
+static int
+trigger_fiber_f(va_list ap)
```
Comment (locker) [inline src/main.cc:149]: All these helper functions should be prefixed `on_shutdown_` so that it's clear what they are related to.

Anyway, this isn't what I meant by "inlining `trigger_fiber_run` in `on_shutdown_f`". I meant that we need to rework `on_shutdown_f` so that it runs user callbacks in fibers using only public trigger API (`trigger_run`), without accessing trigger internals. I think we can do this by adding a wrapper function around a user callback that would call the user callback in a fiber. We would put the wrapper functions in the trigger list instead of user callbacks. Can we teach `lbox_trigger_reset` to do this? If you can't do this, better leave `fiber_trigger_run` as is.

Also, this had better be done before the main patch, which fixes `trigger_run` issues.

**Review by locker — CHANGES_REQUESTED** [review]

**Review by Gerold103 — COMMENTED** [review]
Seems extremely complicated tbh. Did you consider just making the triggers reference counted? We don't even need to allocate them all on heap/mempool. Internal triggers like `txn.fiber_on_yield` we can keep in-place. If a `struct trigger` can't be freed, you don't need to protect it from being deleted from rlist. Just ref `next` trigger in the run loop while running this loop. And if a trigger is "deleted" by its owner, you unref it + set its callback to nop - don't even need to remove it from all currently running places then like you now struggle in `trigger_clear()`. This way in `trigger_run()` the `next` trigger is always valid. And if it is cleared by its owner, its calling will be simply nop.

What do you think of that?

File: src/main.cc (hunk 12 above)
Comment (sergepetrenko) [reply src/main.cc]: >  I meant that we need to rework on_shutdown_f so that it runs user callbacks in fibers using only public trigger API (trigger_run), without accessing trigger internals.

Oh, now I see. Misunderstood that at first.
Anyway, I tried your approach and it doesn't work out too well.
As discussed verbally, I left `trigger_fiber_run` where it was and fixed the issue there.
Also found and fixed typos in `trigger_run` and `trigger_run_reverse`.

<details><summary>diff</summary>

```diff
diff --git a/src/lib/core/trigger.cc b/src/lib/core/trigger.cc
index deb838db7..23bc26ed6 100644
--- a/src/lib/core/trigger.cc
+++ b/src/lib/core/trigger.cc
@@ -145,7 +145,7 @@ trigger_run(struct rlist *list, void *event)
 	struct trigger *trigger;
 	rlist_foreach_entry(trigger, list, link) {
 		if (run_list_put_trigger(&run_list, trigger) != 0) {
-			run_list_clear(list);
+			run_list_clear(&run_list);
 			return -1;
 		}
 	}
@@ -159,7 +159,7 @@ trigger_run_reverse(struct rlist *list, void *event)
 	struct trigger *trigger;
 	rlist_foreach_entry_reverse(trigger, list, link) {
 		if (run_list_put_trigger(&run_list, trigger) != 0) {
-			run_list_clear(list);
+			run_list_clear(&run_list);
 			return -1;
 		}
 	}
@@ -181,7 +181,7 @@ trigger_clear(struct trigger *trigger)
 int
 trigger_fiber_run(struct rlist *list, void *event, double timeout)
 {
-	struct trigger *trigger, *tmp;
+	struct trigger *trigger;
 	unsigned trigger_count = 0;
 	struct region *region = &fiber()->gc;
 	RegionGuard guard(region);
@@ -198,6 +198,14 @@ trigger_fiber_run(struct rlist *list, void *event, double timeout)
 		return -1;
 	}
 
+	RLIST_HEAD(run_list);
+	rlist_foreach_entry(trigger, list, link) {
+		if (run_list_put_trigger(&run_list, trigger) != 0) {
+			run_list_clear(&run_list);
+			return -1;
+		}
+	}
+
 	bool expired = false;
 	struct ev_timer timer;
 	ev_timer_init(&timer, trigger_fiber_run_timeout, timeout, 0);
@@ -211,7 +219,8 @@ trigger_fiber_run(struct rlist *list, void *event, double timeout)
 	ev_timer_start(loop(), &timer);
 
 	unsigned current_fiber = 0;
-	rlist_foreach_entry_safe(trigger, list, link, tmp) {
+	while (!rlist_empty(&run_list)) {
+		trigger = run_list_take_trigger(&run_list);
 		char name[FIBER_NAME_INLINE];
 		snprintf(name, FIBER_NAME_INLINE,
 			 "trigger_fiber%d", current_fiber);
@@ -222,6 +231,7 @@ trigger_fiber_run(struct rlist *list, void *event, double timeout)
 			current_fiber++;
 		} else {
 			ev_timer_stop(loop(), &timer);
+			run_list_clear(&run_list);
 			return -1;
 		}
 	}

```

</details>

File: src/lib/core/trigger.cc (hunk 11 above)
Comment (sergepetrenko) [reply src/lib/core/trigger.cc]: Sure, but why though? Only because the compiler usually ignores it?

File: src/lib/core/trigger.cc (hunk 10 above)
Comment (sergepetrenko) [reply src/lib/core/trigger.cc]: Indeed. Fixed.

File: src/box/alter.cc (hunk 9 above)
Comment (sergepetrenko) [reply src/box/alter.cc]: Sure.

File: src/lib/core/trigger.cc (hunk 11 above)
Comment (locker) [reply src/lib/core/trigger.cc]: Just a general rule: if something isn't necessary, better not do it.

**Comment by sergepetrenko** [comment]
@Gerold103 
> If a struct trigger can't be freed, you don't need to protect it from being deleted from rlist.

Yes, that's true. And when trying to fix that issue I forgot at first that triggers might be freed or maybe statically allocated and destroyed on exit from their scope.
The fix was really much simpler, I don't remember all the details but it looked like what you propose, I believe.

I don't see how we could enforce the user to always use dynamic trigger allocation.
And when allocating trigger statically, the following will be an issue:

```c
trigger:
    wake up waiter
    do a bunch of other stuff yielding from time to time

waiter:
     struct trigger; //create and add it to some list
     while (!woken_up)
        fiber_yield()
     trigger_clear(); // the trigger is still run and will be destroyed by return; trigger->link dereference can read garbage
     return;   
```

IOW I thought that we can't be sure that the trigger is still allocated after `trigger_clear`. So all the mentions and references to trigger must be destroyed right at the moment of `trigger_clear`.
Did I understand you correctly?

We could go with making trigger allocation the business of trigger submodule. Then we can do whatever, reference count the triggers, defer their delete and so on. I haven't thought of this, TBH.

File: src/lib/core/trigger.cc (hunk 11 above)
Comment (sergepetrenko) [reply src/lib/core/trigger.cc]: Ok, seems legit, thanks.
Done.

**Review by locker — APPROVED** [review]

**Comment by Gerold103** [comment]
> I don't see how we could enforce the user to always use dynamic trigger allocation.

The only users of `struct trigger` are we. So we can just check the usages and fix those which require dynamic allocation. 

> And when allocating trigger statically, the following will be an issue:

Are there many places like that? I think our triggers often do not yield and we even rely on that. For example, `on_commit` and `on_rollback` triggers can't yield - they run in the scheduler fiber. Exceptions which I can think of right away are those which are added by users via Lua (all of them are already dynamically allocated anyway via single point - `lbox_trigger_reset()`). And in C we don't have public API for triggers at all (when we will, they will be opaque anyway for sure, and hence dynamically allocated too).

For internal trigger runs we could add assertions or panics in `trigger_run` that each its trigger didn't yield, just for sanity checks. And specifically for public triggers we could add `trigger_run_public` or something which allows yields. Or such protected `trigger_run` could itself add a trigger `fiber->on_yield` in which it would panic.

Or keep single `trigger_run` but `TRASH` trigger objects which are destroyed. So it likely crashes in places which we missed.

> We could go with making trigger allocation the business of trigger submodule. Then we can do whatever, reference count the triggers, defer their delete and so on. I haven't thought of this, TBH. The downside is that it will require always allocating triggers dynamically.

Encapsulating them sounds cool indeed. I thought of it, but I only don't like that it will slow down hot places like `struct txn` which has 2 triggers. One of them is set always (`fiber_on_stop`) and another is set for all memtx txns (except when mvcc is turned on) (`fiber_on_yield`). Maybe not a problem if we allocate those once and keep them in `struct txn` cached. The `txn` objects are already pooled.

I would though firstly locate all the places which can potentially yield. Maybe there are very few. And then decide what to do.

**Comment by sergepetrenko** [comment]
@Gerold103
>  I think our triggers often do not yield and we even rely on that.

Yan stumbled upon a yielding trigger in his patch about retrying join.
`applier_on_state_f` yields as soon as the desired or error state is hit. And there quite a lot of things that can happen while it sleeps. Besides, on_state trigger is allocated statically as a local variable.

Another example is on_shutdown triggers. They definitely can yield and they are even exposed to public. Both in C API and in Lua.

> I would though firstly locate all the places which can potentially yield. Maybe there are very few. And then decide what to do.

In order to see whether there are many yielding triggers I tried the following patch:
<details><summary>diff</summary>

```diff
diff --git a/src/lib/core/trigger.cc b/src/lib/core/trigger.cc
index f27fa53ca..bddd5e822 100644
--- a/src/lib/core/trigger.cc
+++ b/src/lib/core/trigger.cc
@@ -51,16 +51,27 @@ trigger_fiber_f(va_list ap)
 {
        struct trigger *trigger = va_arg(ap, struct trigger *);
        void *event = va_arg(ap, void *);
-       return trigger->run(trigger, event);
+       int old = fiber()->csw;
+       int rc = trigger->run(trigger, event);
+       if (fiber()->csw > old) {
+               say_info("Trigger %p yielded", trigger->run);
+       }
+       return rc;
 }
 
 int
 trigger_run(struct rlist *list, void *event)
 {
        struct trigger *trigger, *tmp;
-       rlist_foreach_entry_safe(trigger, list, link, tmp)
-               if (trigger->run(trigger, event) != 0)
+       rlist_foreach_entry_safe(trigger, list, link, tmp) {
+               int old = fiber()->csw;
+               int rc = trigger->run(trigger, event);
+               if (fiber()->csw > old) {
+                       say_info("Trigger %p yielded", trigger->run);
+               }
+               if (rc != 0)
                        return -1;
+       }
        return 0;
 }
 
@@ -68,9 +79,15 @@ int
 trigger_run_reverse(struct rlist *list, void *event)
 {
        struct trigger *trigger, *tmp;
-       rlist_foreach_entry_safe_reverse(trigger, list, link, tmp)
-               if (trigger->run(trigger, event) != 0)
+       rlist_foreach_entry_safe_reverse(trigger, list, link, tmp) {
+               int old = fiber()->csw;
+               int rc = trigger->run(trigger, event);
+               if (fiber()->csw > old) {
+                       say_info("Trigger %p yielded", trigger->run);
+               }
+               if (rc != 0)
                        return -1;
+       }
        return 0;
 }
 ```

</details>

There are a couple of triggers on bootstrap of an empty instance (I suppose something from alter.cc)
```
2022-08-18 11:41:25.792 [66299] main/103/interactive I> initializing an empty data directory
2022-08-18 11:41:25.808 [66299] main/103/interactive I> Trigger 0x55e2f65c5964 yielded
2022-08-18 11:41:25.809 [66299] main/103/interactive I> Trigger 0x55e2f65c723a yielded
< same about Trigger 0x55e2f65c723a a couple of times more >
2022-08-18 11:41:25.812 [66299] main/103/interactive I> assigned id 1 to replica 06b18997-fb6d-4dc5-aa26-b7394ae7e13a
```
Now on a bootstrapped replica:
```
2022-08-18 11:43:12.285 [66319] main/110/applier/ I> Trigger 0x556878182e8f yielded
2022-08-18 11:43:12.285 [66319] main/103/interactive I> bootstrapping replica from 06b18997-fb6d-4dc5-aa26-b7394ae7e13a at 127.0.0.1:3301
2022-08-18 11:43:12.285 [66319] main/110/applier/ I> Trigger 0x5568781906be yielded
```
And on shutdown:
```
tarantool> os.exit() 
2022-08-18 11:45:25.776 [66319] main/121/iproto.shutdown I> Trigger 0x5568782ff7ce yielded
```

These are function pointers, not trigger pointers, so they should correspond to distinct yielding triggers.

TL; DR
TBH I already like the current approach (probably, because I wasted quite some time on it, and it works).
But besides, I don't think we should impose any restrictions on triggers and what they can do. So even if we are choosing between some options, we are left with current approach vs. dynamic allocation.
And if we are choosing dynamic allocation, we have to rewrite all the places with statically allocated triggers. There are a lot of them. Take alter.cc, for example.
And IMO dynamically allocating the triggers themselves wouldn't be any simpler than dynamically allocating run links, like it's done now.

File: src/lib/core/trigger.cc [hunk 13]
```diff
@@ -74,13 +74,26 @@ trigger_run_reverse(struct rlist *list, void *event)
...
 	unsigned trigger_count = 0;
 	struct region *region = &fiber()->gc;
 	RegionGuard guard(region);
+
+	/* Calculating the total number of triggers. */
+	rlist_foreach_entry(trigger, list, link)
+		trigger_count++;
+
+	struct fiber **fibers = (struct fiber **)
+		region_alloc(region, trigger_count * sizeof(struct fiber *));
```
Comment (Gerold103) [inline src/lib/core/trigger.cc:194]: I would advise to use `region_alloc_array()` to keep the memory properly aligned.

File: changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md [hunk 14]
```diff
@@ -0,0 +1,4 @@
+## bugfix/core
```
Comment (Gerold103) [inline changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md:1]: There is another idea, which seem to require no additional allocations and will work both for dynamic and for static triggers. The idea is that `trigger_run()` registers self in the currently running trigger with a struct `run_link` almost like yours. The struct contains a `next_trigger` pointer. When the currently running trigger is deleted, it walks its `run_list` and updates `next_trigger` in each `run_link` to `rlist_next(self)`.
```C
struct run_link {
    struct rlist in_trigger;
    struct rlist* next_trigger;
};

void
trigger_run(struct rlist *list, void *event)
{
    struct run_link link;
    struct rlist* pos = rlist_first(list);
    while (pos != list) {
        struct trigger *t = rlist_entry(pos);
        link.next_trigger = rlist_next(t);
        rlist_append(t->run_links, &link, in_trigger);
        trigger->run(trigger, event);
        // If the trigger was deleted during `run`, then it updated `next_trigger` too.
        rlist_del(&link.in_trigger);
        pos = link.next_trigger;
    }
}
```
This is pseudocode, but I think it is quite close to how the final code could look. Looks much simpler unless I missed anything?

The behaviour difference would be is that if new triggers are added during executing the current ones, then the new ones will be executed too. If we don't want that, then we could introduce
```C
struct trigger_list {
    struct rlist triggers;
    int64_t generation;
};
```
The generation would be updated on each change of `triggers` member. `trigger_run()` would save current generation before starting to execute the triggers and skip all triggers having a newer generation. Also should be very easy to implement (except that all bare `struct rlist` trigger lists would have to be replaced by `struct trigger_list` first).

File: src/lib/core/trigger.cc [hunk 15]
```diff
@@ -54,30 +53,135 @@ trigger_fiber_f(va_list ap)
...
+void
+trigger_clear(struct trigger *trigger)
+{
+	rlist_del_entry(trigger, link);
+	struct run_link *link, *tmp;
+	rlist_foreach_entry_safe(link, &trigger->run_links, in_trigger, tmp) {
+		rlist_del_entry(link, in_run);
+		mempool_free(&run_link_pool, link);
+	}
+	rlist_create(&trigger->run_links);
```
Comment (Gerold103) [inline src/lib/core/trigger.cc:178]: You don't seem to need this `rlist_create()` - an emptied list is supposed to be the same as a newly created one.

**Review by Gerold103 — COMMENTED** [review]
My final comments. If you don't want to try the new idea below, then I can approve the current version right away as well.

File: src/lib/core/trigger.cc (hunk 13 above)
Comment (sergepetrenko) [reply src/lib/core/trigger.cc:194]: Sure. Good catch!
<details><summary>diff</summary>

```diff
diff --git a/src/lib/core/trigger.cc b/src/lib/core/trigger.cc
index 3234fab9a..ea0b27b2a 100644
--- a/src/lib/core/trigger.cc
+++ b/src/lib/core/trigger.cc
@@ -86,11 +86,12 @@ trigger_fiber_run(struct rlist *list, void *event, double timeout)
        rlist_foreach_entry(trigger, list, link)
                trigger_count++;
 
+       size_t sz;
        struct fiber **fibers = (struct fiber **)
-               region_alloc(region, trigger_count * sizeof(struct fiber *));
+               region_alloc_array(region, struct fiber *, trigger_count, &sz);
        if (fibers == NULL) {
-               diag_set(OutOfMemory, trigger_count * sizeof(struct fiber),
-                        "region", "for trigger fiber pointers");
+               diag_set(OutOfMemory, sz, "region",
+                        "for trigger fiber pointers");
                return -1;
        }
 
```

</details>

File: src/lib/core/trigger.cc (hunk 15 above)
Comment (sergepetrenko) [reply src/lib/core/trigger.cc:178]: The list is not emptied: link has two "hanldes" for two different lists: I'm only removing it from `run_list`, but not from `trigger->run_links`. This was an optimisation, I guess. To clear the run_links list at once instead of doing it element by element. Can't remember why I wrote it this way.

This might be simpler:
```diff
diff --git a/src/lib/core/trigger.cc b/src/lib/core/trigger.cc
index 6442dc7a6..8bb86a74c 100644
--- a/src/lib/core/trigger.cc
+++ b/src/lib/core/trigger.cc
@@ -173,9 +173,9 @@ trigger_clear(struct trigger *trigger)
        struct run_link *link, *tmp;
        rlist_foreach_entry_safe(link, &trigger->run_links, in_trigger, tmp) {
                rlist_del_entry(link, in_run);
+               rlist_del_entry(link, in_trigger);
                mempool_free(&run_link_pool, link);
        }
-       rlist_create(&trigger->run_links);
 }
 
 int
```

File: changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md (hunk 14 above)
Comment (sergepetrenko) [reply changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md:1]: If I understood your proposal correctly, you say that it's enough to store one `run_link` per `trigger_run`, and this `run_link` will always store the next-to-be-run trigger.

When a next to be run trigger is deleted, it updates the run_link.next_trigger to its own next trigger. And run_link starts to be "owned" by the next trigger. The trigger should point at the run link, because if it gets deleted before being run, run_link should move to the next trigger once again, and so on.

Each trigger has a list of run_links, because it might be executed recursively.

Yes, this will work without additional link allocations, this is true, and it looks nice, but I doubt it's simpler than the current approach. 

As far as I can see this will work for all cases except one: when trigger list head is swapped. Then we will loop indefinitely, because trigger->next will never be equal to old list head. This problem is present with old triggers as well, I wrote about it in the commit message:
>    3) swapping trigger list head before the last trigger is run causes an
       infinite loop or a crash (see space_swap_triggers() in alter.cc, which
       had worked all this time by miracle: space _space on_replace trigger
       swaps its own head during local recovery, and that had only worked
       because the trigger by luck was the last to run)

Also, I just noticed another problem: when the next-to-be-run trigger is last, and it is removed, run_link.next starts pointing at rlist_head. But it should distinguish the head from the other elements somehow. Otherwise it would try to make rlist_head "own" the run_link. So the run_link has to remember list head, and this won't work with swapping trigger list head once again.

So it isn't that easy, when we go into details, and I'd personally stay with the current approach.

Comment (Gerold103) [reply changelogs/unreleased/gh-4264-trigger-crash-on-nontrivial-change.md:1]: It would work simple though, if you would make `run_link` in this approach store not just `next_trigger` as direct `rlist_next()` but make it `NULL` if the deleted trigger realized that it is the last one. I suppose we can return to this if any benchmarks would in future reveal a slowdown because of the hot path allocations.

**Review by Gerold103 — APPROVED** [review]

**Comment by locker** [comment]
Cherry-picked to 2.10.
